### ISSUE TITLE
Cocos Dashboard 1.0.20 may not add older projects to the project view

### ISSUE THREAD

**Issue by igt-dbrett** [cocos/cocos-engine#10069]
Sorry if this isn't the right place for this but I couldn't find anywhere else to put this.

### Creator version?（版本号）
Cocos Creator Dashboard 1.0.20

### Affected platform?（受影响的平台）
Windows

### How to reproduce?（如何重现）
Try to add a project where the project.json does not specify the version (for me this was a project originally created on 1.9.7)

### JavaScript output or error produced?（报错信息和调用栈）
![CocosDashboardError](https://user-images.githubusercontent.com/25959749/153347135-d972df8f-332f-4353-84d3-dcf183cceb0c.png)

**Comment by jareguo** [comment]
It seems like Dashboard does not support project older than 2.0.0 @chichinohaha

**Comment by chichinohaha** [comment]
Add the Version field to the configuration file as follows
```json
{
.........
  "version": "1.9.7",
}

```

**Comment by igt-dbrett** [comment]
I know I can do that but it'd be great if the dashboard would still load the files without it.

**Comment by jareguo** [comment]
Sorry we can't support such an old project, manpower is very limited.
