### ISSUE TITLE
Looping BGM is stopped after playing some looping sound effects

### ISSUE THREAD

**Issue by phidung2011** [cocos/cocos-engine#10064]
### Creator version?（版本号）
v3.4.0

### Affected platform?（受影响的平台）

Web

### How to reproduce?（如何重现）
My game have one looping BGM and some looping sound effects. BGM will be discarded after playing some looping sfxs.

Step 1: Play BGM with loop
Step 2: Play sfxs with loop sometimes (at least 23 times)
Error: BGM is stopped 

### Demo project?（demo 项目）

Sorry, I don't provide a demo project this time. I will do it if you need. 
But I think the root cause is in stopping a audio source. I used destroy() function to stop looping sfx and remove the audio source component out of its node. But when destroy a audio source, its '_player' property will be destroy and set to 'null'. Therefore, audioManager cannot remove the player (check point 2). It means audioManager's _audioPlayerInfoList will be memory leak and increase more and more. When _audioPlayerInfoList's length equals AudioPlayer.maxAudioChannel (basically it is 24), audioManager will discard one player before playing a new one, so BGM that is on top of _audioPlayerInfoList will be discard.
If I use audio source's stop() function only, this issue wouldn't appear but I have to call destroy() to remove the audio source component out of it's node to avoid memory leak.

 public onDestroy () {
        this.stop(); // (p1)
        this._player?.destroy();
    }

public stop () {
        if (!this._isLoaded) {
            this._operationsBeforeLoading.push('stop');
            return;
        }
        this._player?.stop().then(() => { // (p3)
            audioManager.removePlaying(this._player!); // (p2)
        }).catch((e) => {});
    }

I think you should wait until stopping this._player finish then call audioManager.removePlaying(this._player!). Use sync/await at p3 
 instead of promise could be better, I guess.

**Comment by timlyeee** [comment]
Thanks for your feedback and it's a shame that we didn't treat this issue well. Sorry about that. 

This issue was also reported by internal groups after several months, and it's fixed with this [pull request](https://github.com/cocos/cocos-engine/pull/12865).
