### ISSUE TITLE
自动图集被打包到了多张图片上

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#10171]
场景 demo [SceneRef.zip](https://github.com/cocos-creator/engine/files/8130545/SceneRef.zip)

问题描述：
自动图集勾选了过滤没被使用的资源后，被场景引用的资源和被Prefab引用的资源会被分别打成两张图集，如果不够选的话就会被合并打到一张图集上

从打包的结果上看，应该是按单个资源扫描自动图集的依赖了
![0](https://user-images.githubusercontent.com/17872773/155480029-35a7b3c6-1b9e-4c95-b9dd-f7c3560ab078.jpg)
<img width="316" alt="1" src="https://user-images.githubusercontent.com/17872773/155480097-6157132e-8bef-4763-ae85-afdb56f4c9ff.png">
<img width="791" alt="2" src="https://user-images.githubusercontent.com/17872773/155480147-272667b2-eb5b-4865-b588-d2d08bb3ed47.png">

**Comment by knoxHuang** [comment]
这个是由于 prefab 放在了 resources 下，它所依赖的资源，被打包到 resource 的 bundle 中，才导致出现出现该 issue 的情况
