### ISSUE TITLE
Bug: CC3.4.1 - Spine Blending Mode Additive

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#10231]
Spine-Cocos bug to this ticket:
In CC 3.4.1 

In Spine when using "Blending: **Additive**"
![image](https://user-images.githubusercontent.com/7983358/156362108-fea6387d-610a-41e3-aea9-50845e812b66.png)

and
in Cocos sp.Skeleton component **SHARED_CACHE**
![image](https://user-images.githubusercontent.com/7983358/156362151-186687de-e1c6-4198-a8e3-7d30e1e5d3b6.png)

The blending mode from Spine doesn't work as it should:
![image](https://user-images.githubusercontent.com/7983358/156360792-7d4ae54d-f3d7-4397-9e19-a2fa2aa635a4.png)
If you put it to **REALTIME** it looks good again:
![image](https://user-images.githubusercontent.com/7983358/156360851-1764043b-5a85-413c-87c9-9629d709b8dc.png)

This should of course work with the more performant SHARED_CACHE as well.

Thanks!

**Comment by zhakesi** [comment]
Thanks a lot for your bug report. This bug will be fixed in version 3.4.2
You can try again after the new version released. If 'SHARED_CACHE' mode still can't work with right color, please leave a message
zhakesi@foxmail.com

Thanks!

**Comment by Ronsku** [comment]
Thanks @zhakesi!

**Comment by Ronsku** [comment]
Yes, it seems to work now properly in 3.4.2! Thanks :)
