### ISSUE TITLE
TiledLayer updateCulling bug with 3D camera

### ISSUE THREAD

**Issue by Camouflager** [cocos/cocos-engine#10240]
### Creator version?（版本号）
2.4.8

### Affected platform?（受影响的平台）
All

### How to reproduce?（如何重现）
TiledMap组件和3D相机同时使用时TiledMap不显示

### JavaScript output or error produced?（报错信息和调用栈）
无报错

https://github.com/cocos-creator/engine/blob/22ca6465effd8063cb95e509843b8bef3d880759/cocos2d/tilemap/CCTiledLayer.js#L820-L840

https://github.com/cocos-creator/engine/blob/22ca6465effd8063cb95e509843b8bef3d880759/cocos2d/renderer/scene/camera.js#L443-L450

camera.js里面screenPos是当作vec3在用，而传进去的是vec2。这里screenPos.z应该报undefined，不知道为什么没报（顺便问一下）。

改成vec3以后问题解决。

**Comment by Camouflager** [comment]
前面描述有误，应该是`_vec2_temp.z`的值在camera.js里被out写入了，导致了后面的计算错误。

**Comment by Camouflager** [comment]
进一步的测试发现：3d相机的tiledmap裁剪整体是有问题不能用的？

**Comment by jareguo** [comment]
抱歉 2.x TiledMap 确实是不支持 3D 相机的，包含裁剪功能在内。
由于资源有限，2.x 不会在 3D 方面继续添加维护了，实在抱歉，如果有其它问题欢迎继续提 issue。
建议你升级到 3.x，可以参考 test-case 里面有一个 2d-rendering-in-3d 的测试用例。
