### ISSUE TITLE
Lost all sounds after reject calls

### ISSUE THREAD

**Issue by obraz29** [cocos/cocos-engine#10269]
Hello cocos team, please take time to have a look on this sound issue.

### Creator version?
Cocos v3.4.1, cocos 3.4.0

### Affected platform?（受影响的平台）
iOS

### How to reproduce?（如何重现）

1. Receive a call while game is running & reject the call, the sound resume normally.
2. Minimize the game => receive a call & reject.
3. Resume the game and all sound lost.

**Comment by minggo** [comment]
@obraz29 thanks for feedback. Can i know the device and OS version?

**Comment by obraz29** [comment]
Hello, i'm using iOS 15.3.1, sorry for missing information

**Comment by novain1102** [comment]
> Receive a call while game is running & reject the call, the sound resume normally. 

not reproduce, seems normal.

>Minimize the game => receive a call & reject. 

reject is ok, but receive will lead to mute, working on it.

Enviroment: iPhone 12, iOS 15.3, Creator Version 3.4.2

**Comment by obraz29** [comment]
@mmyduckx i mean if you follow all 3 steps (1=>2->3) the sound will be lost, thank you for your fix, i will merge and recheck my case.

**Comment by novain1102** [comment]
> @mmyduckx i mean if you follow all 3 steps (1=>2->3) the sound will be lost, thank you for your fix, i will merge and recheck my case.

Please try the PR above and feel free talk to me.

**Comment by minggo** [comment]
Close this issue. Please reopen if still have problem.
