### ISSUE TITLE
3.4.1 - CocosCreator Custom build extension not reload when hitting reload button

### ISSUE THREAD

**Issue by cardinalblues7** [cocos/cocos-engine#10265]
### Creator version?（版本号）
3.4.1

### How to reproduce?（如何重现）
Modify the standard custom build template, recompile and reload in the creator build tab,It's just not reflecting changes.The workaround for now is restart the ide, it works fine after that.

**Comment by yanOO1497** [comment]
Hi, build extension will runs in three processes, you should reload the processe where your code is running. Form more details you can see in [Debugging build extension plugins](https://docs.cocos.com/creator/manual/en/editor/publish/custom-build-plugin.html#debugging-build-extension-plugins).
