### ISSUE TITLE
CC 3.4.2 - Replace Splash Screen Issue

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#10353]
If your goal is to have your players into the game as soon as possible you cannot really do it properly.

Everything defaults to 3000s delay before game starts. If you configure like below it will replace the image with a Cocos Creator 64bit encoded image and still run 3000ms.
![image](https://user-images.githubusercontent.com/7983358/158449501-2b5554a1-b4f7-4ea4-988f-32c43a84e89c.png)

The best hacky way I found is to configure it to 1ms and add a 1x1transparent pixel as the logo.

**Comment by minggo** [comment]
@holycanvas is there a way to skip splash screen?

**Comment by jareguo** [comment]
We will allow users to entirely remove the splash screen in 3.7.0. However, it has not yet been determined how it will be implemented, and users may be asked to fill out a personal message in some countrys.

**Comment by hnmli099** [comment]
We will update the  splash screen in version 3.7, and it will be able to skip entirely.
