### ISSUE TITLE
CC 3.4.2 - WebP support on iOS

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#10377]
WebP format has been supported in Safari iOS for a long time, but still even in Cocos Creator 3.4.2 you cannot run WebP images on an iOS device when you build a web-mobile game.
https://caniuse.com/?search=webp
![image](https://user-images.githubusercontent.com/7983358/158643866-93d7f377-de92-4161-9cf9-94b5e748b627.png)

Testing a .webp image on an iOS Safari/Chrome browser works just fine
Random example image: https://www.maketecheasier.com/assets/uploads/2017/09/webp-logo.jpg.webp

When building a game through CC3.4.2 with only WebP exported image it won't show any of the .webp images in the game. Also when building texture atlases with .webp and .png. It will always pick the larger .png images even though it does support .webp.

**Comment by minggo** [comment]
Thank you for feedback. I will ask somebody to take a look.

**Comment by minggo** [comment]
We use the codes to check if support webp as suggested in [this topic](https://stackoverflow.com/questions/5573096/detecting-webp-support):
```javascript
const _tmpCanvas1 = document.createElement('canvas');
let supportWebp = _tmpCanvas1.toDataURL('image/webp').startsWith('data:image/webp')
```

The codes works on chrome. But it does not work on safari. The result of `_tmpCanvas1.toDataURL('image/webp')` is 
```
"data:image/png;base64,..."
```

**Comment by Ronsku** [comment]
Thank you @minggo!
Yes, I've noticed it now, tested it myself. That's very strange on iOS safari!
Very much appreciated that you look into this. I will also investigate and report back if I find anything useful.

**Comment by minggo** [comment]
It's my pleasure. 
Yep, it is strange, macOS safari can not work too. May be should treat safari separately if can not find a general method.

**Comment by pandamicro** [comment]
What @minggo mentioned is how we check the webp support actually, so if it doesn't work then it won't be loaded from the server. @PPpro Is there anything else to do with this issue ? If not we should close it

**Comment by PPpro** [comment]
It seams that Safari 14 starts supportting webp, but `HTMLCanvasElement.toDataURL('image/webp')`  is not supported yet.
we can try detecting the browser version of Safari to force openning the webp support.

**Comment by pandamicro** [comment]
> It seams that Safari 14 starts supportting webp,

Please make sure of it, this issue will remain active

**Comment by Ronsku** [comment]
Thanks guys! 🥳
