### ISSUE TITLE
Spine Animation is flashing on first frame

### ISSUE THREAD

**Issue by obraz29** [cocos/cocos-engine#10383]
Hello cocos team, please have a look on this graphic issue, 

### Creator version?（版本号）
Cocos 3.4.2 (not occurs on 3.4.1)

### Affected platform?（受影响的平台）

Web Browser

### How to reproduce?（如何重现）
1. Unactive the spine node.
2. Acitve the spine node & set animation
3. See the spine is trashing pixel on first frame. (see video)

### JavaScript output or error produced?（报错信息和调用栈）

No Error

### Demo project?（demo 项目）

[TestSpine.zip](https://github.com/cocos/cocos-engine/files/8282475/TestSpine.zip)

https://user-images.githubusercontent.com/52654061/158763280-91975554-f5fd-4069-b376-182b3bea7798.mov

**Comment by obraz29** [comment]
We merged the pull #10349 and the issue is solved, fyi.

**Comment by SantyWang** [comment]
merged into v3.5

**Comment by obraz29** [comment]
Hi @holycanvas, after merging this pull, we sometimes get this error when playing spine, could you have a look
![offset](https://user-images.githubusercontent.com/52654061/159408902-6424a353-5f24-4fe6-a1f8-da0525ff90b7.jpg)
