### ISSUE TITLE
 Are there plans to support Mac M1 for versions below creator 2.4.5? And v2.0.9 works.

### ISSUE THREAD

**Issue by cj841192685** [cocos/cocos-engine#10420]
### Creator version?（版本号）
2.2.0

### Affected platform?（受影响的平台）
Mac M1

### How to reproduce?（如何重现）
无法启动编辑器，或者报Error: This browser does not support webGL. Try using the canvas renderer

**Comment by minggo** [comment]
Sorry, there is not plan. And please use english in future. Thanks.
