### ISSUE TITLE
Light map baking result is not preview-able

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#10438]
### Creator version
v3.4.1

### Affected platform?
Editor

### How to reproduce?
Bake light maps and preview baked result

![image](https://user-images.githubusercontent.com/632460/159399631-e3fd6000-14ad-4a62-b60a-429fd627165f.png)

**Comment by arsen2010** [comment]
![企业微信截图_1648373043883](https://user-images.githubusercontent.com/13517177/160275416-5c3712ae-7d09-4d7a-a674-6deca3f9c1ee.png)

用地形节点 + main light 测试正常，上述 issue 截图是有两张烘焙图，是怎么操作的，需要更具体些的信息

**Comment by zhefengzhang** [comment]
正在找用户了解更多情况，如有必要会找用户要工程。

**Comment by ChannuKonin** [comment]
In one scene, there are 11 sphere lights and 2 directional lights. In another scene, there are just two directional lights. The lighmapping generates too many images and some of them are not previewable. I followed this https://docs.cocos.com/creator/manual/en/concepts/scene/light/lightmap.html?h=lightmap to do lightmapping. All models have secondary UVs and all materials have Use lightmap checked.

**Comment by arsen2010** [comment]
@ChannuKonin  Hello, my local computer can not appear your report bug situation, maybe it relate to generate lightmap times, this panel use browser webGL module and it is broken.

**Comment by chichinohaha** [comment]
@ChannuKonin 
Sorry, could you please provide us with the pictures generated by your baking

**Comment by arsen2010** [comment]
we are dealing with this issue.

**Comment by arsen2010** [comment]
We fix this bug on UI component in editor, and would be release it at v3.5.1
