### ISSUE TITLE
 Investigate websocket power consumption issue on iOS

### ISSUE THREAD

**Issue by timlyeee** [cocos/cocos-engine#10458]
For iOS game, **Energy Impact** showed by XCode profiler is extremely high when websocket is enabled and used.

![image](https://user-images.githubusercontent.com/43355299/159637546-e8bb7347-2778-4c9a-a524-548fce3f727c.png)
![image](https://user-images.githubusercontent.com/43355299/159637553-836ba11b-9253-4a2d-94f0-55b87ff9f88e.png)

This happens on cocos-engine 2.x and 3.x, as we use SocketRocket library to support websocket connection.

This issue shows the investigation of websocket power consumption by using different libraries and the situation by using other game engine.

**Comment by timlyeee** [comment]
# Summury

The investigation will start by comparing different 3rd party libraries, then different game engines. By comparing the average battery impact and network energy usage proportion. 

## SocketRocket vs libwebsocket vs nw_connection_t

> nw_connection_t is the [Network](https://developer.apple.com/documentation/network?language=objc) module which can be used after ios 12.0. As the CFNetwork is about to be deprecated, nw_connection_t is recommended.

### Cocos2.4.x+SocketRocket vs SocketRocket official demo

We compared the energy impact of the SocketRocket library between our game and the official demo. the average energy impact is kind of the same thing except that we've got CPU usage.

cocos2.4.x+SocketRocket
![image](https://user-images.githubusercontent.com/43355299/159861802-11429040-6545-444e-b2a6-81de208a480c.png)
official Demo
![image](https://user-images.githubusercontent.com/43355299/159861838-8e1a5a81-4437-4a23-adda-1f3675acacf6.png)

### libwebsocket vs Network vs SocketRocket
Using cocos2.4.x with different 3rd party libraries

SocketRocket
![image](https://user-images.githubusercontent.com/43355299/159861802-11429040-6545-444e-b2a6-81de208a480c.png)
libwebsocket
![image](https://user-images.githubusercontent.com/43355299/159872334-96d2af83-bc0b-4c04-a114-1d792366c436.png)
Network module(nw_connection_t)
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/43355299/159872074-a9515b87-26a4-4af4-b76d-08edc18027ed.png">

Overhead and network parts are basically the same, as the overhead component utilization shows about 60%.

Thus for cocos2.4.x, it doesn't matter which 3rd party library we use.

## Cocos vs Unity vs Unreal Engine

We have made a simple demo for each game engine with a WebSocket module only. Here shows the investigation result.

Cocos
![image](https://user-images.githubusercontent.com/43355299/159861802-11429040-6545-444e-b2a6-81de208a480c.png)
Unity
![image](https://user-images.githubusercontent.com/43355299/159875248-24552ecf-61bd-42bd-b145-9cfc46e84821.png)
Unreal Engine
![image](https://user-images.githubusercontent.com/43355299/159875304-1894a106-61f9-4e16-afbd-fea29fd920e6.png)
Ignoring the GPU usage of Unreal Engine, the energy impact of WebSocket is basically the same, if we send the message periodically. 

## What is the overhead component usage?

In [Apple's document](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/EnergyandNetworking.html), they describe the overhead battery use as means to retain the extra work, so no matter how big the data is, the overhead energy impact keeps the same.

![image](https://user-images.githubusercontent.com/43355299/159879207-a8eba005-4a29-4a99-830f-b5211ecb65d4.png)

And it's also listed in Apple's [Observe Signs](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/SignsofEnergyLeaks.html)


## Conclusion

Right now we cannot push it further as Apple keeps the overhead battery usage as necessary, it's better to keep watching.

**Comment by minggo** [comment]
Good job @timlyeee
