### ISSUE TITLE
Link error when running virtualizer on ios

### ISSUE THREAD

**Issue by qiuguohua** [cocos/cocos-engine#10465]
![26c9802b966633061ae4c302f449c2f9](https://user-images.githubusercontent.com/5205637/159663720-4d87e784-ac0e-4c33-a868-2aae120f3efb.jpg)

**Comment by timlyeee** [comment]
Did it once, but not merged. dum....https://github.com/cocos/cocos-engine-external/pull/200

**Comment by minggo** [comment]
oops, i forgot to merge it? @timlyeee could you please notice me if i forgot  in future.
