### ISSUE TITLE
v3.5 Change Log

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#10506]
v3.5 Community Test Version, welcome for testing and feedbacks.

Currently the release note haven't been formed in structure, please refer to the following comments.

## Download ver.041815

* [Windows](https://download.cocos.org/CocosCreator/v3.5.0/CocosCreator-v3.5.0-win-041815.zip)
* [Mac OS X](https://download.cocos.org/CocosCreator/v3.5.0/CocosCreator-v3.5.0-mac-041815.zip)

**Comment by shrinktofit** [comment]
- [FEATURE] Animation graphs are now able to add more layers and here comes an new kind of asset: animation mask, to mask off bones on specified layer. https://github.com/cocos/cocos-engine/pull/10179

- [FEATURE] Trigger variables now have attribute called "Reset next frame". https://github.com/cocos/cocos-engine/pull/10179

- [BREAKING CHANGE] Now effectively change to `SkeletalAnimation.prototype.useBakedAnimation` would stop and recreate all animation states. https://github.com/cocos/cocos-engine/pull/10571

**Comment by hana-alice** [comment]
- [NEW FEATURE] Game Frame Pacing Library:Swappy is available on android, both GLES and Vulkan.

**Comment by Zhmz** [comment]
- [NEW FEATURE] Support vertical alignment in richtext component.
https://github.com/cocos/3d-tasks/issues/9984
- [FIX BUG] Update the split algorithm when the size of richtext input content is over 2048.
https://github.com/cocos/3d-tasks/issues/10487
- [FIX BUG] Update the split condition of richtext truncations.
https://github.com/cocos/3d-tasks/issues/10454
- [FIX BUG] Avoid endless loop when float values are sent to UITransform for calculating.
https://github.com/cocos/3d-tasks/issues/11624

**Comment by yiwenxue** [comment]
* [NEW FEATURE] Add a new format feature query interface. 
    https://github.com/cocos/3d-tasks/issues/8203#issue-952522263
* [NEW FEATURE] New method to select mipmap range dynamically during runtime.
    https://github.com/cocos/3d-tasks/issues/7952#issue-932233523

**Comment by novain1102** [comment]
- [FIX BUG] Fix iOS Simulator compile error when using TBB on Apple Silicon device https://github.com/cocos/cocos-engine-external/pull/232
- [OPTIMIZE] Remove Deprecated API `HttpClient::setTimeoutForConnect` `HttpClient::getTimeoutForConnect` `HttpClient::setTimeoutForRead` `HttpClient::getTimeoutForRead` in native network module. Please use `HttpRequest::setTimeout` `HttpRequest::getTimeout` instead. https://github.com/cocos/cocos-engine/pull/10647

**Comment by qiuguohua** [comment]
Redesign platform adaptation layer
https://github.com/cocos/3d-tasks/issues/8883

**Comment by xubing0906** [comment]
[NEW FEATURE] Skybox UI optimization.
https://github.com/cocos/3d-tasks/issues/10482

**Comment by PatriceJiang** [comment]
[OPTIMIZE] Simplify cmake configurations in the native template.
https://github.com/cocos/3d-tasks/issues/11440
[OPTIMIZE] Reimplement websocket with okhttp on Android.

**Comment by timlyeee** [comment]
[NEW FEATURE] Support iPhone compilation in the editor. (Old version: only iPhone-simulator's app can be built. )
relative issue: * https://github.com/cocos/3d-tasks/issues/10309

**Comment by bofeng-song** [comment]
fix translucent problem due to SurfaceView‘s limit 
#10228

refine context2d, reduce call from native to js 
#10211

**Comment by chichinohaha** [comment]
[NEW FEATURE] Add fix alpha transparency artifacts option
Fill transparent pixels with color of neareast solid pixel. These filled pixels would fix the dark halos at transparent borders of textures. Please turn on this option when you use the Alpha transparency channel in textures.
![image](https://user-images.githubusercontent.com/59186205/163236440-5b37a68b-f0ec-4038-823f-a7c94724512e.png)
relative issue: https://github.com/cocos/3d-tasks/issues/2608

**Comment by LinYunMo** [comment]
- [FIX BUG] Opacity dirty bug when parent change (https://github.com/cocos/cocos-engine/pull/10416)
- [FIX BUG] Fix label Blend Factor bug for BYTEDANCE (https://github.com/cocos/cocos-engine/pull/10516)
- [FIX BUG] Clear Particle under UIMeshRenderer when play end(https://github.com/cocos/cocos-engine/pull/10468)
- [FIX BUG] fix ui-mesh-renderer in editor(https://github.com/cocos/cocos-engine/pull/10582)

**Comment by dogeFu** [comment]
1. fix render error when bakeing lightmap with prefab cocos/3d-tasks#10898
2. fix prefab data lost when exiting animation edit mode to prefab edit mode cocos/3d-tasks#11679
3. fix prefab/scene data may be overwrited when open scene/prefab quickly  cocos/3d-tasks#11446
4. fix warning when clicking on different FBX assets cocos/3d-tasks#11588

**Comment by zhakesi** [comment]
* [OPTIMIZE] Spine/Dragon bones socket attachment   ( https://github.com/cocos/cocos-engine/pull/10260  https://github.com/cocos/cocos-docs/pull/2030 )
* [FIX BUG] Fix setting animation not work when creating spine in a hided node (https://github.com/cocos/cocos-engine/pull/10380 )
* [FIX BUG] Fix Spine show a black shadow at first frame ( https://github.com/cocos/cocos-engine/pull/10349 )
* [FIX BUG] Fix changing asset data for spine/dragonbones not work ( https://github.com/cocos/cocos-engine/pull/10370 )
* [OPTIMIZE] Avoid spine/dragonbones copping buffer from native to js ( https://github.com/cocos/cocos-engine/pull/10235 )

**Comment by MSoft1115** [comment]
fix LightFX multi-thread error
change lightmap bake lighting shader method
fix terrain rebuid weight buffer error(https://github.com/cocos/cocos-engine/pull/10470)
fix terrain lightmap warp mode error(https://github.com/cocos/cocos-engine/pull/10470)
add terrain flatten and set height sculpt tool(https://github.com/cocos/cocos-editor/pull/39)

**Comment by PPpro** [comment]
[BUG FIX] fix pointer event after camera.orthoHeight changed (https://github.com/cocos/cocos-engine/pull/10496)

**Comment by yanOO1497** [comment]
【Animation Editor】
- [Feature] Support drag or select animation clips directly to the animation editor for editing;
![image](https://user-images.githubusercontent.com/27424848/160778454-486c08be-5db6-45d8-bdc0-6ac65828e982.png)

- [BUG] Fix a series of optimization points related to keyframe operation in the animation editor;

【Build】
- [Feature] Support to add custom texture compress tools in the Project Settings;
  ![image](https://user-images.githubusercontent.com/27424848/160773732-0203420c-ebf3-49ca-a98e-910c90c55c31.png)
- [Feature] Support the OS Target option in iOS platform；
  ![image](https://user-images.githubusercontent.com/27424848/160774455-07b4bbe2-85b9-4c61-9d6f-3965704337be.png)

- [Feature] Support engine separation feature in OPPO platform;

- [Optimize] Optimize texture compress panel, support to search config in panel;
- [Optimize] Optimizing the JSON grouping strategy for building Bundle merge dependencies.
- [Optimize] Optimization of build output logs, command build parameter completions, parameter checks for some platforms, etc.

- [BUG] Fix build error on windows platform when editor path contains spaces;
- [BUG] Fix after mac platform adjust [Main Bundle is remote] option, will build failed;

**Comment by SantyWang** [comment]
* Fix Particle System instantiation performance drop, https://github.com/cocos/cocos-engine/pull/10323

**Comment by VisualSJ** [comment]
- [Optimize] In lower-version editors, higher-version assets are allowed to be imported after a warning is thrown
- [Bug] Fixed an issue where the editor extension failed to start and could still be queried
- [Feature] Hide some attributes in a 2D project, when not using 3D modules
    - Hide 3D nodes in the "Creator Node" menu
    - Hide the properties of some of the 3D world in Inspector
- [Bug] Fixed issue, Prefab ID changes after FBX and GLTF are renamed
- [Bug] Fixed issue where default meta could not be set to subAsset

**Comment by arsen2010** [comment]
- [Optimize] Optimizeproperty name display on inspector panel, like 'shadowColor' display 'Shadow Color'  [#10241](https://github.com/cocos/cocos-engine/pull/10241)
- [BUG] Fix bug: reset renderer-component would not update model in the scene [#10342](https://github.com/cocos/cocos-engine/pull/10342)
- [Optimize] Optimize edit material using cache data [#10376](https://github.com/cocos/cocos-engine/pull/10376)
- [Optimize] Optimizeedit fbx add legacy options [#10471](https://github.com/cocos/cocos-engine/pull/10471)
- [Feature] Enable edit readonly material [#10518](https://github.com/cocos/cocos-engine/pull/10518)
- [Optimize] Optimize ts templates [#10553](https://github.com/cocos/cocos-engine/pull/10553)
- [BUG] update a property value of object from null [#10575](https://github.com/cocos/cocos-engine/pull/10575)

**Comment by a22aaass** [comment]
> * [新功能] 在富文本组件中支持垂直对齐。
>   https://github.com/cocos/3d-tasks/issues/9984
> * [FIX BUG] 富文本输入内容大小超过2048时更新分割算法。
>   https://github.com/cocos/3d-tasks/issues/10487
> * [FIX BUG] 更新富文本截断的分割条件。
>   https://github.com/cocos/3d-tasks/issues/10454
> * [FIX BUG] 当浮点值被发送到 UITransform 进行计算时，避免死循环。
>   https://github.com/cocos/3d-tasks/issues/11624



> 
can't open this url，please check

**Comment by a22aaass** [comment]
什么事吖

**Comment by PatriceJiang** [comment]
[Breaking Change] Resource folder name for native platforms has been renamed from `assets/` to `data/`.
