### ISSUE TITLE
CC 3.4.2 - Sprite rename bug

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#10505]
Version CC 3.4.2
https://user-images.githubusercontent.com/7983358/160091989-b14156aa-d28d-431a-a98d-7b33299b8731.mp4

- Clean new empty project
- Drop in the spriteFrame
- It is visible
- Rename it
- It is not visible anymore, linking still OK.

Scene, canvas and camera default settings:
![image](https://user-images.githubusercontent.com/7983358/160092207-ec413664-537a-40fe-a72f-e50d5d5acbde.png)
![image](https://user-images.githubusercontent.com/7983358/160092230-d1c02a07-1c8a-45cd-aa7c-83c8ae509e5e.png)
![image](https://user-images.githubusercontent.com/7983358/160092254-c6b6d62e-7a8e-4867-89c1-3cc6b5fe060c.png)

**Comment by LinYunMo** [comment]
Thank you for your feedback, this issue is due to a bug in our asset system, we have fixed it in version 3.6.1, welcome to upgrade and try!

**Comment by LinYunMo** [comment]
RE: https://github.com/cocos/cocos-editor/pull/902
