### ISSUE TITLE
CC 3.4.2 - Animation Editor Bugs

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#10507]
CC Version: 3.4.2

There are tons of weird behavior in Cocos Creator Animation tool for version 3.4.2. Here are a few listed below.

- Cannot drag the timeline-line by dragging at the time-area, have to click on the actual timeline to drag it
https://user-images.githubusercontent.com/7983358/160093165-18c44d4e-7061-4075-82b0-089f24fa0203.mp4

- Buggy behavior on moving keyframes unless you double-click them before dragging
https://user-images.githubusercontent.com/7983358/160093462-da703884-add8-4e0a-9639-7590721e3adf.mp4

- Updating values in animation window, doesn't make them update in the Inspector window
Uploading Cocos Creator - Bugs - db___assets_main.scene 2022-03-25 12-36-20.mp4…

- Animation values doesn't stay as current from animation or based on node's properties when swapping animation clip:
https://user-images.githubusercontent.com/7983358/160105524-eb3f0c76-2fcb-4612-8b28-0222a393a9c1.mp4

**Comment by yanOO1497** [comment]
Thank you for your feedback!  The issue(1,2,4) mentioned below will be fixed in version 3.5.0.

**Comment by Ronsku** [comment]
Amazing, thank you @yanOO1497!
I see that regarding the issue no3: "Updating values in animation window, doesn't make them update in the Inspector window". The video upload was apparently unsuccessful. The video just showed that when you update the animated value in the animation editor it doesn't match or update the property window the same way. They should have 2 way binding since they are representing the same value. You can see this happen in issue no4 video as well.
![image](https://user-images.githubusercontent.com/7983358/161405545-c13545b3-975d-4dfc-998f-9590b218087b.png)

**Comment by yanOO1497** [comment]
> the issue no3: "Updating values in animation window, doesn't make them update in the Inspector window".

@Ronsku  Sorry to reply you later, we also fix this issue in v3.5.0 already.
