### ISSUE TITLE
Put main.cpp in the template

### ISSUE THREAD

**Issue by qiuguohua** [cocos/cocos-engine#10510]
Put main.cpp in the template, because developers can customize platform-related things, such as interface addition and modification, platform initialization, etc.

**Comment by minggo** [comment]
What's current implementation of main.cpp

**Comment by qiuguohua** [comment]
>What's current implementation of main.cpp

Currently it is implemented inside the engine.
The main job of main.cpp is to initialize the platform.

**Comment by minggo** [comment]
Yep, i agree put main.cpp in template if we will not change it.

**Comment by qiuguohua** [comment]
This design mostly retains the original design because
(1) The platform and the application are isolated
(2) Some platforms do not have main (android platform)
(3) Realized by empty platform

**Comment by qiuguohua** [comment]
https://github.com/cocos/cocos-engine/pull/10556
