### ISSUE TITLE
refactor gfx::FramebufferInfo

### ISSUE THREAD

**Issue by star-e** [cocos/cocos-engine#10528]
Currently gfx::FramebufferInfo hashes pointer, which might be invalidated.
We should use stable keys such as uuid、full descriptors to index framebuffer.

related pr & issues:
https://github.com/cocos/cocos-engine/pull/10525
https://github.com/cocos/cocos-engine/pull/10359
https://github.com/cocos/3d-tasks/issues/11549

**Comment by pandamicro** [comment]
Is there anything else to be done? If not please close it

**Comment by hana-alice** [comment]
nothing has been done yet, still planned.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by minggo** [comment]
I suggest to move this issue to other milestone as we start testing v3.6, and will not accept refactored codes.

**Comment by star-e** [comment]
Currently gfx framebuffer is not causing problem. Not going to refactor it.
