### ISSUE TITLE
Shader compilation process optimization

### ISSUE THREAD

**Issue by stanleyljl** [cocos/cocos-engine#10529]
1, A better way is to automatically generate ts and c++ shaders at the same time through BuildEffect, or even fully automate it. For example, if a shader is modified, the editor will **automatically reload & compile**, which can greatly improve development efficiency.
2, Now to generate the C++ version of the shader, you need to right-click the builtin-res project in vs2019 to generate, the first time to generate effect.js, the second time to generate glsl1.js, then glsl3.js, glsl4.js, and the last time is these four cpp file, and then it is all completed.
3,The generated files: glsl1.cpp,glsl3.cpp,glsl4.cpp should end with "// namespace cc", otherwise the Clang-tidy will report an error.

**Comment by SantyWang** [comment]
in 3.6, we will remove built-in effect compiling process and hand it over to editor

**Comment by SantyWang** [comment]
there is some issue, https://github.com/cocos/3d-tasks/issues/11681
