### ISSUE TITLE
V8 static library compiling error

### ISSUE THREAD

**Issue by chenenyu** [cocos/cocos-engine#10521]
你好，我现在有个需求，就是在已有的ios项目中集成cocos，我用cc导出ios工程后，编译出了libcocos2d.a和其他资源，放到了自己的ios项目里(包括external里的一堆.a)，然后在编译自己的工程时，会报v8的错误：
![image](https://user-images.githubusercontent.com/6647088/156149652-05977ea0-6a95-45bc-aa32-cdcf750e87e8.png)

版本：cc 3.4.1

请问可能是什么原因呢？

**Comment by chenenyu** [comment]
@PatriceJiang 没有，目前只是在调用Game类做最简单的尝试

**Comment by minggo** [comment]
@chenenyu please ask it in forum: https://forum.cocos.org/. This is for issues.

**Comment by luqiuan** [comment]
你好，请教下libcocos2d.a是怎样生成的呢

**Comment by gszo** [comment]
我把3.3.2依赖的外部库丢进去出现同样的报错，libv8_monolith.a也已经添加进来了，是怎么解决的呢@chenenyu@PatriceJiang

**Comment by LuoLuoDev** [comment]
我也遇到了这两个报错， 修改了Xcode 里面的这个配置正常了
<img width="755" alt="image" src="https://github.com/cocos/cocos-engine/assets/2748395/6f069226-988d-4b2e-9493-93648328f816">

**Comment by xinnyu** [comment]
如果有升级 xcode 16 出问题的，这个配置也要修改
<img width="527" alt="image" src="https://github.com/user-attachments/assets/eebc4b30-5f88-4777-b36e-0df8c0dbdcd1">

**Comment by xinnyu** [comment]
如果有 xcode16 出问题的，这个配置也要修改
<img width="528" alt="image" src="https://github.com/user-attachments/assets/c5f5640d-5a8d-4548-8b77-9b8dbabfcdfc">

**Comment by wang-yichun** [comment]
> 如果有 xcode16 出问题的，这个配置也要修改 <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/13888298/368829360-c5f5640d-5a8d-4548-8b77-9b8dbabfcdfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzY2NzcsIm5iZiI6MTcyNjczNjM3NywicGF0aCI6Ii8xMzg4ODI5OC8zNjg4MjkzNjAtYzVmNTY0MGQtNWE4ZC00NTQ4LThiNzctOWI4ZGJhYmZjZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA4NTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNThmZTM5NzZiOTg5ZTAxYjg4MWE3MGM4YzNhYmMyYjJmOWY5NDY4Yjk2YmM2NTgxYzY5MjJjOGQxMzA4ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l7ebEy8ayHQug9pDaRYYbORZSBZ3XEM0OvPvDSyDYKM">

你可真是及时雨，
