### ISSUE TITLE
Optimization of context2d text rendering

### ISSUE THREAD

**Issue by qiuguohua** [cocos/cocos-engine#10546]
1. The current canvas implementation is inconsistent across different platforms
2. There are some legacy interfaces that have been kept inside

**Comment by minggo** [comment]
> The current canvas implementation is inconsistent across different platforms

@qiuguohua could you please describe it in more detail?

**Comment by minggo** [comment]
@bofeng-song please take a look of it too.

**Comment by bofeng-song** [comment]
What does Canvas means here? Context2D ?

**Comment by qiuguohua** [comment]
> What does Canvas means here? Context2D ?

Yes, it's context2d

**Comment by qiuguohua** [comment]
The text will be refactored using freetype later, so this optimization can be dropped for now @bofeng-song
