### ISSUE TITLE
[3.4.2] Static_assert failed due to requirement 'sizeof (*to) == 8' error with iOS packaging(Archive)

### ISSUE THREAD

**Issue by speakissilver** [cocos/cocos-engine#10574]
![image](https://user-images.githubusercontent.com/59194019/160586262-7af07f87-92e9-4191-ac7a-ed5bd6ee40b5.png)
请问下这边要怎么修改才能跑通?

**Comment by PatriceJiang** [comment]
@speakissilver Is your App's target architecture 32 bits?  Uncomment the `static_assert` should work.

**Comment by minggo** [comment]
@speakissilver please use english in future. Or we will not handle it, thanks.

**Comment by speakissilver** [comment]
OK
![image](https://user-images.githubusercontent.com/59194019/160969042-3db0f9a7-b1cd-49e2-915c-50a0e88593b9.png)
my mac is 64 bit

![image](https://user-images.githubusercontent.com/59194019/160969073-0bef86cc-6bc4-473f-9f72-78b6cdea0313.png)
target is arm64 and armv7 both 64bit
how can i do?

**Comment by speakissilver** [comment]
> Is your App's target architecture 32 bits? Uncomment the `static_assert` should work.

target is 64 bit.

when i try Uncomment the  `static_assert` ,
cause more errors
![image](https://user-images.githubusercontent.com/59194019/160971457-69ab2194-79ce-49c1-ba29-0f4dbbb025e5.png)

**Comment by PatriceJiang** [comment]
![image](https://user-images.githubusercontent.com/40414978/160984336-44a8e128-b61d-4673-887a-341999af7572.png)
  remove this in `Build Settings`

**Comment by speakissilver** [comment]
![image](https://user-images.githubusercontent.com/59194019/160999515-704d960e-d943-452b-9f9c-2638b4d47bcf.jpg)
I remove armv7 from  Build Setting
But still have errors

**Comment by PatriceJiang** [comment]
What are the target architectures of libcocos2d.a?

**Comment by speakissilver** [comment]
![image](https://user-images.githubusercontent.com/59194019/161009965-6b54fe88-6a97-4505-8622-9cf9a13f038e.png)

when i build xcode project form cocos creator
target haved cocos2d

**Comment by PatriceJiang** [comment]
I mean Build Settings of `cocos2d`

**Comment by speakissilver** [comment]
![image](https://user-images.githubusercontent.com/59194019/161022109-d0b14b54-4c7e-47ba-b25d-2d78fb3b09e5.png)
what's your mean?

**Comment by PatriceJiang** [comment]
Please check the `Build Settings` of target cocos2d, I need to know the target architectures of cocos2d.

**Comment by speakissilver** [comment]
![image](https://user-images.githubusercontent.com/59194019/161031964-8719ac12-e935-4dbd-91c3-7d3a4d35ab46.png)
is here?

**Comment by PatriceJiang** [comment]
Yes,  please remove armv7, it is no longer supported.

**Comment by speakissilver** [comment]
ok 
when i remove armv7
it is work
thank you
