### ISSUE TITLE
Use CC_NEW/CC_DELETE instead

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#10634]
Most codes use new/delete, some use CC_NEW/CC_DELETE. We should unify them, and i think use CC_NEW/CC_DELETE is better, as:
- can use custom memory manage module in future
- can calculate memory usage conveniently

**Comment by stanleyljl** [comment]
agree

**Comment by dumganhar** [comment]
Agree. 
And we should not use malloc & free directly, should use CC_MALLOC & CC_FREE instead.

**Comment by minggo** [comment]
> Agree. And we should not use malloc & free directly, should use CC_MALLOC & CC_FREE instead.

Right. The same reason.

**Comment by shrinktofit** [comment]
What about use `new` and replace the [operator new](https://en.cppreference.com/w/cpp/memory/new/operator_new) if needed?

> can use custom memory manage module in future
> can calculate memory usage conveniently

Example from cppreference:

```cpp
void* operator new([std::size_t](http://en.cppreference.com/w/cpp/types/size_t) sz) // no inline, required by [replacement.functions]/3
{
    [std::printf](http://en.cppreference.com/w/cpp/io/c/fprintf)("global op new called, size = %zu\n", sz);
    if (sz == 0)
        ++sz; // avoid [std::malloc](http://en.cppreference.com/w/cpp/memory/c/malloc)(0) which may return nullptr on success
 
    if (void *ptr = std::malloc(sz))
        return ptr;
 
    throw [std::bad_alloc](http://en.cppreference.com/w/cpp/memory/new/bad_alloc){}; // required by [new.delete.single]/3
}
```

**Comment by minggo** [comment]
> What about use `new` and replace the [operator new](https://en.cppreference.com/w/cpp/memory/new/operator_new) if needed?

It will affect all codes, including 3rd party libraries. And may have potential issues.

**Comment by minggo** [comment]
Current implementation of `CC_NEW` is 
```c++
#define CC_NEW(T)     new T
```

It has problem when using codes like this
```c++
CC_NEW(std::vector<float, 10>);
```
The compiling error is 
```
Too many arguments provided to function-like macro invocation
```
Because `T` includes `,`, which is treat as parameter separator of macro.

So i think should change the macro to
```c++
#define CC_NEW new
```

Why need `CC_NEW` if it is the same as `new`?
The reason is that, when in debug mode, we can change it to
```
#if CC_DEBUG
#define CC_NEW new(__FILE__, __LINE__)
#endif // CC_DEBUG
```
And it can work with custom operator.

```c++
#if CC_DEBUG

#define CC_CLASS_ALLOCATOR(_Class, _Allocator) \
    inline void* operator new(size_t size, size_t align, const char *fileName, int lineNum) { \
    // use fileName and lineNum \
    ... \
    return _allocator(sizeof(_Class)); \
}

#endif // CC_DEBUG

class MyClass {
    public:
        CC_CLASS_ALLOCATOR(MyClass, CC::DefaultAllocator::getInstance(), 0);
};
```

**Comment by minggo** [comment]
After changing the implementation, the usage of `CC_NEW` is
```c++
CC_NEW MyClass(param ...);
```

**Comment by dumganhar** [comment]
How about using lowercase ? The usage of ccnew is more like the original new operator and easier to type than CC_NEW.

**Comment by minggo** [comment]
In our coding style, macro should use capital words.

**Comment by dumganhar** [comment]
Yep, I know our coding style. But the macro for replacing the standard `new` operator is special. O3DE also has the coding style to require macros to be uppercase, but they defined it as `aznew`.

```c++
auto* pMyClass = ccnew MyClass(); // This looks better in my opinion
```

vs

```c++
auto* pMyClass = CC_NEW MyClass(); // Looks strange, harder to type.
```

**Comment by dumganhar** [comment]
Some similar thing in O3DE is the macro `azdynamic_cast` for replace  `dynamic_cast`.

(1)
```c++
#define azdynamic_cast  AZ::RttiCast
#define azrtti_cast     AZ::RttiCast
#define azrtti_istypeof AZ::RttiIsTypeOf
#define azrtti_typeid   AZ::RttiTypeId

// usage
AZStd::intrusive_ptr<RefCountedSubclass> correctCast = azdynamic_cast<RefCountedSubclass *>(basePointer);
 AZStd::intrusive_ptr<RefCountedSubclassB> wrongCast = azdynamic_cast<RefCountedSubclassB *>(basePointer);
```

(2)
If they define them as 
```c++
#define AZDYNAMIC_CAST  AZ::RttiCast
#define AZRTTI_CAST     AZ::RttiCast
#define AZRTTI_ISTYPEOF  AZ::RttiIsTypeOf
#define AZRTTI_TYPEID   AZ::RttiTypeId

// usage
AZStd::intrusive_ptr<RefCountedSubclass> correctCast = AZDYNAMIC_CAST<RefCountedSubclass *>(basePointer);
AZStd::intrusive_ptr<RefCountedSubclassB> wrongCast = AZDYNAMIC_CAST<RefCountedSubclassB *>(basePointer);
```

It will not make developer think easily what to replace `dynamic_cast` if using the uppercase macro AZDYNAMIC_CAST.
`new` -> `aznew` is in the same case.

**Comment by minggo** [comment]
O3DE use `aznew` and `delete` like
```c++
auto *myClass = aznew MyClass;
delete myClass;
```

They are not consistent, one uses macro, and another doesn't. And why `CC_NEW` is strange?

**Comment by dumganhar** [comment]
> They are not consistent, one uses macro, and another doesn't.

This is another topic. Yes, if defining a `azdelete` macro for `delete` to make it a pair of `aznew` is also ok.
They also have `azcreate` & `azdestroy` macros which is a pair.

> And why CC_NEW is strange?

- Need type more
- Type should be right after CC_NEW, and type starts with capital word too.  `CC_NEW MyClass()` is strange, but if the macro are`auto * p = CC_NEW(MyClass, arg1, arg2)`  or ` auto * p = ccnew MyClass(arg1, arg2) ` will make code clearer.
- and as i said in the previous reply, ccnew, ccdynamic_cast will make developer easier to remember since they just like the normal operators (new, dynamic_cast),just add cc prefix.

**Comment by minggo** [comment]
> This is another topic. Yes, if defining a azdelete macro for delete to make it a pair of aznew is also ok.

What i mean is that we should not just copy O3DE, we should think what is better. O3DE just define `azmalloc`, it is a macro, and also has parameters, but it also uses lower case letters. Do you think it is better than `AZ_MALLOC`? 

What you mean is that, if a macro doesn't use like a function, then it is strange?

**Comment by minggo** [comment]
> This is another topic. Yes, if defining a azdelete macro for delete to make it a pair of aznew is also ok.

What i mean is that we should not just copy O3DE, we should think what is better. O3DE just define `azmalloc`, it is a macro, and also has parameters, but it also uses lower case letters. Do you think it is better than `AZ_MALLOC`? 

What you mean is that, if a macro doesn't use like a function, then it is strange?

**Comment by dumganhar** [comment]
> What i mean is that we should not just copy O3DE

I agree this. But we need to know better that why they designed that lowercase macros. There should be some reasons.  The previous reply is what I guess and my understanding of O3DE in my perspective.

> O3DE just define azmalloc, it is a macro, and also has parameters, but it also uses lower case letters. Do you think it is better than AZ_MALLOC?

The `malloc` is also a macro on some systems. It's a macro to wrap function, azmalloc(100) & AZ_MALLOC(100) are both ok for me. 

> What you mean is that, if a macro doesn't use like a function, then it is strange?

But `new` is a c++ builtin operator rather than a function.

**Comment by minggo** [comment]
> What you mean is that, if a macro doesn't use like a function, then it is strange?
But new is a c++ builtin operator rather than a function.

My question is that, why you think CC_NEW is strange?

> O3DE also has the coding style to require macros to be uppercase, but they defined it as aznew

If you look at the codes of O3DE, you can find many macros don't use uppercase. For example, `AZ_Crash` and `az_ctz_u32`. The coding style is not consistent.

**Comment by dumganhar** [comment]
> My question is that, why you think CC_NEW is strange?

I think I replied the reason here: 

> Type should be right after CC_NEW, and type starts with capital word too. CC_NEW MyClass() is strange, but if the macro areauto * p = CC_NEW(MyClass, arg1, arg2) or auto * p = ccnew MyClass(arg1, arg2) will make code clearer.

Anyway, this does not matter a lot. `auto* p = CC_NEW MyClass()` or `auto*  p = ccnew MyClass()` is both ok for me now.

**Comment by minggo** [comment]
After thinking a lot and do some prototype, i think using `ccnew` and `delete` is ok, so the codes looks like
```c++
#define ccnew                      new (std::nothrow)
#define ccnew_placement(placement) new (placement)

auto *myClass = ccnew MyClass(param);
delete myClass;

auto *memory = CC_MALLOC(size);
auto *myClass = ccnew_placement(memory);
myClass->~MyClass();
CC_FREE(memory);
```
