### ISSUE TITLE
Plain JSON files are recognized as spine assets

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#10639]
### Cocos Creator version

3.5.0

### System information

Windows 11

### Issue description

My plain JSON file is recognized as spine asset.

### Relevant error log output

```txt
 [Asset DB] Can not find X:\Dev\Projects\MarionettePrototyping\IK\assets\Source\Demo\Data.atlas
Error: Can not find X:\Dev\Projects\MarionettePrototyping\IK\assets\Source\Demo\Data.atlas
at X:\Dev\Repos\Cocos\cocos-editor\app\modules\engine-extensions\extensions\engine-extends\dist\importer\importers\spine.js:47:26
at suppressedCallback (fs.js:227:5)
at FSReqCallback.oncomplete (fs.js:171:23
```

### Steps to reproduce

Put such a  JSON file in project named `Data.json`:

```json
{
  skeletons: []
}
```

### Minimal reproduction project

[assets.zip](https://github.com/cocos/cocos-engine/files/8401674/assets.zip)

**Comment by VisualSJ** [comment]
Thanks for the feedback.

Our preliminary guess is that the Spine importer misidentified it.
We'll check it to reduce misidentification.

**Comment by zhakesi** [comment]
* https://github.com/cocos/engine-extensions/pull/252

**Comment by zhakesi** [comment]
目前spine json的识别虽然包含了'skeleton'作为关键字，
但同样检查了 json转换的bones数据，上述文件并不会被识别为spine资源
