### ISSUE TITLE
UI module i18n solution research

### ISSUE THREAD

**Issue by SantyWang** [cocos/cocos-engine#10638]
Objectives：
* Research the solution of different UI layouts in multiple env
* Research the solution of text apparence of multiple language
* Research the asset varient workflow for different language
* Optimize UI developer workflow

**Comment by holycanvas** [comment]
related issue: https://github.com/cocos/3d-tasks/issues/8821

**Comment by jareguo** [comment]
中东 layout 的镜像可以放到第二期实现。第一期相关任务：https://github.com/cocos/3d-tasks/issues/9103

**Comment by SantyWang** [comment]
same issue, https://github.com/cocos/cocos-engine/issues/12419
