### ISSUE TITLE
Safari feature WebGL via Metal have issue on iOS 15.4

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#10659]
Feedbacks

- https://forum.cocos.org/t/topic/133522
- https://forum.cocos.org/t/topic/133821
- https://forum.cocos.org/t/topic/133819

Possible walk around:

- Disable shadowmap
- Disable WebGL anti alias

Testable projects:

- https://vshell-1257946517.cos.ap-nanjing.myqcloud.com/web-mobile.zip
- https://mmp-cdn.rayjump.com/qatask/t76700/v6/unity_en_ROK_R2IdHN6sk_ios/unity_en_ROK_R2IdHN6sk_ios.html?preview=true&itavideo=2&mw_test=0

**Comment by pandamicro** [comment]
Not an isolated issue, it's widely produced in many webgl based project, the direct reason is Apple enables "WebGL via Metal" by default on iOS 15.4.

https://github.com/openlayers/openlayers/issues/13486
https://github.com/mapbox/mapbox-gl-js/issues/11609
https://github.com/mrdoob/three.js/issues/23733

The work around is to disable `WEBGL_ANTIALIAS` in project settings for iOS build.
We are still investigating the root reason, but I think there is a great chance we can only wait for Apple to fix it in new version

**Comment by pandamicro** [comment]
Can't be resolved in v3.5, we will continue to monitor the issue in future version

**Comment by avpeery** [comment]
Saw this issue linked to: https://github.com/mapbox/mapbox-gl-js/issues/11609

Received an update from webkit that it is resolved in 15.5 Safari release: https://bugs.webkit.org/show_bug.cgi?id=237918#c10. Cheers!

**Comment by pandamicro** [comment]
@avpeery Thanks for the notification, we will verify and close it

**Comment by 911lqn** [comment]
It is verified that this problem does not occur on safari of IOS 15.5 and 15.6

**Comment by pandamicro** [comment]
Ok, this issue can be closed because Apple have fixed it
