### ISSUE TITLE
Changes in Prefab is not applied to existing prefabs in all of the scenes

### ISSUE THREAD

**Issue by macs054** [cocos/cocos-engine#1068]
I have edited an existing prefab(added new nodes on it) and saved it using the green save button. The prefab itself saved just fine but the changes did not apply to the existing(created) ones in all of the other scenes.

**Comment by jareguo** [comment]
Yes we have not yet implemented the feature. But it should be available after merging https://github.com/cocos-creator/engine/pull/1056

**Comment by macs054** [comment]
I see, thanks for the update.
