### ISSUE TITLE
Feature cropping bug

### ISSUE THREAD

**Issue by stanleyljl** [cocos/cocos-engine#10685]
### Cocos Creator version

3.6.0

### System information

all web platforms

### Issue description

The switch module removal has no effect, and the check box is restored after restarting

![image](https://user-images.githubusercontent.com/26244076/162161982-9fd5cc3f-82bb-4241-a912-951479013d1c.png)

### Steps to reproduce

Steps:
1. Check a module, such as Audio
2. Save
3. After restarting, it is found that there is no check

In addition, uncheck the Geometry Render module, you can also use it.

**Comment by Ronsku** [comment]
This definitely works for me in CC 3.4.2. When I check something off and restart Cocos Creator it stays that way.
The selections are updated in this JSON file
![image](https://user-images.githubusercontent.com/7983358/163254219-3799d8ea-6c5b-45d2-937a-2c6a600f36ee.png)

The issue I'm having is the size of cc.js:
**CC 3.4.2** (everything checked)
![image](https://user-images.githubusercontent.com/7983358/163255126-cd2c3046-0b5e-4721-b382-adde18401874.png)

**CC 3.4.2** (With only Core, Graphics Backend, WebGL, WebGL 2.0, Tween, Marionette, Basic 2D Features, User interface, Tiled Map and Spine Animations selected)
![image](https://user-images.githubusercontent.com/7983358/163255191-69554d17-05e6-43ba-9ca9-07ac75f6a5a7.png)
The cc.js file itself even grows by having so much less selections and no 3D.

Compared to **CC 2.4.6** the difference is massive, over double smaller:
![image](https://user-images.githubusercontent.com/7983358/163255621-4bfe6487-719e-4fa1-88e0-65ceadaa5b43.png)

This I would love to find an answer or fix to!

Link to the other issue: https://github.com/cocos/cocos-engine/issues/10354

**Comment by yanOO1497** [comment]
@stanleyljl This is an issue with the editor UI component, which has been fixed by the person in charge.
