### ISSUE TITLE
Optimize clang-format CI workflow

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#10731]
Now every PR which changes C++ files will trigger a clang-format CI and create a complete new PR then generated a new commit. I think it's too verbose. It results the double increment speed of commit tree and PR number. The count of commits is however important since it impacts the review experiences of commit tree and git performance(you have to admit it even it doesn't suggest now). The PR number is also important because we sometimes need to reference it in code(e.g reference it in unit test). Could we:

1. Append such format commits to original PR or file such a patch-PR to original repository(from which the PR was filed). This repo is public so we can in theory do that without permission problem.

2. Only check. Entrust such format work to people who file the PR. **Just like the eslint CI does** and many repositories do.

Attachments:

1. Our commit tree:

![image](https://user-images.githubusercontent.com/28807867/162869412-e8ece60b-d9d2-4ae6-b3f4-ada2d0559a63.png)

2. Our PR list:

![image](https://user-images.githubusercontent.com/28807867/162869493-df53c3d5-fc39-4527-98af-a98fa283e354.png)

**Comment by minggo** [comment]
> Append such format commits to original PR or file such a patch-PR to original repository(from which the PR was filed). This repo is public so we can in theory do that without permission problem.

If want to append a commit to original PR, then need to have the permission to do it. I don't think we can have the permission.

> Only check. Entrust such format work to people who file the PR. Just like the eslint CI does and many repository do.

It is not easy for developers to set up environment to correct the code format. 
- There is a [documentation](https://github.com/cocos/cocos-engine/blob/develop/native/docs/LINTER_AUTOFIX_GUIDE.md) to set up environment. As different platforms use different tools, for example macOS uses Xcode, Windows uses Visual Studio, and there is not a good way for all tools. So we uses VSCode to do the thing. But C++ developers usually do not use VSCode.
- Different versions of  clang tidy have different behavior of the code format.

But i agree that we should avoid these commits. May be we just do formats before releasing, and just do one time in the version.

**Comment by shrinktofit** [comment]
> As different platforms use different tools, for example macOS uses Xcode, Windows uses Visual Studio, and there is not a good way for all tools. So we uses VSCode to do the thing. But C++ developers usually do not use VSCode.

I'm sorry I only know about Visual Studio(no Code), it integrated clang-format tool and can be configurated as "format-using-clang-format-as-save". Does it help?

> But i agree that we should avoid these commits. May be we just do formats before releasing, and just do one time in the version.

Good idea!

**Comment by minggo** [comment]
And i found these rules bring most code format commit:
```
DerivePointerAlignment:          false
PointerAlignment:                     Right
```
These rules require alignment of the codes, like this
```c++
_debuggerInfo.port         = 6086;
_debuggerInfo.address      = "0.0.0.0";
_debuggerInfo.pauseOnStart = false;
```
It makes the `=` at the same column.  We can remove these rules.

**Comment by dumganhar** [comment]
Should `=` alignment be set false too ?
```
AlignConsecutiveMacros:               true  // set to false?
AlignConsecutiveAssignments:          true // set to false?
AlignConsecutiveDeclarations:         true // set to false?
```

**Comment by minggo** [comment]
Yep, it seems you are right. I am not sure, just want to remove these rules.

**Comment by minggo** [comment]
If changing the coding style, then all codes will be affected. So i will change the rules and format all codes after v3.5 is released and is merged to v3.6.

**Comment by minggo** [comment]
Of course, i can disable the CI workflow first.

**Comment by minggo** [comment]
Adjust format like this
- delete these rules
```
AlignConsecutiveAssignments:          true
AlignConsecutiveDeclarations:          true 
```
- modify pointer alignment rule
change
```
DerivePointerAlignment:               false
PointerAlignment:                     Right
```
to
```
DerivePointerAlignment:               true
```
In previous, pointer alignment has different behavior with different clang-tidy version.

I sent a PR to modify it, and format all codes https://github.com/cocos/cocos-engine/pull/10919

**Comment by minggo** [comment]
I will enable clang-format workflow after merging v3.5.x to v3.6.0, or it will bring many conflicts.

**Comment by minggo** [comment]
Currently, the CI is disabled. And it seems work well without it, so close this issue.
