### ISSUE TITLE
make sensor & orientation feature can be config

### ISSUE THREAD

**Issue by bofeng-song** [cocos/cocos-engine#10737]
make sensor & orientation disabled by default

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/10750

**Comment by bofeng-song** [comment]
make sensor`s feature can be config at running

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/10770

**Comment by minggo** [comment]
Please also sync to creator 2.x.
