### ISSUE TITLE
After upgrading the 2.x project to 3.5.0 the game has changed dramatically

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#10743]
### Cocos Creator version

3.5.0

### System information

apple m1, macOS 12.3.1

### Issue description

2.4.6 ttf font effect
![图片](https://user-images.githubusercontent.com/35944775/163085619-9f049734-9c59-41b3-9cf4-91ed59dd6016.png)

3.5.0 ttf font effect
![图片](https://user-images.githubusercontent.com/35944775/163085631-3c055b05-1014-48cf-967a-e64fcbf691c0.png)

Result: 3.5.0 has wrong font spacing and white border on text

---

2.4.6 Rich Text
![图片](https://user-images.githubusercontent.com/35944775/163085679-bacd4d3a-1d0f-4952-8c54-6584449a7109.png)

3.5.0 Rich Text
![图片](https://user-images.githubusercontent.com/35944775/163085831-19e1955b-b2e2-4849-850f-aaf710242621.png)

Result: 
```
3.5.0 does not display the underscore of <u> correctly for </u>
```

---

2.4.6 fbx
![图片](https://user-images.githubusercontent.com/35944775/163085857-dc092137-8251-45ab-85a3-6ae92a1a71ca.png)
![图片](https://user-images.githubusercontent.com/35944775/163085874-f7bfb75c-7507-4fda-a8d7-1c10b2e4a184.png)

3.5.0 fbx
![图片](https://user-images.githubusercontent.com/35944775/163085896-ac8a6bed-9164-4748-aec5-ecbffee6583d.png)
![图片](https://user-images.githubusercontent.com/35944775/163085905-6376a046-9540-4474-8dbe-1b82179740ed.png)

Result: 3.5.0 fbx rendering and toon material effect is different from 2.4.6 version

---

2.4.6 spine hanging point, keel hanging point
![图片](https://user-images.githubusercontent.com/35944775/163085964-58e8bc46-39e9-474f-8de6-43e7fec107ce.png)
![图片](https://user-images.githubusercontent.com/35944775/163085973-8d2176e1-e2e3-43d1-a0b7-55e4a3dc7970.png)

3.5.0 spine hanging point, keel hanging point
![图片](https://user-images.githubusercontent.com/35944775/163086184-0060a85d-7003-44cd-b974-416e5c957f03.png)
![图片](https://user-images.githubusercontent.com/35944775/163086204-97750654-b985-4ddf-869a-7820053113d3.png)

Result: Upgrading the project from version 2.4.6 to 3.5.0 results in a spine peg location exception

---

### Steps to reproduce

Just open the test project I provided.

The scenarios in which problems arise are.
assets/cases/02_ui/02_label/Label.scene
assets/cases/3d/3d-model.scene
assets/cases/3d/3d-model-toon.scene
assets/cases/dragonbones/DragonBonesAttach.scene
assets/cases/spine/SpineAttach.scene
assets/cases/02_ui/11_richtext/RichText.scene

### Minimal reproduction project

[001.zip](https://github.com/cocos/cocos-engine/files/8477712/001.zip)

**Comment by zhakesi** [comment]
关于spine/dragonbones挂点问题, 因为实现方式的改动，不支持自动兼容。
需参照V3.5文档 ’Spine 挂点‘ 章节的文档手动修改设置方式.(注：v3.5.0的版本与之前3.x的版本设置方式也略有差异)

**Comment by zhefengzhang** [comment]
The richText underline does not appear by switching scenes or re-opening the editor.

**Comment by Zhmz** [comment]
In v3.5
, the width of the outline is calculated into the width of the font, but in v2.4, it is not.
Outline and Shadow components are planned to be resturctured in these coming versions.

**Comment by Zhmz** [comment]
![企业微信截图_16499924975085](https://user-images.githubusercontent.com/32831993/163512673-6ff9740a-e59a-418d-99c4-6fcfa9d9f0e9.png)
![image](https://user-images.githubusercontent.com/32831993/163512651-efe1ea1c-b280-46d4-8df1-1bb9df8f0ec3.png)
the underline in editor is missing, but it is visible in runtime on chrome.

**Comment by SantyWang** [comment]
@Zhmz Need to find out why the underline disappears in the editor

**Comment by Zhmz** [comment]
![企业微信截图_16505286694553](https://user-images.githubusercontent.com/32831993/164417315-989daa4e-ccd4-47f8-a065-f021ccdfb595.png)

ununderlineheight of the segment in richtext had not assigned with any value.
we need to assign it in getSegmentByPool extrally.
