### ISSUE TITLE
Label artifact on web platform

### ISSUE THREAD

**Issue by MrKylinGithub** [cocos/cocos-engine#10756]
Can reproduce on PC and mobile web

![image](https://user-images.githubusercontent.com/5723832/148930217-06f76c5d-8aa5-49ae-8061-d43109d6ff3d.png)

After using LabelOututline, the artifact disapears

**Comment by LinYunMo** [comment]
The contentSize is exactly equal to the label canvas, and it's probably using repeat clamp mode

**Comment by SantyWang** [comment]
Should change label texture's WrapMode to Clamp

**Comment by pandamicro** [comment]
Could be related to pixel alignment, user says he can fix it by keeping the label position rounded

**Comment by Zhmz** [comment]
https://github.com/cocos/3d-tasks/issues/8825
Related issue
It could be related to uv offset, should first find correct baselineratio before handle this issue

**Comment by Zhmz** [comment]
![image](https://user-images.githubusercontent.com/32831993/160040686-45377f52-b0cb-49b6-8fcf-12eb993e373e.png)
Condition to reproduce:
1. ttf font (cachemode none)
2. content size <= width of all characters

![image](https://user-images.githubusercontent.com/32831993/160040892-3af4a4f6-a0fc-4985-b806-b97984c6d2c9.png)

**Comment by Zhmz** [comment]
> Could be related to pixel alignment, user says he can fix it by keeping the label position rounded

![image](https://user-images.githubusercontent.com/32831993/160048602-e5543252-3da7-4c89-8078-a348c76a82d2.png)

User provided an idea to adjust all position of label to integer, it helps to improve clarity, but not helping with the edge artifact
用户提供的思路应该是解决字体不清晰，而不是由虚边的问题，虚边问题我自己手动调pos为整数同样不会消除。

**Comment by Zhmz** [comment]
this issue had been resolved by PR#10754
