### ISSUE TITLE
Vulkan rendering issue with specific auto atlas setting

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#10786]
Environment to reproduce
1. Using auto atlas for packing textures
2. Using texture in UI Sprite
3. Using Vulkan backend
4. Most Android device can reproduce, but some are ok

Auto atlas settings causing issue
![企业微信截图_16500034304267](https://user-images.githubusercontent.com/632460/163563579-08c8d178-72bc-4746-ae1e-d01f3246dbe1.png)

Auto atlas settings without issue
<img width="545" alt="wecom-temp-7daf6b849e1bac19b36509f6ebb6e43a" src="https://user-images.githubusercontent.com/632460/163563757-98454bc4-4acc-4389-93c3-84c4050fb9bd.png">

Rendering result

![企业微信截图_d66961fe-2189-4e60-807e-1b2100ad3e41](https://user-images.githubusercontent.com/632460/163563851-7947dbb4-2ac9-49d3-a60c-7e483e288684.png)

**Comment by yiwenxue** [comment]
The main difference is that the first setting enabled `useCompressTexture` to save GPU memory, but the `preset` was not set (for some unknown reason).

It's definitely an undefined behavior and is impossible to reproduce, in 3.7 and 3.6.2.
