### ISSUE TITLE
The scrollbar is not displayed properly.

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#10785]
### Cocos Creator version

3.4.2，3.5.0

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/127414

### Steps to reproduce

editor:
![image](https://user-images.githubusercontent.com/40415168/163562222-5ac11449-e1ad-442e-bcfa-3b8cc1741e4d.png)

preview:
https://user-images.githubusercontent.com/40415168/163562282-2182bb4e-7544-40eb-a3c3-e56e93e6e1d9.mp4

demo:
[NewProject_23.zip](https://github.com/cocos/cocos-engine/files/8495506/NewProject_23.zip)

**Comment by Zhmz** [comment]
before clicking
![image](https://user-images.githubusercontent.com/32831993/201452851-eed6544f-2473-44a2-8989-3df49ea0ab4f.png)
after clicking
![image](https://user-images.githubusercontent.com/32831993/201452841-f7acd65b-99e5-4a7d-a71d-62982bcc85f7.png)

I have tested two conditions of showing and hiding scroll bar.

**Comment by Zhmz** [comment]
please QA group validate it

**Comment by LinYunMo** [comment]
[NewProject_23_new.zip](https://github.com/cocos/cocos-engine/files/10244616/NewProject_23_new.zip)
