### ISSUE TITLE
[2.4.8] mobx-keystone import error

### ISSUE THREAD

**Issue by az198071123** [cocos/cocos-engine#10790]
### Cocos Creator version

2.4.8

### System information

MacOS 12.3

### Issue description

I try to use `mobx-keystone` from npm
when I just define a `RootStore` class and extends `Model` (from mobx-keystone) and I got error in Editor.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/5800906/163707338-30d5376d-a322-42f4-87ee-44992cc2627d.png">

please help me take a look. 
Thank you!

### Relevant error log output

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/5800906/163706895-dcf2756c-9754-4cde-b521-8c1ce187f2bf.png">

### Steps to reproduce

1. create a empty project with 2.4.8
2. run cmd `npm i mobx-keystone -S`
3. create RootStore class and extends Model (from mobx-keystone)
4. check console output and got error

### Minimal reproduction project

[TestMobx.zip](https://github.com/cocos/cocos-engine/files/8501236/TestMobx.zip)

**Comment by knoxHuang** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/7564028/171128977-61748b44-e3a5-4706-9cd2-397800d79463.png">

The try catch code here is wrong and needs to be adjusted to the following code

<img width="532" alt="image" src="https://user-images.githubusercontent.com/7564028/171129050-f693f14b-6736-47ab-a64b-95ac04a4aa2e.png">
