### ISSUE TITLE
Deprecated API doesn't work as expected

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#10819]
Currently, some deprecated API are just put into a named deprecated.ts(for example, [UI deprecated API](https://github.com/cocos/cocos-engine/blob/develop/cocos/ui/deprecated.ts) ), and keep compatible. But not any warning message is printed if using these deprecated API. So should:
- print warning message if using these deprecated API
- the engine codes should stop using these deprecated API

**Comment by PPpro** [comment]
There is no way for JS to do this, 

for more detailed info, please take a look into this issue: https://github.com/cocos/cocos-engine/issues/10821
