### ISSUE TITLE
Native  getSlot and getAttachment return incorrect data

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#10814]
### Cocos Creator version

3.4.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/134521
The data returned by web and native is different。
web: (getAttachment)
![image](https://user-images.githubusercontent.com/40415168/164205674-e7eac426-43a0-440c-b676-22af81b38f72.png)

native: (getAttachment)
![image](https://user-images.githubusercontent.com/40415168/164205771-c3845264-48b5-4508-92b6-6837352eda2b.png)

### Steps to reproduce

demo :[NativeSpineTest_330.zip](https://github.com/cocos/cocos-engine/files/8520581/NativeSpineTest_330.zip)
Hopefully the data returned will be the same on both platforms, just like the 2.x implementation.
2.x:
![企业微信截图_16504367184428](https://user-images.githubusercontent.com/40415168/164206429-c85c0768-c5fe-4789-a0ec-45757877b193.png)

**Comment by zhakesi** [comment]
fix like this.
* https://github.com/cocos/cocos-engine/commit/9a4915b043616f8df427a010539e59fb32f8a68c

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14421
