### ISSUE TITLE
Add class deprecation function

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#10821]
In x-deprecated there are only deprecation for methods or properties, we need deprecation for classes.

Currently class deprecation can't be removed, because two reasons

1. Using direct name alias exporting: https://github.com/cocos/cocos-engine/blob/v3.5.0/cocos/ui/deprecated.ts
2. Deprecate message in constructor but user may still use static method: https://github.com/cocos/cocos-engine/blob/v3.5.0/cocos/core/geometry/deprecated-3.0.0.ts
    In this scenario, user can use `ray.create` without any problem and have none warning report.

We need a new class deprecation function for covering all needs in class deprecation, and all class deprecations should be using the new way. We need to make sure warning reported for any kind of usage of deprecated classes

- Constructing classes
- Using static methods or properties

**Comment by pandamicro** [comment]
https://github.com/cocos/cocos-engine/issues/10819

**Comment by PPpro** [comment]
JS can't do that, neither by `Proxy` or use `Object.defineXXX` methods.
There is no way to make a proxy to access the top level variable for JS.
Also there is no way to override the constructor of class. Though the `Proxy` provide a way to do that, it's not polyfillable.

And here is what we can do to optimzie the UI deprecated info for developers:  https://github.com/cocos/cocos-engine/pull/11472
(To give more deprecated info when developers are coding)

**Comment by shrinktofit** [comment]
We may achieve this with the help of transpiling:

```ts
import { Meow, Woof as Woof2 } from 'cc';
```

👇

```diff
import { Meow, Woof as Woof2 } from 'cc';
+ // Inject the following statements if somewhat was imported from 'cc'
+ import { checkObsoletes } from 'cc';
+ checkObsoletes(Meow, Woof);
```

but the deficiency is certain forms of import can not be captured:

```ts
import * as cc from 'cc';
cc.Meow; // Could not be detected unless do semantic analyize deeply
cc['Me' + 'ow']; // Not possible to detect
```

----------------------------

Edit: well I got an idea to handle the above case:

```diff
-import * as cc from 'cc';
+import * as _cc from 'cc';
+const cc = new Proxy(_cc, { /* Traffic and hook certain sementics */ }); // This object can be somehow shared by all modules
cc.Meow;
cc['Me' + 'ow'];
```

**Comment by PPpro** [comment]
what if developers code like 

```
import * as ccc from 'cc'
```
