### ISSUE TITLE
API doc i18n optimization

### ISSUE THREAD

**Issue by SantyWang** [cocos/cocos-engine#10851]
```
"cocos/tween/tween.ts": [
    "Tween"
  ],
  "cocos/tween/actions/action.ts": [
    "TAG_INVALID"
  ],
```

**Comment by Zhmz** [comment]
![企业微信截图_16507954116395](https://user-images.githubusercontent.com/32831993/164972249-44948d91-7a02-4e31-a69b-9554ca47c435.png)
the “Tween” is scaned from the tag in "{}", no need to modify

![企业微信截图_16507951716934](https://user-images.githubusercontent.com/32831993/164972304-61592f63-50d2-44c0-95a8-8a19b6d10209.png)
"TAG_INVALID" is scaned exceptionally.
