### ISSUE TITLE
[3.4.2] Importing 2.x to 3.4.2 version using importer, editor crashes

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#10864]
### Cocos Creator version

2.4.6、3.4.2

### System information

windows

### Issue description

The user has a large amount of project resources, about 60,000 resources. Every time we use the importer to import the project from version 2.x to version 3.4.2, it crashes. After talking with our editor colleague @arsen2010, we confirmed that the editor crashes after taking up too much memory.

### Steps to reproduce

Use the 2.x import tool in CocosCreator version 3.4.2 to import 2.x projects into new projects in CocosCreator version 3.4.2.

### Minimal reproduction project

You can find @arsen2010

**Comment by jareguo** [comment]
It feels like when importing, we can't import too many at once, we have to make it in batches

**Comment by VisualSJ** [comment]
The problem has been solved

**Comment by zhefengzhang** [comment]
[crash.zip](https://github.com/cocos/cocos-engine/files/9306405/crash.zip)

**Comment by VisualSJ** [comment]
I tried several machines and found one machine that crashed when 5W resources were imported at a time, and the impact area was small.  Therefore, lower the priority

**Comment by VisualSJ** [comment]
The problem has been dealt with
