### ISSUE TITLE
Incomplete particle release.

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#10887]
### Cocos Creator version

3.4.2

### System information

android

### Issue description

Before loading：
![image](https://user-images.githubusercontent.com/40415168/165276409-1ad9dd78-4d5e-4f36-92a3-1080ee0454f2.png)

After loading:
![image](https://user-images.githubusercontent.com/40415168/165276576-bb62ec8c-7467-4fed-9981-f12a9daa8084.png)

After release：
![image](https://user-images.githubusercontent.com/40415168/165278773-264292f3-0ee0-4eb5-ba9a-fcee32c66c86.png)

The internal memory is also growing after release

### Steps to reproduce

demo：
[NewProject.zip](https://github.com/cocos/cocos-engine/files/8562114/NewProject.zip)
 
![1650968060(1)](https://user-images.githubusercontent.com/40415168/165277992-ddfadc56-6610-4ac9-9e92-cf2a8b61660f.png)
Steps：
After clicking the button, wait for a while and then just press the button again.（First load, second release）

**Comment by OnlyKoei** [comment]
https://github.com/cocos/3d-tasks/issues/11259

**Comment by pandamicro** [comment]
@OnlyKoei Please attach diagnostic results in the internal issue here and close if applicable

**Comment by OnlyKoei** [comment]
Update Status.

others memory is the memory opened by v8 engine for old and new generation memory management. It has different memory allocation modes under different kernels on different platforms. It will use mmap reserved memory address in Android environment, because to ensure the application can run properly afterwards. others memory will not fall back on most of the models. Previously, our engine did not focus on this piece of memory management because v8 does not expose an explicit call to the interface for manually reclaiming others memory.
Normally, we consider it reasonable as long as the others memory can remain stable when switching back and forth between several scenarios, i.e., the expansion to normal size does not repeatedly increase again.

Therefore, we should not dwell on this (others memory) after confirming that there is no memory leak in other parts of the resource release and that it can be released completely.

If you are worried about excessive memory usage, lite-mode is Google's strategy to trade time for space when adapting low-end models, see [https://v8.dev/blog/v8-lite](https://v8.dev/blog/v8-lite). For the vast majority of phones with sufficient memory, you don't need to enable it.

**Comment by OnlyKoei** [comment]
https://github.com/cocos/cocos-engine/pull/11032

https://github.com/cocos/3d-tasks/issues/12262
