### ISSUE TITLE
Editor Spine animation can not set to "None"

### ISSUE THREAD

**Issue by yanjifa** [cocos/cocos-engine#10891]
### Cocos Creator version

3.5.0

### System information

Mac OS

### Issue description

控制台报错如下：
[Scene] Spine: Animation not found: \<None\>

### Steps to reproduce

None

**Comment by Ronsku** [comment]
@yanjifa How do you try to set the spine animation to "None"? I think it says "None" in the Cocos dropdown menu, but if you set the animation though code you should set it to an empty string
`setAnimation = '';`
Otherwise it is looking for an animation with the name "None"

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14619
