### ISSUE TITLE
Graphical drawing errors

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#10900]
### Cocos Creator version

3.4.2，3.5.0

### System information

chrome，native

### Issue description

![image](https://user-images.githubusercontent.com/40415168/165457860-a0b62ac1-bb1b-43db-bd00-b747feaf55d0.png)

This problem is caused by the different conditions established in sortLink, resulting in different plotting point generation.
![image](https://user-images.githubusercontent.com/40415168/165459647-4bd1b648-fd7b-400c-8b25-c814d74085dc.png)

### Steps to reproduce

2.4.9 demo:
[NewProject_22.zip](https://github.com/cocos/cocos-engine/files/8569551/NewProject_22.zip)

3.4.2 demo:
[NewProject_18.zip](https://github.com/cocos/cocos-engine/files/8569591/NewProject_18.zip)

graphic.ts -> fill() -> graphics-assembler.ts -> _expandFill() -> earcut.ts -> earcut() -> earcutLinked()
-> **indexCurve(**) -> sortLinked()
File path：.\engine\cocos\2d\assembler\graphics\webgl\earcut.ts
Interim Program：
![image](https://user-images.githubusercontent.com/40415168/165460404-fdc2afb0-8cd3-4c81-90a1-d5b6d2e2c67f.png)
![image](https://user-images.githubusercontent.com/40415168/165460631-1a23524e-fb8c-4962-83e4-e7b47287e342.png)

**Comment by zhefengzhang** [comment]
Feedback on the same issue: https://forum.cocos.org/t/topic/112037/, please raise the priority to fix this issue.

**Comment by LinYunMo** [comment]
Errors due to type errors.

We can consider updating this library. [Earcut](https://github.com/mapbox/earcut)

**Comment by dbq817** [comment]
this remains on 3.6.2!
