### ISSUE TITLE
Is CC_ASSERT needed?

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#10904]
The implementation if `CC_ASSERT` is 
```c++
#define CC_ASSERT(cond) assert(cond)
```

It just invoke `assert`, and should include `Macros.h` to use it. So do we need this macro?

**Comment by bofeng-song** [comment]
Mostly, user need log info. And at release mode may be user also want to abort application running

**Comment by minggo** [comment]
> Mostly, user need log info

Why not invoke log function?

> And at release mode may be user also want to abort application running

Assert is known as take effect with debug mode. If want to abort application in release mode, then should define another function. Or how do you know should abort or not in release mode?

**Comment by minggo** [comment]
@dumganhar @stanleyljl @star-e any idea?

**Comment by star-e** [comment]
I suggest keeping `CC_ASSERT`.
`assert` is disabled by `NDEBUG`, which is defined in Release build.
Sometimes, we want to assert in Release mode (with `NDEBUG` defined). This cannot be achieved using `assert`.
We can implement custom behavior using `CC_ASSERT` in this situation.

**Comment by dumganhar** [comment]
There is an  advantage to keep using CC_ASSERT in our code:
It will be easier to replace the implementation of CC_ASSERT, e.g. not depend the system `assert`.
```c++
#if CC_DEBUG
#define CC_ASSERT(cond) \
if (UNLIKELY(!(cond)) {
    CC_FATAL("condition check failed: file: %s, line: %d, function: %s", __FILE__, __LINE__, __FUNCTION__);
// CC_FATAL will output log and make app crash.
}
#else
#define CC_ASSERT(cond) 
#endif // CC_DEBUG
```

**Comment by star-e** [comment]
`CC_ASSERT` also looks better. 
`assert` looks like a function, which is inconsistent with our naming convention.

**Comment by minggo** [comment]
Though i don't agree should abort it in release mode using CC_ASSERT, but i agree that it keeps the ability to do more things in future. Then, let's keep it.
