### ISSUE TITLE
Hash computation in native engine causes loss of precision

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#10929]
## Background

Javascript VM (e.g. V8) uses `Double` to store number for representing both Integer & Double. There is a SMI (Small Integer) optimization that if an integer is less than 31 bits on 32  bits architecture device or less than 32 bits  on 64 bits architecture device. SMI is not what we need to discuss here. We're discussing the situation of how JS VM bind an integer that larger than 32 bits.

Javascript defines `Safe Integer` to remind developer that integer represented with Number has a range between `-2^53` to `2^53`, "Safe" means integers that can be represented one-by-one, that is, in the range (-2^53, 2^53), doubles and integers are one-to-one, and conversely, in Within this range, all integers have a unique floating-point representation, which is called safe integers. Beyond this range, there will be two or more integers whose double-precision representations are the same; on the other hand, beyond this range, some integers cannot be represented exactly, and can only be rounded to their nearest floating-point representations. Such cases are called unsafe integers. This is not a JS-specific property, but that is how IEEE754 double-precision floating-point numbers are defined.

### What happen if we bind a 64 bit integer to JS VM

In Cocos Creator native engine, we have many Hash computation logic to compute a hash value for some resources and export 64 bits integer (`size_t`) to JS. For instance, there is an interface called `Sampler::getHash` in gfx.

https://github.com/cocos/cocos-engine/blob/271cc5cf232e88238a8e5c35458c2e77bfd1bee5/native/cocos/renderer/gfx-base/states/GFXSampler.h#L42

```c++
class CC_DLL Sampler : public GFXObject {
public:
    explicit Sampler(const SamplerInfo &info);

    static size_t computeHash(const SamplerInfo &info);
    static SamplerInfo unpackFromHash(size_t hash);

    inline const SamplerInfo &getInfo() const { return _info; }
    inline const size_t &getHash() const { return _hash; } // Return size_t that is 64bits when targeting 64bits device.

protected:
    SamplerInfo _info;
    size_t _hash{0U};
};
```

https://github.com/cocos/cocos-engine/blob/271cc5cf232e88238a8e5c35458c2e77bfd1bee5/native/cocos/bindings/auto/jsb_gfx_auto.cpp

```c++
static bool js_gfx_Sampler_getHash(se::State& s) 
{
    auto* cobj = SE_THIS_OBJECT<cc::gfx::Sampler>(s);
    SE_PRECONDITION2(cobj, false, "js_gfx_Sampler_getHash : Invalid Native Object");
    const auto& args = s.args();
    size_t argc = args.size();
    CC_UNUSED bool ok = true;
    if (argc == 0) {
        const size_t& result = cobj->getHash();
// s.rval() will store int64_t with BigInt type, that's ok by now.
        ok &= nativevalue_to_se(result, s.rval(), nullptr /*ctx*/); 
        SE_PRECONDITION2(ok, false, "js_gfx_Sampler_getHash : Error processing arguments");
        SE_HOLD_RETURN_VALUE(result, s.thisObject(), s.rval());
        return true;
    }
    SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
    return false;
}
SE_BIND_FUNC(js_gfx_Sampler_getHash)
```

```c++
template <typename T>
void setReturnValueTemplate(const Value &data, const T &argv) {
    if (data.getType() == Value::Type::Undefined) {
        argv.GetReturnValue().Set(v8::Undefined(argv.GetIsolate()));
    } else if (data.getType() == Value::Type::Null) {
        argv.GetReturnValue().Set(v8::Null(argv.GetIsolate()));
    } else if (data.getType() == Value::Type::Number) {
        argv.GetReturnValue().Set(v8::Number::New(argv.GetIsolate(), data.toDouble()));
    } else if (data.getType() == Value::Type::BigInt) {
        // We cast the int64 to a double value and construct a v8::Number here. Precision will lost here.
        // If a 64 bit hash value is beyond the range of `-2^53 <-> 2^53`, JS will get the wrong hash value and hash conflict may happen.
        argv.GetReturnValue().Set(v8::Number::New(argv.GetIsolate(), static_cast<double>(data.toInt64())));
    }
    ......
}

void setReturnValue(const Value &data, const v8::FunctionCallbackInfo<v8::Value> &argv) {
    setReturnValueTemplate(data, argv);
}

void setReturnValue(const Value &data, const v8::PropertyCallbackInfo<v8::Value> &argv) {
    setReturnValueTemplate(data, argv);
}

#define SE_BIND_FUNC(funcName)                                                                                                              \
    void funcName##Registry(const v8::FunctionCallbackInfo<v8::Value> &_v8args) {                                                           \
        JsbInvokeScope(#funcName);                                                                                                          \
        bool                   ret      = false;                                                                                            \
        v8::Isolate *          _isolate = _v8args.GetIsolate();                                                                             \
        v8::HandleScope        _hs(_isolate);                                                                                               \
        se::ValueArray &       args = se::gValueArrayPool.get(_v8args.Length());                                                            \
        se::CallbackDepthGuard depthGuard{args, se::gValueArrayPool._depth};                                                                \
        se::internal::jsToSeArgs(_v8args, args);                                                                                            \
        se::PrivateObjectBase *privateObject = static_cast<se::PrivateObjectBase *>(se::internal::getPrivate(_isolate, _v8args.This(), 0)); \
        se::Object *           thisObject    = reinterpret_cast<se::Object *>(se::internal::getPrivate(_isolate, _v8args.This(), 1));       \
        se::State              state(thisObject, privateObject, args);                                                                      \
        ret = funcName(state);                                                                                                              \
        if (!ret) {                                                                                                                         \
            SE_LOGE("[ERROR] Failed to invoke %s, location: %s:%d\n", #funcName, __FILE__, __LINE__);                                       \
        }                                                                                                                                   \
        // We convert state.rval() which is represented with int64_t to v8::Number
        se::internal::setReturnValue(state.rval(), _v8args);                                                                                \
    }
```

https://github.com/cocos/cocos-engine/blob/271cc5cf232e88238a8e5c35458c2e77bfd1bee5/cocos/2d/renderer/batcher-2d.ts#L357

```ts
export class Batcher2D implements IBatcher {
......
    public commitComp (comp: Renderable2D, renderData: BaseRenderData|null, frame: TextureBase|SpriteFrame|null, assembler, transform: Node|null) {
        ......

        if (this._currHash !== dataHash || dataHash === 0 || this._currMaterial !== mat
            || this._currDepthStencilStateStage !== depthStencilStateStage) {
            ......
            if (frame) {
                this._currTexture = frame.getGFXTexture();
                this._currSampler = frame.getGFXSampler();
                this._currTextureHash = frame.getHash();
                this._currSamplerHash = this._currSampler.hash; // Call JSB method: js_gfx_Sampler_getHash
            } else {
                ......
            }
        }

        assembler.fillBuffers(comp, this);
    }
......
}
```

### Possible Solutions

- Solution (1)

Cocos Creator Web Engine uses 32 bits hash  computation by the third-party library `murmurhash2_32_gc` now. If native engine keeps the same strategy of using 32 bits hash (Use `uint32_t` for hash value) , hash value will not be clipped in the static_cast<double> conversion. Because double could represent the whole range of 32bits integer, we could make sure the return value is safe (not clipped) for JS.

But @star-e suggest that 32 bit hash value will cause Hash conflict easily in games.

- Solution (2)

Both Cocos Creator Web engine & native engine use BigInt for representing hash value.  In the hash implementation on web platform, `murmurhash2_32_gc` needs to be extend to something like `murmurhash2_64_gc` and the result value of this function needs to be changed to BigInt too.

And if bit operation is needed, the left and the right side of bit operation should both be a BigInt value, otherwise JS VM will trigger an error. For example:

<img width="826" alt="Screen Shot 2022-05-05 at 11 15 28" src="https://user-images.githubusercontent.com/493372/166858833-2afa8f97-6239-4fe5-8823-076378cd2dae.png">

### My Advice

We need to keep the same logic for both Web & Native platform. Solution (1) and (2) are both ok for me. But I'm not familiar with Javascript language, perhaps use 64 bit hash computation will make the performance worse on web platform. 

Suggestions are appreciated.

**Comment by star-e** [comment]
We should store the actual key/descriptor along with the hash value.
In case of hash collision (value found), we can use the key to do equal comparison. (Just like std::unordered_map)
In this case, 32bit hash-value is enough.

If we don't have the original key/descriptor, UUID is required.
This UUID is at least 53bit and128bit is better. Using domain specific UUID as seed, and `hash_combine` with the key/descriptor.

If 53bit hash value can be implemented, we can use `number` to store the value. Otherwise `BigInt` is required.

**Comment by dumganhar** [comment]
> We should store the actual key/descriptor along with the hash value.
In case of hash collision (value found), we can use the key to do equal comparison. (Just like std::unordered_map)
In this case, 32bit hash-value is enough.

The hash APIs  in our engine are something like getHash, computeHash and return an ID. If we store key/descriptor for classes need hash functionality, it will take more memory, every time a hash value is required, we need to check whether there is a collision happen which needs a finding operation. Is my understanding correct?  

> This UUID is at least 53bit and128bit is better. Using domain specific UUID as seed, and hash_combine with the key/descriptor.

Could this approach resolve the hash collision issue?

> If 53bit hash value can be implemented, we can use number to store the value. Otherwise BigInt is required.

Yep, if 53bits hash could be implemented, that will be great.

**Comment by minggo** [comment]
I suggest to use BitInt, and just use hash value to check conflict, not use it for other computation. Then i think it will not affect performance.

**Comment by dumganhar** [comment]
There is a 53bit hash implementation for JS: https://github.com/bryc/code/blob/master/jshash/experimental/cyrb53.js

**Comment by minggo** [comment]
If using 53bit hash in JS, then should provide a corresponding C++ version.

**Comment by dumganhar** [comment]
> If using 53bit hash in JS, then should provide a corresponding C++ version.

Yes.

Or could we just ignore 11 bits (64 - 53) from the boost 64 bit hash? We need to investigate and test hash collision.

**Comment by dumganhar** [comment]
BigInt is supported from Chrome 67 and some browsers and mini-game platforms may not support BigInt.

**Comment by star-e** [comment]
When compute/hash combine 53bit value, the intermediate result should also be 53bit. Otherwise it might produce different result in different language (javascript / c++).

**Comment by dumganhar** [comment]
> When compute/hash combine 53bit value, the intermediate result should also be 53bit. Otherwise it might produce different result in different language (javascript / c++).

So if we wanna use 53bit hash, we need to replace `boost` hash function with the new 53bit hash algorithm which works both on javascript & native and generate the same hash value if input is the same.

**Comment by star-e** [comment]
> > When compute/hash combine 53bit value, the intermediate result should also be 53bit. Otherwise it might produce different result in different language (javascript / c++).
> 
> So if we wanna use 53bit hash, we need to replace `boost` hash function with the new 53bit hash algorithm which works both on javascript & native and generate the same hash value if input is the same.

Yes. All std::hash, boost::hash, boost::hash_combine need rewrite. It is quite a lot of work.

**Comment by dumganhar** [comment]
There is a problem if we using 53 bits hash for web, look at this example:

<img width="370" alt="企业微信截图_e9e4b84d-e634-4b4d-9c8a-95417e641f6a" src="https://user-images.githubusercontent.com/493372/168712471-5ae9b65a-a4ec-41cf-b4b3-df3eb8cfb6c8.png">

JS safe number range is (-2^53, 2^53), Math.pow(2, 32) is 0x100000000, if we right shift it by 1, it should be the value of Math.pow(2, 31) which is 0x80000000, but it becomes 0 on web. Finally, I found a documentation describes bit operation of javascript number is 32 bits only, you could refer to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#bitwise_operators
<img width="833" alt="企业微信截图_934568b7-ff08-41d9-ad88-0081e4db4fc8" src="https://user-images.githubusercontent.com/493372/168713020-96e19ef0-71aa-427c-ac9d-33d2fedd8515.png">

In Cocos Creator engine, if hash getter function returns a number bigger than 32bits and if we do a bit operation for that number, it will be cut to 32 bits first, do the bit operation later. This behavior is not what we expect.

![企业微信截图_b9e75de6-21a5-4669-a9ef-22433baca078](https://user-images.githubusercontent.com/493372/168714312-de29902a-e486-423f-8a58-8bb316d05855.png)

So 53 bits hash probably is not an option.

**Comment by dumganhar** [comment]
In Cocos Creator engine, hash value in asset json file is defined as 32 bits integer.
```js
"shaders": [
  {
    "name": "billboard|vert:vs_main|tinted-fs:add",
    "hash": 1676330124, // 32 bits integer currently
    "builtins": {
    ...
    }
  },
  ...
}
```

Because JS number could not be represented as 64 bits integer, we could not put a 64 bits integer directly since it will be cut while being deserialized. To solve this, the hash data needs to be saved by two 32bits integers separately (low 32bits, high 32bits). This breaks the compatibility and needs to data upgrade in editor.

```js
"shaders": [
  {
    "name": "billboard|vert:vs_main|tinted-fs:add",
    "hash": {
      "__type__": "cc.Int64",
      "low": 1676330124, // low 32bits
      "high": 1676330124 // high 32 bits
    },
    "builtins": {
    ...
    }
  },
  ...
}
```

@star-e @holycanvas What are your opinion?

**Comment by dumganhar** [comment]
Another option is:
- Keep using 32 bits Hash for web
- C++ code  uses 64 bits Hash 
- When JS invokes JSB methods to get hash value, convert the 64 bits result to 32 bits by right shift & xor operation, for example

```c++
uint32_t getHash32() const { // Export this method to JS
    return (_hash >> 16) ^ (_hash & 0xFFFFFFFF); // I think it could avoid hash collision if some 64 bits _hash value is often distributed on high bits.
}

uint64_t getHash64() const {
    return _hash;
}
```

So CPP code keeps using 64 bits hash on 64 bits device. 

There is another problem: 
Currently, we use boost::hash_range/hash_combine for compute hash value , it only accesses size_t for seed and result hash value. size_t is platform-dependence type which is 32bits on 32bits system, 64bits on 64bits system. Do we need 64 bits hash for 32bits devices (Android armeabi-v7a )?

**Comment by star-e** [comment]
I think it is too troublesome to use 64-bit hash. The problem introduced by 64bit-hash is larger than 32bit hash collision.
Use 32-bit hash is also easier in x64. We just need to provide custom hash function.
We can also get consistent hash-value across 32bit/64bit systems.

We can reduce object number, or uses different groups to control hash collision.
