### ISSUE TITLE
[v3.6] Performance Test for loading large scenes

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#10935]
We have moved most classes in 3d assets from JS to cpp. But we continue to depend on the deserialization logic in JS which will cause a lot of JSB invocations if loading a large scene.

Therefore, we need to do more performance test and figure out how much performance cost in v3.6.
If the performance of v3.6 is exactly lower than v3.5, we need to find a better way to avoid. For example, we could try to move some of deserialization logic to cpp.

**Comment by SantyWang** [comment]
Performance Record

windows-v3.5:
LoadScene 408.01820000074804 ms
InitScene: 14.396399999968708 ms
Activate: 2359.523299999535 ms

windows-v3.6
loadScene: 879 ms
InitScene: 83.0773999998346 ms
Activate Scene: 3982.9556999998167 ms

project:
[Performance-Loading-3.6.zip](https://github.com/cocos/cocos-engine/files/8630706/Performance-Loading-3.6.zip)

**Comment by holycanvas** [comment]
Performance Hot Spot
![image](https://user-images.githubusercontent.com/15109777/166878124-0e8a128a-8def-49b0-a516-969538a1e4f3.png)
![image](https://user-images.githubusercontent.com/15109777/166878264-a55fd50a-9902-4354-8fd0-674e40ac6ad6.png)

**Comment by dumganhar** [comment]
## Android test result

On Redmi 5 plus Android 8.1.0 (arm64-v8a) (3.5.0)
- LoadScene: 1646ms, 1620ms, 1562ms
- runScene: 4514ms, 4417ms, 4499ms

On Redmi 5 plus Android 8.1.0  (arm64-v8a) (3.6.0)
- LoadScene: 2038ms, 1768ms, 1828ms
- runScene: 2664ms, 2663ms, 2827ms

On Redmi 5 plus Android 8.1.0  (arm64-v8a) (3.6.0 - unify CCObject:  #11060)
- LoadScene: 2063ms, 1815ms, 1831ms
- runScene: 2662ms, 2643ms, 2618ms

---------------------------------------------
On Pixel 4XL Android 13 (arm64-v8a) (3.5.0)
- LoadScene: 589ms, 586ms, 572ms
- runScene: 1186ms, 1368ms, 1256ms

On Pixel 4XL Android 13 (arm64-v8a) (3.6.0)
- LoadScene: 630ms, 535ms, 527ms
- runScene: 717ms, 804ms, 851ms

On Pixel 4XL Android 13 (arm64-v8a) (3.6.0 - unify CCObject:  #11060 )
- LoadScene: 522ms, 598ms, 554ms
- runScene: 732ms, 830ms, 752ms

---------------------------------------------
On OnePlus 6 Android 11 (arm64-v8a) (3.5.0)
- LoadScene: 738ms, 607ms, 665ms
- runScene: 1745ms, 1562ms, 1570ms

On  OnePlus 6 Android 11 (arm64-v8a) (3.6.0)
- LoadScene: 876ms, 668ms, 706ms
- runScene: 962ms, 961ms, 987ms

---------------------------------------------
On SM-N9005 Android 5.0 (armeabi-v7a) (3.5.0)
- LoadScene: 2970ms, 3013ms, 2776ms
- runScene: 8116ms, 7932ms, 8025ms

On SM-N9005 Android 5.0 (armeabi-v7a) (3.6.0)
- LoadScene: 3514ms, 3425ms, 3532ms
- runScene: 6621ms, 6136ms, 6447ms

---------------------------------------------
On SM-G610F Android 7.0 (armeabi-v7a) (3.5.0)
- LoadScene: 2258ms, 2389ms, 2340ms
- runScene: 7135ms, 6934ms, 6890ms

On SM-G610F Android 7.0 (armeabi-v7a) (3.6.0)
- LoadScene: 3133ms, 2801ms, 2736ms
- runScene: 6002ms, 4959ms, 5034ms

---------------------------------------------

[loading350-32.apk.zip](https://github.com/cocos/cocos-engine/files/8638638/loading350-32.apk.zip)
[loading350-64.apk.zip](https://github.com/cocos/cocos-engine/files/8638639/loading350-64.apk.zip)
[loading360-32.apk.zip](https://github.com/cocos/cocos-engine/files/8638642/loading360-32.apk.zip)
[loading360-64.apk.zip](https://github.com/cocos/cocos-engine/files/8638643/loading360-64.apk.zip)

Rename xxx.apk.zip to xxx.apk and install to your android device for testing.

Look for log in logcat window:

D/jswrapper: JS: [ERROR]: loadScene: 706
D/jswrapper: JS: [INFO]: cjh runSceneImmediate cost: 987.9220000000005ms

**Comment by dumganhar** [comment]
## iOS test result

On iphoneX iOS12.0 (3.5.0)
- LoadScene: 595ms, 600ms, 593ms
- runScene: 1011ms, 1024ms, 1035ms

On iphoneX iOS12.0 (3.6.0)
- LoadScene: 647ms, 492ms, 498ms
- runScene: 625ms, 583ms, 568ms

On iphoneX iOS12.0 (3.6.0 - after unifying CCObject: https://github.com/cocos/cocos-engine/pull/11060 )
- LoadScene: 651ms, 501ms, 497ms
- runScene: 568ms, 548ms, 531ms

---------------------------------------------

**Comment by minggo** [comment]
Good news.

**Comment by minggo** [comment]
> Performance Record
> 
> windows-v3.5: LoadScene 408.01820000074804 ms InitScene: 14.396399999968708 ms Activate: 2359.523299999535 ms
> 
> windows-v3.6 loadScene: 879 ms InitScene: 83.0773999998346 ms Activate Scene: 3982.9556999998167 ms
> 
> project: [Performance-Loading-3.6.zip](https://github.com/cocos/cocos-engine/files/8630706/Performance-Loading-3.6.zip)

Did you use release mode?

**Comment by SantyWang** [comment]
Using release mode

3.5.0:
load scene: 230
init scene: 7
activate scene: 630

3.6.0:
load scene: 278
init scene: 12
activate scene: 495

**Comment by minggo** [comment]
Good news. So the performance(from loading to see the scene) is better than v3.5.0.

**Comment by dumganhar** [comment]
## Android test result (Demo2, private demo)

On Redmi 5 plus Android 8.1.0 (armeabi-v7a) (3.5.0)
- director.loadScene: 4797ms, 4699ms, 4651ms

On Redmi 5 plus Android 8.1.0  (armeabi-v7a) (3.6.0)
- director.loadScene: 4546ms, 4549ms, 4543ms

---------------------------------------------
On Pixel 4XL Android 13 (armeabi-v7a) (3.5.0)
- director.loadScene: 2474ms, 2422ms, 2406ms

On Pixel 4XL Android 13 (armeabi-v7a) (3.6.0)
- director.loadScene: 2332ms, 2360ms, 2679ms


---------------------------------------------

**Comment by dumganhar** [comment]
## Android test result ( Marionette demo: https://github.com/cocos-creator/example-marionette )

On Redmi 5 plus Android 8.1.0 (armeabi-v7a) (3.5.0)
- director.loadScene -> onLaunch:  8319ms, 8032ms, 7862ms
- onLaunch -> next scene shown: 433ms, 331ms, 330ms

On Redmi 5 plus Android 8.1.0  (armeabi-v7a) (3.6.0)
- director.loadScene -> onLaunch: 5997ms, 5974ms, 5994ms
- onLaunch -> next scene shown: 231ms, 225ms, 217ms

---------------------------------------------
On Pixel 4XL Android 13 (armeabi-v7a) (3.5.0)
- director.loadScene -> onLaunch: 4005ms, 3964ms, 3949ms
- onLaunch -> next scene shown: 84ms, 81ms, 81ms

On Pixel 4XL Android 13 (armeabi-v7a) (3.6.0)
- director.loadScene -> onLaunch: 2369ms, 2458ms, 2362ms
- onLaunch -> next scene shown: 68ms, 57ms, 57ms


---------------------------------------------
On iphoneX iOS12 (3.5.0)
- director.loadScene -> onLaunch: 1708ms, 1533ms, 1431ms
- onLaunch -> next scene shown: 244ms, 243ms, 242ms

On iphoneX iOS12(3.6.0  - after unifying CCObject: https://github.com/cocos/cocos-engine/pull/11060 )
- director.loadScene -> onLaunch: 1582ms, 1256ms, 1239ms
- onLaunch -> next scene shown: 37ms, 35ms, 34ms


---------------------------------------------

**Comment by dumganhar** [comment]
## Android test result ( UI demo: https://github.com/cocos/cocos-example-ui/tree/v3.1  )

On Redmi 5 plus Android 8.1.0 (armeabi-v7a) (3.5.0)
- director.loadScene -> onLaunch:  720ms, 736ms, 734ms
- onLaunch -> next scene shown: 510ms, 512ms, 505ms

On Redmi 5 plus Android 8.1.0  (armeabi-v7a) (3.6.0)
- director.loadScene -> onLaunch: 749ms, 727ms, 714ms
- onLaunch -> next scene shown: 540ms, 537ms, 504ms

---------------------------------------------
On Pixel 4XL Android 13 (armeabi-v7a) (3.5.0)
- director.loadScene -> onLaunch: 358ms, 371ms, 355ms
- onLaunch -> next scene shown: 187ms, 171ms, 173ms

On Pixel 4XL Android 13 (armeabi-v7a) (3.6.0)
- director.loadScene -> onLaunch: 364ms, 362ms, 374ms
- onLaunch -> next scene shown: 162ms, 171ms, 164ms


---------------------------------------------

**Comment by dumganhar** [comment]
## Android + iOS test result ( Benchmark  demo, model-animation, load 300 models : https://github.com/cocos/cocos-benchmark.git  )

On Redmi 5 plus Android 8.1.0 (armeabi-v7a) (3.5.0)
- director.loadScene -> onLaunch:  86ms, 90ms, 91ms
- onLaunch -> next scene shown:  7099ms, 6993ms, 6964ms

On Redmi 5 plus Android 8.1.0  (armeabi-v7a) (3.6.0)
- director.loadScene -> onLaunch: 85ms, 87ms, 90ms
- onLaunch -> next scene shown: 6884ms, 6955ms, 7169ms

---------------------------------------------
On Pixel 4XL Android 13 (armeabi-v7a) (3.5.0)
- director.loadScene -> onLaunch: 31ms, 29ms, 31ms
- onLaunch -> next scene shown: 2052ms, 2087ms, 2085ms

On Pixel 4XL Android 13 (armeabi-v7a) (3.6.0)
- director.loadScene -> onLaunch: 33ms, 33ms, 36ms
- onLaunch -> next scene shown: 2262ms, 2769ms, 2479ms

---------------------------------------------
On SM-N9005 Android 5.0 (armeabi-v7a) (3.5.0)
- director.loadScene -> onLaunch: 143ms, 107ms, 101ms
- onLaunch -> next scene shown: 11285ms, 11673ms, 11671ms

On SM-N9005 Android 5.0 (armeabi-v7a) (3.6.0)
- director.loadScene -> onLaunch: 137ms, 136ms, 137ms
- onLaunch -> next scene shown: 11704ms, 11698ms, 11607ms

---------------------------------------------
On iphoneX iOS12 (3.5.0)
- director.loadScene -> onLaunch: 31ms, 31ms, 29ms
- onLaunch -> next scene shown: 2300ms, 2299ms, 2223ms

On iphoneX iOS12 (3.6.0)
- director.loadScene -> onLaunch: 27ms, 28ms, 30ms
- onLaunch -> next scene shown: 1478ms, 1477ms, 1415ms

On iphoneX iOS12 (3.6.0 - after unifying CCObject: https://github.com/cocos/cocos-engine/pull/11060)
- director.loadScene -> onLaunch: 31ms, 40ms, 34ms
- onLaunch -> next scene shown: 1389ms, 1307ms, 1303ms


---------------------------------------------

**Comment by Ronsku** [comment]
I've also noticed that even though the scene is preloaded and ready to be fired up, it takes some time to launch. Would it be possible to create a "await preLaunch()" command that does the launching without showing or causing drawcalls and then launch itself would be almost instant?

Often you want to swap scenes in a matter of milliseconds, mid animation transition or such and it's quite difficult to create smooth transitions now between scenes.

The way I've done it now is to use persistent nodes on the current scene, launching the next scene behind the current scene and then just destroy and remove the current scene from persistent nodes. It works, but it's a very ugly solution.

**Comment by dumganhar** [comment]
@Ronsku Yes, I also notice that, the time of loading scene is much less than the time of the next scene is shown.
@holycanvas Any thoughts of that? Are there better solutions ?

**Comment by SantyWang** [comment]
> I've also noticed that even though the scene is preloaded and ready to be fired up, it takes some time to launch. Would it be possible to create a "await preLaunch()" command that does the launching without showing or causing drawcalls and then launch itself would be almost instant?

> Often you want to swap scenes in a matter of milliseconds, mid animation transition or such and it's quite difficult to create smooth transitions now between scenes.

> The way I've done it now is to use persistent nodes on the current scene, launching the next scene behind the current scene and then just destroy and remove the current scene from persistent nodes. It works, but it's a very ugly solution.

I would like to know, What is the functionality of these two scenes? and what transition needed for the two scenes?

**Comment by Ronsku** [comment]
> I would like to know, What is the functionality of these two scenes? and what transition needed for the two scenes?

I use multiple scenes per game to keep everything organized. Just as an example, let's say you are playing a 2D overview game and walk into a door, you run a quick animation that opens the door (covering the whole screen with something) and swap scene mid animation where screen is covered by the animation. This animation could be ran on a persistent node above both scenes. This would make it possible to create a smooth transition from one scene to another.

When now, depending on the device you are running on the next scenes instantiation could take 100ms or 1000ms you cannot run it mid animation, instead you have to separate the animation into something
- Run a "open animation" that covers the screen
- Wait for scene swap (100ms 1000ms or how long it takes)
- Then run a "close animation" to remove the overlay that covers the screen to reveal the new scene.

Sometimes I've used fade to black 500ms animation, then stay at black until scene has swapped and fade back to from the black overlay in the new scene. Problem here is that I want the swap to be fast and smooth, 500ms fade to black, 500ms fade back to invisible overlay. But since it might take a long time to instantiate the next scene player might be stuck in a black screen for a few seconds wondering "what is going on..?"

This is why it would be amazing to just be able to "await preLaunch()" a scene that does all the heavy lifting and basically instantiates the scene for you in memory and when you then "launchScene()" it would be instant. The same way you would just toggle "node.active = true". And my workaround with placing a scene as persistent node solves this in an ugly way.

**Comment by dumganhar** [comment]
@Ronsku I think you could create a new issue to describe the problem. This issue is just for comparing the loading performance between 3.5 & 3.6 . Thanks.
