### ISSUE TITLE
[2.x][ios]Cannot set the current playback time of the video

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#10946]
### Cocos Creator version

2.4.9

### System information

ios

### Issue description

https://forum.cocos.org/t/topic/135112
Using `videoplayer.currentTime = 30` does not modify the current playback progress.

The reason for this is that the video and videoplayer components are not synchronized with the currentTime on the web platform.

### Steps to reproduce

You need to use ios WeChat to scan the QR code to reproduce it.
No problem for Android.

**Comment by zhefengzhang** [comment]
On IOS mobile browsers, the play event is triggered before the canPlay event, so loaded cannot be set to true. onCanPlay function does not need to determine _playing, so it is removed.
在 IOS 手机浏览器上，play 事件比 canPlay 事件更早被执行，所以导致 loaded 无法被设置为 true。onCanPlay 函数中无需判断 _playing，所以去掉。
