### ISSUE TITLE
cc.macro.KEY can't get keyCode 6,8,9 because duplicated key with back, backspade and tab

### ISSUE THREAD

**Issue by KKK13121997** [cocos/cocos-engine#10960]
### Cocos Creator version

2.4.6

### System information

All

### Issue description

```
let key6 = cc.macro.KEY[6];
let key8 = cc.macro.KEY[8];
let key9 = cc.macro.KEY[9];
console.log(key6, key8, key 9);
```

### Relevant error log output

output: back, backspade, tab
expect : 54, 56, 57

### Steps to reproduce

using the code above

**Comment by PPpro** [comment]
![微信截图_20220512142954](https://user-images.githubusercontent.com/17872773/168006190-d7ae876d-716b-43e4-a18f-906b5ed9ba67.png)
here is the output I test on the chrome inspector, I think this should meet the expectation

**Comment by PPpro** [comment]
I'll close this issue, 
If you have any other issue, please give us feedback
