### ISSUE TITLE
iOS Safari web audio sound crackles

### ISSUE THREAD

**Issue by yoki0805** [cocos/cocos-engine#10977]
### Cocos Creator version

3.4.2

### System information

iOS 15.4 Safari, iPhone 6S, iPhone 8, iPhone SE2

### Issue description

Using AudioSource component to play sounds in many times. 5 minutes later, iPhone will be playing noise.

### Steps to reproduce

To play sounds in many times.

### Minimal reproduction project

[NewProject.zip](https://github.com/cocos/cocos-engine/files/8639298/NewProject.zip)

**Comment by Ronsku** [comment]
I have experienced the same with Howler, I think it has to do something with performance of the game, memory and stuff. I know sounds eat up a lot of memory at least. I don't think it's something related directly to the CC sound engine. Just my guess.

**Comment by yoki0805** [comment]
Yes, it's happening later with newer iPhone (more larger memory).
But, I did many projects in 2.4.x version, they didn't seem to have this issue.
Android works fine, either 2.4.x or 3.4.2.

**Comment by Ronsku** [comment]
@yoki0805 do you have the same drawcalls in CC2 as in CC3 in your games? I had myself slight issues with performance in CC3, for example opacity = 0 causes a drawcall in CC3 which it didn't in CC2. I have created this issue/suggestion for the drawcalls on invisible items https://github.com/cocos/cocos-engine/issues/11210.

**Comment by yoki0805** [comment]
No, they are different games, but I control the drawcalls in 70~100 times for my games.

**Comment by bofeng-song** [comment]
Fixed at this [PR](https://github.com/cocos/cocos-engine/pull/15807)
