### ISSUE TITLE
Manually control the execution of github workflow

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#10987]
There are some situations we want to manually control the execution of github workflows:
- If a PR doesn't modify any source code, for example, just modify comments, then we want to skip all github workflows. The usage is
```
[skip ci]PR title
```
- If a PR only modifies javascript codes, then want to skip native related github workflows(workflows have the name prefix `native-`.), the usage is
```
[skip native]PR title
```
- If a PR only modifies c++ codes, then want to skip web related github workflows(the github workflows except native-related github workflows), the usage is
```
[skip web]PR title
```

**Comment by minggo** [comment]
It is better that, when PR title is changed, then the execution state of github workflows are changed too. For example, 
- At first, the PR only modified ts codes, and the PR title is `[skip native]Modify something`, all native related github workflows will not execute.
- After reviewed, this PR need to modify c++ codes, and change the PR title to `Modify something`, then all github workflows should execute as the PR title is changed.

**Comment by pandamicro** [comment]
Another option is to provide check lists for PR creator to select, for example, add the following section to PR template:

-------
### Continuous Integration

This pull request:
- [ ] contains engine modification
- [ ] needs code quality check
- [ ] needs build check
- [ ] needs automatic test cases check
-------

User can directly choose what fits.

Also if they want to run test case manually, they can still use

`@cocos-robot run test cases`

**Comment by minggo** [comment]
Yep, it is more clear.

> contains engine modification

I think should divide it into more options: all, TS, c++

**Comment by star-e** [comment]
I think build check should be mandatory. User might have uploaded incorrect code by accident.

**Comment by stanleyljl** [comment]
> Another option is to provide check lists for PR creator to select, for example, add the following section to PR template:
> 
> ### Continuous Integration
> This pull request:
> 
> * [ ]  contains engine modification
> * [ ]  needs code quality check
> * [ ]  needs build check
> * [ ]  needs automatic test cases check
> 
> User can directly choose what fits.
> 
> Also if they want to run test case manually, they can still use
> 
> `@cocos-robot run test cases`

It's better to add manual commands after each option. In case the developer forgets to check, he can manually copy the command to execute.

**Comment by pandamicro** [comment]
I agree, I think we can also check modifications in the PR to decide whether TS engine or Cpp engine is modified, e.g.

- All modification applied in `cocos`, `exports`, `extensions`, `external`, `pal` folder means TypeScript engine modification
    - Requires web related CI
- All modification applied in `native` means Cpp engine modification
    - Requires Native related CI

In this case, we will leave the following options to the user

-------
### Continuous Integration

This pull request:
- [ ] **does not** change any runtime related code or build configuration // Manually trigger ci with `@cocos-robot run ci`
- [ ] needs automatic test cases check // Manual trigger with `@cocos-robot run test cases` afterward
-------

**Comment by minggo** [comment]
> All modification applied in native means Cpp engine modification

We may modify folder structure, and mix TS and C++ together. So it is not extensible.

**Comment by pandamicro** [comment]
Yes, but I think it applies for now, when we change the code structure, we will need to modify the rules

**Comment by fish9167** [comment]
Change the action (run test cases) triggering
- manual: add comments "@cocos-robot "
- auto: [x] needs automatic test cases check.

[Change action run test cases #11386](https://github.com/cocos/cocos-engine/pull/11386)
[sync action yml #11495](https://github.com/cocos/cocos-engine/pull/11495)

**Comment by pandamicro** [comment]
Change the template to 

- [ ] does not change any runtime related code or build configuration
> If reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue

**Comment by pandamicro** [comment]
This has been fulfilled
