### ISSUE TITLE
浏览器调整大小导致控件点击响应区域偏移错位（2.4.3版本）

### ISSUE THREAD

**Issue by xiaobiG** [cocos/cocos-engine#10996]
### Cocos Creator version

2.4.3

### System information

Windows10, Mac , Chrome

### Issue description

Web端调整浏览器窗口大小后会出现挂了Widget的控件的鼠标事件响应区域和实际显示区域偏移错位。

### Steps to reproduce

1. 创建带cc.Widget的node，上下左右贴边
2. 添加cc.Button到上述node中
3. 运行，反复改变浏览器窗口大小。

### Minimal reproduction project

[NewProject_1.zip](https://github.com/cocos/cocos-engine/files/8644966/NewProject_1.zip)
![cocos](https://user-images.githubusercontent.com/17143195/167251432-f2cd2268-f7e8-4a49-b4d0-649cf228b1ec.gif)

**Comment by jareguo** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下 最新 版本的引擎（3.5），看看这个 bug 是否仍然存在。先不用考虑升级到 最新 版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。如果测试完仍然有问题，可以 reopen，我们来跟进处理。
