### ISSUE TITLE
v3.5.0 Particle 2d in prefab reporting error

### ISSUE THREAD

**Issue by zenskcode** [cocos/cocos-engine#10998]
### Cocos Creator version

3.5.0

### System information

windows10

### Issue description

Sampler binding ‘cc_spriteTexture’ at set 2 binding 11 index 0 is not bounded

canvas下粒子动画作为预制体嵌入（使用了材质），概率触发该bug，不断报错，触发后点一下从预制体还原，错误消失。看起来像是在不断切换预制体场景时，资源保存写的时候，概率会脏

### Relevant error log output

Sampler binding ‘cc_spriteTexture’ at set 2 binding 11 index 0 is not bounded
![image](https://user-images.githubusercontent.com/46669456/167286165-cdcb308a-7a18-45df-97ee-4b3cc171727e.png)

### Steps to reproduce

canvas下粒子动画作为预制体嵌入（使用了sprite材质），概率触发该bug，不断报错，触发后点一下从预制体还原，错误消失。看起来像是在不断切换预制体场景时，资源保存写的时候，概率会脏

### Minimal reproduction project

公司项目暂不方便提供

**Comment by pandamicro** [comment]
ParticleSystem can't use Sprite effect, it just won't work, you should remove the custom effect and add UIModelComponent to the particle node.

Please have a try if it's ok or no feed back I will close this issue

**Comment by zenskcode** [comment]
我使用的是ParticleSystem2D 与sprite effect，当我设置完成，表现正常，也得到了预期的美术效果。

但是在场景——预制体切换或者预制体之间切换的时候，偶尔会发生上述错误，清除缓存后重新打开工程又表现正常。然后在之后的切换操作中，又会反复出现，又进行清缓存操作。概率发生，但概率比较高。

**Comment by zenskcode** [comment]
运行完全正常，但是编辑器疯狂报错，通过屏蔽以下目录文件的代码先解决错误了，初步判断未日志条件错误，请核查.
除了以上情况，在预制体中嵌套含有spine动画的预制体，也会发生该错误，待空闲一点，我看看能不能提供demo，方便引擎组测试排错
C:\CocosDashboard_1.1.1\resources\.editors\Creator\3.5.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js

![image](https://user-images.githubusercontent.com/46669456/167530568-bd7128cd-ef9a-4f0d-b632-934ed1d3a69a.png)

**Comment by dogeFu** [comment]
我这边复现了一下，可能是和材质预览有关系。你在切换场景和预制体的过程中，资源面板是否有选中材质？如果有的话，可以试试不选中，看看报错会不会减少。我们会尽快修复这个问题 @zenskcode

**Comment by zenskcode** [comment]
没有选中材质的情况下也会触发，报错是每一帧都在不断增加，只能重启编辑器才能解决，但是一旦切换预制体，又会触发，时间长不关编辑器就很卡，然后又只能重启编辑器，一直循环。我先屏蔽编辑器日志，这样可能会误伤有效的提醒日志，但是也只能先这样处理了。

**Comment by dogeFu** [comment]
我这边有一个必现的流程：拖拽一个预制体（使用UI-Sprite-material.mtl材质的2d元素）到场景中，然后创建一个材质，就会出现报错，不过这个复现方式，错误日志只会打印几条，后面就不会再报错了。这个问题我们会在3.5.1修复。

**Comment by dogeFu** [comment]
该问题是材质绑定异常导致，已在3.5.1修复。

**Comment by zenskcode** [comment]
3.5.1测试不再复现
