### ISSUE TITLE
[3.5] Uncaught RangeError: Offset is out of bounds still accured on v3.5

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#11004]
### Cocos Creator version

3.5.0

### System information

Macos 11.4, Chrome Version 100.0.4896.127 (Official Build) (x86_64)

### Issue description

Ref: https://discuss.cocos2d-x.org/t/3-4-2-spine-issue-uncaught-rangeerror-offset-is-out-of-bounds/55847
This issue has not fixed completely, no error throws for the first time (before 3.5, this will be accured immediately for the first call), but if we trying to play the game for a while then the error will be throwed again.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/18746281/167378369-0901a106-05d2-4c9a-9b4a-e3e6645d9c43.png">

### Steps to reproduce

.

**Comment by bofeng-song** [comment]
382 has been changed to use the wasm implementation method, and after multiple rounds of testing, the issue has not been reproduced. If the issue reoccurs in 382, please provide timely feedback. Thank you.
