### ISSUE TITLE
3.5.0 spine命名空间漏导出

### ISSUE THREAD

**Issue by zenskcode** [cocos/cocos-engine#11008]
### Cocos Creator version

3.5.0

### System information

windows10

### Issue description

3.4.2 cc.d.ts:
![651faaa3de78b18c73e0cdb8e445de1](https://user-images.githubusercontent.com/46669456/167447142-112250e3-ae67-4fc6-b100-201207054cc6.png)

3.5 cc.d.ts
![5484eda10bbbc1b33254cb6e30941aa](https://user-images.githubusercontent.com/46669456/167447259-21697323-d3bf-4534-bfa7-ed409b89e0d5.png)

api:
![image](https://user-images.githubusercontent.com/46669456/167447337-b61d2473-48d8-4b50-a2f3-626b5a38bfa3.png)

3.5.0 导出spine命名空间应该存在遗漏

### Steps to reproduce

use:
![c62833cb4d5bcca3a36d9bab1c06941](https://user-images.githubusercontent.com/46669456/167447483-22e7c5c7-8d33-4492-b6fa-38354c7d0a22.png)

**Comment by zhakesi** [comment]
暂不影响运行.

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/12402
