### ISSUE TITLE
Audio play error

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11019]
### Cocos Creator version

3.4.1，3.4.2，3.5.0

### System information

window10, android , web

### Issue description

When play is called immediately after setting currentTime, the audio will start over.
Test platform：
android, vivo mini game, wechat mini game, web-mobile

![image](https://user-images.githubusercontent.com/40415168/167583662-da424a72-3a40-4060-a2bc-efc1c94cc8d4.png)

### Steps to reproduce

demo:
[NewProject_10.zip](https://github.com/cocos/cocos-engine/files/8659679/NewProject_10.zip)

normal:
1. click play - button;
2. click pause - button;
3. click time - button;
4. click play - button;

error:
1. click play - button;
2. click pause - button;
3. click timeplay - button;
or
1. click timeplay - button directly

**Comment by PPpro** [comment]
![1](https://user-images.githubusercontent.com/17872773/177103360-346b462c-82ce-4ff3-a119-c342a4e7c7c3.png)


This is what we expected，we should restart the audio if it's playing when call `audioSource.play()`
