### ISSUE TITLE
Subsystem start up and shut down

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#11027]
Currently, engine uses the codes to initialize a subsystems
```c++
Engine::Engine() {
    _scheduler = std::make_shared<Scheduler>();
    FileUtils::getInstance()->addSearchPath("Resources", true);
    FileUtils::getInstance()->addSearchPath("data", true);
    EventDispatcher::init();
    se::ScriptEngine::getInstance();

#if CC_USE_PROFILER
    Profiler::getInstance();
#endif
}
```

It has some problems:
- use different ways to initialize a subsystem
   - use `XXX::getInstance()`
   - use `XXX::init()`
   - just construct a object instance
- use the same method to initialize a subsystem and get the singleton object
  - it is not a clear
  - it is uncontrollable, each invoking of the static method may initialize it again

# How to improve

It is better to have a unify way to initialize subsystems. There are two ways to do it as "Game Engine Architecture" suggests:
- Method1: use global static object with default constructor, and have startup and shutdown function
```c++
// System1.cpp
class SubSystem1 {
public:
    SubSystem1() { // do nothing }
    ~SubSystem1() { // do nothing }
    void startUp() { // start up the subsystem }
    void shutDown() { // shut down the subsystem }
};

// Engine.cpp
Subsystem1 gSubSystem1;
Engine() {
    gSubSystem1.startUp();
    ...
}

~Engine() {
    gSubSystem1.shutDown();
}
```
- Method2: only creates subsystem instance in engine constructor
```c++
// System1.cpp
class SubSystem1 {
public:
    SubSystem1() { // do nothing }
    ~SubSystem1() { // do nothing }
    void startUp() { // start up the subsystem }
    void shutDown() { // shut down the subsystem }
};

// Engine.h
class Engine {
private:
    SubSystem1 *_subSystem1{nullptr}
};

// Engine.cpp
Engine() {
     _subSystem1 = new SubSystem1;
     subsystem1->startUp();
}

~Engine() {
    _subSystem1->shutDown();
    delete _subSystem1;
}
```

# How to get the subsystem instance

There are two ways to get the subsystem:
- use engine object to get subsystem
```c++
auto *subSystem1 = engine->getSubSystem1();
subSystem1->doSomething();
```
- use subsystem static method
```
SubSystem1::getInstance()->doSomething();
```

I think use subsystem static method is more convenient

**Comment by stanleyljl** [comment]
It is better for each singleton to have a common parent class, and the parent class has a unified initialization and destruction interface. These singletons are not necessarily suitable as subclasses of subsystems, because they may just provide some simple functions and cannot be called a subsystem.

**Comment by minggo** [comment]
@stanleyljl could you please add some pseudo codes? I think it may easily cause multiple inheritance.

**Comment by timlyeee** [comment]
What about those subsystems that rely on each other? For example, EventDispatcher should be the first one to start, and most modules rely on it. Will the solution makes it easier to check if the dependency is alive?

**Comment by minggo** [comment]
> What about those subsystems that rely on each other? For example, EventDispatcher should be the first one to start, and most modules rely on it. Will the solution makes it easier to check if the dependency is alive?

Initialize all subsystems explicitly in a function in well-defined order.

**Comment by dumganhar** [comment]
```c++
auto *subSystem1 = engine->getSubSystem1();
subSystem1->doSomething();
```

I think solution 1 has some benefits: 
- Could be easily extended to support running multiple game engine instances in a single process
- Avoid to define `getInstance` method because different developers may use a different name, for example, getSingleton(), instance() 
- Avoid to use global variables, something like `Context` class should take the responsibility of registering internal `Subsystem`s, so need registerSubsystem & unregisterSubsystem

Could refer to Urho3D ( https://github.com/urho3d/Urho3D ) or rbfx ( https://github.com/rbfx/rbfx ) game engine:

https://github.com/urho3d/Urho3D/blob/master/Source/Urho3D/Engine/Engine.cpp#L111
https://github.com/urho3d/Urho3D/blob/master/Source/Tools/Urho3DPlayer/Urho3DPlayer.cpp#L39

**Comment by minggo** [comment]
> Avoid to use global variables, something like Context class should take the responsibility of registering internal Subsystems, so need registerSubsystem & unregisterSubsystem

It requires
- every object has a type information, or should add many get functions to get subsystems
- if using Context, then all every constructors should accept a Context pointer

**Comment by dumganhar** [comment]
> every object has a type information, or should add many get functions to get subsystems

Yep, need Object RTTI information. 
Don't need many get functions, since we could use c++ template. Refer to : https://github.com/rbfx/rbfx/blob/master/Source/Urho3D/Core/Context.h#L135

**Comment by dumganhar** [comment]
> if using Context, then all every constructors should accept a Context pointer

Yes, that's what Urho3D does.

**Comment by minggo** [comment]
> > every object has a type information, or should add many get functions to get subsystems
> 
> Yep, need Object RTTI information. Don't need many get functions, since we could use c++ template. Refer to : https://github.com/rbfx/rbfx/blob/master/Source/Urho3D/Core/Context.h#L135

Yep, that's why i said `or should add many get functions`.  Which means we should implement RTTI first.

**Comment by minggo** [comment]
@dumganhar  as getInstance() already exists, we can not remove it, or it will break compatibility. So i plan to do like this
- keep getInstance(), but it will not construct an object instance, and all subsystems use the same function name
- construct subsystem instance in engine

After we implement RTTI, then deprecated `getInstance()` method, use `engine->getSubsystem()` instead.

**Comment by dumganhar** [comment]
That's ok for me.

**Comment by stanleyljl** [comment]
> > every object has a type information, or should add many get functions to get subsystems
> 
> Yep, need Object RTTI information. Don't need many get functions, since we could use c++ template. Refer to : https://github.com/rbfx/rbfx/blob/master/Source/Urho3D/Core/Context.h#L135

Urho3d‘ s solution is a good candidate.

**Comment by minggo** [comment]
> > > every object has a type information, or should add many get functions to get subsystems
> > 
> > 
> > Yep, need Object RTTI information. Don't need many get functions, since we could use c++ template. Refer to : https://github.com/rbfx/rbfx/blob/master/Source/Urho3D/Core/Context.h#L135
> 
> Urho3d‘ s solution is a good candidate.

Yep, we will use it after we implement RTTI as i said above.
