### ISSUE TITLE
Trigger failure for colider in PhysX mode

### ISSUE THREAD

**Issue by jianglixin85** [cocos/cocos-engine#11029]
### Cocos Creator version

3.5.0

### System information

mac editor

### Issue description

Details can be seen in the post, and there are reproducible demos in the post
https://forum.cocos.org/t/topic/135347

### Steps to reproduce

There are two rigid bodies A and B, if isTrigger is checked at the same time then the onTriggerEnter function will not be triggered, if only one is checked then it will be triggered normally

**Comment by SantyWang** [comment]
![企业微信截图_16522574274438](https://user-images.githubusercontent.com/15109777/167999457-f23209f6-294e-40af-bd55-ae98ade5915e.png)
The events between triggers are completely removed in physX after version 3.5

We are using Physx 4.0
