### ISSUE TITLE
vsync & max frame rate setting for all platforms

### ISSUE THREAD

**Issue by stanleyljl** [cocos/cocos-engine#11039]
### Use Case

Two use cases:
1, Set by developers via code
2, Set directly in the cocos-creator

### Problem Description

We need two interfaces to control vsync and max frame rate for all platforms.

### Alternatives Considered

Please support this feature for all platforms.

**Comment by minggo** [comment]
The engine already has the interface to set fps `Root.fixedFPS()`. This function may rename to `Root.setMaxFps()`. About vsync setting, we should do some research if all platforms support it.
