### ISSUE TITLE
A optimization point about v8 Object.cpp, will affect framerate drop

### ISSUE THREAD

**Issue by oahc09** [cocos/cocos-engine#11041]
### Use Case

Profile game's fps, use android profiler to check the code cpu consume time.

### Problem Description

In Object::init

if (__objectMap) {
	CC_ASSERT(__objectMap->find(this) == __objectMap->end());
	__objectMap->emplace(this, nullptr);
}

we can find the _objectMap's size will increase with engine run, this will make map->find consume more time, and fps will drop.

This is the size statistics log:
Cocos: 14:37:26 [INFO]: [v8.Object.cpp]__objectMap' size is 7775
Cocos: 14:38:20 [INFO]: [v8.Object.cpp]__objectMap' size is 12959
Cocos: 14:39:24 [INFO]: [v8.Object.cpp]__objectMap' size is 21368
Cocos: 14:40:50 [INFO]: [v8.Object.cpp]__objectMap' size is 32787
Cocos: 14:44:20 [INFO]: [v8.Object.cpp]__objectMap' size is 56467
Cocos: 14:46:42 [INFO]: [v8.Object.cpp]__objectMap' size is 72840

### Alternatives Considered

Keep __objectMap's size stable or remove the find logic

**Comment by PatriceJiang** [comment]
`__objectMap` is an instance of `std::unordered_map` and the Complexity of `find` is `O(1)` which should not be the bottleneck. 

Would you pls upload the profiling data or screen capture

**Comment by oahc09** [comment]
> Object

yes, find is o(1) , i didn't notice before
i write some code to test
pc c++14 test release mode:
map 10,000 size find consume time is 100 ns
map 50,000 size find consume time is 0 ns
map 100,000 size find consume time is 100 ns
map 1000,000 size find consume time is 100 ns
map 10000,000 size find consume time is 0 ns

time is not always 0 ns, sometime is 100ns

below screen shot is android cpu profile about unordered_map find/emplace time, it not stable

i think __objectMap's size better not to keep growing indefinitely

![mapfind](https://user-images.githubusercontent.com/4092367/171371114-68b565bd-bc5a-4fda-946f-cee1760eddda.PNG)

**Comment by PatriceJiang** [comment]
I have noticed that the execution time of these functions is relatively low. I don't think optimization is needed at present.

> we can find the _objectMap's size will increase with engine run, this will make map->find consume more time, and fps will drop.

And I suppose frame dropping may be caused by other reasons

**Comment by oahc09** [comment]
> I have noticed that the execution time of these functions is relatively low. I don't think optimization is needed at present.
> 
> > we can find the _objectMap's size will increase with engine run, this will make map->find consume more time, and fps will drop.
> 
> And I suppose frame dropping may be caused by other reasons

ok，this issue can be closed firstly, thks for reply.
