### ISSUE TITLE
particle has residual shadow under specific conditions

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#11056]
### Cocos Creator version

3.5.0

### System information

web-mobile, window

### Issue description

after particle node'parent remove from his parent node, then wait a second, re-add to parent node, particle  will show the last time render status when render new first frame.

### Steps to reproduce

[test.zip](https://github.com/cocos/cocos-engine/files/8683906/test.zip)

click reset button, and wait the first frame show of particle, the first frame is uncorrect.
![1652412773(1)](https://user-images.githubusercontent.com/8321365/168206071-e214a1b7-d49e-4631-b091-ff35ad1a56e2.png)

![image](https://user-images.githubusercontent.com/8321365/168220607-f41d619b-f0f0-40b4-8d45-68296f16a5d8.png)

**Comment by zxx43** [comment]
pr https://github.com/cocos/cocos-engine/pull/11066
