### ISSUE TITLE
3.5.0 Make Android Chome OS (x86, x86_64) failed!

### ISSUE THREAD

**Issue by gitignorekun** [cocos/cocos-engine#11058]
### Cocos Creator version

3.5.0

### System information

Windows 10 Editor, Android Build Chome OS (x86, x86_64) 

### Issue description

![image](https://user-images.githubusercontent.com/81616993/168210992-25ed664b-8401-473c-a891-b5a0e0c72791.png)
![image](https://user-images.githubusercontent.com/81616993/168211037-efb6b877-63cb-4fff-a7f6-78711f197dea.png)
![image](https://user-images.githubusercontent.com/81616993/168211114-f8df6208-df85-4f71-a926-c80ecbf04e78.png)

### Relevant error log output

![image](https://user-images.githubusercontent.com/81616993/168211259-88e39743-d911-4105-b165-9e9a94b145e2.png)

### Steps to reproduce

1. Create a project in Cocos Creator v3.5.0
2. Build Android with APP ABI: x86, x86_64
3. Wait a few minutes until build success
4. Click Make button

**Comment by minggo** [comment]
@gitignorekun what's Android Chrome OS?

**Comment by bofeng-song** [comment]
@gitignorekun  

Compiling libuv with a higher version of NDK will appear  __ stack_ chk_ fail_local  error that does not exist
You can try the following methods
1.  choose lower ndk version, such as 21
2. try to add back the missing function, you can refer to this link https://stackoverflow.com/questions/64679192/undefined-reference-to-stack-chk-fail-local
