### ISSUE TITLE
Review texture cube import and build format, allow compression and reduce package size

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#11077]
Reported https://forum.cocos.org/t/topic/135475

Related https://github.com/cocos/3d-tasks/issues/10900

1. Review the current process and ability
2. Make sure build process can generate accurate and compact texture cube formats, and user controllable

**Comment by jk20012001** [comment]
![image](https://user-images.githubusercontent.com/15099632/168410563-56308e6f-90a6-4b99-8bb1-647b543ae13f.png)
use zlib for lossless compression
quality must be set to 100, keep RGBE data precision

**Comment by xubing0906** [comment]
The current compression level is already the fastest.
![企业微信截图_16527854862328](https://user-images.githubusercontent.com/49358166/168797274-8172f358-3c75-403c-8053-e9d5e2a1cb4f.png)
For example image size 1024*51 51KB jpg format，compressionLevel = 0 total size of 6 pictures is 1.5MB，compressionLevel = 9 the size is 405 KB.
If use JPG format to generate six sides，the total size is 25.6KB.
