### ISSUE TITLE
cc.Node decorator is not shown in inspector

### ISSUE THREAD

**Issue by attolee** [cocos/cocos-engine#11082]
### Cocos Creator version

3.4.1

### System information

Windows 11 Editor

### Issue description

```
@property({ type: Node })
node: Node = null;
```

this decorator can't shown in inspector when named it as `node`.

[more infomation here.](https://forum.cocos.org/t/topic/134918/3)

### Steps to reproduce

Just name it as `node`, then check the inspector.

### Minimal reproduction project

[decorator-test.zip](https://github.com/cocos/cocos-engine/files/8692317/decorator-test.zip)

**Comment by jareguo** [comment]
Sorry, node is the inherited propery of Component. You would see some warning when re-declaring an existing property.
