### ISSUE TITLE
Test code coverage optimization

### ISSUE THREAD

**Issue by SantyWang** [cocos/cocos-engine#11092]
Many of our current unit tests have low code coverage and cannot guarantee that the engine works properly under various boundary cases. Code coverage evaluation needs to be introduced to guide the writing of test cases afterwards.

* Investigate the tools that can evaluate code coverage
* Try to integrate into the **ci pipeline** and **auto test framework**
* Specify code coverage requirements

**Comment by LIUYIa** [comment]
Rough testing using Chrome DevTools tool shows that the current cocos-test-projects code coverage is about 70%. The automation test development team will then plan specific features for precise testing.
