### ISSUE TITLE
Restart engine will crash

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#11106]
How to reproduce:
- use latest cocos-engine codes with v3.6.0
- run 3d test case `Restart`
- will crash on macOS

![WeChatWorkScreenshot_39b1be7a-3b12-4b22-9644-6054af3e076a](https://user-images.githubusercontent.com/488203/168514543-ea0f5ee3-f2dc-4381-8b2d-8a5387f03acf.png)

I think it may crash on all platforms.

**Comment by novain1102** [comment]
![WXWorkCapture_16527815749728](https://user-images.githubusercontent.com/18634782/168785597-73b87eab-391b-4ef2-ab3b-6800e1ad299f.png)
Also crash on windows. Debug Info shows Resrouce leaded in Pass.cpp

**Comment by novain1102** [comment]
<img width="1945" alt="wecom-temp-a4a43b00b2088d8aee91995644cec798" src="https://user-images.githubusercontent.com/18634782/168791719-30d94cdc-265b-41aa-8ee8-9577337918bd.png">
Remove gfx::DeviceManager::destroy() logic restart run well. Need to figure out why we add this logic

**Comment by minggo** [comment]
> Remove gfx::DeviceManager::destroy() logic restart run well. Need to figure out why we add this logic

Can refer https://github.com/cocos/cocos-engine/issues/11124. But it indicates that some gfx objects are not deleted, which causes memory leak. Should fix the memory leak.
