### ISSUE TITLE
Low performance feedback

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#11129]
### Cocos Creator version

3.5.0

### System information

iphone6

### Issue description

Test with 100 box, FPS the down to 42FPS in wechat mini game. 
![image](https://user-images.githubusercontent.com/8321365/168942983-12ce09d9-dff3-4ba9-902a-3318a873763d.png)

### Steps to reproduce

a simple demo to reproduce.
[Performance.zip](https://github.com/cocos/cocos-engine/files/8712774/Performance.zip)

**Comment by troublemaker52025** [comment]
![图片](https://user-images.githubusercontent.com/20809296/195570297-01bd527b-5771-4595-a7a1-9a78b61a905b.png)

**Comment by troublemaker52025** [comment]
![图片](https://user-images.githubusercontent.com/20809296/195570345-5551631c-3075-473f-8328-c72c73e56fa9.png)

**Comment by troublemaker52025** [comment]
在 iPhone se 上测试   帧率有提高

**Comment by pandamicro** [comment]
We need more precise data on the performance difference to evaluate, please test on different mobile devices and platforms, test cases should include this simple one and a complex one.

**Comment by troublemaker52025** [comment]
# performance scene

## v3.5.0 performance

|     | web-moblie | wechat mini game | Android(release) | ios |
|  ---- | ---- | ---- | ---- | ---- |
| Mi 6 | 60 fps | 58 fps | 60 fps |  |
| iphone 6 | 60 fps | 42 fps |  | fps |
| iphone se | 60 fps | 38 fps |  | 60 fps |

---

## v3.7.0 performance

|     | web-moblie | wechat mini game | Android(release) | ios |
|  ---- | ---- | ---- | ---- | ---- |
| Mi 6 | 60 fps | 58 fps | 60 fps |  |
| iphone 6 | 60 fps | 54 fps ⬆️ |  | fps |
| iphone se | 60 fps | 52 fps ⬆️ |  | fps |

**Comment by troublemaker52025** [comment]
# sponza scene

## v3.5.0 preformance

|     | web-moblie | wechat mini game | Android(release) | ios |
|  ---- | ---- | ---- | ---- | ---- |
| Mi 6 | 17 fps | 13 fps | 13 fps |  |
| iphone 6 | 5 fps | 5 fps |  | fps |
| iphone se | 3 fps | 4 fps |  | fps |

---

## v3.7.0 preformance

|     | web-moblie | wechat mini game | Android(release) | ios |
|  ---- | ---- | ---- | ---- | ---- |
| Mi 6 | 20 fps | 12 fps | 15 fps |  |
| iphone 6 | 15 fps ⬆️ | 6 fps |  | fps |
| iphone se | 16 fps ⬆️ | 4 fps |  | fps |

**Comment by jk20012001** [comment]
Mi 6这种机子应该是支持uniform分支的, 所以改成宏分支的提升不大, 但是低端机提升很大

**Comment by troublemaker52025** [comment]
我们的mac机器上的xcode 与 iphone 测试机的版本不匹配。等待mac机器更新到最新的xcode 版本再继续验证ios

**Comment by pandamicro** [comment]
What's the tested case ?
