### ISSUE TITLE
Does it need to delete gfx device when doing restart javascript vm?

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#11124]
Now `Engine::restartVM()` will destroy and delete gfx device. Is it needed? If not delete the gfx device, will it cause memory leak? Especially GPU memory leak.

**Comment by dumganhar** [comment]
When script engine restarts, all GFX binding objects must get collected by GC, the relevant c++ GFX objects must be destroyed. In this case, whether to delete GFXDevice will make no much differences, it is just the case of whether to reuse GFXDevice instance.

> If not delete the gfx device, will it cause memory leak?

So if there are memory leaks, they need to be fixed.

**Comment by star-e** [comment]
If some part of native engine is not destroyed, and these parts hold some gfx objects. Then GFXDevice shall not be destroyed.

**Comment by minggo** [comment]
Can not make sure if any object holds gfx object until invoke `DeviceValidator::doDestroy()`. So may be move the logic to another function to check GPU memory leak?

**Comment by minggo** [comment]
Can not make sure if any object holds gfx object until invoke `DeviceValidator::doDestroy()`. So may be move the logic to another function to check GPU memory leak?

**Comment by star-e** [comment]
> Can not make sure if any object holds gfx object until invoke DeviceValidator::doDestroy(). So may be move the logic to another function to check GPU memory leak?

Yes, gfx need to provide these statistics.

**Comment by minggo** [comment]
@holycanvas does TS engine destroy all GPU resources before restarting?

**Comment by SantyWang** [comment]
> @holycanvas does TS engine destroy all GPU resources before restarting?

For now, it's not. In the long term, I think it depends on how we define ***restarting***，If we want to achieve the cleanest reboot, then I think we need to go through the destruction of all the modules and then go through the boot process again, not just restart the virtual machine

**Comment by minggo** [comment]
> > @holycanvas does TS engine destroy all GPU resources before restarting?
> 
> For now, it's not. In the long term, I think it depends on how we define _**restarting**_，If we want to achieve the cleanest reboot, then I think we need to go through the destruction of all the modules and then go through the boot process again, not just restart the virtual machine

Then what's the difference between restart VM and re-launch application?

**Comment by SantyWang** [comment]
> Then what's the difference between restart VM and re-launch application?

Oh，I'm talking about restarting, not just restart VM. For restart vm, I don't think it's necessary to clean up the gfx device

**Comment by minggo** [comment]
@holycanvas the implementation of `game.restart()` is `engine::restartVM()`. So we should define the behavior of `game.restart()` first. If it equals to re-launch, then should try to do re-launch operation instead restart VM. If operation system doesn't support the operation, then do simulator, like current implementation.

**Comment by minggo** [comment]
https://github.com/cocos/cocos-engine/issues/11162 will refactor game.restart(). Current implementation may need on some platforms. But do not have to delete device.
