### ISSUE TITLE
Add native public API documentations

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#11135]
Currently there is no doc about how to use jsb APIs, they are absolutely needed for native development. The missing content include but not limited to 

1. Application
2. FileUtils
3. PAL related APIs
4. Native Events
5. Network

@minggo please give a complete list and assign the tasks

Either we create manual docs which describes briefly all the APIs, or we generate all native APIs from JS Binding tools and make them available in API docs

**Comment by minggo** [comment]
Ok, i will check which module is needed and suitable to be public in v3.6.0 for native developers.

**Comment by minggo** [comment]
And should check if anything is available in ts, but missing documentation.

**Comment by minggo** [comment]
JSB related documentation:
- [x] FileUtils(should check if some api missed) @qiuguohua 
- [x] jsb.copyTextToClipboard @qiuguohua 
- [x] jsb.zipUtils @mmyduckx 
- [x] jsb.garbageCollect @PatriceJiang 
- [x] reflection @timlyeee 
- [x] AssetsManager @PatriceJiang 

Where and how to write the API doc @PPpro

**Comment by dumganhar** [comment]
JSB related documentation:

jsb.onError
jsb.garbageCollect
jsb.copyTextToClipboard
jsb.saveByteCode
jsb.zipUtils

**Comment by dumganhar** [comment]
Should `EventDispatcher` be public for native developers?

**Comment by minggo** [comment]
> Should `EventDispatcher` be public for native developers?

If not, then how to listen some events in c++? Some application may do some operations based on these events in C++.

> jsb.onError
jsb.copyTextToClipboard
jsb.saveByteCode

Does engine have these features?

**Comment by dumganhar** [comment]
> If not, then how to listen some events in c++? Some application may do some operations based on these events in C++.

Why do developers need to write event registration code by C++ ? In general, he should do it in JS to subcribe `touch`, `mouse`, `background`, `foreground` ... events.  I think `EventDispatcher` should be private now and it should be only used for dispatching events to JS or interactive with other internal modules.

> Does engine have these features?

Yes, I found some code like :
```objective-c
void SystemWindow::copyTextToClipboard(const std::string &text) {
    NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
    [pasteboard clearContents];
    NSString *tmp = [NSString stringWithCString:text.c_str() encoding:NSUTF8StringEncoding];
    [pasteboard setString:tmp forType:NSPasteboardTypeString];
}
```

**Comment by minggo** [comment]
> Why do developers need to write event registration code by C++ ? In general, he should do it in JS to subcribe touch, mouse, background, foreground ... events. I think EventDispatcher should be private now and it should be only used for dispatching events to JS or interactive with other internal modules.

It is ok not be public currently.

Yep, we should add docs for `copyTextToClipboard ` .

**Comment by minggo** [comment]
@PPpro please describe where and how to write the API.

**Comment by PPpro** [comment]
docs added https://github.com/cocos/3d-tasks/blob/master/api-docs/native-binding-api.md
related PR https://github.com/cocos/cocos-engine/pull/11478

**Comment by qiuguohua** [comment]
https://github.com/cocos/cocos-engine/pull/11830

**Comment by PPpro** [comment]
we also need to update the mannual docs @minggo 
- [x] https://docs.cocos.com/creator/manual/zh/advanced-topics/js-java-bridge.html?h=%E5%8F%8D%E5%B0%84 @timlyeee 
- [x] https://docs.cocos.com/creator/manual/zh/advanced-topics/js-oc-bridge.html @timlyeee 
- [x] https://docs.cocos.com/creator/manual/zh/advanced-topics/jsb-bridge-wrapper.html @timlyeee 
- [x] https://docs.cocos.com/creator/manual/zh/advanced-topics/hot-update-manager.html @PatriceJiang
