### ISSUE TITLE
director.pause() stops UI animations from working correctly

### ISSUE THREAD

**Issue by mrtzd** [cocos/cocos-engine#11144]
### Cocos Creator version

3.5.0, 3.4.2

### System information

Windows 10 Editor

### Issue description

`director.pause()` should not stop the UI animations (like button scale transition) from working. Right now it's not possible to use the "Scale Transition" for UI buttons in a pause menu even though the "Sprite Transition" still works. 
Is there any other method to pause the game's logic without breaking UI elements?
Thanks

### Steps to reproduce

Simply call the `director.pause()` method inside the game and then click on some buttons that use the "Scale Transition" mode.

**Comment by minggo** [comment]
If doing like this, it will break compatibility.
