### ISSUE TITLE
the description  of `enableCulling` in  `creator.d.ts` is wrong

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#11161]
### Cocos Creator version

2.4.9

### System information

all

### Issue description

the CCTiledMap's `enableCulling` should be  setter & getter
```
set enableCulling(value: boolean): void;
get enableCulling(): boolean;
```

the CCTiledLayer's `enableCulling` should be :
```
enableCulling(value: boolean): void;
```

I think the CCTiledLayer also should use setter &  getter  (but need to change the source code).

### Steps to reproduce

please open the creator.d.ts file and  engine's source code, r then ead them.

**Comment by zhakesi** [comment]
2.4.12 will merge
* https://github.com/zhakesi/engine/commit/94105f04f591b1e53afd934bb5bb32e4bb134893
