### ISSUE TITLE
game.restart() in native

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#11162]
The meaning of `game.restart()` is to exit an app and re-launch it again. Current implementation just restarts the JS VM, should fix the behavior. 
- android: @bofeng-song 
- iOS/macOS @mmyduckx 
- windows @timlyeee

**Comment by dumganhar** [comment]
For compatibility, is it better to add a new function called `game.restartApp()` for re-launching app. And continue to keep `game.restart()` to be just restarting js vm but deprecate it and add a new function called `game.restartScriptVM()`.

**Comment by minggo** [comment]
> add a new function called game.restartScriptVM()

Is there any reason to have a function to just restart JS VM?

**Comment by dumganhar** [comment]
> Is there any reason to have a function to just restart JS VM?

It may be used after hot-updating JS code and restart JS VM for all platforms.

Some platforms may not support to restart application.

**Comment by minggo** [comment]
> It may be used after hot-updating JS code and restart JS VM for all platforms.

It is a new request. We can create another issue.

> Some platforms may not support to restart application.

If so, then try to simulate the behavior as possible.

**Comment by dumganhar** [comment]
> If so, then try to simulate the behavior as possible.

So for the platform that doesn't support the true restartApp, engine has the responsibility to implement it by restartScriptVM?

**Comment by minggo** [comment]
Yep, as the function is provided by engine.

**Comment by novain1102** [comment]
> There is no private or public API that can be executed as mobile from inside of an app. It's annoying, but that's truth

It seems NO restart API to exit an app and re-launch it again in iOS

in macOS, restart instructions may be like this:
```Objective-C
let path = NSBundle.mainBundle().resourcePath!.stringByDeletingLastPathComponent.stringByDeletingLastPathComponent
let task = NSTask()
task.launchPath = "/usr/bin/open"
task.arguments = [path]
task.launch()
exit(0)
```

**Comment by minggo** [comment]
> It seems NO restart API to exit an app and re-launch it again in iOS

Can use exit function to exit. Is there a function to re-launch it?

**Comment by minggo** [comment]
As not all platforms support re-launch application, so use the same way. I just deleted and re-created all resources as possible in https://github.com/cocos/cocos-engine/pull/11301
