### ISSUE TITLE
can not set target api when build.

### ISSUE THREAD

**Issue by sfzhanglimin** [cocos/cocos-engine#11172]
### Cocos Creator version

3.4.2-3.5.0

### System information

android

### Issue description

already set target api to 31 .
but the PROP_COMPILE_SDK_VERSION version still 28 when build.

### Steps to reproduce

already set target api to 31 .
but the PROP_COMPILE_SDK_VERSION version still 28 when build.

**Comment by bofeng-song** [comment]
@sfzhanglimin 
This PR(https://github.com/cocos/cocos-engine/pull/10627) has been fixed this problem.
Please refer to the previous PR.
