### ISSUE TITLE
shadow map shader if performance optimize

### ISSUE THREAD

**Issue by jk20012001** [cocos/cocos-engine#11178]
We use if to enable shadow calculations, if can be translated to uniform dynamic branch or static branch. There is an obvious performance cost with static branch. So we should use macro instead of if to solve this, but stucking will occur when user changing UI.

1. PCFType should use CC_DIR_SHADOW_PCF_TYPE instead of cc_shadowWHPBInfo.z
2. Use CC_ENABLE_DIR_SHADOW instead of cc_mainLitDir.w, when dir light is valid and dir shadow is enabled.
3. Use CC_USE_CASCADED_SHADOW instead of cc_shadowLPNNInfo.w, when CSM is used
spot shadows are batched processing, so can not use macro to toggle On/Off and PCFType

**Comment by troublemaker52025** [comment]
* https://github.com/cocos/cocos-engine/pull/12368
