### ISSUE TITLE
[v3.6] Memory leaks

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#11221]
![Screen Shot 2022-05-25 at 15 42 32](https://user-images.githubusercontent.com/493372/170208375-367c9448-85ef-4e63-9054-d90528be1012.png)

**Comment by novain1102** [comment]
remaining memory leak after merge above pr: 
<img width="1853" alt="image" src="https://user-images.githubusercontent.com/18634782/170685298-94927e3c-ff4b-475d-bd0d-f35063b80c75.png">

**Comment by oahcy** [comment]
leak point is this line:
![image](https://user-images.githubusercontent.com/9692838/174284871-275f5ed9-b0f7-4c50-90c5-78ed7222d8b8.png)
but i remove subview immediately， it also found this leak ：
![image](https://user-images.githubusercontent.com/9692838/174285067-db681443-7e91-4590-9063-fad6e9a67aee.png)

may check tools wrong？

**Comment by minggo** [comment]
Ok, it seems it is error reporting. Close it.
