### ISSUE TITLE
BoxCollider2D

### ISSUE THREAD

**Issue by hnmli099** [cocos/cocos-engine#11228]
### Cocos Creator version

Creator 版本： <3.4.1>

### System information

Target platform: < IOS / Android >
目标平台： < iOS / Android >

### Issue description

In the [spriteframe] during the animation playback, the size of the collider [boxcollider2d] is dynamically changed, so that the attack judgment can be made only at the time of the attack picture

The following problems are found in the implementation process:

The key is inserted in the animation editor to change the collision volume of the object

在【SpriteFrame】在播放动画过程中，动态的改变碰撞体【BoxCollider2D】的大小，来达到只有在攻击图片的时间才有攻击判定

实现过程发现如下问题：
在动画编辑器中插入了关键这，改变物体的碰撞体积

### Steps to reproduce

Novice has just contacted cocos creator recently

Now, I want to make a requirement that the size of the boxcollider2d is dynamically changed during the animation of the spriteframe, so that the attack judgment can only be made at the time of the attack picture

The following problems are found in the implementation process:

The key is inserted in the animation editor to change the collision volume of the object

Wechat screenshot_ twenty trillion and two hundred and twenty billion five hundred and twelve million one hundred and five thousand seven hundred and fifty-two

Wechat screenshot_ twenty trillion and two hundred and twenty billion five hundred and twelve million one hundred and five thousand seven hundred and fifty-two

one thousand one hundred and fifty-one × 511 35.6 KB

When playing the animation, it is obvious that the collision body changes with the key frame, as shown in the following wechat screenshot_ twenty trillion and two hundred and twenty billion five hundred and twelve million one hundred and five thousand nine hundred and one

Wechat screenshot_ twenty trillion and two hundred and twenty billion five hundred and twelve million one hundred and five thousand nine hundred and one

nine hundred and forty × 404 59.8 KB

However, during the real operation, the collision body did not change. Wechat screenshot_ twenty trillion and two hundred and twenty billion five hundred and twelve million one hundred and five thousand nine hundred and twenty-four

Xiaobai, I don't understand here. I hope you can give me some advice

新手最近刚接触Cocos Creator
现在想做一个需求，就在【SpriteFrame】在播放动画过程中，动态的改变碰撞体【BoxCollider2D】的大小，来达到只有在攻击图片的时间才有攻击判定

实现过程发现如下问题：
在动画编辑器中插入了关键这，改变物体的碰撞体积

微信截图_20220512105752
微信截图_20220512105752
1151×511 35.6 KB

播放动画的时候，是能明显看到碰撞体是随着关键帧变化的，如下微信截图_20220512105901
微信截图_20220512105901
940×404 59.8 KB

但是真正运行的时候，碰撞体并没有发生变化微信截图_20220512105924
小白，这里就不太明白了，希望大佬指点一二

https://forum.cocos.org/t/topic/135404

Creator 版本： <3.4.1>

目标平台： < iOS / Android >

**Comment by lealzhan** [comment]
![Image](https://user-images.githubusercontent.com/9999378/196925562-3aa8d14e-bdbc-486f-8bc5-74fc5215df2b.png)
