### ISSUE TITLE
Use C++ 17

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#11223]
In order to support iOS 10.x, engine can not use C++17. I collected the market share of iOS 10.x through the [web site](https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/worldwide). It seems iOS 10.x 's market share is very low. Using C++ 17 brings some conveniences:
- can use variant
- can use optional
- can use constexpr in if statement which is easy to write codes

**Comment by freeboy** [comment]
can use nested namespaces

**Comment by hana-alice** [comment]
`const auto [x, y, z] = [](){return std::tie{1.0F, 2U, "3"}}` [structure binding](https://en.cppreference.com/w/cpp/language/structured_binding)

**Comment by star-e** [comment]
can use std::string_view

**Comment by PatriceJiang** [comment]
The `if constexpr` can combine a large number of specialized template implementations to reduce the amount of code.

https://www.codingame.com/playgrounds/2205/7-features-of-c17-that-will-simplify-your-code/constexpr-if

**Comment by minggo** [comment]
Already use c++17. But we should add c++17 features carefully in future.
