### ISSUE TITLE
Cocos can only detect dynamic rigid bodies?

### ISSUE THREAD

**Issue by hnmli099** [cocos/cocos-engine#11226]
### Cocos Creator version

2.x

### System information

PhysicsManager.testPoint

### Issue description

PhysicsManager.testPoint use PhysicsAABBQueryCallback，
PhysicsAABBQueryCallback.prototype.ReportFixture = function (fixture) {
var body = fixture.GetBody();
if (body.GetType() === b2.Body.b2_dynamicBody) {
if (this._isPoint) {
if (fixture.TestPoint(this._point)) {
this._fixtures.push(fixture);
// We are done, terminate the query.
return false;
}
}
else {
this._fixtures.push(fixture);
}
}

// True to continue the query, false to terminate the query.
return true;
};

From the above code, we can see that only dynamic rigid bodies can be detected. Why should I write this? What if I want to detect static rigid bodies
从上述代码中看到只能检测动态刚体，为什么要这么写，如果我想检测静态刚体怎么办

### Steps to reproduce

web：https://forum.cocos.org/t/creator-physicsmanager-testpoint/61757

**Comment by lealzhan** [comment]
看起来是box2d自己的测试代码，不是box2d用来判断碰撞的代码
