### ISSUE TITLE
PhysX must find bug

### ISSUE THREAD

**Issue by hnmli099** [cocos/cocos-engine#11227]
### Cocos Creator version

3.4.2

### System information

Native platform or direct simulator operation

原生平台，或者直接模拟器运行

### Issue description

The camera is attached to the player

Players add the capsulecollider component and rigidlybody component

Set player movement through setlinearvelocity

摄像机挂载在玩家身上
玩家添加CapsuleCollider组件和RigidlyBody组件
通过setLinearVelocity设置玩家移动

### Steps to reproduce

Environmental Science:

Native platform or direct simulator operation

Physical engine -physx (no problem in bullet test)

Expected results

The camera should move as the player moves

Actual results

The player moved, but the camera did not move

环境：
原生平台，或者直接模拟器运行
物理引擎-PhysX （ bullet测试没有问题）
预期结果
摄像机应该跟随玩家的移动而移动
实际结果
玩家移动了，但是摄像机未移动
YWYK66H7{(@ETM4B_(K~SJ
YWYK66H7{(@ETM4B_(K~SJ
1648×864 129 KB

https://forum.cocos.org/t/topic/135751

**Comment by lealzhan** [comment]
这是physx原生实现时物理世界和场景的同步的bug，将在近期修复。
This is due to the native physx implementation called inappropriate scene node transform update flag. Will be fixed soon.

**Comment by lealzhan** [comment]
测试了3.6.2的原生实现， 已经没有这个bug了（windows平台）。应该是非物理模块的原生场景同步相关的bug已经修复了。
This is fixed in Cocos Creator 3.6.2.
