### ISSUE TITLE
Wrong compiling project in CocosCreator for Mac (for simulator and browser)

### ISSUE THREAD

**Issue by DrMoriarty** [cocos/cocos-engine#1124]
Hello! I don't know if this issue is engine related, btw I can't find cocos creator repository for reporting this bug.

So, my game project is pretty big and yesterday I noticed very destructive bug in cocos creator for MacOSX. 

When I try to recompile scripts I get the error:

```
SyntaxError: Unexpected token }
```

I'm sure that my scripts are valid. The project can be compiled and ran successfully in cocos creator for windows, the problem exists only for mac.

So, when I tried to run project in simulator I get this error message:

```
Simulator: SyntaxError: syntax error
at a (/Volumes/Transcend/projects/fluffy-dances-dev/fluffy-dances/library/bundle.project.js?009:7533:0)
```

When I inspect the bundle.project.js file I see that it has invalid syntax:

![2016-09-16 11 36 52](https://cloud.githubusercontent.com/assets/1177068/18580069/63f23e0c-7c0a-11e6-8155-3b7ed89f8a6f.png)

As you can see the RemovablePattern module starts in the line which is commented out. This is line 

```
//# sourceMappingURL=data:application/json;charset=utf-8;base64,blablabla
```

I can find several places in file bundle.project.js where the code is corrupted by the same way. For example, one more broken module:

![2016-09-16 11 42 00](https://cloud.githubusercontent.com/assets/1177068/18580178/070e5c7e-7c0b-11e6-9fc6-7dbfaa645f02.png)

I uploaded the full [bundle.project.js](https://dl.dropboxusercontent.com/u/996824/bundle.project.js)  file to dropbox

When I run the project in browser I get the same problem:

![2016-09-16 11 50 37](https://cloud.githubusercontent.com/assets/1177068/18580371/4369a074-7c0c-11e6-9246-cdc7c27aefdf.png)

So, the main question is: how can I disable generating source maps at all? I don't need them for debugging.

**Comment by DrMoriarty** [comment]
PS: I use cocos creator 1.2.1 but the problem was also in creator 1.1.2

**Comment by DrMoriarty** [comment]
I successfully built the previous revision of my game. And I noticed that bundle.project.js has only one sourceMappingURL in the very end of file.

**Comment by jareguo** [comment]
It seems like the EOF of `bundle.project.js` is not placed correctly because the end part of `bundle.project.js` repeated 4 times. This maybe an IO error and I have no idea about it. Did you see any other error before the `SyntaxError`? Do you know how can I do reproduce the bug?

**Comment by DrMoriarty** [comment]
I don't know what exactly was the reason but the bug was gone on. I reinstalled cocos on another drive (the previous one was with case sensitive file system) also I redownloaded my project from git, rebooted my computer several times. And voila!

**Comment by jareguo** [comment]
😂
