### ISSUE TITLE
crypto-es does not work with 3.5.0

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11248]
### Cocos Creator version

3.4.2，3.5.0

### System information

chrome

### Issue description

https://forum.cocos.org/t/topic/135954
![image](https://user-images.githubusercontent.com/40415168/170473187-0c6b7368-5dd9-41eb-8b21-1dc07cd84ade.png)

The crypto-es can be used in 3.4.2 tests.

### Steps to reproduce

https://www.npmjs.com/package/crypto-es
1. npm i crypto-es
2. import CryptoES from 'crypto-es';
3. package.json ->> "type": "module"
4. tsconfig.json ->>  "skipLibCheck": true

![image](https://user-images.githubusercontent.com/40415168/170473929-c2ef2543-ed48-45cc-81c3-79de5514c3f2.png)

**Comment by shrinktofit** [comment]
Fixed by https://github.com/cocos/cocos-editor/pull/320
