### ISSUE TITLE
WeChat mini-game does not support webP format images

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#11261]
### Cocos Creator version

3.3.2

### System information

P30Pro wechat game

### Issue description

Real machine test on WeChat mini-game does not support webP format images, WeChat development tools are normal.

### Steps to reproduce

Test cc.sys.capabilities.webp in Real machine is false.
![企业微信截图_16536457587292](https://user-images.githubusercontent.com/18083506/170687441-8abab83f-c9d4-4898-9ad6-5f96792e0969.png)
In WeChat development cc.sys.capabilities.webp is true.
![企业微信截图_16536458001252](https://user-images.githubusercontent.com/18083506/170687496-87012ac6-2998-432f-971c-18bb831fc5ab.png)
There is a problem with the judgment of this place:
![企业微信截图_16536458442069](https://user-images.githubusercontent.com/18083506/170687542-ca27d41f-2dd1-490a-b28b-9758392cd8de.png)
Here is a demo:
[webp.zip](https://github.com/cocos/cocos-engine/files/8786184/webp.zip)

**Comment by PPpro** [comment]
@yyycggg please take a look whether we need to fix on Android  https://github.com/cocos/cocos-engine/pull/12830
