### ISSUE TITLE
摄像机使用rendertexture时未禁用触摸，导致触摸结果不确定

### ISSUE THREAD

**Issue by zenskcode** [cocos/cocos-engine#11271]
### Cocos Creator version

3.5.0

### System information

windows10

### Issue description

canvas下2个摄像机A、B，A为canvas使用的摄像机，B为rendertexture摄像机，B未禁用触摸，导致触摸结果不确定,影响canvas下触摸操作
类似帖子（5月9日）：
https://forum.cocos.org/t/topic/135198

请问在引擎修复前，我们可以采取什么方式先规避问题，目前影响功能进行

### Steps to reproduce

canvas下存在一个自动创建的摄像机A，copy A得到摄像机B，B使用rt

**Comment by pandamicro** [comment]
@PPpro please check whether user can forbid a camera from being managed by the Input

**Comment by PPpro** [comment]
可以试试合并这个修改，禁用 RT 上的触摸检测

https://github.com/cocos/cocos-engine/pull/11299

**Comment by pandamicro** [comment]
@zenskcode 
If you don't want to modify the engine, you can also temporarily forbid all system events for canvas panel that is rendered on the RenderTexture, use [pauseSystemEvents](https://docs.cocos.com/creator/3.5/api/zh/class/Node?id=pauseSystemEvents) API

```
rootNodeOfCanvas.pauseSystemEvents(true)
```

**Comment by PPpro** [comment]
we've fixed this issue here on v3.6.0, thanks for feedback

https://github.com/cocos/cocos-engine/pull/11299
