### ISSUE TITLE
[ Feature ] Reduce the memory usage of GFXBuffers and mesh arrays.

### ISSUE THREAD

**Issue by timlyeee** [cocos/cocos-engine#11288]
### Use Case

Right now the graphics memory usage is much higher than Unity, as we would draw precisely the same object but with a greater number of triangles, for example, a car with 500,000 triangles. 

The principal cause of it is that we use FLOAT and UNSIGNED_INT to store all data, which is not necessary for normal and UV, as well as a mesh with less than 65535 triangles.

### Problem Description

If we're concentrating on the code, for gles render backend, we shall see the codes to bind buffer is using the same type from the beginning to the end.
```cpp
for (auto &gpuInput : gpuPipelineState->gpuShader->glInputs) {
                    for (size_t a = 0; a < gpuInputAssembler->attributes.size(); ++a) {
                        const GLES3GPUAttribute &gpuAttribute = gpuInputAssembler->glAttribs[a];
                        if (gpuAttribute.name == gpuInput.name) {
                            GL_CHECK(glBindBuffer(GL_ARRAY_BUFFER, gpuAttribute.glBuffer));

                            for (uint32_t c = 0; c < gpuAttribute.componentCount; ++c) {
                                GLuint   glLoc        = gpuInput.glLoc + c;
                                uint32_t attribOffset = gpuAttribute.offset + gpuAttribute.size * c;
                                GL_CHECK(glEnableVertexAttribArray(glLoc));

                                cache->glEnabledAttribLocs[glLoc] = true;
                                GL_CHECK(glVertexAttribPointer(glLoc, gpuAttribute.count, gpuAttribute.glType, gpuAttribute.isNormalized, gpuAttribute.stride, BUFFER_OFFSET(attribOffset)));
                                GL_CHECK(glVertexAttribDivisor(glLoc, gpuAttribute.isInstanced ? 1 : 0));
                            }
                            break;
                        }
                    }
                }
```
The `gpuAttribute.glType` is hesitated.
And according to the editor's behavior, all meshes are using the same type of UINT even if we support drawing elements with USHORT.

### Alternatives Considered

Considering the whole workflow from the editor to the engine, if we can set mesh data type in the editor or we should save it intelligently?

**Comment by timlyeee** [comment]
As it's mentioned before, right now I realize that it all depends on how JS shows the data in mesh.ts, which should be checked first

**Comment by pandamicro** [comment]
@timlyeee It's because the mesh asset is using the specific format for those attributes, the engine itself won't change format settings.

If any optimization applicable to the attribute format, it should be applied during DCC import process.

@shrinktofit please confirm how we created the mesh asset, and how we determine the attribute format. Is there any space to improve the memory usage of mesh asset

**Comment by shrinktofit** [comment]
> @shrinktofit please confirm how we created the mesh asset, and how we determine the attribute format. Is there any space to improve the memory usage of mesh asset

Vertex attribute format is determined by the model file it belongs to. In glTF case, it can be one of the possible formats as specified in https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes-overview . In case of FBX, all attributes are stored as 32 bits floating points except as joint indices are stored as 32 bits unsigned integers.

**Comment by timlyeee** [comment]
Formate Type defined in define.ts, which does not include a type with half_float,
```js
// define.ts
export enum FormatType {
    NONE,
    UNORM,
    SNORM,
    UINT,
    INT,
    UFLOAT,
    FLOAT,
}
```
In fact, in javascript, number is a type for 32bit, which makes no difference between half_float and float.
On Native, all data come from javascript, thus format type keeps the same.
```cpp
const FormatInfo GFX_FORMAT_INFOS[] = {
...
{"RGB16F", 6, 3, FormatType::FLOAT, false, false, false, false},
{"RGB32F", 12, 3, FormatType::FLOAT, false, false, false, false},
}
enum class FormatType : uint32_t {
    NONE,
    UNORM,
    SNORM,
    UINT,
    INT,
    UFLOAT,
    FLOAT,
};
```

Should add one format type a least

**Comment by pandamicro** [comment]
There are three critical point along the way to make sure GPU using more compact layout of data:

1. Importer: FBX and glTF importer should both support choosing suitable data format, for example, using RGB16F for normal or uv attributes when possible. The new formats also need to be defined in FormatType. @AFeiYA 
2. Runtime asset loading: While loading the mesh asset in runtime, we need new types of arrays to store corresponding data format, for example, Float16Array (maybe we can implement it with Uint16Array). @dumganhar 
3. Upload buffer to GPU: Make sure we upload the buffer with correct data format and stride. Need implementation in both TS engine and Cpp Engine @dumganhar 

We need to schedule this into v3.6

**Comment by star-e** [comment]
Different platforms might need different formats. 
For example, some platforms, half(float16) might not be supported.

https://developer.qualcomm.com/sites/default/files/docs/adreno-gpu/developer-guide/gpu/best_practices_vertex.html#:~:text=One%20array%20with%20vertex%20attributes%20and%20other%20attributes,no%20support%20for%20half%20floats%20in%20Vulkan%20shaders.

**Comment by star-e** [comment]
There are also some recommendations on android.

    Compressing vertex position to half-precision 16-bit floats
    Compressing UV texture coordinates to 16-bit unsigned integer ushorts
    Compressing the tangent space by encoding normal, tangent, and binormal vectors using quaternions

https://developer.android.com/agi/frame-trace/vertex-formats

**Comment by dumganhar** [comment]
Need to check `GL_ARB_half_float_vertex` for OpenGLES.

**Comment by dumganhar** [comment]
@pandamicro The changes of optimizing mesh memory in engine were done and merged. We currently support developer to enable converting some formats (uv, normal, tangent) of mesh attribute from `float` to `half` at runtime by setting `CC_OPTIMIZE_MESH_DATA` macro to `1` in Mesh.cpp.

The remaining work is that editor needs to export mesh data with `half` format and index with `ushort` if index is less than 65536.

I unassigned me from this issue.  I will cooperate with @AFeiYA if editor finishes the task.

**Comment by dumganhar** [comment]
OpenGLES2 (webgl1) standard doesn't require to support `half format of vertex attribute`, it's supported by OpenGLES2 extension,  some devices may not support half vertex format data uploaded to GPU.  Therefore, Offline `float to half` vertex attribute data conversion should not be done in `mesh import` stage, it's better to do it in `Project Building` stage and let developer to decide whether to enable this feature.

We need to 
- develop a command line tool for converting mesh data,
- let project building script to invoke the command line tool.

**Comment by pandamicro** [comment]
Related to https://github.com/cocos/3d-tasks/issues/7358

It might also need build time mesh manipulation

@dumganhar we also need to expose CC_OPTIMIZE_MESH_DATA in project settings

**Comment by AFeiYA** [comment]
集成draco，使用draco压缩，可以保证数据的一致性 [issues/7743](https://github.com/cocos/cocos-engine/issues/7743)
