### ISSUE TITLE
CC 3.5.0 - Multiplied Drawcalls for each Canvas

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#11290]
### Cocos Creator version

3.5.0

### System information

Windows 11, Chrome

### Issue description

When you create more Canvas Components, you multiply ALL drawcalls by the number of Canvas components you have in your project, even though the other Canvas or Cameras would not render anything.

I think Canvas / Camera rendering should be separated completely from each other and not affected what is placed in one or in the other.

This completely ruins the possibilities to use multiple canvas/camera combinations in a scene, because it will always double the performance requirements, which is very bad.

### Steps to reproduce

**1 Canvas:**
- Create 1 Canvas / Camera combination
- Add a sprite frame
- Launch the game
- Check drawcalls
- It creates 1 drawcall which is correct (it says 2 because the stats chart causes 1 drawcall which is fine)
![image](https://user-images.githubusercontent.com/7983358/171052520-7090070e-ba3a-4e0f-9002-1b589221bd46.png)
![image](https://user-images.githubusercontent.com/7983358/171052584-b88eeed1-37f5-413d-9146-2ca0d0bc4bcf.png)

**2 Canvas:**
- Add an empty Canvas / Camera combination in the same scene
- Check Drawcalls
- For some reason you now doubled your drawcalls (from 1 to 2, stats drawcall is not doubled)
- Should be 2 Drawcalls still.
![image](https://user-images.githubusercontent.com/7983358/171052677-a9a49709-fa77-483d-8bae-c48cffa4e8ee.png)
![image](https://user-images.githubusercontent.com/7983358/171052767-584c6210-b55f-4fc1-94bd-2afeb4dde7c8.png)

**1 Canvas -  5 Assets**
- With 1 Canvas and 5 assets like the image below you should be causing in development 5 drawcalls + 1 drawcall from the stats = 6 drawcalls
![image](https://user-images.githubusercontent.com/7983358/171053071-7ebecb43-2741-4a33-84db-97683c3588ed.png)

**2 Canvas -  5 Assets in ONE canvas**
- Just add an empty canvas and watch the drawcalls double 5(assets) * 2(canvas) = 10 drawcalls + 1 from stats = 11
![image](https://user-images.githubusercontent.com/7983358/171053200-37641923-1a70-4a8f-9e14-5b040ff558d4.png)
![image](https://user-images.githubusercontent.com/7983358/171053245-af854fd9-6457-4293-b8d8-09478b5c2b98.png)

**Split up the 5 assets between the 2 canvases:**
- Still causes 11 drawcalls like previous. Both canvases draws all the assets and this is the problem.
![image](https://user-images.githubusercontent.com/7983358/171053327-a9e649ed-255f-4292-b40a-c57569366b1e.png)
![image](https://user-images.githubusercontent.com/7983358/171053361-e404a04e-dd62-4a8b-8e6b-c9f134a5908e.png)

**Add 5 Total Canvases with 5 Assets**
- You would expect from 5 assets, 5 drawcalls in this example but what you get is 5 * 5 = 25 drawcalls + 1 from stats = 26.
![image](https://user-images.githubusercontent.com/7983358/171053471-c3d7650b-b2fb-4cf4-968d-d358f3752603.png)
![image](https://user-images.githubusercontent.com/7983358/171053492-4c8dd947-aa85-4d70-aa8b-d17aef210764.png)

### Minimal reproduction project

[drawcall-test.zip](https://github.com/cocos/cocos-engine/files/8800571/drawcall-test.zip)

**Comment by pandamicro** [comment]
Hi, the reason for that is your project have all node set to DEFAULT layer and all cameras set to see DEFAULT layer

![截屏2022-05-31 上午10 19 09](https://user-images.githubusercontent.com/632460/171079979-ff3de705-27b1-470e-8fbc-bacc5a3fb39f.png)

If you want to use multiple Canvas (contains multiple camera), you can either use only one camera to capture them all, or manage nodes layer and Camera visibility to reduce draw call.

Please read this doc for details: https://docs.cocos.com/creator/manual/en/editor/components/camera-component.html#camera-group-rendering

I will close this issue because it's the correct behavior

**Comment by Ronsku** [comment]
Yeah, thanks! I figures this out later, it all makes sense! 💪 Should have closed the ticket :)
