### ISSUE TITLE
[3.5.0] When vulkan + swappy is checked in the Android platform build, the game retires to the background and returns to the foreground with a black screen

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#11311]
### Cocos Creator version

3.5.0

### System information

android 12，redmi k40

### Issue description

https://forum.cocos.org/t/topic/135980

![图片](https://user-images.githubusercontent.com/35944775/171152880-d88781e0-d354-4c74-9d8c-a502a56e6e48.png)

### Steps to reproduce

1、Create a new HelloWorld project, then open the build panel and select the android platform. Then check the configuration options as shown below. （创建一个新的HelloWorld项目，然后打开构建面板，选择Android平台。然后检查配置选项，如下图所示。）
![图片](https://user-images.githubusercontent.com/35944775/171154131-ae781349-b16c-4368-b413-8e7297b8b6b5.png)
2、Then build the release and test run it on a real machine.（然后构建发布，并在真机上测试运行。）
3、Switch the game to the background and return to the foreground afterwards.（将游戏切换到后台，之后再回到前台。）
4、Check if the game will black screen. Black screen means the game appears abnormal.（检查游戏是否会黑屏。黑屏意味着游戏出现异常。）

**Comment by ashleylin97** [comment]
We can reproducible this problem by this phone.
中兴ZTE Axon30 | Android 11 | 8GB+128GB | Snapdragon 870

**Comment by pandamicro** [comment]
If user encounter this issue, please ask them to switch off Swappy temporarily
