### ISSUE TITLE
Rigid body rotation not synchronized to node 刚体旋转未同步到node

### ISSUE THREAD

**Issue by hnmli099** [cocos/cocos-engine#11329]
### Cocos Creator version

cocoscreator 3.4.0

### System information

chrome

### Issue description

Reproduction method: add 2D rigid body and collision body to the picture. When the rigid body changes its rotation under the influence of the physical system, use node Rotation obtains the rotation angle. The resulting angle is the same as the initial angle of the object and is inconsistent with the current rigid body angle

First error:

Which previous version was normal:

Phone model:

Mobile phone browser:

Editor operating system: win10

Recurrence probability: 100%

重现方式：给图片加上2d刚体和碰撞体，刚体受物理系统影响改变旋转时，通过node.rotation获得旋转角度，结果角度和物体初始角度一样与当前刚体角度不符.

首个报错：

之前哪个版本是正常的：

手机型号：

手机浏览器：

编辑器操作系统： win10

重现概率： 100%

### Steps to reproduce

https://forum.cocos.org/t/topic/128497

**Comment by lealzhan** [comment]
Creator3.7中测试没有这个问题。
![image](https://user-images.githubusercontent.com/9999378/207286529-07b03165-cc08-48ef-8feb-3d4c8d72b4a5.png)
