### ISSUE TITLE
Touch Event adaptation issues on WeChat Mini Program

### ISSUE THREAD

**Issue by jareguo** [cocos/cocos-engine#11330]
In the forum, there are many touch-end related issues when running in the webview of WeChat Mini Program.
It seems all of them are caused by the same problem and only raise in WeChat DevTools, not real device. Could be fixed by using
```
window.navigator.msPointerEnabled = true
```

Please verify and fix in 2.x/3.x.

See
https://forum.cocos.org/t/topic/103840
https://forum.cocos.org/t/touchend/62783
https://forum.cocos.org/t/h5-web-view/71943
https://forum.cocos.org/t/cocoscreator/68553

**Comment by PPpro** [comment]
fixed on 2.x, 
3.x doesn't encounter this issue
