### ISSUE TITLE
No response from force to rigid body  力到刚体上无响应

### ISSUE THREAD

**Issue by hnmli099** [cocos/cocos-engine#11331]
### Cocos Creator version

2.4.5

### System information

 simulator

### Issue description

Reproduction method: for a rigidbody component, call its applyforcetocenter() to apply a force to the center of mass on the rigid body. Change the mass attribute of rigidbody, and the acceleration of rigidbody does not change

First error: no error

重现方式：对一个RigidBody组件，调用其 applyForceToCenter （）施加一个力到刚体上的质心上。改变rigidbody的mass属性，rigidbody的加速度没有变化

首个报错：没有报错

### Steps to reproduce

https://forum.cocos.org/t/topic/127284

**Comment by lealzhan** [comment]
在设置完collider2d的mass属性之后，再调用下collider2d的apply()函数应该就可以了
![image](https://user-images.githubusercontent.com/9999378/207528682-c4e4f89c-1e85-40e0-b47d-00b1f5c545ec.png)
