### ISSUE TITLE
2D物理 改变了节点的scaleX导致碰撞触发错误

### ISSUE THREAD

**Issue by hnmli099** [cocos/cocos-engine#11343]
### Cocos Creator version

cocos creator v2.4.0

### System information

cocos creator

### Issue description

When using physical collision, the two objects are still in contact, but changing the direction will trigger onbegincontact and onendcontact repeatedly.

在使用物理碰撞的时候，两个物体还在接触阶段，但是改变方向却会重复触发onBeginContact和onEndContact。

如图：

Kapture 2020-08-12 at 1.34.26.gif

会出现这种情况的原因是改变了节点的 scaleX。（这个应该是BUG吧？）

代码：

const { ccclass, property } = cc._decorator;

@ccclass
export default class NewClass extends cc.Component {

    _body;

    start() {
        this._body = this.getComponent(cc.RigidBody);
        this._body.enabledContactListener = true;
        // 测试绘制
        cc.director.getPhysicsManager().debugDrawFlags = cc.PhysicsManager.DrawBits.e_aabbBit |
            cc.PhysicsManager.DrawBits.e_jointBit |
            cc.PhysicsManager.DrawBits.e_shapeBit
            ;

        cc.systemEvent.on(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown, this);
        cc.systemEvent.on(cc.SystemEvent.EventType.KEY_UP, this.onKeyUp, this);
    }

    onBeginContact(contact, selfCollider, otherCollider) {
        cc.log("接触物体");
    }

    onEndContact(contact, selfCollider, otherCollider) {
        cc.log("离开物体");
    }

    onKeyDown(event: cc.Event.EventKeyboard): void {
        switch (event.keyCode) {
            case cc.macro.KEY.left:
            case cc.macro.KEY.d:
                this.moveCtrl(1);
                break;
            case cc.macro.KEY.right:
            case cc.macro.KEY.a:
                this.moveCtrl(-1);
                break;
        }
    }

    onKeyUp(event: cc.Event.EventKeyboard): void {
        let v = this._body.linearVelocity;
        v.x = 0;
        this._body.linearVelocity = v;
    }

    moveCtrl(direct: number) {
        let v = this._body.linearVelocity;
        v.x = 300 * direct;
        this._body.linearVelocity = v;

        // 问题所在：改变水平翻转时，会触发onEndContact和onEndContact，实际上两个物体还是接触状态
        this.node.scaleX = direct;

        cc.log("移动：" + direct);
    }
}

### Steps to reproduce

https://forum.cocos.org/t/bug/96919

**Comment by lealzhan** [comment]
[碰撞检测回调函数重复执行了怎么解决](https://forum.cocos.org/t/topic/112878)

**Comment by lealzhan** [comment]
改变节点Scale后，该节点下的Shape会销毁后重新生成。这个导致了碰撞触发的错误。
![image](https://user-images.githubusercontent.com/9999378/207018423-653366c0-c7b2-47c0-8a66-d0e4a4f38f5f.png)

**Comment by lealzhan** [comment]
2d物理的碰撞回调处理设计存在不少问题，需要要重新设计一下。
