### ISSUE TITLE
When the sensor property is false, onpresolve cannot be executed normally  sensor属性为false时，无法可正常执行onPreSolve

### ISSUE THREAD

**Issue by hnmli099** [cocos/cocos-engine#11346]
### Cocos Creator version

null

### System information

null

### Issue description

When the sensor attribute is false, the onprosolve method can be executed normally. After setting the sensor to true, the onprosolve method will not be executed. Please consult the great gods. How to solve it. thank you.
sensor属性为false时、可正常执行onPreSolve方法、设置sensor为true后，onPreSolve方法不执行了。请教各位大神。如何解决。谢谢。

### Steps to reproduce

https://forum.cocos.org/t/sensor/98760

**Comment by minggo** [comment]
The behavior is expected. Please refer to [this doc](https://www.iforce2d.net/b2dtut/sensors) for more detail information.
