### ISSUE TITLE
Should not export atlas plist raw file when building project

### ISSUE THREAD

**Issue by jareguo** [cocos/cocos-engine#11357]
### Cocos Creator version

3.5.0

### System information

WeChat Mini Game & Android

### Issue description

![image](https://user-images.githubusercontent.com/1503156/171856772-63813540-efc2-4c91-b0cb-cfd10ab2da74.png)
This file is useless, since we already import plist as SpriteAtlas object.

Re: https://forum.cocos.org/t/topic/135525/14?u=jare

### Steps to reproduce

nope

**Comment by jareguo** [comment]
3.0 开始就有的 bug

**Comment by VisualSJ** [comment]
功能已经合并，3.6 将带上
