### ISSUE TITLE
select object is not accurat enough

### ISSUE THREAD

**Issue by jk20012001** [cocos/cocos-engine#11352]
### Cocos Creator version

3.6.0

### System information

Windows 10

### Issue description

select object is not accurat enough

### Steps to reproduce

![image](https://user-images.githubusercontent.com/15099632/171608614-8573157e-b70e-4707-854c-c53585e7c47d.png)
Create a new scene, place a sphere(0, 2, 0) on the top of a plane which at (0, 0, 0), when I click on the sphere, the plane has been selected.

**Comment by dogeFu** [comment]
![select](https://user-images.githubusercontent.com/23008916/236374185-98dac32d-3769-4281-b149-8a6bc0751dd1.gif)
as the gif show, sphere was selected correctly.  when you select sphere and click sphere again, the object behind sphere will be selected.It's a feature...
