### ISSUE TITLE
sp.spine syntax error

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11372]
### Cocos Creator version

3.4.2，3.5.1，3.5.0

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/136317

3.4.2：
![image](https://user-images.githubusercontent.com/40415168/172118558-510f18e0-928a-4987-88b1-b3bc1a460090.png)

3.5.1，3.5.0：
![image](https://user-images.githubusercontent.com/40415168/172118663-9a5d3af6-ee20-4f37-b1dc-26dee47a91c8.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/40415168/172118728-68eeea8b-5268-4f5d-88e9-d13312a52e91.png)

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/12402
