### ISSUE TITLE
script import error

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#11373]
### Cocos Creator version

3.4.2,3.5.1

### System information

Chrome on Window

### Issue description

the script load OK in 3.4.x, but throw an error in 3.5.1

![企业微信截图_16544974369777](https://user-images.githubusercontent.com/8321365/172121425-75c044bd-ec54-4d17-b6a5-99586fc0eb02.png)
![企业微信截图_16544974755886](https://user-images.githubusercontent.com/8321365/172121445-0d30c6c1-8fcf-452f-aaec-768a25457890.png)

### Steps to reproduce

Reproduce project:
[NewProject.zip](https://github.com/cocos/cocos-engine/files/8842849/NewProject.zip)

**Comment by shrinktofit** [comment]
Fixed in https://github.com/cocos/cocos-editor/pull/308
