### ISSUE TITLE
PhysX Physics costs some time even there is not physics node in scene

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#11382]
## How to Reproduce ?

- Open cocos-benchmark ( https://github.com/cocos/cocos-benchmark ) project in Cocos Creator
- Project -> Project Settings -> Feature Cropping -> Packing all features -> Physics System -> select PhysX Based Physics System
<img width="800" alt="WeChat5768f38932361d99ba9ec8cd10e88393" src="https://user-images.githubusercontent.com/493372/172292059-e7f64ef5-8f51-4b5f-8b71-cf505b884908.png">
- Build and run it on Android device

## Current Result

Physics time in profile view show that it costs time even more than the whole `Game Logic`.

![WechatIMG1546](https://user-images.githubusercontent.com/493372/172292424-d287d9e8-ada4-4704-b798-37d7eacc73e4.jpeg)

## Expected Result

A scene without any physics nodes should not cause much time in simulating physics.

**Comment by lealzhan** [comment]
step() functions of all other physics-backend's PhysicsWorld check the number of sharedBodies. If the number is zero, it will directly return.PhysXWorld::step() funciton does not  do this.
![企业微信截图_16545850256520](https://user-images.githubusercontent.com/9999378/172513435-5ab674a0-2818-42ec-96fb-dc6854aa3a93.png)
