### ISSUE TITLE
richtext triggers two click events

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11412]
### Cocos Creator version

3.5.1

### System information

chrome

### Issue description

When the text is a line break, the overlapping part of the text area will trigger two click events；
In the video you can see that the log prints twice after clicking in some areas

https://user-images.githubusercontent.com/40415168/172595151-4c174b9b-84dd-4322-aef5-1037cde9958c.mp4

### Steps to reproduce

demo:
[NewProject_3.zip](https://github.com/cocos/cocos-engine/files/8860734/NewProject_3.zip)

**Comment by Zhmz** [comment]
there is no spare time to debug this issue because of the workload of protobiochemistry. I decide put it into version 3.6.1. Hope to understand.

**Comment by Zhmz** [comment]
![image](https://user-images.githubusercontent.com/32831993/201024401-c85d4942-dfb2-4611-bf33-c49cc2e55ced.png)
![image](https://user-images.githubusercontent.com/32831993/201025414-f9d96229-6876-4dcb-ba2b-c99a1fb306fc.png)

These two part label segment are all 50.4 height(1.26*lineHeight). it is designed to avoid border truncation.
It is hard to remove the hack modification.
It will be resolve when richtext is restructured.
