### ISSUE TITLE
richtext Line feed display exception

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11439]
### Cocos Creator version

3.5.0，3.5.1

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/136509
![image](https://user-images.githubusercontent.com/40415168/172813817-8efd0538-6dfc-41b6-a61c-82494077d973.png)

video:

https://user-images.githubusercontent.com/40415168/172813912-7af6fe34-9c8e-463a-94bc-5d8e67f2f935.mp4

### Steps to reproduce

demo:
[NewProject_1.zip](https://github.com/cocos/cocos-engine/files/8868941/NewProject_1.zip)

![image](https://user-images.githubusercontent.com/40415168/172814770-d993a432-a5c9-49da-994a-70d4e05b5526.png)

string1:
艳阳天那么风光好<color=#FF0000>红的花</color>是<color=#13BE00>绿的草</color>我乐乐呵呵向前跑，踏遍青山人未老。春城花飞飞，蛇虫四处追，不怕妖孽来，我道显神威..

string2:
艳阳天那么风光好<color=#FF0000>红的花</color>是<color=#13BE00>绿的草</color>我乐乐呵呵向前跑，踏遍青山人未老。春城花飞飞，蛇虫四处追，不怕妖孽来，我道显神威。

**Comment by xianyinchen** [comment]
补充测试文本
```xml
艳阳天那么风光好<color=#FF0000>红的花是<color=#13BE00>绿的sssss
ssss草我乐乐呵呵向前跑，踏遍青山人未老。春城花飞飞，蛇虫四处追，不怕妖孽来，我道显神威......
```

**Comment by Zhmz** [comment]
please QA group validate it

**Comment by Zhmz** [comment]
https://github.com/cocos/cocos-engine/pull/12999

the pr can resolve the issue
please QA group validate it
