### ISSUE TITLE
canot use Export Asset Package 

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#11443]
### Cocos Creator version

3.5.1

### System information

Windows 10 Editor

### Issue description

use Export Asset Package , the editor shows :[Scene] Cannot read property 'E:\gitee\forum\136461_351\assets\bundle001' of undefined
![image](https://user-images.githubusercontent.com/18083506/172828099-8cc095d5-97db-4261-93f0-2398a46fcad3.png)

![企业微信截图_16547673312325](https://user-images.githubusercontent.com/18083506/172828074-7f03aa95-fa3b-4c88-b91a-255da3327710.png)

demo:
[136461_351.zip](https://github.com/cocos/cocos-engine/files/8869551/136461_351.zip)

### Steps to reproduce

1.create a project
2.create a folder
3.create a material
4.use Export Asset Package

**Comment by knoxHuang** [comment]
Thanks for the feedback, this issue has been fixed, we recommend using >= 3.7.0 version of the editor
