### ISSUE TITLE
Native platform dragonBones does not get the correct node size

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11450]
### Cocos Creator version

2.4.9，3.5.1

### System information

window10, android , web

### Issue description

https://forum.cocos.org/t/topic/136526
![image](https://user-images.githubusercontent.com/40415168/172986868-3b32396a-b3d5-44de-9847-73c7b9004e38.png)

The native platform is the initial size of the node, while the web platform gets the size of the node after the dragonBone animation is updated.
![image](https://user-images.githubusercontent.com/40415168/172998385-277c9fd6-d65f-478e-a6d7-a83dad0d2e39.png)

### Steps to reproduce

2.x demo:
[NewProject_7.zip](https://github.com/cocos/cocos-engine/files/8876108/NewProject_7.zip)

3.x demo:
[NewProject_3.zip](https://github.com/cocos/cocos-engine/files/8876114/NewProject_3.zip)

ps: spine is normal.

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13678
