### ISSUE TITLE
[2.4.9] Got SyntaxError when using `SignalR` 6.0.5

### ISSUE THREAD

**Issue by az198071123** [cocos/cocos-engine#11469]
### Cocos Creator version

2.4.9

### System information

MacOS 12.4

### Issue description

I try to use `SignalR` from npm
when I import signalR and use it then I got error in Editor.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/5800906/173182482-7caad99c-8bc4-4070-9fb6-242fc5e214aa.png">

Note: When I using version 5.0.17, It's works fine.

please help me take a look.
Thank you!

### Relevant error log output

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/5800906/173182819-f85e6e33-ff75-44da-a535-73eee0e4c61f.png">

### Steps to reproduce

Please refer to the following zip archive

### Minimal reproduction project

[TestSignalR.zip](https://github.com/cocos/cocos-engine/files/8883612/TestSignalR.zip)

**Comment by jareguo** [comment]
Sorry, 2.x is no longer maintained due to manpower shortage.
