### ISSUE TITLE
Latest engine leaks HTMLCanvasElements

### ISSUE THREAD

**Issue by mikecoker** [cocos/cocos-engine#11466]
### Cocos Creator version

3.5.1

### System information

ALL

### Issue description

https://github.com/cocos/cocos-engine/blob/f7e0deca938c27a6489a9f43ecc882cc5916165e/cocos/2d/assembler/label/font-utils.ts#L146

someone commented out the return to the pool and it should be this:

`public destroy () {
        this.image = null;
        // Label._canvasPool.put(this._data);
        CanvasPool.getInstance().put(this.data as ISharedLabelData);
    }
`

### Steps to reproduce

Step 1: Make a game that uses any text and changes scenes
Step 2: use the safari timelines profiler to see allocations of HTMLCanvasElement keep increasing because the pool is empty

**Comment by mikecoker** [comment]
here is a PR for this issue: https://github.com/cocos/cocos-engine/pull/11979

**Comment by pandamicro** [comment]
Thanks @mikecoker , your PR have been merged
