### ISSUE TITLE
animationClip uuid 搜索遗漏

### ISSUE THREAD

**Issue by zenskcode** [cocos/cocos-engine#11465]
### Cocos Creator version

3.5.1

### System information

windows10

### Issue description

1、控制台报资源丢失
![image](https://user-images.githubusercontent.com/46669456/173075316-b99e5719-3910-440f-a537-34320928cb25.png)
编辑器搜索uuid，搜索不到
但是通过vscode检索prefab，可以查到该uuid,
![image](https://user-images.githubusercontent.com/46669456/173076068-836a7753-ac8b-43c5-9d91-36a36523b034.png)
得知组件为animation后，返回编辑器查找该组件
![image](https://user-images.githubusercontent.com/46669456/173077266-ee291c8d-425d-4bb7-bfe1-472da47a9bcd.png)

2、另一个bug，通过组件名称搜索节点，根节点被遗漏，搜索不到结果
![image](https://user-images.githubusercontent.com/46669456/173076832-6deb3485-44bc-45cd-a41c-d59d81b98c3a.png)

### Steps to reproduce

如上

**Comment by jareguo** [comment]
1，构建过程中的报错，3.6 会改成警告（实际上用户一般不关心，其它引擎也完全不管），并且警告信息里会像 2.x 一样包含比较详细的信息便于查找
3，增加一个搜索选项“仅丢失资源的节点“（Only Nodes with Missing Asset），置于底部，效果和这个一样样
![image](https://user-images.githubusercontent.com/1503156/173559487-d16a2941-756c-4470-b959-b03bad2226ca.png)

**Comment by arsen2010** [comment]
This feature would be added on big editor version v3.7

**Comment by dogodo-cc** [comment]
https://github.com/cocos/editor-extensions/pull/485
https://github.com/cocos/cocos-editor/pull/1687

**Comment by LoryWu** [comment]
3.7.2-030423版本验证已解决
