### ISSUE TITLE
Native platform setting dragonBones cache mode crashes

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11511]
### Cocos Creator version

3.5.1

### System information

android，window10

### Issue description

https://forum.cocos.org/t/topic/135736
![image](https://user-images.githubusercontent.com/40415168/173731846-4da158b7-5e90-4368-90c8-ac15700972b5.png)

Error Log：
![企业微信截图_16552605009996](https://user-images.githubusercontent.com/40415168/173731985-bb06a5d8-16b2-4d96-b31a-2e46bc3c36b0.png)

### Steps to reproduce

demo:
[NewProject_3.zip](https://github.com/cocos/cocos-engine/files/8905507/NewProject_3.zip)

**Comment by zhakesi** [comment]
中间件render调用太早
https://github.com/zhakesi/engine/commit/1d68aa697d97e694a2f6831a495345a4324f09cb
