### ISSUE TITLE
Optimize resetHasChangedFlags

### ISSUE THREAD

**Issue by SantyWang** [cocos/cocos-engine#11607]
When there are too many nodes, resetHasChangedFlags consumption will gradually increase. and this operation is **per-frame**

![image](https://user-images.githubusercontent.com/15109777/174517164-8afe8219-2b2a-46cf-9ba1-3e9326044d89.png)

for example. when number of node comes to 50K, resetHasChangedFlags consumption comes to **3ms** on the native platform.
Need to find a way to optimize this per-frame overhead

**Comment by minggo** [comment]
Any suggestion?

**Comment by SantyWang** [comment]
> Any suggestion?

In most cases, the user only needs to determine whether the transform has changed, not exactly which part of the RTS has changed. Maybe can try the following solution

```c++
class Node {
      static currentVersion = 0;
      static resetHasChanged () {
            Node.currentVersion++;
      }
      _changedVersion = Node.currentVersion;
      get hasChanged () {
            return this._changedVersion === Node.currentVersion;
      }
      set position (pos: Vec3) {
            this._changedVersion = Node.currentVersion;
            // other logic
      }
}

class Director {

      tick () {
            // reset all node's hasChanged value without enumeration
            Node.resetHasChanged();
      }
}
```

**Comment by minggo** [comment]
It is a good solution. The only concerned is that, it will break compatibility. `Node.hasChangedFlags()` will return an enum value, which indicates which part is changed.

We should discussion if we can modify like this.

**Comment by PatriceJiang** [comment]
Or by using seperate storage field

```C++

static uint32_t currentVersion;
uint32_t _changedVersion;
uint32_t _changedFlags;

bool updateVersion(uint32_t flag) {
    if(!hasChanged()) {
       _changedVersion = currentVersion;
       _changedFlags = 0;
    }
    _changedFlags|= flag;
}

bool hasChanged() {
    return _changedVersion ==  currentVersion ;
}

void setPosition() {
     updateVersion(TRANSFORM_BIT_POSITION);
     // ...
}

uint32_t gethasChangedFlags() {
    return hasChanged() ?  _changedFlags: 0;
}
```

**Comment by PatriceJiang** [comment]
For a 60 fps game, 2^32(4294967296) lasts for 828.5 days, that should be enough for local games. I am not sure if it will be a problem for server mode?

**Comment by PatriceJiang** [comment]
According the test result 
![image](https://user-images.githubusercontent.com/40414978/174560569-968549c4-8665-4c0a-bed4-7475dbaf0c0a.png)
The benefits brought by the modification need to be further verified

**Comment by minggo** [comment]
It is wired. Though it does't improve performance, i think we should also change the logic because:
- it can simplify the codes, for example, can remove `BookOfChange` in ts
- it can reduce memory size: currently, engine uses a global vector to store dirty nodes, but doesn't shrink the size

**Comment by PatriceJiang** [comment]
Committed at https://github.com/cocos/cocos-engine/pull/11639
