### ISSUE TITLE
Over iOS version 15.3, should modify regex

### ISSUE THREAD

**Issue by Zhmz** [cocos/cocos-engine#11632]
### Cocos Creator version

3.6

### System information

over iOS 15.3

### Issue description

![Uploading 36cdb47c291823137aaa9c367ad96c3.png…]()

### Steps to reproduce

change regex

**Comment by Zhmz** [comment]
<img width="1083" alt="36cdb47c291823137aaa9c367ad96c3" src="https://user-images.githubusercontent.com/32831993/175486853-d7efa233-a270-4ae8-936a-e3937f15de2b.png">

**Comment by Zhmz** [comment]
committed PR:
https://github.com/cocos/cocos-engine/pull/11698

**Comment by Zhmz** [comment]
please QA group validate it.

**Comment by Zhmz** [comment]
Test steps：
1. provide an appID to me and add authority on it to start WeChat minigame in high performance mode.
2. modify "iOSHighPerformance" as "true" in game.json
3. compare FPS of various iOS versions. If there is a small distance between 14 to 15.3 and other area of versions, it succeeds.

**Comment by pandamicro** [comment]
@Zhmz you need to close this issue and notify QA to test it

**Comment by Zhmz** [comment]
![image](https://user-images.githubusercontent.com/32831993/180594655-cafe87b6-13d4-4d04-891d-79711029dcc0.png)
when high performance mode is turned on, its FPS can reach 37 while its FPS is about 13 when the mode is turned off.
