### ISSUE TITLE
Native Glslang upgrade

### ISSUE THREAD

**Issue by yiwenxue** [cocos/cocos-engine#11635]
Our Glslang library is out of date, and doesn't support Vulkan 1.3, so cocos game will crash when running with Vulkan 1.3.

The solution contains two parts:
- [x] Add new VK flags to cocos-engine.
- [ ] upgrade the `Glslang` libraries in `cocos-external-project` to `11.10.0`.

**Comment by yiwenxue** [comment]
The first part https://github.com/cocos/cocos-engine/pull/11445#issue-1265966110

**Comment by star-e** [comment]
https://github.com/cocos/cocos-engine/issues/11849

**Comment by minggo** [comment]
Update glslang will cause crash on some Android devices.
@star-e i suggest to move this issue to other milestone, treat it as a known issue.

**Comment by star-e** [comment]
> i suggest to move this issue to other milestone, treat it as a known issue.

I agree. It is too risky to upgrade in v3.6. @minggo

**Comment by yiwenxue** [comment]
目前有两个可用的解决方案：

1. 降级 vulkan SDK 和 gpu driver。
2. 下载较新的 spirv 库，可以用这个解压替换 engine/native/external/sources/glslang 目录，可以暂时正常使用。
[glslang.zip](https://github.com/cocos/3d-tasks/files/9177531/glslang.zip)

**Comment by yiwenxue** [comment]
glslang 有对旧版本的兼容，新的 vulkan sdk 已经 fallback 到了旧版本上面之后 3.6 都没有遇到问题。

**Comment by minggo** [comment]
@yiwenxue please use english in future.
If so, can close this issue?

**Comment by yiwenxue** [comment]
> @yiwenxue please use english in future. If so, can close this issue?

Ok, I will.

No need to upgrade glslang since the fallback works fine, problem solved let's close it.
