### ISSUE TITLE
Uncaught RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by obraz29** [cocos/cocos-engine#11644]
### Cocos Creator version

3.4.2, 3.5.0

### System information

Chrome

### Issue description

Hello cocos team, I created 5 spines on scene and get this error, could you please help check:
![image](https://user-images.githubusercontent.com/52654061/174940491-7f2e47ca-36e9-4897-8ddc-491595e010f6.png)

### Steps to reproduce

Create 5 nodes with spine on scene

### Minimal reproduction project

[TestSpine.zip](https://github.com/cocos/cocos-engine/files/8954259/TestSpine.zip)

**Comment by zhakesi** [comment]
please try to modify code:
```
public static IB_SCALE = 4;
```
to
```
public static IB_SCALE = 6;
```
engine/cocos/2d/renderer/static-vb-accessor.ts

**Comment by zhefengzhang** [comment]
https://forum.cocos.org/t/topic/140146

User feedback is still problematic on the WeChat mini-game platform.

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13715

**Comment by zhefengzhang** [comment]
https://discuss.cocos2d-x.org/t/spine-issue-uncaught-rangeerror-offset-is-out-of-bounds-still-happen-in-cocos-3-7-2/58537

Other users have experienced this issue on version 3.7.x.
