### ISSUE TITLE
freeze frame happend on window native platform

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#11662]
### Cocos Creator version

3.4.2, 3.5.1

### System information

window11

### Issue description

I think it has something to do with the Canvas context of Label, the canvas object depends on GC destruction, the canvas will create DC and hold FONT handle on window platform, if a large number of Canvas instances are not released, there will be handle instance exception and the window rendering will be abnormal at this time and the interface will not refresh.

The most obvious error logs:
``` shell
E/jswrapper (277): Failed to create custom font(font name: Arial, font size: 48.000000), use default font.
```

The canvas reuse depends on the following configuration, defaut is 20.
cc.macro.MAX_LABEL_CANVAS_POOL_SIZE=20

### Steps to reproduce

test project.
[textdemolite.zip](https://github.com/cocos/cocos-engine/files/8957042/textdemolite.zip)

**Comment by bofeng-song** [comment]
Firstly: need to call pb.destroy at test case. the issue will disappear at version 3.4.2, 3.5.1.
Secondly: the problem also exist at version 3.6.0, we fix it at this pr (https://github.com/cocos/cocos-engine/pull/11809)
