### ISSUE TITLE
Terrain  error report

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11677]
### Cocos Creator version

3.5.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/137013
![image](https://user-images.githubusercontent.com/40415168/175271416-a0d66d92-7ab0-4a09-93e2-43f6e9b2fa01.png)
![image](https://user-images.githubusercontent.com/40415168/175271494-7cbdf239-0def-40ff-832e-7902ea684f3b.png)

### Steps to reproduce

1. create a  Node Prefab;
2. create a new terrain node in the Node Prefab;
3. create  typescript, modify it ;

https://user-images.githubusercontent.com/40415168/175272778-e750a3e1-68a9-4be3-a684-74d3b92f1721.mp4

demo: [NewProject_23.zip](https://github.com/cocos/cocos-engine/files/8966158/NewProject_23.zip)

**Comment by roadright** [comment]
mark

**Comment by MSoft1115** [comment]
prefab加载terrain block的renderable uuid为“”，导致Scheduler.unscheduleAllForTarget没有找到而报错，不影响运行

**Comment by MSoft1115** [comment]
![企业微信截图_16584719072481](https://user-images.githubusercontent.com/15318610/181414062-8cfc915c-adac-40bb-ae33-0256239fa3da.png)
