### ISSUE TITLE
Error in the inspector when filling an array

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#11682]
### Cocos Creator version

3.5.2

### System information

Windows10

### Issue description

component array canot add component in order.
Question source:
https://discuss.cocos2d-x.org/t/error-in-the-inspector-when-filling-an-array/56419

### Steps to reproduce

add the component Test1 to the element at index 1,then the index 2 canot add Test2.
![image](https://user-images.githubusercontent.com/18083506/175279608-1f291ab8-a8b2-442e-878d-37b3050af13f.png)

here is the demo to reproduce it:
[56419.zip](https://github.com/cocos/cocos-engine/files/8966382/56419.zip)

**Comment by arsen2010** [comment]
Sorry it took so long to get back to you. This issue has been addressed since 3.7.0
