### ISSUE TITLE
Shadows lost

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11717]
### Cocos Creator version

3.5.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/135688
![image](https://user-images.githubusercontent.com/40415168/175916331-cee875fe-aef9-4528-ad1f-a093451c4ea5.png)

### Steps to reproduce

demo:
[NewProject_23.zip](https://github.com/cocos/cocos-engine/files/8990878/NewProject_23.zip)

**Comment by troublemaker52025** [comment]
* https://github.com/cocos/cocos-engine/pull/11758
