### ISSUE TITLE
Simulator should be compiled in release mode

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#11726]
Currently, we build simulator in debug mode.
Start from v3.6, more code is implemented in CPP. If using debug flags to build simulator, it may impact game performance in simulator.

## Expectation

Simulator ( Win + Mac) should be compiled in release mode .

**Comment by dumganhar** [comment]
If simulator needs log output in debug mode, probably, we could define CC_DEBUG=1 in release mode for simulator only.

**Comment by novain1102** [comment]
change Simulator(Mac) compile from debug to release https://github.com/cocos/cocos-engine/pull/11755
