### ISSUE TITLE
Classes inherits RefCounted should hide destructor

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#11730]
If a class inherits RefCounted, then should use reference count to control the life cycle for its instance. If not, it is easy to cause memory issues, for example:
```c++
class Foo : public RefCounted {
public:
    void doSomething() {
    }
};

class Bar final {
public:
    Bar(Foo *f): _foo(f) {
        _foo->addRef();
    }
    ~Bar() {
        _foo->release();
    }
    void func() {
         _foo->doSomething();
    }
};

// Test code
auto *foo = new Foo;
auto *bar = new Bar(foo);
delete foo;  // if Foo::~Foo() is private, then it can not delete it.
bar->func();  // will crash as foo is deleted;

```

**Comment by star-e** [comment]
I agree. It is safer and less error prone.

**Comment by dumganhar** [comment]
Agree. But there're some more complex situations: For example `Frustum` class which may be allocated on stack.
If the destructor is private, compiler will trigger errors.
So if we disallow `RefCounted`'s sub classes being allocated on stack, we need to use `heap` to allocate them. e.g.
 ```c++
Frustum* f = new Frustum();
f->addRef();
// balabala
f->release();
```
Performance for creating temporary heap objects will be worse than which on stack.

**Comment by minggo** [comment]
If so, may be it is not suitable to inherit from RefCounted.

**Comment by dumganhar** [comment]
In theory, `Frustum` should not be inherited from RefCounted from `c++` point of view.
But we currently need to bind `Frustum` to JS for some interfaces, its lifecycle need to be shared by both cpp and javascript, so it need to be a  RefCounted's subclass.

Another way is to use std::shared_ptr for  the method returning `Frustum * / const Frustum &`. It will be:
```c++
class SomeClass {
...
std::shared_ptr<Frustum> getFrustum() const { return _frustum; }
...
private:
    std::shared_ptr<Frustum> _frustum;
```

**Comment by minggo** [comment]
Yep, it is a special case. And we will hide RefCounted's destructor after all its subclass hide their destructors.

**Comment by minggo** [comment]
I reverted the PR above, it will crash, as the reference count of a new object is 0, which means the codes will crash
```c++
// suppose class Test inherits RefCounted
auto *obj = new Test();
obj->release(); // will crash
```

If you want to make it work correctly, then should change to
```c++
auto *obj = new Test();
obj->addRef();
obj->release();
```
It seems wired.

The other solution is to hide constructor too, add reference count in constructor like this, and provide a create function:
```c++
Test* Test::create() {
    auto ret = new Test();
    ret->addRef();
}

auto *obj = Test::create();
obj->release(); // work as expected;
```
If changed like this, then can not `std::shared_ptr` with Test now.

**Comment by minggo** [comment]
> If changed like this, then can not std::shared_ptr with Test now.

I think it is not a big problem. If hide destructor, then it already can not be used with std::shared_ptr.

**Comment by star-e** [comment]
I usually don't hide destructor.
- If object is allocated on stack, refCount should always be 0.
- If object is allocated on heap, addRef and release must be called. Newly created object should be wrapped in IntrusivePtr.
- Helper function like `makeIntrusivePtr<Foo>(xxx)` might be used to prevent misuse.

**Comment by minggo** [comment]
> I usually don't hide destructor.
> 
> * If object is allocated on stack, refCount should always be 0.
> * If object is allocated on heap, addRef and release must be called. Newly created object should be wrapped in IntrusivePtr.
> * Helper function like `makeIntrusivePtr<Foo>(xxx)` might be used to prevent misuse.

Yep, it can work. But just as i mentioned above, it is easy to misuse. All developers should remember and obey the rules.

**Comment by bluesky013** [comment]
`IntrusivePtr<Test> objPtr = Test::create();` may generate additional reference counts.

**Comment by minggo** [comment]
> `IntrusivePtr<Test> objPtr = Test::create();` may generate additional reference counts.

Yep, can not write like this.

**Comment by star-e** [comment]
We might make operator new in class as protected. So user can only new Object using factory function.

**Comment by minggo** [comment]
> We might make operator new in class as protected. So user can only new Object using factory function.

Is there any different from hide constructor?

**Comment by bluesky013** [comment]
> > `IntrusivePtr<Test> objPtr = Test::create();` may generate additional reference counts.
> 
> Yep, can not write like this.

I'm worried about introducing new misuses. What about use factory function like `IntrusivePtr<Test> Test::create()`.

I think the main problem is `IntrusivePtr` can be directly cast to pointer. It is a trade-off between safty and compatibility.  So I suggest not to protect it by adding limitation to class, use warning like `assert(referenceCount == 0)` in the `RefCounted` destructor.

**Comment by minggo** [comment]
> I suggest not to protect it by adding limitation to class, use warning like assert(referenceCount == 0) in the RefCounted destructor.

So the usage looks like
```c++
auto *obj = new Test();
obj->addRef();
delete obj;
```
It seem wired, but i can not find a better way now.

**Comment by minggo** [comment]
> I suggest not to protect it by adding limitation to class, use warning like assert(referenceCount == 0) in the RefCounted destructor.

It is a little better than current implementation.

**Comment by star-e** [comment]
> > We might make operator new in class as protected. So user can only new Object using factory function.
> 
> Is there any different from hide constructor?

User cannot directly new Object. Object is allocated in factory function, whose return value is an IntrusivePtr.
However, user can still create object on stack, since constructor is public.

**Comment by minggo** [comment]
> > > We might make operator new in class as protected. So user can only new Object using factory function.
> > 
> > 
> > Is there any different from hide constructor?
> 
> User cannot directly new Object. Object is allocated in factory function, whose return value is an IntrusivePtr. However, user can still create object on stack, since constructor is public.

Got it, sounds reasonable.

**Comment by minggo** [comment]
> > > We might make operator new in class as protected. So user can only new Object using factory function.
> > 
> > 
> > Is there any different from hide constructor?
> 
> User cannot directly new Object. Object is allocated in factory function, whose return value is an IntrusivePtr. However, user can still create object on stack, since constructor is public.

@star-e we may add memory allocate module, it will override new to do it. Make new as protected may have problem.

**Comment by star-e** [comment]
> we may add memory allocate module, it will override new to do it. Make new as protected may have problem.

We might use custom memory allocator's implementation, but still mark it as protected. I'm not sure whether it will work.

**Comment by minggo** [comment]
As i think we may change `ccnew` to
```c++
define ccnew(T, allocator)  new T(allocator)
```
Then it needs to access public new function.

**Comment by star-e** [comment]
> As i think we may change `ccnew` to
> 
> ```c++
> define ccnew(T, allocator)  new T(allocator)
> ```
> 
> Then it needs to access public new function.

We can use allocator to allocate memory and construct object. It does not use class's "(protected) operator new", but it uses "(public) placement operator new"

![image](https://user-images.githubusercontent.com/13654656/201042787-7fe3f398-e308-4015-bd45-153fb000612f.png)

**Comment by minggo** [comment]
Got it, `placement new` and `operator new` are different functions. We just protect operator new.

**Comment by minggo** [comment]
>  but it uses "(public) placement operator new"

@star-e  In your demo, the placement operator new is protected. And if make it public, then we may also meet the same problem as operator new, for example:
```c++
auto *test = new (Test, allocator); // reference count of test is still 0.
```

**Comment by minggo** [comment]
As discussed above, can not hide the constructor currently.
