### ISSUE TITLE
 left mouse button swipe on WeChat  PC is invalid

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11736]
### Cocos Creator version

3.4.2 ，3.5.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/137187
![image](https://user-images.githubusercontent.com/40415168/176148871-1c6e7017-a842-4850-adbf-07cf4a282815.png)
![image](https://user-images.githubusercontent.com/40415168/176155432-82a742e3-71ca-4146-a296-a5cc01482055.png)

### Steps to reproduce

demo:
[NewProject_2.zip](https://github.com/cocos/cocos-engine/files/8999891/NewProject_2.zip)

**Comment by yyycggg** [comment]
@OnlyKoei This problem will be fixed in 3.7.
