### ISSUE TITLE
支持手机设备系统相机 绑定共享纹理绘制

### ISSUE THREAD

**Issue by liufsd** [cocos/cocos-engine#11766]
### Use Case

Android/iOS 可以通过共享纹理id的方式（OpenGL shareContext），给到小游戏前端，但 cocos似乎没有对应的方式可以绘制出来，目前采用的方式是客户端给rgba数据给到游戏然后通过 https://github.com/cocos/cocos-engine/blob/6a29cb9fdb558a4ef99fe8aa7de47448527b0d7a/cocos/core/gfx/base/device.ts#L326  进行绘制。

### Problem Description

但这种方式性能太差，因为从客户端相机中拷贝GPU数据到内存(glReadPixels)，速度会非常慢，帧率无法达到要求。

### Proposed Solution

是否有绑定纹理id的解决方案？
类似
```
root.device.copyTexImagesToTexture([纹理id], e.textureRender.getGFXTexture() .....)
```

### Alternatives Considered

。

**Comment by liufsd** [comment]
应用场景：AR； 
需要手机系统相机实时数据， 配合游戏引擎做很多效果。
但是走rgba方案(https://developers.weixin.qq.com/minigame/dev/api/media/camera/Camera.onCameraFrame.html)，基本不太商用,   比如微信提供的数据帧小的可怜，模糊，无法当背景使用； 
所以拿相机共享的纹理id， 在配合小游戏才能达到高清高帧率； 但引擎这一块没有看到可以绑定纹理的。

是否可以开放支持？

**Comment by pandamicro** [comment]
Sorry cross application or context render sharing is not in our plan. It really depend on native side implementation, and our hands are tied on wechat platform.

So I'm sorry I must reject your request
