### ISSUE TITLE
NodePool should't put a node has been destroy

### ISSUE THREAD

**Issue by yanjifa** [cocos/cocos-engine#11817]
### Cocos Creator version

3.5.0, 3.6.0

### System information

ALL

### Issue description

节点池 put 了 destroy 过的 node 后，get 使用时，会出现一些非预期的情况，希望不要 put 进去， 并且打印警告

### Steps to reproduce

无

**Comment by minggo** [comment]
I am not if it is to reuse Node for performance in web. And if want to reuse Node, then need to destroy it first and initialize it again.

@yanjifa please use english in future, thanks.
