### ISSUE TITLE
Missing light in instanced lighting scene

### ISSUE THREAD

**Issue by hana-alice** [cocos/cocos-engine#11812]
### Cocos Creator version

3.6.0

### System information

MacOS 12

### Issue description

<img width="802" alt="Screen Shot 2022-07-01 at 17 07 43" src="https://user-images.githubusercontent.com/18626925/176863778-d3a6292f-45e3-44f7-8f47-6046908056bb.png">
应该是要有4个光源叠加的效果的
<img width="646" alt="Screen Shot 2022-07-01 at 17 11 09" src="https://user-images.githubusercontent.com/18626925/176864273-2361af32-3192-4c16-9707-16003f28d1ce.png">
抓帧太长没截全，也只画了两次。

### Steps to reproduce

[v3.6.0，this branch ](https://github.com/troublemaker52025/engine/tree/reduce-instanced-queue-recordCommandBuffer-v3.6.0)
example-showcase: instanced-skining-lighting.

**Comment by hana-alice** [comment]
can't reproduce on windows

**Comment by troublemaker52025** [comment]
* https://github.com/cocos/cocos-engine/pull/11798
