### ISSUE TITLE
Should support gles2 on native?

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#11837]
Supports GLES2 only makes sense for Android devices that only supports gles2. We should try to get the market share of these devices then decide whether to support it.

**Comment by dumganhar** [comment]
I guess the devices those only support OpenGLES2 are in a very low percentage. 
They're born at least ten years ago and it's really hard to run any games on them.
Yep, it's better to get device percentage report to help us make the decision.

**Comment by minggo** [comment]
Can not make decision currently.
