### ISSUE TITLE
Triangles and drawcall display exceptions

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11839]
### Cocos Creator version

3.5.2， 3.5.1

### System information

chrome

### Issue description

https://forum.cocos.org/t/topic/136456
![image](https://user-images.githubusercontent.com/40415168/177131498-848790fa-bf4a-441e-a374-abb1edb4dcb6.png)

Custom materials are used, USE_INSTANCING is checked.
![image](https://user-images.githubusercontent.com/40415168/177131920-cf1d55b9-b13c-4568-8e2c-30b60fb979ad.png)

### Steps to reproduce

demo:
[planeTest.zip](https://github.com/cocos/cocos-engine/files/9038400/planeTest.zip)

**Comment by pandamicro** [comment]
Already responded in the forum
It's due to lighting and shadow rendering
