### ISSUE TITLE
Image deletion causes an error in the editor

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11875]
### Cocos Creator version

3.5.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/137530
![image](https://user-images.githubusercontent.com/40415168/177513864-9d7ef4e3-ceb5-4f75-acaa-6dd1888a004d.png)

### Steps to reproduce

![bug](https://user-images.githubusercontent.com/40415168/177508460-40b046be-16fd-47cf-a854-145bf1351e2f.gif)

**Comment by yanOO1497** [comment]
Hi, this issue was fixed in 3.8  https://github.com/cocos/3d-tasks/issues/15599
