### ISSUE TITLE
There is a problem with spine setEndListener

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#11888]
### Cocos Creator version

3.5.0 & 3.5.2

### System information

chrome web

### Issue description

https://forum.cocos.org/t/topic/135666

<img width="767" alt="图片" src="https://user-images.githubusercontent.com/35944775/177905229-8e8decc1-cf5b-4a22-84b0-560afe5b37fc.png">

### Steps to reproduce

null

**Comment by zhakesi** [comment]
此问题非bug. EventType.end 当不再应用该条目动画时调用该方法。
当切换动画时会触发。entry.animation.name对应的动画为切换前的动画
