### ISSUE TITLE
Touch events need to be handled for compatibility

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11947]
### Cocos Creator version

3.5.2

### System information

window10，chrome

### Issue description

https://forum.cocos.org/t/topic/137714
https://forum.cocos.org/t/topic/137664

![image](https://user-images.githubusercontent.com/40415168/178477083-cfe3e0ed-8aa9-4164-b252-37dc24f313cf.png)
![image](https://user-images.githubusercontent.com/40415168/178477165-d758e60a-6d0d-4b29-83fb-540e8876f938.png)

### Steps to reproduce

demo:
[NewProject_18.zip](https://github.com/cocos/cocos-engine/files/9092305/NewProject_18.zip)

**Comment by minggo** [comment]
I tested the demo, no error. It may be fixed in some version.
