### ISSUE TITLE
tsconfig.json "paths" not working

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#11950]
### Cocos Creator version

3.5.2

### System information

Windows 11, Chrome

### Issue description

Adding paths in tsconfig.json doesn't work with Cocos Creator. This is quite unfortunate since it really cleans up the import paths a lot

Following setup does not work.
![image](https://user-images.githubusercontent.com/7983358/178615729-2659330c-d4e0-462d-90d4-91e36a9cb073.png)

### Relevant error log output

![image](https://user-images.githubusercontent.com/7983358/178615820-76471cce-458d-4ac8-b933-5bfc161ab6c3.png)

### Steps to reproduce

Modify tsconfig.json to 
![image](https://user-images.githubusercontent.com/7983358/178615729-2659330c-d4e0-462d-90d4-91e36a9cb073.png)
Createa a TS file and try to import with that tsconfig.json path.
Check Cocos console or launched games for errors not finding the paths

**Comment by shrinktofit** [comment]
tsconfig is not processed. If you have module mapping requirements. Use [import map](https://docs.cocos.com/creator/manual/en/scripting/modules/import-map.html) instead.

Put this JSON into project root folder and configure the setting according to manual:
```json
{
  "imports": {
    "@src/": "./assets/src/"
  }
}
```

You need as well keep the stuff in tsconfig.json to achieve type checking.

**Comment by Ronsku** [comment]
@shrinktofit amazing, works perfectly! I wasn't aware that import-map worked with directory mapping as well :)
