### ISSUE TITLE
Reference diagrams can set layers

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#11986]
### Cocos Creator version

3.5.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/137776
![image](https://user-images.githubusercontent.com/40415168/178931877-fd31e603-5d05-4af5-961c-5dd1a1e1a576.png)
![image](https://user-images.githubusercontent.com/40415168/178931801-b5883ae9-d564-4ad8-917b-3f83133a3cdd.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/40415168/178932904-6373f87e-ad3b-4b7c-82d3-bcfb64f7ef97.png)
If opacity is 255, the node is not visible

**Comment by wuzhiming** [comment]
now is set to bottom layer
