### ISSUE TITLE
spine resource release causes memory growth

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#12008]
### Cocos Creator version

3.4.2 3.5.2

### System information

web

### Issue description

Question feedback from:
https://discuss.cocos2d-x.org/t/gfx-buffer-memory-leak-when-destroy-spine-node/56514
spine resource frequent release , causes GFX Buffer Mem growth.

### Steps to reproduce

here is the demo:
[56514.zip](https://github.com/cocos/cocos-engine/files/9117509/56514.zip)
run the demo , then will see the GFX Buffer Mem grow continuous.
![image](https://user-images.githubusercontent.com/18083506/179143458-fbf36360-0f4f-4710-a583-4b58ab61c1f1.png)

An attempt has been made to call destroyRenderData, it doesnot work.

**Comment by zhakesi** [comment]
ts层batcher2d LocalDescriptorSet 没有销毁释放_localBuffer机制。
ts组件层和DrawBatcher以及LocalDescriptorSet 无直接强关联，无法通过销毁组件释放LocalDescriptorSet 中_localBuffer.
后续需通过代码结构调整系统性解决。目前可使用enableBatch模式屏蔽该问题。

batcher2d LocalDescriptorSet buffer问题另建issue处理。
* https://github.com/cocos/cocos-engine/issues/13676
