### ISSUE TITLE
When dynamically adding particle nodes to the scene, the effect appears abnormal

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12003]
### Cocos Creator version

3.5.2

### System information

chrome web

### Issue description

![图片](https://user-images.githubusercontent.com/35944775/179130067-0ff8dd0f-1f2d-4cde-a898-a6ff69e2f8a0.png)

If the particle resource is loaded after the node is added to the scene, the effect will be abnormal.
如果粒子资源在节点添加到场景之后才加载，则会出现效果异常。

![图片](https://user-images.githubusercontent.com/35944775/179130267-f035e690-7343-4c8d-9043-47700b3d073e.png)

If the particle resource is loaded before the node is added to the scene, there is no problem.
如果粒子资源在节点添加到场景之前就加载，则没有问题。

The following is a screenshot of when an exception occurs
下图是出现异常时的截图

<img width="473" alt="图片" src="https://user-images.githubusercontent.com/35944775/179130428-5b46a7a4-0879-4c50-8334-2b7e9bd3f30e.png">

Here is a screenshot when there is no abnormality
下面是无异常时的截图

<img width="477" alt="图片" src="https://user-images.githubusercontent.com/35944775/179130354-34e8fd0c-6595-4394-a92a-8978462be3ba.png">

### Steps to reproduce

null

### Minimal reproduction project

[TestParticle.zip](https://github.com/cocos/cocos-engine/files/9117015/TestParticle.zip)

**Comment by zxx43** [comment]
call _updateBlendFunc when change plist file
