### ISSUE TITLE
Failed to set game frame rate on ios platform

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12002]
### Cocos Creator version

3.6.0

### System information

ios

### Issue description

Testing with CocosCreator 3.6.0 Community Edition 071301, after setting game.frameRate on ios platform (running with xcode emulator), the game frame rate does not match the input value.

使用 CocosCreator 3.6.0 社区版 071301 进行测试，在 ios 平台（使用 xcode 模拟器运行）上设置 game.frameRate 之后，游戏帧率无法和输入的数值保持一致。

### Relevant error log output

null

### Steps to reproduce

null

**Comment by SantyWang** [comment]
xcode 模拟器的问题， @timlyeee 帮忙看一眼

**Comment by novain1102** [comment]
How to reproduction? Seems run well in my local enviroment.

![image](https://user-images.githubusercontent.com/18634782/181455969-22b767d5-9de7-4cfc-af71-444d4748d11b.png)
![image](https://user-images.githubusercontent.com/18634782/181456007-61f35945-7c52-42ac-b004-1d9cca33b85a.png)

**Comment by novain1102** [comment]
Run well when set frameRate to 30. However, If you set frameRate to other value like 45, it failed on all the platform(Android, iOS, etc), not only for iOS simulator. I'm not sure if it's a known issue. @holycanvas @minggo

**Comment by minggo** [comment]
It is not an known issue.

**Comment by minggo** [comment]
@qiuguohua please take a look.

**Comment by qiuguohua** [comment]
There is no problem in my test here, including android and IOS.

My test android may have an average of two frames higher than the set value.

testing method:
In test-case, set by calling game.frameRate = value

![image](https://user-images.githubusercontent.com/5205637/181728172-bf45ea0e-d8a0-41d5-a694-bfd3a7d90566.png)
![aaa6b07103082c7e21dc06b86b676075](https://user-images.githubusercontent.com/5205637/181728200-6dfaa8f2-62b7-4bd6-8025-f13fa3fc3e2b.jpg)

**Comment by novain1102** [comment]
Test in 3.6.0, setFrame as expect on Android, but NOT as expect on iOS.
And this issue also reproduce in 3.5.2 version. It's not a new problem in 3.6.0 version, so change priority to p2

**Comment by novain1102** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/18634782/182032254-1066fc37-0b4c-49ba-aa58-e4539b459d3b.png">
I'v try each value from 0~60. It shows that when frame rate set below 30, it can be set precisely. But when set [31 ,40] the result could be 30, when set to [41, 60], the result could be 60.

So I guess there is kind of iOS mechanism like vSync to limit frame rate range.
Apple commuity said there is an option(Accessibility > Motion) to turn off limit frame rate, yet i didn't find it on my iPhone. 
https://discussions.apple.com/thread/251782661

Similar issue in Unity:https://answers.unity.com/questions/791437/targetframerate-vsync-for-ios.html

**Comment by novain1102** [comment]
We've add document to describle this strategy later.
