### ISSUE TITLE
3.4.2 IOS Can not use UINavigationController

### ISSUE THREAD

**Issue by speakissilver** [cocos/cocos-engine#12010]
### Cocos Creator version

3.4.2

### System information

ios 15.5 build on iphone 7 plus

### Issue description

The app crashed when I try to run:

"UINavigationController *nav = [[UINavigationController alloc]initWithRootViewController:_viewController];
[self.window setRootViewController:nav];"

and the error message shows:

"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CALayer pixelFormat]: unrecognized selector sent to instance 0x280263d20'"

I think there might be something wrong with the following part:

"uintptr_t windowHandle = reinterpret_cast<uintptr_t>(UIApplication.sharedApplication.delegate.window.rootViewController.view);"

![image](https://user-images.githubusercontent.com/59194019/179150047-d3c1ade2-9955-4814-bf95-aa5465d0f31c.png)

### Relevant error log output

"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CALayer pixelFormat]: unrecognized selector sent to instance 0x280263d20'"

### Steps to reproduce

build and running on iphone

**Comment by novain1102** [comment]
Have you tested whether it will reproduce on other devices, except iphone 7p. And can you describe the steps to reproduce in detail? Or just provide me with a demo.

**Comment by novain1102** [comment]
The code mentioned above has been refactored. Please re-test in above 3.6.0 version and let me know if reproduce this issue.

**Comment by longjianjiang** [comment]
At engine 3.6.0, I try  not run cocos when app start, window's rootViewController is TestViewController, TestViewController has one button, click button (call enterGame method) run cocos, then crash.

```
- (void)enterGame {
    CGRect bounds = [[UIScreen mainScreen] bounds];
    _viewController                           = [[ViewController alloc] init];
    _viewController.view                      = [[View alloc] initWithFrame:bounds];
    _viewController.view.contentScaleFactor   = UIScreen.mainScreen.scale;
    _viewController.view.multipleTouchEnabled = true;
    
    [self.appDelegateBridge application:[UIApplication sharedApplication] didFinishLaunchingWithOptions:@{}];
    
    [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:_viewController animated:YES completion:nil];
}
```

```
[CALayer pixelFormat]: unrecognized selector sent to instance 0x6000031daf80"
```

---

i found here get render view is wrong, always find window's rootViewController?

```
class SystemWindow;
uintptr_t SystemWindow::getWindowHandle() const {
    return reinterpret_cast<uintptr_t>(UIApplication.sharedApplication.delegate.window.rootViewController.view);
}
```

@mmyduckx

**Comment by novain1102** [comment]
> At engine 3.6.0, I try not run cocos when app start, window's rootViewController is TestViewController, TestViewController has one button, click button (call enterGame method) run cocos, then crash.
> 
> ```
> - (void)enterGame {
>     CGRect bounds = [[UIScreen mainScreen] bounds];
>     _viewController                           = [[ViewController alloc] init];
>     _viewController.view                      = [[View alloc] initWithFrame:bounds];
>     _viewController.view.contentScaleFactor   = UIScreen.mainScreen.scale;
>     _viewController.view.multipleTouchEnabled = true;
>     
>     [self.appDelegateBridge application:[UIApplication sharedApplication] didFinishLaunchingWithOptions:@{}];
>     
>     [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:_viewController animated:YES completion:nil];
> }
> ```
> 
> ```
> [CALayer pixelFormat]: unrecognized selector sent to instance 0x6000031daf80"
> ```
> 
> i found here get render view is wrong, always find window's rootViewController?
> 
> ```
> class SystemWindow;
> uintptr_t SystemWindow::getWindowHandle() const {
>     return reinterpret_cast<uintptr_t>(UIApplication.sharedApplication.delegate.window.rootViewController.view);
> }
> ```
> 
> @mmyduckx

I'm not sure if the engine supports this usage. Could you give me a reproducible demo for further diagnosis?

**Comment by longjianjiang** [comment]
[TestDemo.zip](https://github.com/cocos/cocos-engine/files/9582125/TestDemo.zip)


@mmyduckx

**Comment by longjianjiang** [comment]
@mmyduckx Hi, can this be fix?

**Comment by novain1102** [comment]
> @mmyduckx Hi, can this be fix?

Hi, I try your demo. Does overriding the previous view by changing the rootViewController after click the button do not meet your needs?
I would like to know your further requirements so that we can improve the engine logic to make it easier to use![image](https://user-images.githubusercontent.com/18634782/192747367-184612fa-152c-4e82-88db-4d0f0597b4ef.png)

**Comment by novain1102** [comment]
> At engine 3.6.0, I try not run cocos when app start, window's rootViewController is TestViewController, TestViewController has one button, click button (call enterGame method) run cocos, then crash.
> 
> ```
> - (void)enterGame {
>     CGRect bounds = [[UIScreen mainScreen] bounds];
>     _viewController                           = [[ViewController alloc] init];
>     _viewController.view                      = [[View alloc] initWithFrame:bounds];
>     _viewController.view.contentScaleFactor   = UIScreen.mainScreen.scale;
>     _viewController.view.multipleTouchEnabled = true;
>     
>     [self.appDelegateBridge application:[UIApplication sharedApplication] didFinishLaunchingWithOptions:@{}];
>     
>     [[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:_viewController animated:YES completion:nil];
> }
> ```
> 
> ```
> [CALayer pixelFormat]: unrecognized selector sent to instance 0x6000031daf80"
> ```
> 
> i found here get render view is wrong, always find window's rootViewController?
> 
> ```
> class SystemWindow;
> uintptr_t SystemWindow::getWindowHandle() const {
>     return reinterpret_cast<uintptr_t>(UIApplication.sharedApplication.delegate.window.rootViewController.view);
> }
> ```


If you want to use presentViewContoller to show cocos engine content, maybe you could try this modification.
![image](https://user-images.githubusercontent.com/18634782/192752786-cb929665-3be2-416d-b860-938e2097c7bf.png)
But don't forget to modify all the codes contain rootViewController usage in engine.
![image](https://user-images.githubusercontent.com/18634782/192752685-c99a3ecd-d148-46ee-883d-e01650eaa106.png)

@qiuguohua Maybe we need to improve this usage by save _viewController in SystemWindow Class and decouple `getWindowHandle` with rootViewController

**Comment by yxcsky** [comment]
@novain1102  Hello，我在使用cocos engine V3.8.7版本，使用上面提供的TestCocosManager present 游戏窗口方式，也会崩溃下面信息-[CALayer pixelFormat]: unrecognized selector sent to instance 0x2803d0180'，下方有压缩包代码，麻烦看下是否有办法可以通过其他按钮进入cocos游戏：

<img width="1417" height="987" alt="Image" src="https://github.com/user-attachments/assets/bbda2586-7855-4ade-ba68-d2bbe5b7add6" />

<img width="2025" height="511" alt="Image" src="https://github.com/user-attachments/assets/7d2d9f72-c7a4-4d8c-bf51-d8958f52ef67" />

[Cocos387.zip](https://github.com/user-attachments/files/22273678/Cocos387.zip)
