### ISSUE TITLE
[3.6.0-071301] iOS crash

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#12018]
### Cocos Creator version

3.6.0

### System information

Xcode 13.4.1，iphone 7 iOS 15.5,  macOS 12.4

### Issue description

Using Creator 3.6.0 Community Edition version 3.6.0-071301, using skeletal animations, building iOS to run on Xcode, app crashes.
The other project works fine on 3.5.2 and the web preview works fine.
Test devices: iOS simulator, iphone 7

### Relevant error log output

JS: [INFO]: [Physics][Bullet]: Using asmjs Bullet libs.
JS: [INFO]: [PHYSICS]: register bullet.
JS: [INFO]: [PHYSICS]: using bullet.
JS: [WARN]: Download Font [ OpenSans-Bold_LABEL ] failed, using Arial or system default font instead
JS: [WARN]: Download Font [ OpenSans-Italic_LABEL ] failed, using Arial or system default font instead
JS: [WARN]: Download Font [ OpenSans-BoldItalic_LABEL ] failed, using Arial or system default font instead
JS: Cocos Creator v3.6.0
JS: [Localization Editor] not found translate language list, skip init l10n
15:36:17 [INFO]: builtin-geometry-renderer|line-vs:vert|line-fs:front compile succeed.
15:36:17 [INFO]: builtin-geometry-renderer|line-vs:vert|line-fs:back compile succeed.
15:36:17 [INFO]: builtin-geometry-renderer|dashed-line-vs:vert|dashed-line-fs:front compile succeed.
15:36:17 [INFO]: builtin-geometry-renderer|dashed-line-vs:vert|dashed-line-fs:back compile succeed.
15:36:17 [INFO]: builtin-geometry-renderer|triangle-vs:vert|triangle-fs:front compile succeed.
15:36:17 [INFO]: builtin-geometry-renderer|triangle-vs:vert|triangle-fs:back compile succeed.
15:36:17 [INFO]: builtin-debug-renderer|debug-renderer-vs:vert|debug-renderer-fs:frag compile succeed.
15:36:17 [INFO]: builtin-occlusion-query|occlusion-query-vs:vert|occlusion-query-fs:frag compile succeed.
15:36:17 [INFO]: util/splash-screen|splash-screen-vs:vert|splash-screen-fs:frag compile succeed.
Assertion failed: (false), function operator(), file PassUtils.cpp, line 171.
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

### Steps to reproduce

Using Creator 3.6.0 Community Edition version 3.6.0-071301, 
using skeletal animations, building iOS to run on Xcode, app crashes.

**Comment by PatriceJiang** [comment]
Fixed in https://github.com/cocos/cocos-engine/pull/12028

**Comment by obraz29** [comment]
hello @PatriceJiang, another crash on iOS platform, it's similiar this issue, could you help check ?
![image](https://user-images.githubusercontent.com/52654061/188832219-ce9ddd2c-f648-45ec-80c9-b1dd4ae44f61.png)

**Comment by PatriceJiang** [comment]
Could you please upload a demo?

**Comment by PatriceJiang** [comment]
And create a new issue to track it
