### ISSUE TITLE
Add ReleaseWithDebugInfo or profile 'build variant' for android

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#12025]
ReleaseWithDebugInfo should not hide symbols

**Comment by PatriceJiang** [comment]
![image](https://user-images.githubusercontent.com/40414978/185829058-e8c9822d-f4f1-484f-bd8f-8da2f9a390c2.png)

This will cause all libraries that developers depend on to provide this build type. This breaks compatibility.

**Comment by dumganhar** [comment]
Could we create a default relWithDebug variant which is based on release variant for 3rd libraries automatically?

**Comment by PatriceJiang** [comment]
We cant, as the error report in the screenshot, libservice is download by editor plugin. We got no mechanism to modify it.

**Comment by PatriceJiang** [comment]
I add a switch in build.gradle https://github.com/cocos/cocos-engine/pull/12496
