### ISSUE TITLE
3.6.0社区版，局部换装spine原生安卓崩溃

### ISSUE THREAD

**Issue by zenskcode** [cocos/cocos-engine#12030]
### Cocos Creator version

3.6.0-社区公测版

### System information

windows10

### Issue description

3.6.0社区版，局部换装spine原生安卓崩溃，推测崩溃与局部换装无关，jiaose.png为spine导出贴图，spine导出版本为3.8

使用官方技术团队提供的spine局部换装
https://github.com/cocos/cocos-awesome-tech-solutions/tree/3.4.0-release/demo/Creator3.4.0_2D_spine_changeSlot_with_texture
在3.5.2上原生、web均表现正常，但性能欠佳，局部贴图无法参与动态合图，参与合图后显示异常。

3.6.0社区版上，web表现正常，安卓原生崩溃crash，日志如下
![image](https://user-images.githubusercontent.com/46669456/179251502-7478e05a-4f7c-4d51-8da2-7ff01c7e72d0.png)

![image](https://user-images.githubusercontent.com/46669456/179251596-145797c5-7cc5-41b0-9f90-cc4300b7ecd9.png)

![image](https://user-images.githubusercontent.com/46669456/179251134-79cce020-78c2-45e3-af21-b02d114ae5bb.png)

![image](https://user-images.githubusercontent.com/46669456/179251041-76086fba-9970-4658-ac1f-97da36e4f150.png)

### Steps to reproduce

使用官方技术团队提供的spine局部贴图，运行android debug包

**Comment by zenskcode** [comment]
空工程运行spine，统一spine素材，表现正常，因此判断上述问题可能与局部换装方案有关

**Comment by zhefengzhang** [comment]
@zenskcode 你好，此问题你可以试试把 macro.BATCHER2D_MEM_INCREMENT 的值改大一些来暂时解决。
后续等 3.6.0 正式版发布时，就会解决这个问题。

**Comment by zenskcode** [comment]
咨询得知顶点的上限是 65535，换算成 kb 约为 2303，与我目前2048较为接近，可能需要其他的方式来解决这个问题

**Comment by zhakesi** [comment]
已测试验证V3.6.0可正常运行。
js_register_spine_updateRegion 函数添加到jsb_spine_manual.cpp   register_all_spine_manual函数之前
在 register_all_spine_manual 注册ns->defineFunction("updateRegion", _SE(js_register_spine_updateRegion));

**Comment by migachen18** [comment]
> 已测试验证V3.6.0可正常运行。 js_register_spine_updateRegion 函数添加到jsb_spine_manual.cpp register_all_spine_manual函数之前 在 register_all_spine_manual 注册ns->defineFunction("updateRegion", _SE(js_register_spine_updateRegion));

你好，我使用3.8的也出现了类似问题，但是在3.8没有找到js_register_spine_updateRegion这个函数
