### ISSUE TITLE
Dynamically setting the convex property of the MeshCollider after rigid body generation has no effect

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12048]
### Cocos Creator version

3.5.2

### System information

all

### Issue description

Dynamically setting the convex property of the MeshCollider after rigid body generation has no effect

刚体生成后，动态设置 MeshCollider 的 convex 属性没有效果

### Steps to reproduce

..

### Minimal reproduction project

[001.zip](https://github.com/cocos/cocos-engine/files/9129132/001.zip)

**Comment by zhefengzhang** [comment]
https://forum.cocos.org/t/topic/136252

**Comment by lealzhan** [comment]
https://github.com/cocos/cocos-engine/pull/13312
