### ISSUE TITLE
[3.5.2] Illumination mapping baked model display exception

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#12056]
### Cocos Creator version

3.5.2

### System information

macOS 12.4

### Issue description

Use the editor's light mapping function to bake, operate according to the official documentation, and the model has 2UV, one UV for light mapping. The baking effect shows exceptions.
![47A95B177239DFFCA6C417D5121080E0](https://user-images.githubusercontent.com/14273437/179497101-6b6eff8a-4480-4579-800e-588373f98411.png)
![13D6F3C9C46297260D7806F659E22E9D](https://user-images.githubusercontent.com/14273437/179497109-782ca220-f1ca-4bd7-a802-b1393e8a0d0d.png)

### Steps to reproduce

Light mapping of the baked model after building the project

**Comment by MSoft1115** [comment]
https://github.com/cocos/editor-extensions/pull/271

**Comment by MSoft1115** [comment]
已解决
