### ISSUE TITLE
stencil test does not display correctly

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12085]
### Cocos Creator version

3.5.2，3.6.0-0715

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/137967
![537e58addcc3f2c006de76c07bde3901ebacfd7f](https://user-images.githubusercontent.com/40415168/179892780-d0a65b5c-644d-49f2-bb4b-5cc9f712eaec.gif)

### Steps to reproduce

https://user-images.githubusercontent.com/40415168/179893034-aa95ec52-e56e-4b13-ab30-b3db34e95714.mp4
demo :
[stecil.zip](https://github.com/cocos/cocos-engine/files/9146352/stecil.zip)

This happens because these parameters on the material have been modified：
![企业微信截图_16582886827372](https://user-images.githubusercontent.com/40415168/179893192-5ca0c42e-6497-4584-bf2f-bcafc4ca20e9.png)

**Comment by xubing0906** [comment]
moving the ball or box will sort the render queue, if the box render first the stencil test will fail, so just modify the priority of the ball material to ensure that the ball render before the box.
![企业微信截图_16589017877182](https://user-images.githubusercontent.com/49358166/181172850-a86282c7-1d09-445a-bc09-f8bba483a2ea.png)
