### ISSUE TITLE
The generated Xcode project needs to be changed according to the configuration set by the editor

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#12101]
- set `debug` mode in editor, the Xcode project setting should
  - use debug build
  - disable `Metal API Validation`
  - disable `Metal Shader Validation`
- set `release` mode in editor, the Xcode project setting should
  - use release build
  - enable `Metal API Validation`
  - enable `Metal Shader Validation`

**Comment by PatriceJiang** [comment]
CMake does not support setting
- `enableGPUValidationMode = "1"`          XCODE_SCHEME_GPU_API_VALIDATION
- `enableGPUShaderValidationMode = "2"`    XCODE_SCHEME_GPU_SHADER_VALIDATION

https://cmake.org/cmake/help/latest/prop_tgt/XCODE_GENERATE_SCHEME.html#prop_tgt:XCODE_GENERATE_SCHEME



I created a issue https://gitlab.kitware.com/cmake/cmake/-/issues/23857

**Comment by PatriceJiang** [comment]
The [merge request](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7581) for this feature in CMake repo is target at 3.25.0, which will not be released in recent.

**Comment by PatriceJiang** [comment]
The [merge request](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7581) has be merged. This issue is tracked in https://github.com/cocos/cocos-engine/issues/12651
