### ISSUE TITLE
[3.5.2] xml error problem

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#12177]
### Cocos Creator version

3.5.2

### System information

mac

### Issue description

xml error invalid doc source
There is no way to locate which file is reporting an error
![CAA5E0DC-C409-42B1-9DD8-763F7F59AE18](https://user-images.githubusercontent.com/14273437/180714980-8707983c-b380-48fb-bca3-0e2c9236c0ce.png)
![WechatIMG60](https://user-images.githubusercontent.com/14273437/180714990-79bc2e2a-c2d9-4e94-b996-ab16bf85a4cf.jpeg)

### Steps to reproduce

Resource Import 3.5.2 Editors

**Comment by VisualSJ** [comment]
xmldom is a tool that outputs errors directly inside the tool, and there is no way to get them for now
