### ISSUE TITLE
websocket native crashes

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12199]
### Cocos Creator version

2.4.9，3.5.2，3.6.0-072219

### System information

window10, android , web

### Issue description

https://forum.cocos.org/t/topic/133665
![image](https://user-images.githubusercontent.com/40415168/180947551-029e696c-0546-49b1-a446-f7ff190bbc52.png)

### Steps to reproduce

3.6 demo :
[NewProject_3.zip](https://github.com/cocos/cocos-engine/files/9187500/NewProject_3.zip)

2.4.9 demo:
[cocos_creator_framework-master.zip](https://github.com/cocos/cocos-engine/files/9187510/cocos_creator_framework-master.zip)

![企业微信截图_16588172805295](https://user-images.githubusercontent.com/40415168/180948635-b8d63e0f-f137-49e4-b82d-97d88bf52e73.png)
![企业微信截图_16588177461204](https://user-images.githubusercontent.com/40415168/180948668-d57b0006-cac8-45fe-b1f6-4499c27c021d.png)
![image](https://user-images.githubusercontent.com/40415168/180949122-182ccd73-2cef-45f9-b0a9-ab876e7ee8b0.png)

The reason for the crash is that the two parameters passed in by ws.close are of undefined type, do we need to fix this?
This is a usage issue, and if it needs to be fixed, both 2.x and 3.x should fix it.

**Comment by novain1102** [comment]
Please @OnlyKoei help to verify 2.x PR above. Thanks.
