### ISSUE TITLE
webSocketServer support for iOS

### ISSUE THREAD

**Issue by novain1102** [cocos/cocos-engine#12222]
### Use Case

https://forum.cocos.org/t/topic/137962

### Problem Description

Can't run well when set USE_WEBSOCKET_SERVER ON. Try to repair this issue.
![image](https://user-images.githubusercontent.com/18634782/181210072-1ab36be5-ef3b-48a1-a7c7-ef763754fa67.png)

![wecom-temp-27d4a4293b6fdedabd05eb2306fb16f3](https://user-images.githubusercontent.com/18634782/181209547-c7783b20-d8c5-4059-a9dc-4ab1ab220b7e.png)

### Alternatives Considered

null

**Comment by mmyduckx** [comment]
iOS simulator DO NOT support below 13.0; Please choose iOS simulator version above 13.0;

related disscussion: https://forum.cocos.org/t/topic/137230
