### ISSUE TITLE
Disappearance of Label Shadow on Android platform

### ISSUE THREAD

**Issue by Zhmz** [cocos/cocos-engine#12253]
### Cocos Creator version

3.6.0

### System information

Android

### Issue description

LabelShadow doesn't work on Android platform

### Steps to reproduce

1. new a project ,new a label in scene and add a LabelShadow component on it
2. build in Android platform
3. run it and find the LabelShadow doesn't work.

**Comment by minggo** [comment]
Should also check iOS platform. And please add a test case for it too.

**Comment by bofeng-song** [comment]
support shadow feature at Android platform
https://github.com/cocos/cocos-engine/pull/12332

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/12382
support shadow feature at IOS platform
