### ISSUE TITLE
Touch event ownership issue on mobile native

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#12257]
Reproduce with the project
[testTouchEventDemo.zip](https://github.com/cocos/cocos-engine/files/9208177/testTouchEventDemo.zip)

![wecom-temp-107265-76f8d8cdfda342aaf65c8735e2d87298](https://user-images.githubusercontent.com/632460/181483699-de7cd285-684d-48d8-9e93-53bb104df448.jpg)

Description
1. Only red panel registered event, and blue panel doesn't
2. Multitouch enabled
3. The label will show all event triggered on red panel

Reproduce
1. Publish to Android or iOS
2. Hold a finger on red panel, the label will show "TOUCH_START, event.target: A", don't release it
4. Tap another finger on blue panel, it will also trigger red panel event
5.  If you release the second finger, the label will show "TOUCH_END, event.target: A"

**Comment by PPpro** [comment]
we should implement `changedTouches` property on Native platforms
https://developer.mozilla.org/zh-CN/docs/Web/API/TouchEvent/changedTouches

and we should still keep the current implementation as `touches` property
https://developer.mozilla.org/zh-CN/docs/Web/API/TouchEvent/touches

**Comment by bofeng-song** [comment]
android has been fixed the issue
https://github.com/cocos/cocos-engine/pull/12285

**Comment by novain1102** [comment]
Cannot Reproduce on iOS platform when enable multi-touch.
