### ISSUE TITLE
ttf doesn't work on Windows platform

### ISSUE THREAD

**Issue by Zhmz** [cocos/cocos-engine#12262]
### Cocos Creator version

3.6.0

### System information

Windows

### Issue description

![image](https://user-images.githubusercontent.com/32831993/181672090-b46c4960-2267-4003-a723-165d0a53e4cf.png)
![企业微信截图_16590587697680(2)](https://user-images.githubusercontent.com/32831993/181672103-bf3641dd-05d8-4b46-bcce-f2ec4afe1344.png)

The display effect of various ttf is the same on Windows

### Steps to reproduce

1. new a project and new several label in scene
2. assign various ttf on them
3. build in Windows
4. run it and find that their display effect is the same

**Comment by Zhmz** [comment]
It is an issue left over from history
There is no spare time in v3.6
and it has little effect
so delay it to v3.6.1

**Comment by AnkoGo123** [comment]
哪个版本都是这样，除了2.3.x，2.4.x有.3以上的版本之外，3.x版本到目前没见过.3+以上的版本，都在快速的迭代，每个bug都遗留到下一个版本，然后下一个版本又产生新的bug，又遗留到下一个版本，尿性

**Comment by AnkoGo123** [comment]
> 哪个版本都是这样，除了2.3.x，2.4.x有.3以上的版本之外，3.x版本到目前没见过.3+以上的版本，都在快速的迭代，每个bug都遗留到下一个版本，然后下一个版本又产生新的bug，又遗留到下一个版本，尿性

最重要的是每个bug并没有提供专门的帖子收集现有版本的bug的pr给旧版本的人提供修复

**Comment by bofeng-song** [comment]
This PR has fixed the issue.
https://github.com/cocos/cocos-engine/pull/14448
