### ISSUE TITLE
CC 3.5.2 - The Asset Is Missing! Which asset?

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#12279]
### Use Case

When you remove and clean up your project and by mistake remove an asset which is in use, you will receive an error like this

![image](https://user-images.githubusercontent.com/7983358/181755345-df2a9033-4ab9-4095-8782-bd5b2060f3c1.png)

### Problem Description

This is very good that Cocos reports that something isn't right, but having an UUID for a missing file, doesn't really tell you anything. Since you removed the file, you cannot search for the UUID and since Cocos doesn't give the name of the file you have no clue what file that was.

### Proposed Solution

Could Cocos somehow store the name and UUID of the files attached to be able to present to the user the Name of the missing asset instead of the UUID, because UUID doesn't help you at all.

### Alternatives Considered

Maybe some way in the editor to:
- Scan for unused files
- Scan for issues (places where missing files exist), Now I have to click through all prefabs and scenes to find them
- An easier way to "find UUID usage" as well, since it requires so many clicks to search for a file if it is used and then click away all the "x"-marks in the search box and then move into the next search. It's just cumbersome and slow. Maybe an additional window that you can open to show where this file is used just by clicking on it in the assets window.

**Comment by minggo** [comment]
I think you can search uuid in editor:
![Uploading WeChatWorkScreenshot_1a66dd9c-0c37-4ed4-96f9-f73928b56463.png…]()

**Comment by minggo** [comment]
<img width="282" alt="WeChatWorkScreenshot_1a66dd9c-0c37-4ed4-96f9-f73928b56463" src="https://user-images.githubusercontent.com/488203/182082386-138c3b6e-dd06-4581-8c41-0dd74601f344.png">

**Comment by Ronsku** [comment]
Thanks for your response @minggo!

There are many things listed in this ticket, but what you are suggesting is searching for an UUID. If an asset is removed, so will the meta file including the UUID be. If the link is still setup and you'll get a missing file, you won't be able to find the file by UUID. That's why there needs to be a name linked as well in addition to the UUID.

The other feature suggestions I mentioned is a separate window that you could immediately see "find usage". Just by clicking on an asset in the asset window, the other "find usage"-window would show in which scena or prefabs the asset is used.

The third thing mentioned is "find unused assets". A way to easily locate every asset in a project that has no linking to any scene or prefab. This would make it very easy to clean up a project from uneccesary files.

There isn't either a way to locate scenes and prefab errors, you have to click through them all to get error in the logs to find where the missing asset linking is. It's just complicated and manual, when it doesn't need to be.

**Comment by minggo** [comment]
@Ronsku sorry, i have not idea about these suggestions. 
@jareguo could you please take a look?

**Comment by jareguo** [comment]
@Ronsku Thanks for the report. This is indeed a legacy issue that we will address as soon as possible. We suggest you use this method to search for resources that use a uuid:
![image](https://user-images.githubusercontent.com/1503156/182622356-e9588aa9-05b0-4892-8cb0-1fd06945639c.png)

> * An easier way to "find UUID usage" as well, since it requires so many clicks to search for a file if it is used and then click away all the "x"-marks in the search box and then move into the next search.

Is this the interface you are talking about?

![image](https://user-images.githubusercontent.com/1503156/182622978-ae9ecd3d-a307-468f-b085-d9c7a0e70800.png)

**Comment by Ronsku** [comment]
I will create a demo where you can replicate all the cases in this ticket to understand it better 👍

**Comment by Ronsku** [comment]
I'm on vacation, I will create the demo after returning back to work after 5.9

**Comment by Ronsku** [comment]
I'm not sure if we need a demo project more than this. Broken link and this is the error you get
![image](https://user-images.githubusercontent.com/7983358/191803626-6cad92f1-ddb6-4f87-acf2-ec0d8e731acd.png)

**Comment by jareguo** [comment]
Thanks! Tracking of this issue has been established, and these information will be further optimized.

**Comment by yanOO1497** [comment]
@Ronsku  Hi, the missing asset error has been optimised in version 3.9, thank you for your feedback.

![image](https://github.com/cocos/cocos-engine/assets/27424848/775938aa-9454-4a61-89e1-4b6913160be7)

**Comment by Ronsku** [comment]
> @Ronsku Hi, the missing asset error has been optimised in version 3.9, thank you for your feedback.
> 
> ![image](https://user-images.githubusercontent.com/27424848/243929988-775938aa-9454-4a61-89e1-4b6913160be7.png)

That's amazing! Thank you so much, big improvements! 💪😊
