### ISSUE TITLE
Default preview settings of simulator are not reasonable.

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#12278]
Currently, the default preview settings of simulator are:
<img width="796" alt="WeChatWorkScreenshot_0ad0d010-0a99-411c-ad86-4a775a77ca7a" src="https://user-images.githubusercontent.com/488203/181749148-a2b80f0d-ec8d-49f1-af53-571090425235.png">

So when preview with simulator, it will
- open devtools
- blocked by devtools
- should click run button in devtools to continue

I think it is not reasonable, expected default behavior is: can preview in simulator without any block, just one click is enough.

**Comment by PPpro** [comment]
fixed https://github.com/cocos/cocos-editor/commit/b6c0076125646171bace0e417ae6c5a0afeac68f
