### ISSUE TITLE
2DParticle System doesn't render sprite frame if the same asset is being used by another sprite component (in another node) in the same scene

### ISSUE THREAD

**Issue by khoonlincha** [cocos/cocos-engine#12304]
### Cocos Creator version

2.4.7, 2.4.8, 2.4.9

### System information

MacOS 11.6.1, Chipset: Apple M1, Memory: 16GB

### Issue description

当某资源被同一场景的 `Sprite` 节点及 `Particle System` 节点所使用时，无论这俩节点是什么关系与渲染次序先后（只要是在同一场景内），2D粒子系统将无法正确地渲然该资源，而 `Sprite` 节点则往往不受影响。

https://user-images.githubusercontent.com/33044812/182519398-77910b35-e3dc-49e8-b213-8d0f1da8f85d.mp4

而根据draw call数目来看，粒子系统确实是在渲染着某些东西，因为只要将场景内的粒子节点关闭，draw call就会少了一个。

Both particle node and sprite node are active:
<img width="286" alt="Screenshot 2022-08-03 at 11 47 51 AM" src="https://user-images.githubusercontent.com/33044812/182519904-ab333293-b109-4f34-a68b-fd24f5dafab0.png">

Only sprite node is active:
<img width="293" alt="Screenshot 2022-08-03 at 11 47 34 AM" src="https://user-images.githubusercontent.com/33044812/182519911-e2c9b234-bbfd-41cf-9d23-1d0b9807093b.png">

此情况是无论节点关系或次序都会发生。我尝试了改个顺序，各自加个不一样的父节点，把两个节点归在同一个父节点下等等，此问题都会发生。

有没有可能是两个节点位置重叠了并且 `Sprite` 节点渲染顺序靠后，所以遮盖了粒子节点？
---
我试过了把Sprite节点的scale设为0，也是没看到粒子。而且此问题是**无论节点顺序如何**都会发生。
两个节点位置就算不重叠，粒子也不会被显示

有没有可能是粒子系统没有被启动？
---
我试过了使用 `playOnLoad` 来自动启动粒子系统，也试过了使用代码 `resetSystem()` 来启动粒子系统，结果还是如视频所示：只要把 `Sprite` 节点关了，粒子资源就会正常显示，反之亦然。

### Steps to reproduce

1. 使用 2.4.7 （或以上，v3以下）的编辑器
2. 创建一场景
3. 准备一图片资源A
4. 创建一节点，为其加个 `cc.Sprite` 组件，把资源A设为此组件的贴图
5. 创建另一节点，为其加个 `cc.ParticleSystem` 组件，勾选 `Custom` 选项并也把资源A设为此组件的贴图
6. 在粒子系统里勾选 `Play On Load` 选项
7. 这两个节点的坐标及顺序都可随意，并不影响问题的触发
8. 保存此场景。开启场景预览以测试结果。

### Minimal reproduction project

[Test_Project.zip](https://github.com/cocos/cocos-engine/files/9247890/Test_Project.zip)

**Comment by zxx43** [comment]
![图片](https://user-images.githubusercontent.com/3156403/186053701-04f0a08a-5715-4642-bd8f-44ecb5a6abd6.png)
do not open the packable option when particle and sprite using the same image

**Comment by khoonlincha** [comment]
@zxx43 noted, thanks bro.
