### ISSUE TITLE
A bug in system-event

### ISSUE THREAD

**Issue by koyoter** [cocos/cocos-engine#12310]
https://github.com/cocos/cocos-engine/blob/85059956345ecae3a5e5612be8804cf44b7b47e6/cocos2d/core/event/system-event.js#L146

如果游戏逻辑先通过 cc.internal.eventManager.addListener 添加键盘事件（需要事件权重和停止冒泡功能）
后续通过 cc.systemEvent.on(cc.SystemEvent.EventType.KEY_UP) 注册的事件就不会再响应了，因为 systemEvent 判断逻辑过不了了。

**Comment by PPpro** [comment]
eventManager 作为内部接口，从 2.x 开始就已经废弃不建议使用了哈，请勿使用该接口来注册输入事件回调，
建议使用 input 接口，详情请参考
https://docs.cocos.com/creator/manual/zh/engine/event/event-input.html?h=input

感谢反馈
