### ISSUE TITLE
[3.6.0-080401] The editor reports an error when the Tiled Sprite size is large

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12341]
### Cocos Creator version

3.6.0-080401

### System information

--

### Issue description

https://forum.cocos.org/t/topic/138413

### Steps to reproduce

Error [Scene] Invalid typed array length: 63504 for modifying the tiled size of an image to 15000*15000

**Comment by pandamicro** [comment]
https://docs.cocos.com/creator/manual/zh/ui-system/components/engine/ui-batch.html#v341-%E4%B9%8B%E5%90%8E

版本限制，需要调节 BATCHER2D_MEM_INCREMENT
