### ISSUE TITLE
Label color is not correct when char mode used

### ISSUE THREAD

**Issue by SantyWang** [cocos/cocos-engine#12356]
Label color is not correct when using char mode and color is not white

**Comment by SantyWang** [comment]
https://github.com/cocos/cocos-engine/pull/12355

**Comment by gdoudeng** [comment]
The problem still exists in 3.6.1
https://forum.cocos.org/t/topic/140371/8?u=1774358245

**Comment by gdoudeng** [comment]
@holycanvas
