### ISSUE TITLE
bundle use a Chinese name，report error

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12388]
### Cocos Creator version

3.5.2

### System information

window10，chrome

### Issue description

https://forum.cocos.org/t/topic/138635
![image](https://user-images.githubusercontent.com/40415168/183883618-a3e02ee1-70cc-40a0-a605-cb2c15b8c341.png)

![image](https://user-images.githubusercontent.com/40415168/183883787-010308c8-7434-4bf1-a86b-dfbfe3b6fc5f.png)
![image](https://user-images.githubusercontent.com/40415168/183883843-202fd964-2302-4344-ae9d-2c69a46b17a4.png)

### Steps to reproduce

test code:
![image](https://user-images.githubusercontent.com/40415168/183884399-7d407aa0-864a-4248-bab0-0d1d3a5b54bd.png)

**Comment by SantyWang** [comment]
@yanOO1497 please help to handle special character input
