### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'x')

### ISSUE THREAD

**Issue by tandanchendu** [cocos/cocos-engine#12393]
### Cocos Creator version

3.3.2

### System information

win10

### Issue description

![TGTQ)XX@`BKL@8%U9CJO)T3](https://user-images.githubusercontent.com/42135824/184077354-c9bb302f-938a-4041-9116-6e091f7f2cc6.png)

### Relevant error log output

![Q6B{_`MIVO406C0RSJHR8~R](https://user-images.githubusercontent.com/42135824/184077410-c019a7fc-47e2-43e3-b3a2-2c5379ca33bc.png)

### Steps to reproduce

Sprite平铺模式下update里不断修改图片宽度，概率出现这个错误，貌似越界了，也有可能是改变了宽度按但datalist数据没更新导致。
路径
cocos-engine/cocos/2d/assembler/sprite/tiled.ts

**Comment by tandanchendu** [comment]
cocos-engine/cocos/2d/assembler/sprite/tiled.ts

**Comment by tandanchendu** [comment]
![({S0DM6VXFQ1_HN4 YHA`N7](https://user-images.githubusercontent.com/42135824/184082987-1d1a46cf-816a-4a1f-8a27-0bd0011d3e4d.png)
加个限制应该暂时可以了

**Comment by tandanchendu** [comment]
可能是因为直接通过获取UITransform修改width属性导致的，改成修改节点width属性。

**Comment by LinYunMo** [comment]
未能复现，结构已经发生变化，麻烦再出现时重新反馈，感谢
