### ISSUE TITLE
Label rendering on iOS is not consistent with the editor display

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#12411]
### Cocos Creator version

3.4.2,3.6.0

### System information

iOS

### Issue description

Problems with both bold and italic.

Editor:
![image](https://user-images.githubusercontent.com/8321365/184299879-ebb54140-9e35-4d9e-98a1-022a674cfdd2.png)

iOS:
![a7cce58284ec03a22e3cb95832786fd](https://user-images.githubusercontent.com/8321365/184299987-0614cb70-710c-4b24-8a02-ab3cb950cdf4.jpg)

### Steps to reproduce

build iOS app and run.
[test-2.zip](https://github.com/cocos/cocos-engine/files/9314294/test-2.zip)

**Comment by bofeng-song** [comment]
fixed at this pr
https://github.com/cocos/cocos-engine/pull/12421.

Bold has been supported at v3.6.0
