### ISSUE TITLE
Switching background music main threads Stuck for three seconds

### ISSUE THREAD

**Issue by jianglixin85** [cocos/cocos-engine#12438]
### Cocos Creator version

3.6.0

### System information

android

### Issue description

安卓播放背景音乐卡3秒，主线程卡死，3秒后正常，在3.4.2没问题，在3.6.0会出现

### Steps to reproduce

swtich music

**Comment by jianglixin85** [comment]
[Test3.6Audio.zip](https://github.com/cocos/cocos-engine/files/9348767/Test3.6Audio.zip)

**Comment by timlyeee** [comment]
fixed
