### ISSUE TITLE
[3.6.0 - 080521]  Build ios project in xcode emulator for ios 12.4 devices, runs with a crash

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12437]
### Cocos Creator version

3.5.2、3.6.0-080521

### System information

xcode simulator, ios12.4

### Issue description

https://discuss.cocos2d-x.org/t/ios-simulation-build-error/56838

### Relevant error log output

<img width="1280" alt="图片" src="https://user-images.githubusercontent.com/35944775/184819456-45adf325-6df9-43a8-9118-41092162de80.png">

### Steps to reproduce

https://discuss.cocos2d-x.org/t/ios-simulation-build-error/56838

**Comment by novain1102** [comment]
iOS simulator DO NOT support below 13.0; Please choose iOS simulator version above 13.0;

related disscussion: https://forum.cocos.org/t/topic/137230

**Comment by minggo** [comment]
@mmyduckx i think we should mention it in some doc, and describe the reason.

**Comment by mmyduckx** [comment]
> 

I'll check the document later

**Comment by novain1102** [comment]
> @mmyduckx i think we should mention it in some doc, and describe the reason.

I'll check the document later
