### ISSUE TITLE
Use freetype to implement label rendering

### ISSUE THREAD

**Issue by bofeng-song** [cocos/cocos-engine#12433]

**Comment by stanleyljl** [comment]
support bitmap font and freetype font

**Comment by bofeng-song** [comment]
Need to support text auto wrap and spacing setting
https://github.com/cocos/cocos-engine/issues/11829

**Comment by bofeng-song** [comment]
Consider the support of small games

**Comment by bofeng-song** [comment]
Goal: Remove Label's dependency on Canvas

Feature request:
    Supported fonts: freeType(.ttf) and bitmap font(.fnt)
    Italic: italic
    Support bold: bold
    Support underline
    Support background box on Label (similar to Context2d, fillRect & clearRect)
    Support for automatic text line breaks and no word truncation
    Web-side and native-side implementation is consistent (whether to consider the package body)

Implementation options:
    Principle: Prefer to use the platform built-in fonts supported by italic, bold, etc.
    System built-in fonts cross-platform interface: load, getFontPath
    clearRect & fillRect, underline: Execute a draw call before text rendering
    italic(not supported): skews the rectangle with four vertices
    bold(font not supported), outline, shadow: bold changes strokeWidth according to fontSize and is implemented with a stroke, with the advantage that the current label's shader can be reused
    bold and outline, shadow can refer to 2.x implementation, need to change the current shader

The current attempt (based on DebugRenderer): 
Normal state & italic
![normal](https://user-images.githubusercontent.com/3078423/188126583-dd620548-feeb-4427-a9f7-f340e4fb95f6.png)
Bold width set to 1.5 pixel ![bold_1 5](https://user-images.githubusercontent.com/3078423/188126686-ad46861d-63c9-4d4e-ae65-582bf0757cc9.png)
Bold width set to1 pixel ![bold_1](https://user-images.githubusercontent.com/3078423/188126758-9c509e61-a88b-4d0f-bb3a-661c7fa737f1.png)
Outline ![outline](https://user-images.githubusercontent.com/3078423/188126797-d4edd399-e10f-43a1-ab34-08271d692c06.png)
Shadow offestX & offsetY set to 2  ![shadow_2_outline](https://user-images.githubusercontent.com/3078423/188126844-44f721af-c2d4-4a27-8057-d63b8bc1a5dd.png)
Shadow offestX & offsetY set to 3   ![shadow_3_outline](https://user-images.githubusercontent.com/3078423/188126903-a7181eb2-c578-41c5-9f4c-2ef63920dc2c.png)

**Comment by bofeng-song** [comment]
1. If DebugRenderer's solution is used.
    Will the effect of shadow meet the requirements?
    Need two drawCall, one is rectangle drawing (if there is a call to fillRect or call clearRect), the other is font drawing

2. If the 2.x solution is used.
    Need three drawCall, one for rectangle (if fillRect is called or clearRect is called), one for shadow, and one for stroke + font

**Comment by LinYunMo** [comment]
Re：https://github.com/cocos/3d-tasks/issues/15357
