### ISSUE TITLE
Script compiler support for TypeScript 4.7+

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#12447]
### Use Case

Directly using 4.7 variance comments does not affect compilation, but using 4.3 override does not compile, both of which are very important.

### Problem Description

Is it compatible with TypeScript 4.7, or at least 4.3?
Contributes to the maintainability of the project.

### Alternatives Considered

There is no alternative but to not use override.

**Comment by PPpro** [comment]
we need to upgrade the babel, this will be considered in v3.7 or later

I put this issue in v3.7 milestone for now

**Comment by 3dos** [comment]
Hi guys, I see the issue is still opened but it looks like `override` works on 3.7.2 so maybe this issue can be closed and marked as done in the v3.7 milestone.

**Comment by dumganhar** [comment]
@smallmain Thanks for report the issue.

I also confirm that `override` works in 3.8.2. 

> Directly using 4.7 variance comments does not affect compilation

Could you describe more about this? Some code snippet is better.

**Comment by smallmain** [comment]
> @smallmain Thanks for report the issue.
> 
> I also confirm that `override` works in 3.8.2.
> 
> > Directly using 4.7 variance comments does not affect compilation
> 
> Could you describe more about this? Some code snippet is better.


Variance notes:
```ts
class A<out T> {
justIt: T;
}
console.log(new A());
```
This is not a problem, I mean variance annotations are OK, but `override` is not supported.
But now that it compiles normally, this post is out of date and it's time to request an update to 5.3+: https://github.com/cocos/cocos-engine/issues/16573
