### ISSUE TITLE
Status of CCUI?

### ISSUE THREAD

**Issue by ntrrgc** [cocos/cocos-engine#1244]
I've seen CCUI files are included in the repo and have some changes from upstream (e.g. usage of `require()`), but they are not linked in `index.js` for compilation.

Is CCUI supported in this fork? Is it planned, dropped or deprecated...? Is it usable already and maybe I'm missing something?

Regards.

**Comment by jareguo** [comment]
CCUI has been dropped...

**Comment by ntrrgc** [comment]
Why? What's the alternative? Will this change impact upstream cocos2d-html5?

**Comment by jareguo** [comment]
Because creator implemented its own UI system based on Component. This will not change cocos2d-html5.

**Comment by ntrrgc** [comment]
Why? What's the alternative? Will this change impact upstream?

**Comment by jareguo** [comment]
Because creator implemented its own UI system based on Component. This will not change cocos2d-html5.
