### ISSUE TITLE
Failed to play oneshot audio

### ISSUE THREAD

**Issue by 2youyou2** [cocos/cocos-engine#12455]
### Cocos Creator version

3.6

### System information

windows web, mac web

### Issue description

exists several same audio which cause failed to play oneshot audio

![image](https://user-images.githubusercontent.com/1862402/185101027-04f1607c-f998-423b-8a33-ce10bdc2d7b1.png)

the callback was called after destroying audio source, the properties are all be null.

![image](https://user-images.githubusercontent.com/1862402/185100722-069ae705-be35-4dab-a51f-4334a6963946.png)

### Steps to reproduce

destroy an audio source and debugging the stop function

**Comment by timlyeee** [comment]
Fix with pull request.
