### ISSUE TITLE
[3.6.0] Using SHARED_CACHE or PRIVATE_CACHE after a spine animation has a mesh and a mask will cause a rendering exception

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12451]
### Cocos Creator version

3.6.0

### System information

all

### Issue description

https://forum.cocos.org/t/topic/138902

### Steps to reproduce

After the spine animation is meshed and masked, use SHARED_CACHE or PRIVATE_CACHE

**Comment by zhakesi** [comment]
非新引入问题，3.x 均有此问题

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13525
