### ISSUE TITLE
rendertexture display exception

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#12453]
### Cocos Creator version

3.6.0,3.5.2,3.4.2

### System information

macOS 12.4, Chrome  Or Windows 10, Windows GLES2/3

### Issue description

For the first time, set the 3D camera's target texture renderTexture to the sprite in start.
The second time, clear the camera's target texture and hide the sprite node and reset the camera target texture and show the sprite node.
The first time and the second time, the displayed effect is different.

### Steps to reproduce

1. Render the rendered content of the 3D camera to the rendertexture, and then mount the rendertexture to the sprite component
![87F30A6FC1CCB5DAE5948CB00CFFB9D2](https://user-images.githubusercontent.com/14273437/185097990-fb75887b-dc68-4ec3-bd43-3392f2bd24dc.png)

2. click the button (it will clear the targetTexture of the 3D camera and set the node active of the sprite component to false)
3. click the button (will set the 3D camera's targetTexture to rendertexture again and mount the rendertexture to the sprite component)
4. the picture shows the top and bottom upside down.
![B574DC65A9D857C87A577DCDEFD356D9](https://user-images.githubusercontent.com/14273437/185098042-f0f499e9-bb77-4ce2-8d39-7a8a71f4023c.png)

### Minimal reproduction project

[NewProject360.zip](https://github.com/cocos/cocos-engine/files/9358805/NewProject360.zip)

**Comment by troublemaker52025** [comment]
![图片](https://user-images.githubusercontent.com/20809296/203689445-1fe918eb-a087-4f7f-b217-106fb3127ae5.png)
