### ISSUE TITLE
[CocosCreator 3.6.0] Slower loading of 3D particles compared to Creator 3.5.0

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12454]
### Cocos Creator version

3.5.2、3.6.0

### System information

All

### Issue description

https://forum.cocos.org/t/topic/138911/

### Steps to reproduce

[3.5.0 demo](https://forum.cocos.org/uploads/short-url/5i3aDp6YeKwu66Lhx8abe3tfWYB.zip)

[3.6.0 demo](https://forum.cocos.org/uploads/short-url/rKkL7hf1JUr9LtqjefknQfOHUgI.zip)

**Comment by SantyWang** [comment]
@zxx43 please have a check

**Comment by SantyWang** [comment]
The performance degradation is reasonable, the previous 3.5 version incorrectly reused objects and created less objects，and it had been fixed in https://github.com/cocos/cocos-engine/pull/11052
