### ISSUE TITLE
[3.6.0] NodeJS is not found in $PATH (Native Plugins feature)

### ISSUE THREAD

**Issue by patrick-fu** [cocos/cocos-engine#12456]
### Cocos Creator version

3.6.0

### System information

macOS Editor (Mac with M1 chip, macOS 12.5), build for Android

### Issue description

Hi, I'm trying the [Native Plugins](https://docs.cocos.com/creator/manual/en/advanced-topics/native-plugins/brief.html) feature launched in Cocos Creator v3.6.0, and playing the demo [https://github.com/PatriceJiang/ccplugin_tutorial](https://github.com/PatriceJiang/ccplugin_tutorial)

I have try to build for iOS / macOS and they works well

But when I build for android, the native plugin can not be compiled due to `"NODE_EXECUTABLE" is not found`

I try to add some log in the CMakeList.txt:

```cmake
message(STATUS "hello_cocos_glue PATH: '$ENV{PATH}'")
message(STATUS "hello_cocos_glue SHELL: '$ENV{SHELL}'")
```

And the "build_output.txt" shows:

```txt
hello_cocos_glue PATH: '/usr/bin:/bin:/usr/sbin:/sbin'
hello_cocos_glue SHELL: '/bin/zsh'
.....
Try generating /Users/patrickfu/code/ccplugin_tutorial/NewProject/native/engine/android/Pre-AutoLoadPlulgins.cmake
NodeJS is not found in $PATH, skip searching native plugins.
.....
```

So it seems like that the problem is when the Android Studio running `cmake` with gradle sync, it does not use my "PATH" env which defined in both `~/.zprofile` and `~/.zshrc` (I have `node` installed by homebrew which located in `/opt/homebrew/bin` )

Maybe cocos engine can add some program search path in [predefine.cmake](https://github.com/cocos/cocos-engine/blob/9ddae58790111249c3d832f1bf80d7d2f286bcd2/native/cmake/predefine.cmake#L224) 

```cmake
find_program(NODE_EXECUTABLE NAMES node) // Add several common path like /usr/local/bin:/opt/homebrew/bin ?
find_program(TSC_EXECUTABLE NAMES tsc)
find_program(CCACHE_EXECUTABLE NAMES ccache)
```

Or maybe I have make something wrong with Android Studio?

### Relevant error log output

```
Try generating /Users/patrickfu/code/ccplugin_tutorial/NewProject/native/engine/android/Pre-AutoLoadPlulgins.cmake
NodeJS is not found in $PATH, skip searching native plugins.
```

### Steps to reproduce

1. Clone [https://github.com/PatriceJiang/ccplugin_tutorial](https://github.com/PatriceJiang/ccplugin_tutorial)
2. Open the project with Cocos Creator v3.6.0
3. Build for Android (export the android project)
4. Open the exported android project, then run gradle sync

### Minimal reproduction project

https://github.com/PatriceJiang/ccplugin_tutorial

**Comment by PatriceJiang** [comment]
The env var `PATH` seems to be incorrect. Can you try to open Android Studio through Terminal or run Make on the build panel?

**Comment by patrick-fu** [comment]
`open -a Android\ Studio` solves this problem, but I think there should be a better solution, for example, simply add a fallback strategy when the `find_program()` failed, like:

```cmake
find_program(NODE_EXECUTABLE NAMES node)
if("${NODE_EXECUTABLE}" STREQUAL "NODE_EXECUTABLE-NOTFOUND")
if(APPLE)
find_program(NODE_EXECUTABLE NAMES node "/usr/local/bin" "/opt/homebrew/bin")
endif()
endif()
```

**Comment by PatriceJiang** [comment]
> ```cmake
> find_program(NODE_EXECUTABLE NAMES node "/usr/local/bin" "/opt/homebrew/bin")
> ```

This does increase the success rate of find_program execution 👍.  
Cocos Creator is based on Electron, and I create a PR [here](https://github.com/cocos/cocos-engine/pull/12486),  that allows developers to specify the path to NodeJS, and in the worst case fallback to electron's NodeJS executable. Idea of the PR is not conflict with yours.

`NodeJS` will be optional then.

**Comment by patrick-fu** [comment]
Looks great! 🤩

**Comment by patrick-fu** [comment]
Still not work on v3.6.1,  seems like the "EDITOR_NODEJS" variable has not been defined
<img width="826" alt="企业微信截图_3cf350ba-507f-4946-9530-27268cb5e7c1" src="https://user-images.githubusercontent.com/20736775/192672544-726f511b-636d-4535-90c2-939150686d45.png">

**Comment by PatriceJiang** [comment]
The Editor_Nodejs is not a regular nodejs executable, and this change has been reverted. Developers still need to set `NODE_EXECUTABLE` manually if it is not found in ENV

common/CMakeLists.txt
![image](https://user-images.githubusercontent.com/40414978/192674414-4c5f6906-0174-46bf-93ce-394a3d5d7429.png)

I will update the document later.

**Comment by patrick-fu** [comment]
🤔 I think it is not a good idea to set the path of "node" in project's cmake file, it destroys portability and is not suitable for team collaboration @PatriceJiang

**Comment by PatriceJiang** [comment]
Yes, it is a temporary solution.  I will add an entrance for  developers to override options in cfg.cmake on each device.

**Comment by PatriceJiang** [comment]
Developers can set `NODE_EXECUTABLE` in `native/engine/common/localCfg.cmake`.
