### ISSUE TITLE
Draw call will not decrease on Android when opacity=0

### ISSUE THREAD

**Issue by AndroidSix** [cocos/cocos-engine#12469]
### Cocos Creator version

3.6.0

### System information

Android

### Issue description

When the opacity is 0, the browser DC will drop, which doesn't happen on Android. .
This seems to be a native issue

### Steps to reproduce

When node opacity=0

**Comment by jareguo** [comment]
Related feedback https://forum.cocos.org/t/topic/138885

**Comment by pandamicro** [comment]
duplicated with https://github.com/cocos/cocos-engine/issues/11210
