### ISSUE TITLE
9-Sliced SpriteFrame rendering issue

### ISSUE THREAD

**Issue by SantyWang** [cocos/cocos-engine#12472]
https://forum.cocos.org/t/topic/137747/674?u=jare

**Comment by Zhmz** [comment]
![cb4fbd5cbca4f3d8666ae88a9fa7dba2](https://user-images.githubusercontent.com/32831993/190106768-331d359f-13f5-457b-955c-34568b74ac39.jpg)
最新3.6.1验证无误
