### ISSUE TITLE
Cocos Creator 3.6.0 - plist is broken

### ISSUE THREAD

**Issue by arathore-gaming** [cocos/cocos-engine#12476]
### Cocos Creator version

3.6.0

### System information

Windows 11

### Issue description

I am using an atlas (`.plist`) and trying to change sprite frames on runtime based on diffrent conditions in a game.
The name of atlas is `clolliders` and it has got multiple sprite frames like  `Left_2` , `Left_2_active` etc.

The issue is when I try to get the `spriteAtlas` via following code the name field of `spriteFrames` is wrong- 

```
selfCollider.node.getComponent(Sprite).spriteAtlas
```
![image](https://user-images.githubusercontent.com/6205629/185556856-da72d81a-6e93-4920-9ef7-3bce55cb59c6.png)

Frame names looks fine inside UI Editor -
![image](https://user-images.githubusercontent.com/6205629/185557082-5004e34a-598d-4786-802a-c9dd45ea20be.png)

This was working fine in Cocos Creator version 3.5.x, following is the output of same code with v 3.5.2
![image](https://user-images.githubusercontent.com/6205629/185558567-f7ba0ffe-763c-4c12-bb85-3b90991bfed7.png)

### Steps to reproduce

Because of the change in name property the code which was working fine in 3.5.2 now doesn't works in 3.6.0

Actual result: `name: "clolliders"`
Expected Result: `name: <Should contain relevant name of sprite frame>`

**Comment by arathore-gaming** [comment]
@jareguo Any update on this?

**Comment by yanOO1497** [comment]
@arathore-gaming 

It's seems good in v3.7.0 , you can try in the new version. 

![image](https://user-images.githubusercontent.com/27424848/205861031-2f6fdeed-0154-4f4a-8636-bd780b2f1f12.png)
