### ISSUE TITLE
[2.4.7] Build-Failed: Error: Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12487]
### Cocos Creator version

2.4.7、2.4.9

### System information

mac

### Issue description

https://forum.cocos.org/t/topic/138322 、 https://forum.cocos.org/t/too-many-open-files/39641/10

### Steps to reproduce

Not currently available

**Comment by zhefengzhang** [comment]
User feedback says that there are more than 30,000 resources in the bundle.

**Comment by zhefengzhang** [comment]
![图片](https://user-images.githubusercontent.com/35944775/185598657-2d6ca20b-b9e6-4377-841e-fc2cb9bdb44a.png)

**Comment by jareguo** [comment]
3.x 最近好像没收到同类反馈了，如果有的话帮忙关注一下，2.x 就不考虑修复了。
