### ISSUE TITLE
When the playOnAwake of the AudioSource component is true and the node's first active is false, the subsequent setting of active to true has no sound

### ISSUE THREAD

**Issue by zhangyizhang** [cocos/cocos-engine#12492]
### Cocos Creator version

3.6.0

### System information

html5

### Issue description

![image](https://user-images.githubusercontent.com/26247903/185673972-23f5c7ad-cb86-4ff9-89af-1cd8a7832a24.png)
I think the code in the red box should be moved to the blue box

### Steps to reproduce

When the playOnAwake of the AudioSource component is true and the node's first active is false, the subsequent setting of active to true has no sound

**Comment by timlyeee** [comment]
Seems like the priority of Node activate is higher, and some part of callback is missing.

**Comment by zhangyizhang** [comment]
Because _syncPlayer is called in onload and this._lastSetClip === clip, _isLoaded is always false

**Comment by timlyeee** [comment]
I'm not sure if my way to reproduce the issue is right, I've tried like below: 
```ts
@ccclass('activate')
export class activate extends Component {
    @property(Node)
    nodeToActivate: Node | null;
    start() {
        this.nodeToActivate.active = true; //Here to activate the audio source node.
    }

    update(deltaTime: number) {
        
    }
}

```

and in editor I manually disable audio source node.
![image](https://user-images.githubusercontent.com/43355299/191900141-97b8bf82-cae1-49b2-8278-d705abd5769d.png)

In that way I didn't reproduce the error.

Could you please show me a demo for this? Thank you @zhangyizhang

**Comment by zhangyizhang** [comment]
[test.zip](https://github.com/cocos/cocos-engine/files/9640832/test.zip)

**Comment by zhangyizhang** [comment]
![image](https://user-images.githubusercontent.com/26247903/192145708-a1ebd5ea-d796-4eb7-bbd1-9ecad9f8dadc.png)

**Comment by zhangyizhang** [comment]
![image](https://user-images.githubusercontent.com/26247903/192145731-1e1b7979-68ef-4a31-b404-11a1eeaf1698.png)
