### ISSUE TITLE
Debug Renderer will crash if use single thread on iOS/macOS

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#12490]
Step to reproduce:
- disable multi-thread
- enable debug renderer
- run a test case on iOS/macOS, then crash

It is because Debug Renderer update buffer after begin render pass.

**Comment by stanleyljl** [comment]
@stanleyljl test

**Comment by stanleyljl** [comment]
@stanleyljl test2

**Comment by stanleyljl** [comment]
@stanleyljl ttt

**Comment by stanleyljl** [comment]
@stanleyljl aaa

**Comment by stanleyljl** [comment]
@stanleyljl ddd
