### ISSUE TITLE
the sleep not use in Physics bullet

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#12508]
### Cocos Creator version

3.5.2,3.4.2

### System information

Windows10

### Issue description

the sleep not use in Physics bullet,
Manual call rigidbody.sleep() is in effect in cannon and PhysX, but not in bullet.

the bug is come from : https://forum.cocos.org/t/topic/138847

### Steps to reproduce

test in case-dynamic :
![image](https://user-images.githubusercontent.com/18083506/185907057-0140db13-a422-46dd-a518-8e8b727be9d3.png)
add code like this:
![image](https://user-images.githubusercontent.com/18083506/185907242-52855ed9-1f92-4a1b-89a4-b0d6b579ed36.png)

**Comment by lealzhan** [comment]
目前使用了错误的接口。
![image](https://user-images.githubusercontent.com/9999378/207776990-236d11cd-930b-4f73-bca5-7dda0b44f68d.png)
