### ISSUE TITLE
The script lifecycle lacks a callback for Pause / Resume

### ISSUE THREAD

**Issue by oahc09** [cocos/cocos-engine#12505]
### Use Case

Referring to Unity, the script contains trigger pullbacks involving the application lifecycle:
OnApplicationFocus(bool hasFocus)	Sent to all GameObjects when the player gets or loses focus.
OnApplicationPause(bool pauseStatus)	Sent to all GameObjects when the application pauses.
OnApplicationQuit	        Sent to all GameObjects before the application quits.

https://docs.unity3d.com/ScriptReference/MonoBehaviour.html

In the scene, for example, there is a UI showing the current network and Bluetooth status. During the use process, jump to the external setting APP, modify the network, change the Bluetooth switch, and then go back to the scene.
You need to refresh the UI state, and this refresh logic needs a trigger  point. Currently in-engine scripts have no similar callback function to support.

Want the script to join the above 3 application lifecycle related trigger callback.

### Problem Description

none

### Alternatives Considered

none

**Comment by minggo** [comment]
@oahc09 please use english in future. Thanks.

**Comment by oahc09** [comment]
> @oahc09 please use english in future. Thanks.

OK

**Comment by oahc09** [comment]
game.on(Game.EVENT_HIDE, function () {
    console.log('game event hide');
    });

game.on(Game.EVENT_SHOW, function () {
      console.log('game event show');
    });


but component's onDestroy will not triggered when app exit
