### ISSUE TITLE
simulator 调试的时候用 SocketIO.connect 报了 Microsoft Visual C++ .exe R6010 abort error

### ISSUE THREAD

**Issue by abos5** [cocos/cocos-engine#1251]
如题

![image](https://cloud.githubusercontent.com/assets/5197118/19831157/b2d25172-9e35-11e6-99c8-2bc64290f340.png)

CCC 1.3.0 console 信息:
![image](https://cloud.githubusercontent.com/assets/5197118/19831173/26065a80-9e36-11e6-9729-bd0f89cb65bb.png)

代码如下:
(在谷歌浏览器下工作正常)
plugin:

``` js
(function (root) {
    // 绑定 dragon planet 的全局库
    let dp = {
        remote: {
            single: null,
            init: function (host) {
                if (cc.sys.isNative) {
                    this.single = root.io.connect(host)
                } else {
                    this.single = root.io(host)
                }
            }
        }
    }
    root.dp = dp
    if (cc.sys.isNative) {
        root.io = SocketIO
    } else if (typeof io === 'undefined') {
        root.io = require('socket.io-client')
    } else {
        root.io = io
    }

})(this)
```

Game.js

``` js
   dp.remote.init('ws://xxx:3000/star');
```

> 备注: sample 里的 network 代码是可以正常执行的

**Comment by abos5** [comment]
根据 sample 1.3 network 里的介绍, 将 socket-io.js 做为plugin, 
且 socketio 的请求 都使用 io.connect('ws://xxx.space:3000') 也是会报 R6010

**Comment by jareguo** [comment]
能不能试试 http scheme?

**Comment by abos5** [comment]
改为 http 之后的 调试信息:

![image](https://cloud.githubusercontent.com/assets/5197118/19835035/78f0849a-9eb4-11e6-8a17-5e83986ace50.png)

 修改之后的代码(在浏览器上是正常运行的): 
![image](https://cloud.githubusercontent.com/assets/5197118/19835037/98c052a0-9eb4-11e6-8337-f3ccf67168cf.png)

**Comment by abos5** [comment]
上面的错误信息是 _直接使用了nginx配置的upstream_, 在 simulator 下handshake失败了;
刚刚改为 host+端口号直连, 现在在simulator里面也正常了...
handshake失败的应该是和我后端socketio, koajs 或者nginx 那边再调一下

但windows的 R6010 这个问题, 代码没有修改, 睡一觉起来就好了...怪怪的
