### ISSUE TITLE
[3.6] Spine cause error on native when Feature Cropping disable DragonBone

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#12539]
### Cocos Creator version

3.6.0

### System information

Window, iOS, Android

### Issue description

in build path, build\windows\data\jsb-adapter\engine-adapter.js has dragbone update code in middleware module. when spine into scene, the middleware module always update dragbone,  the dragbone has been cull out and cause error.

![企业微信截图_16613314456747](https://user-images.githubusercontent.com/8321365/186385032-d6e84456-b709-46f7-aee9-4b586a8201ff.png)

### Steps to reproduce

test on native platform, such as Window 11
[TestOP.zip](https://github.com/cocos/cocos-engine/files/9415043/TestOP.zip)

**Comment by mrtzd** [comment]
I think it's related to this issue #12511

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/12605
