### ISSUE TITLE
Should cache Light in Root?

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#12538]
Light is created and cached in Root. They are not destroyed when switching scenes. There are two questions about it
- Should create/cache Light in Root? Any performance result about it?
- Even need cache Lights in Root, should destroyed them when switching to a new scene?

**Comment by jk20012001** [comment]
should delete some objects which are unused for a long time

**Comment by star-e** [comment]
Light management might be refactored in 3.8.5.
Will open a new issue about light management, deferred rendering and ray tracing.
