### ISSUE TITLE
Graphical glitches, broken physics and more issues after upgrade to v3.6.0

### ISSUE THREAD

**Issue by mrtzd** [cocos/cocos-engine#12543]
### Cocos Creator version

3.6.0

### System information

Windows 10 Editor

### Issue description

So recently I upgraded my game from v3.5.2 to v3.6.0. After solving my initial problem (#12511) I'm having so many other problems with my game. These issues occur while running on an Android device and not in browser preview.

- There are random graphical issues everywhere and my characters disappear randomly:
  ![Screenshot_2022-08-24-14-23-36-900_com morteza](https://user-images.githubusercontent.com/82378750/186397965-8fde330a-4e51-405b-b58a-de864fce5d83.jpg)

- The 2D physics are broken and collisions don't work properly anymore.

- 2D particles don't work.

- The mobile back button event doesn't work anymore.

### Steps to reproduce

Unfortunately I can't share my whole project so I'll see if I can reproduce these issues with simpler demos when I have more time. Right now I'm probably going to stick with v3.5.2 for a while as it seems like there's so many incompatibilities with v3.6.0.

**Comment by minggo** [comment]
Thanks for feedback, and sorry about the incompatibility. Did you inherits some engine class, such as Node, and override something. I native, you can not modify. returned readonly properties.

**Comment by minggo** [comment]
And any error log?

**Comment by mrtzd** [comment]
Since some of these issues have already been fixed in v3.6.1 I'll close this issue and will create new issues for the remaining problems.
