### ISSUE TITLE
TS device add new api InvalidateState

### ISSUE THREAD

**Issue by oahc09** [cocos/cocos-engine#12568]
### Use Case

for example:

Device.InvalidateState

Invalidate the internally cached render state.

This invalidates any cached render state tied to the active graphics API. If for example a (native) plugin alters the render state settings then rendering engine must be made aware of that.

use case : 
Android Platform : draw video texture/camera texture to 3d ui
in component's update, we call c++ function updateTexture (in this function we execute gl draw command to render external texture to normal texture used by 3d ui), after this operation we need call invalidatestate api to notify render engine the render state has changed.

### Problem Description

none

### Alternatives Considered

none

**Comment by pandamicro** [comment]
Related request: https://github.com/cocos/cocos-engine/issues/13832

**Comment by star-e** [comment]
Currently not supporting video texture.
