### ISSUE TITLE
cc.tween error in gameview jogging on color.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#12581]
### Cocos Creator version

3.6.0

### System information

Mac Editor

### Issue description

![image](https://user-images.githubusercontent.com/28684663/187056556-420fe26d-9868-48cd-b409-ecf4afab8fa3.png)

```ts
if(EDITOR)
```

This judgement doesn't work in GameView, it still walks in, the tween is constructing a dummy object to set, which is also a problem.

### Steps to reproduce

rt.

**Comment by smallmain** [comment]
There is a problem with my screenshot, the code is in ui-renderer.ts.

```ts
        set color(value) {
          if (this._color.equals(value)) {
            return;
          }

          this._color.set(value);

          this._updateColor();

          if (EDITOR) {
            const clone = value.clone();
            this.node.emit(NodeEventType.COLOR_CHANGED, clone);
          }
        }
```

**Comment by dogeFu** [comment]
EDITOR is true in GameView mode.You should use cc.GAME_VIEW

**Comment by dogeFu** [comment]
```
 if (EDITOR) {
      const clone = value.clone();
      this.node.emit(NodeEventType.COLOR_CHANGED, clone);
}
```
This code didn't change _color property of ui-renderer. Any details of the tween error?

**Comment by smallmain** [comment]
As I recall it should be Fake objects do not have a clone function
