### ISSUE TITLE
[3.6.0] AnimationController component controls the model animation, which causes display exceptions on facebook app and wechat browser.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12593]
### Cocos Creator version

3.6.0

### System information

ios 15.6.1，WeChat 8.0.26

### Issue description

https://forum.cocos.org/t/topic/139366

### Steps to reproduce

https://forum.cocos.org/t/topic/139366

### Minimal reproduction project

[AnimationController.zip](download.cocos.org/CocosTest/zhefengzhang/NoDelete/AnimationController.zip)

**Comment by zhakesi** [comment]
初步定位该问题由ios系统版本兼容问题导致.
ios15.4.1 之前的版本无问题
ios 15.6.1 之后的版本有此问题

ios系统版本升级后，deviceManager.gfxDevice.capabilities.maxVertexUniformVectors与实际可以使用的UniformVectors数量不匹配(根据测试最多支持62根骨骼)

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13979
