### ISSUE TITLE
spine crash

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#12597]
### Cocos Creator version

3.4.2, 3.6.0

### System information

window10, huaweiP30pro

### Issue description

The crash is in the MiddlewareManager.cpp redner or update, the specific reason is render or update polling a _updateList element, the element is a spine but the spine's resources have been released, resulting in a wild pointer on the C++ side. The reason is that the spine is a spine, but the resource of the spine has been freed. According to our research, the process is as follows
1 there are 2 nodes, parentNode and childNode, childNode has a spine component, the game will add childNode as a child node to parentNode, if childNode.parent = parentNode before the execution of this line of code childNode or parentNode is false, when the parentNode is removed (parentNode.destroy()), the onDestroy() of the Skeleton component on the childNode cannot be executed.
2 native, create a spine, which will be added to _updateList by MiddlewareManager::addTimer, and destroyed by this._ in onDestroy() of jsb-spine-skeleton.js nativeSkeleton.stopSchedule() to MiddlewareManager::removeTimer from _updateList, because in this case of 1 above Skeleton's onDestroy is not executed, so it cannot be removed from _updateList. updateList, so when the childNode is destroyed, the spine resource on the node is destroyed but the MiddlewareManager's _updateList still holds the spine, so when the MiddlewareManager's render or update is executed, it will crash.

Have upgraded to 3.6.0 test will also have this problem.

### Steps to reproduce

Since the demo is a client company project, it is not open to the public.

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/12623
