### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by graphine27** [cocos/cocos-engine#12614]
### Cocos Creator version

3.6,0

### System information

Windows 11

### Issue description

Component scripts do not compile if there is a circular dependency in them
This was working fine in 2.4

### Relevant error log output

If the project is very big, circular error wont event be shown if there are many other errors, so it's hard to track down the exact issue

### Steps to reproduce

Create a simple circular dependency on a component that is used in a scene and that component will no longer compile

### Minimal reproduction project

[Test.zip](https://github.com/cocos/cocos-engine/files/9451307/Test.zip)

**Comment by minggo** [comment]
Circular dependency may cause unknown issue on native. I suggest to treat it as error and fix it.

**Comment by pandamicro** [comment]
It's by design reported as an error in TypeScript, so please fix them in your project
