### ISSUE TITLE
The content cannot be distinguished after the atlas is loaded

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#12629]
### Cocos Creator version

3.6.0

### System information

Windows10

### Issue description

issue from:
https://forum.cocos.org/t/topic/139440
it works well in creator3.5.2.

### Steps to reproduce

use resources.loadDir() like this:
![image](https://user-images.githubusercontent.com/18083506/187636236-01e1bb0e-2917-41d9-9b13-675ddc00a71c.png)
here is the demo:
[139440.zip](https://github.com/cocos/cocos-engine/files/9460019/139440.zip)

**Comment by linruimin** [comment]
the same feedback from: https://forum.cocos.org/t/topic/139547

**Comment by SantyWang** [comment]
fixed in 3.6.1
