### ISSUE TITLE
The size property in BoxCollider2D and worldAABB are not the same size

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#12631]
### Cocos Creator version

3.6.0

### System information

Window10

### Issue description

issue from:
https://forum.cocos.org/t/topic/139353

### Steps to reproduce

here is the demo:
[139353_360.zip](https://github.com/cocos/cocos-engine/files/9460155/139353_360.zip)
run the demo , and click the button, then the console will print the boxCollider2D.

the same in 3.5.2.

**Comment by lealzhan** [comment]
physics2d调用了box2d的这个接口，导致得到了过大的AABB
![image](https://user-images.githubusercontent.com/9999378/207543950-8597acc9-e643-4143-9809-9740ff813d2e.png)
