### ISSUE TITLE
submeshes have different instancing state, non-instancing submesh can't display correctly

### ISSUE THREAD

**Issue by jk20012001** [cocos/cocos-engine#12634]
if one mesh has 5 submeshes, and 4 submeshes use instancing, 1 submesh disable instancing.
the non-instancing submesh has bad (uninitialized) world matrix, and it will disappear or has bad position and shape.
![image](https://user-images.githubusercontent.com/15099632/187654709-09d9a052-1e7e-4999-a0e4-3b38bf46de5b.png)
![image](https://user-images.githubusercontent.com/15099632/187654813-54d9c7ba-2717-4bdf-b8f3-1d983b655a98.png)

USE_INSTANCING / BATCHING macro should use at model-level, not submesh-level

**Comment by jk20012001** [comment]
[NewProject-003.zip](https://github.com/cocos/cocos-engine/files/9460593/NewProject-003.zip)

**Comment by star-e** [comment]
instancing control is moved to submodel level
