### ISSUE TITLE
richtext switch line exceptionally

### ISSUE THREAD

**Issue by Zhmz** [cocos/cocos-engine#12665]
### Cocos Creator version

3.6.x

### System information

All

### Issue description

https://discuss.cocos2d-x.org/t/richtext-displaying-issue-on-cocos-creator-3-6-0/57016

type English words of "0" to "19" in richtext, and find that it behaves abnormal

### Steps to reproduce

normal condition
"one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen ni"
![image](https://user-images.githubusercontent.com/32831993/188099008-7266c92e-64a2-4e82-981d-fb1b874d41b2.png)

abnormal condition1
"one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nin"
append a “n” to the end
![image](https://user-images.githubusercontent.com/32831993/188099216-d2a0ed6c-9308-4a08-9a68-a27eef825718.png)

abnormal condition2
complete the word "nineteen"
![image](https://user-images.githubusercontent.com/32831993/188532680-a246adae-eecc-476d-915b-2081b6634f27.png)

**Comment by LinYunMo** [comment]
Re：https://github.com/cocos/cocos-engine/pull/14782

fixed with this PR
