### ISSUE TITLE
Add AppleTV Support

### ISSUE THREAD

**Issue by paulocoutinhox** [cocos/cocos-engine#12676]
### Use Case

Hi,

Can add tvOS support for native part?

Thanks.

### Problem Description

AppleTV is not supported (device and simulator)

### Proposed Solution

Add tvOS support

### Alternatives Considered

n/a

**Comment by minggo** [comment]
Currently, there is not plan for it. Could you please describe why need it?

**Comment by paulocoutinhox** [comment]
To run the app on Apple TV?

**Comment by minggo** [comment]
Apple TV is not so popular as other platforms. So we don't consider it right now.
