### ISSUE TITLE
Error effect of 3d-rendering-in-3d

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#12673]
<img width="800" alt="Screen Shot 2022-09-05 at 11 11 46 AM" src="https://user-images.githubusercontent.com/488203/188353610-aae2809e-f9a8-46b5-beea-dc7d614a4b55.png">

Use latest codes in develop and run `2d rendering in 3d` test case can reproduce it. I only tested on macOS.

**Comment by dumganhar** [comment]
From v3.7, we have changed the js binding generator tool from `bindings-generator` to `swig`.
There are probably some configurations of `tojs/2d.ini` are not synchronized to `swig-config/2d.i`.

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/12721
