### ISSUE TITLE
Sprite doesn't show up in the editor

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12694]
### Cocos Creator version

3.6.0

### System information

window10

### Issue description

https://user-images.githubusercontent.com/40415168/188578137-335683e3-ff5e-461f-8f79-db28a789c830.mp4

### Steps to reproduce

1. first delete the project's cache folder: library,local,temp;
    先删除项目缓存文件夹：library,local,temp;
2. import a new pic, and then follow the actions in the video to reproduce it.
    导入一张新图，按照视频操作就能复现
Import a new pic, and delete the cache because the chances of reproduction will be greater.
导入新图，和删缓存是因为这样复现几率会大点

**Comment by OnlyKoei** [comment]
https://user-images.githubusercontent.com/40415168/188595508-15ca3b87-6729-4b6d-9caa-0f6aa0d7f9db.mp4

**Comment by OnlyKoei** [comment]
https://user-images.githubusercontent.com/40415168/188595646-d662994b-30b5-49db-bd46-6631fd716a0a.mp4

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/188595861-dfd3e013-079b-4618-963e-aa07ae662a37.png)

**Comment by SantyWang** [comment]
暂时先绕过了
