### ISSUE TITLE
remove unneeded res files

### ISSUE THREAD

**Issue by bofeng-song** [cocos/cocos-engine#12692]

**Comment by bofeng-song** [comment]
The appcomt theme uses resource files, so we must replace AppcompatActivity with Activity to delete resource files that are not needed by the application.

**Comment by bofeng-song** [comment]
https://github.com/cocos/3d-tasks/issues/7706
Android Game Text Input may depend on Appcompat， so we need to investigate whether it is necessary to eliminate the use of appcompat

**Comment by minggo** [comment]
We can depend on Appcompat, but these resources are not needed. So should find a way to remove these resources when generating apk.

**Comment by bofeng-song** [comment]
AppCompatDelegate is the AppCompatActivity's proxy.  Before onCreate function called at AppCompatActivity, it'll create abc_screen_simple layout. But abc_ screen_simple layout depends on other resource files. So we can not remove appCompat's resource files if we consider use appCompat

**Comment by bofeng-song** [comment]
![1663810054675](https://user-images.githubusercontent.com/3078423/191639309-d17afea3-aacd-44a4-8902-b876a55a405c.png)
![1663810120073](https://user-images.githubusercontent.com/3078423/191639324-fffd8610-d54e-4d9f-bcc2-986f3f06968e.png)
![1663810153001](https://user-images.githubusercontent.com/3078423/191639339-1b6c35eb-2b9d-4bac-b664-0cd4d9a428fd.png)
![1663810168989](https://user-images.githubusercontent.com/3078423/191639345-18592b24-6c5c-4d24-b88c-b9cf31f4c1a5.png)

**Comment by minggo** [comment]
As we haven't integrated game text input, so we should remove Appcompat. When we decide to integrate game text input, then we can add Appcompat back.

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine-external/pull/296
https://github.com/cocos/cocos-engine/pull/12854
Temporarily delete the dependency on appcompat
