### ISSUE TITLE
Add cropping settings for network modules

### ISSUE THREAD

**Issue by PatriceJiang** [cocos/cocos-engine#12695]
- [ ] Add options in editor
![image](https://user-images.githubusercontent.com/40414978/188580185-5231a371-fc42-4337-9710-63388ee3e45d.png)
- [ ] Exclude okhttp.jar on android

**Comment by novain1102** [comment]
Now, we cannot exclude `downloader` and `xmlHttpRequeset` because of engine internal usage. 
So, now network module looks like:
- Network
- [ ] ~~xmlHttpRequest~~
- [ ] ~~downloader~~
- [x] websocket
- [x] websocket-server

Also, downloader rely on okhttp on Android, so we can't exclude okhttp.jar
