### ISSUE TITLE
Custom rendering pipeline initialization earlier than pipeline code

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#12699]
### Cocos Creator version

3.6.0

### System information

Chrome

### Issue description

 **Preview Mode Only**

![image](https://user-images.githubusercontent.com/8321365/188612597-985b0afc-d0e9-440f-8d27-5f1fa2cc9eef.png)

### Steps to reproduce

just preview in chrome, will show the error.
[ssao_361.zip](https://github.com/cocos/cocos-engine/files/9495785/ssao_361.zip)

**Comment by PPpro** [comment]
![企业微信截图_166426092721](https://user-images.githubusercontent.com/17872773/192459647-387d8944-969d-4a05-8333-588ffaaafa90.png)
