### ISSUE TITLE
gfx object must call destroy, and should never be used again

### ISSUE THREAD

**Issue by star-e** [cocos/cocos-engine#12745]
### Use Case

In webgpu backend, we have to destroy resources and delete object in `xxx.destroy()` method.

In native engine, v8 finalizer is used to delete native c++ object, while in webgpu, browser finalizer is not fully supported.
As a result, we must call `destroy` to delete webgpu object.

### Problem Description

Currently, gfx object might be used after destroy.
``` ts
const framebuffer = shadowFrameBufferMap.get("xxx");
frameBuffer.destroy();
frameBuffer.initialize(info);
```
It is forbidden in webgpu backend.

### Proposed Solution

Remove all usages of re-initialization of gfx object.

### Alternatives Considered

destroy leak gfx object in webgpu backend.

**Comment by minggo** [comment]
Does it affect native usage? In native, we just use IntrusivePtr to control the lifecycle.

**Comment by minggo** [comment]
I agree that should not reuse gfx objects when they are destroyed.

**Comment by star-e** [comment]
> Does it affect native usage? In native, we just use IntrusivePtr to control the lifecycle.

It does not affect native usage. In native engine, v8's finalizer will be called and c++ object is deleted or decRefed. So there is no leak.

In webgpu, browser's finalizer might not be called or is not supported at all. So every webgpu/webasm object must be deleted manually.

**Comment by pandamicro** [comment]
@star-e  I assigned @hana-alice , if it's not appropriate, please re-assign

**Comment by star-e** [comment]
We use non-wasm version of WebGPU now. Problem solved.
