### ISSUE TITLE
Error after duplicating animation graph

### ISSUE THREAD

**Issue by Biodam** [cocos/cocos-engine#12751]
### Cocos Creator version

3.5.1

### System information

Windows 11

### Issue description

It seems that a “ghost” variable is staying in the serialized file of animation graph after a duplication and deleting a variable

### Relevant error log output

![image](https://user-images.githubusercontent.com/15266822/189953429-e6f7eb50-d005-45ea-a29f-2c1ce6d10bc7.png)

### Steps to reproduce

1.     Create a animation graph with a trigger variable
2.     Duplicate it
3.     Delete the variable in the new animation graph, and create a new trigger variable
4.     Try to use the newly created graph

**Comment by arsen2010** [comment]
You need to remove the references of that variable as well. In later release 3.6.2 version, we're going to optimize this behavior.

**Comment by arsen2010** [comment]
Sorry，this optimization too late to catch up v3.6.2 , would be delay to v3.7 .
On v3.7 when remove a variable ,if the variable is be used would pop a confirm warning dialog to user.
