### ISSUE TITLE
Prefabs variants

### ISSUE THREAD

**Issue by Biodam** [cocos/cocos-engine#12750]
### Use Case

When working with enemies of even UI that have similar structure it would be good to be able to have a base prefab and variants that have overrides similar to how overrides work in scene.

Also we need a better visualization of prefabs overrides. It is hard to know which values have been overwritten.

### Problem Description

1. Create a base prefab
2. Create a variant prefab
3. Set overrides in variant prefab
4. When editing base prefab the changes should reflect in variants

### Alternatives Considered

Don't know any

**Comment by m-gomes** [comment]
This feature would be great and spare a LOT of development time!

**Comment by wuzhiming** [comment]
now creator have + UI show in hierarchy
![image](https://github.com/cocos/cocos-engine/assets/6093737/1cd51aad-92ce-42ac-95ac-43fe2386b0da)

**Comment by kaxifakl** [comment]
we also need to know whitch values changed, like position.x，name...
