### ISSUE TITLE
Error while opening other prefab while in animation mode

### ISSUE THREAD

**Issue by Biodam** [cocos/cocos-engine#12752]
### Cocos Creator version

3.5.1

### System information

Windows 11

### Issue description

Node structures will go from one prefab to another when interacting with animation mode from within prefab mode and opening another prefab.

### Steps to reproduce

1.     Open prefab 1
2.     Open animation mode
3.     Double click in prefab 2 in assets without closing animation mode
4.     Save in the popup
Now the prefab 2 will have the nodes of prefab 1

**Comment by OnlyKoei** [comment]
https://user-images.githubusercontent.com/40415168/190047429-400603ce-9440-4f30-8306-f4ceff2c9710.mp4

**Comment by dogeFu** [comment]
This issue will be fixed at 3.6.2.
Exiting animation editor when you want to open other prefab can avoid this problem.
