### ISSUE TITLE
tiledmap display exception

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12763]
### Cocos Creator version

3.6.0，3.5.0，3.3.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/139958
![image](https://user-images.githubusercontent.com/40415168/190092295-47c7dae9-1092-4076-865d-926b6d6eadde.png)

2.4.10：
![image](https://user-images.githubusercontent.com/40415168/190094877-4448fd3a-65f4-462a-bca9-cffef3f794d7.png)

3.6.0：
![image](https://user-images.githubusercontent.com/40415168/190097083-889e6fbb-514a-4154-8b18-ee95abffdc38.png)

修改 trimType 后显示正常
After modifying trimtype:
![image](https://user-images.githubusercontent.com/40415168/190097453-097237cc-a1b4-439e-98b4-706b45035729.png)
![image](https://user-images.githubusercontent.com/40415168/190097365-fb5a9b9a-5fc4-4b92-ae44-67945a53f413.png)

### Steps to reproduce

2.4.10 demo:
[NewProject_17.zip](https://github.com/cocos/cocos-engine/files/9564111/NewProject_17.zip)

3.6.0 demo:
[mat.zip](https://github.com/cocos/cocos-engine/files/9564115/mat.zip)

**Comment by OnlyKoei** [comment]
有的 trimtype 需要设置成 none, 有的需要设置为 custom; 才能正常显示
Some textures trimtype needs to be set to none, some need to be set to custom to display properly

**Comment by zhakesi** [comment]
需要修改下资源中
spriteFrame 的Trim Type从auto 改为none
<img width="270" alt="捕获" src="https://user-images.githubusercontent.com/14008865/190946261-5eb6eda6-5a8c-4dfb-8d39-faca01412e2e.PNG">
