### ISSUE TITLE
The editbox on the web cannot enter decimals, such as 0.1

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12784]
### Cocos Creator version

3.6.0

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/139729

When the decimal point was entered, it was recognized as a null character on the web, and then cut again, causing the index to be misaligned.
web 上在小数点键位输入时识别为空字符串，之后又进行了切割，下标索引就错乱了。
![image](https://user-images.githubusercontent.com/40415168/190352375-d0ddaf8b-f1be-4a6f-bb79-e40cbe23af3a.png)

For the time being, it can be modified as follows.
![image](https://user-images.githubusercontent.com/40415168/190352797-e515664c-5411-4994-9113-e4cf6bae88f8.png)

### Steps to reproduce

1. create editbox-node;
2. change inputmode to DECIMAL;
3. preview on web;
https://user-images.githubusercontent.com/40415168/190340135-bf8d27bf-49a8-43c4-b42e-105081e58e6c.mp4

**Comment by knoxHuang** [comment]
已在 3.8.2 修复
