### ISSUE TITLE
Native build system optimize

### ISSUE THREAD

**Issue by PatriceJiang** [cocos/cocos-engine#12791]
- [ ] ~~Collect FAQs~~ Document-related task, will be further improved in the future.
    - OOM
    - Output FAQ url when error occurs
    - Android multiple configuration practice for different release channel [duplicate issue](https://github.com/cocos/3d-tasks/issues/11959)

- [x] Remove build directory is required in some cases
- [ ] ~~Enviroment variables update~~, No related needs at the moment,application path can be configure through edior.
- [x]  Xcode related environment verification (Build after creating a new Apple ID). https://github.com/cocos/cocos-engine/pull/14737
- [x] Allow select VS version in build panel https://github.com/cocos/3d-tasks/issues/16095

**Comment by minggo** [comment]
Please describe tasks in more detail.
