### ISSUE TITLE
[Native] Game crash when using private cache mode for spine

### ISSUE THREAD

**Issue by obraz29** [cocos/cocos-engine#12792]
### Cocos Creator version

3.6.0

### System information

iOS, android

### Issue description

When set private cache & active the spine in the same frame, the game will be crashed

### Relevant error log output

![image](https://user-images.githubusercontent.com/52654061/190561532-91867615-5fdd-4cea-99db-529650f2e4cd.png)

### Steps to reproduce

Please check demo project

### Minimal reproduction project

[NewProject_2.zip](https://github.com/cocos/cocos-engine/files/9580844/NewProject_2.zip)

**Comment by pandamicro** [comment]
@zhakesi please confirm it with latest engine

**Comment by zhakesi** [comment]
It's a legacy bug in 3.x. Be solved in 3.6.3.
* https://github.com/cocos/cocos-engine/pull/13419

There are a few other issues with this version, i recommend version 3.6.3
Maybe you need take a look at this too, if you need to create a spine in a hided node.
* https://github.com/cocos/cocos-engine/pull/13370
