### ISSUE TITLE
[iOS 15.5] App crash when enter background

### ISSUE THREAD

**Issue by obraz29** [cocos/cocos-engine#12803]
### Cocos Creator version

3.6.0

### System information

iOS 15.5

### Issue description

App will be crashed when enter background.

### Relevant error log output

![image](https://user-images.githubusercontent.com/52654061/190619883-899c7809-1361-4b3b-820c-9ff513310c42.png)

### Steps to reproduce

the bug occurs on iOS 15.5 only
1. Open app
2. Send app to background (minimize or press lock key)
3. Wait 5 seconds and open app again

https://user-images.githubusercontent.com/52654061/190621043-cfdd9892-48f8-4d48-9a28-4b1d288b9a33.mp4

### Minimal reproduction project

[NewProject_2 2.zip](https://github.com/cocos/cocos-engine/files/9583284/NewProject_2.2.zip)

**Comment by novain1102** [comment]
I've tested your demo running well on 15.2 and latest 15.7.1.
I don't have available iOS 15.5 device. Maybe you could upgrade iOS version and test again?
