### ISSUE TITLE
HarmonyOS projects do not work in DEVECO 3.X

### ISSUE THREAD

**Issue by qiuguohua** [cocos/cocos-engine#12827]
Check out Huawei's official instructions：
https://developer.huawei.com/consumer/cn/forum/topic/0203876484517800640?fid=26

**Comment by minggo** [comment]
What's the current status of this issue?

**Comment by qiuguohua** [comment]
Currently you can only use 2.x deveco to compile projects for harmonyos, if you use 3.x, you will have problems. Maybe we need to upgrade the project

**Comment by qiuguohua** [comment]
Maintain the current situation and do not upgrade for the time being
