### ISSUE TITLE
[3.6.0] Some event callbacks of Android joystick buttons are missing

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12820]
### Cocos Creator version

3.6.0

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/139561
![image](https://user-images.githubusercontent.com/40415168/191181965-03277ac9-c1b4-4786-84df-8a8f77c961ab.png)

### Steps to reproduce

.

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/12854
https://github.com/cocos/cocos-engine-external/pull/296
Temporarily delete the dependency on appcompat
