### ISSUE TITLE
Error replacing dragonbone's resources repeatedly on the editor

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12821]
### Cocos Creator version

3.6.0

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/140177
![image](https://user-images.githubusercontent.com/40415168/191193586-ff96c50c-ac7d-4d2c-9939-f15aafa321c9.png)
![image](https://user-images.githubusercontent.com/40415168/191193680-ee7ead84-8130-4ddf-a320-4f3c4f4c1ed2.png)

### Steps to reproduce

demo:
[NewProject.zip](https://github.com/cocos/cocos-engine/files/9605088/NewProject.zip)

**Comment by OnlyKoei** [comment]
https://forum.cocos.org/t/topic/140331
![image](https://user-images.githubusercontent.com/40415168/191902968-807109ac-4ebd-4257-861c-a9e2b4ef6bd7.png)
类似问题
demo:
[NewProject_5.zip](https://github.com/cocos/cocos-engine/files/9631921/NewProject_5.zip)

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/12987
