### ISSUE TITLE
[3.4.2 ~ 3.6.0] After using game.restart(), the game's memory grows and a memory leak occurs

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12839]
### Cocos Creator version

3.4.2 ~ 3.6.0

### System information

ios 15.6.1

### Issue description

![图片](https://user-images.githubusercontent.com/35944775/191446489-75ea50c5-1e65-412e-8d6d-13cb26b4c669.png)

### Steps to reproduce

Build IOS projects and test them on IOS phones.

[momoryleak.zip](https://github.com/cocos/cocos-engine/files/9614240/momoryleak.zip)

**Comment by novain1102** [comment]
follow up in internal issue: https://github.com/cocos/3d-tasks/issues/14034

**Comment by novain1102** [comment]
Test for iOS/macOS(metal), Android/Windows (gles3, vulkan);
Memory do not grow significantly on Android/Windows when restart:
![wecom-temp-89702-c15d367762953b7963d0b68db337e133](https://user-images.githubusercontent.com/18634782/194695896-928c445d-2262-48ab-9149-9fd70a700207.png)
![image](https://user-images.githubusercontent.com/18634782/194697209-572b527d-b60b-48d8-9a03-6eb637be8c5c.png)
![image](https://user-images.githubusercontent.com/18634782/194697230-c12bfdc1-7f8c-453b-94aa-7d3ffc91dc15.png)

![image](https://user-images.githubusercontent.com/18634782/194697842-bb5f329b-cc1c-4600-80ea-fb259b769d39.png)

There is a gradually rising resource leakage only on iOS/macOS(metal) after each restart(although not as obvious as described in the issue). 
![image](https://user-images.githubusercontent.com/18634782/194701282-9adb6b30-0be8-4400-8b9a-12bd563b169d.png)
Please have a check with gfx related codes @hana-alice.

**Comment by novain1102** [comment]
![企业微信截图_481f0b31-1da9-42e2-a70a-d94c474fa97e](https://user-images.githubusercontent.com/18634782/194735047-8868b33e-ef1c-4929-a73a-7651207151c4.png)

**Comment by novain1102** [comment]
Resolved: https://github.com/cocos/cocos-engine/pull/12995

**Comment by hana-alice** [comment]
Do not check memory allocation by this indicator, use Instruments->leaks->allocations instead. Focus on allocations, the anonymous VM part is not controlled by user but the system.

**Comment by novain1102** [comment]
Still have MsgQueue related leak when using game.restart(). Please pay attention to this issue @hana-alice
