### ISSUE TITLE
Destroy Collider High performance consumption

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12843]
### Cocos Creator version

3.6.0

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/139056
![image](https://user-images.githubusercontent.com/40415168/191468759-d29f9d7e-addd-4cfe-bed5-4ef35c336429.png)

### Steps to reproduce

.

**Comment by lealzhan** [comment]
[demoA1.zip](https://github.com/cocos/cocos-engine/files/9857549/demoA1.zip)

![image](https://user-images.githubusercontent.com/9999378/197696390-ca5fefd7-4ee1-4066-a341-fcd2af173279.png)

**Comment by lealzhan** [comment]
![image](https://user-images.githubusercontent.com/9999378/198205469-ac325afa-6a9d-4345-ba3a-572801372855.png)
使用builtin 2d物理的collider-2d component 在 disable 时，会调用removeShape函数，`contacts.splice(i, 1)`，如果contacts数组长度达到几万，性能损耗就特别大。
