### ISSUE TITLE
node.worldScale has faulty logic

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#12861]
### Cocos Creator version

3.6.0

### System information

Chrome

### Issue description

Set the world scale and print it, then get a different value? That's weird.

``` typescript
this.child.worldScale = new Vec3(1, 1, 1);
console.log(this.child.worldScale);
```

### Steps to reproduce

Reproduce project， press key 'A' on PC Chrome.
[NewProject.zip](https://github.com/cocos/cocos-engine/files/9625217/NewProject.zip)

**Comment by bofeng-song** [comment]
This function is normal. After setting worldscale, the transform will change, and the final value obtained will change with the transform

**Comment by bofeng-song** [comment]
Cocos engine: update scale at the api of updateWorldTransform

**Comment by bofeng-song** [comment]
@xianyinchen notify developer, he can merge following pr.
https://github.com/cocos/cocos-engine/pull/12165
