### ISSUE TITLE
[Feature Request] Physics System with Web Worker

### ISSUE THREAD

**Issue by kenkozheng** [cocos/cocos-engine#12874]
### Use Case

We are building H5 games targeting all levels of mobile phones.
Low-end devices meet serious performance issues, especially when a physics system is involved.

### Problem Description

Low performance of physics system.

### Proposed Solution

leverage web worker to separate calculating and rendering

### Alternatives Considered

None

**Comment by pandamicro** [comment]
We are not planning to use Web Worker currently for physics, because the sync between main thread and physics worker is very complex. But we do support bullet and physx with webassembly build, they should be quite fast now, please check v3.7.x.
So I will reject this request for now
