### ISSUE TITLE
[3.6.1] new custom layer can't get

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12888]
### Cocos Creator version

3.6.1

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/140382
![image](https://user-images.githubusercontent.com/40415168/192210418-dabf3e1f-1155-4f48-b0bb-9d827f3685ef.png)

3.6.0 :
![image](https://user-images.githubusercontent.com/40415168/192210645-7f1d2658-4ee4-47cc-b55b-91314589f788.png)

3.6.1:
![image](https://user-images.githubusercontent.com/40415168/192210770-65beac8d-f3c9-457a-93ab-032e7accfb77.png)

### Steps to reproduce

.

**Comment by arsen2010** [comment]
confirm this is bug added from v3.6.1 , would be fixed on v3.6.2

**Comment by jhyoo2** [comment]
Fixed in the inspector. However, it still doesn't show up when building Android.
