### ISSUE TITLE
[3.6.1] Particle Native Crash

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12893]
### Cocos Creator version

3.6.1

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/140441
![image](https://user-images.githubusercontent.com/40415168/192242046-5644d6a5-63f3-48e7-8a7b-bf6039a5569c.png)

Android crash information：
![image](https://user-images.githubusercontent.com/40415168/192242082-ad147d73-00c5-4bad-a12a-1cc836cde87d.png)

The web runs fine, if you run it with the emulator, the emulator will just flash back without reporting an error.
web 运行正常，如果使用模拟器运行，模拟器会直接闪退，没有报错。

### Steps to reproduce

demo:
[361.zip](https://github.com/cocos/cocos-engine/files/9644885/361.zip)

**Comment by wardehuang** [comment]
Bugly crash log.

![image](https://user-images.githubusercontent.com/1259296/192249631-020edf0e-4c85-40fd-a6ab-b0d4a773559e.png)
