### ISSUE TITLE
update to 3.6.1 particle error

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#12915]
### Cocos Creator version

3.6.1

### System information

windows10

### Issue description

1.particle set capacity to 1
![image](https://user-images.githubusercontent.com/18083506/192479851-b058416d-b6f9-4311-8ac3-d2f20d14bdf7.png)
run on web, the console will show:
![image](https://user-images.githubusercontent.com/18083506/192479746-36313b7c-1268-4526-a48c-e538e54c1612.png)
2.trail module not enable, but it inited.
![image](https://user-images.githubusercontent.com/18083506/192481803-0315364e-ef49-42b7-b299-c0dc6b456d93.png)

### Steps to reproduce

issue from: https://forum.cocos.org/t/topic/140372

**Comment by zxx43** [comment]
https://github.com/cocos/cocos-engine/pull/13378/files this pr resolve the first issue

**Comment by zxx43** [comment]
https://github.com/cocos/cocos-engine/pull/13378/commits/bcfab18f70ba278c85727611554a01c66994fd68 this commit resolve the second issue
