### ISSUE TITLE
Base rely on Primitive causing unexpected issue when Primitive being culled

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#12921]
![企业微信截图_587a7634-e627-437e-a1fd-fc6be03992c6](https://user-images.githubusercontent.com/632460/192499220-9126672d-9aca-4f3b-ae1a-82ab36deb9f8.png)

As shown here, `Skybox` class rely on `primitive.Box` to create mesh for skybox, and primitive module could be culled in project settings, which cause issues in 3d project.

Options are
1. Make `base` module dependent on `primitive` module in `cc.config.json`
2. Move `primitive` into `base` module
3. Separate `Skybox` and other 3d environment classes from `base` and move into `3d` module. (Tried once in https://github.com/cocos/cocos-engine/pull/10643, no success on environment data, because they are deeply dependent in render pipeline)

**Comment by minggo** [comment]
cocos/core/renderer is moved to cocos/render-scene, it is not part of base module now

**Comment by pandamicro** [comment]
Then render-scene must rely on primitive module. That is acceptable, but it would be even better to move environment related classes into 3d module.

**Comment by minggo** [comment]
Sorry, what did you mean environment related classes?
