### ISSUE TITLE
[Android] cc_time is not calculated correctly in Android

### ISSUE THREAD

**Issue by tuan243** [cocos/cocos-engine#12940]
### Cocos Creator version

3.5.1, 3.6.0

### System information

GLES3

### Issue description

Demo project: https://github.com/iwae/2DWater-Reflection
cc_time variable get more incorrectly over short period of time. It cause the water caustic effect get more pixelated overtime (about 5 min). This problem does not happen in web platform.

### Steps to reproduce

- Clone and open demo project
- Open build panel, choose platform Android, untick Vulkan, and press build
- Using Android studio and run project on any device

### Minimal reproduction project

The apk file of the project build by cocos creator 3.6.0, release build
[2D_Reflection-release.zip](https://github.com/cocos/cocos-engine/files/9666636/2D_Reflection-release.zip)

**Comment by minggo** [comment]
@jk20012001 where to pass cc_time to shader?

**Comment by tuan243** [comment]
Hi all, any update on this issue?

**Comment by OnlyKoei** [comment]
> Hi all, any update on this issue?

[2D_Reflection-release.zip](https://github.com/cocos/cocos-engine/files/9836764/2D_Reflection-release.zip)
try this,and show all the parameters on your build panel:
![image](https://user-images.githubusercontent.com/40415168/197140901-284f1364-d742-4f95-b71d-bf83deab0bef.png)

**Comment by troublemaker52025** [comment]
* We tested v3.5.1 and v3.6.2 on Samsung SM-G9810 and neither of them reproduced the problem
* Please provide us with the device model of the phone that is having the problem
* Please provide us with the error screen

![图片](https://user-images.githubusercontent.com/20809296/197162183-d59d72c3-e85d-41bd-befb-00fdd6c0c76a.png)

**Comment by tuan243** [comment]
The problem is more clear when you let the game run more than 5 mins. Here is the video when the game is run more than 10 mins.

https://user-images.githubusercontent.com/43067174/197383728-a00b0204-2f7f-426b-b08a-8de77c5de33c.mp4

This is my build config
![image](https://user-images.githubusercontent.com/43067174/197383867-b8ffd746-15df-4e55-8b59-f28365271212.png)

I see this problem on any of our tested devices, In this case this is my Realme 5 pro
I don't see any log about error
Thanks

**Comment by troublemaker52025** [comment]
![图片](https://user-images.githubusercontent.com/20809296/197435527-0e21630b-e187-450e-b3d2-f7daa8aa954e.png)

* Modify the code with the `TIME_OFFSET` keyword in PipelineUBO.cpp of the native engine. Add an extra line there

```c++
  uboGlobalView[UBOGlobal::TIME_OFFSET + 3] = root->getCumulativeTime() - floorf(root->getFrameTime());  // better precious, use cc_time.w instead of cc_time.x
```

---

![图片](https://user-images.githubusercontent.com/20809296/197443298-f52980da-07e8-442e-827e-e784d30d76a7.png)

* Modify the code with the `TIME_OFFSET` keyword in pipeline-ubo.ts of the native engine. Add an extra line there
```typescript
  fv[UBOGlobal.TIME_OFFSET + 3] = root.cumulativeTime - Math.floor(root.frameTime);  // better precious, use cc_time.w instead of cc_time.x
```

* And use cc_time.w as time in the shader code

**Comment by troublemaker52025** [comment]
* https://github.com/cocos/cocos-engine/pull/13132
