### ISSUE TITLE
[Android] Issue with uniform variable

### ISSUE THREAD

**Issue by tuan243** [cocos/cocos-engine#12941]
### Cocos Creator version

3.6.0

### System information

GLES3

### Issue description

Demo project: https://github.com/iwae/2DWater-Reflection
The game crash on launch in debug buildk. In release build the game doesn't crash, but the causticColor variable in water-sprite.effect doesn't take effect, it cause the caustic texture became white
In web:
![image](https://user-images.githubusercontent.com/43067174/192827910-d2921fb6-7c16-4b7d-9c5d-4ea4726ffe14.png)
In android:
![unknown](https://user-images.githubusercontent.com/43067174/192828384-1e27b556-1f63-41a4-b7e8-9af59249470c.png)

### Relevant error log output

The code where crash happened in Android studio in debug build:
![image](https://user-images.githubusercontent.com/43067174/192828838-0d32414d-d2c2-4934-8637-7866af1de197.png)

### Steps to reproduce

- Clone and open demo project
- Open build panel, choose Android platform, untick Vulkan, press build
- Open Android studio and run in build and release mode

### Minimal reproduction project

release apk:
[2D_Reflection-release.zip](https://github.com/cocos/cocos-engine/files/9666861/2D_Reflection-release.zip)
debug apk:
[2D_Reflection-debug.zip](https://github.com/cocos/cocos-engine/files/9666862/2D_Reflection-debug.zip)

**Comment by novain1102** [comment]
![image](https://user-images.githubusercontent.com/18634782/193175512-f7648ddb-a376-400c-89e5-dcfceb3159ec.png)
In your effect code,  `type: color ` but value is FLOAT3; you should assign value as FLOAT4 like [1.0, 1.0, 1.0, 1.0]; You could see in built-in effect.
![企业微信截图_14057750-ad8a-4995-a4e7-ef39117b9f2a](https://user-images.githubusercontent.com/18634782/193176882-be5292fe-a4f7-4db7-9f1a-354030469e7f.png)

**Comment by yiwenxue** [comment]
![image](https://user-images.githubusercontent.com/24495793/193226810-39f2a823-243a-4942-a8eb-dc7196677c5a.png)

合并 https://github.com/cocos/cocos-engine/pull/12962 的修改之后，windows 上面可以正确渲染了（Windows11， ES3，debug 模式测试）。

metal 上水的波纹是纯黑色。可能是后端的问题。

**Comment by novain1102** [comment]
> ![image](https://user-images.githubusercontent.com/24495793/193226810-39f2a823-243a-4942-a8eb-dc7196677c5a.png)
> 
> 合并 #12962 的修改之后，windows 上面可以正确渲染了（Windows11， ES3，debug 模式测试）。
> 
> metal 上水的波纹是纯黑色。可能是后端的问题。

![image](https://user-images.githubusercontent.com/18634782/193233880-56e008ae-451a-44fc-ab82-a9b2e4181e0b.png)
Error effect shows in version 3.5.x & 3.6.x in Metal
@hana-alice Please have a check.

**Comment by yiwenxue** [comment]
Fatal error appears on the Vulkan backend
![image](https://user-images.githubusercontent.com/24495793/193236432-e910c173-da29-4a1b-8b20-9a167243d863.png)

**Comment by novain1102** [comment]
> Fatal error appears on the Vulkan backend ![image](https://user-images.githubusercontent.com/24495793/193236432-e910c173-da29-4a1b-8b20-9a167243d863.png)

Please help to figure out VK related issue. @yiwenxue

**Comment by yiwenxue** [comment]
The reason Vulkan emits errors is that the render area exceeds the render target. In this demo the render area is set to {{0, -0.37}, {1, 1}}. It would be better if you move the camera upwards and set the Rect to {{0, 0}, {1, 1}}.
![image](https://user-images.githubusercontent.com/24495793/194702863-8070718e-b052-44c2-898d-7009c563792e.png)

**Comment by novain1102** [comment]
> The reason Vulkan emits errors is that the render area exceeds the render target. In this demo the render area is set to {{0, -0.37}, {1, 1}}. 

Maybe we need to limit the range in editor panel for `cc.Camera Rect` @GengineJS @arsen2010

**Comment by yiwenxue** [comment]
<img width="796" alt="企业微信截图_702a4b75-15ad-4bc5-9bd5-110bd3173df2" src="https://user-images.githubusercontent.com/24495793/194991632-dd5804fe-3798-4bf7-b853-4baf34bc52d0.png">
In this demo, the reflection RT can't be sampled as we expected on Metal and Vulkan, but it's reasonable. Users should solve this problem in their shaders. The underlying problem is not trivial and the related discussion can be found here https://github.com/cocos/3d-tasks/issues/11118#issuecomment-1060174022.
