### ISSUE TITLE
char label color is incorrected

### ISSUE THREAD

**Issue by Zhmz** [cocos/cocos-engine#12942]
### Cocos Creator version

3.6.x

### System information

Windows,Android,iOS

### Issue description

https://forum.cocos.org/t/topic/140371/7

### Steps to reproduce

press the button
then the colors are different

**Comment by gdoudeng** [comment]
哥哥们 这个问题有排期吗?🥹 @holycanvas

**Comment by LinYunMo** [comment]
Because the label in char mode should not be filled with the vertex color, fixed.

**Comment by SantyWang** [comment]
@gdoudeng 已在 3.7.2 修复
