### ISSUE TITLE
canvas with lower camera priority is rendered over higher one

### ISSUE THREAD

**Issue by attolee** [cocos/cocos-engine#12960]
### Cocos Creator version

3.6.0

### System information

Web, Android Simulator

### Issue description

According to the definition, 

> Render priority of the camera. High-priority Camera's will be rendered first in the rendering process

so canvas with lower camera priority is expected to be rendered under the higher one, this is true in web, but it's contrary in  android simulator or real phone.

![image](https://user-images.githubusercontent.com/4199324/193048419-199c4804-4b1a-497d-9b3a-59ca855ac8bf.png)

### Steps to reproduce

After importing the project into 3.6.0 editor,

1. run it on web, white label is shown.
2. run it on android simulator or real phone, red label is shown.

### Minimal reproduction project

[test-camera-priority.zip](https://github.com/cocos/cocos-engine/files/9675024/test-camera-priority.zip)

**Comment by pandamicro** [comment]
It should have been fixed, because the camera's priority was transferred to native as a signed int while it should be unsigned.
Please check the latest version
