### ISSUE TITLE
Message Manager shows incomplete information

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#12969]
### Cocos Creator version

3.6.1

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/140680
![image](https://user-images.githubusercontent.com/40415168/193236014-0dcab608-965d-407f-945a-eb61bb5343d6.png)

### Steps to reproduce

.

**Comment by arsen2010** [comment]
we fixed this bug on v3.7
