### ISSUE TITLE
[3.6.1] script compile issue

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#12970]
### Cocos Creator version

3.6.1

### System information

window

### Issue description

script load in editor, show error.
![image](https://user-images.githubusercontent.com/8321365/193241622-8a6032c8-f43e-40fe-bbb7-40f858a03427.png)

the error code, such like these.
![企业微信截图_16645272681518](https://user-images.githubusercontent.com/8321365/193242460-489eabcb-b752-4a24-8f90-a44f1d877028.png)

if we remove the line warp, the error will fixed.
![image](https://user-images.githubusercontent.com/8321365/193241698-b24eb069-c2c6-45fb-afeb-ef2386fb7eac.png)

### Steps to reproduce

put this code to project, it will show the error in editor.
[NewComponent.zip](https://github.com/cocos/cocos-engine/files/9682900/NewComponent.zip)

**Comment by PPpro** [comment]
this demo encounter the same issue https://github.com/cocos/cocos-engine/issues/12615

which should be fixed on 3.8 milestone

**Comment by PPpro** [comment]
will be fixed on 3.7.3
