### ISSUE TITLE
User Layer isn't shown in Camera Visuility Property

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#12984]
### Cocos Creator version

3.6.1

### System information

Windows 10

### Issue description

User Layer isn't shown in Camera Visuility Property 3.6.1

issue from:
https://discuss.cocos2d-x.org/t/user-layer-isnt-shown-in-camera-visuility-property-3-6-1/57287

### Steps to reproduce

edit layer:
![image](https://user-images.githubusercontent.com/18083506/194696985-011ada20-dc05-46d5-8481-a0d4ee5aa762.png)
the layer show in node layer:
![image](https://user-images.githubusercontent.com/18083506/194697003-cad8b76e-24bb-4ae5-a90f-09fb21157483.png)
but not in camera visbility:
![image](https://user-images.githubusercontent.com/18083506/194696992-0fea0112-d503-4e1f-91c9-3eed9ad22388.png)
it works well in creator3.4.2.

**Comment by linruimin** [comment]
The same issue already exists, and has fixed.
https://github.com/cocos/cocos-engine/issues/12888

**Comment by jhyoo2** [comment]
Fixed in the inspector. However, it still doesn't show up when building Android.
