### ISSUE TITLE
[3.6.1]  touch event confusion

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#12986]
### Cocos Creator version

3.6.1

### System information

Android

### Issue description

There is a problem with the touch event of the node, I tracked down the node enable and disable, the data inside the event is not cleared.

![企业微信截图_16635838062953](https://user-images.githubusercontent.com/8321365/194699339-b7e82799-3498-44b6-bf80-2d3b2a371ac4.png)

will cause the touch-end event to be handled here.

![企业微信截图_16635838692602](https://user-images.githubusercontent.com/8321365/194699343-4b1ba133-4e3c-4d0e-8bb9-6ee007e35c6e.png)

button touch event will ended incorrect.
![image](https://user-images.githubusercontent.com/8321365/194699387-e12b02c0-129d-4ba3-bd66-a67b1f0b501d.png)

### Steps to reproduce

test project.
[test-double-touch (1).zip](https://github.com/cocos/cocos-engine/files/9738819/test-double-touch.1.zip)

**Comment by PPpro** [comment]
fixed here https://github.com/cocos/cocos-engine/pull/14211
