### ISSUE TITLE
tiledMap rendering exception

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#12993]
### Cocos Creator version

3.6.1

### System information

MACOS

### Issue description

https://forum.cocos.org/t/topic/140899，this is fine on version 2.4.x.

### Relevant error log output

This is the correct picture:
![图片](https://user-images.githubusercontent.com/35944775/194741703-8c029605-2cbc-4525-a85e-6daaf77e6561.png)

This is the wrong picture:
![图片](https://user-images.githubusercontent.com/35944775/194741682-96196e42-8b26-4757-a0cd-ddf2f37bd195.png)

### Steps to reproduce

Just create a 2D project and import the test resources.

[map.zip](https://github.com/cocos/cocos-engine/files/9740890/map.zip)

**Comment by wuweikd** [comment]
https://forum.cocos.org/t/topic/141349/9

应该是同一个问题，这个问题是所有的图块都向上偏移了

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14341

**Comment by zhakesi** [comment]
目前需要把 tiledmap 使用的sprite-frame资源的trim 设置为none.
