### ISSUE TITLE
[Suggestion] Component select dialog shall not lose its focus on name input when click component menus

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#13001]
https://user-images.githubusercontent.com/28807867/194805023-7bf39773-a23e-4557-a273-95702c0df694.mp4

**Comment by arsen2010** [comment]
Ok ，our team UE designer agree this optimization . Deal with it in v3.7

**Comment by arsen2010** [comment]
Thank you for suggestion, our UE designer would consider it seriously in our ui-kit project.  Not watch its progress in this issue any more.
