### ISSUE TITLE
[3.6.1] change node sibling Index wasn't working in native platform.

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13010]
### Cocos Creator version

3.6.1

### System information

window

### Issue description

we change the children index, the sibling Index change and work in browser. but native platform no working.

```
this.root.children.sort((a, b) => {
    return -(a.position.y - b.position.y);
});
```

### Steps to reproduce

test project.
[NewProject_9.zip](https://github.com/cocos/cocos-engine/files/9744639/NewProject_9.zip)

**Comment by minggo** [comment]
children is a readonly property, can not modify it like this in native.
