### ISSUE TITLE
[3.6.1] A different kind of particle effect between web browser and native platform

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13044]
### Cocos Creator version

3.6.1

### System information

Android

### Issue description

publish to web browser:
![image](https://user-images.githubusercontent.com/8321365/195746858-cf3d2828-9f5a-4319-8329-12b5d47e95c8.png)

publish to android:
![image](https://user-images.githubusercontent.com/8321365/195746846-487c8ce1-35e2-4a09-b183-9fd61f7ba30e.png)

### Steps to reproduce

contact me for test project.

**Comment by zxx43** [comment]
![图片](https://user-images.githubusercontent.com/3156403/221741392-578c8aba-9aca-4359-8a4e-8111af8f268e.png)
the effect in 3.7.2 is the same like android
