### ISSUE TITLE
scene file corruption according to null child nodes

### ISSUE THREAD

**Issue by jk20012001** [cocos/cocos-engine#13042]
after some unknown operations, two child nodes of an edit control are null, it may save to .scene file like this
![企业微信截图_16654762134280](https://user-images.githubusercontent.com/15099632/195577084-0770b569-0fea-4f58-9b0c-d6ae5f5956a7.png)

Errors occur with loading scene:
![image](https://user-images.githubusercontent.com/15099632/195577019-a68a6611-b0a9-440c-829b-e476a203325e.png)

and the scene could not be loaded anymore that make me realized the scene file is corrupted.

If null nodes are not allowed while loading, I think it's still illegal while saving
![企业微信截图_1665478884823](https://user-images.githubusercontent.com/15099632/195581596-c145fa5b-7e97-4a3a-a901-ec1f24cb3e95.png)

[HeSuan001.zip](https://github.com/cocos/cocos-engine/files/9775994/HeSuan001.zip)

**Comment by minggo** [comment]
> If null nodes are not allowed while loading, I think it's still illegal while saving

I think it is reasonable.

**Comment by pandamicro** [comment]
Can we add protection for this in v3.7 ? @dumganhar

**Comment by jk20012001** [comment]
重现方法:
创建一个空节点，底下挂一个cube，保存。然后删除父节点，然后撤销，保存。父节点便会失去 children 的信息，只留下等量的 null

**Comment by dumganhar** [comment]
> Can we add protection for this in v3.7 ? @dumganhar

I need to figure out what causes this issue today.

**Comment by dumganhar** [comment]
While serializing the parent node, its children were set to invalid state (child.isValid is false) which causes `this.verifyNotParsedValue` returns null and set to children array a null value.

<img width="612" alt="WeChatcfd3da05a8331ab770577c4d38241947" src="https://user-images.githubusercontent.com/493372/205201572-bf064c88-6539-4300-8c58-beb3cfa6c320.png">

**Comment by dogeFu** [comment]
it's fixed
