### ISSUE TITLE
[3.6.1]2d particle display on the editor is not the same as on the web preview

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13056]
### Cocos Creator version

3.6.1

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/141180?from_wecom=1

https://user-images.githubusercontent.com/40415168/195829708-9fbd8c81-93b2-4f5e-a9bc-59ab18b7fe65.mp4

### Steps to reproduce

demo:
[NewProject_15.zip](https://github.com/cocos/cocos-engine/files/9785350/NewProject_15.zip)

**Comment by zxx43** [comment]
fix commit: https://github.com/zxx43/engine/commit/f4afc7424f38974b046da61a56487fddf8ece070
