### ISSUE TITLE
[Web Platform] sys.hasFeature(sys.Feature.IMAGE_BITMAP) always return false

### ISSUE THREAD

**Issue by mhourousha** [cocos/cocos-engine#13057]
### Cocos Creator version

3.6.1

### System information

Chrome, Firefox, Edge

### Issue description

In Web or Web Mobile platform
sys.hasFeature(sys.Feature.IMAGE_BITMAP) always return false
thus create ImageAsset with ImageBitmap always fail

I think this problem is caused by the following:
In the Source Code: pal\system-info\web\system-info.ts
line 172-179, 185
the 'supportImageBitmap' is modified by a Promise.then(), thus 'this._featureMap[Feature.IMAGE_BITMAP]'is alway the initial value of supportImageBitmap(false),not the modified value.

### Steps to reproduce

just check 'sys.hasFeature(sys.Feature.IMAGE_BITMAP)' in web platform

**Comment by qiuguohua** [comment]
Fixed in https://github.com/cocos/cocos-engine/pull/13165.
