### ISSUE TITLE
[optimization] Mesh should use ushort index format if index count is less than 65536

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#13082]
Currently, Mesh uses uint index format by default, it only fallback to ushort only when device could not support uint index format.
Most devices support uint, so current implementation will waste a lot of memory if there are many large meshes.

**Comment by dumganhar** [comment]
Also, while editor imports model , it should generate mesh data according vertex count per mesh.
If vertex count is less than 65536, editor should save `ushort` index format to`.bin` file.

**Comment by dumganhar** [comment]
Relevant issue：https://github.com/cocos/cocos-engine/issues/11288

**Comment by novain1102** [comment]
after discuss, do not implement in v3.7. maybe in v3.8

**Comment by AFeiYA** [comment]
集成draco，对gltf文件进行统一的压缩 [issues/7743](https://github.com/cocos/cocos-engine/issues/7743)
