### ISSUE TITLE
editor modify skeletons assets automatically, it should open a operation like 'Mesh Optimizer'

### ISSUE THREAD

**Issue by zhakesi** [cocos/cocos-engine#13096]
### Cocos Creator version

3.4,3.5,3.6

### System information

win10 editor

### Issue description

two models use same skeletons in maya.
import to editor, skeletons assets are different.

### Steps to reproduce

use test-models import to editor. two models use same skeletons in maya.
check differences between two skeletons assets
now,it's different.

### Minimal reproduction project

[test-models.zip](https://github.com/cocos/cocos-engine/files/9819361/test-models.zip)

**Comment by pandamicro** [comment]
Mesh Optimizer is replaced by another mesh reduction tool, it won't change skeletons, so it's fixed
