### ISSUE TITLE
console error when scrollBar is deleted

### ISSUE THREAD

**Issue by Zhmz** [cocos/cocos-engine#13103]
### Cocos Creator version

3.6.x

### System information

ALL

### Issue description

https://forum.cocos.org/t/topic/140022

### Steps to reproduce

console error when scrollbar is deleted

**Comment by LinYunMo** [comment]
This problem occurs in all components that have references, when the component node is deleted in the editor, the reference to this component still exists, and the status of this reference is abnormal and the isValid property of the component is true. needs to be handled by the @VisualSJ .

--------------------------------------------------------------------------------------------------------------------------------------------

这个问题会出现在所有存在引用的组件中，当组件节点在编辑器中被删除，此组件的引用依旧存在，且此引用的状态异常，组件的isValid属性为 true。需要编辑器处理。

**Comment by SantyWang** [comment]
https://github.com/cocos/cocos-engine/pull/14041, has added `isValid` check.
