### ISSUE TITLE
PhysicsPolygonCollider on 3.x reports an error

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#13190]
### Cocos Creator version

3.4.2， 3.6.1

### System information

all

### Issue description

The PhysicsPolygonCollider on 3.x reported an error and found that there was a fix for PR on 2.4.10 that was not synced to 3.x.

2.4.10 fix  PR https://github.com/cocos/cocos-engine/pull/10888

bug error message:
![image](https://user-images.githubusercontent.com/14273437/198951315-2d09d0c2-6a23-4352-8fc5-cc40f33d035d.png)

https://forum.cocos.org/t/topic/141956

### Steps to reproduce

https://forum.cocos.org/t/topic/141956/3

Provide replicated demos

**Comment by lealzhan** [comment]
This 2.x fix PR https://github.com/cocos/cocos-engine/pull/10888 won't solve the problem.
The belowing is the bug case, and the algorithm will easily crash if you randomly chage the polygon shape
[terrainEdit.zip](https://github.com/cocos/cocos-engine/files/10101266/terrainEdit.zip)

The cocos's polygon convex decomposition algorithm comes from [here](https://mpen.ca/406/bayazit). As shown by the author, the algorithm seems not considering all the cases.

The belowing point sets will cause the algorithm to crash in the original c++ code offered by bayazit:
```c++
incPoly.push_back(Point(417, -312));
incPoly.push_back(Point(600, -312));
incPoly.push_back(Point(600, 200));
incPoly.push_back(Point(554.25, 208.20101039203263));
incPoly.push_back(Point(508.5, 228));
incPoly.push_back(Point(462.75, 247.79898960796737));
incPoly.push_back(Point(417, 256));
polyComplete = true;
makeCCW(incPoly);
decomposePoly(incPoly);
for (int i = 0; i < polys.size(); ++i) {
    printf("-----------\n");
    for (int j = 0; j < polys[i].size(); ++j) {
        printf("poly %d v %d : %f %f\n", i, j, polys[i][j].x, polys[i][j].y);
    }
}
```
