### ISSUE TITLE
[3.6.2]  replay music after pause has burst sound in begining.

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13197]
### Cocos Creator version

3.6.2

### System information

iOS 15.4 build on Ihpone12 min,

### Issue description

as title saying.

### Steps to reproduce

ask me for test peoject.

**Comment by timlyeee** [comment]
[testmusic.zip](https://github.com/cocos/cocos-engine/files/9906111/testmusic.zip)

**Comment by timlyeee** [comment]
https://github.com/cocos/cocos-engine/pull/13222
