### ISSUE TITLE
[3.6.2] No rendering after minisize window on windows platform

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13200]
### Cocos Creator version

3.6.2

### System information

window

### Issue description

After minisize window, move mouse to the application icon on task bar, the window preview wasn't rendering.
![97aa828e-4702-4b36-87e5-9973d4029ef6](https://user-images.githubusercontent.com/8321365/199145472-223c5223-f943-4807-b918-c1960acfd923.png)

we compare with unity, it still rendering after minisize window, maybe it's a optional configuration.
[video(4).zip](https://github.com/cocos/cocos-engine/files/9906255/video.4.zip)

### Steps to reproduce

create an empty project, build and run on window platform. After minisize window, move mouse to the application icon on task bar, the window preview wasn't rendering.

**Comment by jareguo** [comment]
Unity 是可以在平台上进行配置的，不一定就要在后台渲染，参考 https://blog.csdn.net/WenHuiJun_/article/details/126009388
我们只要提供相应的 API 就行，用户启动后在代码中调用对应接口完成设置。

**Comment by star-e** [comment]
Unity在桌面使用d3d11运行，d3d11窗口最小化不会导致swapchain失效。
把graphics切换成vulkan，再看看有没有这个效果？

**Comment by qiuguohua** [comment]
在windows不发送最小化的消息，仍然没有渲染。需要@bluesky013 帮忙看看

**Comment by xunyi0** [comment]
> Unity 是可以在平台上进行配置的，不一定就要在后台渲染，参考 https://blog.csdn.net/WenHuiJun_/article/details/126009388 我们只要提供相应的 API 就行，用户启动后在代码中调用对应接口完成设置。

1. Entry: Project Settings -> Macro Configurations.
2. Name: RUN_IN_BACKGROUND.
3. Display: Checkbox, checked by default.
4. Tooltips：
    中文：在原生桌面平台上运行游戏时，当窗口失去焦点后是否在后台保持运行。
    English：When running a game on a native desktop platform, whether the window stays running in the background when it loses focus.
5. Compatibility: make sure the old project is not checked by default after upgrading to the new version, and the new project is checked by default.

**Comment by minggo** [comment]
Hi, all. Could you please use english in future?
Thanks.

**Comment by xianyinchen** [comment]
The goal has been achieved, the demand is temporarily postponed, issue close.
