### ISSUE TITLE
can't modify skybox custom property on update

### ISSUE THREAD

**Issue by ankye** [cocos/cocos-engine#13215]
### Cocos Creator version

3.6.1

### System information

mac os and build web mobile

### Issue description

when i use custom skybox material and want modify ratio property on update , call setProperty will not take effect。
 update(deltaTime: number) {
       
            //无效1
             this._skyboxInfo.skyboxMaterial?.setProperty("ratio", this._time);
           //无效2
            //const h = this._skyboxInfo.skyboxMaterial.passes[0].getHandle('ratio');
            // this._skyboxInfo.skyboxMaterial.passes[0].setUniform(h,this._time);
}

### Steps to reproduce

https://github.com/ankye/skybox

**Comment by jk20012001** [comment]
[skybox.zip](https://github.com/cocos/cocos-engine/files/9916894/skybox.zip)

**Comment by xubing0906** [comment]
After setting the material parameters, you need to update to skybox again
like this
![image](https://user-images.githubusercontent.com/49358166/215739018-0bb8abc4-5fcc-48ce-bd5c-56e056df41a7.png)

**Comment by pandamicro** [comment]
@xubing0906  The usage you suggested is very strange, it looks like the setter of `skyboxMaterial` must be invoked after any change, but from the code, it means nothing to assign itself back. Please consider a better solution or API

**Comment by xubing0906** [comment]
add api setMaterialProperty for skyboxinfo
use like this:  this._skyboxInfo.setMaterialProperty("ratio", this._time);
