### ISSUE TITLE
Image display is not normal

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13221]
### Cocos Creator version

3.6.1

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/141922
![image](https://user-images.githubusercontent.com/40415168/199439723-322e3f3a-2c08-42e1-b946-d46c3b627fba.png)

If this option is not checked, the picture will be displayed normally.
uncheck:
![image](https://user-images.githubusercontent.com/40415168/199440004-f287a7ae-c5a2-4f80-9a8a-204128088bb7.png)

checked:
![image](https://user-images.githubusercontent.com/40415168/199440232-d544fea4-4384-4d01-917b-b88e33c66d89.png)

### Steps to reproduce

![test](https://user-images.githubusercontent.com/40415168/199439795-d5180e54-a92d-498e-b1c3-c2c7acc5e85a.png)

**Comment by chichinohaha** [comment]
The png image has only two channels, which causes this problem
