### ISSUE TITLE
Can't tween color of cc.Sprite

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#13229]
### Cocos Creator version

3.6.1

### System information

OSX

### Issue description

Hello,

I want to tween the color of a cc.Sprite with this line:

    `    tween(this.sprite1).to(3, { color:Color.TRANSPARENT }).start();`

But the **color** property is not present.
![image](https://user-images.githubusercontent.com/758680/199543100-cd53446c-6c2a-4627-af51-ba02887c6687.png)

Regarding this post, this bug should be fixed in CocosCretor 3.6
https://discuss.cocos2d-x.org/t/fade-in-and-out/55902/2

But I got this problem with CocosCreator 3.6.1.

I need to add UIOpacity component to change the opacity property.

`   tween(this.sprite1.getComponent(UIOpacity)).to(1, { opacity:0 }).start();`

### Steps to reproduce

Add a Sprite component then try to tween the color.
`tween(this.sprite1).to(3, { color:Color.TRANSPARENT }).start();`

**Comment by minggo** [comment]
@bofeng-song please discuss with @qiuguohua , who will take charge of it.

**Comment by minggo** [comment]
@bofeng-song please discuss with @qiuguohua , who will take charge of it.

**Comment by dumganhar** [comment]
@BenoitFreslon Cocos Creator uses `Entity Component` architecture. So `Node` is an entity without any rendering relative functionality. So you can't tween `color` property on Node since it doesn't exist on Node.

**Comment by dumganhar** [comment]
I misunderstand the issue. 
The issue is to create a tween color for sprite component, it is not relative to color property on `Node`. I will fix this issue soon.

**Comment by BenoitFreslon** [comment]
Yes it is.
If I remeber the old documentation shows an example with a tween to change the color sprite. That's why I posted this.
Thanks.

**Comment by dumganhar** [comment]
@BenoitFreslon , thanks for your report. I submitted a pull request here https://github.com/cocos/cocos-engine/pull/16977
If you get time, you could apply this patch to verify whether it works for you.
