### ISSUE TITLE
export class atlas

### ISSUE THREAD

**Issue by kaxifakl** [cocos/cocos-engine#13236]
### Use Case

There has a condition of using atlas in custom rendering. 
Drawing texture in atlas with manual processing.
The exported atlas is Convenient in this condition.

### Problem Description

The atlas was exported in 2.x but different in 3.x.

### Alternatives Considered

Custom engine

**Comment by minggo** [comment]
Did you mean `Atlas` class, which is defined in `cocos/2d/utils/dynamic-atlas/atlas.ts`?

**Comment by kaxifakl** [comment]
> Did you mean `Atlas` class, which is defined in `cocos/2d/utils/dynamic-atlas/atlas.ts`?

yeah
