### ISSUE TITLE
Bug 1.3.2 安卓上 cc.game.restart()报错

### ISSUE THREAD

**Issue by moonwalkerjay** [cocos/cocos-engine#1325]
4:36.458 3448 3464 D cocos2d-x debug info: Cocos2d-JS v3.13
11-28 18:44:38.453 3448 3464 E cocos js error:: /data/user/0/com.baiyou.dkd/files/blackjack-remote-asset/src/jsb_polyfill.js line:28901 msg:TypeError: cc.director.getScheduler(...)._schedule is not a function
11-28 18:44:38.454 3448 3464 D cocos2d-x debug info: Evaluating main.js failed (evaluatedOK == JS_FALSE)
11-28 18:48:59.072 1397 1461 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{e64af45 u0 com.baiyou.dkd/org.cocos2dx.javascript.AppActivity t3034} time:27741710
11-28 18:48:59.161 2481 16985 I AD-PLUGIN-SystemAdController: activityIdle:ActivityInfo{efc2c07 org.cocos2dx.javascript.AppActivity} mPendingSwitchingActivityInfo:null

**Comment by moonwalkerjay** [comment]
window.setTImeout里的报错     cc.director.getScheduler(...)._schedule is not a function

**Comment by jareguo** [comment]
这个 API 暂时还未实现好，麻烦用其它方式代替，我们会尽快完善。
