### ISSUE TITLE
Add and remove item when scrolling on Android

### ISSUE THREAD

**Issue by tgioihan** [cocos/cocos-engine#13256]
### Cocos Creator version

3.5.2

### System information

Android 11

### Issue description

 When adding and removing node when scrolling, the FPS dropdown from 60 to 49,50 even if I don't update any child.
Everything is great on IOS and the web.

### Relevant error log output

Here is my screen record 

https://user-images.githubusercontent.com/1877784/200266470-2ee2f648-b806-4a3d-9a00-e77704436d91.mp4

### Steps to reproduce

Run my example project :
[NewProject_2.zip](https://github.com/cocos/cocos-engine/files/9949674/NewProject_2.zip)

**Comment by minggo** [comment]
@tgioihan did you tested with release mode on Android?

**Comment by minggo** [comment]
I tested on Galaxy A12 with release mode, can not reproduce it. The fps looks good. Of course, you should enable showing fps in game.ts to show fps in release mode.

So I think it is not tested with release mode.
