### ISSUE TITLE
[3.6.2] planar shadow missing when model material enable instancing

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13255]
### Cocos Creator version

3.6.2

### System information

Window Editor

### Issue description

planar shadow missing when model material enable instancing

![企业微信截图_16678109931018](https://user-images.githubusercontent.com/8321365/200266260-aa9cb9d3-aa92-4ea6-88c8-6bab79b4e540.png)

disable instancing

![企业微信截图_16678110325014](https://user-images.githubusercontent.com/8321365/200266406-318d81c5-8164-4271-9a8d-ac6d5cbfa857.png)

### Steps to reproduce

test project.
[planar_shadow.zip](https://github.com/cocos/cocos-engine/files/9949672/planar_shadow.zip)

**Comment by troublemaker52025** [comment]
Resolved, please verify in v3.7.0 after 11/21

**Comment by pandamicro** [comment]
@troublemaker52025 please cherry pick this commit to 3.6.3

**Comment by troublemaker52025** [comment]
Sync this fix to v3.6.3

* https://github.com/cocos/cocos-engine/pull/13480
