### ISSUE TITLE
[3.6.x]dragonbones display error

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13258]
### Cocos Creator version

3.6.1,3.6.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/142296
![企业微信截图_16678115771422](https://user-images.githubusercontent.com/40415168/200272113-7afe54e8-e260-41a7-8b21-ae1430794ccb.png)

https://user-images.githubusercontent.com/40415168/200272149-5652f0e7-43b1-44b9-b35b-3710cfccc255.mp4

### Steps to reproduce

demo:
[NewProject_27.zip](https://github.com/cocos/cocos-engine/files/9949938/NewProject_27.zip)

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13287
