### ISSUE TITLE
[3.6.2] Pause audio will appear zipping sound

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13274]
### Cocos Creator version

3.6.2

### System information

iOS 15.7

### Issue description

Pause audio will appear zipping sound

### Steps to reproduce

test project

[testmusic33.zip](https://github.com/cocos/cocos-engine/files/9958879/testmusic33.zip)

**Comment by timlyeee** [comment]
Audio pause on ios calls openal pause directly and nothing else, considering fix this error with the refactor of audio system
