### ISSUE TITLE
[3.6.1] There is an exception in the listener of the expansion panel, the hide callback will be called 2 times

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#13271]
### Cocos Creator version

3.6.1

### System information

MacOS

### Issue description

![图片](https://user-images.githubusercontent.com/35944775/200486412-e4e5227f-2231-4b61-8820-ea6df8688b24.png)
<img width="679" alt="图片" src="https://user-images.githubusercontent.com/35944775/200486377-187503de-ad03-4eec-ac13-78693daf4772.png">

### Steps to reproduce

--

**Comment by knoxHuang** [comment]
Fixed, please test with version >= 3.8.2 and turn it on again if there is any problem.
