### ISSUE TITLE
Clear skeletonData for sp.Skeleton in Creator editor result a 'chunk' error.

### ISSUE THREAD

**Issue by LZhenHong** [cocos/cocos-engine#13285]
### Cocos Creator version

3.5.0, 3.6.1, 3.6.2

### System information

Cocos Creator Editor

### Issue description

Assign spine data to the `sp.Skeleton` component, then click the clear button in the Skeleton Data field. Result in the error below that freeze the editor:
![92549485-56de-4235-96be-dc9720604702](https://user-images.githubusercontent.com/9366368/200719038-d9a2280e-a2bf-402b-b737-929c81c648fa.png)

### Steps to reproduce

1. assign spine data to `sp.Skeleton` component.
2. clear the Skeleton Data.
3. the error would print in the editor's console.

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14402
