### ISSUE TITLE
Error on the editor due to prefab

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13298]
### Cocos Creator version

3.6.1,3.6.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/142401/
![image](https://user-images.githubusercontent.com/40415168/200812278-bcfbfa60-ccef-4672-bb5b-af3d05b3651a.png)

### Steps to reproduce

demo:
[Test (3).zip](https://github.com/cocos/cocos-engine/files/9970164/Test.3.zip)

https://user-images.githubusercontent.com/40415168/200812623-f2f4780f-ffd9-4a2a-aca1-5fd904b90ffc.mp4

**Comment by dogeFu** [comment]
https://forum.cocos.org/t/topic/142401/ has resolution now,it's not a bug.
