### ISSUE TITLE
script missing or invalid when use sys.localStorage

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#13308]
### Cocos Creator version

3.6.1

### System information

Windows10 Editor

### Issue description

When building a task, code that uses sys.localStorage will prompt a missing or invalid.

### Steps to reproduce

The issue is from : https://discuss.cocos2d-x.org/t/sys-localstorage-crashes-native-builds-v3-6-1/57513/2,
a demo is attaching in.

**Comment by PPpro** [comment]
I checked that this issue is fixed in v3.7.0, please try upgrading the version of Cocos Creator
