### ISSUE TITLE
能把creator.d.ts下的错误修改一下吗？

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#1331]
错误如下
export class RawAsset extends **CCObject** {
     不知道CCObject和Object定义中的有什么区别

export function jumpBy(duration: number, position: Vec2|number, y?: number, **height**: number, jumps: number): ActionInterval;

 dragonBones.**xxx**

**Comment by jareguo** [comment]
> 不知道CCObject和Object定义中的有什么区别

一个是 cocos 内部的，一个是 js 原生的，作用不同

> export function jumpBy(duration: number, position: Vec2|number, y?: number, height: number, jumps: number): ActionInterval;
> 
> dragonBones.xxx

有什么问题？？

**Comment by GameKeys** [comment]
export class CCObject extends Object{} 我整成继承还不对，行吧
没有报错的代码提示都没有问题，报错的提示就有问题。有的能改但有的不知道是否是原生调用的（不止是代码提示，还有对原继承的理解）
![2016-12-01 4 49 06](https://cloud.githubusercontent.com/assets/6950818/20787304/158159b8-b7a3-11e6-9d97-9506f9e2de80.png)

**Comment by jareguo** [comment]
麻烦 @knoxHuang  有空过一遍吧，看看哪些地方报错了

**Comment by GameKeys** [comment]
修改了一下，好多只是添加上了，里面还没有内容，就是不报错了。
看看对吗，给你们参考一下

**Comment by knoxHuang** [comment]
好的，我明天看看吧，能解决的就解决掉~

**Comment by GameKeys** [comment]
creator.d.ts还不能直接上传，整了个包
[creator.d.ts.zip](https://github.com/cocos-creator/engine/files/624114/creator.d.ts.zip)

**Comment by nantas** [comment]
@GameMidlet 
大部分能改的错误都已经修正了，目前你遇到的几个问题可以归类如下：

- 基类的 API 没有暴露出来，所以 ts 文件里缺少这部分的声明。
- 部分外部库的接口没有提供 API 声明，比如 spine，dragonBones 这些
- 可选参数的问题，ts 里可选参数必须放在最后一个位置，但 cocos 引擎有很多习惯用法是通过类型判断来决定一个可选参数是否被添加到了两个参数中间

这些问题短时间内无法解决，可能需要我们有空了再仔细研究一下，包括整个 API 类型信息的生成方式都可能需要更新（TS 已经放弃 d.ts 格式了，现在在推的是 typings）

**Comment by jareguo** [comment]
> 基类的 API 没有暴露出来，所以 ts 文件里缺少这部分的声明。
> 可选参数的问题，ts 里可选参数必须放在最后一个位置，但 cocos 引擎有很多习惯用法是通过类型判断来决定一个可选参数是否被添加到了两个参数中间

这两个问题已解决

> 部分外部库的接口没有提供 API 声明，比如 spine，dragonBones 这些

dragonBones 声明已添加，spine 的声明暂时不考虑添加了
