### ISSUE TITLE
[3.6.0] Android download file error: StreamResetException: stream was reset: INTERNAL_ERROR

### ISSUE THREAD

**Issue by wooden-uncle** [cocos/cocos-engine#13338]
### Cocos Creator version

3.6.0

### System information

Android

### Issue description

When downloading files, there is a possibility that errors

### Relevant error log output

<img width="770" alt="image" src="https://user-images.githubusercontent.com/117958684/201272579-494dbbf4-b204-4a36-9b72-bf504526c0f4.png">

### Steps to reproduce

occurs when download bigger files, and might be solved by set protocols:
```JAVA
            downloader._httpClient = new OkHttpClient().newBuilder()
                    .dispatcher(dispatcher)
                    .followRedirects(true)
                    .followSslRedirects(true)
                    .connectTimeout(timeoutInSeconds, TimeUnit.SECONDS)
                    .protocols(Collections.singletonList(Protocol.HTTP_1_1)) // add this line!
                    .build();
```

**Comment by novain1102** [comment]
Hi, may I ask how large file you download when this problem occured, or if you can provide me the URL?
