### ISSUE TITLE
ToggleGroup 能不能添加个属性

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#1333]
let group=cc.find('Canvas/ToggleGroup').getComponent(cc.ToggleGroup);
let count=group.node.childrenCount;//数据大小没有问题，内容有问题
let counta=group._toggleItems.length;
cc.log("count:"+count+"\t"+counta);
let index=group.node.children.indexOf(toggle);//目前还不知道这里面是什么东西
let indexa=group._toggleItems.indexOf(toggle);//这个内容是没有问题的
cc.log("index:"+index+"\t"+indexa);

假如ToggleGroup就添加一个事件,还想知道是哪个Toggle触发的事件
能不能把_toggleItems整出到外部，可以调用的API(类似于node. children)

**Comment by zilongshanren** [comment]
@GameMidlet 可以考虑提供一个 toggleItems 的属性，感谢建议。

**Comment by zilongshanren** [comment]
@GameMidlet 
1.5 版本会给 toggleGroup 添加一个 toggleItems 属性
