### ISSUE TITLE
ScriptEngine stuck in the cleanup method

### ISSUE THREAD

**Issue by PatriceJiang** [cocos/cocos-engine#13342]
Steps to reproduce
1. Create a empty scene
2. Export a windows project
3. Run & Quit

**Comment by PatriceJiang** [comment]
Known information

- Version 3.5.x does not have such issue
- Issue disappeared when the bullet physical engine is *NOT* enabled
- Issue disappeared when upgrading v8 to 10.9.194.4
- v8 stuck at `Run<EscapeAnalysisPhase>()` stage, issue disappeared after turning off `--turbo-escape`
- After running app for 5 minutes, `cleanup()` finish immeditaly
- Occurs on iOS & Mac & Windows 

Possible workarounds
1. Upgrade v8. Need to do this in next major version upgrade
2. Turn off `--turbo-escape`. Need to evaluate side effects further

**Comment by minggo** [comment]
@PatriceJiang please add information about the conditions that trigger this issue.

**Comment by PatriceJiang** [comment]
By adding the flag `--no-turbo-escape` the performance in some test scenes can be improved.   

According to https://v8.dev/blog/disabling-escape-analysis , ideally, we can assume that if the code is written correctly, *escape analysis* is not necessary.
