### ISSUE TITLE
Model with realtime animation will not show in Wechat buildin browerse

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#13363]
### Cocos Creator version

3.6.2

### System information

ios 16.0

### Issue description

https://store.cocos.com/app/detail/4207g, try this demo.

If I use real time animation, the model will not show in wechat build-in browser in ios 16.x, but for baked animation , all good.
![image](https://user-images.githubusercontent.com/26038745/201619017-f5367b27-b891-441c-b376-b07af35e2bb7.png)

### Steps to reproduce

open this link in ios 16.x wechat build-in browser, the model will not hosw

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13979
