### ISSUE TITLE
replace slpash screen in wechat will show default black splash first

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#13364]
### Cocos Creator version

3.6.2

### System information

iphone 15

### Issue description

after choosing replace splash screen for wechat, it will still show default black splash for about 0.4s( for old phones, it last longer)
![image](https://user-images.githubusercontent.com/26038745/201619970-acd67fa1-770b-49f2-8436-4e0629437257.png)

![image](https://user-images.githubusercontent.com/26038745/201620047-37c2cde6-9d5a-4d8e-8d1e-b2a0263b69a4.png)

### Steps to reproduce

choose replace splash for wechat ,and try it in wechat

**Comment by PPpro** [comment]
@mmyduckx please take a look

**Comment by novain1102** [comment]
Already solved.
