### ISSUE TITLE
Mouse inputs not detected "Preview In Editor"

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#13395]
### Cocos Creator version

3.6.2

### System information

OSX 12.6

### Issue description

Hello,

I can't detect mouse inputs when I launch the game in editor: "Preview In Editor"
The game in browser works well.

Did I missed something to configure on Cocos Creator on OSX?

https://user-images.githubusercontent.com/758680/201971689-cbf72cd7-a6f8-42d9-964d-0ddb8a656872.mp4

### Steps to reproduce

Crate a project on OSX
Try to detect inputs with preview in editor.

```
 input.on(Input.EventType.MOUSE_DOWN, this.onMouseDown, this);
           input.on(Input.EventType.KEY_DOWN, (event: EventKeyboard) => {
               console.log("key", event);
           }, this);
```

**Comment by PPpro** [comment]
Sorry, I can't reproduce the issue you encountered.
It looks like you're doing fine without anything missed.

would you please provide with a simple demo project ?
so that I can take a look into the issue.

**Comment by BenoitFreslon** [comment]
Hello there, I don't know how and why the inputs are working now. I just clicked on all my mouse buttons Left, middle right to enable the inputs after several tries.

**Comment by novain1102** [comment]
![image](https://github.com/cocos/cocos-engine/assets/18634782/e3c35d87-ab89-4bbd-85a5-f84bd33993d1)

![image](https://github.com/cocos/cocos-engine/assets/18634782/dae6c074-9834-4150-91d2-a19d3aa17c59)

Test for above, all work well. Closed issue.
