### ISSUE TITLE
An error occurred when using "director.runScene" to switch scenes in version 3.6.2

### ISSUE THREAD

**Issue by mambo723** [cocos/cocos-engine#13400]
### Cocos Creator version

3.6.2

### System information

Windows10 Chrome

### Issue description

An error occurred when using `director.runScene` to switch scenes, I hope to use `director.runScene` to switch scenes normally.

### Relevant error log output

```
base-node.ts:649 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Scene.walk (base-node.ts:649:36)
    at Scene._load (scene.ts:327:14)
    at Director.runScene (director.ts:438:15)
    at Scene2.runScene1 (Scene2.ts:10:18)
    at EventHandler.emit (component-event-handler.ts:175:17)
    at Function.emitEvents (component-event-handler.ts:89:19)
    at Button._onTouchEnded (button.ts:861:35)
    at CallbacksInvoker.emit (callbacks-invoker.ts:344:34)
    at NodeEventProcessor.dispatchEvent (node-event-processor.ts:288:33)
    at Node.dispatchEvent (base-node.ts:1162:30)
```

### Steps to reproduce

I created two scenes `Scene1` and `Scene2` in the editor, and attached the components `Scene1` and `Scene2` respectively:
```TypeScript
import { _decorator, Component, Node, SceneAsset, director } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('Scene1')
export class Scene1 extends Component {
    @property(SceneAsset)
    scene2: SceneAsset = null;

    runScene2() {
        director.runScene(this.scene2);
    }
}
```
```TypeScript
import { _decorator, Component, Node, SceneAsset, director } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('Scene2')
export class Scene2 extends Component {
    @property(SceneAsset)
    scene1: SceneAsset = null;

    runScene1() {
        director.runScene(this.scene1);
    }
}
```
Run the project in Chrome, click the button after entering `Scene1`, and call `runScene2` to switch to `Scene2` normally; but when clicking the button in `Scene2` to call `runScene1`, an error will occur.

### Minimal reproduction project

[Here's my post in the forum with the minimal reproduction project.](https://forum.cocos.org/t/topic/142650)

[I have some other questions also about preload scene, here is another post.](https://forum.cocos.org/t/topic/142671?u=1712655110)

**Comment by minggo** [comment]
Could you please provide a project to reproduce it? Thanks.

**Comment by mambo723** [comment]
@minggo 

> Could you please provide a project to reproduce it? Thanks.

I've uploaded the project to my post in the community, it's written in the last part above, but I can also upload a copy here.

[TestProject.zip](https://github.com/cocos/cocos-engine/files/10065007/TestProject.zip)

https://user-images.githubusercontent.com/33975950/203254703-36d139f6-ecfe-4130-85ce-adaf413ddec9.mp4

**Comment by minggo** [comment]
@mambo723 thanks

**Comment by SantyWang** [comment]
Thanks, The scene asset is not an ordinary asset and you cannot reference it like any other asset. You need to reload the scene asset every time when you want to run the scene.

**Comment by mambo723** [comment]
> Thanks, The scene asset is not an ordinary asset and you cannot reference it like any other asset. You need to reload the scene asset every time when you want to run the scene.

I'm sorry I didn't quite understand what you said.
In the project I uploaded, the scene asset are referenced in inspector:

![inspector_1](https://user-images.githubusercontent.com/33975950/203922999-52397d10-1970-463c-be01-3d646dcdd747.png)
![inspector_2](https://user-images.githubusercontent.com/33975950/203923015-35f9fbcb-75e6-4771-a15f-277674a9b446.png)
![inspector_3](https://user-images.githubusercontent.com/33975950/203923020-fad4e7f6-edc2-41e4-9456-78fc35a62bf4.png)

Do you mean that the Scene1 asset is not loaded after entering Scene3, so they cannot be switched to Scene1 normally?

But why Scene2 asset and Scene3 asset can be loaded successfully and used normally after entering Scene1 and Scene2?

Under what circumstances can the scene asset referenced by the inspector not be automatically loaded by the engine?

Or is the scene asset not allowed to be referenced in this way?

@holycanvas

**Comment by mambo723** [comment]
Perhaps developers should be prohibited from referencing scene assets in the editor's inspector.

@minggo @holycanvas 

In addition, maybe you should also pay attention to the problem of the large difference in the switching speed between using runScene and loadScene. (preloadScene has been used before using loadScene)
