### ISSUE TITLE
The model import will mount several of the same materials

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13404]
### Cocos Creator version

3.6.2

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/142569
![企业微信截图_16685051072968](https://user-images.githubusercontent.com/40415168/202112996-9f3aa75d-e413-428e-a7fa-e9ae0b1999e5.png)

### Steps to reproduce

。

**Comment by AFeiYA** [comment]
https://github.com/cocos/engine-extensions/pull/214
