### ISSUE TITLE
The contents of the labe_latlas file is missing

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13423]
### Cocos Creator version

3.4.2，3.6.2，2.4.10

### System information

window10

### Issue description

https://forum.cocos.org/t/topic/142701
![image](https://user-images.githubusercontent.com/40415168/202409028-c889d032-0352-44ff-a0d6-ebddd922cbff.png)
![企业微信截图_16686760349721](https://user-images.githubusercontent.com/40415168/202409075-9a7b974e-7e7c-436f-a6a5-34b18749521f.png)

![企业微信截图_16686758012069](https://user-images.githubusercontent.com/40415168/202409133-a824703e-02ed-4102-903b-154c395cb40b.png)

### Steps to reproduce

。

**Comment by yanOO1497** [comment]
修改测试例后验证无此问题，这些新建资源的内容是不重要的，不会影响导入结果。目前用户也无法复现，有复现再结合复现 demo 重新打开 issue。
