### ISSUE TITLE
[3.6.2] BlockInputEvents is invalid in some cases

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13440]
### Cocos Creator version

3.6.2

### System information

Chrome

### Issue description

add two sub node to button node, the BlockInputEvents node layer cover the another Node who Registered touch events. then button can be click bypass the BlockInputEvents layer.
![image](https://user-images.githubusercontent.com/8321365/202687364-9a28e8eb-21e5-442b-9b73-2e1aad624a3a.png)

### Steps to reproduce

test project
[demo (2).zip](https://github.com/cocos/cocos-engine/files/10040573/demo.2.zip)

**Comment by minggo** [comment]
Don't put `Node-001` as a child of Button. Should do it like this
![企业微信截图_d0bd8272-aede-483d-87f0-e8aba6741f0e](https://github.com/cocos/cocos-engine/assets/488203/864759c4-4e53-4e8b-8781-57e5b9b6d910)
