### ISSUE TITLE
cc.Sprite('')希望添加一下功能吧

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#1347]
Sprite(SpriteFrame|String newSpriteFrame) {
	var node = new cc.Node("Sprite");
	var sprite = node.addComponent(cc.Sprite);
	sprite.spriteFrame = newSpriteFrame;
	return sprite
}
cc.loader.loadxxx
var abc=cc.Sprite('abc');

希望添加这样的功能吧！不止Sprite。。。

**Comment by jareguo** [comment]
可以考虑提供一些类似 cc.Sprite.createNode('abc') 的 API，不过这种函数用户很容易自己封装一下吧？

**Comment by ZuoEr** [comment]
感觉没必要，之前就是这种API太多，臃肿
