### ISSUE TITLE
[3.6.2] Incorrect calculation of video display area

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13470]
### Cocos Creator version

3.6.2

### System information

iOS 15

### Issue description

we use widget to detect the display area, the white background can be seen.

<img src="https://user-images.githubusercontent.com/8321365/203212589-8bdadad2-755d-4b86-97b3-c5ccd5b6086f.png" width = "200" height = "600" alt="" align=center />

### Steps to reproduce

test project

[video-ios.zip](https://github.com/cocos/cocos-engine/files/10063154/video-ios.zip)

**Comment by novain1102** [comment]
Test for iphone11 iphone12 iphone14 iphone14plus iphone se, iphone 12 mini, iphone 13 mini.
![image](https://user-images.githubusercontent.com/18634782/203509884-5330dc02-a920-4611-ab90-a85cb70a1a9a.png)
Only iphone12 mini, iphone13 mini will show above issue.
![image](https://user-images.githubusercontent.com/18634782/203508672-e319bdd8-8d2e-4e36-84b7-421e4fb65a6c.png)

**Comment by novain1102** [comment]
For some devices, rendered pixels DO NOT equal physical pixels.(like iphone 12 mini, iphone 13 mini. which  the former is (1125,2536), yet the latter is (1080, 2340)).
So we need to cosider the scale factor between rendered pixels and physical pixels.
![企业微信截图_e1944236-9744-4a2c-b5af-2c038cc5dc74](https://user-images.githubusercontent.com/18634782/203935068-1f9ff252-69cd-4dd4-816e-03f38fa237e7.png)


![企业微信截图_faf64baa-84ea-44fb-85e4-3a162d2af63b](https://user-images.githubusercontent.com/18634782/203933965-2b90a927-fe47-448a-afd1-c14f86260ba9.png)

![企业微信截图_16691889486454](https://user-images.githubusercontent.com/18634782/203935235-2f9393a0-7d8f-4f88-a8bc-52db6fdf50ca.png)

**Comment by minggo** [comment]
Good to know.

**Comment by novain1102** [comment]
WebViewImpl also has this issue:
![5851669369806_ pic_hd](https://user-images.githubusercontent.com/18634782/203964673-834b01a1-0455-44b2-8f0c-4ed2644bc4ca.jpg)
After merge above PR:
![5861669370183_ pic_hd](https://user-images.githubusercontent.com/18634782/203964719-5af42a3b-d086-4079-a420-2ad04b6863f2.jpg)
