### ISSUE TITLE
[Cocos Creator 3.7.0] Release doc prepare: New Features and Bug Fixes list

### ISSUE THREAD

**Issue by AndyYuTian** [cocos/cocos-engine#13487]
3.7.0 is on the way and it is another huge milestone for us!!

A lot of important updates are comming, including Offline Global Illumination workflow support with probes, LODs, enhanced lightmap workflows, native editor scene, and improved default renders. We couldn't wait to share more with you.

We kindly ask all the contributors to reply with a small intro of your updates and bug fixes in this version below, and help us to work on the release document for 3.7.

Thanks for your support again!

**Comment by zxx43** [comment]
Fix particle gravity module with parent node

**Comment by stanleyljl** [comment]
**Add light probe**
    Light probe is used to deal with the lighting of characters or dynamic objects in the game world, and provide high-quality lighting (including indirect light) on moving objects in the scene. Its advantage is that it has good processing performance at runtime and precomputations are also fairly fast.

1, character using light probe
![企业微信截图_16675447863860](https://user-images.githubusercontent.com/26244076/203289060-d7cb618d-6ecd-4e69-8565-2f65ece9517a.png)

2, spheres using light probe with instancing
![MTY4ODg1MDkxMTE3NTg5Mw_846615_x-PAOVxqfa_kz47g_1667550109 1](https://user-images.githubusercontent.com/26244076/203289250-69e10cf9-6466-4dc9-853d-8475008e81b3.png)

**Comment by moshuying** [comment]
Add Mesh UV Debug

**Comment by moshuying** [comment]
1. [feature] Add mesh UV Debug 
![image](https://user-images.githubusercontent.com/37231523/203290546-62408dd4-8c7b-44d7-a9cb-f88d2eff63f6.png)
2. [feature] Add light probe gizmo
3. [fix] preview update WebGL, fix draw preview bug for all preview window , material-preview, mesh-preview, camera-preview and more.
4. [optimize] Improve the editing experience of large scenes and reduce the memory usage when editing scenes

**Comment by knoxHuang** [comment]
Add the Scale property to the reference image

![image](https://user-images.githubusercontent.com/7564028/203295506-aeb99e4f-b149-47de-bf78-383edc1df9be.png)

**Comment by obraz29** [comment]
But could you please fix all spine bugs first...

**Comment by xubing0906** [comment]
add reflection probe:https://github.com/cocos/3d-tasks/issues/12047
![image](https://user-images.githubusercontent.com/49358166/203302116-e7937baa-5b63-4900-b3bc-1dae7e2997ef.png)

**Comment by dumganhar** [comment]
- Switch to [swig](https://www.swig.org) to generate JS binding glue code, the old `bindings-generator` tool is deprecated now. The time cost of generating all JS binding code is reduced to `3~5 seconds`. Please refer to [README](https://github.com/cocos/cocos-engine/tree/develop/native/tools/swig-config) .
- Optimize the construction and destruction of se::Object, remove unused hash operations. [PR 12944]( https://github.com/cocos/cocos-engine/pull/12944 )
- Add se::Object::createObjectWithConstructor method to create JS object by JS constructor in CPP code. [PR 12946](https://github.com/cocos/cocos-engine/pull/12946)
- Support to pass command-line arguments to execution file on native desktop platforms ( Windows, Linux, macOS ). [PR 13268](https://github.com/cocos/cocos-engine/pull/13268)
- Add support to create, modify, check ES6 Map/Set for se::Object. [PR 13275](https://github.com/cocos/cocos-engine/pull/13275)

**Comment by PatriceJiang** [comment]
- Provide `cc::event::EventBus` and `cc::event::EventTarget` to simplify event dispatching within the engine. [PR 13100](https://github.com/cocos/cocos-engine/pull/13100)

**Comment by pandamicro** [comment]
- [BREAKING] Force type validator in `Pass.setUniform`, this is more strict than previous versions, especially on web platform. E.g. if a Vec4 value is passed to a Vec3 uniform, the engine will now raise an error in debug mode, previous version won't. https://github.com/cocos/cocos-engine/pull/13462

**Comment by yiwenxue** [comment]
* [feature] Add `FixedConstraint` support to `Physics` system. https://github.com/cocos/3d-tasks/issues/12930
* [feature] GFX now supports `blitTexture`. https://github.com/cocos/cocos-engine/pull/13831
* [feature] GFX now supports `Texture2DArray` and `Texture3D`. https://github.com/cocos/cocos-engine/pull/12938
* [feature] Effects can set a default value for the boolean Macro. https://github.com/cocos/engine-extensions/pull/177
* [fix] Correct the scaling behavior of `cylinder` and `cone` colliders in Cocos Creator. https://github.com/cocos/3d-tasks/issues/13994
* [fix] Fix the bug that `Vulkan` backend cannot upload huge buffers, solved by uploading by chunks. https://github.com/cocos/cocos-engine/pull/12978
* [fix] Correct the implementation of `PointToPoint` constraint of `PhysX` backend. https://github.com/cocos/cocos-engine/pull/13245
* [fix] Fix the bug that native physics system emits tons of wrong events https://github.com/cocos/cocos-engine/pull/13683
* [fix] Fix the access violations in `shadowCulling`. https://github.com/cocos/cocos-engine/pull/13606

**Comment by lealzhan** [comment]
- [feat] physics system supports lineStripCast 
   - https://github.com/cocos/cocos-engine/pull/13086 
   - https://github.com/cocos/cocos-example-projects/pull/246
- [feat] default physics Material is set through file in project setting now
   - https://github.com/cocos/cocos-engine/pull/13464
   - https://github.com/cocos/cocos-engine/pull/13852
- https://github.com/cocos/cocos-engine/pull/13824
- [opt] bullet MeshCollider set Mesh func x100 faster
    - https://github.com/cocos/cocos-engine/pull/13488
    - https://github.com/cocos/cocos-engine/pull/13624
    - https://github.com/cocos/cocos-engine/pull/13879
-    https://github.com/cocos/cocos-engine/pull/13421
- https://github.com/cocos/cocos-engine/pull/13312
- https://github.com/cocos/cocos-engine/pull/12911
## 2D Physics Features and Bug Fixes
- https://github.com/cocos/cocos-engine/pull/13859
- https://github.com/cocos/cocos-engine/pull/13839
- https://github.com/cocos/cocos-engine/pull/13819
- https://github.com/cocos/cocos-engine/pull/13810
- https://github.com/cocos/cocos-engine/pull/13790
- https://github.com/cocos/cocos-engine/pull/13747
- https://github.com/cocos/cocos-engine/pull/13650
- https://github.com/cocos/cocos-engine/pull/13585
- https://github.com/cocos/cocos-engine/pull/13239
- https://github.com/cocos/cocos-engine/pull/13177

**Comment by shrinktofit** [comment]
## Animation System

### Highlighted

- Here comes a new animation asset type: **animation variant**, make it possible to reuse the same animation graph on different characters.

    https://user-images.githubusercontent.com/28807867/197739550-ec674bdc-02c9-44d6-b998-a03a1583ef4d.mp4

### New Feature

- [**Experimental**] Class `AnimationController` added a method to dynamically overrides animation clips in animation graph.

- Class `AnimationController` added a method to query layer count in animation graph.

- Animation graph editor: support state copy operation.

- Animation graph editor: added a right click menu to turn a motion state into sub-statemachine state.

### Bugfixes

- Model animation preview: fixed that the playback speed is abnormal.

- Fixes and optimizes some status query method. See https://github.com/cocos/cocos-engine/pull/13323 for more information.

**Comment by bofeng-song** [comment]
[feature] support LOD 
Level of detail (LOD) is a technique reduces the number of GPU operations that requires to render distant meshes.
When a node uses LOD, engine displays the appropriate LOD level for that node based on the node’s distance from the Camera.
 [PR 13171](https://github.com/cocos/cocos-engine/issues/13171)


![屏幕捕获_2022_12_29_09_15_34_763](https://user-images.githubusercontent.com/3078423/209891229-2e487fb9-37c8-4fd8-9a24-4e08af01429d.png)

**Comment by novain1102** [comment]
- [feature] remove `BaseNode` class, please use `Node` class to instead. https://github.com/cocos/cocos-engine/pull/11977
- [feature] native.Downloader support abort function. https://github.com/cocos/cocos-engine/issues/12006 
- [feature] ios websocketServer supporthttps://github.com/cocos/cocos-engine/pull/12467
- [feature] add network-module in function-corpping https://github.com/cocos/cocos-engine/pull/12896
- [bugfix] fix videoPlayer display incorrectly in specific devices (iphone12 mini/iphone13 mini) https://github.com/cocos/cocos-engine/pull/13563
- [bugfix] fix webview display incorrectly in specific devices (iphone12 mini/iphone13 mini)  https://github.com/cocos/cocos-engine/pull/13570
- [bugfix] fix JSBLoadFont memory leak in macOS/iOS. https://github.com/cocos/cocos-engine/pull/13076
- [bugfix] refine downloader in iOS to fix slow remote loading. https://github.com/cocos/cocos-engine/pull/13737

**Comment by troublemaker52025** [comment]
* [feature] support compressed mipmaps https://github.com/cocos/cocos-engine/pull/13226

* [feature] support csm layers transition  https://github.com/cocos/cocos-engine/pull/13144

![csm transition](https://user-images.githubusercontent.com/20809296/204722083-37570ae9-45b8-4827-b066-81182ebab79b.png)

**Comment by chichinohaha** [comment]
[feature] auto update import path when move/rename .ts file https://github.com/cocos/cocos-editor/pull/1095
[feature] add lod gizmo https://github.com/cocos/cocos-editor/pull/1002
[feature] add reflection-probe gizmo and the panel for bake https://github.com/cocos/cocos-editor/pull/1069
[feature] Using the rect transform tool, you can hold down shift to scale evenly
[optimize] lightmap will record the results of each scene https://github.com/cocos/editor-extensions/pull/450
[optimize] Creator no longer has built-in 'Localization-editor' extension which means that 'Localization-editor' needs to be installed in the extension Manager

**Comment by dogeFu** [comment]
[feature] support native engine for creator
[feature] support multiwindow for editor preview with native engine
[fix] support 2d physic backend switch in editor preview
[fix] reference of prefab child failed to save in some case
已知问题:
native engine not support render debug

**Comment by yanOO1497** [comment]
【Feature】
● Support to interrupt the build task by clicking the X button during the build process；
● Build task queuing support
![image](https://cdn.nlark.com/yuque/0/2022/gif/1178456/1669777149518-6efbc682-7527-41e1-ae88-01fb02e43d46.gif)
【Feature】Support build pre-generated mipmaps when enable texture compress, which will be turned off by default after the upgrade of old projects.
![image](https://user-images.githubusercontent.com/27424848/205024889-44324f17-1032-4d1a-867f-c7960972a596.png)
【Feature】Support green channel flip config in image asset, support .exr suffix image asset to import
![image](https://user-images.githubusercontent.com/27424848/205025364-2b99916c-ef7f-40ac-8a55-0ff7500625c0.png)
【Optimize】The physical configuration of the project settings is adjusted to physical material, the old configuration will be automatically generated as custom physical material
![image](https://user-images.githubusercontent.com/27424848/205025059-368ce8ca-0616-4694-8a4d-d7d5711c7f98.png)
● 【Optimize】Optimize the animation editor interface display
![image](https://user-images.githubusercontent.com/27424848/205025115-1e8205ec-893a-489f-983c-6d2797a6f810.png)

**Comment by LinYunMo** [comment]
- [feature] Add sorting component, and provide sortingLayer order editing interface, users can use this component to control the rendering order of meshRender. https://github.com/cocos/cocos-engine/pull/12465
- [BREAKING] We removed the condition that the layout must have children to update the layout, now the layout will update the layout based on dirtyFlag, regardless of whether it has children or not.https://github.com/cocos/cocos-engine/pull/13630

**Comment by naturalch** [comment]
- [optimize] remove joint texture layout to prject-settings
![image](https://user-images.githubusercontent.com/39176194/206655728-2446ecb9-6582-412d-98d0-82257c961bca.png)
- [feature] wechatgame support the high performance mode
![image](https://user-images.githubusercontent.com/39176194/206656331-8cae9e99-01c3-4727-a2ef-273c5205ee17.png)
- [fix] native build platform do not support chinese or special characters
- [optimize] update default compress presets
![image](https://user-images.githubusercontent.com/39176194/206657287-d4fb3373-aa95-49d3-84cf-1f785fa98ec4.png)
- [optimize] update splash setting
![image](https://user-images.githubusercontent.com/39176194/206658640-175ae452-a8b3-4b8e-9309-1bb44965298e.png)
- [optimize] remove generate build extension case to create extension panel
![image](https://user-images.githubusercontent.com/39176194/206658830-3b36638c-2386-4960-8696-e1857204680a.png)

**Comment by PPpro** [comment]
### Bug Fix
- fix some devices can't load subpackages on ByteDance platform https://github.com/cocos/cocos-engine/issues/12815
- fix WeChat webp support detect https://github.com/cocos/cocos-engine/issues/11261

### Optimization
- reduce engine size and improve particle instantiation performance https://github.com/cocos/cocos-engine/pull/13248

**Comment by jk20012001** [comment]
- [feature] support stationary light source with baked indirect lighting and real-time direct lighting https://github.com/cocos/cocos-engine/pull/13327
 - [feature] support exr textures with signed floating-point data https://github.com/cocos/cocos-engine/pull/13619
 - [optimization] better edge looking for fxaa https://github.com/cocos/cocos-engine/pull/13457
 - [optimization] default skybox, light & shadow settings and pbr material parameters  https://github.com/cocos/cocos-engine/pull/13265 https://github.com/cocos/cocos-engine/pull/12917

**Comment by arsen2010** [comment]
- [optimize] the interface of Editor in window platform.
![image](https://user-images.githubusercontent.com/13517177/207010471-687c5785-4275-4a87-9a40-afb61096567a.png)
- [feature] add new propery of node 'mobility'.
![image](https://user-images.githubusercontent.com/13517177/207010949-d5401acc-4f40-4f70-8d45-e02f6a36b503.png)
- [optimize] add 'simplify' algorithm in editing mesh optimizer of fbx.
![image](https://user-images.githubusercontent.com/13517177/207011418-808aec1f-3a5d-47c2-b53b-ca2058029379.png)
- [fix] support to select multiple folds to edit.
![image](https://user-images.githubusercontent.com/13517177/207012140-710a6d75-afe8-483f-83f5-cc64c0954992.png)
- [optimize] assets panel add ipc message 'asset-db:pause' and 'asset-db-resume' to lock or unlock the panel.
![image](https://user-images.githubusercontent.com/13517177/201089366-519917d8-a1c5-498c-8a07-3e2a572d5b12.png)
- [optimize] in 2d project create a camera under canvas node, the visibility property of camera include 'DEFAULT' value.
![image](https://user-images.githubusercontent.com/13517177/198294025-1b2257a3-1e7f-47fe-b99d-747547c916b9.png)
- [fix] fix the bug of setting 'autoheight' attribute to ui-textarea but it cannot work correctly.
- [feature] add new extension panel of Light Probe
![image](https://user-images.githubusercontent.com/13517177/207014979-1e89a0c7-57e4-4b16-b1cc-1d3fd6e53f79.png)
- [feature] add Sorting Layers in Project Settings 
![image](https://user-images.githubusercontent.com/13517177/207015397-c8fc62cb-0c81-4bde-a465-35b90b838d1c.png)
- [feature] add one new asset called 'animation graph variant' and enable editing it
![image](https://user-images.githubusercontent.com/13517177/207016403-a5dbfd5a-d5bf-40d8-b12c-71c2809423d1.png)
- [optimize]  support to copy and paste the state of animation-graph
![image](https://user-images.githubusercontent.com/13517177/207016840-3ca29f7c-de7b-4272-8e72-feab38d1c60d.png)
- [optimize] optimize the preview are operating of blend 2d motion state 
![image](https://user-images.githubusercontent.com/13517177/207017296-28bd95e9-8238-4266-a90c-a0ca88884a64.png)

**Comment by dogodo-cc** [comment]
[feature] console panel add info type and support multi selected
![image](https://user-images.githubusercontent.com/35713518/207018523-b211e55f-8d49-4c8c-a7ee-24ee7d731384.png)
[feature] Help scene camera to expose more control properties
![image](https://user-images.githubusercontent.com/35713518/207019077-7ecc27f5-e0b0-42cf-b7a8-25b55a93f3e0.png)

**Comment by doommm** [comment]
### Feature

- renew extension manager for better user experience of extension management

![image](https://user-images.githubusercontent.com/20528478/207029252-0bad230d-43af-40bc-8bd3-1f32acbeaca1.png)
![image](https://user-images.githubusercontent.com/20528478/207029329-b025e7a2-ec3d-45b9-8e3e-8cd2171eab9e.png)

**Comment by zhakesi** [comment]
* [fix] fix native dragonbones component not init ui contentSize https://github.com/cocos/cocos-engine/pull/13678
* [fix] fix 2d module mesh buffer indices out of range https://github.com/cocos/cocos-engine/pull/13715
* [fix] fix spine cached mode https://github.com/cocos/cocos-engine/pull/13525
* [optimize] remove dragonbones batch error report https://github.com/cocos/cocos-engine/pull/13536

**Comment by pandamicro** [comment]
> But could you please fix all spine bugs first...

@obraz29 Please take a look at the above note

**Comment by AndyYuTian** [comment]
Closing this issue, if there is more infomation to fil, please put into the share document: https://doc.weixin.qq.com/doc/w3_AfEAqQaZACQ118ZYkQdQ8uPXwbIsA?scode=ADcAmwdCAAoUI0yxkqAfEAqQaZACQ
