### ISSUE TITLE
Raw assets sets on property panel are inaccessible from code and potentially loaded twice

### ISSUE THREAD

**Issue by javierhoar** [cocos/cocos-engine#1350]
Hi,
I found a problem on the javascript engine related to assets management. Raw assets set on property panel are created automatically before the scene start but they cannot be accessed from code because cc.load.getRes doesn't find it even though the resource is present on cc.loader._cache.
Debugging a bit I found that cc.load.getRes fail because cc.loade._getResUuid(url) fail as well. 
The problem is that the mapping from the raw assets url to Uuid is not being created when the resources is created automatically.
On cc.loader.resources.pathToUuid the mapping is not present and cc.loade._getResUuid(url) search on that structure for the mapping.

This problem cause that raw assets are loaded twice, once because the asset is created and load automatically and next time for instance  cc.audioEngine.playEffect(clip) is called. This happen because playEffect relays on cc.load.getRes to find the clip, but due cc.load.getRes is failing, the resource es created and load again. So as a result cc.loader._cache has the same resource with different ids.

Exactly the same problem happens for texture2d set as a property, it's created automatically but it's inaccesible using cc.loader.getRes.

This is a new issue appeared recently because before of version V1.3.1 this worked properly.

Thanks

**Comment by jareguo** [comment]
Hi Javier, 
You should not use loader.getRes in this situation, if you need to access by **url**, you should use cc.loader.loadRes.

**Comment by jareguo** [comment]
> This problem cause that raw assets are loaded twice, once because the asset is created and load automatically and next time for instance cc.audioEngine.playEffect(clip) is called.

This maybe a bug, @VisualSJ 麻烦看下

**Comment by javierhoar** [comment]
Hi Jareguo, 
thanks for the quick answer. 
I can use loadRes but its not the case, if I do that the resource will be loaded twice. You use loadRes when you want to loada resource dynamically in runtime in any moment. But when you set a raw assets as a property, the engine already load the assets before the first scene start. the problem is that the resource cannot be accessed by url after the engine has loaded it.
The  workaround I have to do now to use the asset already loaded is iterating over all resources on cc.loader._cache searching for any that match the url, then I get the id of it and after that I can find the assets using cc.load.getItem() using that found id, here the hack:

getAudioClip = function(url)
{
	var audioClipUrl = url;
	var audioClipId = "";
	for (var key in cc.loader._cache) {
		 if (cc.loader._cache.hasOwnProperty(key)) {
			var elem = cc.loader._cache[key];
			if(elem.url == audioClipUrl){
				audioClipId = key;
				break;
			}
		}
	}
		
	var audioClip = cc.loader.getItem(audioClipId);
    return audioClip;
}; 

As you can see, I had to do that because getRes is not working for raw assets resources automatically loaded. As I commented before this worked properly on old releases of cocos creator.

Regards,
Javier.

**Comment by jareguo** [comment]
> I can use loadRes but its not the case, if I do that the resource will be loaded twice

Is this bug limited to the audio clip, or will it affect other types of assets?

**Comment by javierhoar** [comment]
For Texture2d happen exactly the same, didnt check other types, but I think it happens with any raw raw asset.

Javier.

**Comment by jareguo** [comment]
Okey, thanks!

**Comment by VisualSJ** [comment]
>   This problem cause that raw assets are loaded twice, once because the asset is created and load automatically and next time for instance cc.audioEngine.playEffect(clip) is called.

I run this code in the example-cases.

    cc.audioEngine.playEffect('res/raw-assets/resources/audio/music_logo.mp3');

Resource loading is normal. How to be able to appear repeatedly load?

![image](https://cloud.githubusercontent.com/assets/7113508/21090541/75be6786-c07b-11e6-817c-2653a0de9c7d.png)

**Comment by javierhoar** [comment]
Hi VisualSJ,
playEffect works fine if the mp3 is not already loaded automatically. if you declare the mp3 as a property on any scene element. that mp3 is loaded automatically by the engine during scene loading and before the scene is shown.  playEffect without already load the resource adds extra time to load the resource and may run the sound a bit late. There are cases where you need that all mp3 are loaded before the scene is shown. that's way I set mp3 as a properties.

The problem is that automatic resource loading add the loaded resource to cc.loader._cache with the id as a key then when you want to fetch the resource using the url, getRes does not work, because getRes find the resouce by the url. Here two snapshots, firstone with the resource loaded automatically, second one with the resource loaded again after call play effect.  

1) 
![image](https://cloud.githubusercontent.com/assets/24510463/21099127/34e840ea-c04b-11e6-8a8a-a81627931e2b.png)

2)
![image](https://cloud.githubusercontent.com/assets/24510463/21099227/cd62b0d0-c04b-11e6-9ea3-e618a67305e7.png)

In my case I need to use the automatica resource loaded because I want no delay when the mp3 is played, but also because I need to get the sound duration before the scene is shown.
So as can be seen on both screenshot raw assets set on property panel:
![image](https://cloud.githubusercontent.com/assets/24510463/21099326/6c4fc516-c04c-11e6-9117-f6927c8f8c1d.png)
are loaded automatically as expected and manual describe. But the problem is that on _cache structure the resource is added with an id as a key and then getRes does not work even though the resource is alredy loaded.

**Comment by javierhoar** [comment]
I had an application working fine on an older versions of cocos creator but after update, I think, to 1.3.0 and newer, my app stop working.

**Comment by VisualSJ** [comment]
Thanks @javierhoar 
https://github.com/cocos-creator/engine/pull/1324

With regard to the problem of repeated loading of resources, we have fixed.
This is because the cache index allows for UUID and URL.

It's changed to URL now.

**Comment by javierhoar** [comment]
Thanks you @VisualSJ for the fix.
Just a question, after the fix, does automatic resource loading still work before the scene is shown? 
Thanks in advance

**Comment by jareguo** [comment]
Thanks @javierhoar , resource loading still work before scene shown
