### ISSUE TITLE
WebAssembly.instantiate didn't work in Android

### ISSUE THREAD

**Issue by kaxifakl** [cocos/cocos-engine#13502]
### Cocos Creator version

2.4.10

### System information

Window 10

### Issue description

There has no problem in web env, but didn't trigger callback in Android;
```
WebAssembly.instantiate(buffer, {
        wbg: {
        }
    }).then(res => {
        console.log('succ');
    }, (err) => {
        console.log('fail', err);
    })
```

### Steps to reproduce

none

**Comment by minggo** [comment]
Please use english in future. Thanks.

Why you use WebAssembly on Android?

**Comment by kaxifakl** [comment]
> Please use english in future. Thanks.
> 
> Why you use WebAssembly on Android?

For simple import with more quickly lib, like `gzip.wasm`.Instead of cpp module,because it needed adapter both in native and web.

**Comment by minggo** [comment]
But you can use gzip cpp version on android and WebAssembly on web like engine does. So i don't know why use WebAssembly on Android.

**Comment by kaxifakl** [comment]
> But you can use gzip cpp version on android and WebAssembly on web like engine does. So i don't know why use WebAssembly on Android.

For convenient transplanting without using custom engine.
I think the most import problem is why webassembly didn't work in Android.
Is there any solution to fix it?

**Comment by minggo** [comment]
I don't know, we haven't use WebAssembly on Android. And there is not plan to do it. And i think it is nothing about engine.

**Comment by qingwabote** [comment]
The job of "WebAssembly.instantiate" is executed in the background thread of v8, and put into foreground task queue after finishing. You must call "v8::platform::PumpMessageLoop" in cocos event loop to run the foreground task.
