### ISSUE TITLE
Can't use the URL object in native platform

### ISSUE THREAD

**Issue by mambo723** [cocos/cocos-engine#13546]
### Cocos Creator version

3.6.2

### System information

Windows simulator, Android

### Issue description

Can't use the `URL` object in native platform, the code is as follows: `let obj = new URL("url string");`.
Such use will generate an error in the `web-adapter.js` file.

### Relevant error log output

```log
TypeError: Cannot read property 'toLowerCase' of undefined
    at new <anonymous> (jsb-adapter/web-adapter.js:357:35)
    at Function.getRecordData (assets/main/index.b1c91.js:7911:22)
    at LoadingScene.getRecordData (assets/main/index.b1c91.js:1593:17)
    at LoadingScene.onLoad (assets/main/index.b1c91.js:1554:16)
    at eval (eval at createInvokeImplJit (src/cocos-js/cc.c2244.js:29938:69), <anonymous>:3:65)
    at OneOffInvoker._invoke (src/cocos-js/cc.c2244.js:29945:19)
    at OneOffInvoker.invoke (src/cocos-js/cc.c2244.js:29875:22)
    at NodeActivator.activateNode (src/cocos-js/cc.c2244.js:30200:31)
    at Scene._activate (src/cocos-js/cc.c2244.js:28976:48)
    at Director.runSceneImmediate (src/cocos-js/cc.c2244.js:36573:23)
```

### Steps to reproduce

Just use `URL` object in project, like this: `let obj = new URL("url string");`.

### Minimal reproduction project

Any project running in the native platform will generate an error where the URL object is used.

I also reported this bug in the community: [https://forum.cocos.org/t/topic/143060](https://forum.cocos.org/t/topic/143060)

**Comment by minggo** [comment]
URL is part of web standard, but native is not a web platform. So you can not use it on native. All web special features can not be used on native platforms.

**Comment by mambo723** [comment]
> URL is part of web standard, but native is not a web platform. So you can not use it on native. All web special features can not be used on native platforms.

I know that special web standard features cannot be used in native platform as a matter of course, but I think that if it is not allowed to be used in the native platform, its construction method should not be implemented in the adapter file, which will make people mistakenly think that you have adapted these web standard features in the native platform.

@minggo

**Comment by minggo** [comment]
web-adapter just provide features needed by engine. It doesn't adapt the whole web environment.

**Comment by mambo723** [comment]
> web-adapter just provide features needed by engine. It doesn't adapt the whole web environment.

Thanks for your answer, if I can see the relevant instructions in the documentation, there will be no misunderstanding, although this is not a big problem.

**Comment by minggo** [comment]
Yep, we will complete the doc.

**Comment by endel** [comment]
Hi there. Is this file open-source? `jsb-adapter/web-adapter.js`
I'm interested in making a pull-request to bring URL parsing to Cocos native platform.

**Comment by minggo** [comment]
@endel in v3.x, the adapter is in platforms folder. If you mean 2.x, it's here https://github.com/cocos-creator-packages/jsb-adapter.
