### ISSUE TITLE
[3.6]spine native platform display exception

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13566]
### Cocos Creator version

3.6.1,3.6.2

### System information

window10, chrome

### Issue description

https://forum.cocos.org/t/topic/143085
![image](https://user-images.githubusercontent.com/40415168/203939431-e93f89d4-40fa-48ac-a8d9-f7645134e474.png)

The display is normal when 38 nodes are created.
当只创建 38 个 spine 节点，显示是正常的.
![image](https://user-images.githubusercontent.com/40415168/203940628-2c783579-9fbf-4212-bcb2-852505184f79.png)

The display does not work properly when 39 nodes are created.
当创建数量大于 38 个 spine 节点，显示就开始不正常.
![image](https://user-images.githubusercontent.com/40415168/203940800-2d713a79-31c4-46cf-a2d0-1344df112814.png)

When the value of IB_SCALE is changed to 8, the web page can be displayed normally, but the native platform is still not displayed properly.
当IB_SCALE的值改为8时，网页可以正常显示，但原生平台仍然不能正常显示。
engine\cocos\2d\renderer\static-vb-accessor.ts public static IB_SCALE = 4 -> IB_SCALE  = 8;
![image](https://user-images.githubusercontent.com/40415168/203941272-cf2048b5-1669-4eba-91e8-be8851679e28.png)

The native platform can modify the value of INIT_INDEX_BUFFER_SIZE.
原生平台可以修改 INIT_INDEX_BUFFER_SIZE 的数值.
![image](https://user-images.githubusercontent.com/40415168/203943441-4dd2507f-7fc8-4c3d-9e27-92119f40e27e.png)

### Steps to reproduce

demo:
[cocos-3.x-demo-main.zip](https://github.com/cocos/cocos-engine/files/10090051/cocos-3.x-demo-main.zip)

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13715
