### ISSUE TITLE
v3.6版本里面怎么开启碰撞检测调试功能

### ISSUE THREAD

**Issue by houdianjie** [cocos/cocos-engine#13572]
### Cocos Creator version

3.6

### System information

Win10

### Issue description

v3.6版本里面怎么开启碰撞检测调试功能

### Steps to reproduce

2.x里面有cc.director.getCollisionManager().enabledDebugDraw = true;
请问3.6版本有替代的方法么

**Comment by minggo** [comment]
Please use english in future. 
@holycanvas does v3.x support this feature?

**Comment by lealzhan** [comment]
**2D Physics** can turn on debug mode like this:
![image](https://user-images.githubusercontent.com/9999378/208801453-6ff426ae-ab2e-451a-801c-6b7d83121685.png)
https://docs.cocos.com/creator/manual/en/physics-2d/physics-2d-system.html

**3D Physics** doesn't have debug mode at this moment.

**Comment by minggo** [comment]
> 3D Physics does have debug mode at the moment.

@lealzhan  Did you want to say `doesn't`?

**Comment by lealzhan** [comment]
> > 3D Physics does have debug mode at the moment.
> 
> @lealzhan Did you want to say `doesn't`?

yes..
