### ISSUE TITLE
[Editor]some problems in editor

### ISSUE THREAD

**Issue by kaxifakl** [cocos/cocos-engine#13596]
### Use Case

...

### 1. Start Scene
There has no config about setting default start scene in 3.6.2.
![image](https://user-images.githubusercontent.com/63728902/204697538-1bbb04c3-5184-4737-afb7-3e4cf7d0ebea.png)
There can set it but it will become current scene when restart editor.
![image](https://user-images.githubusercontent.com/63728902/204697763-cfc771d8-7848-4cd1-9efa-776e4d912e6d.png)
---
### 2. Simulater Config
There has no config about setting simulater starting config in 3.6.2.
But it can config in 2.4.x
![image](https://user-images.githubusercontent.com/63728902/204698284-e1fa3020-7ca6-404b-a1db-fe96a35edf46.png)

### Alternatives Considered

I think it will be a effective solutions that adding or removing some feature from user's requirement  within a certain range.

**Comment by kaxifakl** [comment]
3.Without api tip
![image](https://user-images.githubusercontent.com/63728902/204938494-5e41ce90-b9f6-433a-9a28-207fadd9946c.png)
It's not work when adding component life methods since 3.x.
The problem is caused by the file called cc.d.ts.

**Comment by kaxifakl** [comment]
@jareguo

**Comment by pandamicro** [comment]
There are multiple issues here, please report code completion issue in a separate one.

**Comment by wuzhiming** [comment]
1. you can try it again
2. now you can config simulator when simulator is launched
3. fixed
