### ISSUE TITLE
tiled map layer size calculation error

### ISSUE THREAD

**Issue by zvars** [cocos/cocos-engine#13594]
### Cocos Creator version

all versions

### System information

Windows 10

### Issue description

https://forum.cocos.org/t/topic/143240

### Steps to reproduce

just drop tile map fie to project

map properties:
![image](https://user-images.githubusercontent.com/36719037/204689209-f95d9e4e-4180-4a48-9301-47338c21f8d2.png)

map layers: 
![image](https://user-images.githubusercontent.com/36719037/204689720-4de6b2f2-66e3-40de-8a56-d3a437ca1936.png)

hover mouse right bottom of map editor view for map pixel size, then compare with layer size calculate by cocos engine:
![image](https://user-images.githubusercontent.com/36719037/204690092-04c5f6e2-0275-4e98-aa26-9024d67e776c.png)
![image](https://user-images.githubusercontent.com/36719037/204690133-8af17ced-872b-4005-878b-8d606fb253f0.png)

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13817
