### ISSUE TITLE
assetManager.loadRemote can‘t load android & ios device url assets

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#13614]
### Cocos Creator version

3.6.2

### System information

macos

### Issue description

![图片](https://user-images.githubusercontent.com/35944775/204977650-5c828547-eb8c-45db-a1ec-dbe40f9918f8.png)
![图片](https://user-images.githubusercontent.com/35944775/204977499-ab314d46-41e4-411c-9b24-b7902319176f.png)
![图片](https://user-images.githubusercontent.com/35944775/204977815-f499c47b-46c9-4559-ac25-eda20f4514c0.png)
The image resource is there, but it doesn't load.
Previously in 3.4.x it was loading fine

### Steps to reproduce

Download the project below and open it in CocosCreator. Then just build the android or ios package and test it.
下载下方的项目，然后在 CocosCreator 中打开它。之后构建 android 或者 ios 包并测试即可。

### Minimal reproduction project

[loadRemoteErrorTest.zip](https://github.com/cocos/cocos-engine/files/10129649/loadRemoteErrorTest.zip)

**Comment by novain1102** [comment]
saveImageData is an async function. You should use like:
```
        native.saveImageData(pixelData, path, width, height, filePath).then(()=>{
            console.log("Save image data success");
        }).catch(()=>{
            console.log("Fail to save image data");
        });
```
Try to revise script like this :
![image](https://user-images.githubusercontent.com/18634782/208072399-669f6220-7c0c-425b-aea3-ffcbc685b723.png)
Run well like this:
![image](https://user-images.githubusercontent.com/18634782/208072637-8c5aeaa0-a45e-47b6-afc8-c36ca1872420.png)
