### ISSUE TITLE
uitransform can't be triggered

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#13621]
### Cocos Creator version

3.6.2

### System information

macos

### Issue description

-

### Steps to reproduce

Download the demo below, open the project using CocosCreator, run it on your browser, and click on the web page. It should normally output the text "123" in the console.
下载下方的 demo，使用 CocosCreator 打开项目，运行在浏览器上，点击网页页面。正常应该会在控制台输出文字 “123”。

### Minimal reproduction project

[testHit.zip](https://github.com/cocos/cocos-engine/files/10131672/testHit.zip)

**Comment by minggo** [comment]
If want to treat it as a UI node, should put it into canvas, and also change its Layer. In the demo provided, buildings is treated as a 3d node.
