### ISSUE TITLE
getDuration of audioclips on JSB doesn't work, always returns -1 

### ISSUE THREAD

**Issue by javierhoar** [cocos/cocos-engine#1370]
Hi guys,
when testing a cocoscreator app on the simulator or by building to windows,  getDuration of audioClips always returns -1. This was tested on Release 1.3.2

Also in order to improve interface,  now getDuration requires pass the cc.audioEngine's audioId as a parameter and to obtain the id, the audio mast be played before, 
var id = cc.audioEngine.playEffect(sound);
var duration = cc.audioEngine.getDuration(id);

Most of the time is useful to get the duration only without play the clip, can the interface be improved to get the duration using the clip url and without play it before?

Thanks in advance.

**Comment by javierhoar** [comment]
Hi guys,

I was debugging this a bit to see why getDuration always returns -1 and I think I found a problem on AudioEngine-win32.cpp, and function "float AudioEngineImpl::getDuration(int audioID)"

Im doing this in code:
"var clip = "any.mp3";
cc.audioEngine.preload(clip , function(val){
	var id = cc.audioEngine.playEffect(clip );
	var dur = cc.audioEngine.getDuration(id)
});"

So when the getDuration is called, the audio is already loaded and playing. but still the result is -1.
I think the problem is here:

float AudioEngineImpl::getDuration(int audioID)
{
    auto& player = _audioPlayers[audioID];
    if(player._ready){
        return player._audioCache->_duration;
    } else {
        return AudioEngine::TIME_UNKNOWN;
    }
}

Because even thought player._audioCache->_duration has the right duration, the function always returns -1 because player._ready is false.

Could you please check?

Thanks in advance

**Comment by VisualSJ** [comment]
@dumganhar Look at this issue.

**Comment by dumganhar** [comment]
I'm busy for other projects, I will take a look at this issue when I have time.
Yes, `getDuration` seems not to works well on Win32. :(
Need refactoring...

**Comment by javierhoar** [comment]
It is a very useful feature. Hope you can fix it.

Thanks in advance.

**Comment by zhefengzhang** [comment]
There is no such problem in 2.4.x and 3.0.0 versions.
