### ISSUE TITLE
3.6.1 IOS 签名后 无法加载文件 assertManager.loadRemote

### ISSUE THREAD

**Issue by yinniermei** [cocos/cocos-engine#13758]
### Cocos Creator version

3.6.1

### System information

iphone 11 pm

### Issue description

3.6.1 IOS 签名后 无法加载文件 assertManager.loadRemote 

### Steps to reproduce

100%必现

**Comment by yinniermei** [comment]
assetManager.loadRemote(Global.instance.serverUrl + "?r=" + Date.now().toString(), (err:Error, ret:JsonAsset) => {
            //隐藏加载
            if( !err ) { //加载未发生错误
                Global.instance.serverCfg = ret.json;
				console.log("hcgame====>当前读取到的数据" ,JSON.stringify(ret.json));
				// 通知回调
				callback && callback();
            } else {
                 console.log("hcgame====>读取错误", err);
			}
        });

**Comment by novain1102** [comment]
请问使用的是哪种签名? 个人签 or 企业签 or 超级签? 
是走的archive export 后的ipa包安装验证的还是怎么验证的?
我这边目前验证个人签是没问题的. 方便的话发个demo我们这边看看具体原因

**Comment by yinniermei** [comment]
把这里注释掉 就好了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月21日(星期三) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cocos/cocos-engine] 3.6.1 IOS 签名后 无法加载文件 assertManager.loadRemote (Issue #13758)





 
请问使用的是哪种签名? 个人签 or 企业签 or 超级签?
 是走的archive export 后的ipa包安装验证的还是怎么验证的?
 我这边目前验证个人签是没问题的. 方便的话发个demo我们这边看看具体原因

**Comment by novain1102** [comment]
已与有类似问题的用户确认, 都是由于使用了第三方的企业签导致. 通过xcode自行签名/商店分发/使用软件(如爱思助手)安装都是正常的.
已告知相关用户, 有类似问题可以先把下面后台下载相关代码注释掉. 猜测是通过第三方企业签的涉及到了权限修改.
![311fd060bca68cc0698dbda5f95d57b090863389_2_1380x502](https://user-images.githubusercontent.com/18634782/209644335-991eb5bf-6495-452c-a8d0-f1310969ba10.png)
目前没想到太好的可以在不修改代码和保证后台下载功能的同时解决问题的方法.
持续关注该问题.

**Comment by novain1102** [comment]
No longer tracked due to problems caused by not using official authorized methods
