### ISSUE TITLE
接电话后返回游戏声音没有

### ISSUE THREAD

**Issue by rongmingLi** [cocos/cocos-engine#1377]
接电话后，以下事件无响应，导致游戏声音无法恢复
cc.game.EVENT_HIDE
cc.game.EVENT_SHOW 
此时，就算重新使用cc.audioEngine.playMusic()也无法再次播放声音。

**Comment by pandamicro** [comment]
native 还是 web ？

**Comment by lich2333** [comment]
ios 原生上也会有这个问题。 @pandamicro  
论坛反馈https://forum.cocos.org/t/ios13/85654

**Comment by xianyinchen** [comment]
该问题已在 2.4.4 版本修复，iOS14.4 系统上验证没有复现。

**Comment by majunxin** [comment]
升级到了2.4.4，iOS14.4，依然没有修复
原生，使用audioEngine，来了个电话，整个游戏声音都没了，怎么手动播放也没有声音。

**Comment by jkcnl001** [comment]
@xianyinchen 这个能修复一下么

**Comment by jkcnl001** [comment]
ios14 来电跟闹钟上滑不进入后台  就会导致声音不能播放了

**Comment by jkcnl001** [comment]
@pandamicro

**Comment by zhefengzhang** [comment]
你好，你可以参考这个修复 pr 手动修复一下你的引擎，pr 已经合并到 2.4.6 版本，即将合并到 3.3 版本。
https://github.com/cocos-creator/engine-native/pull/3565
定制引擎的流程参考：
https://docs.cocos.com/creator/3.1/manual/zh/advanced-topics/engine-customization.html?h=%E5%AE%9A%E5%88%B6
