### ISSUE TITLE
steam & cocos vulkan

### ISSUE THREAD

**Issue by whaqzhzd** [cocos/cocos-engine#13785]
### Cocos Creator version

3.6.1

### System information

windows 10

### Issue description

使用steam api在cocos vulkan 下无法显示steam界面
[参考](https://partner.steamgames.com/doc/features/overlay)

正常情况下，使用cocos gles3 在[SteamAPI_RestartAppIfNecessary](https://partner.steamgames.com/doc/api/steam_api#SteamAPI_RestartAppIfNecessary) 和[SteamAPI_Init](https://partner.steamgames.com/doc/api/steam_api#SteamAPI_Init) 下可以显示steam界面，cocos vulkan不可以，也没有任何报错信息

### Steps to reproduce

空项目接入steam api，采用480的app id项目正常初始化就行

**Comment by pandamicro** [comment]
Sorry we are not covering Steam yet, it will be resolved when we integrate Steam support, but this can't be considered as an individual issue currently.

For the above reason, I have to reject this issue
