### ISSUE TITLE
After a 2.x project is imported into 3.x using the import plugin, all nodes in a prefab that uses a nested prefab will no longer refer to the prefab

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#13798]
### Cocos Creator version

3.6.2

### System information

MacOS & Windows

### Issue description

After a 2.x project is imported into 3.x using the import plugin, all nodes in a prefab that uses a nested prefab will no longer refer to the prefab
2.x 的项目使用导入插件导入到 3.x 之后，使用了预制体嵌套的预制体中它的所有节点不再引用预制体

### Relevant error log output

--

### Steps to reproduce

Download the 2.x project zip below and extract it to disk, then import the 2.x project in the 3.6.2 editor using the `Import 2.x project` function.
Then look at the content node in the ScrollView prefabricated body. It was a nested prefab on 2.x, but the reference to the prefab is missing on 3.x.
下载下方的 2.x 项目压缩包并解压到磁盘中，之后在 3.6.2 的编辑器中使用 `导入 2.x 项目` 功能导入 2.x 项目。
之后查看 ScrollView 预制体中的 content 节点。它在 2.x 上时是一个嵌套预制体，但是在 3.x 上丢失了预制体的引用关系。

### Minimal reproduction project

[2.x_Prefab.zip](https://github.com/cocos/cocos-engine/files/10213757/2.x_Prefab.zip)

**Comment by zhefengzhang** [comment]
@knoxHuang

**Comment by knoxHuang** [comment]
This issue is fixed on 3.7.0
