### ISSUE TITLE
Add performance test for Node

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#13825]
As node is a basic data struct, its performance will more significant impact on engine performance. So should add more performance test for it. These performance tests can be implemented without rendering.

This issue is to collect the requirement for needed test case, then will create sub issues for all test cases. Some test cases are obvious:
- Node::invalidChildren()
- Node::setParent() as @holycanvas said it is a performance hotspot
- Node::updateWorldTransform()

**Comment by SantyWang** [comment]
I think it‘s OK, It is better to add test cases for the underlying mathematical operations as well

**Comment by minggo** [comment]
> I think it‘s OK, It is better to add test cases for the underlying mathematical operations as well

I created another issue for math library.
