### ISSUE TITLE
Support android oes texture shader writing

### ISSUE THREAD

**Issue by oahc09** [cocos/cocos-engine#13832]
### Use Case

Support android oes texture shader writing：
#extension GL_OES_EGL_image_external:require
#extension GL_OES_EGL_image_external_essl3:require
uniform samplerExternalOES mainTexture;

for example:
create a effect to render camera preview images or Android Webview, Video stream and other external textures.

### Problem Description

.

### Alternatives Considered

.

**Comment by pandamicro** [comment]
@bluesky013 can you take a look ?

**Comment by bluesky013** [comment]
> @bluesky013 can you take a look ?

ok.

**Comment by bluesky013** [comment]
OES texture effect can be supported through (https://github.com/cocos/cocos-engine/pull/14021).

However, using oes texture effect might need a new texture type like `VideoTexture`. Video or hardware camera updates to texture need to be inside the gfx render thread.

**Comment by bluesky013** [comment]
Can only be supported when the GFX thread is closed.

**Comment by star-e** [comment]
Currently not supporting oes texture.
