### ISSUE TITLE
[3.6.2] import 2.x project will rename some node name.

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13866]
### Cocos Creator version

3.6.2

### System information

window

### Issue description

compare like this.
![image](https://user-images.githubusercontent.com/8321365/208806136-d95cc0bd-25f4-48f2-b355-68c7c35cc1d1.png)

### Steps to reproduce

2.x project

[NewProject_24x.zip](https://github.com/cocos/cocos-engine/files/10274022/NewProject_24x.zip)

**Comment by knoxHuang** [comment]
<img width="1280" alt="企业微信截图_343046b3-a363-4dd9-b8d8-39e80ac2813e" src="https://user-images.githubusercontent.com/7564028/208808757-b1e0912e-c389-45f4-ba40-6bd822b9e4bd.png">

这个是 3.x 的限制，prefab 根节点的名字要跟 prefab 名保持一致

**Comment by knoxHuang** [comment]
<img width="1280" alt="企业微信截图_343046b3-a363-4dd9-b8d8-39e80ac2813e" src="https://user-images.githubusercontent.com/7564028/208808757-b1e0912e-c389-45f4-ba40-6bd822b9e4bd.png">

这个是 3.x 的限制，prefab 根节点的名字要跟 prefab 名保持一致
