### ISSUE TITLE
dragonBone动画换肤在H5上表现正常, 在原生平台闪退

### ISSUE THREAD

**Issue by stormslowly** [cocos/cocos-engine#1387]
我们自己调查了下

https://github.com/cocos-creator/engine/blob/de1c6b174b6399f502cfe6280d64b9aebf3126f7/extensions/dragonbones/ArmatureDisplay.js#L323

调用的原生解析方法返回的是一个空对象,里面`this._dragonBonesData.armatureNames` 为 `undefined`

我们游戏中调用的代码片段

```
      this._armatureDisplay.armatureName = 'qiao';
      this._armatureDisplay.buildArmature('qiao');
      this._armatureDisplay.playAnimation('qiao', 1);
```

使用的dragonData 在 https://pan.baidu.com/s/1jHJAhIu

**Comment by natural-law** [comment]
@stormslowly 请问你们使用的 Creator 版本是多少呢？

**Comment by natural-law** [comment]
我刚刚在 1.3.2 版本和开发环境中测试了一下，并没有闪退的问题。
可能你们使用的 Creator 版本较低，在新版本中问题已经解决了。

**Comment by stormslowly** [comment]
creator 版本 1.3.1 我升级看看吧

**Comment by stormslowly** [comment]
1.3.2 是好的. 谢谢
