### ISSUE TITLE
Error opening in ie mode

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13871]
### Cocos Creator version

3.6.2，3.5.2

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/143888

![image](https://user-images.githubusercontent.com/40415168/208835933-38b70811-6ba6-488e-b251-2d01534a478e.png)
![image](https://user-images.githubusercontent.com/40415168/208835976-55b97d60-ce58-47fd-8592-7556729b0ca6.png)

### Steps to reproduce

1. build web-mobile;
2. open it in Microsoft Edge in IE mode.
3. Run the command line %systemroot%\system32\f12\IEChooser.exe
Open the development tool in IE mode to see the error report
![image](https://user-images.githubusercontent.com/40415168/208836563-f6c266fe-1401-4dc1-a7b8-30c74d88a180.png)

**Comment by pandamicro** [comment]
We don't support IE nor do we plan to do it.
