### ISSUE TITLE
ios exit app crash issue

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13889]
### Cocos Creator version

3.6.2

### System information

mac

### Issue description

https://forum.cocos.org/t/topic/143275
![image](https://user-images.githubusercontent.com/40415168/209106243-215124a1-f58b-434b-a6af-56bbfb23b89b.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/40415168/209106296-f5aad645-9d07-4c29-8b1d-4810689107a3.png)
[AppDelegate.mm.zip](https://github.com/cocos/cocos-engine/files/10285752/AppDelegate.mm.zip)

**Comment by minggo** [comment]
Engine should release resources in a certain order. And iOS doesn't have a way to exit application. Currently can not fix it until engines provide game.exit().
