### ISSUE TITLE
Improve api doc

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#13888]
We should improve api doc in every version. Any one is appreciated to contribute or feedback.

**Comment by qiuguohua** [comment]
https://github.com/cocos/cocos-engine/pull/13882

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/13921

**Comment by minggo** [comment]
* https://github.com/cocos/cocos-engine/pull/13937

**Comment by pandamicro** [comment]
@shrinktofit please review all decorator doc and improve them,
for example, the range API without any specification on each parameter is meaningless
<img width="693" alt="企业微信截图_f4d0673b-00c0-471a-92ea-8b2001663b3e" src="https://user-images.githubusercontent.com/632460/213099405-2be378ed-f9d7-4635-ad8d-3fe3c1f3c41f.png">
