### ISSUE TITLE
[optimization] Some TS classes have static and non-static copy/clone methods both, do we need to deprecate the static ones?

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#13904]
<img width="489" alt="企业微信截图_f8426293-5304-4755-8b13-e4e4ee69cd0d" src="https://user-images.githubusercontent.com/493372/209515561-4adfe1cd-60fd-4562-945a-bcb55475f330.png">

**Comment by dumganhar** [comment]
AABB.transform also has this problem.

**Comment by minggo** [comment]
Yep, i think we can remove the static functions.
