### ISSUE TITLE
Is it possible to add a destroySelf API to tween?

### ISSUE THREAD

**Issue by JoneLau** [cocos/cocos-engine#13902]
### Cocos Creator version

3.6.1

### System information

Engine

### Issue description

https://forum.cocos.org/t/2-3-0-cc-action/88963/14

### Steps to reproduce

![企业微信截图_a0c6c5f5-960c-4cbe-944b-df7b73bab7d7](https://user-images.githubusercontent.com/32630749/209493045-e7bbb615-85c5-442b-a089-037be0173c8e.png)

**Comment by pandamicro** [comment]
@holycanvas @zhakesi do you have any thoughts on this

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14309
