### ISSUE TITLE
Should test the performance of js.createMap()

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#13901]
js.createMap() says it does some optimization for v8. Should test if it really improves it.

**Comment by PatriceJiang** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#null-prototype_objects, null prototype objects do not have Object methods and are pure dictionary objects. They can be faster in specific scenarios.

**Comment by PatriceJiang** [comment]
The description in the code comments is accurate.
