### ISSUE TITLE
Scene Window is so small in Mac m1/m2 laptop

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#13918]
### Use Case

<img width="1457" alt="企业微信截图_794b624d-2a3d-402f-99df-5b3a3740d2fc" src="https://user-images.githubusercontent.com/26038745/209605937-f8f5947b-b880-482c-bd23-311eee4c1df7.png">

the window size is limited by the property window, its hard to develop in laptop.

<img width="1468" alt="企业微信截图_a915b298-5153-410a-9659-187370fc3bb3" src="https://user-images.githubusercontent.com/26038745/209605984-836c7b95-cae6-4aeb-bfac-e7e731309969.png">

unity is much better in scene preview and editor play.

### Problem Description

100% in Mac M1/M2 laptop, Cocos version 3.6.2

### Alternatives Considered

<img width="1468" alt="企业微信截图_a915b298-5153-410a-9659-187370fc3bb3" src="https://user-images.githubusercontent.com/26038745/209606062-35d5d1b8-dfaf-47a8-a224-484261b13f28.png">

I would like to see this big scene window in Cocos as well in laptop

**Comment by VisualSJ** [comment]
Because we're taking the minimum width of all the panels in the same group.
In the future we will change to calculating the minimum value of the currently displayed panel.

**Comment by jareguo** [comment]
Just because 构建发布 has a minimum width limit.

**Comment by VisualSJ** [comment]
We will optimize this part of the interaction in 3.8.
Only the displayed panel will be involved in the calculation of the minimum value.
