### ISSUE TITLE
RigidBody2D component is not enabled, but still works

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#13954]
### Cocos Creator version

3.6.2

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/144291
![image](https://user-images.githubusercontent.com/40415168/209917063-fc5be408-cd0e-4c91-9a5b-d14bcfa28a5d.png)

### Steps to reproduce

demo:
[NewProject_20.zip](https://github.com/cocos/cocos-engine/files/10318096/NewProject_20.zip)

**Comment by lealzhan** [comment]
![image](https://user-images.githubusercontent.com/9999378/222687217-c90117c6-3cf7-4807-9847-e2c36e95e465.png)

**Comment by minggo** [comment]
> ![image](https://user-images.githubusercontent.com/9999378/222687217-c90117c6-3cf7-4807-9847-e2c36e95e465.png)

I used v3.8.2, the result is correct.
