### ISSUE TITLE
添加tiledmap后编辑器无法渲然地图

### ISSUE THREAD

**Issue by dum3ng** [cocos/cocos-engine#13967]
### Cocos Creator version

3.6.2

### System information

mac 13.0.1

### Issue description

添加tiledmap后，控制台报错：
![image](https://user-images.githubusercontent.com/8268760/209973131-2b46a06e-09a6-48de-9633-cec2cf6aa615.png)
然后整个编辑器的场景编辑区域就不可用了。
但是使用预览，在浏览器中地图却显示出来：
![image](https://user-images.githubusercontent.com/8268760/209973372-f7c16006-8177-4d01-a946-49eaedb111bb.png)

### Steps to reproduce

1，使用3.6.2创建项目
2，拖动一个tmx到节点树上生成tiledmap组件

**Comment by pandamicro** [comment]
@zhakesi please take a look

**Comment by zhakesi** [comment]
@dum3ng  try to increase BATCHER2D_MEM_INCREMENT size.
项目->项目设置->宏配置BATCHER2D_MEM_INCREMENT defualt 144 增大。 最大值为2303
重启编辑器。
