### ISSUE TITLE
Label not show Thai vowel when set cache mode to char

### ISSUE THREAD

**Issue by Nizaki** [cocos/cocos-engine#13964]
### Cocos Creator version

3.6.0

### System information

windows 11 , web mobile

### Issue description

Label when set cache to none or bitmap text like "กู ก่า" show as normal
but when set cache to chare only "ก กา" show
![report](https://user-images.githubusercontent.com/2827280/209930182-d5c57986-477f-40f2-a71c-499a3080ec3c.png)

### Steps to reproduce

1. Create label in canvas
2. add text like "กู ก่า"
3. set label cache to char

**Comment by pandamicro** [comment]
Sorry Characters with liaison could not work with CHAR cache mode, because they stored individually and we would never know how characters will be connected in user's Label.
In conclusion it's not possible by design, please use other CACHE mode
