### ISSUE TITLE
CocosCreator 2D particle effects are not consistent with ParticleDesigner design software effects in terms of life cycle changes

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#13962]
### Cocos Creator version

3.6.2

### System information

All Editor

### Issue description

(in CocosCreator 3.x)
![Dec-29-2022 16-58-25](https://user-images.githubusercontent.com/35944775/209928046-7b1b340b-1564-4307-b5ba-b54214e5f50c.gif)

(in ParticleDesigner)
![Dec-29-2022 17-00-33](https://user-images.githubusercontent.com/35944775/209928237-9af8fbaa-40bd-4436-b354-5df3347746bd.gif)

Although the colors are close, the styles of the two are different. The lifeVar property of the particle is 0, but it behaves differently in CocosCreator than in ParticleDesigner.
It is expected that after the particles are imported into the editor, it is not possible to customize the particle configuration to be consistent with the effect of ParticleDesigner.
虽然颜色接近，但是两者的样式不同。粒子的 lifeVar 属性是 0 ，但是在 CocosCreator 中的表现和在 ParticleDesigner 中不一样。
期望粒子导入编辑器后，无法自定义粒子配置可以与 ParticleDesigner 的效果保持一致。

---

Another exception
另外一种异常情况

CocosCreator 2D particle effects are not consistent with ParticleDesigner design software effects in terms of color cycle changes
CocosCreator 2D 粒子效果与 ParticleDesigner 设计软件效果在颜色周期变化上不一致

这是在设计软件中的粒子效果（in ParticleDesigner）
![Dec-29-2022 16-26-01](https://user-images.githubusercontent.com/35944775/209925646-13565a40-7973-4de2-8484-07af6cdcfec6.gif)

这是粒子在 CocosCreator 3.x 中的效果（in CocosCreator 3.x）
![Dec-29-2022 16-23-43](https://user-images.githubusercontent.com/35944775/209925717-3f34a038-8b49-4cd1-b6fd-19b8feebd55a.gif)

Green and purple particle units appeared in 3.x, but none of them appeared in the design software.
3.x 中出现了绿色、紫色的粒子单位，而在设计软件中均没有出现。

Expect the particles to be imported into the editor without going through custom particle configuration to display the same effect as the particle design software.
期望粒子导入编辑器后，不需要经过自定义粒子配置，就可以显示出与粒子设计软件一致的效果。

### Relevant error log output

null

### Steps to reproduce

[guang.plist.zip](https://github.com/cocos/cocos-engine/files/10318571/guang.plist.zip)
[dong1.plist.zip](https://github.com/cocos/cocos-engine/files/10318432/dong1.plist.zip)
This is the particle resource. Unzip it and import it into the editor, then load it in the CocosCreator engine to see the effect.
这是粒子资源，将它解压并导入到编辑器中，之后在 CocosCreator 引擎中加载即可查看效果。

[ParticleDesigner.zip](https://github.com/cocos/cocos-engine/files/10318441/ParticleDesigner.zip)
This is the ParticleDesigner software, which is a mac application.
这是 ParticleDesigner 软件，它是 mac 应用程序。

**Comment by zhefengzhang** [comment]
For the time being, you can turn off the color change by modifying the particle's color change range properties StartColorVar and EndColorVar to rgb(0, 0, 0), and the rgb of EndColor and StartColor to be the same.
暂时可以通过修改粒子的颜色变化范围属性 StartColorVar 和 EndColorVar 为 rgb(0, 0, 0) ，还有 EndColor 与 StartColor 的 rgb 改为一致，关闭颜色变化。

---
For now, you can get close by modifying the lifeVar of the particle to 0.2 and the endColor to new Color(17, 116, 172, 0).
暂时可以通过修改粒子的 lifeVar 为 0.2 ，endColor 为 new Color(17, 116, 172, 0) 达到接近的效果。

**Comment by SantyWang** [comment]
2D 粒子除了严重问题，其他就不动了吧
