### ISSUE TITLE
[3.6.3] Layout component hava negative size when use spacing

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#13966]
### Cocos Creator version

3.6.2

### System information

Window 10

### Issue description

layout setting map.

![img_v2_80f04d20-f241-4d8b-b891-3a15f82b12cg](https://user-images.githubusercontent.com/8321365/209942204-8bbeede4-a353-4761-b5d1-05e21180aebc.jpg)

try to fix:

![img_v2_ffd11d41-c5aa-469f-8fc8-f83dc8f914bg](https://user-images.githubusercontent.com/8321365/209942365-fefdcb05-fbd5-4e0e-a2c6-489b477ea359.jpg)
![img_v2_3f71255f-8b0f-42a2-9bb4-0b7edfa1639g](https://user-images.githubusercontent.com/8321365/209942383-7a450ef8-8d80-48fa-bb92-318f5e51df5f.jpg)
![img_v2_dfbe6b70-c050-4a73-9dad-c75e577665fg](https://user-images.githubusercontent.com/8321365/209942399-8525fa2f-8e46-4db4-acd2-22dfefe6780a.jpg)

### Steps to reproduce

see Issue description.

**Comment by LinYunMo** [comment]
3.8 版本已修复
