### ISSUE TITLE
Pipeline feature request

### ISSUE THREAD

**Issue by jk20012001** [cocos/cocos-engine#13978]
### Use Case

1. MRT for motion vector in forward pass
2. PreZ pass for depth-based shading
3. CS based cluster light culling
4. SSSS for skin rendering
5. MSAA auto resolve for refraction objects

### Problem Description

1. material support multi-passes with different phase such as "DiffuseOnly" and "SpecularOnly"
2. these passes order are: 
    no_ssss is normal objects, ssss1 and ssss2 are skin objects.
             no_ssss_base ssss1_diffuse_base  ssss2_diffuse_base
             no_ssss_additive ssss1_diffuse_additive ssss2_diffuse_additive
             ssss_blur (post process)
             ssss1_spec_base  ssss2_spec_base ssss1_spec_additive ssss2_spec_additive
3. if pass use "SceneColor" or "SceneDepth" with MSAA enabled, MSAA RT will be resolved and bind to pass

### Alternatives Considered

cluster calculations also can use CPU instead of CS.

**Comment by star-e** [comment]
Added
