### ISSUE TITLE
Investigate model compression integration

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#13999]
### Use Case

In other engine cases(https://static.ssl.jimingkeji.com.cn/popmart_show/?source=fma&sceneId=107003#/home), use Draco  can significantly  reduce the mesh/animation size. 

### Problem Description

Currently, the mesh stored with binary costs much more storage compared with Draco compressed file's size, which may could be improved with Draco compression.

### Alternatives Considered

Moreover, by using Draco loader with wasm+worker, which increases its decoding speed as well, which has been widely used in Cesium for large projects(http://ecnuzlwang.top/draco/ )

**Comment by pandamicro** [comment]
Could be a solution for https://github.com/cocos/cocos-engine/issues/13998

**Comment by pandamicro** [comment]
There is a very good comparison in this article https://juejin.cn/post/6931954784018628621
So we should include `EXT_meshopt_compression` as a candidate.
I modified the title to model compression integration, the output of this issue should be a detailed solution, executable tasks and plan.

**Comment by iwae** [comment]
> There is a very good comparison in this article https://juejin.cn/post/6931954784018628621 So we should include `EXT_meshopt_compression` as a candidate. I modified the title to model compression integration, the output of this issue should be a detailed solution, executable tasks and plan.

I would suggest to use MeshQuan with 2 reasons, 1st the ASM of meshOpt performs unstable at some platforms, 2nd some platforms don't support WASM. So with the choice of MeshQuan, it would be a more completable solution, since it simply just compresses the float data without changing the data structure, which does not require special uncompress methods/libs with it ( and also it mays save several tens of  KB)
