### ISSUE TITLE
Particle texture display exception when particle loading switch

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#14004]
### Cocos Creator version

3.6.2

### System information

All

### Issue description

Particle texture display exception when particle loading switch
粒子加载切换时粒子的纹理显示异常

### Relevant error log output

no

### Steps to reproduce

下载并解压工程压缩包，之后使用 CocosCreator 3.6.2 版本打开工程。
在 Web 浏览器运行预览，在游戏中加载切换粒子。
游戏中有两个粒子，当加载粒子 xue1_yewai 之后再加载粒子 yan，会发现粒子 yan 的粒子纹理错误。
重新加载游戏。
当加载粒子 yan 之后加载 xue1_yewai ,会发现粒子 xue1_yewai 的纹理错误。

### Minimal reproduction project

[TestParticle.zip](https://github.com/cocos/cocos-engine/files/10349169/TestParticle.zip)

**Comment by zxx43** [comment]
fixed

**Comment by SantyWang** [comment]
fixed in v3.7.2
