### ISSUE TITLE
WeChat mini-game audio memory growth

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14017]
### Cocos Creator version

3.6.2

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/144533
![image](https://user-images.githubusercontent.com/40415168/210974478-48fc2fe9-43d6-4a0b-9639-f66f92ea97ff.png)

### Steps to reproduce

demo:
[TestAudio362.zip](https://github.com/cocos/cocos-engine/files/10359121/TestAudio362.zip)

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/217793248-73d41063-ab90-455d-b40b-00655a2f80b7.png)
this func: `this._innerAudioContext.stop() `
No destruction of the _innerAudioContext instance object

**Comment by bofeng-song** [comment]
InnerAudioContext.destroy can not be trigger has fixed at this [PR](https://github.com/cocos/cocos-engine/pull/15541)
