### ISSUE TITLE
Animation Editor could not preview Baked Animation

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14029]
### Cocos Creator version

3.7.0

### System information

Mac OS

### Issue description

Animation Editor could not preview Baked Animation, which needs to toggles off Use Baked Animation 1st

### Steps to reproduce

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/26038745/211308274-8753e58d-fbc4-4bd0-97a6-30512cb5a078.png">
Animation Editor could not preview Baked Animation, which needs to toggles off Use Baked Animation 1st

**Comment by VisualSJ** [comment]
You mean when you're in the animation editing process and bake opens, you can't preview?

**Comment by zhakesi** [comment]
010913版本复测，无上述问题。

后续可改为进入编辑模式，useBaked选项置灰，变为不可以编辑状态，避免用户错误设置.
