### ISSUE TITLE
vegetation project behaves incorrectly

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14028]
### Cocos Creator version

3.6.2

### System information

mac os

### Issue description

https://github.com/cocos/cocos-example-cartoon-vegetation, the vege shader behaves incorrectly in 3.6.2

### Steps to reproduce

upgrade the project into 3.6.2,  which behaves incorrectly

**Comment by pandamicro** [comment]
It's probably due to shader upgrade, @jk20012001 please help assign the task

**Comment by jk20012001** [comment]
https://github.com/cocos/cocos-example-cartoon-vegetation/pull/10
