### ISSUE TITLE
Unable to recognize compressed gltf files

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14039]
### Cocos Creator version

3.6.2

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/144603
![image](https://user-images.githubusercontent.com/40415168/211486627-a121f6d3-8536-481a-9489-af3c2e112aba.png)

### Steps to reproduce

.

**Comment by AFeiYA** [comment]
https://forum.cocos.org/t/topic/144603/3
