### ISSUE TITLE
Can't add a point "." in the Inspector

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#14049]
### Cocos Creator version

3.7 beta

### System information

macOS

### Issue description

The "." is removed when I try to enter a float in the Inspector

See the demo:
https://gyazo.com/37b4c996e9843124d3d0ac1130129f5e

We are using French keyboard layout. Windows and macOS.

### Steps to reproduce

https://gyazo.com/37b4c996e9843124d3d0ac1130129f5e

**Comment by pandamicro** [comment]
It should have been fixed in v3.7 official version

**Comment by LoryWu** [comment]
3.7.2-030423版本验证已解决
