### ISSUE TITLE
Cocos Creator API - "Defined in" links are not working (Error 404: Page not found)

### ISSUE THREAD

**Issue by namlegdev** [cocos/cocos-engine#14044]
Hello,
Currently, the "Defined in..." links on Cocos Creator API page (https://docs.cocos.com/creator/api/en/) are not working.
The URLs seem to be wrong. Please help fix them. Many thanks. 非常感谢

Attached some screenshots, for your reference.
![cocos-creator-api-issue-1](https://user-images.githubusercontent.com/61752055/211581603-66954dfe-6454-486f-85eb-4a199eb89e68.png)
![cocos-creator-api-issue-2](https://user-images.githubusercontent.com/61752055/211581610-9f2e6da8-6575-48e8-aeb1-c4d6ba69e568.png)

**Comment by pandamicro** [comment]
@VisualSJ Who should be in charge of this ?

**Comment by nam-impact360** [comment]
The links are working correctly now. May close this issue. 🙏
Thank you. 谢谢。

**Comment by namlegdev** [comment]
The links are working correctly now.
Thank you. 谢谢。🙏
