### ISSUE TITLE
additive light pass issue for instancing objects

### ISSUE THREAD

**Issue by stanleyljl** [cocos/cocos-engine#14059]
### Cocos Creator version

3.7

### System information

all native platforms

### Issue description

addtive light problem with instancing objects

### Steps to reproduce

Add two spheres using instancing, two point lights, the additive light pass will be draw twice per light.

**Comment by troublemaker52025** [comment]
* 在 v3.7.1 上修复 https://github.com/cocos/cocos-engine/pull/14072
