### ISSUE TITLE
Field name "turn180Threshold" is not displayed consistently with others

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#14050]
Reproducible code:

```ts
import { _decorator, Component } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('IssueClass')
class IssueClass extends Component {
  @property({ min: 0, max: 180, step: 1, slide: true, unit: '°' })
  public minTurnAngle = 45.0;

  @property({ min: 0, max: 180, step: 1, slide: true, unit: '°' })
  public turn180Threshold = 135.0;
}
```

The inspector show this component as:

![image](https://user-images.githubusercontent.com/28807867/211773273-fb1ae705-02b1-4eaf-a9c0-a74a286ca9d7.png)

As you can see field `minTurnAngle` is displayed as `Min Turn Angle` while `turn180Threshold` is displayed as `Turn180Threshold`(no spaces). It should be displayed as `Turn 180 Threshold` I think.

**Comment by arsen2010** [comment]
not support auto transform 'turn180Threhold' to 'Turn 180 Threshold', because we firstly support some props like 'rotation3D' display as ‘Rotation 3D’。
please use '@property({ displayName: 'Turn 180 Threshold' })'.
