### ISSUE TITLE
jsbBridgeWrapper "Trigger event" log is showed in release buildings

### ISSUE THREAD

**Issue by wooden-uncle** [cocos/cocos-engine#14062]
### Cocos Creator version

3.6.2

### System information

Any Android Devices

### Issue description

![image](https://user-images.githubusercontent.com/117958684/212255697-87e6f88b-70c9-4db4-a430-66a2a033a1f6.png)
![45ee8e76-40c3-486c-b4b7-d070620e52f4](https://user-images.githubusercontent.com/117958684/212255940-410ab1e1-f078-4d61-a205-f1b9e05e1d53.jpeg)

### Relevant error log output

search "Trigger event", you will see logs even in release build!

### Steps to reproduce

1. the game use `jsbBridgeWrapper` 
2. call the API in release mode
3. search "Trigger event" in logcat
> not only `jsbBridgeWrapper` issues, seems like all the `SE_LOGD` will be showed in logcat!

**Comment by pandamicro** [comment]
@minggo please help assign this task
