### ISSUE TITLE
Toon material shows exceptions on Snapdragon devices and MediaTek devices

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#14063]
### Cocos Creator version

3.6.2,3.6.3

### System information

Chrome on Vivo S9，vivo built-in browser on Vivo x7Plus

### Issue description

Using builtin-toon material shows exceptions on Snapdragon devices and normal on MediaTek devices.

Snapdragon devices
![f377e5dec441b0732b2bb369c9340ed0](https://user-images.githubusercontent.com/14273437/212259473-7f986361-9988-419c-aa8e-c687c4a3199d.jpg)

MediaTek devices
![aa2c5d7b41116a5bee17cbc9c0ad2a9f](https://user-images.githubusercontent.com/14273437/212259515-c31143dd-97b1-4723-b535-63274e06774c.jpg)

Using surfaces/toon material, it appears normal on Snapdragon devices and abnormal on MediaTek devices.

Snapdragon devices
![6f07d570ec9f0c9d4fab73b22e60ca79](https://user-images.githubusercontent.com/14273437/212259396-c0770aef-4b6b-4eeb-b71e-8c18561f717c.jpg)

MediaTek devices
![eec6d9ca12c18c8ed33abf47c5550568](https://user-images.githubusercontent.com/14273437/212259364-16bbed32-8948-4396-a19f-e9765f22dae3.jpg)

Tested devices
Snapdragon devices（Vivo X7Plus、 RedMi 7A）
MediaTek devices (Vivo S9)

### Steps to reproduce

Using the test project, switch the material to builtin-toon or surfaces/toon to reproduce the problem

### Minimal reproduction project

[ChetanSharmaTextureTest.zip](https://github.com/cocos/cocos-engine/files/10408970/ChetanSharmaTextureTest.zip)

Open the project with Cocos Creator version 3.6.2 or 3.6.3

**Comment by jk20012001** [comment]
MediaTek device -- oppo renoz

**Comment by troublemaker52025** [comment]
1. 显示效果不正确的问题已经在v3.7.0 修复了
2. 如果只有一个 Main Camera 时，clear flag 要设置成 SOLID_COLOR，不然会造成插屏与场景重叠在一起然后闪烁
![图片](https://user-images.githubusercontent.com/20809296/217488159-6c4688b3-0b89-4df2-91f0-30a3f42aba4d.png)
