### ISSUE TITLE
Local Position for Animation property

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#14069]
### Use Case

Hello,
Could we add an option to save the current scene when we press the Play button?

### Problem Description

Sometimes we miss to save the scene before.

### Proposed Solution

Add an option to save the scene.

### How it works

-

### Alternatives Considered

-

**Comment by pandamicro** [comment]
@dogeFu please have a product team member consider it

**Comment by dogeFu** [comment]
Creator use your current scene to play with,even if you don't save it,thosee changes you made will take effect.

**Comment by AndyYuTian** [comment]
> ### Use Case
> Hello, Could we add an option to save the current scene when we press the Play button?
> 
> ### Problem Description
> Sometimes we miss to save the scene before.
> 
> ### Proposed Solution
> Add an option to save the scene.
> 
> ### How it works
> 
> ### Alternatives Considered
> 
> ### Additional Information
> _No response_

Were you in the animation editing mode?

**Comment by jareguo** [comment]
Further feedback is required and the issue can be reopened at any time. We also plan to support saving partial scene data in PIE mode.
