### ISSUE TITLE
Disable mesh split doesn't work for the first time default set to be on

### ISSUE THREAD

**Issue by AndyYuTian** [cocos/cocos-engine#14078]
### Cocos Creator version

3.6.1 3.6.2 3.7.0

### System information

win

### Issue description

The fbx import option "Disable Mesh Split" option is default on, but will not disable the mesh split automatially. User need to manually uncheck the box and check again to really enable this feature.

This issue is reported from chinese forum: https://forum.cocos.org/t/topic/102621/8

### Steps to reproduce

Import a fbx mesh with more than 30 bones

**Comment by AFeiYA** [comment]
https://github.com/cocos/engine-extensions/pull/214
