### ISSUE TITLE
Mouse misalignment cannot be clicked

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14099]
### Cocos Creator version

3.7.0

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/145024
![image](https://user-images.githubusercontent.com/40415168/215256082-5dd38960-929b-4ec8-8bfb-cc4ee9f41af5.png)

https://user-images.githubusercontent.com/40415168/215256105-d82b21ab-aa04-4767-9494-4dc003a26957.mp4

### Steps to reproduce

1. Right-click to open the display settings
右键打开显示设置
![image](https://user-images.githubusercontent.com/40415168/215256129-db012673-a4f2-45af-a64e-605cd22666fb.png)

2. Select advanced scaling settings
选择高级缩放设置
![image](https://user-images.githubusercontent.com/40415168/215256164-4aa17223-04b3-4f2a-9d57-cd32a12fb82a.png)

3. Set zoom ratio
设置缩放比（我电脑上设置 300 后能复现问题）
![image](https://user-images.githubusercontent.com/40415168/215256177-f0c77d91-ae40-4356-bf87-a57fe1e2e427.png)

4. Reproduced by video operation
参照视频里面的操作就能复现

**Comment by VisualSJ** [comment]
May I ask whether the editor has been opened when modifying dpi?

**Comment by OnlyKoei** [comment]
> May I ask whether the editor has been opened when modifying dpi?

It is the editor that runs only after the modification.
