### ISSUE TITLE
 new Canvas with Default layer is not suitable

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14098]
### Cocos Creator version

3.7.0

### System information

Mac

### Issue description

![企业微信截图_9135a84c-9ae7-4bf5-8213-dbab04cf194a](https://user-images.githubusercontent.com/26038745/215252100-940b23ca-9b8d-421c-a299-26eb545c674d.png)
in 3.7, when create a new Canvas in Editor, the default layer will be DEFAULT instead of UI-2D, which will be invisible to the Canvas camera, which is not suitable

### Steps to reproduce

Create a new Canvas in Editor panel

**Comment by jareguo** [comment]
![image](https://user-images.githubusercontent.com/1503156/215444523-924602d9-3e27-43d5-b654-a91777873de8.png)
What more weire is, after creating a button, the Button node is DEFAULT, Label node is UI_2D. Why are their layers different?

**Comment by arsen2010** [comment]
We fixed it on Editor V3.7.1 which would be released soon.
