### ISSUE TITLE
將騰訊開發的tutorial blackjack在Android Device運行問題

### ISSUE THREAD

**Issue by chiangandy** [cocos/cocos-engine#1409]
我有將騰訊開發的tutorial blackjack以cocos creator1.3.2與1.3.3編輯，這遊戲在html5 web與ios都可以跑，但是在Android device上面執行(我是用htc 728測試)，在主畫面點擊button...就會crash 閃退(但是在Android 模擬器又可以順利執行)，用Logcat也看不到明確的錯誤log出來，這是何解啊～！？ 有人有這情況嗎？ 由於cocos creator是我們公司2017年開發項目的主義技術依據，麻煩各位大大給點意見～

**Comment by nantas** [comment]
可能是音频解码程序和硬件不兼容导致的，可以尝试使用1.4版本（很快会发布）测试，改善了很多 android 音频兼容性的问题

**Comment by xianyinchen** [comment]
热更新测试例在2.4.4版本验证，安卓真机与模拟器均没有发生崩溃，如果后续有遇到新的问题，麻烦提供下安卓运行日志和崩溃堆栈，并新建issue告知我们。
