### ISSUE TITLE
Plist file overwritten with exceptions

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14104]
### Cocos Creator version

3.6.2，3.7.0

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/145077
![image](https://user-images.githubusercontent.com/40415168/215397041-1e74ff47-1234-44ad-9cfc-d1f582dc1842.png)

### Steps to reproduce

testRes:
[testRes.zip](https://github.com/cocos/cocos-engine/files/10532928/testRes.zip)

1. Create a new project and add plist.
创建工程，添加图集资源
![image](https://user-images.githubusercontent.com/40415168/215397363-febaaf83-43d8-4ef5-8372-4c5b70f4cbbb.png)
2. Display exception after replacing resources.
替换资源后显示异常
![image](https://user-images.githubusercontent.com/40415168/215397792-fa07f014-27b7-4849-8b06-095cebeab9f7.png)
![image](https://user-images.githubusercontent.com/40415168/215397941-6a8502d9-b6c3-423a-b525-a8a9ba555c0b.png)
3. Deleting the meta file and re-creating the sprite displays correctly
![image](https://user-images.githubusercontent.com/40415168/215398753-5daa7867-18d1-4ea3-a72b-192a0452671f.png)

ps: 3.6.2 Testing normal

**Comment by VisualSJ** [comment]
Version 3.7.1 will fix this
