### ISSUE TITLE
Chrome on mac is getting the wrong button ID on mouse_move

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#14119]
### Cocos Creator version

2.4.9,2.4.11

### System information

macOS + Chrome、macOS + Safari

### Issue description

mac computer on chrome, listening to mouse_move for mouse events, holding down the left mouse button to move, gets a buttonID of 0 (correct), holding down the right mouse button to move, gets a buttonID of 0 (incorrect)

<img width="434" alt="image" src="https://user-images.githubusercontent.com/14273437/215991395-cce0495f-c58d-41e8-af68-79cc8ab8ec3f.png">

mac computer on safari, listening to mouse_move for mouse events, holding down the left mouse button to move, gets a buttonID of 0 (correct), holding down the right mouse button to move, gets a buttonID of 2 (correct)

<img width="291" alt="image" src="https://user-images.githubusercontent.com/14273437/215991700-0b5977c8-c7cf-4031-a3e8-68dfebc4bb5c.png">

### Steps to reproduce

Refer to this demo

[NewProject_1.zip](https://github.com/cocos/cocos-engine/files/10554970/NewProject_1.zip)

Related Forum Feedback

https://discuss.cocos2d-x.org/t/an-issue-with-node-on-cc-node-eventtype-mouse-move-v2-4-9/58158/3

**Comment by yeshao2069** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/14273437/219316871-890364d9-072d-4780-b242-d098d951d732.png">

[NewProject_370.zip](https://github.com/cocos/cocos-engine/files/10754028/NewProject_370.zip)


I tested with version 3.7.0 and on Chrome + mac, the buttonID obtained is correct.

**Comment by LoryWu** [comment]
2.4.12-0906版本验证已解决
