### ISSUE TITLE
Custom texture compression broken for Auto Atlases in Cocos 3.7.0

### ISSUE THREAD

**Issue by winmain** [cocos/cocos-engine#14147]
### Cocos Creator version

3.7.0

### System information

Windows 10 Editor, Web mobile build

### Issue description

After switching from Cocos 3.6.3 to 3.7.0 compressed texture presets for Auto Atlases seems broken.

For example, we have a preset with only WEBP and ASTC 8x8 formats, but after the build there are only PNG textures are exported.
In Cocos 3.6.3 this feature worked fine, but not in Cocos 3.7.0.

![image](https://user-images.githubusercontent.com/167248/216607011-4a918f37-3d93-4044-93b2-7198030547d8.png)
![image](https://user-images.githubusercontent.com/167248/216607187-8add5512-0df2-4392-a431-274d31be30bc.png)

### Steps to reproduce

1. Create custom texture compression preset with only WEBP in it for Web platform.
2. Assign this preset to a sprite atlas (PAC file).
3. Build the project for Web mobile platform.
4. The exported texture should be in WEBP format, but there are only PNG.

### Minimal reproduction project

[testproject.zip](https://github.com/cocos/cocos-engine/files/10578936/testproject.zip)

**Comment by lagatun54** [comment]
Thank you <3 <3
