### ISSUE TITLE
Both spotlights on shadow, runtime will have one without light

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#14149]
### Cocos Creator version

3.7.0

### System information

all

### Issue description

There are 2 spotlights, a spotlight on the left, and another spotlight on the right.

The left spotlight is on shadow, the right spotlight is on shadow, and there is no light on the right side of the game.
The left spotlight is on shadow, the right spotlight is off shadow, the right side of the game is illuminated.

### Steps to reproduce

You can refer to the video in this forum post for a reproduction

https://discuss.cocos2d-x.org/t/lights-stop-to-display-when-more-than-one-have-shadows-enabled-cocos-creator-3-7-0/58176

**Comment by jk20012001** [comment]
can not reproduce
