### ISSUE TITLE
Transparency of 0 is invalid for setting coordinates

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14152]
### Cocos Creator version

3.7.0

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/145398
![image](https://user-images.githubusercontent.com/40415168/216914373-e1f4e378-f91b-4594-bc33-ca7afd640c8f.png)

### Steps to reproduce

demo:
[NewProject_22.zip](https://github.com/cocos/cocos-engine/files/10660790/NewProject_22.zip)

**Comment by SantyWang** [comment]
fixed in v3.7.2
