### ISSUE TITLE
The display changed after the dragonbone X-axis rotation

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14150]
### Cocos Creator version

3.6.0,3.6.3

### System information

window10, chrome

### Issue description

https://forum.cocos.org/t/topic/145381
![image](https://user-images.githubusercontent.com/40415168/216902935-577b42cc-1b0a-4d6c-8932-0b4cbb147973.png)
![image](https://user-images.githubusercontent.com/40415168/216903011-f0eb1fa4-0bfa-4b1b-9a7f-8caa25f2dee2.png)

### Steps to reproduce

.

**Comment by zhakesi** [comment]
* https://github.com/zhakesi/engine/commit/95e37f90bc6169056b8ef0fe76c8230d11ab15b1
will merge to next version

**Comment by pandamicro** [comment]
Please link PR instead of commit @zhakesi

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14369

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14386
