### ISSUE TITLE
Models with UIMeshRenderer cannot be displayed after removing UIMeshRenderer

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14156]
### Cocos Creator version

3.6.2，3.7.0

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/114666
![image](https://user-images.githubusercontent.com/40415168/217163579-dffde3a5-53c5-4ba0-b8f2-6fda85dd9179.png)

### Steps to reproduce

demo:
[TestUIMeshRenderer.zip](https://github.com/cocos/cocos-engine/files/10672065/TestUIMeshRenderer.zip)

**Comment by OnlyKoei** [comment]
https://user-images.githubusercontent.com/40415168/217170602-dae9bd5e-36e9-4d0f-9f2a-44dbe12162e8.mp4

**Comment by LinYunMo** [comment]
Not a good way to fix this, consider using RenderTexture to provide this functionality in the future.

If you need this capability urgently, please refer to the above PR.
