### ISSUE TITLE
[v3.7.0] Web build throws errors when engine call the updateRenderData() -> updateUvs()

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#14153]
### Cocos Creator version

3.7.0

### System information

Macos Bigsur, IMac 2019, Intel Core i5, AMD RX560

### Issue description

- Cocos version: 3.7.0
- Build platform: Web
- RunningMachine: Macos Bigsur

While running the built on the web platform, the game throws massive error logs (image attached)
THis may cause the memory leak. My project was on v3.4.0 without any issue or memory leak, but after updated to v3.7.0 The memory increase rapidly, (250mb extras for 25 mins of play the game on iOS native build)

### Relevant error log output

![image](https://user-images.githubusercontent.com/18746281/216936616-e0dbf305-9d61-44a7-abfc-2dc125613d4e.png)

### Steps to reproduce

Can't preproduce.

**Comment by thinhlv** [comment]
This issue also accured on Android platform with the same callstack error.

**Comment by pandamicro** [comment]
Can you show the very first errors ?
The reason is probably due to RenderData lost, but the given information can't show any root reason of thiss

**Comment by pandamicro** [comment]
Please take a look at this doc, it might be related to `BATCHER2D_MEM_INCREMENT` setting
https://docs.cocos.com/creator/manual/en/ui-system/components/engine/ui-batch.html#after-v341

**Comment by thinhlv** [comment]
I've found that, my Build machine never cleanup the cache library folder, this may caused the issue.
After I cleanup all project then rebuild the game again, the issue is gone!
Thanks!
