### ISSUE TITLE
[3.7] bytedance-mini-game on ipad not full screen

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14163]
### Cocos Creator version

3.6.2，3.7.0，3.5.2

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/145405
![image](https://user-images.githubusercontent.com/40415168/217191480-fd5974df-9c36-4dcc-b31f-f6f816b60e2c.png)
![企业微信截图_16757390538639](https://user-images.githubusercontent.com/40415168/217197574-def10d5a-ec73-433e-ae60-2afe675fcd4d.png)

![image](https://user-images.githubusercontent.com/40415168/217196802-7d2de199-5fb2-4cd1-91b7-bab9c9ba75dc.png)
If you change code：
```
windowWidth -> screenWidth，
windowHeight -> screenHeight, 
```
the display will be normal.

### Steps to reproduce

demo:
[NewProject_22.zip](https://github.com/cocos/cocos-engine/files/10673112/NewProject_22.zip)

**Comment by ashleylin97** [comment]
Test passed.
