### ISSUE TITLE
object gizmo issue while modifying the editor camera fov

### ISSUE THREAD

**Issue by jk20012001** [cocos/cocos-engine#14166]
### Cocos Creator version

3.7.0

### System information

Windows 11

### Issue description

If I modify the editor camera fov value, the 3-axies of gizmo become hard to select while rotating an object, and the gizmo size is changing randomly.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/15099632/217211834-28bca6b4-291d-4818-996f-c6380d4da36c.png)
![image](https://user-images.githubusercontent.com/15099632/217212028-653dc676-bf3e-41b7-9ced-ddb5bd95c139.png)
![企业微信截图_16757544917547](https://user-images.githubusercontent.com/15099632/217210266-767f1c9c-f68b-4cd6-ab23-a4254296f0ee.png)
while the mouse pointing here, the red-axis being selected, there is an offset between point pos and red-axis

**Comment by dogeFu** [comment]
fixed
