### ISSUE TITLE
[V3.7.0] iOS app  with spine crahsed with callstack: cc::middleware::MiddlewareManager::render(float)

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#14172]
### Cocos Creator version

3.7.0

### System information

Iphone X, iOS 15.4

### Issue description

iOS crashed by spine animation after a while play the game (The nodes that contains the spine animation has been pooling using NodePool)

### Relevant error log output

11:57:31 [DEBUG]: Init Stacktrace:  - [0]anonymous@src/cocos-js/cc.js:1
 - [1]tick@src/cocos-js/cc.js:1
 - [2]_updateCallback@src/cocos-js/cc.js:1
 - [3]anonymous@src/cocos-js/cc.js:1
 - [4]tick@jsb-adapter/web-adapter.js:610
11:57:31 [WARN]: Triple buffer enabled for infrequently-updated buffer, consider using MemoryUsageBit::DEVICE instead
11:57:31 [DEBUG]: Init Stacktrace:  - [0]anonymous@src/cocos-js/cc.js:1
 - [1]tick@src/cocos-js/cc.js:1
 - [2]_updateCallback@src/cocos-js/cc.js:1
 - [3]anonymous@src/cocos-js/cc.js:1
 - [4]tick@jsb-adapter/web-adapter.js:610
11:57:31 [DEBUG]: D/ GC end ..., (js->native map) size: 37714
<img width="1757" alt="Screen Shot 2023-02-08 at 11 59 44" src="https://user-images.githubusercontent.com/18746281/217439151-b00574c8-7833-42aa-81d5-32ca25816395.png">

### Steps to reproduce

Build the game in iOS, the game contains so many spine animations (appear and disappear using a NodePool). After a random time (may take up to 2 hours) then this issue will be accured.

**Comment by zhakesi** [comment]
@thinhlv  Could you provide a demo project that reproduces the issue?

**Comment by thinhlv** [comment]
The issue has the higher chance to be accured if we change the scene after a while.

@zhakesi , there is more information of the spine object that cause the issue.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/18746281/225244205-766062d3-6755-4e53-a679-a66c4b1d7834.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/18746281/225244726-82e1df2a-0e10-4392-979f-3a63b2ffe68e.png">

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/18746281/225245165-e85eee76-77c7-42eb-bd64-83f0e4ad1c6c.png">

**Comment by Canvasfull** [comment]
Does 3.8.1 still have this problem? Can you provide a test project?

**Comment by minggo** [comment]
Close it as it is not active now.
