### ISSUE TITLE
[V3.7.1] iOS jsb.device.getDeviceOrientation value error while screen orientation change

### ISSUE THREAD

**Issue by bravetwo** [cocos/cocos-engine#14197]
### Cocos Creator version

3.7.1

### System information

macOS Monterey 12.6.1, Xcode 13.0 build on iPhone12 Pro

### Issue description

- build set Screen orientation all.
- get jsb.device.getDeviceOrientation in view canvas-resize callback.
- the value is correct while first enter to the scene.
- then get wrong value while rotate phone and emit canvas-resize event.
- the value do not change in some frames and then change, getting the value is not conform to device orientation.

### Steps to reproduce

- simple scene use component code:
``` ts
start() {
    if (sys.platform === sys.Platform.IOS) {
        view.on("canvas-resize", () => {
            console.log("on resize jsb.device.getDeviceOrientation::::", jsb.device.getDeviceOrientation());
        });
        console.log("start jsb.device.getDeviceOrientation::::", jsb.device.getDeviceOrientation());
    }
}
```
- build set Screen orientation all.
-  run and rotate phone.

**Comment by novain1102** [comment]
Use Cocos Creator 3.7.0/3.7.1, tested on iphone12(16.2), run nomral as expected:
![image](https://user-images.githubusercontent.com/18634782/218033161-e3a252d5-1f78-46b9-bef3-e7a0233d9522.png)

**Comment by bravetwo** [comment]
Use Creator 3.7.0
    - Xcode 13.0 build on iPhone12 Pro(15.5) and iPad Air 3(13.6)
    - Xcode 14.2 build on iPhone12 Pro(15.5) and iPad Air 3(13.6)
still get the same error, seems like the value is conform to the last time changed device orientation, always lag

**Comment by novain1102** [comment]
Test on iPhone11(15.7) and upgrade to iOS 16.x and test again.
iOS 15.x result is wrong but run well in iOS 16.x for same device

So I assume that `[[UIApplication sharedApplication] statusBarOrientation]` return wrong value before iOS16
![image](https://user-images.githubusercontent.com/18634782/218687276-e48ef0e2-8962-4967-aa90-7557c8b6133e.png)
