### ISSUE TITLE
[v2.4.4] wechatgame onDeviceOrientationChange 

### ISSUE THREAD

**Issue by DreamZhou** [cocos/cocos-engine#14198]
### Cocos Creator version

2.4.4

### System information

WeChat

### Issue description

FindN 7.1 折叠屏 可以横屏竖屏转向，但是引擎没有做处理，导致转屏后 触摸点位置不对。

### Steps to reproduce

构建微信小游戏，使用 FindN 7.1 折叠屏 打开。

**Comment by pandamicro** [comment]
Please refer to the comment in the source code, there is a bug reported to wechat, I'm not aware of the current status, but we won't modify the behavior unless something has changed in the platform side

https://github.com/cocos/cocos-engine/blob/develop/pal/minigame/wechat.ts#L90
