### ISSUE TITLE
A bug in vulkan backend

### ISSUE THREAD

**Issue by Xrysnow** [cocos/cocos-engine#14192]
### Cocos Creator version

3.7.0

### System information

Vulkan

### Issue description

There is a bug in `CCVKGPUStagingBufferPool`:
https://github.com/cocos/cocos-engine/blob/4a739b00272d684bd2dda46b1aa4f7a6309ec7e4/native/cocos/renderer/gfx-vulkan/VKGPUObjects.h#L790-L800
In line 796, `CHUNK_SIZE` and `offset` are unsigned but `offset` can be bigger than `CHUNK_SIZE` due to `roundUp` sometime. This will give invalid offset and cause memory error.

### Steps to reproduce

-

**Comment by pandamicro** [comment]
@bluesky013 please check
