### ISSUE TITLE
[3.x] The first scene fails to release automatically for the first time

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14229]
### Cocos Creator version

2.4.10，3.6.3，3.7.0

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/145757
![image](https://user-images.githubusercontent.com/40415168/218697892-7aef7363-6eb7-49b3-b7ff-53867dd9ab53.png)

![image](https://user-images.githubusercontent.com/40415168/218697701-a134012f-6ab5-4241-a92b-e9f3341c8d69.png)
The first time the project was opened, the data of the first scene was not recorded correctly, and then it was switched again and again before it was recorded properly.
第一次打开项目时，第一个场景的数据没有被正确记录，然后又反复切换场景后才被正确记录。
![image](https://user-images.githubusercontent.com/40415168/218700128-b0ab9b78-afc7-4af5-b375-13a5428112b5.png)

### Steps to reproduce

demo:
[NewProject_12.zip](https://github.com/cocos/cocos-engine/files/10731088/NewProject_12.zip)

**Comment by OnlyKoei** [comment]
It works fine after the build.
构建后运行正常

**Comment by zhefengzhang** [comment]
@holycanvas

**Comment by SantyWang** [comment]
This problem is because when previewing in the editor, the scene uuid given is `currentScene`, and this uuid is incorrect.

**Comment by SantyWang** [comment]
@VisualSJ The preview scene needs a persistent uuid.

**Comment by knoxHuang** [comment]
3.8.0 的版本已经修复
