### ISSUE TITLE
be able to merge cconb in building stage

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#14271]

**Comment by nitrobin** [comment]
This functionality would significantly speed up the bundle loading process for projects with a large number of animations.  For example, in our case, bundle loading takes around 4 seconds and there are over 100 requests to load each animation clip. 
What are your plans for implementing this feature and are there any workarounds currently available?

**Comment by shrinktofit** [comment]
We plan to optimize this in V3.9 if everything goes well.

**Comment by shrinktofit** [comment]
Replaced by https://github.com/cocos/cocos-engine/issues/15676 .
