### ISSUE TITLE
Wrong alignment of trimmed sprites loaded from sprite sheet

### ISSUE THREAD

**Issue by CodeAndWeb** [cocos/cocos-engine#14292]
### Cocos Creator version

3.7.0

### System information

macOS 13

### Issue description

On a sprite sheet transparent borders of sprites can be trimmed to reduce sprite sheet size:

<img width="483" alt="untrimmed" src="https://user-images.githubusercontent.com/716009/219391418-3dfbb7a5-08f6-48e4-9c6a-2ee91d08deb9.png">
<img width="432" alt="trimmed" src="https://user-images.githubusercontent.com/716009/219391412-9d7a034b-6d59-4777-995b-719b17a72255.png">

To restore the original sprite, the plist sprite sheet data file contains the sprite offset and the original sprite size:
```
            <key>anim-1.png</key>
            <dict>
                <key>aliases</key>
                <array/>
                <key>spriteOffset</key>
                <string>{-28,0}</string>
                <key>spriteSize</key>
                <string>{34,34}</string>
                <key>spriteSourceSize</key>
                <string>{100,50}</string>
```

The spriteOffset is read by CocosCreator, but not applied to the sprite. spriteSourceSize isn't read/displayed, CocosCreator displays the trimmed sprite outlines instead.

<img width="214" alt="sprite-offset" src="https://user-images.githubusercontent.com/716009/219394125-bb64b8ce-edc4-4784-ac72-0c9eeccc44e3.png">

This makes it almost impossible to align animation frames properly.

With cocos2d-x this works fine.

### Steps to reproduce

Create an animation with the untrimmed sprites from the attached sprite sheet in CocosCreator: the red sprite moves from left to right. This is the expected behaviour.
[anim-untrimmed.zip](https://github.com/cocos/cocos-engine/files/10757060/anim-untrimmed.zip)

Create an animation with sprite sheet with trimmed sprites: the sprite doesn't move at all:
[anim-trimmed.zip](https://github.com/cocos/cocos-engine/files/10757059/anim-trimmed.zip)

**Comment by CodeAndWeb** [comment]
Problem still persists in version 3.7.1

**Comment by LinYunMo** [comment]
Thanks for your feedback.
If you want create an animation with sprite sheet with trimmed sprites，please set the Sprite component's `Trim` property to `false`, like this:

You can also refer to the instructions in our documentation，[Sprite Animation with offset](https://docs.cocos.com/creator/manual/en/ui-system/components/engine/trim.html#sprite-animation-with-offset)


![企业微信截图_16786890313766](https://user-images.githubusercontent.com/42071583/224624416-be3e4266-bf13-420d-acf5-cfca807aff60.png)
