### ISSUE TITLE
xiaomi-quick-game on some phones click offset

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14329]
### Cocos Creator version

3.5.2，3.6.3，3.7.1

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/146035

https://user-images.githubusercontent.com/40415168/220275594-556788a4-6cd8-4a03-8f24-db74e85538cd.mov

This happens with some Xiaomi phones。
不是所有小米手机都会，只有部分机型会；
![image](https://user-images.githubusercontent.com/40415168/220276374-c7852f42-20f6-4f00-b858-000139fe14eb.png)

### Steps to reproduce

demo:
[CocosTest.zip](https://github.com/cocos/cocos-engine/files/10790712/CocosTest.zip)

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/221540022-88cad6a6-879b-43fb-b66a-73219e14db47.png)

**Comment by bofeng-song** [comment]
On Xiaomi 11, the value of pixelRatio returned by getSystemInfoSync is 3.66; the scaledDensity obtained by the Java end is 3.5. The values obtained on both sides are inconsistent, and 3.5 should be used as the standard. It has been reported to Xiaomi.

**Comment by dadidzf** [comment]
有没有什么办法，可以临时打个补丁，最方便地修复呀，最好是不用定制引擎的那种。求教！

**Comment by bofeng-song** [comment]
> 有没有什么办法，可以临时打个补丁，最方便地修复呀，最好是不用定制引擎的那种。求教！

小米平台问题，引擎无法处理。你可以看下getSystemInfo或是否有getDeviceInfo的接口获取手机型号信息，根据这个判断。或者问下小米如何处理

**Comment by dadidzf** [comment]
为什么2.4.x没有这个问题？2.4.x没有使用小米的getSystemInfo接口吗？我们多款2.4.x游戏，并没有这个问题。仅仅3.x有问题。

**Comment by dadidzf** [comment]
![image](https://github.com/cocos/cocos-engine/assets/4944726/4d003717-6f79-48c3-8166-948a05fc40e2)
```

 let oldFunc = input['_touchInput'].__proto__._getLocation;
        input['_touchInput'].__proto__._getLocation = function (touch: Touch, windowSize: Size, dpr: number) {
            console.log("XiaoMiPlat _getLocation -------------", dpr, windowSize.width, windowSize.height);
            dpr = windowSize.width / window.screen.availWidth;
            console.log("XiaoMiPlat real dpr ", dpr);
            return oldFunc.bind(this)(touch, windowSize, dpr);
        }


```

这种方式实测可以暂时用来规避这个问题，而且不用改引擎源代码。具体原因，应该是小米返回的pixelRatio太小了（小于2），红米9实测返回1.83，然后看源代码里面web/screen-adapter的devicePixelRatio小于2时会返回2。更具体的细节希望引擎大佬跟踪，这不一定是小米的问题哦。。。

**Comment by dadidzf** [comment]
大佬麻烦看下我的回复，问题不一定出在小米身上，而有可能是那个ratio < 2时，强制把ratio设置为2的问题。具体引擎源码我不太懂。

**Comment by bofeng-song** [comment]
> 大佬麻烦看下我的回复，问题不一定出在小米身上，而有可能是那个ratio < 2时，强制把ratio设置为2的问题。具体引擎源码我不太懂。


你看的文件错了，需要看screeen-adapter/minigame下的；另外2.x和3.x对touch的处理逻辑是不一样的，3.x是依赖dpr
