### ISSUE TITLE
Openharmony build plugin upgraded to 3.8

### ISSUE THREAD

**Issue by qiuguohua** [cocos/cocos-engine#14325]
Openharmony build plugin upgraded to 3.8

**Comment by minggo** [comment]
Is it fixed? Can close it?

**Comment by qiuguohua** [comment]
After merging the latest branch, there is a problem and it can't be closed yet.
https://github.com/cocos/3d-tasks/issues/16036

**Comment by qiuguohua** [comment]
https://github.com/cocos/creator-runtime-extensions/pull/362

**Comment by qiuguohua** [comment]
https://github.com/cocos/creator-runtime-extensions/pull/355

**Comment by minggo** [comment]
> After merging the latest branch, there is a problem and it can't be closed yet. [cocos/3d-tasks#16036](https://github.com/cocos/3d-tasks/issues/16036)

既然有对应的 issue 跟进了，那么这个 issue 就可以关闭了。
