### ISSUE TITLE
When debugging with the emulator, modifying the design resolution cannot affect the game's window size

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#14326]
### Cocos Creator version

3.7.1

### System information

windows&mac

### Issue description

使用模拟器调试时，修改设计分辨率不能影响游戏的窗口大小
![图片](https://user-images.githubusercontent.com/35944775/220260063-86f6f0c1-9f96-4b11-b55c-02172589da44.png)

![图片](https://user-images.githubusercontent.com/35944775/220260118-de272387-4da9-4654-9aae-1fea90975214.png)

https://forum.cocos.org/t/topic/145214

### Steps to reproduce

-

**Comment by OnlyKoei** [comment]
https://github.com/cocos/cocos-engine/pull/14908
