### ISSUE TITLE
CocosCreator3.x希望能够支持tiled map瓦片地图的staggered等角交错模式

### ISSUE THREAD

**Issue by Joustany** [cocos/cocos-engine#14356]
### Use Case

我正在开发一款slg类型的2.5d游戏，需要用到tiled map瓦片地图的staggered等角交错模式

### Problem Description

导入tmx格式的tiledmap时，tiledmap组件渲染出错，tiled全部错位。
控制台提示：
[Scene] cocos2d: TMXFomat: Unsupported orientation: staggered

### Alternatives Considered

如果能通过修改CocoCreator的cocos2d引擎源代码快速实现也可以

**Comment by zhakesi** [comment]
等角交错 和 六角交错边长设置为0等效.
地图可以改用 六角交错边长设置为0
