### ISSUE TITLE
[3.7.1]spine runs in the editor with an error

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14399]
### Cocos Creator version

3.7.1

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/146367
![企业微信截图_16775655701323](https://user-images.githubusercontent.com/40415168/221772832-95caed48-7e90-415b-bab5-de820ff51fc6.png)

spine:
https://user-images.githubusercontent.com/40415168/221773684-e583371d-1782-4fc9-82b0-bde51690c0ec.mp4

dragonBones:
https://user-images.githubusercontent.com/40415168/221773896-e6c2aa0d-09e5-4484-a730-c1550297c1f9.mp4

### Steps to reproduce

DEMO: 
[NewProject_19.zip](https://github.com/cocos/cocos-engine/files/10847252/NewProject_19.zip)

**Comment by OnlyKoei** [comment]
https://github.com/cocos/cocos-engine/pull/14402

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14402
