### ISSUE TITLE
3.7.1 Animation.addClip doesn't work correctly

### ISSUE THREAD

**Issue by swiftcafex** [cocos/cocos-engine#14404]
### Cocos Creator version

3.7.1

### System information

macOS

### Issue description

代码文件： https://github.com/cocos/cocos-engine/blob/afd22296b417d2b34791c855c066aa4d49059395/cocos/animation/animation-component.ts

Cocos Creator 3.7.1 

Animation.addClip 方法内部逻辑错误。

```
public addClip (clip: AnimationClip, name?: string): AnimationState {
  if (js.array.contains(this._clips, clip)) {
    this._clips.push(clip);
  }
  return this.createState(clip, name);
}
```

如果没理解错， 这个 `if (js.array.contains(this._clips, clip)) {` 判断逻辑应该是反了， 新的 clip 永远不会被添加进来。 引擎团队关注下吧。

### Steps to reproduce

调用 Animation.addClip

**Comment by shrinktofit** [comment]
Thanks for your feedback. Should have been fixed in https://github.com/cocos/cocos-engine/pull/14440
