### ISSUE TITLE
Portrait option do not effect in Android Build

### ISSUE THREAD

**Issue by bravetwo** [cocos/cocos-engine#14414]
### Cocos Creator version

3.7.1

### System information

Windows 10 Editor

### Issue description

Get android:screenOrientation="sensorLandscape" in AndroidManifest if set all options in Screen orientation in Android Build panel

### Steps to reproduce

- create an empty creator project
- Set all options in Screen orientation in Android Build panel, than build

**Comment by bravetwo** [comment]
v3.7.2, Get android:screenOrientation="landscape" in AndroidManifest if set Portrait and Landscape Right in Screen orientation in Android Build panel

**Comment by bravetwo** [comment]
if i change the screenOrientation to fullSensor in as project get crash while rotate device from portrait to landscape

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/15064
