### ISSUE TITLE
nodejs version affects vivo minigames cannot be built

### ISSUE THREAD

**Issue by AndroidSix** [cocos/cocos-engine#14435]
### Cocos Creator version

3.x all versions

### System information

MacOS

### Issue description

vivo minigames cannot be built when the local nodejs LTS version is 18 or greater

### Steps to reproduce

Create project to build vivo minigame

**Comment by PPpro** [comment]
sorry, this is not the issue we can handle in engine team.

we've report this issue to the platform building team, hope this issue can be fixed.

I'll close this issue for now. 
Thanks for your feadback.

**Comment by heyanfei** [comment]
Vivo replied ：that it is not recommended to upgrade the nodejs version. They will arrange time to solve it;
