### ISSUE TITLE
Compatibility issues with shadowbias on vivo IQOO Z1

### ISSUE THREAD

**Issue by troublemaker52025** [cocos/cocos-engine#14434]
![图片](https://user-images.githubusercontent.com/20809296/222315570-5c8787a9-d021-4a05-a163-1ed60845c9a6.png)

**Comment by jk20012001** [comment]
别的 vivo oppo 都不能重现，上海没有 z1，先延期

**Comment by star-e** [comment]
3.8.4暂无发现问题，先关闭了
