### ISSUE TITLE
safari webgl2 skeleton mesh renderer not display

### ISSUE THREAD

**Issue by 2youyou2** [cocos/cocos-engine#14453]
### Cocos Creator version

3.7.2

### System information

iOS safari webgl2

### Issue description

safari webgl2 skeleton mesh renderer not display

### Steps to reproduce

[test-animation.zip](https://github.com/cocos/cocos-engine/files/10877669/test-animation.zip)

open demo project in 3.7.2, build web mobile version, run on safari webgl2 version

**Comment by 2youyou2** [comment]
![企业微信截图_16777439864362](https://user-images.githubusercontent.com/1862402/222618567-fd85f526-d1a5-43fe-b59e-c8b57477244a.png)
![54d785d4626ff728267ecc81f596e0d8](https://user-images.githubusercontent.com/1862402/222618581-3f79089d-d6b2-4c0a-8d6b-d73c07d93f57.jpg)

**Comment by zhakesi** [comment]
* https://github.com/cocos/cocos-engine/pull/14508
