### ISSUE TITLE
Reflection use RGB and dont support transparent mat

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14478]
### Cocos Creator version

3.7

### System information

mac

### Issue description

when use transparent mat ,the result will turn into white, without warning or tips

![image](https://user-images.githubusercontent.com/26038745/222937339-d2dcddfa-24df-4a1a-b3f7-a24e43adaf7e.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/26038745/222937346-f39a2a04-dcc2-4244-b8ac-d72b0026561d.png)
![image](https://user-images.githubusercontent.com/26038745/222937350-bfce7fca-8b7d-485b-9a6e-b498bd20af6d.png)

**Comment by xubing0906** [comment]
The baking result is in RGBE format, and the A channel is occupied, so it cannot support baking transparent objects, and the transparent objects will be filtered out in next versions.

**Comment by xubing0906** [comment]
merge to 3.8
