### ISSUE TITLE
Reflection Result will lose when click mesh in Editor Prefab window

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14477]
### Cocos Creator version

3.7 3.71

### System information

mac

### Issue description

after baking, when clicked the mesh in prefab window, the baking result will lose, it turns into white

![image](https://user-images.githubusercontent.com/26038745/222937234-9e46af27-f5ac-4261-b57e-1baa24527f9e.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/26038745/222937254-5713af00-8eb7-4a99-9834-0b0214c99008.png)

click the mesh, it turns into white

**Comment by jareguo** [comment]
现在确实不太好看，反射天空盒的话有个问题是之前是存在场景上的，prefab 没有这个信息。
可以考虑反射默认的天空盒。

**Comment by AndyYuTian** [comment]
When preview prefabs, it is better to display a default skybox so user can view reflective materials.

**Comment by xubing0906** [comment]
反射使用默认的天空盒，PR已经合并
