### ISSUE TITLE
Reflection Probe fails to capture the node with UI_3D layer

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14479]
### Cocos Creator version

3.7

### System information

win

### Issue description

![image](https://user-images.githubusercontent.com/26038745/222937425-eec2df9e-cc38-403b-a0de-8fca02865274.png)
when node use UI_3D layer, it fails to capture,  but the flag does have UI_3D****

### Steps to reproduce

use UI_3D layer to the mesh , and add UI_3D to probe vis and bake

**Comment by xubing0906** [comment]
In the Visibility option, you can select UI_3D, but the objects in UI_3D cannot use the baking results of the reflection probe. We fixed the exclusion of the following layers UI_2D UI_3D GIZMOS EDITOR SCENE_GIZMO PROFILER IGNORE_RAYCAST
![image](https://user-images.githubusercontent.com/49358166/223030279-39eab9d2-0df5-4ad4-be83-9992ac6ed376.png)
