### ISSUE TITLE
Reflection baking failed when use mediump in standard effect

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14481]
### Cocos Creator version

3.7 

### System information

mac

### Issue description

when use mediump in FS and VS, the baking will fail

![image](https://user-images.githubusercontent.com/26038745/222937611-7984e66d-32f2-4cf3-8b71-f1800753baf2.png)

### Steps to reproduce

As des, use mediump in FS and VS

**Comment by xubing0906** [comment]
Using mediump float may cause an Effect compilation error and is not recommended
