### ISSUE TITLE
[Proposal] Inspector: display some fields as "controlled"

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#14482]
# Motivation

In our engine, editing some fields manually is meaningless due to these fields are "controlled", that's, these fields would be overridden in runtime by something else.

Let's look at an example. Drag a _Progress Bar_ component into scene. Try to modify the content width property(`UITransform.ContentSize.w`) of the auto-generated node `<the-progress-bar>/Bar`. You can see the modifying succeed. However, when you're attempting to change the default progress property (`<the-progress-bar>.ProgressBar.progress`) of the progress bar. The content width you previously modified will be reset. Actually, you can only set the width property of that node through `<the-progress-bar>.ProgressBar.totalLength`. Let's say in such a case, the `UITransform.ContentSize` is a **controlled** field.

This is not a rare case but a common phenomenon. For such mechanism, manually editing these controlled fields is meaningless. So, I'd like to propose that inspector can give these fields a "controlled" mark. Here I'm goanna propose some ideas:

1. Display these fields as semi-read-only: render them as grey to warn they're controlled: editing is not required. At the same time, give it an opportunity to violate this behaviour.

2. Give these fields a special icon.

3. Combine 1 & 2.

**Comment by SantyWang** [comment]
It's good, can we dynamically toggle the readonly state of a property on the inspector now? @VisualSJ

**Comment by jareguo** [comment]
这个需求相比现在的锁定，它们其实目的是一样的，通过 flag 精准标记传递给场景 gizmo 和 inspector 的节点设置。
![image](https://github.com/cocos/cocos-engine/assets/1503156/452182c4-68f5-488b-956e-9217b32cb926)

或许我们可以对这个机制进行扩展，使之更加语义化、通用化
不过鉴于目前的用户反馈情况，以及竞品的实现情况来看，我没看到这件事情的重要性和紧迫性，建议延后。

---
EN:
This demand compared to the current lockdown, they actually serve the same purpose. The node settings passed to the scene gizmo and inspector are accurately labeled with flags.
![image](https://github.com/cocos/cocos-engine/assets/1503156/452182c4-68f5-488b-956e-9217b32cb926)

Perhaps we can extend this mechanism to be more semantic and generalized
However, given the current user feedback, and the implementations of competing products, I don't see the importance or urgency of this, and would recommend delaying it.
