### ISSUE TITLE
Reflection Probe baking speed is super slow in some cases

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#14480]
### Use Case

In a big scene, the baking speed will be super slow, please give a Preview function 

### Problem Description

![image](https://user-images.githubusercontent.com/26038745/222937502-fb7af599-a4c1-4ecf-90f3-885b556f1e20.png)

It may take years to bake

### Alternatives Considered

Provide preview bake

**Comment by xubing0906** [comment]
we have added a fast bake option in version 3.7.2
![image](https://user-images.githubusercontent.com/49358166/223027705-92aa30ef-ebc9-4f51-b9f9-04d4235015fb.png)

https://github.com/cocos/cocos-engine/pull/14449
