### ISSUE TITLE
A property of type Asset cannot mount any type of resource

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#14484]
### Cocos Creator version

3.7.1

### System information

Mac

### Issue description

Such as the title.

### Steps to reproduce

in class:

```ts
    @property(Asset)
    asset: Asset | null = null;
```

can't mount any sub type asset.

**Comment by arsen2010** [comment]
Tested in v3.8.0， the code works in the editor inspector, can mount any type of assets.
