### ISSUE TITLE
Effect parser 添加在预编译指令种使用 ‘||’ 语句的支持。

### ISSUE THREAD

**Issue by yiwenxue** [cocos/cocos-engine#14529]
### Use Case

```glsl
#if CC_USE_REFLECTION_PROBE || CC_RECEIVE_SHADOW
    // ...
#endif
```

### Problem Description

当前版本的 effect parser 在收集 shader 的宏依赖信息时会忽略掉 ‘||’ 之后的内容，
![WXWorkCapture_16782645729333](https://user-images.githubusercontent.com/24495793/223966781-807ecec1-810e-49bd-a1dd-77d0696fc790.png)
这导致在写 shader 的时候无法使用如下写法：
```glsl
#if CC_USE_REFLECTION_PROBE || CC_RECEIVE_SHADOW
    // ...
#endif
```
这导致 shader 写起来非常麻烦，很容易出错。需要新增此种写法的支持。

### Proposed Solution

修改 effect parser 的 extractDefines 实现。

### Alternatives Considered

None

**Comment by jk20012001** [comment]
https://github.com/cocos/engine-extensions/pull/254
