### ISSUE TITLE
Renaming the ccclass, the data in the prefab becomes invalid and cannot be salvaged.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#14547]
### Cocos Creator version

3.7.1

### System information

Mac

### Issue description

```ts
@ccclass("A")
export class A {
    // ...
}

@ccclass
export class B extends Component {
    @property(A)
    a: A = new A();
}
```

Mount the B component on the node, and store the data of a in the prefab like this:
```json
{
    "__type__": "A",
    "_property": "",
}
```
If I rename A,the __type__ in the prefab will not change accordingly,then open this prefab in the editor, the console will print that A cannot be found, but there will be no error prompts in the inspector (if the component script is missing, there will be an error prompt that the component script is missing) , and nothing works except manually modifying the __type__ or removing the a attribute and adding it back.

### Steps to reproduce

.

**Comment by jareguo** [comment]
Automatic refresh doesn't seem to be a technical solution.
For a manual refresh, the editor should show a reset button, which clears a. After reset, there should be a create button, which creates a new a object with the new type.

**Comment by smallmain** [comment]
Associated: https://github.com/cocos/cocos-engine/issues/14550#issuecomment-1674265880

**Comment by smallmain** [comment]
> Automatic refresh doesn't seem to be a technical solution. For a manual refresh, the editor should show a reset button, which clears a. After reset, there should be a create button, which creates a new a object with the new type.

It is hoped that the engine should display the repair button first, try to repair as much as possible (corresponding attributes one by one), and then pop up a failure dialog box after failure, asking the user if they need to reset, instead of directly resetting and causing the user's data to disappear directly.

**Comment by smallmain** [comment]
Including errors such as component loss, you can also give a drag area to allow users to replace new components and do their best to restore data instead of just deleting.

**Comment by arsen2010** [comment]
@smallmain Hello, when i check and test this bug in v3.8.0，find it is normal.  Please help me to varify it again.
![image](https://github.com/cocos/cocos-engine/assets/13517177/245f5fe7-2f87-4865-bc2d-42a2f93f5398)

![image](https://github.com/cocos/cocos-engine/assets/13517177/3c5a0c9c-e6ea-4d9f-a099-2b083afecab7)

**Comment by smallmain** [comment]
@arsen2010 Please check the data in the prefab, \_\_type__ will not change due to the type change of @property, no error is reported just because the old type's class still exists.
