### ISSUE TITLE
Normal ccclass scripts cannot find references

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#14548]
### Cocos Creator version

3.7.1

### System information

Mac

### Issue description

in script:
```ts
@ccclass("A")
export class A {
    // ...
}
```

in the another component script:
```ts
@ccclass
export class B extends Component {
    @property(A)
    a: A = new A();
}
```

If mount B is on the prefab, use the reference function to find the uuid for script A, it will not show that there is a reference on the prefab.

### Steps to reproduce

.

**Comment by jareguo** [comment]
use the reference function 指的是什么？

**Comment by smallmain** [comment]
Find all UUID references, but thought about what I said before, and closed this invalid question
