### ISSUE TITLE
Terrain‘s Effect Asset Bug

### ISSUE THREAD

**Issue by EricF88** [cocos/cocos-engine#14591]
### Cocos Creator version

3.7.2

### System information

windows

### Issue description

After we add Effect Asset on top of our terrain, the material will become darker. After adding the in-engine builtin-terrain.effect, the overall color of the terrain becomes darker.
![企业微信截图_1678872945778](https://user-images.githubusercontent.com/109512513/225272880-0b54ffdf-54f8-41ef-a8d8-4463f4db12ec.png)
![企业微信截图_16788730551823(2)](https://user-images.githubusercontent.com/109512513/225272897-9b9a5c51-f63f-4017-b1c7-64e2be5c8272.png)

### Steps to reproduce

See description above

**Comment by jk20012001** [comment]
legacy/terrain is different from builtin-terrain
