### ISSUE TITLE
[2.4.x] Wrong return-type of `insertSpriteFrame(spriteFrame: SpriteFrame)` in creator.d.ts		

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#14598]
### Cocos Creator version

2.4.11

### System information

all

### Issue description

Wrong return-type of `insertSpriteFrame(spriteFrame: SpriteFrame)` in creator.d.ts.

It should be `Object` or `any`  , NOT `void`.

### Steps to reproduce

none

**Comment by finscn** [comment]
`insertSpriteFrame ` is a method of class `DynamicAtlasManager `.

**Comment by minggo** [comment]
@PPpro please take a look.

**Comment by dumganhar** [comment]
@finscn 你确定是在 2.4.11 中还有这个问题吗？

这个问题之前已经在： https://github.com/cocos/cocos-engine/pull/11981

中修复的了。2.4.10 开始 insertSpriteFrame 函数返回的是 any

**Comment by dumganhar** [comment]
@finscn 确认了，2.4.10 开始也还是有问题，原因是 2.4.10 后，.d.ts 并没有重新生成。

这个 @knoxHuang 会排查一下打包流程。

**Comment by knoxHuang** [comment]
已修复，该修复会进到 2.4.14
