### ISSUE TITLE
custom pipeline in editor

### ISSUE THREAD

**Issue by whaqzhzd** [cocos/cocos-engine#14610]
### Use Case

~

### Problem Description

Regardless of whether it is a new pipeline or an old pipeline implementation in the editor, after we customize the pipeline, the editor always transmits all cameras in the editor to the user layer, regardless of whether it is a camera that the user layer should care about, such as Gizmo camera or other cameras. In theory, does the user layer not need to care about cameras or only care about their own cameras in the scene?

### Alternatives Considered

~

**Comment by star-e** [comment]
I think in [custom pipeline](https://docs.cocos.com/creator/manual/en/render-pipeline/custom-pipeline.html), we will pass all the cameras (including editor's) to the user. See [Write a Custom Render Pipeline](https://docs.cocos.com/creator/manual/en/render-pipeline/custom-pipeline.html#write-a-custom-render-pipeline).

In most cases, user can only customize GAME or GAME_VIEW cameras. These cameras affects game and game preview (in editor/browser).
However, if user has written a very complicated render pipeline such as gpu-driven render pipeline. Scene view might not render correctly in the editor. So a customized EDITOR pipeline should be provided.

Chinese translation:
新的自定义管线会将所有相机交给用户（包括Editor中使用的相机），由用户决定是否要自定义。详情参见 [Write a Custom Render Pipeline](https://docs.cocos.com/creator/manual/en/render-pipeline/custom-pipeline.html#write-a-custom-render-pipeline).

绝大多数情况用户只需关心GAME和GAME_VIEW相机，这些相机影响游戏画面以及预览表现。
假如用户编写了复杂的渲染管线，比如GPU-Driven，那么一般也需要提供对应的Editor实现，才能在场景编辑窗口正常预览。
@whaqzhzd
