### ISSUE TITLE
Remove dependence of CocosActivity

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#14626]
On Android, cocos only have to interact with SurfaceView. Games or other applications can integrate the SurfaceView. So should refactor `CocosActivity` and `CocosSurfaceView`, make engine only interact with SurfaceView.

In order to keep compatible, should keep `CocosActivity`, but it is only a proxy of game's activity.

**Comment by zhitaocai** [comment]
This feature sounds very attractive, looking forward to it

**Comment by bofeng-song** [comment]
The perfect support can only be achieved once this [issue](https://github.com/cocos/cocos-engine/issues/14627) is resolved.
