### ISSUE TITLE
Should remove game activity on Android?

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#14627]
Game activity is a heavy sdk, we should re-consider to use it or not.

**Comment by bofeng-song** [comment]
The main tasks of GameActivity currently are:
1. Handling of the joystick, which was previously handled in the Activity;
=== After removal, only the surfaceView that currently has focus can handle events in multiple windows. Will this meet the expectations of developers?
2. Passing of Activity lifecycle, managing the native lifecycle (library load & unload)
=== After removal, will there be any issues with the android_native_app_glue lifecycle and event dispatching, as well as thread forwarding?
3. After removing GameActivity, can the corresponding code in GameActivity.cpp be retained, and is it necessary to retain it?

**Comment by minggo** [comment]
As engine will finally run in an activity. So i think there is not problem. We may ask the activity to do the same thing that game activity did.

Of course, we should consider:
- why need game activity, the pros and cons

**Comment by bofeng-song** [comment]
Need to do:
- Lifecycle
- Controller Input
- MultiWindow(windowId)
- move Swappy files to libCocos & remove game sdk(containe jar & external files)
