### ISSUE TITLE
[2.2.2] Apk load manifest fail with Android 9

### ISSUE THREAD

**Issue by deploygo88** [cocos/cocos-engine#14631]
### Cocos Creator version

2.2.2

### System information

Windows 10 Pro

### Issue description

Cocos creator: 2.2.2
NDK: 19.2.5345600
JDK: jdk-8u361
Python: 2.7.18

Apk load manifest failed (ERROR_PARSE_MANIFEST) with android version 9 but android version 7 success

### Steps to reproduce

Build apk success but android version 7 connect success, android version 9 manifest failed (same apk file). Can you help me fix it, please? Thanks!

**Comment by deploygo88** [comment]
When i run debug android studio, it show message error "cocos2d-x: AssetsManagerEx : Fail to download version file, step skipped". How can i fix it, please?

**Comment by minggo** [comment]
AssetsManagerEx module doesn't depend on Android version. The error message only exists on Android version 9?

**Comment by deploygo88** [comment]
Yes sir @minggo , I tested with android version 7 and android version 9, and only error message on Android version 9. I don't know where i false.

- Android 7

![image](https://user-images.githubusercontent.com/126611757/227109255-ebb67d66-97ee-4d8b-8dc4-cf417cdf9640.png)

- Android 9

![image](https://user-images.githubusercontent.com/126611757/227109384-a877ff29-e63a-4859-8fc9-aaf30c3f938c.png)

![image](https://user-images.githubusercontent.com/126611757/227109421-de2d4ff9-c705-4ace-aef9-6536b1c3fc19.png)

**Comment by minggo** [comment]
It seems it is something wrong with Android 9 itself: https://stackoverflow.com/questions/55534046/data-not-showing-on-android-pie-9-0.

**Comment by kaokey2204** [comment]
I'm having this problem too. I added network_security_config.xml but that doesn't change anything

**Comment by minggo** [comment]
There is also a doc in Chinese https://www.jianshu.com/p/518669631e01. The meaning is that, there are 3 ways to fix it
**method 1**
- add content in manifest.xm
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ... >
    <application android:networkSecurityConfig="@xml/network_security_config">
    </application>
</manifest>
```
- create `network_security_config.xml` in `res/xml`
```<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

**method 2**
Use https instead.

**method 3**
Change SDK to `27`.

**Comment by deploygo88** [comment]
Thanks for your support, issue done @minggo

**Comment by minggo** [comment]
Glad to hear that the issue is resolved.
