### ISSUE TITLE
fix type issue: animation module

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#14640]
issue from PR: https://github.com/cocos/cocos-engine/pull/14638
see this commit: https://github.com/cocos/cocos-engine/pull/14638/commits/5472d3f8a080c51a9890ee76ffe96225c1d1d855

**Comment by shrinktofit** [comment]
Should be fixed in https://github.com/cocos/cocos-engine/pull/14907 and should eventually be merged in master branch.
