### ISSUE TITLE
[3.7.2]Editor preview fails to load remote bundle

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14660]
### Cocos Creator version

3.7.2

### System information

window 10

### Issue description

![image](https://user-images.githubusercontent.com/40415168/227829862-8fccb60f-2737-438e-8d73-4af5dbbf40b2.png)
![image](https://user-images.githubusercontent.com/40415168/227830308-2cf10200-9f7b-4346-8f94-3f69add62303.png)
Loading a remote bundle link in the editor preview case will splice the timestamp and cause the file to fail to load.
编辑器预览情况下加载远程 bundle 链接会拼接时间戳，导致加载文件失败。

![image](https://user-images.githubusercontent.com/40415168/227831371-bbea5a7e-25f6-4c42-9408-37e76c2a04a3.png)
Data parsing failure due to platform limitations.
由于平台限制导致数据解析失败。

### Steps to reproduce

.

**Comment by SantyWang** [comment]
https://github.com/cocos/cocos-engine/pull/14709/file
