### ISSUE TITLE
[3.7]Android landscape and portrait screen switching causes crashes

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14669]
### Cocos Creator version

3.7.0，3.7.1，3.7.2,3.6.3

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/147427
![image](https://user-images.githubusercontent.com/40415168/227864741-f3a74f5f-61a6-4777-a361-bc285f217272.png)
![image](https://user-images.githubusercontent.com/40415168/227864993-eb37d4f3-5265-4379-be84-d94d6fbae1ba.png)

Version 3.6 works fine
Merge this pr and the resulting:
https://github.com/cocos/cocos-engine/pull/12243/

win10 构建
测试机型： 荣耀 v20, android 10

### Steps to reproduce

demo:
[Creator3.4.0_2D_ScreenSwitch.zip](https://github.com/cocos/cocos-engine/files/11075633/Creator3.4.0_2D_ScreenSwitch.zip)

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/14670
