### ISSUE TITLE
editbox does not get the input text in real time on Android

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14689]
### Cocos Creator version

3.7.1

### System information

android

### Issue description

![image](https://user-images.githubusercontent.com/40415168/228710667-7523d2c3-be44-4cf7-ab19-cde07f44c28d.png)
![image](https://user-images.githubusercontent.com/40415168/228710782-d96cb207-b924-4fff-9ee1-c9f35c3b252e.png)

### Steps to reproduce

.

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/14687
