### ISSUE TITLE
Multi-touch causes Android to crash

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14688]
### Cocos Creator version

3.7.2

### System information

android

### Issue description

https://forum.cocos.org/t/topic/147595
![企业微信截图_1680085342815](https://user-images.githubusercontent.com/40415168/228709687-0e21ea73-ef73-46b6-9ef0-d9398e541293.png)
![企业微信截图_1680085349504](https://user-images.githubusercontent.com/40415168/228709707-255107d3-e554-4d90-8f87-0521648b6256.png)

### Steps to reproduce

.

**Comment by bofeng-song** [comment]
fix at this [PR](https://github.com/cocos/cocos-engine/pull/15796)

Synchronize official processing logic:
https://github.com/android/games-samples/blob/main/agdk/agdktunnel/app/src/main/cpp/input_util.cpp
https://developer.android.com/games/agdk/game-activity/get-started?hl=zh-cn
