### ISSUE TITLE
iOS 键盘弹出,确认键被遮挡

### ISSUE THREAD

**Issue by twiglau** [cocos/cocos-engine#14696]
### Cocos Creator version

3.7.2

### System information

iOS15.5 iPhone13 Pro

### Issue description

v3.7.2/native/cocos/ui/edit-box/EditBox-ios.mm
CGRect getSafeAreaRect() {
    UIView *view = UIApplication.sharedApplication.delegate.window.rootViewController.view;
    CGRect viewRect = view.frame;

    // safeAreaInsets is avaible since iOS 11.
    if (@available(iOS 11.0, *)) {
        auto safeAreaInsets = view.safeAreaInsets;

        UIInterfaceOrientation orient = [UIApplication sharedApplication].statusBarOrientation;
        // 当横屏时, viewRect 应该减去安全区域 [左,右]
        if (UIInterfaceOrientationLandscapeLeft == orient) {
            viewRect.origin.x = 0;
            viewRect.size.width -= safeAreaInsets.right;
            viewRect.size.width -= safeAreaInsets.left;
        } else {
            viewRect.origin.x += safeAreaInsets.left;
            viewRect.size.width -= safeAreaInsets.left;
            viewRect.size.width -= safeAreaInsets.right; 
        }
    }

    return viewRect;
}

### Relevant error log output

nothing

### Steps to reproduce

nothing

### Minimal reproduction project

nothing

**Comment by novain1102** [comment]
Verified, Thanks for your feedback!
