### ISSUE TITLE
se->setExceptionCallback could not catch the Null property (read 'children') for this kind of error.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#14735]
### Cocos Creator version

3.6.2 ～ 3.7.2

### System information

android

### Issue description

---

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/35944775/230563278-f6dc8c66-97b8-493d-aeb4-52652bb0db7e.png)
Unzip and open the following project to build and publish to the Android platform. Add a breakpoint and see if it will run to the breakpoint.

### Minimal reproduction project

[10961.zip](https://github.com/cocos/cocos-engine/files/11176937/10961.zip)

**Comment by dumganhar** [comment]
It was not triggered since the callback was `try catch` by this Pull Request.

https://github.com/cocos/cocos-engine/pull/13647
