### ISSUE TITLE
[3.7.2] remove material pass will cause animation throw error.

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#14752]
### Cocos Creator version

3.7.2 and before version

### System information

Window Editor

### Issue description

1 Enter animation edit mode. 
2. Create an animation tracer with material pass2 value.
3. Save animation.
4. Remove material pass2
5. Restart editor.
6. Animation threw an error.

![image](https://user-images.githubusercontent.com/8321365/230845179-6502e373-f182-4401-9e03-e693faf4a065.png)

### Steps to reproduce

no project.

**Comment by shrinktofit** [comment]
Engine: https://github.com/cocos/cocos-engine/pull/14764
Editor: https://github.com/cocos/cocos-editor/pull/1877
