### ISSUE TITLE
Bitmap font kerning space not correct on font scale

### ISSUE THREAD

**Issue by May2nd** [cocos/cocos-engine#14775]
### Cocos Creator version

3.7.x

### System information

MacOS

### Issue description

space between text "AY" with default font size = 40, kerning = -2 is too narrow on small size.
![Screenshot 2023-04-11 at 16 57 50](https://user-images.githubusercontent.com/122350047/231131215-28855ace-9c2d-4b10-ae9e-d4710c690d39.png)

after fix:
![Screenshot 2023-04-11 at 16 58 36](https://user-images.githubusercontent.com/122350047/231131356-64f94382-767d-4ac5-90c1-dfcbfc1d7234.png)

### Steps to reproduce

Try any bmfont with kerning couple with different font size

**Comment by May2nd** [comment]
Fixed here: https://github.com/cocos/cocos-engine/pull/14776

**Comment by LinYunMo** [comment]
Nice work, thanks for your feedback and fix, I will merge it.
