### ISSUE TITLE
rpVisualizer 这里少写了一个 .default

### ISSUE THREAD

**Issue by Devilsparta** [cocos/cocos-engine#14801]
https://github.com/cocos/cocos-engine/blob/08aa8283b3e1e10d44f81808ab388a79edac2a8d/scripts/build-engine/src/index.ts#L543
https://github.com/cocos/cocos-engine/blob/08aa8283b3e1e10d44f81808ab388a79edac2a8d/scripts/build-engine/src/index.ts#L549

这个 rpVisualizer 是 commonjs 的，少写了一个 .default，或者直接动态 require? 我瞎说的，不过得记得改一下，否则会报错～

**Comment by dumganhar** [comment]
What was the error you got?
BTW, script/build-engine is deprecated, the functionality was moved to `ccbuild` repo https://github.com/cocos/cocos-ccbuild from v3.8.0 .
So I close this issue. If you still get the error, please report it again.

**Comment by dumganhar** [comment]
We disabled Virtualizer plugin in ccbuild temporarily.

**Comment by dumganhar** [comment]
Fixed in v3.8.2 branch
