### ISSUE TITLE
Please ensure access to profiler stats

### ISSUE THREAD

**Issue by mikecoker** [cocos/cocos-engine#14837]
### Use Case

Need to maintain access to profiler stats.

### Problem Description

We're using the profiler._stats field at the moment to track fps and send it through our logging service. According to the comments here: https://github.com/cocos/cocos-engine/blob/d76a8ae2dacb68899972dfdbb7453e2047a2d4e4/cocos/profiler/profiler.ts#L98
This is planned for future deprecation. I hope this is replaced with a different public accessor.

### Proposed Solution

provide a public getter to _stats.

### Alternatives Considered

NA

**Comment by LinYunMo** [comment]
We provide a new public interface that allows you to use **profiler.stats** instead it
