### ISSUE TITLE
cc 2.4.11制作淘宝多页面应用或者将cc游戏部分的内容制作为淘宝小程序组件，退出游戏后，无法重新进入

### ISSUE THREAD

**Issue by liujin1992112** [cocos/cocos-engine#14841]
### Cocos Creator version

2.4.11

### System information

Windows 10 

### Issue description

现象：cc 2.4.11制作淘宝多页面应用或者将cc游戏部分的内容制作为淘宝小程序组件，退出游戏后，无法重新进入。
目的：现在cocos适配了淘宝创意互动小程序，我也使用了接近10年的cocos，考虑使用ccc.2.x、ccc.3.x来做淘宝2d、3d相关应用，但是我这边对技术进行预研和测试了一下。现在cocos只能做单页面的应用程序，如果做多页面应用或者与前端混合开发，离开游戏页面进入其他页面后，Cocos游戏页面无法进入，后面查了一下。由于cocos的脚本资源没有做释放操作，我这边做了一个demo的释放，但是做的不是很完善。看能不能给官网这边反馈，cocos这边考虑优化一下不。我这边做了一个demo，可以释放，但是还是释放不干净。修复过程这是按照以往我们layabox适配淘宝创建互动小程序的方案。
修复工程参考：tb-helloworld/build/taobao-fix 此工程。
复现工程参考：tb-helloworld/build/taobao-修改
原始工程：tb-helloworld/build/taobao

参考论坛地址：https://forum.cocos.org/t/topic/147772

### Steps to reproduce

[tb-helloworld.zip](https://github.com/cocos/cocos-engine/files/11267642/tb-helloworld.zip)

**Comment by minggo** [comment]
Please use english in future, thanks.
And cocos may not design to support this usage.

**Comment by bofeng-song** [comment]
At the current stage, the engine does not support the use of multiple pages because the canvas on the page is limited to on-screen instead of off-screen.
