### ISSUE TITLE
cc 3.7.2 制作淘宝多页面应用或者将cc游戏部分的内容制作为淘宝小程序组件，退出游戏后，无法重新进入

### ISSUE THREAD

**Issue by liujin1992112** [cocos/cocos-engine#14846]
### Cocos Creator version

3.7.2

### System information

Windows 10 

### Issue description

cc 3.7.2 制作淘宝多页面应用或者将cc游戏部分的内容制作为淘宝小程序组件，退出游戏后，无法重新进入

### Relevant error log output

index-a2caeee9.js:1 Error 9100, please go to https://github.com/cocos-creator/engine/blob/develop/EngineErrorMap.md#9100 to see details. Arguments: 2, 
F @ index-a2caeee9.js:1
Y @ index-a2caeee9.js:1
(anonymous) @ gfx-webgl.js:1
i.initialize @ gfx-webgl.js:1
a.createTexture @ gfx-webgl.js:1
a.initialize @ gfx-webgl.js:1
a.createSwapchain @ gfx-webgl.js:1
t._initSwapchain @ find-7986c85b.js:1
t.init @ find-7986c85b.js:1
(anonymous) @ deprecated-a8677f1c.js:1
Promise.then (async)
s.init @ deprecated-a8677f1c.js:1
start @ application.js:42
(anonymous) @ index.js:60
Promise.then (async)
(anonymous) @ index.js:56
Promise.then (async)
(anonymous) @ index.js:53
Promise.then (async)
$global.__onCanvasCreated @ index.js:50
success @ index.js:93
(anonymous) @ af-appx.worker.min.js:6
e.whenElementReady @ af-appx.worker.min.js:6
e.whenCompositeElementReady @ af-appx.worker.min.js:6
fn @ af-appx.worker.min.js:6
e.invoke @ af-appx.worker.min.js:6
Ao @ af-appx.worker.min.js:6
e.call4PublicNamed @ af-appx.worker.min.js:6
canvasOnReady @ index.js:84
e.invokePublicMethod @ af-appx.worker.min.js:6
e.invokeHostTargetMethod @ af-appx.worker.min.js:6
e.onReceiveMethodCall @ af-appx.worker.min.js:6
e.onMessage @ af-appx.worker.min.js:6
e.executeFunctionAsync @ vendors.bundle.js/:46
e.handleMessageFromRender4MessagePort @ vendors.bundle.js/:66
e.handleMessageFromRender @ vendors.bundle.js/:66
t.postMessage2Host @ vendors.bundle.js/:79
e.postMessage2Host @ vendors.bundle.js/:79
e.handleAPI4PostMessage @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
t.onPortMessage @ af-appx.min.js:6
t.postOppositeMessage @ af-appx.min.js:6
t.postMessage @ af-appx.min.js:6
t.invokeHostTargetMethod @ af-appx.min.js:6
t.invokeHostTargetMethod @ af-appx.min.js:6
t.callMethod @ af-appx.min.js:6
t.callHostReadyTargetMethod @ af-appx.min.js:6
vl @ af-appx.min.js:6
t.invokeEventContext @ af-appx.min.js:6
i.onRenderReady @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
(anonymous) @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
invokeCallback @ vendors.bundle.js/:79
render @ vendors.bundle.js/:31
e.invokeRenderMessage @ vendors.bundle.js/:79
e.render @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
n.invokeClientBridgeCall @ af-appx.min.js:6
t.invokeClientBridgeCall @ af-appx.min.js:6
t.render @ af-appx.min.js:6
t.onStateReady @ af-appx.min.js:6
il @ af-appx.min.js:6
t.afterUpdate @ af-appx.min.js:6
t.flushUpdatedQueue @ af-appx.min.js:6
t.onMount @ af-appx.min.js:6
t.onMount @ af-appx.min.js:6
t.onDispatchRequestImpl @ af-appx.min.js:6
t.onDispatchRequestBeforeRequirements @ af-appx.min.js:6
t.onDispatchActionImpl @ af-appx.min.js:6
t.onMessage @ af-appx.min.js:6
t.postOppositeMessage @ af-appx.min.js:6
t.postMessage @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
eval
eval
(anonymous) @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:46
a @ vendors.bundle.js/:46
t.evalScript @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:66
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
a @ vendors.bundle.js/:16
t.dispatchEvent @ vendors.bundle.js/:66
(anonymous) @ vendors.bundle.js/:66
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
a @ vendors.bundle.js/:16
t.dispatchEvent @ vendors.bundle.js/:66
s @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
o @ vendors.bundle.js/:79
t.postMessage2Client @ vendors.bundle.js/:79
t.postMessage2Runtime @ vendors.bundle.js/:79
postMessage @ vendors.bundle.js/:66
e.onRenderMount @ af-appx.worker.min.js:6
e.performMountAfterWaiting @ af-appx.worker.min.js:6
e.onMount @ af-appx.worker.min.js:6
e.bootstrap @ af-appx.worker.min.js:6
e.bootstrap @ af-appx.worker.min.js:6
postprocess @ af-appx.worker.min.js:6
e.postprocess @ af-appx.worker.min.js:6
e.performPostNavigation @ af-appx.worker.min.js:6
e.onPageCreate @ af-appx.worker.min.js:6
e.createInstance @ af-appx.worker.min.js:6
Wf @ af-appx.worker.min.js:6
(anonymous) @ af-appx.worker.min.js:6
e.prepareAndLoadPage @ af-appx.worker.min.js:6
e.onCreatePage @ af-appx.worker.min.js:6
Ff @ af-appx.worker.min.js:6
onmessage @ af-appx.worker.min.js:6
t @ af-appx.worker.min.js:6
(anonymous) @ vendors.bundle.js/:66
e.handleMessageFromRender4Init @ vendors.bundle.js/:66
e.handleMessageFromRender @ vendors.bundle.js/:66
t.postMessage2Host @ vendors.bundle.js/:79
e.postMessage2Host @ vendors.bundle.js/:79
e.handleAPI4PostMessage @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
t.postMessage @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
t.finish @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
n.finish @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
(anonymous) @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
invokeCallback @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
e.registerCompleteListener @ vendors.bundle.js/:79
e.createWorker @ vendors.bundle.js/:79
e.handleAPI4RegisterWorker @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
i @ af-appx.min.js:6
b0 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
n.create @ af-appx.min.js:6
t.add @ af-appx.min.js:6
V1 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
onReady @ index.html:11
waitEnvReady @ af-appx.min.js:6
j1 @ af-appx.min.js:6
window.bootstrapApp @ af-appx.min.js:6
(anonymous) @ index.html:17
(anonymous) @ index.html:21
Show 73 more frames
index.js:65 TypeError: Cannot read property 'glTexture' of undefined
    at gfx-webgl.js:1
    at a.i.initialize (gfx-webgl.js:1)
    at s.a.createTexture (gfx-webgl.js:1)
    at s.a.initialize (gfx-webgl.js:1)
    at s.a.createSwapchain (gfx-webgl.js:1)
    at e.t._initSwapchain (find-7986c85b.js:1)
    at e.t.init (find-7986c85b.js:1)
    at deprecated-a8677f1c.js:1
(anonymous) @ index.js:65
Promise.catch (async)
$global.__onCanvasCreated @ index.js:62
success @ index.js:93
(anonymous) @ af-appx.worker.min.js:6
e.whenElementReady @ af-appx.worker.min.js:6
e.whenCompositeElementReady @ af-appx.worker.min.js:6
fn @ af-appx.worker.min.js:6
e.invoke @ af-appx.worker.min.js:6
Ao @ af-appx.worker.min.js:6
e.call4PublicNamed @ af-appx.worker.min.js:6
canvasOnReady @ index.js:84
e.invokePublicMethod @ af-appx.worker.min.js:6
e.invokeHostTargetMethod @ af-appx.worker.min.js:6
e.onReceiveMethodCall @ af-appx.worker.min.js:6
e.onMessage @ af-appx.worker.min.js:6
e.executeFunctionAsync @ vendors.bundle.js/:46
e.handleMessageFromRender4MessagePort @ vendors.bundle.js/:66
e.handleMessageFromRender @ vendors.bundle.js/:66
t.postMessage2Host @ vendors.bundle.js/:79
e.postMessage2Host @ vendors.bundle.js/:79
e.handleAPI4PostMessage @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
t.onPortMessage @ af-appx.min.js:6
t.postOppositeMessage @ af-appx.min.js:6
t.postMessage @ af-appx.min.js:6
t.invokeHostTargetMethod @ af-appx.min.js:6
t.invokeHostTargetMethod @ af-appx.min.js:6
t.callMethod @ af-appx.min.js:6
t.callHostReadyTargetMethod @ af-appx.min.js:6
vl @ af-appx.min.js:6
t.invokeEventContext @ af-appx.min.js:6
i.onRenderReady @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
(anonymous) @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
invokeCallback @ vendors.bundle.js/:79
render @ vendors.bundle.js/:31
e.invokeRenderMessage @ vendors.bundle.js/:79
e.render @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
n.invokeClientBridgeCall @ af-appx.min.js:6
t.invokeClientBridgeCall @ af-appx.min.js:6
t.render @ af-appx.min.js:6
t.onStateReady @ af-appx.min.js:6
il @ af-appx.min.js:6
t.afterUpdate @ af-appx.min.js:6
t.flushUpdatedQueue @ af-appx.min.js:6
t.onMount @ af-appx.min.js:6
t.onMount @ af-appx.min.js:6
t.onDispatchRequestImpl @ af-appx.min.js:6
t.onDispatchRequestBeforeRequirements @ af-appx.min.js:6
t.onDispatchActionImpl @ af-appx.min.js:6
t.onMessage @ af-appx.min.js:6
t.postOppositeMessage @ af-appx.min.js:6
t.postMessage @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
eval
eval
(anonymous) @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:46
a @ vendors.bundle.js/:46
t.evalScript @ vendors.bundle.js/:46
(anonymous) @ vendors.bundle.js/:66
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
a @ vendors.bundle.js/:16
t.dispatchEvent @ vendors.bundle.js/:66
(anonymous) @ vendors.bundle.js/:66
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
(anonymous) @ vendors.bundle.js/:16
a @ vendors.bundle.js/:16
t.dispatchEvent @ vendors.bundle.js/:66
s @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
o @ vendors.bundle.js/:79
t.postMessage2Client @ vendors.bundle.js/:79
t.postMessage2Runtime @ vendors.bundle.js/:79
postMessage @ vendors.bundle.js/:66
e.onRenderMount @ af-appx.worker.min.js:6
e.performMountAfterWaiting @ af-appx.worker.min.js:6
e.onMount @ af-appx.worker.min.js:6
e.bootstrap @ af-appx.worker.min.js:6
e.bootstrap @ af-appx.worker.min.js:6
postprocess @ af-appx.worker.min.js:6
e.postprocess @ af-appx.worker.min.js:6
e.performPostNavigation @ af-appx.worker.min.js:6
e.onPageCreate @ af-appx.worker.min.js:6
e.createInstance @ af-appx.worker.min.js:6
Wf @ af-appx.worker.min.js:6
(anonymous) @ af-appx.worker.min.js:6
e.prepareAndLoadPage @ af-appx.worker.min.js:6
e.onCreatePage @ af-appx.worker.min.js:6
Ff @ af-appx.worker.min.js:6
onmessage @ af-appx.worker.min.js:6
t @ af-appx.worker.min.js:6
(anonymous) @ vendors.bundle.js/:66
e.handleMessageFromRender4Init @ vendors.bundle.js/:66
e.handleMessageFromRender @ vendors.bundle.js/:66
t.postMessage2Host @ vendors.bundle.js/:79
e.postMessage2Host @ vendors.bundle.js/:79
e.handleAPI4PostMessage @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
t.postMessage @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
t.finish @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
n.finish @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
(anonymous) @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
invokeCallback @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
e.registerCompleteListener @ vendors.bundle.js/:79
e.createWorker @ vendors.bundle.js/:79
e.handleAPI4RegisterWorker @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
i @ af-appx.min.js:6
b0 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
n.create @ af-appx.min.js:6
t.add @ af-appx.min.js:6
V1 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
onReady @ index.html:11
waitEnvReady @ af-appx.min.js:6
j1 @ af-appx.min.js:6
window.bootstrapApp @ af-appx.min.js:6
(anonymous) @ index.html:17
(anonymous) @ index.html:21
Show 73 more frames
gfx-webgl.js:1 Uncaught TypeError: Cannot read property 'glTexture' of undefined
    at _t (gfx-webgl.js:1)
    at r.s.bindStates (gfx-webgl.js:1)
    at r.s.draw (gfx-webgl.js:1)
    at e.t.render (director-53a48848.js:1)
    at t.i.render (director-53a48848.js:1)
    at t.render (director-53a48848.js:1)
    at t.i.render (director-53a48848.js:1)
    at t.n.render (director-53a48848.js:1)
    at e.i.frameMove (director-53a48848.js:1)
    at t.i.tick (director-53a48848.js:1)
_t @ gfx-webgl.js:1
s.bindStates @ gfx-webgl.js:1
s.draw @ gfx-webgl.js:1
t.render @ director-53a48848.js:1
i.render @ director-53a48848.js:1
t.render @ director-53a48848.js:1
i.render @ director-53a48848.js:1
n.render @ director-53a48848.js:1
i.frameMove @ director-53a48848.js:1
i.tick @ director-53a48848.js:1
s._updateCallback @ deprecated-a8677f1c.js:1
_updateCallback @ deprecated-a8677f1c.js:1
requestAnimationFrame (async)
_updateCallback @ deprecated-a8677f1c.js:1
requestAnimationFrame (async)
_updateCallback @ deprecated-a8677f1c.js:1
requestAnimationFrame (async)
_updateCallback @ deprecated-a8677f1c.js:1
requestAnimationFrame (async)
t.start @ deprecated-a8677f1c.js:1
s.resume @ deprecated-a8677f1c.js:1
s.resumeByEngine @ deprecated-a8677f1c.js:1
s._onShow @ deprecated-a8677f1c.js:1
e.emit @ index-a2caeee9.js:1
(anonymous) @ index-a2caeee9.js:1
onShow @ index.js:101
e.invokePublicMethod @ af-appx.worker.min.js:6
e.invokePageEvent @ af-appx.worker.min.js:6
e.performLifeHook @ af-appx.worker.min.js:6
i.<computed> @ af-appx.worker.min.js:6
e.setStateFromState @ af-appx.worker.min.js:6
e.setState @ af-appx.worker.min.js:6
e.setState @ af-appx.worker.min.js:6
e.bootstrap @ af-appx.worker.min.js:6
e.bootstrap @ af-appx.worker.min.js:6
postprocess @ af-appx.worker.min.js:6
e.postprocess @ af-appx.worker.min.js:6
e.performPostNavigation @ af-appx.worker.min.js:6
e.onPageCreate @ af-appx.worker.min.js:6
e.createInstance @ af-appx.worker.min.js:6
Wf @ af-appx.worker.min.js:6
(anonymous) @ af-appx.worker.min.js:6
e.prepareAndLoadPage @ af-appx.worker.min.js:6
e.onCreatePage @ af-appx.worker.min.js:6
Ff @ af-appx.worker.min.js:6
onmessage @ af-appx.worker.min.js:6
t @ af-appx.worker.min.js:6
(anonymous) @ vendors.bundle.js/:66
e.handleMessageFromRender4Init @ vendors.bundle.js/:66
e.handleMessageFromRender @ vendors.bundle.js/:66
t.postMessage2Host @ vendors.bundle.js/:79
e.postMessage2Host @ vendors.bundle.js/:79
e.handleAPI4PostMessage @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
t.postMessage @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
t.finish @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
n.finish @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
(anonymous) @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
invokeCallback @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
e.registerCompleteListener @ vendors.bundle.js/:79
e.createWorker @ vendors.bundle.js/:79
e.handleAPI4RegisterWorker @ vendors.bundle.js/:79
e.bridgeCall @ vendors.bundle.js/:79
e.callBridgePluginAsyncInternal @ vendors.bundle.js/:79
(anonymous) @ vendors.bundle.js/:79
setTimeout (async)
e.bridgeCall @ vendors.bundle.js/:79
t.invokeBridgeAsync @ vendors.bundle.js/:66
call @ vendors.bundle.js/:46
t0 @ af-appx.min.js:6
o0 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
i @ af-appx.min.js:6
b0 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
n.create @ af-appx.min.js:6
t.add @ af-appx.min.js:6
V1 @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
(anonymous) @ af-appx.min.js:6
onReady @ index.html:11
waitEnvReady @ af-appx.min.js:6
j1 @ af-appx.min.js:6
window.bootstrapApp @ af-appx.min.js:6
(anonymous) @ index.html:17
(anonymous) @ index.html:21
Show 22 more frames
gfx-webgl.js:1 Command 'updateBuffer' must be recorded outside a render pass.

### Steps to reproduce

现在cocos只能做单页面的应用程序，如果做多页面应用或者与前端混合开发，离开游戏页面进入其他页面后，Cocos游戏页面无法进入，后面查了一下。由于cocos的脚本资源没有做释放操作，我这边做了一个demo的释放，但是做的不是很完善。看能不能给官网这边反馈，cocos这边考虑优化一下不。我这边做了一个demo，可以释放，但是还是释放不干净。修复过程这是按照以往我们layabox适配淘宝创建互动小程序的方案。

**Comment by minggo** [comment]
Please use english in future, thanks.
And cocos may not design to support this usage.

**Comment by bofeng-song** [comment]
Cocos doesn`t support multi page program. Because a page requires an on-screen canvas.
