### ISSUE TITLE
MOUSE_LEAVE event does not respond after mouse over canvas

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14852]
### Cocos Creator version

3.7.2

### System information

window 10，chrome

### Issue description

https://forum.cocos.org/t/topic/148249
![image](https://user-images.githubusercontent.com/40415168/233005924-43add5b5-9f56-46e0-ab56-aa7e48ea57e6.png)

### Steps to reproduce

.

**Comment by 1226085293** [comment]
需要在 mouse-input.ts 中 _registerEvent 函数监听 canvas 的 mouseleave 事件

**Comment by minggo** [comment]
Don't quite understand the issue. Cocos app is drawn in a canvas, why can it receive leave event?

**Comment by 1226085293** [comment]
> Don't quite understand the issue. Cocos app is drawn in a canvas, why can it receive leave event?

Because if used for borderless applications, the display effect of the button will be wrong.

**Comment by minggo** [comment]
Got it. But i am not familiar with web, you are appreciated if you can provide a demo for the issue.

**Comment by 1226085293** [comment]
> Got it. But i am not familiar with web, you are appreciated if you can provide a demo for the issue.

Refer to the GIF demonstration in the post. You only need to place a button close to the edge, and then move the mouse from the button to outside the canvas to reproduce it.

**Comment by minggo** [comment]
I did as you said, but can not produce the issue.
![WeChat5c808d488875ace3e6f4ba6327118083](https://github.com/cocos/cocos-engine/assets/488203/383887c3-5052-4e3f-a87f-19b503b15d30)

**Comment by 1226085293** [comment]
> I did as you said, but can not produce the issue. ![WeChat5c808d488875ace3e6f4ba6327118083](https://private-user-images.githubusercontent.com/488203/320247860-383887c3-5052-4e3f-a87f-19b503b15d30.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTcyMjMsIm5iZiI6MTcxMjQ1NjkyMywicGF0aCI6Ii80ODgyMDMvMzIwMjQ3ODYwLTM4Mzg4N2MzLTUwNTItNGUzZi1hODdmLTE5YjUwM2IxNWQzMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwMjI4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGNhNGM0MzBjNDRmNTY4NjIzMDEzYjQ1ZTM0MWYwYmM1YmY3NTJlODg5MDY1NzEzZjczOTkyNWExMDI2ZDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GqM-qOLQ3PTIBdb2RwaS3MzL3er9QNGos8DZoJLRaps)

![image](https://github.com/cocos/cocos-engine/assets/45589707/015ff586-1b0f-47aa-a12f-ac5823f584c1)

**Comment by 1226085293** [comment]
https://github.com/cocos/cocos-engine/assets/45589707/71efe29e-4e59-4832-b71d-b6f9778ed602

**Comment by minggo** [comment]
Thanks, i can reproduce it.

**Comment by minggo** [comment]
Fixed it in https://github.com/cocos/cocos-engine/pull/16886
