### ISSUE TITLE
微信小游戏平台，通过resources.load spineData资源，Texure 图片实际为空

### ISSUE THREAD

**Issue by honghu91** [cocos/cocos-engine#14859]
### Cocos Creator version

3.6.1, 3.7

### System information

MacOS 12.3.1

### Issue description

将spine动画导出的资源（png，json, atlas)导入到resources目录，通过脚本，resources.load动态加载资源，Texure 图片实际为空

### Steps to reproduce

**导入资源**

1. 将 spine.png spine.atlas spine.json同名文件导入到assets/resources目录
2. 在脚本中添加如下代码
```
resources.load('spine', sp.SkeletonData, (err, asset) => {
  console.log('spineData', err, asset);
});
```
3. 编译代码，在微信小游戏平台运行
检查asset.textures[0].image, 其url, width, height均有问题，实际image不可用

**Comment by minggo** [comment]
Please use english in future, thanks. Or we may not handle it.

**Comment by Canvasfull** [comment]
3.8.1 has fixed this problem.
