### ISSUE TITLE
On Web games, the Input.EventType.DEVICEMOTION event does not fire on Android devices

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#14872]
### Cocos Creator version

3.6.3

### System information

android 12

### Issue description

test code：
```
input.on(Input.EventType.DEVICEMOTION, (e)=>{
        console.log(e);
})
```

### Relevant error log output

-

### Steps to reproduce

-

**Comment by PPpro** [comment]
Please use DEVICEMOTION event under a domain name with a security certificate

**Comment by zhefengzhang** [comment]
https://download.cocos.org/CocosTechnicalSupport/VipIssues/XinXiang/20230420/001/web-mobile/ 
This is my test link and it still doesn't work.

<img width="432" alt="图片" src="https://user-images.githubusercontent.com/35944775/233312251-0c096376-143c-41b9-ba78-add3bb949bad.png">

**Comment by zhefengzhang** [comment]
原因是现在引擎想要监听重力感应事件，只调用
```
input.on(Input.EventType.DEVICEMOTION, (e)=>{
            console.log(e);
        })
```

其实并不会真正的添加全局重力感应事件监听。
只有调用 `input.setAccelerometerEnabled(true);` 才会真正的添加事件监听。
当全局事件触发之后，才能接着触发用户监听的 Input.EventType.DEVICEMOTION 事件

---

The reason is that now the engine wants to listen for gravity sensing events, just calling 
```
input.on(Input.EventType.DEVICEMOTION, (e)=>{
            console.log(e);
        })
```
does not really add global gravity sensing event listening. 
Only the call to `input.setAccelerometerEnabled(true);` will actually add the event listener. After the global event is triggered, the user-monitored Input.EventType.DEVICEMOTION event can be triggered
