### ISSUE TITLE
Test case3.7 build resources are too large, close to 400m

### ISSUE THREAD

**Issue by qiuguohua** [cocos/cocos-engine#14882]
### Use Case

Build android, windows, openharmony platform are the same.

![WXWorkCapture_16819628051469](https://user-images.githubusercontent.com/5205637/233553673-0f3b91c6-9a1d-4106-9be6-16f6adf0e779.png)

### Problem Description

The resources of test-case 3.7 build are close to 400M, even if only some scenarios are selected, the resources are close to 300M.

### Alternatives Considered

Non-testing scenarios with reduced resource size

**Comment by jk20012001** [comment]
https://github.com/cocos/cocos-test-projects/pull/773
