### ISSUE TITLE
When rigidbody2d is deleted, mouseJoint2d reports an error

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#14895]
### Cocos Creator version

3.7.2

### System information

all

### Issue description

![image](https://user-images.githubusercontent.com/14273437/233833379-d8d8a31b-a3b6-49a0-8737-403fd4bede89.png)

When deleting a 2d rigid body, clicking on the mousejoint node gives an error.

I found out that the engine added a canvas fullscreen listener event, but did not destroy the listener action.

![企业微信截图_16822433409080](https://user-images.githubusercontent.com/14273437/233834156-d59c9b36-eb82-4215-8e80-69e2c32e46a4.png)

### Steps to reproduce

[Creator3.7.2_Box2D_MouseJoint.zip](https://github.com/cocos/cocos-engine/files/11303394/Creator3.7.2_Box2D_MouseJoint.zip)

**Comment by yeshao2069** [comment]
https://discuss.cocos2d-x.org/t/problem-with-mousejoint2d/58572/5

**Comment by minggo** [comment]
It seems it is fixed with latest codes.
