### ISSUE TITLE
Bug of UI alignment tool in 3.7.2

### ISSUE THREAD

**Issue by gh201200** [cocos/cocos-engine#14925]
URL : https://github.com/cocos-creator/creator-docs/blob/master/zh/editor/scene/index.md

In version 3.7.2, the UI alignment tool has a bug. If you first select A, then B, and increase the distance between A and B, clicking on "align bottoms" will align the bottom of A to the bottom of B. Sometimes both A and B will move.

----

3.7.2 UI对齐工具有bug，先选中A再选中B，AB距离拉大点，然后点底对齐会把A的底对齐到B的底，有时候AB都会移动

**Comment by AndyYuTian** [comment]
After several tries, it seems that we cannot reproduce this bug on our end. Just wondering is it always reproducible for you? If it is, could you please let us know more about your system and device?

我们在3.7.2上面试过了无法复现，请问在你那边是必现么？如果是的话 ，你的系统和机器信息， 或者错误项目能给我们发一下吗？

**Comment by gh201200** [comment]
必现的，给你们录屏了
https://pan.baidu.com/s/1NotZnYnsYLD-PTrkZg7dNA?pwd=p2wt




Just&nbsp;So&nbsp;So
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cocos/cocos-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 下午3:16
***@***.***&gt;;
抄送:&nbsp;"Just So ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cocos/cocos-engine] Bug of UI alignment tool in 3.7.2 (Issue #14925)





 
After several tries, it seems that we cannot reproduce this bug on our end. Just wondering is it always reproducible for you? If it is, could you please let us know more about your system and device?
 
我们在3.7.2上面试过了无法复现，请问在你那边是必现么？如果是的话 ，你的系统和机器信息， 或者错误项目能给我们发一下吗？

**Comment by AndyYuTian** [comment]
哦 我明白您的意思了 按照文档的意思 是应该以最后一个选中的作为锚点对齐，而在你的录屏中，可以看到在锚点长度小于选择对齐组件长度时，锚点反转了，造成了顺序行为不统一的结果。 我们可以在用户选择对齐时，锚点高亮或者以不同颜色显示，这样不容易产生困惑。

**Comment by gh201200** [comment]
我看FGUI和Laya3.0都是把第一个选择的UI作为参考对齐后面选择的UI，不管后面选择的UI位置在哪儿第一个选参考UI都是不变的，而且把这些常用的功能展开更好吧
&nbsp;


Just&nbsp;So&nbsp;So
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月26日(星期三) 下午3:55
收件人: ***@***.***&gt;; 
抄送: "Just So ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cocos/cocos-engine] Bug of UI alignment tool in 3.7.2 (Issue #14925)





 
哦 我明白您的意思了 按照文档的意思 是应该以最后一个选中的作为锚点对齐，而在你的录屏中，可以看到在锚点长度小于选择对齐组件长度时，锚点反转了，造成了顺序行为不统一的结果。 我们可以在用户选择对齐时，锚点高亮或者以不同颜色显示，这样不容易产生困惑。

**Comment by zakiya0-0** [comment]
UI对齐交互：
1、添加4个边及中心对齐磁吸效果
2、默认以第一个选中的为对齐对象
3、选中多个后，再次选中其中某个对象指定为对齐对象

**Comment by dogeFu** [comment]
文档描述有误；
目前的逻辑是，选中所有的节点后，会根据当前非子节点（如果选中节点中有父子关系，那只考虑父节点）的位置，算出这些节点的AABB,当点击底部对齐时，则将所有的节点都放到底部；当点击左对齐时，则把所有的节点对齐到最左边；
麻烦@UniqueDisplayNameIsInUse 更新一下文档https://docs.cocos.com/creator/manual/zh/editor/scene/#%E5%AF%B9%E9%BD%90%E5%92%8C%E5%88%86%E5%B8%83

**Comment by UniqueDisplayNameIsInUse** [comment]
已修复 
https://github.com/cocos/cocos-docs/pull/2581
