### ISSUE TITLE
Provide build scripts for V8 library

### ISSUE THREAD

**Issue by adrianmdumitru** [cocos/cocos-engine#14935]
### Cocos Creator version

3.7.2

### System information

All platforms

### Issue description

Currently in https://github.com/cocos/cocos-engine-external there is no way for users to re-compile V8 library.

There are cases when we need to include some features like i18n which require the library to be re-compiled with certain flag but we have no build script for it in order to match the original built file.

### Steps to reproduce

Write code that uses `Intl`, it can not run correctly

**Comment by minggo** [comment]
Compile v8 is a little difficult. We just use the method provided by v8. But yep, we should record the flags we used to build v8.

**Comment by adrianmdumitru** [comment]
@PatriceJiang @dumganhar  can you help with this?

**Comment by dumganhar** [comment]
Hi, @adrianmdumitru you could follow v8 official documentation here: 
https://v8.dev/docs/cross-compile-arm
https://v8.dev/docs/cross-compile-ios

args.gn could be 

```
target_cpu = "arm64"
v8_target_cpu = "arm64"
use_thin_lto = false
use_lld = false
clang_use_chrome_plugins = false
chrome_pgo_phase = 0
is_component_build = false
v8_monolithic = true
use_custom_libcxx = false
is_debug = false
v8_use_external_startup_data = false
is_official_build = true
v8_enable_i18n_support = false // Modify this to true if you want the i18n support
treat_warnings_as_errors = false
symbol_level = 0
v8_enable_webassembly = true
use_cxx17 = true
v8_enable_sandbox = false
```

**Comment by dumganhar** [comment]
Build script: https://github.com/dumganhar/v8/blob/11.6/build-android.sh
