### ISSUE TITLE
[3.7.1] 平面阴影开启use instance,每个影子会存在多个实例

### ISSUE THREAD

**Issue by guoyuandong** [cocos/cocos-engine#14953]
### Cocos Creator version

3.7.1

### System information

web native

### Issue description

           //代码片段  位于 cocos\rendering\planar-shadow-queue.ts

            const subModels = model.subModels;
            for (let j = 0; j < subModels.length; j++) {
                const subModel = subModels[j];
                const passes = subModel.passes;
                /**我修改后的代码**/
                const batchingScheme = passes[0].batchingScheme;
                if (batchingScheme === BatchingSchemes.INSTANCING) {
                    instancedBuffer.merge(subModel, 0, subModel.planarInstanceShader);
                    this._instancedQueue.queue.add(instancedBuffer);
                } else {
                    this._pendingSubModels.push(subModel);
                }
                /** 引擎原本代码**/
                // for (let k = 0; k < passes.length; k++) {
                //     const pass = passes[k];
                //     const batchingScheme = pass.batchingScheme;
                //     if (batchingScheme === BatchingSchemes.INSTANCING) {
                //         instancedBuffer.merge(subModel, k, subModel.planarInstanceShader);
                //         this._instancedQueue.queue.add(instancedBuffer);
                //     } else {
                //         this._pendingSubModels.push(subModel);
                //     }
                // }
            }

           这里原本的逻辑为什么是物体每有一个pass阴影就多一个实例。我按照自己的理解改成一个物体产生一个阴影实例后，实 
           测性能有提升。
           

### Relevant error log output

none

### Steps to reproduce

none

### Minimal reproduction project

none

**Comment by troublemaker52025** [comment]
planar-shadow in instanced mode uses instances of the standard material (with multiple instances), and the instanced layout is the same. Obviously this is not correct, and we will fix it in a later version.
In v3.7.3, we are temporarily removing planar-shadow support for instanced to ensure that the effect is correct.

* For more details, please refer to https://github.com/cocos/cocos-engine/pull/14941

**Comment by jk20012001** [comment]
need add a pass to legacy / surface shader, enable instancing feature only when this pass existed

**Comment by troublemaker52025** [comment]
> need add a pass to legacy / surface shader, enable instancing feature only when this pass existed

Will be implemented on v3.8.0 version https://github.com/cocos/cocos-engine/pull/14958
