### ISSUE TITLE
[ios]Audio does not resume playback properly

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#14969]
### Cocos Creator version

2.4.11 , 3.7.2

### System information

ios 15.7, ios 16.2

### Issue description

https://forum.cocos.org/t/topic/148553
![image](https://user-images.githubusercontent.com/40415168/236398543-a684c48f-f640-46b9-9097-237417d0826e.png)

Higher chance of recurrence with ios 16.2 testing
使用 ios16 测试复现几率较高；

测试机型：iPhone12 (蓝) ios 16.2

### Steps to reproduce

3.7.2 demo:
[归档 (2).zip](https://github.com/cocos/cocos-engine/files/11404108/2.zip)

2.4.11demo:
[归档 (1).zip](https://github.com/cocos/cocos-engine/files/11404096/1.zip)

**Comment by bofeng-song** [comment]
This version of Unity, 2021.3.16f1c1, also has similar issues.
Only iOS 16 and above have problems, which may be a system-level issue that the application cannot modify.

**Comment by bofeng-song** [comment]
wechat version: 8.0.37
