### ISSUE TITLE
Avoid stopping playground music because of resource limit.

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#14970]
If two many musics are played simultaneously, background music will be stopped because of resource limitation. Should find a way to resolve it. For example, add a method to keep a music instance that are not stopped.

**Comment by bofeng-song** [comment]
The current implementation is that if more than 10 sound effects are played, the first one will be stopped and the new one will be added to the management queue, without stopping all sound effects.

**Comment by bofeng-song** [comment]
Developers can use play to play regular sounds, playoneShot to play sound effects, and call different interfaces for different sounds.
