### ISSUE TITLE
Error when compiling a project with Android Studio after enabling native built-in memory checking

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#15004]
### Cocos Creator version

3.7.2

### System information

Windows10

### Issue description

form forum: https://forum.cocos.org/t/topic/148851

used ndk : 18、19、21

### Relevant error log output

F:/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/new:345: undefined reference to __cyg_profile_func_enter' libswappy_static.a(ChoreographerThread.cpp.o): In function std::__ndk1::_DeallocateCaller::__do_deallocate_handle_size_align(void*, unsigned long, unsigned long)’:
F:/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/new:265: undefined reference to __cyg_profile_func_enter' libswappy_static.a(ChoreographerThread.cpp.o): In function std::__ndk1::__is_overaligned_for_new(unsigned long)’:
F:/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/new:235: undefined reference to __cyg_profile_func_enter' F:/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/new:237: undefined reference to __cyg_profile_func_exit’
libswappy_static.a(ChoreographerThread.cpp.o): In function std::__ndk1::_DeallocateCaller::__do_deallocate_handle_size_align(void*, unsigned long, unsigned long)': F:/sdk/ndk/19.2.5345600/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/new:277: undefined reference to __cyg_profile_func_exit’
libswappy_static.a(ChoreographerThread.cpp.o): In function `std::__ndk1::__libcpp_deallocate(void*, unsigned long, unsigned long)’:

### Steps to reproduce

-

**Comment by minggo** [comment]
I tested in v3.8.3, no problem. It seems it is fixed in some version.
