### ISSUE TITLE
[Security] Advisory in triage state for a month

### ISSUE THREAD

**Issue by intrigus-lgtm** [cocos/cocos-engine#15002]
Hey, could you please triage https://github.com/cocos/cocos-engine/security/advisories/GHSA-24jj-5hhj-gr8p ?
It's in triage state for about a month.

**Comment by minggo** [comment]
Sorry, what's the problem? I can not open the url above.

**Comment by intrigus-lgtm** [comment]
@minggo unfortunately, only [owners](https://github.com/orgs/cocos/people?query=role%3Aowner) of the cocos organization can view the advisory.

**Comment by minggo** [comment]
@jareguo could you please take a look? I don't have the permission to open the URL.

**Comment by jareguo** [comment]
Thank you for your response. We will verify it as soon as possible. Your feedback is appreciated!

**Comment by minggo** [comment]
https://github.com/cocos/cocos-engine/pull/15415 fixed the usage.
@intrigus-lgtm could you please take a look if it resolved the issue. Thanks.

**Comment by intrigus-lgtm** [comment]
This action is now safe.
However, it will fail for external contributors.
I don't know if this is acceptable to you.

**Comment by minggo** [comment]
> However, it will fail for external contributors.

Could you please describe it in more detail?

**Comment by intrigus-lgtm** [comment]
@minggo see #15451

**Comment by minggo** [comment]
@intrigus-lgtm thanks, we will take a look.
