### ISSUE TITLE
Simulator switching between dual monitors may result in a click offset

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#15010]
### Cocos Creator version

3.7.2

### System information

mac

### Issue description

https://forum.cocos.org/t/topic/148892
![企业微信截图_16836173375060](https://user-images.githubusercontent.com/40415168/237028147-de697004-53e8-46da-82c8-80a036ed04dd.png)

### Steps to reproduce

.

**Comment by novain1102** [comment]
We found that there is a new problem in 3.7. The mouse coordinates will be incorrect between screens with different resolutions (dpi), which will cause the click to fail.
For example: if you pull from a laptop retina screen to a 2k display, the coordinates will be misplaced.
When the 2k display B is pulled down from the 2k display A, it will not cause coordinate misalignment.
