### ISSUE TITLE
编辑器以窗口模式运行,高度经常会超出屏幕范围很多

### ISSUE THREAD

**Issue by 1054114709** [cocos/cocos-engine#15042]
### Cocos Creator version

3.7.3

### System information

win10

### Issue description

有的时候还无法从上边拖动缩小编辑器
![image](https://github.com/cocos/cocos-engine/assets/56641124/78aaaa4b-39d8-4846-b9ff-93a4dceb381c)

### Steps to reproduce

以窗口模式运行,正常开发,几个软件来回切换,一会就会超出屏幕高度

**Comment by ChinaChenMingQuan** [comment]
你这个BUG我在3.6.1版本时遇到过，到现在都没解决我也是服了！可见COCOS官方都顾着赚钱去了...

**Comment by carlosyzy** [comment]
今天刚打开3.7.3 就出现了这个问题，拖那都没办法缩小，重启也不行，老问题了已经，

**Comment by 1054114709** [comment]
官方对这个问题选择视而不见

**Comment by VisualSJ** [comment]
sorry，这个问题我们已经找到了原因，在某些特殊情况下，拿到的窗口可用区域有一些问题，导致了我们在计算窗口大小的时候，出现了问题。
我们会在 3.8.1 版本中修复。

**Comment by VisualSJ** [comment]
> 今天刚打开3.7.3 就出现了这个问题，拖那都没办法缩小，重启也不行，老问题了已经，

可以点一下双击标题栏，然后再拖拽外框缩放回来

**Comment by wuzhiming** [comment]
已修复~
