### ISSUE TITLE
Memory leaks or How to release a Scene

### ISSUE THREAD

**Issue by DrMoriarty** [cocos/cocos-engine#1505]
Hello!
I have made a  [very simple cocos creator project](https://dl.dropboxusercontent.com/u/996824/builds/test-cocos-scenes.zip). Just four scenes which switches in a cyclic manner. Each scene has a huge background picture.

The switching code is also very simple:

```
cc.Class {
    extends: cc.Component

    properties: {
    }

    bntNext: (event, sceneName) ->
        #scene = cc.director._scene
        #scene.autoReleaseAssets = true
        cc.director.loadScene sceneName, 
            () ->
                cc.log sceneName, 'loaded'
            () ->
                cc.log 'current scene unloaded'
}
```

When I run the project (on iOS simulator or device) and switch between the scenes I have this memory usage graph:
![2017-02-17 11 40 41](https://cloud.githubusercontent.com/assets/1177068/23058448/131e97bc-f506-11e6-8803-8672e1bb018a.png)

As you can see the scenes was loaded on demand (only once) and have never been released. All four scenes resources remain in the memory.

When I uncomment these lines
```
        scene = cc.director._scene
        scene.autoReleaseAssets = true
```
I get a much more strange effect:
![2017-02-17 11 47 38](https://cloud.githubusercontent.com/assets/1177068/23058618/eddc55a6-f506-11e6-80f6-810409476846.png)
The scene doesn't release resources but every time it loaded them again and again.

I tried some magic with `cc.loader.releaseAll()` and `cc.textureCache.removeAllTextures()` but had no lucky at all.

So how can I release a scene with all it's resources?

**Comment by pandamicro** [comment]
Which version of creator are you using?

**Comment by DrMoriarty** [comment]
Cocos Creator v1.3.3 for MacOSX

**Comment by pandamicro** [comment]
@DrMoriarty Sorry there is indeed some issues with v1.3.3 native loader. The solution is:

1. Please try v1.4
2. Try not to release any resources in v1.3.3, then it won't reload again, so memory won't grow up dramatically

With v1.4, you can release resources with `cc.loader.release`, here is couple of examples described in the API:

```
// Release a texture which is no longer need
cc.loader.release(texture);
// Release all dependencies of a loaded prefab
var deps = cc.loader.getDependsRecursively('prefabs/sample');
cc.loader.release(deps);
// If there is no instance of this prefab in the scene, the prefab and its dependencies like textures, sprite frames, etc, will be freed up.
// If you have some other nodes share a texture in this prefab, you can skip it in two ways:
// 1. Forbid auto release a texture before release
cc.loader.setAutoRelease(texture2d, false);
// 2. Remove it from the dependencies array
var deps = cc.loader.getDependsRecursively('prefabs/sample');
var index = deps.indexOf(texture2d._uuid);
if (index !== -1)
    deps.splice(index, 1);
cc.loader.release(deps);
```

B.t.w, we still have some minor memory leak issue in v1.4, and we are investigating into it.

**Comment by pandamicro** [comment]
Another thing need to mention is that JSB memory deallocation is always delayed, because JS object can only be freed when the garbage collection(GC) is invoked, the timing of GC is controlled by Spidermonkey. You can also manually call GC with

`cc.sys.garbageCollect();`

Some objects may need various times of GC to be finally released

**Comment by DrMoriarty** [comment]
@pandamicro 
I've downloaded CocosCreator_v1.4.0_2017021001.dmg and modified my test project. Now I loaded and unloaded the big texture in the same scene:

```
cc.Class {
    extends: cc.Component

    properties: {
        loaded: 
            default: false
            visible: false
        texture: 
            default: null
            visible: false
    }

    checkResources: (event) ->
        if @loaded
            @unloadResources()
        else
            @loadResources()

    loadResources: () ->
        url = cc.url.raw 'resources/splash_4.png'
        cc.log 'Load', url
        cc.loader.load url, ((err, res) ->
            @texture = res
            @loaded = true
        ).bind(@)

    unloadResources: () ->
        cc.log 'Unload texture'
        cc.loader.release(@texture._id)
        @loaded = false
        cc.sys.garbageCollect();
}
```

When I tested the application on iOS device or simulator I have this memory usage graph:
![2017-02-22 13 23 15](https://cloud.githubusercontent.com/assets/1177068/23207511/92746a5a-f902-11e6-843a-9567f59cac02.png)

The first button click loads the texture (and allocates the memory) and next button clicks produces no equal memory release.

I also checked the first test case and it behaviour was exactly the same. Without `autoReleaseAssets = true` all scenes was loaded in memory once and never released. With `autoReleaseAssets = true` all scenes loads it's resources every time when I switched the scene.

**Comment by DrMoriarty** [comment]
@pandamicro also I noticed that during the second test `Ref::release()` was never called for `cocos2d::Texture2D` object.

Ref::retain() for Texture2D was called twice: from TextureCache::addImageAsyncCallBack function and from jsb_ref_get_or_create_jsobject function.

**Comment by DrMoriarty** [comment]
@pandamicro Finally I noticed that I have no ideas what is the right way to release a texture. None of these are helped: cc.loader.release(@texture), cc.loader.release(@texture._id), cc.loader.release(@texture._uuid), cc.loader.releaseRes(@texture.url, cc.Texture2D), cc.loader.releaseRes(cc.url.raw('resources/splash_4.png'), cc.Texture2D)

Some of them does nothing, another part raises an error. What is the right way to release a texture (which is loaded by cc.loader.load(url)) ?

**Comment by DrMoriarty** [comment]
@pandamicro 
May be I was inattentive when tested first time cocos creator 1.4. Now I checked the first test case with additional `cc.sys.garbageCollect();` when scene is released. And it works pretty well!
![2017-02-22 15 29 28](https://cloud.githubusercontent.com/assets/1177068/23211624/0fffd5fc-f914-11e6-95ad-22293555f041.png)

The worked code is:
```
cc.Class {
    extends: cc.Component

    properties: {
    }

    bntNext: (event, sceneName) ->
        cc.director._scene.autoReleaseAssets = true
        cc.director.loadScene sceneName, 
            () ->
                cc.log sceneName, 'loaded'
            () ->
                cc.log 'current scene unloaded'
                cc.sys.garbageCollect();
}

```

**Comment by pandamicro** [comment]
The thing is that GC can only release objects that have no reference, in Web platform it's pretty straight forward and effective. But with JSB it's much complicated, in the new memory model introduced after v1.3, most C++ object life cycle was controlled by JS object, but we still have some C++ to JS references, for example, JSCallbackWrapper, JSFunctionWrapper, JSScheduleWrapper, they make GC more complicated. Sometimes you will need to invoke GC more than once to release all useless objects.

**Comment by pandamicro** [comment]
> Finally I noticed that I have no ideas what is the right way to release a texture. None of these are helped: cc.loader.release(@texture), cc.loader.release(@texture._id), cc.loader.release(@texture._uuid), cc.loader.releaseRes(@texture.url, cc.Texture2D), cc.loader.releaseRes(cc.url.raw('resources/splash_4.png'), cc.Texture2D)

Often you can't release the texture directly, even if you can remove it from the loader's cache, but there will always be a SpriteFrame hold its reference, then Texture2D's JS object is always alive.

For example, if you know your texture's sprite frame was only used by a Sprite, then remove the Sprite from the scene, or set its `spriteFrame` property to null. And release the SpriteFrame from the Loader recursively : 

```
var spriteFrameToRelease = sprite.spriteFrame;
sprite.spriteFrame = null;
// Release all dependencies of a loaded sprite frame
var deps = cc.loader.getDependsRecursively(spriteFrameToRelease);
cc.loader.release(deps);
```

This way can effectively remove all reference of thie Texture2D, if the `spriteFrameToRelease` wasn't referenced anywhere else
