### ISSUE TITLE
Support to configure 'resizeableActivity' in build panel

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#15057]
Reference: https://developer.android.com/guide/topics/large-screens/multi-window-support#resizeableActivity

In some situations,  game activity doesn't need to be resized. But currently, we didn't assign a `resizeableActivity` in the AndroidManifest.xml of android template. Therefore, it will use the default value android provides. 

Developer could modify AndroidManifest.xml to add `resizeableActivity` but it will be more convenient if we add a `checkbox` in the `build panel`.

**Comment by minggo** [comment]
Should also have checkbox for `maxAspectRatio` and `minAspectRation`. And please upload the `setting interface` here.

**Comment by PatriceJiang** [comment]
![image](https://github.com/cocos/cocos-engine/assets/40414978/1f678ea5-d118-46a9-8d0e-f9c427f3b1b8)

**Comment by PatriceJiang** [comment]
![image](https://github.com/cocos/cocos-engine/assets/40414978/a9d9c801-5476-4ea7-b04c-1c1570f54fac)
Interaction Description:

- When the resizeableActivity option is checked, the Max Aspect Ratio option is gray out.
- The Max Aspect Ratio can be selected from a dropdown list of presets, or it can be manually entered.
- The input format can be a decimal number or in the format of M:N. If the input is in the format of M:N, it is rendered as 1.77 (16:9).
