### ISSUE TITLE
Inaccurate setting of values in the Property Editor panel

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#15163]
### Cocos Creator version

3.7.3

### System information

window 10

### Issue description

https://forum.cocos.org/t/topic/149382
![image](https://github.com/cocos/cocos-engine/assets/40415168/cda45768-4304-4ecb-9f01-26bec077cd6c)

When you have finished typing, quickly click on the margin of the panel.
position 输入完，快速点击面板空白处(概率性复现)

### Steps to reproduce

.

**Comment by arsen2010** [comment]
We can not recurrence this bug in v3.7.3 or v3.8.0. 
Close this issue.
