### ISSUE TITLE
Light probe works on CocosCreator editor, but errors in Web preview

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#15164]
### Cocos Creator version

3.7.2 ~ 3.8.0 052401

### System information

MacOS 12.5.1

### Issue description

![图片](https://github.com/cocos/cocos-engine/assets/35944775/6fe55911-0f3a-404d-91e9-274aca767a66)

### Steps to reproduce

-

### Minimal reproduction project

https://github.com/cocos/cocos-test-projects/blob/v3.7/assets/cases/light-probe/sponza.scene

**Comment by stanleyljl** [comment]
It's ok on latest v3.8. Maybe the light probe feature is cut out.
