### ISSUE TITLE
label cache mode char unsupport emoji

### ISSUE THREAD

**Issue by ankye** [cocos/cocos-engine#15192]
### Cocos Creator version

3.73

### System information

mac os and build web mobile

### Issue description

label select cache mode bitmap is support emoji and select char is unsupport
text: 王🐻爷

![image](https://github.com/cocos/cocos-engine/assets/5154427/71549e99-32f8-405f-ac1c-126aab230d5e)

### Steps to reproduce

![image](https://github.com/cocos/cocos-engine/assets/5154427/7ce32087-da2d-4225-931c-b0748ab914e4)

**Comment by ankye** [comment]
![image](https://github.com/cocos/cocos-engine/assets/5154427/6bca6da5-4b88-454a-ba4f-b4b573a8dd74)
The _safeSubstring function is also problematic when dealing with Composite emoji
test case: 🐻👨‍👩‍👧‍👦一家人
![image](https://github.com/cocos/cocos-engine/assets/5154427/bc4edb6d-45a9-4eb5-a33e-33c1614c5368)

**Comment by myonlylonely** [comment]
Any news about this issue?
