### ISSUE TITLE
Memory leak on resize sprite with tiled mode

### ISSUE THREAD

**Issue by May2nd** [cocos/cocos-engine#15211]
### Cocos Creator version

3.7.x, v3.8.0

### System information

MacOS

### Issue description

Memory leak on resize sprite with tiled mode.
Not occurs on others mode.

![Screenshot 2023-05-29 at 11 18 18](https://github.com/cocos/cocos-engine/assets/122350047/80d463f1-31e4-4d0c-b005-09b3cc52058a)

Memory increase > 20MB ~10min on sample project

### Steps to reproduce

<img width="561" alt="Screenshot 2023-05-29 at 11 12 56" src="https://github.com/cocos/cocos-engine/assets/122350047/3baa8435-efaa-490f-b002-3764ce480be0">

Create a sprite with tiled mode, then keep resize it on update(dt)

![Screenshot 2023-05-29 at 11 09 07](https://github.com/cocos/cocos-engine/assets/122350047/6b3dc844-c374-4fef-abda-f8eeabe2265a)
tempRenderData in tiled assembler will increase each time sprite update size.

### Minimal reproduction project

[NewProject370Physics.zip](https://github.com/cocos/cocos-engine/files/11588369/NewProject370Physics.zip)

**Comment by May2nd** [comment]
Fixed here:
https://github.com/cocos/cocos-engine/pull/15212

**Comment by pandamicro** [comment]
Thank you for reporting and the fix !
