### ISSUE TITLE
Adding A Render Target to Camera Causes camera.screenPointToRay to Generate Wrong Ray

### ISSUE THREAD

**Issue by lealzhan** [cocos/cocos-engine#15241]
https://discuss.cocos2d-x.org/t/shooting-raycast-through-canvas/58819
[raycast-demo.zip](https://github.com/cocos/cocos-engine/files/11609222/raycast-demo.zip)
![image](https://github.com/cocos/cocos-engine/assets/9999378/1557aa85-b2c8-4e8d-a94f-6e1d0d311851)
![image](https://github.com/cocos/cocos-engine/assets/9999378/c5a85365-aae8-4098-847e-e73566b097e2)
![image](https://github.com/cocos/cocos-engine/assets/9999378/6404196d-c99a-4751-9f6f-c7cf718905c4)
![image](https://github.com/cocos/cocos-engine/assets/9999378/b26cd9bd-91b1-4ce5-b568-ce614b943e6a)

**Comment by mvrlin** [comment]
The solution that I found, is to create a second camera, with nothing visibility and use that for raycast.
