### ISSUE TITLE
1.4热更新模块有问题，每次启动会清掉storagepath下的数据。

### ISSUE THREAD

**Issue by 845629143** [cocos/cocos-engine#1524]
1.4热更新模块有问题，每次启动会清掉storagepath下的数据。

1、storagepath和storagepath_temp里面都没有任何东西。
![image](https://cloud.githubusercontent.com/assets/5147234/23445427/30794ee6-fe76-11e6-8946-98c6d1b3e492.png)
2、点击检查更新，在storagepath_temp路径下会出现version文件。
![image](https://cloud.githubusercontent.com/assets/5147234/23445447/5eb4c4fc-fe76-11e6-85ef-bf7e9fee819d.png)
3、点击更新，storagepath_temp路径下的内容会被转移到sotargepath路径下。
![image](https://cloud.githubusercontent.com/assets/5147234/23445457/7b218ea4-fe76-11e6-8590-1efda1c08686.png)

现在说明整套更新流程是OK的，但是。当我重新允许应用的时候，整体被恢复了。
目录被重写生成，数据清空。 重复流程1、2、3。

android环境测试也是一样

**Comment by xianyinchen** [comment]
你好，如果每次重启，都可以检测到更新，一般是因为 main.js 文件并没有写入热更新搜索路径的代码或者全局搜索路径被覆盖了，需要确认热更新的扩展插件存在，且 main.js  包含热更新搜索路径设置代码，详见文档。

https://docs.cocos.com/creator/1.9/manual/zh/advanced-topics/assets-manager.html#%E9%87%8D%E5%90%AF%E7%9A%84%E5%BF%85%E8%A6%81%E6%80%A7

由于问题久远，如果有新的问题，请创建新的issue告知我们。
