### ISSUE TITLE
sorting component Disable is invalid

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#15302]
### Cocos Creator version

3.7.3，3.8-0601

### System information

window10, chrome

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/40415168/ab216d74-998a-47bd-ad90-0720c73c3ea8)

### Steps to reproduce

demo:
[NewProject_15.zip](https://github.com/cocos/cocos-engine/files/11633718/NewProject_15.zip)

**Comment by minggo** [comment]
I tested in v3.8.3, and it works. I tested as:
- change cc.Sorting of Cube to
  - Sorting Layer: default
  - Sorting Order 2
- change cc.Sorting of Cone to
  - Sorting Layer: default
  - Sorting Order 1
  
Then Cone is hidden by Cube.

<img width="390" alt="企业微信截图_9420b8e1-28aa-4bca-bfc5-729936cf4141" src="https://github.com/cocos/cocos-engine/assets/488203/3a7f8227-83d1-49b3-8942-7e3fff56f7f3">
