### ISSUE TITLE
How to use ClippingRectangleNode in cocos creator

### ISSUE THREAD

**Issue by DrMoriarty** [cocos/cocos-engine#1542]
Hello!
In my game I have a very large game map. It is a ScrollView with content about 13 x device heights. The content node places inside of a Mask node with RECT clipping mode. I have noticed that my game map has very low fps, about 30.

I tried to check another clipping algorithm and hacked ClippingNode (it always uses stencil for clipping even for simple rect). I simple copied the code of ClippingRectangleNode (it makes clipping with gl scissors which much more faster then stencil) into it. And then my game map shows me about 50 fps! But as far as I know there is no bindings in javascript for ClippingRectangleNode. And so I have no legal way to use it in my cocos creator scene.

So the main question is: how can I use gl scissor clipping rect in cocos creator scene (if the stencil clipping node is very slow for me)?

**Comment by zhefengzhang** [comment]
Can't use gl.scissor directly in the component，You need to customize the engine to use：
https://docs.cocos.com/creator/manual/en/advanced-topics/engine-customization.html#13-%E5%AE%89%E8%A3%85%E7%BC%96%E8%AF%91%E4%BE%9D%E8%B5%96
https://github.com/cocos-creator/engine/tree/v2.4.5/cocos2d/renderer/gfx
