### ISSUE TITLE
我的ndk版本太高了？APP_ALLOW_MISSING_DEPS=true

### ISSUE THREAD

**Issue by lazeyliu** [cocos/cocos-engine#1546]
是我的ndk 版本太高了么？
/usr/local/Cellar/android-ndk/r14/build/core/build-binary.mk:687: 
Android NDK: Module cocos2djs_shared depends on undefined modules: cocos2d_js_android_static log    
/usr/local/Cellar/android-ndk/r14/build/core/build-binary.mk:700:
 *** Android NDK: Aborting (**set APP_ALLOW_MISSING_DEPS=true** to allow missing dependencies)    .  Stop.

设置完以后 出现新的错误

/Applications/CocosCreator.app/Contents/Resources/cocos2d-x/cocos/prebuilt-mk/../../
prebuilt/android/armeabi-v7a/libcocos2dxinternal.a(CCConsole.o):function cocos2d::Console::listenOnTCP(int): error: **undefined reference to 'bzero'**
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libcocos2djs.so] Error 1
make: Leaving directory `/Users/liuzeyuan/rjmj_bak/build/jsb-binary/frameworks/runtime-src/proj.android'
Error running command, return code: 2.

**Comment by ghost** [comment]
是的，太高了。
https://github.com/cocos2d/cocos2d-x/issues/17443

**Comment by xianyinchen** [comment]
该问题已修复，请参考下面PR
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/283
