### ISSUE TITLE
Issue of SIBLING_ORDER_CHANGED event.

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#15479]
Detail information can refer to the forum topic: https://forum.cocos.org/t/topic/148397 .

The issue is that:
- parent node instead of children that whose sibling index are changed emit the event

After fixing this issue, may have more nodes emit SIBLING_ORDER_CHANGED event, so should do performance test.

**Comment by jareguo** [comment]
By placing this file in the project migrated from old version:
```js
/*
 * This script is automatically generated by Cocos Creator and is only used for projects compatible with the v2.1.0 ～ 2.2.1 version.
 * You do not need to manually add this script in any other project.
 * If you don't use cc.Toggle in your project, you can delete this script directly.
 * If your project is hosted in VCS such as git, submit this script together.
 *
 * 此脚本由 Cocos Creator 自动生成，仅用于兼容 v2.1.0 ~ 2.2.1 版本的工程，
 * 你无需在任何其它项目中手动添加此脚本。
 * 如果你的项目中没用到 Toggle，可直接删除该脚本。
 * 如果你的项目有托管于 git 等版本库，请将此脚本一并上传。
 */

if (cc.Toggle) {
    // Whether to trigger 'toggle' and 'checkEvents' events when modifying 'toggle.isChecked' in the code
    // 在代码中修改 'toggle.isChecked' 时是否触发 'toggle' 与 'checkEvents' 事件
    cc.Toggle._triggerEventInScript_isChecked = true;
}
```

2.x can maintain compatibility when engine behavior changes.

**Comment by minggo** [comment]
@jareguo though i don't know how to keep compatibility by using Toggle. i will take a look of it.

**Comment by minggo** [comment]
After discussion with @jareguo , we think it is just a naming issue. Should just fix the event name to make it more clear. There is not need to trigger sibling change event for all nodes that their sibling index are changed.
