### ISSUE TITLE
Widget on canvas: can not set fullscreen canvas properly

### ISSUE THREAD

**Issue by DrMoriarty** [cocos/cocos-engine#1549]
Hello! I have about 12 scenes in my project, but two of them behaves in very strange way. I set widget for every canvas in every scene and set in to stretch to fullscreen (the main reason is android screens with many screen aspect ratios). The most of my scenes allows me to do that:

![2017-03-14 8 20 59](https://cloud.githubusercontent.com/assets/1177068/23886871/3dc9030c-088f-11e7-8066-d418ea5752fb.png)

But two of them (as I mentioned before) doesn't allow me to set all margins to zero:

![2017-03-14 8 15 30](https://cloud.githubusercontent.com/assets/1177068/23886890/62dbcb8e-088f-11e7-94a4-8b707f71f2d6.png)

When I try to set top margin to 0px it immediately changes top and bottom margin. The left and right margins behaves the same way. For example, when I enable widget it sets left 210px and right -210px (the canvas width is 420px). When I set left to zero it changes it to left=105px and right=-315px. When I one more time set left to zero it changes it to left=52.5px and right=-367.5px.

I always set them in order to left-right = 420px and bottom-top = 747px (the height of my scene).

I don't know why some my scenes allows me to set widget and some do not.

**Comment by DrMoriarty** [comment]
I checked scene fire file and found the widget class description. The right widget is:

```
  {
    "__type__": "cc.Widget",
    "_name": "",
    "_objFlags": 0,
    "node": {
      "__id__": 2
    },
    "_enabled": true,
    "isAlignOnce": true,
    "_target": null,
    "_alignFlags": 45,
    "_left": 0,
    "_right": 0,
    "_top": 0,
    "_bottom": 0,
    "_verticalCenter": 0,
    "_horizontalCenter": 0,
    "_isAbsLeft": true,
    "_isAbsRight": true,
    "_isAbsTop": true,
    "_isAbsBottom": true,
    "_isAbsHorizontalCenter": true,
    "_isAbsVerticalCenter": true,
    "_originalWidth": 420,
    "_originalHeight": 747
  }
```

The wrong widget is:

```
  {
    "__type__": "cc.Widget",
    "_name": "",
    "_objFlags": 0,
    "node": {
      "__id__": 2
    },
    "_enabled": true,
    "isAlignOnce": true,
    "_target": null,
    "_alignFlags": 45,
    "_left": 210,
    "_right": -210,
    "_top": -373.5,
    "_bottom": 373.5,
    "_verticalCenter": 373.5,
    "_horizontalCenter": 210,
    "_isAbsLeft": true,
    "_isAbsRight": true,
    "_isAbsTop": true,
    "_isAbsBottom": true,
    "_isAbsHorizontalCenter": true,
    "_isAbsVerticalCenter": true,
    "_originalWidth": 420,
    "_originalHeight": 747
  }
```

If I change margins in file and start game it looks very good. But if I open the scene in cocos creator and save it then it again makes widget with wrong margins (which leads to move bottom left corner of canvas to the center of device screen)

**Comment by jareguo** [comment]
Sorry you should not attach Widget to Canvas node because canvas size is immutable.
If you want to fullscreen, just create a new root node besides Canvas and attach this widget to it.

**Comment by betovidal** [comment]
It was my approach too. Shouldn't there be a restriction so the user can't attach a widget component to the canvas ?

Assigning a widget component to the canvas worked only for desktop mobile, however it's broken in Android and the chrome mobile emulator.

**Comment by jareguo** [comment]
Indeed, we should add a restriction so users can't attach a widget to canvas.

**Comment by OnlyKoei** [comment]
If there are no other problems, this issue will be closed first. If there are still problems, you can continue to contact us and we will follow up.

**Comment by idchlife** [comment]
Right now Cocos Creator 3.8.1 attaches cc.Widget to Canvas component automatically on creation. Is this normal?
