### ISSUE TITLE
dragonbones/spine crashes on native platform

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#15524]
### Cocos Creator version

3.6.3，3.7.3

### System information

android

### Issue description

![企业微信截图_16849097987733](https://github.com/cocos/cocos-engine/assets/40415168/f3b0528a-ba44-40ba-9283-2030f419b83d)

![企业微信截图_16876789001913](https://github.com/cocos/cocos-engine/assets/40415168/319546a1-ffb4-4659-a398-402641f2be01)

### Steps to reproduce

Private project, not convenient to give demo directly, contact me to send private.
私人项目，不方便直接提供演示，请联系我发送私人项目。

**Comment by minggo** [comment]
I think it is fixed in v3.8.2. Please reopen it if still exists.
