### ISSUE TITLE
EventMouse object gets wrong button id on native Mac platform

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#15528]
feadback from https://discuss.cocos2d-x.org/t/wrong-button-id-when-move-mouse/58984

**Comment by novain1102** [comment]
![企业微信截图_10f67d72-e160-4b22-ba26-3b6a2b527999](https://github.com/cocos/cocos-engine/assets/18634782/4f797f03-52db-418b-b33c-9ef4e3ded545)
![企业微信截图_33b3d62f-44f8-4aba-a85a-2cb1fc00c56e](https://github.com/cocos/cocos-engine/assets/18634782/4775fa02-ece4-4748-91b4-c5a7b2e191d3)
Test on 3.7.3 & 3.8.0, result is correct.

**Comment by novain1102** [comment]
Find different implement between native and web. And jsb.MouseEvent do not have member variable `buttons` like web's MouseEvent

![image](https://github.com/cocos/cocos-engine/assets/18634782/3a226aa8-537e-4cbd-98ce-55d35ca2336f)

**Comment by novain1102** [comment]
Need @qiuguohua do further research whether to implement `buttons` variable in jsb.MouseEvent to support multi-response
