### ISSUE TITLE
cocos cc.sys.language竟然没有繁体

### ISSUE THREAD

**Issue by yangzhu6263736** [cocos/cocos-engine#1552]
快加上吧。。你们别乱爱国了。一个中国也可以有两种语言的。

**Comment by jareguo** [comment]
参考 PR
https://github.com/cocos-creator/engine/pull/1320/files
https://github.com/cocos-creator/cocos2d-x-lite/pull/418/files

**Comment by KAndQ** [comment]
> 参考 PR
> https://github.com/cocos-creator/engine/pull/1320/files
> https://github.com/cocos-creator/cocos2d-x-lite/pull/418/files

请问上面两个 PR 链接的意思是自己参考着处理吗?

**Comment by jareguo** [comment]
不是，我是留着给我们内部人员参考的

**Comment by jareguo** [comment]
论坛讨论：https://forum.cocos.com/t/cc-sys-language/47608

**Comment by jareguo** [comment]
已经加入，谢谢反馈，将在 2.0.7 提供

**Comment by zyqq** [comment]
2.4.5 打包安卓，手机系统语言设置繁体返回的cc.sys.language是en，languageCode是en-us
