### ISSUE TITLE
Pipeline State data isn't cached when changing technique

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#15531]
### Cocos Creator version

3.7 & 3.8 tested, it could also exist in older versions

### System information

Windows & Mac

### Issue description

Reported https://forum.cocos.org/t/topic/149932/272

Using two transparent material with different priority, doesn't affect the rendering order in editor, but it works correctly in preview or build.

### Steps to reproduce

Use the reproduction project to see the difference between editor scene view and preview

### Minimal reproduction project

https://forum.cocos.org/uploads/short-url/cbiPnwKguYrgU9QROHUM5Cgtc00.zip

**Comment by pandamicro** [comment]
@star-e please help assign

**Comment by jk20012001** [comment]
![image](https://github.com/cocos/cocos-engine/assets/15099632/de679551-0d90-4251-8336-0d57683f82de)
transparency mode, priority setting working correctly with editor and runtime

**Comment by pandamicro** [comment]
After test, it was because user changed technique of the material, and the priority in pipeline state of Pass0 was reset to 128, so it's an editor cache issue
