### ISSUE TITLE
After version 3.7.0, 'contact.disabled' is no longer effective. Even in the current version 3.8.0, I still cannot use it. I have noticed that there have been solutions submitted, but why is it still not working?

### ISSUE THREAD

**Issue by xyhallo** [cocos/cocos-engine#15530]
### Cocos Creator version

3.8.0

### System information

windows 11

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/44963132/28b7e97c-02b2-4264-a66c-baef7d38ebda)
无效

### Steps to reproduce

import { Collider2D, Component, Contact2DType, IPhysics2DContact, Vec2, _decorator, v2 } from "cc";
const { ccclass, property } = _decorator;

@ccclass
export default class jumpBreach extends Component {
  onLoad() {
    let collider = this.getComponent(Collider2D);
    if (collider) {
      // 只在两个碰撞体开始接触时被调用一次
      collider.on(Contact2DType.BEGIN_CONTACT, this.onBeginContact, this);
    }
  }

  // 碰撞检测
  onBeginContact(selfCollider: Collider2D, otherCollider: Collider2D, contact: IPhysics2DContact) {
    contact.disabled = true;
  }
}

这段代码挂载到组件上，和其他碰撞依然无法穿透

**Comment by minggo** [comment]
Please use english in future. Thanks.
