### ISSUE TITLE
截图问题

### ISSUE THREAD

**Issue by rongmingLi** [cocos/cocos-engine#1554]
环境：native
问题描述：用以下代码实现全屏截图，当节点中存在渲染组件“Mask”时。会被导致截图不完整
const shotRender= new cc.RenderTexture(winSize.width, winSize.height, 2);
       shotRender.begin();
        cc.director.getRunningScene().visit();
        shotRender.end();
==================原图=================
![image](https://cloud.githubusercontent.com/assets/24645328/23983727/a8cb6ba0-0a50-11e7-92a5-cec2cf271f10.png)
==================出问题的截图==================
![image](https://cloud.githubusercontent.com/assets/24645328/23984064/6a968d54-0a52-11e7-8e98-78893b445b65.png)

**Comment by xianyinchen** [comment]
该问题在 2.4.4 测试已经解决，如果有新的问题，请提供下creator版本信息，并创建issue告知我们。
