### ISSUE TITLE
fix type issue in getComponent when we pass abstract component class

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#15593]
relative feadback https://forum.cocos.org/t/topic/142656

there are two problem in this issue:
- the build-declaration workflow haven't supported abstract class parameters
- we only supported `node.getComponent()` for abstract class, but the `component.getComponent()` is not

**Comment by cad-icandy** [comment]
what is the progress of this?

**Comment by minggo** [comment]
Duplicate with https://github.com/cocos/cocos-engine/issues/16594
