### ISSUE TITLE
"Fix alpha transparency artifacts" does not always work for moving sprites

### ISSUE THREAD

**Issue by mrtzd** [cocos/cocos-engine#15599]
### Cocos Creator version

3.7.3

### System information

Windows 10 Editor

### Issue description

I have a couple of sprites in my game that are semi-transparent and they are moving through a scene. The problem is that sometimes there are flickering lines near the border of these sprites when they are moving (just a looping animation that moves that back and forth). This happens no matter if this option("Fix alpha transparency artifacts") is turned on or not. And unfortunately does not always happen and it seems to happen randomly.

Here's how it appears inside the game while running in a browser:

https://github.com/cocos/cocos-engine/assets/82378750/f74b1bbf-8190-4bac-8aee-4945bfc21861

Is this a known issue? Are there any temporary measures that I can use to avoid this? Thanks

### Steps to reproduce

Described above. Move some transparent sprites in a game with bright background to see the issue.

**Comment by mrtzd** [comment]
After some testing it seems like this issue only happens when the filter mode is set to "Bilinear". So changing the filter mode to anything other than Bilinear solves this problem. I think it would be nice to add a notice for this in the docs.

**Comment by jareguo** [comment]
![image](https://github.com/cocos/cocos-engine/assets/1503156/9e0707d1-4d52-4d66-a049-f0806720ceaa)
There may be some issues with GPU UV precision on certain platforms, please try switching the wrap mode to see if it resolves the issue. If the problem persists, kindly reopen this issue.
