### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#15595]
A typical 3D + physics project
![企业微信截图_12452603-af67-40d4-87ac-316e7cdae506](https://github.com/cocos/cocos-engine/assets/632460/9919e5a8-e96c-4a57-be90-d33d9d9ee65a)

## Big modules
- [ ] Render pipeline @star-e 
- [ ] Marionette @shrinktofit 
- [ ] Basic 3D @minggo 
- [ ] Physics System (bullet or physx) @lealzhan 
- [ ] Basic 2D @holycanvas 

## Other important tasks
- [ ] Remove or reduce effects used by builtin-res-manager @jk20012001 
- [ ] Make all wasm lib pack to sub-packages: spine, bullet, physx @PPpro 

Target: Reduce release package to smaller than 4MB with previous setup

**Comment by pandamicro** [comment]
Related: https://github.com/cocos/cocos-engine/issues/10354

**Comment by iwae** [comment]
## CN

1. Bullet 物理引擎或者Spine引擎的WASM包可以放子包，可以选择性加载
2. 部分模块可以使用gzip压缩延迟加载（如材质）
3. 支持材质剔除，部分游戏可能用自己的光照模型（比如blinn-phong），支持剔除standard材质，只保留基本的global ubo fog planarshadow这些chunk
4. 部分组件继续细分可以剔除，比如slider，editbox，graphics ，controller，灯光（不包含基础平行光）等等（最好提供大的分类）
5. 粒子支持 CPU粒子或 GPU粒子 的分别剔除
6. 动画图目前太大，功能太多了，能否做基础动画图，其他镶嵌，变种的可以剔除


## EN

1. The WASM files for Bullet physics engine or Spine engine can be placed in  subpackages.
2. Some modules can use gzip compression for deferred loading (such as materials).
3. Supports material culling, some games may use their own lighting models (such as Blinn-Phong), support for culling standard materials, and only retain basic global UBO chunks such as fog, planar shadow, shadow map etc. 
4. Some components can be further subdivided and culled, such as sliders, edit boxes, graphics, controllers, lights (excluding basic directional lights), and so on (it is best to provide large categories). 
5. Particle supports culling CPU particles and GPU particles separately. 
6. The animation graph is currently too large and has too many features, can we create a basic animation atlas and cull other embedded and variant animations?

**Comment by PPpro** [comment]
done here https://github.com/cocos/cocos-engine/issues/15493

we don't support phsx wasm subpackage, because it's too big

**Comment by Ronsku** [comment]
Update from CC **3.8.0**, vs latest CC2 version **2.4.11**.

Very Stripped 2D Build in 3.8.0:
![image](https://github.com/cocos/cocos-engine/assets/7983358/555e5cb4-770d-4d43-992f-ce90946c7a75)

I think things were moved out from the bundle, but the bundle is still relatively the same size or slightly bigger?
Compared to version 3.7.2:
**3.7.2:** CC bundle is **1,806 KB**
**3.8.0:** CC bundle is **1,825 KB** while it looks like Spine has even been stripped out and adds an additional 701 KB?!
![image](https://github.com/cocos/cocos-engine/assets/7983358/104433c3-42c1-4d1d-aa7b-8a17f5274b37)

**2.4.11** while CC2 stays at **991 KB**

Here are the statistics of just the CC bundle between CC2 and CC3, without taking into consideration the 701 KB Spine file.

![image](https://github.com/cocos/cocos-engine/assets/7983358/f99424b3-82e4-48a9-b570-6ae8a181636d)

I'm getting really worried getting stuck in legacy CC2 forever or having to look for alternatives, which I really wouldn't like to do 😨?!

**Comment by jk20012001** [comment]
FXAA with default pipeline
https://github.com/cocos/cocos-engine/issues/16075

**Comment by minggo** [comment]
We are keeping reducing package size. Will do it in many issues, so close this one.

**Comment by Ronsku** [comment]
> We are keeping reducing package size. Will do it in many issues, so close this one.

Okay, which are the different issues linked to reducing the package size?

I would love to upgrade our CC2 projects to CC3, but size and initial load times are too high for making faster loading games on the web, so this is critical for making CC3 work.

**Comment by minggo** [comment]
Indeed, there can not have an issue to collect all PR to reduce package size.

**Comment by Ronsku** [comment]
> Indeed, there can not have an issue to collect all PR to reduce package size.

Which new issues have been created to replace this one? So that I can follow the progress of them.

**Comment by iwae** [comment]
> > Indeed, there can not have an issue to collect all PR to reduce package size.
> 
> Which new issues have been created to replace this one? So that I can follow the progress of them.

We have collected a lot feedback from developers, you can replay in this issue
