### ISSUE TITLE
Saving script while editing animation event will trigger refresh that causes user input lost

### ISSUE THREAD

**Issue by AndyYuTian** [cocos/cocos-engine#15608]
### Cocos Creator version

3.8.0

### System information

win

### Issue description

Saving script while editing animation event will trigger refresh that causes user input lost.

动画编辑器编辑设置时间时，此时保存脚本会导致界面刷新，刷新导致用户正在编辑的界面丢失，会还原的上一次保存的状态。

操作流程：先编辑事件不保存，然后修改脚本再回到编辑器，就会刷新还原到之前.

### Steps to reproduce

1. In animation editor, create an animation event and edit
2. save script
3. user input on events are lost

**Comment by arsen2010** [comment]
It has been fixed in v3.8.1
