### ISSUE TITLE
physX physical system configuration does not take effect

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#15610]
### Cocos Creator version

3.7.2

### System information

window 10

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/40415168/5e2ec9fe-fd71-403e-8f9b-255ab43fc7d2)

![image](https://github.com/cocos/cocos-engine/assets/40415168/189c5ff0-e6e1-46bc-94ea-c47442a0886d)

Rigid body auto-dormancy is not based on the set value.
(bullet and cannon are normal)

### Steps to reproduce

.

**Comment by lealzhan** [comment]
Two problems:
- Unlike bullet and cannon, When using physx, PhysicsSystem.instance.sleepThreshold is not assigned to rigid body during its initialization by default.
- sleepTheadhold in bullet and cannon is velocity, on the other hand, it's mass-normalized kinematic energy in physx. We haven't dealt with this difference now.

https://forum.unity.com/threads/how-to-calculate-a-rigidbodys-mass-normalized-energy-for-sleepthreshold.311941/

**Comment by lealzhan** [comment]
![physx sleep](https://github.com/cocos/cocos-engine/assets/9999378/51470630-178a-4a20-ac73-4a2871a60973)
