### ISSUE TITLE
Discussion: deprecate some duplicate functions in Node

### ISSUE THREAD

**Issue by minggo** [cocos/cocos-engine#15729]
There are duplicate functions in Node. They have the same logic, but with different function names, one use attribute getter/setter, one use API. We should deprecate one version. We can discuss keep which version.

## getParent & parent
```typescript
public getParent (): Node | null {
        return this._parent;
}

@editable
get parent (): Node | null {
        return this._parent;
    }
```
I prefer to keep attribute version, or how to implement `@editable`?

## getSiblingIndex & siblingIndex
```typescript
public get siblingIndex (): number { return this._siblingIndex; }

public getSiblingIndex (): number {
        return this._siblingIndex;
}
```
getter is `engine internal`, so I prefer to remove getter. But only keep setter is strange. 

## getPosition & position
```typescript
public get position (): Readonly<Vec3> {
        return this._lpos;
}

 public getPosition (out?: Vec3): Vec3 {
        if (out) {
            return Vec3.set(out, this._lpos.x, this._lpos.y, this._lpos.z);
        }
        return Vec3.copy(new Vec3(), this._lpos);
}

// As setter invokes setPosition(), so just keep setPosition() is enough.
public set position (val: Readonly<Vec3>) {
        this.setPosition(val as Vec3);
}
```
C++ version doesn't have similar implementation of ` public getPosition (out?: Vec3): Vec3`.

Ok, there are some other functions have similar problem. This issue is to discuss how to handle it. There are some options:
- keep both style: attribute getter/setter and getXXX/setXXX
- use attribute getter/setter only if possible, and deprecate getXXX/setXXX
- use getXXX/setXXX only if possible, and deprecate attribute getter/setter

**Comment by shrinktofit** [comment]
> use attribute getter/setter only if possible, and deprecate getXXX/setXXX

I agree with this. Accessors are important and widely used mech. For such style of problem, JS is not required to be align its style with C++.

**Comment by dumganhar** [comment]
The design of 
```ts
public getPosition (out?: Vec3): Vec3 {
```
is to reuse the `out` parameter to avoid gc and its returned value is a copied value of current this._lpos, but `get position()`  returns the reference of `this._lpos;`.

So the behaviors of `.position` & `.getPosition(out)` are difference.

**Comment by minggo** [comment]
@dumganhar the usage can use the getter and set Vec3 outside. As the getter returns a readonly reference.

**Comment by jareguo** [comment]
> getter is `engine internal`, so I prefer to remove getter. But only keep setter is strange.

If it can only be set, it is recommended to use a method uniformly.

> // As setter invokes setPosition(), so just keep setPosition() is enough.

The position getter is used for the Animation editor and Inspector. Each value that needs to be set in the editor should ideally have a getter.
