### ISSUE TITLE
Node with 2D Collider is not sync when it positionned before changing the parent node

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#15805]
### Cocos Creator version

3.7.3

### System information

Windows 11

### Issue description

When a prefab is instanciated, if the parent is set before the position of a 2D collider, the collider doesn't move after the instanciation of the prefab. Box2D physic engine.

![image](https://github.com/cocos/cocos-engine/assets/758680/3d1643fe-aa3b-4fdf-8d37-2dcd2b462268)

### Steps to reproduce

```
        const sun: Node = instantiate(this.sunPrefab);
        // Random position
        const x = Math.random() * 100;
        const y = Math.random() * 100;
        sun.parent = find("Canvas");
        sun.position = new Vec3(x, y, 0);
```

**Comment by joshi-cse-4000** [comment]
Yes same issue happening with me. The collider doesn't move while i drag and drop any workaround for this ?

**Comment by minggo** [comment]
@BenoitFreslon could you please provide a demo? What's `sunPrefab `?

**Comment by minggo** [comment]
>  the collider doesn't move

What does it mean?

**Comment by BenoitFreslon** [comment]
I think I can't reproduce this bug in CC 3.8.1

**Comment by minggo** [comment]
Ok, i will close this issue. Please reopen it if it still has problem.

**Comment by fahrettinenes** [comment]
I also get the same problem on a hobby-project.
<img width="385" alt="image" src="https://github.com/user-attachments/assets/505fdbde-af76-4012-a2d1-c93bd52fff2f">


```
import { _decorator, Component, Node, NodeSpace, RigidBody2D, Vec2, Vec3 } from 'cc';
const { ccclass, property } = _decorator;

@ccclass('PipeController')
export class PipeController extends Component {
    start() {

    }

    update(deltaTime: number) {
        this.node.position = new Vec3(this.node.position.x - 1, this.node.position.y, this.node.position.z)
    }
}
```

PipeController is attached for each Pipe Node.
