### ISSUE TITLE
duplicated defined ccclass in js plugin scripts

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#15847]
![企业微信截图_b981a1cb-d113-4d4f-93d4-9af98faa2db5](https://github.com/cocos/cocos-engine/assets/17872773/384514f1-c9e9-492e-ab0c-3839d4864ed7)

**Comment by dogeFu** [comment]
https://github.com/cocos/cocos-editor/pull/2259   这个引入的问题，浏览器预览时都会触发脚本重新执行。

**Comment by PPpro** [comment]
> https://github.com/cocos/cocos-editor/pull/2259 这个引入的问题，浏览器预览时都会触发脚本重新执行。

please take a look @yanOO1497 @changhua0118

**Comment by yanOO1497** [comment]
加载脚本之前不会自己会清空缓存吗？ 为什么会有重复 ID 的警告？

**Comment by naturalch** [comment]
> 加载脚本之前不会自己会清空缓存吗？ 为什么会有重复 ID 的警告？

![image](https://github.com/cocos/cocos-engine/assets/39176194/6ccb026e-08cd-4e92-b9e7-4d11a816171a)
![image](https://github.com/cocos/cocos-engine/assets/39176194/750b64a7-5e33-445b-b023-6050048026a2)
![image](https://github.com/cocos/cocos-engine/assets/39176194/39e16a77-c763-42f8-ba5b-a62cf85254a0)
![image](https://github.com/cocos/cocos-engine/assets/39176194/4ba082af-2b9d-49d9-823f-07121b4c6118)

The ccclass registration in the plugin script works correctly during the initial startup, but when attempting to register the script again after subsequent reloads, it results in a duplicate registration error.
`Module.__protected__.removeCache(codeFile)` only clears the cache referenced by the plugin script but does not clear the engine's registered component cache.

please check if it's possible to clear the registered cache before loading the plugin script to registe class or component? @PPpro

**Comment by naturalch** [comment]
The same issues also exist in build task.

**Comment by dogeFu** [comment]
Plugins should not be executed repeatedly.
We don't know what the user will do in the code, what changes will be made to the js global environment
Remove from the module, just re-require this file.
And the pollution of the global environment in plugins is unpredictable unless we can provide a sandbox

**Comment by PPpro** [comment]
it seems there are 2 issues here:
1. on 3.8.0, every preview will execute the plugin script, need to take a look at the design of `Load in Editor` option, it stands to reason that it should not be executed every preview @yanOO1497 @changhua0118 
2. `globalEnv.clear()` not cleared global environment, resulting in the second execution of the plugin script and an error class duplication registration @PPpro

**Comment by PPpro** [comment]
> globalEnv.clear() not cleared global environment, resulting in the second execution of the plugin script and an error class duplication registration @PPpro

ccclass is register in local variable `_idToClass` and `_nameToClass`, need to mannually call `js.unregisterClass` somewhere
