### ISSUE TITLE
Can't load scene if use prefab have cc.SceneAsset betweet 2 scene

### ISSUE THREAD

**Issue by joker8x** [cocos/cocos-engine#1584]
As title when I create prefab have cc.SceneAsset and reuse it in another scene. At first, it seems ok but if reload it will be stuck at loading on both scene.

**Comment by jareguo** [comment]
who is stuck?

**Comment by joker8x** [comment]
Cocos Creator v1.4.2

**Comment by jareguo** [comment]
Would it be possible for you to upload a demo?

**Comment by joker8x** [comment]
[DemoBug.zip](https://github.com/cocos-creator/engine/files/921279/DemoBug.zip)
this bug will happen if I use cc.SceneAsset as an array.

**Comment by jareguo** [comment]
Thanks @joker8x, this is a bug about the loader.

@pandamicro please fix this issue, I have a more simple way to reproduce the bug, just create two cross-referenced prefab, and drag them into a scene, creator will be stuck at loading on the scene.

**Comment by jareguo** [comment]
fixed
