### ISSUE TITLE
import glb into cocos creator 3.8.0,the Albedo Roughness etc in pbr material not correct

### ISSUE THREAD

**Issue by xbcoastline** [cocos/cocos-engine#15844]
### Cocos Creator version

3.8.0

### System information

Windows 11 

### Issue description

import glb into cocos creator 3.8.0,the Albedo Roughness etc in pbr material not correct

in blender 
![image](https://github.com/cocos/cocos-engine/assets/3320343/826adcf0-5af6-41d4-ad56-6cb7d434e38d)

in cocos
![image](https://github.com/cocos/cocos-engine/assets/3320343/02ae3915-884f-4042-b816-88d6ad6afc9c)

demo glb file
[tree.zip](https://github.com/cocos/cocos-engine/files/12235882/tree.zip)

### Relevant error log output

the preview of tree is not correct with wrong roughness
![image](https://github.com/cocos/cocos-engine/assets/3320343/3a6c84a7-290f-482a-910a-4d11b67fae28)

### Steps to reproduce

import the demo glb file into cocos creator,can reproduce the problem

### Minimal reproduction project

[demo.zip](https://github.com/cocos/cocos-engine/files/12235925/demo.zip)
alse can see the demo project

**Comment by AFeiYA** [comment]
这个 glb 流程， 属于是正常的行为， blender 导出 glb 会对材质重新计算的 pbr 参数, 实际值存在 glb 中， 导出后材质的 roughness 丢失了， 因此使用了默认参数 0.5。而导入引擎以 glb 中的数据为准， 以下是 glb 中的材质数据信息：
![image](https://github.com/cocos/cocos-engine/assets/11383513/e56371e3-75b7-47f6-bcf3-c3171fe20836)
