### ISSUE TITLE
How to import a template into a new project?

### ISSUE THREAD

**Issue by alankevin2** [cocos/cocos-engine#1586]
I want you have our compliment in advance : 『cocos creator is a marvelous game-editor!』

However, we had bumped into some situations that we are unable to find a solution.

The problem is, we have a project that is a **template** (or boilerplate if more appropriate) which contains resource, scripts, prefab and etc.
And we have, let's say, two games that we want to apply this **template**. 
How do we do to develop the game without including actual files to the game project? 

Ex: the two games require same image(PNG) which is put in the **template**, we would do something like:

```js
//Game Canvas
onLoad () {

    //the code below occurs error!
    cc.loader.loadRes("../Template/assets/resources/image.png", cc.Texture2D, () => {
        //blah
    });


}

```

The script files or prefabs cannot be use in this way too.

Is there anyways to achieve this goal?

BTW, this is not only for development, but also when we publish to any platforms, we do want to put the template in specific directory path, then access by any other games.

**Comment by nantas** [comment]
You can share assets across projects with extension package, first create a package according to basic workflow:

https://github.com/cocos-creator/creator-docs/blob/master/source/en/extension/your-first-extension.md

Then register a path that contains shared assets in package folder:

```js
//add this key in package.json of extension package
  "runtime-resource": {
    "path": "path/to/runtime-resource",
    "name": "shared-resource" // name freely, this will show in asset panel
  }
```

For every project that load this package, your shared assets will be shown in project's asset panel.

**Comment by alankevin2** [comment]
@nantas 
Hi, sorry for the late reply.

This works like charm in development. But I think Creator bundles all the scripts and serialize all resources for the Project. Is there any officially recommended way to exclude the files from **Template**? We would like to separate files of **Template** and **Games**.
Why is this so critical is because if there are multiple games requiring same resources from **Template**, same resources will exist in **EVERY** games.

Sorry for the poor English. 
Any advices will be greatly appreciated.

**Comment by xianyinchen** [comment]
We apologise for the late response，all resources need under assets folder，but in 2.4.4 you can use asset bundle to share resource.
