### ISSUE TITLE
‘webgl2-framebuffer.ts’ script question

### ISSUE THREAD

**Issue by kaxifakl** [cocos/cocos-engine#15861]
### Cocos Creator version

3.8.0

### System information

Window 10

### Issue description

Is it a written bug even though that width==height？
(webgl2-framebuffer.ts)
![image](https://github.com/cocos/cocos-engine/assets/63728902/d4699001-e0cc-42ac-b601-894ba60c6c28)

### Steps to reproduce

as the des show

**Comment by bluesky013** [comment]
fixed(https://github.com/cocos/cocos-engine/pull/15927)
