### ISSUE TITLE
ToggleGroup 修改建议

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#1587]
设置toggle.ischecked按钮是隐藏或显示checkmark组件sprite，而不是checkmark组件node节点，假如做一些 给节点下放自定义的组件，它就隐藏或显示不了了

ToggleGroup 修改建议
       Background 默认显示背景
      checkmark 选择后的背景
1:**Toggle.isChecked的开关 -> 隐藏或打开应该设置 checkmark.node.active 不要设置sprite本身的隐藏或显示**
2:**节点层次问题(Background,checkmark 修改成兄弟节点)**
	{默认层次
		New ToggleGroup{
			toggle1{
				Background{
					checkmark{}
				}
			}
			...
		}
	}
	{修改成
		New ToggleGroup{
			toggle1{
				Background{}//这个地方就用户就可以添加自己的东西了
				checkmark{}//节点下内容用户就可以自行添加了(加入隐藏sprite本身的话子节点就全部显示或隐藏)
			}
			...
		}
	}
	Background，checkmark父子节点修改成兄弟节点

**Comment by zilongshanren** [comment]
@GameMidlet 感谢建议，我们正好打算修改这一块。

**Comment by zilongshanren** [comment]
fixed
