### ISSUE TITLE
game.frameRate not working in editor preview

### ISSUE THREAD

**Issue by Grozamir** [cocos/cocos-engine#15938]
### Cocos Creator version

3.8.0

### System information

Windows 10/11 editor

### Issue description

Not working game.frameRate and editBox to limit fps in Preview in Editor. Checked it in cocos creator 3.7.3, everything works correctly there.

### Steps to reproduce

I wrote in the start method: "game.frameRate = 30;" or changed the value in the editBox for fps in the editor.

**Comment by dogeFu** [comment]
fixed on 3.8.1
