### ISSUE TITLE
Click Pause in the preview, but go back to the scene editor.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#15936]
### Cocos Creator version

3.8.0

### System information

MacOS

### Issue description

Start the preview, click pause, and see the picture.
![image](https://github.com/cocos/cocos-engine/assets/28684663/8403cbe6-8289-4e94-8cd8-57491712ec72)
If this is by design, can it be changed?

### Steps to reproduce

RT.

**Comment by smallmain** [comment]
I think we should show the scene editor and preview at the same time, ready to switch, just like any other engine.

**Comment by jareguo** [comment]
> I think we should show the scene editor and preview at the same time, ready to switch, just like any other engine.

Currently, panel multi-opening is only supported with native scene enabled (in the lab). When enabled, a Game panel will appear in the Panel menu.

> If this is by design, can it be changed?

This is so by design if the native engine is not enabled.
