### ISSUE TITLE
Unable to breakpoint in GameView when not started.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#15935]
### Cocos Creator version

3.8.0

### System information

MacOS

### Issue description

Open the preview developer tool, can't find any user scripts, so can't break points in it.

User scripts only appear if preview is enabled.

### Steps to reproduce

RT.

**Comment by dogeFu** [comment]
The scriptes doesn't load when you don't start it, it's for memory and performance reasons, you can hit a breakpoint once after you start it and it will take effect when you start it again.

**Comment by smallmain** [comment]
This experience is very bad. Can you provide an option? @dogeFu
