### ISSUE TITLE
Have residual meta files.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#15942]
### Cocos Creator version

3.8.0

### System information

MacOS

### Issue description

If you rename, delete or move a file in a non-editor, the meta file will not be deleted. Inconsistent with the behavior of older versions.

If this is incorrect behavior:
- fix it.

If correct:
- mentioned in the documentation.
- How to clean up these obsolete meta files?

### Steps to reproduce

RT.

**Comment by yanOO1497** [comment]
Thank you for your feedback, we are aware of this issue and have fixed it in the upcoming 3.8.1 release. You can also download the 3.8.1 beta version from the forums.
