### ISSUE TITLE
screen.resolution is expired data.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#15973]
### Cocos Creator version

3.8.0

### System information

MacOS

### Issue description

Modify shadingScale, screen.resolution will not be refreshed.

### Steps to reproduce

RT.

**Comment by dumganhar** [comment]
screen.resolution is a readonly property, so if you modify its return value directly like `screen.resolution.width = xxx;`, it will not take effect. 
```ts
    /**
     * @en Get the current resolution of game.
     * This is a readonly property.
     * @zh 获取当前游戏的分辨率。
     * 这是一个只读属性。
     *
     * @readonly
     */
    public get resolution (): Size {
        return screenAdapter.resolution;
    }
```



And about `shadingScale`, did you mean `director.root.pipeline.shadingScale`?

**Comment by smallmain** [comment]
> screen.resolution is a readonly property, so if you modify its return value directly like `screen.resolution.width = xxx;`, it will not take effect.
> 
> ```ts
>     /**
>      * @en Get the current resolution of game.
>      * This is a readonly property.
>      * @zh 获取当前游戏的分辨率。
>      * 这是一个只读属性。
>      *
>      * @readonly
>      */
>     public get resolution (): Size {
>         return screenAdapter.resolution;
>     }
> ```
> 
> And about `shadingScale`, did you mean `director.root.pipeline.shadingScale`?

Yeah I know, I mean

```ts
director.root.pipeline.shadingScale
screen.resolutionScale
screen.resolution
```

The relationship between these three looks like:
- `resolution` in the code is the actual rendering resolution (`winSize` * `resolutionScale`)
- `resolutionScale` has the same meaning as `shadingScale`

Modifying resolutionScale will cause shadingScale to change, but modifying shadingScale will not, so `resolution` has not changed, but the actual rendering resolution has changed.

**Comment by dumganhar** [comment]
I found `screen.resolutionScale` method was commented at https://github.com/cocos/cocos-engine/pull/9642/files#diff-be2bdcc494d154ec3dc114bc27094a50d857d8eff8f9f18c122eb342dadc63ed . It was a change from v3.4.0. So you probably could not use `screen.resolutionScale` now.

I will check this functionality later.

**Comment by star-e** [comment]
`director.root.resize` changes screen size. For example window size 1920 x 1080 -> 1280 x 720
`director.root.pipeline.shadingScale` does not change window size. It changes render pipeline render targets' sizes.
For example, if screen size is 1920 x 1080, shading can be done at 1280 x 720 by changing shading scale, and then copied to 1920 x 1080 screen.
@smallmain

**Comment by smallmain** [comment]
> `director.root.resize` changes screen size. For example window size 1920 x 1080 -> 1280 x 720 `director.root.pipeline.shadingScale` does not change window size. It changes render pipeline render targets' sizes. For example, if screen size is 1920 x 1080, shading can be done at 1280 x 720 by changing shading scale, and then copied to 1920 x 1080 screen. @smallmain

ah, what is the difference between `director.root.resize` and setting `screen.windowSize`?

**Comment by dumganhar** [comment]
`cc.screen.windowSize` changes the system window size.
`director.root.resize` changes the rendering target size.

**Comment by smallmain** [comment]
> `cc.screen.windowSize` changes the system window size. `director.root.resize` changes the rendering target size.

> `director.root.pipeline.shadingScale` does not change window size. It changes render pipeline render targets' sizes.

ah, what is the difference between `director.root.resize` and setting `director.root.pipeline.shadingScale`?
