### ISSUE TITLE
[dev] 无法获得 visibleRect

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#15984]
### API documentation URL

https://docs.cocos.com/creator/3.8/api/zh/variable/visibleRect

### Issue description

按文档中描述的代码 并不行: 
<img width="415" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/aed23f7b-59f0-4569-a2f8-e5af0ce905cb">

经过尝试, 发现要用下面的代码才行:
<img width="333" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/e2c88a82-2574-44c7-8439-592067dd5a3f">

**Comment by pandamicro** [comment]
You should use [View.getVisibleSize](https://docs.cocos.com/creator/3.8/api/zh/class/View?id=getVisibleSize) and [View.getVisibleOrigin](https://docs.cocos.com/creator/3.8/api/zh/class/View?id=getVisibleOrigin)
