### ISSUE TITLE
dashboard linux (lutris win7)

### ISSUE THREAD

**Issue by grodemar** [cocos/cocos-engine#15981]
### Use Case

cocos dashboard linux (lutris win7 64)

### Problem Description

installs editor (C)downloding... 0%

### Proposed Solution

is it possible to download manually "CocosCreator-v3.8.0-win-072014.zip" ?

i see dashboard have button for local installer

### Alternatives Considered

...

**Comment by jareguo** [comment]
Sorry it won't work because of the installation license involved. Please install it directly in Windows.
