### ISSUE TITLE
android ReflectionProbe bug

### ISSUE THREAD

**Issue by whaqzhzd** [cocos/cocos-engine#16003]
### Cocos Creator version

3.8

### System information

ANDROID

### Issue description

In the Android environment, using the latest custom pipeline, a planar real-time reflection probe is placed in the scene and published to the Android platform. It can be seen that in the buildReflectionProbePass function, calling probe's renderArea will fail. On Android, the probe only has getRenderArea and does not have renderArea

### Relevant error log output

runtime：
![image](https://github.com/cocos/cocos-engine/assets/16913061/5a4bed06-efe1-4223-a741-523421689fde)

debug:
![image](https://github.com/cocos/cocos-engine/assets/16913061/6a0d74e3-5f50-4273-aea3-4d62bb0aa7bd)

### Steps to reproduce

-

**Comment by whaqzhzd** [comment]
Similarly, the camera function of a similar reflection probe uses camera to acquire in web, while in Android it needs to use getCamera to acquire. The function call is also in buildReflectionProbePass

![image](https://github.com/cocos/cocos-engine/assets/16913061/37a74348-d71a-45e2-94d4-c22603e5fa0d)

**Comment by whaqzhzd** [comment]
And there are also several other bugs.

**Comment by whaqzhzd** [comment]
It seems that planar reflection has never been tested on Android before

**Comment by whaqzhzd** [comment]
To supplement, this seems to be native across platforms. 

windows:
![image](https://github.com/cocos/cocos-engine/assets/16913061/9e84f88e-c4c7-41c0-b35c-52554527ed69)

**Comment by xubing0906** [comment]
There is indeed an issue with planar reflection under the custom pipeline, and we will fix it as soon as possible.

**Comment by whaqzhzd** [comment]
Let's discuss some other bugs related to planar reflection. 

We know that after setting the camera for planar reflection in the editor, we can adjust the camera's Visibility to achieve the goal of which objects need to be reflected.
![image](https://github.com/cocos/cocos-engine/assets/16913061/4393e046-4d2c-4b6b-a141-f21f0b831d5a)

But the problem is that the implementation of planar reflection update will cause the parameters set in the editor to become meaningless. 

[reflection-probe-component](https://github.com/cocos/cocos-engine/blob/develop/cocos/3d/reflection-probe/reflection-probe-component.ts#L378) The renderPlanarReflection call on line 738 will cause the Visibility set in the editor to be overridden.
The override implementation is on line 315. [this._syncCameraParams(sourceCamera)](https://github.com/cocos/cocos-engine/blob/develop/cocos/render-scene/scene/reflection-probe.ts#L315)

We should use the parameters of the reflection component itself, rather than the camera's.  [args](https://github.com/cocos/cocos-engine/blob/develop/cocos/render-scene/scene/reflection-probe.ts#L182)

**Comment by jk20012001** [comment]
ClearFlag and Visiblity should synchronous with Main Camera，these options should be removed from Refleciton Probe Component
https://github.com/cocos/cocos-engine/pull/16115

**Comment by whaqzhzd** [comment]
> ClearFlag and Visiblity should synchronous with Main Camera，these options should be removed from Refleciton Probe Component
https://github.com/cocos/cocos-engine/pull/16115

Oh, really? Let me think about this scenario: What if the project requirement is to have partial reflection and partial non-reflection. If synchronizing the reflection camera with the main camera means we need a third camera to do this, then assuming Camera A is the main scene camera, and Camera B is the reflection camera created based on Camera A. Based on the early implementation, at this point we only need to modify the visibility etc to make it work. But with the new implementation, does it mean we need to create a camera with no actual meaning just to serve as the reflection main camera? This reflection main camera would need to maintain exactly the same transform as Camera A. And assign it for the reflection component to use. Isn't this a bit redundant?

**Comment by jk20012001** [comment]
Synchronizing with the main camera is just to minimize settings, and this requirement you are talking about can be solved by removing bake to reflection probe from MeshRenderer. However, after discussion, it was decided to keep this visibility option, the default value is default, and it is no longer synchronized with the main camera

**Comment by whaqzhzd** [comment]
> Synchronizing with the main camera is just to minimize settings, and this requirement you are talking about can be solved by removing bake to reflection probe from MeshRenderer. However, after discussion, it was decided to keep this visibility option, the default value is default, and it is no longer synchronized with the main camera

OK, if it is implemented by modifying MeshRenderer, it seems much more troublesome than modifying the visibility of the reflection probe. For example, in the early stage of project production, prefabs were not used but copied and pasted directly in the scene, etc. or other lazy production methods.

**Comment by jk20012001** [comment]
So the currently determined solution is to keep the visibility and take effect independently, no longer overridden by the main camera settings, which should be fixed in 3.8.1

**Comment by whaqzhzd** [comment]
> So the currently determined solution is to keep the visibility and take effect independently, no longer overridden by the main camera settings, which should be fixed in 3.8.1

LGTM!
