### ISSUE TITLE
the edit box decimal mode is broken in web

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#16039]
### Cocos Creator version

3.8

### System information

Mac

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/26038745/e10c472f-df74-46c2-801e-4c21b0a2efb0)
when change input mode to decimal, I cant type decimal point in run time, it will change the input flag to 1st place
![s2](https://github.com/cocos/cocos-engine/assets/26038745/687fac93-d52a-4bcf-8217-bcbc37fedc1b)

### Steps to reproduce

change input mode to decimal, I cant type decimal point directly, it will change the input flag to 1st place
![s2](https://github.com/cocos/cocos-engine/assets/26038745/687fac93-d52a-4bcf-8217-bcbc37fedc1b)

**Comment by khanhnd1120** [comment]
Hello, I have same bug and how to fix it in cocos version 3.7?

**Comment by minggo** [comment]
You can refer the PR above.

**Comment by vivek4148** [comment]
Can it be fixed on 2.4.13?

**Comment by knoxHuang** [comment]
@vivek4148 fixed to 2.4.14

**Comment by heyanfei** [comment]
Resolved in version 2.4.14（0603） validation
