### ISSUE TITLE
3.8 property no hints compared with 2.4

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#16042]
### Use Case

in 2.4 property has hint ,which is easy to use 
<img width="524" alt="image" src="https://github.com/cocos/cocos-engine/assets/26038745/52948eca-1778-4b5f-bee0-3b3e916f8dda">
3.8 its private, hard to use
![image](https://github.com/cocos/cocos-engine/assets/26038745/60be27ec-2f82-4f4d-9379-7cb9a0248462)

### Problem Description

in 2.4 property has hint ,which is easy to use 
<img width="524" alt="image" src="https://github.com/cocos/cocos-engine/assets/26038745/52948eca-1778-4b5f-bee0-3b3e916f8dda">
3.8 its private, hard to use
![image](https://github.com/cocos/cocos-engine/assets/26038745/60be27ec-2f82-4f4d-9379-7cb9a0248462)

### Alternatives Considered

add hint to 3.8 property 
![4311692584875_ pic](https://github.com/cocos/cocos-engine/assets/26038745/eb9bbbf0-645e-4781-9d5a-10182656b005)

**Comment by PPpro** [comment]
this is the difference between 2.x and 3.x

```ts
function property_2_x (a: {
    foo: number;
    bar: string;
}) {}

interface PropertyOptions {
    foo: number;
    bar: string;
}
function property_3_x (a: PropertyOptions) {}
```

In 3.x, the property options is defined as an interface, I think it's the better implementation than 2.x, though our developpers can't see the exact option items, they can check it out in the interface declaration of `PropertyOptions `.

**Comment by PPpro** [comment]
I'll close this issue if there is no any other discussion about it
