### ISSUE TITLE
3.8 will pack 2 standard materials

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#16075]
### Cocos Creator version

3.8

### System information

Mac

### Issue description
1. 
![image](https://github.com/cocos/cocos-engine/assets/26038745/ecd43253-87ff-43bf-aa30-72321e96a86d)
3.8 will pack legacy standard mat as well, which will increase a lot in package size

2.
![企业微信截图_689a9eec-0c63-4c98-a9b6-9cb0700a9a92](https://github.com/cocos/cocos-engine/assets/26038745/51e1f82e-f210-4d22-90a7-90a0d86a877d)
even if I toggle off fxaa, fxaa still in mat json

![image](https://github.com/cocos/cocos-engine/assets/26038745/113ff0b4-2d3a-408a-868b-d2b0b9db3971)
3.
can we cull particle's gpu/cpu mat separately for smaller package size 

4.
cull unused posteffect for smaller size

![image](https://github.com/cocos/cocos-engine/assets/26038745/b2223c7b-9205-45b7-b966-996e54fb76dd)

5.
add global surface view debug view macro to cull the debug view for smaller size 
SURFACES_DEBUG_VIEW

6. after I culling these effects manually , the scripts size of the engine will also decrease 200+kb, I think there are duplicate copy in scripts as well，same for bloom as well
![image](https://github.com/cocos/cocos-engine/assets/26038745/34bdb56c-fe31-4d74-8b87-60caa6994abd)

### Steps to reproduce

![image](https://github.com/cocos/cocos-engine/assets/26038745/ecd43253-87ff-43bf-aa30-72321e96a86d)
3.8 will pack legacy standard mat as well, which will increase a lot in package size

**Comment by linshun** [comment]
Why was such a serious bug fix not included in the v3.8.1 plan, and it was three weeks ago?

**Comment by jk20012001** [comment]
https://github.com/cocos/cocos-engine/pull/15650
it has been fixed in 3.8.0

**Comment by iwae** [comment]
all fixed

**Comment by iwae** [comment]
all fixed
