### ISSUE TITLE
Baked EnvMap out of source control

### ISSUE THREAD

**Issue by MrKylinGithub** [cocos/cocos-engine#16076]
### Cocos Creator version

3.8.0

### System information

Windows and Mac

### Issue description

When using the default envmap in the internal folders. the baked envmap can't be committed via git tools.
This leads to the hdr texture losing on another computer.

### Steps to reproduce

1. create an empty scene and save
2. change the Env Lighting Type to the second or third one
3. bake Envmap
4. commit & push to git and clone & pull on another computer. ( or just simply copy the whole project to another computer)
5. open the project and run.

### Minimal reproduction project

kunkun knows how to reproduce it.

**Comment by jk20012001** [comment]
internal resource should bake / generate / find  in assets/internal/samepath/samename....

**Comment by jk20012001** [comment]
https://github.com/cocos/editor-extensions/pull/655
