### ISSUE TITLE
Avast antivirus delete CocosDashboard.exe and CocosCreator.exe

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#16080]
### Cocos Creator version

3.7.4

### System information

Windows 11

### Issue description

I'm using CocosDashboard 2.0.0
I installed some editors but when I close all editors and dashboard the CocosCreator 3.7.4 only is missing.
The CocosCreator.exe of 3.7.4 editor is missing and the CC Dashboard too.

![image](https://github.com/cocos/cocos-engine/assets/758680/38ff3481-9fda-4637-a3b5-1297b5af4c93)

![image](https://github.com/cocos/cocos-engine/assets/758680/70922551-20de-4d4b-a0b6-827c8add8c31)

I have to reinstall the Dashboard and the editor each time.

### Steps to reproduce

Install 3.7.4 and close all apps.
Re open the Dashboard.
Install Avast free.

![image](https://github.com/cocos/cocos-engine/assets/758680/7ee86442-b56b-4031-a704-ba249db1edad)

**Comment by SummerJL-ws** [comment]
Hi, I can't reproduce the issue from my side. Here's advice from Avast, which may be helpful:
- [Using the Blocked & Allowed apps settings screen in Avast Antivirus](https://support.avast.com/en-us/article/use-antivirus-blocked-allowed-apps/#pc)
- [Excluding certain files or websites from scanning in Avast Antivirus and Avast One](https://support.avast.com/en-us/article/antivirus-scan-exclusions/#pc)
