### ISSUE TITLE
GFXObject null pointer

### ISSUE THREAD

**Issue by Limiandy** [cocos/cocos-engine#16091]
### Cocos Creator version

3.8.1

### System information

ios 16.4

### Issue description

xcode version: 14.3.1
ios version: 16.4

I am making the first game according to the example of the official website, but after building the ios version, I can't run it with the simulator in xcode, and there is a null pointer error.

<img width="905" alt="image" src="https://github.com/cocos/cocos-engine/assets/46664435/98c4e2a8-5f9e-4a5d-9d89-be8dc3b11b94">

### Steps to reproduce

xcode version: 14.3.1
ios version: 16.4

I am making the first game according to the example of the official website, but after building the ios version, I can't run it with the simulator in xcode, and there is a null pointer error.

**Comment by bluesky013** [comment]
@Limiandy Thank you for your feedback. Which sample did you encounter the issue in?

**Comment by star-e** [comment]
Currently we are not able to reproduce the problem.
If you still have this issue, please provide a demo project, so we can investigate the problem.
