### ISSUE TITLE
[v3.8.1]old project texture leads crash on iOS

### ISSUE THREAD

**Issue by bravetwo** [cocos/cocos-engine#16176]
### Cocos Creator version

3.8.1 082412 090112

### System information

macOS Ventura 13.5.1, Xcode 14.3.1 build on iPhone12 Pro 15.5

### Issue description

create new project with AR(Mobile) Example in 3.8.1 in Dashboard, add a cube to an empty scene, using the built-in standard effect material, and set the AlbedoMap to "gymnasium.jpg" from the ar example, get crash.

right click gymnasium.jpg, reimport asset, still crash.

copy gymnasium.jpg in finder, then set the AlbedoMap to the copy, won't crash.

### Relevant error log output

Assertion failed: (hasAllFlags(DeviceValidator::getInstance()->getFormatFeatures(info.format), ff)), function doInit, file TextureValidator.cpp, line 66.

### Steps to reproduce

 - create new project with AR(Mobile) Example in 3.8.1 in Dashboard
- add a cube to an empty scene, using the built-in standard effect material, and set the AlbedoMap to "gymnasium.jpg" from the ar example, get crash.

 - right click gymnasium.jpg, reimport asset, still crash.

- copy gymnasium.jpg in finder, then set the AlbedoMap to the copy, won't crash.

**Comment by bravetwo** [comment]
[Test3819.zip](https://github.com/cocos/cocos-engine/files/12509354/Test3819.zip)
090112 version, eliminate ar part, use the scene under assets

**Comment by bluesky013** [comment]
Format validation in debug build. Fixed by format feature check.
