### ISSUE TITLE
Compilation errors if using Clang 15 with c++17 since std::unary_function has been removed

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#16190]
### Xcode15 beta8:

➜  build git:(v3.8.2) ✗ xcrun clang -v
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

![Screenshot 2023-09-05 at 17 00 45](https://github.com/cocos/cocos-engine/assets/493372/f4aef4ab-f809-42df-a693-9d1a6fb6271c)

### Emscripten 3.1.41 which uses clang 17

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.41 (71634e036d20209a5d81c2b2171e145b44de1e12)
clang version 17.0.0 (https://github.com/llvm/llvm-project 88421ea973916e60c34beb26597a5fc33f83dd8f)

```
error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
   13 | struct my_hash_base : std::unary_function<T, size_t> {};
      |                       ~~~~~^~~~~~~~~~~~~~
      |                            __unary_function
/Users/james/projects/webassembly/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
   46 | using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
      | ^
1 error generated.
```

**Comment by onecpp** [comment]
when add BOOST_NO_CXX98_FUNCTION_BASE define, it will be clash on ios sdk 12.55 iphone, but it is ok for ios sdk 15

**Comment by dumganhar** [comment]
@onecpp Thanks for testing. Which iphone device and system version did you test on?

**Comment by onecpp** [comment]
iphone 6, and ios sdk update to 12.5.7, macos 13.5.2, xcode 15  still clash, but it is fine at macos 12.3.1, xcode 12, 
the cash info : 
![471695263023_ pic](https://github.com/cocos/cocos-engine/assets/96186119/adeea035-7be2-446a-b24e-8ed03fee90b4)
![481695263056_ pic](https://github.com/cocos/cocos-engine/assets/96186119/a3944525-b34a-49da-a525-c0b3be909f11)

**Comment by dumganhar** [comment]
From the crash stack, I didn't ensure that it was caused by defining `BOOST_NO_CXX98_FUNCTION_BASE` macro.
If you remove the line defines `BOOST_NO_CXX98_FUNCTION_BASE` macro in native/CMakeLists.txt. Would it crash too?

**Comment by onecpp** [comment]
if remove the macro, it can't be build on xcode 15, std::unary_function has been removed

**Comment by onecpp** [comment]
xcode 15, ios sdk 15.3.1, macos  13.5.2, it is fine, when i add BOOST_NO_CXX98_FUNCTION_BASE macro, but clash on ios 12.5.7

**Comment by dumganhar** [comment]
Could you help to check this environment?
Xcode 14 or 12 ( < 15 is ok),  iOS 12.5.7,  add `BOOST_NO_CXX98_FUNCTION_BASE` definition in CMakeLists.txt.

**Comment by onecpp** [comment]
i think : don't add BOOST_NO_CXX98_FUNCTION_BASE macro, and use something instead of std::unary_function, it will be ok? but i don't how to replace std::unary_function

**Comment by dumganhar** [comment]
I don't think the crash was caused by `BOOST_NO_CXX98_FUNCTION_BASE`, You could look at the source code of boost.
If we define BOOST_NO_CXX98_FUNCTION_BASE, it use a custom struct to replace `std::unary_function`.

**Comment by dumganhar** [comment]
Because the crash stack doesn't contain any boost stuff.

**Comment by onecpp** [comment]
i add BOOST_NO_CXX98_FUNCTION_BASE at xcode 13.2, macos 12.3.1, ios sdk 12.5.7, it is ok, so how to fixed at xcode 15? it must be something wrong inside

**Comment by dumganhar** [comment]
Just as I thought, it's not because of adding `BOOST_NO_CXX98_FUNCTION_BASE`. Something was broken in Xcode 15.
I found that the Xcode 15 stable version is out. I will have a try.

**Comment by dumganhar** [comment]
See https://github.com/facebook/react-native/issues/39069

**Comment by dumganhar** [comment]
@onecpp Could you help to try this PR: https://github.com/cocos/cocos-engine/pull/16306 ? Thanks.

**Comment by onecpp** [comment]
I test PR: #16306 on xcode15, ios sdk 12.5.7, macos 13.5.2, it is ok now, so NB man, thanks

**Comment by dumganhar** [comment]
@onecpp Good to know that works.
