### ISSUE TITLE
3D GPU Particle running on WeChat Mini games shows exception

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16199]
### Cocos Creator version

3.7.3

### System information

HarmonyOS 2.0

### Issue description

WeChat Mini games platform, the effect of GPU particles on Huawei p30 pro or p40 will be inconsistent with the web preview

web mobile effect is(correct):
![图片](https://github.com/cocos/cocos-engine/assets/35944775/d74ecc74-7c62-49f0-be22-e26964d15835)

wechat game effect is(wrong):
![图片](https://github.com/cocos/cocos-engine/assets/35944775/3a50bcea-e3de-4f1a-ae7f-94b240aa5575)

### Relevant error log output

---

### Steps to reproduce

---

### Minimal reproduction project

[gpuParticleTest.zip](https://github.com/cocos/cocos-engine/files/12535405/gpuParticleTest.zip)

**Comment by zxx43** [comment]
This platform do not support gpu particle
