### ISSUE TITLE
The event in the Spine animation doesn't trigger expectedly.

### ISSUE THREAD

**Issue by Outsiderxx** [cocos/cocos-engine#16221]
### Cocos Creator version

3.8.1

### System information

Windows11, Edge 116

### Issue description

When the event is about to trigger, 

![image](https://github.com/cocos/cocos-engine/assets/49907488/6bc681c1-08e9-4707-a0eb-1ab2e1c6d9c9)

error above will appear.

### Steps to reproduce

Play an animation that contains an event (e.g., the run animation of Spineboy from Spine's example).

**Comment by Outsiderxx** [comment]
Error will be thrown when evaluate the properties of event.data

[Demo](https://drive.google.com/file/d/11zx9o3Aq42Y36IkpU6SK_o7jMY0racEv/view?usp=sharing)

**Comment by Canvasfull** [comment]
Can you see what version date is being used?
<img width="214" alt="Screenshot 2023-10-12 at 10 13 47" src="https://github.com/cocos/cocos-engine/assets/2398658/2ba0b5f1-435e-4093-8b87-9a2b7bef9589">

**Comment by Outsiderxx** [comment]
![image](https://github.com/cocos/cocos-engine/assets/49907488/33620f0a-6ee2-4738-8008-73ba7fc32006)

**Comment by Outsiderxx** [comment]
I have tried the latest commit of v3.8.1 branch, but it still has this issue.
![image](https://github.com/cocos/cocos-engine/assets/49907488/9b83c4c5-99fc-4165-841c-382acb6927bf)

**Comment by Canvasfull** [comment]
You need to update the content of the repository https://github.com/cocos/cocos-engine-external to the directory `engine/native/external`.

<img width="1267" alt="Screenshot 2023-10-12 at 14 14 24" src="https://github.com/cocos/cocos-engine/assets/2398658/30f04e6d-9f79-40b4-a85a-308e8355cbb8">

https://docs.cocos.com/creator/3.7/manual/en/advanced-topics/engine-customization.html

**Comment by Outsiderxx** [comment]
I see, thank for your help.
