### ISSUE TITLE
The relevant code will still be executed after the 3 D physical system is cropped

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16237]
### Cocos Creator version

3.8.0

### System information

web

### Issue description

![img_v2_283a04c6-9361-495b-b810-5cb473262bdg](https://github.com/cocos/cocos-engine/assets/35944775/9c31aecf-2eae-498a-a0d0-07f95922f7c5)

![img_v2_e0e19bc9-983e-4b38-93d1-9a24c994270g](https://github.com/cocos/cocos-engine/assets/35944775/790960d6-5ad9-4734-8926-1759f683fb98)

**This issue does not appear in Creator 3.7**

### Steps to reproduce

-

**Comment by minggo** [comment]
I can not reproduce it in v3.8.2. So close it.
