### ISSUE TITLE
[2D camera]  the alpha of camera's clearColor has no effect.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16255]
### Cocos Creator version

3.8.1

### System information

all

### Issue description

<img width="641" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/3d23dc4f-a679-486d-9aa4-d81529e7fdf6">

In my opinion, the background  should be transparent, because  the alpha of  clearColor is 0 , and clearFlags is SOLID_COLOR .

But in runtime , the background is red.
<img width="208" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/b971c273-532d-41f1-b481-88d2f47296f0">

If I checked the ENABLE_TRANSPARENT_CANVAS , the background is transparent, but there are red boards around front-ojects.

<img width="178" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/2d9d41ae-caca-4106-8d5c-65e1249bbcb4">

In cocos 2.x , the result is  correct. (background is transparent & no red boards ).

### Steps to reproduce

..

**Comment by pandamicro** [comment]
By investigating the project, the setup is using two camera, one for capturing content with transparent (colored) background to RT, another for presenting this RT.

The root reason of these red pixels is that your RT is set to bilinear filter, and this will cause GL to blend your edge pixels with transparent pixel (red colored) around it, so the color value is blended to the edge pixels.

The way to avoid either of the two
1. Use nearest filter for RT
2. Change RT camera's background color to transparent black to avoid blending issue

**Comment by pandamicro** [comment]
So I will close this issue as it's correct behavior
