### ISSUE TITLE
热更新过程中强杀进程！可能导致js层奔溃的问题

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#1625]
在android 机器中！热更新过程中强杀进程！可能导致js层奔溃的问题

热更新过程中还走热更新的状态(更新进度，更新资源。。。)，强杀进程后，在进入游戏就立马还走热更新的状态机制

不走 coco2d-js v3.14 （js层打印）

求解决

**Comment by xianyinchen** [comment]
你好，从你提供的信息，可以看出你使用的引擎是 coco2d-js v3.14，不属于 cocos creator 仓库问题，该issue会被关闭，如果问题还存在，请提交到 cocos2dx 仓库。
https://github.com/cocos2d/cocos2d-x
