### ISSUE TITLE
web ios 13.7 surface shader and dcc shader error

### ISSUE THREAD

**Issue by ankye** [cocos/cocos-engine#16263]
### Cocos Creator version

3.8.0,3.8.1

### System information

ios 13.7

### Issue description

https://github.com/cocos/cocos-engine/assets/5154427/5afe6dfa-5b71-4bd1-984a-532c65ada46e

ios 13.7 safari and chrome both have problems

### Steps to reproduce

create 3d cube object, and use surface shader 
![26371694766241_ pic](https://github.com/cocos/cocos-engine/assets/5154427/c7d9abc6-c4d1-412c-93ac-d6eef8c4aa74)
or
![26381694766241_ pic](https://github.com/cocos/cocos-engine/assets/5154427/546b2939-45b6-40f3-87b0-c235cebffa02)

run on ios 13.7 safari and chrome both has this problem

**Comment by xubing0906** [comment]
In version 13.6.1, there is no problem, is WebGL 2.0 enabled，Set> Safari > Advanced > Experimental Features

**Comment by ankye** [comment]
![121695043629_ pic](https://github.com/cocos/cocos-engine/assets/5154427/c05dbd3e-dfc4-4d2a-86b9-c84a67ee7d63)

**Comment by ankye** [comment]
my default setting is not enabled webgl 2.0

**Comment by xubing0906** [comment]
can you provide a demo?

**Comment by ankye** [comment]
[web3d.zip](https://github.com/cocos/cocos-engine/files/12659122/web3d.zip)


> can you provide a demo?

**Comment by xubing0906** [comment]
The issue cannot be reproduced in version 13.6.1; it might only exist in version 13.7.
![6f0efd91-9664-434c-a5f3-80b5730e1075](https://github.com/cocos/cocos-engine/assets/49358166/b39a9116-6b8b-4d3a-9786-ef26968e8870)

**Comment by ankye** [comment]
3.7.3 is ok，3.8 and 3.8.1 has this problem

**Comment by ankye** [comment]
![image](https://github.com/cocos/cocos-engine/assets/5154427/51d21142-b96a-4638-b9e6-a2560b06f69c)

**Comment by ankye** [comment]
ios 12-14.8 all not supported by default

**Comment by jareguo** [comment]
抱歉我们无法重现，尝试过比你高或比你低的版本都是正常的。这种特殊设备特殊版本的兼容性问题，现在没人力跟进了。如果有您有其它发现欢迎重新 open。

---
Sorry we can't reproduce it, tried versions higher or lower than yours and it works fine. There is no manpower to follow up on this special device-specific version compatibility issue right now. If you find something else, feel free to re-open it.
