### ISSUE TITLE
HBAO lost effect after exiting from full screen mode during preview 

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#16267]
### Cocos Creator version

3.8.0

### System information

Windows 11

### Issue description

RT. 

### Steps to reproduce

1. Prepare a HBAO scene.

2. Preview in browser.

3. Enter full screen mode.

4. Exit the full screen mode.

**Comment by star-e** [comment]
HBAO is disabled in builtin-pipeline.
HBAO need scene depth buffer. It will downgrade performance on mobile-platform.
We will add HBAO back on other platforms.
