### ISSUE TITLE
PAL module @pal/wasm should export only instantiateWasm() method

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#16265]
- `fetchBuffer` method is not being used outside.

- `ensureWasmModuleReady()` can be directly integrated in `instantiatedWasm()` instead. i.e..:

   ```ts
  export function instantiatedWasm() {
    return ensureWasmModuleReady().then(() => {
      // original logic
    });
  }
  /* NO EXPORT */function ensureWasmModuleReady() {
  }
   ```

They should be private to `@pal/wasm`  implementation themselves.

**Comment by PPpro** [comment]
> fetchBuffer method is not being used outside

I think `fetchBuffer` should be part of the design of 'pal/wasm' module, no matter whether it is used outside. The `pal/wasm` need to provide this general ability to help fetch wasm buffer.

> ensureWasmModuleReady() can be directly integrated in instantiatedWasm()

`ensureWasmModuleReady()` need to be exported. we need to dynamic import the wasm module outside 'pal/wasm'.
we cannot import these modules in 'pal/wasm' module
```ts
ensureWasmModuleReady().then(() => Promise.all([
        import('external:emscripten/bullet/bullet.wasm'),
        import('external:emscripten/bullet/bullet.asm.js'),
    ]).then(([
        { default: bulletWasmUrl },
        { default: asmFactory  },
    ]) => {
        if (shouldUseWasmModule()) {
            return initWasm(bulletWasmUrl, importObject);
        } else {
            return initAsmJS(asmFactory);
        }
    })).catch(errorReport);
```
