### ISSUE TITLE
求接入FMOD

### ISSUE THREAD

**Issue by neytsomh** [cocos/cocos-engine#16270]
### Use Case

我是半吊子音效师，之前一直是在Unity平台弄FMOD、Wwise中间件。

### Problem Description

在FMOD接入Cocos方面，我自己真的技术不行，像Unity和UE官方都原生支持FMOD。这对我们搞音效的来说很便利。
但是Cocos在这方面我查询了一些资料，目前没有找到很方便的方式。我又不会C++，我很菜。

### Proposed Solution

所以希望官方能给FMOD的接入提供便利。FMOD官网可以很方便下载API。

### How it works

最好的结果是希望能实现像Unity那样的FMOD插件，支持FMOD 事件、Parameter、BankLoader，以及3D音效等API。参考fmod for unity插件。
其次最起码要能读fmod导出的bank，调用fmod的事件、控制parameter等接口。

### Alternatives Considered

实在不行，建议Cocos好好发展自己的Audio系统，类似Unity的AudioManager。拥有音轨系统、侧链系统、快照系统，以及一些基本的效果器，如压缩器、闪避、限幅器、混响等。

### Additional Information

谢谢。Cocos原生的音频功能，实在是无法满足最基本的音频需求。目前音频工作的主流趋势还是往中间件上走，因为其实音效想做好，是需要程序造很多轮子的，不如用中间件来得实在。当然我强烈支持我们自己能开发出一个中间件。

**Comment by minggo** [comment]
Please use english in future, thanks.
FMOD is a commercial product, we can not integrate it in cocos.
