### ISSUE TITLE
windows platform: Graphics component node still has a large amount of memory occupied after executing destroy

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16291]
### Cocos Creator version

3.8.0

### System information

Windows

### Issue description

https://discuss.cocos2d-x.org/t/memory-leak-even-when-call-node-destroy/59492

Before loading Graphics:
![图片](https://github.com/cocos/cocos-engine/assets/35944775/42ee070f-88a2-433a-aba0-57786048efc3)

After loading Graphics:
![图片](https://github.com/cocos/cocos-engine/assets/35944775/2daeaccb-a18d-4dbe-84e1-0e0397c02167)

after destroying all Graphics:
![图片](https://github.com/cocos/cocos-engine/assets/35944775/76a1a393-e74d-4c16-bdc8-620a4480b6e4)

### Relevant error log output

--

### Steps to reproduce

Download and open the project, build, compile the Windows project and run it in VS.
Click the create button to generate Graphics nodes, then click destroy to delete all Graphics nodes, and finally observe the memory situation and found problems.

### Minimal reproduction project

[59492.zip](https://github.com/cocos/cocos-engine/files/12670325/59492.zip)

**Comment by Kingurus** [comment]
Also Label Component has leaks after destroy. I tried these, leak remains:
   cclegacy.director._nodeActivator._deactivateNodeRecursively(node);
   cclegacy.director._nodeActivator.activateNode(node,0);
     node.removeComponent(e);
     node._removeComponent(e);
      e._destruct();
      cclegacy.director._nodeActivator.destroyComp(e);
      cclegacy.director.getScheduler().unscheduleAllForTarget(e);
      e.enabled=false;
      e.destroy();
      e._onPreDestroy();
      e._destroyImmediate(); //still: memory leak after removing the component

**Comment by Kingurus** [comment]
I tried on native: Windows and Android
node.destroy() does not work. node._destroyImmediate() works and has no leaks unless the node has the added components. If it has these components -> memory leak
I tried  these Components: Label, Graphics

**Comment by zhefengzhang** [comment]
https://discuss.cocos2d-x.org/t/memory-is-not-free-by-node-destroy/59563/
