### ISSUE TITLE
After building the ByteDance Mini games, the project runs an error on the developer tool

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16305]
### Cocos Creator version

3.8.0

### System information

Windows10

### Issue description

![图片](https://github.com/cocos/cocos-engine/assets/35944775/6a7d5b93-5faf-4fb6-b1eb-c300c4b84111)

### Relevant error log output

--

### Steps to reproduce

![图片](https://github.com/cocos/cocos-engine/assets/35944775/224cb300-e988-406d-986e-8c40a13fc121)
![图片](https://github.com/cocos/cocos-engine/assets/35944775/745e22c6-d226-4532-9e01-5dc211efcec7)

**Comment by lealzhan** [comment]
https://forum.cocos.org/t/topic/153116
建议使用2.x版本的抖音开发者工具。新版本的开发者工具似乎没有提供native physx包。由于字节方面这块没有维护，我们会在近期全面使用我们自己的physx包，这个问题也会得到解决。
