### ISSUE TITLE
[2.x] xcode 15 build success run error

### ISSUE THREAD

**Issue by Maxize** [cocos/cocos-engine#16340]
### Cocos Creator version

2.4.12,2.4.11,2.4.6

### System information

MacOS 13.5.2, iOS 16.6.1 on iPhone 13, Xcode 15.0

### Issue description

使用 2.4.12 编辑器版本，新建 Hello World 项目，直接发布运行，报错如图所示。
在 2.4.11，2.4.6 也是如此。
应该是 Xcode 15 & iOS 17 调整了什么配置导致的，先反馈到官方，坐等修复。

![image](https://github.com/cocos/cocos-engine/assets/3771476/88299469-b7f3-4adf-9644-35f1622aec47)

### Steps to reproduce

使用 2.4.12 编辑器版本，新建 Hello World 项目，直接发布运行，报错如图所示。

**Comment by dumganhar** [comment]
Hi, it's xcode 15 broke something.
For a workaround, you could add a link flag `-ld_classic` in xcode's `Build Settings -> Linking - General -> Other Link Flags `.

**Comment by Maxize** [comment]
> Hi, it's xcode 15 broke something. For a workaround, you could add a link flag `-ld_classic` in xcode's `Build Settings -> Linking - General -> Other Link Flags `.

it doesn't work.

![Snipaste_2023-11-02_18-11-39](https://github.com/cocos/cocos-engine/assets/3771476/99085f80-e786-4940-8f88-b4726e9214d3)

**Comment by dumganhar** [comment]
@Maxize Try `-Wl,-ld_classic` instead.

**Comment by Maxize** [comment]
`-ld_classic` Add it to the end and it will run successfully.
@dumganhar Thanks!
