### ISSUE TITLE
Bug: node world transforms retrieved from immediately loaded scene are incorrect

### ISSUE THREAD

**Issue by shrinktofit** [cocos/cocos-engine#16352]
If a scene is not runed, world transforms retrieved from nodes within the scene are incorrect.

Reproduce steps:

- Author a scene but don't open or run it.

- Load that scene through asset manager.

- Try to retrieve transforms of nodes under that scene.

**Comment by dumganhar** [comment]
Close this issue since it was fixed in 3.8.2
