### ISSUE TITLE
Customize scene view shortcut

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#16389]
### Use Case

Hello,
It will be cool if we could customize shorts in the scene view when we navigate with "Right Click + Key"

![image](https://github.com/cocos/cocos-engine/assets/758680/6652862d-645b-46de-a5ed-9688c089432c)

### Problem Description

I'm using AZERTY Layout not a QWERTY layout like all french developers.

### Proposed Solution

Add there shortcuts in tjhe shortcuts window

![image](https://github.com/cocos/cocos-engine/assets/758680/c26c58e4-a8d5-451a-bb56-2428eb0e4449)

### Alternatives Considered

Change keyboard layout but we are not familiar with QWERTY layout for typping text.

**Comment by knoxHuang** [comment]
Thanks for the feedback, this feature will make it to 3.8.5
