### ISSUE TITLE
Collider/Trigger event problem in Windows/Android Build

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16394]
### Cocos Creator version

3.8.0

### System information

Windwos 10

### Issue description

https://discuss.cocos2d-x.org/t/collider-trigger-event-problem-in-windows-android-build/59615

### Relevant error log output

-

### Steps to reproduce

Downloading the demo and running it in a web browser shows that physical events can be triggered normally. However, when running on Windows or Android, physical events are unable to be triggered properly.

### Minimal reproduction project

[59615.zip](https://github.com/cocos/cocos-engine/files/12852345/59615.zip)

**Comment by minggo** [comment]
I tested in v3.8.3. It works on macOS and android.

**Comment by zhefengzhang** [comment]
The previous demo did not explain the problem correctly, so you need to use the new demo test:
[59615.zip](https://github.com/cocos/cocos-engine/files/14832992/59615.zip)

**Comment by minggo** [comment]
Can work with v3.8.3 on macOS too.
