### ISSUE TITLE
Physics2D: Joint2D should not rely on Collider2D to work

### ISSUE THREAD

**Issue by lealzhan** [cocos/cocos-engine#16414]
### Use Case

https://github.com/cocos/cocos-docs/issues/2790

### Problem Description

 Joint2D should not rely on Collider2D to work. When the node has a Joint2D component, engine now require the node to have a Collider2D component to make the Joint2d to work, this is inappropriate.

### Alternatives Considered

.

**Comment by minggo** [comment]
I don't find joint2d relies on collider.
