### ISSUE TITLE
cacheDir in cacheManager not correct when inside wechat develop tools (init twice)

### ISSUE THREAD

**Issue by Yuki001** [cocos/cocos-engine#16423]
### Cocos Creator version

3.7.3

### System information

window10

### Issue description

When i use wechat minigame develop tools , I found some error with wroing gamecache directory path . For example : 
http://usr/http:/usr/gamecaches/cachelist.json 
and all game cache operation reports error because this path error.

The reason for this bug is inside cache-manager.js in platforms/adapters .at cache-manager init : 
this.cacheDir = getUserDataPath() + '/' + this.cacheDir; 
This statement is called twice in wechat minigame develop tools. Add 2 userDataPath at the front of cacheDir.

So i fix this bug by add a variable 
cacheDirName : 'gamecaches',
And change this statement to : 
this.cacheDir = getUserDataPath() + '/' + this.cacheDirName;

3 files should be changed : 
engine/platforms/minigame/common/engine/cache-manager.js
engine/platforms/native/engine/jsb-cache-manager.js
engine/platforms/runtime/common/engine/cache-manager.js

and need to run bundle-adapter to update the bin/adapter files.

### Steps to reproduce

In wechat minigame develop tools

**Comment by qiuguohua** [comment]
> This statement is called twice in wechat minigame develop tools. 

Do you know why it's called twice?

**Comment by Yuki001** [comment]
> > This statement is called twice in wechat minigame develop tools.
> 
> Do you know why it's called twice?

I init assetManager manually in my Resource Manager, then i find it have be inited inside engine code. may be i misunderstand the assetManager doc for init it.
