### ISSUE TITLE
property starts with "_" are not displayed in the Inspector

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#16429]
### Cocos Creator version

3.8.0

### System information

Windows 11

### Issue description

property starts with "_" are not displayed in the Inspector

`@property(Button) private _nextLevelButton: Button = null!;`

### Steps to reproduce

Create any property like this

`@property(Button) private _nextLevelButton: Button = null!;`
![image](https://github.com/cocos/cocos-engine/assets/758680/8d8aec98-0be3-4e7d-9518-553d4e1e99f8)
![image](https://github.com/cocos/cocos-engine/assets/758680/33b0a14d-e24f-43e4-99ab-dda6fc50bc35)

**Comment by wuzhiming** [comment]
Yes, if a property starts with _ , we consider it a private variable and it won't be displayed in the inspector.
