### ISSUE TITLE
iOS AudioEngineImpl 析构 崩溃

### ISSUE THREAD

**Issue by KChengYang** [cocos/cocos-engine#16435]
### Cocos Creator version

2.4.7

### System information

iphone13 16.3

### Issue description

iOS AudioEngineImpl 析构 崩溃 如下图所示：
<img width="826" alt="企业微信截图_b0632c6e-f56a-408c-aeb8-0af7bb595184" src="https://github.com/cocos/cocos-engine/assets/78268984/ed86cdf5-f92a-4615-9035-3bfaddf173d1">

### Steps to reproduce

![image](https://github.com/cocos/cocos-engine/assets/78268984/09584dc4-7c2f-42db-8ffd-d1f5515e5dbb)
![image](https://github.com/cocos/cocos-engine/assets/78268984/6ed89819-1063-48b7-ad35-b1a0b0db86dd)
我们是将游戏嵌入到原生的App，Cocos游戏退出后会销毁整个Application及其他对象（除了v8引擎）。销毁过程大概如下图所示，大致是参考这篇文章修改的。https://forum.cocos.org/t/cocos2-x/98806

**Comment by minggo** [comment]
Please use english in future. Engine is not designed to be embedded into an application. You should fix it by yourself.
