### ISSUE TITLE
3.8.1 Mesh Compression if selected - Encoding, can cause model display to be abnormal

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16437]
### Cocos Creator version

3.8.1

### System information

Windows10

### Issue description

<img width="1093" alt="企业微信截图_13d5a380-b73d-453c-8d3c-e2e3ac075c1c" src="https://github.com/cocos/cocos-engine/assets/35944775/c775d803-9152-4dff-963e-e8cc89cfe48c">

### Steps to reproduce

--

### Minimal reproduction project

[20231025001.zip](https://github.com/cocos/cocos-engine/files/13161724/20231025001.zip)

**Comment by knoxHuang** [comment]
是引擎那边代码没有对 renderingSubMeshes 进行判空

<img width="1081" alt="企业微信截图_34afc1d1-2bea-452d-83c1-8a5d798f0537" src="https://github.com/cocos/cocos-engine/assets/7564028/2545d613-eb85-4b94-be15-6e0f2a671c94">

为什么代码不会提示报错是因为返回值用了 !

<img width="582" alt="image" src="https://github.com/cocos/cocos-engine/assets/7564028/87838488-8454-4aec-8b0a-359bad92a0d0">

**Comment by minggo** [comment]
It is fixed in https://github.com/cocos/cocos-engine/pull/16539
