### ISSUE TITLE
spine.js 's file name doesn`t changed, but it's content is different

### ISSUE THREAD

**Issue by bofeng-song** [cocos/cocos-engine#16456]
### Cocos Creator version

3.8.0

### System information

Web

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/3078423/91f3527c-a2f8-4922-b74a-24f5c14836f0)

### Steps to reproduce

First, choose web-mobile platform and build.
Second, review cocos-js/spine*.js

**Comment by bofeng-song** [comment]
@dumganhar @PatriceJiang

**Comment by dumganhar** [comment]
https://forum.cocos.org/t/topic/153857/18?u=dumganhar
