### ISSUE TITLE
Input.EventType.MOUSE_MOVE isn't firing if the cursor is moving on Button

### ISSUE THREAD

**Issue by cad-icandy** [cocos/cocos-engine#16454]
### Cocos Creator version

3.6.2

### System information

macOS v12.6

### Issue description

As title described, I have a **Button** component on screen, then have another script and subscribe to Input.EventType.MOUSE_MOVE

```
input.on(Input.EventType.MOUSE_MOVE, this.onMouseMove, this);

private onMouseMove(event: EventMouse) {
        console.log(event.getLocation());
}
```

I noticed the mouse move event isn't firing when the mouse cursor is moving on a Button.

Isn't that input events should be the top priority and shouldn't be interrupted by NodeEventType?

### Steps to reproduce

Create an empty project.

Add a UI **Button** on scene

Create a new Component script and add the following codes into the script

```
start() {
        input.on(Input.EventType.MOUSE_MOVE, this.onMouseMove, this);
}

private onMouseMove(event: EventMouse) {
        console.log(event.getLocation());
}
```

Run the scene, and observe browser's console and you won't see the onMouseMove is firing when the cursor is on Button

**Comment by cad-icandy** [comment]
It should be related to this issue
https://forum.cocos.org/t/topic/148290/8

**Comment by minggo** [comment]
It is because, when mouse pointer is on a UI element, the mouse event is not handled, only handle ENTER and LEAVE event. Yep, it seems it is strange. If you want to listen the mouse move event, you can add the script in canvas, and do it like
```
this.node.on(Input.EventType.MOUSE_MOVE, this.onMouseMove, this);
```

**Comment by minggo** [comment]
In Input._emit(), if event is handled by PointorEventDispatcher(when cursor is on Button, it will handle the event), then Button will not receive MOUSE_MOVE event any more.

**Comment by minggo** [comment]
I don't want to change the implementation `Input._emit()` as it may trigger other issues.
