### ISSUE TITLE
On Android devices, when clicking on an EditBox, the input field jumps to the wrong position

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16462]
### Cocos Creator version

3.8.1

### System information

Android12

### Issue description

![wecom-temp-286159-cd11a39d3a1bb4ed20fbca3482a7dd4b](https://github.com/cocos/cocos-engine/assets/35944775/bf3b6362-818c-47d2-8438-af030824fcd0)

### Steps to reproduce

-

**Comment by bofeng-song** [comment]
On devices with higher API levels, the system will handle the displacement of the rootView itself. Devices that have been processed will modify the bottom value in mFrameOffsets. In the source code, the bottom value corresponds to getSystemWindowInsetBottom.
