### ISSUE TITLE
Custom Pipeline

### ISSUE THREAD

**Issue by whaqzhzd** [cocos/cocos-engine#16466]
### Cocos Creator version

3.8.1

### System information

ALL

### Issue description

Now when starting the 3.8.1 custom pipelines one after another, the data of each item has improved too significantly compared to the built-in pipelines. 

When using the built-in pipelines, the profile data is as follows:
![image](https://github.com/cocos/cocos-engine/assets/16913061/724f2db5-e128-4227-aa8c-280f050e1598)

When we enable the Custom pipelines, the data of each item is as follows:
![image](https://github.com/cocos/cocos-engine/assets/16913061/c4746087-e5aa-4182-8ea4-b3e2853fd55f)

The pipeline settings are as follows, no post-processing has been enabled yet.
![image](https://github.com/cocos/cocos-engine/assets/16913061/499dc8f0-f5fd-42a9-a3bb-d45e728aa762)

I have reported this issue on the 3.8.0 forum before. At that time, after optimization, the situation was alleviated to some extent. But when I updated to 3.8.1, this problem occurred again.

The related 3.8.0 forum post is as follows:
https://forum.cocos.org/t/topic/149932/386?u=544430497

### Steps to reproduce

-

**Comment by whaqzhzd** [comment]
I have learned that version 3.8.4 will designate the new pipeline as the default, and it appears that the issue has been resolved. Is the performance of the new default pipeline superior to that of the classic pipeline, particularly on devices with limited capabilities such as iOS and WeChat games? This is a crucial consideration for game engines.

**Comment by star-e** [comment]
We will continue to improve the performance of the `builtin-pipeline`, currently it should be on a par with the `legacy-pipeline`.

We have done some optimizations compared with the `legacy-pipeline`.

1. The new `builtin-pipeline` will discard depth-stencil buffer by default, which might imply better performance on mobile platform.
2. We have supported MSAA on all native platforms, and utilized on-chip memory on mobile platforms. So it will have better image-quality with relatively low performance cost (it might be free on some hardware). 

The new `builtin-pipeline` also inherited several post-process features from the previous version. These features are optimized and redundant draw calls are totally removed.

**Comment by whaqzhzd** [comment]
I can't wait!

**Comment by star-e** [comment]
According to our performance test cases, the issue should have been solved in 3.8.4.
