### ISSUE TITLE
3.8引擎运行久了，无法预览

### ISSUE THREAD

**Issue by yuhank97** [cocos/cocos-engine#16488]
### Cocos Creator version

3.8.1

### System information

win10

### Issue description

![微信截图_20231108183615](https://github.com/cocos/cocos-engine/assets/66947856/0d98d2d6-5ebc-4d38-bde7-d3700140d93e)

### Steps to reproduce

我工作运行几个小时后，就无法预览了

**Comment by dumganhar** [comment]
We fixed a preview issue in v3.8.2 . Have a try when it is released.
