### ISSUE TITLE
Activation Email Not Received for Account Creation

### ISSUE THREAD

**Issue by Harikrishna3** [cocos/cocos-engine#16486]
### Cocos Creator version

CocosDashboard_2.0.1

### System information

windows 11

### Issue description

I am writing to report an issue related to the activation email for my account creation. I have recently signed up for an account on your platform, but I have not received the activation email necessary to complete the registration process.

Additional Information:

I have checked my email's spam folder, and the activation email is not there.
I have confirmed that the email address provided during registration is correct.
I have not received any error messages during the registration process.

### Relevant error log output

![image](https://github.com/cocos/cocos-engine/assets/86600101/bc091372-06bc-4813-bef9-9a6aed0ef50b)

![image](https://github.com/cocos/cocos-engine/assets/86600101/e89ca5b7-5918-40b3-8d26-349c5d20df8b)

### Steps to reproduce

I completed the account registration process by providing my email address and other required information.
I waited for the activation email to arrive, but it did not appear.

**Comment by minggo** [comment]
Thanks for feedback. I reflected this issue to the guy who takes charge or it.

**Comment by minggo** [comment]
@Harikrishna3 I was told that it is fixed. Could you please try again? And i will close this issue, please reopen it if the issue still exists.
