### ISSUE TITLE
Billboard Component's Texture appears transparent and barely visible in the 3D space.

### ISSUE THREAD

**Issue by MrZak-dev** [cocos/cocos-engine#16504]
### Cocos Creator version

3.8.1

### System information

MacOS

### Issue description

I am trying to use the Billboard component to display an image that always facing the camera .
the Texture appears to be affected by the environment lights and Colors.

The Texture becomes **TRANSPARENT** and barely visible .

https://github.com/cocos/cocos-engine/assets/27586088/a5b5af4e-b246-4386-8406-1e582ff92b1f

### Steps to reproduce

- Create a 3D Project
- Add a Node with a Billboard Component
- Assign a Texture and run the Project 

### Minimal reproduction project

[billboard-issue.zip](https://github.com/cocos/cocos-engine/files/13322064/billboard-issue.zip)

**Comment by MrZak-dev** [comment]
for reference only, this is how a billboard works in the Godot engine.



https://github.com/cocos/cocos-engine/assets/27586088/47843ef0-84ad-41ca-a4d0-30007b8159e8

**Comment by star-e** [comment]
![image](https://github.com/cocos/cocos-engine/assets/13654656/a4ce0237-9ba6-4fc3-8a01-8815cc89b48f)
User can choose technique now.
(default) Technique 0 will use additive blending, which causes over-bright billboard.
