### ISSUE TITLE
Some Spine animations have rendering issues after setting the cache mode

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16510]
### Cocos Creator version

3.8.1

### System information

Web

### Issue description

Some Spine animations have rendering issues after setting the cache mode, if set to RealTime, there will be no issues.
This issue did not exist in version 3.7.4.

### Steps to reproduce

Download the demo project, open it in Cocos Creator, and run the web preview to discover the issue.

### Minimal reproduction project

[20231116001.zip](https://github.com/cocos/cocos-engine/files/13371662/20231116001.zip)

**Comment by bofeng-song** [comment]
fix at
https://github.com/cocos/cocos-engine/pull/16516
https://github.com/cocos/cocos-engine/pull/16519

**Comment by zhefengzhang** [comment]
If you load the Spine prefab and add it to the scene, the issue will still occur.

[20231115001.zip](https://github.com/cocos/cocos-engine/files/13407013/20231115001.zip)
