### ISSUE TITLE
component property in Component.EventHandler is not working

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#16517]
### Cocos Creator version

3.8.1

### System information

Windows 10

### Issue description

We want to add an click event in the Button component in code but the **component** property doesn't set the component parameter.

We have to use the **_componentName** property instead but this property seems deprecated

**Not working:**
```
        const event2 = new Component.EventHandler();
        event2.target = this.node;
        event2.component = 'Test_Button';
        event2.handler = "onClick";
        event2.customEventData = "";

        this.getComponent(Button).clickEvents.push(event2);
```

![image](https://github.com/cocos/cocos-engine/assets/758680/0c52be21-8822-4de4-8e3a-41520ffe6e3f)

**Working**

```
        const event2 = new Component.EventHandler();
        event2.target = this.node;
        event2._componentName = "Test_Button";
        event2.handler = "onClick";
        event2.customEventData = "";

        this.getComponent(Button).clickEvents.push(event2);
```

![image](https://github.com/cocos/cocos-engine/assets/758680/ed7fc491-6895-4e94-bc17-4368b1d24369)

### Steps to reproduce

Create a Button in the 2D Canvas and a script in this node with this code:

```
start() {
        const event2 = new Component.EventHandler();
        event2.target = this.node;
        event2.component = 'Test_Button';
        event2.handler = "onClick";
        event2.customEventData = "";

        this.getComponent(Button).clickEvents.push(event2);
}
public onClick(){
}
```

**Comment by minggo** [comment]
It seems it is fixed in latest codes. No matter using `event2._componentName = "Test_Button";` or using `event2.component = 'Test_Button';`. Can view correct result if manually adding `Click Events`.

But i have questions about this issue:
- Did you mean the click event should be shown automatically in editor if adding codes as above?
- If you manually adding click events in editor, then why need to do it in codes?

**Comment by BenoitFreslon** [comment]
I developed a component for all buttons. It makes sounds when the player click on the button. So, I want to add the click event in code.

**Comment by minggo** [comment]
> Did you mean the click event should be shown automatically in editor if adding codes as above?

Is it the issue?

**Comment by BenoitFreslon** [comment]
The issue is: the **component** property doesn't work and should be work. The **_componentName** property works but shouldn't be accessible > https://docs.cocos.com/creator/2.2/api/en/classes/Component.EventHandler.html
If the component property works well now it's OK.

And yes, the component name should be visible in the Inspector too. I didn't check the code on the last version of CC.

**Comment by minggo** [comment]
> And yes, the component name should be visible in the Inspector too

Adding component in codes can not be shown in the Inspector.

> If the component property works well now it's OK.

Yep, you can check it with latest version. I will close this issue, and please open it again if you find it also has problem in latest engine version. And it is better to provide a demo to make sure we have the same context. Thanks.
