### ISSUE TITLE
When the number of simultaneous audio tracks played exceeds the value of AudioPlayer.maxAudioChannel, the game background music is automatically turned off.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16522]
### Cocos Creator version

3.8.1

### System information

Windows10，Web

### Issue description

When the number of simultaneous audio tracks played exceeds the value of AudioPlayer.maxAudioChannel, the game background music is automatically turned off.

### Relevant error log output

-

### Steps to reproduce

Download the demo and run the project. Play the background music first in the web browser, then play all the sound effects. Note if the background music disappears.

### Minimal reproduction project

[20231117001.zip](https://github.com/cocos/cocos-engine/files/13408121/20231117001.zip)

**Comment by bofeng-song** [comment]
Background audio should call audiosource's play, but effect audio should call playOneShot
@zhefengzhang

**Comment by zhefengzhang** [comment]
ok
