### ISSUE TITLE
RigidBody2D.getInertia() is always zero

### ISSUE THREAD

**Issue by ebenmo** [cocos/cocos-engine#16536]
### Cocos Creator version

3.8.1

### System information

win 10, chrome

### Issue description

RigidBody2D.getInertia() is always zero, however getMass() is not zero

### Steps to reproduce

create a node of sprite. add RigidBody2D Component. Also add BoxCollider2D Component or CircleCollider2D Component.
set BoxCollider2D Component correct (size such as 32 * 32) or set CircleCollider2D Component correct (radius such as 32)

in script, try this:
let body = this.node.getChildByName(“Sprite”).getComponent(RigidBody2D);
console.log(“mass”, body.getMass());
console.log(“inertia”, body.getInertia());

the mass is not zero but the inertia is zero.
the correct inertia of CircleCollider2D should be 
massData->I = massData->mass * (0.5f * m_radius * m_radius + b2Dot(m_p, m_p));

**Comment by ebenmo** [comment]
Is anyone can tell me the progress of fixing this bug?

**Comment by ebenmo** [comment]
@minggo @jareguo needs help, please

**Comment by minggo** [comment]
Could you please provide a demo?

**Comment by ebenmo** [comment]
@minggo , ok, I just create a new project by cocos creator 3.8.1. 
[NewProject_2.zip](https://github.com/cocos/cocos-engine/files/13558484/NewProject_2.zip)
The zip file is whole project.
the source code screenshot and the browser output is attached below
![2](https://github.com/cocos/cocos-engine/assets/7875807/0c7d2fda-6cad-4bab-9b91-3908f648cf2e)
![3](https://github.com/cocos/cocos-engine/assets/7875807/e6b64ce7-2bfa-472d-ab15-2a9bc134777e)

**Comment by ebenmo** [comment]
by the way, i also create a same project by cocos creator 2.4.12. the inertia is not zero, but the angularVelocity is zero.
[NewProject.zip](https://github.com/cocos/cocos-engine/files/13558747/NewProject.zip)
he source code screenshot and the browser output is attached below
![4](https://github.com/cocos/cocos-engine/assets/7875807/ac3b3b51-c615-4010-a3c2-4de1eb47db60)
![5](https://github.com/cocos/cocos-engine/assets/7875807/3b7f560a-1089-452d-8e65-f7baa8e9a0a8)

**Comment by ebenmo** [comment]
@minggo

**Comment by minggo** [comment]
Ok, thanks.

**Comment by minggo** [comment]
@ebenmo i fixed it in https://github.com/cocos/cocos-engine/pull/16566.
