### ISSUE TITLE
CopyBuffersToTexture Error In Debug Mode

### ISSUE THREAD

**Issue by kaxifakl** [cocos/cocos-engine#16554]
### Cocos Creator version

3.7.4

### System information

Android Ios

### Issue description

I am trying to copyTextureWithImageAsset like this;
![image](https://github.com/cocos/cocos-engine/assets/63728902/c135399d-568a-41be-a271-803e312a5c73)
But it don't work with ASTC image asset in DEBUG apk;
And error in `CC_ASSERT(offsetX % blockWidth == 0);`
![image](https://github.com/cocos/cocos-engine/assets/63728902/632a0642-e7e8-48e3-be98-5850f6c91174)

It works in RELEASE apk;
So why `DeviceValidator.cpp` need `CC_ASSERT` offset and size?
Is there any render device don't support astc image whitch not size or offset powed of 4(blockSize)?

### Steps to reproduce

.....

**Comment by kaxifakl** [comment]
@jareguo need help

**Comment by jareguo** [comment]
Calling @minggo

**Comment by star-e** [comment]
Simple explanation: 
ASTC is block compressed, so we should upload by encoded blocks, whose pixel offset/size is multiple of block size.

Detailed explanation:
ASTC is block compressed, such as 4x4.
Assume we have a 8x8 texture, with ASTC4x4.
There will be 2x2 encoded blocks (2 rows and 2 columns) and the uploading buffer will contain these 4 encoded blocks.
When texture copy destination offset is multiple of block width/height, there will be no issue.
When texture copy destination offset is not multiple of block width/height, such as offset = (2, 2), size = (4, 4)
It covers more encoded blocks.
In offset = (2, 2), size = (4, 4) case, when uploading 4x4 pixels, it actually covers all encoded blocks.
So the whole 8x8 pixels should be uploaded.

As a result, user should always upload block-compressed textures block by block.

@kaxifakl

**Comment by kaxifakl** [comment]
thanks!

**Comment by kaxifakl** [comment]
Will it cause render error, if used astc image witch size is not multi of block?

**Comment by star-e** [comment]
> Will it cause render error, if used astc image witch size is not multi of block?

Image size can be arbitrary, however size of power of two is recommended.

When size is not multiple of block, ceil is used to calculate number of encoded blocks.
For example, 6x6 pixels of ASTC4x4, 4 encoded blocks is needed for uploading.

**Comment by star-e** [comment]
These asserts are requirements, not bugs.
