### ISSUE TITLE
Add ASM options for building web version

### ISSUE THREAD

**Issue by iwae** [cocos/cocos-engine#16550]
### Use Case

a lot developers working on playable AD, which have problems with spine WASM to build one single HTML page for playable AD, add ASM option could solve it 

### Problem Description

a lot developers working on playable AD, which have problems with spine WASM to build one single HTML page for playable AD

### Alternatives Considered

add ASM option for web build could solve it

**Comment by minggo** [comment]
fixed in https://github.com/cocos/cocos-engine/pull/16679
