### ISSUE TITLE
Can the engine support Apple's latest visionOS?

### ISSUE THREAD

**Issue by BlackJack757** [cocos/cocos-engine#16567]
### Use Case

I encountered an issue while integrating Cocos engine on visionOS in Xcode 15.

### Problem Description

building for 'visionOS-simulator', but linking in object file (/Libs/external/glslang/libGenericCodeGen.a[arm64][2](CodeGen.cpp.o)) built for 'iOS'

### Alternatives Considered

无

**Comment by minggo** [comment]
Cocos XR will support it instead of engine.
