### ISSUE TITLE
Box2D's RigidBody2D.angularVelocity is wrong

### ISSUE THREAD

**Issue by ebenmo** [cocos/cocos-engine#16579]
### Cocos Creator version

3.8.1

### System information

Windows10

### Issue description

RigidBody2D.angularVelocity is wrong since its get and set are not Idempotent，box2d-wasm also has the same problem.
![1](https://github.com/cocos/cocos-engine/assets/7875807/3da4e7b0-f64c-45aa-a002-b20c5916bc5b)

### Steps to reproduce

let body = this.node.getChildByName(“Sprite”).getComponent(RigidBody2D);
let angularVelocity  = body.angularVelocity;
console.log(angularVelocity);
body.angularVelocity = angularVelocity;
console.log(body.angularVelocity);

**Comment by ebenmo** [comment]
@minggo needs help

**Comment by minggo** [comment]
Could you please provide a demo to make sure i do the same operations as did .

**Comment by ebenmo** [comment]
the problem is RigidBody2D.angularVelocity's get result is degree but the set result is radian. it‘s inconsistent. 
the source code 
setAngularVelocity (v: number): void {
        this._body!.SetAngularVelocity(v);
}

may be
setAngularVelocity (v: number): void {
        this._body!.SetAngularVelocity(toRadian(v));
}
@minggo

**Comment by minggo** [comment]
> RigidBody2D.angularVelocity is wrong since its get and set are not Idempotent

Did you mean only `not Idempotent` has the problem?

**Comment by minggo** [comment]
> the problem is RigidBody2D.angularVelocity's get result is degree but the set result is radian. it‘s inconsistent. the source code setAngularVelocity (v: number): void { this._body!.SetAngularVelocity(v); }
> 
> may be setAngularVelocity (v: number): void { this._body!.SetAngularVelocity(toRadian(v)); } @minggo

Got it, i will check why it implemented like this. And may be should add new interface to keep compatible.

**Comment by ebenmo** [comment]
ok

**Comment by minggo** [comment]
I found the codes in rigid-body-2d.ts
```typescript
get angularVelocity (): number {
        if (this._body) {
            this._angularVelocity = this._body.getAngularVelocity();
        }
        return this._angularVelocity;
    }
    set angularVelocity (v: number) {
        this._angularVelocity = v;
        if (this._body) {
            this._body.setAngularVelocity(v);
        }
    }
```
The logic is error, as `this._angularVelocity` will be assigned to degree in getter. So i will unify it to use radius in getter and setter.

**Comment by ebenmo** [comment]
fine

**Comment by minggo** [comment]
Fixed in https://github.com/cocos/cocos-engine/pull/16580.

**Comment by ebenmo** [comment]
@minggo I just found that if this._angularVelocity use radian as default, then the code in line 306, physics-world.ts should remove toRadian too. please check this again, thank you.

![1](https://github.com/cocos/cocos-engine/assets/7875807/cc74499f-3d89-4ab8-aa34-bf2946905a3e)

**Comment by minggo** [comment]
Yep, you are right. I fixed it in https://github.com/cocos/cocos-engine/pull/16611

**Comment by ebenmo** [comment]
ok
