### ISSUE TITLE
The zip compression feature for building Android projects with encrypted scripts does not reduce the package size.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16595]
### Cocos Creator version

3.8

### System information

All

### Issue description

Test with a project that includes a script. Testing in version 2.4.x has an effect, but testing in version 3.x does not.

### Steps to reproduce

-

**Comment by liuhy-liu** [comment]
https://github.com/cocos/3d-tasks/issues/18033  在这个issue下跟踪
