### ISSUE TITLE
[Spine] Shall we use `this.clearTracks()` instead of `this.clearTrack(0)`

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16604]
https://github.com/cocos/cocos-engine/blob/1bdd90b5d384a90c05fb2b2b5e29f486158b56d2/cocos/spine/skeleton.ts#L723

Shall we use `this.clearTracks()` instead of `this.clearTrack(0)`? 

or pass trackIndex to clearAnimation(...) ? 

when I use 
```
const a = spine.setAnimation( 0 ,  'run');
const b = spine.setAnimation( 1 ,  'idle');

spine.clearAnimation()
```
the `clearAnimation()` only  clear  the first track only , the others will make some mistakes.

-------

the logic of  `clearAnimation()` like the `ClearAnimationSetupPose()` of Spine offical Runtime.
the code of `ClearAnimationSetupPose()` : 

[(https://github.com/EsotericSoftware/spine-runtimes/blob/dd81e4b0629cad4571619c877609357e2fd697c1/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Asset%20Types/SkeletonDataAssetInspector.cs#L1024)](https://github.com/EsotericSoftware/spine-runtimes/blob/dd81e4b0629cad4571619c877609357e2fd697c1/spine-unity/Assets/Spine/Editor/spine-unity/Editor/Asset%20Types/SkeletonDataAssetInspector.cs#L1024)

<img width="530" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/917b0b8e-d830-430c-9970-7913c3ee6b38">

**Comment by minggo** [comment]
It sounds reasonable. But in order to keep compatible, I think it is better to add a new function named clearAnimations.

**Comment by finscn** [comment]
> It sounds reasonable. But in order to keep compatible, I think it is better to add a new function named clearAnimations.

那现在这个方法最好支持传参 , 不传默认是0 . 否则还是会有潜在问题.

PR已更新.

**Comment by minggo** [comment]
嗯嗯，这样可以。不过 PR 有冲突了，还麻烦更新一下。

**Comment by finscn** [comment]
> 嗯嗯，这样可以。不过 PR 有冲突了，还麻烦更新一下。

已解决

**Comment by finscn** [comment]
> It sounds reasonable. But in order to keep compatible, I think it is better to add a new function named clearAnimations.

发现一个逻辑问题. 你这个说法其实不太对.

因为这个方法 并不是 clear 多个 动画.
它clear 的其实只是"当前动画", 以及这个动画对应的所有track.

叫 clearAnimations 并不合适.
