### ISSUE TITLE
Mobile WebGL app doesn't work on Android Chrome 120

### ISSUE THREAD

**Issue by tanioka-takeshi** [cocos/cocos-engine#16602]
### Cocos Creator version

3.6.1, 3.6.3, 3.7.4, 3.8.1

### System information

Chrome 120 on Android

### Issue description

device | os | web brower | web brower version | comment
-- | -- | -- | -- | -- 
Pixel 7a | Android 14 | Chrome | 120.0.6099.43 | Problem has occurred
Pixel 7a | Android 14 | Chrome | 120.0.6099.115 | Problem has occurred
Pixel 7a | Android 14 | Chrome Beta | 121.0.6167.7 | No problem 
Pixel 7a | Android 14 | Chrome Canary | 122.0.6181.0 | Problem has occurred 
Pixel 7a | Android 14 | Microsoft Edge | 119.0.2151.107 | No problem  
Pixel 7a | Android 14 | Firefox | 120.1.0 (Build #2015989146) | No problem  
Xperia 5Ⅱ | Android 12 | Chrome | 120.0.6099.43 | Problem has occurred 
Xperia 5Ⅱ | Android 12 | Chrome Beta | 121.0.6167.7 | No problem  
Xperia 5Ⅱ | Android 12 | Microsoft Edge | 119.0.2151.107 | No problem  
Xperia 5Ⅱ | Android 12 | Firefox | 120.1.0 | No problem  

### Relevant error log output

No error logs on Chrome console.

### Steps to reproduce

When you create a new project using the Hello World template and access an app built for Web Mobile using the Android Chrome browser (120), the screen turns black and stops after loading the Cocos logo.

For reference, the apps built with each editor version are shown below.
- https://aoizone.net/361/index.html
- https://aoizone.net/363/index.html
- https://aoizone.net/374/index.html
- https://aoizone.net/381/index.html

**Comment by minggo** [comment]
I have reflected the issue to google. And google found the reason: https://bugs.chromium.org/p/chromium/issues/detail?id=1511506. And it may be fixed in Jan. 2024.

It is a bug of chrome, so i will close this issue.
