### ISSUE TITLE
[XR]Can I use cocos on xr platform? like apple vision pro, meta quest2 or 3?

### ISSUE THREAD

**Issue by LuoLuoDev** [cocos/cocos-engine#16624]
### Use Case

Now i have made a demo game for my phone with cocos creator 3.7.2. Can I use cocos on xr platform like apple vision pro, meta quest2 or 3? I have found doc (https://docs.cocos.com/creator/manual/en/xr/project-deploy/ar-proj-deploy.html) , but i can not get a clear guide to adapting to Apple Vision Pro or Meta ?

### Problem Description

Now i have made a demo game for my phone with cocos creator 3.7.2. Can I use cocos on xr platform like apple vision pro, meta quest2 or 3? I have found doc (https://docs.cocos.com/creator/manual/en/xr/project-deploy/ar-proj-deploy.html) , but i can not get a clear guide to adapting to Apple Vision Pro or Meta ?

### Alternatives Considered

Maybe a clear guide for adapted devices list is needed. And Using Compositor Services can support vision pro device, you can refer apple doc (https://developer.apple.com/documentation/compositorservices/drawing_fully_immersive_content_using_metal?language=objc) @minggo sorry to cue at you, do you know if there is a plan to add cocos support to vision os with Compositor Services or other ways?

**Comment by QingliWang** [comment]
Hi, currently Cocos CreatorXR supports Meta quest2, has not test quest3 yet. 
For Apple VisionPro, there is a plan to support, and in progress.
About the device list, you can find it in the drop-down box of the build window.
FYI.

**Comment by LuoLuoDev** [comment]
Get it. Thanks for your reply. With the establishment of Apple's xr ecosystem, I believe that soon xr will develop rapidly, it's better to have a roadmap about XR!
