### ISSUE TITLE
Should we use the logic as same as `static cc.Color.fromHEX()` ?

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16632]
https://github.com/cocos/cocos-engine/blob/611d5ac4c841c7f45170b9afc250d19dec0ee38e/cocos/core/math/color.ts#L506

Should we use the logic as same as `static cc.Color.fromHEX()`

And another question :  `color.fromHEX()` doesn't change the  attributes `color.r/g/b/a` , why ?

**Comment by yanjifa** [comment]
https://github.com/cocos/cocos-engine/blob/611d5ac4c841c7f45170b9afc250d19dec0ee38e/cocos/core/math/color.ts#L330
It seems that color.r/g/b/a is unnecessary.

**Comment by yanjifa** [comment]
I think it can be changed like this.
```diff
@@ -152,10 +152,6 @@ export class Color extends ValueType {
             }
             hexNumber = hex;
         }
-        out.r = hexNumber >>> 24;
-        out.g = (hexNumber & 0x00ff0000) >>> 16;
-        out.b = (hexNumber & 0x0000ff00) >>> 8;
-        out.a = hexNumber & 0x000000ff;
         out._val = ((out.a << 24) >>> 0) + (out.b << 16) + (out.g << 8) + out.r;
 
         return out;
@@ -500,17 +496,11 @@ export class Color extends ValueType {
      * 十六进制颜色字符串应该以可选的 "#" 开头，紧跟最多 8 个代表十六进制数字的字符；<br/>
      * 每两个连续字符代表的数值依次作为 Red、Green、Blue 和 Alpha 通道；<br/>
      * 缺省的颜色通道将视为 0；缺省的透明通道将视为 255。<br/>
-     * @param hexString the hex string
+     * @param hexString the hex string or hex number
      * @returns `this`
      */
-    public fromHEX (hexString: string): Color {
-        hexString = (hexString.indexOf('#') === 0) ? hexString.substring(1) : hexString;
-        const r = parseInt(hexString.substr(0, 2), 16) || 0;
-        const g = parseInt(hexString.substr(2, 2), 16) || 0;
-        const b = parseInt(hexString.substr(4, 2), 16) || 0;
-        let a = parseInt(hexString.substr(6, 2), 16);
-        a = !Number.isNaN(a) ? a : 255;
-        this._val = ((a << 24) >>> 0) + (b << 16) + (g << 8) + (r | 0);
+    public fromHEX (hexString: string | number): Color {
+        Color.fromHEX(this, hexString);
         return this;
     }
```

**Comment by minggo** [comment]
I don't know the original design of this interface, but it seems it it changes Color._val and returns Color. Use static method is another choice, but i think both are ok, just for different design purpose.

> And another question : color.fromHEX() doesn't change the attributes color.r/g/b/a , why ?

It modifies Color._val, and Color.r/g/b/a is attracted from it. So it modified Color.r/g/b/a indirectly.

**Comment by finscn** [comment]
@minggo , 不建议关闭这个问题 . 如果 只更改 _val, 不更改 rgba, 会导致color对象内部存在不一致性. 这应该是一个bug.

目前看来  这个问题存在一些不确定性, 存在一些你也不知道的事情.  
在把这些不确定的 不明白的事情 搞明白之前, 不建议就这么稀里糊涂 得过且过的关闭这个issue.

**Comment by jareguo** [comment]
<img width="405" alt="image" src="https://github.com/cocos/cocos-engine/assets/1503156/c86f7c24-92ad-4609-8e84-a9a021dfa73c">

因为 rgba 都是 getset 而已
