### ISSUE TITLE
Fail to register to Cocos dashboard 

### ISSUE THREAD

**Issue by whiletrue111** [cocos/cocos-engine#16649]
### Cocos Creator version

3.7

### System information

windows10 

### Issue description

I am trying to register on the Cocos Dashboard with a new user account. No matter what email I use, I can't complete the registration. I found some similar tickets, but none of them address my specific issue. I added a comment here: https://github.com/cocos/cocos-docs/issues/2697.
I also haven't received any response on Discord, and I can't find any support email.

### Steps to reproduce

download cocose dashboard in windows 
try to register with gmail account 

### Minimal reproduction project

try to register in cocos dashboard with gmail account

**Comment by minggo** [comment]
I was told that, gmail may be blocked. What type of mail did you test?

**Comment by minggo** [comment]
Have you tried other type of mail? About the gmail issue, we are resolving it.

**Comment by whiletrue111** [comment]
Sorry im not going to open new email account i trust only gmail  . you need to resolved it with google  , if its blocked by gmail its not good sign ...  
Any way add option to skip registering .

**Comment by minggo** [comment]
We will not ignore gmail, just to let you have an option to register. We will solve it, of course.

**Comment by Polly2000** [comment]
Hello! Could you tell me what type of email to use for registration?

**Comment by minggo** [comment]
@Polly2000  I think all mail type should work, as i was told that gmail issue is fixed. Did you meet any problem?

**Comment by xrafaelcruz** [comment]
i tried with outlook and gmail and don't work, always fail

**Comment by Polly2000** [comment]
@minggo hey! after several attempts I registered with gmail :)

**Comment by minggo** [comment]
@Polly2000 glad to hear that. Did you do anything special? I think your experience is needed for others.

**Comment by Polly2000** [comment]
@minggo unfortunately no, I just tried to register many times, and one day it worked 🙄

**Comment by minggo** [comment]
Got it. I think it is because it is fixed as my colleague said.

**Comment by Polly2000** [comment]
@minggo thank you for the fix! 😊

**Comment by minggo** [comment]
It's ok. I will close this issue. And please reopen it if anyone meet it again.

**Comment by The-AlphaCat** [comment]
You should try registering on https://cocos2d-x.org/u/register
Totally avoid this https://auth.cocos.com/sign_up/register

**Comment by whiletrue111** [comment]
Thanks but i left this engine long time ago , it was fun when it was true c++ .
