### ISSUE TITLE
When using BMFont for Label and updating the string property, it can cause the opacity set by the UIOpacity component to be ineffective.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16647]
### Cocos Creator version

3.8.1

### System information

Windows 10

### Issue description

Label 组件属性面板
The property panel for the Label component
![image](https://github.com/cocos/cocos-engine/assets/35944775/7b65601c-65d3-459e-a7cb-9498c585582e)

The testing process is carried out on the native simulator of CocosCreator. First, set the opacity value to semi-transparent, then increase the text value. If an exception occurs, it can be observed that the semi-transparent effect originally set by the component will be ineffective.
在 CocosCreator 原生模拟器上测试的过程。首先设置半透明度的值，之后增加文字数值，如果发生异常，能看到原先组件设置的半透明效果会失效。
![GIF](https://github.com/cocos/cocos-engine/assets/35944775/ca9b5775-fffd-4e6c-ac6d-f534f6ac6ceb)

### Steps to reproduce

-

### Minimal reproduction project

[NewProject_LabelOpacity.zip](https://github.com/cocos/cocos-engine/files/13808121/NewProject_LabelOpacity.zip)

**Comment by minggo** [comment]
@qiuguohua i am not sure if it is fixed by you. Could you please help to check it?
