### ISSUE TITLE
Native platforms emit .wasm/.mem.bin assets which are unused.

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#16665]
Because spine module on native platform is implemented by C++ and JSB, we don't need the wasm/asmjs version.

Expect：No spine.wasm/ spine.mem.bin generated for native platforms.

![企业微信截图_085f4d76-4364-487a-b44b-5a482755ee64](https://github.com/cocos/cocos-engine/assets/493372/a4ad4b63-a369-4e0f-87bc-cf94df38f128)

**Comment by LuoLuoDev** [comment]
https://groups.google.com/g/v8-reviews/c/2q_SKUw5ufk/m/e6QOej87AAAJ 
<img width="1179" alt="image" src="https://github.com/cocos/cocos-engine/assets/2748395/c8bcceed-b427-4388-bb8b-b0b08928f7a2">
As above, I wonder that iOS native supports wasm ?  @dumganhar

**Comment by LuoLuoDev** [comment]
As we known, V8 in ios platform does not have jit and wasm is not supported either. We found that with the complexity of business logic, the execution efficiency of js on the iOS platform is also significantly reduced. We have compiled the v8 engine(version 9.1.269 at cocos engine 3.7.2) . And use instrument to view cpu consumption with jit compiled version and jitless compiled version.

<img width="1817" alt="image" src="https://github.com/cocos/cocos-engine/assets/2748395/15dc6ed5-fccb-4148-8084-14f4b805d2c9">
<img width="1811" alt="image" src="https://github.com/cocos/cocos-engine/assets/2748395/8855c402-777c-4db6-bb9e-eafc99034169">


I found that it costs much more cpu in jitless version than jit version. Can you give us some suggestions to improve performance degradation caused by V8 engine not having jit. @dumganhar @jareguo @minggo

**Comment by minggo** [comment]
There is not a good way to fix the jitless issue. If possible, you can implement these codes in c++, and used in javascript.

**Comment by dumganhar** [comment]
@LuoLuoDev 

> As above, I wonder that iOS native supports wasm ?

No. V8 wasm depends on JIT enabled.

**Comment by LuoLuoDev** [comment]
> There is not a good way to fix the jitless issue. If possible, you can implement these codes in c++, and used in javascript.

@minggo  Thank you for your professional reply, but I think our business logic is not particularly complex, but the CPU peak is still quite high, accompanied by frame drops and heat generation.
After research, I learned that currently only Apple's own WKWebview has JIT capabilities on the iOS platform. Although WKWebview is not a js runtime environment, js code can be executed through the evaluateJavaScript interface. I would like to ask whether cocos engine could replace the V8 engine on the iOS platform. Is it feasible to explain js programs for WKWebview? I think it is a big project. I would like to know if this is done, is there any other big resistance in cocos?

**Comment by minggo** [comment]
As i know, WKWebview uses jscore which is jit enabled, as WKWebview is implemented by apple. Other apps can use jscore too, but it is jit disabled. cocos supported jscore in early versions, but its performance is bad than v8 core. So cocos uses v8 for all platforms.

**Comment by LuoLuoDev** [comment]
> As i know, WKWebview uses jscore which is jit enabled, as WKWebview is implemented by apple. Other apps can use jscore too, but it is jit disabled. cocos supported jscore in early versions, but its performance is bad than v8 core. So cocos uses v8 for all platforms.

Thanks for your detailed answer, @minggo.  Yes, I agree with what you said. In addition, I am wondering if there is a way to combine cocos engine and WKWebview, such as using the [evaluateJavaScript](https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript?language=objc) interface to execute js code and use XMLHttpRequest to communicate with native to allow iOS cocos engine to use jit optimization ?

**Comment by LuoLuoDev** [comment]
> > As i know, WKWebview uses jscore which is jit enabled, as WKWebview is implemented by apple. Other apps can use jscore too, but it is jit disabled. cocos supported jscore in early versions, but its performance is bad than v8 core. So cocos uses v8 for all platforms.
> 
> Thanks for your detailed answer. Yes, I agree with what you said. In addition, I am wondering if there is a way to combine cocos engine and WKWebview, such as using the [evaluateJavaScript](https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript?language=objc) interface to execute js code and use XMLHttpRequest to communicate with native to allow iOS cocos engine to use jit optimization ? how about this idea?  Is it feasible from a technical perspective in cocos creator engine? @minggo @jareguo

**Comment by minggo** [comment]
If you want to use WKWebview, then you can just export the program as a web app which can run in WKWebView. But it turns to be a web game. I don't think WKWebview can communicate with cocos engine.
