### ISSUE TITLE
Error when expanding custom shortcut keys

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#16688]
### Cocos Creator version

3.8.2 beta

### System information

MacOS

### Issue description

package.json:
```json
    "shortcuts": [
      {
        "message": "restart_editor",
        "win": "ctrl+shift+r",
        "mac": "cmd+shift+r"
      }
    ]
```
engine logging:
`raw shortcut "shift+cmd+r" already exists in package "xxx"`
in edtior:
![image](https://github.com/cocos/cocos-engine/assets/28684663/d9e525c3-a3f0-42bf-84c4-883f6ac8f75c)
![image](https://github.com/cocos/cocos-engine/assets/28684663/7b8c8e11-7e1f-47d2-a27a-f24835fc3c0d)
Clicked "Remove" button but unable to remove.
The message was changed once during this period, so there is an invalid item.

### Steps to reproduce

.

**Comment by knoxHuang** [comment]
Feeling the feedback, the fix for this issue will go into version 3.8.5
