### ISSUE TITLE
3.8.1插件脚本"允许编辑器加载"功能运作不正常

### ISSUE THREAD

**Issue by FlatJ** [cocos/cocos-engine#16699]
### Cocos Creator version

3.8.1

### System information

window11

### Issue description

`console.log("AAAA")`
新建一个js脚本,内容为单个console.
到编辑器内选择 "导入为插件", 并勾选 ”允许编辑器加载“.  
预期结果是：编辑器控制应该打印 输出  AAAA。 
实际表现: 无任何输出.  
奇怪的点,  但把脚本的  "导入为插件" 取消后, 日志正常输出AAAA了( 取消导入 不应该不会跑这个脚本吗)，
当再次勾选 ”导入为插件“ 后，控制台还是不能正常打印AAAAA.

### Steps to reproduce

1.新建js脚本，脚本内容 `console.log("AAAA")`
2.设置该js脚本为插件脚本,并允许编辑器加载
3.控制台应该输出AAAA.
实际表现是:    当你取消勾选 ”导入为插件脚本“,会打印AAAA,    而勾选"导入为插件脚本"的时候 反而不会正常打印AAAA了.

**Comment by yanOO1497** [comment]
> 奇怪的点, 但把脚本的 "导入为插件" 取消后, 日志正常输出AAAA了( 取消导入 不应该不会跑这个脚本吗)

取消导入为插件并非取消导入，而是将为正常的项目脚本执行，因为我们依然兼容过去旧版本使用 js 编写项目脚本的项目。

正常勾选导入为插件并且勾选在编辑器内加载后没有正常打印的问题已在 3.8.3 修复，目前论坛版已发布（https://forum.cocos.org/t/topic/157509） 可以下载体验。
