### ISSUE TITLE
If a button is set to use scaling mode and the zoomScale is less than 1.0, clicking on the button's edge may not trigger the touch_end event.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16692]
### Cocos Creator version

3.8.1

### System information

Windows

### Issue description

If a button is set to use scaling mode and the zoomScale is less than 1.0, clicking on the button's edge may not trigger the touch_end event.
设置按钮使用缩放模式并且 zoomScale 小于 1.0，之后点击按钮边缘时不触发 touch_end 事件

https://github.com/cocos/cocos-engine/assets/35944775/c9391f05-7837-4274-9992-75ecc09a0c5c

I have solved this problem by modifying the engine code.

![image](https://github.com/cocos/cocos-engine/assets/35944775/2a98773f-20f0-4e6e-a890-cca2882faadf)

![image](https://github.com/cocos/cocos-engine/assets/35944775/69c03688-6804-42af-a8a5-fde4d66c924e)

### Relevant error log output

-

### Steps to reproduce

-

### Minimal reproduction project

[20240111002.zip](https://github.com/cocos/cocos-engine/files/13958323/20240111002.zip)

**Comment by minggo** [comment]
Can not modify like this. In this situation, i think should listen the touch cancel event.
