### ISSUE TITLE
Label word wrap not working with some Spanish words

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#1671]
Some words are not being wrapped in the right way. For example: debería.

There is a detailed explanation in this thread forum and a possible solution:
http://discuss.cocos2d-x.org/t/bug-label-1-5-label-word-wrap-not-working-on-words-with-accents/36913

I might be able to add the missing characters to the js library, and send a pull request. 
But Im not sure if thats ok, or you have plans to fix it.

Here you have a screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/24223792/26367877/5c012f28-3ff0-11e7-847f-90c1b99dac9a.png)

And a test project:
[LabelBug.zip](https://github.com/cocos-creator/engine/files/1023141/LabelBug.zip)

**Comment by zilongshanren** [comment]
@jrosich 
The solution provided in the forum is correct, feel free to open a PR and I will merge it, thanks.

**Comment by randalfien** [comment]
Hi, could you please add Slavic language accents, too?

Czech: ěščřžýáíéóúůťďňĚŠČŘŽÁÍÉÓÚŤ? 
Polish: żźśóńłęćąŻŹŚÓŃŁĘĆĄ

Thanks!

**Comment by blocksbarcelona** [comment]
Hi, I will wait a few days in case more people wants to add more languages before doing a new PR.

**Comment by blocksbarcelona** [comment]
I already added Czech and Polish. Thanks @randalfien!

**Comment by blocksbarcelona** [comment]
Hi, the bugfix has nit yet been added to release. 1.5.2 still have the bug.

**Comment by nantas** [comment]
> Hi, the bugfix has nit yet been added to release. 1.5.2 still have the bug.

It was merged into master branch which will be in 1.6 release.

**Comment by blocksbarcelona** [comment]
Ok. Thanks!
