### ISSUE TITLE
Support Tinify API to compress images and Auto Atlas as well

### ISSUE THREAD

**Issue by BenoitFreslon** [cocos/cocos-engine#16726]
### Use Case

Hello,
We need to optimize all assets in our game so we usually use tiny.png to compress all PNGs.

### Problem Description

 However when we use the Auto Atlas feature, we can't compress manually the image generated from the Auto Atlas.
 
 With CC compression:
![image](https://github.com/cocos/cocos-engine/assets/758680/6bd4c2e4-deb4-472b-a32a-c47ea300730b)
With tiny.png compression:
![image](https://github.com/cocos/cocos-engine/assets/758680/2adf5a2e-7091-460c-9929-40ffa2a678b1)

### Proposed Solution

Propose an option that uses the Tinify API to compress images.

### How it works

Sorry I don't know how to code this.

### Alternatives Considered

The only solution we found is to use Free Texture Packer with the Tinify API
![image](https://github.com/cocos/cocos-engine/assets/758680/61748667-fac4-4840-8bd4-97c584d6bdbe)

Or go to the build folder and find the image to manyally compress the Atlas with Tiny.png.

**Comment by wuzhiming** [comment]
you can go to cocos store and find the plugin，
like this https://store.cocos.com/app/search?name=%E5%9B%BE%E7%89%87%E5%8E%8B%E7%BC%A9
