### ISSUE TITLE
Potential bug in transformMat4Normal，but I’m not certain

### ISSUE THREAD

**Issue by guoyuandong** [cocos/cocos-engine#16720]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

![bug](https://github.com/cocos/cocos-engine/assets/55247160/f87cb908-c012-4a13-b0ec-a8e8773aaba6)
**I believe there shouldn’t be a division by w here, as it could potentially lead to incorrect direction of the final computed normal vector.I have indeed encountered this issue while actually using this API.As shown in the following figure：**
![bug2](https://github.com/cocos/cocos-engine/assets/55247160/c6378800-9c9e-43b3-8023-cf6b5f196e7f)
**We all know that translation transformations do not change the normal vector, but dividing by w might cause the direction of the normal vector to reverse.**

### Steps to reproduce

none

**Comment by minggo** [comment]
Sorry, i don't quite understand the issue. x, y, z are divided by w just to make it a normalized vector, i don't think there is an issue.

**Comment by guoyuandong** [comment]
> Sorry, i don't quite understand the issue. x, y, z are divided by w just to make it a normalized vector, i don't think there is an issue.

I will explain the problems I encountered while using this API.
![bug](https://github.com/cocos/cocos-engine/assets/55247160/e15c1cf4-4ce5-4579-be40-f0b107cb32f7)
I simply did a translation on the plane. If the value of w is negative, the direction of the transformed normal vector is opposite to the original, which I think is incorrect.For transforming the normal vector, I think treating w as 0 directly would suffice.

**Comment by guoyuandong** [comment]
> Sorry, i don't quite understand the issue. x, y, z are divided by w just to make it a normalized vector, i don't think there is an issue.

https://stackoverflow.com/questions/10596548/correctly-transforming-a-surface-normal
I think this post can explain the issue very well.

**Comment by minggo** [comment]
This function just transform and make the vector normalized, it has nothing about normal vector.

**Comment by guoyuandong** [comment]
> This function just transform and make the vector normalized, it has nothing about normal vector.

Sorry, it was my mistake to use this function in the wrong place.
