### ISSUE TITLE
duplicative `timeScale` of Spine Animation

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16728]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

when set  timeScale of Spine Animation , 
```
    set timeScale (value) {
        if (value !== this._timeScale) {
            this._timeScale = value;
            if (this._instance) {
                this._instance.dtRate = this._timeScale * timeScale;
            }
        }
    }
```
`dtRate` has multiplied  this._timeScale.

and `dt` has multiplied  this._timeScale again
```
    updateAnimation (dt: number): void {
        this.markForUpdateRenderData();
        if (EDITOR_NOT_IN_PREVIEW) {
            return;
        }
        if (this.paused) {
            return;
        }
        dt *= this._timeScale * timeScale;
        ... ...
```

the real timeScale will be    timeScale * timeScale.

### Steps to reproduce

set  any spine animation timeScale , the real timeScale will be `timeScale * timeScale`

**Comment by finscn** [comment]
我觉得正确做法应该是 

set timeScale 里  dtRate 直接等于  this._timeScale,

updateAnimation 里  dt 只乘以 timeScale.

**Comment by bofeng-song** [comment]
> 我觉得正确做法应该是
> 
> set timeScale 里 dtRate 直接等于 this._timeScale,
> 
> updateAnimation 里 dt 只乘以 timeScale.

这里的 timeScale使用的是外部的全局变量 ,默认是1。造成这个问题的原因是 wasm内部也重新计算了一次timeScale，造成乘以2次的问题，目前该版本只需要把instance timeScale的设置去掉即可。下个版本修复该问题
