### ISSUE TITLE
[3.8.2] Modify active of different canvas when previewing editor To switch rendering content, render residue appears

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16723]
### Cocos Creator version

3.8.2

### System information

Windows10

### Issue description

Modify active of different canvas when previewing editor To switch rendering content, render residue appears
编辑器预览时修改不同 canvas 的 active 用于切换渲染内容，会出现渲染残留

![企业微信截图_17071144302185](https://github.com/cocos/cocos-engine/assets/35944775/251ec565-1e30-472b-aa70-86c290bb34a9)

### Relevant error log output

-

### Steps to reproduce

https://github.com/cocos/cocos-engine/assets/35944775/f0e04296-f054-4e53-9866-26c8ee3b2730

### Minimal reproduction project

[20240205001.zip](https://github.com/cocos/cocos-engine/files/14161466/20240205001.zip)

**Comment by star-e** [comment]
![image](https://github.com/cocos/cocos-engine/assets/13654656/cf9b762a-5b7e-4fbb-ae68-18596f659284)
for the camera which is not rendering, the `camera.window.swapchain` is `null`.

**Comment by star-e** [comment]
![image](https://github.com/cocos/cocos-engine/assets/13654656/26102e84-ecf7-4ba0-a15d-b4659cc52ae4)
The cameras have different `_window: RenderWindow`.

**Comment by star-e** [comment]
![image](https://github.com/cocos/cocos-engine/assets/13654656/9972fee4-7c6f-444d-8f39-8b6251e7c81c)
It seems Editor will call `changeTargetWindow` on the first active camera, with the swapchain `65538`
![image](https://github.com/cocos/cocos-engine/assets/13654656/d6bdc4c2-d312-4652-8180-2fa0a2d74f38)
For the 2nd enabled camera, the swapchain will remain 'null'.

**Comment by star-e** [comment]
Fixed in 3.8.4
