### ISSUE TITLE
An API for getting  number of  ResolutionPolicy .

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16749]
### Use Case

通过 cc.view.getResolutionPolicy() 获得的是个对象, 但是从这个对象里,  开发者并不能直观的得到 适配模式是FIXED_WIDTH 还是 FIXED_HEIGHT 或者其他

ResolutionPolicy对象里应该记录自己对应的 number类型的标记.

希望提供一个类似这样的API: 

cc.view.getResolutionPolicy().flag 返回一个number , 对应 cc.ResolutionPolicy里的那些 number静态属性.

### Problem Description

无

### Alternatives Considered

无

**Comment by finscn** [comment]
@minggo  希望能看到这个需求.

**Comment by minggo** [comment]
加了 PR，调用 ResolutionPolicy.getContentStragety().stragety 可以获取到。

**Comment by minggo** [comment]
本来想在 ResolutionPolicy 加个方法的，但是没有想到好的名字。因为有了 ContentStrategy 类了。
