### ISSUE TITLE
AudioContext实列  在3.x的闭包里，外部无法获取，能爆露出来吗？

### ISSUE THREAD

**Issue by allenlzg** [cocos/cocos-engine#16758]
### Use Case

https://forum.cocos.org/t/topic/156100

### Problem Description

3.x外部无法获取AudioContext实列

### Alternatives Considered

可以放到 game里，跟 canvas一样 game.canvas

**Comment by minggo** [comment]
为什么需要这个 context 呢？直接用引擎提供的音频功能就好了。

**Comment by allenlzg** [comment]
因为我要录音，

**Comment by minggo** [comment]
引擎开放接口就得一直保持兼容。目前这不是引擎规划的功能，暂时不对外开放。

**Comment by minggo** [comment]
@bofeng-song 可以看下开放这个接口是否会对后续的兼容性带来问题。

**Comment by allenlzg** [comment]
好的，谢谢

**Comment by bofeng-song** [comment]
AudioContext 目前只有 web在使用，canvas是所有平台都存在的变量；
如果在game.ts 增加 AudioContext，其他平台未按照web-audio的标准实现，后期会有更多人有疑问

**Comment by allenlzg** [comment]
不加入game.ts,还放入sys.ts可以吗，我要做录屏录音相关的，必须调用这个接口！！！

**Comment by bofeng-song** [comment]
> 不加入game.ts,还放入sys.ts可以吗，我要做录屏录音相关的，必须调用这个接口！！！

可以考虑在AudioManager暴露一个record的接口，内部判断context是否存在，存在则执行录音。

**Comment by allenlzg** [comment]
好的，谢谢

**Comment by bofeng-song** [comment]
@allenlzg 如果没其他问题，准备关闭该issue了

**Comment by allenlzg** [comment]
没有了关闭把
