### ISSUE TITLE
[3.8.2] EditBox销毁后在屏幕尺寸变化时报错.

### ISSUE THREAD

**Issue by stollor** [cocos/cocos-engine#16750]
### Cocos Creator version

3.8.2

### System information

window10

### Issue description

EditBoxImpl在init里新增了View.instance.on('canvas-resize', this._resize, this); 但没有在合适时机off. 导致在监听到画布变化时报错

### Steps to reproduce

新建一个EditBox放在屏幕里,预览网页段. 改变分辨率.

**Comment by stollor** [comment]
复现时要销毁一次editbox

**Comment by qiuguohua** [comment]
https://github.com/cocos/cocos-engine/pull/16648
