### ISSUE TITLE
关于setRotationFromEuler和eulerAngles

### ISSUE THREAD

**Issue by Modo-Global** [cocos/cocos-engine#16779]
### Use Case

api使用不便，希望调整api命名。

### Problem Description

当我要给节点按角度设置旋转的时候，我找到了`setRotationFromEuler`接口，但是接口参数是xyz，然后我下意识的会想使用`getRotationFrameEuler`，但是并没有这个接口，而且后面想想，如果提供这个接口的话名字也不对，就应该改成`getEulerFromRotation`才对，后面也是翻看了源码才知道，原来是要通过eulerAngles接口来获取的。这就导致了学习成本增大了很多。
然后`eulerAngles`这个名字会让人感觉是个数组，例如`rotation`的属性感觉用起来就很舒服，所以感觉用`eulerAngle`会更舒服一些。甚至更精简一点，我觉得这个接口也没必要强调`euler`，直接用`angle`就完事了，即`angle`就表示的是欧拉角就好了，也符合我们平时说的“旋转多少角度”的这个。但是后面查看了才发现，`angle`已经在node里面被使用了，是欧拉角的`z`值。

### Alternatives Considered

综上，我个人建议的api修改：
废弃`setRotationFromEuler`接口，新增getEulerAngles和setEulerAngles接口，使得`属性`于`属性的get/set方法`保持普遍的是用规范。

**Comment by minggo** [comment]
已经有 eulerAngles 的 set/get 接口了，所以不太适合再加 getEulerAngles和setEulerAngles接口。eulerAngles 的 set 接口和 setRotationFromEuler 确实点重复。不过 setRotationFromEuler 可以让你只设置某个轴的分量，而不用是用 Vec3，所以也还算有点区别。
