### ISSUE TITLE
点光源的问题

### ISSUE THREAD

**Issue by a1076559139** [cocos/cocos-engine#16785]
### Cocos Creator version

3.8.2

### System information

mac os

### Issue description
点光源的问题是边缘硬，没有过度，我理解点光源应该是“向所有方向均匀地发散光线”。

最右侧的是点光源
![D-Chat_20240315141620](https://github.com/cocos/cocos-engine/assets/8677640/ff18b046-a296-4e4a-8c4d-5f69086cb5e6)

### Steps to reproduce

无

**Comment by a1076559139** [comment]
@minggo 光源效果这个问题有解决么，还是说不太好搞

**Comment by minggo** [comment]
这个问题解决了，可以看上面的 PR 链接。忘记关闭了。

**Comment by a1076559139** [comment]
> 这个问题解决了，可以看上面的 PR 链接。忘记关闭了。

👌
