### ISSUE TITLE
[native only] Incorrect exported namespace for GeometryRenderer

### ISSUE THREAD

**Issue by hana-alice** [cocos/cocos-engine#16787]
### Cocos Creator version

3.8.1

### System information

Win11

### Issue description

With GeometryRenderer enabled in editor, I built a native application on windows platform,  after connect to chrome console, I saw `cc.GeometryRenderer` is undefined. Check with swig config file `pipeline.i` where `GeometryRenderer` was exported:
> %module(target_namespace="nr") pipeline

while in `cocos\rendering\geometry-renderer.jsb.ts`:

> export const GeometryRenderer: typeof JsbGeometryRenderer = jsb.GeometryRenderer;

possibly ` nr.GeometryRenderer` ?

### Steps to reproduce

build a native(eg. windows) application, connect to js debugger, type cc.GeometryRenderer in console.
expect: definition of GeometryRenderer;
got: undefined.

**Comment by dumganhar** [comment]
@hana-alice , you're right, it was a mistake and it should be `nr.GeometryRenderer`. I will fix it soon.
