### ISSUE TITLE
vivo y66，wechat minigame，proto is not defined

### ISSUE THREAD

**Issue by lenonqing** [cocos/cocos-engine#16798]
### Cocos Creator version

3.8.1

### System information

机型: vivo y66 操作系统: Android 10 QP1A.190711.020 微信: 8.0.24 

### Issue description

其他机型微信小游戏都正常，但是 vivo y66 出现 "proto is not defined" 错误。

![E02512ED-CE1A-4210-8936-05E1CE081847](https://github.com/cocos/cocos-engine/assets/4057544/ca9c8ffb-eb96-48c9-8fad-89a15ee5d041)

### Steps to reproduce

[cocoscreatordemo.zip](https://github.com/cocos/cocos-engine/files/14596788/cocoscreatordemo.zip)

**Comment by lenonqing** [comment]
[cocoscreatordemo.zip](https://github.com/cocos/cocos-engine/files/14596735/cocoscreatordemo.zip)

**Comment by minggo** [comment]
@dumganhar 这个应该是微信的问题吧？
@lenonqing 这么特殊的机型和系统版本，我们估计很难解决。

**Comment by dumganhar** [comment]
从楼主这个描述看，感觉是微信的问题。

我们需要有对应的机型来确认问题。

**Comment by lenonqing** [comment]
@dumganhar @minggo 升级微信后，没有这个错误了，发现微信库 3.1.5 之下，会有这样的报错
https://developers.weixin.qq.com/minigame/dev/guide/runtime/client-lib/version.html

**Comment by dumganhar** [comment]
应该是 微信 库 的兼容问题了。这个 issue 可以关闭了吗？
