### ISSUE TITLE
creator 3.8.2 remove atlas or script file, .meta file can't remove

### ISSUE THREAD

**Issue by ankye** [cocos/cocos-engine#16793]
### Cocos Creator version

3.8.2

### System information

win10，macos

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/5154427/293d14b6-c55f-4760-84ef-01adbaf90653)
![image](https://github.com/cocos/cocos-engine/assets/5154427/0144f97e-463f-4c71-bdf0-315312de2e11)

### Steps to reproduce

remove directory or scene file , reopen editor, .meta can't clean

**Comment by yanOO1497** [comment]
Thank you for your feedback. This issue has been fixed in version 3.8.3. The beta version has been released in the forum （https://forum.cocos.org/t/topic/157509）. You can download and try it.
