### ISSUE TITLE
Xcode15.2 iOS14.0.1 Crash

### ISSUE THREAD

**Issue by Samueler** [cocos/cocos-engine#16794]
### Cocos Creator version

3.8.1/3.8.2

### System information

iOS14.0.1

### Issue description

Cocos打包成Framework嵌入到已有APP，使用Xcode15，iOS14.0.1真机调试时，一启动游戏界面，报内存错误：错误如下
malloc: Incorrect checksum for freed object 0x14aec0f80: probably modified after being freed.
Corrupt value: 0xa02020227070612e
malloc: *** set a breakpoint in malloc_error_break to debug

<img width="1230" alt="image" src="https://github.com/cocos/cocos-engine/assets/20416400/27306967-47e2-42be-80ec-378534f0770c">
其它机型表现正常。
在配置中打开Malloc Stack Logging选项并选中Live Allocations Only选项时，又可正常使用，不会崩溃，设置如下图：
<img width="824" alt="image" src="https://github.com/cocos/cocos-engine/assets/20416400/e1a5030b-e79f-4e12-ac52-2e56ba151dda">

### Steps to reproduce

<img width="1240" alt="image" src="https://github.com/cocos/cocos-engine/assets/20416400/69d5ceb4-75f8-4078-959d-5c796bd98149">

**Comment by minggo** [comment]
不集成，单独运行有问题吗？

**Comment by Samueler** [comment]
单独运行没有问题，但是即使是集成到空的新项目里也会崩溃

minggo ***@***.***> 于 2024年3月25日周一 11:29写道：

**Comment by minggo** [comment]
集成的话需要自己根据源码去处理了，这不是引擎设计的目的。
