### ISSUE TITLE
removeFromParent 方法在 forEach 遍历中无法删除全部子节点

### ISSUE THREAD

**Issue by xinstring** [cocos/cocos-engine#16807]
### Cocos Creator version

3.8.2

### System information

Windows 11 编辑器，Edge 浏览器中构建

### Issue description

在父节点包含两个或更多子节点的情况下，使用 forEach 遍历父节点，在回调函数中调用子节点的 removeFromParent 方法，无法将所有子节点删除。
```typescript
    /**
     * 点击按钮, 删除全部子节点
     */
    deleteChildNode() {

        // 找到父节点
        const fatherNode: Node = find("Canvas/FatherNode");

        // 遍历父节点
        fatherNode.children.forEach(child => {
            child.removeFromParent(); // 从父节点身上删除该节点
        })
    }
``` 

### Steps to reproduce

1. 运行下面的最小复制项目。
2. 使用浏览器预览。
3. 点击删除按钮，即可复现。预期：删除所有子节点。目前：每次点击按钮，删除一半子节点。
4. 思路：进入按钮对应的方法，打开原本注释掉的代码，注释掉现运行代码，将 removeFromParent 方法添加到任务队列中，可以解决该问题。

### Minimal reproduction project

[CocosBugDemo.zip](https://github.com/cocos/cocos-engine/files/14621595/CocosBugDemo.zip)

**Comment by eoeuou** [comment]
这个是基础面试题，不用在这里问，到论坛问问

**Comment by McvCar** [comment]
> ### Cocos Creator version
> 3.8.2
> 
> ### System information
> Windows 11 编辑器，Edge 浏览器中构建
> 
> ### Issue description
> 在父节点包含两个或更多子节点的情况下，使用 forEach 遍历父节点，在回调函数中调用子节点的 removeFromParent 方法，无法将所有子节点删除。
> 
> ```ts
>     /**
>      * 点击按钮, 删除全部子节点
>      */
>     deleteChildNode() {
> 
>         // 找到父节点
>         const fatherNode: Node = find("Canvas/FatherNode");
> 
>         // 遍历父节点
>         fatherNode.children.forEach(child => {
>             child.removeFromParent(); // 从父节点身上删除该节点
>         })
>     }
> ```
> 
> ### Relevant error log output
> _No response_
> 
> ### Steps to reproduce
> 1. 运行下面的最小复制项目。
> 2. 使用浏览器预览。
> 3. 点击删除按钮，即可复现。预期：删除所有子节点。目前：每次点击按钮，删除一半子节点。
> 4. 思路：进入按钮对应的方法，打开原本注释掉的代码，注释掉现运行代码，将 removeFromParent 方法添加到任务队列中，可以解决该问题。
> 
> ### Minimal reproduction project
> [CocosBugDemo.zip](https://github.com/cocos/cocos-engine/files/14621595/CocosBugDemo.zip)

使用 removeAllChildren 不就好了

**Comment by minggo** [comment]
在遍历 _children 的过程中会修改 _children 导致了这个问题。就如其他开发者说的，用其他的方式解决。
