### ISSUE TITLE
spriteFrame.flipUVY = true 后, node的active改变, flipUVY变回了false

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16818]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

spriteFrame.flipUVY = true 后,
改变所在node的acitve
先 active=false,  再active=true 后,  flipUVY变回了默认值

### Steps to reproduce

详见描述

**Comment by qiuguohua** [comment]
我用3.8.2弄了个demo试了下
![image](https://github.com/cocos/cocos-engine/assets/5205637/beba51ef-2b68-437c-8c7c-67f020544422)
好像并没有复现。不知道这样测试是否正确？

**Comment by finscn** [comment]
@qiuguohua  第二和第三行换一下 .

**Comment by finscn** [comment]
@qiuguohua 补充下, 我遇到的案例 frame是一个 rendertexture.
rt的y不是颠倒的. 于是我就用  flipUVY把它翻转成正的. 结果是正确的.
但是node一旦切换active的值, 就又反了.

**Comment by qiuguohua** [comment]
能帮忙做个简单的demo么？我换了下，好像也没复现。

**Comment by yanjifa** [comment]
看起来和这个是一个问题
https://github.com/cocos/cocos-engine/pull/16689
https://forum.cocos.org/t/topic/155680

**Comment by finscn** [comment]
> 看起来和这个是一个问题 #16689 https://forum.cocos.org/t/topic/155680

对 , 是一个问题

**Comment by qiuguohua** [comment]
最好还是提供一个实例，我验证下。我复现不出来。

**Comment by yanjifa** [comment]
@qiuguohua 
demo 工程: 
[test2d.zip](https://github.com/cocos/cocos-engine/files/14836660/test2d.zip)
复现视频: 
https://github.com/cocos/cocos-engine/assets/5621114/664e81ee-a0a3-4db5-8dee-b9609a77df17
修复 PR: 
https://github.com/cocos/cocos-engine/pull/16689

**Comment by qiuguohua** [comment]
@yanjifa 感谢 感谢，我看看

**Comment by minggo** [comment]
https://github.com/cocos/cocos-engine/pull/16689

**Comment by finscn** [comment]
@minggo 3.8.3 中并没有修复.   会放到 3.8.4 还是 3.8.5 呢?

**Comment by minggo** [comment]
可能是修复得有问题。会在 3.8.5 处理。
