### ISSUE TITLE
Pool的对象数量上限以及初始化数量应该要分开

### ISSUE THREAD

**Issue by Modo-Global** [cocos/cocos-engine#16812]
### Use Case

现在的Pool的对象数量上限以及初始化数量公用了`_elementsPerBatch`字段，导致要多大上限就必须先预创建多少数量出来。
但对象池本身就有延迟在需要的时候在创建的功能，这就将功能限制得太死了。

### Problem Description

在`callbacks-invoker.ts`中：
```ts
const callbackInfoPool = new Pool(() => new CallbackInfo(), 32);
const MAX_SIZE = 16;
const callbackListPool = new Pool<CallbackList>(() => new CallbackList(), MAX_SIZE);
```
这两个对象池的数量才设置了一点点，而这两个池的内容输出会直接跟node节点关联，也就是说跟当前的节点数量保持统一。而通常来讲，一个界面的节点数量已经远远超过了这个数量了（我们的项目都几百个了），导致会突然出现大量的对象创建，然后隔了几秒，通过自动回收又慢慢的销毁掉。

### Alternatives Considered

应该将数量上限和初始化数量分开，这样子就可以把上面的两个池子的上限设置成大一点，例如640，初始化的数量还是保持原来的。这样小一点的项目依然不会创建太多，大一点的项目就可以保持较好的对象复用了。

**Comment by minggo** [comment]
上限不是 `_elementsPerBatch `。它只是扩容时用这个数字，也就是 Pool 没有可用的对象时，每次预分配这么多数量的对象。

**Comment by minggo** [comment]
经沟通后发现 issue 写的内容不准确。issue 想表达的是缩容时能有个参数设置最小值，低于这个值就不缩容了。而目前的这个最小值就是 _elementsPerBatch。
