### ISSUE TITLE
Spine runtime in Cocos Creator 3.x is not backwards compatible with animations exported from Spine version 3.7

### ISSUE THREAD

**Issue by yanjifa** [cocos/cocos-engine#16816]
### Cocos Creator version

3.8.2

### System information

ALL

### Issue description

https://forum.cocos.org/t/topic/156888

### Steps to reproduce

必现

**Comment by bofeng-song** [comment]
As you metioned at https://forum.cocos.org/t/topic/156888 , this issue caused by the spine's source code. 
Cocos has no plans to modify the source code of third-party libraries.

**Comment by yanjifa** [comment]
@bofeng-song 那能否说下，WASM 库编译的步骤，让开发者可以自己处理这个问题

**Comment by bofeng-song** [comment]
1. 下载 https://github.com/emscripten-core/emsdk， 我们本地的用的分支是main， emsdk使用3.1.41
2. 切换目录到 resources\3d\engine\native\cocos\editor-support\spine-wasm；创建build目录并在该目录执行 emsdk目录下的emsdk_env.bat 或 emsdk_env.sh
3. 执行 emcmake cmake ..
4. 根据 build目录生成物，决定用ninja还是emmake， 如果以ninja后缀，则环境变量添加ninja所在目录(没有从网络下载)；否则在当前目录执行 emmake make
5. 将生成物拷贝到 resources\3d\engine\native\external\emscripten\spine； spine.js应该要重命名spine.wasm.js
