### ISSUE TITLE
淘宝创意互动小游戏有计划支持videoplayer吗？ 

### ISSUE THREAD

**Issue by pkjy** [cocos/cocos-engine#16829]
### Use Case

项目需要发布在淘宝创意互动小游戏，游戏里带有大量视频素材。

### Problem Description

如题，请问淘宝创意互动小游戏有计划支持videoplayer吗？看了下淘宝创意互动的文档，貌似只有cocos特意注明了暂不支持videoplayer和webview这两个功能。

### Alternatives Considered

期望淘宝创意互动小游戏能支持下videoplayer和webview这两个功能。

**Comment by minggo** [comment]
这个平台已经没有支持了。
