### ISSUE TITLE
Setting macros in build settings has no effect

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#16846]
### Cocos Creator version

3.8.2

### System information

MacOS

### Issue description

settings:
![image](https://github.com/cocos/cocos-engine/assets/28684663/d4c5e910-772b-4949-9323-4d6695d14d51)

engine code:
![image](https://github.com/cocos/cocos-engine/assets/28684663/37d46048-ab2c-447f-badc-f325794b7b47)

settings.json:
```json
{
    "macros":{}
}
```

You should think carefully about the priorities among platform defaults, preferences, and build settings.
Now I can only modify it through code, so what's the use of providing these panels?

### Steps to reproduce

.

**Comment by dumganhar** [comment]
@yanOO1497 Any ideas of this issue?

**Comment by dumganhar** [comment]
Need to remove the hard code in core/platform/macro.ts

```ts
if (NATIVE || MINIGAME || RUNTIME_BASED) {
    this.CLEANUP_IMAGE_CACHE = true;
}
```

and update the default value in build panel for native/minigam/runtime-based platforms.
