### ISSUE TITLE
move model fbx to another directory,material loss

### ISSUE THREAD

**Issue by ankye** [cocos/cocos-engine#16859]
### Cocos Creator version

3.8.2

### System information

mac os 13.5.2

### Issue description

 if i dump materials , then change fbx files from a to b dir, some materials will loss
so after move，should modify dump materials path

### Steps to reproduce

![WechatIMG1225](https://github.com/cocos/cocos-engine/assets/5154427/34a2a2b2-0571-4f8a-baf2-2cf37deb1526)

**Comment by wuzhiming** [comment]
Yes, this is a known issue, but for now, it indeed requires you to manually handle it.
Sorry, recent versions won't be able to improve on this issue as it involves some problems with assets importing that need to be addressed.
