### ISSUE TITLE
[3.8.2] The effect of spherical lighting on objects performs abnormally on the native platform

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16853]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

<img width="941" alt="d8cbd78d48a1e8079781de74acac40c" src="https://github.com/cocos/cocos-engine/assets/35944775/4b42fae4-5ffa-44f6-b255-400c57ad629d">

### Relevant error log output

-

### Steps to reproduce

-

### Minimal reproduction project

[demo.zip](https://github.com/cocos/cocos-engine/files/14830928/demo.zip)

**Comment by star-e** [comment]
Fixed in #17001.
If the problem still exists, please reopen this issue.
