### ISSUE TITLE
Spine render command is breaking batch on web

### ISSUE THREAD

**Issue by yuriilychak** [cocos/cocos-engine#1685]
Any region of sprite generate new draw call. I don't use meshes only simple regions.
Reproduce:
    1. Create spine boy on stage.
    2. Run scene in any browser.
    3 .Get a bunch of draw calls, instead of one.

**Comment by yuriilychak** [comment]
@jareguo  Hello again. I was fixed this small bug in SkeletonWebGLRenderer.
Solution is check base textures, not texture regions.
Your code:
```
...
            if ((cachedVertices + vertCount) * 6 > f32buffer.length ||
                textureAtlas !== regionTextureAtlas ||
                blendMode !== slot.data.blendMode) {
...
```
Fix:
```
...
            if ((cachedVertices + vertCount) * 6 > f32buffer.length ||
                textureAtlas.texture.getRealTexture() !== regionTextureAtlas.texture.getRealTexture() ||
                blendMode !== slot.data.blendMode) {
...
```
Can you ad it to cocos creator and cocos html5?

**Comment by jareguo** [comment]
Thanks @yuriilychak , @pandamicro please check this issue

**Comment by pandamicro** [comment]
@yuriilychak confirmed this is indeed the correct solution, thanks
