### ISSUE TITLE
Add editor zoom level

### ISSUE THREAD

**Issue by mvrlin** [cocos/cocos-engine#16864]
### Use Case

When having a big screen it gets hard to use the editor.

### Problem Description

Add **Window Zoom** similar to the VSCode
<img width="926" alt="image" src="https://github.com/cocos/cocos-engine/assets/24970784/711e9d2e-1d71-4d2c-8659-597f8a7b3d09">

<img width="1232" alt="image" src="https://github.com/cocos/cocos-engine/assets/24970784/57a58839-eaff-4b43-8b58-4860d030c402">

### Proposed Solution

We can add `zoom` property to the body

<img width="1728" alt="image" src="https://github.com/cocos/cocos-engine/assets/24970784/3a132a4f-1e0a-4cc8-a2f0-9690b17673c6">

<img width="1728" alt="image" src="https://github.com/cocos/cocos-engine/assets/24970784/a9df6ef5-a232-4eab-bd8e-af5c7ee9e962">

### Alternatives Considered

Adding `zoom` property to the body style on startup.

### Additional Information

You can take a look at ElectronJS docs https://www.electronjs.org/docs/latest/api/web-contents#contentssetzoomlevellevel

**Comment by HyperAlch** [comment]
Great idea. This would be great for the pathetic excuse that I call my eye balls, because I have trouble reading small stuff even with my glasses on, lol

😂💖

**Comment by wuzhiming** [comment]
Great idea, we might add this feature in the next version

**Comment by wuzhiming** [comment]
~~delay to v3.8.5~~

**Comment by wuzhiming** [comment]
already add to v3.8.4
