### ISSUE TITLE
MotionStreak组件会受地图移动的影响，如何禁止受地图移动的影响？

### ISSUE THREAD

**Issue by coderyqy** [cocos/cocos-engine#16863]
### Cocos Creator version

3.8

### System information

all

### Issue description

cocos MotionStreak组件，我在使用过程中出现了问题，我给我的子弹增加了MotionStreak组件，当子弹移动的时候也的确出现了拖尾效果，我的命名为stage的节点可以上下左右移动，当stage移动的时候，在stage中飞行的子弹的拖尾效果就会变得很奇怪，会随场景的移动，拖尾轨迹就会发生变化，但是我只想拖尾轨迹跟随子弹变化，请问如何禁止stage移动而影响到子弹的拖尾效果呢？？？

### Relevant error log output

无

### Steps to reproduce

创建一个命名为stage的节点，在stage中创建一个子节点bullet，bullet添加MotionStreak组件，移动bullet，在bullet移动过程中，改变stage的位置，上下左右移动stage。

**Comment by coderyqy** [comment]
Why doesn't anyone care about this issue?

**Comment by minggo** [comment]
请到论坛询问引擎的使用问题。
