### ISSUE TITLE
[MacOS ARM] Spine does not render when using cc.Spine with Enable Batch

### ISSUE THREAD

**Issue by MrcSnm** [cocos/cocos-engine#16881]
### Cocos Creator version

3.8.2

### System information

MacOS Arm (M3)

### Issue description

Nothing shows on the screen when using cc.Spine with the flag "Enable Batch" active.
It does show on the editor, but not when running in realtime.

### Steps to reproduce

Simply create an empty node.
Add a cc.Spine component
Add the SkeletonData asset
Mark it as Enable Batch.
Try it.

**Comment by bofeng-song** [comment]
Hello, is it possible to upload a demo? I've tried to reproduce the issue using the [official test](https://github.com/cocos/cocos-test-projects) cases, but couldn't.

**Comment by MrcSnm** [comment]
Hello @bofeng-song . I've identified some lacking steps:

Change the camera far value from 1000 to 1.
Reset camera position, so, the Z will become 0.
Reset the spine position so Z will become 0.

Now, it only renders with enable batch disabled

**Comment by MrcSnm** [comment]
[spine_test.zip](https://github.com/cocos/cocos-engine/files/14916853/spine_test.zip)

There it is a simplified test. I guess it would be hard for you to detect without the camera steps since they are quite surprising in 2D.

**Comment by bofeng-song** [comment]
@MrcSnm This [PR](https://github.com/cocos/cocos-engine/pull/16888) has been resolved this issue.

**Comment by MrcSnm** [comment]
@bofeng-song Thanks a lot :)
