### ISSUE TITLE
Broken order of duplicated nodes

### ISSUE THREAD

**Issue by lampysprites** [cocos/cocos-engine#16899]
### Cocos Creator version

3.8

### System information

WIndows 11 desktop

### Issue description

There's small but very irritating UI issues that make designing levels needlessly time consuming in cocos editor.

- Duplicating a node puts the new node in the end of the children list. I expect the new node to appear next to the original. The former is a problem because, first, that changes 2D draw order; and second, creates a sort of chronological ordering in hierarchy, and to find anything later (i.e when a node is locked, or invisible) i basically have to either loop through the entire subtree, or drag them back each time.
  
![CocosCreator_UQ9qsXjezi](https://github.com/cocos/cocos-engine/assets/49268426/e1d19ece-1792-4d34-a13b-53e441fc1576)

Above is a simplified version of what i have to do now, but with more children it becomes much longer to scroll (and they also LOVE to drop inside a prefab) so safe to say dragging the new nodes back in place takes about 2/3 of the time i spend designing levels. I'd much rather spend that on the task itself.

- Another problem is that duplicating several nodes more than once also changes their order, which causes the exact same kind of problem as above, times the number of nodes.

![CocosCreator_4OV5UmDUhR](https://github.com/cocos/cocos-engine/assets/49268426/f8bb2d82-49b0-471e-b998-78102a6746e6)

---------------------------------

I wonder that all that is perhaps a simple hack i can do myself, but I can't for life figure out how duplication even happens. I do see a `duplicate-node` message being dispatched in the message manager, yet [there's no mention of 'duplicate-node' anywhere in the source](https://github.com/search?q=repo%3Acocos%2Fcocos-engine%20duplicate-node&type=code)?

Thanks for your attention.

### Steps to reproduce

- Create a few nodes inside the same parent and give them recognisable names (say, A, B, C)
- Select the topmost node in the list and press Ctrl + D to duplicate

- Create a few nodes inside the same parent and give them recognisable names (say, A, B, C)
- Select said nodes and duplicate them a few times

**Comment by minggo** [comment]
I think it is designed like this, or it may change many nodes.
