### ISSUE TITLE
编辑器缩放操作状态下，切换到移动状态，并取消选中，鼠标消失

### ISSUE THREAD

**Issue by Judu233** [cocos/cocos-engine#16891]
### Cocos Creator version

3.8.2

### System information

Microsoft Windows 10 Pro for Workstations

### Issue description

编辑器缩放操作状态下，按住缩放不松开，切换到移动状态，并松开取消选中，鼠标消失

### Steps to reproduce

编辑器缩放操作状态下，按住缩放不松开，切换到移动状态，并松开取消选中，鼠标消失

**Comment by knoxHuang** [comment]
已在 3.8.3 修复，麻烦在 3.8.3 测试一下，安装包先在论坛下载：https://forum.cocos.org/t/topic/157509
