### ISSUE TITLE
Spine encountered an error while destroying

### ISSUE THREAD

**Issue by cx-github** [cocos/cocos-engine#16894]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/6309189/c69374c1-cc33-44b0-bfa9-65e80d922fb4)

this._instance There is no way to destroy

### Steps to reproduce

Once the spine is created, destruction is bound to happen

**Comment by bofeng-song** [comment]
Could you upload your demo? When using the [official test cases](https://github.com/cocos/cocos-test-projects), switching scenes doesn't encounter any issues and _instance.destroy() is triggered normally.

**Comment by bofeng-song** [comment]
Make sure your component's onDestroy can be triggered

**Comment by cx-github** [comment]
这是必现的问题，你可以直接把spine的node节点销毁掉 必现的

**Comment by bofeng-song** [comment]
> 这是必现的问题，你可以直接把spine的node节点销毁掉 必现的

removeChild，只是移除parent对他的引用关系
需要调用被删除节点的  destroyAllChildren， 这样才能触发组件的onDestroy

如：
this.node.removeChild(playerNode);
playerNode.destroyAllChildren();

**Comment by cx-github** [comment]
神经病啊
你们试过吗 就这样直接关掉饿了

**Comment by cx-github** [comment]
开发者反馈问题你们就这样对待的吗

**Comment by cx-github** [comment]
node的上挂一个spine的组件，你把node销毁掉，比如node.destroy  ，是必现的问题

**Comment by bofeng-song** [comment]
> 神经病啊 你们试过吗 就这样直接关掉饿了

说下你的问题：
1. 让你上传你的测试用例有那么费劲？所有开发人员都应该花大部分的时间来沟通？
2. 在哪个平台出现的问题描述清楚了吗？（第一步就是要避免其他沟通问题），你这边写的是所有平台都有问题，但是我测试是没问题的（windows 浏览器预览模式下）。



这个是测试代码：
const rightHandNode = this.node.getChildByPath("player-003/rightHand");
        rightHandNode.active = false;
        const playerNode = this.node.getChildByPath("player-003");
        

        this.scheduleOnce(() => {
            playerNode.destroy();
        }, 1);
        
creator设置：
![image](https://github.com/cocos/cocos-engine/assets/3078423/db89d463-e108-478c-8889-34bbadea13d8)

在pc 浏览器预览模式测试正常。


如果存在引用关系可能的处理办法：
this.node.removeChild(playerNode);
playerNode.destroyAllChildren();
