### ISSUE TITLE
3.8.2 spine skin getAttachmentsForSlot findNamesForSlot 接口实现错误

### ISSUE THREAD

**Issue by vollen** [cocos/cocos-engine#16908]
### Cocos Creator version

3.8.2

### System information

any

### Issue description

这两个接口没有返回值，依靠往传入的数组中塞入数据来实现往外传数据。
但是下面框出来的实现中，可能修改数组的引用。后续操作均在新数组中进行，外部无法获取到想要的数据。
![image](https://github.com/cocos/cocos-engine/assets/15061290/b0fef278-105f-4eea-a7fc-68027b6ab9eb)

### Steps to reproduce

code error

**Comment by bofeng-song** [comment]
@vollen fixed at this [PR](https://github.com/cocos/cocos-engine/pull/16909)
