### ISSUE TITLE
EditBoxImpl 监听的全局事件没有移除，销毁后在 web 调整窗口大小会报错

### ISSUE THREAD

**Issue by vollen** [cocos/cocos-engine#16910]
### Cocos Creator version

3.8.2

### System information

any

### Issue description

具体参考代码
clear 中没有清理监听的 View.instance 的事件。
当 EditBox 销毁后，调整窗口大小会报错。
![image](https://github.com/cocos/cocos-engine/assets/15061290/561c522f-2cfd-4da3-b8b3-28a52d02452d)
![img_v3_02a2_0c657eed-0455-43fb-bfe7-1e6962ed967g](https://github.com/cocos/cocos-engine/assets/15061290/fca0451f-db5b-411d-aaf7-6eef8c688495)

### Steps to reproduce

打开一个包含 EditBox 的窗口，然后销毁它
这时候调整窗口大小。
今天升级到 3.8.2, 发现不少问题，issue 反馈问题相对不及时。
如果方便的话，请联系我。wechat: focus_lingfeng

**Comment by minggo** [comment]
@qiuguohua 确认下，我记得是修复过的。

**Comment by qiuguohua** [comment]
https://github.com/cocos/cocos-engine/pull/16648, 是的
