### ISSUE TITLE
cc.d.ts中  getComponent()方法参数类型不对.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16915]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

d.ts中  cc.Node 和 cc.Component 类的 getComponent()方法参数类型声明好像不一致.
导致  对象类型是   `cc.Node | cc.Component` 时,  getComponent()只支持字符串

### Steps to reproduce

(无)

**Comment by finscn** [comment]
<img width="713" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/0f3b109f-145e-4207-bffe-d67632a6a612">
<img width="512" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/22313e82-a6fb-42a8-b633-0e3be472b56c">

错误如上图

**Comment by dumganhar** [comment]
It was fixed at https://github.com/cocos/cocos-engine/pull/16921, it will be in v3.8.4.
Thanks for your report.
