### ISSUE TITLE
游戏运行起来之后，华为出现权限界面一定会这样闪屏

### ISSUE THREAD

**Issue by lianchengtong** [cocos/cocos-engine#16913]
### Cocos Creator version

cocos 3.16

### System information

android 华为荣耀magic_4

### Issue description

https://forum.cocos.org/t/topic/85916

### Steps to reproduce

版本：cocos 3.16
平台：安卓
机型：华为荣耀magic_4
游戏运行起来之后，华为出现权限界面一定会这样闪屏。
游戏启动的时候有个背景图，之后出现权限选择，授权完之后，并且同意权限以后，界面疯狂闪烁,并且游戏界面不出来

http://8.138.25.248/magic_4%20%E8%87%B3%E8%87%BB%E7%89%88%E9%97%AA%E5%B1%8F.mp4

https://www.jianshu.com/p/24899efafc82, 按这个处理，现已解决处理

**Comment by minggo** [comment]
你说的是 cocos2d-x 的问题吧？这个 issue 系统是给 cocos creator 用的。
