### ISSUE TITLE
Editor bug : 粘贴组件时, 总是在添加到最下面

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16916]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

<img width="303" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/857fb116-8f1a-47ef-affd-6c2d457587fb">

粘贴组件时, 总是在添加到最下面.
期望是添加到 我点击的那个组件的下面. 

如果总是在最下面 那不如在 下面 "添加组件"按钮旁边加一个"粘贴组件"

### Steps to reproduce

无

**Comment by finscn** [comment]
顺便说一下, 其实我一只希望在最下面 "添加组件"按钮旁边加一个"粘贴组件"(不能粘贴时灰掉)

**Comment by wuzhiming** [comment]
我想请教一下，这个复制组件->粘贴组件，在你什么的情景下是一个比较高频的操作吗？设计的时候，这部分操作并不认为这个事情会是一个经常性的高频操作。所以并没有留一级菜单。

**Comment by finscn** [comment]
> 我想请教一下，这个复制组件->粘贴组件，在你什么的情景下是一个比较高频的操作吗？设计的时候，这部分操作并不认为这个事情会是一个经常性的高频操作。所以并没有留一级菜单。

我最近做的两个项目比较高频. 但是对别人可能不是.
所以后面提的那个一级按钮倒是没那么迫切.
不过这个 粘贴位置 应该是bug吧?

**Comment by wuzhiming** [comment]
> > 我想请教一下，这个复制组件->粘贴组件，在你什么的情景下是一个比较高频的操作吗？设计的时候，这部分操作并不认为这个事情会是一个经常性的高频操作。所以并没有留一级菜单。
> 
> 我最近做的两个项目比较高频. 但是对别人可能不是. 所以后面提的那个一级按钮倒是没那么迫切. 不过这个 粘贴位置 应该是bug吧?

不是的，我们设计的时候就是放到末尾，特地去友商那看了下，他们其实也是。。。

**Comment by finscn** [comment]
> > > 我想请教一下，这个复制组件->粘贴组件，在你什么的情景下是一个比较高频的操作吗？设计的时候，这部分操作并不认为这个事情会是一个经常性的高频操作。所以并没有留一级菜单。
> > 
> > 
> > 我最近做的两个项目比较高频. 但是对别人可能不是. 所以后面提的那个一级按钮倒是没那么迫切. 不过这个 粘贴位置 应该是bug吧?
> 
> 不是的，我们设计的时候就是放到末尾，特地去友商那看了下，他们其实也是。。。

尴尬了...

**Comment by smallmain** [comment]
> 不是的，我们设计的时候就是放到末尾，特地去友商那看了下，他们其实也是。。。

他们的设计不一定是好的，我支持粘贴时会考虑点击位置。

复制黏贴组件对我一直也是偏中频的操作，虽然想不起来具体操作场景，但是我觉得组件这边显然需要改进的有：

- 如果以后也没有冲突的更重要的操作，应该可以右键组件的标题来弹出菜单，能让操作更流畅。
- 组件应该也像资源、节点一样支持多选、拖拽移动、快捷键操作，起码实现个拖拽移动吧。
- 移除有依赖组件的组件时，应该能让用户选择一键全部移除。

**Comment by wuzhiming** [comment]
考虑到目前的现状，加上这个需求目前并没有收到比较多的用户反馈，暂时不做修改，后续如果有更多用户反馈，我们再讨论这个操作行为的修改。
