### ISSUE TITLE
Spine Rendering Bug

### ISSUE THREAD

**Issue by MrcSnm** [cocos/cocos-engine#16924]
### Cocos Creator version

3.8.3

### System information

Windows 10 

### Issue description

Some parts of the spine are being rendered in a glaring way. Even without the `premultiplied alpha` marked there, it still looks terrible.

I've kept the .spine and example file in there for you to test

### Steps to reproduce

Just hit play and you'll see that the spine is not doing the correct effects

### Minimal reproduction project

[SpineTest.zip](https://github.com/cocos/cocos-engine/files/15078784/SpineTest.zip)

**Comment by bofeng-song** [comment]
@MrcSnm
Because the current version of the engine is using Spine 3.8, please create the corresponding .spine resources using Spine 3.8 editor.
![image](https://github.com/cocos/cocos-engine/assets/3078423/a0706da8-3945-4c45-bf88-2385f313eb19)


If there are still issues, please kindly change curBlendSrc to BlendFactor::SRC_ALPHA for verification. Thank you.

**Comment by MrcSnm** [comment]
@bofeng-song Maybe the engine should give an warning when having a mismatching spine version?

**Comment by bofeng-song** [comment]
@MrcSnm Does the problem exist after change the spine's version ?

**Comment by MrcSnm** [comment]
I still need to test it

**Comment by MrcSnm** [comment]
[SpineTest2.zip](https://github.com/user-attachments/files/16969829/SpineTest2.zip)
@bofeng-song Tested and the issue still occurs after version migration

**Comment by MrcSnm** [comment]
@bofeng-song I've just got someone which made that work with different export settings:

Maybe that is useful for debugging

Normal is the working version, while H1 is the old that does not work

[Normal.zip](https://github.com/user-attachments/files/16970057/Normal.zip)
[H1.zip](https://github.com/user-attachments/files/16970058/H1.zip)

**Comment by bofeng-song** [comment]
@MrcSnm Thank you for the feedback on this issue. Please refer to the changes in this [PR](https://github.com/cocos/cocos-engine/pull/17755). Thanks!

**Comment by MrcSnm** [comment]
Thx for the fix!
