### ISSUE TITLE
[3.8.2] Setting the "trackIndex" to 1 in spine will result in the game being unable to run.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#16932]
### Cocos Creator version

3.8.2

### System information

Windows10

### Issue description

<img width="615" alt="1c50f5adb3fe7f41094318266adc06d" src="https://github.com/cocos/cocos-engine/assets/35944775/c58e04d1-c612-4d13-be8b-ef162873352b">

### Relevant error log output

--

### Steps to reproduce

--

### Minimal reproduction project

[spineTrackTest.zip](https://github.com/cocos/cocos-engine/files/15124392/spineTrackTest.zip)

**Comment by bofeng-song** [comment]
![企业微信截图_17144392516](https://github.com/cocos/cocos-engine/assets/3078423/9fdee5d8-15ff-4b21-9057-a067fbd3c328)

出问题的原因：
1. this.spine.setCompleteListener 会监听组件上所有动画的结束事件 
2. loop的动画，每次动画播放完成都会回调onComplete
===以上两点导致待播放的队列无限制放大

针对以上两点可以修改用户代码改用 this.spine.setTrackCompleteListener进行监听即可
