### ISSUE TITLE
Support removing progress bar from splash screen.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#16945]
### Cocos Creator version

3.8.2

### System information

MacOS

### Issue description

We want to display the cocos logo, but the progress bar:

- Too ugly.
- No use, the game doesn't take long to load anyway, just 1-2 seconds.

This need should be very common, so we need to be able to remove it without customizing the template.

### Steps to reproduce

.

**Comment by minggo** [comment]
We will take a look.

**Comment by WisteriaCyan** [comment]
Thanks for your suggestion! The progress bar only displays when previewing the project. Error and bug happens usually when developing and previewing, progress bar is helpful in that time. if you want to remove it, you can read [Web Preview Customization Workflow](https://docs.cocos.com/creator/manual/zh/editor/preview/browser.html?h=%E9%A2%84%E8%A7%88%E6%A8%A1%E6%9D%BF).

**Comment by smallmain** [comment]
> Thanks for your suggestion! The progress bar only displays when previewing the project. Error and bug happens usually when developing and previewing, progress bar is helpful in that time. if you want to remove it, you can read [Web Preview Customization Workflow](https://docs.cocos.com/creator/manual/zh/editor/preview/browser.html?h=%E9%A2%84%E8%A7%88%E6%A8%A1%E6%9D%BF).


Why close it directly? Who said this only appears during preview? Go check out the release package of WeChat mini-games.
