### ISSUE TITLE
哪些类creator会一直使用js的实现

### ISSUE THREAD

**Issue by lyjstudy** [cocos/cocos-engine#1695]
在creator里面的Widget
模拟器里面使用的C++的UIWidget
web里面使用的JS的CCWidget
发布windows平台也是用的JS的CCWidget 在 src/jsb_poll.js里面
哪些类creator会使用js的实现在哪里可以查到
如果统一在js里实现模拟器也最好使用js的这样不会造成困惑
cocos creator 1.5 引擎版本都是v1.5的分支 vs2015

[https://github.com/cocos-creator/cocos2d-x-lite/issues/654](url)

**Comment by lyjstudy** [comment]
模拟器用的也是js的实现，我去2d-x-lite问问

**Comment by jareguo** [comment]
> 哪些类creator会使用js的实现在哪里可以查到

目前没有这样的官方列表，不过你可以看看 engine/jsb/index.js

基本上能用 js 实现的都会尽量用纯 js
