### ISSUE TITLE
EditBox 销毁时 没有移出对 canvas-resize事件的监听

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16957]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

在 edit-box-impl.ts里监听了canvas resize事件 但是没有移出监听

### Steps to reproduce

无

**Comment by minggo** [comment]
@qiuguohua 我记得是修复过的，请确认一下。

**Comment by qiuguohua** [comment]
是的，已经修复了。https://github.com/cocos/cocos-engine/pull/16648
