### ISSUE TITLE
EditBox text position is wrong when editing in Layout

### ISSUE THREAD

**Issue by mcube-12139** [cocos/cocos-engine#16955]
### Cocos Creator version

3.8.2

### System information

Windows 10 Browser

### Issue description

When I add 2 EditBox Nodes to a container Layout Node as children, one of the EditBox Nodes displays text at a wrong position when I edit it.
![image](https://github.com/cocos/cocos-engine/assets/73683960/cbf96b64-cdcc-4cca-9c67-19d9c77640a5)
![image](https://github.com/cocos/cocos-engine/assets/73683960/32cb85d9-bef4-4515-875c-ef03d93cb4d6)
![image](https://github.com/cocos/cocos-engine/assets/73683960/e1b0e63e-2e4e-461a-9fd8-273d538f60da)

### Relevant error log output

Nothing

### Steps to reproduce

1. Add a Layout Node to Canvas.
2. Set the Layout type to "HORIZONTAL" and resizeType to "CONTAINER".
3. Instantiate 2 EditBox Nodes **by code**, and add them to the Layout Node as children.
4. Test to run in browser.

### Minimal reproduction project

[editbox-bug.zip](https://github.com/cocos/cocos-engine/files/15242547/editbox-bug.zip)

**Comment by minggo** [comment]
I think it is fixed in v3.8.3. 
@qiuguohua could you please double check it?

**Comment by qiuguohua** [comment]
I tested it and it works fine in 3.8.3
