### ISSUE TITLE
开启 spine动画的 cache模式后, 设置动画所在节点的 透明度 无效

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16960]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

开启 spine动画的 cache模式后, 设置动画所在 Node 的 透明度 无法改变 动画整体的透明度. 只有实时模式下有效.

### Steps to reproduce

无

**Comment by bofeng-song** [comment]
此问题待重构版本修复，若需更改，请参考此issuse的回复
https://github.com/cocos/cocos-engine/issues/16601
