### ISSUE TITLE
Tween needs to support difference targets in `sequence` and `parallel` chain.

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#16978]

**Comment by wsLyr** [comment]
很有必要很需要的特性，下个版本能上太好了

**Comment by dumganhar** [comment]
@linxi1990 嗯，这个功能计划会在 3.8.5 中上。如果想提前体验的话，也可以 pull 我的修改 PR （ https://github.com/cocos/cocos-engine/pull/16979 ） 验证，我们也欢迎开发者提前给我们提交反馈建议。谢谢。

**Comment by dumganhar** [comment]
https://github.com/cocos/cocos-engine/pull/17020
