### ISSUE TITLE
Can not remove cc.instantiate prefab which has box2d body

### ISSUE THREAD

**Issue by nshermione** [cocos/cocos-engine#1698]
```js
let cell = cc.instantiate(this.cellPrefab);

row.addChild(cell);

cell.removeFromParent();
```

It will throw exception as below:
![image](https://cloud.githubusercontent.com/assets/3451918/26768908/420a89f4-49d5-11e7-9593-98a053d2f995.png)

**Comment by nshermione** [comment]
I found the world had not been init before. Close!

**Comment by jareguo** [comment]
should not emit error even if row not initialized @2youyou2
