### ISSUE TITLE
Android crush(JS: Error 5302, please go to *************************************************************************** to see details. Arguments: cc.LightProbesData)

### ISSUE THREAD

**Issue by GamewolfLongMan** [cocos/cocos-engine#16985]
### Cocos Creator version

3.8.2

### System information

Window 10 editor build android in vivo v2250

### Issue description

Android crush in begin

### Steps to reproduce

 E Cocos   : 17:21:47 [ERROR]: JS: Error 5302, please go to *************************************************************************** to see details. Arguments: cc.LightProbesData
![image](https://github.com/cocos/cocos-engine/assets/163411621/10ad5937-be1b-4102-8cc0-f1599ceacc18)

**Comment by minggo** [comment]
Could you please provide a demo to reproduce it? Does it only crash on vivo v2250?

**Comment by GamewolfLongMan** [comment]
> Could you please provide a demo to reproduce it? Does it only crash on vivo v2250?
I only have one device , and it is empty project

**Comment by minggo** [comment]
Thanks for the information.

**Comment by GamewolfLongMan** [comment]
I solved the problem by recreat first scene.

**Comment by minggo** [comment]
How did you recreate the first scene?

**Comment by GamewolfLongMan** [comment]
> How did you recreate the first scene?
I found other scene is no problem .so I  delete old one and rebuild new

**Comment by minggo** [comment]
But you said an empty project also crashed. So you created a new empty scene?

**Comment by GamewolfLongMan** [comment]
> But you said an empty project also crashed. So you created a new empty scene?

yes

**Comment by minggo** [comment]
Have you tried to create a new empty project to test? I just want to make sure if can constantly reproduce it or not.

**Comment by GamewolfLongMan** [comment]
> Have you tried to create a new empty project to test? I just want to make sure if can constantly reproduce it or not.
I try  .but I can't reproduce it now.
I dont know what I done before.

**Comment by minggo** [comment]
Got it. If so i will close this issue. Fell free to reopen it if you meet it again.
