### ISSUE TITLE
iOS原生项目集成3.8.2报错

### ISSUE THREAD

**Issue by kindvoon** [cocos/cocos-engine#16989]
### Use Case

我尝试用iOS原生项目集成3.8.2版本，采用的是编译cocos creator导出的 project工程 产生的libboost_container.a和libcocos_engine.a这两个.a库。想采用组件化的方式将其集成至iOS原生项目中。但是报错如下。

### Problem Description

报错如下：
![Pasted Graphic 5](https://github.com/cocos/cocos-engine/assets/17755806/255c4cbb-aafd-4ba2-adc9-ad4eef065d06)
这是podspec配置：
![Pasted Graphic](https://github.com/cocos/cocos-engine/assets/17755806/9882b699-e5d8-4b6c-bd68-ce42e6e3e425)
组件结构图如下：
![Pasted Graphic 1](https://github.com/cocos/cocos-engine/assets/17755806/050d4abc-25a4-4dfa-a733-86f31278d5e3)
![Pasted Graphic 2](https://github.com/cocos/cocos-engine/assets/17755806/a9b87ee5-0cad-4859-8c01-03bef7badadd)
![Pasted Graphic 3](https://github.com/cocos/cocos-engine/assets/17755806/64e395d4-6fbf-437d-b7db-28d69f5706d9)
![Pasted Graphic 4](https://github.com/cocos/cocos-engine/assets/17755806/6e2560c1-d12e-4759-b970-76eb78b135c8)

### Alternatives Considered

如果不用组件化的形式集成，有推荐的方案集成吗？

**Comment by kindvoon** [comment]
报错：
Showing All Messages
Undefined symbol: v8::api_internal::MakeWeak(unsigned long**)

podspec配置：
`  s.source_files = 'PublicHeader/*.{h}'
  s.public_header_files = 'PublicHeader/*.{h}'

  s.ios.vendored_libraries = 'Libraries/*.{a}'

  s.preserve_paths = [
      "engine-native/**/*"
  ]
  
  s.pod_target_xcconfig = {'DEFINES_MODULE' => 'NO'}

  s.framework = 'CoreVideo', 'AudioToolbox', 'OpenGLES', 'CoreMotion', 'CoreText', 'CFNetwork', 'CoreFoundation', 'MobileCoreServices', 'GameController', 'WebKit', 'CoreMedia', 'AVKit', 'CoreGraphics', 'SystemConfiguration', 'QuartzCore', 'JavaScriptCore', 'Security', 'OpenAL', 'AVFoundation', 'Foundation', 'UIKit', 'Metal', 'MetalKit', 'MetalPerformanceShaders'
  
  s.library = 'c++', 'stdc++', 'z', 'sqlite3', 'iconv'`

**Comment by minggo** [comment]
不支持这个方案，需要用自定义引擎的方式自己去修改。

**Comment by kindvoon** [comment]
请问下，3.8.2支持将cocos项目集成到iOS原生的项目中吗？如果支持的话，怎么能集成呢？ @minggo
