### ISSUE TITLE
编辑器文本错误: 偏好设置 -> 设备管理

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#16994]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

<img width="180" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/fca59a4c-9fc4-4553-a590-0cb6b9106e9b">

应该是 Apple iPad Air 

### Steps to reproduce

无

**Comment by yanOO1497** [comment]
你好，谢谢反馈，已修改。自 383 起，这份设备配置是动态更新的，重启编辑器即可。
