### ISSUE TITLE
3.8.3在2D引擎下节点沿X轴或者Y轴旋转，节点只显示了一半

### ISSUE THREAD

**Issue by zwtderek1986** [cocos/cocos-engine#16999]
### Cocos Creator version

3.8.3

### System information

Macos, Chrome

### Issue description

翻转动画时，直接少一半
<img width="216" alt="image" src="https://github.com/cocos/cocos-engine/assets/39580899/dc90e9a8-7690-4544-a84c-2dd655868435">

### Steps to reproduce

Tween.stopAllByTarget(this.node_test);
this.node_test.setRotationFromEuler(v3(0, 0, 0));
tween(this.node_test)
.to(0.25, { eulerAngles: v3(0, 90, 0) })
.start();

**Comment by zwtderek1986** [comment]
https://forum.cocos.org/t/topic/157659，也有人在论坛里面提了，没人回应

**Comment by dumganhar** [comment]
你这个节点是一个 2D sprite？如果是 2D 面片，绕 Y 轴旋转 90 度，应该直接不显示了吧。
在编辑器中调整 Rotation Y 是什么效果？

因此，为了避免理解上的差异，请提供一个 Demo，和描述一下你的预期。

另外，我猜想，你是说动画过程中少了一半？还是动画结束时？

**Comment by dumganhar** [comment]
我按你的实例代码，写了个测试例验证，并没有出现此问题。所以还是提供一个示例 demo。
有点怀疑跟你的相机配置有一定关系。

**Comment by zwtderek1986** [comment]
> 你这个节点是2D sprite？如果是2D面片，绕Y轴旋转90度，应该直接不显示吧。 在编辑器中调整旋转Y 是什么效果？
> 
> 因此，为了避免了解问题的差异，请提供一个Demo，并描述一下你的预期。
> 
> 另外，我想，你是说动画过程少了一半？还是动画结束？

2D的项目，节点也是2D的，实现一个翻牌效果，动画一开始就直接少一半，动画完毕后正常，Anchor Point设置的0.5，0.5！引擎3.8.2和3.8.3都有这个问题。2D项目相机要什么特殊配置么？我是直接创建的2d工程

**Comment by dumganhar** [comment]
截图一下你的相机属性面板。
最好提供一下最简复现demo，便于我们排查。谢谢。

**Comment by zwtderek1986** [comment]
> 截图一下你的相机属性面板。 最好提供一下最简复现demo，便于我们排查。谢谢。

demo如下
[bugDemo.zip](https://github.com/cocos/cocos-engine/files/15450065/bugDemo.zip)

**Comment by dumganhar** [comment]
收到，我定位一下。

**Comment by dumganhar** [comment]
![WeChatd42c0bcb2a909512866dbe4aa4245219](https://github.com/cocos/cocos-engine/assets/493372/9e3c42d7-81ef-406b-bd74-9baf12e8e4bc)

你项目 相机 Far 设置 为 1000， position 也是 1000，肯定会出现这个问题。
你这里改为 2000，就好了。

**Comment by zwtderek1986** [comment]
> 

https://forum.cocos.org/t/topic/157659
论坛里有人提到过，3.4.2是正常的！

我是默认生成的项目，所以没有关注相机的问题

**Comment by dumganhar** [comment]
嗯，那可能某个版本相机参数有调整。

**Comment by zwtderek1986** [comment]
> 嗯，那可能某个版本相机参数有调整。

希望还是优化一下，或者是说明一下吧，做2D的项目，对这个关注真不多！还是谢谢了

**Comment by dumganhar** [comment]
嗯。我测试跟进一下。感谢反馈。

**Comment by zwtderek1986** [comment]
明白了，我的size是400*400。anchor point是0.5*0.5
受到3d的影响，position中z:1000，所以最小要设置成1000+400/2 = 1200，至少是这个值才能正常y轴旋转！

**Comment by zwtderek1986** [comment]
> 嗯。我测试跟进一下。感谢反馈。

明白了，我的size是400400。anchor point是0.50.5
受到3d的影响，position中z:1000，所以最小要设置成1000+400/2 = 1200，至少是这个值才能正常y轴旋转！

**Comment by dumganhar** [comment]
是的。

另外，我查到历史：https://github.com/cocos/cocos-engine/pull/13170

**Comment by dumganhar** [comment]
@wuzhiming 
这个的确触发了一定的兼容性问题，看怎么修下？

**Comment by knoxHuang** [comment]
感谢反馈,已经修复
