### ISSUE TITLE
spine淘宝phone test will show the Spine incompletely.

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#16997]
### Cocos Creator version

2.4.12, 2.4.13, 3.7.4

### System information

any devices

### Issue description

under the phone test, the spine show incompletely .
![WechatIMG8](https://github.com/cocos/cocos-engine/assets/26586287/37faa457-1325-4ac7-8165-146472472ec4)

### Relevant error log output

none

### Steps to reproduce

click 真机调试, generate qrcode, use phone scan the code. while entered the game ,you will see the issue.

### Minimal reproduction project

[animalCity.zip](https://github.com/cocos/cocos-engine/files/15329328/animalCity.zip)

**Comment by bofeng-song** [comment]
The issue at the platform layer is that the implementation of the Array differs from the standard implementation in TypeScript.

**Comment by tangkaikk** [comment]
begin game initialization, inject the code below:        
let oldClear = sp.spine.IntSet.prototype.clear
        sp.spine.IntSet.prototype.clear = function() {
            oldClear.apply(this);
            this.array = [];
        }
