### ISSUE TITLE
taobao minigame when pad rotate the game, the window will adjust in an inappropriate way.

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17004]
### Cocos Creator version

2.4.12, 2.4.13, 3.7.4,3.8.2

### System information

pad

### Issue description

taobao minigame when pad rotate the game, the window will adjust in a wrong way.

to solve this problem, here is the ttemporary solution:
1.find the script screen-adapter.ts (C:\ProgramData\cocos\editors\Creator\3.8.2\resources\resources\3d\engine\pal\screen-adapter\minigame\screen-adapter.ts)
2.modify the windowSize function below:
    public get windowSize (): Size {
        const sysInfo = minigame.getSystemInfoSync();
        const dpr = this.devicePixelRatio;
        let screenWidth = sysInfo.windowWidth;
        let screenHeight = sysInfo.windowHeight;
        if (BYTEDANCE) {
            screenWidth = sysInfo.screenWidth;
            screenHeight = sysInfo.screenHeight;
        }
        if (ALIPAY &amp;&amp; rotateLandscape  &amp;&amp; screenWidth &lt; screenHeight) {
            const temp = screenWidth;
            screenWidth = screenHeight;
            screenHeight = temp;
        }
        if(TAOBAO_MINIGAME){
           var windowInfo = minigame.getWindowInfoSync();
           screenWidth = windowInfo.screenWidth;
           screenHeight = windowInfo.screenHeight;
        }
        return new Size(screenWidth * dpr, screenHeight * dpr);
    }

### Relevant error log output

none

### Steps to reproduce

1.generate a taobao minigame
2.generate the qrcode
3. with pad to scan the qrcode
4. rotate the pad.

### Minimal reproduction project

[NewProject.zip](https://github.com/cocos/cocos-engine/files/15344595/NewProject.zip)

**Comment by bofeng-song** [comment]
2.4.x fixed [PR](https://github.com/cocos-creator-packages/adapters/pull/283)
3.8.x fixed [PR](https://github.com/cocos/cocos-engine/pull/17107)

**Comment by bofeng-song** [comment]
由于微信在ipad上的旋转并未触发resize，orientation-change等事件，对应的逻辑由微信处理。
淘宝上对应的逻辑，需要由淘宝处理，如果淘宝处理后，有点击等小问题，cocos再帮忙处理

**Comment by bofeng-song** [comment]
等淘宝有具体进展再处理，先关闭此issue
