### ISSUE TITLE
3.8.3 Building Android debug mode may render exceptions

### ISSUE THREAD

**Issue by zhitaocai** [cocos/cocos-engine#17016]
### Cocos Creator version

3.8.3

### System information

Android 14

### Issue description

Since the project was upgraded from 3.8.2 to 3.8.3

When building Android **Debug** mode, there **may be** rendering exceptions (note, it is possible, not guaranteed), and the following error will be reported:

![image](https://github.com/cocos/cocos-engine/assets/5856724/696d87be-7e16-4cbb-9470-740e65d9a5fb)

In addition, with the same project configuration, when building Android **Release** mode, there will be no rendering exceptions.

After my own investigation, I found that the following places did not perform empty judgment processing, which led to the above problems:

![image](https://github.com/cocos/cocos-engine/assets/5856724/32a6c811-f85a-4257-b02c-f152aea84b13)

At present, I comment out this judgment code, and all rendering exception problems can be solved.

But I haven't found the root cause of the problem. I hope the technical students in the engine team can troubleshoot the positioning problem.

In addition, this problem only occurred after upgrading my project from 3.8.2 to 3.8.3. The same code has no rendering problem in 3.8.2.

### Steps to reproduce

---

**Comment by dumganhar** [comment]
Also reported at https://forum.cocos.org/t/topic/160454/4

**Comment by zhitaocai** [comment]
still happen in 3.8.4

**Comment by dumganhar** [comment]
@zhitaocai did you get the steps to reproduce this issue?

**Comment by zhitaocai** [comment]
There is no way to reproduce it stably for now.

But you can observe the `render-data.ts` file. All places where `this._renderDrawInfo` is used have a null check, except for the lines that report errors.

**Comment by zhitaocai** [comment]
> There is no way to reproduce it stably for now.
> 
> But you can observe the `render-data.ts` file. All places where `this._renderDrawInfo` is used have a null check, except for the lines that report errors.

i hope this msg will be helpful

**Comment by zhitaocai** [comment]
I just found [issue 17365](https://github.com/cocos/cocos-engine/issues/17365), is this issue possibly related to issue 17365?
