### ISSUE TITLE
When using bitmapfont in taobao-minigame, the game becomes unresponsive.

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#17022]
### Cocos Creator version

2.4.12

### System information

windows10

### Issue description

![image](https://github.com/cocos/cocos-engine/assets/35944775/9c2af519-b203-439a-8d71-1745863c6121)

### Steps to reproduce

![image](https://github.com/cocos/cocos-engine/assets/35944775/e32999ed-4363-4d85-8abd-da83f0c1e590)
Continuous rapid clicking of the button

### Minimal reproduction project

[demo.zip](https://github.com/cocos/cocos-engine/files/15388379/demo.zip)

**Comment by zhefengzhang** [comment]
因为淘宝真机运行的 JS 虚拟机是 quickjs 的定制版，模拟器是 v8，所以在对数据类型对象进行处理时会有一些差异。此问题是因为淘宝真机上执行下面这种代码时会报错，而在淘宝模拟器上不会。
```
var a = new Unit16Array(2);
a[2] = 0;
```

目前可以修改 assembler-2d.js 中的代码暂时解决此问题。
![image](https://github.com/cocos/cocos-engine/assets/35944775/3b93915b-6df2-4598-83a5-fe3e09ae65eb)

**Comment by liuhy-liu** [comment]
2.4.15-0328，使用上述demo，真机运行黑屏报错，如下，模拟器白屏
![Image](https://github.com/user-attachments/assets/178b282a-23d5-490f-a3a5-e3b30554e4f2)
