### ISSUE TITLE
Mark component dirty in editor

### ISSUE THREAD

**Issue by ze0nni** [cocos/cocos-engine#17034]
### Use Case

I am create component, who provides access to other compoent data.

Like this:
```
class MyBytton {
    @property(MyText)
    private _text: MyText;
    
    @property(CCString)
    get string(): string { retunr this._text.string; }
    set string(value: string) { this._text.string = value; }
}
```

### Problem Description

This is work good in play mode.

I have problem in edit mode:
Then I change MyBytton.string in editor inspector, I see how text changed in MyText. But then I save prefab -- MyText нет saved. 
I understand that I need to mark the component as "dirty" but I couldn't find how.

I saw there is a flag `CCObject.Flags.Dirty` and use it like this:
```
this._text.string = value;
this._text.node._objFlags |= CCObject.Flags.Dirty;
this._text._objFlags |= CCObject.Flags.Dirty;
```

But no result

### Alternatives Considered

Avoid to complex components?

**Comment by wuzhiming** [comment]
When you change MyBytton.string and focus to another place editor will mark as dirty and the title will have change to xx.scene*

but if you want to know your text change event at inspector, you can use  getter and setter as you provided and just add `@executeInEditMode` decorator
```TS
//add this decorator and this component will run on editor and you can use you setter and getter when on editor mode
@executeInEditMode
export class testComponent extends Component {
@property(MyText)
    private _text: MyText;
    
    @property(CCString)
    get string(): string { retunr this._text.string; }
    set string(value: string) { this._text.string = value; }
}
```

**Comment by ze0nni** [comment]
Tried create minimal project to reproduct bug. But No problem not reproduced.

I think the problem is in my project. This is what it looks like:
https://www.youtube.com/watch?v=vJX2dJir9M8

I will research problem more

**Comment by wuzhiming** [comment]
or  you  can upload a simple demo and we will try this
https://www.youtube.com/watch?v=vJX2dJir9M8

**Comment by ze0nni** [comment]
Success. This happens if you use prefabs

[CocosTest.zip](https://github.com/cocos/cocos-engine/files/15498935/CocosTest.zip)

**Comment by knoxHuang** [comment]
you need to modify the property via a `set-property` message to trigger the prefab's mechanism for storing the property

Here's the example, which focuses on the `setComponentPropertyInEditor` function.

```ts
import { _decorator, CCString, Component, Label, Node } from 'cc';
import { EDITOR } from 'cc/env';
const { ccclass, property, executeInEditMode } = _decorator;

@ccclass('MyButton')
@executeInEditMode
export class MyButton extends Component {
    @property(Label)
    private label: Label|null = null;

    @property(CCString)
    get string(): string { return this.label?.string ?? "" }
    set string(value: string) { 
        if (EDITOR) {
            this.setComponentPropertyInEditor(this.label, 'string', value, 'string');
        } else {
            if (this.label) this.label.string = value;
        }
    }

    setComponentPropertyInEditor(component: Component | null, key: string, value: any, type: string) {
        if (!EDITOR) return;
        if (!component) return;

        const idx = component.node.components.findIndex((comp) => comp === component);
        if (idx === -1) return;

        // @ts-ignore
        Editor.Message.request('scene', 'set-property', {
            uuid: component.node.uuid,
            path: `__comps__.${idx}.${key}`,
            dump: {
                type,
                value,
            },
        });
    }

}
```
