### ISSUE TITLE
spine隐藏时调用setAnimation报错

### ISSUE THREAD

**Issue by kaxifakl** [cocos/cocos-engine#17038]
### Cocos Creator version

3.8.3

### System information

Window 10

### Issue description

1.节点一开始active=false，调用setAnimation播放动画，此时会报错
```
    protected onLoad(): void {
        this.skeleton.setAnimation(0, 'run', true);
        this.skeleton.node.active = true;

        console.log(this.skeleton)
    }
  ```
![image](https://github.com/cocos/cocos-engine/assets/63728902/cad0c5d8-00a0-47ea-8fb2-a1d67126420a)
2.手动调用skeleton初始化，此时不会报错，但动画不会播放
```
    protected onLoad(): void {
        if (!this.skeleton._skeleton) {
            this.skeleton.__preload()
        }
        this.skeleton.setAnimation(0, 'run', true);
        this.skeleton.node.active = true;

        console.log(this.skeleton)
    }
```

### Steps to reproduce

打开上传的项目，运行`scene`场景

### Minimal reproduction project

[NewProject_383.zip](https://github.com/cocos/cocos-engine/files/15414336/NewProject_383.zip)

**Comment by bofeng-song** [comment]
@kaxifakl  setAnimation先改成  在node.active=true后面，这个问题后面会修复

**Comment by kaxifakl** [comment]
哪个版本会修复？

**Comment by kaxifakl** [comment]
@bofeng-song 这个问题还有后续吗

**Comment by bofeng-song** [comment]
385处理

**Comment by kaxifakl** [comment]
@bofeng-song 这个操作只是不让它报错，在未激活前setAnimation还是无效的。是否有一些缓存机制让animationName缓存下来呢？

**Comment by bofeng-song** [comment]
> @bofeng-song 这个操作只是不让它报错，在未激活前setAnimation还是无效的。是否有一些缓存机制让animationName缓存下来呢？

![image](https://github.com/user-attachments/assets/ef68be84-84fb-4cc8-be55-38f07ab712a3)
active后，会设置skeletonData，这个时候需要重新设置animationName，不然animation可能是不存在的。

**Comment by kaxifakl** [comment]
@bofeng-song 那这时候是否可以直接用缓存的animationName赋值呢，并且验证一下animationName是否有效

**Comment by bofeng-song** [comment]
@kaxifakl  setSkeletonData 接口正常只做和skeletonData有关的事情，不应该顺带执行setAnimation，这样会职责不清晰

**Comment by kaxifakl** [comment]
@bofeng-song 这里的问题应该是，skeleton组件未激活前，手动赋值了SkeletonData，但__preload()方法未执行，所以this._skeleton为空，此时setAnimation, 会在这里被return 
![image](https://github.com/user-attachments/assets/4f8ad841-8e0d-4cfd-9960-9dd8f9a86ee9)

**Comment by kaxifakl** [comment]
@bofeng-song [https://github.com/cocos/cocos-engine/issues/17784](url) 这个issue也是同样的问题，SkeletonData赋值后，setAnimation应该设计为可以被成功调用，即使节点未被激活

**Comment by bofeng-song** [comment]
@kaxifakl 
[https://github.com/cocos/cocos-engine/issues/17784](https://github.com/cocos/cocos-engine/issues/url)
这个的根本问题是节点重用，skeleton因为skeletonData设置null而被置空，第二次使用时，未对skeleton进行赋值
