### ISSUE TITLE
[bug] The generated JS code format  was changed in v3.8.3

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#17055]
If user writes code like:
![141716779599_ pic](https://github.com/cocos/cocos-engine/assets/493372/04ebfc9f-f07b-4e9a-b2ff-13bc1a454c40)

Build it in release mode, the generated JS code will be:

![151716779628_ pic](https://github.com/cocos/cocos-engine/assets/493372/83ae7c7d-f28f-40cf-8eba-57ea7692fb0f)

which will trigger compilation failed while `require` the script. Error information:

![621716797949_ pic](https://github.com/cocos/cocos-engine/assets/493372/cd95ab65-e22a-4461-8a87-cfb64a272e29)

Demo: 
[AndroidBugDemo.zip](https://github.com/cocos/cocos-engine/files/15467335/AndroidBugDemo.zip)

**Comment by martianma** [comment]
3.8.4修吗？大神们

**Comment by martianma** [comment]
这个bug，构建报错了，原生都跑不起来了，很严重啊！

**Comment by dumganhar** [comment]
@martianma 先改下 

let aaa = bbb?.foo(); 地方的写法为：

```ts
let aaa;
if (bbb) aaa = bbb.foo();
```

**Comment by dumganhar** [comment]
@martianma 3.8.4 是鸿蒙特供版本，不会带这个修复。

**Comment by martianma** [comment]
我把构建的目录删掉，在打开，然后在打开debug关掉debug倒腾倒腾自己好了，不知道为什么🥲

**Comment by martianma** [comment]
我是mac机器，刚才构建的iOS和Android都是报错的，现在自己好了，很奇怪

**Comment by dumganhar** [comment]
> 我是mac机器，刚才构建的iOS和Android都是报错的，现在自己好了，很奇怪

这么神奇啊。那看后续是否还出现？

**Comment by dumganhar** [comment]
fixed at https://github.com/cocos/cocos-engine/pull/17227

@martianma , 你可以修改一下引擎目录下的 native/.browserslistrc 文件，把 116 改为 80 来临时修复。
