### ISSUE TITLE
typescript不能定义get()、set()函数

### ISSUE THREAD

**Issue by a1q123456** [cocos/cocos-engine#1709]
```typescript
    _width: number = 10;
    @property(cc.Integer)
    get width()
    {
        return this._width;
    }
    set width(value)
    {
        this._width = value;
    }
```

会在Cocos2d Creator的控制台提示
> The 'default' value of '5513.width' should not be used with a 'get' function.

**Comment by jareguo** [comment]
抱歉，property 一直就不能直接赋值为 cc.Integer，需要写 `{ type: cc.Integer }`

**Comment by a1q123456** [comment]
@jareguo 刚找到问题，貌似getset添加@property的时候，不能设置类型，必须用@property装饰，不能用@property(...)来修饰

**Comment by jareguo** [comment]
可以，只不过是 cc.Integer 不能直接传给 property，要用 property({ type: cc.Integer })

**Comment by a1q123456** [comment]
原来是这样，刚试了一下{type: cc.Integer, default: undefined}不行，以为不能加()，感谢回复
