### ISSUE TITLE
IOS Native audios issues

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17108]
### Cocos Creator version

3.x 2x

### System information

iphones

### Issue description

1.IOS game has been blocked by phone, enter background and come back , the game audio will be silence， which will happen in 3.x and 2.x
2.in ios system 17.5.1 when pickup the phone, and comeback , the game audio will be silence.
fixes #17106 

### Relevant error log output

none

### Steps to reproduce

1.IOS game has been blocked by phone, enter background and come back , the game audio will be silence， which will happen in 3.x and 2.x
issue one reproduce steps: 1.enter game 2.phone calling show 3. turn phonecall into background 4.turn game into background, 5pickup phone,6 hang off phone 7.back to game.
issue two reproduce steps: 1:enter game 2：phone calling show 3:pickup phone 4:turn phonecall into background 5:hang off phone 6.back to game.
2.in ios system 17.5.1 when pickup the phone, and comeback , the game audio will be silence.
reproduce steps: 1:enter game 2：phone calling show3:pickup phone 4:turn phonecall into background 5.turn game into background, 6turn phonecall into foreground,6 hang off phone 7.back to game.

### Minimal reproduction project

[audiodemo.zip](https://github.com/user-attachments/files/15573974/audiodemo.zip)

**Comment by bofeng-song** [comment]
Need to test other scenarios:
During a call, when the game is brought to the foreground, can the game function normally, and does sound playback cause a crash?

Current logic:
Sound can only resume playback after the interruption ends.

**Comment by tangkaikk** [comment]
Closes #17108
