### ISSUE TITLE
Let Tween System support any object type and string type support

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#17110]
### Use Case

由于考虑到时间和表达准确性，接下来使用中文。

该 issue 紧接着 https://github.com/cocos/cocos-engine/issues/17076 中的讨论。

我重新整理了一下思路，想出了一个完整的方案，请看：

改动：
- `props` 增加 `clone`、`asUpdate` 属性。
- 使 `tween` 支持 `string` 类型，并默认使用 `parseFloat` 或 `Number` 做数值转换处理，在赋值前使用 `Math.round`。
- `opts` 增加 `format` 属性。

示范：

对于合法数值字符串，提供简洁直观的处理方式：

```ts
tween(o).to(1,{ str: "100" });  // 如果你需要的是整数，引擎内部处理可以直接满足需求。
tween(o).to(1,{ str: "100" }, { format: v => v.toFixed(2) });  // 如果你需要的是小数或者其它任何返回合法数值字符串的处理。
```

对于更复杂的字符串缓动、实现任意类型的缓动，和完全控制插值过程，统一使用 `progress` 来实现：

```ts
const o = { gold: "¥100.00" };

tween(o).to(1, {
    gold: {
        value: "¥1000.00",
        progress: (start, end, current, ratio) => {
            start = Number(start.slice(1));
            end = Number(start.slice(1));
            return `¥${lerp(start, end, ratio).toFixed(2)}`;
        },
    },
});
```

上面稍微比较复杂的缓动代码会写得比较长，但我们这样设计的好处是对同类型的格式可以进行封装：

```ts
export function money(value) {
    return {
        value: `¥${value}`,
        progress: (start, end, current, ratio) => {
            start = Number(start.slice(1));
            end = Number(start.slice(1));
            return `¥${lerp(start, end, ratio).toFixed(2)}`;
        },
    }
}
```

然后写法就可以非常可怕地简洁：

```ts
tween(o).to(1,{ gold: money(100) });
```

所以多个不同属性在封装良好的情况下，它的可读性也可以很好：

```ts
tween(o).to(1, {
    gold: tweenFormat.currency(100),
    coin: tweenFormat.currency(100),
    health: tweenFormat.health(10),
    attack: tweenFormat.attack(10),
    lv: tweenFormat.lv(10),
    exp: tweenFormat.exp(10),
});
```

对于任意类型的支持，光有 `progress` 还不够，于是有了 `clone` 与 `asUpdate` 属性。

`asUpdate` 主要用于兼容旧的普通对象处理逻辑。
`clone` 主要用于处理 `start` 的初始化问题。

示范：

```ts
class AnyValue {
    constructor(
        public a: number,
        public b: number,
        public c: number,
    ) {}

    static lerp(
        start: AnyValue,
        end: AnyValue,
        current: AnyValue,
        ratio: number,
    ) {}

    clone(): AnyValue {}
}

const o = {
    v: new AnyValue(0, 0, 0),
};

tween(o).to(1, {
    v: {
        value: new AnyValue(1, 1, 1),
        progress: AnyValue.lerp,
        clone: v => v.clone(),
        asUpdate: true, // 默认 false，这个标志用于兼容旧的普通对象处理逻辑，也就是说启用这个标志表示完全掌控对象的插值过程，也就是不走之前处理普通对象的逻辑，而是像 number 一样调用 progress
    },
});
```

`asUpdate` 仅适用于对象，其它类型均无效果并发出警告。
`clone` 在非对象和字符串时均无效果并发出警告。（为什么字符串不发出警告？请看下面的提案）

还有一个提案不确定是否合理，就是让 `clone` 在遇到字符串时，不仅对 `start` 进行处理，还对 `end` 进行处理，那么就可以通过 `clone` 对字符串进行性能优化：

```ts
tween(o).to(1, {
    str: {
        value: "¥100.00",
        progress: (start, end, current, ratio) =>
            `¥${lerp(start, end, ratio).toFixed(2)}`,
        clone: v => Number(v.slice(1)),
    },
});
```

在这里，经过 `clone` 处理，传入 `progress` 的 `start` 和 `end` 变成了数值类型，这样就不用每帧进行类型转换了。

但是我注意到现在的代码是判断目标属性的类型来进行处理的，那么其实我们是可以允许虽然目标属性是字符串类型，但结束值可以传入数值的这种用法的：

```ts
const o = { gold: "¥100.00" };

tween(o).to(1, {
    gold: {
        value: 1000.00,     // <- 传入数值，而不是字符串
        progress: (start, end, current, ratio) =>
            `¥${lerp(start, end, ratio).toFixed(2)}`,
        clone: v => Number(v.slice(1)),
    },
});
```

这样的话其实不需要 `clone` 会对字符串进行特殊处理也可以对性能进行优化。

这就是全部，我们实现了：

- 支持任意类型！
- 支持完全控制插值过程！
- 没有破坏性变更！
- 提供 string 的默认处理逻辑，和合法数值字符串的简便格式化方式！
- 所有处理逻辑可以封装在类似 `tweenFormat` 的模块中，也就是社区可以发布一些类似 `lodash` 的字符串缓动工具库，让用户得到无论是日期、时间、或者是任意格式字符串的缓动的开箱即用支持！

**Comment by smallmain** [comment]
然后，我们应该修复 `props` 的 d.ts 以正确反映运行时行为，然后补充文档。

包括 `props` 其实一直都可以传入函数以在 `clone` 自身为新 `tween` 实例时重新计算目标值：

```ts
tween().to(1, { string: ()=> "asdf" });
```

**Comment by dumganhar** [comment]
```ts
tween(o).to(1, {
    str: {
        value: "¥100.00",
        progress: (start, end, current, ratio) =>
            `¥${lerp(start, end, ratio).toFixed(2)}`,
        clone: v => Number(v.slice(1)),
    },
});
```
> 在这里，经过 clone 处理，传入 progress 的 start 和 end 变成了数值类型，这样就不用每帧进行类型转换了。

这里直接用 clone 这个名字，感觉不是特别贴切。因为其输入是一个 string 输出是 number，违背了`克隆`这个单词的本意。
改为 `toNumber` 怎么样?

**Comment by dumganhar** [comment]
> 然后，我们应该修复 props 的 d.ts 以正确反映运行时行为，然后补充文档。

> 包括 props 其实一直都可以传入函数以在 clone 自身为新 tween 实例时重新计算目标值：

> tween().to(1, { string: ()=> "asdf" });

嗯，这个应该是因为之前从 2.x JS 版本引擎升级到 3.x TS 的时候，没有对这块做类型控制、文档、单元测试例的完善。我后续跟进一下。

**Comment by smallmain** [comment]
> ```ts
> tween(o).to(1, {
>     str: {
>         value: "¥100.00",
>         progress: (start, end, current, ratio) =>
>             `¥${lerp(start, end, ratio).toFixed(2)}`,
>         clone: v => Number(v.slice(1)),
>     },
> });
> ```
> 
> > 在这里，经过 clone 处理，传入 progress 的 start 和 end 变成了数值类型，这样就不用每帧进行类型转换了。
> 
> 这里直接用 clone 这个名字，感觉不是特别贴切。因为其输入是一个 string 输出是 number，违背了`克隆`这个单词的本意。 改为 `toNumber` 怎么样?

@dumganhar 

这个名字确实不好，当时我还不太确定是否有特殊处理 string 的必要，因为这个 `clone` 对 string 的支持好像除了用于性能优化之外没有其它的功能了。

但是为 string 增加一个 `toNumber` 而不是重用 `clone` 确实能让代码更清晰。

`toNumber` 足够好，但我个人更倾向于更短更通用的名称，比如：

`convert: (v: string) => number`
or
`parse: (v: string) => number`

**Comment by dumganhar** [comment]
修复在 props 里面自定义 progress, easing 的类型： https://github.com/cocos/cocos-engine/pull/17140
