### ISSUE TITLE
Cannot call native C++ method from TypeScript

### ISSUE THREAD

**Issue by yuigahamayuki** [cocos/cocos-engine#17113]
### Cocos Creator version

3.8.0

### System information

Windows

### Issue description

I want to modify cocos-engine code to customize the builtin rendering pipeline. I tried to add a new public method of ForwardPipeline class in ForwardPipeline.h. When I call the added function from TypeScript (a game Component), Visual Studio (**Debug Build**) reports the **"Invoking function failed"** error.

The added function's binding has been successfully generated in jsb_pipeline_auto.cpp, I put a breakpoint in the js_cc_pipeline_ForwardPipeline_${MY_NEW_FUNCTION}(se::State& s) function, but the breakpoint does not hit.

Then I tried calling the existing method RenderPipeline::getOcclusionQueryEnabled() from TypeScript as the following code snippets (take from cocos-example-projects occulusion-query.ts):
`if (NATIVE) {
            director.root.pipeline.setOcclusionQueryEnabled(true);
        }`
I still get the error.

The Visual Studio error output is pasted in **Relevant error log output** section.

### Relevant error log output

[ERROR]: [SE_ERROR]  (cocos-engine\native\cocos\bindings\jswrapper\v8\ScriptEngine.cpp, 1204): Invoking function failed, TypeError: director.root.pipeline.setOcclusionQueryEnabled is not a function

[ERROR]: [SE_ERROR]  (cocos-engine\native\cocos\bindings\jswrapper\v8\Object.cpp, 754): Invoking function failed, TypeError: director.root.pipeline.setOcclusionQueryEnabled is not a function

[ERROR]: [SE_ERROR]  (cocos-engine\native\cocos\bindings\jswrapper\v8\Object.cpp, 764): Invoking function (0000027BC6A32AE0) failed!

### Steps to reproduce

Create a TypeScript Component in a newly created project, implement the onEnable() method:
`onEnable(): void {
        if (NATIVE) {
            director.root.pipeline.setOcclusionQueryEnabled(true);
        }
    }`

**Comment by yuigahamayuki** [comment]
Update: The exact engine version is 3.8.2. I test the official cocos-example-projects/occlusion-query project with builtin engine (version 3.8.2), build a windows debug application, **setOcclusionQueryEnabled()** triggers the same error.

In occlusion-query.ts, I add **director.root.pipeline.pipelineSceneData.getOctree();**, this function is triggered. The modified function onToggle() in occlusion-query.ts is as follows:
```
    onToggle (toggle: Toggle) {
        if (NATIVE) {
            director.root.pipeline.pipelineSceneData.getOctree();
            director.root.pipeline.setOcclusionQueryEnabled(toggle.isChecked);
        }
        log('Occlusion query enabled: ' + toggle.isChecked);
    }
```
Why method of PipelineSceneData could be called, while method of RenderPipeline could not? The difference of the two classes I see is PipelineSceneData directly derives from RefCounted, while RenderPipeline does not.

BTW, RenderPipeline::getOcclusionQueryEnabled() seems deleted, so I deleted line 15 of occlusion-query.ts:
`this.toggleOcclusionQuery.isChecked = director.root.pipeline.getOcclusionQueryEnabled();`

**Comment by yuigahamayuki** [comment]
Found the problem. Since v3.6.0, the engine has re-implemented Native render pipeline. When calling director.root.pipeline in TypeScript, **Native** version will return an instance of RenderPipelineBridge (defined in Root.cpp), which derives from PipelineRuntime cpp class, while **TypeScript** version will return an instance of RenderPipeline (not a cpp class, defined in render-pipeline.ts).

The official cocos-example-projects are based on engine version 3.4.0, I guess native version of **director.root.pipeline** returns an instance of RenderPipeline (cpp class, defined in RenderPipeline.h)

**Comment by star-e** [comment]
> Found the problem. Since v3.6.0, the engine has re-implemented Native render pipeline. When calling director.root.pipeline in TypeScript, **Native** version will return an instance of RenderPipelineBridge (defined in Root.cpp), which derives from PipelineRuntime cpp class, while **TypeScript** version will return an instance of RenderPipeline (not a cpp class, defined in render-pipeline.ts).
> 
> The official cocos-example-projects are based on engine version 3.4.0, I guess native version of **director.root.pipeline** returns an instance of RenderPipeline (cpp class, defined in RenderPipeline.h)

Sorry for the inconvenience.

To support custom render pipeline in 3.6.0, we have refactored the native engine.
The custom pipeline and legacy pipeline share the common `PipelineRuntime` interface.

Native `RenderPipeline` cannot be access from typescript anymore, as we are moving forward to the custom pipeline.

Currently, occlusion query is not well supported in custom pipeline. The reason is that we have not yet worked out a cross-platform solution.

We might support occlusion query in the future release, and are also considering other methods such as PVS (potential visible set).
