### ISSUE TITLE
强烈要求 让开发者可以选择 ts版本的 spine runtime.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17116]
### Use Case

概述:
实测下来,  wasm版本的spine 并没有提升多少性能. wasm在计算方面可能确实快了些, 但是它和js之间的通讯也是耗时的, 提升的性能有时候并无法弥补通讯的消耗.
而且 spine 的wasm库 没有使用共享内存作为通讯(小游戏平台的wasm也不支持共享内存)    wasm 和 js 之间的通讯更慢.

强烈要求 让开发者可以选择 ts版本的 spine runtime.

( 在 https://github.com/cocos/cocos-engine/issues/17085#issuecomment-2153862659 里还有一些相关讨论 )

### Problem Description

见上

### Alternatives Considered

无

**Comment by minggo** [comment]
官方的 spine 的 JS runtime 和 c++ 的 runtime 是没有兼容的。引擎要去做这二者的统一的话就会很麻烦。后续也很难升级。另外，wasm 版本的性能是更高的。

**Comment by finscn** [comment]
> 官方的 spine 的 JS runtime 和 c++ 的 runtime 是没有兼容的。引擎要去做这二者的统一的话就会很麻烦。后续也很难升级。另外，wasm 版本的性能是更高的。

我把同样的spine动画 用 2.4  和 3.8 各做了一个demo,  2.4 性能比 3.8 好.  这是为什么呢?

**Comment by minggo** [comment]
有可能是你的交互过多了。可以给我们看看。另外，由于无法做兼容性，我们也没法一个平台提供一份。
