### ISSUE TITLE
Node.EventType.TOUCH_END 事件回调抛异常时，会导致其他 UI 事件派发错乱

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#17121]
### Cocos Creator version

3.8.3

### System information

Windows 11

### Issue description

假设存在以下层级节点
- n1
- n2

给定事件绑定
```ts
n1.on(Node.EventType.TOUCH_END, () => console.log("n1 TOUCH_END"));
n2.on(Node.EventType.TOUCH_END, () => { throw "n2 TOUCH_END error" });  // n2 事件回调抛异常
```

### Steps to reproduce

点击 n2 节点，释放触点，n2 会抛出异常，
这时候点击 n1 节点并释放触点，n1 的事件回调不会做出响应

怀疑是 n2 事件回调抛异常时，claimedTouchIdList 没有释放对 touchID 的引用，导致下次点击 n1 时，没办法正确处理事件派发

虽然事件回调里出现异常是开发者自己的锅，但是一旦出现异常，就会造成无法补救的结果，整个UI的事件派发就乱了，

感觉这里还是引擎侧在派发事件的时候做一下异常捕获比较合适，这样就算这次事件派发抛异常了，也不会影响下一次的事件派发

**Comment by dumganhar** [comment]
这个 PR https://github.com/cocos/cocos-engine/pull/17032 应该能修复你说的问题，可以考虑合并一下补丁再试试？

**Comment by minggo** [comment]
@PPpro 补丁有问题的话再重开 issue 吧。

**Comment by PPpro** [comment]
[NewProject.zip](https://github.com/user-attachments/files/16092125/NewProject.zip)

我来提交一个修复和复现 demo，麻烦 review 下https://github.com/cocos/cocos-engine/pull/17295

@dumganhar
