### ISSUE TITLE
IOS Native could not build or run.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#17134]
### Cocos Creator version

3.8.2

### System information

MacOS

### Issue description

in Xcode 15.4, IOS 17.5.1.

https://forum.cocos.org/t/topic/148813/6
https://forum.cocos.org/u/smallmain/activity

### Steps to reproduce

.

**Comment by minggo** [comment]
3.8.3 修复了 https://github.com/cocos/cocos-engine/pull/16849
