### ISSUE TITLE
移动正交相机，相机预览画面残留。

### ISSUE THREAD

**Issue by wsLyr** [cocos/cocos-engine#17167]
### Cocos Creator version

3.8.3

### System information

win10

### Issue description

移动正交相机，相机预览画面残留看图
![image](https://github.com/cocos/cocos-engine/assets/53005137/1bd77f4f-ee0b-4af8-aff3-6cc2a9ab5e18)

### Relevant error log output

no response.

### Steps to reproduce

创建一个空项目，移动canvas下的相机就能复现bug

### Minimal reproduction project

no response.

**Comment by a1076559139** [comment]
你摄像机的`Clear Flags`是不是`Dont Clear`

**Comment by wsLyr** [comment]
> 你摄像机的`Clear Flags`是不是`Dont Clear`

是depth only

**Comment by wuzhiming** [comment]
@knoxHuang 检查一下

**Comment by knoxHuang** [comment]
<img width="222" alt="image" src="https://github.com/user-attachments/assets/daafd24b-06c4-4ec1-99ac-c7b8cbb8f060" />

预期效果是对的

如果跟浏览器不一致的原因是因为为了性能提升，把 WebGLContextAttributes 中的 preserveDrawingBuffer 关闭了，所有才不会出现残影

不过残留的效果与原生平台的效果是一样
