### ISSUE TITLE
提交个android调用websocket内存泄漏的错误 以及修改方案

### ISSUE THREAD

**Issue by luyangliu616** [cocos/cocos-engine#17162]
### Cocos Creator version

3.8.0

### System information

Android

### Issue description

主要体现在websocket的传输后 内存泄漏问题。   cocos我感觉开源非常好，但是可编程渲染管线支持非常差。 特别是用js写代码还不能写线程 你要是用cpp写代码我立马抛弃unity    ，   毕竟以后dots为天下 希望支持dots时候改成cpp写代码

websocket 拿onbinarymessage。在android 的时候会有内存不断升高的bug，经过长时间的探究发现 需要在Websocket-okhttp.cpp的binarymessage里面加一句env->ReleaseByteArrayElements(static_cast<jbyteArray>(strongRef), array, 0);

### Steps to reproduce

![image](https://github.com/cocos/cocos-engine/assets/8186724/2f028707-2718-4cdc-b40e-9431d13b4fbd)

**Comment by dumganhar** [comment]
感谢反馈，已经提交一个紧急修复： https://github.com/cocos/cocos-engine/pull/17164
