### ISSUE TITLE
自定义渲染管线中DevicePass里framebuffer中的texture可能失效

### ISSUE THREAD

**Issue by hszhsh** [cocos/cocos-engine#17197]
### Cocos Creator version

3.8.3

### System information

web

### Issue description

如题，如果texture销毁，某种情况下framebuffer不会更新，导致引用无效的texture

### Steps to reproduce

自定义pass中两个pass使用同一个rendertarget，第一次正常，关掉后处理，相应纹理会销毁，第二次打开的时候，第一个pass的framebuffer正常更新，第二个不会更新，导致引用无效的texture

**Comment by star-e** [comment]
This issue might have been fixed in v3.8.4.
https://github.com/cocos/cocos-engine/pull/17669
