### ISSUE TITLE
IOS Native: [ERROR]: CCMTLBuffer:: Illegal index buffer stride.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#17206]
### Cocos Creator version

3.8.2

### System information

MacOS

### Issue description

https://forum.cocos.org/t/topic/148813/14?u=smallmain

### Steps to reproduce

.

**Comment by minggo** [comment]
It is fixed here: https://github.com/cocos/cocos-engine/pull/17214.
