### ISSUE TITLE
Ios Native don't support .ogg audio.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#17218]
### Cocos Creator version

3.8.2

### System information

MacOS

### Issue description

Unable to play and error, change to.mp3 to solve.

### Steps to reproduce

.

**Comment by minggo** [comment]
iOS system doesn't support ogg. And we don't have plan to support it in engine by using a 3rd lib.

**Comment by smallmain** [comment]
> iOS system doesn't support ogg. And we don't have plan to support it in engine by using a 3rd lib.

@minggo 

please update document: https://docs.cocos.com/creator/3.8/manual/zh/asset/audio.html#%E6%94%AF%E6%8C%81%E7%9A%84%E9%9F%B3%E9%A2%91%E8%B5%84%E6%BA%90%E7%9A%84%E6%A0%BC%E5%BC%8F

**Comment by minggo** [comment]
Ok, we will take a look.

**Comment by minggo** [comment]
@bofeng-song please update the documentation.
