### ISSUE TITLE
Script culling in engine-internal

### ISSUE THREAD

**Issue by star-e** [cocos/cocos-engine#17228]
### Use Case

Need someway to cull individual scripts in `cocos-engine/editor/assets` folder (engine-internal)

### Problem Description

There are circumstances when certain TS script is not used in engine-internal. This will increase app size.
It will be better if they are not included.

### Alternatives Considered

Manually delete them from cocos-engine.

**Comment by dumganhar** [comment]
A similar issue: https://github.com/cocos/cocos-engine/issues/16850

**Comment by star-e** [comment]
Added in https://github.com/cocos/cocos-engine/pull/17379
