### ISSUE TITLE
When reopening a prefab containing missing resources, it will not print missing errors.

### ISSUE THREAD

**Issue by smallmain** [cocos/cocos-engine#17221]
### Cocos Creator version

3.8.3

### System information

MacOS

### Issue description

RT.

### Steps to reproduce

Missing scripts throw an error, asset don't.

**Comment by minggo** [comment]
I don't quite understand the issue. Did you mean should print error message when an assent in a prefab misses?

**Comment by smallmain** [comment]
> I don't quite understand the issue. Did you mean should print error message when an assent in a prefab misses?

Yes. 

Like this project I gave you.

https://pan.quark.cn/s/a73d4d2be009

Image resources such as res are deleted, possibly after a series of saving, restarting the editor, and so on.

Opening the prefab with the missing resource will not print the missing error, but will only see it rendered in Burgundy.

---

就比如我给你的这个工程。

https://pan.quark.cn/s/a73d4d2be009

把 res 等图片资源删除，可能经过了一系列保存，重启编辑器等操作之后。

再打开含有丢失资源的预制体，不会打印丢失错误，只能看到渲染为紫红色。

**Comment by minggo** [comment]
Ok, i changed the title.

**Comment by wuzhiming** [comment]
> > I don't quite understand the issue. Did you mean should print error message when an assent in a prefab misses?
> 
> Yes.
> 
> Like this project I gave you.
> 
> https://pan.quark.cn/s/a73d4d2be009
> 
> Image resources such as res are deleted, possibly after a series of saving, restarting the editor, and so on.
> 
> Opening the prefab with the missing resource will not print the missing error, but will only see it rendered in Burgundy.
> 
> 就比如我给你的这个工程。
> 
> https://pan.quark.cn/s/a73d4d2be009
> 
> 把 res 等图片资源删除，可能经过了一系列保存，重启编辑器等操作之后。
> 
> 再打开含有丢失资源的预制体，不会打印丢失错误，只能看到渲染为紫红色。

sorry late for this，but the file is delete.
can you upload again.

**Comment by smallmain** [comment]
> > > I don't quite understand the issue. Did you mean should print error message when an assent in a prefab misses?
> > 
> > 
> > Yes.
> > Like this project I gave you.
> > https://pan.quark.cn/s/a73d4d2be009
> > Image resources such as res are deleted, possibly after a series of saving, restarting the editor, and so on.
> > Opening the prefab with the missing resource will not print the missing error, but will only see it rendered in Burgundy.
> > 就比如我给你的这个工程。
> > https://pan.quark.cn/s/a73d4d2be009
> > 把 res 等图片资源删除，可能经过了一系列保存，重启编辑器等操作之后。
> > 再打开含有丢失资源的预制体，不会打印丢失错误，只能看到渲染为紫红色。
> 
> sorry late for this，but the file is delete. can you upload again.

Strange, why was the file deleted? I didn't save this project, but you can try using any project, referencing images in a prefab, then deleting the images, closing the prefab, opening the prefab, saving the prefab, restarting the editor—this kind of operation.  After that, opening the prefab again should stop the missing error from appearing.

**Comment by knoxHuang** [comment]
The logs are output, they are just adjusted to be output within the scenario debugging tool, which you can find through the main menu developer portal to open the scenario debugging tool for viewing

**Comment by smallmain** [comment]
@knoxHuang We're discussing a processing method that results in a very poor user experience.

**Comment by smallmain** [comment]
@knoxHuang Why not directly print the error message if users cannot tell which prefabricated components have missing resources?
