### ISSUE TITLE
Refine scrollview behaviour on mobile

### ISSUE THREAD

**Issue by kwellman** [cocos/cocos-engine#1722]
When testing the scroll view component on my iPhone, there is a very noticeable "slippery" feel to scrolling. A swipe to scroll will never generate the expected amount of initial scrolling velocity you expect from using native apps.  It's an unpleasant user experience.

This seems to be caused by the *brake* parameter. Unlike in cocos2d-x C++ (which has a scroll view that feels a lot better), the *brake* value is applied in the calculateTouchMoveVelocity method.

e.g. https://github.com/cocos-creator/engine/blob/master/cocos2d/core/components/CCScrollView.js#L1301

        return cc.p(totalMovement.x * (1 - this.brake) / totalTime,
                    totalMovement.y * (1 - this.brake) / totalTime);

Why apply the brake when calculating touch velocity? This is not done in cocos2d-x, and will always cause the calculated velocity to be lower than it actually is for every non-zero value for brake.

**Comment by zilongshanren** [comment]
@kwellman 
The brake value used for calculating touch velocity is mainly for slowing down the inertia scrolling.

If you want to achieve smoothly scrolling, you could change the brake value to 0.3-0.5.
