### ISSUE TITLE
creator3.8，OpenGL2渲染崩溃问题，GLES2PrimaryCommandBuffer里面draw函数数组越界。必现

### ISSUE THREAD

**Issue by zhoujianbo0** [cocos/cocos-engine#17234]
### Cocos Creator version

3.8

### System information

Windows10

### Issue description

if (_isStateInvalid) {
        ccstd::vector<uint32_t> &dynamicOffsetOffsets = _curGPUPipelineState->gpuPipelineLayout->dynamicOffsetOffsets;
        ccstd::vector<uint32_t> &dynamicOffsets = _curGPUPipelineState->gpuPipelineLayout->dynamicOffsets;
        for (size_t i = 0U; i < _curDynamicOffsets.size(); i++) {
            size_t count = dynamicOffsetOffsets[i + 1] - dynamicOffsetOffsets[i];
            // CC_ASSERT(_curDynamicOffsets[i].size() >= count);
            count = std::min(count, _curDynamicOffsets[i].size());
            if (count) memcpy(&dynamicOffsets[dynamicOffsetOffsets[i]], _curDynamicOffsets[i].data(), count * sizeof(uint32_t));
        }
        cmdFuncGLES2BindState(GLES2Device::getInstance(), _curGPUPipelineState, _curGPUInputAssember,
                              _curGPUDescriptorSets.data(), dynamicOffsets.data(), &_curDynamicStates);

        _isStateInvalid = false;
    }
    
for循环里面的dynamicOffsetOffsets[i + 1]获取会数组越界。我看OpenGL3里面的代码是做了这方面处理的。希望引擎团队跟进OpenGL2的问题修复。我VS 和 AS 都断点调试了确认有问题。下面提供必现问题的demo工程
[label-test.zip](https://github.com/user-attachments/files/16006847/label-test.zip)

### Steps to reproduce

creator3.8，OpenGL2渲染崩溃问题，GLES2PrimaryCommandBuffer里面draw函数数组越界。必现

**Comment by star-e** [comment]
Fixed and will be released in v3.8.5.

**Comment by star-e** [comment]
https://github.com/cocos/cocos-engine/pull/17235
