### ISSUE TITLE
3.8引擎因为渲染问题导致部分安卓模拟器(比如 逍遥模拟器)无法运行问题，直接影响所有出了原生包的creator游戏。必现！

### ISSUE THREAD

**Issue by zhoujianbo0** [cocos/cocos-engine#17265]
### Cocos Creator version

3.8

### System information

Windows10

### Issue description

[label-test.zip](https://github.com/user-attachments/files/16051720/label-test.zip)
提供必现demo，按照默认的选项出个安卓包，在部分模拟器(比如逍遥模拟器或者夜神模拟器)上面无法运行。经过检查，发现是opengl3的渲染问题。如果关闭OpenGL3采用OpenGL2渲染则可以运行，如果开启平滑采用平滑的渲染模式发现也可以运行。然而打包默认是选择gl3和gl2，关闭平滑，这就导致打出来的原生包几乎都会有这个问题！！！影响所有原生游戏

### Steps to reproduce

3.8引擎因为渲染问题导致部分安卓模拟器(比如 逍遥模拟器)无法运行问题，直接影响所有出了原生包的creator游戏。必现！

**Comment by star-e** [comment]
这个问题修复比较耗时。
有个临时解决方案：
可以在`cocos/native/cocos/renderer/GFXDeviceManager.h` 中 undef  `CC_USE_GLES3`，来强制使用GLES2。
![image](https://github.com/cocos/cocos-engine/assets/13654656/56801b38-62fe-480c-8166-fc005f5e523c)

Temporary solution:
You can force GLES2 by undef `CC_USE_GLES3` in `cocos/native/cocos/renderer/GFXDeviceManager.h`

**Comment by zhoujianbo0** [comment]
这样不行啊，游戏的压缩纹理不能用了，ETC2。而且现在几乎都不用gl2了，我们不能走回头路啊！问题总归要解决的，而且是这样影响所有原生游戏的底层问题。

**Comment by star-e** [comment]
如果要用GLES3的话，建议先开启swappy。
GLES3在真机上没有遇到过这问题，模拟器环境比较复杂，定位问题需要时间。

**Comment by zhoujianbo0** [comment]
我们这儿刚刚发现了3.7.3是没有这个问题的。是3.8出现了这个问题。可以比较两边的代码看看问题出在哪里。通过比较 引擎专门负责这块的人应该会比较容易发现问题！！

**Comment by zhoujianbo0** [comment]
比较两边opengl3的代码改动很大，问题也是出在opengl3的代码上面。

**Comment by star-e** [comment]
初步定位到添加msaa的pr引起了问题。

SHA-1: 979e3c9677a47b4357d6d6fe3f8908ec7f2e3ee3
* V3.8.1 msaa (#15584)

进一步排查中。

**Comment by star-e** [comment]
https://github.com/cocos/cocos-engine/pull/17300
可以试试这个修复，在3.8.1和3.8.5验证过。 @zhoujianbo0

**Comment by zhoujianbo0** [comment]
测试可以了，大佬牛逼！

**Comment by star-e** [comment]
Fixed in #17300.
The problem is caused by GLES3 backend and the app will stuck on splash screen on some Android Emulator.
