### ISSUE TITLE
cc.audioEngine.playEffect (typescript, html5) [bug]

### ISSUE THREAD

**Issue by vmatkarimov** [cocos/cocos-engine#1729]
Hello,

Just finish one of the tutorial "Pick up the star".

When I try to use "cc.audioEngine.playEffect" function, typescript compiler doiesn't saw that function. I look into creator.d.ts and also does not saw "playEffect" function in it. Ok, I just left all as is and then start the simulator in Cocos Creator and the game work like a charm. But in my VSCode were errors: _**'Property 'playEffect' does not exist on type 'typeof audioEngine'.'**_

After that, I ran the game through VSCode: "Creator Debug: Launch Chrome", the game does not work and in VSCode show some Errors: **_"DOMException: Unable to decode audio data"_**.

![cc audioengine playeffect_error](https://user-images.githubusercontent.com/5332153/27057851-900bc454-4fd6-11e7-9e5f-120c9dc29f6b.png)

**Comment by vmatkarimov** [comment]
I add static functions (playEffect and playMusic) in **creator.d.ts** and the problem was gone.

I think creator.d.ts need to update.

**Comment by PooperPig** [comment]
This still seems to be an issue 5 months later?

**Comment by jareguo** [comment]
This is because playEffect is deprecated. But we are planning to add it come back. Maybe you should just ignore the warning for now.
