### ISSUE TITLE
搭建好的场景 无法正常运行（黑屏）

### ISSUE THREAD

**Issue by renoyuan** [cocos/cocos-engine#17302]
### Cocos Creator version

3.8.3

### System information

win11 谷歌浏览器

### Issue description

搭建好的场景 无法正常运行（黑屏）
下面是报错信息
Error: Unable to resolve bare specifier '__unresolved_2' from http://localhost:7456/scripting/x/chunks/6d/6d8fd2b0177941b032ddc0733af48a561fb60657.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (resolve.js:12:9)
![image](https://github.com/cocos/cocos-engine/assets/50486789/bf564505-ea69-4222-9e78-5bf5196245c7)

   请问这个一般要怎么去排查呢？

### Steps to reproduce

搭建好的场景 无法正常运行（黑屏）
下面是报错信息
Error: Unable to resolve bare specifier '__unresolved_2' from http://localhost:7456/scripting/x/chunks/6d/6d8fd2b0177941b032ddc0733af48a561fb60657.js (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (resolve.js:12:9)
   请问这个一般要怎么去排查呢？

**Comment by minggo** [comment]
这个错误没看明白是哪里的问题。方便的话，可以提供个 demo。

**Comment by renoyuan** [comment]
谢谢大佬，已解决。原因是 我有两个场景 A 场景 B 我运行场景A 的时候场景B 有个关联脚本中有一些语法错误。导致整体报错了，场景A 也无法显示，这个感觉挺奇怪的，也没有错误提示。

**Comment by minggo** [comment]
好的，那我关闭这个 issue 了。
