### ISSUE TITLE
spine 开启 enableBatch 后,  移动 缩放 等变换会延迟一帧.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17307]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

spine 开启 enableBatch 后,  移动 缩放 等变换会延迟一帧.

比如 我在 第 n 帧的 update 里 移动了 spine 所在节点,  并且同步移动了 另一个普通的 sprite 节点.
spirte节点会正常移动, 但是 spine 会滞后一帧. 虽然最后还是会和 sprite 同步, 但是在移动过程中 滞后感非常强烈.
尤其在游戏帧率不到60时.

### Steps to reproduce

如上所述

**Comment by finscn** [comment]
补充: 微信小游戏 和 抖音小游戏真机上 出现的情况. 原生app没有测试.

**Comment by bofeng-song** [comment]
@finscn 
看director.ts
目录的逻辑：
update 里如果执行了 移动 缩放 等变换
执行结束后才执行 uiRendererManager.updateAllDirtyRenderers();
->spine/simple.ts  updateComponentRenderData()-> 之后在当前帧就会执行一下逻辑：
if (comp.enableBatch) {
        const worldMat = comp.node.worldMatrix;
        let index = 0;
        for (let i = 0; i < vc; i++) {
            index = i * floatStride;
            tempVecPos.x = vbuf[index];
            tempVecPos.y = vbuf[index + 1];
            tempVecPos.z = 0;
            tempVecPos.transformMat4(worldMat);
            vbuf[index] = tempVecPos.x;
            vbuf[index + 1] = tempVecPos.y;
            vbuf[index + 2] = tempVecPos.z;
        }
    }
    
    
    看代码目前没发现问题，方便的话，还请上传demo

**Comment by finscn** [comment]
为了优化性能, 我不会每帧都执行  spine 的 skeleton.updateAnimation()  
而是隔帧执行. 

不执行 updateAnimation, 就不会执行 markForUpdateRenderData()
开启 enableBatch 后 ,spine 的 USE_LOC = false 了
USE_LOC 的值 是否和 执行markForUpdateRenderData();  有什么关联呢?

目前看来 关闭 enableBatch 时,   隔帧执行 updateAnimation() 和 markForUpdateRenderData() 也没什么问题
但是 开启enableBatch后,  隔帧执行 就不行了.

另外 updateAnimation 里调用了 其他cpp的原生方法, 我就不知道具体啥逻辑了.

**Comment by bofeng-song** [comment]
enableBatch开启，spine/assemble/simple.ts会处理变形相关的。
你隔一帧才调用updateAnimation，延迟一帧响应是正常的。若没其他问题，该issue后面会关闭
