### ISSUE TITLE
在处理 fbx 模型时,   meta里的 "hasAlpha" 变来变去.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17322]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

我们公司 两台 mac (操作系统版本一样) , 1 台windows .
出现了非常奇怪的现象
 从 cocos打开项目后,  fbx.meta 的 hasAlpha 属性会被 其中一台mac设置为 true,  
但是另一台 mac 和 windows 会改为 false.

### Steps to reproduce

如上所述

**Comment by finscn** [comment]
我使用的图片的 meta信息: 
<img width="613" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/3fdda583-2e82-45bd-8232-1939f63c4165">
两个都是false

但是 fbx的meta里,  有的是一个true一个false,  有的是 两个true . 

我确定图片本身是没有alpha的.

**Comment by finscn** [comment]
@minggo , 快半年了.  是不是负责的人离职了?  要不要让 knoxHuang 来看看? 我看另一个 fbx meta的问题是他处理的.

**Comment by minggo** [comment]
休产假了。

**Comment by knoxHuang** [comment]
@finscn 给我一下能复现的 fbx 模型 或者 demo 吧，这样能快点排查

**Comment by finscn** [comment]
> @finscn 给我一下能复现的 fbx 模型 或者 demo 吧，这样能快点排查

一个内联png图片(但是png图片没有透明像素)的 fbx文件 就可以复现.

**Comment by knoxHuang** [comment]
经过沟通，暂时先关闭，如在复现再打开

<img width="429" alt="image" src="https://github.com/user-attachments/assets/2291ca80-75fe-4724-963d-4c324e528e0d" />
