### ISSUE TITLE
cocos 编辑器 无从从构建面板删除无用的scene

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17338]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

当我删除了一个 scene 后,  构建发布 面板里 只有错误提示, 但是我无法改动

<img width="529" alt="image" src="https://github.com/cocos/cocos-engine/assets/288367/c1fb2096-c569-46f9-b1a1-c4790555b510">

只有重新创建一个构建方案, 非常麻烦. 希望能支持在这个页面自动删除不存在的scene.

### Steps to reproduce

如上

**Comment by yanOO1497** [comment]
重新全选全部场景可以绕过，这个问题已在下个版本修复。
