### ISSUE TITLE
Button,ProgressBar,EditBox等的子节点Label，Bar, TEXTLABEL,PLACEHOLDER_LABEL在创建时其layer没有跟随父节点

### ISSUE THREAD

**Issue by Will-Z666** [cocos/cocos-engine#17354]
### Cocos Creator version

3.8.5

### System information

Win10

### Issue description

我在layer为自定义UI_FRONT的节点下创建Button,他的layer是UI_FRONT,但其子节点Label的layer仍是UI_2D。

### Steps to reproduce

Button,ProgressBar,EditBox已测，其他有子节点的应该也有类似问题

**Comment by knoxHuang** [comment]
This issue has been fixed in 3.8.6
