### ISSUE TITLE
(Cocos Creator - CI/CD) Endless build build via cmd on build agent teamcity: Stops at this log and loads endlessly - [Package] engine@1.0.9 enable

### ISSUE THREAD

**Issue by mlkvs** [cocos/cocos-engine#17355]
### Cocos Creator version

3.8.3, 3.8.2, 3.8.1, 3.8.0

### System information

Windows 10

### Issue description

filePath: [en/publish/publish-in-command-line.md](https://github.com/cocos/cocos-docs/blob/master/versions/2.4/en/publish/publish-in-command-line.md)
content:
Good afternoon!

For some reason teamcity build agent does not build a build.

The logs show that the process reaches the following point:
[08:11:47 ](https://ci.tiltshift.xyz/buildConfiguration/Zuma_Project_Test/2690?buildTab=log&linesState=102&logView=flowAware&focusLine=102)OUTPUT: engine:compile-builtin-engine-success (154ms)
[08:11:47 ](https://ci.tiltshift.xyz/buildConfiguration/Zuma_Project_Test/2690?buildTab=log&focusLine=103&linesState=103&logView=flowAware)OUTPUT: Load engine in C:\Program Files\Cocos Creator\Creator\3.8.3\resources\resources\3d\engine
[08:11:47 ](https://ci.tiltshift.xyz/buildConfiguration/Zuma_Project_Test/2690?buildTab=log&focusLine=104&linesState=104&logView=flowAware)OUTPUT: Profile changed: engine (modules.includeModules: 2d,3d,animation,audio,base,debug-renderer,geometry-renderer,gfx-webgl,gfx-webgl2,intersection-2d,light-probe,meshopt,occlusion-query,particle,particle-2d,physics-2d-box2d,physics-ammo,primitive,profiler,skeletal-animation,spine,terrain,tween,ui)
[08:11:47 ](https://ci.tiltshift.xyz/buildConfiguration/Zuma_Project_Test/2690?buildTab=log&focusLine=105&linesState=105&logView=flowAware)OUTPUT: Register native engine in C:\Program Files\Cocos Creator\Creator\3.8.3\resources\resources\3d\engine\native
[08:11:47 ](https://ci.tiltshift.xyz/buildConfiguration/Zuma_Project_Test/2690?buildTab=log&focusLine=106&linesState=106&logView=flowAware)OUTPUT: [Package] engine@1.0.9 enable

However, if you build the build by hand through the engine or exactly the same way through the command line - everything works correctly. The build is assembled successfully

cmd: CocosCreator.exe --project "./zuma" --build "configPath=./zuma/configs/buildConfig_web-mobile.json"

log on build agent:
Starting: C:\BuildAgent\temp\agentTmp\custom_script11267838237146798565.cmd
08:13:47  in directory: C:\BuildAgent\work\bc951c68fcb756c6
08:13:48  OUTPUT: Arguments:
08:13:48  OUTPUT: C:\Program Files\Cocos Creator\Creator\3.8.3\CocosCreator.exe: true
08:13:48  OUTPUT: project: C:\BuildAgent\work\bc951c68fcb756c6\zuma
08:13:48  OUTPUT: build: configPath=./zuma/configs/buildConfig_web-mobile.json
08:13:48  OUTPUT: dev: false
08:13:48  OUTPUT: home: C:\Windows\system32\config\systemprofile.CocosCreator
08:13:48  OUTPUT:
08:13:48  OUTPUT: [Package] metrics@1.0.0 enable
08:13:49  OUTPUT: [Package] menu@1.0.0 enable
08:13:49  OUTPUT: [Package] profile@1.0.0 enable
08:13:49  OUTPUT: [Package] project@1.0.6 enable
08:13:49  OUTPUT: [Package] messages@1.0.0 enable
08:13:49  OUTPUT: [Package] utils@1.0.0 enable
08:13:49  OUTPUT: [Package] program@1.0.4 enable
08:13:49  OUTPUT: [Package] tester@1.0.0 enable
08:13:49  OUTPUT: [Package] information@1.0.1 enable
08:13:49  OUTPUT: [Package] preferences@1.0.0 enable
08:13:49  OUTPUT: [Package] Profile Migrate project: [1.0.8 -> 1.0.9]: engine@Cocos Creator...
08:13:49  OUTPUT: [Package] Profile migrateProject: engine(1.0.9)...
08:13:50  OUTPUT: [EditorQuickCompiler]Version information looks good.
08:13:50  OUTPUT: Note, quick compiler does not get launched.
08:13:50  OUTPUT: engine:compile-builtin-engine-success (154ms)
08:13:50  OUTPUT: Load engine in C:\Program Files\Cocos Creator\Creator\3.8.3\resources\resources\3d\engine
08:13:51  OUTPUT: Profile changed: engine (modules.includeModules: 2d,3d,animation,audio,base,debug-renderer,geometry-renderer,gfx-webgl,gfx-webgl2,intersection-2d,light-probe,meshopt,occlusion-query,particle,particle-2d,physics-2d-box2d,physics-ammo,primitive,profiler,skeletal-animation,spine,terrain,tween,ui)
08:13:51  OUTPUT: Register native engine in C:\Program Files\Cocos Creator\Creator\3.8.3\resources\resources\3d\engine\native
08:13:51  OUTPUT: [Package] engine@1.0.9 enable

Running...

### Relevant error log output
Errors not found. Log stay...
08:13:51   OUTPUT: [Package] engine@1.0.9 enable

### Steps to reproduce

Run through the teamcity build agent
cmd: CocosCreator.exe --project "./zuma" --build "configPath=./zuma/configs/buildConfig_web-mobile.json"

If you build on other computers or on the same build agent using this command - everything works correctly. 

However, as soon as I try to do it through teamcity build agent via build step, it reaches the engine startup and loads endlessly

### Minimal reproduction project

Work it on empty project

**Comment by Mrrebrik-code** [comment]
The solution was simple. It was enough to grant administrator rights to the agent

You can check this online. By launching the agent manually through the console with administrator rights.

/bin/agent.sh 
agent.sh start
agent.sh stop

**Comment by mlkvs** [comment]
The solution to this was simple. It was enough to grant administrator rights to the agent

You can check this online. By launching the agent manually through the console with administrator rights.

/bin/agent.sh 
agent.sh start
agent.sh stop

Continue:
I created a separate user for the server, configured access rights for it (added it to the administrators group), but with some restrictions for security purposes.

Then I decided to write a service for myself in .net (it simply ran the build command for CocosCreator.exe and processed the execution result, which is where the code for terminating the process came from).

I configured this service to run under the name of the user I created.

This is roughly what my service looked like (more precisely, its main logic).

Link: https://gist.github.com/Melkov-source/a915e0c7cc7f26d26a8d5d10b83a050c
