### ISSUE TITLE
Releasing the LMB outside the canvas keeps MouseInput._isPressed boolean true

### ISSUE THREAD

**Issue by Remmoze** [cocos/cocos-engine#17368]
### Cocos Creator version

3.8.2

### System information

Windows 10

### Issue description

`MouseInput` has a boolean inside of it called [`.isPressed`](https://github.com/cocos/cocos-engine/blob/c4969f4f477cdb1f1afbe1ff856e7bc15e578e66/pal/input/web/mouse-input.ts#L39). It is [set to `true`](https://github.com/cocos/cocos-engine/blob/c4969f4f477cdb1f1afbe1ff856e7bc15e578e66/pal/input/web/mouse-input.ts#L140) when MOUSE_DOWN event is dispatched, and [to `false`](https://github.com/cocos/cocos-engine/blob/c4969f4f477cdb1f1afbe1ff856e7bc15e578e66/pal/input/web/mouse-input.ts#L143) when MOUSE_UP event is dispatched. When mouse leaves the area of the canvas and LMB gets released, `.isPressed` boolean is stuck at `true` until new MOUSE_DOWN event is triggered. In my cause this is troublesome, because my game is primarily a scrollview.
When LMB gets released outside of the canvas and then the cursor returns to the game, the scrollview scrolls even though LMB is not pressed.

https://github.com/user-attachments/assets/da902f84-4f63-4e92-98f9-bde733ab46d5

For my game, I've hacked my way around the engine and trigger a `MOUSE_UP` when `mouseleave` event is dispatched. 
```ts
export function enableMouseLeave () {
    // @ts-ignore
    input._mouseInput._canvas?.addEventListener('mouseleave', input._mouseInput._createCallback('mouse-up'));
}
```
For my game in particular, this works great, but I do realize that this might be a bad solution for other games. 
Perhaps the solution should be to respond to `mouseleave` event only for scrollview?
Either way, that fixed my issue:

https://github.com/user-attachments/assets/dde3ad92-b5c6-4837-a86e-9cbe5b19ab9a

### Steps to reproduce

1) Create a scrollview the size of the game
2) hold left mouse button to start scrolling
3) leave the bounds of the canvas 
4) release the left mouse button
5) return cursor to the scrollview
6) scrollview is getting scrolled even without pressed left mouse button

**Comment by minggo** [comment]
It is fixed in https://github.com/cocos/cocos-engine/pull/16886. Of course, should also include https://github.com/cocos/cocos-engine/pull/17576 to fix event name conflict.

Or you can try v3.8.4 when it is fixed.
