### ISSUE TITLE
希望能考虑下出差办公的程序员, 不要"断网不可用".

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17384]
### Use Case

希望能考虑下出差办公的程序员, 不要"断网不可用".
现在的 3.8.3 如果没有联网 ,没有登录cocos账号, 无法预览项目 , 无法预览自动图集.
以前2.4 系列并不会这样.

我能理解你们联网的目的. 但是至少有个时间宽容度. 比如我联网后 未来48小时内 无网也能用.

并不是所有人的出差环境都是实时有网的. 

希望cocos能考虑下那种时时刻刻都需要办公的苦逼程序员.

### Problem Description

.

### Alternatives Considered

.

**Comment by finscn** [comment]
补充:
无网络时, 启动cocos, 选择跳过登录.
然后在ide里如果要预览项目, ide控制台会报错

<img width="920" alt="image" src="https://github.com/user-attachments/assets/940065cb-0279-4406-92ca-caeb577e598b">

浏览器那边没有任何反应 空白屏幕, 也不报错. 
等待几十秒后, 浏览器会给出 ERR_CONNECTION_REFUSED 错误.

**Comment by finscn** [comment]
再补充:
我是 macos 14.5

**Comment by wuzhiming** [comment]
我们没有做无网络无法使用的限制，无法预览的问题，更新设备列表的时候出现的一个 bug，如果不着急就等3.8.4 如果着急你用这个插件，论坛上也有，临时修复一下下。
[fix-devices-1.0.2.zip](https://github.com/user-attachments/files/16278249/fix-devices-1.0.2.zip)

**Comment by finscn** [comment]
> 我们没有做无网络无法使用的限制，无法预览的问题，更新设备列表的时候出现的一个 bug，如果不着急就等3.8.4 如果着急你用这个插件，论坛上也有，临时修复一下下。 [fix-devices-1.0.2.zip](https://github.com/user-attachments/files/16278249/fix-devices-1.0.2.zip)

谢谢.
那无法预览自动图集 也是这个问题吗?

**Comment by yanOO1497** [comment]
无法预览自动图集是什么意思？有报错效果截图吗？

**Comment by finscn** [comment]
> 无法预览自动图集是什么意思？有报错效果截图吗？

这个问题请无视. 是之前配置有问题 , 我的错
