### ISSUE TITLE
IDE的自动图集预览时, 希望能显示一下生成的图集的尺寸

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17386]
### Use Case

目前只会显示图片, 不会显示尺寸

### Problem Description

如上

### Alternatives Considered

如上

**Comment by yanOO1497** [comment]
已采纳，下个版本添加。

![image](https://github.com/user-attachments/assets/f0e4533e-92f3-4be3-8672-4e61932ab886)
