### ISSUE TITLE
抖音小游戏安卓平台, 渲染动态合图的RenderTexture 时, alpha的处理出现问题

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17399]
### Cocos Creator version

3.8.3

### System information

android

### Issue description

现象: 
同一个游戏 同一个版本: 
不开启动态图集时, 一切正常.

开启动态图集后, 
微信iOS  , 微信 Android ,  抖音 iOS , PC浏览器 都正常.
但是 抖音 Android 版本 出现 半透明区域变黑变暗 的现象. (类似预乘错误) 

使用的都是系统自带的 2D sprite相关配置, 没有自定义材质 没有修改shader 没有修改blend等参数, 没有使用任何高级技巧.
就是 普通的 2d sprite + 半透明图片 + 动态图集.

抖音app已经升级到最新版. 多台安卓手机均有此现象.
不知道是抖音的bug 还是cocos的.

### Steps to reproduce

如上

**Comment by minggo** [comment]
这个看上去是一个抖音已知的问题，抖音那边反馈查到问题了。具体修复还得等对方。
@GengineJS 请确认下是否是同一个问题。

**Comment by GengineJS** [comment]
@finscn 是同一个问题， 已经跟你反馈解决方法了吧？https://github.com/cocos/cocos-engine/issues/17266
