### ISSUE TITLE
spine动画组件缺少 remove attachment 相关的api

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17409]
### Use Case

spine动画组件缺少 remove attachment 相关的api.
游戏中需要这个特性有用来移除一个插槽上的附件.

关于这个功能 这里有两篇讨论
https://zh.esotericsoftware.com/forum/d/11278-how-to-change-slot-or-hide-attachment/2
https://zh.esotericsoftware.com/forum/d/10023-removing-attachment/3
但是文章中提到的 

slot.attachment = null
或者
slot.setAttachment(null)

在cocos里测试 都无效, 并没有隐藏 slot或者attachment .

使用 
spineComp.setAttachment(slotName, null)  这个api也不行.

------

我看了下 cpp部分的代码, 可能是因为 cocos使用的spine cpp 不允许设置 空的 attachment.

代码如下
```
void Skeleton::setAttachment(const String &slotName, const String &attachmentName) {
    assert(slotName.length() > 0);

    for (size_t i = 0, n = _slots.size(); i < n; ++i) {
        Slot *slot = _slots[i];
        if (slot->_data.getName() == slotName) {
            Attachment *attachment = NULL;
            if (attachmentName.length() > 0) {
                attachment = getAttachment(i, attachmentName);

               // 这里如果 attachment 为空, 好像就直接中断了.
                assert(attachment != NULL);
            }

            slot->setAttachment(attachment);

            return;
        }
    }

    printf("Slot not found: %s", slotName.buffer());

    assert(false);
}
```

但是 spine本身是允许的.

所以在spine里 如果要暂时关闭某个 slot 可以通过
```slot.setAttachment(slotName, '一个不存在的附件名') ```
来间接实现.
而且这个似乎并不是什么奇技淫巧, spine官方给出的方案也是如此. (上面帖子里给出这个方案的人`Nate` 好像就是spine的员工) 

### Problem Description

如上所述

### Alternatives Considered

.

**Comment by bofeng-song** [comment]
@finscn 
slot.attachment = null
或者
slot.setAttachment(null)

cocos可以通过获取slot对象，再通过slot对象调用setAttachment
![企业微信截图_17228207946217](https://github.com/user-attachments/assets/710cb228-3ec3-4873-ab0f-dd81f21ad57a)
