### ISSUE TITLE
CustomPipeLine effect shows Error

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17400]
### Cocos Creator version

3.x

### System information

All

### Issue description

Use customPipeline , when I copy the effect, pass, and pipeline files and relative meta files to another project. then run the project in website, it shows errors, like the pictures below：
![企业微信截图_1721639071899](https://github.com/user-attachments/assets/b8ceaf7d-4741-4efe-8088-2ecfabde26c2)
![企业微信截图_17216390507969](https://github.com/user-attachments/assets/d6e6ddf2-0fe6-454c-bc18-3372513173b1)

### Steps to reproduce

1.copy effect, pass, and pipeline files and relative meta files to anther project asset folder,2 open the project with dashboard 3 then adjust customPipeline setting, 4run the project in website, 

### Minimal reproduction project

[CustomPipeLineErrorTest.zip](https://github.com/user-attachments/files/16331144/CustomPipeLineErrorTest.zip)

**Comment by star-e** [comment]
Please re-import all effects (Menu->Developer->Refresh All Effect) and restart Creator.
If the problem still exists, please reopen this issue.
