### ISSUE TITLE
来回点击切换不同的prefab，prefab界面会无规律的设置初始化位置

### ISSUE THREAD

**Issue by Modo-Global** [cocos/cocos-engine#17424]
### Cocos Creator version

3.8.2

### System information

all

### Issue description

creator编辑器中来回点击切换不同的prefab，prefab界面会无规律的设置初始化位置

### Steps to reproduce

creator编辑器中来回点击切换不同的prefab，prefab界面会无规律的设置初始化位置

https://github.com/user-attachments/assets/46c7c680-18b9-4bbb-b11f-fe6a2445f165

**Comment by wuzhiming** [comment]
可以试试3.8.5，看看是否正常了，还不正常可以再来打开
