### ISSUE TITLE
[bug] Sprite created as a child of a  Camera node could not be shown

### ISSUE THREAD

**Issue by dumganhar** [cocos/cocos-engine#17437]
https://forum.cocos.org/t/topic/159373/15

**Comment by qiuguohua** [comment]
![image](https://github.com/user-attachments/assets/c1c2096c-4e55-45a8-8302-d91c21d6b689)
这是创建的测试d的demo。调试发现顶点数据已经提交到渲染里了，不知道为啥显示不出来，应该是跟z轴有关系？
![image](https://github.com/user-attachments/assets/995baac9-f036-48a0-b9b5-53e20579501a)

**Comment by GengineJS** [comment]
这个问题我看了下，首先sprite的layer是default。这个需要改为UI_2D || UI_3D。
![image](https://github.com/user-attachments/assets/12f83017-7cf1-41db-9b97-ed487b6a4465)
然后由于节点拖到了camera下后，sprite相对于它的父级节点camera的pos为(0, 0, 0)
这样也会导致ui camera看不到sprite，因为camera的near为1，所以需要调整下sprite到截锥体当中。
然后可以正常显示了：
![image](https://github.com/user-attachments/assets/bbc5313c-18d1-428f-9552-2341acad1f4d)
