### ISSUE TITLE
[spine相关] 运行时,  执行 setAttachment() 无效

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17441]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

某 slot下 有两个 附件A 和B, 均为 皮肤占位符.

默认生效的是A,, 运行时切换成B.

执行下面的代码无效
```
skeletonComp.setAttachment(slotName, 'B');
```

这样做也无效:
```
        const skeletonData = skeletonComp.skeletonData.getRuntimeData();
        const skin: sp.spine.Skin = skeletonData.findSkin(skinName);
        const slotIndex = skeletonData.findSlotIndex(slotName);
        const atta = skin.getAttachment(slotIndex, 'B');
        const slot = skeletonComp.findSlot(slotName);
        slot.setAttachment(atta);
```

不报错, 只是无效,

### Steps to reproduce

.

**Comment by finscn** [comment]
简单跟踪了下, 怀疑 slot 的 getAttachment和 setAttachment  绑定的 wasm内的方法不对

<img width="475" alt="image" src="https://github.com/user-attachments/assets/121a3c67-72f0-46c0-847b-9d3467dc716f">

两个操作 返回的都是 spine的 Attachment 类型,   但是数据结构完全不一样. 
.
通过 skin 获得 附件时, 结果 和  window.anim.getAttachment 一致 (图中的第一个结果) 
```
         runtimeData = window.anim.skeletonData.getRuntimeData();
         skin= runtimeData.findSkin('LVL0');
         slotIndex = runtimeData.findSlotIndex('Blackberries');
        skin.getAttachment(slotIndex, '_empty');
```

**Comment by finscn** [comment]
这片文章中, 官方给的方法 也无效: 

https://zh.esotericsoftware.com/forum/d/15062-changing-attachment-in-slot-when-skin-doesnt-have-it/2

感觉根本原因可能就是 slot.getAttachment() , slot.setAttachment() , slot.attachment 有bug.

**Comment by bofeng-song** [comment]
![image](https://github.com/user-attachments/assets/dc787cdb-94f6-49a1-8317-6dd30a56aa0c)
我这边调用skeleton.ts的 getAttachment接口，返回的对象和findSkin是一样的。是否可以把你的demo上传上来看下？

我的测试例是 官方test-case里的 SpineAttach测试例

**Comment by bofeng-song** [comment]
使用组件的findSlot().setAttachment，再通过findSlot().getAttachment或者通过this._skeleton.getSlots().get(1)查看是修改过的
@finscn

**Comment by finscn** [comment]
已经找到原因

**Comment by ch274137014** [comment]
我也碰到这个问题了，请问是怎么解决的，感谢 @finscn

**Comment by finscn** [comment]
> 我也碰到这个问题了，请问是怎么解决的，感谢 @finscn

没解决... 但是感觉在这个问题上 很难和官方沟通清楚

**Comment by bofeng-song** [comment]
@ch274137014 @finscn 可以把你们能复现的demo 上传上来，我用的cocos test-case官方测试例验证是没问题，不确定哪块设置不一样
