### ISSUE TITLE
Camera会导致IOS项目崩溃

### ISSUE THREAD

**Issue by a1076559139** [cocos/cocos-engine#17451]
### Cocos Creator version

3.8.3

### System information

IOS

### Issue description

场景中存在这样一个Camera
![image](https://github.com/user-attachments/assets/ae927545-d577-4fe3-b945-a2b9617f951c)
会在这里崩溃
![WechatIMG1](https://github.com/user-attachments/assets/15599f93-5d8a-4433-af48-6a75b1bd97ce)

### Steps to reproduce

none

**Comment by a1076559139** [comment]
@minggo Web、小游戏和Cocos模拟器(Mac)不会报错

**Comment by a1076559139** [comment]
@GengineJS 请问有结论吗，可以用这个项目复现
https://gitee.com/cocos2d-zp/cococs-creator-frame-3d

**Comment by a1076559139** [comment]
![QQ20240806-222954](https://github.com/user-attachments/assets/40c86353-af5b-4034-8316-114aa216b2f3)

**Comment by a1076559139** [comment]
@GengineJS @minggo 经过测试发现是因为Camera的near和far都为0导致的，把far改为>0的整数就不会崩溃了

**Comment by minggo** [comment]
> Camera的near和far都为0导致的

是你自己设置的还是别的什么操作引起的？

**Comment by a1076559139** [comment]
> > Camera的near和far都为0导致的
> 
> 是你自己设置的还是别的什么操作引起的？

是我自己设置的，这个相机只有一个作用就是最开始进行一次SOLID_COLOR，所以我索性就把它near和far都改为0了

**Comment by GengineJS** [comment]
你这样会除0操作了，你都把visibility设置为nothing了，设置near跟far都为0没啥必要的，我让编辑器组协助修改下far的最小值
![image](https://github.com/user-attachments/assets/3db7ea67-b507-4691-b72d-6aa0498f8ec9)
![image](https://github.com/user-attachments/assets/c3594e27-7de8-4c90-a394-0f348023b0cd)

**Comment by GengineJS** [comment]
透视投影也是一样的：
![image](https://github.com/user-attachments/assets/f492799e-7f29-48b7-9426-88f21b484680)
![image](https://github.com/user-attachments/assets/55dac681-45b4-4e41-8100-8bbef7725afd)

**Comment by a1076559139** [comment]
> 你这样会除0操作了，你都把visibility设置为nothing了，设置near跟far都为0没啥必要的，我让编辑器组协助修改下far的最小值

👌是没啥必要，我原本以为你们会有一些优化处理，比如两个相等(差值为0)就可以避免掉一些运算。
