### ISSUE TITLE
jsb adapter syntaxError

### ISSUE THREAD

**Issue by yanjifa** [cocos/cocos-engine#17468]
### Cocos Creator version

3.8.4

### System information

ALL

### Issue description

https://github.com/cocos/cocos-engine/blob/f2f024bcc94f14f53efe940188b8e763bac2c776/platforms/native/builtin/jsb-adapter/HTMLImageElement.js#L5

### Steps to reproduce

![image](https://github.com/user-attachments/assets/d2e2338a-810d-4efa-8615-084118d0b0a8)

**Comment by dumganhar** [comment]
Go to the root directory and execute `node ./scripts/build-adapter.js` or `npm run build:adapter`.

**Comment by dumganhar** [comment]
Close this issue.
If you still get the error, feel free to re-open it.
