### ISSUE TITLE
typescript non-empty assertion operator is invalid

### ISSUE THREAD

**Issue by 1226085293** [cocos/cocos-engine#17510]
### Cocos Creator version

\>= 3.7

### System information

Windows 10 专业版

### Issue description

Using the ! non-null assertion operator in class to declare an attribute will still be assigned undefined at the end of construction, such as the _aaa attribute in the example

## Demo Code

```ts
import { _decorator } from "cc";

const { ccclass } = _decorator;

@ccclass('absTest')

export abstract class absTest<T> {

    constructor(value: T) {

        this.Update(value);

    }

    private _bbb: T;

    public get bbb(): T {

        return this._bbb;

    }

    public Update(val: T) {

        this._bbb = val;

        this.OnUpdate();

    }

    protected abstract OnUpdate(): void;

}

@ccclass('test1')

export class test1 extends absTest<string>{

    protected OnUpdate(): void {

        this._aaa = "aaaaa";

    }

   

    private _aaa!: string;

    public log(){

        //这里，应该输出 aaaaa,哈哈

        console.log(this._aaa,this.bbb);

    }

}

new test1("哈哈").log();
```

参考这个帖子

https://forum.cocos.org/t/topic/160220/11?u=1226085293

**Comment by smallmain** [comment]
As expected, '! 'is TypeScript syntax, and the idea has always been that all features don't affect the output file. If this doesn't make sense to you, you may need to file an issue with TypeScript first: 

https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99&noLib=true&experimentalDecorators=true#code/ MYGwhgzhAECC0G8CwAoa7oDcBc0B2ArgLYBGApgE4DcqqG0wA9nhAC4UHCuMUAUAlMhR0MAX1TjhKUJBgAhRCPSYAhLkKlKNKfSYt2nbn0G00YiaZlRoAYUV n0AEzIyKZLOuLlqp3czYcXDwCQkrQkqJAA

Only 'declare' is the solution, behavior prior to 3.6 should be a BUG.

**Comment by 1226085293** [comment]
> As expected, '! 'is TypeScript syntax, and the idea has always been that all features don't affect the output file. If this doesn't make sense to you, you may need to file an issue with TypeScript first:
> 
> https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99&noLib=true&experimentalDecorators=true#code/ MYGwhgzhAECC0G8CwAoa7oDcBc0B2ArgLYBGApgE4DcqqG0wA9nhAC4UHCuMUAUAlMhR0MAX1TjhKUJBgAhRCPSYAhLkKlKNKfSYt2nbn0G00YiaZlRoAYUV n0AEzIyKZLOuLlqp3czYcXDwCQkrQkqJAA
> 
> Only 'declare' is the solution, behavior prior to 3.6 should be a BUG.

![image](https://github.com/user-attachments/assets/cfeca211-a333-45b1-9db7-073a4ea62582)

Why the same code, not the same result? Using the same tsconfig configuration as cocos

**Comment by smallmain** [comment]
> > As expected, '! 'is TypeScript syntax, and the idea has always been that all features don't affect the output file. If this doesn't make sense to you, you may need to file an issue with TypeScript first:
> > https://www.typescriptlang.org/play/?useDefineForClassFields=true&target=99&noLib=true&experimentalDecorators=true#code/ MYGwhgzhAECC0G8CwAoa7oDcBc0B2ArgLYBGApgE4DcqqG0wA9nhAC4UHCuMUAUAlMhR0MAX1TjhKUJBgAhRCPSYAhLkKlKNKfSYt2nbn0G00YiaZlRoAYUV n0AEzIyKZLOuLlqp3czYcXDwCQkrQkqJAA
> > Only 'declare' is the solution, behavior prior to 3.6 should be a BUG.
> 
> ![image](https://private-user-images.githubusercontent.com/45589707/356073034-cfeca211-a333-45b1-9db7-073a4ea62582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODkxMTksIm5iZiI6MTcyMzA4ODgxOSwicGF0aCI6Ii80NTU4OTcwNy8zNTYwNzMwMzQtY2ZlY2EyMTEtYTMzMy00NWIxLTlkYjctMDczYTRlYTYyNTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzNDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YzM5NTY5YjgwYWUzZjRjN2RjZWE2ZGViNmZmMTgzNzhlNjMyYWI5YjIyYWIyOGM1YTMxNDY2MzE0ZTBlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j1_sPR6pLSa84eSKXVU02i2zCU5iSri-UXWNVYRWU70)
> 
> Why the same code, not the same result? Using the same tsconfig configuration as cocos

This is caused by `useDefineForClassFields` and can be turned off in the Cocos project Settings. In my experience, Cocos v3.x seems to ignore this switch when using decorators.

https://www.typescriptlang.org/play/?useDefineForClassFields=true#code/IYIwzgLgTsDGEAJYBthjAgggg3gWACgFikB7AO0igFd5SoAKASnyJPYgAsBLMAOggBTSMwDchdgF8JJUFTiIhIpgC4AbqW4ATcQWkFCKNBgBCCQQA8h5LRmyt2wJwEIVCctQC2IQVF0ziJQhmB3YSLl4+J2AEAF4EAEYAJgBmXSlCfUNUdAQAYXMrQRs7XACEaLcPb19-NkDhYJZyjh5+aLjE1PSSfSyCWAowUmRBPmRSAHMGckEAdwQTZiinABp3efzl6KZRIA

Look at playground, try from TS Config -> Language and Environment ->
useDefineForClassFields toggles, which results in either '123' or 'undefined'.

By the way, useDefineForClassFields is an ECMA standard, provided only for compatibility, and we need to keep it enabled for the future.

**Comment by 1226085293** [comment]
https://github.com/cocos/cocos-engine/issues/17514
