### ISSUE TITLE
Splash Setting occur 403 forbidden, while update it from others

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17531]
### Cocos Creator version

3.x

### System information

All

### Issue description

someone make the Splash Setting, when I update the project. Open the project, is shows "403 forbidden" 
![17235139147572](https://github.com/user-attachments/assets/a509cc0a-3f5c-4d83-a905-a777a8147083)

### Steps to reproduce

1. someone made Splash Setting
2. After three days, I updated the project from git.
3. open the project, enable the custom Splash, then pop the 403 forbidden "Directory access is forbidden"

### Minimal reproduction project

[shaderdiffentResult.zip](https://github.com/user-attachments/files/16580026/shaderdiffentResult.zip)

**Comment by Bbaotran0509** [comment]
> ### Cocos Creator version
> 
> 3.x
> 
> ### System information
> 
> All
> 
> ### Issue description
> 
> someone make the Splash Setting, when I update it. Open the project, is shows "自定义插屏启动失败，将使用默认插屏进行构建 ..." 
> 
> ### Relevant error log output
> 
> _No response_
> 
> ### Steps to reproduce
> 
> 1. someone made Splash Setting
> 
> 2. After three days, I updated the project from git.
> 
> 3. open the project, it showed the error "自定义插屏启动失败，将使用默认插屏进行构建 ..." 
> 
> ### Minimal reproduction project
> 
> [shaderdiffentResult.zip](https://github.com/user-attachments/files/16580026/shaderdiffentResult.zip)
> 
>
