### ISSUE TITLE
Setting import-map.json to Import Map，after clear the path of it, it still occur error in the packing

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17532]
### Cocos Creator version

3.x

### System information

All

### Issue description

Setting import-map.json to Import Map，after clear the path of it, during the packing it still occur error "Failed to load import map at project://: Error: EISDIR: illegal operation on a directory, read"

### Relevant error log output

"Failed to load import map at project://: Error: EISDIR: illegal operation on a directory, read"

### Steps to reproduce

1.set a path of Import Map in the project setting -> Scripting 
2.cleat the path of Import Map
3.make the web-destop packing

### Minimal reproduction project

[prefabPackDifferent.zip](https://github.com/user-attachments/files/16580224/prefabPackDifferent.zip)

**Comment by sampadaKelkar** [comment]
1. Check the Import Map Path
2. Review the Directory Structure
3.correct the Configuration
4. Permissions and File Access
5 Clear Caches or Rebuild 
6. Log or Debug the Path

**Comment by sampadaKelkar** [comment]
1. Check the Import Map Path
2. Review the Directory Structure
3.correct the Configuration
4. Permissions and File Access
5 Clear Caches or Rebuild 
6. Log or Debug the Path
