### ISSUE TITLE
AssetsManagerEx.cpp AssetsManagerEx::prepareUpdate, cost a lot of times

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17544]
### Cocos Creator version

3.x 2.x

### System information

Android & IOS

### Issue description

when compare the manifest file of 8 M in function of AssetsManagerEx::prepareUpdate, it costs 37586ms, 
。 Is there any way to optimize this problem.
![image](https://github.com/user-attachments/assets/e0b63fe6-a812-450c-89b2-8d42aa220439)

The cost time comes from mumu模拟器V4.0.3。

The phones to be low speed:
Oppo find x
vivo iqoo u3
![image](https://github.com/user-attachments/assets/c41324ff-803f-4ff2-af24-3e1955549dbd)

### Relevant error log output

none

### Steps to reproduce

none

### Minimal reproduction project
here is the manifests.
[Downloads.zip](https://github.com/user-attachments/files/16632041/Downloads.zip)
_No response_

**Comment by zhefengzhang** [comment]
[hot-update-test.zip](https://github.com/user-attachments/files/16654756/hot-update-test.zip)

在构建原生平台游戏，并运行在设备上，点击游戏画面右上角的版本更新按钮，会自动下载远程资源服务器上的版本信息文件，然后自动进入热更检查阶段。

**Comment by qiuguohua** [comment]
是因为数据太多，而且每个数据操作了json，导致很慢。 现在把函数改成异步的了。不回卡住ui
