### ISSUE TITLE
Feature request: Scene transitions support

### ISSUE THREAD

**Issue by Brujo2020** [cocos/cocos-engine#1756]
Hi guys,

How are you, I hope you are fine, congrats for this engine. I missing transitions support between scenes like cocos2dx, will be great and always needed. 
Thanks in advance.

Cheers,
Mario Alejandro

**Comment by jareguo** [comment]
which transition effect do you need?

**Comment by Brujo2020** [comment]
Like cocos 2d: Push and pop scene, and flip or swipe horizontal

**Comment by nantas** [comment]
We add your request to roadmap's 'Suggestion' and see if there's many people support it.

You can vote here:

https://trello.com/c/APfRZ7FO/110-push-pop-scene-like-old-school-cocos2d-xer
https://trello.com/c/o9PMFEc5/111-builtin-scene-transitions-swipe-flip-etc

**Comment by zhefengzhang** [comment]
You can refer to this: https://github.com/2youyou2/transitions.
