### ISSUE TITLE
Unable to attach file image in android webview

### ISSUE THREAD

**Issue by NikitaOgg** [cocos/cocos-engine#17569]
### Cocos Creator version

3.8.0

### System information

OnePlus 9 - Android 13

### Issue description

If you open a website in webview that has feature to upload image from phone media, it doesn't work on android. Tested with ios and web-mobile (android) is working. Only android app is not working. Expect to able prompt media selection when clicked on attach media button on the website. 

### Steps to reproduce

1. Input website that has upload media function to cocos webview 
2. Build cocos app into android mobile 
3. Open webview in cocos-built android app and test in webview

**Comment by minggo** [comment]
As discussed, the webview in cocos just supports showing a web page. If need more features, developers should do it by themselves.
