### ISSUE TITLE
在安卓设备上反复进出导致崩溃

### ISSUE THREAD

**Issue by swlkkk** [cocos/cocos-engine#17589]
### Cocos Creator version

3.8.2

### System information

安卓设备 渲染后端为Vulkan sdk版本为33 ndk版本21.4.7

### Issue description

采用so库的方式安卓代码集成cocos 在安卓设备上多次反复进入cocos场景引起概率性崩溃 .
目前来看有两种崩溃比较常见第一种情况如下
1.根据反复测试在场景资源少的情况下崩溃概率较低、场景资源较多的情况下崩溃概率会提升(具体错误信息请查看如下截图)
2.在安卓和cocos场景在频繁切换过快导致的崩溃

### Relevant error log output

第一种崩溃错误如下：
 #00 pc 0000000002c20b44  /data/app/~~65Zgs_ONPFWV7awRP_m-gQ==/com.lotogram.cocostest-I0WwF8AVJBdNWFj_wDmHKQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::physics::PhysXSharedBody::addShape(cc::physics::PhysXShape const&)+236) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
  #01 pc 0000000002d2cd50  /data/app/~~65Zgs_ONPFWV7awRP_m-gQ==/com.lotogram.cocostest-I0WwF8AVJBdNWFj_wDmHKQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::physics::PhysXShape::onEnable()+64) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
  #02 pc 0000000002bf0dc0  /data/app/~~65Zgs_ONPFWV7awRP_m-gQ==/com.lotogram.cocostest-I0WwF8AVJBdNWFj_wDmHKQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::physics::BoxShape::onEnable()+56) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
  #03 pc 00000000020b757c  /data/app/~~65Zgs_ONPFWV7awRP_m-gQ==/com.lotogram.cocostest-I0WwF8AVJBdNWFj_wDmHKQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
  #04 pc 0000000001d3693c  /data/app/~~65Zgs_ONPFWV7awRP_m-gQ==/com.lotogram.cocostest-I0WwF8AVJBdNWFj_wDmHKQ==/base.apk!libcocos.so (offset 0x3f55000) (jsbFunctionWrapper(v8::FunctionCallbackInfo<v8::Value> const&, bool (*)(se::State&), char const*)+464) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
  #05 pc 00000000020b74a8  /data/app/~~65Zgs_ONPFWV7awRP_m-gQ==/com.lotogram.cocostest-I0WwF8AVJBdNWFj_wDmHKQ==/base.apk!libcocos.so (offset 0x3f55000) (js_cc_physics_BoxShape_onEnableRegistry(v8::FunctionCallbackInfo<v8::Value> const&)+36) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
  #06 pc 000000000000f528  /data/app/~~65Zgs_ONPFWV7awRP_m-gQ==/com.lotogram.cocostest-I0WwF8AVJBdNWFj_wDmHKQ==/base.apk (offset 0x78d3000)
  第二种崩溃错误如下：
  #00 pc 00000000034bdd3c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #01 pc 0000000001d45c58  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (se::AutoHandleScope::AutoHandleScope()+44) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #02 pc 0000000001cd5e00  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::EventDispatcher::doDispatchJsEvent(char const*, std::__ndk1::vector<se::Value, std::__ndk1::allocator<se::Value> > const&)+56) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #03 pc 0000000001cd549c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::EventDispatcher::dispatchEnterForegroundEvent()+24) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #04 pc 0000000001cea1c0  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #05 pc 0000000001cea170  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (void std::__ndk1::__invoke_void_return_wrapper<void>::__call<void (*&)()>(void (*&)())+24) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #06 pc 0000000001cea148  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #07 pc 0000000001ce8e8c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (std::__ndk1::__function::__func<void (*)(), std::__ndk1::allocator<void (*)()>, void ()>::operator()()+28) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #08 pc 000000000171a240  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #09 pc 000000000171940c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (std::__ndk1::function<void ()>::operator()() const+20) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #10 pc 00000000017401dc  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (void cc::event::Listener<cc::events::EnterForeground>::invoke<>()+72) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #11 pc 0000000001740154  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::event::BusEventBroadcaster<cc::events::EnterForeground>::doBroadcast()+100) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #12 pc 0000000001740090  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (bool cc::event::BusEventListenerContainer::broadcast<cc::events::EnterForeground>()+56) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #13 pc 000000000173ffd8  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (void cc::event::broadcast<cc::events::EnterForeground>()+28) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #14 pc 000000000173bcf0  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::events::EnterForeground::broadcast()+8) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #15 pc 000000000173ba80  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::Engine::redirectWindowEvent(cc::WindowEvent const&)+108) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #16 pc 0000000001742378  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #17 pc 0000000001742334  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #18 pc 00000000017422c4  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #19 pc 0000000001742278  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #20 pc 0000000001740f7c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #21 pc 0000000001718888  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #22 pc 00000000017187e8  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (std::__ndk1::function<void (cc::WindowEvent const&)>::operator()(cc::WindowEvent const&) const+56) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #23 pc 000000000171873c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (void cc::event::Listener<cc::events::WindowEvent>::invoke<cc::WindowEvent const&>(cc::WindowEvent const&)+108) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #24 pc 0000000001718690  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::event::BusEventBroadcaster<cc::events::WindowEvent, cc::WindowEvent const&>::doBroadcast(cc::WindowEvent const&)+136) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #25 pc 00000000017185a8  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (bool cc::event::BusEventListenerContainer::broadcast<cc::events::WindowEvent, cc::WindowEvent const&>(cc::WindowEvent const&)+80) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #26 pc 00000000017184ac  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (void cc::event::broadcast<cc::events::WindowEvent, cc::WindowEvent const&>(cc::WindowEvent const&)+72) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #27 pc 0000000001718010  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::events::WindowEvent::broadcast(cc::WindowEvent const&)+20) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #28 pc 0000000001748eb0  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::GameInputProxy::handleAppCommand(int)+1476) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #29 pc 0000000001747214  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #30 pc 0000000001cf6db0  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #31 pc 0000000001747bdc  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::AndroidPlatform::loop()+120) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #32 pc 0000000001747b2c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (cc::AndroidPlatform::run(int, char const**)+48) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #33 pc 0000000001717dac  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (android_main+104) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #34 pc 0000000001cf6d1c  /data/app/~~157UgMCY6WiF88V5YXrPHw==/com.lotogram.cocostest-FfnaFdWpIh2LWa3q2amzfQ==/base.apk!libcocos.so (offset 0x3f55000) (BuildId: 1eff3287c2ea7ef39f8d27120675005fce16f866)
      #35 pc 00000000000fd134  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)
      #36 pc 0000000000096ae4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 1e3ca19bcae05c01b019c85f3f422e56)

### Steps to reproduce

第一种崩溃复现方式为反复进出cocos场景在代码执行到addComponent(BoxCollider)的时候在c层的addShape函数中就会出现概率崩溃
<img width="698" alt="error" src="https://github.com/user-attachments/assets/8f0e24ec-64c3-44f6-8ee8-c11f50b49b1c">
第二种崩溃目前根据测试来看是因为在频繁切换的时候在上一个activity还没完全销毁的时候再次进入就会导致第二种崩溃

**Comment by minggo** [comment]
和 https://github.com/cocos/cocos-engine/issues/17594 同一个问题。
