### ISSUE TITLE
小米快应用打包失败

### ISSUE THREAD

**Issue by Jonas1024** [cocos/cocos-engine#17623]
### Cocos Creator version

3.8.2

### System information

MacOS 

### Issue description

空工程打包小米快游戏报错，应该是怎样的一个打包流程呢？
我按照官方的文档：https://docs.cocos.com/creator/3.8/manual/zh/editor/publish/publish-xiaomi-quick-game.html 打包一直失败，尝试用空工程也是。
![image](https://github.com/user-attachments/assets/06b702cd-d745-40f7-b585-956a28c1b286)
![image](https://github.com/user-attachments/assets/37e700c9-db4d-4ebd-a060-de06e6efed03)

默认构建设置，
点击"构建->生成"报错了
9-8-2024 21:42:22 build -> make task failed! Child process exit width code 1:npm run,build,–cocos-wx-game

如果是先点击构建，再点击生成
9-8-2024 21:44:59 make package /Users/fanjianrong/Practise/Cocos/Test2/build/xiaomi-quick-game failed!

[Test2.zip](https://forum.cocos.org/uploads/short-url/1wL09uw4k7ZLUx5oNDQbTdQ3OV6.zip)

### Steps to reproduce

-

**Comment by knoxHuang** [comment]
It's a Node version issue, just switch to 18.17.0
