### ISSUE TITLE
saferi audio can not resume.

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17637]
### Cocos Creator version

3.x

### System information

saferi

### Issue description

1.browser the website with saferi
2.tap the screen and play the audio
3.tap the home button
4.after 10 secends back to game. then the error shows

### Relevant error log output

![image](https://github.com/user-attachments/assets/f6b56995-5208-49fa-bd9e-49cd4373c3e6)
![image](https://github.com/user-attachments/assets/cf767c11-684c-4fef-8eb1-8eed743fadd2)

follow the code, I found that when run runContext function of player-web, it can not resume audio correctly function

### Steps to reproduce

1.browser the website with saferi
2.tap the screen and play the audio
3.tap the home button
4.after 10 secends back to game. then the error shows

### Minimal reproduction project

[383demo_music.zip](https://github.com/user-attachments/files/16992428/383demo_music.zip)

**Comment by pong-raman** [comment]
I am using the latest v3.8.6 version. I am still facing the issue.
When returning to the application tab on the IOS Safari browser, the sound doesn't resume, even after touching.

I even tried to play and stop forcefully.
It's a blank scene with "AudioSource" attached to the canvas. Clip is attached, while "Loop" and "PlayOnAwake" are set to true.
Am I missing something?

Note:- in new tab i open a random page on google.

```
       document.addEventListener('visibilitychange', () => {
            if (document.hidden) {
                console.log("stop sound")
                this.getComponent(AudioSource).stop();
            } else {
                console.log("play sound")
                this.getComponent(AudioSource).play();
            }
        });
```


Please help. @tangkaikk

**Comment by Binz-IT** [comment]
@tangkaikk 
我也有这个问题，ios自带浏览器，播放音乐，然后切换到其他页签，玩一会大概1min左右，回来，音乐没有了。

查了下，onstatechange回调函数里面，state还是running，所以不会在执行resume了。

这好像是浏览器假死问题

AudioContextAgent最好开放出来，我们自己就可以调用audiocontext实例来规避了，或者你们把它改好。

谢谢大大

**Comment by pong-raman** [comment]
For the switching tab issue.
I fixed it by intercepting the audio context in HTML.  Along with adding "visibilitychange" event listener, so that I can manually resume/suspend the audio context.

**Comment by tangkaikk** [comment]
> I am using the latest v3.8.6 version. I am still facing the issue. When returning to the application tab on the IOS Safari browser, the sound doesn't resume, even after touching.
> 
> I even tried to play and stop forcefully. It's a blank scene with "AudioSource" attached to the canvas. Clip is attached, while "Loop" and "PlayOnAwake" are set to true. Am I missing something?
> 
> Note:- in new tab i open a random page on google.
> 
> ```
>        document.addEventListener('visibilitychange', () => {
>             if (document.hidden) {
>                 console.log("stop sound")
>                 this.getComponent(AudioSource).stop();
>             } else {
>                 console.log("play sound")
>                 this.getComponent(AudioSource).play();
>             }
>         });
> ```
> 
> Please help. [@tangkaikk](https://github.com/tangkaikk)

1.How to reproduce the error you have encountered? 2.What is the Version of IOS?

**Comment by tangkaikk** [comment]
> [@tangkaikk](https://github.com/tangkaikk) 我也有这个问题，ios自带浏览器，播放音乐，然后切换到其他页签，玩一会大概1min左右，回来，音乐没有了。
> 
> 查了下，onstatechange回调函数里面，state还是running，所以不会在执行resume了。
> 
> 这好像是浏览器假死问题
> 
> AudioContextAgent最好开放出来，我们自己就可以调用audiocontext实例来规避了，或者你们把它改好。
> 
> 谢谢大大

1.ios 版本是多少？2.其他页签也有播放音乐吗？

**Comment by pong-raman** [comment]
@tangkaikk 
I am on IOS version 18.5 and using Cocos Creator 3.8.6. Opening other applications and returning to the browser is fixed with this pull request.
Issue exists: Open the application in the browser, switch to a new tab in the browser, and conduct some Google research. Return to the application after, say, 1 minute. Open the application in the browser, switch to a new tab in the browser, and conduct some Google research. Return to the application after, say, 1 minute. The round doesn't resume.
