### ISSUE TITLE
Node 的 onSetParent 方法 在 ts 和 cpp 中名称不一致

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17639]
### Cocos Creator version

3.8.3

### System information

all

### Issue description

在 ts 里 叫  _onSetParent ,  在 cpp 里 叫 onSetParent (没有下划线) .
希望能统一下. 
另外希望 cpp 能暴露 onSetParent 到 jsb , 因为某些情况下 需要自己调用这个方法.

### Steps to reproduce

如上所述

**Comment by minggo** [comment]
私有方法，没计划暴露。
