### ISSUE TITLE
相机渲染到RenderTexutre后，设置为SpriteFrame的texture，在web和native上方向相反

### ISSUE THREAD

**Issue by dum3ng** [cocos/cocos-engine#17647]
### Cocos Creator version

3.8.2

### System information

mac sonoma, chrome, ios 12

### Issue description

将一个相机的targetTexture设置为RenderTexture，然后再设置为SpriteFrame的texutre，结果在web和ios上方向是相反的。
```
        const rt = new RenderTexture()
        rt.initialize({ width: 300, height: 200 })
        this.offlineCamera.targetTexture = rt

        const sp = this.getComponent(Sprite)
        const frame = new SpriteFrame()
        frame.texture = this.offlineCamera.targetTexture
        frame.flipUVY = true  // 为了让在浏览器上是正向的
        sp.spriteFrame = frame
```

<table>
<tr>
 <td>
cocoscreator编辑中：

 <td>
浏览器上：
 <td>
ios simulator中：
<tr>
 <td><img src="https://github.com/user-attachments/assets/f7d52caa-e361-410e-9649-1d8c05476dc5" >
 <td><img src="https://github.com/user-attachments/assets/1ac866a9-0d38-41d7-a834-66c0bcb3ff1e">
 <td><img width="403" alt="image" src="https://github.com/user-attachments/assets/7cefe7ce-17a3-4361-9485-82711acb1f06">
</table>

### Steps to reproduce

如问题描述。

**Comment by GengineJS** [comment]
为什么要设置flipUVY

**Comment by GengineJS** [comment]
看一下这个仓库的rendertexture部分怎么做的吧，https://github.com/cocos/cocos-test-projects
