### ISSUE TITLE
Feature request: Customizable baseURL for web resource loading

### ISSUE THREAD

**Issue by bnega** [cocos/cocos-engine#1767]
## Problem
With a web build, all resources and assets are loaded from a directory relative to the current page's url. I would like to be able to specify a base URL for files, rather than the engine assume they are relative to the current page. 

## CURRENTLY
Users playing my game land on a page at `http://myDomain.com/games/myGameName`, which downloads `main.js` from `http://myAssetServer.myDomain.com/myGame/v1/`

When the engine is loaded and ready to load my game code, it will try to load  `http://myDomain.com/games/myGame/src/project.js`. Similarly, resources will attempt to load from a url like `http://myDomain.com/games/myGame/res/import/08/0884a0c4a.json`

Because all of my game files are hosted on a different cdn server, this fails. 

## DESIRED
Ideally, I would be able to load the  `main.js` from another URL, and then have `main.js` set the url for the engine to use to find all of the other files in the `option` object that is passed to `cc.game.run()`. I tried adding `engineDir: "http://myAssetServer.myDomain.com/myGame/v1/"` to `option` but it did not do anything. 

## REFERENCES
Phaser is one example of another engine that provides this functionality: http://phaser.io/docs/2.4.4/Phaser.Loader.html#baseURL

**Comment by pandamicro** [comment]
Take a look at your main.js, you should be able to find the assets init code as shown below.

```
cc.AssetLibrary.init({
    libraryPath: 'res/import',
    rawAssetsBase: 'res/raw-',
    rawAssets: settings.rawAssets,
    packedAssets: settings.packedAssets
});
```

What you need to do is to modify the libraryPath, rawAssetsBase to your desired relative path, hope this can resolve your problem

**Comment by bnega** [comment]
Yes, this worked perfectly for the assets. I had to make some further customizations to properly load the scripts, but it wasn't too difficult.

For others who are going down this road, I had to also take the following steps to load everything from main.js (without anything being preloaded from the web page itself):
1) Manually load settings
```
var settingsScript = document.createElement('script');
        settingsScript.async = true;
        settingsScript.src = myCustomUrl + 'src/settings.js';

        var settingsLoaded = function()
        {
            document.body.removeChild(settingsScript);
            settingsScript.removeEventListener('load', settingsLoaded, false);

            loadEngine();
        }

        settingsScript.addEventListener('load', settingsLoaded, false);
        document.body.appendChild(settingsScript);
```
2) Load engine. This is in main.js by default. Very similar code to above, with the only difference is setting the src to debug or minified based on settings like so:
```
cocos2d.src = myCustomUrl + (window._CCSettings.debug ? 'cocos2d-js.js' : 'cocos2d-js-min.js');
```
3) Load game manually after the engine is loaded. By default, it is passed in to the engine via jsList and the engine loads it, but I couldn't get it to respect the custom base url that way. So removed the code that adds it to jsList and load it manually like the other two steps.
```
var gameScriptName = 'src/' + (window._CCSettings.debug ? 'project.dev.js' : 'project.js');
var gameCode = document.createElement('script');
gameCode.async = true;
gameCode.src = myCustomUrl + gameScriptName;
```

4) After game code is loaded, then call the existing boot() function which is mostly unchanged. Only noteworthy differences are that jsList no longer has any elements added to it, and libraryPath/rawAssetsBase are customized as @pandamicro suggested


Thanks!

**Comment by dragonWin147** [comment]
Hi guy, can you please send me an example ? Thank you very much @bnega ?
