### ISSUE TITLE
cocos creator 3.8 左下角的调试信息怎么手动控制打开和关闭

### ISSUE THREAD

**Issue by laolang2016** [cocos/cocos-engine#17679]

**Comment by GengineJS** [comment]
旧管线的话，pipeline下有个profiler属性，enable设置为true应该就好了
![image](https://github.com/user-attachments/assets/a3031f34-e9f3-4dde-b984-8f75169c19ff)
cc.director.root.pipeline.profiler.enabled = true/false

**Comment by minggo** [comment]
@laolang2016 以后这种使用问题请到论坛里问，谢谢。
