### ISSUE TITLE
在"浏览器预览"时，会收到 Chrome 的 apple-mobile-web-app-capable 弃用警告

### ISSUE THREAD

**Issue by puxiao** [cocos/cocos-engine#17751]
### Cocos Creator version

3.8.4

### System information

Window11

### Issue description

预览栏 > 浏览器预览 > Chrome 控制台查看该警告：
```
<meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
```

<br>

我查询了一下资料：

- Safari 支持 `apple-mobile-web-app-capable` 但  Chrome 不支持

- Chrome 建议使用 `mobile-web-app-capable`

  > 也有一些非官方网页讲 Safari 也支持 `mobile-web-app-capable`

<br>

该标签涉及到的文件有：

* templates/fb-instant-games/index.ejs
* templates/web-desktop/index.ejs
* templates/web-mobile/index.ejs

<br>

解决方案1：直接使用 `mobile-web-app-capable` 替换 `apple-mobile-web-app-capable`

```diff
- <meta name="apple-mobile-web-app-capable" content="yes">
+ <meta name="mobile-web-app-capable" content="yes">
```

<br>

2 个知名框架就是这样做的：

* Flutter：https://github.com/flutter/flutter/pull/154964
* Next.js：https://github.com/vercel/next.js/pull/70363

<br>

**解决方案2：2个标签共存**

简单来说就是把 2 个标签都定义一次：

```diff
+ <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
```

<br>

具体该怎么做，要不要直接采用 替换方式，需要衡量一下。

**Comment by wuzhiming** [comment]
Thinks we will add the other meta tag at v3.8.5
```html
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
```
