### ISSUE TITLE
如何编译出DEVECO 5的工程

### ISSUE THREAD

**Issue by jackie-weiwei** [cocos/cocos-engine#17765]
### Use Case

我发现目前的 3.8.4编译鸿蒙出来的工程为3.1.1的，而现在最新的DEVECO是5.0的，请问如何编译出5.0的工程？

### Problem Description

我发现目前的 3.8.4编译鸿蒙出来的工程为3.1.1的，而现在最新的DEVECO是5.0的，请问如何编译出5.0的工程？

### Alternatives Considered

我发现目前的 3.8.4编译鸿蒙出来的工程为3.1.1的，而现在最新的DEVECO是5.0的，请问如何编译出5.0的工程？

**Comment by wangyatong** [comment]
3.8.5他们说支持api12, 但是3.8.5还没又发布

**Comment by minggo** [comment]
是的，得等 3.8.5

**Comment by wangyatong** [comment]
> 是的，得等 3.8.5

3.8.5有预计发布时间嘛？

**Comment by minggo** [comment]
12.27
