### ISSUE TITLE
[Spine]  没法调用EventTimeline.getEvents 接口 Cannot call EventTimeline.getEvents due to unbound types

### ISSUE THREAD

**Issue by AILHC** [cocos/cocos-engine#17768]
### Cocos Creator version

3.8.4

### System information

Windows 10

### Issue description

```ts
private _collect_one_anim_info(ani: sp.spine.Animation, info: ISpineCollectInfo) {
        console.info('process anim : ', ani.name);
        let ani_info: ISpineAniInfo = {};
        info[ani.name] = ani_info;
        ani_info.duration = ani.duration;

        const timelines = ani.timelines;
        for (const one of timelines) {
            if (one instanceof sp.spine.EventTimeline) {
                for (const one_evt of one.events) {
                    if (one_evt.intValue < 0) {
                        ani_info.evts = ani_info.evts || {};
                        ani_info.evts[one_evt.intValue] = one_evt.time;
                    }
                }

            }
        }
    }
```

### Relevant error log output

message
: 
"Cannot call EventTimeline.getEvents due to unbound types: PN5spine6VectorIPNS_5EventEEE"
name
: 
"UnboundTypeError"
stack
: 
"UnboundTypeError: Cannot call EventTimeline.getEvents due to unbound types: PN5spine6VectorIPNS_5EventEEE\n  

### Steps to reproduce

message
: 
"Cannot call EventTimeline.getEvents due to unbound types: PN5spine6VectorIPNS_5EventEEE"
name
: 
"UnboundTypeError"
stack
: 
"UnboundTypeError: Cannot call EventTimeline.getEvents due to unbound types: PN5spine6VectorIPNS_5EventEEE\n

**Comment by bofeng-song** [comment]
https://github.com/cocos/cocos-engine/pull/17783/files#diff-e0b614a6cf0422fb256ae3cfc45540eabab150a4c237b98853d5a1aff35758bf
The changes in this PR can be merged, or you can make the modifications to spine-type-export.cpp yourself. Refer to the modifications made to SPVectorEventPtr for reference.
