### ISSUE TITLE
ParticleSystem系统坐标系问题 Simulation Space 无论设置为什么状态粒子都无法跟随父节点旋转

### ISSUE THREAD

**Issue by chelios001** [cocos/cocos-engine#17773]
### Cocos Creator version

3.8.4

### System information

windows 10 Editor android 各种小程序

### Issue description

![image](https://github.com/user-attachments/assets/8b8a5c0a-5925-48e9-abce-7b85bdde2921)
![image](https://github.com/user-attachments/assets/79bbfc4b-300d-4941-94a5-ad356b26299d)
父节点0的时候，特效正常
父节点设置为-180 刀光特效没有跟随父节点旋转
![image](https://github.com/user-attachments/assets/fc9cab65-93ed-420d-9d9a-46f2e6e39b5b)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/779628b5-b8f4-4139-b16e-beebfb153030)
这样修改后可以解决这个问题。

**Comment by longchuan** [comment]
getWorldRotation不是local的解决方案，下面有相同代码，这个不算解决，也许是你使用有问题。
