### ISSUE TITLE
抖音小程序VideoPlayer错误

### ISSUE THREAD

**Issue by chelios001** [cocos/cocos-engine#17771]
### Cocos Creator version

3.8.4

### System information

android

### Issue description

![image](https://github.com/user-attachments/assets/a9d00a9f-a2df-485d-b19d-20304c5b7ed2)

### Steps to reproduce

随便创建一个视频组件，打包到抖音小程序就报错

**Comment by liuhy-liu** [comment]
[3.8.5-1204]抖音小游戏：oneplus8t，使用抖音扫码，运行无该报错

**Comment by qiuguohua** [comment]
未复现

**Comment by chelios001** [comment]
[douyinTest.zip](https://github.com/user-attachments/files/18226976/douyinTest.zip)
我在3.8.4上就拖了一个视频上去，打包到抖音小程序，视频就播放不出来啊。
抖音开发者工具上提示
![image](https://github.com/user-attachments/assets/dcf12eea-aa23-4e7d-9e1d-153880b702ad)

**Comment by qiuguohua** [comment]
不好意思，复现了。这个有两个问题，一个问题是 模拟器的问题，另一个是真机上渲染不出来的问题。 模拟器的问题，已经反馈给抖音了。我这边会修复真机渲染不出来的问题
