### ISSUE TITLE
ParticleSystem勾选UseGPU直接报错

### ISSUE THREAD

**Issue by chelios001** [cocos/cocos-engine#17772]
### Cocos Creator version

3.8.4

### System information

windows 10 Editor

### Issue description

![image](https://github.com/user-attachments/assets/05c1847b-2dfc-40b6-a09f-6f9a908f45d4)

### Steps to reproduce

随便新建一个场景，创建一个 ParticleSystem 勾选UseGPU就开始疯狂报错

**Comment by minggo** [comment]
@knoxHuang 在勾选 GPU 时，编辑器需要动态给它设置一个对应的 particle 的 gpu shader。设置完 shader 后不会报错，不过效果不太对。这属于另外一个问题。
