### ISSUE TITLE
网格压缩在微信小游戏非分离引擎选项上有问题

### ISSUE THREAD

**Issue by JoneLau** [cocos/cocos-engine#17776]
### Cocos Creator version

3.8.4

### System information

微信开发者工具

### Issue description

模型资源勾选上网格压缩上的编码选项，构建微信小游戏，不勾选分离引擎（勾选没问题）会无法导出网格压缩所使用的第三方库导致报错

### Steps to reproduce

操作步骤如下：
1. 任意项目场景显示一个3D模型，模型勾选网格压缩，并且勾选上编码
2. 构建微信小游戏并运行
![image](https://github.com/user-attachments/assets/ee598a1f-28c9-4f4d-a7e7-c5cb261b117c)
![image](https://github.com/user-attachments/assets/8469261b-bfd8-4c6b-acac-196ea4542b4a)
![image](https://github.com/user-attachments/assets/bf3d8787-790e-4734-b06e-4d5a6af830ab)

**Comment by longchuan** [comment]
#16352

**Comment by knoxHuang** [comment]
这个 bug 是没有勾选 3D 模块导致的，勾选已经就能正常，不过这里的模块剔除会出现没有体验出来有误导用户，后续会进行完善
