### ISSUE TITLE
事件委托

### ISSUE THREAD

**Issue by jackie-97** [cocos/cocos-engine#17775]
### Cocos Creator version

3.8.0

### System information

win10

### Issue description

事件委托写法，在回调函数中拿到的target依旧是父节点，而非点击的子节点，子节点未注册任何事件监听
```js

@ccclass("Levels")
export class Levels extends Component {
  @property(Prefab)
  levelItemPrefab: Prefab = null;

  start() {
    // 生成关卡列表，要求能够滚动
    console.warn("Levels");
    for (let i = 0; i < 10; i++) {
      const levelNode = instantiate(this.levelItemPrefab);
      levelNode.name = "level" + i;
      levelNode.getChildByName("Label").getComponent(Label).string =
        "level " + (i + 1);
      this.node.addChild(levelNode);
    }

    this.node.on(Node.EventType.TOUCH_END, this.goGame, this);
  }

  update(deltaTime: number) {}

  goGame(event: EventTouch) {
    console.warn("event ", event.target.name);
  }
```

### Steps to reproduce

...

**Comment by longchuan** [comment]
this.node指代Levels所在的节点，而不是你添加的子节点。（解决了之后记得关闭）

**Comment by jackie-97** [comment]
> this.node指代Levels所在的节点，而不是你添加的子节点。（解决了之后记得关闭）

我想表达的意思是点击其中一个子节点level，event.target应该是子节点，event.currentTarget则应该是父节点，事件委托的目的就是不要让每个子节点都绑定一个事件监听，直接监听父节点即可！

**Comment by minggo** [comment]
子节点没有监听，那么事件就会抛给父节点。

**Comment by longchuan** [comment]
> ```js
> this.node.on(Node.EventType.TOUCH_END, this.goGame, this);
> ```



> > this.node指代Levels所在的节点，而不是你添加的子节点。（解决了之后记得关闭）
> 
> 我想表达的意思是点击其中一个子节点level，event.target应该是子节点，event.currentTarget则应该是父节点，事件委托的目的就是不要让每个子节点都绑定一个事件监听，直接监听父节点即可！

你这个设定不符合多个子节点的设计方案，如果你想获取父节点，可以直接使用node.parent，而不是通过event获取。或者使用target.parent也可以。target的含义，就是当前事件绑定的节点，这个含义与currentTarget重复了。
