### ISSUE TITLE
384 web-mobile, when into fullscreen mode, rotation adaption gets problem.

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17774]
### Cocos Creator version

3.8.4

### System information

web

### Issue description

[video]https://github.com/user-attachments/assets/ffe1057d-342f-41a5-a9d8-f80e46d2aef7
Adaption issue, please check the video。

### Steps to reproduce

1.Use phone to open the website 2.click website when into the full screen, rotate the cellphone.

### Minimal reproduction project

[384rotateBug.zip](https://github.com/user-attachments/files/17487342/384rotateBug.zip)

**Comment by tangkaikk** [comment]
refer to https://github.com/cocos/3d-tasks/issues/18555

**Comment by minggo** [comment]
fixed in https://github.com/cocos/cocos-engine/pull/17780
