### ISSUE TITLE
the Light Probe Group‘s edit mode could not be maintained when you rotate the editor scene

### ISSUE THREAD

**Issue by longchuan** [cocos/cocos-engine#17797]
### Cocos Creator version

3.8.4

### System information

windows 11

### Issue description

the Light Probe Group‘s edit mode could not be maintained when you rotate the editor scene

### Steps to reproduce

1、add a Light Probe Group to scene
2、edit area box
3、press the key alt,and rotate the editor scene
4、release the key,and the edit mode will be canceled

**Comment by longchuan** [comment]
搞笑，如果你快速松开键盘和鼠标，那么就不会触发编辑模式的退出。可能是鼠标触发了场景点击。

**Comment by knoxHuang** [comment]
Thank you for your feedback; this issue will be fixed in version 3.8.5.
