### ISSUE TITLE
Error processing XMLHttpRequest response: InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest'

### ISSUE THREAD

**Issue by longchuan** [cocos/cocos-engine#17808]
### Cocos Creator version

3.8.4

### System information

windows 11,edge

### Issue description

![image](https://github.com/user-attachments/assets/709e251e-841d-43d1-af0f-166b8e10a8d7)
Error processing XMLHttpRequest response: InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
But there had no errors from firefox or chrome.

### Steps to reproduce

on browser of edge, launch a scene or relaunch a scene.But there had no errors from firefox or chrome.There had no errors before last month. Perhaps,you should install all of them to test the errors.

**Comment by minggo** [comment]
Did the error happen in preview mode?

**Comment by longchuan** [comment]
> Did the error happen in preview mode?

yes,the web preview

**Comment by knoxHuang** [comment]
Can you give me a reproducible demo? It is normal for us to use the Hello world scene here.

**Comment by longchuan** [comment]
> Can you give me a reproducible demo? It is normal for us to use the Hello world scene here.

perhaps , because the method of loadOneAssetPipeline.async(subTask); was async.
```
private _flow (index: number, task: Task): void {
        const pipe = this.pipes[index];
        pipe(task, (result) => {
            if (result) {
                task.isFinished = true;
                task.dispatch('complete', result);
            } else {
                index++;
                if (index < this.pipes.length) {
                    // move output to input
                    task.input = task.output;
                    task.output = null;
                    this._flow(index, task);
                } else {
                    task.isFinished = true;
                    task.dispatch('complete', result, task.output);
                }
            }
        });
    }
```
and the flow did not catch the error

**Comment by longchuan** [comment]
how the piplines handle the async?
@knoxHuang

**Comment by longchuan** [comment]
```
export default function downloadFile (
    url: string,
    options: Record<string, any>,
    onProgress: FileProgressCallback | null | undefined,
    onComplete: ((err: Error | null, data?: any) => void),
): XMLHttpRequest {
    const xhr = new XMLHttpRequest();
    const errInfo = `download failed: ${url}, status: `;

    xhr.open('GET', url, true);

    if (options.xhrResponseType !== undefined) { xhr.responseType = options.xhrResponseType as XMLHttpRequestResponseType; }
    if (options.xhrWithCredentials !== undefined) { xhr.withCredentials = options.xhrWithCredentials as boolean; }
    if (options.xhrMimeType !== undefined && xhr.overrideMimeType) { xhr.overrideMimeType(options.xhrMimeType as string); }
    if (options.xhrTimeout !== undefined) { xhr.timeout = options.xhrTimeout as number; }

    if (options.xhrHeader) {
        for (const header in options.xhrHeader) {
            xhr.setRequestHeader(header, options.xhrHeader[header] as string);
        }
    }

    xhr.onload = (): void => {
        if (xhr.status === 200 || xhr.status === 0) {
            if (onComplete) { onComplete(null, xhr.response); }
        } else if (onComplete) { onComplete(new Error(`${errInfo}${xhr.status}(no response)`)); }
    };

    if (onProgress) {
        xhr.onprogress = (e): void => {
            if (e.lengthComputable) {
                onProgress(e.loaded, e.total);
            }
        };
    }

    xhr.onerror = (): void => {
        if (onComplete) { onComplete(new Error(`${errInfo}${xhr.status}(error)`)); }
    };

    xhr.ontimeout = (): void => {
        if (onComplete) { onComplete(new Error(`${errInfo}${xhr.status}(time out)`)); }
    };

    xhr.onabort = (): void => {
        if (onComplete) { onComplete(new Error(`${errInfo}${xhr.status}(abort)`)); }
    };

    xhr.send(null);

    return xhr;
}
```
the end error is  xhr.send(null);

**Comment by longchuan** [comment]
where is the onreadystatechange?

**Comment by longchuan** [comment]
provide an onreadystatechange method
```
        var flag = false;
        var xhr = new XMLHttpRequest();

        xhr.open("GET", url);
        if (sys.isNative) {
            // xhr.setRequestHeader("Accept", "*/*");
            xhr.setRequestHeader("Accept-Encoding", "gzip,deflate");
        }
        xhr.timeout = 2000;
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4) {
                if (xhr.status == 200) {
                    // cc.log(xhr.responseText);
                    cbSucc(xhr.responseText);
                } else {
                    if (!flag) {
                        flag = true;
                        if (cbFail) {
                            cbFail(xhr.statusText, xhr.responseText);
                        }
                    }
                }
            }
        };
        xhr.onerror = function () {
            if (!flag) {
                flag = true;
                cbFail(xhr.statusText, null);
            }
        };
```

**Comment by longchuan** [comment]
there is a solution
https://blog.csdn.net/amiao_2018/article/details/130427300

**Comment by longchuan** [comment]
![image](https://github.com/user-attachments/assets/64f30d0e-9931-42a4-aad0-a907d691dbd0)
the gles' version is old

**Comment by longchuan** [comment]
```
var responseData = !responseType || responseType === 'text' ||  responseType === 'json' ?
        request.responseText : request.response;
```
this,if a scene was not loaded,maybe the responseType would not be "json"

**Comment by longchuan** [comment]
![image](https://github.com/user-attachments/assets/7db29129-74c9-451d-96a7-134f476563b4)
In the end error,the inspector.js'` handleResponse(contentType, Promise.resolve(this.responseText), this.responseURL)` did not handle the responseText and response

**Comment by longchuan** [comment]
shutdown the plugin to solve the problem...

**Comment by foreversos** [comment]
> shutdown the plugin to solve the problem... @knoxHuang

您好,我也有这个问题,关闭插件要怎么操作?是否是屏蔽引擎的那个axios.谢谢

**Comment by longchuan** [comment]
> > shutdown the plugin to solve the problem... @knoxHuang
> 
> 您好,我也有这个问题,关闭插件要怎么操作?是否是屏蔽引擎的那个axios.谢谢

浏览器，管理扩展，关闭或者删除

**Comment by Fun005** [comment]
> > shutdown the plugin to solve the problem... @knoxHuang
> 
> 您好,我也有这个问题,关闭插件要怎么操作?是否是屏蔽引擎的那个axios.谢谢

请问解决了么，我这边也有同样的问题

**Comment by foreversos** [comment]
> > > shutdown the plugin to solve the problem... @knoxHuang
> > 
> > 
> > 您好,我也有这个问题,关闭插件要怎么操作?是否是屏蔽引擎的那个axios.谢谢
> 
> 请问解决了么，我这边也有同样的问题

你按照[longchuan](https://github.com/longchuan)说的,CHROME系的新建一个隐私窗口(基本上就没插件了),再测试,如果不报错就说明是插件问题
如果还报错,可以搞一个纯净的FIREFOX,也不报错

**Comment by Fun005** [comment]
> > > > shutdown the plugin to solve the problem... @knoxHuang
> > > 
> > > 
> > > 您好,我也有这个问题,关闭插件要怎么操作?是否是屏蔽引擎的那个axios.谢谢
> > 
> > 
> > 请问解决了么，我这边也有同样的问题
> 
> 你按照[longchuan](https://github.com/longchuan)说的,CHROME系的新建一个隐私窗口(基本上就没插件了),再测试,如果不报错就说明是插件问题 如果还报错,可以搞一个纯净的FIREFOX,也不报错

意思就是被其他的chrome插件影响导致这个情况么？

**Comment by foreversos** [comment]
> > > > > shutdown the plugin to solve the problem... @knoxHuang
> > > > 
> > > > 
> > > > 您好,我也有这个问题,关闭插件要怎么操作?是否是屏蔽引擎的那个axios.谢谢
> > > 
> > > 
> > > 请问解决了么，我这边也有同样的问题
> > 
> > 
> > 你按照[longchuan](https://github.com/longchuan)说的,CHROME系的新建一个隐私窗口(基本上就没插件了),再测试,如果不报错就说明是插件问题 如果还报错,可以搞一个纯净的FIREFOX,也不报错
> 
> 意思就是被其他的chrome插件影响导致这个情况么？

是的.

**Comment by Fun005** [comment]
> > > > > > shutdown the plugin to solve the problem... @knoxHuang
> > > > > 
> > > > > 
> > > > > 您好,我也有这个问题,关闭插件要怎么操作?是否是屏蔽引擎的那个axios.谢谢
> > > > 
> > > > 
> > > > 请问解决了么，我这边也有同样的问题
> > > 
> > > 
> > > 你按照[longchuan](https://github.com/longchuan)说的,CHROME系的新建一个隐私窗口(基本上就没插件了),再测试,如果不报错就说明是插件问题 如果还报错,可以搞一个纯净的FIREFOX,也不报错
> > 
> > 
> > 意思就是被其他的chrome插件影响导致这个情况么？
> 
> 是的.

好的，感谢
