### ISSUE TITLE
The engine clipping could cut the locked model

### ISSUE THREAD

**Issue by longchuan** [cocos/cocos-engine#17806]
### Cocos Creator version

3.8.4

### System information

windows 11

### Issue description

![image](https://github.com/user-attachments/assets/7e1e90ee-6e87-4ae0-b2de-b38c5965fef6)
The engine clipping could cut the locked model

### Steps to reproduce

engine clipping,select to cut all model. select the unlocked model

**Comment by minggo** [comment]
Could you describe it in more detail?

**Comment by longchuan** [comment]
> Could you describe it in more detail?

![image](https://github.com/user-attachments/assets/38dfb374-3aa5-45f3-a8b4-6dfa96cec743)
this is normal
![image](https://github.com/user-attachments/assets/5fafae26-d58e-4431-8538-4a3e46956850)
this is cutting all
![image](https://github.com/user-attachments/assets/dbcf27fb-78b8-4762-aabd-b231a8b2f6b8)
I could not select the block(gray) model,and I selected the unblock model,the block model could not be selected.If I run the game,the game would not had the base model,and caused many errors

**Comment by minggo** [comment]
It is fixed in https://github.com/cocos/cocos-engine/pull/17803. You can have try in v3.8.5.
