### ISSUE TITLE
windows file explorer could not be focus

### ISSUE THREAD

**Issue by longchuan** [cocos/cocos-engine#17814]
### Cocos Creator version

3.8.4

### System information

windows 11

### Issue description

When you open the dir of resource in editor,the opened file explore could not be focus
![image](https://github.com/user-attachments/assets/d6cd59ee-df3f-4163-9813-d0005607c2f3)
There was a flicker of  the explorer and did not open the window.

### Steps to reproduce

press the right key of mouse on resource in editor.Click to open the file explorer.

**Comment by wuzhiming** [comment]
fixed at 3.8.5
