### ISSUE TITLE
minigame/screen-adapter 的实现需要兼容不支持安全区域的机型

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#17816]
### Cocos Creator version

3.8.2

### System information

Android

### Issue description

微信接口 wx.getSystemInfoSync().safeArea 可能返回 undefined，引擎侧需要做判空处理

https://github.com/cocos/cocos-engine/blob/102d05e7e0db90cb4cddfd9eef35e594f1f6b962/pal/minigame/wechat.ts#L155-L158

此处返回类型需要修正，可以确认下其他小游戏平台是否也有类似的问题
```diff
- minigame.getSafeArea = function (): SafeArea
+ minigame.getSafeArea = function (): SafeArea | undefined
```

https://github.com/cocos/cocos-engine/blob/102d05e7e0db90cb4cddfd9eef35e594f1f6b962/pal/screen-adapter/minigame/screen-adapter.ts#L124-L126

此处需要做判空处理

### 参考微信 API 文档 safeArea 字段的说明:
> 部分机型没有安全区域概念，也不会返回 safeArea 字段，开发者需自行兼容。

https://developers.weixin.qq.com/minigame/dev/api/base/system/wx.getSystemInfoSync.html

### Steps to reproduce

属于机型兼容性问题，没有复现步骤

**Comment by bofeng-song** [comment]
@PPpro 请参考此 [PR](https://github.com/cocos/cocos-engine/pull/17831)
