### ISSUE TITLE
[iOS原生] build出来的ios项目提供的虚拟机app的cpu架构不对

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17821]
### Cocos Creator version

3.8.4

### System information

iOS

### Issue description

在 M1芯片的mac上 build后, 在xcode里通过模拟器运行 和 调试项目时, 有如下错误信息:

```
Error creating LLDB target at path '/项目目录/build/ios/proj/Debug-iphonesimulator/项目名称-mobile.app', target architecture: arm64 : the specified architecture 'arm64-*-*' is not compatible with 'x86_64-apple-ios12.0.0-simulator' in '/项目目录/build/ios/proj/Debug-iphonesimulator/项目名称-mobile.app/项目名称-mobile'.
Using an empty LLDB target instead but this can cause slow memory reads.
```

虽然能勉强运行 但是开发调试时性能堪忧.

### Steps to reproduce

.

**Comment by longchuan** [comment]
这个是自己设置的

**Comment by finscn** [comment]
> x86_64-apple-ios12.0.0-simulator

在哪里设置?

**Comment by longchuan** [comment]
随便找找，build相关设置

**Comment by longchuan** [comment]
看看这个
https://www.jianshu.com/p/f33d407a3eb8

**Comment by finscn** [comment]
> 看看这个 https://www.jianshu.com/p/f33d407a3eb8

这个问题和 xcode无关.  `proj/Debug-iphonesimulator/项目名称-mobile.app` 这个 app是 cocos编译过程产生的. 这个时候并不涉及 xcode.

**Comment by minggo** [comment]
修改 Xcode 构建设置
打开项目的 Xcode 工程文件（.xcworkspace 或 .xcodeproj），并按以下步骤检查并调整设置：

在 Build Settings 中搜索 Architectures。
将 Architectures 设置为 $(ARCHS_STANDARD)，这样 Xcode 会自动根据运行环境选择合适的架构。
在 Build Active Architecture Only 设置中，为 Debug 配置为 Yes（即仅构建当前设备架构）。

**Comment by minggo** [comment]
像这样的问题，自己搜索一下或者问下 chatgpt

**Comment by finscn** [comment]
> 修改 Xcode 构建设置 打开项目的 Xcode 工程文件（.xcworkspace 或 .xcodeproj），并按以下步骤检查并调整设置：
> 
> 在 Build Settings 中搜索 Architectures。 将 Architectures 设置为 $(ARCHS_STANDARD)，这样 Xcode 会自动根据运行环境选择合适的架构。 在 Build Active Architecture Only 设置中，为 Debug 配置为 Yes（即仅构建当前设备架构）。

你这个就是  chatgpt 给你的 或者你搜的吧? 
不对的.

**Comment by finscn** [comment]
> 修改 Xcode 构建设置 打开项目的 Xcode 工程文件（.xcworkspace 或 .xcodeproj），并按以下步骤检查并调整设置：
> 
> 在 Build Settings 中搜索 Architectures。 将 Architectures 设置为 $(ARCHS_STANDARD)，这样 Xcode 会自动根据运行环境选择合适的架构。 在 Build Active Architecture Only 设置中，为 Debug 配置为 Yes（即仅构建当前设备架构）。

我设置了 也没用

<img width="558" alt="image" src="https://github.com/user-attachments/assets/4441e4c1-4344-414a-96a2-766c5b2b4996">

我也尝试过 手动把所有都写成 arm64 , 还是没用. 一样的错误提示.


另外,  不管我怎么折腾和设置这几个选项,  在cocos里重新构建后 都会变成默认值.

**Comment by longchuan** [comment]
都说是x86了，你还要改为arm

**Comment by finscn** [comment]
> 都说是x86了，你还要改为arm

你是不是没看懂我说啥? 我机器是 arm的.   ios也是arm的 我就是想全用arm架构运行啊

**Comment by longchuan** [comment]
> > 都说是x86了，你还要改为arm
> 
> 你是不是没看懂我说啥? 我机器是 arm的.   ios也是arm的 我就是想全用arm架构运行啊

target architecture: arm64 : the specified architecture 'arm64-*-*' is not compatible with 'x86_64-apple-ios12.0.0-simulator'

**Comment by finscn** [comment]
> > > 都说是x86了，你还要改为arm
> > 
> > 
> > 你是不是没看懂我说啥? 我机器是 arm的.   ios也是arm的 我就是想全用arm架构运行啊
> 
> target architecture: arm64 : the specified architecture 'arm64-_-_' is not compatible with 'x86_64-apple-ios12.0.0-simulator'

你在说什么啊? .   我问题的核心不就是  如果 **_不要_**构建出 x86_64-apple-ios12.0.0-simulator 吗 ?  
我明明是arm的机器, 为什么构建出一个  x86_64 模拟器? 我想要  arm64-apple-ios12.0.0-simulator .
