### ISSUE TITLE
希望在 macOS 上构建 iOS项目时, 可以 忽略 .DS_Store 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17832]
### Cocos Creator version

3.8.4

### System information

iOS

### Issue description

目前在mac下构建项目时, 会把 .DS_Store 文件写入项目中

<img width="379" alt="image" src="https://github.com/user-attachments/assets/8d96ac8d-19df-46d1-88a1-545c89e8129a">

希望能忽略 .DS_Store 已经加入 git 和 vscode项目的忽略列表, 但是在构建 原生时, 还是被加到项目里了.

### Steps to reproduce

.

**Comment by minggo** [comment]
这个是 mac 系统自己的行为，不是引擎写的。
