### ISSUE TITLE
some bullet wasm errors（A bug of how to use the _safe_delete）

### ISSUE THREAD

**Issue by longchuan** [cocos/cocos-engine#17839]
### Cocos Creator version

3.8.4

### System information

web，GLES2, GLES3

### Issue description

RuntimeError: null function or function signature mismatch
![image](https://github.com/user-attachments/assets/8d3a6944-e771-46a0-aa90-5da851cf4a79)

RuntimeError: table index is out of bounds
![image](https://github.com/user-attachments/assets/0ffc778f-13a2-4bb5-a3a9-3fbc94f8cb45)

RuntimeError: memory access out of bounds
![image](https://github.com/user-attachments/assets/e5a1f0cc-c7ce-44fb-b615-0e7e16be9146)

![image](https://github.com/user-attachments/assets/05fe6708-907f-4ccf-afc4-e3e6e7ce2bad)

### Steps to reproduce

1、set a physics world with scene
2、get the scene result and reload the scene
3、reload about 1000 counts,found the errors

**Comment by longchuan** [comment]
at Object.TriangleMesh_addTriangle (
看起来是`cocos2BulletTriMesh`这个方法有内存泄漏

**Comment by longchuan** [comment]
问题代码
```
private static readonly BulletBvhTriangleMeshShapeMap = new Map<number, BulletBvhTriangleMeshShape>();

    public static getBulletBvhTriangleMeshShape (key: number, mesh: Mesh): BulletBvhTriangleMeshShape {
        let newBulletBvhTriangleMeshShape!: BulletBvhTriangleMeshShape;
        if (BulletBvhTriangleMeshShape.BulletBvhTriangleMeshShapeMap.has(key)) { //can be improved
            newBulletBvhTriangleMeshShape = BulletBvhTriangleMeshShape.BulletBvhTriangleMeshShapeMap.get(key)!;
            newBulletBvhTriangleMeshShape.reference = true;
        } else {
            newBulletBvhTriangleMeshShape = new BulletBvhTriangleMeshShape(key, mesh);
            BulletBvhTriangleMeshShape.BulletBvhTriangleMeshShapeMap.set(key, newBulletBvhTriangleMeshShape);
        }
        return newBulletBvhTriangleMeshShape;
    }
```

**Comment by longchuan** [comment]
![image](https://github.com/user-attachments/assets/65028423-83a2-40f9-8c8b-9250fad8784e)
![image](https://github.com/user-attachments/assets/6c29d278-d99a-4f08-bf78-0319fc7160e6)
How the _safe_delete works with bullet?There is an opposite usage.

**Comment by minggo** [comment]
How did you reload the scene? It is better you provide a demo to reproduce it.

**Comment by minggo** [comment]
And you posted many information above, but i can't get what you want to express. It seems it said different things.

**Comment by longchuan** [comment]
> And you posted many information above, but i can't get what you want to express. It seems it said different things.

solved the problem with edit the safedelete

**Comment by minggo** [comment]
Can i know how did you fix it?

**Comment by longchuan** [comment]
> Can i know how did you fix it?

https://github.com/cocos/cocos-engine/pull/17842

**Comment by minggo** [comment]
Thank you, i will take a look.
