### ISSUE TITLE
[iOS原生] 渲染到 rendertexture 上的内容 还是 y轴颠倒的. 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17830]
### Cocos Creator version

3.8.4

### System information

iOS

### Issue description

小游戏平台(无论安卓还是ios) 以及  安卓原生 都是正确的. 但是 ios原生不行.  

### Steps to reproduce

.

**Comment by finscn** [comment]
我说的不太准确  其实是 ios是正的, 其他平台是反的.

我有一行代码 是处理这个问题的
```
spriteFrame.flipUVY = true
```
在其他平台需要执行这个 不执行就是错的. 但是在 ios平台 不需要执行这个

**Comment by GengineJS** [comment]
rt贴图有个sample from rt的选项，勾选了么?https://docs.cocos.com/creator/3.8/manual/zh/asset/render-texture.html#%E8%AE%BE%E7%BD%AE-rendertexture-%E4%B8%BA%E6%9D%90%E8%B4%A8%E8%B4%B4%E5%9B%BE

**Comment by finscn** [comment]
> rt贴图有个sample from rt的选项，勾选了么?https://docs.cocos.com/creator/3.8/manual/zh/asset/render-texture.html#%E8%AE%BE%E7%BD%AE-rendertexture-%E4%B8%BA%E6%9D%90%E8%B4%A8%E8%B4%B4%E5%9B%BE

勾选了. 问题的关键是 不同平台的不一致性. 就算我没勾选 出错了, 那也应该所有平台都有错才对.
现在有的平台是对的 有的是错的, 这个就很奇怪了

**Comment by GengineJS** [comment]
> 勾选了. 问题的关键是 不同平台的不一致性. 就算我没勾选 出错了, 那也应该所有平台都有错才对. 现在有的平台是对的 有的是错的, 这个就很奇怪了

为啥没勾选所有平台就应该出错？这个宏本身就是为了纠正部分平台出错的问题，而不是所有平台都会出错。那勾选了还有没问题？

**Comment by finscn** [comment]
> > 勾选了. 问题的关键是 不同平台的不一致性. 就算我没勾选 出错了, 那也应该所有平台都有错才对. 现在有的平台是对的 有的是错的, 这个就很奇怪了
> 
> 为啥没勾选所有平台就应该出错？这个宏本身就是为了纠正部分平台出错的问题，而不是所有平台都会出错。那勾选了还有没问题？

哦  明白了,  我之前不知道 "这个宏本身就是为了纠正部分平台出错的问题" , 我以为是勾选了 你们就统一反转呢.

然后回答你后面的问题:  勾选了 还是不行.  勾选后错误不一样了. 画面不仅仅是颠倒的问题 可以说是 乱七八糟 没法看 很奇怪.

不过我怀疑是我们项目的问题 否则这么明显的大bug 你们不可能没发现.  我先再研究下.  你可以先无视这个问题 . 
有进展我再和你沟通

**Comment by GengineJS** [comment]
> > > 勾选了. 问题的关键是 不同平台的不一致性. 就算我没勾选 出错了, 那也应该所有平台都有错才对. 现在有的平台是对的 有的是错的, 这个就很奇怪了
> > 
> > 
> > 为啥没勾选所有平台就应该出错？这个宏本身就是为了纠正部分平台出错的问题，而不是所有平台都会出错。那勾选了还有没问题？
> 
> 哦 明白了, 我之前不知道 "这个宏本身就是为了纠正部分平台出错的问题" , 我以为是勾选了 你们就统一反转呢.
> 
> 然后回答你后面的问题: 勾选了 还是不行. 勾选后错误不一样了. 画面不仅仅是颠倒的问题 可以说是 乱七八糟 没法看 很奇怪.
> 
> 不过我怀疑是我们项目的问题 否则这么明显的大bug 你们不可能没发现. 我先再研究下. 你可以先无视这个问题 . 有进展我再和你沟通

嗯嗯，rt的渲染比较特殊，每个后端viewport起始点跟朝向不同，rt的纹理采样有些平台会导致Y轴颠倒问题，
