### ISSUE TITLE
编辑器资源导出时的bug: 无法导出FBX材质上绑定的图片

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17872]
### Cocos Creator version

3.8.4

### System information

all

### Issue description

<img width="314" alt="image" src="https://github.com/user-attachments/assets/3bdded7e-4d0c-46be-936d-54e0ae694bb8">

某fbx 内的材质上绑定了 一张纹理.
该fbx文件 被 scene 引用.
右键选择该 scene 导出资源包,  此时 scene 和 fbx文件都能被导出 但是绑定的图片没有.

### Steps to reproduce

.

**Comment by knoxHuang** [comment]
<img width="360" alt="image" src="https://github.com/user-attachments/assets/6ee4fc62-fe91-4a46-ad94-fbcc256f65af">

<img width="411" alt="image" src="https://github.com/user-attachments/assets/746a8b2c-07c2-46eb-8b28-d310253bab3a">


试了一下是可以的，给一下可复现的 demo 吧

**Comment by finscn** [comment]
@knoxHuang  见下面的附件
[model.zip](https://github.com/user-attachments/files/17856846/model.zip)

我的设置如下图
![image](https://github.com/user-attachments/assets/b8bc19ff-d595-4c0b-abb9-7d456d533f77)
<img width="310" alt="image" src="https://github.com/user-attachments/assets/57e9954d-79c6-419f-9cc9-45d97efc51d6">

我随便找了几个 kenney工作室提供的 免费的fbx格式的素材 , 
我在cocos里绑定图片(fbx和图片都是他们提供的, 图片是独立的, 不是内嵌在fbx中) ,  再导出时, 都不会导出图片.

**Comment by knoxHuang** [comment]
好的，我们这边验证一下，有问题会修复

**Comment by knoxHuang** [comment]
该 bug 会修复到 3.8.5
