### ISSUE TITLE
spine自定义材质开启DepthWrite，渲染错误

### ISSUE THREAD

**Issue by hubluesky** [cocos/cocos-engine#17884]
### Cocos Creator version

3.8.4

### System information

windows

### Issue description

没有开启深度写入之前正常
![image](https://github.com/user-attachments/assets/2b6e6ee6-a561-4976-ad5f-399b6ea26ebd)
开启深度写入之后，显示异常
![image](https://github.com/user-attachments/assets/ed5c444f-650e-42dd-b48b-6d2e754aca9a)

### Steps to reproduce

1、在场景中添加一个spine
2、新建一个材质，shader选择for2d/builtin-spine，并给上面的spine
3、开启材质的的DepthTest、DepthWrite

**Comment by longchuan** [comment]
spine是一个2D对象，默认是在UI_3D层吗

**Comment by hubluesky** [comment]
> spine是一个2D对象，默认是在UI_3D层吗

我是要把spine放到3D场景中当3D对象使用，所以想要开启深度测试和深度写入。
这个层只是我用来表示这是一个2D的东西，但要在3D场景中使用的意思。

**Comment by minggo** [comment]
spine 目前是在 2D 渲染队列渲染的，没法直接用到 3D 里。目前 2D 的模块要在 3D 场景渲染，需要用 render texture。
