### ISSUE TITLE
MTLDevice.mm里CC_PLATFORM宏定义编写错误

### ISSUE THREAD

**Issue by Zhengbledor** [cocos/cocos-engine#17885]
### Cocos Creator version

3.8.4

### System information

iOS

### Issue description

cocos-engine/native/cocos/renderer/gfx-metal/MTLDevice.mm
CC_PLATFOTM❌
CC_PLATFORM✅
![image](https://github.com/user-attachments/assets/21fe1946-4941-4c95-8856-4fa8e3b7e998)

### Steps to reproduce

1

**Comment by longchuan** [comment]
fork一下，提交一个pull request，应该会被合并。
