### ISSUE TITLE
编辑器导出 构建的配置的json 时,   "sourceMaps" 一项出现错误.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17896]
### Cocos Creator version

3.8.4

### System information

all

### Issue description

导出的内容是:
```
  "sourceMaps": "false",
```

此处应该是    ``` "sourceMaps": false,``` 才对吧?  false前后不应该有引号.

### Steps to reproduce

.

**Comment by longchuan** [comment]
别看导出的格式，看能不能导入

**Comment by dogodo-cc** [comment]
可以改成☑️，然后再导出看看，按理说这个不应该有差异。

**Comment by knoxHuang** [comment]
构建是有对 sourcemap 为字符串做兼容处理的，所有只要功能正常就可以无视

**Comment by finscn** [comment]
> 构建是有对 sourcemap 为字符串做兼容处理的，所有只要功能正常就可以无视

@knoxHuang  我知道没问题 因为带着这个"错误" 用了好久了.   不过还是建议修复一下, 强迫症不能忍啊 哈哈哈
