### ISSUE TITLE
[编辑器bug] 编辑器的"项目设置"中的 Bundle设置 里, 修改 各种配置的名称后,  属性检查器的下拉列表里的 内容没有同步.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#17916]
### Cocos Creator version

3.8.4

### System information

macOS

### Issue description

如题.

修改下图中, 配置的名称
<img width="178" alt="image" src="https://github.com/user-attachments/assets/5f18a966-14ce-4304-a01e-2ce20194d0c6">

在下图 属性检查器 的 平台设置 的下拉框里 不会同步. 要 重启编辑器 才行.
<img width="187" alt="image" src="https://github.com/user-attachments/assets/2fc7a9b6-8c44-4b5f-bea2-2660fb434b71">

有些设置的修改 要重启编辑器我能接受, 但是这种小修改也要重启 , 我觉得不太合适.

我是macOS , 不知道其他平台是否有类似问题.

### Steps to reproduce

.

**Comment by knoxHuang** [comment]
录了一个视频，你看看操作是不是跟你一样的，如果一样的，我这边是可以同步的，如果不一样写一下具体的操作步骤我们这边复现看看

https://github.com/user-attachments/assets/46b54e83-0f77-406c-b6ca-5e31b37eb541

**Comment by finscn** [comment]
奇怪了. 操作一模一样, 但我这里就是不同步(macOS 最新版) . 晚些时候我也录一个我的操作给你看下.

**Comment by finscn** [comment]
@knoxHuang  视频来了.  macOS .  复制一个现有的配置. 对赋值出来的配置改名,  属性检查器的下拉列表里仍然是带有 copy 后缀的老名字

https://github.com/user-attachments/assets/4aa14f90-3c8b-4882-9692-123f424ff406

**Comment by knoxHuang** [comment]
好的，那可能跟拷贝导致的，我们排查看看

**Comment by knoxHuang** [comment]
经过验证，该问题在 3.8.5 修复
