### ISSUE TITLE
spine call function queryStoreMemory but dont use freeStoreMemory to free memory.

### ISSUE THREAD

**Issue by tangkaikk** [cocos/cocos-engine#17919]
### Cocos Creator version

3.8.x

### System information

All

### Issue description

refer to : https://github.com/cocos/3d-tasks/issues/18640
![5d358266bb66759db54e70f0a35815a3](https://github.com/user-attachments/assets/74588bc3-4d7a-4ea8-9647-583eb40951be)

### Relevant error log output

none

### Steps to reproduce

none

### Minimal reproduction project

none

**Comment by longchuan** [comment]
How does it free the memory?

**Comment by longchuan** [comment]
> refer to : https://github.com/cocos/3d-tasks/issues/18640

The link is 404

**Comment by bofeng-song** [comment]
Fixed at this [PR](https://github.com/cocos/cocos-engine/pull/18018)
