### ISSUE TITLE
cc.Texture2D missing initWithData, updateWithData JSB

### ISSUE THREAD

**Issue by cphuoc91** [cocos/cocos-engine#1797]
Hi guys,

Hope you are all well !

I have a question about about cocos-creator as I am quite new to your great tool.

Currently I have a small game project written using cocos-creator there have an functional with send a dynamic generated image from a server then send it via WebSocket, parsed it as ArrayBuffer
and it work perfectly on WebGL except on JSB there are no "initWithData" this functionality is not available. So I want to pass data to a Texture2D directly via initWithData. But it turns out that the initWithData method is explicitly skipped from the JSB. I just wanted to check what the reason for this is. If I can’t use initWithData, is there any other way into a texture2D when running on native not in a browser?

**Comment by pandamicro** [comment]
Sorry it's not supported yet, we will try to add it in future version.

**Comment by kanelr** [comment]
I am expecting this feature to create live streaming instead of rtmp protocol, hope soon!

**Comment by pandamicro** [comment]
I created a task in our internal issue tracker

**Comment by cphuoc91** [comment]
Hi @pandamicro,

Btw is there have any alternative methods to do that at this time?

**Comment by xianyinchen** [comment]
This feature is already supported in version 2.4.4 and close now.
