### ISSUE TITLE
读取远程Bundle里的AnimationClip文件报错

### ISSUE THREAD

**Issue by szrpf** [cocos/cocos-engine#17986]
### Cocos Creator version

3.8.2

### System information

Windows10

### Issue description

项目部署在远程，Bundle也部署在远端服务器
浏览器打开部署的H5项目，loadBundle读取远端Bundle
如果Bundle里的预制体绑定了AnimationClip，就会报错
编辑器运行，同样读该远程Bundle则正常
![0](https://github.com/user-attachments/assets/d2f18a47-2b28-4c80-82ab-78be54d88ce8)

### Steps to reproduce

构建项目、构建Bundle
项目、Bundle分别部署到远程
浏览器打开部署的项目，url后面输入?/assetUrl=【Bundle地址】
demo运行会报错。
去掉PageGame预制体根节点下Animation组件绑定的AAA，重复以上步骤则正常

### Minimal reproduction project

[Uploading RemoteDemo.zip…]()

**Comment by wuzhiming** [comment]
[RemoteDemo.zip](https://github.com/user-attachments/files/17945366/RemoteDemo.zip)
add demo

**Comment by szrpf** [comment]
解决了吗？我上传一个最新版的复现demo
[Uploading RemoteDemo.zip…]()

**Comment by szrpf** [comment]
> [RemoteDemo.zip](https://github.com/user-attachments/files/17945366/RemoteDemo.zip) add demo

新demo已上传

**Comment by szrpf** [comment]
> [RemoteDemo.zip](https://github.com/user-attachments/files/17945366/RemoteDemo.zip) add demo

解决了吗？我上传一个最新版的复现demo
[Uploading RemoteDemo.zip…]()

**Comment by yufengctbu** [comment]
经排查在 3.8.4 以前的版本在构建 bundle 的时候没有把 bundle 资源的对应关系保存到 extensionMap 这个字段中导致资源加载问题，建议使用 3.8.4 及以后的版本构建 bundle
