### ISSUE TITLE
Spine属性面板不能切换动画

### ISSUE THREAD

**Issue by szrpf** [cocos/cocos-engine#18013]
### Cocos Creator version

3.8.5社区12月4日公测版

### System information

Windows10

### Issue description

spine属性面板没有切换动画的Animation下拉列表

### Steps to reproduce

拖入一个spine.json到场景里，右边属性面板没有切换动画的Animation下拉列表
同一个动画在3.8.2里是正常的
[SuperSpinLight.zip](https://github.com/user-attachments/files/18058711/SuperSpinLight.zip)

**Comment by wuzhiming** [comment]
@knoxHuang 请检查下，是否是新引入的面板显示问题，如果是的话，请在 3.8.5 修复

**Comment by szrpf** [comment]
![image](https://github.com/user-attachments/assets/89ac9742-c2f1-4b91-b230-f4d3022e3ad5)
这个是属性面板截图，没有Animation下拉列表

**Comment by wsLyr** [comment]
12.04版本bug比上个测试版本多

**Comment by knoxHuang** [comment]
感谢反馈，已修复

**Comment by szrpf** [comment]
好的，辛苦！~~




刘飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cocos/cocos-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月10日(星期二) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cocos/cocos-engine] Spine属性面板不能切换动画 (Issue #18013)





 
感谢反馈，已修复
