### ISSUE TITLE
希望cocos构建小游戏时, 能支持 ETC2 纹理压缩格式.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#18021]
### Use Case

目前小游戏的龙头  微信小游戏 和 抖音小游戏 都支持 ETC2 了.

但是 cc 的 3.8.4 里 还是只有ETC1 . 
<img width="761" alt="image" src="https://github.com/user-attachments/assets/dd21bf2f-daa5-420b-832b-3d6b0ae79cb4">

希望 cocos能跟进.

### Problem Description

.

### Alternatives Considered

.

**Comment by wuzhiming** [comment]
下面的自定义配置可以自己配

**Comment by finscn** [comment]
> 下面的自定义配置可以自己配

具体要怎么填写呢?

**Comment by wuzhiming** [comment]
> > 下面的自定义配置可以自己配
> 
> 具体要怎么填写呢?
自己建一个配置，就可以使用
![image](https://github.com/user-attachments/assets/0433e050-359f-4f48-a160-b1d6c556fcdb)

**Comment by finscn** [comment]
谢谢. 希望未来能直接加到自带配置里

**Comment by wuzhiming** [comment]
> 谢谢. 希望未来能直接加到自带配置里

默认配置会对所有的小游戏平台生效，需要所有小游戏平台都支持，才可以放到默认配置中去。
