### ISSUE TITLE
Spine batch few skeletons in one on web.

### ISSUE THREAD

**Issue by yuriilychak** [cocos/cocos-engine#1804]
Hello again. I have new question about spine on web. In native version of engine few skeletons that use same atlas batch in one draw-call, but in web version every skeleton render in one draw-call. 

The problem is in  SkeletonWebGLRenderCmd. Before adding every new command for render skeleton calling batch rendering, and after adding slots it call's too. I try to reduce them, but vertices of new skeleton is overriding stored vertices, and rendered only last skeleton.

I know that  you don't have the resources to implement this, but if you tell me how to merge few render commands to one, or do something else to fix this I think I can do this.

**Comment by jareguo** [comment]
Is this the same with https://github.com/cocos-creator/engine/issues/1685 ?

**Comment by pandamicro** [comment]
@yuriilychak  With the previous modifications based on your suggestions, I can observe that one skeleton can be drawn in one batch, slots rendering are not divided in between. Do you mean batching different skeletons together ? Is it a usual case that they share the same texture ?

**Comment by yuriilychak** [comment]
@pandamicro I mean when I create 5 spine animations from same atlas via c++ version of engine or jsb I have one draw-call, but on web I have 5 draw-calls. In web every skeleton provide one draw-call.
I have a big game with a lot of animation in one scene between 500. On native version I have 100 draw-calls because some of skeletons use same texture, but on web I have 500. 
When I looked through the code of SkeletonWebGLRenderCmd (function uploadData) I see two batch rendering commands.
First at startup of function:
```
proto.uploadData = function (f32buffer, ui32buffer, vertexDataOffset){
        // rendering the cached data first
        cc.renderer._batchRendering();
```
and second when all slots data added for rendering:
```
// render the left vertices
        if (cachedVertices > 0) {
            cc.renderer._batchRendering();
        }
```
They breaking batch. 

Slots from different skeletons use same atlas, shader and blend mode. In webgl inspector commands are the same. They use only different vertices.
![screenshot from 2017-07-12 21-53-49](https://user-images.githubusercontent.com/8695823/28135171-f3aa98a8-674d-11e7-836b-efe366f6016f.png).
The question is how to merge them to one command to use few skeletons in one batch if they use same atlas. Or you have different solution? On native platform all work fine and I think it can work good on web too.

**Comment by pandamicro** [comment]
I see, so you want to batch skeleton commands together, the problem in the current code is that the Skeleton render command doesn't exactly follow the renderer's batching protocol, it's using a hack way to implement batching inside one skeleton. I will try to make it right

**Comment by pandamicro** [comment]
@yuriilychak  it's fixed in the previous pull request

**Comment by yuriilychak** [comment]
@pandamicro Thanks a lot. I use cocos-html5 and add part of your fix to it, and it's work grate. Can you add it to cocos-html5 repository? Or i need create pull request?

**Comment by pandamicro** [comment]
I'm doing it, don't worry

**Comment by pandamicro** [comment]
Done @yuriilychak

**Comment by yuriilychak** [comment]
Thanks.
