### ISSUE TITLE
Bloom Postprocess all over the pace

### ISSUE THREAD

**Issue by Lykdraft** [cocos/cocos-engine#18050]
### Cocos Creator version

3.8.4, 3.8.5

### System information

Windows 10, OSX 10.15

### Issue description

Bloom Postprocess in Cocos 3.8.4 and 3.8.5 at runtime all over the place.

Node:

![Screenshot 2024-12-17 at 15 05 41](https://github.com/user-attachments/assets/76f520ae-6686-4a9b-83d3-9b3c3eb0a421)

In-Editor Camera Preview (lower right corner):
![inEditor Camera View](https://github.com/user-attachments/assets/7cea95e4-c05d-417c-9c88-da1457b172f8)

Run in-editor:
![bloom2-ezgif com-optimize](https://github.com/user-attachments/assets/d5b78b04-ab79-4a6a-a3a4-24d3a9761a4f)

Run in Webbrowser:
![bloomweb-ezgif com-optimize](https://github.com/user-attachments/assets/24563eb0-2d64-4f47-9cae-e2ce8505a8a9)

Not sure what this is, but it does feel broken.

(Steps: Added a postprocessing c

### Relevant error log output

None.

### Steps to reproduce

Before:
1) Add a node
2) Add MainCamera and Main Light to that node as children.
3) Rotate the node with a script.

Then:
1) Add a 'BuildinPipelineSettings' Component to the main camera,
2) Add a 'buildin-bloom.mtl'
3) enable bloom.
4) run in browser and/or editor.

(Use a 3D scene with some geometry and rotate 

### Minimal reproduction project

Rotate script attached:
[Rotate.ts.zip](https://github.com/user-attachments/files/18166730/Rotate.ts.zip)

**Comment by Lykdraft** [comment]
dropbox link to the demo project:

﻿https://www.dropbox.com/scl/fi/0id28xaiaezgq85k1mjzu/GeometryBloom_Demo.zip?rlkey=0alznd40q2jl7ywcyqbinu38f&dl=0

**Comment by GengineJS** [comment]
Enabling post-processing will affect all areas, including the editor. This is by design, as it adheres to the WYSIWYG (What You See Is What You Get) philosophy.

**Comment by Lykdraft** [comment]
So, in the camera view at the lower right corner, all is good, play-in-editor is wrong, play in htm5 browser is wrong, but you say its by design. ok...
