### ISSUE TITLE
请恢复支持Typescript原生的import模块引用

### ISSUE THREAD

**Issue by a1q123456** [cocos/cocos-engine#1808]
在1.5.0中，可以通过
```shell
nam install --save axios
```
```typescript
import axios from 'axios';
```
但是在1.5.2中似乎不再支持了，会提示找不到Module，感觉是import路径不对，被exclude掉了，没有进一步测试

**Comment by jareguo** [comment]
npm install 本来就是废弃的用法，为什么不用插件脚本？

**Comment by a1q123456** [comment]
因为还需要下载js文件啊，没有npm方便

**Comment by jareguo** [comment]
如果 npm 没有副作用，又那么方便，为什么我们要标记为废弃的用法？

**Comment by a1q123456** [comment]
原来被废弃了，多谢回复

**Comment by jareguo** [comment]
不客气，修是能修，不过正好趁这个机会让大家迁移到插件脚本吧…… 这样问题会少得多
