### ISSUE TITLE
1.5.2 cc.removeSelf is broken

### ISSUE THREAD

**Issue by persypers** [cocos/cocos-engine#1836]
Running this code in 1.5.2 on web causes an exception in main loop:
```
var node = new cc.Node();
node.parent = cc.find('Canvas');
node.runAction(cc.removeSelf());
```
Problem seems to be that ccNode.removeFromParent modifies state of cc.ActionManager

**Comment by pandamicro** [comment]
It's fixed a little later after 1.5.2 release, sorry for that, you can use a standalone engine and do the following modifications

https://github.com/cocos-creator/engine/pull/1812
