### ISSUE TITLE
Cocos Creator on Linux

### ISSUE THREAD

**Issue by KioriSun** [cocos/cocos-engine#1841]
This is a feature request.
Have you guys thought about porting the client to linux? I mean since it's an electron app it should be really straight forward. Also, a lot of the js community loves and uses linux anyways, so I really don't see why not. Also, pretty much everything in cocos is cross-platform, so I really don't understand why there isn't a port.

**Comment by jareguo** [comment]
Hi, just because we have no more human resources to port and test.

**Comment by KioriSun** [comment]
Thanks so much for answering. I wish you guys good fortune!

**Comment by mean-ui-thread** [comment]
@KioriSun @jareguo Can we re-open this feature request? I'd love to see Cocos Creator available for Linux. I'm not sure why it got closed.

**Comment by jareguo** [comment]
Sorry I will not re-open it, Linux support is not necessary for most game developers.

**Comment by ma1onso** [comment]
Cool idea. Using Unity 3D from elementary os.

**Comment by KioriSun** [comment]
@AlonsoEnrique @mchiasson , beyond Unity, on Linux, you can also try Defold(has great html5 export), or Phaser/Contruct 3 if you need a pure js engine.

Yoyo games says they might also release an editor for Linux in the future, they have just released for mac, so stay tuned.

**Comment by ma1onso** [comment]
@KioriSun more options in Linux it's much better, reopen this please maybe some developer can help with this task.

**Comment by osanir** [comment]
A lot of developers using GNU/Linux distros and maybe somewhere there are developers to build and test Cocos Creator for on linux. This request opened on 2017 but now 2018. Maybe it's time to reopen.

**Comment by VictorQueiroz** [comment]
Very disappointing to see such contempt regarding Linux developers.

**Comment by jareguo** [comment]
Human resources are very scarce for us, and opening a new platform will only greatly distract us from our energies. The engine also has a lot of modules that need to be perfected. Linux, by contrast, has a much lower priority. I'm not averse to supporting Linux, it's just not the time.

**Comment by zhefengzhang** [comment]
对 Linux 的支持目前不在我们的短期计划中，但是我们会在以后的某个版本中实现。
Support for Linux is not currently in our short-term plans, but we will implement it in a future release.

**Comment by snoweuph** [comment]
I just switched to Linux because of Windows11, but F for me, thought I could try out this engine :( but if you have no resources, you have no resources

**Comment by darklight9811** [comment]
Really sad to see that there are no linux support yet :c

**Comment by gehaollt** [comment]
测试我们可以帮助你们测试啊，要啥测试，你只要放出来linux版本

**Comment by JorgeMarinoDev** [comment]
What is the status of this? It'd be great to have a Linux version of Cocos Creator.

**Comment by oOwombatOo** [comment]
I would also love to see Cocos Creator on Linux.

And as has been mentioned before, considering it is an Electron App, it should be extremely simple and straightforward ... (?)

**Comment by kt3v** [comment]
Still waiting Cocos on Linux

**Comment by CrescentSine** [comment]
> 测试我们可以帮助你们测试啊，要啥测试，你只要放出来linux版本

Because Cocos Creator Editor is a non-open-source software, to fixing issues is also requires the manpower of the development company, besides adaptation and testing. If anyone hope to gain Linux support for CCE through the power of the community, and given the current situation where the development company has no extra resources, it would be better to initiate an "OpenCCE" project in the community rather than trying to prove to the CCE company that "this doesn't require many resources."
