### ISSUE TITLE
[bug] cc.audioEngine.play ignores volume parameter in browser

### ISSUE THREAD

**Issue by bnega** [cocos/cocos-engine#1854]
The volume parameter of cc.audioEngine.play does not seem to work in the browser.

`cc.audioEngine.play(this.audio, false, 0);` is silent when played in simulator, but is fully audible when played in browser.

My code sample was adapted from the "Use AudioEngine" example here: http://cocos2d-x.org/docs/editors_and_tools/creator-chapters/audio/audio/index.html

(Observed on MacOS 10.12.5,  Chrome Version 59.0.3071.115, Cocos Creator v1.5.2)

**Comment by jareguo** [comment]
Thanks so mush! This should be fixed by https://github.com/cocos-creator/engine/pull/1848/files

**Comment by bnega** [comment]
Great, thanks. What release will this fix be in?

**Comment by jareguo** [comment]
1.6 Beta4
