### ISSUE TITLE
Array property shows as single item in Windows editor

### ISSUE THREAD

**Issue by sommerper** [cocos/cocos-engine#1864]
CC v1.6.b3

Declaring a property like so
```
@property(cc.SpriteFrame)
ballSprites: Array<cc.SpriteFrame> = [];
```

![image](https://user-images.githubusercontent.com/1512048/28804246-376e06ce-7662-11e7-858b-00f41cc3e552.png)

I cannot add multiple items.

(This works on Mac)

**Comment by jareguo** [comment]
You should not ignore the `default` value in `@property`, this is a bug of TypeScript compiler.
```
@property({
  type: cc.SpriteFrame,
  default: []
})
ballSprites: Array<cc.SpriteFrame> = [];
```

**Comment by nkpresh** [comment]
I tried this but I got an error @jareguo
