### ISSUE TITLE
如何远程调试cocos-h5版本的js代码

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#1880]
如何远程调试cocos-h5版本的js代码， 用cocos creator打出h5包在各种浏览器中运行时遇到非常多的兼容性问题， 现在需要在手机上运行游戏时能够在pc端进行代码调试。

**Comment by jareguo** [comment]
请参考 https://github.com/wuchangming/remote_inspect_web_on_real_device

**Comment by lovekankan** [comment]
多谢了。
