### ISSUE TITLE
Polygon Physics editing improvements and docs

### ISSUE THREAD

**Issue by KioriSun** [cocos/cocos-engine#1885]
This is a suggestion for interface improvement.
When editing physics polygons, i noticed that sometimes the transform gizmos?(the arrows and rotation helpers) would get in the way of the polygonal axis, and making it hard to select each one when there was overlap.
It would be nice if when you clicked on the 'editing' checkbox it would take away the transforms from the object, leaving only the polygon visible.(and the image of course)

Another thing is, it would be cool if when you clicked on a point of the polygon in the panel(the respective property), it would light up differently(light blue?) in the polygon on the scene, making it easier to know which one you are editing at the time, for a more effective value based editing.

Also, i saw an error at the docs, and dunno where to report this:
http://cocos2d-x.org/docs/editors_and_tools/creator-chapters/physics/physics/physics-manager/index.html
The text reads:
`cc.director.getPhysicsManager().debugDrawFlags = 
	cc.PhysicsManager.DrawBits.e_aabbBit |
    Cc.PhysicsManager.DrawBits.e_pairBit |
    Cc.PhysicsManager.DrawBits.e_centerOfMassBit |
    Cc.PhysicsManager.DrawBits.e_jointBit |
    Cc.PhysicsManager.DrawBits.e_shapeBit
    ;`
Notice the uppercase **C**c, this causes an error. I struggled with this for quite sometime until i noticed that it was a "typo" in the docs, please fix this for other newcomers. 
In the api reference it's correct.

I also added a few more reports and suggestions to the 1.6 beta3 post at the forum, but they are more focused on the beta.

**Comment by 2youyou2** [comment]
Thanks for your advice, it's very useful.
And we will fixed the typo soon.
