### ISSUE TITLE
用cocos creator1.4.2 开发的html5游戏在qq浏览器上运行异常。

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#1887]
其它浏览器运行度没问题，就qq浏览器运行异常， 控制台报错： 
SCRIPT5022: InvalidStateError 
bundle.project.js, 行20744 字符9
CSS3114: @font-face 未能完成 OpenType 嵌入权限检查。权限必须是可安装的。 
msyh.ttf

**Comment by knoxHuang** [comment]
bundle.project.js, 行20744 字符9，这行的代码能截图给我看看吗？

**Comment by lovekankan** [comment]
![image](https://user-images.githubusercontent.com/11287620/29011056-8268ed4c-7b62-11e7-93e1-d4cc1a615d86.png)

**Comment by knoxHuang** [comment]
你这个是加载字体的时候报错的吗？还是去请求什么报错的？能不能找一下具体的原因？

**Comment by lovekankan** [comment]
嗯，我自己看下， http://bath5.mggame.com.cn   这边有个测试链接， 在android的QQ浏览器上运行时点左上角头像打开个人中心没反应， 其它浏览器都是可以打开的， 可以帮忙看下吗？  
![image](https://user-images.githubusercontent.com/11287620/29011160-8667f0c2-7b63-11e7-9056-61b262519b20.png)

**Comment by knoxHuang** [comment]
好的

**Comment by knoxHuang** [comment]
是不是单纯放 ttf 上去就会有异常？
还是需要通过什么代码去加载？
最好能给我一个小的 demo 让我测试一下

**Comment by lovekankan** [comment]
我自己找到问题了， 很奇怪cc.loader.loadRes（） 在qq浏览器上运行没有走进回调函数
![image](https://user-images.githubusercontent.com/11287620/29013492-f7b766d8-7b75-11e7-93e8-9bac68e06d00.png)

**Comment by knoxHuang** [comment]
http://www.cnblogs.com/feigao/p/4789049.html 
应该是 TTF 的问题，你自定义 engine 一下，然后在 engine\cocos2d\core\label\CCTextUtils.js 中的 _loadWithCSS 函数中找到 

```js
fontStr += "url('" + url + "')
```
然后在后面加 `format('truetype');` 
```js
fontStr += "url('" + url + "') format('truetype');"; 
```

<**该问题上面为解决方案**>

**Comment by lovekankan** [comment]
好的， 帮忙看下这个cc.loader.loadRes（）加载预置资源，在android机器qq浏览器上没有进回调函数怎么回事哦

**Comment by knoxHuang** [comment]
不太可能没回调，你要打印一下 err 看是不是有错误信息

**Comment by lovekankan** [comment]
都没进回调函数， 怎么打印err信息？  我这边加了个alert("---heald.onPopup.4--");  提示都没有显示

**Comment by knoxHuang** [comment]
没报错信息吗？你先试看看我上面发的，有可能是被中断了

**Comment by lovekankan** [comment]
有联系方式么 私聊下 我qq： 545292428
