### ISSUE TITLE
scheduleUpdate() don't start on Spine and ParticleSysytem when change layer [HTML5]

### ISSUE THREAD

**Issue by yuriilychak** [cocos/cocos-engine#1893]
Hello.
On web platform particles and spine skeletons freezing when change layer of them. Every time when I change parent node of them I need to do scheduleUpdate manualy.
Steps to reproduce:
1. Create spineBoy or particle via ParticleSystem.
2. Retain it.
3. Remove from layer and add to another.
4. Release it.
5. See that animation freezing.
6. Do scheduleUpdate() and animation working.
On native it works automatically.

**Comment by jareguo** [comment]
These is no retain, release, or layer operation in Creator. Are you still using Cocos2d-JS ?

**Comment by yuriilychak** [comment]
@jareguo Yes, but Spine run-time are the same in both (retain and  release not important, the main idea to change layer). I see that particle system is different, and check it tomorrow.

**Comment by jareguo** [comment]
Sorry but I don't understand, there is no layer in Creator, how could you change it in spine runtime?

**Comment by yuriilychak** [comment]
@jareguo  Ok.
1. Create 2 variables with type cc.Node.
2. Create Spine skeleton.
3.  Apply some animation and add skeleton to one of the node.
4. Remove from added node and add to another node.
5. See freezing.
6. Manualy call scheduleUpdate() for skeleton.
7. All work fine

**Comment by jareguo** [comment]
If you called the `removeFromParent`, you should remember to pass a `false` otherwise it will cleanup all registered scheduler. see https://github.com/cocos-creator/engine/blob/master/cocos2d/core/utils/base-node.js#L572
