### ISSUE TITLE
Please provide an option to choose including/excluding anysdk into project

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#1897]
By default anysdk is integrated in project. Each time we built the main.js is reloaded with code:
        // anysdk scripts
        if (cc.sys.isNative && cc.sys.isMobile) {
            jsList = jsList.concat(['jsb_anysdk.js', 'jsb_anysdk_constants.js']);
        }

I dont want to use anysdk because I publish my game to Apple, I dont use Wechat IAP. I have to delete it all the time.

**Comment by zhefengzhang** [comment]
Now the Cocos engine no longer provides anysdk.
