### ISSUE TITLE
Can not include ScriptingCore.h

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#1931]
When I include “ScriptingCore.h” into my project, Xcode returned error:

In file included from /Users/BugsKiller/Documents/TDG/Test/SampleProj/build/jsb-default/frameworks/runtime-src/Classes/sample.cpp:12:
In file included from /Users/BugsKiller/Documents/TDG/Test/SampleProj/build/jsb-default/frameworks/runtime-src/proj.ios_mac/../../cocos2d-x/cocos/scripting/js-bindings/manual/ScriptingCore.h:29:
In file included from /Users/BugsKiller/Documents/TDG/Test/SampleProj/build/jsb-default/frameworks/runtime-src/proj.ios_mac/../../cocos2d-x/external/ios/include/spidermonkey/jsapi.h:18:
/Users/BugsKiller/Documents/TDG/Test/SampleProj/build/jsb-default/frameworks/runtime-src/proj.ios_mac/../../cocos2d-x/external/ios/include/spidermonkey/mozilla/RefPtr.h:422:1: error: variable has incomplete type 'void'
ImplCycleCollectionUnlink(RefPtr<T>& aField)
^
/Users/BugsKiller/Documents/TDG/Test/SampleProj/build/jsb-default/frameworks/runtime-src/proj.ios_mac/../../cocos2d-x/external/ios/include/spidermonkey/mozilla/RefPtr.h:422:27: error: reference to 'RefPtr' is ambiguous
ImplCycleCollectionUnlink(RefPtr<T>& aField)
...
I’m using Cocos Creator 1.6. With Cocos Creator 1.5.2 it's ok. I guess it’s related to C++ version.

**Comment by cuongnmx** [comment]
The problem is namespace conflict. 
cocos2d.h and ScriptingCore.h refer to different Ref classes (and maybe other classes too), but confuse by namespace. Maybe spidermonkey added new Ref class.

Solution: cocos2d::Ref instead of "using namespace cocos2d" and reference to "Ref".

**Comment by pandamicro** [comment]
You are right, it's always suggested to use the full namespaced name

cocos2d::Ref
