### ISSUE TITLE
Mask IMAGE_STENCIL not work in Canvas

### ISSUE THREAD

**Issue by kotjarko** [cocos/cocos-engine#1940]
I'm trying to create not flat level ground using the sprite mask.
It correctly works in WebGL render mode, but when i switch to Canvas render mode - it shows all of image. Mask not affects the image.

Screens:
in canvas mode:
![canvas](https://user-images.githubusercontent.com/10481232/29805650-45e45f6e-8cb5-11e7-8643-b4dacd07e150.png)
in webgl mode
![webgl](https://user-images.githubusercontent.com/10481232/29805651-45e428d2-8cb5-11e7-8237-8c921120df6f.png)

**Comment by jareguo** [comment]
Yes, it can only works in webgl mode, not supported in canvas.
