### ISSUE TITLE
Windows 10 Simulator don't work

### ISSUE THREAD

**Issue by dzen-intelligence** [cocos/cocos-engine#1957]
I'am install cocos creator version 1.6, and later install 1.6.6 and i have a problem. Simulator don't work. His show error "VCRUNTIME140D.dll not found" and "msvc140d.dll not found". On my windows i have installed only vc++ 2013. So, i'am trying to install vc++ 2015, but don't work still. When i'am install vc++ 2017, i have the same problem. In folder with simulator, was some dll, but previous versions. When u fixes this?

**Comment by jareguo** [comment]
I think it was fixed by @2youyou2

**Comment by dzen-intelligence** [comment]
thank u for answer
