### ISSUE TITLE
[Urgent] Wrong properties when added multi joint

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#1960]
I am adding some Revolute Joints. When I add the second joint, the first joint property changed to the same as the second one (everything). Now I can not modify the first joint because I can see it any more. I'm using CC 1.6.1

**Comment by 2youyou2** [comment]
@jareguo  
I think it's the same problem with this issue : https://github.com/cocos-creator/fireball/issues/6243.

**Comment by jareguo** [comment]
Yes this should be fixed in 1.6.2

**Comment by cuongnmx** [comment]
@jareguo
When 1.6.2 is released?

**Comment by jareguo** [comment]
It will released in next week
