### ISSUE TITLE
cocos creator 1.6.1 android editbox 崩溃

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#1961]
![image](https://user-images.githubusercontent.com/11287620/30106111-0d0e8812-932d-11e7-8a80-ca9fb2fedbfa.png)

**Comment by lovekankan** [comment]
注释掉editBox.setSelection(position);  这行代码就没事了， 崩溃日志：
![image](https://user-images.githubusercontent.com/11287620/30106342-b46b8dd0-932d-11e7-8522-3dccd6de10ce.png)

**Comment by knoxHuang** [comment]
问一下楼主你是通过什么操作触发这个报错的？我想测试一下，感谢

**Comment by lovekankan** [comment]
就是调用了editbox的setText方法就会崩溃， 不过不是所有的机型都会崩溃。

**Comment by knoxHuang** [comment]
好像并没有给出 setText 接口，只有

![image](https://user-images.githubusercontent.com/7564028/30192706-a4727d72-947b-11e7-9094-50eaee9a58f3.png)

**Comment by lovekankan** [comment]
底层调用的是setText , 上层不是， 操作步骤好像是点击输入框， 输入文字的时候崩溃的。

**Comment by knoxHuang** [comment]
哦，那我试看看，那你是什么机型导致崩溃的？

**Comment by lovekankan** [comment]
华为 TAG-AL00

**Comment by knoxHuang** [comment]
好的，感谢，我试看看（我问看看有没有这个机型）

**Comment by lovekankan** [comment]
这边可以帮忙看个creator1.6.1编辑器的问题吗？ 比较急， 场景的跟节点Canvas点击打不开属性检查器了。

**Comment by lovekankan** [comment]
![image](https://user-images.githubusercontent.com/11287620/30192839-6da8d72c-947c-11e7-9712-360341dadecd.png)

**Comment by knoxHuang** [comment]
@jareguo 能尽快帮他解决吗？还是需要等新版本？

**Comment by knoxHuang** [comment]
@VisualSJ 这个你在 1.6.2 修复了，但是他现在要怎么办？

**Comment by lovekankan** [comment]
找到原因了，  所有scene绑定了这个组建，  这么写不对吗？
cc.Class({
    extends: cc.Component,

    properties: {
        exitLogic: cc.Component.EventHandler,
        _list : null,
        _stack: {
            get : function() {
                if (!this._list) {
                    this._list = new Array();
                }
                return this._list;
            },
            set: function (value) {
                this._list = value;
            }
        }
    },
.....

**Comment by lovekankan** [comment]
把这个去掉就没事了：   
_stack: {
        get : function() {
            if (!this._list) {
                this._list = new Array();
            }
            return this._list;
        },
        set: function (value) {
            this._list = value;
        }
    }

**Comment by jareguo** [comment]
没有什么不对，是编辑器不够健壮而已

**Comment by VisualSJ** [comment]
这是编辑器的问题。
你先把 _list : null, 这个定义去掉试试。
应该可以正常使用

**Comment by lovekankan** [comment]
_stack: {
            get : function() {
                if (!this.__stack) {
                    this.__stack = new Array();
                }
                return this.__stack;
            },
            set: function (value) {
                this.__stack = value;
            }
        }    

真是奇怪啊，这样就好了，  _stack  里面只能用__stack变量

**Comment by lovekankan** [comment]
嗯嗯， 换成_list也可了

**Comment by knoxHuang** [comment]
这楼已经歪得不成样子了

EditorBox 目前因为没有你说的机型，然而我们这边的机型都不会出现崩溃的问题，只能等后面我们购买
机型以后再说了

**Comment by knoxHuang** [comment]
相关用户反馈： http://forum.cocos.com/t/creator-editbox-string/51587/8

**Comment by jareguo** [comment]
已经修复，感谢反馈。
