### ISSUE TITLE
cocos creator 1.6.1 webview 崩溃

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#1968]
(android安装包问题)   cocos creator 1.6.1 打开一个webview，同时监听android返回键， 点下返回键程序崩溃。

**Comment by lovekankan** [comment]
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if(keyCode == KeyEvent.KEYCODE_BACK){
            getGLSurfaceView().onKeyDown(keyCode,event);
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }

在按钮事件里面把key_back 事件转到getGLSurfaceView()里面就好了，  感觉webview把按钮点击事件的焦点拿走了

**Comment by knoxHuang** [comment]
能否把报错信息贴出来一下？

**Comment by lovekankan** [comment]
这个没有什么有用的错误信息， bug是必现的， 你们可以测试看看

**Comment by knoxHuang** [comment]
你这个操作是，打开 webView 然后按返回键就崩溃了？

**Comment by lovekankan** [comment]
嗯， 需要先监听android返回键事件

**Comment by knoxHuang** [comment]
你用什么监听 android 返回键事件的？ cc.systemEvent ？

**Comment by lovekankan** [comment]
cc.systemEvent.on(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown, this);

**Comment by knoxHuang** [comment]
```js
    onLoad: function () {
        cc.systemEvents.on(cc.SystemEvent.EventType.KEY_DOWN, this.onKeyDown, this);
    },

    onKeyDown: function (keyCode, event) {
        if(keyCode == KeyEvent.KEYCODE_BACK){
            getGLSurfaceView().onKeyDown(keyCode,event);
        }
    }
```
这样吧？

**Comment by lovekankan** [comment]
不是， if(keyCode == KeyEvent.KEYCODE_BACK){
            getGLSurfaceView().onKeyDown(keyCode,event);
        }   这个代码是在android activity里面加的

**Comment by knoxHuang** [comment]
有空的话，能否给一个 demo？

**Comment by knoxHuang** [comment]
此 issue 关闭，在 2.0 后如果遇到在打开
