### ISSUE TITLE
[BUG] 1.5.2 web published game not able to load TMX. Works on Android/iOS and Creator web server

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#1976]
Project includes a TMX map built with Tiled. Executing on browser and simulator works great.
Android/iOS builds works great.

Web mobile and web desktop has the following error:

> CCBoot.js:134 1.5.2
pack-downloader.js:163 Create unpacker 067ca4310 for 623f4319-b084-4612-8c0a-751d0ba7d9fe
CCDebugger.js:367 Can not find class 'cc.TiledMap'
(anonymous) @ CCDebugger.js:367
main.js:114 Success to load scene: db://assets/testMap.fire
CCDebugger.js:367 Script attached to 'nodetest' is missing or invalid.
(anonymous) @ CCDebugger.js:367

nodetest is a node with a tiledMap component and do not has a script attached.

Here is the project so you can try it: https://www.dropbox.com/s/nzpbez7w6aodc0y/realmsTestTmx.zip?dl=0

Is this a known bug?

**Comment by jareguo** [comment]
TiledMap module is not included, you should check the checkbox in project's module settings.
