### ISSUE TITLE
Video player 'ready-to-play' event behavior

### ISSUE THREAD

**Issue by cocosftw** [cocos/cocos-engine#1988]
On ios, ready-to-play event doesn't get triggered until videoplay play method is invoked while in android, ready-to-play event is invoked after the videoplayer is loaded.

**Comment by cocosftw** [comment]
Hi is there any update on this? As shown in the sample project we should only call the cc.videoplayer play method after the ready-to-play event is emitted but somehow in ios browser only meta-loaded event is triggered but not ready-to-play.

**Comment by qi0727** [comment]
I think it is caused by race condition. https://stackoverflow.com/questions/10235919/the-canplay-canplaythrough-events-for-an-html5-video-are-not-called-on-firefox

**Comment by Ronsku** [comment]
How should this be solved, so that it works for all browsers and devices? Found any good solution @cocosftw?

**Comment by xianyinchen** [comment]
Because of the platform difference, you can use the following judgement to make sure it is playable.
```
event === cc.VideoPlayer.EventType.READY_TO_PLAY || event === cc.VideoPlayer.EventType.META_LOADED
```
