### ISSUE TITLE
cocos creator 1.6.1 webview 半透明问题。

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#1990]
cocos creator 1.6.1 webview控件在h5上显示网页半透明，

**Comment by knoxHuang** [comment]
麻烦给一下详细的操作方式跟截图，或者 demo

**Comment by lovekankan** [comment]
好的， 这在准备demo， 弄好了怎么传给你啊？

**Comment by knoxHuang** [comment]
直接打包拖上来就行了，thx

**Comment by lovekankan** [comment]
我先描述下情况吧， 这种问题出现在oppo自带的浏览器上， 当不允许手机旋转时（默认是竖屏），打开一个横屏的的h5游戏，此时打开webview上的网页是半透明的。而且也不是所有的网页都这样。

**Comment by knoxHuang** [comment]
会不会是 oppo 自带浏览器的限制，其他浏览器会出现这种问题吗？

**Comment by lovekankan** [comment]
试了qq，猎豹 uc，没出现

**Comment by lovekankan** [comment]
百度浏览器也不行

**Comment by lovekankan** [comment]
[NewProject.zip](https://github.com/cocos-creator/engine/files/1319798/NewProject.zip)   demo做好了， 要构建选择横屏之后测试， 用oppo手机 百度浏览器测试。

**Comment by knoxHuang** [comment]
好的，我看看测试组是否有 oppo 手机，这个问题会跟进的，感谢

**Comment by lovekankan** [comment]
![image](https://user-images.githubusercontent.com/11287620/30680518-a39b8e96-9ed2-11e7-95c1-5def5b40c680.png)
麻烦看下CCSGWebView.js文件里面createDom() 方法， 代码好像有点问题

**Comment by knoxHuang** [comment]
嗯，这块应该是多余的，虽然这里有设置白色背景色，但是可能在 oppo 手机上不支持这样的写法，或许是需要在他的上一层设置背景色，这个会跟进的（现在任务比较多，所以不会立即的修复）

**Comment by knoxHuang** [comment]
我刚刚测试了一下并不会出现半透明的效果：

![image](https://user-images.githubusercontent.com/7564028/30736157-3f8af774-9fb4-11e7-9da2-4a8507f96f60.png)

**Comment by knoxHuang** [comment]
此 issue 关闭，在 2.0 后如果遇到在打开
