### ISSUE TITLE
cocos creator1.6.1 华为p9 搜狗浏览器 手机竖着运行横屏游戏时不会自动变为横屏， 而是竖屏摆放着， 导致游戏表现异常麻烦官方团队看下

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#1999]

**Comment by jareguo** [comment]
其它浏览器就正常吗？

**Comment by lovekankan** [comment]
正常， 就搜狗有问题

**Comment by lovekankan** [comment]
可以直接新建个helloword项目构建时选择横屏，把手机竖着测试。 （华为P9，搜狗浏览器）

**Comment by jareguo** [comment]
好的我们有空看看

**Comment by lovekankan** [comment]
大神， 有时间看下这个问题吗？

**Comment by lovekankan** [comment]
@jareguo  这个问题有复现到吗？

**Comment by jareguo** [comment]
抱歉，目前还没有测试，这个优先级不高。等 P 大有空看看吧。

**Comment by zhefengzhang** [comment]
使用华为 p20 （android 10） 启动搜狗浏览器 (6.2.18.100803 版本）进行测试。
![image](https://user-images.githubusercontent.com/35944775/110292707-99a97980-8028-11eb-9a75-77339b39b26d.png)
在 CocosCreator 2.4.4 版本上不能复现此问题。
