### ISSUE TITLE
cocos creator 1.6.1 热更bug

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#2006]
![image](https://user-images.githubusercontent.com/11287620/30907278-cc8f8698-a3ac-11e7-8168-fb17fdebb50e.png)
![image](https://user-images.githubusercontent.com/11287620/30907316-e6578602-a3ac-11e7-9819-2f802bac7190.png)
正在下载的文件大小 > 总大小。 这个有问题

**Comment by lovekankan** [comment]
不好意思，问题查到原因了， 被运维坑了， 替换文件时搞错了， 配置文件的大小跟实际不符合。

**Comment by jareguo** [comment]
这样子，那就好~
