### ISSUE TITLE
[BUG] Tmx wrong culling issue

### ISSUE THREAD

**Issue by dganzella** [cocos/cocos-engine#2015]
Hello!

I think I found a bug.

It I use cc.Camera on a tmx map, and this map is scaled, It will produce wrong culling on web.
![bug](https://user-images.githubusercontent.com/30127664/31239032-2359997a-a9d2-11e7-969f-58474ead84a7.gif)

Sample project:
[TMXCullingIssue.zip](https://github.com/cocos-creator/engine/files/1360141/TMXCullingIssue.zip)

Instructions: Press any key to move the camera.

ps1. It only happens on web, not on Android.
ps2. Changing the scale to (1,1) the scale o the "Scale" Node (in the example) will make everything work.
ps3. Setting ENABLE_TILEDMAP_CULLING to false C:\CocosCreator\resources\engine\bin\cocos2d-js-for-preview.js also 'corrects' the problem

**Comment by 2youyou2** [comment]
Hi, which version did you use?
Can you try 1.6.1 version ?

I think it's already been fixed.

https://github.com/cocos-creator/engine/commit/bd43e8b89d5f78712d45dbb18f8fa1da49dfc2de#diff-5ee0a747ff37b87d78b1df65e3884870

https://github.com/cocos-creator/engine/commit/19d0b45dc9b4226a849f0ffb1d30c2764de1061f#diff-5ee0a747ff37b87d78b1df65e3884870

**Comment by dganzella** [comment]
I tried on 1.6.1 - Windows

**Comment by dganzella** [comment]
Im fact I think these changes were an attempt to fix the bug but didnt solve it entirely

**Comment by 2youyou2** [comment]
It seems 1.6.1 not contains this pr : https://github.com/cocos-creator/engine/pull/1974.
#1974 should fixed scale problem.
