### ISSUE TITLE
CCWebView not releasing in Native

### ISSUE THREAD

**Issue by cocosftw** [cocos/cocos-engine#2017]
Hi apparently after loading a page in webview the memory will not be released even after calling destroy method explicitly on the cc.webview component as well as the node associated with it on ios. This is a sample project.
[test_web_view.zip](https://github.com/cocos-creator/engine/files/1361487/test_web_view.zip)

**Comment by dganzella** [comment]
I wonder if they use Uiwebview or wkwebview on cocos creator. wkwebview is much more performatic and handles memory better, I will take a look on the native code later.

**Comment by knoxHuang** [comment]
@cocosftw  Can you tell me your version of Creator？

**Comment by knoxHuang** [comment]
@dganzella  sorry, There is no intention to refactor CCWebView

**Comment by cocosftw** [comment]
v1.6.1

**Comment by knoxHuang** [comment]
You can use 1.6.2 or use this PR https://github.com/cocos-creator/cocos2d-x-lite/pull/838 to fix it
