### ISSUE TITLE
contact.getImpulse() returns null

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#2018]
I want to get impulse on collision but this code does not work:

onEndContact (contact, selfCollider, otherCollider) {
    cc.log('impulse = ' + contact.getImpulse());
}

// result: impulse = null

**Comment by dcorpStudio** [comment]
Same problem here with Cocos Creator V2.1.2
contact.getImpulse().normalImpulses =>always be { x:0, y:0 }
contact.getImpulse().tangentImpulses=>always be { x:0, y:0 }

Called onPostSolve() and contact.getImpulse() only have value inside onPostSolve()

**Comment by zhefengzhang** [comment]
PhysicsImpulse can only used in onPostSolve callback.
https://docs.cocos.com/creator/api/en/classes/PhysicsContact.html#getimpulse
