### ISSUE TITLE
Cocos Creator doesn't allow multiple spines (skeletons) to share the same atlas.

### ISSUE THREAD

**Issue by hyena3300** [cocos/cocos-engine#2020]
Hi, I would like to request a extension feature to allow skeletons to use the same atlas and png.

**Comment by khalid-sani** [comment]
Any updates on this? Currently, we have to duplicate the same atlas file to match the json filename

**Comment by sunnylanwanjun** [comment]
Try to place the file which you want to share atlas into same directory.
