### ISSUE TITLE
cc.sys.browserType

### ISSUE THREAD

**Issue by cocosftw** [cocos/cocos-engine#2021]
Hi theres a typo in the browser type determination code.
![screen shot 2017-10-07 at 5 09 35 pm](https://user-images.githubusercontent.com/31945498/31306415-628ca888-ab82-11e7-9c5d-fb03ba146d61.png)
Besides, on nexus devices with android Oreo all browsers are wrongly determined as Opera browser due to the word OPR in the android build version which presents in the user-agent.
![screen shot 2017-10-07 at 5 11 07 pm](https://user-images.githubusercontent.com/31945498/31306447-c1febd38-ab82-11e7-818a-e03120adce97.png)

**Comment by jareguo** [comment]
Hi @cocosftw, #2022 should fix this. Thanks.
