### ISSUE TITLE
cocos creator1.6.1 Hot update problem

### ISSUE THREAD

**Issue by lovekankan** [cocos/cocos-engine#2037]
when In the process of hot update, switch the cell phone network from 2g to wifi, restart after downloading, and make errors in the runtime js file.

**Comment by lovekankan** [comment]
切换网络之后重新开始下载了
![image](https://user-images.githubusercontent.com/11287620/31482328-73bfe224-af5a-11e7-8f59-aa0a1430dc23.png)

**Comment by lovekankan** [comment]
@pandamicro  这个可以优先看下吗？

**Comment by lovekankan** [comment]
![image](https://user-images.githubusercontent.com/11287620/31491872-61665d12-af7b-11e7-8952-f1492f779db5.png)

**Comment by xianyinchen** [comment]
这个是断点续传问题，2.4已经修复了
