### ISSUE TITLE
Weird Boundary lines in canvas mode in firefox 

### ISSUE THREAD

**Issue by shishir67** [cocos/cocos-engine#2038]
Hi,
Can anyone explain these boundary lines!
I am trying to take a screenshot in my game, but couldn’t succeed in webgl mode.
So thought of fixing my game to canvas mode.
But in canvas mode, in firefox textures have these weird boundaries.
Can anyone suggest something.
Either to remove these lines, or to implement screenshot in webgl.

Thanks in advance.

![lines](https://user-images.githubusercontent.com/32736161/31494878-d9a464da-af72-11e7-937a-2a577e827d52.png)

**Comment by shishir67** [comment]
Also i need to get base64 data to upload to server or share on facebook

**Comment by jareguo** [comment]
which version of Creator are you using?

**Comment by shishir67** [comment]
1.6.1

And I have managed to get base 64 data. So that's not an issue anymore.

**Comment by jareguo** [comment]
okay, but I can not reproduce this problem. Can you upload a demo?

**Comment by shishir67** [comment]
I shall do that in a bit of time,
Meanwhile I have found the boundaries are of nine scale stretching of slicing.
(They disappear if I change sprite type from SLICED to SIMPLE).
You could try nine scale stretch a sprite and set type of sprite to SLICED.
And then run in canvas mode in firefox.

**Comment by zhefengzhang** [comment]
Sorry. Starting from the 2.x version, canvas rendering is no longer supported.
