### ISSUE TITLE
If asset used in prefab fails to load, no error is thrown from cc.loader.loadRes

### ISSUE THREAD

**Issue by evkwan** [cocos/cocos-engine#2039]
Hi, I encountered a problem in using Cocos Creator.

I have a prefab that is using many resources in my game, and loaded it using cc.loader.loadRes. The assets used in the prefab will be loaded asynchronously after the prefab json file has been successfully loaded. But subsequently if some resources failed to load, no error will be reported by cc.loader.loadRes. The result is a broken prefab being shown on the game screen. 

![image](https://user-images.githubusercontent.com/14858904/31573469-817b81c0-b0ef-11e7-93b7-b8aaf393a645.png)

How to prevent this situation form happening? We do not want to show an incomplete prefab.

I have a test project prepared here for you to try. You can try turning off Chrome's network when the prefab starts to load after 5s of starting the scene. More pictures in the folder to illustrate the issue if I haven't described it well. 

[PrefabLoadingIssue.zip](https://github.com/cocos-creator/engine/files/1384464/PrefabLoadingIssue.zip)

**Comment by xianyinchen** [comment]
This problem no longer exists in 2.4 version.
![image](https://user-images.githubusercontent.com/8321365/109744796-db43ba00-7c0d-11eb-9611-a47c38085ebd.png)
