### ISSUE TITLE
animation clip event infinite loop at low frame rate

### ISSUE THREAD

**Issue by stewiic** [cocos/cocos-engine#2040]
Hello guys. To achieve a specific animation loop for my project, I have an animation clip with event tag to call a second animation clip to start playing. The second animation clip also have an event to call the first animation clip to start playing again.

this works fine until I manually lower the frame rate to 3 fps. This will cause an infinite event calling loop and hang the game. This worries me as my project would occasionally load some big resources and causing the frame rate to drop temporarily.

My project runs on Google Chrome web browser. Using its task manager I noticed the memory usage will rise up from normal 100mb to 2gb in a short period.

Attached is a test project of the problem. Please advise. Thank you so much :)

[AnimationCallbackTest.zip](https://github.com/cocos-creator/engine/files/1384514/AnimationCallbackTest.zip)

**Comment by zhefengzhang** [comment]
When cocos1 runs the animation, let cocos2 run the animation, and when cocos2 runs the animation, let cocos1 run the animation. This is your setting in the animation system and has nothing to do with fps.

![image](https://user-images.githubusercontent.com/35944775/110297033-fce9da80-802d-11eb-8d59-851bb8d58976.png)
