### ISSUE TITLE
Invalid Project path

### ISSUE THREAD

**Issue by Impulse21** [cocos/cocos-engine#2041]
I am using a valid path for my project and cocos creator states it's an invalid project path

version 1.6.1
![image](https://user-images.githubusercontent.com/9197147/31580591-9b99f4a0-b122-11e7-88c2-e7d394f9cf97.png)

**Comment by jareguo** [comment]
It is not a valid path, you should not contain "." in the path.

**Comment by Impulse21** [comment]
Why would cocos editor not accept a "." in the path. This is a valid OS path, shouldn't Coco's be able to handling this case since it's permit by the operating system. Also, to add to this. cocos2d-x CLI doesn't have this restriction.

I believe this is something that should be fixed.

**Comment by jareguo** [comment]
Because it is an invalid path for the Android project. It's not our restriction.

**Comment by Impulse21** [comment]
Hmm, never experienced issues with my path with other android projects outside of cocos. Nor do other game engines impose such restrictions. I found a work around for creating a project in the mean time.

Thank you for the explanation.

**Comment by jareguo** [comment]
You are welcome. We can improve it in the future.
