### ISSUE TITLE
protobufjs6.8  ts项目 在android和ios、模拟器上的黑屏问题（web正常）附demo

### ISSUE THREAD

**Issue by 15951836388** [cocos/cocos-engine#2042]
这算是主流的库了。官方最好能傻瓜式支持就好了，减少了很多用户的采坑，小白用户基本搞不定
[assets.zip](https://github.com/cocos-creator/engine/files/1386190/assets.zip)

**Comment by 15951836388** [comment]
android 真机 也黑屏

**Comment by jareguo** [comment]
![image](https://user-images.githubusercontent.com/1503156/31595694-21e5a3f2-b203-11e7-89da-99053643ceb0.png)
麻烦 @pandamicro 看看，这个报错信息查不了

**Comment by 15951836388** [comment]
刚又测试了js项目，凡是用了protobufjs，都是黑屏

**Comment by jareguo** [comment]
![image](https://user-images.githubusercontent.com/1503156/31598945-ebc4a58a-b215-11e7-9fb7-7379c66d25de.png)

**Comment by 15951836388** [comment]
那要怎么改？才能在真机上跑起来？

**Comment by 15951836388** [comment]
对了，初次编译报了一个错，但是web正常。不知道是不是这个问题
http://forum.cocos.com/t/hellow-android/51916

**Comment by 15951836388** [comment]
可以关掉了，1.7什么都不用改，就能正常运行jsb和web。有个小问题是。protobuf的生成的XXX.d.ts的代码提示文件必须要放在项目assets才行。

**Comment by jareguo** [comment]
嗯，1.7 用的 VM 不太一样，可能兼容性比较好。既然能支持那就关掉了。之后有问题可以再提。
.d.ts 应该是工具设置问题。
