### ISSUE TITLE
1.6.1-TiledMap 左边缘瓦块资源丢失

### ISSUE THREAD

**Issue by cpple** [cocos/cocos-engine#2044]
当试图加载一个比设定的地图单元格大的瓦块资源并将图片靠近左边缘时会出现丢失这个瓦块资源的问题
问题请参见 http://forum.cocos.com/t/creator-tiledmap-bug/52124

**Comment by jareguo** [comment]
麻烦提交一个 demo

**Comment by cpple** [comment]
[assets.zip](https://github.com/cocos-creator/engine/files/1388289/assets.zip)
以上demo @jareguo

**Comment by cpple** [comment]
看起来是有规律的，应该是x轴的条件判断错误，现在好像是  渲染边界、图片宽度、及图片边界坐标的计算时正负号有问题😙

**Comment by knoxHuang** [comment]
你是说渲染时裁剪的问题吗？

**Comment by cpple** [comment]
是的

**Comment by knoxHuang** [comment]
抱歉，现在手头上有比较紧急的任务，麻烦你先看看，我会尽快更进这块的

**Comment by cpple** [comment]
好的源码我不太熟悉，如果能告诉我渲染裁剪处理单元在哪个js相信会快些

**Comment by knoxHuang** [comment]
你看看 engine\cocos2d\tilemap\CCTMXLayerWebGLRenderCmd.js 中的 uploadData

**Comment by cpple** [comment]
好的谢谢

**Comment by knoxHuang** [comment]
这个好像没关系的，是因为你场景视角太靠近的原因，你用滚轮拉远一下场景应该就不会有裁剪了

**Comment by cpple** [comment]
尝试修正了这个问题 已经请求提交 具体是否合理请官方check

**Comment by cpple** [comment]
会被裁剪而且无论你用什么样的方式都会被裁剪包括引擎本身的预览及webgl

**Comment by knoxHuang** [comment]
好的，感谢你提的 PR, 这个可能要等一下 panda 有空的时候才能看，你先用着

**Comment by cpple** [comment]
我的修改是有问题的，新的修改已经提交我想应该是这里的问题，请review下

**Comment by knoxHuang** [comment]
好的，感谢，不过要等 panda 休假回来再能合，还需要他过目一下看看是否有其他问题

**Comment by cpple** [comment]
我想这个问题依然存在，但我并不认为我的修复是可行的，还请官方操心下！

**Comment by cpple** [comment]
我尝试在1.9.2，仍然出现这个问题 @knoxHuang

**Comment by knoxHuang** [comment]
该 bug 已经在 2.0 修复，可关闭
