### ISSUE TITLE
1.6 - 1.6.1 and 1.6.2beta3 Breakpoints not working on VSCode

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#2045]
Hi, I just tested my game developed with 1.5.2 with 1.6 - 1.6.1 and 1.6.2Beta3 and Breakpoints are not working (my code is javascript and typescript).

I believe I found out the problem. The issue is related to launch.json.

My project has this launch.json created with version 1.5.2:

```
{
    "version": "1.4.0",
    "configurations": [
        {
            "name": "Creator Debug: Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:7456",
            "sourceMaps": true,
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "diagnosticLogging": false,
            "sourceMapPathOverrides": {
                "assets/*": "${workspaceRoot}/assets/*"
            },
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

And if I open it with any 1.6+ version, sourcemaps are not working properly. I found out that this config file works well for 1.5.2 but for 1.6+ I have to update it to the newest version (generated by cocos 1.6+).

```
{
    "version": "1.4.0",
    "configurations": [
        {
            "name": "Creator Debug: Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:7456",
            "sourceMaps": true,
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "diagnosticLogging": false,
            "pathMapping": {
                "/preview-scripts/assets": "${workspaceRoot}/temp/quick-scripts/assets",
                "/": "${workspaceRoot}"
            }    
        }
    ]
}
```

This something that you should warn to developers. It is not clear anywhere that the launch.json has to be updated with a new version in order to properly work.

**Comment by xianyinchen** [comment]
Hi, this problem no longer exists in 2.4 version.
