### ISSUE TITLE
1.6.1 - 1.6.3 - 1.7 Tilemap Bug

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#2046]

**Comment by blocksbarcelona** [comment]
Hi, this is how it looks my map in 1.5.2 and 1.6:
![creator-1 5 2](https://user-images.githubusercontent.com/24223792/31627553-f5aadc98-b2ad-11e7-8720-98d45090ea2c.png)

And this is how it looks the same project opened with 1.6.1 and 1.6.2:
![screen shot 2017-10-16 at 19 57 33](https://user-images.githubusercontent.com/24223792/31627574-056082aa-b2ae-11e7-80cb-973b45f75594.png)

The map actually looks good with 1.6.1 in the editor. The problem is when I play the game:
![screen shot 2017-10-16 at 19 57 55](https://user-images.githubusercontent.com/24223792/31627587-12d4e58e-b2ae-11e7-9ad0-841f1ef89664.png)

In version 1.7, the editor is unable to load the map:
![screen shot 2017-10-16 at 20 02 33](https://user-images.githubusercontent.com/24223792/31627608-25f5d592-b2ae-11e7-9463-8f4f67b534db.png)

And Im unable to play the game because it is unable to load the map.

**Comment by cpple** [comment]
it looks has another bug.just when you take the tiles in different tiledset and put it into the same layer you well get break screen! sorry my pool english

**Comment by knoxHuang** [comment]
@jrosich Do you have any wrong information?

**Comment by knoxHuang** [comment]
This is 2 bugs, 1.7 version，It has been fixed

Can you give me a test case? (Test the 1.6 version)

**Comment by blocksbarcelona** [comment]
I will provide a test case for 1.6 later today.

**Comment by knoxHuang** [comment]
ok，thx

**Comment by blocksbarcelona** [comment]
Hi, I tried to load the map in a new test project and everything goes well. So I do not know how to reproduce it. All I know, is that it works in 1.5.2 and 1.6, and it doesn't in 1.6.1 and 1.6.2Beta3

**Comment by knoxHuang** [comment]
Can you give me appears the wrong tilemap resource ?

**Comment by blocksbarcelona** [comment]
The tmx resource do you mean? It is a tilemap created with "Tiled". The base map is almost final but still waiting to get the final icons from the artist. Here you have it: https://www.dropbox.com/s/u5wcqg1rlc04w5j/tmx.zip?dl=0

**Comment by blocksbarcelona** [comment]
I believe I found something... the issue is related to the opacity of the tiles (I change them dynamically whenever a new hexagon is explored). Still working on providing a test case.

**Comment by blocksbarcelona** [comment]
I found out the issue. It seems the bug its happening under the following conditions:

- WebGL (no issue with canvas)
- Change opacity of tiles in a given COL and a given ROW (no issues with just all tiles of a column)
- No issues on native
- Tested with 1.6.2Beta3 (I believe 1.7 has the same issue)

This is a test case: https://www.dropbox.com/s/u964lwcew743w9r/tilesBug.zip?dl=0

My computer:
![screenshot 2017-10-21 08 50 52](https://user-images.githubusercontent.com/24223792/31849093-023c20b0-b63d-11e7-9bd2-224d0f272860.png)

**Comment by jareguo** [comment]
Wow, thanks very much. Please submit a demo to us.

**Comment by blocksbarcelona** [comment]
@jareguo the link includes a project demo/test case to reproduce the issue. Let me know if you need anything else.

**Comment by blocksbarcelona** [comment]
Any feedback on this? Have you been able to reproduce it?

**Comment by blocksbarcelona** [comment]
I have updated the initial post as I found out that the bug is not present on 1.6. So it happened on 1.6.1 for the first time. This may help you track it down.

I'm unable to use newer versions of creator because of this issue. Any estimations on when are you planning to take check it out? Thanks!

**Comment by jareguo** [comment]
@knoxHuang is in holiday, he will check it after 28 Nov. Thanks for help!

**Comment by jareguo** [comment]
Will fix in 1.7.2-beta.2

**Comment by blocksbarcelona** [comment]
Hi, I have tested the fix and it works with Web builds and Android However there is a crash on iOS. I got this error:

```
ERROR: TypeError: this._sgNode.getTiles is not a function. (In 'this._sgNode.getTiles()', 'this._sgNode.getTiles' is undefined), location: src/jsb_polyfill.js:23258:57
STACK:
getTiles@src/jsb_polyfill.js:23258:57
buildMap@src/project.dev.js:3529:44
loadManager@src/project.dev.js:2295:35
mapLoaded@src/project.dev.js:2239:25
invoke@src/jsb_polyfill.js:13977:28
emit@src/jsb_polyfill.js:14156:117
sendEvent@src/project.dev.js:105:49
callBckMap@src/project.dev.js:3992:19
_loadMapCallback@src/project.dev.js:2389:35
_loadMapCallback@[native code]
src/jsb_polyfill.js:15111:38
src/jsb_polyfill.js:14982:43
src/jsb_polyfill.js:20281:21
onceWrapper@src/jsb_polyfill.js:14132:26
invoke@src/jsb_polyfill.js:13977:28
emit@src/jsb_polyfill.js:14156:117
callback@src/jsb_polyfill.js:24643:27
```

As you can see this is related to tilemap. it crashes on .getTiles(). This works great in Android.
My XCode version is 9.0.1 (9A1004). Check initial posts for my OS (I haven't updated it).
Thanks!

**Comment by jareguo** [comment]
Thanks, we will fix it in next version.

**Comment by knoxHuang** [comment]
What do you want getTiles to do? 
Because this API will be discarded to 2.0

**Comment by blocksbarcelona** [comment]
hi @knoxHuang I'm getting the tile Type of each tile using tiles.getTile(). Is there a better way to do it?

This is what Im doing:

```
var tiledLayer = this.node.getComponent(cc.TiledLayer);
var size = tiledLayer.getLayerSize();
this.mapTiles = tiledLayer.getTiles();
```
Then I use the information in mapTile to get the tile type:

hex.type = this.mapTiles[(row * this.cols) + col]

what else would be discarded? Do you have info on what would be the API to access the tiles of a tilemap?

**Comment by jareguo** [comment]
Why don't you use `setTileGID` and `getTileGIDAt`?

**Comment by blocksbarcelona** [comment]
Because it is easy to get an array of all tiles with tiledLayer.getTiles(); and I didnt know I couldnt use it ( and that you will remove it). 

I can change my code to work with setTileGID and getTileGIDAt, but still I want to know what API calls would be removed and what would be kept so I can adjust the rest of my code. 

@knoxHuang said API would be discarded. There are many developers are working with tiles like me (check forum), so it would be great to understand what API calls would be removed and what would be kept, and what would be added (and why the change, if you dont mind). Thanks!

**Comment by jareguo** [comment]
ping @pandamicro

**Comment by pandamicro** [comment]
@jrosich sorry for the confusion, in the current version, this should be a bug.

It's not decided yet whether we are keeping or removing this API in v2.0, we are seeing some use cases that requires these APIs. That's also why we want to know the reason you are using these APIs

**Comment by blocksbarcelona** [comment]
@pandamicro ok, I understand. 

This is my use case: I need to know the type of tile in order to trigger game events for that type of tile (type 1 = mountain, type 2 = forest, etc...). I also need access to the tiles to change opacity (explored, not explored...). See post 1 for game use. 

I can build an array of tile types with getTileGIDAt, but this means I have to build the loop myself through the map. 

With tiledLayer.getTiles(), I just got the bidimensional array in 1 instruction and there is no need to build the loop.

Let me know if I can be of any help.

**Comment by pandamicro** [comment]
@knoxHuang please ask @dumganhar for the help to bind getTiles / setTiles

**Comment by dumganhar** [comment]
Binds getTiles method：
https://github.com/cocos-creator/cocos2d-x-lite/pull/1053

It was missing since we did a big refactor of JSB in creator 1.7. Sorry for that.

**Comment by blocksbarcelona** [comment]
Thanks for the explanation! Happy to help.

**Comment by zlpersonal** [comment]
Regarding this opacity that is being mentioned, I find that node opacity property will not change the tilemap opacity. Is this intended or is it a bug?
