### ISSUE TITLE
Hover popups while debugging don't work when using 1.6-1.7

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#2049]
This is how it look likes on 1.5.2 for hellow world test project:
![screenshot 2017-10-17 22 20 23](https://user-images.githubusercontent.com/24223792/31688676-615c52a2-b38d-11e7-9b69-62b8a5a9601e.png)

And it is **not** showing any popup/content on 1.6-1.7

**Comment by jareguo** [comment]
Are you debugging on native?

**Comment by blocksbarcelona** [comment]
Hi, this is debugging web, while playing on Chrome. My computer: Macbook pro late 2011 with macOS Sierra 10.12.16 and latest version of VSCode (but I already got this issue a few months when tested the first 1.6Beta. So it is not related to VSCode I believe).

**Comment by blocksbarcelona** [comment]
Any feedback on this? Have you been able to reproduce it?

**Comment by jareguo** [comment]
Sorry we don't have time to test the VSCode debugger. Please use Chrome.
