### ISSUE TITLE
cc.sys.os is undefined with Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by obouton** [cocos/cocos-engine#2067]
Despite using Cocos Creator 1.6.1, I still have an issue with Error 3300 and Error 3400 under Firefox and Ubuntu Mate.

After some research, I found that cc.sys.os is undefined when running in the above conditions.
Thus the test below (from misc.js) is false and imagePool is not modified:

if ((sys.os === sys.OS_WINDOWS || sys.os === sys.OS_LINUX) && sys.browser !== sys.BROWSER_TYPE_CHROME) {
    misc.imagePool.resize(0);
}

Also, shouldn't "sys.browser" be "sys.browserType"? It seems "sys.browser" doesn't exist.

**Comment by jareguo** [comment]
Sorry, we do not have such device to test. Can you submit a PR to fix it ?
sys.os is initialized in CCSys.js (https://github.com/cocos-creator/engine/blob/master/cocos2d/core/platform/CCSys.js#L561-L566)
