### ISSUE TITLE
Game almost stopped when close ads on iOS

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#2074]
Steps to reproduce:
1. Show interstitial or video ads
2. Hide app (press Home button on device)
3. Show game again
4. Close ads
5. Click any item in game to print log and change some UI (hide some node, for example). Code runs, log shown, but UI is not changed.
Sometimes UI will updated, but after 5-10 minutes

Using Cocos Creator 1.6.2.

**Comment by zhefengzhang** [comment]
This problem has been tested in the 2.x version and has not been reproduced.

**Comment by zhefengzhang** [comment]
This problem has been tested in the 2.x version and has not been reproduced.
