### ISSUE TITLE
[1.6.2, quick-scripts] downloadScript fails on scripts from node_modules with # in path

### ISSUE THREAD

**Issue by jgod** [cocos/cocos-engine#2081]
Cocos Creator version 1.6.2, when previewing in browser.

`es5-ext` is a [common](https://www.npmjs.com/package/es5-ext) npm dependency, why is this breaking?

Expected behavior is to load along with all other dependencies in `quick-scripts/__node_modules` that loaded fine.

I also opened up a [topic](http://discuss.cocos2d-x.org/t/1-6-2-web-preview-missing-some-necessary-node-modules/39689) on the forum.

![node_modules](https://i.gyazo.com/0ddaa9098234aeb1d74c80775dd6003b.png)
![errors](https://i.gyazo.com/6089e286f51b05908e24dd426daec7d2.png)
![path](https://i.gyazo.com/f08cbf7cff09546b8cea7a183f43c08e.png)

**Comment by zhefengzhang** [comment]
![图片](https://user-images.githubusercontent.com/35944775/111608947-befe6a80-8814-11eb-8f6b-129608f3f8b4.png)
Is your file directory like this?

**Comment by jgod** [comment]
No, I probably had the `node_modules` (and my `package.json`) a folder above this. That explains why I ended up having to pre-compile my modules and include them as a module myself, outside the normal node_module loading mechanism. I did it like that so I could have my build-tools, typescript compilation, etc. before Cocos.
