### ISSUE TITLE
[Feature Request] Scene/prefab duplication

### ISSUE THREAD

**Issue by nimluckyfish** [cocos/cocos-engine#2089]
I would like to ask for easier duplication of assets in CocosCreator which is essential when creating levels or similar components/animations, etc.

Currently the only way I have found to duplicate a .fire or .prefab resource file is to:
1. Ensure the scene/prefab has a single root node
2. Drag the root node to the Assets panel (to create a new prefab)
3. **For scenes:** create a new empty scene and add the prefab to it
4. Convert the added prefab to an ordinary node

While this may be acceptable for a single file, when needing to duplicate a whole folder of prefabs & scenes, this manual approach becomes very time intensive.

We need the ability to select one or more assets or folders in the Assets panel, and duplicate the items selected, where CocosCreator would take care of generating both:
1. The new UUIDs for the newly duplicated files and
2. For newly duplicated resources which include references to other resources that were included in the selection - those UUID references should be updated with the new UUIDs of the duplicated referenced assets.

**Comment by jareguo** [comment]
@VisualSJ 第二点满足了吗？也就是说如果同时复制相互关联的 ABC 三个资源，会产生 DEF 三个新资源，并且三个新资源仍然相互关联。

**Comment by zhefengzhang** [comment]
Already provided
