### ISSUE TITLE
ios 关闭wifi，马上重连wifi.收不到onclose事件

### ISSUE THREAD

**Issue by DeloDuan** [cocos/cocos-engine#2090]
如果用户关闭wifi,再马上连接wifi 会收不到onclose事件，但这个时候socket句柄已经失效了。必须要重新连接才能发送和接受服务器消息。

**Comment by dumganhar** [comment]
报bug是这样报的么？

最最最基础的版本信息都没说。

**Comment by zhefengzhang** [comment]
请问怎么复现问题？

**Comment by zhefengzhang** [comment]
用户长时间没有回复 issues ，此工单暂时关闭。
