### ISSUE TITLE
TileMap里的对象层用到了“图像集合”， 在creator中不显示。

### ISSUE THREAD

**Issue by zhaochengcai** [cocos/cocos-engine#2113]
对象层用单独的图片可以在creator中显示，
但是用“图像集合”就不显示了。

**Comment by jareguo** [comment]
请提供 demo

**Comment by zhaochengcai** [comment]
creator版本 1.6.2

**Comment by xiaohao9509** [comment]
[map.zip](https://github.com/cocos-creator/engine/files/1477213/map.zip)
他上传不了,我帮他上传了  @jareguo @knoxHuang

**Comment by knoxHuang** [comment]
目前暂时不支持

**Comment by jareguo** [comment]
嗯，demo 我们先收下了，之后有人力的话会安排开发的。

**Comment by zhaochengcai** [comment]
好的, 谢谢！

**Comment by knoxHuang** [comment]
duplicated with #https://github.com/cocos-creator/fireball/issues/7873
