### ISSUE TITLE
scrollview 用代码设置偏移

### ISSUE THREAD

**Issue by CoderGLEric** [cocos/cocos-engine#2116]
this.scrollview.scrollToOffset()这个API 只是左右偏移
有没有API 和这个一样的 可以上下偏移
使用的是cocos2dx-JS cocosCreator 1.6版本

**Comment by knoxHuang** [comment]
这个就是根据你 scrollView 的朝向来进行偏移的，你左右偏移代表你现在的 scrollview 是 horizontal 方向，想要上下就设置为 vertical

**Comment by CoderGLEric** [comment]
如果想往 右下  坐下 一点一点偏移呢？ 是使用哪个api
scrollToOffset?这个api的意思真正是什么样？我试了下 左右是正常的 上下和预期效果不一样

**Comment by knoxHuang** [comment]
![image](https://user-images.githubusercontent.com/7564028/32934460-ccc5c8bc-cba6-11e7-8823-610807caf260.png)

那你就用这个来做吧

**Comment by CoderGLEric** [comment]
ok thanks  不知道为什么 scrollToOffset（）这个API 和预期效果又一致了
