### ISSUE TITLE
[Feature Request] Add checkbox "Fit target node" to Widget

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#2119]
Many times we use widget to scale a node to fit it's parent. I suggest to create a check box as a shortcut to do it in Widget component. Alternative shortcut is providing 2 checkboxes: "Fit to width" and "Fit to height"

**Comment by jareguo** [comment]
How about if Alt/Options is pressed down while clicking Left, we also set the left margin to 0px automatically. So user just need to click 4 times.

Or add a menu - maximize

![image](https://user-images.githubusercontent.com/1503156/32937192-566784d8-cbb2-11e7-8f22-767f8625f3e6.png)

**Comment by cuongnmx** [comment]
Ok. That would be better than current config.

**Comment by zhefengzhang** [comment]
Already used in version 3.0.0.
