### ISSUE TITLE
[Feature request] Add more hot keys to editor

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#2122]
As many other developers, I prefer using hot key for routine tasks. There are some hot key/shortcut I would like to have:
- Hot key to build project with latest build config (currently I have to Save, press Shift+Cmd+B, then click Build)
- Hot key to Preferences
- Hot key to clear log (or better: option to clear log every time run on simulator)
- Hot key to add new component (for example: Shift+Cmd+W to add a Widget), new script, new folder
- Hot key to clone a node and add it to new node
-...

**Comment by jareguo** [comment]
> (or better: option to clear log every time run on simulator)

It will be added in 1.8

> Hot key to clone a node

You can use Cmd + D

**Comment by zhefengzhang** [comment]
> (or better: option to clear log every time run on simulator)
Already provided.
![image](https://user-images.githubusercontent.com/35944775/110299505-b2b62880-8030-11eb-9860-6ce5117bc6d7.png)
