### ISSUE TITLE
[1.6-1.7beta] npm modules error - Only TS

### ISSUE THREAD

**Issue by blocksbarcelona** [cocos/cocos-engine#2130]
Cocos Creator shows this error message when trying to compile the project after adding a npm module (only TypeScript).

Note: **Works fine with  TS and JS on Creator 1.5.2**

![screenshot 2017-11-22 18 56 47](https://user-images.githubusercontent.com/24223792/33142650-8217b87e-cfb7-11e7-8a76-c41a32eec313.png)

How to reproduce:
This is what I did (**step-by-step**) to create the test case project and get that screenshot:

1) Create a new hello world TS project
2) select helloworld scene in the project
3) open the project folder in VSCode
4) Install build task from Creator
5) execute build task (add isbuildCommand: true or you wont be able to build. Please fix that too, thanks!). Save. Build. test that everything works ok.
6) open terminal in the project folder and execute: "npm init" to create package.json
7) install any node module (tested with eventManager and moment). For example, moment: "npm install moment"
8) add import statement: "import * as moment from "../../node_modules/moment";"
9) adding a test function:

```
    testCode() {
        cc.log(moment.now());
    }
```

Here it is the test project: https://www.dropbox.com/s/bfeti97599zm2gb/modules17b3ts.zip?dl=0

My system:
![screenshot 2017-11-22 19 12 55](https://user-images.githubusercontent.com/24223792/33143128-28ace9d8-cfb9-11e7-873f-42d641d5c3a6.png)

VSCode: 1.18
Cocos Creator: 1.17Beta3 (tested with 1.6.2 and 1.7rc2 and also failed). Error in TS files only. Works fine with JS.
Node version: v7.6.0
npm version: 5.0.3

Let me know if need further information.

**Comment by blocksbarcelona** [comment]
I found out the problem, thanks to the feedback of a fellow member of the forum. In version 1.5.2 I had to import the module using the path to node_module:
`import * as moment from "../../node_modules/moment";`

But starting on version 1.6.x I have to add them without path:
import * as moment from "moment";

I was not aware of the change and thats why the warnings and errors.

**Comment by jareguo** [comment]
You should not use npm modules, its deprecated since 1.3. Use plugin scripts instead.
