### ISSUE TITLE
CCClass 子类和父类必须在一个js文件中吗?

### ISSUE THREAD

**Issue by xiaohao9509** [cocos/cocos-engine#2136]
你好,我把子类和父类放在不同的.js文件中后,
creator1.6.2 报了 failed : ReferenceError: ValetBase is not defined.
子类和父类需要放在一个.js文件中才能继承吗?

**Comment by xiaohao9509** [comment]
var Node = cc.Class({
    ctor: function () {
        this.name = "node";
    }
});
var Sprite = cc.Class({
    extends: Node,
    ctor: function () {
        // 子构造函数被调用前，父构造函数已经被调用过，所以 this.name 已经被初始化过了
        cc.log(this.name);    // "node"
        // 重新设置 this.name
        this.name = "sprite";
    }
});
就像官网的例子一样

**Comment by jareguo** [comment]
请参考 http://www.cocos.com/docs/creator/scripting/modular-script.html
