### ISSUE TITLE
node.on('cancle')问题

### ISSUE THREAD

**Issue by CoderGLEric** [cocos/cocos-engine#2137]
cocos2dx-JS 中貌似没有监听事件冲突时的一个cancle回调，node.on（‘cancle’）；监听的只是不在该节点上的一个事件回调 ， 我查看源码，确实是有ccTouchesCallback onTouchesCancelled这个回调，请问下系统的touchCanclelled这个回调js中是怎么监听的？谢谢

**Comment by pandamicro** [comment]
touch cancel 事件
http://docs.cocos.com/creator/api/zh/classes/Node.EventType.html#touchcancel
http://docs.cocos.com/creator/manual/zh/scripting/internal-events.html
