### ISSUE TITLE
Can not change PhysicsCircleCollider radius in code

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#2140]
Bellow code does not work as expected: 

    let cl = this.node.addComponent(cc.PhysicsCircleCollider);
    cl.radius = 400;

**Comment by xianyinchen** [comment]
Hi, you need more some operation, refer this code.
```
let cl = this.node.addComponent(cc.PhysicsCircleCollider);
cl.radius = 400;
cl.apply();
```
