### ISSUE TITLE
集成android 原生，在切换activity 的时候，界面卡住。

### ISSUE THREAD

**Issue by gzbbxu** [cocos/cocos-engine#2150]
11-29 17:58:03.392 32600-433/com.ifreetalk.ftalk A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 433 (GLThread 11387)
11-29 17:58:03.533 1631-1631/? E/DEBUG: engrave tombstone!
11-29 17:58:03.533 1631-1631/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-29 17:58:03.533 1631-1631/? A/DEBUG: Build fingerprint: 'OPPO/A77/A77:7.1.1/NMF26F/1499074074:user/release-keys'
11-29 17:58:03.533 1631-1631/? A/DEBUG: Revision: '0'
11-29 17:58:03.534 1631-1631/? A/DEBUG: ABI: 'arm'
11-29 17:58:03.534 1631-1631/? A/DEBUG: pid: 32600, tid: 433, name: GLThread 11387  >>> com.ifreetalk.ftalk <<<
11-29 17:58:03.534 1631-1631/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-29 17:58:03.534 1631-1631/? A/DEBUG:     r0 00000001  r1 bf24f128  r2 00000000  r3 00000000
11-29 17:58:03.534 1631-1631/? A/DEBUG:     r4 beeeadd0  r5 bf24f000  r6 ae009178  r7 bf252000
11-29 17:58:03.534 1631-1631/? A/DEBUG:     r8 adf0e660  r9 00000002  sl b2fedd18  fp 00000001
11-29 17:58:03.534 1631-1631/? A/DEBUG:     ip 000002ec  sp beeeacc0  lr bfb03f4c  pc bfafd610  cpsr 200e0010
11-29 17:58:03.536 1631-1631/? A/DEBUG: backtrace:
11-29 17:58:03.537 1631-1631/? A/DEBUG:     #00 pc 006b9610  /data/app/com.ifreetalk.ftalk-1/lib/arm/libcocos2djs.so
11-29 17:58:04.001 1169-1169/? E/SystemGestures: SIWPE_TOUCH_EVENT_GAP_TIME  TIME OUT
11-29 17:58:06.537 552-552/? E/lowmemorykiller: Error writing /proc/32600/oom_score_adj; errno=22

**Comment by dumganhar** [comment]
@gzbbxu , 请提供demo。
手机机型？
系统Android版本？

**Comment by jareguo** [comment]
没有答复，issue 关闭
