### ISSUE TITLE
RichText AutoWrap Bug

### ISSUE THREAD

**Issue by skaraman** [cocos/cocos-engine#2151]
http://discuss.cocos2d-x.org/t/richtext-autowrap-bugged/40019

Hi, I found two bugs with autowrap -
![entered text](http://discuss.cocos2d-x.org/uploads/default/original/3X/2/3/23da982adba0a6d49d0d2f663c32cc19211464f3.png)

![resulting rich text](http://discuss.cocos2d-x.org/uploads/default/optimized/3X/8/7/871fcaba3094ebad276924beee749a954ddc22ca_1_496x500.png)

the expectation would be -

1 - no space in front of "uneeded space"
2 - whole word “autowrap’s” to drop to second line

**Comment by jareguo** [comment]
@knoxHuang : 文本换行要完美支持多语言是很难的，麻烦看看有没有办法简单的修改一下，或者提供接口由用户自定义换行方式。另外这个 bug 应该在 Label 中也存在。

**Comment by knoxHuang** [comment]
- [x] no space in front of "uneeded space"
- [x] whole word “autowrap’s” to drop to second line

**Comment by skaraman** [comment]
FYI - words like "don't, can't, shouldn't" and "we'll, I'll, we've, they've" should also drop to the next line. 
https://en.oxforddictionaries.com/punctuation/apostrophe

**Comment by pandamicro** [comment]
@skaraman  Thanks for the report, it's fixed and will be released in v1.7.2
