### ISSUE TITLE
Editbox, Input Mode Number , not display when string = "1,000"

### ISSUE THREAD

**Issue by boyvk92** [cocos/cocos-engine#2166]
Cocos creator 1.7.0 
When players enter the gold value to buy items, I want to transform that number ( the value ) into a different form. Players will find it easier to check the value that they has entered before ( Eg : 100000 => 100,000 )

I use cc.Edibox so players can enter the gold value they need. Input mode is a kind of Numeric that only number can be entered so players can not enter other kind of character

An error occurs when players enter more than 1000 gold value,the text doesn’t display in editbox. I’ve re-checked that, the error occurs when the text contains character “,’’ or 2 character ‘’.’’

**Comment by knoxHuang** [comment]
html5 input only supports 1.00 or 1 numbers in this format

**Comment by jareguo** [comment]
You should use normal mode instead of number mode. Then validate input text by yourself.
