### ISSUE TITLE
Spine environment problem

### ISSUE THREAD

**Issue by yuriilychak** [cocos/cocos-engine#2175]
Hello. I try to switch from Cocos2d-JS to Cocos Creator and have a lot problems with spine integration in Cocos Creator. I describe it on example.
I have game with a lot of spine objects.
![terrain01](https://user-images.githubusercontent.com/8695823/33770938-f9a00c8e-dc37-11e7-9adc-6c873919e5a0.png).
All stage objects made with spine. For reducing draw calls,  minimize atlas size (cause some skeletons use same images) and simplify re skin of levels, I merge all level data (springboard, walls, road tiles, speed ups and etc) to one atlas via TexturePacker (Spine texture packer is terrible).
![atlas](https://user-images.githubusercontent.com/8695823/33771540-01d7613e-dc3a-11e7-8ea8-7dc2cd844b33.png)
But when I try import it to Cocos Creator I get an error. The examples that you provide use only one skeleton for one atlas. SkeletonData has only two parameters, scale and atlas texture (this parameter do nothing).
![print](https://user-images.githubusercontent.com/8695823/33771909-77bc87de-dc3b-11e7-9aaa-77c8f3a3e7c9.png).
After that I try to create skeleton from code:
```
let jsonPath = cc.url.raw( 'resources/Trampoline.json' );
        let atlasPath = cc.url.raw( 'resources/Level.atlas' );
        let texturePath = cc.url.raw( 'resources/Level.png' );
        cc.loader.load( [jsonPath, atlasPath, texturePath], (err, result) => {
            let skeletonData: sp.SkeletonData = new sp.SkeletonData();
            skeletonData.textures = [result.getContent(texturePath)];
            skeletonData.atlasText = result.getContent(atlasPath);
            skeletonData.skeletonJson = result.getContent(jsonPath);
            let node = new cc.Node();
            let skeleton: sp.Skeleton = node.addComponent(sp.Skeleton); 
            skeleton.skeletonData = skeletonData; 

            node.setPosition(200, 200);

            this.node.addChild(node, 5);
        }); 
```
But in this case I have error that engine don't support creating skeletons from script :(
And in the third part I try to change meta file of skeleton to write linkages for atlas and texture, but it also  didn't work.
Are you have any solution to use spine json with atlas that have another name that skeleton?

About atlases. Other engines like Unity, Starling, Defold, PixiJS, LibGDX support native atlases for spine. 
This solves 2 problems: 

- You can use every texture from skeleton like sprite, and batch skeletons with other sprites (For example I can merge background atlas and level objects to one atlas, for reduce draw calls).
- You remove ".atlas" format from game, and use only one type of atlases.

This great made in [Defold](https://www.defold.com/manuals/spine/), they use auto atlases for spine. Earlier I write [implementation](http://esotericsoftware.com/forum/Cocos2d-x-TextureCache-integration-7450)  for use native plist atlases for Cocos2d-x runtime (It works only with quads).

**Comment by jareguo** [comment]
Thanks for the reply. We should make this more clear.
Now I have two question.
 - Why don't you just copy one duplicated JSON and rename it?
 - Is it possible to change entire atlas by using setSkin()?

FYI. On native platform, you can not create skeleton data dynamically, but you can change atlas dynamically
```
var skeletonData = this.skeletonData;  // the loaded skeleton data
skeletonData.atlasUrl = cc.url.raw('resources/Level.atlas');  // change its atals to other one
```

**Comment by yuriilychak** [comment]
Hello @jareguo. I have few json files for one atlas, and in library skeleton data always crashing cause don't find atlases with same name.
![dff](https://user-images.githubusercontent.com/8695823/33792691-3c13ee88-dcaf-11e7-9a34-66027b1cb23b.png).
I can't create spine objects in stage cause can't set atlas of spine data in editor, and get message like "Failed to drop asset <asset id>, message: Error: Can not create node from sp.SkeletonData". When I rename json to "Level" spine data works, but when I rename back it crash.
Editor use only atlases that named like json.
If you don't understend what I mean, I give you an example. I merge spine-boy and goblin to one atlas. Try add to stage both of them.
[Test.zip](https://github.com/cocos-creator/engine/files/1544394/Test.zip)

**Comment by jareguo** [comment]
Understand.

**Comment by zhefengzhang** [comment]
refer to this: https://docs.cocos.com/creator/manual/en/getting-started/faq.html#load-the-spine-resources-in-json-format

It can run in 2.4.x version.
