### ISSUE TITLE
引擎分包实现讨论

### ISSUE THREAD

**Issue by jareguo** [cocos/cocos-engine#2179]
需求：减小 72 变引擎首包。完整首包包含首场景、游戏脚本首包、引擎首包。引擎首包包含骨骼动画。

**Comment by jareguo** [comment]
建议的分包工作流：
1. 使用编辑器标准的模块裁剪裁剪出首包
1. 使用其它方式裁剪出扩展包
1. 加入扩展包热加载代码

在这个工作流之下，需求归纳成两个核心问题：
 - 如何让引擎核心包更小
现在核心包还是太大了，加上骨骼动画什么的，估计还是会超过 700KB，可能还是满足不了需求，**需要 `@Sunny` 直接在编辑器中裁剪一下试试。不行的话就还要再拆分核心包，这个难度就比较大**，需要后续讨论。
 - 扩展包如何生成
引擎现在采用的是基于 browserify 的 require 打包机制。browserify 基于 [module-deps](https://github.com/browserify/module-deps) 来静态解析脚本之间的依赖关系。因此可以用 module-deps 解析出首包用到了哪些脚本，或者自己解析生成好的 cocos2d.js 也能得出首包用到的脚本。然后使用编辑器标准的模块裁剪正常打包完整包，在打包的过程中排除所有首包用到的脚本，应该就能得出扩展包。
   - 编辑器标准的模块裁剪的 API 在 [engine.js](https://github.com/cocos-creator/engine/blob/master/gulp/tasks/engine.js) 中的 buildCocosJsMin，可以在这里面加点 log 看看项目构建时的传入参数是什么。要排除首包的脚本，需要在 excludes 中传入首包用到脚本。

注意的点：
 - 首包如何划分
这个可能要人工进行比较好，因为涉及首场景和游戏脚本首包的使用情况
 - 扩展包要能支持热加载
主要是扩展包要能 require 到首包内的脚本，这个需要测看看，应该是支持的。我记得 browserify 在 require 包内不存在的脚本时，会尝试去调用包外部的 require。
 - 整合编辑器构建流程
建议编辑器的模块设置，仅勾选首包用到的部分。首包正常构建，扩展包另外添加。注意 H5 平台的 url
 要添加 md5。

**Comment by pandamicro** [comment]
以前的相关讨论：cocos-creator/3d-tasks#11330

**Comment by pandamicro** [comment]
另外，在 new renderer 中删除了大量引擎中的无用代码，对于包体有一定的帮助。也可以尝试将引擎更好地模块化，在需要的时候才请求相关的模块，甚至可以由用户自己定义游戏代码的模块化。模块之间的相互引用是比较大的难点，可能要寻求 gulp + browserify 以外的其他解决方案

**Comment by zilongshanren** [comment]
@pandamicro  通过引擎模块化的时候采用es6的import export， 用rollup 或者 webpack的 tree shaking，应该可以比较好地解决无用模块的剔除。

另外，去除引擎内部的eval, Function等优化，使引擎能够支持 google closure compiler, 甚至在构建中集成 google closure compiler的高级压缩，这样基本可以解决包体的大小。支持gcc后，gcc的dead code elimination 也可以删除一些代码。

想要动态删除object中的无用函数调用，貌似得用静态分析，或者用一些注释，在打包的时候，用工具做预处理。（不成熟的想法。。）

**Comment by pandamicro** [comment]
我确实打算用 rollup 代替 browserify

但是动态模块加载和 gcc 的高级压缩应该是天生不兼容，毕竟高级压缩必须预知所有需要的脚本，并打成一个包

**Comment by jareguo** [comment]
感觉将来也应该不是用 gcc，而是应该用函数级别的 tree shaking。不过这涉及到很多地方，就不细说了。

**Comment by lijialiang** [comment]
对于引擎模块打包使用的工作流能否实现以第三方插件或者模块的模式去实现？因为对于一些开发者，工作流的自定义也相当重要。

**Comment by jareguo** [comment]
模块打包的工作流本来就是开源的，调用的都是 engine 下面的 gulpfile，你本来就能自定义啊

**Comment by lijialiang** [comment]
担心是把 fork 修改了 engine 的工作流，导致后续更新版本引发问题，所以看看有没有已其他的方式让引擎本身支持自定义，这样对于一些模块上的处理问题，可以交予开发者自行开发。

**Comment by jareguo** [comment]
后续更新版本时，merge 远端到本地 fork 的版本就行了吧？这部分代码和引擎耦合太紧密，暂时没想到如何做成插件。

**Comment by lijialiang** [comment]
是可以，但是这样就需要开发者长期维护迭代版本 ，我先 fork 阅读尝试修改源码，感谢回答。

**Comment by jareguo** [comment]
不客气~

**Comment by jareguo** [comment]
Issue moved to [cocos-creator/fireball cocos-creator/fireball#6929](https://github.com/cocos-creator/fireball/issues/6929) via [**ZenHub**](https://www.zenhub.com/)
