### ISSUE TITLE
[1.7.0] Bitmap fonts with spaces in name have missing texture id

### ISSUE THREAD

**Issue by sommerper** [cocos/cocos-engine#2202]
Attached two google fonts. One has a space the other one doesn't.
Only the latter works when assigned on a label.

[HelveticaNeue Light.zip](https://github.com/cocos-creator/engine/files/1579196/HelveticaNeue.Light.zip)
[HelveticaNeue-Light.zip](https://github.com/cocos-creator/engine/files/1579197/HelveticaNeue-Light.zip)

**Comment by jareguo** [comment]
The limitation comes from the browser. We will prompt the user to rename it.
