### ISSUE TITLE
[1.6 - 1.7] Widgets get disabled for no reason

### ISSUE THREAD

**Issue by sommerper** [cocos/cocos-engine#2203]
I'm not sure what is causing it but it appears that sometimes widgets get disabled for no reason.

I turn it back on and it works again for a while until it turns itself off again.

I have a project that I'm currently working that is using widgets extensively and and all of them where turned off all of a sudden.

**Comment by jareguo** [comment]
If AlignOnce is on, the widget will disable itself after alignment. (At Runtime)

**Comment by sommerper** [comment]
But that's not what I'm talking about. In the editor I have to repeatedly enable the widgets because something turns them off.

**Comment by jareguo** [comment]
When you preview animation in the Timeline, the widget will be disabled to make sure animation take effects. After the preview, widgets will be enabled automatically.

**Comment by sommerper** [comment]
There's something going on when I trigger animations. I just had an issue which I can't explain.
1. All widgets are set up and working correctly.
2. In MyView.ts I add some code where I trigger an animation like so
```
this.anim = this.node.getComponent(cc.Animation);
this.anim.play('LeaderboardScreen_Intro');
```
3. Go back to editor and press play
4. In browser widgets are now disabled.
5. Go back to editor and see that widgets are all disabled.

I changed nothing in the editor except for pressing play.

**Comment by jareguo** [comment]
Please post a demo project for us. It should be a bug that the script executed in editor unexpectedly.

**Comment by sommerper** [comment]
Ok, I'll see if I can get around to doing that.
