### ISSUE TITLE
[BUG] Crash on iOS when update tile color, opacity

### ISSUE THREAD

**Issue by cuongnmx** [cocos/cocos-engine#2206]
I'm using tiled map and I regularly update tile in the map:

tiledLayer.getTileAt(x, y).color = color;
tiledLayer.getTileAt(0,0).opacity = opacity;

After few updates the game crashes.

**Comment by jareguo** [comment]
Which version? Please submit a demo.

**Comment by cuongnmx** [comment]
version 1.7, 1.7.2, 1.8.
You can use any tiled map and use above code.

**Comment by jareguo** [comment]
Which platform? Please submit a demo, our developers have no time to do that demo.

**Comment by cuongnmx** [comment]
I have tested on official version 1.7.2 and the bug is fixed. At the moment I post the issue I tested with beta version. I close this issue.

**Comment by jareguo** [comment]
Thanks!
