### ISSUE TITLE
locPosition is null

### ISSUE THREAD

**Issue by kongsanwen** [cocos/cocos-engine#2223]
> Uncaught TypeError: Cannot read property 'x' of null
>             at cc_Node.setPosition (CCNode.js:1576)
>             at cc_SampleAnimCurve._applyValue (animation-curves.js:121)
>             at cc_SampleAnimCurve.sample (animation-curves.js:192)
>             at AnimationState.22.proto.sample (types.js:390)
>             at AnimationState.22.proto.update (types.js:283)
>             at AnimationAnimator.16.animProto.update (animator.js:28)
>             at CCClass.update (animation-manager.js:20)
>             at TheClass.update (CCScheduler.js:401)
>             at TheClass.mainLoop (CCdirector.js:1399)
>             at callback (CCGame.js:567)

我是在我的项目里面发现的这个bug，在游戏场景开始播放动画，动画有回调事件，然后跳转到另一个场景，发现在浏览器控制台出现该异常，不一定会造成游戏卡死，接入bugly之后，发现上传了很多的这种异常，
建议在CCNode.js增加容错，
```
                color: {
                    get: function() {
                        return this._color.clone();
                    },
                    set: function(value) {
+                      if (!this._color) { return ; }
                        if (!this._color.equals(value)) {
                            this._color.fromColor(value);
                            255 !== value.a && cc.warnID(1626);
                            this._sizeProvider instanceof _ccsg.Node && this._sizeProvider.setColor(value);
                        }
                    }
                },

    setPosition (newPosOrX, y) {
        var x;
        if (typeof y === 'undefined') {
            x = newPosOrX.x;
            y = newPosOrX.y;
        }
        else {
            x = newPosOrX;
        }

        var locPosition = this._position; 
  +    if (!locPosition ) {
  +        return ;
  +    }
```

**Comment by jareguo** [comment]
请自行在回调中校验节点是否已经销毁。校验方法是 if (!node.isValid) return;
当然，更好的做法是切换场景时，主动停止动画或者取消回调。

**Comment by kongsanwen** [comment]
额，完整的流程我没办法重现，我们测试也是在一种很极端的情况下重现出来，setposition函数应该不是游戏代码调用的，应该是引擎在执行编辑的动画clip的时候出现的，所以回调是不存在的，我只是根据堆栈里面的异常说这个地方可能有回调什么的。

**Comment by jareguo** [comment]
有可能是动画会控制子节点，播放到一半时，用户不小心把动画的子节点删掉引起的。
麻烦 @2youyou2 确认下这个问题是否存在，如果存在的话，似乎在 sample 的时候验证下 target.isValid 会好点。

**Comment by zhefengzhang** [comment]
2.4.4 版本无法重现。
