### ISSUE TITLE
Cocos Creator Adds Unwanted Blur to Sprites 图片模糊

### ISSUE THREAD

**Issue by maximtsai** [cocos/cocos-engine#2232]
In Cocos, I notice that my sprites are slightly blurry looking. This happens even if I have scale set to 1 and have size mode RAW for the sprite.
![image](https://user-images.githubusercontent.com/6758316/34503499-7cff0870-efcd-11e7-8d87-cf982d169799.png)

Creator version（版本号）: v1.6.1
Affected Platform （受影响的平台）: I am using Windows 10. Problem happens on web and simulator and may happen on other platforms but not yet tested.
How to reproduce?（如何重现）: 
1. Add any sprite with some amount of complexity to Cocos Creator
2. Run Simulator

Here is a picture of my setup. Nothing special.
![image](https://user-images.githubusercontent.com/6758316/34503569-e54ca176-efcd-11e7-9ed7-85118bbea821.png)

Is there any way to get rid of this blur/anti-aliasing from Cocos Creator?

**Comment by pandamicro** [comment]
Globally, `cc.view.enableAntiAlias(false)` will do the trick.
Otherwise, you need to use `texture.setAliasTexParameters();`

**Comment by rajatk001** [comment]
Thanks bro, You solved my problem.
