### ISSUE TITLE
Autocompletion not working - errors in creator.d.ts

### ISSUE THREAD

**Issue by rChaoz** [cocos/cocos-engine#2246]
After doing all the steps in getting auto completion, I could not get VS Code to suggest anything when typing `cc.`. Steps for autcompletion are the ones mentioned in the docs (without the not mentioned but existing in the `Developer/VS Code Workflow` menu option - "Add TypeScrypt Config"):
* installed the cocos creator extension (which appears in VS Code extensions)
* generated VS Code API source (creator.d.ts)

However, autocompletion did not work at all. 

### Fix

So I checked all the files, and I found that there were 39 errors in creator.d.ts, all of them being created by having `&#95;` (ASCII code for '_') in line 1234:

    export function Class(options?: {name?: string; extends?: Function; ctor?: Function; &#95;&#95;ctor&#95;&#95;?: Function; properties?: any; statics?: any; mixins?: Function[]; editor?: {executeInEditMode?: boolean; requireComponent?: Function; menu?: string; executionOrder?: number; disallowMultiple?: boolean; playOnFocus?: boolean; inspector?: string; icon?: string; help?: string; }; update?: Function; lateUpdate?: Function; onLoad?: Function; start?: Function; onEnable?: Function; onDisable?: Function; onDestroy?: Function; onFocusInEditor?: Function; onLostFocusInEditor?: Function; resetInEditor?: Function; onRestore?: Function; _getLocalBounds?: Function; }): Function;	
Naturally, I replaced `&#95;` with `_`. After that, all I had to do is restart VS Code and auto completion was there.

**NOTE**: Having a `tsconfig.json` file will (somehow) disable / break auto completion. Basically, do not generate the typescript config from the developer menu, or, if you have, delete the `tsconfig.json` file.

### Creator version?（版本号）
Creator v1.7.2
VS Code version: 1.19.1 (if that matters for the `tsconfig.json` part)

### How to reproduce?（如何重现）
Have VS Code installed, create a new project, install extension, generate API source. Open the project folder in VS Code.

**Comment by jareguo** [comment]
Thanks for the reply, this will be fixed in 1.8.1 (or 1.7.3, when 1.8.1 is stable enough)
