### ISSUE TITLE
cc.Layout wrong width & height in scaled nodes

### ISSUE THREAD

**Issue by alexanderzubarev** [cocos/cocos-engine#2252]
I am using scaled labels inside layout, but layout does not correctly get the width of the label, it get it without scale factor.
For example i have label with scale 0.5 and width 50, cc.Layout should use width * scale (25) instead of 50.

The initial reason of using scaled labels is that on mobile phones with high DPI all labels looks blurry, so i multiply fontSize & liheHeight with scaleFactor (x2, x3) and scale the label to 1/scaleFactor.

I am using Cocos Creator 1.7

**Comment by jareguo** [comment]
Thanks for the feedback, we should take scale of children into account.

**Comment by jareguo** [comment]
@CocosAss 请看下这个问题，在编辑器中测试，提交到 next 分支。

**Comment by jareguo** [comment]
Fixed, it will be landed on v2.0
