### ISSUE TITLE
1.7 iphoneX下调用cc.director.convertToGL()转换错误

### ISSUE THREAD

**Issue by vonhezhou** [cocos/cocos-engine#2257]
### Creator version?（版本号）
1.7

### Affected platform?（受影响的平台）

IOS11
### How to reproduce?（如何重现）
iPhone X下，调用cc.director.convertToGL(0， 100).y - cc.director.convertToGL(0， 0).y === 200,
而不是300.
iPhone X物理跟逻辑分辨率的比应该是3

**Comment by dumganhar** [comment]
你的理解有误，convertToGL 是把 用户设计分辨率下的 UI 坐标系（左上角为原点）的点转换为下的GL坐标系(左下角为原点)。就是输入输出都是基于设计分辨率的，convertToGL 把Y 做了 height - Y 的操作。
与iphoneX 本身的物理分辨率没关系。

cocos2d-x 里面已经不是ios系统的中的pixel -》point的关系，cocos2d-x是根据用户设置的“设计分辨率”而规划对应的point值。你如果需要获取物理尺寸，可以通过 cc.view.getFrameSize 拿到。

**Comment by jareguo** [comment]
这个 API 讲得也太不清楚了…… convertToUI 和 convertToGL 都只讲到了 point，没说到设计分辨率。麻烦更新一下 CCDirector.js 的注释

**Comment by vonhezhou** [comment]
原来是这个意思"就是输入输出都是基于设计分辨率的"，我一直都误解了，以为是从屏幕坐标转换进入cocos的坐标空间。哦，不对，中文文档就是这么写的啊
