### ISSUE TITLE
Socket.io在native上事件只能有一个监听者

### ISSUE THREAD

**Issue by chenpangzi** [cocos/cocos-engine#2270]
### Creator version?（版本号）
1.6.2

### Affected platform?（受影响的平台）
native

### How to reproduce?（如何重现）
io.on('disconnect', =>console.log('disconnect   1'));
io.on('disconnect', =>console.log('disconnect   2'));
只会打印 disconnect   2

**Comment by jareguo** [comment]
谢谢反馈，我们之后计划移除 socket.io 的原生实现。并且提供在 native 上使用重写过的使用纯 JavaScript 实现的 socket.io 的相关教程。
目前的 socket.io 原生实现都不再维护了，之前这个实现也不是我们做的，是网友提供的，我们没有人能
 hold 住这部分内容，非常抱歉。建议你尝试自己 debug 修复问题。
