### ISSUE TITLE
怎么打包时修改jsb_polyfill文件

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#2278]
### Affected platform?（受影响的平台）
 mac

### How to reproduce?（如何重现）
场景切换时触发这个问题的！可是代码里上下的确没有这个问题

### JavaScript output or error produced?（报错信息和调用栈）

01-22 16:03:19.197 19323 19356 D cocos2d-x debug info: jsb: ERROR: File /Workspace/GitHub/KL_DDZ/KL_DDZ/KL_DDZ/build/jsb-default/frameworks/cocos2d-x/cocos/scripting/js-bindings/proj.android/../auto/jsb_cocos2dx_auto.cpp: Line: 4368, Function: js_cocos2dx_Node_setLocalZOrder
01-22 16:03:19.197 19323 19356 D cocos2d-x debug info: js_cocos2dx_Node_setLocalZOrder : Error processing arguments
01-22 16:03:19.197 19323 19356 E cocos js error:: assets/src/jsb_polyfill.js line:20461 msg:Error: js_cocos2dx_Node_setLocalZOrder : Error processing arguments

**Comment by jareguo** [comment]
请参考 http://docs.cocos.com/creator/manual/zh/advanced-topics/engine-customization.html#%E5%AE%9A%E5%88%B6-javascript-%E5%BC%95%E6%93%8E 进行定制

**Comment by GameKeys** [comment]
我不能定做！能不能简单点告诉我再什么地方修改一个这个文件
build/jsb-default/frameworks/cocos2d-x/ 修改那个文件就可以了！多谢了，项目有点急

**Comment by jareguo** [comment]
不懂，你那个文件跟 jsb_polyfill 有什么关系？？你需要改什么？这是你传入参数有问题吧？

**Comment by GameKeys** [comment]
我查了一下所有调用的地方我都加了输出！那个地方就没有我调用setLocalZOrder 函数

**Comment by jareguo** [comment]
查一下调用栈吧，看看是怎么调用到 jsb_polyfill  的

**Comment by GameKeys** [comment]
zIndex: {
                    get: function() {
                        return this._localZOrder;
                    },
                    set: function(value) {
                        if (this._localZOrder !== value) {
                            console.warn('gfp-zindexA:'+value);
                            // value=(typeof(value)=='number'?value:0);
                            if(!value){
                                value=0;
                            }
                            console.warn('gfp-zindexB:'+value);
                            this._localZOrder = value;
                            this._sgNode.zIndex = value;
                            this._parent && updateOrder(this);
                        }
                    }
                },
01-22 16:36:43.666 27957 27990 D cocos2d-x debug info: gfp-zindexA:NaN
01-22 16:36:43.666 27957 27990 D cocos2d-x debug info: gfp-zindexB:0

我加了一下打印就出现这个问题了！浏览器上没有这个问题！手机和模拟器上有这个问题

**Comment by jareguo** [comment]
这样看看不出来，麻烦提供一个 demo，用于呈现错误的可理解的 Creator 工程或资源，不依赖第三方工具或插件或者服务端。这个 demo 应该越小越好。

**Comment by GameKeys** [comment]
可以远程调试吗？

**Comment by jareguo** [comment]
抱歉公司不行

**Comment by GameKeys** [comment]
手机上可以输出堆栈信息吗？怎么输出？求帮助

**Comment by jareguo** [comment]
真机调试时，IDE 不是都能看到 log 吗？ log 里就有堆栈啦
