### ISSUE TITLE
[Deprecation] GainNode.gain.value setter smoothing is deprecated

### ISSUE THREAD

**Issue by skaraman** [cocos/cocos-engine#2279]
[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

WebAudioElement | @ | CCAudio.js:286

**Comment by VisualSJ** [comment]
Thank you for your feedback.
