### ISSUE TITLE
No option to choose font face for EditBox

### ISSUE THREAD

**Issue by skaraman** [cocos/cocos-engine#2282]
Looks like the EditBox component does not have an option to choose a font face and/or family:

http://docs.cocos.com/creator/manual/zh/components/editbox.html
<img width="285" alt="screen shot 2018-01-23 at 2 11 00 pm" src="https://user-images.githubusercontent.com/2840020/35303570-445d8a66-0047-11e8-98af-624cd732430f.png">

Expectation - have option to insert font face file (.ttf, etc) or input family (Arial) like on Label / RichText
<img width="292" alt="screen shot 2018-01-23 at 2 11 22 pm" src="https://user-images.githubusercontent.com/2840020/35303580-51eceb40-0047-11e8-8e3b-9038a2b15e21.png">
<img width="289" alt="screen shot 2018-01-23 at 2 11 16 pm" src="https://user-images.githubusercontent.com/2840020/35303584-54489934-0047-11e8-83ac-bce7dac42e97.png">

**Comment by knoxHuang** [comment]
https://github.com/cocos-creator/fireball/issues/3308

**Comment by edmand46** [comment]
pls make it.

**Comment by jareguo** [comment]
It will land on v2.1, see https://github.com/cocos-creator/engine/pull/3475
