### ISSUE TITLE
1.6.2下android，unschedule throw 1510错误

### ISSUE THREAD

**Issue by chenpangzi** [cocos/cocos-engine#2286]
### Creator version?（版本号）
1.6.2

### Affected platform?（受影响的平台）
Android

### How to reproduce?（如何重现）
unschedule(fn)这个fn之前没有被schedule过

另外报错的github链接下并没有这个errCode的解释
[报错链接](https://github.com/cocos-creator/engine/blob/master/EngineErrorMap.md#1510)

**1.4.2的android以及1.6.2的web是OK的**

**Comment by chenpangzi** [comment]
个人感觉这种情况下最多给个warn， 而不是直接打断程序的运行

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
