### ISSUE TITLE
cc.directors scheduleUpdate don't work on native

### ISSUE THREAD

**Issue by yuriilychak** [cocos/cocos-engine#2288]
### How to reproduce:
I have array with models (they contain only game data) that don't inherit from cc.Component. Sometimes I need to update some of them every frame.
I try to use cc.director.getScheduler().scheduleUpdate() for them it looks like:
```
cc.director.getScheduler().scheduleUpdate(this._updateNode, 0, false, (dt: number) => {
cc.log("Some actions");
});
```
It works on web, but on native nothing happen.
Now I use ugly workaround for this: 
```
cc.director.getScheduler().schedule(this.onScheduleUpdateHandler.bind(this), this._updateNode, 1/60, Number.MAX_VALUE, 0, false);
```
Is it any way to use scheduleUpdate on native?

**Comment by pandamicro** [comment]
The correct way to use scheduleUpdate is

```
scheduler.scheduleUpdate(this._updateNode, 0, false); // this._updateNode.update will be invoked
```

I know the API doc is indicating a fourth update function, but it's not supported in native. After some discussion, we think it's not very clear to support `updateFunc` parameter in web neither, because you can always use `schedule` to achieve the same task.

Sorry for the confusion in API description and inconsistence, we will remove the `updateFunc` in web.

**Comment by yuriilychak** [comment]
@pandamicro  Thanks for response. The problem is that update function that I wont to use in the simple class that don't extends from cc.Component. Is it any solution for add scheduler to it?
I use MVC for some parts of game, and sometimes some models (not all) need to update, for example, speed with acceleration. I have two ways to update them for loop in controller update in every frame or schedule for single model. In first case I do a lot of unnecessary actions every frame, in second updates only model that need to do some actions.

**Comment by pandamicro** [comment]
It's quite simple, you don't need to extend from cc.Component, you just need a update function definition. For example, the following code would work in your case.

```
this._updateNode.update = function () {
    // ... your two cases implementation
}
scheduler.scheduleUpdate(this._updateNode, 0, false);
```

**Comment by yuriilychak** [comment]
@pandamicro I use TypeScript, and can't extends from cc.Class, cause no TypeScript definition of it. When I try to schedule from class get an error cause class don't have data that generate cc.Class.

**Comment by yuriilychak** [comment]
@pandamicro Thanks.
