### ISSUE TITLE
Particle System texture atlas improvement

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#2292]
### Creator version?（版本号）
1.8.1

### Affected platform?（受影响的平台）
MacOS/Windows

### How to reproduce?（如何重现）
Forum post:
http://discuss.cocos2d-x.org/t/particle-systems-to-support-textures-from-an-image-atlas/40962

I know that Particle Systems doesn’t support textures from an image atlas, but this would be a very nice feature to have. Is there anything that makes this very difficult to do or inefficient CPU/GPU wise?

**Comment by yuriilychak** [comment]
Hello. Particles use another shader than sprites. Particle shader simpler than sprite cause don't need skew, slice9, atlas UV transformation and etc. It need's for create a lot of particles without FPS drop. Even if you merge them to one atlas with sprites, they can batch only with other particles (if cocos particle fragment shader support UV frames).

**Comment by jareguo** [comment]
@yuriilychak is right. But we will still support using SpriteFrame rather than Texture2D in v2.0, for API consistency.

**Comment by pandamicro** [comment]
Yes, it's a nice feature, and already supported in v2.0, we have also implemented particle using GPU based simulation

**Comment by Ronsku** [comment]
Thanks for your response! Great work everyone!
