### ISSUE TITLE
Auto-atlas issues

### ISSUE THREAD

**Issue by yuriilychak** [cocos/cocos-engine#2295]
### How to reproduce?

-  Is it any way to use auto-atlas on debug (simulator or in browser). For example on simulator I have 900 draw-calls but when I build to device I have only 4. It's drop fps on simulator and I don't know is my code drop FPS. In this case simulator is useless;
- Can I load auto atlases (and prefabs) from server (for example get new models for update), cause when project build complete I have only image of atlas(an i think atlas merged with project).
- Compression of image. It would be grate if it in creator, cause every time if project build I need t find all images an use [TinyPNG](https://tinypng.com/) for compress them (It reduce the 75% of image size).
- Margin. When I try to merge Spine atlases to one I get an error _"Uncaught TypeError: Cannot read property 'endsWith' of undefined"_ in cc.Texture2D after build (cause in run-time it don't use). When I try to merge bitmap fonts and UI elements to one auto-atlas it's work but can be better, cause when auto-atlas generate it merge only single images without parse. For example for cocos2d-JS I write parser that merge images and letters with changing .fnt  files (position of letters in .fnt file):  
![untitled-2](https://user-images.githubusercontent.com/8695823/35607292-10477a50-065c-11e8-9a12-7cee8fc4d77f.png)

**Comment by jareguo** [comment]
> Is it any way to use auto-atlas on debug (simulator or in browser). For example on simulator I have 900 draw-calls but when I build to device I have only 4. It's drop fps on simulator and I don't know is my code drop FPS. In this case simulator is useless;

Sorry, the only way is using TexturePacker rather than auto-atlas.

> Can I load auto atlases (and prefabs) from server (for example get new models for update), cause when project build complete I have only image of atlas(an i think atlas merged with project).

No...

> Compression of image. It would be grate if it in creator, cause every time if project build I need t find all images an use TinyPNG for compress them (It reduce the 75% of image size).

Yes, we will support compression, thanks.

**Comment by yuriilychak** [comment]
@jareguo Is prefabs can't be load from server too? Is it any way to do this (for example Unity use Asset bundles), or do it via workarounds, by parsing data from prefabs to json. If no, it means that every time when I add new graphic and animation (creating via cocos creator) to project and union them via prefabs, I increase build size, cause can't upload them at run-time. 
Maybe I did not express myself clearly. I mean how to load content of DLC (or some content that dont need in first user level, but need when user reach 20) if it is in prefab.

**Comment by jareguo** [comment]
> Is prefabs can't be load from server too? Is it any way to do this (for example Unity use Asset bundles)

AssetBundle is not yet implemented, but it will be landed in 2018.

> it means that every time when I add new graphic and animation (creating via cocos creator) to project and union them via prefabs, I increase build size, cause can't upload them at run-time.
Maybe I did not express myself clearly. I mean how to load content of DLC (or some content that dont need in first user level, but need when user reach 20) if it is in prefab.

Yes. There may be some kind of workarounds, but I am not sure how to do it without AssetBundle.
