### ISSUE TITLE
讨论：Node Component 是否应该存在 color 及 opacity 属性 ？

### ISSUE THREAD

**Issue by fusijie** [cocos/cocos-engine#2310]

**Comment by jareguo** [comment]
我觉得是不需要的
作为参考，能否提供一下 Unreal / Godot / PlayCanvas 的相关情况？

**Comment by fusijie** [comment]
**Unreal**
![](http://img.blog.csdn.net/20160830154751112?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

**Godot**
![](https://i.ytimg.com/vi/pFHzsgqufOI/maxresdefault.jpg)

**PlayCanvas**
![](https://forum-files-playcanvas-com.s3-eu-west-1.amazonaws.com/original/1X/42c1ab0f6b4cf64010dce5b18afdbad68036a076.png)

Unity 也是。这几个编辑器基础的 Entity 都只保留了 transform 属性

**Comment by jareguo** [comment]
Issue moved to [cocos-creator/fireball #6924](https://github.com/cocos-creator/fireball/issues/6924) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jareguo** [comment]
以后内部 issue 都建在 fireball 哈
