### ISSUE TITLE
ToggleGroup 文档404了

### ISSUE THREAD

**Issue by chenpangzi** [cocos/cocos-engine#2313]
http://docs.cocos.com/creator/manual/zh/api/classes/toggleGroup.html
404 error 
 并且[ToggleGroup组件参考](http://docs.cocos.com/creator/manual/zh/components/toggleGroup.html)提示我被新的组件取代，但是新组件的链接一样是404

[ToggleContainer组件](http://docs.cocos.com/creator/manual/zh/components/ToggleContainer.md)
404 error

**Comment by jareguo** [comment]
春节后我们会统一更新 API 链接哈

**Comment by chenpangzi** [comment]
嗯 ， 好， 那有可以应急的旧版吗？

**Comment by jareguo** [comment]
![image](https://user-images.githubusercontent.com/1503156/35838772-e6c26de0-0b27-11e8-9d02-246f9ec36ec2.png)
