### ISSUE TITLE
Missing asset-db package

### ISSUE THREAD

**Issue by sercand** [cocos/cocos-engine#2317]
Hello,  
I don't know if this is the correct place to submit the issue. It seems [asset-db](https://www.npmjs.com/package/asset-db) package on npm is not compatible with assets of cocos-creator v1.8. Also, [old repo](https://github.com/fireball-x/asset-db) is removed; therefore I am unable to work with new `.meta` files on created by cocos-creator.   
Is there any plan to re-publish the recent version of `asset-db` package to npm?

**Comment by jareguo** [comment]
Why do you need to use asset-db outside of CocosCreator?

**Comment by sercand** [comment]
@jareguo I am going to create a nodejs package to build games created with CocosCreator. In my case, I want to build the game on each commit and release it to s3. We use gitlab and our CI is docker based so each job runs as docker container. Also, CocosCreator does not support Linux officially. I have rebuilt [CocosCreator](https://hub.docker.com/r/sercand/cocos-creator/) to run on Linux but it is not efficient. I just want to build a game with a script like below.

     $ yarn
     $ yarn run build-game
     # cocos-builder /path/to/game --platform web-mobile

We were using phaser engine and webpack to build games.

**Comment by jareguo** [comment]
You can not build game by using asset-db. asset-db is just resources importers, not a real builder.
You should build the game on Mac, can Docker run on Mac?

**Comment by sercand** [comment]
@jareguo I know I can't build game by just using asset-db, It's for determining which assets to include on builds. CocosCreator generates a JSON file in output res folder and settings.js file to map asset ids and paths.
Docker and all other container technologies are only for Linux.

**Comment by jareguo** [comment]
> It's for determining which assets to include on builds.

It is determined by Creator, not asset-db.

> Docker and all other container technologies are only for Linux.

Well, I suggest using Mac, Linux support is not in the plans.

**Comment by jareguo** [comment]
I will close this because asset-db is not needed.

**Comment by pandamicro** [comment]
Additional info, asset-db is actually our private repo and not yet open sourced

**Comment by sercand** [comment]
@pandamicro asset-db open sourced before under fireball-x and there are some [forks](https://github.com/iHaD/asset-db) still lives on GitHub. When fireball become cocos-creator it was removed.

**Comment by pandamicro** [comment]
You are right, we upgraded a bit since then, the current version will not be open sourced in short term, hope you understand
