### ISSUE TITLE
CC_PREVIEW doesnt match documentation, should be off when game is built

### ISSUE THREAD

**Issue by zynga-jpetersen** [cocos/cocos-engine#2339]
Documentation says:
http://www.cocos2d-x.org/docs/creator-api/en/modules/GLOBAL-MACROS.html#ccpreview
"CC_PREVIEW - Preview in browser or simulator."

Code says:
https://github.com/cocos-creator/engine/blob/11c68ca83049ce28775783298451cd480027491d/predefine.js#L128
"defineMacro('CC_PREVIEW', !CC_EDITOR);"

That would seem to read that the constant is true so long as you arent in the editor? And from my testing that is true.

How should I detect running in the preview mode vs when the game is built?

Thanks,

### Creator version?（版本号）
 \>= 1.7.1 

### Affected platform?（受影响的平台）

All.

### How to reproduce?（如何重现）
Check constants when not in editor.

**Comment by jareguo** [comment]
> "defineMacro('CC_PREVIEW', !CC_EDITOR);"

Good question. Actually, the code only takes effect when running in the editor or previewing in browsers. So it behaves correctly.
When the game is built, CC_PREVIEW will be hard coded as false by UglifyJS, you can test it in your project.
