### ISSUE TITLE
分支1.8 engineVersion = '1.6.0';

### ISSUE THREAD

**Issue by LazyCushion** [cocos/cocos-engine#2340]
这里漏改了我可以理解, 但是 Creator随包的engine的这个值没有错误, 难道你们发布新版本不是从github上同步的么?

**Comment by jareguo** [comment]
目前发布新版本的时候，版本号会在本地替换，不会提交到 GitHub。这是不对的，过完年后我们会把版本号提交到 GitHub，谢谢反馈。
