### ISSUE TITLE
component.schedule 设定repeat，会执行n+1次

### ISSUE THREAD

**Issue by dream2023** [cocos/cocos-engine#2342]
version：1.8.1
platform：Mac
代码：
let interval = 5; // 时间间隔
let repeat = 3; // 重复次数
let delay = 2; // 开始延时
this.schedule(()=>{
     console.log('我执行了!');
}, interval, repeat, delay);

console信息：
eruda.min.js:2 1.8.1
eruda.min.js:2 我执行了!
3 eruda.min.js:2 我执行了!

从上面可以看出，先显示了一次（我执行了），然后又显示了3次，共4次

**Comment by h87kg** [comment]
请查看文档 http://docs.cocos.com/creator/api/zh/classes/Component.html#schedule

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/109625189-fd8bf800-7b79-11eb-911d-951b0b712ac7.png)
你好，目前设计就是这样，这个issue就先关了，如果仍然有其他问题，可以继续联系我们！
