### ISSUE TITLE
creator v1.8.1 的微信UserAgent判断错误

### ISSUE THREAD

**Issue by LazyCushion** [cocos/cocos-engine#2343]
### Creator version?（版本号）
v1.8.1

### Affected platform?（受影响的平台）

微信
### How to reproduce?（如何重现）
cc.sys.browserType

**Comment by pandamicro** [comment]
什么手机系统下？判断出的 browserType 是什么？

**Comment by zhefengzhang** [comment]
在2.4.4 版本和 3.0.0 版本测试均无此问题。
