### ISSUE TITLE
整理 Cocos Creator 1.x to 2.0 API 变更列表

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#2362]
Cocos Creator 2.0 engine 的开发重写了底层的渲染框架，整理了引擎的 API，这涉及到很多公有和私有 API 的变更。所以需要整理给用户，让用户更好得了解升级过程中的成本，这个任务产出的变更列表将作为升级文档的重要部分发布给用户。

这个任务的目标分为以下几个

1. 整理所有公有 API 的变更，模块，类，函数的增删；deprecation；函数名／参数／返回值的变更。
2. 扫描 engine 源码中的 API 注释格式是否有错误或遗漏。如果能补齐中文就更好了。
3. 私有 API 目前也有一部分用户使用，以模块／类为单位整理出我们所删除的 1.x 的私有 API，以便用户知悉。

@CocosAss  这项工作很琐碎，需要耐心和细心，不过也可以帮助你更快熟悉引擎的底层实现有哪些部分，各个模块之间如何协同工作，如果你有耐心，也建议阅读关键部分的引擎源码。

**Comment by ColinCollins** [comment]
收到,我尽快

**Comment by pandamicro** [comment]
take your time

**Comment by ColinCollins** [comment]
Panda大哥~,2.0和现版本的Api我应该去哪里查询啊?

**Comment by pandamicro** [comment]
目前版本：master 分支或 v1.8 / v1.9 分支
2.0：next 分支

所有的 API 文档都是从以上分支的源码中生成的，生成出来的文档 next 分支已经发你，目前分支的可以看[在线 API 文档](http://docs.cocos.com/creator/api/zh/)，顺便 @jareguo 也给他发一份离线的吧

**Comment by jareguo** [comment]
当前的离线版本在 https://github.com/cocos-creator/creator-api-docs ，clone 或者 download 下来即可

**Comment by ColinCollins** [comment]
收到

**Comment by jareguo** [comment]
issue 先关掉，2.0 发布前仍需要定期更新。
