### ISSUE TITLE
Layout component does not ignore non-active children while in children resize mode

### ISSUE THREAD

**Issue by unalakunal** [cocos/cocos-engine#2383]
### Creator version?
v1.8.0

### How to reproduce?
While using NodePool, say there exist 10 children for a parent but 7 of them has `active == false` and `activeInHierarchy == false`, so 3 of them are active at a time. During the resize, the layout component calculates according to all of the children of the corresponding parent node, but it should only care about the active ones instead.

**Comment by jareguo** [comment]
What layout mode you are using?

**Comment by unalakunal** [comment]
It's horizontal mode, I suspect that it's because `_doLayoutHorizontally` uses `children.length` instead of `activeChildCount` in layout component.

https://github.com/cocos-creator/engine/blob/cbe73519d75dd684229600c633b1076df7d77ab4/cocos2d/core/components/CCLayout.js#L526

**Comment by jareguo** [comment]
Thanks, we will check it later.
