### ISSUE TITLE
fnt 解析无法接受字符串格式的数字

### ISSUE THREAD

**Issue by pandamicro** [cocos/cocos-engine#2386]
反馈于 http://forum.cocos.com/t/rect-width-exceeds-maximum-margin/56868

fnt 文件如果数字以字符串形式保存，读取之后在做加法时，会变成字符串拼接，进而导致 uv 错误，需要在 fnt parser 中对字符串读取时做 parseInt 或 parseFloat 操作。

有问题的 fnt 文件：

http://forum.cocos.com/uploads/default/original/3X/3/b/3b474c5926d4b32bed93246e5fc28d631cb99b0b.zip

**Comment by PPpro** [comment]
引擎部分已经修复了这个问题，pr 已经提交
编辑器部分由于没有访问权限，所以没办法修复

**Comment by umbrellaPP** [comment]
已经用BMFont 工具测试过，不会出现小数的情况
