### ISSUE TITLE
微信小游戏不支持TTF字体

### ISSUE THREAD

**Issue by jareguo** [cocos/cocos-engine#2456]
@heyanfei commented on [Tue Mar 20 2018](https://github.com/cocos-creator/fireball/issues/7089)

微信小游戏不支持TTF字体，选择TTF字体后，构建出来的微信平台也还是使用系统默认的字体；

**Comment by ColinCollins** [comment]
看了一下，现在不支持本地的自定义字体，官网上最好的答案是 必须要求 自定义字体是存放在网上的，并且允许跨域操作。

**Comment by jareguo** [comment]
不是吧？这是为什么呀

**Comment by pandamicro** [comment]
@CocosAss 分别验证一下本地和远程的是不是可以通过 wx.loadFont 来加载

**Comment by xmsz** [comment]
微信现在可以了 但是qq不行

**Comment by jareguo** [comment]
那不是引擎能解决的，何况我们也不提供 QQ 小游戏平台适配

**Comment by xmsz** [comment]
为啥，qq和微信基本上是一样，也可以直接使用wx.apiName。 所以理论上兼容qq倒是非常容易。api相同，兼容应该很方便。

那有什么办法可以手动绑定吗？

例如我用wx.loadFont。然后下一步该怎么做
