### ISSUE TITLE
Inconsistent sprite position depending on different uses of cc.loader.loadRes

### ISSUE THREAD

**Issue by maximtsai** [cocos/cocos-engine#2458]
Problem: In-game images appear different depending on whether cc.loader.loadRes(url, type, callback) was used or cc.loader.loadRes(url, callback) where we don't specify the type.

Creator version?（版本号）
v1.7.2

### Affected platform?（受影响的平台）
Tested and confirmed to happen on Simulator, Windows and Maac

### How to reproduce?（如何重现）
Load then create an image with cc.loader.loadRes(url, type, callback) then load and create the same image but using cc.loader.loadRes(url, type, callback). The two images will have different heights and also appear in different locations if the original image has empty space.

![image](https://user-images.githubusercontent.com/6758316/37690811-bec4bf82-2c6a-11e8-8b1e-80032491fa13.png)

Expected behavior is that the two images will have the same width/heights and will appear in the same location.

Sprite used:
![image](https://user-images.githubusercontent.com/6758316/37691038-50b66020-2c6c-11e8-8ae7-2bb39d756461.png)

Code used to generate those two half circles:
```
    start () {
        this.url = 'textures/halfcircle';
        this.loadLeftCircle();
        this.loadRightCircle();
    },

    // load circle at left using cc.loader.loadRes(url, type, callback)
    loadLeftCircle: function () {
        let type = cc.SpriteFrame;
        cc.loader.loadRes(this.url, type, (err, spriteData) => {
            let newNode = new cc.Node();
            let spriteComponent = newNode.addComponent(cc.Sprite);
            this.node.addChild(newNode);
            newNode.x = -100;
            newNode.y = 0;
            spriteComponent.spriteFrame = spriteData;
            console.log(newNode);
        });
    },

    // load circle at right using cc.loader.loadRes(url, callback)
    loadRightCircle: function () {
        cc.loader.loadRes(this.url, (err, spriteData) => {
            let newNode = new cc.Node();
            let spriteComponent = newNode.addComponent(cc.Sprite);
            this.node.addChild(newNode);
            newNode.x = 100;
            newNode.y = 0;
            spriteComponent.spriteFrame = new cc.SpriteFrame(spriteData);
            console.log(newNode);
        });
    },

```
### JavaScript output or error produced?（报错信息和调用栈）
No error

**Comment by jareguo** [comment]
When you load the left circle, you got a cc.SpriteFrame. But when you load the right circle, you got a cc.Texture2D, not spriteData. You should always specify the type if you have a same named texture.
