### ISSUE TITLE
scrollview err 3804

### ISSUE THREAD

**Issue by acvrp-lab** [cocos/cocos-engine#2471]
### Creator version?（版本号）
1.9

### Affected platform?（受影响的平台）
all?

### How to reproduce?（如何重现）
any scrollview while your project doesnt include Layout module

### JavaScript output or error produced?（报错信息和调用栈）
cocos2d-js-min.js:1 Error 3804, please go to https://github.com/cocos-creator/engine/blob/master/EngineErrorMap.md#3804 to see details.
that is, getComponent: Type must be non-nil

(anonymous) | @ | cocos2d-js-min.js:1
-- | -- | --
  | n | @ | cocos2d-js-min.js:1
  | getComponent | @ | cocos2d-js-min.js:1
  | _calculateBoundary | @ | cocos2d-js-min.js:1
  | 82.n.invoke | @ | cocos2d-js-min.js:1
  | 83.c.emit | @ | cocos2d-js-min.js:1
  | set | @ | cocos2d-js-min.js:1

so i checked scrollview.js _calculateBoundary()
line885 :  var layout = this.content.getComponent(cc.Layout);
and a template scrollview created by creator doesnt have Layout component on any of its nodes

**Comment by jareguo** [comment]
Fixed, thanks!
