### ISSUE TITLE
negative time cause action to freeze

### ISSUE THREAD

**Issue by acvrp-lab** [cocos/cocos-engine#2478]
### Creator version?（版本号）
1.9

### Affected platform?（受影响的平台）
web

### How to reproduce?（如何重现）
并不是故意写了一个负的时间，
某个moveby根据移动距离来计算用时，偶尔距离为0时会卡住
打印了一下时间是负的e-17。。 
因为都是向下移动所以距离没有取绝对值

**Comment by zhefengzhang** [comment]
请问怎么测试这个问题？

**Comment by zhefengzhang** [comment]
用户长时间没有回复，issues 暂时关闭。
