### ISSUE TITLE
引擎1.8.1 android8.0 editbox 输入行数串行

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#2488]
版本是1.8.1
android 8.0上遇到的这个问题，editbox 输入行数串行，求解决

遇到问题的机器是 小米6和小米max2 都是android8.0系统

**Comment by jareguo** [comment]
什么叫串行？能截个图吗？

**Comment by GameKeys** [comment]
我在论坛提了，你们有贴图  http://forum.cocos.com/t/1-8-1-android8-0-editbox/58174

**Comment by GameKeys** [comment]
求解决？

**Comment by knoxHuang** [comment]
抱歉，怎么久才回复，能否给一下有问题的 demo 呢？
QA 用官方范例的 editbox 测试没复现

**Comment by GameKeys** [comment]
android 低版本没有发现，小米6,android8.0系统就有这个问题，
输入框不需小于屏幕的一半就会出现这个问题

图片是输入前和输入后的内容？
![9953efc3-0e96-46d1-9700-d9f57f62ffdf](https://user-images.githubusercontent.com/6950818/39621483-840733a0-4fc1-11e8-9603-3353274e0daa.png)

**Comment by GameKeys** [comment]
这个是你们的案例，我在小米6上运行是这样显示的看下面的图，求解决？

![ac16d1fd-334e-433b-9bc4-8a6d36ee0f09](https://user-images.githubusercontent.com/6950818/39622386-9ac70c48-4fc4-11e8-892f-4d3a64ed6966.png)
![b38b6ed4-6e87-4454-bb74-2a856a42ffc1](https://user-images.githubusercontent.com/6950818/39622388-9b169eac-4fc4-11e8-85de-1cc82fe2ac41.png)
![dad99a08-bc15-4997-9e0f-59873e5b70b9](https://user-images.githubusercontent.com/6950818/39622389-9b64e44a-4fc4-11e8-8093-38aaf1af4f03.png)

**Comment by knoxHuang** [comment]
@heyanfei QA 组有空验证一下，谢谢

**Comment by knoxHuang** [comment]
@umbrellaPP 有空的话在 2.0 验证一下

**Comment by PPpro** [comment]
好的

**Comment by PPpro** [comment]
2.0 上验证没这类问题，问题可以关闭
