### ISSUE TITLE
1.8.2  android 7 下会闪退

### ISSUE THREAD

**Issue by chenpangzi** [cocos/cocos-engine#2489]
必现
测试了两台手机 小米5s和华为mate8都会闪退，看逻辑应该是加载某一个场景的时候闪退。并不是一进游戏就闪退的

### Creator version?（版本号）
1.8.2

### Affected platform?（受影响的平台）
android   两台有问题的都是android7

### How to reproduce?（如何重现）
暂时不清楚

### JavaScript output or error produced?（报错信息和调用栈）
04-01 22:39:59.448  1541  1620 I ActivityManager: Displayed packageName/org.cocos2dx.javascript.AppActivity: +3s255ms
04-01 22:39:59.449  1541  1620 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{fe15f12 u0 packageName/org.cocos2dx.javascript.AppActivity t7660} time:64924984

04-01 22:40:07.740 32267 32267 F DEBUG   :     #00 pc 00f628ac  /data/app/packageName-1/lib/arm/libcocos2djs.so (_ZN7cocos2d16FileUtilsAndroid11getContentsERKSsPNS_15ResizableBufferE+475)
04-01 22:40:07.740 32267 32267 F DEBUG   :     #01 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.740 32267 32267 F DEBUG   :     #02 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.740 32267 32267 F DEBUG   :     #03 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.740 32267 32267 F DEBUG   :     #04 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.740 32267 32267 F DEBUG   :     #05 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.740 32267 32267 F DEBUG   :     #06 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.740 32267 32267 F DEBUG   :     #07 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.741 32267 32267 F DEBUG   :     #08 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.741 32267 32267 F DEBUG   :     #09 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.741 32267 32267 F DEBUG   :     #10 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.741 32267 32267 F DEBUG   :     #11 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.742 32267 32267 F DEBUG   :     #12 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.742 32267 32267 F DEBUG   :     #13 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.742 32267 32267 F DEBUG   :     #14 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.742 32267 32267 F DEBUG   :     #15 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.743 32267 32267 F DEBUG   :     #16 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.743 32267 32267 F DEBUG   :     #17 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.743 32267 32267 F DEBUG   :     #18 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.743 32267 32267 F DEBUG   :     #19 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.743 32267 32267 F DEBUG   :     #20 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.743 32267 32267 F DEBUG   :     #21 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.744 32267 32267 F DEBUG   :     #22 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.744 32267 32267 F DEBUG   :     #23 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.744 32267 32267 F DEBUG   :     #24 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.744 32267 32267 F DEBUG   :     #25 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.744 32267 32267 F DEBUG   :     #26 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.745 32267 32267 F DEBUG   :     #27 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.745 32267 32267 F DEBUG   :     #28 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.745 32267 32267 F DEBUG   :     #29 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.746 32267 32267 F DEBUG   :     #30 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.746 32267 32267 F DEBUG   :     #31 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.747 32267 32267 F DEBUG   :     #32 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.747 32267 32267 F DEBUG   :     #33 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.747 32267 32267 F DEBUG   :     #34 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.747 32267 32267 F DEBUG   :     #35 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.747 32267 32267 F DEBUG   :     #36 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.747 32267 32267 F DEBUG   :     #37 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.748 32267 32267 F DEBUG   :     #38 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.748 32267 32267 F DEBUG   :     #39 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.748 32267 32267 F DEBUG   :     #40 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.748 32267 32267 F DEBUG   :     #41 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.748 32267 32267 F DEBUG   :     #42 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.748 32267 32267 F DEBUG   :     #43 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.748 32267 32267 F DEBUG   :     #44 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.749 32267 32267 F DEBUG   :     #45 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.749 32267 32267 F DEBUG   :     #46 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.749 32267 32267 F DEBUG   :     #47 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.749 32267 32267 F DEBUG   :     #48 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.749 32267 32267 F DEBUG   :     #49 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.749 32267 32267 F DEBUG   :     #50 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.749 32267 32267 F DEBUG   :     #51 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.750 32267 32267 F DEBUG   :     #52 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.750 32267 32267 F DEBUG   :     #53 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.750 32267 32267 F DEBUG   :     #54 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.750 32267 32267 F DEBUG   :     #55 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #56 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #57 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #58 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #59 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #60 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #61 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #62 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:07.751 32267 32267 F DEBUG   :     #63 pc 00f628e9  /data/app/packageName-1/lib/arm/libcocos2djs.so (bsd_signal+60)
04-01 22:40:08.763  1541 32283 W ActivityManager:   Force finishing activity packageName/org.cocos2dx.javascript.AppActivity
04-01 22:40:08.826  1541  2044 I WindowManager: WIN DEATH: Window{11c452f u0 packageName/org.cocos2dx.javascript.AppActivity}
04-01 22:40:08.826  1541  2044 W WindowManager: Force-removing child win Window{c3e5fbe u0 SurfaceView - packageName/org.cocos2dx.javascript.AppActivity} from container Window{11c452f u0 packageName/org.cocos2dx.javascript.AppActivity}
04-01 22:40:08.827  1541  2044 I WindowManager: Destroying surface Surface(name=SurfaceView - packageName/org.cocos2dx.javascript.AppActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2043 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:895 com.android.server.wm.WindowState.removeLocked:1467 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2607 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2586 com.android.server.wm.WindowManagerService.removeWindowLocked:2565 com.android.server.wm.WindowState$DeathRecipient.binderDied:1798 android.os.BinderProxy.sendDeathNotice:697
04-01 22:40:08.837  1541  2044 I WindowManager: Destroying surface Surface(name=packageName/org.cocos2dx.javascript.AppActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2043 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:895 com.android.server.wm.WindowState.removeLocked:1467 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2607 com.android.server.wm.WindowManagerService.removeWindowLocked:2565 com.android.server.wm.WindowState$DeathRecipient.binderDied:1798 android.os.BinderProxy.sendDeathNotice:697 <bottom of call stack>

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
