### ISSUE TITLE
能把cocos creator开源吗?

### ISSUE THREAD

**Issue by acrazing** [cocos/cocos-engine#2490]
RT. 用creator, 感觉好多东西都变成了黑盒, 并且有些觉得不合理的地方想改都改不了.
比如 main.js, 如果自定义模板, 现在必须在各个模板目录下面放一个同样的文件(以及shares里面的其它文件), 如果想改这个文件的话, 就得把所有模板目录下面的内容都改了. 并且这个模板应该是用了ejs之类的工具来编译, 不是一个标准的js文件, 如果我想修改, 都没有办法去弄.

**Comment by jareguo** [comment]
谢谢反馈，我们将来会尽量开源的！

**Comment by caijincheng** [comment]
命令行打包工具有开源?

/Applications/CocosCreator.app/Contents/MacOS/CocosCreator --path projectPath
--build "platform=android;debug=true"
