### ISSUE TITLE
SkeletonAnimation would read json file again after its skeletonData did in JSB

### ISSUE THREAD

**Issue by qingwabote** [cocos/cocos-engine#2491]
cocos creator 1.8 & jsb:
We use cc.loader to load SkeletonData, json file would be read during this time.
But then, _SGSkeletonAnimation's constructor would read the json file again at Skeleton._createSgNode.
So the file would be read twice in JSB.

**Comment by jareguo** [comment]
Yes, this is a problem. We fixed it in 2.0, thanks for the reply.
