### ISSUE TITLE
有支持 Label Shadow的打算么?

### ISSUE THREAD

**Issue by acrazing** [cocos/cocos-engine#2492]
我才发现现在的Label是没有Shadow的, 只有个Outline, 但是这个不够用啊. 而原本的cocos2d是支持的, creator为啥把它去掉了?

**Comment by jareguo** [comment]
Creator 是一个新的引擎，没有去掉什么功能，只是没完整实现 -x 的所有功能而已。这个需求 2.1 之后会考虑支持的。

**Comment by RannarYang** [comment]
你好，请问下现在还有支持 Label Shadow的打算么

**Comment by caryliu1999** [comment]
> 你好，请问下现在还有支持 Label Shadow的打算么

2.1.1 版本已经支持了，论坛已发布Beta版本。
