### ISSUE TITLE
需求: Editbox添加Margin选项

### ISSUE THREAD

**Issue by acrazing** [cocos/cocos-engine#2505]
即输入框的文字相对于背景图片/颜色在水平方向的偏移, 因为很多情况下背景图片都是带部分区域不放文字的.
我看了下js的代码, 还可以改, 但是c++的代码实现太复杂, 我没windows/mac上的开发经验, 没这技术.

**Comment by jareguo** [comment]
@knoxHuang 请评估下这个需求好不好做，需不需要做，以什么形式做？

**Comment by PPpro** [comment]
同步 EditBox 的样式需要很大工作量，不同平台实现方式不同
这个需求比较少，现阶段建议可以通过组合 UI 组件的形式去实现需求
![新建项目](https://user-images.githubusercontent.com/17872773/67539513-fbf42980-f714-11e9-8d68-e29180c0d6d2.png)
```
// 伪代码
 btn.onClick(() => {
   editBox.beginEditing();
});
```
