### ISSUE TITLE
Branch Next compiled，I got error ：cc is not defined.

### ISSUE THREAD

**Issue by mooooooi** [cocos/cocos-engine#2508]
### Creator version?（版本号）
2.0 alpha 5

### Affected platform?（受影响的平台）

估计都有
### How to reproduce?（如何重现）
想提前使用 2.0版本，根据了README操作且没有报错

**Comment by Marssssssss** [comment]
您好，谢谢反馈。目前版本已经更新到 v2.1.2 ，可以直接使用最新版本的编辑器~
