### ISSUE TITLE
无网络时 socketio 导致 app crash

### ISSUE THREAD

**Issue by h87kg** [cocos/cocos-engine#2516]
E/URLConnection exception( 4034): java.net.UnknownHostException: Unable to resolve host "test.xx": No address associated with hostname
E/URLConnection exception( 4034): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
E/URLConnection exception( 4034): java.net.UnknownHostException: Unable to resolve host "test.xx": No address associated with hostname

无网络的时候，socketio url是域名，app 会 crash

**Comment by zhefengzhang** [comment]
请问怎么复现这个问题？

**Comment by zhefengzhang** [comment]
用户长时间没有回复，暂时关闭。
