### ISSUE TITLE
webgl模式下canvas无法透明，cc.macro.ENABLE_TRANSPARENT_CANVAS 无效

### ISSUE THREAD

**Issue by inuheaven** [cocos/cocos-engine#2523]
### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）

Web webgl模式

### How to reproduce?（如何重现）
必现。直接修改 
cc.macro.ENABLE_TRANSPARENT_CANVAS = 1; 
 
cc.rendererCanvas._clearColor = cc.color(0,0,0,0);
cc.rendererCanvas._clearFillStyle = "rgb(0,0,0,0)";

cc.rendererWebGL._clearColor = cc.color(0,0,0,0);
cc.director.setClearColor = cc.color(0,0,0,0);

canvas渲染模式下可以透明  webgl模式下不能透明

**Comment by zhefengzhang** [comment]
这个问题在 2.x 和 3.x 版本已经修复。
