### ISSUE TITLE
creator 1.8.1 苹果 提审被拒 4.3问题 就解决

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#2546]
Guideline 4.3 - Design
This app duplicates the content and functionality of other apps submitted by you or another developer to the App Store, which is considered a form of spam.

Apps that simply duplicate content or functionality create clutter, diminish the overall experience for the end user, and reduce the ability of developers to market their apps.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Design section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program. 
- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

**Comment by jareguo** [comment]
这个是你的应用被识别为马甲包了。这个应该你们想办法去优化才对，可以尝试淘宝找找有没有第三方提供的变脸服务。
