### ISSUE TITLE
微信小游戏音效BUG？

### ISSUE THREAD

**Issue by HuMoran** [cocos/cocos-engine#2548]
### Affected platform：huawei mate 10 微信小游戏
我们的游戏分为背景音乐和其他玩家操作音效。
背景音乐先调用```cc.loader.loadRes```获取音频url，然后在调用微信小游戏的api接口播放
```
const bgm = wx.createInnerAudioContext()
bgm.autoplay = true
bgm.loop = true
bgm.src = url
```
玩家操作音效直接用的```cc.audioEngine.play```播放，发现调用```cc.audioEngine.play```会改变前面的```bgm.src ```，在其他机型（包括IOS、Android）上面，虽然改变了```bgm.src ```，但是音效能正常播放，在```huawei mate 10```上面，音效就会混乱，玩家的本次操作，播放的不是本次操作的音效，而是上一轮的音效。
另外能不能提供一下cocos的```weapp-adapter```源码地址？

**Comment by jareguo** [comment]
应该是 adapter 的问题，https://github.com/cocos-creator-packages/weapp-adapter
过几天就会发布 1.9.1 到时你可以试试

**Comment by HuMoran** [comment]
测试了应该是wx音乐播放有bug，建的空项目，只用wx播放声音，如果关了上一个声音马上播放下一个声音资源，就会出现bug

**Comment by jareguo** [comment]
也可以试试 1.9.1
win：http://cocos2d-x.org/filedown/CocosCreator_v1.9.1_win
mac：http://cocos2d-x.org/filedown/CocosCreator_v1.9.1_mac
