### ISSUE TITLE
web-mobile版是否支持webgl的条件判断在UC浏览器上不成立！

### ISSUE THREAD

**Issue by nathanielalexislo** [cocos/cocos-engine#2592]
https://github.com/cocos-creator/engine/blob/0cbdd1119d7457aadf9b9ccb733660face778652/cocos2d/core/platform/CCSys.js#L902

issue(1)# Browsers may NOT expose the '**WebGLRenderingContext**' interface to the DOM scripting API, so this judgement should NOT be a necessary but a sufficient .

https://github.com/cocos-creator/engine/blob/0cbdd1119d7457aadf9b9ccb733660face778652/cocos2d/core/platform/CCSys.js#L934

issur(2)# Missing a '**break**' in the case of '**sys.BROWSER_TYPE_UC**' .

**Comment by jareguo** [comment]
麻烦 @ColinCollins  参考这个帖子 http://forum.cocos.com/t/h5-uc-webgl/60121?u=jare 进行完善，在 next 分支上修改。

**Comment by nathanielalexislo** [comment]
if (win.WebGLRenderingContext) {
这个也应该要改一下。
用mdn推荐的方式。不然也有问题。
function detectWebGLContext () {
// Create canvas element. The canvas is not added to the
// document itself, so it is never displayed in the
// browser window.
var canvas = document.createElement("canvas");
// Get WebGLRenderingContext from canvas element.
var gl = canvas.getContext("webgl")
|| canvas.getContext("experimental-webgl");
// Report the result.
if (gl && gl instanceof WebGLRenderingContext) {
return true;
} else {
return false;
}
}
