### ISSUE TITLE
MotionStreak 拖影位置错误，当节点 rotation 发生改变。

### ISSUE THREAD

**Issue by gz65555** [cocos/cocos-engine#2604]
使用MotionStreak时，当物体的rotation发生改变时， 拖影位置会出现错误。

### Creator version?（版本号）
1.9.0

### How to reproduce?（如何重现）
使用MotionStreak范例中，改变MotionStreak的rotation值即可重现。

**Comment by jareguo** [comment]
请 @ColinCollins 验证一下这个问题

**Comment by ColinCollins** [comment]
确认过了，emmm，MotionStreak 没有进行正确的对应的旋转。。。

**Comment by gz65555** [comment]
请问一下大概是什么时候能解决😂

**Comment by ColinCollins** [comment]
额。。。最快这个下午咯，但是就算我解决了也得是下个版本才更新哇。。。。

**Comment by jareguo** [comment]
这个问题在 2.0 已经修复啦，由于改动太大，1.x 不会再同步这个修改啦。这边其实没有太大关系，只要旋转的是 Motion Streak 的子节点，也就是那个 gold，就没关系啦！
