### ISSUE TITLE
cocos creator 1.9.1发布微信小游戏子域的问题

### ISSUE THREAD

**Issue by caochao** [cocos/cocos-engine#2609]
cocos creator 1.9.1发布微信小游戏， 构建发布栏输入subdomain

这将会在wechatgame包game.json中写入一条"subContext":"subdomain"，这时我把子域代码目录放到wechatgame包中对应目录。微信开发者工具会提示找不到sub.js。

然而，微信文档关系链 [关系链数据使用指南](https://developers.weixin.qq.com/minigame/dev/tutorial/open-ability/open-data.html) 中提到添加到game.json中的应该是openDataContext

**Comment by caochao** [comment]
我这里的子域代码没用cocos creator 1.9.1发布的子域工程，而是按照官方文档手写的js

**Comment by limichange** [comment]
我用发布的子域工程的功能，倒是正常的。你可以发布一下看看，有什么区别。

**Comment by jareguo** [comment]
官方文档也说了要发布为子域工程喔

**Comment by caochao** [comment]
@limichange 区别就是如果用creator发布子域工程到主域wechatgame包，要包含sub.js。但如果我按官方文档用openDataContext，就要要求子域目录包含index.js

**Comment by jareguo** [comment]
麻烦 @knoxHuang 跟进下这个问题，微信似乎调整了 game.json 中的子域字段。新旧字段加载的 js 不是同一个。如果统一用 openDataContext 是否又会有旧版 SDK 不兼容的问题？

**Comment by limichange** [comment]
确实是改了
```
{
  "deviceOrientation": "portrait",
  "openDataContext": "src/myOpenDataContext"
}
```

**Comment by knoxHuang** [comment]
如果是用来 subContext 字段的话，就需要 sub.js，反之使用了 openDataContext 的话就需要 index.js，目前 creator 使用的是 subContext 所以如果要自己写的代码，需要把入口脚本命名为 sub.js

**Comment by jareguo** [comment]
@knoxHuang  最好还是改用微信文档里最新的写法吧

**Comment by limichange** [comment]
微信这个肯定做兼容了，最好按最新的来，不然之后哪个版本微信可能就废弃了。

**Comment by knoxHuang** [comment]
嗯，会改为最新的 openDataContext 来

**Comment by Voyager2718** [comment]
想问一下我在我的主域里面的 `start()` 写了
```
let openDataContext = wx.getOpenDataContext()
    openDataContext.postMessage({
    text: 'WTF',
})
```
同时在主域的
```
properties: {
            display: cc.Sprite
}
```
放入了一个单色的 Sprite 节点。

在子域写了
```
cc.Class({
    extends: cc.Component,

    properties: {
        display: cc.Node
    },

    start() {
        wx.onMessage(function (data) {
            console.log("HERE WTF");
            console.log(data);
        });
    },
});
```

想问一下为什么启动的时候子域没有任何 log 输出呢？
——————————
还有为什么我下载了[官方教程项目文件](https://github.com/cocos-creator/creator-docs/blob/master/en/publish/publish-wechatgame-sub-domain.md)看，里面无论是主域还是子域都没有把 launch.js 添加到 Canvas 节点里面去。这是正常的吗？

**Comment by limichange** [comment]
应该是
```
wx.postMessage()
```

> 你应该发在论坛，这和引擎没有任何关系

**Comment by Voyager2718** [comment]
主域是 `postMessage()`，子域是 `onMessage()` 应该没错阿。
