### ISSUE TITLE
ios运行小游戏时拖出控制中心导致报错

### ISSUE THREAD

**Issue by Holajulie** [cocos/cocos-engine#2615]
### Creator version?（版本号）
v1.8.0

### Affected platform?（受影响的平台）

ios
### How to reproduce?（如何重现）
麻将游戏过程中，拖出控制中心（就是调音量、亮度等的那个组件），如果在控制中心显示时收到socket消息触发动画，动画被封装成了promise，关闭控制中心后，动画显示但是控制台报错并且catch不到异常，wx.onError也监听不到错误。当控制台被拖出时，只有一个动画的时候偶尔不会报错，报错时程序能接着往下运行，多个动画相继被触发时，报错且程序运行不下去了。主要是拖出控制中心无法监听到，没办法找到对应措施。找不到具体哪里报的错，偶尔可以接着运行，偶尔不行，偶尔又不报错，catch不到。
不知道开发人员在一些demo中有没有遇见过类似情况。

### JavaScript output or error produced?（报错信息和调用栈）

UNhandle promise rejection
Object {"line": 24836, "column": 42}

**Comment by jareguo** [comment]
抱歉我们也不太清楚，这不是上层引擎能控制的，麻烦咨询下微信官方技术支持，或者在论坛里问一下吧。
