### ISSUE TITLE
关于引擎性能的问题

### ISSUE THREAD

**Issue by limichange** [cocos/cocos-engine#2624]
### 问题
目前在做一个跑酷游戏时发现一个问题，游戏本身元素很少，但运动的时候有明显的卡顿。在微信小程序（iPhone6）上卡顿明显。

### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）
微信小程序

### How to reproduce?（如何重现）
相关链接里有项目代码

### Demo project?（demo 项目）
https://github.com/cocos-laboratory/Parkour
http://forum.cocos.com/t/topic/58805/32

**Comment by limichange** [comment]
可以提供更加详尽的源代码

**Comment by jareguo** [comment]
性能会在 2.0 有很大幅度提升，1.x 系列已经不再重复进行帧率方面的优化了。请关注我们后续的发布情况，预计 5 月就会有 Preview 版本。

**Comment by limichange** [comment]
🤣 现在已经5月了
