### ISSUE TITLE
cc.game.EVENT_HIDE | cc.game.EVENT_SHOW 问题

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#2632]
### How to reproduce?（如何重现）
切换前后头都没有问题，但在游戏中微信分享，游戏暂停后没有几秒就切入前台了，很诡异，求解决？

### JavaScript output or error produced?（报错信息和调用栈）

下面调用日子输出
cc.game.EVENT_HIDE ...切入后台
cc.game.EVENT_SHOW ...切回来 | ....切入前台

![6a794c9f-718f-44ec-802b-87813d9996bb](https://user-images.githubusercontent.com/6950818/39621343-0239a7c2-4fc1-11e8-9e80-fc52467419f3.png)

**Comment by zhefengzhang** [comment]
没看出来哪里有问题。能否再用 2.4.4 版本测试看看？
