### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#2671]
Hi,

A month or two back Cocos Creator roadmap disappeared completely. It was a very pleasant way to see in what way Cocos Creator is heading and what features or fixes you could expect to see soon. I still see the link in the readme.md file in this project: [Road Map](https://trello.com/b/JWVRRxMG/cocos-creator-roadmap).

I tried to ask on the forums about it, but got no response. [(The forum thread)](https://discuss.cocos2d-x.org/t/cocos-creator-roadmap-trello/33692/19)

Do you have any plans of releasing any roadmap for the community to see?

Thanks for everything! 🙂

**Comment by jareguo** [comment]
Sorry, we hide the roadmap because it's out of date. We don't have any new roadmap at this moment. We will publish a new roadmap after we adjusted human resources. (We will have an independent product group to take charge of CocosCreator development.)
