### ISSUE TITLE
所有asset/Script下的ts文件都会被打包?

### ISSUE THREAD

**Issue by acrazing** [cocos/cocos-engine#2673]
我新建了一个空文件, 写了一行代码:

```ts
console.error("This file is useless, should not be packed!");
```

结果构建发布后, 这个文件被打包进来了:

![image](https://user-images.githubusercontent.com/10029810/39956667-c606953c-5617-11e8-9610-b326cf15bfa0.png)

能做到只把打包的Scene以及resources里面的prefab依赖的ts/js打包进来么? 这样可以把单元测试的文件直接放asset/Script里面, 并且减少不必要的依赖引入.

**Comment by jareguo** [comment]
目前需要手动声明。在脚本里使用 if (CC_EDITOR) { ... } 保住所有代码，这样发布后这些代码会被剔除。之后开放脚本构建的代码后就可以让用户自定义。

**Comment by acrazing** [comment]
唉, 感觉好多功能现在都没接口呢, 可控程度太低了.

我觉得可以考虑下用`jsx`去构建节点树
