### ISSUE TITLE
[1.9.1]微信开发者工具ES6转换ES5项在不同Android手机上报错

### ISSUE THREAD

**Issue by jareguo** [cocos/cocos-engine#2674]
@Ywenwen9 commented on [Wed Apr 18 2018](https://github.com/cocos-creator/fireball/issues/7176)

1.打开example工程，选择微信平台，构建，在微信开发者平台上运行后，勾选“ES6 转 ES5”，勾选“不校验安全域名，TLS 版本以及 HTTPS 证书”——>使用小米4微信进入小程序有报错
2.打开子域工程，选择微信平台，构建，在微信开发者平台上运行后，不勾选“ES6 转 ES5””——>使用Oppo A37微信进入小程序有报错
（注：在其他helloworld，空白工程上不会出现以上问题）
![log](https://user-images.githubusercontent.com/30791406/38923576-7e78273c-432d-11e8-8d69-b23f9fabb430.png)

---

@jareguo commented on [Wed Apr 18 2018](https://github.com/cocos-creator/fireball/issues/7176#issuecomment-382333075)

是因为子域工程引起的吗？子域工程有在子域中运行吗？

---

@heyanfei commented on [Wed Apr 18 2018](https://github.com/cocos-creator/fireball/issues/7176#issuecomment-382334123)

example工程也会出现报错

**Comment by ColinCollins** [comment]
1. example-case 中调用的 socketio.js 文件引用 webSocket 对象在 es6 转 es5 的时候会在微信开发工具上丢失，因此问题一在 example-case 中远程服务器重现的方式似乎是不成立的。
![image](https://user-images.githubusercontent.com/35832931/40041607-31e0fdb6-5851-11e8-94bc-573785c0d1bf.png)
2. 问题二的内容没有重现出来..很有可能是微信那边自己更新了..
微信开发平台 : 1.02
cocosCreator : 1.9.1
手机: 小米note 4
微信: 6.6.5

**Comment by Ywenwen9** [comment]
与家辉沟通了一下：
问题一，意思要处理成直接跳过报错；
问题二，尝试复现，我这也没出现报错了。
