### ISSUE TITLE
cocos creator 不同路径下场景切换

### ISSUE THREAD

**Issue by zhaoqinghai** [cocos/cocos-engine#2715]
当我使用loadscene时 我通过文件名去引用时 是无法找到那个场景的 当我用db://assets/path/filename时也是行不通的 我应该怎么使用loadscenen呢

**Comment by zhaoqinghai** [comment]
全局路径我是参考官方的例子合集 好像就是通过url来进行场景跳转

**Comment by jareguo** [comment]
？？？

**Comment by zhaoqinghai** [comment]
不好意思 其实是我早上弄错了 导致的问题 其实是没问题的

**Comment by jareguo** [comment]
好滴
