### ISSUE TITLE
节点的 localZOrder 被修改了的时候，无法修改节点顺序

### ISSUE THREAD

**Issue by VisualSJ** [cocos/cocos-engine#2723]
场景内的节点的 _localZOrder 如果被修改，无论怎么修改，都会被 sortAllChildren 方法重置回原来的顺序。

**Comment by jareguo** [comment]
怎么可能会被重置呢

**Comment by VisualSJ** [comment]
照理来说不应该被修改的额。
查看了下，scene 数据从 assetLibrary 读取出来的时候，节点的 zIndex 就已经被修改了。

先关闭 issue 吧，问题应该是找到哪里修改了这个 zIndex。
