### ISSUE TITLE
Fixture对象销毁导致的异常

### ISSUE THREAD

**Issue by zqxiaojin** [cocos/cocos-engine#2726]
### Creator version?（版本号）
1.7.1

### Affected platform?（受影响的平台）

iOS

### How to reproduce?（如何重现）
构造物理碰撞小球，触发jsc的 GC

### JavaScript output or error produced?（报错信息和调用栈）

详情见 http://forum.cocos.com/t/undefined-is-not-an-object-evaluating-colliderb-body/60184/12?u=lucky_06

问题有2个：
一是 _disableChildComps 这个函数，在删除component的时候，body有可能比其对应的 Collider 更早被destroy，这就导致Collider 在destroy的时候，没法获取到body对象从而执行 DestroyFixture，导致部分Fixture对象泄露。

二是 当Fixture能稳定Destroy的时候，由于其关联的对象使用了对象池。导致 jsbinding 被误消除。

### Demo project?（demo 项目）

没有demo

**Comment by zqxiaojin** [comment]
该patch可以修正  Collider 在 destroy时，其body已经被先销毁的问题

**Comment by zqxiaojin** [comment]
#2727  该pull request 修正了上面的问题一

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos-creator/cocos2d-x-lite/pull/1264
