### ISSUE TITLE
TouchMove在没有移动情况下会回调

### ISSUE THREAD

**Issue by mooooooi** [cocos/cocos-engine#2739]
### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）

仅测试了Simulator Web
### How to reproduce?（如何重现）
1.创建HelloWorld工程,
2.onLoad(){
      this.node.on('touchmove',function(event){
              cc.log(event.getDelta())
      }
}
3.运行，点击一下屏幕（不移动），会打印出cc.Vec2 ({ x: 0 , y: 0})

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，这个问题在 v2.1.2 已经修复了。
