### ISSUE TITLE
微信小游戏(主域+子域)开发遇到问题

### ISSUE THREAD

**Issue by tdouguo** [cocos/cocos-engine#2740]
### Creator version?（版本号）
Cocos Creator v1.9.1

### Affected platform?（受影响的平台）

Android 华为
- STF-AL10,安卓版本 8.0
- MT7-TL00C01B571 安卓版本 6.0

### How to reproduce?（如何重现）
通过好友分享的链接进入微信小游戏 子域项目 
使用Cocos默认字体 在微信子域中 获取好友排行榜数据之后 绘制lable 赋值

**Comment by tdouguo** [comment]
![huawei1](https://user-images.githubusercontent.com/22972345/40533638-faa885fc-6035-11e8-8824-35c6b26b8b13.jpg)
![huaweirongyao9](https://user-images.githubusercontent.com/22972345/40533640-fb07e150-6035-11e8-9cc6-6ca68de64cd9.jpg)
![Uploading system_huaweirongyao9.jpg…]()
![Uploading systemhuawei1.png…]()

**Comment by pandamicro** [comment]
微信 6.6.7 会彻底修复这个问题

**Comment by gjmvvv** [comment]
微信 6.6.7 什么时候 更新 知道么
