### ISSUE TITLE
关于声音的暂停恢复功能(急！！！ 急 ！！！ 急！！！) 跪谢

### ISSUE THREAD

**Issue by tdouguo** [cocos/cocos-engine#2745]
### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）

微信小游戏
### How to reproduce?（如何重现）
CCAudioSource
模块中  背景声音 循环播放 然后调用 pause 成功暂停  恢复调用resume 第一次恢复不成功
调用暂停 调用恢复 这之后就OK了  然后 停止
在播放 之后暂停恢复都OK  
继续测试之后发现在微信小游戏中  
CCAudioSource.mute 无作用
CCAudioSource.volume 无作用
CCAudioSource.resume 第一次恢复时候调用2次就OJ  以后都正常
[NewProject.zip](https://github.com/cocos-creator/engine/files/2044539/NewProject.zip)

**Comment by tdouguo** [comment]
微信：vvvgjm

**Comment by PPpro** [comment]
resume问题可以参考这个pr
https://github.com/cocos-creator/engine/commit/9029fe04470d229b0950b2e60df377a0d1aa6d8b
