### ISSUE TITLE
构建发布时的第三方库会报错

### ISSUE THREAD

**Issue by gz65555** [cocos/cocos-engine#2746]
在构建发布时，若使用了browserify打包的第三方库会提示报错

```shell
Build Failed: Compile error: Cannot require '$module' from 'file'. Module not found
```

但在开发环境下并没有问题。

可能是构建时代码检查无法识别browserify打包js库的方式，若很难修改构建发布的代码检查方式，是否可以提供忽略错误强行发布的功能？

### Creator version?（版本号）

1.9.1

### Affected platform?（受影响的平台）

All

### How to reproduce?（如何重现）

使用browserify打包后的单个js文件，再构建发布项目时出现

**Comment by jareguo** [comment]
请使用插件脚本来引入第三方库 http://docs.cocos.com/creator/manual/zh/scripting/plugin-scripts.html
