### ISSUE TITLE
Operations column does not do anything. There should be an option to select an action to perform on a record, such as reduce image quality

### ISSUE THREAD

**Issue by frenb** [cocos/cocos-engine#2778]
### Creator version?（版本号）
1.11-alpha.4

### Affected platform?（受影响的平台）

Mac editor
### How to reproduce?（如何重现）
There is no option to select an operation.

**Comment by frenb** [comment]
Please associate with Google Play Instant milestone. I don't have the option to assign it to a milestone.

**Comment by wuzhiming** [comment]
@frenb if we unselect the resource it won't be packed into the apk.

![image](https://user-images.githubusercontent.com/6093737/40770213-99a61e84-64ec-11e8-9dd7-191eace39ffb.png)

**Comment by frenb** [comment]
I stand corrected. In version alpha.5, and after unselecting the resource this does work.
