### ISSUE TITLE
Assets are not sorted by size in refactor step

### ISSUE THREAD

**Issue by frenb** [cocos/cocos-engine#2779]
### Creator version?（版本号）
1.11-alpha.4

### How to reproduce?（如何重现）
Record and then go to refactor UI. Open any of the asset groups such as "Textures." Assets are not ordered by size.

**Comment by frenb** [comment]
Please associate with Google Play Instant milestone. I don't have the option to assign it to a milestone.

**Comment by jareguo** [comment]
Thanks! It will be improved in next version.
