### ISSUE TITLE
Asset groups such as "Texture" are not sorted in descending order

### ISSUE THREAD

**Issue by frenb** [cocos/cocos-engine#2780]
### Creator version?（版本号）
1.11-alpha.4

### Affected platform?（受影响的平台）

Mac editor
### How to reproduce?（如何重现）
Record and then go to refactor step. Asset groups are not sorted. The "Texture" group should be at the top because size of all the textures combined are larger then all the asset groups. 

Asset groups should be sorted by total size in descending order.

**Comment by frenb** [comment]
Please associate with Google Play Instant milestone. I don't have the option to assign it to a milestone.

**Comment by jareguo** [comment]
Fixed in 1.11.0-alpha.4
