### ISSUE TITLE
Dragging and dropping an asset from the asset window to the refactor window should enable user to replace an existing asset

### ISSUE THREAD

**Issue by frenb** [cocos/cocos-engine#2782]
### Creator version?（版本号）
1.11-alpha.4

### Affected platform?（受影响的平台）

Mac editor
### How to reproduce?（如何重现）
Dragging and dropping an asset from the asset window should enable the developer to replace an existing asset. 

As of build 1.11-alpha.4 you can only add an asset by dragging the asset to the refactor window. 

In addition, even after adding an asset to the refactor step it does not change the size of the APK generated.

**Comment by frenb** [comment]
Please associate with Google Play Instant milestone. I don't have the option to assign it to a milestone.

**Comment by jareguo** [comment]
Thanks @frenb !

**Comment by wuzhiming** [comment]
Hello @frenb ,about the dragging and dropping an asset , did you mean we need to enable developer to select an asset from refactor and add a swap button to enable developer replace the selected asset?
![image](https://user-images.githubusercontent.com/6093737/40817242-f7bb29fa-6583-11e8-818c-169086dd9644.png)

In the refactor records, we only record uuid for assets, if the developer replace their assets from asset panel, it will also change when they build the project.

**Comment by frenb** [comment]
Ok. That makes sense. Accepted.
