### ISSUE TITLE
[bug]event.getLocation只是返回一个普通的object={x, y}对象，不是vec2对象。

### ISSUE THREAD

**Issue by guawoo** [cocos/cocos-engine#2795]
### Creator version?（版本号）
1.9.1

### How to reproduce?（如何重现）
直接打印，cc.log(event.getLocation())

今天使用event.getLocation().add()方法一直报错，打印发现event.getLocation()竟然只是简单的返回了一个{x, y}的对象，不是一个vec2对象。

**Comment by unace** [comment]
https://github.com/cocos-creator/engine/commit/920e4dbfa6a369fb6cbc7b5c237250b3642180f4 fixed this.
