### ISSUE TITLE
Click event not triggered on canvas element with javascript

### ISSUE THREAD

**Issue by ashokduddukuri** [cocos/cocos-engine#2808]
### Creator version?（版本号）
V1.8.2

### Affected platform?（受影响的平台）

Web

### Demo project?（demo 项目）

I'm trying to programitically trigger mouse click events using cordinates on the canvas element to perfrom autamted testing. Code([JS Fiddle link](http://jsfiddle.net/gAxHe/95/)) works fine on the normal canvas element.  But when the same code is run against the cavnas created by cocos creator the event is not captured.

I'm not exactly sure if this is the bug or am I missing something simple. trying to find the soulution for a [long time.](https://discuss.cocos2d-x.org/t/automated-testing-for-games/42437)

**Comment by zhefengzhang** [comment]
In version 2.4.4, touch event can be used normally.
