### ISSUE TITLE
creator.d.ts中cc.audioEngine的api和引擎内置接口对应不上

### ISSUE THREAD

**Issue by RockerHX** [cocos/cocos-engine#2817]
[快速上手：制作第一个游戏](http://docs.cocos.com/creator/manual/zh/getting-started/quick-start.html)教程中指出播放音效使用如下代码：
```js
cc.audioEngine.playEffect(this.scoreAudio, false);
```
使用ts编写脚本，自动补全提示只有`static play(filePath: string, loop: boolean, volume: number): number;`这个方法，按照方法的描述填充参数不能播放声音，而在ts脚本里使用上述js代码能播放音效，但是`VSCode`提示找不到该方法，是否是creator.d.ts中的api描述有问题呢？
问题代码如下：
```ts
cc.audioEngine.play(this.scoreAudio, false, 0.8);
```
or
```ts
cc.audioEngine.play('../audio/score.mp3', false, 0.8);
```
均不能播放音效，下载的示例工程也无法播放音效。

Mac: 10.13.4 (17E202)
Chrome:  66.0.3359.139（正式版本） （64 位）
CocosCreator: 1.9.2

**Comment by Marssssssss** [comment]
谢谢您的反馈，在 v2.1.2 版本中的 creator.d.ts 里面已经包含了 playEffect 这个接口，请使用新版本的编辑器测试一下。
