### ISSUE TITLE
浏览器预览，提示uuid关联的json文件找不到。

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#2818]
### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）

全部
### How to reproduce?（如何重现）
打开一个场景，新建cc.Label并设置TTF字体，关闭该编辑场景，然后删除TTF文件，网页预览报错文件找不到，就是TTF的UUID丢失了

**Comment by jareguo** [comment]
现在要做的，就是完善报错信息，让用户看到原来的资源是哪个。然后告诉用户重新打开、保存一次指定资源，就可以消除警告。

**Comment by zhefengzhang** [comment]
此问题已修复。
