### ISSUE TITLE
exact Fit 的canvas 适配在小游戏平台按钮出现偏移

### ISSUE THREAD

**Issue by PPpro** [cocos/cocos-engine#2860]
master 分支

canvas 组件勾选  fit height、fit width，构建打包wechatGame， 运行项目，按钮区域出现偏移

好吧这个问题还是我修，提个 issue 怕忘了

**Comment by jareguo** [comment]
请提交到 1.9.3 对应分支

**Comment by PPpro** [comment]
1.x 小游戏的 bug 不再修复
