### ISSUE TITLE
QQ玩一玩不能发送二进制

### ISSUE THREAD

**Issue by GameKeys** [cocos/cocos-engine#2891]
### Affected platform?（受影响的平台）
  QQ 玩一玩

creator 1.9.2

var request = cc.loader.getXMLHttpRequest();
request.responseType = 'arraybuffer';

发送的二进制数据 服务器收到全是
args
Buffer(20) [91, 111, 98, 106, 101, 99, 116, 32, …]
args.toString();
"[object ArrayBuffer]"

这个项目在微信小游戏上没有问题，浏览器上也没有问题，只有QQ玩一玩上有问题

求解决 @dumganhar @jare @擎开发团队

**Comment by GameKeys** [comment]
帮我看看吧！

**Comment by GameKeys** [comment]
没有人管我，好冷呀

**Comment by dumganhar** [comment]
@jare

**Comment by knoxHuang** [comment]
抱歉，目前 QQ 玩一玩已经不维护了
