### ISSUE TITLE
子域中设置Sprite颜色失效

### ISSUE THREAD

**Issue by 9b9387** [cocos/cocos-engine#2894]
### Creator version?（版本号）
1.9.2

### Affected platform?（受影响的平台）

微信小游戏

### How to reproduce?（如何重现）
新建一个子域项目，Canvas下新建一个Sprite，然后在Node上设置Color。项目设置为子域项目，然后发布运行，Color设置无效，Sprite是原来的颜色。如果不设置为子域项目，颜色正常。这个问题必现。

### JavaScript output or error produced?（报错信息和调用栈）

无

**Comment by jareguo** [comment]
子域不支持 WebGL，所以 color 也没办法支持~

**Comment by 9b9387** [comment]
艺术数字也没办法显示，是同样的原因么？

**Comment by jareguo** [comment]
艺术字很有可能是我们不支持，需要 @pandamicro 确认下

**Comment by zhefengzhang** [comment]
这是微信小游戏开发者文档: https://developers.weixin.qq.com/minigame/dev/guide/open-ability/open-data.html

文档介绍，开放域只支持图片资源，不支持艺术字体资源。
