### ISSUE TITLE
微信小游戏平台一大堆BUG

### ISSUE THREAD

**Issue by xfxdev** [cocos/cocos-engine#2895]
### Creator version?（版本号）
1.9.2

### Affected platform?（受影响的平台）

微信小游戏

### How to reproduce?（如何重现）
都是基础功能BUG，无复杂重现步骤

### JavaScript output or error produced?（报错信息和调用栈）

无

### Demo project?（demo 项目）

无

**Bug：**
1. 音乐音效第二次播不出来
2. MotionStreak不能使用AtuoAtlas（不确定是Bug还是就是不支持）

**子域Bug：**
1. Sprite设置颜色无效
2. Label使用Bitmap Font时启动直接报错
3. Button不会触发事件
4. ScrollView可以滚动，但触摸不精确，经常拖不动

**Comment by jareguo** [comment]
> MotionStreak不能使用AtuoAtlas（不确定是Bug还是就是不支持）

AutoAtlas 只能用于 SpriteFrame喔，所以这个本来就不支持。

**Comment by xfxdev** [comment]
@jareguo 了解了，多谢。不过感觉会很容易带来问题，因为如果MotionStreak用的贴图与其它AutoAtlas的贴图放在一起的话，发布时不会有警告。pc上用模拟器跑正常，但发布到微信就不行了。

**Comment by jareguo** [comment]
嗯嗯，警告信息 1.10 版本已经加上了

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
