### ISSUE TITLE
videoplayer 组件层级太高会挡住下面元素事件

### ISSUE THREAD

**Issue by jy03078959** [cocos/cocos-engine#2908]
### How to reproduce?（如何重现）

如果选择一个视频全屏播放，看了下视频会是才 canvas 的上层做的一个video元素盖住的canvas。导致下层的canvas事件点击不了。建议添加的视频元素加一个 pointer-events: none; 样式。禁用掉他的事件响应，透下去。否则无法点击到元素

![image](https://user-images.githubusercontent.com/3038488/41925998-a62fb5ca-79a0-11e8-8080-86b96aea7192.png)

**Comment by Ronsku** [comment]
+1 :+1: Would be very useful!

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，可以在新版本的 creator 上测试一下是否还有这个问题。

**Comment by zhefengzhang** [comment]
可以参考这个案例：https://github.com/cocos-creator/example-cases/blob/v2.4.3/assets/cases/02_ui/09_videoplayer/videoPlayer-stayOnBottom.fire
演示了如何让 video 显示在 sprite/button 节点下面。
