### ISSUE TITLE
求问 widget 如何获取适配后的高度和宽度  我通过node.height 和 width获得的都是预设的值

### ISSUE THREAD

**Issue by phynero** [cocos/cocos-engine#2916]
### Creator version?（版本号）
v1.9.2

### Affected platform?（受影响的平台）

微信
### How to reproduce?（如何重现）
必现

### JavaScript output or error produced?（报错信息和调用栈）

无

**Comment by OnlyKoei** [comment]
延迟一帧获取，node.getContentSize()
