### ISSUE TITLE
CCDrawNode 的贝塞尔曲线绘制会出现棱角

### ISSUE THREAD

**Issue by wzpan** [cocos/cocos-engine#2927]
### Creator version?（版本号）

1.9.0

### Affected platform?（受影响的平台）

Web / iOS / Android

### How to reproduce?（如何重现）

1. 下载 demo project；
2. 预览 test 场景；
3. 在 test 场景中拖动，会发现线条转角处容易出现一些棱角。期望的效果是不会有这些棱角，而是一条粗细均匀的曲线。

![](http://forum.cocos.com/uploads/default/original/3X/a/0/a027f75504e6ccb3219d8d301335f1d666ad1baa.png)

### JavaScript output or error produced?（报错信息和调用栈）

通过断点我发现在一些情况下，_drawSegments 方法里头的 offset0 和 offset1 两个变量的 x、y 值可能很大，导致绘制出的三角形的某些顶点偏离得特别远，所以就出现了这些棱角。

更详细的分析可以见我在论坛里的一份帖子：http://forum.cocos.com/t/ccc/51528/65

### Demo project?（demo 项目）

[helloworld.zip](https://github.com/cocos-creator/engine/files/2152925/helloworld.zip)

**Comment by jareguo** [comment]
非常感谢您的反馈，你说的问题确实存在。由于我们没有在 1.x 中正式开放 DrawNode 模块，而且 DrawNode 在 2.0 已经移除，因此这些实现层面的东西我们已经不会在旧版本继续维护了。如有需要，建议尝试使用 [Graphics](http://docs.cocos.com/creator/manual/zh/components/graphics.html) 系统代替。如果有其它建议，请继续指正。
