### ISSUE TITLE
CCDrawNode 接口一致性问题

### ISSUE THREAD

**Issue by wzpan** [cocos/cocos-engine#2933]
### Creator version?（版本号）

1.9.0 

### Affected platform?（受影响的平台）

Web / iOS / Android / Simulator

### How to reproduce?（如何重现）

CCDrawNode.js 和 CCDrawNode.h 中定义的大部分的接口存在不一致。

例如，CCDrawNode.js 中的 `drawQuadBezier` ：

``` js
drawQuadBezier(origin, control, destination, segments, lineWidth, color)
```

CCDrawNode.h 中的 `drawQuadBezier`：

``` cpp
  /** Draw a cubic bezier curve with color and number of segments
     *
     * @param origin The origin of the bezier path.
     * @param control1 The first control of the bezier path.
     * @param control2 The second control of the bezier path.
     * @param destination The destination of the bezier path.
     * @param segments The number of segments.
     * @param color Set the cubic bezier color.
     */
    void drawCubicBezier(const Vec2 &origin, const Vec2 &control1, const Vec2 &control2, const Vec2 &destination, unsigned int segments, const Color4F &color);
```

可以看到后者比前者少了个 `lineWidth` 参数。请问这个差异是出于什么样的考虑？

### Demo project?（demo 项目）

下面这个 demo 工程，在 Native 和 Browser 中表现会不一样。Browser 中经过我的 hack （见 #2927 ）表现完美，而 Native 端则有很大差异：线条没有粗细、贝塞尔曲线补间的位置也随机得相当诡异。另外，iOS 下还会出现 crash 。

[helloworld.zip](https://github.com/cocos-creator/engine/files/2154206/helloworld.zip)

**Comment by jareguo** [comment]
非常感谢您的反馈，你说的问题确实存在。由于我们没有在 1.x 中正式开放 DrawNode 模块，而且 DrawNode 在 2.0 已经移除，因此这些功能层面的东西我们已经不会在旧版本继续维护了。如果有其它建议，请继续指正。

**Comment by wzpan** [comment]
@jareguo 能请教下如果不用 DrawNode 我们怎么实现橡皮擦（或者说刮刮乐）效果吗？我没有想到其他方案。

**Comment by wzpan** [comment]
我看了你们的 Mask 的实现，也是利用 CCDrawNode 来绘制的：https://github.com/cocos-creator/engine/blob/cbe73519d75dd684229600c633b1076df7d77ab4/cocos2d/core/components/CCMask.js#L312
想要对 Mask 的内容进行修改，不用 CCDrawNode 我想不到其他的方案呢。

**Comment by jareguo** [comment]
Graphics 目前不支持橡皮擦效果，2.0 稳定后我们研究看看吧，最近几个版本任务已经都排满了。
