### ISSUE TITLE
cc.audioEngine的三个接口存在bug，会导致对音效操作的同时也会对音乐进行操作

### ISSUE THREAD

**Issue by dongerlei** [cocos/cocos-engine#2938]
`setEffectsVolume: function (volume) {
        var musicId = this._music.id;
        this._effect.volume = volume;
        for (var id in id2audio) {
            if (id === musicId) continue;
            audioEngine.setVolume(id, volume);
        }
    },`
这里的id是string类型，而musicId是一个number类型。使用严格等于===，在这里总是会返回false。
所以并没有过滤掉对背景音乐的处理
pauseAllEffects、stopAllEffects存在同样的问题。请及时修复之。

**Comment by knoxHuang** [comment]
谢谢反馈，这个已经进行修复了
