### ISSUE TITLE
1.10以及2.0preview中存在，因合图导致拖拽绑定spriteFrame属性name出错

### ISSUE THREAD

**Issue by lich2333** [cocos/cocos-engine#2942]
在1.10和2.0preview中，通过拖拽绑定的图片 如果被合图，那么在打包后这个图片名字不是原来的！！！
老版本1.9.1是正确的
![image](https://user-images.githubusercontent.com/31687063/42276063-ea8716e4-7fc4-11e8-93fc-7fc7e459ce00.png)
![image](https://user-images.githubusercontent.com/31687063/42276070-f0a25c0a-7fc4-11e8-92d6-d1d427272ed2.png)

**Comment by jareguo** [comment]
是的，所有资源的名字在打包后都会被剔除。请不要依赖这个名字进行开发。
