### ISSUE TITLE
在ios中播放admob插页广告时切到后台，在切回来界面会卡住。无效果。applicationWillEnterForeground不会被调用

### ISSUE THREAD

**Issue by zjsjmvn** [cocos/cocos-engine#2946]
### Creator version?（版本号）
1.9.1

### How to reproduce?（如何重现）
在原生平台播放广告时，切到后台。在回到游戏，游戏会卡住

### JavaScript output or error produced?（报错信息和调用栈）

无堆栈

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，请在新版本的 creator 上进行测试，如果该问题还有出现的话可以提供一份 demo 以帮助我们更快定位这个问题。

**Comment by zhefengzhang** [comment]
你好，我这边测试过 2.x 版本接入穿山甲激励视频广告，切换前后台时并没有这个问题。
