### ISSUE TITLE
CollisionManager 能否手动调用碰撞检测？

### ISSUE THREAD

**Issue by gz65555** [cocos/cocos-engine#2987]
因为业务需求，需要手动去调用碰撞测试，而非使用内置地每帧检测，是否有方法可以可以控制何时去检测一次。

**Comment by fuyifan** [comment]
直接调用cc.director.getCollisionManager().update()

**Comment by knoxHuang** [comment]
![image](https://user-images.githubusercontent.com/7564028/63411920-2d0c6100-c429-11e9-89fa-51cf5d05f440.png)

可以根据 CollisionManager 中的  enabled 来进行开关
