### ISSUE TITLE
cc.audioEngine.isLoop不能正常工作

### ISSUE THREAD

**Issue by EattingGrass** [cocos/cocos-engine#2998]
CCAudioEngine.js中：
    isLoop: function (audioID) {
        var audio = getAudioFromId(audioID);
        if (!audio || !audio.isLoop)
            return false;
        return audio.isLoop();
    },
其中audio.isLoop在CCAudio.js中没有定义，应该改为getLoop

**Comment by knoxHuang** [comment]
对的，谢谢反馈，这个已经在修复了

更新的版本是 1.10 和 2.0
