### ISSUE TITLE
2.0 missing function :  this.m_debugDraw.DrawTransform is not a function (box2d.js:20388)

### ISSUE THREAD

**Issue by unace** [cocos/cocos-engine#3001]
### Creator version?（版本号）
Cocos Creator v2.0.0-beta.7

### Affected platform?（受影响的平台）

I think all platform.

### How to reproduce?（如何重现）
1. create a "HelloWorld" project.
2. open "HellowWorld" scene.
3. add a PhysicsBoxCollider component to cocos node.
4. add 
"cc.director.getPhysicsManager().enabled = true;
        cc.director.getPhysicsManager().debugDrawFlags = cc.PhysicsManager.DrawBits |
            cc.PhysicsManager.DrawBits.e_pairBit |
            cc.PhysicsManager.DrawBits.e_centerOfMassBit |
            cc.PhysicsManager.DrawBits.e_jointBit |
            cc.PhysicsManager.DrawBits.e_shapeBit;"
code to onLoad function in HelloWorld.js.

### JavaScript output or error produced?（报错信息和调用栈）

box2d.js:20388 Uncaught TypeError: this.m_debugDraw.DrawTransform is not a function
    at b2World.290.b2World.DrawDebugData (box2d.js:20388)
    at CCClass.update (CCPhysicsManager.js:219)
    at 32.cc.Scheduler.update (CCScheduler.js:413)
    at 27.cc.Director.mainLoop (CCDirector.js:952)
    at callback (CCGame.js:588)

**Comment by 2youyou2** [comment]
@unace Thanks for your feedback.

**Comment by unace** [comment]
@2youyou2 Thank you for the fix. Could you also look into this https://github.com/cocos-creator/engine/issues/3002 ?
