### ISSUE TITLE
游戏Resize后，物理对象偏离原来界面位置

### ISSUE THREAD

**Issue by yeahlang** [cocos/cocos-engine#3011]
### Creator version?（版本号）
1.9.3

### Affected platform?（受影响的平台）
实际测试在Android、IOS、Web上都受影响

### How to reproduce?（如何重现）
1、创建一个RigidBody，例如Static类型
2、打开物理引擎Debug Draw
3、使屏幕变形（在android上测试是点击了Editbox后产生的变形，ios测试时是横竖屏切换变形，web测试时是切换模拟器变形）
4、观察物理对象调试框跟原来显示位置的位移

### JavaScript output or error produced?（报错信息和调用栈）
无

### Demo project?（demo 项目）
无

自己尝试的修复代码，在android/ios/web上测试可用

    onLoad () {
        xNode = this.node; 

        cc.view.setResizeCallback(this.onCallbackResize); 
    }, 

    onCallbackResize () {
        if (!xNode) return; 

        cc.director.getPhysicsManager().enabled = false;
        xNode.runAction(cc.sequence(
            cc.delayTime(0.0), 
            cc.callFunc(function () {
                cc.director.getPhysicsManager().syncPosition(); 
                cc.director.getPhysicsManager().enabled = true;
            }))); 
    },

**Comment by ColinCollins** [comment]
I think that perhaps is the same question, so I keep the link in here. http://forum.cocos.com/t/editbox/64149
http://forum.cocos.com/t/cocos2dx-3-17/63889

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，可以在新版本测试一下还有没有这个问题。

**Comment by zhefengzhang** [comment]
你好，目前引擎的设计是 resize 事件并不会主动触发 cc.director.getPhysicsManager().syncPosition() 。
这个我们会考虑新版本中补充这个功能。
感谢你的反馈。
