### ISSUE TITLE
发布到native platforms例如iOS系统，发现性能非常差

### ISSUE THREAD

**Issue by jackhub** [cocos/cocos-engine#3013]
您好，我发现通过cocos-creator发布的native版本例如iOS中，游戏运行性能很差。通过工具分析看到主要开销在于JS与native bridge层的调用的通信开销，占了绝大部分CPU。请问你们有注意到这个问题吗，后续有没有什么优化思路？

**Comment by zhefengzhang** [comment]
目前物理场景因为在 ios 平台没有 jit 的原因导致性能较差，目前计划在 3.1.0 版本支持原生物理引擎后端，提升 ios 物理场景性能。
另外渲染场景也会计划采用多线程渲染的方式，尽可能利用设备多核心性能去加速渲染流程。多线程渲染器已经在内部打磨中。
