### ISSUE TITLE
Some functions of rect in Typescript are defined as wrong return type.

### ISSUE THREAD

**Issue by unace** [cocos/cocos-engine#3020]
### Creator version?（版本号）
Cocos Creator v1.9.3

### Affected platform?（受影响的平台）
All

### How to reproduce?（如何重现）
Developer > VS Code Workflow > Add Typescript config.

### JavaScript output or error produced?（报错信息和调用栈）
Non javascript error.

The return type of intersects, contains, containsRect are 'void'. They should be 'boolean'. But they actually return boolean value in runtime.

Please check below.

		@example 
		```js
		var a = new cc.Rect(0, 0, 10, 10);
		var b = new cc.Rect(0, 0, 20, 20);
		a.intersects(b);// true
		``` 
		*/
		intersects(rect: Rect): void;		
		/**
		!#en TODO
		!#zh 当前矩形是否包含指定坐标点。
		Returns true if the point inside this rectangle.
		@param point point
		
		@example 
		```js
		var a = new cc.Rect(0, 0, 10, 10);
		var b = new cc.Vec2(0, 5);
		a.contains(b);// true
		``` 
		*/
		contains(point: Vec2): void;		
		/**
		!#en Returns true if the other rect totally inside this rectangle.
		!#zh 当前矩形是否包含指定矩形。
		@param rect rect
		
		@example 
		```js
		var a = new cc.Rect(0, 0, 20, 20);
		var b = new cc.Rect(0, 0, 10, 10);
		a.containsRect(b);// true
		``` 
		*/
		containsRect(rect: Rect): void;

**Comment by jareguo** [comment]
fixed
