### ISSUE TITLE
Impossible to use full version of Cocos2d JS with Cocos Creator

### ISSUE THREAD

**Issue by serge-shaldanov** [cocos/cocos-engine#3021]
Hi for everyone!

I'm just a confused. Is it not possible to use full version of Cocos2d-JS with Cocos Creator?
Let's me to explain.
Okay, I'm try to use some features of full version of Cocos2d-JS like a `cc.spriteFrameCache` or `cc.loaderScene` in my JS code.
When I use template distributed with this full version of Cocos2d-JS: http://cocos2d-x.org/filecenter/jsbuilder all things do in right way. I really can use `cc.loaderScene.preload` and something else in this code.

When I create JS project with Cocos Creator everything becomes strange.
I'm just can't call `cc.loaderScene` from my code. It's return `undefined`.
So, after the long investigation I believe it's because Cocos Creator uses it's own version of Cocos2d-JS (so-called "engine") where all such features were cut.
I'm trying to add to assets folder my version of `cocos2d-js-v3.13.js` file downloaded from http://cocos2d-x.org/filecenter/jsbuilder and use it as a plugin, but no luck - when I run my project using such version of Cocos2d-js, Web emulator just breaks and I have many errors in my browser log like a:

> CCDebugger.js:367 undefined "cc.PI" "Math.PI"
(anonymous) @ CCDebugger.js:367
2CCDebugger.js:367 undefined "cc.isFunction" ""typeof obj === 'function'""
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.TEXT_ALIGNMENT_CENTER" "cc.TextAlignment.CENTER"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.VERTICAL_TEXT_ALIGNMENT_TOP" "cc.VerticalTextAlignment.TOP"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.isFunction" ""typeof obj === 'function'""
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.isFunction" ""typeof obj === 'function'""
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.TEXT_ALIGNMENT_CENTER" "cc.TextAlignment.CENTER"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.extend" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.isString" "cc.js.isString"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.isObject" ""typeof obj === 'object'""
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.isString" "cc.js.isString"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.isObject" ""typeof obj === 'object'""
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.EDITBOX_INPUT_MODE_ANY" "_ccsg.EditBox.InputMode.ANY"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.EDITBOX_INPUT_FLAG_SENSITIVE" "_ccsg.EditBox.InputFlag.SENSITIVE"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.KEYBOARD_RETURNTYPE_DEFAULT" "_ccsg.EditBox.KeyboardReturnType.DEFAULT"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.isString" "cc.js.isString"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.isObject" ""typeof obj === 'object'""
(anonymous) @ CCDebugger.js:367
2CCDebugger.js:367 undefined "cc.isNumber" "cc.js.isNumber"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.inject" "cc.js.mixin"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:362 undefined
(anonymous) @ CCDebugger.js:362
CCDebugger.js:367 undefined "cc.isString" "cc.js.isString"
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "cc.isObject" ""typeof obj === 'object'""
(anonymous) @ CCDebugger.js:367
CCDebugger.js:367 undefined "sp.SkeletonAnimation" "Skeleton"
(anonymous) @ CCDebugger.js:367
CCInputManager.js:425 Uncaught TypeError: Cannot read property 'UP' of undefined
    at CCInputManager.js:425
CCDirector.js:237 Uncaught TypeError: Cannot read property 'debugMode' of null
    at TheClass.calculateDeltaTime (CCDirector.js:237)
    at TheClass.mainLoop (CCDirector.js:1374)
    at callback (CCGame.js:561)

I have assumption it's because my Cocos2d-JS version goes in conflict with version of Cocos2d-JS embedded in Cocos Creator.

I'm trying to build my project to check changes without debugger (maybe it's a source of my problems?) - no success, I'm still get:

> CCDirector.js:237 Uncaught TypeError: Cannot read property 'debugMode' of null
    at TheClass.calculateDeltaTime (CCDirector.js:237)
    at TheClass.mainLoop (CCDirector.js:1374)
    at callback (CCGame.js:561)

and nothing is loaded.

I'm try to google such problem - no results.

Please say me: Is it possible to use FULL version of Cocos2d-JS with Cocos Creator or I should use my text editor for such purposes?

### Creator version?（版本号）
1.5.2

### Affected platform?（受影响的平台）
Web

Thanks for the feedback.（感谢反馈）

**Comment by serge-shaldanov** [comment]
I got it.

Cocos2d-x that provides described features is an absolutely different engine that is incompatible with Cocos Creator engine.

Cocos Creator is IDE and engine at the same time, and it's "engine" is a non-dividable part of this solution.

So, it's impossible to use Cocos2d-x with Cocos Creator.

It's a very sad because there are some good features in Cocos Creator only, and some good features in Cocos2d-x only.
The same things about docs and examples.

**Comment by jareguo** [comment]
Yes, you are right.
