### ISSUE TITLE
"Inline all SpriteFrames" build option always true, even when unchecked.

### ISSUE THREAD

**Issue by TimOfTheYear** [cocos/cocos-engine#3032]
When building a project for web or web-mobile, the value of the "Inline all SpriteFrames" option is always true, even when unchecked. The value of the "Merge all JSON that the Start Scene depends on" option is always false.

### Creator version?（版本号）
1.9.2 -> 2.0.2

### Affected platform?（受影响的平台）
Windows Editor - Publish to Web

### How to reproduce?（如何重现）
Publish any web project with the "Inline all SpriteFrames" or "Merge all JSON that the Start Scene depends on" options checked. Build a second version with the option unchecked. Diff the resulting published projects, they are identical.

**Comment by TimOfTheYear** [comment]
@slackmoehrle @pandamicro @jareguo Any help on this? It has been 2 and 1/2 months, issue still seems to persist in cocos 2.0.

**Comment by slackmoehrle** [comment]
@TimOfTheYear Thanks for reaching out. Please be patient for a few days as our team is finalizing releasing Cocos Creator 2.0.4. The engineering team can take a look at this issue soon. Please reach out if you need anything in the mean time.

**Comment by knoxHuang** [comment]
hi, i try test it in cocos 2.0.2, they are valid


**Inline all SpriteFrames** and **Merge all JSON that the Start Scene depends on** is false

![image](https://user-images.githubusercontent.com/7564028/47133661-46f68800-d2dc-11e8-9b84-a68b82aeb70a.png)

**Inline all SpriteFrames** is true

![image](https://user-images.githubusercontent.com/7564028/47133690-5fff3900-d2dc-11e8-9b2e-ea8345e590b5.png)

**Merge all JSON that the Start Scene depends on** is true

![image](https://user-images.githubusercontent.com/7564028/47133739-a5236b00-d2dc-11e8-93b1-4a74d24ff944.png)
