### ISSUE TITLE
"setMix" function of Spine Skeleton doesn't work.

### ISSUE THREAD

**Issue by unace** [cocos/cocos-engine#3041]
master branch : https://github.com/cocos-creator/engine/blob/dcd3357d61e518886ccbf8b2026bed4edc6c615d/extensions/spine/SGSkeletonAnimation.js#L159

next branch : https://github.com/cocos-creator/engine/blob/1abfe0c006ad6b562ec4d25eab1dd40b27c73079/extensions/spine/Skeleton.js#L589

should use "setMix" instead of "setMixWith" because fromAnimation and toAnimation are strings.

![image](https://user-images.githubusercontent.com/7022750/43619284-d8982bde-9681-11e8-8d03-dcae64b4cff4.png)

**Comment by jareguo** [comment]
fixed in #3058
