### ISSUE TITLE
微信小游戏在IOS平台，在下拉菜单和上拉状态栏无法收到game show hide事件回调

### ISSUE THREAD

**Issue by Habe-He** [cocos/cocos-engine#3043]
### Creator version?（版本号）
1.9.1

### Affected platform?（受影响的平台）
微信小游戏

### How to reproduce?（如何重现）
微信小游戏中下拉菜单和上拉状态栏即可

不过在游戏中点击Home键以及主动点击关闭按钮，show hide事件会响应了。
在新更新的2.0.0版本中提到修复了此问题，不过按照上面操作还是没有出现事件响应了

**Comment by zhefengzhang** [comment]
经过测试，是微信小游戏平台不支持在这个情况下监听这个类型的事件。
