### ISSUE TITLE
CCNode.js中的问题

### ISSUE THREAD

**Issue by bilibiliChangKai** [cocos/cocos-engine#3054]
### Creator version?（版本号）
2.0.1

### Affected platform?（受影响的平台）

Web

### How to reproduce?（如何重现）
1. CCNode.js中的getWorldMatrix函数(2550行)注释错误。写成了getLocalMatrix函数的注释。
2. 对应[文档](http://docs.cocos.com/creator/api/zh/classes/Node.html#getlocalmatrix)中出现了两个getLocalMatrix条目，应该改成getWorldMatrix。
3. 旧版的getNodeToParentTransform/getNodeToWorldTransform遭废弃，却没有对应的新版API， 新版getLocalMatrix/getWorldMatrix只是和getNodeToParentTransformAR/getNodeToWorldTransformAR相同。

### JavaScript output or error produced?（报错信息和调用栈）

对一个节点使用四个函数：
 - getNodeToWorldTransform()
   ~~~js
    a: 0.6231960706411657,
    b: -1.0371724338495558,
    c: 0.6546786227358439,
    d: 0.8520358270575961,
    tx: 206.37151872750945,
    ty: 616.1299018956438
   ~~~
- getWorldMatrix()
  ~~~js
   m00: 0.6231960706411657 
   m01: -1.0371724338495558 
   m02: 0 
   m03: 0 
   m04: 0.6546786227358439 
   m05: 0.8520358270575961 
   m06: 0 
   m07: 0 
   m08: 0 
   m09: 0 
   m10: 1 
   m11: 0 
   m12: 211.89745465525021 
   m13: 671.0061329818631 
   m14: 0 
   m15: 1
  ~~~

### Demo project?（demo 项目）

web中任意一个节点都能重现。

**Comment by ColinCollins** [comment]
注释内容已修复
https://github.com/cocos-creator/engine/pull/3048

**Comment by jareguo** [comment]
旧版的 getNodeToParentTransform/getNodeToWorldTransform，作用是什么呢？

**Comment by bilibiliChangKai** [comment]
@jareguo 
getNodeToParentTransform是基于节点的左下角的变换矩阵
getNodeToParentTransformAR基于节点锚点的变换矩阵
这个就是他们的区别

**Comment by jareguo** [comment]
是的，我想知道的是，你希望使用基于节点左下角的变换矩阵目的是什么？如果没有特别强烈的理由，新版本应该是不会加回来这两个 API 了。毕竟节点左下角只是一个特例，没理由支持左下角不支持左上角、右下角啥的。可以手动计算下 anchor 绕过这个问题吗？毕竟 node to parent 还是比较简单的

**Comment by bilibiliChangKai** [comment]
@jareguo 
我希望绘制节点的边框，便于DEBUG，所以要计算anchor，否则边框会不符合。
但是，我并没有太强烈的需求，因为之后我也通过手动计算anchor实现了我想要的效果。

**Comment by jareguo** [comment]
好的好的。这边主要还是对旧 API 的兼容不够理想。之后我们尽量避免。
