### ISSUE TITLE
2.0.0 TiledMap相关bug

### ISSUE THREAD

**Issue by hymanbuer** [cocos/cocos-engine#3072]
### Creator version?（版本号）
2.0.0

### Affected platform?（受影响的平台）

All

### How to reproduce?（如何重现）
Bug1：TiledLayer:getTileFlagsAt(pos, y)接口bug。
当pos为0时，会被判断为null。（源码的判断表达式有误）

Bug2：TiledLayer:getTileFlagsAt(x, y, forceCreate)接口问题。
当forceCreate为true而自动创建TiledTile组件后，又没对返回的TiledTile进行任何操作，但所绘制的TiledMap与调用该接口之前不一致，即产生副作用。

Bug3：更改TiledTile所在节点的锚点属性无效果。
我希望将锚点设置为Tile中心，然后做旋转等操作。

### JavaScript output or error produced?（报错信息和调用栈）

无。

### Demo project?（demo 项目）

无

**Comment by zhefengzhang** [comment]
bug1可以修改这里：
![图片](https://user-images.githubusercontent.com/35944775/114873704-26b4cf00-9e2e-11eb-822a-55864ebeff8e.png)

bug2 我不太理解你说的情况，你看能不能描述一下复现步骤，或者给个 demo。

bug3 锚点的设置在 2.4.4 版本是没问题的。

**Comment by zhefengzhang** [comment]
由于用户过长时间没有继续反馈，此 issues 暂时关闭。
