### ISSUE TITLE
Linux/Wine bug

### ISSUE THREAD

**Issue by alphaonex86** [cocos/cocos-engine#3082]
### Creator version?（版本号）
2.0

### Affected platform?（受影响的平台）

Linux/Wine

### How to reproduce?（如何重现）
Start under Linux/Wine

### JavaScript output or error produced?（报错信息和调用栈）

![screenshot_20180813_222213](https://user-images.githubusercontent.com/778581/44056041-5abd44aa-9f47-11e8-8105-e8aeaa30f985.png)

**Comment by wzpan** [comment]
Linux 上有人搞了个 Docker 版本：https://discuss.cocos2d-x.org/t/successfully-run-cocos-creator-on-linux-and-released-it-as-docker-image/40755

如果你们是用来搞页游的话，Docker 版本也许更适用于 Linux 。当然我也没试过。

**Comment by zhefengzhang** [comment]
目前不支持 Linux 系统运行 CocosCreator。
