### ISSUE TITLE
Not able to load image using addImageAsync from facebook profile pic url

### ISSUE THREAD

**Issue by pawankps** [cocos/cocos-engine#3090]
addImageAsync not works if provided facebook image url retrieved from graph api. This url directly download image if opened in browser instead of loading. addImageAsync  work if it is provided the image url which load image in browser instead of downloading it.
url(does not works) - https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=315610502517779&height=100&width=100&ext=1536831584&hash=AeQRPSkdxuvww7m0
url (works) - https://scontent.xx.fbcdn.net/v/t1.0-1/p100x100/306498_10100454212506291_1822407553_n.jpg?_nc_cat=0&oh=e2222f98f4118abbc3b487a02a7a92ea&oe=5C0A1170

**Comment by zhefengzhang** [comment]
CocosCreator 2.4.4 version has no addImageAsync this function, can not test.
