### ISSUE TITLE
2.0的camera

### ISSUE THREAD

**Issue by drrr8991** [cocos/cocos-engine#3101]
### Creator version?（版本号）
creator2.0

### Affected platform?（受影响的平台）

wechat小游戏 真机
### How to reproduce?（如何重现）

官方截图demo，直接重现，camera.render()去掉就不会卡死闪退，但是存在就会；

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
