### ISSUE TITLE
2.0.0 Missing/wrong Typescript definitions

### ISSUE THREAD

**Issue by molinx** [cocos/cocos-engine#3105]
In the 2.0.0 version, these console functions are missing in creator.d.ts:

```
cc.error
cc.warn
cc.log
```

Additionally, in the `VideoPlayer` component, I think the `clip` property should be a `cc.Asset` when using LOCAL Resource Type

**Comment by ColinCollins** [comment]
still be in there.
![image](https://user-images.githubusercontent.com/35832931/44247042-3c543f80-a214-11e8-8fca-27f0f2f2a6c2.png)

**Comment by chenquanjun** [comment]
+1!
missing these function!
![no](https://user-images.githubusercontent.com/2570285/44297343-4e141080-a302-11e8-8f30-b24793e95a0a.png)

**Comment by ColinCollins** [comment]
.... WTF， sorry for the late to response...
just like what I said, those function still exist, maybe you need to find more carefully.
ohhh, perhaps, you need to update your editor version. This problem has been fixed certainly.

**Comment by molinx** [comment]
Console functions are back again in v2.0.1 definitions

**Comment by molinx** [comment]
The VideoPlayer clip type should be updated to `Asset | string` (https://github.com/cocos-creator/creator-api-docs/blob/master/en/classes/VideoPlayer.md#clip)

Is the `creator.d.ts` file generated from the creator-api-docs?
