### ISSUE TITLE
[2.0.1-rc1]Creator安装过程中勾选VS2017进行安装时会出现报错信息（windows版本）

### ISSUE THREAD

**Issue by jareguo** [cocos/cocos-engine#3136]
@heyanfei commented on [Thu Aug 23 2018](https://github.com/cocos-creator/fireball/issues/8259)

操作步骤：进行Creator版本的安装，安装时勾选VS2017进行安装；
预期结果：可以正确安装VS2017
预期结果：在更新下载VS2017过程中出现了报错信息，详见下面截图；
![vs2017](https://user-images.githubusercontent.com/14326991/44510940-99eefd00-a6e8-11e8-80c9-e1b47026697d.jpg)

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/44563802-88622f80-a792-11e8-9a26-d7b06ccf3a16.png)
目前觉得是安装文件 json 文件配置的问题。实际 Cocos Component 是存在的，表示可能是路径相关信息有所变动。

**Comment by jareguo** [comment]
用英文版安装，然后搜看看英文报错信息？

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/44761160-9807bc80-ab74-11e8-9975-817a260d7559.png)

相同报错。。。

**Comment by jareguo** [comment]
不是，你这还是中文啊。你把系统语言改成英文先
