### ISSUE TITLE
Webview not working on Creator 2.0.x

### ISSUE THREAD

**Issue by shinsim** [cocos/cocos-engine#3163]
### Creator version?（版本号）
2.0.x

### Affected platform?（受影响的平台）
iOS & Android

### How to reproduce?（如何重现）
New Empty Project
Create new Webview & put in any url link in the component
Build->Compile->Install in device/simulator
Run

### JavaScript output or error produced?（报错信息和调用栈）
No error

**Comment by drelaptop** [comment]
thanks for this feedback, webview didn't works on 2.0.x, it's a unfinished feature. we plan to support it on creator 2.1.

**Comment by cmontiel** [comment]
Also, the webview position is wrong when exporting to "Web Mobile".

**Comment by tigershinny** [comment]
@drelaptop  videoplayer didn't works on 2.0.x, and will be supported for android and ios in coming creator 2.1?

**Comment by drelaptop** [comment]
yeah, creator 2.1 will be released soon. now we are testing RC version. This is related with Android & iOS Native WebView, AFAIK __WebView in Web platform is supported already__.

**Comment by tigershinny** [comment]
Great, looking forward to it, and thanks for your effort!

**Comment by bmbariah** [comment]
Was the WebView for Android fixed in Creator 2.1.0?

**Comment by drelaptop** [comment]
sure, for Android and iOS @bmbariah

**Comment by bmbariah** [comment]
> 
> 
> sure, for Android and iOS @bmbariah 

@drelaptop Is it possible to send POST data to the webview url? 
Kindly assist.

**Comment by sercand** [comment]
Also does not work on 2.1. It does work with webgl but not with canvas.
```
Uncaught TypeError: Cannot read property 'createBuffer' of undefined
    at new VertexBuffer (cocos2d-js.js:52093)
    at CCClass.ctor (cocos2d-js.js:38376)
    at new CCClass (eval at _createCtor (cocos2d-js.js:29369), <anonymous>:5:22)
    at Object.createIA (cocos2d-js.js:48613)
    at CCClass.onLoad (cocos2d-js.js:47684)
    at CCClass.eval [as _invoke] (eval at createInvokeImpl (cocos2d-js.js:14901), <anonymous>:3:65)
    at CCClass.invoke (cocos2d-js.js:14846)
    at CCClass.activateNode (cocos2d-js.js:26301)
    at CCClass._activate (cocos2d-js.js:11380)
    at 52.cc.Director.runSceneImmediate (cocos2d-js.js:9251)
    at cocos2d-js.js:9333
    at CCLoader.<anonymous> (cocos2d-js.js:28922)
    at cocos2d-js.js:23772
    at cocos2d-js.js:33548
```
which is located at cocos2d/particle/CCParticleSystem.js and cocos2d/particle/particle-system-assembler.js files

```javascript 
// cocos2d/particle/CCParticleSystem.js
    onLoad () {
        if (!this._ia) {
            ParticleSystem._assembler.createIA(this);
        }
    },
```

**Comment by drelaptop** [comment]
AFAIK, cocos creator 2.x didn't support canvas. did it? @umbrellaPP

**Comment by sercand** [comment]
@drelaptop Canvas renderer still there: https://github.com/cocos-creator/engine/tree/2.1.0/cocos2d/core/renderer/canvas and https://github.com/cocos-creator/engine/blob/2.1.0/cocos2d/core/renderer/index.js#L146 example codes. If device does not support webgl it fallbacks to canvas.

**Comment by zhefengzhang** [comment]
Starting from version 2.0.7, webview is supported.
