### ISSUE TITLE
部分AppleWebkit内核浏览器发生无法渲染的异常

### ISSUE THREAD

**Issue by yuangu** [cocos/cocos-engine#3185]
### Creator version?（版本号）
V2.0.1

### Affected platform?（受影响的平台）
Android(部分使用AppleWebkit) 以及旧版本的AppleWebkit浏览器

### How to reproduce?（如何重现）
重现方法：
方法一：小米3的原生浏览器
方法二（建议使用此方法重现）：（safri for windows浏览器）
http://dl.pconline.com.cn/html_2/1/104/id=44487&pn=0.html

### JavaScript output or error produced?（报错信息和调用栈）
大部分是这些。

```
Error
line: 34905
message: "'null' is not an object (evaluating 'gl.getExtension')"
sourceId: 2074162656
sourceURL: "http://10.0.5.174:7456/app/engine/bin/cocos2d-js-for-preview.js"
__proto__: Error
```
```
line: 34905
message: "'null' is not an object (evaluating 'gl.getExtension')"
sourceId: 2074162656
sourceURL: "http://10.0.5.174:7456/app/engine/bin/cocos2d-js-for-preview.js"
__proto__: Error
```

**Comment by yuangu** [comment]
发现 gl = canvasEL.getContext("webgl", opts) || canvasEL.getContext("experimental-webgl", opts) || canvasEL.getContext("webkit-3d", opts) || canvasEL.getContext("moz-webgl", opts);这行获取的gl为nil

**Comment by zhefengzhang** [comment]
> 发现 gl = canvasEL.getContext("webgl", opts) || canvasEL.getContext("experimental-webgl", opts) || canvasEL.getContext("webkit-3d", opts) || canvasEL.getContext("moz-webgl", opts);这行获取的gl为nil

如果是这个情况的话，那就是目标浏览器并不支持 webGL，这种情况引擎无法解决。
