### ISSUE TITLE
[2.0.1-rc3]cc.Graphics extend builds without _assembler

### ISSUE THREAD

**Issue by skaraman** [cocos/cocos-engine#3187]
### Affected platform?（受影响的平台）
Mac / Web 

### How to reproduce?（如何重现）
include custom component that uses `extends: cc.Graphics`
use custom component to render graphics to screen 
build to Mac or Web platforms

### JavaScript output or error produced?（报错信息和调用栈）
e._assembler.updateRenderData() is not a function
e._assembler is null

### Custom Solution
include check for _assembler in onLoad call of custom compnent that extends cc.Graphics
```
let graphicsExtension = cc.Class({
	extends: cc.Graphics,

	onLoad: function () {
		// cocos debug
		let saveCache = this._assembler
		if (!saveCache) {
			this._assembler = new cc.Graphics()._assembler
		}
	},

```

**Comment by ColinCollins** [comment]
The cc.Graphics is a special Component， it inherits from the RenderComponent.
when Creator executes the extends command it will set the constructor as the parent class, you can see [here](https://github.com/cocos-creator/engine/blob/master/cocos2d/core/platform/js.js), the graphics get the _assembler when running the ctor method (you can see  [here](https://github.com/cocos-creator/engine/blob/master/cocos2d/core/components/CCRenderComponent.js)) if you use your own class extends the cc.Graphics , it won't have the _assembler in its propertype.
emmmm, I don't know how to explain that more clearly, so if you still can't understand, just check the engine code, and tell me where you can't get.

**Comment by ColinCollins** [comment]
(it)[https://github.com/cocos-creator/engine/blob/master/cocos2d/core/components/CCRenderComponent.js]

**Comment by zhefengzhang** [comment]
用户长时间没有回复,问题暂时关闭.
