### ISSUE TITLE
2.01 bug  

### ISSUE THREAD

**Issue by karl511** [cocos/cocos-engine#3198]
c节点设置了zIndex600， 复制了这个节点生成d节点，经查看zIndex也是600， 但是却被zIndex100的背景节点a挡住了， 这三个节点是兄弟节点，这canvers下面。背景节点在节点树的最上面..

原因是cc.instantiate 以后， 复制的对象b，zIndex和原对象A的一样，但是_localZOrder 里面高16位为0，缺失了应有的zIndex信息。。  而且设置zIndex的代码里面有判断是否相同，即使后面又设置了和A节点一样的zIndex，有没有起到效果。。。 我现在的临时解决办法就是在cc.instantiate 以后设置b的zIndex为0，应为我后面load函数里有脚本设置zIndex非零参数， 才起到了更新_localZOrder， 画面才正常。 貌似2.0版本里面没有遇到这样的问题。
### Creator version?（版本号）
2.01

**Comment by zhefengzhang** [comment]
请问这个问题如何复现？是否能提供一下复现 demo？

**Comment by zhefengzhang** [comment]
用户长时间没有回复， issues 暂时关闭。
