### ISSUE TITLE
[2.0.1]cc.audioEngine.stopAllEffects会把背景音乐一起停掉

### ISSUE THREAD

**Issue by chenhongtu** [cocos/cocos-engine#3199]
2.0.1 cc.audioEngine.stopAllEffects方法会把背景音乐一起停掉

```
stopAllEffects: function () {
   var musicId = this._music.id;
   for (var id in _id2audio) {
        if (id === musicId) continue;
         var audio = _id2audio[id];
        var state = audio.getState();
        if (state === audioEngine.AudioState.PLAYING) {
	    audio.stop();
        }
   }
}
```
其中   `if (id === musicId) continue;`  id 为String , musicId 为 Number 
要改成  `if (id == musicId) continue;`

**Comment by django-d** [comment]
在stopAllEffects 等多个方法里写了这样的判断 for (var id in _id2audio) { if (id === musicId) continue;}
for in 出来的是 key 是string 这个肯定不成立 导致 判断失败， 改成 if (_id2audio[id].id === musicId) continue;这样就好了
