### ISSUE TITLE
2.0.1 Low resolution on facebook insant games with 2.0.1 (mobile only)  Cocos Creator

### ISSUE THREAD

**Issue by kreys** [cocos/cocos-engine#3212]
### How to reproduce:
1) Create empty project
2) Build for Instant Games
3) Upload, check on mobile by Messenger app
4) View resolultion is too low, everything is totally blured / pixelated

### Demo project: 
[resolutionTest.zip](https://github.com/cocos-creator/engine/files/2357192/resolutionTest.zip)

### Description:
We are just starting a new project for Messenger, and we’ve moved from 1.9.3 to 2.0.1. Everything seems fine, despite one thing.

Web build opened locally and on mobile browser seems ok.
Facebook instant games build opened on desktop browser is ok.
Facebook instant games build opened on mobile with Messenger app is totaly low resolution and blurred. Printing cc.view.getCanvasSize() gives results of 393 x 738, and it is opened on phone with 2160x1080 resolution (and should be somehow close to this number). The same things happenes on a wide variety of devices, in different resolutions - output is way too low.

Is it a Cocos Creator bug?

I have tried different design resolutions, fit to width / height options, nothing helps. The same thing is on a clean empty project, see image below:

Facebook Instant Games on mobile Messenge (WRONG) (device resolution is 2160x1080):
![screenshot_2018-09-06-11-17-14-462_com facebook orca](https://user-images.githubusercontent.com/4800087/45159832-21a83180-b1e8-11e8-8a03-54d5325829ac.png)

Facebook Instant Games on desktop browser (OK):
![2018-09-06 110954 screenshot](https://user-images.githubusercontent.com/4800087/45159850-2e2c8a00-b1e8-11e8-87e1-7371e5db7b18.png)

Local build on desktop or mobile browser (OK):
![2018-09-06 110901 screenshot](https://user-images.githubusercontent.com/4800087/45159890-4a302b80-b1e8-11e8-9ba6-1862a1b5b4c4.png)

Any workarounds or fix ETA?

**Comment by skaraman** [comment]
can you also check and see what `window.devicePixelRatio` is on all 3?

**Comment by jareguo** [comment]
It must be a common issue on all instant games. Can you check the value of cc.view._devicePixelRatio ?

**Comment by kreys** [comment]
We have already released two games on Facebook Instant Games with Cocos Creator 1.9.3 and it never was a feature - they both look good - so there is some degradation with 2.0.1.

Anyway, I did what you both have asked, also doing these tests on same Facebook app, but with Cocos 1.9.3.

**Cocos Creator 2.0.1:**

Device type | `cc.view. getCanvasSize()` |  `cc.view. getDevicePixelRatio()` | `window. devicePixelRatio`
------------ | ------------- | ------------ | ----------
Local desktop browser (looks good) | 960 x 600 | 1 | 1
Messenger desktop browser (looks good) | 1280 x 720 | 1 | 1
Android `2160x1080` local build on browser (looks good) | 1478 x 530 | 2  | 2.75
Android `2160x1080` on Messenger (looks like **very low resolution**) | **738 x 393** | **1** | **2.75**
Android `1920x1080` on Messenger (looks like **very low resolution**) | **592 x 360** | **1** | **3**

**Cocos Creator 1.9.3:**

Device type | `cc.view. getCanvasSize()` |  `cc.view. getDevicePixelRatio()` | `window. devicePixelRatio`
------------ | ------------- | ------------ | ----------
Local desktop browser (looks good) | 960 x 600 | 1 | 1
Messenger desktop browser (looks good) | 1280 x 720 | 1 | 1
Android `2160x1080` local build on browser (looks good) | 1478 x 530 | 2  | 2.75
Android `2160x1080` on Messenger (looks good) | **1476 x 786** | **2** | **2.75**
Android `1920x1080` on Messenger (looks good) | **1184 x 720** | **2** | **3**

So you can clearly see that `cc.view.getDevicePixelRatio()` on Messenger on devices is different in `2.0.1` than it was in `1.9.3`.

**Comment by pandamicro** [comment]
Please check cc.view.isRetinaEnabled() in v2.0.1, from what you posted, it should be false, but we actually enabled it by default in main.js, so please check where do you disable it.

Maybe you are using a custom template for main.js, then you can compare with the default one

**Comment by unace** [comment]
I don't know why, but v2.0.2 doesn't have below code in **default** main.js. It was in v1.9.3. 
After adding this code to main.js, the problem has been resolved.


```
// UC browser on many android devices have performance issue with retina display
if (cc.sys.os !== cc.sys.OS_ANDROID || cc.sys.browserType !== cc.sys.BROWSER_TYPE_UC) {
    cc.view.enableRetina(true);
}
```

**Comment by kreys** [comment]
As @unace mentioned above, the following line that enable `cc.view.enableRetina(true)` disappeared from `fb-instant-games` default `main.js` file. 

It is enabled by default in `web-mobile` `main.js` file, however it is not in facebook template, so I guess it should be enabled here as well. Manually enabling it in `main,js` file fixes issue, and it looks like it was looking in `1.9.3`.

**Comment by jareguo** [comment]
same feedback: http://forum.cocos.com/t/v2-0-1-facebook-instantgame/66453

**Comment by kreys** [comment]
Bug still exists in 2.0.2.

**Comment by ColinCollins** [comment]
I will fix it immediately, Thx for your feedback, This problem will be fixed in the next version. @kreys

**Comment by unace** [comment]
@ColinCollins Is #3390 related to this issue? It doesn't look like that to me.

**Comment by RaoNawaz** [comment]
> I don't know why, but v2.0.2 doesn't have below code in **default** main.js. It was in v1.9.3.
> After adding this code to main.js, the problem has been resolved.
> 
> ```
> // UC browser on many android devices have performance issue with retina display
> if (cc.sys.os !== cc.sys.OS_ANDROID || cc.sys.browserType !== cc.sys.BROWSER_TYPE_UC) {
>     cc.view.enableRetina(true);
> }
> ```

This solved my problem. Thanks a lot
