### ISSUE TITLE
safeMeasureText 改进 

### ISSUE THREAD

**Issue by zilongshanren** [cocos/cocos-engine#3236]
在ios系统上面，如果用户呼出控制中心，或者游戏中接电话，此时如果去操作canvas去获取metric，会得到null, 引擎做了safeMeatureText，但是实现不够好，会导致UI展示出问题。因为不管传什么字符串，返回的宽度都是0.

我这里有一个改进  

```js
    safeMeasureText: function (ctx, string) {
        if (!string) {
            return 0;
        }
        var metric = ctx.measureText(string);
        if (metric) {
            return metric.width;
        }
        if (ctx.font && ctx.font.match) {
            var match = ctx.font.match(/\d+/);
            var fontSize = match ? match[0] : 20;
            return string.length * fontSize;
        } else {
            return 20 * string.length;
        }
    },

```

@jareguo @knoxHuang  有点小懒，就不提PR了。

**Comment by zilongshanren** [comment]
对于中文字符，fontSize * length 和measureText的结果差不多。对于英文，会有一些差异，但是也比直接返回0要好，UI显示不会错的太离谱。

**Comment by jareguo** [comment]
感谢大大，这个修复对什么平台有效呢？小游戏？

**Comment by zilongshanren** [comment]
小游戏，其他平台metric不会为null

**Comment by dumganhar** [comment]
小游戏底层的问题居然要上层hack代码改啊。。。

**Comment by jareguo** [comment]
只是小游戏的话，感觉在 adapter 中修改比较好

**Comment by pandamicro** [comment]
@knoxHuang 在 Adapter 中尝试重写 CanvasRenderingContext2d.prototype.measureText，需要测试真机环境，如果真机环境保护了这个 prototype，不允许重写，那就不要做修改了

**Comment by zilongshanren** [comment]
@pandamicro 那这个修改最后是写在哪里。。。

**Comment by jareguo** [comment]
@knoxHuang 
要不就在 weapp-adapter 中重写 safeMeasureText，内部调用引擎原先的 _safeMeasureText，判断下如果返回是 0 并且 string.length > 0，则说明需要按照子龙的方法重新拿 fontSize 进行计算

**Comment by knoxHuang** [comment]
safeMeasureText 主要是这个在 weapp-adapter 是没办法获取到到

**Comment by jareguo** [comment]
safeMeasureText 其实也不应该放在 text-utils 中。建议直接放到 ttf.js 中，然后注册到 cc.Label._ttfAssembler 中，就可以在其它平台上进行 polyfill 了。
