### ISSUE TITLE
[v2.0.2-beta.2] particle upgrade issues from v1.9.3 to v2.0.2

### ISSUE THREAD

**Issue by unace** [cocos/cocos-engine#3240]
I found particle upgrade issues from v1.9.3 to v2.0.2.
1. custom particle is not upgraded automatically.
2. particle is not changed by scheduler's timescale. (it works on v1.9.3)
3. custom particle sprite frame is displaying as a square.
4. warning message if I save the scene with custom particle sprite frame.
"The SpriteFrame used by component "cc.ParticleSystem" is missing. Detailed information:"

If these are the intended or known issues, please let me know.

### Creator version?（版本号）
Cocos Creator v2.0.2-beta.2

### Affected platform?（受影响的平台）
Mac

### How to reproduce?（如何重现）
1. download a sample cocos creator project file (v1.9.3) : https://drive.google.com/file/d/1ONh1TPhlz2wnUMyXe8Dp4BwhwvZb66XR/view?usp=sharing
2. load it with Cocos Creator v1.9.3 and play it.
3. load it with Cocos Creator v2.0.2-beta.2 and play it. (broken)

### Demo project?（demo 项目）
https://drive.google.com/file/d/1ONh1TPhlz2wnUMyXe8Dp4BwhwvZb66XR/view?usp=sharing

**Comment by benloong** [comment]
#2730  PR may lead to this ParticleSytem backward compatibility broken

**Comment by zhefengzhang** [comment]
In the 2.4.4 version test https://drive.google.com/file/d/1ONh1TPhlz2wnUMyXe8Dp4BwhwvZb66XR/view?usp=sharing there is no problem, so close this issue.
