### ISSUE TITLE
cocos creator 2.x怎么实现3d透视投影效果 

### ISSUE THREAD

**Issue by caochao** [cocos/cocos-engine#3248]
理论上我应该创建一个透视投影类型的相机，2.x场景中默认的相机已经是这种类型的了。
然后我应该能设置3d坐标，但是目前只能设置xy平面的，无法设置z值，因此无法在z轴上实现近大远小的效果。
另外，相机应该能设置lookAt某一个3d坐标，2.x中camera也已经支持了。
所以我的问题是，要如何才能设置相机在z轴上的坐标？在cocos2dx中的写法是这样的
camera->setPosition3D(Vec3(0, 0,300));
camera->lookAt(Vec3(100, 0, 0),Vec3(0,1,0));

@jareguo @pandamicro @knoxHuang

**Comment by caochao** [comment]
发在cocos creator论坛里一直没人理会，所以来这里问一下

**Comment by caochao** [comment]
有没什么办法能魔改一下engine，我对这个需求很强烈。。。

**Comment by caochao** [comment]
理论上只要能设置相机位置在z轴上的坐标，生成一个包含z的3d的视图矩阵。但是我不太清楚应该在引擎哪部分修改，所以请指点一下

**Comment by pandamicro** [comment]
你需要创建一个 Camera 组件，然后重写它的 beforeDraw

```
var camera = node.addComponent(cc.Camera);
camera.beforeDraw = function () {
    ...
}
```

具体实现参考 CCCamera 原始内部实现

**Comment by caochao** [comment]
好的，我看一下

**Comment by caochao** [comment]
![image](https://user-images.githubusercontent.com/1911170/45525963-bffb4f00-b807-11e8-845b-06226df6f293.png)
我可以写死这个camera的z值，来设置它注视点z坐标？

**Comment by caochao** [comment]
但是_vec3_temp_1是设置相机注视的位置。我应该是要设置相机的位置，是这里的node.z值么，现在z值这种计算方法是什么意思？

**Comment by caochao** [comment]
我发现改了node.z值后，相机注视区域有了缩放，但是并没有透视近大远小的效果。 @pandamicro 麻烦指点一下，感谢

**Comment by caochao** [comment]
CCNode里有两个函数
_updateLocalMatrix
_updateWorldMatrix
但是要命的是这两的变换都是基于affine-transform的也就是 只控制了6个元素 a b c d tx ty 同时，这套东西也是标准的2d变换的东西，做不了3d变换。
但是 Node的属性 _matrix _worldMatrix 都是 mat4类型的 也就是说完全可以做3d变换。
所以我现在有点迷茫了，在CCCamera beforeDraw里改z坐标真的能实现3d变换吗

**Comment by caochao** [comment]
![image](https://user-images.githubusercontent.com/1911170/45537288-66f6df80-b836-11e8-8cc7-ab60ac0ebd09.png)
最后发现要搭配调整相机注视点y坐标和相机自身y坐标，能实现效果

**Comment by DylanJiangPro** [comment]
遇到一个问题：当多Camera（分组渲染）时，要怎样设置重写后脚本的cullingMask和clearFlags值？有办法通过脚本来设置吗？
副Camera截图：
![image](https://user-images.githubusercontent.com/30583427/45543416-f1dfd600-b846-11e8-9b7b-4943c8b81945.png)

仅重写了 beforeDraw
![image](https://user-images.githubusercontent.com/30583427/45542863-a678f800-b845-11e8-905e-219f3d35e84b.png)

**Comment by caochao** [comment]
是可以设置的，只是失去了默认的样式。 culling mask default为1，自定义的依次加1。 clear flags参考main camera, 值分别是1，2，4。三者按位与之后值为7。

**Comment by DavidHome** [comment]
你好，请问node怎么支持纵深坐标呢，就是z方向的。现在做2.5d没有z方向也不行啊

**Comment by DavidHome** [comment]
面板属性问题，在继承后把下面这个也加上。感谢你们的问题， 让我解决了我的问题。
 editor: CC_EDITOR && {
        menu: 'i18n:MAIN_MENU.component.others/Camera',
        inspector: 'packages://inspector/inspectors/comps/camera.js',
        executeInEditMode: false
    },

![1](https://user-images.githubusercontent.com/6417695/45876379-14389d00-bdcd-11e8-9bce-840178bfbdbc.jpg)

**Comment by caochao** [comment]
> 面板属性问题，在继承后把下面这个也加上。感谢你们的问题， 让我解决了我的问题。
> editor: CC_EDITOR && {
> menu: 'i18n:MAIN_MENU.component.others/Camera',
> inspector: 'packages://inspector/inspectors/comps/camera.js',
> executeInEditMode: false
> },
> 
> ![1](https://user-images.githubusercontent.com/6417695/45876379-14389d00-bdcd-11e8-9bce-840178bfbdbc.jpg)

ts版本的要这么写：
![image](https://user-images.githubusercontent.com/1911170/46710775-f8157680-cc7b-11e8-8c94-c1849877a81c.png)

**Comment by linguitang** [comment]
修改beforeDraw实现透视投影后，通过getCameraToWorldPoint已经无法得到正确的变换后的坐标，可有啥解决方案 @caochao @DavidHome @pandamicro 

下面是修改的代码
```
        node._updateWorldMatrix();
        _vec3_temp_1.x = node._worldMatrix.m12;
	_vec3_temp_1.y = node._worldMatrix.m13 + 200;
        _vec3_temp_1.z = 300;
        node.y = -350;
```

**Comment by linguitang** [comment]
升级到了2.1，不改引擎代码，用3d相机实现透视，可是依然没法得到透视后，显示在屏幕上的坐标

**Comment by caochao** [comment]
> 升级到了2.1，不改引擎代码，用3d相机实现透视，可是依然没法得到透视后，显示在屏幕上的坐标

你可以使用camera私有方法worldToScreen

**Comment by linguitang** [comment]
> > 升级到了2.1，不改引擎代码，用3d相机实现透视，可是依然没法得到透视后，显示在屏幕上的坐标
> 
> 你可以使用camera私有方法worldToScreen

你之前反馈的问题还是依然存在[https://github.com/cocos-creator/engine/issues/3296](https://github.com/cocos-creator/engine/issues/3296)，获取到的依旧是中心点，还是得再改一次代码

**Comment by caochao** [comment]
> > > 升级到了2.1，不改引擎代码，用3d相机实现透视，可是依然没法得到透视后，显示在屏幕上的坐标
> > 
> > 
> > 你可以使用camera私有方法worldToScreen
> 
> 你之前反馈的问题还是依然存在#3296，获取到的依旧是中心点，还是得再改一次代码

那你用我改的那个worldToScreen2方法，我现在也是用的这个方法。引擎代码里加上这个方法，然后在creator设置里使用自定义js引擎

**Comment by linguitang** [comment]
> > > > 升级到了2.1，不改引擎代码，用3d相机实现透视，可是依然没法得到透视后，显示在屏幕上的坐标
> > > 
> > > 
> > > 你可以使用camera私有方法worldToScreen
> > 
> > 
> > 你之前反馈的问题还是依然存在#3296，获取到的依旧是中心点，还是得再改一次代码
> 
> 那你用我改的那个worldToScreen2方法，我现在也是用的这个方法。引擎代码里加上这个方法，然后在creator设置里使用自定义js引擎

嗯，这个方法我知道，谢谢

**Comment by jareguo** [comment]
这个 issue 可以关闭了吗？ @caochao

**Comment by caochao** [comment]
> 这个 issue 可以关闭了吗？ @caochao

可以

**Comment by linguitang** [comment]
请问一下2.1.3，相机透视是不是又不能用了
