### ISSUE TITLE
打android包使用wss协议进行websocket连接出错

### ISSUE THREAD

**Issue by 252378189** [cocos/cocos-engine#3249]
### Creator version?（版本号）
cocos creator v2.01

### Affected platform?（受影响的平台）
Android

### How to reproduce?（如何重现）
只要使用wss协议来连接的Android包每次都会出现，但是如果改为用ws协议来连的Android包是没有问题的。
PS：服务器是支持wss及ws的，打微信小程序包以及Web包是都是没有问题的。

### JavaScript output or error produced?（报错信息和调用栈）

没有特别的报错，就是连接websocket的时候直接报onerror的连接错误

### Demo project?（demo 项目）

cc.Class({
    extends: cc.Component,

    properties: {
        label: {
            default: null,
            type: cc.Label
        },
        text: 'Hello, World!',
        websocket:null,
        wsServer:null,
    },
    onLoad: function () {
        this.label.string = this.text;
        var aa = 'aa.bb.com:7066/?token=NjNlZXFneTNqQ3JuUThtZTR5T3ZSVFZqRFpBQ2x1L0ZaOGd4cmpoM3hmNSggfdsgdfgfd';
        this.init(aa);
    },

    init:function(wss){
        this.wsServer = "ws://"+wss;
		console.log("init连接地址",this.wsServer);
		//创建websocket事件
        this.websocket = new WebSocket(this.wsServer);
        this.websocket.binaryType="arraybuffer";
		//打开websocket连接
		this.websocket.onopen = function (evt) {
			console.log("websocket.onopen OK");
		}.bind(this);
		//关闭连接
		this.websocket.onclose = function (evt) {
			console.log("websocket.onclose",evt);
		}.bind(this);
		//监听信息的接收
		this.websocket.onmessage = function (evt) {
			console.log("返回的数据:",evt.data);
		};
		//监听websocket出错
		this.websocket.onerror = function (evt) {
			console.log("websocket.onerror",evt);
		}
    },
    // called every frame
    update: function (dt) {

    },
});

**Comment by interfacekun** [comment]
老哥你找到原因了吗

**Comment by 252378189** [comment]
解决了，是需要连接websocket的时候加载证书：
this.websocket = new WebSocket(this.wsServer,"","客户端证书路径");

PS:
这个证书路径要特别注意，不知道为什么把证书像资源文件那样放在资源的目录是不行的。
查看过在构建原生包的时候也是有构建进去，但就是死活报路径不对。
后来这个 客户端证书 我在构建完了之后再复制到构建后的资源路径里，然后写代码的时候硬引用就对了。搞不明白为毛这样。
^O^对了我已转Laya.................

**Comment by interfacekun** [comment]
路径不对可能需要cc.url.raw("resources/214771538980572.pem")转换一下，最近也在了解laya。
