### ISSUE TITLE
creator 2.0.1 worldToScreen求解

### ISSUE THREAD

**Issue by caochao** [cocos/cocos-engine#3296]
我们游戏cocos2dx版本用到了Camera做透视投影的近大远小效果，也用到了projectGL来计算屏幕坐标。目前我把游戏用creator改写的过程中由于自带的cocos2dx-lite移除了Camera，导致遇到一系列问题。

而我之前也有发帖提到过，我修改了cccamera的beforeDraw方法实现了针对节点N做透视投影。这次我想把节点N里的坐标C转化为屏幕坐标。
看到render-engine.js里有个worldToScreen方法，是把一个世界坐标乘以摄像机的视图和投影矩阵最终变化到视口坐标，应该和cocos2dx Camera里的projectGL方法是同样的作用。但是我调用这个方法无论传入什么世界坐标返回结果一直在ui设计尺寸的中心点左右, 设计尺寸是750*1334，返回结果一直近似于(375,667)。麻烦指点一下。
相关代码如下：
![image](https://user-images.githubusercontent.com/1911170/45821545-1131a400-bd1c-11e8-9c99-664f7d86e543.png)
BattleCamera用来渲染PanelBattle。_temp_vec2是PanelBattle里一个点。
![image](https://user-images.githubusercontent.com/1911170/45821646-450cc980-bd1c-11e8-8238-77e5bb469468.png)
![image](https://user-images.githubusercontent.com/1911170/45821750-9026dc80-bd1c-11e8-8b11-573ddfca9177.png)
@pandamicro @jareguo

**Comment by caochao** [comment]
@pandamicro 空闲的时候帮忙看看

**Comment by caochao** [comment]
我发现问题了，render-engine.js worldToScree方法里先用vec3.transformMat4把世界坐标乘以视图投影矩阵，这个方法里已经将x,y坐标除以w做了一次透视除法得到裁剪坐标（这一步似乎不用除w）
![image](https://user-images.githubusercontent.com/1911170/45859065-ffd7ae80-bd92-11e8-98be-9aee7bf4a1e3.png)

接下来又将x,y做了除w操作。x, y除了2次w后变得非常小，所以返回值一直近似于设计尺寸一半。
![image](https://user-images.githubusercontent.com/1911170/45859079-154cd880-bd93-11e8-8597-1ff518bcdbf4.png)

**Comment by caochao** [comment]
![image](https://user-images.githubusercontent.com/1911170/45863823-72a05400-bdaa-11e8-8b46-d5d59aa016aa.png)
我把实现改了一下，使用了vec4.transformMat4（这个方法里没有将x,y除w），所以没有问题。而且我这个改法，和cocos2dx Camera中projectGL方法功能应该是一致的
![image](https://user-images.githubusercontent.com/1911170/45879073-c1171800-bdd5-11e8-84b1-139f264e58c4.png)

**Comment by Ander456** [comment]
额 ，没懂。老哥 意思是 官方的代码 这个 worldToScreen是有bug的么？

**Comment by zhefengzhang** [comment]
2.1.1 版本 worldToScreen 已经修改
![图片](https://user-images.githubusercontent.com/35944775/113397836-411f8f00-93d0-11eb-8389-6b111e436d83.png)
