### ISSUE TITLE
cc.Texture2D initWithData错误

### ISSUE THREAD

**Issue by toddlxt** [cocos/cocos-engine#3313]
使用initWithData后，执行到这一行会报错（this._texture为null）：
https://github.com/cocos-creator/engine/blob/96bda88193f046d4669a2fb38a5ad968c5d6a9df/cocos2d/core/assets/CCTexture2D.js#L377

**Comment by ColinCollins** [comment]
This issue has been fixed, Thx for your feedback. @toddlxt
