### ISSUE TITLE
[2.0.2] cc.audioEngine.setEffectsVolume affects to Music volume

### ISSUE THREAD

**Issue by unace** [cocos/cocos-engine#3318]
### Creator version?（版本号）
2.0.2

### Affected platform?（受影响的平台）

Mac

### How to reproduce?（如何重现）
1. Play Music with "cc.audioEngine.playMusic"
2. Set Effect sound volume to 0 (cc.audioEngine.setEffectsVolume(0);)
3. setEffectsVolume affects to music volume

### JavaScript output or error produced?（报错信息和调用栈）

![image](https://user-images.githubusercontent.com/7022750/46115210-c942cf00-c1aa-11e8-9eba-e9d23dbc1be9.png)

The key of _id2audio in CCaudioEngine.js is "string" not "number". That's the reason why this bug happens.

https://github.com/cocos-creator/engine/blob/master/cocos2d/audio/CCAudioEngine.js#L697

I think other similar codes also have the same problem.

**Comment by ColinCollins** [comment]
This problem has been fixed.
There is the pr:
https://github.com/cocos-creator/engine/pull/3299
we will update this part of the content in the version 2.0.5.
Thx your feedback

**Comment by unace** [comment]
Thank you for the fix.
