### ISSUE TITLE
cocos creator 2.0 首次进入游戏或者分享回来，有机率横竖屏错误

### ISSUE THREAD

**Issue by zilongshanren** [cocos/cocos-engine#3319]
![image](https://user-images.githubusercontent.com/785541/46118705-6e58b880-c23a-11e8-81d1-eb711ab1599b.png)

2.0 首次进入游戏或者分享之后回来游戏，有机率横竖屏错误
反复多按几次右上角退出，然后进入游戏就可以重现了。

**Comment by jareguo** [comment]
据说安卓重现概率大一点
先重现看看吧……

**Comment by dumganhar** [comment]
这还能是引擎的问题啊？不应该是微信小游戏底层没处理好么？

**Comment by zilongshanren** [comment]
@dumganhar 可能是底层的问题。。。

**Comment by knoxHuang** [comment]
测试了一下，并没有走我们引擎 setDesignResolutionSize ，屏幕适配到代码，可能是底层没有旋转成功导致到

子龙也重现验证了一次，发现无法重现

**Comment by knoxHuang** [comment]
经过 @zilongshanren 的测试，目前可以解决的 hack 方法，去掉过滤判断，每帧去做：

![image](https://user-images.githubusercontent.com/7564028/49719059-ffb2c500-fc96-11e8-8aa6-34ea4014dac3.png)

但是这个应该是微信底层去做才对，已经反馈给微信了

**Comment by jareguo** [comment]
好吧，那就先 close 吧，实在还需要我们来改再说
