### ISSUE TITLE
[2.0.2正式版]当 scrollView 内 mask 与 scrollView 外 mask 重叠时，外部 mask 遮罩失效

### ISSUE THREAD

**Issue by xduooo** [cocos/cocos-engine#3339]
### 描述
当 scrollView 内 mask 与 scrollView 外 mask 重叠时，外部 mask 遮罩失效
![image](http://forum.cocos.com/uploads/default/original/3X/a/0/a0a012c8850e74418f0ebb35878af6db832d8952.png)

### 讨论帖
http://forum.cocos.com/t/mask-bug-demo/66995

### Demo project
http://forum.cocos.com/uploads/default/original/3X/0/7/07d420d18e1325c2852d99cca36f3c0d23de51ce.rar

**Comment by hufans** [comment]
cocos2dx 传说中的一裤裆bug 1k bug vs 12k star

**Comment by knoxHuang** [comment]
已经修复，2.0.5 版本可验证

**Comment by sean-looong** [comment]
并没有修复v2.1.0
