### ISSUE TITLE
Moving particle emitter moves particles as well

### ISSUE THREAD

**Issue by corpana** [cocos/cocos-engine#3348]
### Creator version?（版本号）
2.0.2

### Affected platform?（受影响的平台）

Web
### How to reproduce?（如何重现）

https://discuss.cocos2d-x.org/t/moving-particle-emitter-moves-particles-as-well/40145?u=emarine26

**Comment by ggnewt** [comment]
I second this bug. This would be a very helpful fix.

**Comment by Salmakis** [comment]
Any updates here? Still a very annoying bug :(
cocos creator 2.1.0 in browser target

**Comment by ggnewt** [comment]
Hi Annika R -

No updates that I am aware of.. :(

**Comment by zhefengzhang** [comment]
Hello, verify on version 2.4.5, there is no such problem. You can refer to this pr https://github.com/cocos-creator/Engine/pull/5320 manually modify your engine. Custom Engine can be referenced: https://docs.cocos.com/creator/2.0/manual/en/advanced-topics/engine-customization.html?h=%E5%AE%9A%E5%88%B6

**Comment by ggnewt** [comment]
Hi Zhang - Thanks for the follow up on my particles issue. Unfortunately, I
won't be able to verify the fix as I've moved projects and haven't run
cocos creator in many months.

Regards,
Greg
