### ISSUE TITLE
微信小游戏项目调用cc.game.end()  报错：close is not defined

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#3369]
微信小游戏项目调用cc.game.end()  报错：close is not defined

### Creator version 2.0.2
![image](https://user-images.githubusercontent.com/35944775/46783994-05576180-cd5f-11e8-9db9-2879765011cd.png)

### Affected platform?（受影响的平台）
wechatGame

### How to reproduce?（如何重现）
执行cc.game.end()；

### JavaScript output or error produced?（报错信息和调用栈）
close is not defined

### Demo project?（demo 项目
[test_ccgame_end.zip](https://github.com/cocos-creator/engine/files/2467554/test_ccgame_end.zip)
）

**Comment by jareguo** [comment]
已修复，感谢反馈
