### ISSUE TITLE
ios10以下es6语法错误

### ISSUE THREAD

**Issue by caochao** [cocos/cocos-engine#3375]
### JavaScript output or error produced?（报错信息和调用栈）

ERROR: SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode., location: jsb-adapter/engine/jsb-node.js:28:8
这是jsb-adapter的语法错误。用户脚本project.js已经被转译成了es5，为什么adapter不能转译一下

**Comment by zhefengzhang** [comment]
你好，这应该是之前旧版本的时候疏忽了，给你带来迟到的歉意。很抱歉。我这边验证 2.4.5 版本已经没有这个问题了。你可以试试看。
