### ISSUE TITLE
[2.0.2] EXACT_FIT 适配模式效果不对。

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#3392]
### Creator version?（版本号）
2.0.2

### How to reproduce?（如何重现）

var size = cc.view.getDesignResolutionSize();
cc.view.setDesignResolutionSize(size.width, size.height, cc.ResolutionPolicy.EXACT_FIT);
cc.Canvas.instance.alignWithScreen();

**Comment by JarvisMMMM** [comment]
能尽快改这个吗？各位大大们啊

**Comment by sss316** [comment]
求求快修复这个bug，等的好急

**Comment by wangyhzzz** [comment]
官方是放弃EXACT_FIT了吗？ 2.0.7 问题依然存在

**Comment by zhefengzhang** [comment]
好的，请问异常效果是什么？

**Comment by zhefengzhang** [comment]
你好，在 2.4.5 版本测试，这个接口是可以正常使用的。问题关闭。
