### ISSUE TITLE
Webview position is wrong after build.

### ISSUE THREAD

**Issue by cmontiel** [cocos/cocos-engine#3397]
### Creator version?（版本号）

2.0+

### Affected platform?（受影响的平台）

Exporting to 'web mobile'.

### How to reproduce?（如何重现）

Add a WebView and make a build. The webview moves to a wrong place when you resize the browser.

**Comment by micahli** [comment]
same bug!

**Comment by cmontiel** [comment]
It's fixed in 2.1 RC4
