### ISSUE TITLE
Build Failed: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by linml** [cocos/cocos-engine#3415]
Build Failed: TypeError: Cannot convert undefined or null to object 
这种错误如何查看；
TypeError: Cannot read property '_uuid' of null 
如何定位？ 有删除过meta文件

**Comment by yeshao2069** [comment]
出现这种问题的可能是，你场景里面或者prefab里面丢失资源了。
如果出现异常报错，建议附件一个Demo(可以复现问题情况的简易Demo即可)，便于我们排查定位问题，感谢反馈。
另外，目前最新的Creator 2.x系列为 Cocos Creator 2.4.5，Creator 3.x系列为3.1.0。也可以使用最新版本试试。
