### ISSUE TITLE
Mask无法屏蔽遮罩外面的触摸事件

### ISSUE THREAD

**Issue by shangchihh** [cocos/cocos-engine#3417]
### Creator version?（版本号）
2.0.2

### Affected platform?（受影响的平台）

Web 

### How to reproduce?（如何重现）
创建一个ScrollView，ScrollView含有Mask组件。在ScrollView里面添加一些子节点，如Button、Toggle。点击位置落在Mask的外面时，ScrollView的子节点依然可以监听到触摸事件。

希望的结果是：Mask可以屏蔽遮罩外面的触摸事件。

### JavaScript output or error produced?（报错信息和调用栈）

无。

### Demo project?（demo 项目）

无。

**Comment by knoxHuang** [comment]
这个已经在 2.0.5 版本修复了，
