### ISSUE TITLE
Mask Fade-out

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#3439]
It would be very useful if the mask-component would support opacity, so that you could fade-out the masked area. This could be done for example with a stencil image.

**Comment by Ronsku** [comment]
Maybe I didn't explain this clear enough. My thought was to use the stencil image alpha values to create the transparency in the masking, instead of having hard edges with a static alpha threshold.

If the alpha threshold would be removed you could create sharp edges and smooth fade-out edges of your masks.

Let me know if you need more detailed explanation. This feature would be huge for many things!

**Comment by jareguo** [comment]
There is no easy way to do this. Currently Mask does not cull out child nodes in shader, but in gl stencil, which doesn't support alpha blending. To support alpha blending, we need to inject the blending code into every builtin or custom shaders, and compute screen positions in it. You can use a render texture to bake the nodes in the mask, and display it in a custom shader.

cc @2youyou2

**Comment by Ronsku** [comment]
I understood this is difficult. Are there any plans on implementing a gradient masking at any point?

**Comment by jareguo** [comment]
You should be able to do this in Shader
See https://docs.cocos.com/creator/manual/en/render/effect.html
https://github.com/2youyou2/transitions
