### ISSUE TITLE
[2.0.4] Graphics 设置透明度无效 

### ISSUE THREAD

**Issue by k8w** [cocos/cocos-engine#3441]
### Creator version?（版本号）
2.0.4

### Affected platform?（受影响的平台）

Web & All

### How to reproduce?（如何重现）
1. 新建一个Graphics节点，绘制任意内容
1. 修改节点的opacity为50

### 期望结果
半透明

### 实际结果
不透明

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈。直接设置节点的透明度不会改变 Graphics 组件内与作图颜色和透明度有关的设置的，可以参考 [相关文档](https://docs.cocos.com/creator/2.1/manual/zh/components/graphics.html?h=graphi) 中关于颜色和样式的部分 。
