### ISSUE TITLE
[2.0.4] 勾选自动释放资源后，Spine动画无法正常播放

### ISSUE THREAD

**Issue by k8w** [cocos/cocos-engine#3442]
### Creator version?（版本号）
2.0.4

### Affected platform?（受影响的平台）

所有

### How to reproduce?（如何重现）
1. 场景放一个Spine动画，勾选【自动释放资源】
2. 切到其它场景，再切回来
3. Spine动画无法播放

**Comment by caochao** [comment]
是无法播放还是图片全乱了？

**Comment by k8w** [comment]
无法播放 没图

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈！在v2.1.2版本的样例项目中 Spine 工作正常没有出现类似的问题，您可以直接用新版本的编辑器进行测试。
