### ISSUE TITLE
[2.0.5  rc2] mask和多摄像机 mask前面节点都显示为白色，后面节点显示正常

### ISSUE THREAD

**Issue by hulifu** [cocos/cocos-engine#3461]
###2.0.5 rc2?（版本号）
### Affected platform?（受影响的平台）
谷歌浏览器和模拟器
一个摄像机负责把场景所有的节点显示到nodeA的组件sprite上，另一个摄像机负责把nodeA到屏幕上
一旦有mask话，mask前面节点都显示为白色，后面节点显示正常
https://forum.cocos.com/t/cocos-creator-v2-0-5-1030-rc-2/68353/151?u=hulifu

**Comment by Marssssssss** [comment]
属于 api 使用层面的问题， 待 @jareguo 确认之后关闭该 issue

**Comment by jareguo** [comment]
let gl = cc.game._renderContext;
texture.initWithSize(cc.visibleRect.width, cc.visibleRect.height, gl.STENCIL_INDEX8);

可以参考摄像机的文档说明，需要传第三个参数
https://docs.cocos.com/creator/manual/zh/render/camera.html?h=camera5
