### ISSUE TITLE
creator v2.0.2编辑器下onDestroy会被调用两次

### ISSUE THREAD

**Issue by wellziy** [cocos/cocos-engine#3465]
编辑器下通过Node Tree窗口删除node时，node上面executeInEditMode的component的onDestroy会被调用两次。

**Comment by zhefengzhang** [comment]
你好，在 2.4.5 版本测试以下代码，并不会出现你说的那个情况，测试结果是只会调用一次。

![图片](https://user-images.githubusercontent.com/35944775/119968947-8d5a0a80-bfe0-11eb-858d-ec741cdc1a92.png)
![图片](https://user-images.githubusercontent.com/35944775/119968961-90ed9180-bfe0-11eb-982c-e43e13afa21a.png)
