### ISSUE TITLE
小游戏安卓截图保存相册显示不全

### ISSUE THREAD

**Issue by zilongshanren** [cocos/cocos-engine#3489]
需要修改 CCView.js

![image](https://user-images.githubusercontent.com/785541/48251357-4e710300-e43c-11e8-91fd-e344b7f321d8.png)

```
        if (view.isRetinaEnabled()) {
            if (cc.sys.platform === cc.sys.WECHAT_GAME && cc.sys.os == cc.sys.OS_ANDROID) {
                devicePixelRatio = view._devicePixelRatio = window.devicePixelRatio || 1;
            } else {
                devicePixelRatio = view._devicePixelRatio = Math.min(2, window.devicePixelRatio || 1);
            }
        }

```

**Comment by pandamicro** [comment]
感觉这是安卓微信的 bug ？

**Comment by zhefengzhang** [comment]
目前 2.4.5 和 3.1.0 版本还没有改过这个代码，得下礼拜验证下这个问题，再决定修改。

**Comment by zhefengzhang** [comment]
使用 2.4.5 测试，在 一加 8 T 上没复现问题。
2.4.5 引擎代码：
![图片](https://user-images.githubusercontent.com/35944775/123379869-4d774a80-d5c1-11eb-9e22-e2b21c4e0a04.png)
测试 demo：
[002.zip](https://github.com/cocos-creator/engine/files/6713995/002.zip)
