### ISSUE TITLE
dragonBone不支持blendMode

### ISSUE THREAD

**Issue by caochao** [cocos/cocos-engine#3492]
![image](https://user-images.githubusercontent.com/1911170/48261004-94d45b00-e458-11e8-8636-676bbe1a872a.png)

CCSLOT.js直接return了，这是还没完成吗？有计划吗？
https://github.com/cocos-creator/engine/blob/2.0.5/extensions/dragonbones/CCSlot.js

**Comment by caochao** [comment]
@pandamicro @jareguo 现在cc.Scale9Sprite都没了，这块要怎么改呀？_renderDisplay属性也没赋值了.
现在用的是2.0.1的creator。看文档应该是要拿到显示节点的RenderComponent来设置blendFunc吧？

**Comment by caochao** [comment]
大佬关注一下呀

**Comment by jareguo** [comment]
@sunnylanwanjun 有空麻烦透露下我们现在的重构情况

**Comment by sunnylanwanjun** [comment]
这块已经改了，这周会提个dragonbones的pr，到时我发个pr链接上来，稍微等待一下。

**Comment by caochao** [comment]
感谢
