### ISSUE TITLE
v2.0.5 ios9 使用用ttf字体真机运行黑屏

### ISSUE THREAD

**Issue by caochao** [cocos/cocos-engine#3507]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）
ios

### How to reproduce?（如何重现）
场景上放个label, 设置ttf自定义字体

### JavaScript output or error produced?（报错信息和调用栈）

ERROR: ReferenceError: Can't find variable: Promise, location: jsb-adapter/jsb-builtin.js:3008:35

### Demo project?（demo 项目）

![image](https://user-images.githubusercontent.com/1911170/48465238-28bd7280-e81d-11e8-9fd0-1dccb4215054.png)

怀疑是加载字体使用了promise导致没法在ios9上跑

**Comment by zhefengzhang** [comment]
应该是的。得测试看看

**Comment by xianyinchen** [comment]
ios9上的 jsc 引擎没有提供promise，需要自己安装第三方的promise插件，可以参考论坛帖子
https://forum.cocos.org/t/ios-promise/54883/5?u=huanxinyin
