### ISSUE TITLE
龙骨动画闪烁

### ISSUE THREAD

**Issue by KaloFreeze** [cocos/cocos-engine#3508]
### Creator version?（版本号）
1.10.2WIN

### Affected platform?（受影响的平台）

目前测试 网页上正常播放 但是在安卓上出现闪烁

### How to reproduce?（如何重现）
只要动画有透明度 就会出现

**Comment by caochao** [comment]
我2.0 release合并c++版龙骨动画，部分龙骨动画位置会跳动。网页上则正常

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
