### ISSUE TITLE
More enhanced project Manager

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#3511]
A more enhanced project Manger would be very helpful. Especially when working with multiple projects.
Something with custom icons(stored in project folder), an "open project directory" button and maybe a "delete project from HDD" button. 

![moreusefulprojectselect](https://user-images.githubusercontent.com/8083536/48475535-54c8fb80-e7fd-11e8-95db-8b745d584f13.png)

**Comment by jareguo** [comment]
Thanks, we will implement it in the next-generation editor.
