### ISSUE TITLE
creator 1.10.2 微信小游戏勾选ES6转换报错“__require is not defined”

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#3518]
![image](https://user-images.githubusercontent.com/8321365/48542461-2b41ca00-e8fa-11e8-93b4-233ec8cbacbe.png)

主要是勾选es6，微信会强制严格模式，导致这里报错。
把 __require 改成 var __require 就没问题！

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，请您在最新版本上测试一下，如果还有这个问题的话可以上传一份 demo 以便于我们更好地解决这个问题。

**Comment by jareguo** [comment]
> 2018 年的，暂时关闭吧，我找不到问题记录了～ [Awkward]
