### ISSUE TITLE
RichText appearance bug

### ISSUE THREAD

**Issue by utkayd** [cocos/cocos-engine#3527]
Hello,
We are using cocos-creator to deliver games for quite some time, and we've recently been occupied with upgrading the games from v1.9 to v2.x. While most of our scenes transformed rather easily, we've noticed a bug with the RichText component, and scenes using it. When we use a richtext component that is either not enabled or has 0 opacity, we change the text by editing its RichText's "string" component, and want to make it fadeIn to the scene. But in cocos v2, whenever we set the RichText's string to a new string, it briefly appears on the screen and disappears(all for opacity=0, enabled=false, or node's active=false conditions). I think the engine makes it appear after being set, but immediately notices that it should not be visible on the screen and makes it disappear. 
Problem can be recreated by using the below method on any scene by inserting a RichText to a node with 0 opacity or or to a node that's inactive or by adding the RichText component to a visible node but disabling the RichText component. The problem persists in all the aforementioned conditions. We tackled the issue by a workaround of scaling the node containing the RichText to 0 before setting the string, and then setting the scale to an appropriate number after the text is set.

`testLoop() {
    this.testLabel.string =
      "<b><color=#ff638e>LoopCount:" + this.loopCount + "</c>";
    setTimeout(() => {
      this.loopCount++;
      this.testLoop();
    }, 1000);
  }`
PS: The problem existed on both v2.0.1 and v2.0.5.

**Comment by caryliu1999** [comment]
Thank you for your feedback. This problem has been fixed by [pull/3528](https://github.com/cocos-creator/engine/pull/3528).
