### ISSUE TITLE
shader精度highp报错

### ISSUE THREAD

**Issue by lulukdog** [cocos/cocos-engine#3532]
Creator 版本： 2.X

目标平台：web

详细报错信息，包含调用堆栈： Failed to compile fs 0 (ln 4): 'highp' : precision is not supported in fragment shader

重现方式：启动即黑屏

手机型号 ：CHM-TL00

手机浏览器 ： X5内核

编辑器操作系统 ：安卓 4.4.2

出现概率： 用户报，自己尝试未浮现

**Comment by xianyinchen** [comment]
这个是GPU的兼容性问题，跟硬件有关，把源码中的 highp 替换成 mediump 就可以避免这个问题，但是渲染精度会所损失。

**Comment by lulukdog** [comment]
> 这个是GPU的兼容性问题，跟硬件有关，把源码中的 highp 替换成 mediump 就可以避免这个问题，但是渲染精度会所损失。
已经修改，提到线上。多谢
