### ISSUE TITLE
无法自定义引擎 gulp build 没有生成/engine/bin/.cache/dev

### ISSUE THREAD

**Issue by bigbanana** [cocos/cocos-engine#3546]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）
gulp build 然后设置自定义引擎

### JavaScript output or error produced?（报错信息和调用栈）
can not find ... /engine/bin/.cache/dev

**Comment by ColinCollins** [comment]
2.0 之后的版本脚本都是在打开编辑器的时候自动编译的，不需要通过 gulp build 进行编译脚本了。
这个情况之前有偶然遇到过一次，你首先确认 engine 版本以及 编辑器版本对应，同时在偏好设置中勾选自动编译脚本。
找不到缓存路径可能是 engine 路径设置错误，建议尝试重开编辑器。
最终还是不行的话建议重新配置自定义引擎，重新安装编辑器。

若不是 engine 功能问题建议直接在论坛发帖求助。@bigbanana
