### ISSUE TITLE
布局组件缺少居中功能！

### ISSUE THREAD

**Issue by llj1107984843** [cocos/cocos-engine#3549]
http://ae01.alicdn.com/kf/HTB1RBeqXZfrK1Rjy1Xd761emFXaJ.png
暂时用了两布局组件实现了

**Comment by llj1107984843** [comment]
并且 布局组件导致  一个节点移动给另外一个当孩子  撤销一下  节点是回来了  但是场景里位置错了

**Comment by ColinCollins** [comment]
关于组件功能问题请查阅相关功能手册文档。
https://docs.cocos.com/creator/manual/zh/components/widget.html
如果有功能上的 bug 反馈，请提交准确 bug 复现环境描述，并且在能力范围内提供辅助效果展示如：截图，动图，demo 等。
