### ISSUE TITLE
场景加载监听bug  2.05 与 1.9.3 都一样

### ISSUE THREAD

**Issue by llj1107984843** [cocos/cocos-engine#3550]
cc.director.on(cc.Director.EVENT_BEFORE_SCENE_LOADING, function(){
            // console.log("加载新场景之前所触发的事件");
            PopupNotice.playLoadAnim();
        });
        cc.director.on(cc.Director.EVENT_BEFORE_SCENE_LAUNCH, function(){
            // console.log("运行新场景之前所触发的事件");
        });
        cc.director.on(cc.Director.EVENT_AFTER_SCENE_LAUNCH, function(){
            // console.log("运行新场景之后所触发的事件");
            PopupNotice.stopLoadAnim();
        });

第一：为什么一个游戏从头开始  先打印的是【运行新场景之后所触发的事件】，不应该是【加载新场景之前所触发的事件】这个吗？
第二：运行新场景之前所触发的事件打印在【LoadScene 3142a967-48d1-4a67-aaed-3729642760e7: 1.742919921875ms】之后，不应该是之前吗

**Comment by knoxHuang** [comment]
第一个：没有你说到先打印 **运行新场景之后所触发的事件**
![image](https://user-images.githubusercontent.com/7564028/49277667-5f51e900-f4bd-11e8-9430-3caf0f35ccd4.png)

第二个，EVENT_BEFORE_SCENE_LAUNCH 表示到是**运行新场景**之前，而不是加载场景之前，所以这个是正常到表现
