### ISSUE TITLE
两个重叠的mask导致显示异常

### ISSUE THREAD

**Issue by fkworld** [cocos/cocos-engine#3551]
### Creator version?（版本号）
2.0.2

### How to reproduce?（如何重现）
依次创建两个mask，后一个mask如果为IMAGE_STENCIL模式，则会导致前一个mask显示异常。

### JavaScript output or error produced?（报错信息和调用栈）

无报错信息

### Demo project?（demo 项目）

https://gitee.com/fkworld/cocos_bug_demo

**Comment by fkworld** [comment]
更新到2.0.5版本后无法复现

**Comment by knoxHuang** [comment]
这个在 2.0.5 已经修复了，推荐更新到 2.0.5
