### ISSUE TITLE
2.1 release rotateTo旋转不正确

### ISSUE THREAD

**Issue by bigbanana** [cocos/cocos-engine#3554]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）
Web

### How to reproduce?（如何重现）
更换引擎2.1release
使用cc.rotateTo(2, 60);多次调用发再会重复旋转，并且在旋转开始目标旋转就会发生改变（满足最小角度导致的Bug？）

**Comment by bigbanana** [comment]
可能描述得不是很准确，可以新建一个项目试一下，一直调用rotateTo，会发现旋转一开始就会设置一个角度，产生抖动，并不是平滑的。很突兀

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈。这个情况我在 v2.1.2 上对 sprite 连续调用 rotateTo 没有出现抖动的问题，您可以用新版本的 creator 试试或者描述得再具体一些吗？（有 demo 的话当然是最好的了）

**Comment by OnlyKoei** [comment]
你好，用2.4.4版本也无法复现你描述的这个问题。如果你还能复现的话，可以联系我们，非常感谢！
