### ISSUE TITLE
[2.0.5 Editor] Ghost colliders remain "attached" in the editor scene after changing node's parent

### ISSUE THREAD

**Issue by AntonShalgachev** [cocos/cocos-engine#3555]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）

Windows Editor / Web

### How to reproduce?（如何重现）
* Create 2 nodes on the same level in hierarchy:
  * Create empty node (say, 'Objects')
  * Create node (say, 'Player') with RigidBody & PhysicsBoxCollider
* Make 'Player' a child of 'Objects' by dragging 'Player' with the mouse onto 'Objects'
* Move\scale scene in the editor with the mouse

### JavaScript output or error produced?（报错信息和调用栈）

No

### Demo project?（demo 项目）

https://github.com/AntonShalgachev/cocos-creator-bug-demo (scene 'ghost-collider')

**Comment by zhefengzhang** [comment]
At version 2.4.5, this problem did not appear.
