### ISSUE TITLE
[2.0.5 Editor] Component data is lost when reverting node with several components of the same type

### ISSUE THREAD

**Issue by AntonShalgachev** [cocos/cocos-engine#3557]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）

Windows Editor / Web

### How to reproduce?（如何重现）
* Create an empty node (say, 'Player')
* Add 2 PhysicsBoxCollider components to the 'Player' node with different data (e.g. size, offset, density etc)
* Save this node as a prefab
* Press "Go Back" on the top of the "Properties" while 'Player' node is selected (effectively reverting this node to the prefab)

### JavaScript output or error produced?（报错信息和调用栈）

No

### Demo project?（demo 项目）

https://github.com/AntonShalgachev/cocos-creator-bug-demo (scene 'multi-component-revert')

**Comment by zhefengzhang** [comment]
This problem does not appear in version 2.4.5
