### ISSUE TITLE
[2.0.5 Editor] Joint anchor handle jumps to the top-right after moving it with the mouse (on a node with non-zero size)

### ISSUE THREAD

**Issue by AntonShalgachev** [cocos/cocos-engine#3558]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）

Windows Editor / Web

### How to reproduce?（如何重现）
* Create an empty Node (named, say, 'Player')
* Set its size to (100, 100)
* Add RigidBody and WeldJoint to it
* Try to move joint anchor handle on the scene with the mouse

### JavaScript output or error produced?（报错信息和调用栈）

No

### Demo project?（demo 项目）

https://github.com/AntonShalgachev/cocos-creator-bug-demo (scene 'anchor-handle-offset')

**Comment by Marssssssss** [comment]
Thank you for raising this issue and sorry for my late reply, this bug is going to be fixed on version v2.1.3.
