### ISSUE TITLE
facebook打包后不能正常上传

### ISSUE THREAD

**Issue by ayarami** [cocos/cocos-engine#3575]
[https://discuss.cocos2d-x.org/t/the-bundle-config-file-included-in-this-upload-has-an-invalid-configuration-facebook-instant-games/44706](https://discuss.cocos2d-x.org/t/the-bundle-config-file-included-in-this-upload-has-an-invalid-configuration-facebook-instant-games/44706)
fb上传规则修改，选择fb平台构建后不能上传，之前正常。
在fbapp-config.json中添加navigation_menu_version字段后上传成功。

**Comment by VisualSJ** [comment]
已经修复，请在下个版本回归测试
