### ISSUE TITLE
Rotated Particle Systems nodes don't emit into world space correctly.

### ISSUE THREAD

**Issue by ggnewt** [cocos/cocos-engine#3579]
### Creator version?（版本号）
v2.0.1

### Affected platform?（受影响的平台）

Windows Editor

### How to reproduce?（如何重现）
Set a particle system to emit in "Free" mode.
Rotate that particle system node with animation.
Watch particles now emit locally and spin with animated node.
![cocos_particle_rotation_bug](https://user-images.githubusercontent.com/43218307/49342776-43ad2680-f614-11e8-8a73-eb4c3a7072c8.gif)

**Comment by ColinCollins** [comment]
Would you mind providing your demo for us to verify your problem?

**Comment by ggnewt** [comment]
Yes, I'd be happy to.  What's the best way to get it to you?

Thanks, Greg

**Comment by ColinCollins** [comment]
Just drag your zip or dmg file to GitHub comment block, it will be available for others.

**Comment by ggnewt** [comment]
[ParticleRotationBug.zip](https://github.com/cocos-creator/engine/files/2657991/ParticleRotationBug.zip)

Here's the project with the particle rotation bug.

**Comment by ColinCollins** [comment]
Hi, @ggnewt ，I checked your demo, Ummm, but I didn't get what's the problem you have met....
What's wrong with this demo?

**Comment by ggnewt** [comment]
Particles emitting into "Free" world space work correctly when the emitter is translating. When the emitter rotates, the particles rotate with the emitter, as if it was emitted with "Group" or local space. The particles should not rotate with the emitter if the are emitting into world space (Free mode).  Here is an example showing the difference.  Cocos doesn't emit particles into world space, or Free mode correctly.
![cocos_particle_rotation_bug_02](https://user-images.githubusercontent.com/43218307/49831349-7eb40600-fd48-11e8-9b46-c119ad65342b.gif)

**Comment by ColinCollins** [comment]
![gif](https://user-images.githubusercontent.com/35832931/49845147-87681300-fe00-11e8-86db-e92024e979d8.gif)
@ggnewt  Ummm, I get what's your means totally, but our engine particleSystem has a little bit different with others probably. so you need to change some setting for the particleSystem.
![image](https://user-images.githubusercontent.com/35832931/49845272-f8a7c600-fe00-11e8-97d8-197bd910215a.png)
[ __here is the related doc__ ](https://docs.cocos.com/creator/api/zh/classes/ParticleSystem.html)

Absolutly, There are some problems existing, we will fix it, but not immediate. please be patient, Thx for your feedback.

**Comment by ggnewt** [comment]
Hi ColinCollins - Thanks for you response, I appreciate it. Please allow me to explain my point a little differently as I don't think I explained it quite right the first time.  The Cocos Manual states "Free" mode as:

**FREE
Living particles are attached to the world and are unaffected by emitter repositioning.**

Repositioning should be defined to include both both translation and rotation.  Currently, Cocos doesn't honor rotation with it's "Free" mode. The instant any rotation is added to an emitter, the particles then emit as if they were in "Group" mode. To fix this, the trajectory of the particles needs to be disconnected from the rotation of the emitter.

Think of it like this, if you had a turret that shot snowballs and you rotated the turret after you shot a snowball, the snowball would not change it's trajectory no matter how fast you rotated the turret. In Cocos right now, every snowball you shoot rotates with the turret _after_ it's shot out from the cannon.

I see how your example of "Radius" works for an emitter that rotates one direction at a constant speed. However, that would not work if the emitter translates or rotates in the opposite direction. I've included an example in the attached gif.   Hopefully, this is a clearer explanation of my point.

![cocos_particle_rotation_bug_03](https://user-images.githubusercontent.com/43218307/49909861-6cfc5c80-fe35-11e8-9155-ba6d69d124ce.gif)  
Thanks for your time, please feel free to ask if anything is unclear.  

Thanks so much,
Greg
