### ISSUE TITLE
图片资源下载失败，loadRes 仍返回成功。

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#3580]
creator 2.0.5
构建web-mobiel，然后删除指定的图片文件，然后使用loadRes单独下载该文件，下载仍成功，但是纹理为空。
[LoadRes.zip](https://github.com/cocos-creator/engine/files/2637728/LoadRes.zip)

**Comment by ColinCollins** [comment]
2.0.5 测试没问题啊，按照你的要求构建完成之后我删除了 flight1 之后：
![image](https://user-images.githubusercontent.com/35832931/49362503-ebf8e300-f719-11e8-9053-31b85d9c7665.png)
你是不是没删干净， uuid 的记录存储和文件都要删除啊

**Comment by SantyWang** [comment]
@ColinCollins 这里没问题，只是err返回的数据是空数组，我已经修复了

**Comment by pandamicro** [comment]
@xianyinchen
