### ISSUE TITLE
 ios10.3.3 或者更低版本 语音没播放完就停止了

### ISSUE THREAD

**Issue by Flickering-Alvin** [cocos/cocos-engine#3600]
由于项目遇到这个问题比较紧急，麻烦大神们解决一下
### Creator version?（版本号）
v1.10.2  v2.0.5

### Affected platform?（受影响的平台）

iOS
### How to reproduce?（如何重现）
ios10.3.3 或者更低版本，cc.audioEngine.playEffect 播放一段语音，最后几百毫秒没有播放完。

### Demo project?（demo 项目）

https://demo.mathufo.com/h5/test/sample.rar

**Comment by zhefengzhang** [comment]
你好，这个压缩包下载下来显示损坏了。请你重新发一个音频文件给我测试。

**Comment by zhefengzhang** [comment]
用户长时间没有回复， issues 暂时关闭。
