### ISSUE TITLE
编辑器界面卡死

### ISSUE THREAD

**Issue by xingfude123** [cocos/cocos-engine#3601]
### Creator version?（版本号）
V2.1.0

### Affected platform?（受影响的平台）
Windows Editor

### How to reproduce?（如何重现）
控制台报错后,整个编辑器界面无响应.
![image](https://user-images.githubusercontent.com/27794684/49558357-afa9ca80-f945-11e8-8dcf-52917135f89e.png)

**Comment by ColinCollins** [comment]
你好，感谢你的反馈。由于你当前提供的报错信息不够完善导致我们无法锁定这个问题起因。建议提供更详细的信息反馈，详细的实现环境描述，复现操作描述，这有助于我们快速的定位这个问题起因，以尽快解决你当前可能遇到的问题。@xingfude123

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
