### ISSUE TITLE
ObjectLayer images of the TiledMap are gone

### ISSUE THREAD

**Issue by genxium** [cocos/cocos-engine#3611]
### Creator version?（版本号）
I'm using Creator v2.1.0 MAC, but I just upgraded from v1.9 MAC which doesn't have this issue.

### Affected platform?（受影响的平台）

Mac Editor, Web.

### How to reproduce?（如何重现）
I've attached the intact "TMX+TSX+PNG" files in this [big_trunks.zip](https://github.com/cocos-creator/engine/files/2659431/big_trunks.zip) for reproduction of the issue. You can import the file "big_trunk/map.tmx" into any node with a cc.TiledMap component of a completely new CocosCreator v2.1.0 project, e.g. right under CanvasNode to see how it behaves differently from that of a v1.9.1 project.

The expected behavior was provided by v1.9.1, that the image objects in layer named "SomeViewableObjects" are displayed both in Editor and runtime. However, these image objects are NOT displayed either in Editor or runtime while using v2.1.0.

The screenshots below were taken using Tiledv1.1.5 and Creatorv2.1.0.
![screen shot 2018-12-08 at 1 25 25 pm](https://user-images.githubusercontent.com/4541971/49682395-4ca76780-faee-11e8-934e-8efb7d3115a2.png)
![screen shot 2018-12-08 at 1 21 38 pm](https://user-images.githubusercontent.com/4541971/49682405-82e4e700-faee-11e8-9f4f-edfe4f7f7e1e.png)
![screen shot 2018-12-08 at 1 26 07 pm](https://user-images.githubusercontent.com/4541971/49682406-86786e00-faee-11e8-8e18-0436d5fde52f.png)

### JavaScript output or error produced?（报错信息和调用栈）

No it doesn't produce any error or warning message. However I found a similar issue already raised here but not resolved https://github.com/cocos-creator/engine/issues/3449.

### Demo project?（demo 项目）

Please see "How to reproduce" for relevant information. I'll attach a minimum demo project if further required.

**Comment by genxium** [comment]
I noticed that in master-branch, [cc.TiledLayer](https://github.com/cocos-creator/engine/blob/master/cocos2d/tilemap/CCTiledLayer.js) is currently a subclass of cc.RendererComponent whilst [cc.TiledObjectGroup](https://github.com/cocos-creator/engine/blob/master/cocos2d/tilemap/CCTiledObjectGroup.js) is not. Is that a cause of the issue here?

EDITED: In the source code of branch v1.9 they are both direct subclass of cc._SGComponent. 

- https://github.com/cocos-creator/engine/blob/v1.9/cocos2d/tilemap/CCTiledObjectGroup.js
- https://github.com/cocos-creator/engine/blob/v1.9/cocos2d/tilemap/CCTiledLayer.js

**Comment by sunnylanwanjun** [comment]
We have fix the issue，please wait for v2.3
https://github.com/cocos-creator/engine/pull/4245
