### ISSUE TITLE
Facebook Instant Games crash on new Chrome Mobile 71 - Fullscreen issue

### ISSUE THREAD

**Issue by kreys** [cocos/cocos-engine#3612]
### Creator version?（版本号）

both 2.0.2 and 2.0.5

### Affected platform?（受影响的平台）

Android - Messenger Instant Games with newest Chrome 71.0.3578

### How to reproduce?（如何重现）

Just start the build on Messenger on android with newest Chrome 71.0.3578

### JavaScript output or error produced?（报错信息和调用栈）

`TypeError
fullscreen error`

This error is 100% reproducable on every android Messenger game when user update Chrome (webview) to the newest version 71.0.3578. Chrome did some changes to fullscreen mode, and here's an error stack trace:

`22533: return element[this._fn.requestFullscreen]();`
`22544: theScreen.requestFullScreen(element, onFullScreenChange);`

See screen from crash reporting for full context from the non minified version of engine:
![image 2018-12-09 02-11-01](https://user-images.githubusercontent.com/4800087/49692337-67162b00-fb58-11e8-9673-ca0d3f96ca2d.png)

This error is really serious, for now it happenes for about 10% of users (everyone that got Chrome update).

Do you have any idea how to fix it, any workarounds?

**Comment by kreys** [comment]
Does this have anything in common with Chrome 71 supporting new optional parameter of `requestFullscreen` function, which previously was not available?

> These are just a few of the changes in Chrome 71 for developers, of course, there’s plenty more.

>The Element.requestFullscreen() method can now be customized on Android and allows you to choose >between making the navigation bar visible versus a completely immersive mode where no user agent >controls are shown until a user gesture is performed.

New api:
https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

**Comment by unace** [comment]
I just disabled "AutoFullScreen" to avoid this error. I don't know what the "AutoFullScreen" feature is, but my game looks working well on FIG without it.
in main.js
cc.view.enableAutoFullScreen(
                    cc.sys.browserType !== cc.sys.BROWSER_TYPE_BAIDU &&
                    cc.sys.browserType !== cc.sys.BROWSER_TYPE_WECHAT &&
                    cc.sys.browserType !== cc.sys.BROWSER_TYPE_MOBILE_QQ
                );
to 
cc.view.enableAutoFullScreen(
                    false
                );

**Comment by wijesijp** [comment]
I am also getting the error. 
setting the fullscreen to false didn't worked for me.

Is there a fix for this?

**Comment by zhefengzhang** [comment]
From an error, the prohibited request full screen should be able to solve the problem.

I don't know how to test this problem through Chrome? Can you tell me what the test is?

**Comment by zhefengzhang** [comment]
The user has not replied for a long time and is temporarily closed.
