### ISSUE TITLE
_globalOrderOfArrival溢出导致图层错位

### ISSUE THREAD

**Issue by joelyoung** [cocos/cocos-engine#3635]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）
所有平台

### How to reproduce?（如何重现）
反复切换界面

### JavaScript output or error produced?（报错信息和调用栈）
无

反复切换界面或者多次创建删除对象后, _globalOrderOfArrival超过65535溢出, 导致后续所有新节点图层错位

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，可以在最新版本的 creator 上面测试一下是否还有这个问题吗？

**Comment by zhefengzhang** [comment]
你好，请说明反复切换界面或者多次创建删除对象后这句话里面，需要切换多少次？创建多少次才能出现这个问题？

**Comment by zhefengzhang** [comment]
用户长时间没有回复，暂时关闭此 issues。
