### ISSUE TITLE
Color Swatch in Sprite Node UI Not Updating.

### ISSUE THREAD

**Issue by ggnewt** [cocos/cocos-engine#3639]
### Creator version?（版本号）
v2.1.0

### Affected platform?（受影响的平台）

Windows

### How to reproduce?（如何重现）

Create a sprite node with a sprite.
Add an animation node to that Sprite.
Create an animation curve.
Change the color to different colors over the length of the animation.
Save and close the animation curve.
Open the animation for edit again.
Drag around on the timeline, scrolling back and forth through the animation for 10-20 seconds and notice that the color swatch does not update any longer.

When viewing any keyframe on the color channel, notice that the color displayed in the UI swatch does not match the data in the color swatch picker.

**Comment by ggnewt** [comment]
![colorswatch_bug](https://user-images.githubusercontent.com/43218307/50020817-1190b280-ff8c-11e8-96ad-11dbd42a149a.png)

**Comment by ggnewt** [comment]
[ColorSwatch_Bug.zip](https://github.com/cocos-creator/engine/files/2681315/ColorSwatch_Bug.zip)

**Comment by Marssssssss** [comment]
Thank you for raising this issue and sorry for this late reply! Color Swatch Picker is used for color picking but not color showing by our design. In this version this situation is normal.
