### ISSUE TITLE
cc.Label fade-in blinking issue 

### ISSUE THREAD

**Issue by celp** [cocos/cocos-engine#3649]
### Creator version?（版本号）
v2.1.0

### Affected platform?（受影响的平台）
Mobile / Web / Mac Editor

### How to reproduce?（如何重现）
```
    this.label.node.opacity = 0;
    this.label.node.runAction(cc.sequence(cc.delayTime(1.0), cc.fadeIn(1.0)));
```
Label is blinking before fade-in.
Making a delay before fade-in makes the issue clear.

### JavaScript output or error produced?（报错信息和调用栈）
None.

### Demo project?（demo 项目）
[NewProject.zip](https://github.com/cocos-creator/engine/files/2691892/NewProject.zip)

Movie:
[LabelFadeInIssue.zip](https://github.com/cocos-creator/engine/files/2691898/LabelFadeInIssue.zip)

**Comment by fkworld** [comment]
补充：
1. 此bug在2.0.8版本上也存在。
2. 此bug在label节点为子节点，父节点fadeIn()时也存在。
3. fadeTo()时也存在。

**Comment by dnvuanh** [comment]
pump, any solution to work around ?

**Comment by fkworld** [comment]
1. 在2.0.9版本中已经修复。
2. 使用`opacity=1`来代替`opacity=0`。

**Comment by jareguo** [comment]
fixed in 2.0.9
