### ISSUE TITLE
Camera 渲染到纹理，如果与Sprite 组件使用的是相同纹理，而且Sprite的分组和Camera一致，会导致WebGL渲染报错 

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#3654]
rendertexture有个问题，就是把sprite的纹理设置成camera的targetTexture的目标，如果这个sprite的分组是与camera的分组一样，这时候就会出现渲染报错。 glDrawElements: Source and destination textures of the draw are the same.

[rendertexture.zip](https://github.com/cocos-creator/engine/files/2694529/rendertexture.zip)

**Comment by pandamicro** [comment]
哦那肯定啊。。。不能这么做，这样就死循环了
