### ISSUE TITLE
render-flow的sourcemap很混乱，无法调试

### ISSUE THREAD

**Issue by yafacex** [cocos/cocos-engine#3684]
### How to reproduce?（在chrome里调试）
![image](https://user-images.githubusercontent.com/7322814/50437700-df853600-0925-11e9-92c8-b75bfaa5bb95.png)

**Comment by yafacex** [comment]
貌似是core/renderer  core/value-types目录下的文件的source-map都有问题  core/platform目录下的就没事 CCDirector也没事

**Comment by zhefengzhang** [comment]
你好，在 2.4.5 版本上测试，并没有这个问题，请升级编辑器版本解决，感谢你的反馈。
