### ISSUE TITLE
iOS 下 Safari 視窗變化無反應

### ISSUE THREAD

**Issue by Serisu** [cocos/cocos-engine#3687]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）
iOS 

### How to reproduce?（如何重现）
在 GameCanvas 上面疊一層夠長的 div，使用 Safari 開啟後滑動 div 使網址列隱藏，會觸發 resize 事件，但是引擎沒有處理

交叉檢查後發現是 Safari 的 clientWidth 與 clientHeight 會永遠鎖定在網址列顯示時的長寬

目前修改 CCView.js 將 cc.sys.BROWSER_TYPE_SAFARI 如同 cc.sys.BROWSER_TYPE_WECHAT_GAM 使用 window.innerWidth, window.innerHeight 暫時可以解決

**Comment by zhefengzhang** [comment]
你好，请你调试一下引擎代码的这个函数，它是引擎监听 resize 事件触发时的回调，如果有触发 resize 事件，那么这个回调就会执行：
![图片](https://user-images.githubusercontent.com/35944775/119758425-1ab23780-bed9-11eb-80c0-584a16c7d1bd.png)

另外请你把你修改之前和修改之后的代码截图发出来看下。

**Comment by zhefengzhang** [comment]
用户长时间没有回复，暂时关闭此 issues。
