### ISSUE TITLE
2.1.0正式版渲染BUG

### ISSUE THREAD

**Issue by kyrnii** [cocos/cocos-engine#3702]

**Comment by 472225640** [comment]
使用了正交相机，很奇怪，玩很久会出现一次，重新加载场景后就会恢复正常，出现一次就卡得不行，直接没法玩，很头大，求大佬们帮忙看一下

**Comment by 472225640** [comment]
微信小程序线上版本（拥挤城市大感染）比较明显，出现的时候可以看到左边的白云和后面添加的白云明显不一样了
