### ISSUE TITLE
资源后缀名没有完全去掉，比如 samp_audio.mp3?useDom=1, 生成的的path= samp_audio.mp3?

### ISSUE THREAD

**Issue by seiyap70** [cocos/cocos-engine#3733]
https://github.com/cocos-creator/engine/blob/e8a39abcdf26bfe4556a747f68c289b5ec0544ff/cocos2d/core/load-pipeline/asset-table.js#L164

**Comment by Marssssssss** [comment]
您好，谢谢反馈。 example-cases 的11_network/downloader-web/downloader-web 范例里面我在 url 后面添加 ?useDom=1 后缀可以进行正常下载，您可以具体描述下是在什么场合引入资源出现的这个问题吗？（有demo当然是最好的了~）

**Comment by zhefengzhang** [comment]
用户长时间没有继续处理问题，此 issues 暂时关闭。
