### ISSUE TITLE
RichText used custom font can not works 

### ISSUE THREAD

**Issue by ayarami** [cocos/cocos-engine#3739]
### Creator version?（版本号）
Version 2.0.7

![image](https://user-images.githubusercontent.com/20372902/50968306-992efa00-1515-11e9-9384-7280809c1384.png)

it works on version 2.1 and other versions:
![image](https://user-images.githubusercontent.com/20372902/50968288-8fa59200-1515-11e9-979f-25bf7a4ee5c5.png)

but it can not work on version 2.0.7.
![image](https://user-images.githubusercontent.com/20372902/50968360-c2e82100-1515-11e9-846f-c25d18733375.png)

**Comment by Marssssssss** [comment]
Thanks for raising this issue and sorry for this late reply, it proves that this problem has been fixed on version 2.1.
