### ISSUE TITLE
cc.follow()逻辑异常

### ISSUE THREAD

**Issue by fkworld** [cocos/cocos-engine#3747]
### Creator version?（版本号）
2.0.5

### Affected platform?（受影响的平台）

在Web中异常，其他平台未测试过

### How to reproduce?（如何重现）
新建2个node，nodeA.runAction(cc.follow(nodeB))，nodeA的运动逻辑异常。
按照描述，nodeA会跟随nodeB运动，如果B停止，则A停止。
但是实际上会反向一直移动，移动速度可能与nodeB的坐标变动大小有关。

### JavaScript output or error produced?（报错信息和调用栈）

无报错信息

### Demo project?（demo 项目）

工程：
https://github.com/fkworld/game_01_cocos_bug_demo
代码：
https://github.com/fkworld/game_01_cocos_bug_demo/blob/master/assets/BugDemo/Bug_ccfollow/Bug_ccfollow.ts

我查看了cc.follow()的源码部分：
https://github.com/cocos-creator/engine/blob/eff43cc656979bee32e745f898d33cb330778428/cocos2d/actions/CCAction.js#L525-L541

这里的计算有两点不是很明白：
1. 为什么step每次执行时都要重新计算1次delta
2. 为什么最后的位置要加上半个屏幕大小的偏差delta.add(this._halfScreenSize)

我个人在项目中使用到了节点跟随的功能，但是是自己写的一个小工具，想参考一下官方的实现。
如果引擎组能抽空解答一下我的疑惑是再好不过了~

**Comment by Marssssssss** [comment]
您好，谢谢反馈！这个功能是较老的功能，您可能是理解成了节点跟随节点这种类型的功能，但是实际上它主要实现的是子节点在父节点背景中类似摄像机跟随的功能。当子节点移动的时候会让父节点向相反方向移动以产生镜头跟随的观感，那些计算是为了实现这个功能而进行的~~
