### ISSUE TITLE
The game will pause for almost 10 sec after power off and on in wechat game in iOS

### ISSUE THREAD

**Issue by fuyifan** [cocos/cocos-engine#3750]
### Creator version?（版本号）
2.0.7

### Affected platform?（受影响的平台）

wechat game in iOS platform

### How to reproduce?（如何重现）
push the power button to switch off the screen. After some seconds, show the screen.

### Demo project?（demo 项目）

One thread in the forum discussed this issue and someone responsible for the engine proposed to set the preserveDrawingBuffer to false. I tried and it works. However, i don't know why not revise the code in github directly.

**Comment by zhefengzhang** [comment]
Already added in version 2.1.2. https://github.com/cocos-creator/engine/pull/4537
