### ISSUE TITLE
Unable to change editbox input flag: setReturnType not implemented

### ISSUE THREAD

**Issue by smellypotato** [cocos/cocos-engine#3753]
### Creator version?（版本号）
v1.10.2

### Affected platform?（受影响的平台）
iOS / Android / Simulator (Native JSB)

### How to reproduce?（如何重现）
Set input flag of editbox to any one of them in editor
Create a button that call a function to change the input flag to any other
`this.editbox.inputFlag = cc.EditBox.InputFlag.PASSWORD;`

### JavaScript output or error produced?（报错信息和调用栈）

setReturnType not implemented

### Other information
Web platform can run normally, I need to implement a button to change the password visibility by changing the input flag

**Comment by smellypotato** [comment]
The input flag is changed when clicking the button, if you click the button to change the input flag then click the editbox, the visibility is changed. The problem is that it does not change dynamically i.e. click button then change the visibility of current input without further interaction

**Comment by OnlyKoei** [comment]
hi, this kind of dynamic modification is already supported in version 2.4.4.
