### ISSUE TITLE
Label字数太多，导致顶点数超过限制，显示存在bug

### ISSUE THREAD

**Issue by ayarami** [cocos/cocos-engine#3763]
### Creator version?（版本号）
2.1

### How to reproduce?（如何重现）
Label中字数太多，顶点数超过65535的限制，导致显示出现bug

### JavaScript output or error produced?（报错信息和调用栈）
![image](https://user-images.githubusercontent.com/20372902/51291598-a03c9780-1a42-11e9-862a-42f847bd4d06.png)

**Comment by yeshao2069** [comment]
使用最新的版本 Cocos Creator 3.0 测试，目前的Label的纹理是限制 2048 * 2048。
如果文本内容超过纹理的大小，则多余部分不显示，不会导致报错。
测试内容：13W+英文字符(超过65535个)
测试：Web、微信小游戏
![image](https://user-images.githubusercontent.com/14273437/109133089-904e2080-778f-11eb-9859-462778453627.png)
