### ISSUE TITLE
android9.0 设备识别出现问题，cc.sys.os 返回linux。华为meta20pro 版本9.0 

### ISSUE THREAD

**Issue by Tlioylc** [cocos/cocos-engine#3768]
### Creator version?（版本号）
2.0.1版本

### Affected platform?（受影响的平台）

android平台9.0版本
### How to reproduce?（如何重现）

打包成web游戏后,获取当前设备系统平台信息错误
### JavaScript output or error produced?（报错信息和调用栈）

无报错
https://github.com/cocos-creator/engine/blob/42b297e9f0d18dfb930567b1e344bd173043d0d0/cocos2d/core/platform/CCSys.js#L747
webview提供的user-agent为 (Linux; Android 9;........导致正则匹配错误
建议修改代码：
var uaResult = /android (\d+(?:.\d+)*)/i.exec(ua) || /android (\d+(?:.\d+)*)/i.exec(nav.platform);

**Comment by Tlioylc** [comment]
星号被隐藏了- -，把最后一个加号改为星号，亲测可用

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
