### ISSUE TITLE
F12 key not working when Cocos Creator is opened (Mac)

### ISSUE THREAD

**Issue by AndreyPostelzhuk** [cocos/cocos-engine#3786]
### Creator version?（版本号）
Creator version is 2.1.0

### Affected platform?（受影响的平台）
Bug is reproduced in Mac Editor

### How to reproduce?（如何重现）
Just open Cocos Creator and navigate to the another app (VS code for example)
F12 key is not working when editor opened. F12 works in combination with other key. For example Shift+F12 works. But F12 alone not working.

**Comment by zhefengzhang** [comment]
Hello, is this shortcut invalid on vscode?

<img width="900" alt="图片" src="https://user-images.githubusercontent.com/35944775/121783206-e4b2ca00-cbdf-11eb-8fe5-92d14f6f7ee5.png">

**Comment by zhefengzhang** [comment]
Since you have not replied for a long time, temporarily close.
