### ISSUE TITLE
cc.sys.languageCode在安卓平台返回不完整

### ISSUE THREAD

**Issue by zhandouxiaojiji** [cocos/cocos-engine#3788]
### Creator version?（版本号）
2.0.7

### Affected platform?（受影响的平台）

安卓(华为)

### How to reproduce?（如何重现）
在PC浏览器上能返回zh-cn, zh-tw等区码，但在打包到手机上返回的却是zh，跟cc.sys.languageCode的结果一样

**Comment by knoxHuang** [comment]
感谢反馈，该问题已经修复，会进入到 2.1.3 版本

这个是 -lite pr 你也可以自定义

https://github.com/cocos-creator/cocos2d-x-lite/pull/1784
