### ISSUE TITLE
TOUCH_MOVE like MOUSE_MOVE 

### ISSUE THREAD

**Issue by zonex5** [cocos/cocos-engine#3789]
How to make that TOUCH_MOVE fires at the node without initial TOUCH_START on it (like MOUSE_MOVE works)

**Comment by zhefengzhang** [comment]
TouchMove does not need to rely on TouchStart to trigger. Are you sure that your requirement is triggered by TouchMove without relying on TouchStart?

**Comment by zhefengzhang** [comment]
Since you have not replied for a long time, temporarily close.
