### ISSUE TITLE
Android html5 label shown as black box when node is too long

### ISSUE THREAD

**Issue by smellypotato** [cocos/cocos-engine#3790]
### Creator version?（版本号）
v.1.10.1

### Affected platform?（受影响的平台）
Android Web (Chrome)
### How to reproduce?（如何重现）
1. Create a node with label
2. Set overflow to Shrink
3. Set width of the node to any number > 4096 (2^12?)
4. Input some character (not necessary to fill the whole box, one or two char also work
4. Verify the label

May also be reproduced by setting the string to be very long with other overflow settings. Just make sure the width is greater than 4096

### JavaScript output or error produced?（报错信息和调用栈）
No error on console, but the whole node (not only the characters) appeared in black box

**Comment by Marssssssss** [comment]
Thank you for raising this issue and sorry for this late reply, this bug seems to have been fixed. Test this problem on new version please.
