### ISSUE TITLE
引擎初始化报错Can't find variable: performance

### ISSUE THREAD

**Issue by jigelang** [cocos/cocos-engine#3829]
引擎初始化报错：Can't find variable: performance
![log](https://user-images.githubusercontent.com/5381991/52099112-b0d93a00-260c-11e9-9e8c-dcbdae40d13f.png)

**Comment by zhefengzhang** [comment]
经过 caniuse 查询，应该是没法在 ios8.3 和 safari8.3 这两个低版本的系统上访问 performance
<img width="986" alt="图片" src="https://user-images.githubusercontent.com/35944775/121783410-0f515280-cbe1-11eb-873e-336c4cd54745.png">

https://caniuse.com/?search=performance
