### ISSUE TITLE
带有Scrollview 组件的界面 在0-1缩放展现后 初始ScrollOffset 不正确.

### ISSUE THREAD

**Issue by andrewlu1** [cocos/cocos-engine#3839]
### Creator version?（版本号）
CocosCreator 2.1.0 版本.

### Affected platform?（受影响的平台）

全平台.

### How to reproduce?（如何重现）
一个预置体, 其中包含一个ScrollView节点. 要实现预置体实例化后 由小到大 动画显示出来. 类似于弹窗界面.
同时在Script代码中动态向ScrollView的content中添加列表item.
此时content 可以滚动到 Scrollview 中间的位置, 也即顶部有一半的空白区. 同样的 滚动到底部后,底部也出现一半的空白区.
调试发现初始的Scrollview 的 getScrollOffset() != 0 而是等于 Scrollview 高度的一半. 
而未做缩放动画时, 初始的getScrollOffset() == 0. 

### Demo project?（demo 项目）

https://forum.cocos.com/t/scrollview-content/52212/8
论坛已有很多类似的反馈, 且已声明为新版本解决了, 但目前来看仍然存在此异常.

**Comment by andrewlu1** [comment]
https://forum.cocos.com/t/v2-1-0-scrollview/71260/5
这个帖子给出了解决方案:  
延迟0.1S 后手动调用一次. 
this.scParentNode.children[0].getComponent(cc.ScrollView)._calculateBoundary();
已确认可行. 但正常情况不应该调用私有的可能变化的API. 需要官方给出解决方案.

解决方案2: 
已证实是 因为 缩放起始值 scale =0 导致的.  因此做缩放动画时, 给scale一个非0的值 如0.1,即可解决此问题. 且不需要手动调用以上API.

**Comment by Marssssssss** [comment]
您好，谢谢反馈。论坛上的 demo 在 v2.1.2 调试效果是正确的：
1、循环数为3时：

![image](https://user-images.githubusercontent.com/42939682/62524307-f26eca00-b867-11e9-83f0-658f44165ba0.png)

2、循环数为30时：

![image](https://user-images.githubusercontent.com/42939682/62524509-55f8f780-b868-11e9-9d04-dfb2f56c06a4.png)

可以更换使用新版本的编辑器。
