### ISSUE TITLE
编辑器bug：自定义错误的cocos2d-x引擎路径后导致编辑器无法修改\保存项目设置

### ISSUE THREAD

**Issue by fkworld** [cocos/cocos-engine#3863]
### Creator version?（版本号）

2.0.5

### How to reproduce?（如何重现）

1. 新建一个空项目，打开项目-项目设置-自定义引擎-勾掉“使用内置cocos2d-x引擎”-新增任意错误的引擎路径，例如“E:\”。
2. 打开开发者-编译引擎。这是会输出“Compile engine finished”。
3. 再次打开项目设置，此时不可修改\保存任何东西，点击保存按钮会输出“Sorry, save failed. Cannot find simulator config.json under E:\simulator\win32\config.json”。

猜测可能原因是由于编译了错误的引擎后，无法依据错误引擎对项目设置进行修改。

### JavaScript output or error produced?（报错信息和调用栈）

Sorry, save failed. Cannot find simulator config.json under E:\simulator\win32\config.json

### Demo project?（demo 项目）

无

**Comment by fkworld** [comment]
给出一个临时的解决方案：
打开项目文件夹下 local/settings.json，修改/清理/删除此文件后，再次打开项目，则引擎设置会被重置。

**Comment by Marssssssss** [comment]
您好，谢谢反馈。按您说的步骤在 v2.1.2 不会出现不可修改\保存任何东西的情况，也没有出现报错，可以尝试使用最新版本的编辑器。
