### ISSUE TITLE
2.0.8 dragonBones.ArmatureDisplay 使用on注册事件触发不了

### ISSUE THREAD

**Issue by chenhongtu** [cocos/cocos-engine#3877]
### Affected platform 所有

dragonBones.ArmatureDisplay 使用on注册事件，2.0.8都触发不了，要用 addEventListener 注册就正常，之前2.0.5使用 on 是正常的

**Comment by KillerMeng** [comment]
会不会是因为节点上有Mask组件,版本2.0.9,如果node上有mask组件,on注册的点击事件无效

**Comment by sunnylanwanjun** [comment]
2.0.10已修复
