### ISSUE TITLE
引擎初始化报错Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.

### ISSUE THREAD

**Issue by jigelang** [cocos/cocos-engine#3902]
### Creator version?2.0.1

暂时无法重现
![error](https://user-images.githubusercontent.com/5381991/53312287-71da9380-38ef-11e9-96f3-c2b182eb336e.png)

**Comment by jestg** [comment]
cocos  版本 2.0.6

vivo手机 旋转屏幕 就会报 "TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，可以在最新版本的 cocos creator 上面测试一下吗？

**Comment by jestg** [comment]
> 您好，谢谢您的反馈，可以在最新版本的cocos creator上面测试一下吗？

cocos creator 2.1.2 小米 note3 出现同样的报错，并伴随黑屏。出现一次 检测到 小米 note3  不支持 WebGL 的信息

报错如下：

![image](https://user-images.githubusercontent.com/37201086/64222435-a5335600-cf02-11e9-8f88-a52c59e0b36d.png)

**Comment by zhefengzhang** [comment]
您好，这个报错可能是 WebGL 上下文崩溃了，这个问题应该属于特殊机型上对 webgl 的支持不好的原因，这边暂时没有解决方案建议。
这是我们这边 Android 测试机型
![图片](https://user-images.githubusercontent.com/35944775/124108308-af8bf000-da98-11eb-8fac-19ea30211d7f.png)

使用 2.4.5 测试 example-case 场景都没有遇到您这边的问题。您可以提供 demo 给我们测试看看哈。
