### ISSUE TITLE
Cocos Creator 2.0.9 video player set currentTime invalid during play

### ISSUE THREAD

**Issue by ayarami** [cocos/cocos-engine#4025]
### Creator version?（版本号）
2.0.9 2.0.8

when the video player is playing ,the "this._loaded" is always "false",this issue caused that set currentTime can not works
[https://forum.cocos.com/t/video-palyer/74853/3](https://forum.cocos.com/t/video-palyer/74853/3)

**Comment by knoxHuang** [comment]
已修复
