### ISSUE TITLE
cocos creator 1.8.1升级到2.1.0 切换场景的时候闪退

### ISSUE THREAD

**Issue by CrazyCodeLee** [cocos/cocos-engine#4040]
![image](https://user-images.githubusercontent.com/2958987/54338935-45a07000-466e-11e9-8bcb-5f5ccade1ab0.png)
看着这个图能看出来 切换场景的一瞬间直接能涨到 内存360多 然后有memory警告有时直接闪退 我看 场景文件大小是800K 现在是就iphone6 有这个问题 貌似就是1G内存的手机有这问题 能帮忙看下 我这个哪里操作错了吗  我需要提供什么呢。现在就等着上线遇到了这个问题 压力山大。

**Comment by yeshao2069** [comment]
你好，建议反馈此类问题的时候，可以附加一个可以复现问题的Demo，便于排查和问题跟踪。

目前2.x版本最新为2.4.5， 3.x版本最新为3.1.1(3.2.0的beta不计入)，你可以升级项目看看。

这边因为issue时间久远，这边先关闭，后续有任何问题或者反馈，可以重新提issue给我们，感谢反馈。
