### ISSUE TITLE
cc.view.setFrameSize 无效

### ISSUE THREAD

**Issue by xbwxxxxx** [cocos/cocos-engine#4092]
### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）

iOS / Android / Simulator / Web发布版
### How to reproduce?（如何重现）
运行必现，demo里点击按钮即可重现

### JavaScript output or error produced?（报错信息和调用栈）

无
### Demo project?（demo 项目）

[Demo_setFrameSize_2.0.9.zip](https://github.com/cocos-creator/engine/files/3000377/Demo_setFrameSize_2.0.9.zip)

**Comment by knoxHuang** [comment]
谢谢反馈，该 bug 已经记录

**Comment by wuzhiming** [comment]
@xbwxxxxx  这个API在native设置无效是正常的，因为我们没办法像在web上改变外框的大小（比如屏幕大小，窗口的大小）等，所以这个是正常的，所以请问你是需要实现什么功能需要native使用这个方法？

**Comment by yeshao2069** [comment]
这个API在native设置无效是正常的，因为我们没办法像在web上改变外框的大小（比如屏幕大小，窗口的大小）等，所以这个是正常的。
如果你还有其他的功能需求，可以再次反馈的哈。这个issue先关闭了。
