### ISSUE TITLE
cocosCreator2.0.9 ios平台 弱网状态下XMLHttp大概率crash！

### ISSUE THREAD

**Issue by olddriver3000** [cocos/cocos-engine#4095]
cocosCreator2.0.9 ios弱网状态下XMLHttp大概率crash Bug

用Android机器来做热点比较容易复现，因为Android热点关闭4g网络的时候不会顺带关闭热点。

https://forum.cocos.com/t/cocos2-0-9-ios-xmlhttp-crash-bug/75450

**Comment by zhefengzhang** [comment]
问题已修复，可以合并这个 pr 解决：https://github.com/cocos-creator/engine-native/pull/1724
