### ISSUE TITLE
audio音量設為0在chrome中仍會播放約0.01秒

### ISSUE THREAD

**Issue by meifujiwara** [cocos/cocos-engine#4111]
### Creator version?（版本号）
2.0.7 & 2.0.9

### Affected platform?（受影响的平台）

Web in chrome瀏覽器

### How to reproduce?（如何重现）
使用cc.audioEngine或cc.AudioSource播放音檔，將volume設為0，在chrome中仍會播放約0.01秒
cc.AudioSource只有第一次play會出現此問題

**Comment by Marssssssss** [comment]
https://github.com/cocos-creator/engine/pull/4767/files

该问题已修复
