### ISSUE TITLE
自动全图合双份图片数据

### ISSUE THREAD

**Issue by recoye** [cocos/cocos-engine#4122]
### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）
ALL

### How to reproduce?（如何重现）
自动合图里面有已经合过图的图片和plist文件（使用场，原UI已经合好一张图，使用自动合图把艺术数字合到同一张图里面）
目录结构：
ui
- ui.png
- ui.plist
- num.png
- num.labelatlas
- autoUI.pac

合成后的UI里面会有两份ui.png图片数据

### JavaScript output or error produced?（报错信息和调用栈）
无

### Demo project?（demo 项目）
https://github.com/recoye/autoAtls

**Comment by zhefengzhang** [comment]
嗯，现在默认是会把自动图集配置文件夹内的图片都打进图集。并且现在也没有办法标记文件夹中的某个图片不进行合图，确实不够灵活。

**Comment by zhefengzhang** [comment]
这边在 2.4.5 版本测试i，问题已经优化了。最终打出来的图片是这样的。
![图片](https://user-images.githubusercontent.com/35944775/126295821-206bd3fd-0675-4f7e-9bc8-fe3c2e3743ee.png)

测试demo：
[002.zip](https://github.com/cocos-creator/engine/files/6847067/002.zip)

请升级引擎版本体验~
