### ISSUE TITLE
typescrip下配置路径映射, 微信小游戏导出有错

### ISSUE THREAD

**Issue by huangliu** [cocos/cocos-engine#4132]
typescrip下tsconfig.json配置路径映射baseUrl和paths
网页正常, 但是微信小游戏上无法通过映射的路径取到模块, 微信中生成的代码如下.
<img width="443" alt="图片" src="https://user-images.githubusercontent.com/5343499/55457702-48fb9b80-561d-11e9-9d2c-0e9d28485df3.png">
只能识别为void 0, 想问下这部分导出逻辑在哪里可以修改, 我来改也行

**Comment by xianyinchen** [comment]
脚本的导出逻辑，没有开放源码，开发者没法修改，引擎构建的时候并没有读取 tsconfig.json 的 baseUrl 和 paths 配置，所以你可以尝试不配置 baseUrl 和 paths 的情况，是否可以使代码正常运行？

**Comment by zhefengzhang** [comment]
用户长时间未回复，issues 暂时关闭。
