### ISSUE TITLE
ios微信小游戏,EditBox组件InputFlag模式为PASSWORD时,文本颜色失效,只以默认白色渲染

### ISSUE THREAD

**Issue by gandou** [cocos/cocos-engine#4147]
### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）

ios微信小游戏上有问题
微信开发平台上是正常表现

### How to reproduce?（如何重现）
EditBox组件InputFlag模式为PASSWORD时,文本颜色失效,只以默认白色渲染

### JavaScript output or error produced?（报错信息和调用栈）

无

**Comment by PPpro** [comment]
已经反馈给微信，在下个微信版本里会修复这个问题
