### ISSUE TITLE
建议修改ColliderManager.removeCollider的CPU开销的问题

### ISSUE THREAD

**Issue by dracovash** [cocos/cocos-engine#4157]
对contacts的for循环中的 contacts.splice(i, 1); 语句，在对大量碰撞体（例如子弹）一帧内removeChild时会消耗大量的CPU时间，建议修改为双缓冲，push的效率相比splice有显著提高。

代码示例：
removeCollider: function (collider) {
	let colliders = this._colliders;
	let index = colliders.indexOf(collider);
	if (index >= 0) {
		colliders.splice(index, 1);
		
		let contacts = this._contacts;
		let newContacts = this._cachedContacts
		// swap cache
		for (let i = contacts.length - 1; i >= 0; i--) {
			let contact = contacts[i];
			if (contact.collider1 === collider || contact.collider2 === collider) {
				if (contact.touching) {
					this._doCollide(CollisionType.CollisionExit, contact);
				}
				
				//contacts.splice(i, 1);
			} else {
				// add contact not removed in newContacts
				newContacts.push(contact)
			}
		}
		this._contacts = newContacts
		this._cachedContacts = contacts
		this._cachedContacts.splice(0)
		collider.node.off(NodeEvent.GROUP_CHANGED, this.onNodeGroupChanged, this);
	}
	else {
		cc.errorID(6600);
	}
},

**Comment by fsyoungOcean** [comment]
使用樓主提供的方式
針對頻繁移除碰撞器的情形,CPU使用率顯著下降許多

**Comment by zhefengzhang** [comment]
感谢反馈，这确实是个性能优化点。我们会准备合并进引擎的。

**Comment by zhefengzhang** [comment]
你好，你反馈的优化建议目前已经在 CocosCreator 3.7.0 及以上版本优化了此问题。相关 issues 链接：https://github.com/cocos/cocos-engine/issues/12843
