### ISSUE TITLE
Nested ScrollViews do not work

### ISSUE THREAD

**Issue by asarazan** [cocos/cocos-engine#4191]
### Creator version?（版本号）
2.1.0

### Affected platform?（受影响的平台）
All

### How to reproduce?（如何重现）
Create a horizontal scrollview inside a vertical scrollview. The parent scrollview should be able to cancel events to the child scrollview when you try to scroll vertically. Instead it is impossible to scroll the parent vertically using touch events on the child.

**Comment by knoxHuang** [comment]
Sorry, this may require you to rewrite the interface to implement it, the engine will not do anything.
