### ISSUE TITLE
刚体和精体旋转方向

### ISSUE THREAD

**Issue by stonejiang208** [cocos/cocos-engine#4214]
刚体所在的父节点水平翻转后，刚体和精体旋转方向相反 测试代码   https://github.com/stonejiang208/rigid-test

**Comment by xianyinchen** [comment]
你好，物理引擎同步状态的时候，不会考虑节点的缩放系数，这种情况只能开发者在设计物理关联的UI元素时做下规避。
<img width="860" alt="WeChatf75ced692368b70bfa785b75c9124a84" src="https://user-images.githubusercontent.com/8321365/123730433-edd2b500-d8c8-11eb-9c1d-236424707877.png">
