### ISSUE TITLE
Android原生 Editbox键盘被底部导航栏遮挡

### ISSUE THREAD

**Issue by ayarami** [cocos/cocos-engine#4303]
https://forum.cocos.com/t/cocoscreator-editbox/77082

**Comment by ayarami** [comment]
@umbrellaPP

**Comment by PPpro** [comment]
可能是红米的虚拟导航栏适配的问题，暂时没有办法复现

这个 issue 就先关闭了吧，如果还有其他机型出现同样的问题再打开

**Comment by PPpro** [comment]
才发现没有权限 close issue @ayarami

**Comment by ayarami** [comment]
无法复现，关闭issue
