### ISSUE TITLE
Streaming Audio

### ISSUE THREAD

**Issue by asarazan** [cocos/cocos-engine#4309]
### Creator version?（版本号）
v2.1.0

### Affected platform?（受影响的平台）
Mac Editor Simulator

### How to reproduce?（如何重现）
Try to stream remote audio via the DOM: 
```javascript
var audio = document.createElement('audio')
audio.src = 'https://ia802508.us.archive.org/5/items/testmp3testfile/mpthreetest.mp3'
audio.load()
audio.play()
```

### JavaScript output or error produced?（报错信息和调用栈）
`HTMLElement audio.play is not a function`

Am I doing something wrong? Is there a way to stream audio from a server using the `<audio>` tag?

**Comment by knoxHuang** [comment]
The simulator is not a web platform, so audio tags are not supported.

you can try 

```js
cc.audioEngine.play('https://ia802508.us.archive.org/5/items/testmp3testfile/mpthreetest.mp3')
```

**Comment by asarazan** [comment]
Is that a valid method signature? It doesn't exist in creator.d.ts.
