### ISSUE TITLE
where save "javascript engine path" ?

### ISSUE THREAD

**Issue by masteage** [cocos/cocos-engine#4322]
### Question

* Where save  "JavaScript Engine Path", i want clear "JavaScript Engine Path" setting
* **detail**
   *  not good "JavaScript Engine Path" setting after
   * i don`t load project
   * i don`t setting "JavaScript Engine Path"

### Creator version?（版本号）

* branch - master (6ae92ca)

### Affected platform?（受影响的平台）

* Mac

### How to reproduce?（如何重现）

* "JavaScript Engine Path" setting after not able load project CocosCreator

**Comment by yeshao2069** [comment]
In the latest engine (Cocos Creator3.0.0), you can use the Cocos Creator logo at the top left of the editor panel -> Preferences -> Engine Manager
Method 1 Check to use the built-in JS engine, and then restart;
Method 2 After deleting the path of the custom JS engine, check to use the built-in JS engine and restart;
If you have used a custom engine and cannot open the Cocos Creator editor normally, you can try to delete the engine folder where the custom engine is located, and then open the editor, you will be prompted that the custom engine path used is wrong. Click OK to use the built-in engine by default.
