### ISSUE TITLE
没有数学库，无法正常3D开发。请开放vmath数学库

### ISSUE THREAD

**Issue by hubluesky** [cocos/cocos-engine#4326]
### How to reproduce?（如何重现）
没有数学库，无法正常3D开发。请开放vmath数学库

**Comment by yeshao2069** [comment]
你好，感谢反馈。
经过确认，
目前2.4.x.系列最新版本 2.4.5已经开放vmath数学库 https://github.com/cocos-creator/engine/tree/v2.4.6/cocos2d/core/value-types
3.x系列最新版本 3.1.1 已经开放vmath数学库 https://github.com/cocos-creator/engine/tree/v3.1-release/cocos/core/math
