### ISSUE TITLE
engine build use error

### ISSUE THREAD

**Issue by masteage** [cocos/cocos-engine#4347]
### Creator version?（版本号）

* master branch (36d6971bs)

### Affected platform?（受影响的平台）

* Mac

### How to reproduce?（如何重现）

* "JavaScript Engine Path" setting after fail

### JavaScript output or error produced?（报错信息和调用栈）

* **Error Msg**
```
Parsing file /Users/masteage/Desktop/test_libs/engin_test_01/cocos2d/core/3d/CCLightComponent.js: 'import' and 'export' may appear only with 'sourceType: module' (26:0)
```
 
<img width="420" alt="error" src="https://user-images.githubusercontent.com/13742619/56890028-402ea600-6ab3-11e9-93fb-734afaa83fbf.png">

**Comment by xianyinchen** [comment]
Hi, it is a business logic code error, please fix the error code first, then restart editor. the higher version of the editor can enter if an error is reported, you can try.
