### ISSUE TITLE
Gray border appeard in iOS browsers

### ISSUE THREAD

**Issue by corpana** [cocos/cocos-engine#4361]
### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）

Web on iOS

### How to reproduce?（如何重现）
1. Open [this url ](https://cocosreport.firebaseapp.com/)with iOS device.
2. You can see borders of images only in iOS browsers, not in desktop, android browsers.

> grey border screenshot
![image](https://user-images.githubusercontent.com/3689788/57824521-27c7b800-7750-11e9-87c1-1d839989eed8.png)

> [It doesn't happen when I make a demo html with the same font atlas image. So it is not iOS or iOS browser problem.](https://cocosreport.firebaseapp.com/htmltest.html)

### Demo project?（demo 项目）

Download a demo [here](https://cocosreport.firebaseapp.com/grayedge_problem.zip)

**Comment by xianyinchen** [comment]
In this case, you can configure the blend mode as follows:
<img width="666" alt="WeChatc57bc969e117f673937e944389434367" src="https://user-images.githubusercontent.com/8321365/123062154-d6b24400-d43e-11eb-932b-f3434673c4b9.png">

It will draw correct.
![2091624436459_ pic](https://user-images.githubusercontent.com/8321365/123062521-2f81dc80-d43f-11eb-92fc-fc464395649d.jpg)
