### ISSUE TITLE
Deactivating节点时，如需要反激活，应当是哪个节点

### ISSUE THREAD

**Issue by cjz9032** [cocos/cocos-engine#4404]
https://github.com/cocos-creator/engine/blob/19698da168bb0e2c10dd75f48cc192029fc4a9be/cocos2d/core/node-activator.js#L197

root的必须是canvas吗?
按我的理解,只要找到当前Deactivating Node的所有父和祖先都是可以的（即图中的X1或canvas）?

![image](https://user-images.githubusercontent.com/11435814/57580333-c34ff300-74da-11e9-8c0c-fa4207aee402.png)

**Comment by zhefengzhang** [comment]
不理解你的需求，请你详细描述一下你的需求。

**Comment by zhefengzhang** [comment]
用户长时间未回复，暂时关闭。
