### ISSUE TITLE
Action使用精度为FLT_EPSILON

### ISSUE THREAD

**Issue by cjz9032** [cocos/cocos-engine#4412]
https://github.com/cocos-creator/engine/blob/5c36b5b9957e377683c8570c951908c4bd5e3af5/cocos2d/actions/CCActionInterval.js#L156

虽然FLT_EPSILON也是可行(因为比最小精度大),但是不知道为什么不是使用Number.EPSILON呢?
是为了兼容其他的系统还还是什么考虑吗?

**Comment by xianyinchen** [comment]
你好， Number.EPSILON 是 ES6 新增的特性，考虑部分平台的兼容性问题，目前这块代码保持最初设计版本。
