### ISSUE TITLE
Android build produces corrupted paths

### ISSUE THREAD

**Issue by asarazan** [cocos/cocos-engine#4437]
### Creator version? 
2.1.1

### Affected platform?（受影响的平台）
Mac Editor & Android

### How to reproduce?（如何重现）
Create an Android Build. This happened during a release build for me.

### JavaScript output or error produced?（报错信息和调用栈）
It created a bunch of files with paths like this:
```
build/jsb-default/frameworks/runtime-src/proj.android-studio/app/property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, /Users/asarazan/stencil/SuperStory/build/jsb-default/frameworks/runtime-src/proj.android-studio/app/build/intermediates/merged_assets/release/out))/res/import/13/13f34a88-903e-4075-bca3-40e96cd74b38.3225f.json
```

Note specifically: `property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory...` as part of the full path.

**Comment by asarazan** [comment]
I just downgraded to 2.0.9 and the problem still exists. Please fix this as soon as you can! our Android app crashes instantly due to bad resource paths. I can't downgrade past 2.0.9 because of the cc.Label animation bug fix.

**Comment by asarazan** [comment]
Update: Can no longer repro on 2.0.9 so it might just be 2.1.1 -- the problem also coincides with installing the Facebook SDK in SDKBox. Unsure where the problem actually lies.

**Comment by yeshao2069** [comment]
Can you upgrade to the latest 2.4.5 version, and then try to have this problem?

**Comment by yeshao2069** [comment]
No reply for a long time, the issue is temporarily closed
