### ISSUE TITLE
cc.Assert.nativeUrl is wrong when "MD5 Cache" is on

### ISSUE THREAD

**Issue by id-ilych** [cocos/cocos-engine#4448]
### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）
Web / iOS / Android

### How to reproduce?（如何重现）
1. Add property of type `cc.Asset` and assign some file from assets directory
2. Access `nativeUrl` field and see that it matches the filename
3. Build with "MD5 Cache" option on
4. See that `nativeUrl` field doesn't match the filename (hash suffix is missing)

### Demo project?（demo 项目）
https://github.com/id-ilych/cc-asset-nativeurl-issue

One of the consequences of the problem is that CA certificates that are required for secure web socket connections on Android could not be configured this way as missing hash suffix prevents native code (`WebSocketImpl::createVhost`) from discovering the file. See https://github.com/cocos-creator/cocos2d-x-lite/issues/1722 for extra details.

Extra thought: Maybe "MD5 Cache" option should be totally excluded from mobile builds. As I understand it's only purpose is to invalidate browser caches in web builds but for mobile it doesn't make any sense. Am I missing something?

**Comment by PPpro** [comment]
hi, md5 won't be added to `cc.Asset.nativeUrl`
please use `cc.Asset.url` instead
