### ISSUE TITLE
The cocos engine does not limit the maximum width and height of the canvas canvas?

### ISSUE THREAD

**Issue by VYuLinLin** [cocos/cocos-engine#4451]
### Creator version?（版本号）
version 1.9.3

### Affected platform?（受影响的平台）

Web 
### How to reproduce?（如何重现）
When the browser is automatically reduced to a certain extent, the initial load and rendering will be maximized, and the height or width will exceed the visible range.

**Comment by zhefengzhang** [comment]
Maybe you didn't use canvas's Fit Hight and Fit Width correctly.
![图片](https://user-images.githubusercontent.com/35944775/125151880-eee2cc80-e17b-11eb-9da6-1c72fa2be17c.png)
https://docs.cocos.com/creator/1.9/manual/en/components/canvas.html#property
