### ISSUE TITLE
使用 cc.primitive 创建的 Quad 与 Sphere 无法正确绘制

### ISSUE THREAD

**Issue by youenough** [cocos/cocos-engine#4453]
### Creator version?（版本号）
v2.1.1

VertexData 构造函数[参数顺序](https://github.com/cocos-creator/engine/blob/master/cocos2d/core/3d/primitive/vertex-data.js#L12)如下：

```javascript
export default function VertexData (positions, normals, uvs, indices, minPos, maxPos, boundingRadius)
```

[quad.js](https://github.com/cocos-creator/engine/blob/master/cocos2d/core/3d/primitive/quad.js#L38) 与 [sphere.js](https://github.com/cocos-creator/engine/blob/master/cocos2d/core/3d/primitive/sphere.js#L59) 中返回的参数顺序有误，导致使用 primitive 创建的 3D 基础物体无法正确绘制

```javascript
// quad.js
return new VertexData(
  positions,
  indices,
  normals,
  uvs,
  minPos,
  maxPos,
  boundingRadius
);

// sphere.js
return new VertexData(
  positions,
  indices,
  normals,
  uvs,
  minPos,
  maxPos,
  boundingRadius
);
```

**Comment by xianyinchen** [comment]
This problem is fixed in version 2.2, please update to newer version.
