### ISSUE TITLE
节点关联脚本bug

### ISSUE THREAD

**Issue by deathnopool** [cocos/cocos-engine#4505]
### Creator version?（版本号）
win10 v2.0.9

### Affected platform?（受影响的平台）
 Web chrome

### How to reproduce?（如何重现）
1.  一个脚本game.js引用一个节点player(这个节点关联了一个脚本player.js)；
2. 修改player.js.  譬如加入新的方法run(){ console.log("run") }. 
3. 这时候game.js中用这个player实例调用run()会找不到run方法。从浏览器中查看player.js可以看到这个方法，但是实例对象里面却没有。

my solution: 先把节点关联的player.js脚本删掉，重新关联节点和player.js, 这时候在game.js中调用player.run()才不会出错。

### JavaScript output or error produced?（报错信息和调用栈）
Uncaught TypeError: this.game.player.run is not a function

**Comment by Marssssssss** [comment]
按照您说的方式无法重现bug，可以具体说说是如何引用的吗？

**Comment by OnlyKoei** [comment]
按您提供的方式，无法复现，用了2.0.10，2.4.4测试过，均未复现，可能在后续版本已经修复。如果您这边在2.4.4上仍能复现，可以联系我们。
