### ISSUE TITLE
About creator.d.ts

### ISSUE THREAD

**Issue by of28guino** [cocos/cocos-engine#4514]
Good day everyone, I am using cocos creator and I want to share my modifications of engine.d.ts, may it can be useful to other people and even for you, but I don't know where I can share it or create a pull request.

**Comment by Ronsku** [comment]
Awesome @of28guino, @jareguo can you assist him on creating a PR for this?

**Comment by jareguo** [comment]
Hi, the `creator.d.ts` is generated from source codes in the engine. So there's no direct way to merge your .d.ts file into Creator. Can you just upload the .d.ts file here, so we can check what changes you made and update our source codes for you. BTW, which version are you using?

**Comment by of28guino** [comment]
Hi, Thanks for answering, I am using Cocos Creator V2.1.1, at this moment I have no the code, but as soon I have my laptop I will share the extracts from code here.

**Comment by OnlyKoei** [comment]
If you have additional questions, contact us again, this issue first off
