### ISSUE TITLE
希望发布的时候，能检查一下发布的文档

### ISSUE THREAD

**Issue by zhitaocai** [cocos/cocos-engine#4515]
新的功能总是没文档，又或者总是缺这缺哪的文档，又或者直接给了一个与文档不符的.d.ts文件。(比如 **``tween``**)

与其说发布了一个面向开发者的版本，我更愿意理解为发布了一个面向引擎开发人员自身的版本，有点自嗨了。

对开发者很不友好，希望能完善下这方面

**Comment by Marssssssss** [comment]
您好，谢谢您的反馈，我们一直都有在持续地完善这个问题。
