### ISSUE TITLE
Creator 2.1.1 rendering problems

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#4546]
### Creator version?（版本号）
2.1.1

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）

Using an Array of cubes and replace theme while camera moves in one direction. If the camera have moved 100px the last cube moves to the front and stays in camera view.

There will be visible gab between the cubes, after the camera moved some distance and replaced the cube multiple times.

### JavaScript output or error produced?（报错信息和调用栈）
![Alt Text](https://github.com/inkfood/renderingProblems/raw/master/Media/small.gif)
### Demo project?（demo 项目）
https://github.com/inkfood/renderingProblems

**Comment by MarkusTieche** [comment]
Setting camera "near clip" to 1 or larger seems to solve to problem.
https://forum.cocos.com/t/creator2-1-1-z-fbx/78560

**Comment by yeshao2069** [comment]
Thanks for the feedback.
I tested it in your demo by changing the "near clip" of the camera and it works well.
I tested it in the latest Creator 2.x (2.4.5) and the default "near clip" is 1.
You can try to update your Creator version to 2.4.5 and try again, Thank you.
