### ISSUE TITLE
2.0.9 经常出现问题

### ISSUE THREAD

**Issue by hejunmingstrogner** [cocos/cocos-engine#4551]
Error: Uuid Loader: Deserialize asset [ /TagChineseWorl/library/imports/3f/3fe36dc5-0f83-40f7-96df-356ca7410c5e.json ] failed : TypeError: Cannot set property uuid of #<cc_Component> which has only a getter
 
Failed to load scene: Error: [AssetLibrary] loading JSON or dependencies failed: undefined
Task [load-scene-by-uuid] run error, stop running other tasks.

 2.0.9 上面这个cocos creator 经常出现这种问题，好像是library下面一个json  文件uuid不对，这是怎么回事？ 这个导致整个项目无法打开。

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
