### ISSUE TITLE
shader 顶点demo

### ISSUE THREAD

**Issue by godnotking** [cocos/cocos-engine#4605]
建议出一个在2.x版本中怎么使用顶点数据的demo，一直不懂怎么将顶点数据传到shader中使用

**Comment by xianyinchen** [comment]
文档中有自定义渲染的实现过程，可以帮助你理解顶点数据在引擎中的运用。将顶点提交到shader的底层实现流程，需要自己查看引擎代码，并学习关于使用GL接口提交顶点数据的实现。
https://docs.cocos.com/creator/2.1/manual/zh/advanced-topics/custom-render.html
