### ISSUE TITLE
[Feature Request] Widget "Keep aspect ratio"

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#4680]
Feature request: Widget "Keep aspect ratio"

### Creator version?（版本号）
2.1.1

### Affected platform?（受影响的平台）
All

### How to reproduce?（如何重现）
The idea would be to have a widget and give it a certain size according to how it works right now, but to be able to keep the aspect ratio of the image while still satisfy all given parameters.

Example 1:
- Container 500 x 500
- Button 200 x 100
![image](https://user-images.githubusercontent.com/7983358/60000288-927fe380-966c-11e9-86e0-1259d06f17c1.png)

With settings:
- New Keep aspect ratio check box checked [x] and following settings
![image](https://user-images.githubusercontent.com/7983358/60001272-ceb44380-966e-11e9-88d7-d29944a0db6a.png)
Would result in:
Start aspect ratio 200 x 100 -> (200 / 100 = 2)
End Aspect ratio 500px height and keep width with same aspect ratio:
x / 500 = 2
500 / 2 = x
500 / 2 = 250
Should result in a size of 500 x 250
![image](https://user-images.githubusercontent.com/7983358/60001328-eab7e500-966e-11e9-8068-426fcfc7b742.png)

Example 2:
- Same starting state
- Container 500 x 500
- Button 200 x 100
![image](https://user-images.githubusercontent.com/7983358/60000288-927fe380-966c-11e9-86e0-1259d06f17c1.png)

With settings:
- New Keep aspect ratio check box checked [x] and following settings
![image](https://user-images.githubusercontent.com/7983358/60002687-c6a9d300-9671-11e9-95bb-964be34463a1.png)
Would result in:
Start aspect ratio 200 x 100 -> (200 / 100 = 2)
End Aspect ratio 500px height and keep width with same aspect ratio:
500 / x = 2
500 * 2 = x
500 * 2 = 1000
Should result in a size of 1000 x 500
![image](https://user-images.githubusercontent.com/7983358/60003002-7717d700-9672-11e9-8302-72e2e7e57ef2.png)

Example 3:
- Same starting state
- Container 500 x 500
- Button 200 x 100
![image](https://user-images.githubusercontent.com/7983358/60000288-927fe380-966c-11e9-86e0-1259d06f17c1.png)

With settings:
- New Keep aspect ratio check box checked [x] and following settings
![image](https://user-images.githubusercontent.com/7983358/60003179-d1b13300-9672-11e9-9881-d52f9c768bff.png)
- Make sure both width and height is satisfied
- Do the same calculations as in example 2 since, height is the one that requires more adjustments
- End up in same size as in example 2
- Should result in a size of 1000 x 500
![image](https://user-images.githubusercontent.com/7983358/60003002-7717d700-9672-11e9-8302-72e2e7e57ef2.png)

For all other adjustments like adding 50% or some pixel value the calculations would be the exact same, but with different heigh/width values. The most important thing is that it covers all the requirements put into the component and keeps the default aspect ratio of the node's width/height.

If you have any questions regarding this, please don't hesitate to ask!

**Comment by yeshao2069** [comment]
Thanks for the feedback, I have synchronized this requirement to our development, and we may investigate the requirement for this feature in the next version.

**Comment by SantyWang** [comment]
I think it's a good feature, any references about this feature or maybe some other engine support this ? any info will help us, thanks
