### ISSUE TITLE
 Mac 无法显示更多菜单，点击显示更多菜单箭头 ↓是无反应的

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#4715]
### Creator version?（版本号）
v2.0.9

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）
任意可以弹出菜单，且在屏幕下方，并且菜单没法一次展示全部时
例如：

![QQ20190626-111523](https://user-images.githubusercontent.com/31087168/60148466-c6414180-9803-11e9-9586-6e8624e408b6.png)

![QQ20190626-161549](https://user-images.githubusercontent.com/31087168/60163217-ba6a7500-982d-11e9-8ae4-3692bbed68ab.png)

![QQ20190626-161800](https://user-images.githubusercontent.com/31087168/60163463-41b7e880-982e-11e9-8a3d-647047a102b2.png)

**Comment by yeshao2069** [comment]
感谢反馈。
经过确认，可能是早期编辑器版本的问题。
目前最新的2.4.x版本(2.4.5)，编辑器上的箭头为更多菜单按钮指示标识，不是用来点击，需要你一直往下滑动即可实现菜单选项的滚动。
![image](https://user-images.githubusercontent.com/14273437/120955837-df3f2500-c784-11eb-8b21-eb57d3bf46a4.png)

目前最新的3.x系列(3.1.1)，同上。
欢迎升级到最新版本重试，谢谢。
