### ISSUE TITLE
meta 文件在mac和window平台没保持一致！

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#4742]
mata文件在mac和window平台上的文件换行符没保持一致。
mac 是 **\r\n**
windows 是 **\n**

不但**没保持一致**，反而**是相反的**？

### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）

mac editor、windows editor

### How to reproduce?（如何重现）
1、mac系统上新建任意项目，新建任意会自动生成meta文件的文件。
2、上传这个项目到git 上面
3、windows从git下载这个项目，并打开这个项目！
4、等待项目加载完毕后，git status 观察meta文件，会发现它已经发生了变化！
5、可选的，可以用十六进制文件查看器比较两个文件，会发现原本mac上的meta文件中的换行符是0x0D, 0x0A，而window上的换行符竟然是0x0A！

**Comment by xianyinchen** [comment]
Creator生产的meta文件，都是使用的\n换行符，你可以新建个资源，在不提交git的情况下，立即查看meta的文件的换行符。
你的问题可能是git配置不对引起的，可以参考这个帖子
https://forum.cocos.org/t/topic/101484

**Comment by huazizhanyes** [comment]
by [xianyinchen](https://github.com/xianyinchen)
我按照你的说法去配置了，可是meta 文件还是会被git 所检测到
