### ISSUE TITLE
2.0.10版本ccscrollView的上的滚轮事件，会失效的问题

### ISSUE THREAD

**Issue by jigelang** [cocos/cocos-engine#4758]
### Affected platform?Web pc（受影响的平台）
做了个tab形式的界面，两个界面都有ccScrollView组件，切换tab，使他们active的值变化，当首次进来是，可以使用滚轮，但是切换一次回来之后滚轮事件就不好用了

**Comment by Marssssssss** [comment]
您好，这个bug您那里有demo吗？

**Comment by jigelang** [comment]
> 您好，这个bug您那里有demo吗？

2.0.10的更新了一个小版本已经解决了
