### ISSUE TITLE
cretor 2.0.10 label CHAR模式 字母底部被裁剪

### ISSUE THREAD

**Issue by ghost** [cocos/cocos-engine#4800]
开启 label 的 CHAR 模式之后，“qqpy” 底部裁剪，显示如下图：

![1](https://user-images.githubusercontent.com/10294716/60566763-7ed62a80-9d9a-11e9-8a7d-6e33093edced.png)

**Comment by knoxHuang** [comment]
该问题已经在 2.1.2 中修复了，可能到话，麻烦升级到最新版本在验证一次
