### ISSUE TITLE
在微信开发者工具中异常报错

### ISSUE THREAD

**Issue by Hideer** [cocos/cocos-engine#4808]
### Creator version?（版本号）
2.0.10

### Affected platform?（受影响的平台）

微信开发平台

### How to reproduce?（如何重现）
在进行弹窗中按钮执行场景切换的时候报错；
在浏览器中是没问题的

### JavaScript output or error produced?（报错信息和调用栈）

![image](https://user-images.githubusercontent.com/31301552/60635486-93233180-9e45-11e9-94e2-4de25e19b48a.png)

**Comment by Marssssssss** [comment]
谢谢您的反馈，这里已经修复了报 gameThirdScriptError 的问题，请在下一个版本出来以后再测试一下。

**Comment by Marssssssss** [comment]
您好谢谢您的反馈，我这里使用 2.0.10 版本在 example-cases 上面的菜单点击按钮进行测试没有出现您说的状况，您可以在最新版本上测试一下，若还有该问题可以提供一份 demo 以便于这里更快地定位问题。

**Comment by Marssssssss** [comment]
上面的关联的 PR 与该问题无关，请忽略这个错误的关联

**Comment by yeshao2069** [comment]
使用Cocos Creator 2.4.4 测试 example-cases的菜单点击按钮 无法复现这个问题。您可以在最新版本上测试一下，若还有该问题可以提供一份 demo 以便于这里更快地定位问题。
