### ISSUE TITLE
Label 的 overflow 属性 SHRINK 和 CacheMode 属性的 CHAR 冲突

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#4841]
### Creator version?（版本号）
v2.0.9

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）
>1、新建一个Label控件，设置 overflow 属性为 SHRINK，设置 CacheMode 属性为 CHAR
>2、关闭自动换行功能
>3、随意设置一个node的宽高。
>4、随机设置Label的文本，不断向内添加字符。

将会下列结果中任意一个：
>字符能全部在范围内的正常显示
>超过了范围但是没缩小字
>完全看不到了任何字了
>正常显示部分截断掉部分。

**Comment by yeshao2069** [comment]
感谢反馈。
经过测试和验证，你反馈的这个问题已经被修复了。
测试creator版本：2.4.5
测试设备：macbookpro   11.3.1
测试操作步骤：
1、新建一个场景，新建一个Label控件，设置 overflow 属性为 SHRINK，设置 CacheMode 属性为 CHAR
2、关闭自动换行功能
3、随意设置一个node的宽高 100*100。
4、随机设置Label的文本，不断向内添加字符  （labeltest12345678900987654321...）。

测试截图：
![image](https://user-images.githubusercontent.com/14273437/123211812-8a2a3f80-d4f6-11eb-986e-511411054230.png)
测试功能：
[NewProject_1.zip](https://github.com/cocos-creator/engine/files/6706736/NewProject_1.zip)
你可以升级版本至(2.x系列)最新版本 2.4.5试试，谢谢。
