### ISSUE TITLE
重命名

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#4868]
### Creator version?（版本号）
v2.0.9

### Affected platform?（受影响的平台）

Mac Editor 

### How to reproduce?（如何重现）
1、找到任意项目中的文件。
2、按回车进入重命名状态，任意输入内容。不按回车确认，按Esc取消

### 预期行为
放弃本次重命名操作

### 实际行为
文件已经被重命名

**Comment by knoxHuang** [comment]
已经修复，会进到 2.1.3 版本
