### ISSUE TITLE
运行时修改添加 PhysicsCollider 组件的 Node 的 group 属性，报错。

### ISSUE THREAD

**Issue by HengHuH** [cocos/cocos-engine#4942]
### Creator version?（版本号）
2.0.10

### Affected platform?（受影响的平台）

Web, maybe ALL
### How to reproduce?（如何重现）
为 node 添加 PhysicsCollider 组件
运行时修改 node 的 group 属性

### JavaScript output or error produced?（报错信息和调用栈）

collider not added or already removed
Can't find testFunc for (cc.PhysicsBoxCollider, $s). cc.BoxCollider

**Comment by HengHuH** [comment]
原因： PhysicsCollider 组件并没有交给 CollisionManager 管理。
NodeEvent.GROUP_CHANGED 触发后，获取 Node 上所有 Collider 组件（包含 PhysicsCollider）用来删除。

**Comment by knoxHuang** [comment]
未能重现，能否用 2.1.2 版本在测试一次呢？

**Comment by knoxHuang** [comment]
该问题已经修复
