### ISSUE TITLE
通过cc.audioEngine.play播放音乐，始终有一个音乐state等于cc.audioEngine.AudioState.ERROR

### ISSUE THREAD

**Issue by udzhou** [cocos/cocos-engine#4955]
问题：
由于播放的音乐state为error，cc.audioEngine便一直不能控制这个播放的音乐

### Creator version?（版本号）
Mac系统，creator v2.1.2

### Affected platform?（受影响的平台）
Web

### How to reproduce?（如何重现）
var aid = cc.audioEngine.play(clip, true, 1);
var state = cc.audioEngine.getState(aid);
如果第一次state正常，过段时间也会变成error

### JavaScript output or error produced?（报错信息和调用栈）
无

**Comment by udzhou** [comment]
找到bug了，重现情况：
var aid = cc.audioEngine.play(clip, true, 1);
cc.audioEngine.pauseAll();
var state = cc.audioEngine.getState(aid);
if (state == cc.audioEngine.AudioState.PAUSED) {
      cc.audioEngine.setLoop(aid, isLoop);
      cc.audioEngine.setVolume(aid, volume);
      cc.audioEngine.resume(aid);
}

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
