### ISSUE TITLE
希望能增强对typescript的支持。typescript写法和文档有很大出入

### ISSUE THREAD

**Issue by coolqingcheng** [cocos/cocos-engine#4958]
### Creator version?（版本号）2.1.2

- 比如cc.tween。在ts里面，需要写为new cc.Tween().target(obj).to(),但是to或者by等方法里面的所有参数都是必填的，只能自己修改，给不需要的参数加上问号。
- 新建的typescript脚本文件，类名为默认的NewClass，不是ts文件名称。刚开始半天引用不了。最后才发现是这个问题

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
