### ISSUE TITLE
无法在脊柱中设置材质？

### ISSUE THREAD

**Issue by omega-mk10** [cocos/cocos-engine#5024]
当Material（灰色着色器）设置为Spine数据时，显示变得奇怪
你可以修改它以便设置材料吗？
### Creator version?（版本号）
v2.1.2

### Affected platform?（受影响的平台）

Web
### How to reproduce?（如何重现）
let skeleton = this._spine.getComponent(sp.Skeleton);
skeleton.setMaterial(0, this._material);

### JavaScript output or error produced?（报错信息和调用栈）

No errors

**Comment by sunnylanwanjun** [comment]
May I have a look at your gray shader？You'd better copy the origin spine shader and modify it, or you may lost some internal value.

**Comment by omega-mk10** [comment]
it is complete. Thanks.
