### ISSUE TITLE
建议添加Editor环境专属文件夹

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#5121]
### Creator version?（版本号）
2.0.9

效果：
1、Editor环境下，跟普通资源一样能被正常使用
2、编译时。排除掉。不打包进入客户端

好处：
1、美术提供的图片可能包含布局预览图。可直接放到不会被编译的文件夹中，可直接放入场景里面，对照摆放控件，可精准对位。
2、自定义编辑器脚本。仅仅工作在编辑器模式下。
3、其他编辑器专属环境下用的素材什么的。

**Comment by xianyinchen** [comment]
你好，引擎目前没有这个计划，布局预览图的需求可以参考下面方法。
https://forum.cocos.org/t/ui/96354
