### ISSUE TITLE
TypeError: vb.destroy is not a function

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#5130]
### Creator version?（版本号）
2.0.9

### Affected platform?（受影响的平台）
Chrome

### How to reproduce?（如何重现）
暂且未知

### JavaScript output or error produced?（报错信息和调用栈）
mesh-buffer.js:216 Uncaught TypeError: vb.destroy is not a function
    at cc_MeshBuffer.destroy (mesh-buffer.js:216)
    at Impl.clear (impl.js:158)
    at cc_Graphics.onDestroy (graphics.js:185)
    at cc_Graphics.onDestroy (CCClass.js:778)
    at CCClass.destroyComp (node-activator.js:344)
    at cc_Graphics._onPreDestroy (CCComponent.js:517)
    at cc_Graphics.167.prototype._destroyImmediate (CCObject.js:474)
    at cc_Node._onPreDestroy (base-node.js:1253)
    at cc_Node._onPreDestroy (CCNode.js:1194)
    at cc_Node.167.prototype._destroyImmediate (CCObject.js:474)
destroy @ mesh-buffer.js:216
clear @ impl.js:158
onDestroy @ graphics.js:185
(anonymous) @ CCClass.js:778
destroyComp @ node-activator.js:344
_onPreDestroy @ CCComponent.js:517
167.prototype._destroyImmediate @ CCObject.js:474
_onPreDestroy @ base-node.js:1253
_onPreDestroy @ CCNode.js:1194
167.prototype._destroyImmediate @ CCObject.js:474
_onPreDestroy @ base-node.js:1246
_onPreDestroy @ CCNode.js:1194
167.prototype._destroyImmediate @ CCObject.js:474
_onPreDestroy @ base-node.js:1246
_onPreDestroy @ CCNode.js:1194
167.prototype._destroyImmediate @ CCObject.js:474
deferredDestroy @ CCObject.js:204
mainLoop @ CCDirector.js:951
callback @ CCGame.js:639
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
CCDebug.js:254 object already destroyed
27.cc.errorID @ CCDebug.js:254
167.prototype._destroyImmediate @ CCObject.js:469
_onPreDestroy @ base-node.js:1246
_onPreDestroy @ CCNode.js:1194
167.prototype._destroyImmediate @ CCObject.js:474
deferredDestroy @ CCObject.js:204
mainLoop @ CCDirector.js:951
callback @ CCGame.js:639
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
render-engine.js:7839 The buffer already destroyed
destroy @ render-engine.js:7839
destroy @ mesh-buffer.js:216
clear @ impl.js:158
onDestroy @ graphics.js:185
(anonymous) @ CCClass.js:778
destroyComp @ node-activator.js:344
_onPreDestroy @ CCComponent.js:517
167.prototype._destroyImmediate @ CCObject.js:474
_onPreDestroy @ base-node.js:1253
_onPreDestroy @ CCNode.js:1194
167.prototype._destroyImmediate @ CCObject.js:474
_onPreDestroy @ base-node.js:1246
_onPreDestroy @ CCNode.js:1194
167.prototype._destroyImmediate @ CCObject.js:474
_onPreDestroy @ base-node.js:1246
_onPreDestroy @ CCNode.js:1194
167.prototype._destroyImmediate @ CCObject.js:474
deferredDestroy @ CCObject.js:204
mainLoop @ CCDirector.js:951
callback @ CCGame.js:639
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633
requestAnimationFrame (async)
callback @ CCGame.js:633

出错触发文件URL：
http://localhost:7456/app/engine/cocos2d/core/renderer/webgl/mesh-buffer.js

出错触发行：216

出错触发代码：
    destroy () {
        for (let key in this._vbArr) {
            let vb = this._vbArr[key];
            vb.destroy();//本行出错，打断点
        }

我手动在报错处代码行断点暂停，在控制台输入下面内容调试输出
第一个：
vb
ƒ (newSize, defaultValueFunc) {
        while (newSize > this.length) {
            this.push(defaultValueFunc());
        }
        this.length = newSize;
    }
第二个：
vb.destroy
undefined

**Comment by xianyinchen** [comment]
你好，该问题需要提供一个可复现的demo，由于你使用的是早期版本，建议你升级最新版本，然后确认问题是否同样存在。

**Comment by fjqingyou** [comment]
无法提供复现了！
