### ISSUE TITLE
Safari10上会出现Cannot declare a let variable twice: 'e'.的问题

### ISSUE THREAD

**Issue by jigelang** [cocos/cocos-engine#5144]
### Creator version?2.0.10 p1

web safari10

项目打包运行就会出现，
之前在2.0.10的第一个正式版本中出现过，调整过uglify-es解决了，用最新的p1用同样的方式无法解决了，之前是在mifify.js中的mangle中
加入了```
{
safari10：true
}
```

**Comment by jigelang** [comment]
发现在编译引擎的node-module中的uglify-es也会影响，以同样的方式修改了编译引擎中的node-module后就好了

**Comment by zhefengzhang** [comment]
感谢反馈。

**Comment by jareguo** [comment]
opt.safari10 = true;

**Comment by jareguo** [comment]
已合并到 2.4.1
