### ISSUE TITLE
webview界面点击按钮崩溃(jsb_opengl_manual.cpp)

### ISSUE THREAD

**Issue by tuyazuo** [cocos/cocos-engine#5154]
ios webview接入传奇H5手游，在H5界面点击游戏的操作按钮（90%的按钮）都会造成app崩溃。
测试版本creator2.0.10，2.1.2 设备iPhone6 12.3 iPhoneXR 12.1.2以及模拟器均会报错，信息如下：

> [ERROR] (/Applications/CocosCreator2.1.2.app/Contents/Resources/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_opengl_manual.cpp, 4775): glUniformMatrix4fv((GLint)p[1], elementCount / 16, (GLboolean)p[2], &p[4]); GL error 0x502: GL_INVALID_OPERATION
> [ERROR] (/Applications/CocosCreator2.1.2.app/Contents/Resources/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_opengl_manual.cpp, 4781): glUseProgram((GLuint) p[1]); GL error 0x501: GL_INVALID_VALUE
> [ERROR] (/Applications/CocosCreator2.1.2.app/Contents/Resources/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_opengl_manual.cpp, 4649): glUniform1i((GLint)p[1], (GLint)p[2]); GL error 0x502: GL_INVALID_OPERATION
> [ERROR] (/Applications/CocosCreator2.1.2.app/Contents/Resources/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_opengl_manual.cpp, 4775): glUniformMatrix4fv((GLint)p[1], elementCount / 16, (GLboolean)p[2], &p[4]); GL error 0x502: GL_INVALID_OPERATION
> [ERROR] (/Applications/CocosCreator2.1.2.app/Contents/Resources/cocos2d-x/cocos/scripting/js-bindings/manual/jsb_opengl_manual.cpp, 4775): glUniformMatrix4fv((GLint)p[1], elementCount / 16, (GLboolean)p[2], &p[4]); GL error 0x502: GL_INVALID_OPERATION

见论坛帖子：https://forum.cocos.com/t/webview-100/82030

另外还有几个反馈和建议：
1. webview不会自动播放声音（需要用户点击触发一次声音播放），这个建议加个接口给用户，在有声音的页面中开发者的预期肯定是要播放声音的。
2. webview销毁后（webview组件所在的node已经destroy了）不会停止播放声音

**Comment by tuyazuo** [comment]
经测试发现在creator1.9.0版本功能正常，已在论坛帖子中上传demo

**Comment by yeshao2069** [comment]
该问题无法复现，另外从论坛下载的demo中的 https://game.jiulingwan.com 网址已经失效，无法测试。

**Comment by yeshao2069** [comment]
另外，webview 不会自动播放，是因为出于安全性考虑，你可以自己模拟播放操作。在2.4.5上测试，发布ios和网页上预览，webview销毁后，声音也会停止。

你可以升级到最新2.4.5版本试试。
测试demo
[NewProject_5.zip](https://github.com/cocos-creator/engine/files/6807176/NewProject_5.zip)
