### ISSUE TITLE
不缓存纹理是不是有Bug？

### ISSUE THREAD

**Issue by JimsC** [cocos/cocos-engine#5306]
2.0.10版本中
CCTexture2D的_clearImage函数
_clearImage () {
        cc.loader.removeItem(this._image.id || this._image.src);
        this._image.src = "";
    }
为什么是设置_image.src为空字符串来清空缓存纹理？真实的数据不是_image.data吗？为什么不是设置_image.data=null;?

**Comment by xianyinchen** [comment]
对于原生和小游戏平台，_image.src = "" 可以立即清除纹理数据，对于其他平台只能依赖Image的JS对象回收释放。
