### ISSUE TITLE
AudioClip duration

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#5314]
### Creator version?（版本号）
2.0.10

### Affected platform?（受影响的平台）
Mac Editor

#### 第一个问题
let duration = cc.audioEngine.getDuration(audioId);//发布版 duration == NAN

#### 第二个问题 
//设置音效剪辑
audioSource.clip = clip;
            
//取得音效持续时间
let duration = audioSource.getDuration();//发布版 duration == 0

**Comment by yeshao2069** [comment]
在2.4.5版本上验证
第一个问题 let duration = cc.audioEngine.getDuration(audioId);  可以获取到时间的。
在发布的web-mobile上获取duration 是没问题的。
```ts
onClick(){
      this._playIndex++;
      this._playIndex %= 7;
      let audioId = cc.audioEngine.play(this.sounds[this._playIndex], false, 1);
      let duration = cc.audioEngine.getDuration(audioId);

      console.log(duration);
  }
```

![image](https://user-images.githubusercontent.com/14273437/125405817-b7c62280-e3ea-11eb-9883-bf0ed7692340.png)

第二个问题

//设置音效剪辑
audioSource.clip = clip;

//取得音效持续时间
let duration = audioSource.getDuration();
在发布的web-mobile上获取duration 是没问题的。
![image](https://user-images.githubusercontent.com/14273437/125407982-ff4dae00-e3ec-11eb-8ce0-5079225baa42.png)

[testAudio.zip](https://github.com/cocos-creator/engine/files/6806658/testAudio.zip)

**Comment by yeshao2069** [comment]
感谢反馈，你可以升级到最新2.x版本  2.4.5版本试试。
