### ISSUE TITLE
播放音频时，偶现的出现颤音，杂音的问题

### ISSUE THREAD

**Issue by jigelang** [cocos/cocos-engine#5315]
### Affected platform?web

一般首次加载的时候容易复现，再次加载音频的质量一般就好了

**Comment by Marssssssss** [comment]
你好，这个问题我们在 2.0.10 之后的版本好像修复过相关的 bug，请使用最新版本试一下看看有没有出现。

**Comment by zhefengzhang** [comment]
用户长时间未回复，暂时关闭。
