### ISSUE TITLE
层级面板搜索结果，键盘方向键不是按照搜索结果选取，而是原有Scene中的顺序选取

### ISSUE THREAD

**Issue by fjqingyou** [cocos/cocos-engine#5333]
### Creator version?（版本号）
2.0.10

### Affected platform?（受影响的平台）

Mac Editor

### How to reproduce?（如何重现）
1、任意很多节点的场景。搜索多结果，且不是全部结果，例如 t:cc.Label，
2、选取任意一个结果。按向下方向键。。。这里正常执行
3、继续按方向键下。如果下一个不是恰好原有结构就是第二步的下一个，那么选取的就是搜索结果之外的对象了

**Comment by knoxHuang** [comment]
能否用最新版本 2.1.3 测试看看 https://www.cocos.com/creator

**Comment by fjqingyou** [comment]
@knoxHuang 相同结果

**Comment by knoxHuang** [comment]
已经修复，会进入到 2.2.2 或者 2.3 版本
