### ISSUE TITLE
crash on Xiaomi Redmi

### ISSUE THREAD

**Issue by hungphung33** [cocos/cocos-engine#5353]
my app crash randomly on XiaomiRedmi Note 5 Pro (whyred) , Redmi Note 7 (lavender) and ZTE B2017G (tulip)

NDK r16b

### Creator version?（2.0.9）

app link:
https://play.google.com/store/apps/details?id=td.bagato.studio

here my google log picture:
<img width="634" alt="Screen Shot 2019-09-09 at 11 18 38" src="https://user-images.githubusercontent.com/32632791/64503241-4c91fd80-d2f4-11e9-973b-0b6e2a2edbc7.png">

> ********** Crash dump: **********
> Build fingerprint: 'xiaomi/whyred/whyred:8.1.0/OPM1.171019.011/V10.0.6.0.OEIMIFH:user/release-keys'
> pid: 15604, tid: 15684, name: V8 WorkerThread  >>> td.bagato.studio <<<
> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x796ee52000
> Stack frame #00 pc 0000000000f94b0c  /data/app/td.bagato.studio-mLIkflfDCI8O6tfuJqh5hg==/lib/arm64/libcocos2djs.so: Routine v8::internal::Scavenger::ScavengeObject(v8::internal::HeapObject**, v8::internal::HeapObject*) at :?
> Stack frame #01 pc 0000000000f955c4  /data/app/td.bagato.studio-mLIkflfDCI8O6tfuJqh5hg==/lib/arm64/libcocos2djs.so: Routine v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitPointers(v8::internal::HeapObject*, v8::internal::Object**, v8::internal::Object**) at :?
> Stack frame #02 pc 0000000000f94424  /data/app/td.bagato.studio-mLIkflfDCI8O6tfuJqh5hg==/lib/arm64/libcocos2djs.so: Routine v8::internal::Scavenger::Process(v8::internal::OneshotBarrier*) at :?
> Stack frame #03 pc 0000000000d97e68  /data/app/td.bagato.studio-mLIkflfDCI8O6tfuJqh5hg==/lib/arm64/libcocos2djs.so: Routine v8::internal::ScavengingTask::RunInParallel() at :?
> Stack frame #04 pc 0000000000d97c30  /data/app/td.bagato.studio-mLIkflfDCI8O6tfuJqh5hg==/lib/arm64/libcocos2djs.so: Routine v8::internal::ItemParallelJob::Task::RunInternal() at :?
> Stack frame #05 pc 0000000000447f7c  /data/app/td.bagato.studio-mLIkflfDCI8O6tfuJqh5hg==/lib/arm64/libcocos2djs.so: Routine v8::platform::WorkerThread::Run() at :?
> Stack frame #06 pc 000000000043e160  /data/app/td.bagato.studio-mLIkflfDCI8O6tfuJqh5hg==/lib/arm64/libcocos2djs.so: Routine v8::base::ThreadEntry(void*) at :?
> Stack frame #07 pc 0000000000067ec4  /system/lib64/libc.so (__pthread_start(void*)+36)
> Stack frame #08 pc 000000000001f2f4  /system/lib64/libc.so (__start_thread+68)
> Crash dump is completed

**Comment by xianyinchen** [comment]
The crashes appear inside the v8 library and a reproducible demo needs to be provided so that we can have a direction for analysis.

**Comment by zhefengzhang** [comment]
The user has not replied for a long time and is temporarily closed.
