### ISSUE TITLE
Error display text in editbox android 9.0

### ISSUE THREAD

**Issue by zerominh** [cocos/cocos-engine#5391]
Pressed text not display correctly in editbox android 9.0
Creator version?（版本号）
2.1.2
![Layer 1](https://user-images.githubusercontent.com/30307402/64922097-6308ef00-d7f5-11e9-8540-487c22131f26.png)
Like in this image.
I press "fake" but on key board not display "fake" word

**Comment by xianyinchen** [comment]
I think you was setting the max length to zero for label component, so no more text can be inputed.

<img width="1030" alt="WeChat4aa49a14a2fa75d126fdcc7ec6d53bcb" src="https://user-images.githubusercontent.com/8321365/125238862-736b5180-e31a-11eb-9730-5b17fe1b5292.png">
