### ISSUE TITLE
Hago平台Label系统字体会偏移

### ISSUE THREAD

**Issue by hubluesky** [cocos/cocos-engine#5438]
Cocos版本：2.1.2
打包Web Mobile发布Hago平台。
所有Label的系统字体会向上偏移。
目前解决方法：修改引擎代码textUtils。还请官方解决此问题。
// Draw text the textBaseline ratio (Can adjust the appropriate baseline ratio based on the platform)
let BASELINERATIO = window["hg"] ? 0 : 0.26;
if (CC_RUNTIME) {
BASELINERATIO = -0.2;
}
但是这样改引擎会导致字体在显示的时候被超框剪裁，请你们解决或者告诉我怎么解决这个问题。

**Comment by dumganhar** [comment]
我是 hago 底层开发人员，请联系我，微信 
 dumganhar
备注你是谁
