### ISSUE TITLE
Any chance particle system will get improvement?

### ISSUE THREAD

**Issue by andrisole92** [cocos/cocos-engine#5484]
### Affected platform?（受影响的平台）

Browser.

### How to reproduce?（如何重现）
Load 3000 particles.

Hey, are there going to be any particles improvement for WebGL? PixiJS has a great performance for particles. Can we port the code to Cocos? I want to have animated particles and much more of them. Right now the whole thing slows down after I have over 100 particles on the screen...

Looking forward to hearing from you soon. Thanks!

**Comment by SantyWang** [comment]
Thanks for your feedback,maybe you can try the latest version. We have improved performance about particle system

**Comment by zhefengzhang** [comment]
用户长时间没有回复， issues 暂时关闭。
