### ISSUE TITLE
EditBox does not work on Mac build.

### ISSUE THREAD

**Issue by andrisole92** [cocos/cocos-engine#5491]
(As you can see input is horribly distorted)
<img width="343" alt="Screenshot 2019-09-29 at 23 24 10" src="https://user-images.githubusercontent.com/17086705/65847629-52d23300-e310-11e9-9ee7-d40fccb30460.png">

### Creator version?（版本号）
2.1.2

### Affected platform?（受影响的平台）

MacOS build
### How to reproduce?（如何重现）
Just EditBox, build, and try to type in something.

### JavaScript output or error produced?（报错信息和调用栈）

No

**Comment by PPpro** [comment]
issue fixed in v2.1.3, try upgrading Cocos Creator
refference: https://github.com/cocos-creator-packages/jsb-adapter/commit/23f957b8543ad87c48f44024f582815d88a6e789
