### ISSUE TITLE
Feature Request: Please add Websocker Server support in cocos creator

### ISSUE THREAD

**Issue by brantxiong** [cocos/cocos-engine#5519]
### Creator version?（版本号）
V2.1.2

### Affected platform?（受影响的平台）
Android/iOS

### Feature Request
Since Cocos2d-x  Engine has already added support for WebSocket Server ( https://github.com/cocos2d/cocos2d-x/issues/17944 )

Could you pls also add this feature to Cocos Creator?  I need setup a WebSocket Server in js script in Cocos Creator V2.1.2. 

Thanks so much!

**Comment by jareguo** [comment]
Hi, what's the purpose of a socket server? Pear to pear communication?

**Comment by brantxiong** [comment]
Hi, Thanks for your reply. 
    I Would like to integrate the [Poco-SDK](https://github.com/AirtestProject/poco-sdk) into the Cocos Creator Engine. And We need to implement a Server in the Game side created by Cocos Engine.,
    And I am one of the authors of Poco-SDK, If convenient, Could you share your email or others to keep in touch? I think we can cooperate on Automated Testing for Cocos Engines.

Thanks again!

**Comment by jareguo** [comment]
Sure, you can add my Wechat jare85

**Comment by minggo** [comment]
@brantxiong we can update libwebsocket.a. But we are not familiar of web server, do you have any advice about what functions are needed to be bound to Javascript?

**Comment by brantxiong** [comment]
Hi, @minggo You can check the functions here: [https://github.com/AirtestProject/Poco-SDK/blob/master/cocos2dx-js/Poco/Poco.js#L15](https://github.com/AirtestProject/Poco-SDK/blob/master/cocos2dx-js/Poco/Poco.js#L15)

We need setup a WebSocker Server in js, and common API are server.onServerUp, server.onMessage and etc, which has been list in the poco.js file.

**Comment by jareguo** [comment]
> https://poco-chinese.readthedocs.io/en/latest/source/doc/integration.html#cocos2dx-js-beta
我们之前的方案是找了一个开源的实现：http://discuss.cocos2d-x.org/t/cocos2d-js-websocket-server/33570

> https://poco-chinese.readthedocs.io/en/latest/source/doc/integration.html#cocos2dx-js-beta
这个是我们集成sdk的文档

> https://github.com/AirtestProject/Poco-SDK/blob/master/cocos2dx-js/Poco/Poco.js#L72
server.onServerUp
server.onServerDown
server.onConnection
server.onMessage
server.onDisconnection
server.onError
主要是这几个接口需要绑定到 JS

**Comment by PatriceJiang** [comment]
@brantxiong I am going to implement interfaces according to https://www.npmjs.com/package/nodejs-websocket#server, it is ok to you?

**Comment by brantxiong** [comment]
OK, Thanks @PatriceJiang .
Looking forward to this feature!

**Comment by minggo** [comment]
WebSocket only be used on Android. iOS uses SocketRocket, it doesn't support server features. If we export server related features, then we should use WebSocket on iOS too. Or the server related features are only exist on Android, it is not good.

**Comment by PatriceJiang** [comment]
Switching to libwebsockets on iOS has both pros and cons. 
#### pros:
- support compressing
- support websocket server
#### cons:
- increase package binary size by ~1M
- require an embedded or external CA file, ~200K

**Comment by brantxiong** [comment]
I think we can do support for Android based on libwebsockets first.
Since libwebsockets does not work on iOS, Could we try other server solution on iOS? Like the socket server.

Anyway, pls implement on Android first. And we can keep researching on the iOS solution.
Thanks!

**Comment by minggo** [comment]
We can use libwebsockets on iOS too, as @PatriceJiang said above. It just make the package about 1M bigger.
@jareguo what's your opinion?

**Comment by brantxiong** [comment]
require an embedded or external CA file, ~200K

**Comment by jareguo** [comment]
Even if we only support Android, it's pretty good, it's guaranteed (for game logic testing).
@minggo  On iOS, can we integrate libwebsockets as an independent native module? So deverlopers can compile it for testing only.

**Comment by minggo** [comment]
> Even if we only support Android, it's pretty good, it's guaranteed (for game logic testing).

I don't think so, if a feature exists only on one platform, then it is not good. Developers should know which feature is supported on which platform and do some special logic on different platforms. We should avoid it as possible.

> @minggo On iOS, can we integrate libwebsockets as an independent native module? So developers can compile it for testing only.

I don't think we can do it easily, it includes C++ codes, Javascript codes, should modify Xcode project to include:
- libwebsockets
- binding codes
- replace Javascript codes

**Comment by minggo** [comment]
Sorry, it is my fault, the server feature doesn't include Javascript codes. So there are two ways to add the server feature on iOS:
- developers modify the Xcode project to include libwebsockets and binding codes in its project to use it
- lite template includes libwebsockets and binding codes, but it is disabled by default, developers should enable it manually

**Comment by jareguo** [comment]
> Developers should know which feature is supported on which platform and do some special logic on different platforms. We should avoid it as possible.

I meant if there's a test framework targeting for test rather than game, we can say it's Android only. But yes, we should support iOS.
