### ISSUE TITLE
Richtext click handler not working

### ISSUE THREAD

**Issue by parvezdesignworks** [cocos/cocos-engine#5524]
Dear Team

The richtext component string with click handler is not working

I have tried below strings
```
<color=#0000ff click="GoUrl"> Show me</color>
<color=#0000ff click='GoUrl'> Show me</color>
<color=#0000ff click="Game.GoUrl"> Show me</color>
```

I have tried with on tag also

the string in rich text component is valid as per the docs

Kindly guide or if any issue, then please provide solution

I am using cocos creator v2.1.3

Regards

**Comment by SantyWang** [comment]
Thanks for your feedback，we will check it as soon as possible

**Comment by caryliu1999** [comment]
> <color=#0000ff click="GoUrl"> Show me</color>

Hi, thank you for your feedback. But I have verified that the v2.1.3 version is no problem. Have you checked the HandleTouchEvent option?

And this is a test demo.
[Test213.zip](https://github.com/cocos-creator/engine/files/3722858/Test213.zip)

**Comment by zhefengzhang** [comment]
用户长时间未回复，暂时关闭。
