### ISSUE TITLE
[2.0.10] 富文本位置异常

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#5543]
Chrome 浏览器预览下，文本显示偏上。

https://forum.cocos.com/t/topic/84432

![image](https://user-images.githubusercontent.com/8321365/66794054-947af480-ef32-11e9-8138-56917323dc5a.png)

**Comment by knoxHuang** [comment]
2.1.x 版本已经修复过，推荐升级到 2.1.3，
