### ISSUE TITLE
资源化地形创建流程

### ISSUE THREAD

**Issue by MSoft1115** [cocos/cocos-engine#5577]
流程：
  1.新建地形资源
  2.创建空节点并创建地形组件
  3.将地形资源绑定到地形组件
  4.像之前一样编辑地形
  5.保存场景时，要保存修改后的地形资源

问题：
  1.地形跟场景是强关联的，作为资源其实不是很不合适
  2.资源化后，用户需要操作的步骤变多了

**Comment by gameall3d** [comment]
1-3，在通常使用情况下一步就可以达到，在层级管理器中新建地形就会把这三步一起做了

**Comment by YunHsiao** [comment]
能不能还是在场景资源里，但保存这部分大块数据为二进制？看起来和动画遇到的问题很像，关键是数据格式的事

**Comment by JayceLai** [comment]
保存在场景资源里面会不好复用吧，特别是跨项目的时候。

迁移也可能会比较麻烦

**Comment by MSoft1115** [comment]
用户需要知道这个资源的存在，否则删除组件后，资源还残留在项目里
