### ISSUE TITLE
场景新增东西导出到微信还是老场景

### ISSUE THREAD

**Issue by StevenCoober** [cocos/cocos-engine#5580]
### Creator version?（版本号）
2.2

### How to reproduce?（如何重现）
版本是从1.9.3升级上来的,添加了几张贴图Spirte后场景导出错误,还是老场景

### JavaScript output or error produced?（报错信息和调用栈）

没有报错

**Comment by SantyWang** [comment]
感谢反馈，麻烦测试一下web平台是否正常？

**Comment by SantyWang** [comment]
可能因为用的还是缓存
