### ISSUE TITLE
当前v2.2.0版的物理引擎只能用在2D上 希望能够新增3D物理引擎

### ISSUE THREAD

**Issue by LoS-Light** [cocos/cocos-engine#5592]
### Creator version?（版本号）2.2.0
当前v2.2.0版的物理引擎只能用在2D上 希望能够新增3D物理引擎

**Comment by SantyWang** [comment]
你好，感谢反馈，我们目前将只会在2D增加一些3D的碰撞系统，其他物理部分，比如刚体系统，目前是没有考虑的，不知道这样是否满足你的需求呢？

**Comment by LoS-Light** [comment]
> 你好，感谢反馈，我们目前将只会在2D增加一些3D的碰撞系统，其他物理部分，比如刚体系统，目前是没有考虑的，不知道这样是否满足你的需求呢？

感谢您的回覆
目前主要是想知道未来有没有机会引进Cocos Creator 3D V1.0的3D物理引擎到Cocos Creator
如果未来没有考虑这项更新，我可能考虑转向使用Cocos Creator 3D了

**Comment by SantyWang** [comment]
你好，我们目前有计划的是迁移3d的碰撞系统到2d，但是一些其他的物理系统比如刚体，这些目前没有计划迁移。如果碰撞系统不足以满足你的需求，你想要更完善的物理系统，可以用 Cocos Creator 3D 即可

**Comment by LoS-Light** [comment]
> 你好，我们目前有计划的是迁移3d的碰撞系统到2d，但是一些其他的物理系统比如刚体，这些目前没有计划迁移。如果碰撞系统不足以满足你的需求，你想要更完善的物理系统，可以用 Cocos Creator 3D 即可

好的 我了解了
