### ISSUE TITLE
[v2.2.0][Material][Effect]两个Material使用同一个effectAsset资源，传入的uniform属性只有第一个Material生效

### ISSUE THREAD

**Issue by ErukuMeo** [cocos/cocos-engine#5600]
### 编辑器版本: 
2.2.0

---

### 问题描述: 

当两个Sprite分别引用两个Material，Material引用同一个Effect Asset资源时，
调用`Material.setProperty()`
第一个被渲染的Material会覆盖第二个Material设置的属性

备注：按节点的渲染顺序，先渲染节点上Material设置的属性会覆盖掉后渲染的节点设置的Material的属性
如果是两个相同内容的EffectAssets文件不会有这个问题
因为对渲染方面的知识了解较少，不确定这是Bug还是我的实现方式有问题

---
### Demo:
EffectAssets:
``` GLSL
CCEffect %{
  techniques:
  - passes:
    - vert: vs
      frag: fs
      blendState:
        targets:
        - blend: true
      rasterizerState:
        cullMode: none
      properties:
        texture: { value: white }
        u_color: { value: [0.0, 0.0, 0.0, 1.0]}
}%


CCProgram vs %{
    precision highp float;

    #include <cc-global>
    #include <cc-local>

    in vec3 a_position;

    uniform m_property {
        vec4 u_color;
    }

    out vec4 v_color;

    void main () {
        v_color = u_color;
        gl_Position = cc_matViewProj * vec4(a_position, 1);
    }
}%


CCProgram fs %{
    precision highp float;

    #include <alpha-test>

    uniform sampler2D texture;

    in vec4 v_color;

    void main () {
        gl_FragColor = v_color;
    }
}%

```
---
TypeScript代码片段:
``` TypeScript
    //精灵1
    @property(cc.Sprite)
    sprite_1: cc.Sprite = null;
    //精灵2
    @property(cc.Sprite)
    sprite_2: cc.Sprite = null;

    //精灵1在场景中层级比精灵2高

    //EffectAsset
    @property(cc.EffectAsset)
    effect_asset: cc.EffectAsset = null;

    start () {
        //创建一个Material并设置effectAsset为this.effect_asset
        let material_1 = new cc.Material();
        material_1.effectAsset = this.effect_asset;
        material_1.name = this.effect_asset.name + this.sprite_1.node.name;
        this.sprite_1.setMaterial(0, material_1);
        //设置第一个Material的的u_color属性为红色
        material_1.setProperty('u_color',[1.0,0.0,0.0,1.0]);

        //创建第二个Material并设置effectAsset为this.effect_asset
        let material_2 = new cc.Material();
        material_2.effectAsset = this.effect_asset;
        material_2.name = this.effect_asset.name + this.sprite_2.node.name;
        this.sprite_2.setMaterial(0, material_2);
        //设置第二个Material的的u_color属性为绿色
        material_2.setProperty('u_color',[0.0,1.0,0.0,1.0]);

        /**
         *运行后结果为 两张图片都变成了红色
         */
    }
```
### Demo项目：
[Effect-Demo](https://github.com/Elk953/CocosCreator-Effect-Demo)

**Comment by SantyWang** [comment]
你可以用Material.getInstantiatedMaterial复制一个材质出来试试

**Comment by ErukuMeo** [comment]
> 你可以用Material.getInstantiatedMaterial复制一个材质出来试试

您好，试了一下复制也不行，感觉这个应该是两个不同的Material引用了同一个EffectAsset导致的,因为我demo中就是new了两个Material，但是它们引用的是同一个EffectAsset

**Comment by ErukuMeo** [comment]
> > 你可以用Material.getInstantiatedMaterial复制一个材质出来试试
> 
> 您好，试了一下复制也不行，感觉这个应该是两个不同的Material引用了同一个EffectAsset导致的,因为我demo中就是new了两个Material，但是它们引用的是同一个EffectAsset

试了调用了EffectAsset.getInstantiatedEffect()复制一个新Effect也有问题 @holycanvas

**Comment by SantyWang** [comment]
好的，感谢，我跟同事确认下

**Comment by ErukuMeo** [comment]
> 好的，感谢，我跟同事确认下

好的 麻烦了，新添加了一个Demo [Effect-Demo](https://github.com/Elk953/CocosCreator-Effect-Demo)

**Comment by 2youyou2** [comment]
试下这样

```
let sharedMaterial = new cc.Material();
sharedMaterial.effectAsset = this.effect_asset;

let m1 = Material.getInstantiatedMaterial(sharedMaterial, this.sprite_1);
this.sprite_1.setMaterial(0, m1);
m1.setProperty(xxx);

let m2 = Material.getInstantiatedMaterial(sharedMaterial, this.sprite_2);
this.sprite_2.setMaterial(0, m2);
m2.setProperty(xxx);
```

**Comment by ErukuMeo** [comment]
> 试下这样
> 
> ```
> let sharedMaterial = new cc.Material();
> sharedMaterial.effectAsset = this.effect_asset;
> 
> let m1 = Material.getInstantiatedMaterial(sharedMaterial, this.sprite_1);
> this.sprite_1.setMaterial(0, m1);
> m1.setProperty(xxx);
> 
> let m2 = Material.getInstantiatedMaterial(sharedMaterial, this.sprite_2);
> this.sprite_2.setMaterial(0, m2);
> m2.setProperty(xxx);
> ```

您好，刚刚按这种方式试了一次，还是不行，感觉问题好像是出在`cc.effectAsset`上面

**Comment by SantyWang** [comment]
谢谢反馈，我们内部会再进行跟踪修复的，之后会通知您

**Comment by 2youyou2** [comment]
查了下是材质 hash 计算的问题，感谢反馈
pr: https://github.com/cocos-creator/engine/pull/5615
