### ISSUE TITLE
去除图片黑边使用自动合图之后失效

### ISSUE THREAD

**Issue by zhhd** [cocos/cocos-engine#5606]
### Creator version?（版本号）
2.1.3之前的版本

### Affected platform?（受影响的平台）
Web 其他平台没测试

### How to reproduce?（如何重现）
1.使用编辑器将原图的premultiply alpha勾上
2.选择src渲染通道为one 

### Demo project?（demo 项目）

比较容易重现的bug就不写demo了，在开发环境下不影响，只有打包之后会出现

**Comment by SantyWang** [comment]
你好，感谢反馈，这个在2.2上已经修复了
