### ISSUE TITLE
2.2.0 Cocos2dxDownloader.java 参数错误

### ISSUE THREAD

**Issue by 942Avril** [cocos/cocos-engine#5613]
### Affected platform?（Android）

2.2.0版本安卓的加载器Cocos2dxDownloader.java做了大量的修改,发现该类221行和259行均有调用downloader.onProgress的方法,
但参数传输的顺序有错,downloader.onProgress(id, current, len, total); 其中current和len的位置应该调换,
其中len对应onProgress方法的downloadBytes(触发当前onProgrees单次的加载字节), current为从该任务开始加载到当前所有字节,所以应该对应downloadNow.

**Comment by SantyWang** [comment]
谢谢反馈，有同事会跟进一下

**Comment by SantyWang** [comment]
已修复，下个版本推出
