### ISSUE TITLE
Matrix code editor- kos

### ISSUE THREAD

**Issue by Gurigraphics** [cocos/cocos-engine#562]
You can enjoy something of this idea in Cocos Creator?
https://github.com/Gurigraphics/plurality
The idea is to use matrix to organize the information and do something better than blockly google and spaghetti code.

**Comment by jareguo** [comment]
Visual Programming Language is a good idea but not our primary focus. It requires a lot of human labor, and should be added in as a plug-in, we'd be glad to talk to people about doing so.

**Comment by Gurigraphics** [comment]
Thanks for reply. Yes. This is just a brainstorm ideas.

The main proposal is to use matrix folders to organize the code as modules (As json sintaxe). Instead of separate files, and folders, or copy and paste code, or different information mixed in the same page.

I think the code would be more readable and easier to expand and create something more complex with javascript.

Visual, you could drag data block of documentation to the code, instead of copy and paste, auto-complete or memorize code. This organization would come just before it Become truly visual. 

But, it has more to do with a code editor, than Cocos2D really. The relationship with Cocos is just a way to organize docs information to be used in this editor.
