### ISSUE TITLE
cc.director.preloadScene 失败回调在 android手机 微信下 不执行....

### ISSUE THREAD

**Issue by fatdai** [cocos/cocos-engine#5645]
### How to reproduce?  
将 cc.director.preloadScene 预加载的场景所依赖的图片随便删除一张.

**Comment by SantyWang** [comment]
只有安卓上有这个问题么

**Comment by fatdai** [comment]
> 只有安卓上有这个问题么

是的, ios下可以收到回调。 微信开发工具下也可以收到回调, 但是  android 的微信下收不到失败的回调.

**Comment by fatdai** [comment]
> 只有安卓上有这个问题么

V2.1.3 是正常的!

**Comment by SantyWang** [comment]
感谢反馈，已修复
