### ISSUE TITLE
error 3408

### ISSUE THREAD

**Issue by fsm2018** [cocos/cocos-engine#5655]
![image](https://user-images.githubusercontent.com/48814847/67914600-8fbd6e00-fbcb-11e9-8b56-53b65815448b.png)

**Comment by Marssssssss** [comment]
您好，您是否在脚本中调用了非节点对象的 getComponent 函数或者 getComponent 参数写错了？
![image](https://user-images.githubusercontent.com/42939682/67916619-3ce6b500-fbd1-11e9-8a59-73f764fc80e9.png)

**Comment by fsm2018** [comment]
是分包加载的问题&nbsp; &nbsp;把脚本变成子包了&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YuanJie"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 中午11:24
收件人: "cocos-creator/engine"<engine@noreply.github.com&gt;; 
抄送: "1365064385"<1365064385@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cocos-creator/engine] error 3408 (#5655)




您好，您是否在脚本中调用了非节点对象的 getComponent 函数或者 getComponent 参数写错了？

**Comment by Marssssssss** [comment]
> 是分包加载的问题&nbsp; &nbsp;把脚本变成子包了&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YuanJie"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 中午11:24 收件人: "cocos-creator/engine"<engine@noreply.github.com&gt;; 抄送: "1365064385"<1365064385@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [cocos-creator/engine] error 3408 (#5655) 您好，您是否在脚本中调用了非节点对象的 getComponent 函数或者 getComponent 参数写错了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

噢噢，那现在是已经解决了吗？

**Comment by fsm2018** [comment]
已经解决了 把脚本放到主包 就好了
ps：h5 启动速度 要怎么优化啊&nbsp; 感觉加载好慢啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YuanJie"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 中午11:40
收件人: "cocos-creator/engine"<engine@noreply.github.com&gt;; 
抄送: "1365064385"<1365064385@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cocos-creator/engine] error 3408 (#5655)



 
是分包加载的问题&nbsp; &nbsp;把脚本变成子包了&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YuanJie"<notifications@github.com&gt;; 发送时间: 2019年10月31日(星期四) 中午11:24 收件人: "cocos-creator/engine"<engine@noreply.github.com&gt;; 抄送: "1365064385"<1365064385@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [cocos-creator/engine] error 3408 (#5655) 您好，您是否在脚本中调用了非节点对象的 getComponent 函数或者 getComponent 参数写错了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
噢噢，那现在是已经解决了吗？

**Comment by SantyWang** [comment]
自动图集，json合并，都可以提升一定的加载速度
