### ISSUE TITLE
Scrollbar is displayed after ScrollView is disabled and re-enabled, even if content fits in view.

### ISSUE THREAD

**Issue by DevanEngland** [cocos/cocos-engine#5704]
### Creator version?（版本号）
v2.1.2

### Affected platform?（受影响的平台）
Web, but probably all platforms

### How to reproduce?（如何重现）
- Create a new ScrollView with a Scrollbar.
- Set the content to be smaller than the view.
- Set up a button that toggles the 'active' flag of the ScrollView's node or one of its parents.
- View the ScrollView at runtime and note that the Scrollbar is (correctly) hidden.
- Use the button to make the ScrollView inactive and then active again.
- Observe that the Scrollbar is (incorrectly) visible. This is particularly noticeable if Auto-Hide is turned off.

### JavaScript output or error produced?（报错信息和调用栈）
There is no error output as this is a logic bug within the CCScrollView class.

### Demo project?（demo 项目）
[ScrollbarBugReproProject.zip](https://github.com/cocos-creator/engine/files/3820369/ScrollbarBugReproProject.zip)

**Comment by SantyWang** [comment]
Please try the lastest version

**Comment by SantyWang** [comment]
I have try it in v2.2.0, it worked fine
