### ISSUE TITLE
进度条问题

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#5710]

**Comment by 284263380** [comment]
在start里面 设置一个进度条0.065    发现根本不现实,(进度条没有刷新,进度条是空的,看不到进度)

**Comment by SantyWang** [comment]
感谢你的反馈，start里面设置进度条是什么意思？

**Comment by 284263380** [comment]
就是一个界面的start函数里面  （类似onLoad ，onDestroy一样的）

**Comment by SantyWang** [comment]
麻烦在最新版尝试一下

**Comment by 284263380** [comment]
修改了么?怎么修改的,我看下差异,然后试一下

**Comment by lostdream0505** [comment]
这个bug在2.2.1版本已经修复了，但是我对照这个pr修改引擎无法解决
#5609 
表现是进度条初始从0-0.125不显示。大于0.125会显示。
还有和这个bug相关的其他改动吗？
