### ISSUE TITLE
建议：creator增加过滤功能

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#5729]
项目比较大，文件快过万了，所有文件都在resources里面，但是resources下面会有core，001，002，003，....等多个目录，这些目录功能独立，但是都依赖core目录，任何一个core+001 或者core+002都可以成为一个单独的游戏，开发过程中打开creaotr，太卡了，所以是否可以添加一个filter功能配置，
像git的.gitignore功能一样，如果过滤了，creator启动的时候就不加载了。

备注：这个是一个项目，大厅+很多小游戏，这些小游戏虽然独立，但是逻辑还是统一的，所以如果一个游戏修改，可能要修改好几个游戏，所以不可能一个游戏一个项目去操作，并且出包是一起出的。

**Comment by jareguo** [comment]
@syxcools 这个需求比较复杂。其实项目大的话应该是拆分成多个子项目比较好。我们将在 2.3 支持 AssetBundle，到时候就可以动态加载子项目了。

**Comment by 284263380** [comment]
但是我们是一个大厅+子游戏开发，多平台  h5也支持，h5 的时候就需要一起打包，然后我们通过自定义引擎代码，也做到了拆分游戏块，

**Comment by jareguo** [comment]
一起打包这个不太方便吧，分开不是更好吗？如果加了过滤功能，又如何一起打包？
