### ISSUE TITLE
launch.json deprecated

### ISSUE THREAD

**Issue by wildfire810** [cocos/cocos-engine#5739]
###
"diagnosticLogging": false,
'diagnosticLogging' is deprecated. Use 'trace' instead.

###
{
    "version": "1.4.0",
    "configurations": [
        {
            "name": "Creator Debug: Launch Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:7456",
            "sourceMaps": true,
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "diagnosticLogging": false,
            "pathMapping": {
                "/preview-scripts/assets": "${workspaceRoot}/temp/quick-scripts/assets",
                "/": "${workspaceRoot}"
            }    
        }
    ]
}

**Comment by xianyinchen** [comment]
你好，你可以按照下面修改来规避这个警告。
将  "diagnosticLogging": false,
修改成 "trace": "verbose",
