### ISSUE TITLE
引入tiledmap后，报错：_traverseAllGrid grid is null

### ISSUE THREAD

**Issue by zlq4863947** [cocos/cocos-engine#5751]
### Creator version?（版本号）
2.2.0

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）
我已经建立了一个单独分支：
https://github.com/zlq4863947/m3k6/tree/tiledmap
当mac版载入map005的scene后报错，如下图
![image](https://user-images.githubusercontent.com/6490251/69004623-f4155700-0959-11ea-8b04-50fd6aaf38bf.png)

### JavaScript output or error produced?（报错信息和调用栈）
_traverseAllGrid grid is null

### Demo project?（demo 项目）
https://github.com/zlq4863947/m3k6/tree/tiledmap

**Comment by SantyWang** [comment]
真是个有个性的项目

**Comment by SantyWang** [comment]
有游戏项目截图么

**Comment by sunnylanwanjun** [comment]
看样子是tileset多贴图引起的，试试这个pr
https://github.com/cocos-creator/engine/pull/5728
会合到2.2.1

**Comment by zlq4863947** [comment]
好的 非常感谢
