### ISSUE TITLE
编辑器，Assets窗口，选择创建的材质文件，然后如选择其他文件等等操作都不行了

### ISSUE THREAD

**Issue by unusable** [cocos/cocos-engine#5752]
### Creator version 
2.1.3

### Affected platform 
MacOS

### How to reproduce?（如何重现）
打开编辑器，
在Assets窗口中 
创建或选择材质文件

**Comment by SantyWang** [comment]
是在代码中扩展了一下Array么

**Comment by yeshao2069** [comment]
感谢反馈。
经过测试，没能复现你的问题，建议你升级到最新的Cocos Creator版本重试。
目前最新的Cocos Creator 2.x系列的版本为 2.4.5
目前最新的Cocos Creator 3.x系列的版本为 3.1.1

测试
设备 : macbook pro     11.3.1
Cocos Creator 2.4.5

新建一个项目，新建一个scene，保存。创建几个TypeScript脚本，在资源管理器创建材质后，点击编辑器其他文件，表现正常。

如果操作不当或者其他，欢迎继续反馈，本issue先关闭。
