### ISSUE TITLE
isAnimationCached 生成的creator.d.ts中 方法的返回值为void 应该为 boolean

### ISSUE THREAD

**Issue by a417958382** [cocos/cocos-engine#5757]
https://github.com/cocos-creator/engine/blob/79b9133d6e0e44b4b8f033ba86231ae21522f2dc/extensions/spine/Skeleton.js#L578

**Comment by SantyWang** [comment]
谢谢你的反馈

**Comment by SantyWang** [comment]
我们会完善一下

**Comment by sunnylanwanjun** [comment]
已修复
https://github.com/cocos-creator/engine/pull/5774
