### ISSUE TITLE
建议：打包流交给业务方

### ISSUE THREAD

**Issue by zhangyugege** [cocos/cocos-engine#5773]
希望可以把打包流让给开发者。目前cocos creator使用gulp打包。打包产物多个方面不太符合生产环境的要求。

1. 兼容性： 打包产物不会对未来语法（ES6+）做转换，需要业务开发者二次打包。
2. 文件间依赖： 目前打包的所有文件依赖并没有暴露给开发者，开发者在二次打包，定制化js代码时，拿不到依赖，可能会导致产物多次依赖引入的问题。
3. 打包手段： 希望支持webpack方式的打包，可以利用到webpack丰富的生态圈。

I hope that the package flow can be given to the developer. Currently cocos creator is packaged with gulp. Many aspects of the packaged product do not meet the requirements of the production environment.

1. Compatibility: The packaged product does not convert to the future syntax (ES6+) and requires a second package for the business developer.
2. Dependencies between files: All the file dependencies currently packaged are not exposed to the developer. When the developer is packaged twice and customizes the js code, the dependencies may not be obtained, which may lead to multiple dependency of the product.
3. Packing frame: I hope to support the packaging of webpack, you can use the webpack rich ecosystem.

### Creator version?（版本号）
Every version.

**Comment by yeshao2069** [comment]
感谢反馈，目前暂时不支持 打包流程开放给开发者， 请知悉，谢谢。
