### ISSUE TITLE
进度条的问题

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#5796]
一个奇怪的问题,
我这里只有我的项目的这个地方会出现,所以我无法提供demo因为我的工程很大,并且有native的元素在里面,

我项目的现象是 (使用的是圆形进度条):
我下载进度设置(方案A)xx.getComponent(cc.ProgressBar).progress = precent;
这样设置,我打印了所有的log,数据调用没有问题,当前进度条行进到89%的时候显示的进度条是0.

我的猜测:可能是因为帧前 帧后调用的问题

然后我修改
(方案B)
settimeout(()=>{
xx.getComponent(cc.ProgressBar).progress = precent;
},0)

好了.

我之后打印引擎log

方案A的log是
D/jswrapper (149): JS: =========== 0.89000000000000001 
D/jswrapper (149): JS: =========== 0.89895739287487642
D/jswrapper (149): JS: =========== 0.89895739287487642
D/jswrapper (149): JS: =========== 0

第一行是我设置的xx.getComponent(cc.ProgressBar).progress = precent;
后面3行引擎的progress属性的notify通知打印,最后都有一个0
所以很奇怪,
但是方案B的log就和方案A的不一样

**Comment by zhefengzhang** [comment]
请问 bug 表现是 native 上进度条行进到89%的时候显示的进度条是 0 么？

**Comment by 284263380** [comment]
是的

**Comment by 284263380** [comment]
这个89是我这边设定的,不是89%就可以重现.
你可以测试下,用 native的  Application::getInstance()->getScheduler()->performFunctionInCocosThread里面执行回调,然后显示进度条数据,估计会有问题.

**Comment by zhefengzhang** [comment]
明白了，我确认下问题。

**Comment by zhefengzhang** [comment]
测试过程中没有发现问题，请你提供一个demo给我，可以发送到我的邮箱：
337031709@qq.com

**Comment by yeshao2069** [comment]
感谢反馈。
因为时间久远，用户暂时没有回复(没有提供demo),无法进行进一步验证，此单先行关闭。
若后续还存在问题，欢迎新建issue工单和我们反馈。
