### ISSUE TITLE
Cocos Creator 2.2/2.2.1 shadow cast not working

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#5812]
Shadow casting is visible in the editor/preview but not in the simulator/web. 
Please check in examples "examples/3d/3d-model"

**Comment by SantyWang** [comment]
thanks，we will check it

**Comment by caryliu1999** [comment]
> Shadow casting is visible in the editor/preview but not in the simulator/web.
> Please check in examples "examples/3d/3d-model"

Thanks for your feedback. But we have tested it is normal, can you elaborate on your problem?

![image](https://user-images.githubusercontent.com/39078800/70410961-c3719a80-1a8b-11ea-9fb9-6370397096fb.png)

**Comment by MarkusTieche** [comment]
Thanks for looking into this :)

Testing in CocosCreator 2.2.0 & 2.2.1 on Mac osx 10.15.1
Creating a new "examples" project and open 3d-model scene.
 
In Editor:
  Shadows working as intended
<img width="1887" alt="CC_2 2 0" src="https://user-images.githubusercontent.com/8083536/70413154-fd747980-1a56-11ea-8334-79da9df99fa5.png">

In Simulator:
  No Shadows at all
<img width="652" alt="simulator" src="https://user-images.githubusercontent.com/8083536/70413209-1ed56580-1a57-11ea-8fb7-cfbe90618ab0.png">

In Browser:
  seems to work normal(tested in Chrome,Safari)
<img width="1795" alt="web" src="https://user-images.githubusercontent.com/8083536/70413239-34e32600-1a57-11ea-9308-088c74a5d95e.png">

**Comment by caryliu1999** [comment]
Thanks for your feedback :), I have fixed it, you can merge the PR to check.

**Comment by MarkusTieche** [comment]
Awesome, seems to work with the fix applied (Tested with simulator in 2.2.0)
Thank you 👍 

<img width="1072" alt="Screenshot 2019-12-09 at 10 54 19" src="https://user-images.githubusercontent.com/8083536/70425976-85b44800-1a72-11ea-820f-7075b4cde050.png">
