### ISSUE TITLE
canvas模式下roundRect画不出

### ISSUE THREAD

**Issue by zhangyugege** [cocos/cocos-engine#5836]
在`renderMode =canvas`条件下，

this api： https://docs.cocos.com/creator/api/zh/classes/Graphics.html#roundrect
code ：https://github.com/cocos-creator/engine/blob/79b9133d6e0e44b4b8f033ba86231ae21522f2dc/cocos2d/core/graphics/graphics.js#L325

这个方法没有被draw执行过。

### Creator version?（版本号）

V2.1.4

**Comment by SantyWang** [comment]
感谢你的反馈，有同事会验证一下

**Comment by caryliu1999** [comment]
> 在`renderMode =canvas`条件下，
> 
> this api： https://docs.cocos.com/creator/api/zh/classes/Graphics.html#roundrect
> code ：
> 
> https://github.com/cocos-creator/engine/blob/79b9133d6e0e44b4b8f033ba86231ae21522f2dc/cocos2d/core/graphics/graphics.js#L325
> 
> 这个方法没有被draw执行过。
> 
> ### Creator version?（版本号）
> V2.1.4
> 
> ### Affected platform?（受影响的平台）
> ### How to reproduce?（如何重现）
> ### JavaScript output or error produced?（报错信息和调用栈）
> ### Demo project?（demo 项目）

抱歉，Canvas模式下的Graphics被屏蔽掉了，所以没有执行，你可以先修改一下引擎代码看，我们会在2.3版本修复这个问题。

core/graphics/graphics.js

![image](https://user-images.githubusercontent.com/39078800/70416196-71377600-1a99-11ea-8688-c571098aa3f7.png)
