### ISSUE TITLE
Label首次渲染文字出现异常

### ISSUE THREAD

**Issue by JacketChen0021** [cocos/cocos-engine#5838]
### Creator version?（版本号）
Cocos Creator 2.2.0

### Affected platform?（受影响的平台）
Android

### How to reproduce?（如何重现）
创建一个Label节点，构建一个android apk运行，Label首次渲染出现问题，后续修改label文字恢复正常
![B77C4A2D8A28DC9B44F15AC24D7B5C16](https://user-images.githubusercontent.com/57745382/70123709-2f2fbe00-16ae-11ea-8231-3b3afb9624d7.png)

### Demo project?（demo 项目）
https://github.com/JacketChen0021/LabelTestProject

**Comment by JacketChen0021** [comment]
![Screenshot_20191204-122630](https://user-images.githubusercontent.com/57745382/70131964-2e068d00-16be-11ea-87a0-b7ffd51d596c.png)
![Screenshot_20191204-122622](https://user-images.githubusercontent.com/57745382/70131968-2fd05080-16be-11ea-92d9-217b2e2fa723.png)
出现问题的机型

**Comment by SantyWang** [comment]
好的，感谢你的反馈，我们有同事会验证一下

**Comment by JacketChen0021** [comment]
补充一下，不只是在native上出现问题，无论是那个平台，在这部手机上都会出现

**Comment by yeshao2069** [comment]
感谢反馈。
这边使用 一台比较旧的手机 OPPO A57测试， Android: 6.0.1  , Cocos Creator版本:  2.4.5。 验证label首次渲染没有问题。建议你升级Cocos Creator版本为最新的 2.4.5或者使用目前最新的3.x版本 3.1.1版本
![7AB10287521C81354EC3A141C6639906](https://user-images.githubusercontent.com/14273437/121529311-dd988a00-ca2e-11eb-8255-38efb100a154.jpg)
![A14D38B19845A5DE80A695B5EF4F8453](https://user-images.githubusercontent.com/14273437/121529323-dffae400-ca2e-11eb-8cc3-9f1805ee2715.jpg)
