### ISSUE TITLE
[BUG] Moving parent node with rigidbodies children doesn't work

### ISSUE THREAD

**Issue by ghost** [cocos/cocos-engine#5856]
### Creator version?（版本号）
2.2.1, 2.2.2

### Affected platform?（受影响的平台）

Tested on Windows Editor

### How to reproduce?（如何重现）
1) Create TWO nodes in the scene - _nodeParent_ and _nodeChild_. Assign _nodeChild_ as a children to _nodeParent_. Add some Sprite component to _nodeChild_ to see it work.
2) Add **Rigidbody** component to _nodeChild_. Make it static with Gravity scale 0 (actually it doesn't matter what you will set in these properties, this is just to make sure that the body is not affected by gravity)
3) Add this script to _nodeParent_:
```
const {ccclass, property} = cc._decorator;
@ccclass
export default class Movement extends cc.Component {

    onLoad() {
        cc.director.getPhysicsManager().enabled = true;
    }

    update (dt) {
        this.node.x -= 0.5;
    }
}
```

This should move  _nodeParent_ as well as _nodeChild_ to the left, but it doesn't. If I add this script to _nodeChild_, it works. It works also if I remove Rigidbody from _nodeChild_.

**Conclusion:**
Rigidbody component attached to children node prevents children node from desired movement. Please take a look on it. Thanks!

**Comment by SantyWang** [comment]
Thanks for your feedback, we will check it

**Comment by zhefengzhang** [comment]
![image](https://user-images.githubusercontent.com/35944775/70407626-0b8ac000-1a80-11ea-88b9-2fc8bfb845f9.png)

This is cc.RigidBody api, correction you code like this:
```
const {ccclass, property} = cc._decorator;
@ccclass
export default class Movement extends cc.Component {

    onLoad() {
        cc.director.getPhysicsManager().enabled = true;
    }

    update (dt) {
        this.node.x -= 0.5;
        this.node.getChildByName("__childrenNodeName__").getComponent(cc.RigidBody).syncPosition();
    }
}
```

**Comment by ghost** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/35944775/70407626-0b8ac000-1a80-11ea-88b9-2fc8bfb845f9.png)
> 
> This is cc.RigidBody api, correction you code like this:
> 
> ```
> const {ccclass, property} = cc._decorator;
> @ccclass
> export default class Movement extends cc.Component {
> 
>     onLoad() {
>         cc.director.getPhysicsManager().enabled = true;
>     }
> 
>     update (dt) {
>         this.node.x -= 0.5;
>         this.node.getChildByName("__childrenNodeName__").getComponent(cc.RigidBody).syncPosition();
>     }
> }
> ```

Hi, first, sorry for late answer, I had a long vacation.
Thanks for your suggestion, this code really works, but I consider it as a walkaround to real problem - there is a bug in the engine which needs to be fixed. In 2.2.2 version, the problem still persists.

@holycanvas did you already addressed the problem?
Thanks for your time, guys!

**Comment by xianyinchen** [comment]
The current design is such that the engine will synchronize the node position of the physical world to the scene node in real time, but the scene node will not synchronize the changes to the physical engine node in real time. If you need to synchronize the scene node position to the physical world, please call syncPosition manually.
