### ISSUE TITLE
Wrong shadow texture

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#5877]
Cocos Creator 2.2.0/2.2.1 on macOS 10.15.1

Shadow uses wrong texture after applying a diffuse texture to Material.
I use "examples/3d-model" as test scene and add a new Material with builtIn-phong effect.
Shadows are normal until I add a texture to the material.

<img width="1640" alt="Screenshot 2019-12-10" src="https://user-images.githubusercontent.com/8083536/70491925-00c53f00-1b03-11ea-882e-5b69cc20a2b7.png">

**Comment by SantyWang** [comment]
thanks, we will fix it in next version

**Comment by SantyWang** [comment]
done!
