### ISSUE TITLE
cc.loader.loadResDir totalCount 数值不固定

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#5904]
creator 2.2.1

cc.loader.loadResDir函数进行预加载

现象:进度条异常,比如本来加载到90% 然后发现又回到80%,从80%-100%,加载过程中,发现有倒退现象

结论: cc.loader.loadResDir(gameName+'/res/element',(completedCount,totalCount,item)=>{})
这个totalCount竟然会变动,比如原来是totalCount  是300个,然后加载过程中,变成345 400 最后到500,所以进度会有倒退情况

**Comment by SantyWang** [comment]
抱歉，现在的设计确实是这样的，因为在加载到具体的资源之前是不知道他有多少个依赖资源的，也就是说无法在一开始统计好totalCount，totalCount会随着资源的加载不断地增加，某些时候确实会有回退（单个资源依赖数量非常大时，totalCount 急增），你可以稍微做下判断，不让他减少
