### ISSUE TITLE
Blurred graphics using Chrome.

### ISSUE THREAD

**Issue by cmontiel** [cocos/cocos-engine#5917]
Blurred graphics on Chrome.

It happens on a 2K Dell monitor using MacOS 10.15.2.
Also on iPhoneX 13.2.3

Only using Chrome, works fine on Firefox and Safari.

### Creator version?（版本号）
2.2.1

### Affected platform?（受影响的平台）
Web

### How to reproduce?（如何重现）
The game runs inside an iframe. Just resizing the browser (or rotating on mobile).

### JavaScript output or error produced?（报错信息和调用栈）
No error.

### Demo project?（demo 项目）
Unfortunately, I can't provide a demo project.

**Comment by OnlyKoei** [comment]
Can you provide a screenshot to see the actual situation?

**Comment by OnlyKoei** [comment]
The test could not be reproduced. Since you have not replied for too long, the issue is temporarily closed
