### ISSUE TITLE
粒子合批

### ISSUE THREAD

**Issue by hubluesky** [cocos/cocos-engine#5929]
请计划粒子合批，谢谢。

**Comment by zhefengzhang** [comment]
GPU 粒子：
参考demo：http://download.cocos.org/CocosTest/zhefengzhang/NoDelete/GPU_particle.zip

粒子合批：
参考demo：https://github.com/caogtaa/CCBatchingTricks.git

目前引擎还没有计划在 2.x 版本支持粒子合批。这两个合批方案提供给客户尝试。
