### ISSUE TITLE
Be smart when creating file.

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#5947]
I think this is in between feature and bug. Anyway allow me not having all the bug report because the issue I'm about to report is very simple and tiny.

While creating file, if I was inputting `Test.ts` for a `.ts` file. The `Test.ts.ts` file is created. It would be nice if just ripe off the `.ts` part of it.

Thanks!

**Comment by SantyWang** [comment]
good advise, thank you very much, we will support it and tiny issue is welcome!

**Comment by jareguo** [comment]
This feature will be landed on 2.3. Thanks.
