### ISSUE TITLE
[Feature Request] Pressing `f` to focus on the node object.

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#5950]
As title, would this be the nice feature to have? Just like most of the engine or modeling tool does. e.g. Unity, Unreal, Maya, 3DMax, etc.

**Comment by SantyWang** [comment]
Thanks, it's a good advise. we will support this feature in the next version

**Comment by jcs090218** [comment]
That will be awesome! Happy to hear that. :D

**Comment by SantyWang** [comment]
done!
