### ISSUE TITLE
cc.Director.calculateDeltaTime死循环

### ISSUE THREAD

**Issue by recoye** [cocos/cocos-engine#5956]
### Creator version?（版本号）
2.2.1

### Affected platform?（受影响的平台）
微信小游戏

### How to reproduce?（如何重现）
偶发，一般是从后台换醒回前台时出错

### JavaScript output or error produced?（报错信息和调用栈）

Maximum call stack size exceeded;at requestAnimationFrame callback function RangeError: Maximum call stack size exceeded at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95740) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833) at 24.cc.Director.calculateDeltaTime (https://usr/game.js:3:95833)
--

### Demo project?（demo 项目）

**Comment by SantyWang** [comment]
感谢你的反馈，请尝试下这个pr https://github.com/cocos-creator/engine/pull/5952

**Comment by jareguo** [comment]
谢谢反馈，这个问题将在下个版本修复。
