### ISSUE TITLE
注释错误

### ISSUE THREAD

**Issue by rancekk** [cocos/cocos-engine#5969]
![D $ {12~TQ8{2X$R{NE41`V](https://user-images.githubusercontent.com/23482942/71443689-6a6e5b80-2747-11ea-8fc7-a1f990e246d3.png)

**Comment by SantyWang** [comment]
请问有什么问题？

**Comment by rancekk** [comment]
> 请问有什么问题？

@language

**Comment by rancekk** [comment]
@holycanvas

**Comment by jcs090218** [comment]
I think he is saying the `@language` tag aren't correct for their corresponding languages. 

| Comment | Explanation |
|:---|:---|
| `矩形的高度` | should have tag as `zh_CN` but tag `en_US` |
| `The height of the rectangle` | should have tag as `en_US` but tag `zh_CN` |

But they are in the opposite spot right now base on the screenshot @w1532106001 gave.

**Comment by yeshao2069** [comment]
你好，首先感谢你的反馈。这个注释错误问题，将会在新版本被修改，谢谢。
