### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#5983]
Is there any way or future plan to make gamepads work on native builds?
It seems to work fine on web builds with ``` window.addEventListener("gamepadconnected")```, but does not work on native. 

source: 
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

**Comment by SantyWang** [comment]
it's good advise, our team will consider it
