### ISSUE TITLE
切换场景的时候，资源释放导致的报错

### ISSUE THREAD

**Issue by linguitang** [cocos/cocos-engine#5997]
![image](https://user-images.githubusercontent.com/8371546/71554588-e9230b80-2a5b-11ea-81aa-fcd22026db8c.png)
资源释放之后，frame._texture就是null，所以就会引起报错 if (frame && !CC_TEST) { 是不是应该改成if (frame &&frame._texture&& !CC_TEST) {

**Comment by SantyWang** [comment]
感谢你的反馈，有同事会确认一下

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
