### ISSUE TITLE
Prompt while opening the project.

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#6010]
So, here is the thing. When I click on the `open` button on one of my project's icon it wouldn't show anything if it is opening the project. I think it would be better if you told the user that the software is opening the project or maybe minimize the cocos creator itself. :D Just an advice and this make the product has the better user experience.

**Comment by SantyWang** [comment]
Thansk for your advises, our team will talk about it lator

**Comment by jcs090218** [comment]
Please do! Thanks! :D

**Comment by SantyWang** [comment]
Thanks! A tip will be shown on new dashboard

**Comment by jcs090218** [comment]
> Thanks! A tip will be shown after rafactoring dashboard

I'm note quite sure what you mean by refactoring dashboard?

**Comment by SantyWang** [comment]
Sorry, I mean new version of dashboard will be more friendly when open project

**Comment by jcs090218** [comment]
Thanks!
