### ISSUE TITLE
[Feature] Add search ability when adding new component.

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#6018]
This is another behaviour that Unity Engine uses and I think this is very handy to the developer. Thanks!

**Comment by SantyWang** [comment]
Thanks, we already have plan to support this feature

**Comment by jcs090218** [comment]
That's awesome! And again I appreciate the team's effort and work very much! :D If this issue cause distraction please feel free to close it!

**Comment by yeshao2069** [comment]
Thank you for your valuable suggestions！
We have supported the search ability when adding a new component in the latest version 3.0.

![image](https://user-images.githubusercontent.com/14273437/116529699-ce8eca00-a90f-11eb-9106-037d48be1b90.png)
