### ISSUE TITLE
getComponent: Type must be non-nil

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#6026]
Hi,

I have this error but I literally don't know why I am getting this error. Do you think you could make this kind of the error describe it's error more explicit? Or else this is pain in the butt to search for the issue.

Thanks!

**Comment by SantyWang** [comment]
Thanks, would you please provide more information about this error. editor or runtime?

**Comment by jcs090218** [comment]
I'm sorry for have this report earlier because I didn't know how to reproduce this hence I made a quick report just to hope maybe the team would have any heads up. Anyway, once I restart Cocos Creator then the issue disappear and doesn't remain afterward. I will reopen this issue if I know how to reproduce this issue! Thanks for having a concern for it! :D
