### ISSUE TITLE
Probably TileMap rendering bug

### ISSUE THREAD

**Issue by ggarek** [cocos/cocos-engine#603]
I encounter an exception at design- and runtime while trying to render TileMap.

My .tmx file uses one tileset, which consists of _two separate images_.
But in runtime only one image gets loaded. (Network tab)

Error Callstack
<img width="894" alt="screen shot 2016-04-16 at 17 53 24" src="https://cloud.githubusercontent.com/assets/5501062/14581718/3ca185be-03fc-11e6-9e1f-4a4921a6d766.png">

It seems like the engine does not handle case, when _tileset is composed of several separate images_.
Because it tries to use the first tile image with "displaced" rect ({ x: 0, y: 50, width: 50, height: 50 })

May be i miss something, but there is an error nonetheless.
[Here is a Creator project with the bug](https://github.com/cocos-creator/engine/files/222259/tilemap-bug.zip)

I use Cocos Creator v1.0.1

Would appreciate any help, thanks! 

p.s.: Great project you are doing, keep going!

**Comment by ggarek** [comment]
Just created [another project](https://github.com/cocos-creator/engine/files/222269/cc-tilemap-tiles-one-file-ok.zip) with .tmx, which uses single image for all tiles.
Works just fine.

In Tiled editor it is type of a TileSet, which can be "Based on Tileset Image" or "Collection of Images".
The bug is with "Collection of Images" TileSet.

**Comment by natural-law** [comment]
@ggarek
I'm sorry that `Collection of Images` TileSet is not supported for some historical reasons.

The TiledLayer in the engine is only support TileSet info with only-one `sourceImage` attribute. Take a look at this code:
https://github.com/cocos-creator/engine/blob/master/cocos2d/tilemap/CCSGTMXLayer.js#L266

After all, thanks for your feedback! We will try to improve the implementation of component TiledMap.
