### ISSUE TITLE
浏览器调整宽高后显示元素重绘但是鼠标点击事件触发位置不变

### ISSUE THREAD

**Issue by harryhuang2015** [cocos/cocos-engine#6031]
### Creator version?（版本号）
2.2.2

### Affected platform?（受影响的平台）

Mac Editor/Web/Simulator

### How to reproduce?（如何重现）
1.设置Fit Hight true
2.在浏览器打开中，对应Button点击事件正常。
3.改变浏览器窗口大小，整个页面Button显示随浏览器窗口大小调整正常，但是点击Button无法触发事件，点击该button在浏览器调整前的相对位置，才能触发事件

点击事情正常，红包圆表标点击区域，五条表示button
![1578130313003](https://user-images.githubusercontent.com/14197585/71763602-b922af00-2f18-11ea-8a2b-9ad1b49c0275.jpg)
拉宽浏览器窗口后，点击事件位置发生偏离。红包圆表标点击区域，五条表示button
![1578130321400](https://user-images.githubusercontent.com/14197585/71763601-b88a1880-2f18-11ea-85a8-4c694c35d778.jpg)

项目代码：
https://gitee.com/gs089597/beimi/tree/master/client/version/chess
进入场景：游客登陆-血战麻将-初级场-准备

**Comment by SantyWang** [comment]
请问是什么浏览器

**Comment by harryhuang2015** [comment]
> 请问是什么浏览器

chrome,   华为手机浏览器，cocos creator模拟器都有这个问题。

**Comment by OnlyKoei** [comment]
测试版本：2.2.2，2.4.3，2.4.4
并未复现。是否方便提供个demo?

**Comment by zhefengzhang** [comment]
用户长时间未回复，暂时关闭。
