### ISSUE TITLE
[Suggestion] Close all nodes as default?

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#6038]
Right now when you opened a scene all node are tend of be opened. But would it be better if the default is closed? Than I would never have to close all the nodes that causes distraction. Thanks!

**Comment by SantyWang** [comment]
Thanks, we will discuss it later

**Comment by jcs090218** [comment]
I don't remember about Unreal Engine 4 or Unity Engine, but in my experiences, I would not ever need to close the nodes at the start of every scene. Hence I assume they have it all closed at the very start of the scene! Please discuss and consider this! Thanks! :D

**Comment by SantyWang** [comment]
Cocos Creator has one option to do this
![image](https://user-images.githubusercontent.com/15109777/71874439-e9f32600-315c-11ea-8a76-253b89a4e050.png)

**Comment by jcs090218** [comment]
This is neat! Still willing to see `collapse all` as the default one though! :kissing:
