### ISSUE TITLE
[BUG] Abstract class shouldn't be showed up in custom component.

### ISSUE THREAD

**Issue by jcs090218** [cocos/cocos-engine#6039]
As a title, I think the abstract class shouldn't be showing up inside the custom component section while adding a new component. Anyway, it shouldn't be added to any node too!

**Comment by SantyWang** [comment]
Thanks, you can remove the decorator 'ccclass' above abstract class's declaration to do same thing

**Comment by jcs090218** [comment]
It works! Thanks! Would you guys consider to preprocess it hence it don't included in the custom component section? If not, feel free to close it! :D 

I very appreciate your work!
