### ISSUE TITLE
[BUG] IphoneX Editbox position

### ISSUE THREAD

**Issue by minhtrungaa** [cocos/cocos-engine#6042]
![image](https://user-images.githubusercontent.com/23292030/71868453-c1f5c980-3140-11ea-8c87-e45efa959a9e.png)

The bug even worst when the virtual keyboard shows up and first 5 characters will be hidden

### Creator version?（版本号）
v2.2.2

### Affected platform?（受影响的平台）
iOS

### How to reproduce?（如何重现）
A simple project with an edit box

**Comment by minggo** [comment]
I think it is fixed in https://github.com/cocos-creator/cocos2d-x-lite/pull/1848.

**Comment by yeshao2069** [comment]
Thanks for the feedback.
Testing has confirmed that this issue has been fixed. You can upgrade your creator version to 2.4.5 and retry.
Test version: 2.4.5
Test device: iPhone X
Test screenshots:
![3461624506573_ pic_hd](https://user-images.githubusercontent.com/14273437/123203109-6a8c1a80-d4e8-11eb-88a7-533f5b18a59d.jpg)
![3471624506574_ pic_hd](https://user-images.githubusercontent.com/14273437/123203110-6a8c1a80-d4e8-11eb-82b1-22546c350db8.jpg)
![3481624506575_ pic_hd](https://user-images.githubusercontent.com/14273437/123203111-6a8c1a80-d4e8-11eb-963b-77ce52fd6ef7.jpg)

Test Demo:
[testEditboxIphoneX.zip](https://github.com/cocos-creator/engine/files/6706248/testEditboxIphoneX.zip)
