### ISSUE TITLE
一个问题,看看不能加个保护

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#6045]
这里你们可不可以加个保护
core/renderer/render-flow.js
 _proto._updateRenderData = function (node) {
            var comp = node._renderComponent;
            // 这里comp 有可能为空,我项目遇到了,但是我没有定位到具体位置,所以我没有办法提供demo
            comp._assembler.updateRenderData(comp);
            node._renderFlag &= ~UPDATE_RENDER_DATA;
            this._next._func(node);
        };

错误日志
render-flow.js? [sm]:73 Uncaught TypeError: Cannot read property '_assembler' of null
    at RenderFlow._proto._updateRenderData (render-flow.js? [sm]:73)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._render (render-flow.js? [sm]:82)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._render (render-flow.js? [sm]:82)
    at RenderFlow._proto._updateRenderData (render-flow.js? [sm]:75)
_proto._updateRenderData @ render-flow.js? [sm]:73
_proto._children @ render-flow.js? [sm]:110
_proto._render @ render-flow.js? [sm]:82
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._render @ render-flow.js? [sm]:82
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
RenderFlow.visitRootNode @ render-flow.js? [sm]:206
RenderFlow.render @ render-flow.js? [sm]:214
render @ index.js? [sm]:183
cc.Director.mainLoop @ CCDirector.js? [sm]:980
callback @ CCGame.js? [sm]:643
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
CCDebug.js? [sm]:251 Stencil manager does not support level bigger than 8 in this device.
cc.errorID @ CCDebug.js? [sm]:251
pushMask @ mask-assembler.js? [sm]:62
fillBuffers @ mask-assembler.js? [sm]:173
_proto._render @ render-flow.js? [sm]:81
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
RenderFlow.visitRootNode @ render-flow.js? [sm]:206
RenderFlow.render @ render-flow.js? [sm]:214
render @ index.js? [sm]:183
cc.Director.mainLoop @ CCDirector.js? [sm]:980
callback @ CCGame.js? [sm]:643
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
CCDebug.js? [sm]:251 Stencil manager does not support level bigger than 8 in this device.
cc.errorID @ CCDebug.js? [sm]:251
pushMask @ mask-assembler.js? [sm]:62
fillBuffers @ mask-assembler.js? [sm]:173
_proto._render @ render-flow.js? [sm]:81
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._render @ render-flow.js? [sm]:82
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
RenderFlow.visitRootNode @ render-flow.js? [sm]:206
RenderFlow.render @ render-flow.js? [sm]:214
render @ index.js? [sm]:183
cc.Director.mainLoop @ CCDirector.js? [sm]:980
callback @ CCGame.js? [sm]:643
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
CCDebug.js? [sm]:251 Stencil manager does not support level bigger than 8 in this device.
cc.errorID @ CCDebug.js? [sm]:251
pushMask @ mask-assembler.js? [sm]:62
fillBuffers @ mask-assembler.js? [sm]:173
_proto._render @ render-flow.js? [sm]:81
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._render @ render-flow.js? [sm]:82
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
RenderFlow.visitRootNode @ render-flow.js? [sm]:206
RenderFlow.render @ render-flow.js? [sm]:214
render @ index.js? [sm]:183
cc.Director.mainLoop @ CCDirector.js? [sm]:980
callback @ CCGame.js? [sm]:643
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
CCDebug.js? [sm]:251 Stencil manager does not support level bigger than 8 in this device.
cc.errorID @ CCDebug.js? [sm]:251
pushMask @ mask-assembler.js? [sm]:62
fillBuffers @ mask-assembler.js? [sm]:173
_proto._render @ render-flow.js? [sm]:81
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
_proto._render @ render-flow.js? [sm]:82
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._render @ render-flow.js? [sm]:82
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
RenderFlow.visitRootNode @ render-flow.js? [sm]:206
RenderFlow.render @ render-flow.js? [sm]:214
render @ index.js? [sm]:183
cc.Director.mainLoop @ CCDirector.js? [sm]:980
callback @ CCGame.js? [sm]:643
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
CCDebug.js? [sm]:251 Stencil manager does not support level bigger than 8 in this device.
cc.errorID @ CCDebug.js? [sm]:251
pushMask @ mask-assembler.js? [sm]:62
fillBuffers @ mask-assembler.js? [sm]:173
_proto._render @ render-flow.js? [sm]:81
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._children @ render-flow.js? [sm]:110
_proto._render @ render-flow.js? [sm]:82
_proto._updateRenderData @ render-flow.js? [sm]:75
_proto._children @ render-flow.js? [sm]:110
RenderFlow.visitRootNode @ render-flow.js? [sm]:206
RenderFlow.render @ render-flow.js? [sm]:214
render @ index.js? [sm]:183
cc.Director.mainLoop @ CCDirector.js? [sm]:980
callback @ CCGame.js? [sm]:643
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
requestAnimationFrame (async)
callback @ CCGame.js? [sm]:637
render-flow.js? [sm]:73 Uncaught TypeError: Cannot read property '_assembler' of null
    at RenderFlow._proto._updateRenderData (render-flow.js? [sm]:73)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._render (render-flow.js? [sm]:82)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._children (render-flow.js? [sm]:110)
    at RenderFlow._proto._render (render-flow.js? [sm]:82)
    at RenderFlow._proto._updateRenderData (render-flow.js? [sm]:75)

**Comment by 284263380** [comment]
然后是2.2.1的creator,项目比较大

**Comment by caryliu1999** [comment]
> 然后是2.2.1的creator,项目比较大

多谢反馈，报错经常出现吗？有没有前置报错？assembler 是跟 renderComponent 匹配的，对于渲染节点来说是不该出现节点有UpdateRenderData的标志位, 但是不存在 renderComponent 的情况的。加保护意味着多一次判断，还是得找到根源问题。

**Comment by 284263380** [comment]
我有一个必现的界面,现在时间太忙,没时间找问题,等后面稍微不紧张了,我可以去找找根源.我是通过下面代码处理的,不知道原因,但是暂时解决了.  或者你给我个保护的代码,怎么写,让我先临时用下,我还有遇到其他偶现的情况呢,所以我的项目这个肯定是要保护一下

//TODO:这句话一加,则首冲,开关两次界面,就出问题.
        // if(node.getComponent(cc.Sprite)){
        //     node.removeComponent(cc.Sprite);
        // }

**Comment by 284263380** [comment]
晓得了,算是我的问题
cc.loader.loadRes我修改成如果加载过的,然后代码就是同步执行的
下面代码如果不加cc.isValid(com,true)==false  就会出这个问题


if(node.getComponent(cc.Sprite)){
node.removeComponent(cc.Sprite);
}
....
cc.loader.loadRes(...()=>{
let com = node.getComponent(cc.Sprite);
 if(!com || cc.isValid(com,true)==false){
                com = node.addComponent(cc.Sprite);
            }
})

**Comment by SantyWang** [comment]
好的，感谢你的反馈
