### ISSUE TITLE
webglContext在lost以后，尝试通过restoreContext救活，但是引擎里的_renderContext应该已经失效，现在有更新_renderContext的机制么？

### ISSUE THREAD

**Issue by a417958382** [cocos/cocos-engine#6065]
webglContext在lost以后，尝试通过restoreContext救活，但是引擎里的_renderContext应该已经失效，现在有更新_renderContext的机制么？

**Comment by a417958382** [comment]
或者是在webglcontextlost以后，有可以救活的方式么？

**Comment by SantyWang** [comment]
抱歉，现在没有这个机制，未来应该会加上，你可以修改下引擎，在恢复之后，重新初始化下渲染引擎
