### ISSUE TITLE
start()函数问题

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#6068]
start函数如果这个函数里面报错了,那么h5 这个start就会执行一次,然后打印错误日志(浏览器)

但是native如果start出错了,就会一直 start执行.所以造成:如果一个界面start出错,则游戏就一直死循环调用start,然后游戏卡死现象.  native是否可以去掉这个特性,跟h5一样操作

或者告诉我怎么修改

**Comment by xianyinchen** [comment]
可以定位到jsb-adapter该文件的函数，按照下面实现，来防止事件因为报错而无法从事件队列中移除，出现无限报错情况。
![image](https://user-images.githubusercontent.com/8321365/123076187-77a6fc00-d44b-11eb-9bbd-ff395fae8f7b.png)
