### ISSUE TITLE
TiledMap rendering artefacts

### ISSUE THREAD

**Issue by ggarek** [cocos/cocos-engine#607]
Hey,

Tried to render tile map, here is the result:

<img width="781" alt="screen shot 2016-04-18 at 13 25 33" src="https://cloud.githubusercontent.com/assets/5501062/14601138/13a9de40-0569-11e6-90d7-6c1bed675d60.png">

As you can see, there are rendering artefacts.

Here is the texture, and the .tmx file:
![platformertiles](https://cloud.githubusercontent.com/assets/5501062/14601163/3adaea68-0569-11e6-8ed3-3d61b2d24c50.png)

[tmx-and-texture.zip](https://github.com/cocos-creator/engine/files/223545/tmx-and-texture.zip)

---

I am using Cocos Creator v1.0.1

**Comment by nantas** [comment]
We're looking into it. Thanks for your feedback!

**Comment by myonlylonely** [comment]
Is this bug fixed by [https://github.com/cocos-creator/engine/commit/7814b3fda638d7227aa80c19ad3bc25bdef0997b](url) ? @nantas  I am still facing the same problem when moving the maps.

**Comment by nantas** [comment]
should be fixed in v1.4
