### ISSUE TITLE
iPad设备偶现黑屏，需要重启设备才能恢复使用

### ISSUE THREAD

**Issue by MrHu4127** [cocos/cocos-engine#6089]
iPad设备偶现启动黑屏，并且一旦启动黑屏之后，杀进程再进入必现黑屏，只有重启设备才可以解决。
分享用户log之后发现，如下图，黑屏时，上面红色框的代码日志能过打印出来，但是下面红色框部分的日志就不会打印了。初步怀疑是onload没有执行
![1](https://user-images.githubusercontent.com/33243475/72231208-20192580-35f5-11ea-8a4a-56da969318c8.png)

**Comment by SantyWang** [comment]
应该是什么地方抛异常了，所以运行不到这里

**Comment by MrHu4127** [comment]
如果是代码异常的话，应该不会是非必现，而且必须重启设备才能使用

**Comment by xianyinchen** [comment]
这个需要提供ipad型号和系统版本，早期设备脚本运行环境会自动切换到JSC引擎，JSC 存在 promise 问题，需要自己使用第三方 promise 实现替换原有的 promise。这个可能是存在的问题之一。

**Comment by zhefengzhang** [comment]
用户长时间没有回复，问题暂时关闭。
