### ISSUE TITLE
The label width calculation is abnormal when italic font is used.

### ISSUE THREAD

**Issue by choi98772** [cocos/cocos-engine#6116]
The label width calculation is abnormal when italic font is used.

### Creator version?（版本号）
2.2.2(Maybe all versions)

### Affected platform?（受影响的平台）

all platform

### How to reproduce?（如何重现）
Add ui label to scene
set italic font to label

### JavaScript output or error produced?（报错信息和调用栈）

no error message
![cocosbug](https://user-images.githubusercontent.com/5504025/72517416-b4ee7e00-3896-11ea-9a5e-9bffac3bc0bd.png)

### Demo project?（demo 项目）

[https://github.com/choi98772/cocosfontbug.git](url)

**Comment by caryliu1999** [comment]
![image](https://user-images.githubusercontent.com/39078800/72676272-4f82d300-3aca-11ea-9a55-7bec3d9751b7.png)

There is a problem with the Font in the Demo. Need to adjust the right edge of the character，which is the position of the blue line.

![image](https://user-images.githubusercontent.com/39078800/72676310-d59f1980-3aca-11ea-9e2a-d59cea277e0c.png)

**Comment by SantyWang** [comment]
Thanks for your reporting

**Comment by choi98772** [comment]
How do I adjust the light edge of the font?
Do you want to modify it directly through the font tool?
Or is there a way to adjust in Cocos Creator?
I'm sorry, but on other game engines, the fonts are all displayed as normal (Unreal, Flash, Unity 3d, etc.).
