### ISSUE TITLE
从2.2.1升级到2.2.2之后，性能差了很多

### ISSUE THREAD

**Issue by yyymmmzzz** [cocos/cocos-engine#6118]
### Creator version?（版本号）
2.2.2

### Affected platform?（受影响的平台）

微信、QQ小游戏，安卓、iOS

**Comment by SantyWang** [comment]
可以使用 cc.pool.assembler.enable = true 试一下，这个在2.2.1原生上有点问题，在2.2.2被默认关闭了，你可以手动打开，但最好全面测试下有没有异常

**Comment by yyymmmzzz** [comment]
> 可以使用 cc.pool.assembler.enable = true 试一下，这个在2.2.1原生上有点问题，在2.2.2被默认关闭了，你可以手动打开，但最好全面测试下有没有异常

cc.pool.assembler.enable 这个是2dx里面的对象存储吧，creator里面没有

**Comment by SantyWang** [comment]
有的，2.2.2相比2.2.1就改了这个地方，这是当时的pr
https://github.com/cocos-creator/engine/pull/5905

**Comment by yuangu** [comment]
我想问一下，2.3版本做了修复了么？我现在也是用的2.2.2，发现性能确实不如前两个2.2版本，如果2.3修复的话，我就跟进至2.3版本。

**Comment by yyymmmzzz** [comment]
> 我想问一下，2.3版本做了修复了么？我现在也是用的2.2.2，发现性能确实不如前两个2.2版本，如果2.3修复的话，我就跟进至2.3版本。

不知道，2.3 不敢用啊
