### ISSUE TITLE
热更新重启后奔溃,求解决

### ISSUE THREAD

**Issue by daxiang1911** [cocos/cocos-engine#6129]
creator v2.2.1
更新完资源重启后就包这个错(里面有个dome)
Simulator: libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
E/jswrapper (176): [ERROR] (f:\jenkins\workspace\creator_2d\cocos2d-x-lite\windows\cocos2d-x-lite\cocos\scripting\js-bindings\manual\jsb_global.cpp, 176): Can't decrypt code for src/settings.jsc
E/jswrapper (710): ScriptEngine::runScript script src/settings.js, buffer is empty!
E/jswrapper (292): [ERROR] Failed to invoke require, location: f:\jenkins\workspace\creato

论坛地址 https://forum.cocos.org/t/topic/88500

**Comment by daxiang1911** [comment]
这个地方有个dome https://forum.cocos.org/t/topic/88500/8  大佬们看一下，什么问题

**Comment by SantyWang** [comment]
> Can't decrypt code for src/settings.jsc

报错看起来是解码失败，是不是加密的密钥不对

**Comment by xianyinchen** [comment]
该问题是由于热更新打包前后版本的加密密钥配置不一致导致。
