### ISSUE TITLE
MOUSE_LEAVE and/or TOUCH_CANCEL not triggered

### ISSUE THREAD

**Issue by moblabdev** [cocos/cocos-engine#6135]
### Creator version?（版本号）
2.2.2

### Affected platform?（受影响的平台）
Web (web_mobile)

### How to reproduce?（如何重现）
Build for web_mobile and drag mouse outside of the node region and/or canvas. The expectation is that TOUCH_CANCEL or MOUSE_LEAVE should trigger but neither is triggered.

### JavaScript output or error produced?（报错信息和调用栈）
No javascript error produced

**Comment by SantyWang** [comment]
Thanks for your reporting, could you provide a simple project to help us to reproduce this issue

**Comment by zhefengzhang** [comment]
The user has not responded for a long time, temporarily closed.
