### ISSUE TITLE
Vertex buffer bug CocosCreator 2.3_rc3

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#6136]
Switching one mesh with an other causes a render error in 2.3_rc3. It does work in web but not on native devices. Seems to work fine in CocosCreator 2.2 :)

Trying to switch the mesh from left to right, but vertices are not updated correctly.
```
this.model2.getComponent(cc.MeshRenderer).mesh = this.model1.getComponent(cc.MeshRenderer).mesh
```

![meshSwap](https://user-images.githubusercontent.com/8083536/73527389-43c0d600-4413-11ea-8c40-094657f0638d.gif)

**Comment by SantyWang** [comment]
Thanks for your reporting, my colleague will check it

**Comment by xianyinchen** [comment]
Sorry for the late reply, we can't reproduce this problem in 2.3.4, if the issue still exist on new version, please provide an test project, we will try.
