### ISSUE TITLE
Tiled组件 不支持 图像 的翻转.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6147]
### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
全部平台

### How to reproduce?（如何重现）
TIledMap 对象层里加入图片 ,  选择 水平翻转: 

![image](https://user-images.githubusercontent.com/288367/74173635-6c479c00-4c6d-11ea-981e-c2b54394fa45.png)

但是在cocos引擎里, 图像并没有翻转.

**Comment by finscn** [comment]
tiled 把元素 是否翻转的信息 存储在了 gid 里
具体的可以看一下 https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping

不仅 对像层 , tile图块层 也是如此. 通过gid来做存储关于反转的属性.

建议在 CCTMXXMLParser 阶段, 就直接提取出这部分信息, 以标准的属性形式存储在 mapInfo里

**Comment by finscn** [comment]
看了下代码, 应该在这里做下处理就行: 

![image](https://user-images.githubusercontent.com/288367/74177957-b5035300-4c75-11ea-9b21-9f2029c8607d.png)


但是有个地方要注意休息, 在翻转的时候,  是以图像中心点为锚点的,  但是在渲染的时候是0,0为锚点.
所以这个地方要特殊处理下, 不能直接翻转.

**Comment by finscn** [comment]
我尝试对  2.3 版本engine 的 CCTiledObjectGroup.js 文件做了个修改

![image](https://user-images.githubusercontent.com/288367/74182374-e2ec9580-4c7d-11ea-98e6-9071ae1522c3.png)


目前简单测试正交地图是ok的,  但是在 地图类型是 isometric 时  位置不对.
isometric 下锚点 和 object.x 都要做变换. 我这段代码没有做,  所以仅供参考

**Comment by finscn** [comment]
我又看了下代码 你们有做 object.xy的转换
但是转化方式错了

你们用的是:
```
                    let posIdxX = object.x / tileSize.width * 2;
                    let posIdxY = object.y / tileSize.height;
```

其实应该时 
```
                    let posIdxX = object.x / tileSize.height;
                    let posIdxY = object.y / tileSize.height;
```
不要怀疑 你没看错, 两个都是 ```height```.
因为很多时候 我们做 isometric 地图时,  高度都是宽度的一半, 所以 你们这个转换公式没有暴露出问题.
但是当 tile 宽高比不是 2:1 时, 就出问题了.

我和tiled作者交流过, 他这里在做变换时 用height来代替 tile的边长. 可以简化很多计算.
够着 tile边长(注意, 是边长) 需要用勾股定理计算.

所以他直接用height来代替边长.

比如下图  tile 宽度80,  高度60 , 标记点的 object.x/y 坐标在tiled里其实时 120,120

![image](https://user-images.githubusercontent.com/288367/74212908-a5b1f300-4cd1-11ea-8e7a-6a6cd4719420.png)

**Comment by finscn** [comment]
我搜了下代码
你们用了
```
 var posIdxX = object.x / tileSize.width * 2;
var posIdxY = object.y / tileSize.height;
```
的地方还不少

类似的转换公式 都要改

**Comment by sunnylanwanjun** [comment]
https://github.com/cocos-creator/engine/pull/6157 已在pr中支持
