### ISSUE TITLE
2.2.1版本Native的Graphics组件在touchMove事件回调中画图，切换场景回来之后还有残留

### ISSUE THREAD

**Issue by Panda-K** [cocos/cocos-engine#6163]
### Creator version?（版本号）
2.2.1

### Affected platform?（受影响的平台）

Android 和 Simulator
### How to reproduce?（如何重现）
Graphics组件在touchMove事件回调中画图，touchEnd事件中clear掉，然后切换到其他场景，再切换回来，会有之前画图的残留。

### JavaScript output or error produced?（报错信息和调用栈）

无

**Comment by SantyWang** [comment]
感谢反馈，2.3.1会进行修复，谢谢

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
