### ISSUE TITLE
建议不要用`arr.splice(0, 0, foo)` , 直接用 unshift .

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6188]
建议

### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
全平台

### How to reproduce?（如何重现）
源码可见

cocos engine里有两处用了类似 arr.splice(0, 0, foo) 的代码来实现 在数组前面加入一个元素的功能.
建议直接用 unshift .
代码更简洁, 语义上也更直观. 性能也好一点点点点...

**Comment by xianyinchen** [comment]
这类问题希望可以直接给引擎仓库提交优化PR，目前2.3不再更新了， 我们同事会提交个优化更新到最新的 2.x 版本。
