### ISSUE TITLE
2.3的 `creator.d.ts` 里有很多奇怪的语法错误

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6197]
### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
全平台
### How to reproduce?（如何重现）

![image](https://user-images.githubusercontent.com/288367/74852293-53c73800-5377-11ea-8660-506001101b8f.png)

![image](https://user-images.githubusercontent.com/288367/74852345-68a3cb80-5377-11ea-8f37-7b715f813578.png)

![image](https://user-images.githubusercontent.com/288367/74852400-75c0ba80-5377-11ea-8cb8-83477034134b.png)

**Comment by 2youyou2** [comment]
2.3.1 已经都修了~
https://github.com/cocos-creator/2d-tasks/issues/2518
