### ISSUE TITLE
3dParticle has wrong shader technique on Native

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#6200]
Changing the effect technique(add, alphaBlend, add-Multiply, etc.) of the Particle3d Material seems to have no effect on native/simulator, works perfectly fine on web :).
Cocos Creator 2.3, Mac Osx 10.15  

![particleMaterialBug](https://user-images.githubusercontent.com/8083536/74953243-b9600680-5401-11ea-8b05-ef9198f9bc9d.gif)

**Comment by SantyWang** [comment]
Thanks a lot, we'll check it out.

**Comment by caryliu1999** [comment]
@inkfood Thank you for your feedback. We have fixed it.
