### ISSUE TITLE
BUG: TiledMap组件无法通过编辑器隐藏某一个Layer

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6210]
#5284 # Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）
在编辑器里, 选择地图的某一个 TiledLayer节点,  把节点的 对号选择 去掉,  此时在编辑器里看不到该地图层.
但是在游戏运行时 还是能看到.

cc @sunnylanwanjun

**Comment by sunnylanwanjun** [comment]
以tiledmap编辑器中layer的visible属性为准了，在creator中修改active，在启动游戏时，会被tiledmap编辑器的设置覆盖。
