### ISSUE TITLE
creator.d.ts 里没有 collider.world

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6211]
### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
Mac Editor

### How to reproduce?（如何重现）
文档里  collider有world属性,  但是creator.d.ts里没有对应描述

**Comment by OnlyKoei** [comment]
![1](https://user-images.githubusercontent.com/40415168/109459068-06f16380-7a99-11eb-99fc-dcfe5d890f92.png)
在最新版2.4.x上以添加，这边就先关闭了。
