### ISSUE TITLE
No property `z` in `Vec2`

### ISSUE THREAD

**Issue by arniu** [cocos/cocos-engine#6212]
https://github.com/cocos-creator/engine/blob/051fd4f12b39d2457b025f7def17b74efbc3c178/cocos2d/core/value-types/vec2.ts#L770

**Comment by holycanvas** [comment]
OMG, It's a mistake. So sorry about it. We'll fix it.

**Comment by 2youyou2** [comment]
@arniu Thanks for your feedback!
