### ISSUE TITLE
Can not find class "cc.ParticleSystem3D" on iOs build Xcode

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#6214]
While building a project of Cocos Creator 2.3 which contains a 3d particle system in xCode, this error pops up. 

<img width="359" alt="Screenshot 2020-02-24 at 05 22 27" src="https://user-images.githubusercontent.com/8083536/75128774-0d9b0d00-56c6-11ea-92b1-1b149491432a.png">

**Comment by SantyWang** [comment]
Thanks for your reporting. Please make sure that you have checked `3D Particle` module in project settings.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/15109777/75131345-9e490b80-570d-11ea-99ee-2f70babfb7c6.png">

**Comment by MarkusTieche** [comment]
Works perfectly fine, thank you :). Documentation?

**Comment by SantyWang** [comment]
Please refer this, https://docs.cocos.com/creator/manual/en/3d/particle-system-3d.html
