### ISSUE TITLE
在频繁的设置  node.zIndex 一段事件后,  zIndex出现混乱的情况

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6225]
### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
mac

### How to reproduce?（如何重现）

        发现在频繁的设置  node.zIndex 一段事件后,  zIndex出现混乱的情况.
        代码片段如下: 
```
        // zmapping 里记录了 zindex 和 children索引的映射关系
        // children.length 为 60
        for (let idx = 0; idx < children.length; idx++) {
            children[zmapping[idx]].zIndex = idx;
        }
```
        以上代码会在每一帧都进行( 每一帧都会对某节点的所有子节点进行重新排序)
        一开始程序是符合预期在运行. 但是过一段时间 就不对了.
        我排查了排序算法, 以及zmapping里的映射关系, 没发现问题

**Comment by finscn** [comment]
我找到原因了

```js
  sortAllChildren: function sortAllChildren() {
    if (this._reorderChildDirty) {
      this._reorderChildDirty = false; // delay update arrivalOrder before sort children

      var _children = this._children,
          child;
      this._parent && (this._parent._childArrivalOrder = 1);

      for (var i = 0, len = _children.length; i < len; i++) {
        child = _children[i];

        child._updateOrderOfArrival();
      }
 ......

    }
......
  }
```

引擎的这段代码有问题. 
应该重置  this._childArrivalOrder , 而不是 this._parent._childArrivalOrder.
因为 child._updateOrderOfArrival 里的parent其实是 this, 需要重置this._childArrivalOrder

**Comment by SantyWang** [comment]
感谢，合到了2.3.1版本
