### ISSUE TITLE
[BUG] 3D粒子组件官方示例就有bug

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6235]
### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
mac

### How to reproduce?（如何重现）
打开 examples项目 ( 官方范例项目) 
运行 particle-trail2 示例. 
适当的修改动画中 x y z  的坐标,  让其在3d空间里运动 (原始示例只是y轴运动)

于是会出现下面图中的bug 
1 在底端反弹时 有多余的折线
![image](https://user-images.githubusercontent.com/288367/75340707-f2025300-58cd-11ea-8070-bcd42d514a20.png)
![image](https://user-images.githubusercontent.com/288367/75340729-fc245180-58cd-11ea-99e6-f79f5f0a935a.png)

2 回来时 中间拖尾会断掉. (见动图, 速率我已经降低)
![ScreenFlow 2020-02-26 19_30_21](https://user-images.githubusercontent.com/288367/75341032-8a98d300-58ce-11ea-8382-d2773e38a0a9.gif)

**Comment by zhefengzhang** [comment]
感谢反馈，问题已经反馈给引擎开发团队处理，issues 暂时关闭。
