### ISSUE TITLE
龙骨动画 组件 对 playTimes 的支持存在bug

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6252]
### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
mac

### How to reproduce?（如何重现）
当设计师导出的动画 是无限循环播放时,  
我在调用api `playAnimation` 播放动画时,  不管playTimes参数是多少, 动画都始终是无限循环播放.

**Comment by sunnylanwanjun** [comment]
实际上ArmatureDisplay 就是转调了下dragonbones库的Animation的play方法，没有作额外的处理，应该不是引擎本身带来的bug。
不过这儿有个疑问，既然编辑器导出的时候设置了无限循环，dragonbones的runtime，要如何知道“啥时候结束”算播放一次呢？

**Comment by finscn** [comment]
@sunnylanwanjun  循环播放 也是指的 到了最后一帧 之后, 再重头播放.
库的内部是能拿到 当前是否是播放到了最后一帧的. 否则那些帧事件就没法实现了

**Comment by finscn** [comment]
@sunnylanwanjun ,  

我又验证了一些.  和子骨架有关. 没有子骨架时 是正常的.

所以我觉得 cc封装的 这一层龙骨的代理 并没有考虑到 子骨架的情况.

我们的动画子骨架是帧动画. (骨骼动画的某个插槽上插入了一个帧动画)

我现在的解决方法是 弃用 dragonBones.ArmatureDisplay上的playAnimation.
而是用:
```
armatureDisplay.armature().animation.play(....)
```
以前就都正常了.
但是也因此失去了一些cocos提供的特性 (比如缓存相关的)
