### ISSUE TITLE
【必要需求】龙骨插件 需要 stopAnimation 方法.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6253]
如果没有stopAnimation方法，  那么当骨架上的插槽里挂接了子元件的话
子元件无法正确重复播放。
比如我播放动画 abc 1次

playAnimation("abc", 1) 
播放后,再播放:
playAnimation("abc", 1) 
动画会一直停止在最后一帧.

所以现在我要
stopAnimation("abc") 
playAnimation("abc", 1) 

我写了个参考  cocos开发人员可以看一下
ArmatureDisplay 类里

```
  stopAnimation: function stopAnimation(animName) {
    this.playTimes = -1;
    this.animationName = animName;

    if (this.isAnimationCached()) {
      var cache = this._armatureCache.getAnimationCache(this._armatureKey, animName);

      if (!cache) {
        cache = this._armatureCache.initAnimationCache(this._armatureKey, animName);
      }

      if (cache) {
        this._accTime = 0;
        this._playCount = 0;
        this._frameCache = cache;

        if (this.attachUtil._hasAttachedNode()) {
          this._frameCache.enableCacheAttachedInfo();
        }

        this._frameCache.updateToFrame(0);

        this._playing = true;
        this._curFrame = this._frameCache.frames[0];
      }
    } else {
      if (this._armature) {
        return this._armature.animation.stop(animName);
      }
    }
  },
```

你们可以看一下 龙骨自己的官方的 demo播放器， 也是在动画播放时会先调用 stopAnimation的
龙骨官方的 stopAnimation 很简单, 因为它有一个 lastAnimationState 的东西.
直接 lastAnimationState.stop() 就行了 . 但是在cocos里没找到获取的方法.

**Comment by finscn** [comment]
不提供自己记录 也行 . 我现在是这么做的: 
![image](https://user-images.githubusercontent.com/288367/75622592-0f406580-5bdd-11ea-8744-76bcdd82dd18.png)

相当于自己记录 last animationState.  然后播放动画前 把前一个stop

**Comment by a834286983** [comment]
我也遇到这个问题了，由于项目用到了大量的龙骨，导致游戏CPU占用过高，官方大佬救命~！！！！
