### ISSUE TITLE
龙骨动画的事件回调参数类型不正确.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6255]
### Creator version?（版本号）
2.3

### Affected platform?（受影响的平台）
全平台

### How to reproduce?（如何重现）
![image](https://user-images.githubusercontent.com/288367/75628960-d6be7d00-5c18-11ea-9719-60ecde2adb21.png)

龙骨回调函数的参数用了 cc.Event 类型,  导致实际开发时无法得到正确的编译器检查和语法提示.
建议针对龙骨, 定义一个新的Event类型描述,  或则给cc.Event加入
[string as index]: any

**Comment by xianyinchen** [comment]
这个定义已经有了的，你可以看下这样书写
``` javascript
 var _weaponR =this.db.armature().getSlot('weapon_r').childArmature;
  _weaponR.addEventListener(dragonBones.EventObject.FRAME_EVENT, (event: dragonBones.EventObject)=>{
      console.log(event.name)
      console.log(event.animationState);
  }, this)
```
