### ISSUE TITLE
不支持node_modules里面的module包和不支持环境变量process.env.xxx

### ISSUE THREAD

**Issue by vicwang163** [cocos/cocos-engine#6261]
### Creator version?（版本号）
2.2.0

### How to reproduce?（如何重现）

对于这种都不能处理
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./engine.cjs.production.min.js')
} else {
  module.exports = require('./engine.cjs.development.js')
}

**Comment by xianyinchen** [comment]
你好，creator不支持这种处理，建议提前使用webpack打包成单个JS文件，然后以插件脚本的形式导入到creator中。
https://docs.cocos.com/creator/2.2/manual/zh/scripting/plugin-scripts.html
