### ISSUE TITLE
仿照cocos2dx做资源引用计数,用于释放资源

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#6281]
现在这个释放资源太难维护了,对于大一点的项目来说,资源的相互引用造成很大问题.所以可以按照cocos2dx那样,增加引用计数的原理,来管理资源,这样,可以用一个函数,释放掉现在不使用的资源内存.

比如图片被组件引用+1  组件被释放-1  这种原理

**Comment by 284263380** [comment]
现在资源释放要么是根据目录,或者单个资源.小项目还可以.大项目资源分类本来就很难,在加上很多界面会用到其他界面的某一个图片,又不能单独为了引用一个图片,临时将这一个图片重新归纳新的文件夹(或者说是类型),并且还有很多动态添加的组件

**Comment by zhefengzhang** [comment]
2.4.x 版本开始支持了。建议您升级到 2.4.x 版本或者 3.x 版本试试。
