### ISSUE TITLE
资源被释放了,则如果再次打开perfab,是否可以添加保护

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#6282]
一个正在使用的资源被释放了,则如果再次打开perfab,则渲染出错,然后一直报错,造成游戏没法完了(一直卡死),

解决方案:是否可以通过检查这个是否还是一个有效资源来确认渲染操作,如果不是有效资源,则不渲染,加一个保护

**Comment by xianyinchen** [comment]
你好，请问你使用的creator版本是多少？2.4.x版本资源管理添加了引用关系，你如果使用decRef这类接口去做资源释放操作，不会出现你提到的问题，可以参考文档。
https://docs.cocos.com/creator/manual/zh/asset-manager/release-manager.html
