### ISSUE TITLE
[TiledMap组件bug] 隐藏的图像对象还是会被渲染出来

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6302]
### Creator version?（版本号）
2.3.1

### Affected platform?（受影响的平台）
全平台

### How to reproduce?（如何重现）
地图编辑器里将 对象层 的某个image对象隐藏,  游戏中还是会被渲染.

![image](https://user-images.githubusercontent.com/288367/76164791-ab91db80-618c-11ea-8f9f-3fd7a608f0ce.png)

cc @sunnylanwanjun

**Comment by sunnylanwanjun** [comment]
已修复，感谢反馈
