### ISSUE TITLE
[需求]希望MotionStreak组件能支持opacity 特性

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6307]
### Creator version?（版本号）
2.3.1

目前改组件不支持设置 透明度,  虽然可以通过指定一张有透明度的图片来间接实现, 但是如果透明度是动态变化的 则难以实现.
所以 希望MotionStreak组件能支持opacity 特性.

**Comment by OnlyKoei** [comment]
动态修改 MotionStreak 组件上的 color 就行，测试版本2.4.6
