### ISSUE TITLE
希望新建项目和打开项目时, 支持 路径中的 `@` 符号

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6310]
虽然提示里说了 只支持 数字 英文 下划线 等等,   但是其实引擎和编辑器的底层架构是支持@的.

只是在新建项目是 路径输入框里 人为的限制了 @ .

而其他地方基本都支持@ .  @符号如今也算是常见的路径和文件名符号了.

**Comment by finscn** [comment]
再次呼吁一下.
在移动互联网时代,   `@` 已经和 `_` `-` 一样, 已经是文件路径里比较常见的特殊字符了.
形式如:      user@project   ,   user@team ,    file@2x  ,  file@mdpi  ... 的名字已经比较常见了.

**Comment by finscn** [comment]
再次呼吁下.  @jareguo @2youyou2 @holycanvas 

其实 creator 是支持@的. 只是新建项目时 路径那里有@符号时 报错, 理论上只要修改那里的校验函数就行.

**Comment by yeshao2069** [comment]
感谢反馈，你的需求已经提交引擎组。

**Comment by yeshao2069** [comment]
1.0.16版本我们会放松名称规范，但是不允许包括 @ 等特殊符号

如果真的希望用 @ 符号，可以在文件夹使用，例如 E:\CocosProj@user\project1
