### ISSUE TITLE
这个return的跳出缺少了cc.view._viewportRect变化的判断, 导致placeholder错位了

### ISSUE THREAD

**Issue by zty8023ys** [cocos/cocos-engine#6319]
https://github.com/cocos-creator/engine/blob/3319b8596729dcc83a2c52607d1e072aeecd8f6a/cocos2d/core/components/editbox/WebEditBoxImpl.js#L311

![image](https://user-images.githubusercontent.com/7736339/76501230-d9bd3700-647c-11ea-8727-82ed73dfbbbe.png)

应该添加cc.view._viewportRect变化的判断. 目前的bug是窗口变化会是placeholder错位
打开具有editbox的界面, 然后修改浏览器窗口大小, 然后点击editbox, 就看到placeholder错位了

![image](https://user-images.githubusercontent.com/7736339/76500913-57347780-647c-11ea-8d54-dd711fe5b952.png)

![image](https://user-images.githubusercontent.com/7736339/76500887-4be14c00-647c-11ea-98d1-167b5ebd99eb.png)

个人临时解决方案
![image](https://user-images.githubusercontent.com/7736339/76501044-8ba83380-647c-11ea-8a7d-db4b58b4a46e.png)

**Comment by zty8023ys** [comment]
@umbrellaPP @jareguo

**Comment by SantyWang** [comment]
感谢反馈

**Comment by PPpro** [comment]
感谢反馈，修复会进入下一个版本
