### ISSUE TITLE
安卓下，场景加载时，不管是场景中的资源还是动态加载的资源，都会有概率出现白色

### ISSUE THREAD

**Issue by withu2018** [cocos/cocos-engine#6331]
### Creator version?（版本号）
2.3.1

### Affected platform?（受影响的平台）
测试了安卓和ios，只出现了安卓，而且可以复现
ios未出现，网页测试未出现，模拟器未出现，web未出现

### How to reproduce?（如何重现）
场景不断切换
https://forum.cocos.org/t/cocos-creator2-3-1-bug/90038

### JavaScript output or error produced?（报错信息和调用栈）
无报错。在调试模式下未能复现。

### Demo project?（demo 项目）
cocos creator2.3.1中自带项目和我开发的项目都能复现。

**Comment by withu2018** [comment]
补充，已测出iphone8上也出现了该问题
https://forum.cocos.org/t/cocos-creator2-3-1-bug/90038/2?u=271833059

**Comment by SantyWang** [comment]
感谢你的反馈，麻烦你试下这个pr能否修复你的问题，感谢。https://github.com/cocos-creator/cocos2d-x-lite/pull/2258
