### ISSUE TITLE
mac10.15.3 android studio 3.6.1 安卓编译时，有很多fcntl(): Bad file descriptor警告，案例项目也有

### ISSUE THREAD

**Issue by withu2018** [cocos/cocos-engine#6332]
cocos creator 2.3.1 提供的案例项目，默认编译配置

**Comment by yeshao2069** [comment]
感谢反馈。
经过测试验证，并没有发现这个问题。如果还有疑问，可以再次和我们反馈。

测试Creator版本：2.4.5
测试工程： 默认的helloworld-ts工程
测试设备：mac book pro    macOS 11.3.1
测试平台：android
测试android studio版本：
![image](https://user-images.githubusercontent.com/14273437/123393869-1c9f1180-d5d1-11eb-9d85-98e735178af9.png)
测试结果
![image](https://user-images.githubusercontent.com/14273437/123393970-32acd200-d5d1-11eb-89b7-9ec33ef5c6bd.png)
测试工程：
[NewProject_1.zip](https://github.com/cocos-creator/engine/files/6714699/NewProject_1.zip)
