### ISSUE TITLE
camere.render (root) 的参数是可选的, creator.d.ts里没有体现

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6334]
camere.render (root) 的参数是可选的, creator.d.ts里没有体现

另外 game._renderContext 也没有

导致 文档里 https://docs.cocos.com/creator/manual/zh/render/camera.html?h=%E6%88%AA%E5%9B%BE 
代码报错

**Comment by finscn** [comment]
不是真的错 而是 vscode提示错误

**Comment by OnlyKoei** [comment]
私有方法目前我们还是认为应该开发者自己定义，而不是由我们来定义。
暂时这个就先关了，有其他问题再联系我们进行处理
