### ISSUE TITLE
[建议] 当自定义引擎找不到 或者报错时, 项目以内置引擎启动, 并且给出提示. 而不是...

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6344]
[建议] 当自定义引擎找不到 或者报错时, 项目以内置引擎启动, 并且给出提示. 而不是没有反应 卡死

**Comment by SantyWang** [comment]
现在是这样的呀。。可能有地方出问题了

**Comment by finscn** [comment]
> 现在是这样的呀。。可能有地方出问题了

是的.  我把自定义引擎的 目录名修改了.  启动不起来了.  macOS ,  最新的cocos creator

**Comment by SantyWang** [comment]
已修复
