### ISSUE TITLE
[需求] 需要提供一个 空白Texture2D. 不占用内存资源, 用于占位.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6374]
我需要提前创建好 一些 sprite 并初始化好大小, 但是不设置图片 , 用来在后期使用 (类似一个 对象池)

但是现在cocos不支持 类似 空白texture 一类的对象, 而 texture又是 准备期必备的. 否则给 精灵设置 spriteFrame时报错.
我尝试继承 Texture2D 自己写一个. 但是按照ts的规范, 我必需调用 Texture2D 的构造函数, 但是 Texture2D构造函数里 直接就调用了``` gl.createTexture()```  这不是我希望的.
这样也失去了  "只是构造一个空的, 什么都不做的 texture2d 的意义.

希望 Texture2D 能把构造函数进行重构,  方便继承它创建一个空的Texture2D

**Comment by finscn** [comment]
比如, 现在的代码 :

```
  constructor(device, options) {
    super(device);

    let gl = this._device._gl;
    this._target = gl.TEXTURE_2D;
    this._glID = gl.createTexture();

    // always alloc texture in GPU when we create it.
    options.images = options.images || [null];
    this.update(options);
  }
```

重构成
```
  constructor(device, options) {
    super(device);

    options.images = options.images || [null];

    this.init(options);

    // always alloc texture in GPU when we create it.
    this.update(options);
  }

  init(options) {
    let gl = this._device._gl;
    this._target = gl.TEXTURE_2D;
    this._glID = gl.createTexture();
  }

```

这样子类可以重写 init, 来让它什么都不做.


当然 还是希望官方出一个真正的 EMPTY Texture 
(pixi 就有这个玩意 )

**Comment by jareguo** [comment]
@LinYunMo 在 3D 里，这种需求是如何满足的呢？如果能满足 2D 这个时候就不做这个重构了吧

**Comment by jareguo** [comment]
谢谢反馈，在 Creator 3.0 的版本中已经默认延迟 init gpu 资源。目前的版本先不改动了。
