### ISSUE TITLE
creator.d.ts 问题整理贴 (持续更新)

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6386]
最近在一些相对底层的开发, 整理一些 我觉得 cocos creator 的ts描述文件缺失的东西:

* 不包含私有方法和属性
* 常见错误有 :  缺失描述,  类型错误 , 可选性错误
* 其实我觉得有一些私有方法应该暴露出来. 对性能优化很有帮助.
* 只罗列, 每一条就不写具体原因了

------
Material.getProperty

cc.Trs
cc.gfx
cc.Effect
EffectAsset.getEffect

RenderTexture.updateSize 
Material.techniqueIndex
Material.setBlend
Node.getWorldPosition
Node.setWorldPosition
Material.getBuiltinMaterial
Material.getInstantiatedBuiltinMaterial
Material.getInstantiatedMaterial
RenderComponent.setMaterial
RenderComponent.markForRender

**Comment by finscn** [comment]
更新:

Camera.render 
RenderComponent.setVertsDirty

Collider.world

**Comment by yuzp2160hot** [comment]
2.3.2中
export class _BaseNode extends Object 
应该是
export class _BaseNode extends EventTarget

**Comment by finscn** [comment]
更新:

cc.visibleRect  (缺失)

**Comment by jareguo** [comment]
私有方法目前我们还是认为应该开发者自己定义，而不是由我们来定义。

**Comment by arniu** [comment]
`Vec2`、`Vec3`、`Vec4` 个别方法入参、出参类型标记不合理，或限制太死，或丢失类型信息。

具体见 [TypeScript Play 样例](https://typescript-play.js.org/#code/JYOwLgpgTgZghgYwgAgJIDUIIEwBlgDWKA3gFDLIAeAXMiAK4C2ARtANznICetDL7pAL6lSCADZwAzpOSYcyYIwAOYiIwjgZGLHkIlOCAPYhJYKPQRhDUABRL6zMcARVeTVlGQBeZAAYANMj2js7cbvyePr4AlMjEwpymcGChcAAmaQA8APL0YMgQlJAgaVpyukQAfDaGebS5YIFw9XmBzC1gsWQUFLVgAHSU3shwg8gA1MjMgxw9yH39XMOjS5PTXLM9UBBg9FAg83mbCRRJKS7paQD6hgQ5eQVFGqVo5fhVNXXIDU202jjvCBtP5vPRdTi9PJjHyjIZrGYQw4DJYwxYTKaLTYUba7fZI44iChpCCSBBQYBKFLGGzguY4vYHAAGNgAJMQwAALYCSQaCQJszncxaCaKMgmcS42MC0cqBPoAfhlOlpPT6wzVAB8NXQIAB3WQ6GlYpHQ5CCnlws0IuYLFFmrk81ZWjaI+l4vriiiXG53AAqj2KL3+FQg1WlyF9cryioNOBVkPyPk12pAetj2CNiIWQx85rGkwGlGNtuGeadyONboOHs4wgSRhM+SUhlAieQNhzfkCdsosS8lXbxCo3eQIo4pFT+vKNP6kubrZsAEZAovotEOJP0zPvbc7C3wEuV2vx+VZxkbJvp9FAvOD9egvuwDTov1iaTyZTgNT16RTzuCBeaZXjej40iBC5rq+JJkhSVIgJmQA)。

**Comment by jareguo** [comment]
得尽可能使用 IVec2Like 是吧？不过 description 这个无解吧？

**Comment by jareguo** [comment]
> 2.3.2中
> export class _BaseNode extends Object
> 应该是
> export class _BaseNode extends EventTarget

EventTarget 是 implement 才对，不是继承

**Comment by finscn** [comment]
sp.Skeleton.setAnimation : 返回值不对
sp.Skeleton.findAnimation : 返回值不对
sp.Skeleton.findSlot : 返回值不对

**Comment by arniu** [comment]
> 得尽可能使用 IVec2Like 是吧？不过 description 这个无解吧？

也不尽然，需对入参、出参区别对待：

- 入参，尽可能使用 `IVec2Like`，提高函数泛化能力；
- 出参，要使用泛型，尽可能保留类型信息。

至于 `description`，是演示类型信息丢失的，请不必在意。

**Comment by finscn** [comment]
@2youyou2 @sunnylanwanjun 

Material.setBlend()  方法的 第一个参数类型不对.

**Comment by zhefengzhang** [comment]
> sp.Skeleton.setAnimation : 返回值不对
> sp.Skeleton.findAnimation : 返回值不对
> sp.Skeleton.findSlot : 返回值不对

我在 2.4.0 版本上检查了一下，发现没有错呢。

**Comment by jareguo** [comment]
@finscn 关联的几个 PR 已经都修复啦。可以点开看看。或者之后如果还有遗漏欢迎再反馈！谢谢！

**Comment by finscn** [comment]
![image](https://user-images.githubusercontent.com/288367/83850632-c94aee80-a743-11ea-8591-4352a976f5dc.png)


cc.Audio 相关内容 没有在 creator.d.ts 里暴露 

@jareguo

**Comment by jareguo** [comment]
抱歉这是我们的底层模块，是 Cocos-2d 遗留下来的接口，之后我们会调整为私有的。目前在文档中是没有相关介绍的，API 也没有，将来也不会进行暴露。
