### ISSUE TITLE
[需求] 提供一个通过字符串动态创建EffectAsset 的方法

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6388]
在某些场景下, 需要动态生成 着色器代码. 
希望 cocos creator 能满足这个需求,  提供 从字符串动态创建 EffectAsset  的方法.

我猜内部应该是有的吧, 只是没暴露出来.

**Comment by yeshao2069** [comment]
感谢反馈，这个需求已经提交给引擎组，谢谢。
