### ISSUE TITLE
spriteFrame.setRect 无效, 需要resize一下node才能生效

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6390]
### Creator version?（版本号）
2.3.2

直接调用api
```
    sprite.spriteFrame.setRect(cc.rect(10, 10, 500, 250));
```
无法改变精灵的rect, 设置后没有效果. 必需这样才行:
```
            sprite.spriteFrame.setRect(cc.rect(10, 10, 500, 250));
            sprite.node.width++;
            sprite.node.width--;
```

我觉得应该是bug.

**Comment by finscn** [comment]
看了下源码,  核心问题是 修改rect 时, 内部没有调用
setVertsDirty()

所以虽然UV重新计算了 但是还有一些状态没有刷新.

sprite.spriteFrame.setRect(cc.rect(10, 10, 500, 250));
sprite.setVertsDirty()

这样就可以了.  但是 creator.d.ts里没有暴露setVertsDirty, 建议增加.

**Comment by jareguo** [comment]
所有资源对引擎来说，都是不可变的。引擎不可能监听资源的所有改动。所以如果资源发生改变，需要重新赋值给引擎。你只要重新执行 sprite.spriteFrame = sprite.spriteFrame; 引擎就会刷新了。目前 spriteFrame 赋值时，这几个是会依次调用到的：
_applySpriteFrame -> _applySpriteSize -> setVertsDirty
