### ISSUE TITLE
The first argument of `Vec2#add` shoule be `IVec2Like` 

### ISSUE THREAD

**Issue by arniu** [cocos/cocos-engine#6424]
https://github.com/cocos-creator/engine/blob/3319b8596729dcc83a2c52607d1e072aeecd8f6a/cocos2d/core/value-types/vec2.ts#L886

`vector` should be `IVec2Like`.

**Comment by shrinktofit** [comment]
@2youyou2

**Comment by OnlyKoei** [comment]
already modified,test version 2.4.6:
![image](https://user-images.githubusercontent.com/40415168/127449266-7c7e635c-8d53-475e-93c1-2b737ada1dba.png)
