### ISSUE TITLE
使用 Firefox 打开预览，控制台提示 “http://localhost:7456/settings.js” 不是有效的 JavaScript MIME 类型

### ISSUE THREAD

**Issue by arniu** [cocos/cocos-engine#6459]
### Creator version?（版本号）

Version 2.3.1

### Affected platform?（受影响的平台）

Mac Editor

### How to reproduce?（如何重现）

创建空项目并运行，用 Firefox 打开预览，查看控制台，可见如下警告：

> 即使其 MIME 类型（“text/html”）不是有效的 JavaScript MIME 类型，仍已加载来自“http://localhost:7456/settings.js”的脚本。

另附环境信息如下：

- MacOS 10.15.4
- Firefox 74.0

### JavaScript output or error produced?（报错信息和调用栈）

无。

### Demo project?（demo 项目）

官方 [hello-world](https://github.com/cocos-creator/hello-world)。

**Comment by arniu** [comment]
类似还有 #6461

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/112604969-bd0a5c00-8e51-11eb-8d49-8befff46d71d.png)
这是浏览器兼容性问题。
