### ISSUE TITLE
使用 Firefox 打开预览，控制台提示 Error: WebGL warning: texSubImage 相关警告

### ISSUE THREAD

**Issue by arniu** [cocos/cocos-engine#6461]
### Creator version?（版本号）

Version 2.3.1

### Affected platform?（受影响的平台）

Mac Editor

### How to reproduce?（如何重现）

创建空项目并运行，用 Firefox 打开预览，查看控制台，可见如下警告：

> Error: WebGL warning: texSubImage: Texture has not been initialized prior to a partial upload,forcing the browser to clear it. This may be slow. texture-2d.js:177:9
> Error: WebGL warning: texSubImage: Tex image TEXTURE_2D level 0 is incurring lazy initialization. texture-2d.js:177:9

另附环境信息如下：

- MacOS 10.15.4
- Firefox 74.0

### JavaScript output or error produced?（报错信息和调用栈）

无。

### Demo project?（demo 项目）

官方 [hello-world](https://github.com/cocos-creator/hello-world)。

**Comment by xianyinchen** [comment]
It is safe for the engine to start some processing that will trigger such warnings. If it occurs during runtime then you need to be concerned about.
