### ISSUE TITLE
原生打包后 无法捕获全局 Promise.reject 事件, 但是 h5 模式下可以

### ISSUE THREAD

**Issue by Aslijia** [cocos/cocos-engine#6480]
### How to reproduce?（如何重现）
window.__errorHandler 或者 window.onerror 设置好监听打印
然后在逻辑代码中 throw Error 和 async 函数内 Promise.reject 测试, 会发现 reject 在原生应用中无法捕获

**Comment by shrinktofit** [comment]
@pandamicro  这是一个已知问题

**Comment by yeshao2069** [comment]
@shrinktofit    现在这个有修复吗？

**Comment by yeshao2069** [comment]
感谢反馈，这个问题已经修复了。你可以升级到最新版本(2.4.6) 或者3.1.2版本，试试
