### ISSUE TITLE
AudioSource 音频时,  播放 & 暂停的 一个bug 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6492]
### Creator version?（版本号）
2.3.2

用dom audio时,  play之后 如果在比较短的时间内, 比如50毫秒内(不一定, 取决于音频文件), 调用暂停 或者 stop, 就报错.

具体原因见:   https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

**Comment by PPpro** [comment]
感谢反馈，该异常应该不影响 API 使用，目前已经捕获了相关异常
