### ISSUE TITLE
double shadow bug 

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#6512]
Shadow projection is not blocked by surface and appears on other side, adjusting frustum size or minDepth/maxDepth does not help.
Default Phong shader on CocosCreator 2.3.2 on osX

<img width="1066" alt="Screenshot 2020-04-08 at 16 41 07" src="https://user-images.githubusercontent.com/8083536/78797807-832e1480-79b8-11ea-902a-6e3e9cf51970.png">
<img width="461" alt="Screenshot 2020-04-08 at 16 41 30" src="https://user-images.githubusercontent.com/8083536/78797827-888b5f00-79b8-11ea-88c6-d26196459647.png">

**Comment by MarkusTieche** [comment]
Seems to be fixed in CocosCreator 2.3.3

**Comment by SantyWang** [comment]
Thanks for your checking
