### ISSUE TITLE
2.3.3 引擎的版本号文本错误

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6520]
这两个文件里写的还是 2.3.2
 package.json
 predefine.js

**Comment by SantyWang** [comment]
没有吧，我这是正常的呢，用了自定义引擎了？
![image](https://user-images.githubusercontent.com/15109777/81463574-0d9ea980-91ed-11ea-8518-46c48ae09382.png)
![image](https://user-images.githubusercontent.com/15109777/81463580-17281180-91ed-11ea-9ec3-ca98ed0da655.png)
