### ISSUE TITLE
[Question] Scene transitions

### ISSUE THREAD

**Issue by LiadIdan** [cocos/cocos-engine#6528]
Hi,

Sorry in advance I know that I'm not supposed to post questions here, but I couldn't find an answer to this question anywhere.

I'm trying to create a transition between two scenes when the new scene will slide up on top of the current scene. From what I found in the docs the only way to load a new scene is by using the `cc.director.loadScene` method, but it's also removing the current scene instantly.

So is there any way to prevent/delay the removal of the current scene when using `loadScene`? Or maybe a different method to load new scenes and translate between them using tweens?

Many thanks!

**Comment by mrspd** [comment]
You can render current scene to texture, add that texture to persist node, load new scene and then run translate animation.

**Comment by LiadIdan** [comment]
@mrspd that could work if the current scene is static, but for scenes with running animations, it doesn't solve anything. Also, taking a screenshot each time you switch between scenes feels a bit sloppy.

**Comment by yeshao2069** [comment]
have a try :

https://github.com/2youyou2/transitions

**Comment by yeshao2069** [comment]
You can try to follow the plan. If you have any other questions, please feel free to give us feedback. Thanks.
https://github.com/2youyou2/transitions
