### ISSUE TITLE
[Feature Request] Support For TypeScript Paths

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#6532]
### Creator version? 2.3.3

Currently the TypeScript Pahts in the tsconfig.json does not work, you just get errors when you try to run with these.

Here is a very detailed thread I've discussed this already a couple of years ago. I think it would be nice to get the Paths working with Cocos Creator.

https://discuss.cocos2d-x.org/t/compile-error-cannot-require-typescript/40997

Thanks!

**Comment by shrinktofit** [comment]
@2youyou2  Could this be supported in 2D? 3D has supported.

**Comment by OnlyKoei** [comment]
Issue has been created to deal with this problem, this side first shut down。 #https://github.com/cocos-creator/3d-tasks/issues/7539

**Comment by Ronsku** [comment]
https://github.com/cocos-creator/3d-tasks/issues/7539 page not found 🤔

**Comment by shrinktofit** [comment]
Creator 3.3(comming soon) shipped the experimantal import map feature. By which you can implement the affects like tsconfig paths.
