### ISSUE TITLE
动态切换 Sprite材质 时的bug

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6543]
### Creator version?（版本号）
2.3.3

### Affected platform?（受影响的平台）
全平台.

代码:
![image](https://user-images.githubusercontent.com/288367/79110518-30d06780-7dad-11ea-988c-1d26748a94fa.png)

期待效果:  在彩色和黑白之间切换.
实际效果 , 第一次切换ok, 后面就只有黑白的正常,  变成彩色时,  只是显示一个白色矩形.

**Comment by finscn** [comment]
原因是 , 通过编辑器设置 buildin-2d-sprite 时,  "USE_TEXTURE" 是默认选中的.

![image](https://user-images.githubusercontent.com/288367/79111174-98d37d80-7dae-11ea-92c7-78b166655aed.png)

但是通过代码创建时,  要自己执行``` meterial.define("USE_TEXTURE", true);```
否则图片不会传到shader里, 导致了错误.

我把代码改成下图这样 就可以了.
![image](https://user-images.githubusercontent.com/288367/79111296-d6380b00-7dae-11ea-8064-aa91b3720bbb.png)

我的建议是这个地方应该统一行为. 或者变成智能化的. 如果spriteFrame有texture, 那么就默认启用USE_TEXTURE.

**Comment by finscn** [comment]
另外针对 2d-gray-sprite 和 2d-sprite 额外多说两句.
我觉得  2d-gray-sprite 里没有判断 是否使用图片的宏,  而2d-sprite  里有. 我觉得他们两个歧视也应该统一.

还有个疑问实际项目里 , 会有选择了2d-sprite材质,  但是又不给它传texture的情况吗? 
如果没有, 建议去掉相关的宏 (类似 gray-sprite那样)

如果极少数情况下会有不需要texture的情况, 那么可以考虑提供一个新的材质.

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
