### ISSUE TITLE
2.3.3版本手动setPremultiplyAlpha会flipY纹理

### ISSUE THREAD

**Issue by xifengxi** [cocos/cocos-engine#6546]
### Creator version?（版本号）
2.3.3

### Affected platform?（受影响的平台）

Web
### How to reproduce?（如何重现）
手动对纹理setPremultiplyAlpha

### Demo project?（demo 项目）

![image](https://user-images.githubusercontent.com/10802972/79179845-1b098380-7e3b-11ea-8543-13d6e72763d3.png)
![image](https://user-images.githubusercontent.com/10802972/79179881-35dbf800-7e3b-11ea-9875-c70502e20d83.png)
我只单独设置预乘，flipY在这里是undefined，为什么会直接置为true，看起来与这个有关系。

**Comment by finscn** [comment]
原来时bug ?  我之前一直以为 这个是 cc renderTexture的特性呢.
我说每次我用renderTexture时, 都是反的呢...

**Comment by finscn** [comment]
@holycanvas 奇怪, 我更新了代码,  RenderTexture 还是反的.

**Comment by finscn** [comment]
rendertexture上的东西不是反的,  但是 把它做为  某个精灵的spriteFrame的texture时  是反的.

**Comment by lsybblll** [comment]
本来就应该是反的，opengl的纹理坐标左上角为0点，但是咱们更容易理解的是左下角为0点。平常显示没问题是因为做了处理。现在怎么处理的忘了，我好像记得原来的时候是uv.y = 1.0 - uv.y
