### ISSUE TITLE
3D cc.instantiate 方法返回类型为any，没有代码提示，建议修改返回类型为Node

### ISSUE THREAD

**Issue by k8w** [cocos/cocos-engine#6549]
### Creator version?（版本号）
3D v1.0.4

### How to reproduce?（如何重现）
```
let node = instantiate(xxx);
```
node类型为 `any`，后续代码提示都没有了，必须手动 `as Node`
建议instantiate方法类型与2.x一致，返回`Node`而非`any`

**Comment by SantyWang** [comment]
感谢反馈

**Comment by yeshao2069** [comment]
首先，感谢反馈。
验证。目前3D的最新版本Cocos Creator 3D 1.2.0 以及 Cocos Creator 3.0
instantiate实例化返回已经修改为返回Node

参考
https://github.com/cocos-creator/engine/blob/develop/cocos/core/data/instantiate.ts#L68
