### ISSUE TITLE
对 builtin-2d-gray-sprite 的建议

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6556]
从实际应用角度来说,  此shader 不应该 对 node上的 color 进行灰度处理. 比如下面的设置:

![image](https://user-images.githubusercontent.com/288367/79226291-b24cf600-7e90-11ea-913b-5c5f2910f0f1.png)

结果应该是一个 灰度图, 但是整体颜色偏红.

也就是说  应该先对 texture 的原始颜色做 灰度处理,  然后再乘以 v_color.

否则会导致  使用builtin-2d-gray-sprite 时,  node的color失去意义,  同时也缺失了一个重要的特性.

**Comment by jareguo** [comment]
内置的gray在引擎是用在button上的，button通常会用白色图片，然后设置各种节点的颜色作为通用按钮，如果不全部置灰的话，按钮的禁用效果就会有问题。
这里开发者自己拷一份材质一份 effect 出来很容易就能改成自己想要的效果。
