### ISSUE TITLE
对于 骨骼动画播放系统的 建议

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6572]
最近在尝试将项目从 龙骨 迁移到 spine , 遇到了很多问题.

我希望 Cocos Creator 做为引擎 能够提供一层相对通用的 Animation Player 模块.
用来播放动画, 屏蔽底层的具体实现. 从而让开发者无论用龙骨 spine 还是 SpriteStudio ,  对动画播放的代码尽量产生小的影响.

当然 每个动画引擎都有一些自己的特性. 这部分特性(高级特性) 只要提供接口让用户直接调用动画引擎自己的runtime api即可.

**Comment by finscn** [comment]
再简单说一下我的常见API功能需求:

### 常用特性: 
加载/创建/初始化动画信息
播放指定动画 若干次:     1次,  n次,  无限loop
暂停指定动画:   动画暂停, 帧数定格在当前状态.
继续指定动画:  从暂停位置继续播放
停止指定动画:    动画暂停, 帧数定格在第0帧

### 高级特性: 
调整动画的 当前时间
调整动画的 timeScale
反向播放动画
动画多次播放时,  单次播放的开始/结束事件
动画整体的开始/结束事件 (loop循环播放的动画不会主动触发结束事件, 除非用户手动stop) 
动画中用户自定义的帧事件
碰撞事件

### 更高级的特性
换肤(换装)
换骨架
换Mesh数据


----

希望 cocos 官方能封装一个库,  可以实现 常用特性 和 高级特性.

**Comment by finscn** [comment]
还有个问题.
目前 cc里的动画组件的一些属性设置 都是针对 动画本身的.  而不是针对 "当前播放" 的.
希望这里能优化下, 两种都支持.

比如 spine 或者 龙骨里
通过  trackEntry / state 来设置 timeScale时,  只是当前播放会受到影响.  
下次播放时,会产生新的 trackEntry / state对象, 一切又会回复到默认值.

而直接修改 animation 的 timeScale 时,  才是一直有效. 

在实际游戏里, 前者使用更广泛.  而且两者并不能互相替代.  (很麻烦 要做很多额外判断 还有事件回调)

**Comment by OnlyKoei** [comment]
已建立内部 issue，对这个进行讨论，感谢反馈！
这边 issue 先关闭了。
