### ISSUE TITLE
龙骨动画开启 缓存模式时,  不支持获取currentTime, duration, 不支持负数的timeScale (倒着播放)

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6582]
### Creator version?（版本号）
2.3.3

### Affected platform?（受影响的平台）
全平台

----
龙骨动画开启 缓存模式时:
* 不支持获取 currentTime (没有提供相关API)
* 不支持获取 duration (没有提供相关API)
* 不支持负数的timeScale (倒着播放) ,  设置 timeScale<0 时, 有bug.

**Comment by finscn** [comment]
spine动画应该也有类似问题

**Comment by finscn** [comment]
当 使用 Cache 模式时, 本质上, cocos内部就是在播放一个帧动画.

建议这里应该单独用一个 帧动画的类,  
然后  cc里 封装的 ArmatureDisplay 和 Skeleton都聚合这个帧动画类.

这个类的实例里包含动画的基本信息, 比如 总时长, 当前播放时间, 当前帧, timeScale 等等.

**Comment by finscn** [comment]
因为强大的 spine 都不建议倒着播放 (spine官方回复我的) , 所以 对龙骨的倒着播放的需求 我觉得暂时也可以无视了.
就当做 他们都不支持倒着播放好了.

**Comment by zhefengzhang** [comment]
> 因为强大的 spine 都不建议倒着播放 (spine官方回复我的) , 所以 对龙骨的倒着播放的需求 我觉得暂时也可以无视了.
就当做 他们都不支持倒着播放好了.
- 那就关闭此 issues 了。
