### ISSUE TITLE
Creator 3D 1.0.4 缺少判断 OPPO VIVO 华为小游戏的变量（如CC_WECHAT）

### ISSUE THREAD

**Issue by k8w** [cocos/cocos-engine#6597]
如题

版本号：Creator 3D 1.0.4 （查看了源码，1.1也存在该问题）

`@types/global.d.ts` 下只有这些：
```
declare const CC_BUILD: boolean;
declare const CC_TEST: boolean;
declare const CC_EDITOR: boolean;
declare const CC_PREVIEW: boolean;
declare const CC_DEV: boolean;
declare const CC_DEBUG: boolean;
declare const CC_JSB: boolean;
declare const CC_WECHAT: boolean;
declare const CC_ALIPAY: boolean;
declare const CC_XIAOMI: boolean;
declare const CC_BAIDU: boolean;
declare const CC_COCOSPLAY: boolean;
declare const CC_MINIGAME: boolean;
declare const CC_RUNTIME_BASED: boolean;
declare const CC_SUPPORT_JIT: boolean;
```

缺少 `CC_OPPO` `CC_VIVO` `CC_HUAWEI`

**Comment by shrinktofit** [comment]
感谢！ 1.1.1 将修复

**Comment by shrinktofit** [comment]
@pandamicro  请给该 issue 加一下 label： 3d、Bug 然后指给我

**Comment by yeshao2069** [comment]
这个在目前最新的  3D 1.2.0已经补充  HUAWEI、 OPPO、 VIVO等变量了

**Comment by yeshao2069** [comment]
![image](https://user-images.githubusercontent.com/14273437/116525263-eadc3800-a90a-11eb-9653-b0b156ca9e17.png)
https://github.com/cocos-creator/engine/blob/v3.1-release/@types/consts.d.ts
从3.0开始，cocos creator 2.x和cocos creator 3D合并成全新的版本。
目前最新版本 3.0 版本，关于小游戏的定义已经从 global.d.ts 移到 consts.d.ts，且已经补充了  HUAWEI、OPPO、VIVO等小游戏判断的变量。

另外cocos creator 3D 1.2.0也已经已经补充了  HUAWEI、OPPO、VIVO等小游戏判断的变量。
![image](https://user-images.githubusercontent.com/14273437/116525925-9d13ff80-a90b-11eb-86a6-1660a8d27de9.png)
