### ISSUE TITLE
[需求] 希望能增强下effect shader的内置 uniforms 参数

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6598]
目前迫切希望增加一个功能:

在传入一个 sample2D 贴图时,
也能够自动把 贴图的尺寸(单位: 像素)传入进去.

可以定一条规则,  比如当shader里定义了 
```
sample2D abcTexture
```
则 自动将`abcTextureSize` 做为贴图尺寸传入.
当然前提是 用户在shader里进行了如下定义: 
```
vec2 abcTextureSize
```

**Comment by YunHsiao** [comment]
这个引擎里不好做同步，而且大部分情况是不需要 size 信息的，在设置贴图时多调一句 setProperty 就好了~

**Comment by finscn** [comment]
我觉得关于默认参数这个地方 可以借鉴下  shaderToy 网站的 shader系统.   它们提供的内置参数很实用.  而cc提供那些 很多都没啥用.

**Comment by YunHsiao** [comment]
如果你是说 cc-global 里面的数据，这些是 pipeline 层面的全局变量，每帧只需要更新上传一次，所以能传就传了；
另外最好能提供下具体的使用例子，在什么情况下 texture size 需要被大量使用呢？我可以试着帮你看看有没有更好的办法

**Comment by finscn** [comment]
@YunHsiao , 这个我和 @jareguo @sunnylanwanjun 交流过.
基本上需要修正宽高比的shader  都需要这个参数.
比如 描边,  内发光,  外发光,  投影,  rgb split ....  

我参与了大量pixi 的 filter的开发,
基本上 https://pixijs.io/pixi-filters/tools/demo/ 这个页面里的这些filter特效 有一多半需要.

**Comment by YunHsiao** [comment]
哦这些都是 2D 需求啊，@2youyou2 可以看下在 2D 里是不是默认加下更好

**Comment by jareguo** [comment]
@YunHsiao 其实这个需求在 3D 也是需要的，比如后处理的时候。所有涉及到宽高比的操作，比如描边、模糊，都需要使用宽高比对采样的 UV 进行修正。何况之后 2D/3D 得合并啊。

**Comment by YunHsiao** [comment]
后处理在 pipeline 里有独立的步骤，可以在 render stage 里单独赋值，这个不适合放在材质层面直接自动做

**Comment by jareguo** [comment]
有办法让开发者能获取到吗？在不调用 API 的情况下，只把 shader、material 拖到编辑器就能看到正确的效果？否则之后 shader/material 要共享的话会很麻烦，等于还要把脚本也共享出去，挂到节点上……

**Comment by YunHsiao** [comment]
一定不想加这个脚本的话，可以从 worldMatrix 里提取这个信息

**Comment by jareguo** [comment]
要怎么提取捏？

**Comment by YunHsiao** [comment]
类似这样：
```glsl
vec2 scale = vec2(length(worldMatrix[0].xyz), length(worldMatrix[1].xyz));
```

前提是 vb 本身得是正方形，3D 的面片都符合的

**Comment by finscn** [comment]
@YunHsiao  这个 scale是什么? 还是没懂.  从这个scale如何得出宽高比?

另外 在片元着色器里调用 两次length() , 其实挺耗性能的吧

为什么不能借鉴下 unity pixi一类的引擎,  把贴图大小传进去呢?

**Comment by YunHsiao** [comment]
嗯是会费一些，算出来是世界变换的缩放值，对 3D 面片就是它的长宽比了。我没有细看 unity 这块的实现，他给的接口是怎样的，你可以描述一下或是链一下文档吗

**Comment by finscn** [comment]
> 嗯是会费一些，我没有细看 unity 这块的实现，他给的接口是怎样的，你可以描述一下或是链一下文档嘛

是 ~~@sunnylanwanjun~~  @holycanvas 告诉我的 哈哈哈 我也不知道.

**Comment by jareguo** [comment]
See https://docs.unity3d.com/Manual/SL-PropertiesInPrograms.html

> ![image](https://user-images.githubusercontent.com/1503156/82635177-3e8dce00-9c32-11ea-852c-891c122295cb.png)

      sampler2D _MainTex;    
      float4 _MainTex_ST;
      float4 _MainTex_TexelSize;

**Comment by sunnylanwanjun** [comment]
>  是 @sunnylanwanjun 告诉我的 哈哈哈 我也不知道.

@finscn  兄弟，不要 @ 我了， 你可能是想@ 2youyou2 吧，搞错人了。
打开邮箱一堆消息，还以为出什么世纪大bug了。
