### ISSUE TITLE
[需求&建议] 用户可以指定 碰撞系统的回调脚本 所在节点.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6606]
现在的cc的设计是:
```
当碰撞系统检测到有碰撞产生时，将会以回调的方式通知使用者
```

但是在实际项目里,  处理碰撞的回调脚本可能需要统一管理, 而不是 "谁挂接了 碰撞组件, 就要谁来处理"

可以参考下 Button的设计.  Button里 click的回调 用户就是可以自己指定的. 而不是 哪个node挂接了Button组件 就只能由这个node自己来处理click.

当然 碰撞系统也不用像 Button那么灵活 (可以指定具体的回调函数).
我觉得可以设置 回调的响应节点 就可以. 不设置 就是用当前挂接组件的 节点,  否则就用设置的节点.

**Comment by finscn** [comment]
我具个例子来说明下我的应用场景(只是举例, 虚构的例子): 

游戏里有一个风车,  风车的扇叶是有碰撞的, 添加了 碰撞组件.

节点结构如下:

```
 风车Node  (组件:  风车Logic )
     |___  风车身体Node  (组件:  Sprite )
     |___  若干个风车扇叶Node ( 组件:  Sprite  ,  cc.Collider )
```
其中 `风车Logic ` 是处理整个风车逻辑的组件.

现在我有这个需求:  风车扇叶被撞了, 那么风车停止工作.
我想把这个需求在   `风车Logic ` 里实现.

虽然理论上 我也可以写个单独的组件,  挂街到 风车扇叶上, 但是
* 首先我并不想只为这一个小的功能(可能只有两行代码) , 单独写一个组件.
* 其次 把风车相关的逻辑  整合到一个组件里, 更清晰明了,  反之分散到很多琐碎的小文件里并不便于管理和维护
* 假如风车有很多,  那么最终性能应该也会受到一点点影响吧? (每个风车要多出很多个组件)

---
所以我希望 Collider 组件能够让用户 指定一个包含了 回调方法的节点 . 如果不指定,那么就用碰撞组件所在节点.

**Comment by jareguo** [comment]
从统一性的角度，我不太建议除了 UI 组件以外也使用完全自由的事件派发机制。
因为这些组件的用途通常明确，改动没有 UI 那么频繁。
或许支持类似刚体那样的碰撞机制会更好？刚体用来处理逻辑，碰撞体用来描述外观。

**Comment by finscn** [comment]
@jareguo  我觉得你的这个建议好像不能很好的解决我上面的风车的例子.
因为 风车的扇叶和 风车整体的运动 不是绑定的.  (扇叶在转, 风车不动)
如果用   风车做为刚体,  包含若干个碰撞体的做法的话.  比较难单独更新碰撞体的坐标角度等.

你的这个建议比较适合我举的那个 "一辆车是个凹多边形, 为了性能, 拆分成若干个矩形碰撞体" 的例子.

**Comment by jareguo** [comment]
> * 假如风车有很多,  那么最终性能应该也会受到一点点影响吧? (每个风车要多出很多个组件)

这个不用担心，JS 还不至于性能差到这个地步。

> * 首先我并不想只为这一个小的功能(可能只有两行代码) , 单独写一个组件.

我们目前也只收到一次这类反馈，之后如果有更多人有同类诉求我们会再考虑添加的。目前我们也不想有一个需求就加一点代码，引擎会越来越大。

> * 把风车相关的逻辑  整合到一个组件里, 更清晰明了,  反之分散到很多琐碎的小文件里并不便于管理和维护

你也可以自己实现一个通用的转发组件。这样你就可以把风车的逻辑继续整合到一个组件。
