### ISSUE TITLE
[需求] Sprite的 tiled(平铺) 模式支持设置 tile的缩放和位置偏移量.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6617]
标题说的有点抽象. 拿pixi举例子吧: 

就是类似这个demo的效果:

https://pixijs.io/examples/#/sprite/tiling-sprite.js

**Comment by finscn** [comment]
@holycanvas 这个如何实现呢.

**Comment by yeshao2069** [comment]
这个需求和 https://github.com/cocos-creator/engine/issues/6951 是相同issue.
目前这个issue 需求已经同步给引擎组了，感谢反馈。
