### ISSUE TITLE
[建议] cc.Label组件的 string setter方法 输入参数改为 `string | number`

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6623]
### Creator version?（版本号）
2.3.3

现在好像只有 `string`  , 导致下面这种常用方法 在 vs code里总是提示错误

![image](https://user-images.githubusercontent.com/288367/80340579-7869ef80-8893-11ea-9981-a9f66ef5c57c.png)

**Comment by jareguo** [comment]
这里需要开发者自己 as string 才行。因为如果我们改了类型，获取的时候就会报错。比如
label.string.startsWith(...)
