### ISSUE TITLE
2.2.2 两个节点，一个在上面一个在下面， 上面那个节点once事件之后，下面那个节点once事件不响应

### ISSUE THREAD

**Issue by baiguo** [cocos/cocos-engine#6628]
### Creator version?（版本号）
2.2.2

### Affected platform?（受影响的平台）

Web / iOS / Android / Simulator 

### How to reproduce?（如何重现）
两个节点，一个在上面一个在下面， 上面那个节点once事件之后，下面那个节点once事件不响应

### JavaScript output or error produced?（报错信息和调用栈）

必先

**Comment by knoxHuang** [comment]
可以更新新版本看看是否会重现

**Comment by baiguo** [comment]
> 可以更新新版本看看是否会重现

我给陈大大反馈过， 临时解决了一下。 新版本，有空我试试

**Comment by yeshao2069** [comment]
你好，在2.x系列最新的版本，2.4.5上测试，无法复现这个问题了，推荐升级版本试试。
[NewProject_7.zip](https://github.com/cocos-creator/engine/files/6686554/NewProject_7.zip)
