### ISSUE TITLE
自定义了一个父类，然后两个场景下的分别继承该父类，编辑器内展示错误

### ISSUE THREAD

**Issue by sansui-orz** [cocos/cocos-engine#6633]
### How to reproduce?（如何重现）
先定义一个父类 Parent, 假设父类内容如下:
`
class Parent extends cc.Component {
  @property(cc.Node)
  public parentNode: cc.Node = null;
}
`
然后定义子类1 Children1:
`
class Children1 extends Parent {
  @property(cc.Node)
  public childNode1: cc.Node = null;
}
`
然后定义子类2 Children2:
`
class Children2 extends Parent {
  @property(cc.Node)
  public childNode2: cc.Node = null;
}
`

然后在cocos creator中，children1节点中需要挂节点的参数有两个，分别是 parentNode, childNode1
但是children2节点需要挂节点的参数有三个，分别是parentNode, childNode1, childNode2

也就是说它会将之前继承的属性也算进去，在运行的项目中则是正常的
这个不会影响项目运行，但是每次控制台都会输出警告有点烦

**Comment by 9romise** [comment]
在 3.8.3 遇到了同样问题，请问当时有解决方案吗？
