### ISSUE TITLE
允许编辑器添加多个 SpriteFrame

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6636]
### Creator version?（版本号）
2.3.3

### Affected platform?（受影响的平台）
全平台

### How to reproduce?（如何重现）

Sprite组件那边 size mode里的Trimed 和 下面选择框的trim选不选都一点效果都没有。
完全依赖于图像资源下的spriteFrame设置。
SpriteFrame设置一旦trim , 那么sprite里的图就总是被trim的.

**Comment by finscn** [comment]
刚才和 cc的研发 同学沟通了下,  这个不是bug, 而是 cc有意为之的.

如果是这样, 那么 我有两个建议(两者取其一即可): 

1)  支持一个 图片资源 可以定义多个不同的 spriteFrame .
2) sprite上可以设置 属于该sprite专属的 spriteFrame trim信息,  使其可以不依赖于 图像资源自己的 spriteFrame设置.

**Comment by jareguo** [comment]
1. 将来我们可以支持
2. 似乎跟工作流程有点违背，毕竟要如何 trim 应该是在资源生产过程中美术就可以决定的，为什么要放到场景里面再决定呢？

**Comment by yeshao2069** [comment]
感谢反馈，该需求已经提交到引擎组，谢谢。

**Comment by yeshao2069** [comment]
同步最新反馈
目前计划在3.5版本实现这个需求。
暂定方案：
新建一个子资源，允许关联一个 image 资源。
