### ISSUE TITLE
[需求] 图像资源下的 spriteFrame编辑器提供一个"不进行trim"的选项

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6637]
### Creator version?（版本号）
2.3.3

现在的版本 只有 auto和custom选项.
虽然custom选项也能间接的实现  不trim的效果, 但是非常麻烦.

顺便建议这个编辑spriteFrame的页面也显示下图片的原始大小. 否则每次还要再点击下图片 查看大小.

![image](https://user-images.githubusercontent.com/288367/80607326-f383ff00-8a67-11ea-88ec-117b2c69ea06.png)

现在下面只显示 trim width/height, 没有图像原始大小.

**Comment by finscn** [comment]
另外 , 下图重 蓝色的文本 是不是改成 "SpriteFrame" 更合适呢? 

![image](https://user-images.githubusercontent.com/288367/80620559-be33dd00-8a78-11ea-9c01-98756cd885cc.png)

**Comment by knoxHuang** [comment]
多加了一个 none 的选项，该下面是效果图

效果图：

none： 

![image](https://user-images.githubusercontent.com/7564028/81132437-ffe4ec00-8f80-11ea-87b4-bd18bb16d6b5.png)

custom

![image](https://user-images.githubusercontent.com/7564028/81132346-aa104400-8f80-11ea-91a3-82ae96a7df1a.png)

auto

![image](https://user-images.githubusercontent.com/7564028/81132359-b8f6f680-8f80-11ea-8177-8278297f36a6.png)
