### ISSUE TITLE
[文档增强建议] 关于 Node大小 与 其下 SpriteFrame大小的关系问题

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6639]
我在实际编码中 遇到了这样一个需求:

要对一个 sprite node 进行 剪裁, 只保留它的一部分.
于是通过 设置 spriteFrame 的rect的方式,  并重新设置node大小的方式来实现.

但是发行这段代码运行有错:

![image](https://user-images.githubusercontent.com/288367/80786153-4cad7900-8bb5-11ea-9cb8-be6b2247a7b2.png)

运行后, sprite被剪裁了, 但是整体被缩小了 (在可视区域变小的基础上, 再进一步的缩小了).

后来发现  必需要在前面加一句
```
frame.setOriginalSize((rect as cc.Size));  
```
但是理论上 , 不应该需要这一句, 意义不对. 
我只是从原图中切割出新的一个区域, 而并没有改变原始大小. 
不应该要求我必需重新修改OriginalSize 吧? 

举个例子: 
我的 texture大小时 512, 512, 
最初, 我的spriteFrame ,  是从 这个 512*512的图里, 切出了一块: 
```
{
x: 10,
y: 20,
width:  100,
height : 200
}
```
此时:    spriteFrame 的rect就是上面的数值,  而 originalSize 是 512 * 512.
node的 contentSize 大小是 100 * 200.
以上都是ok的, 正常的.

现在 我要做的只是 把重新剪裁, 比如剪裁成: 
```
{
x: 11,
y: 22,
width:  55,
height : 99
}
```
这时, 我就必需要把  originalSize 修改成 是 55 * 99,  才行正常.

这显然是说不通的吧.

这一点不知道是 设计如此  还是bug.
如果不是bug, 而且难以通过重构来实现"无需修改OriginalSize"

建议文档里说明一下.

**Comment by finscn** [comment]
这一点不知道是 设计带来的副作用, 还是bug.
如果不是bug,  而且难以通过重构来让这段逻辑变成顺序无关的话,
建议文档里说明一下.

**Comment by finscn** [comment]
另外, 如果我是  新创建了一个 sprite,  直接设置spriteFrame rect为 
{
x: 11,
y: 22,
width:  55,
height : 99
}

也是ok的.

也就是说, 只有对已经存在 的 sprite进行 重新剪裁时, 才需要重新设置originalSize . 
我越发觉得 这是一个bug了.

**Comment by finscn** [comment]
我发现问题了.
和 https://github.com/cocos-creator/engine/issues/6637  提到的一些问题有着千丝万缕的联系.

与 trim 以及 图像资源的spriteFrame里的设置有关.

如果我不自己弄一些特殊需求, 而是老老实实的按照 cc的默认的来,  就没问题.

**Comment by jareguo** [comment]
能介绍一下你发现的问题是什么？
