### ISSUE TITLE
[需求] 希望`renderer` 变为cc.Director实例的属性, 而不要用作用域保护起来.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6640]
因为一些特殊需求, 需要重写 cc.Director的 mainLoop 方法.

本来  `cc.Director.prototype.mainLoop = 新的mainLoop`  就可以了
但是因为 mainLoop 调用了一个受到作用域限制的  `renderer` 导致难以实现简单的重写.

希望能在 cc.Director 初始化时, 加一个 
```
this._renderer = renderer 
```

谢谢.

**Comment by SantyWang** [comment]
要不直接用cc.renderer呗

**Comment by finscn** [comment]
@holycanvas 两者是一样的 ?  那就没问题了

**Comment by SantyWang** [comment]
一样的
