### ISSUE TITLE
[BUG: v1.1 RC] Button的Scale，只要xyz任一为0，即可全屏触发点击

### ISSUE THREAD

**Issue by k8w** [cocos/cocos-engine#6642]
### Creator version?（版本号）
1.1 RC

### Affected platform?（受影响的平台）

All

### How to reproduce?（如何重现）
1. 新建一个Node，挂载ButtonComponent
2. 将Node的Scale设为 `(0,0,1)` 或 `(1,0,0)` 等（x/y/z任一为0即可）
3. 给Button的Click事件挂一个Handler（比如 `console.log('XXX')`）
4. 运行程序，此时Button不可见（因为scale为0），但全屏皆可触发点击

**Comment by OnlyKoei** [comment]
如果方便可以在最新版进行验证修复是否完成，如果后续还有问题，可以联系我们。
