### ISSUE TITLE
box2d的周期内修改静态物体的位置问题

### ISSUE THREAD

**Issue by zszen** [cocos/cocos-engine#6643]
### Creator version?（版本号）
2.3.2

### How to reproduce?（如何重现）
.移动静态物体位置
.崩溃
.提示在物理计算锁定时出错
```
b2Body.prototype.SetTransformXY = function(x, y, angle) {
          if (this.m_world.IsLocked()) throw new Error();
```

### 问题
1. 如何避免这样的错误
2. 如何获得m_world的 lock 状态, 貌似并没有可读取的接口参数
3. 看了源码的物理引擎的update函数内, 有个在预处理时发送了个“before-step"事件, 但是没有“after-step”事件, 也不能通过这个来判断是否可以对物体位置进行操纵.

我知道直接操作box2d内物体位置是尽量避免, 但现在有这个需求, 而且在文档中有注释static对象是可以移动的.

**Comment by dubox** [comment]
这个问题解决了吗？

**Comment by xianyinchen** [comment]
你好，如果你遇到 m_world.IsLocked() 判断导致的抛出异常，说明你是在物理引擎监听事件回调里做了更新物理节点坐标的操作，这个是不允许的，你可以加个定时函数异步去更新物理节点即可。

**Comment by yeshao2069** [comment]
感谢反馈。
建议  在物理引擎监听事件回调( 如做了物理碰撞的  onBeginContact )， 可以在回调中记录状态然后去更新物理节点。  或者 加一个定时函数 异步去更新物理节点(延迟1帧 以上时间)。   
https://docs.cocos.com/creator/manual/zh/physics/physics/contact-callback.html?h=%E7%A2%B0%E6%92%9E
