### ISSUE TITLE
Creator 3D 编辑器问题反馈

### ISSUE THREAD

**Issue by yukunxie** [cocos/cocos-engine#6648]
![image](https://user-images.githubusercontent.com/12712676/81148807-8a444480-8faf-11ea-90a4-29fea70e9360.png)

由于项目需要，需要对引擎的部分代码进行定制，所以会指定引擎的编译路径，但是可能是有编译错误或其它什么问题，启动编译器会一些卡在loading resource阶段，能否在编译失败的情况下给出更详细的信息，而不是在这一直卡着？

**Comment by yeshao2069** [comment]
感谢反馈。
关于在编译失败的情况下给出更详细的信息，已经提交需求。
目前编译失败或者自定义引擎为空的情况下，会提示后并使用内置引擎。

临时方案： 如果你遇到这种卡死的情况下，可以尝试删除自定义引擎，也可以升级目前3.1.2版本试试。
