### ISSUE TITLE
Scrollview旋转触摸没有转换

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#6654]
版本:2.2.1  ScrollView 添加节点   设置Horzontal(横向)
以上没有问题

如果将ScrollView旋转90度,或者ScrollView的上层父亲旋转90度,
则ScrollView不能正常触摸,

**Comment by knoxHuang** [comment]
2.3.0 版本已经修复了，可以同步上面的 pr 或者更新到最新版本

**Comment by 284263380** [comment]
粒子也有问题,native和h5表现不一样,对于旋转的情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Knox"<notifications@github.com&gt;; 
发送时间: 2020年5月18日(星期一) 下午3:15
收件人: "cocos-creator/engine"<engine@noreply.github.com&gt;; 
抄送: "司炎昭"<284263380@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cocos-creator/engine] Scrollview旋转触摸没有转换 (#6654)





 
2.3.0 版本已经修复了，可以同步上面的 pr 或者更新到最新版本
