### ISSUE TITLE
[Bug] 编辑器Sprite的blend设置有bug

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6659]
### Creator version?（版本号）
2.3.3

### How to reproduce?（如何重现）

将 Sprite组件的Blend 的  src blend factor 设置成 任意模式后, 
再设置回  SRC_ALPHA 时 无效, 仍然保持之前的状态.

**Comment by caryliu1999** [comment]
这个 PR 里已经修复这个问题了：https://github.com/cocos-creator/engine/pull/6451

**Comment by finscn** [comment]
ParticleSystem 也有类似问题,  这个PR 是不是也修复了?
