### ISSUE TITLE
建议开放 typescript 版本供选择

### ISSUE THREAD

**Issue by fkworld** [cocos/cocos-engine#6663]
大量新语法糖无法使用。

另外，应当在文档中写明所用的 typescript 版本。

**Comment by m2nlight** [comment]
最好能支持 node_modules 中安装的 typescript 版本选择，就跟 VSCode 一样，它支持在 VSCode 包含的版本、Workspace 的版本和 node_moduels 中的版本进行选择。

**Comment by yeshao2069** [comment]
支持的typescript版本，文档是有说明的，比如3.1版本的，可参考https://docs.cocos.com/creator/3.1/manual/zh/scripting/language-support.html?h=%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81

引擎不支持开放typescript版本选择，请知悉，谢谢。
