### ISSUE TITLE
没有导出 MaskType , 导致无法在脚本里更改 mask 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6666]
### Creator version?（版本号）
2.3.3

如题

**Comment by finscn** [comment]
原来导出的叫 cc.Mask.Type....

**Comment by dcxs** [comment]
@finscn 你好，这边2.3.3与2.3.2构建后，cc.Mask也为undefined，请问如何解决的？

**Comment by finscn** [comment]
@dcxs  我用的2.3.3 , cc.Mask.Type 是可以用的啊
