### ISSUE TITLE
[需求] 基于`RenderTexture` 的 SpriteFrame 缺少一个快捷的`刷新texture`机制

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6667]
### Creator version?（版本号）
2.3.3

### How to reproduce?（如何重现）

用 RenderTexture 创建了一个 SpriteFrame.

RenderTexture会被动态更新 (只是更新内容, 大小, uv等等 信息都不变) .
 现在每次更新RenderTexture , 必需重 setTexture, 而且还要重新设置 rect , originalSize , offset
否则 spriteFrame不会被更新,   不重新设置originalSize , offset则会报null异常.

另外 我看了一下代码, 以上过程也会产生很多无效的重复计算.

希望能够提供一个 api , 来快捷的刷新 texture.

另外, 我看了下代码, 现在有一个  _refreshTexture 方法,

直接调用 `spriteFrame._refreshTexture(texture);`  可以省去传`rect , originalSize , offset` 的麻烦.
但是 _refreshTexture 方法内部仍然存在重新计算UV 的问题(事实上我并不需要)

综上所诉, 希望能SpriteFrame提供一个 快捷的 刷新texture的机制.

**Comment by finscn** [comment]
如果实在怕麻烦, 那就把  `_refreshTexture` 变成public的 `refreshTexture` 吧.

**Comment by jareguo** [comment]
考虑增加一个 replaceTexture 或者 refreshTexture

**Comment by finscn** [comment]
2.4.0里会提供吗? 
或者把 refreshTexture 开放出来?
为了安全起见,  _ refreshTexture 可以继续保留

refreshTexture = _ refreshTexture  即可

**Comment by pandamicro** [comment]
> 考虑增加一个 replaceTexture 或者 refreshTexture

Sorry, 我拒绝了之前的 PR，这个处理方法并不合理，更新 RT 不是用户的责任，应该在 `_refreshTexture` 中增加对 RT 的特殊处理，在 RT 更新时做响应的更新（建议增加 RT 的内容更新事件）

**Comment by yeshao2069** [comment]
关于这个问题的需求，目前已经提交内部反馈，该issue暂时先关闭，后续有修复，我会继续在此同步。
