### ISSUE TITLE
[需求] 开放 "active-in-hierarchy-changed" 事件

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6668]
### Creator version?（版本号）
2.3.3

我看源码, 目前系统中有一个 `active-in-hierarchy-changed` 事件, 当node的active发生变化时触发.
但是目前这个事件 并没有在 Node.EventType  里定义.

我非常需要这样的一个事件来做一些事情. 希望能暴露这个事件.

**Comment by finscn** [comment]
我的实际需求是: 
我写了一个组件 ,  它除了 关注自己所在的节点,   还会处理另外一些节点.
它会关注 其他节点的  active的变化.
所以需要这个事件.

而不能简单的通过 这个组件宿主node 和 组件自身的enable/disable 来实现我的需求.

**Comment by finscn** [comment]
从设计角度来说,    一个组件 关注很多个node,   以及一个node 被很多组件关注.  都是合理的设计.

既然如此, 那么 组件可以监听 node特别重要的active状态 ,  就是合理的需求.

虽然 一个node的active 会触发它下属的 组件的onEnable onDisable回调,  但是 有一类组件, 它本身相当于 manager/controller ,  它会关注很多个node,  但是它又不隶属于这些被它关注的node,  而是凌驾于他们之上.


它可能会控制 关注的node的active, 也可能需要监听node的active.

这种情况下,  监听 active 事件就很有必要了

总结下

1)  node.active 是 node非常非常重要的一个属性/状态
2) 一个node 可以被很多组件关注,  一个组件也可以关注很多个node
3) 既然关注了一个node,  就不可能 完全不在乎 node的active属性,  总会有一些功能需要监听node的active变化

**Comment by yeshao2069** [comment]
感谢反馈，这个需求已经同步给引擎组。

**Comment by yeshao2069** [comment]
第一阶段，可以先提供对外的事件名称
第二阶段，可以考虑提供一个子系统做每一帧 Transform 信息变化的收集

**Comment by yeshao2069** [comment]
https://github.com/cocos-creator/engine/pull/9369/files   已经同步到3.4.0版本了

**Comment by finscn** [comment]
> https://github.com/cocos-creator/engine/pull/9369/files 已经同步到3.4.0版本了

2.4.x 系列能否同步下呢?  先提供对外的事件名称.
