### ISSUE TITLE
[需求] cc.Color 提供 toRGBAValue 方法.  也就是包含`Alpha通道`的颜色数值.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6676]
目前的一个应用场景: 

我写了一个组件,  需要设置 material 的blendColor
blendColor  是一个 32位的, 含alpha通道的 rgba数值.
我给组件的该属性 类型选择了 cc.Color
但是发现没有一个快捷的方法 从 cc.Color 获得 32位rgba数值.

rgba数值在研发时应用还是比较广的, 比如shader里大量用到.

希望引擎能提供.

**Comment by whg333** [comment]
cc.Color不是能直接获取4个通道rgba的数值吗？直接封装成自己的toRGBAValue方法

**Comment by finscn** [comment]
自己封装当然是可以的. 但是我觉得这个是基础常用功能, 最好引擎提供

**Comment by yeshao2069** [comment]
感谢反馈，该需求已经提交给引擎组，谢谢。
