### ISSUE TITLE
[BUG] All meshes disappear after camera.z is too large on Android

### ISSUE THREAD

**Issue by MarkusTieche** [cocos/cocos-engine#6678]
I am moving the camera in negative z direction, once a certain point is reached all 3d meshes disappear :(. Only happens on Android devices! This is a huge problem for endless levels / runner game.
Please let me know if I am doing something wrong, thank you :).

https://github.com/inkfood/CC_AndroidDepthTest_Bug
(Recorded on Android device)
![depthProblem Android 2020-05-12 07_52_43](https://user-images.githubusercontent.com/8083536/81643682-5d1bea00-9426-11ea-92ea-a6e40ad4dc51.gif)

**Comment by 2youyou2** [comment]
What version did you use?
Can you check if engine use a mediump matrix in  `engine/cocos2d/renderer/build/chunks/cc-global.inc`

**Comment by MarkusTieche** [comment]
Thank you for the fast response :).
Tested in CC 2.3.3 & 2.3.2, both have the same cc-global.inc same as
https://github.com/cocos-creator/engine/blob/master/cocos2d/renderer/build/chunks/cc-global.inc

**Comment by 2youyou2** [comment]
Not sure, what is your android device and did you test other android device?

**Comment by MarkusTieche** [comment]
Tested only on Samsung Galaxy A5 with Android 8.0, which should be support by CC.
The project was built with Android Studio without any changes to the project files.  
My first thought was that there might be a something off in the depth buffer.

**Comment by MarkusTieche** [comment]
The bug seems only to appear if the project is built with CocosCreator 2.3.2, if built with 2.3.3 everything seems to work fine. 

I did still experience some flickering on Android with the shaders I built/extended with 2.3.2, I did one change in the vertex shader portion, instead of using ```In.position``` directly I used a variable  
```vec4 position = In.position;``` which works perfectly fine now. :)
