### ISSUE TITLE
TMX render: inconsistent pixel size

### ISSUE THREAD

**Issue by dtori** [cocos/cocos-engine#6699]
Hi guys, 
Cocos Creator is amazing, you guys are doing an impeccable job, I am so grateful.

I am having problems with Tilesets and pixel art, below I explain the problem. I think it is a bug since I have tried everything and I cannot get it to work properly.

### Creator version? 
2.3.2 and 2.3.3

### Affected platform? 
Mac Editor (catalina)

### How to reproduce? 
I have created a map, which in “tiled” looks like it should, but when importing the asset in CC it renders incorrectly. The pixels are inconsistents:
![70c652438eb3359ce5a66cb84a1b4192d0fbad7c_2_603x500](https://user-images.githubusercontent.com/19737932/82087039-bbb2c380-96c5-11ea-860a-c615945a9cf5.png)

It should look like this:
![e6cb88cc37ca3fc9fb487ded22837ed7ec990b36_2_602x500](https://user-images.githubusercontent.com/19737932/82087416-6cb95e00-96c6-11ea-82ae-44128a4ef9c0.png)

Forum post: https://discuss.cocos2d-x.org/t/tmx-asset-render-problems-inconsistent-pixel-width/50317

### JavaScript output or error produced?
No errors

### Demo project?
[TMXRenderBug.zip](https://github.com/cocos-creator/engine/files/4636640/TMXRenderBug.zip)

**Comment by zhefengzhang** [comment]
Thanks for the feedback, it has been submitted to the engine team for processing.
