### ISSUE TITLE
自动图集纹理压缩配置体验不好

### ISSUE THREAD

**Issue by shangdibaozi** [cocos/cocos-engine#6704]
1. 安卓平台选择etc1 rgba压缩格式，H5平台选择了png。构建H5平台的时候正常，但是如果构建安卓平台则不会生成pkm格式的压缩文件。

2. 如果只对安卓平台进行了纹理压缩格式的设置，在构建H5平台的时候也会生成pkm格式文件。能不能在构建的时候只生成配置了的平台格式文件？

2.1.3和2.3.3都有这种情况。

**Comment by knoxHuang** [comment]
能否录制一下操作行为？我这边测试是正常的

**Comment by shangdibaozi** [comment]
![image](https://user-images.githubusercontent.com/6499838/82191754-96bc8b80-9925-11ea-8553-b1eb4a66f315.png)
对自动图集，选择etc1 rgba。
然后旋转安卓平台构建会生成pkm文件。

如果再对图集选择h5平台的Png
![image](https://user-images.githubusercontent.com/6499838/82191891-c53a6680-9925-11ea-85b1-5a9931614bcc.png)
再构建安卓项目，就不会生成pkm文件了。

**Comment by shangdibaozi** [comment]
我再仔细整理下流程。

**Comment by shangdibaozi** [comment]
2.3.3

测试3个平台：Android、微信小游戏、H5
测试1张图集
![image](https://user-images.githubusercontent.com/6499838/82198526-04b98080-992f-11ea-8398-94b6a2a360e2.png)

![image](https://user-images.githubusercontent.com/6499838/82197088-1c900500-992d-11ea-9456-b6c32771590a.png)
![image](https://user-images.githubusercontent.com/6499838/82197096-1ef25f00-992d-11ea-8592-17d8cde07580.png)
![image](https://user-images.githubusercontent.com/6499838/82197104-20bc2280-992d-11ea-812d-95dff5f7bc2e.png)

分别构建Android、微信小游戏和Web Mobile
![image](https://user-images.githubusercontent.com/6499838/82197327-755f9d80-992d-11ea-9780-049016380ae0.png)
搜索pkm文件
![image](https://user-images.githubusercontent.com/6499838/82197351-7bee1500-992d-11ea-9b08-1e2632254b67.png)

对Android平台选择etc1 rgb separate a
![image](https://user-images.githubusercontent.com/6499838/82197649-d2f3ea00-992d-11ea-9ede-39fcd55f90c1.png)
然后再次构建Android、微信小游戏和Web Mobile
搜索pkm文件
![image](https://user-images.githubusercontent.com/6499838/82197756-f323a900-992d-11ea-8ce5-389dfc74d1d8.png)

看到，**微信和H5平台也生成了pkm文件。**


对该自动图集再次选择H5平台png压缩
![image](https://user-images.githubusercontent.com/6499838/82198054-57466d00-992e-11ea-8055-c1ee1c88a46c.png)
然后再次构建Android、微信小游戏和Web Mobile
搜索pkm文件
![image](https://user-images.githubusercontent.com/6499838/82198089-63cac580-992e-11ea-8237-1a361e3ce099.png)

微信和H5平台还是生成了pkm文件。

**Comment by shangdibaozi** [comment]
如果对自动图集选择了Android平台的etc1配置，但是我先构建Web Mobile平台，然后再构建Android平台，Android平台下也不会生成pkm。如果我先构建的是Android平台，再构建Web Mobile平台，在Web Mobile平台也会生成pkm。

**Comment by yeshao2069** [comment]
使用2.4.6测试， 指定android 为ETC1 RGB ， Web 和 MiniGame 为 PNG ， 构建安卓和web-mobile，没问题。
安卓生成pkm，web不会生成pkm。(不管是先构建安卓还是先构建web)

**Comment by yeshao2069** [comment]
我试试2.3.3 看看

**Comment by yeshao2069** [comment]
2.3.3 测试，如果 指定android 为ETC1 RGB ， Web 和 微信小游戏 为 PNG， 那么打包安卓或者web，pkm不生成。
如果 指定android 为ETC1 RGB， 不指定  Web 和 微信小游戏，  那么打包安卓或者web，pkm不生成。

感谢你的反馈，你可以升级 creator 2.4.6试试。


2.3.3测试例
[test233.zip](https://github.com/cocos-creator/engine/files/6898967/test233.zip)
2.4.6测试例
[test246.zip](https://github.com/cocos-creator/engine/files/6898978/test246.zip)
