### ISSUE TITLE
Color.fromHex负数问题

### ISSUE THREAD

**Issue by weilichuang** [cocos/cocos-engine#6706]
Color.fromHex(0xff123456) 结果r为负数，操作符应该使用>>>

### Creator version?（版本号）
master

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/113391677-7a530180-93c6-11eb-8e98-93bf68015953.png)
![image](https://user-images.githubusercontent.com/40415168/113391702-8212a600-93c6-11eb-907c-2d61d56b599b.png)
测试版本：2.2.2，2.3.3，2.4.3，2.4.4，3.0.0；
结果如上图，并未出现负数；
能否告知版本？具体的复现步骤？

**Comment by yeshao2069** [comment]
感谢反馈,  经过验证确实有问题.  不过目前 目前的版本(最新版本 2.4.5)建议 使用cc.Color.fromHEX接口, 弃用cc.Color.fromHex接口,可以试试.

the same issue
https://github.com/cocos-creator/engine/issues/6910
