### ISSUE TITLE
[bug]qq无法加载自定义字体

### ISSUE THREAD

**Issue by xmsz** [cocos/cocos-engine#6720]
### Creator version?（版本号）
2.3.3

### Affected platform?（受影响的平台）

All

### How to reproduce?（如何重现）
使用自定义字体

构建以后，在qq开发工具，及qq真机都无法加载自定义字体。但qq是有这个功能的，然后微信端完全不受影响

### JavaScript output or error produced?（报错信息和调用栈）

当前版本暂不支持此加载自定义字体

**Comment by OnlyKoei** [comment]
你好，2.3.3版本引擎并没有适配 QQ 小游戏平台，在这个平台上出现的问题暂时不接受处理。
