### ISSUE TITLE
cocos 2.3.3版本，龙骨动画设置size，关闭编辑器，尺寸恢复原样

### ISSUE THREAD

**Issue by cocosyang** [cocos/cocos-engine#6746]
### Creator version?（版本号）
cocos creator 2.3.3

### How to reproduce?（如何重现）
按照demo里的龙骨动画，设置size，然后关闭编辑器，重新开启

### Demo project?（demo 项目）

[Test233.zip](https://github.com/cocos-creator/engine/files/4680198/Test233.zip)

**Comment by yeshao2069** [comment]
你好，使用你的测试demo，并不能运行。可以确认下，你的工程吗？
![image](https://user-images.githubusercontent.com/14273437/116522695-0eea4a00-a908-11eb-961a-7a4fa98c8a5c.png)

**Comment by yeshao2069** [comment]
用户长时间未回复，此单先关闭。

如果还是有问题，建议用户升级引擎版本到 2.4.5，再试试。请知悉，谢谢。
