### ISSUE TITLE
cc.Mask组件(type :RECT )，mask节点区域内子节点在 iOS9.x 上无法展示，必现无报错

### ISSUE THREAD

**Issue by yanyuling** [cocos/cocos-engine#6756]
### Demo project?（demo 项目）
[maskDemo.zip](https://github.com/cocos-creator/engine/files/4686278/maskDemo.zip)

**Comment by OnlyKoei** [comment]
你好，目前我们没有收到类似的反馈，如果可以的话，麻烦用最新版2.4.4测试下，看问题是否依旧存在。如果问题依旧存在，可以联系我们，我们会对其进行修复。
