### ISSUE TITLE
scrollView destroyAllChildren

### ISSUE THREAD

**Issue by 284263380** [cocos/cocos-engine#6758]
版本:2.1.2
控件 scrollView
问题:
1.scrollView 的content添加上孩子(很多个),孩子要求有label并且有描边
2.调用scrollView destroyAllChildren,然后带秒表的label报错了,h5平台

我修改了 
CCRenderComponent.js的函数,对this.node做了校验,你们看看是怎么样子
_canRender: function _canRender() {
                return this._enabled && cc.isValid(this.node) && this.node._activeInHierarchy;
 },

![image](https://user-images.githubusercontent.com/7555386/82981733-4c22c980-a01f-11ea-9699-1c08dd99b86f.png)

**Comment by 284263380** [comment]
版本是2.2.1, 写错了

**Comment by OnlyKoei** [comment]
这个问题由于我们最近都没收到同类反馈，可能已经修复了。麻烦你尝试一下最新 2.4.4 版本的引擎，看看这个 bug 是否仍然存在。先不用考虑升级到最新版是否稳定，会不会出现新的问题，仅仅是为了测试这个 bug。
如果没问题了，你们才考虑是否升级或者合并引擎某些修复。
如果测试完仍然有问题，我们来跟进处理。
如果还有复现，方便的话提供个demo.
