### ISSUE TITLE
C3D SpriteFrame在使用自动图集后 width height 获取错误

### ISSUE THREAD

**Issue by k8w** [cocos/cocos-engine#6759]
### Creator version?（版本号）
Creator 3D 1.1

### Affected platform?（受影响的平台）

ALL

### How to reproduce?（如何重现）
```
@property
sf: SpriteFrame;

start(){
    console.log(this.sf.width, this.sf.height);
}
```
当使用了自动图集后，编译后，获取的 `this.sf.width` 和 `this.sf.height` 均为对应的大图集的尺寸。
这显然与开发习惯和需求不符，应该是返回SpriteFrame对应原始图片的宽高才合理。

**Comment by yeshao2069** [comment]
感谢反馈，这个应该是一个引擎的bug了。

临时方案：
修改自动图集的配置，取消扩边选项(这个会导致左右各多出1像素)，修改默认的图片间距 padding 默认为0(padding默认为2，会导致左右多出各2像素)

**Comment by yeshao2069** [comment]
另外，你使用  sf.originslSize.width   sf.originslSize.height  这两个也是原始尺寸。

**Comment by yeshao2069** [comment]
感谢反馈，这个问题已经反馈给引擎组优化了。
可以按照临时方案处理，谢谢。
1、修改自动图集的配置，取消扩边选项，修改默认的图片间距 padding 默认为0
2、不修改配置的情况下，可以使用sf.originslSize.width sf.originslSize.height代替 sf.width/sf.height.
