### ISSUE TITLE
mac 打包 Etc1透明度错误

### ISSUE THREAD

**Issue by dmydb** [cocos/cocos-engine#6765]
### Creator version?（版本号）
cocos creator 2.3.1

### Affected platform?（受影响的平台）

android
### How to reproduce?（如何重现）
图集 压缩Etc1 RGB Separate A

mac 打包 Etc1透明度错误,被压缩了？ windows 平台打包正常

**Comment by xianyinchen** [comment]
这个压缩格式会导致透明度失真，但是应该不会出现mac和window存在差异情况，需要有对比图和原图资源才能确认。

**Comment by xianyinchen** [comment]
你好，如果该问题还有继续跟踪，麻烦提供个demo，我们会再做确认。
