### ISSUE TITLE
.excludes-min文件是怎么生成的？

### ISSUE THREAD

**Issue by TXWSLYF** [cocos/cocos-engine#6805]
我想在不支持webgl的手机上面切换到canvas渲染，但是发现打包的时候把canvas render相关的代码去除了，但是自己没有手动设置过。

然后切换到自定义引擎，发现构建的时候生成了一个.excludes-min文件，想问问这个文件的生成机制。
![image](https://user-images.githubusercontent.com/25768349/83490897-665b1c80-a4e3-11ea-9aa6-f169b063eacc.png)

### Creator version?（版本号）
2.3.2

### Affected platform?（受影响的平台）

web
### How to reproduce?（如何重现）
正常构建项目

**Comment by SantyWang** [comment]
现在编辑器都是默认剔除 Canvas Renderer 模块的，你把 Canvas Renderer 模块的入口文件，再复制一份出来吧，这样应该就能保留这个模块的代码了。
![image](https://user-images.githubusercontent.com/15109777/87660264-5d6f9300-c791-11ea-9d31-24a80cbfcfa6.png)
