### ISSUE TITLE
Synchronous calls that are actually Asynchronous in the Engine

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#6840]
### Creator version?（版本号）
- All versions up to 2.3.3

### Affected platform?（受影响的平台）
- Windows / macOS

### Description
This happens for many things in the game, but as a good and easy way to understand the problem is to explain with cc.destroy().
When you destroy a node with cc.destroy() or destroy all children or similar, the call is synchronous, while the actual action is asynchronous. This causes a lot of weird scenarios where you might be able to do some action on the node after the destroy() has been called.

This also happens with cc.NodePool().put() which is a synchronous call to the engine but works asynchronously.

I've seen that there will proper async handling in CC 2.5, I hope things like these are though of, cause it causes a lot of strange behavior when you don't take them into account and you have to run code like
```
cc.destroy()
setTimeout(() => wait for the current callstack to complete and hope that destroy is ready in the next callstack);
/** if cc.destroy() would return a promise, you could easily just:
 * await cc.destroy()
 * or cc.destroy.then(...)
 * and be sure it is deleted.
**/
```

### How to reproduce?（如何重现）
- Create a node with a button.
- Create a script with one function that calls cc.destroy(this.node) and apply it to the button node.
- Link the button click event to the function that runs cc.destroy(this.node) on the same node.
- Run the project and spam-click the button
- Now you check browser developer console and see that you call destroy of null, because you are able to send multiple click events and call multiple times cc.destroy(this.node) on the same node before it is actually destroyed.
![image](https://user-images.githubusercontent.com/7983358/84025891-fc37f100-a994-11ea-8f1a-ef0ac163222c.png)

**Comment by jareguo** [comment]
Hi, can you upload a demo for it? It should result "object already destroyed", or nothing happen. Since we checked destroy state here:
![image](https://user-images.githubusercontent.com/1503156/84102573-72932c80-aa43-11ea-9bb7-0894ed566a2a.png)

**Comment by zhefengzhang** [comment]
You can use cc.isValid to determine whether the node has been destroyed.
https://docs.cocos.com/creator/api/en/modules/cc.html#isvalid

**Comment by Ronsku** [comment]
I see, so it gets destroyed before next frame. I got a lot of weird bugs when thinking that node.destroy() would actually destroy it immediately. Couldn't this function be asynchronous then and resolve on next frame when it actually is destroyed? :)
