### ISSUE TITLE
Render problem of 3D character in browser

### ISSUE THREAD

**Issue by Jahangir-Redapple** [cocos/cocos-engine#6841]
The problem that we are facing in cocos creator 2.3.3 are as follows:
Create a player that moves over the platform and the camera follow the player. When we run that player it will properly render in simulator but not in browser.
In browser the player is not rendering for some time interval.

**Comment by yeshao2069** [comment]
Can you provide a demo?

**Comment by yeshao2069** [comment]
Due to long time no response, the ticket is temporarily closed. If possible, provide a simple demo for verification. thanks.
