### ISSUE TITLE
inverseTransformPoint 调用直接报错

### ISSUE THREAD

**Issue by xue2han** [cocos/cocos-engine#6874]
### Creator version?（版本号）
Cocos Creator 3D 1.1.0

### Affected platform?（受影响的平台）

所有平台
### How to reproduce?（如何重现）
只要调用inverseTransformPoint就报错，原因是inverseTransformPoint会对该节点的所有父节点，调用
`Vec3.transformInverseRTS(out, out, cur._lrot, cur._lpos, cur._lscale);`，然而根节点也就是Scene根本就没有_lrot,_lpos,_lscale这些属性，只有_rot,_pos,_scale。

### JavaScript output or error produced?（报错信息和调用栈）

TypeError: Cannot read property 'x' of undefined

**Comment by yeshao2069** [comment]
感谢反馈，问题可以复现，目前这个问题已经提交issue给开发排查了。

**Comment by yeshao2069** [comment]
这个问题是因为scene这个node 没有position的信息导致的。修复PR https://github.com/cocos-creator/engine/pull/9154
