### ISSUE TITLE
[需求] cocos提供默认的 白色图片, 和 透明图片.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6886]
其他游戏引擎里, 会有类似 Texture.WHITE  和 Texture.EMPTY 的对象,  分别对应一张 1*1 大小的白色图片, 和 透明图片.

这两个对象的存在 在实际开发中有很大的用处.
白色的可以方便的用 代码来创建单色精灵 ( 配合mesh 和 mask 可以创建任意形状的)

透明图片可以用来做图像占位符等.

希望cocos也能内置这两种对象.

**Comment by lupin888** [comment]
可以自己弄个文件夹 内置这2个图

**Comment by finscn** [comment]
> 可以自己弄个文件夹 内置这2个图

@lupin888  ,  我当然知道可以这样做, 但是这种做法 是从 "做项目" 的角度来思考.
而我是要做通用的工具和插件. 这么做 会给使用工具的人带来一些麻烦.  明明我写的是一个 工具函数 (一个js/ts文件) , 但是非要附带上一些图片文件, 然后还要让用户放到指定位置, 或者去设置资源所在位置. 然后使用前 还要确保这几个资源文件被正确加载了.  非常麻烦.

**Comment by finscn** [comment]
@2youyou2   ,  我后来用 你建议我的 canvas方式 确实实现了功能. 但是我发行 创建canvas其实是 创建了一个rendertexture.
(我看了代码 , 你们有 "合并" 的处理. 但是这个合并也是有极限的, 超过极限, 就会创建新的rendertexture)

对于我这个需求而已, 这个其实是不太好的一种做法 .
  首先 rendertexture对于很多设备来说, 是一种稀有资源(允许的数量有限) , 
 其次 它太过于牛逼了 (功能很强大, 能做的事情很多, 也占用更多系统资源) , 在这个小需求上, 用rendertexture有些 杀鸡用牛刀的感觉. 浪费资源.

所以我还是希望引擎能内置 这样两个 1*1像素的图片, 并在引擎初始化时加载, 并且以类似 Texture.WHITE, Texture.EMPTY 的形式全局保存.

然后在 彻底销毁sprite/spriteFrame(就是连通texture一起销毁时)  的代码里判断一下, "如果texture是这两个对象, 则不销毁texture".

望考虑. 谢谢

**Comment by 1226085293** [comment]
我也觉得可以提供这样的图片，每次都要自己弄一个，麻烦

**Comment by 1226085293** [comment]
1*1白色图用到的地方很多，背景、按钮、列表...等，都可以通过update渐变颜色实现各种效果，还是内置比较好

**Comment by 1226085293** [comment]
透明图片就直接用设置color就行了，半透明效果可以用白色底图调色，所以只需要1*1白色图

**Comment by lh4111** [comment]
可以使用`texture.initWithData`传入图片的数据
```js
    const data: any = new Uint8Array(2 * 2 * 4)
    for (let i = 0; i < 2; i++) {
      for (let j = 0; j < 2; j++) {
        //R
        data[i * 2 * 4 + j * 4] = 0
        //G
        data[i * 2 * 4 + j * 4 + 1] = 0
        //B
        data[i * 2 * 4 + j * 4 + 2] = 0
        //A
        data[i * 2 * 4 + j * 4 + 3] = 0
      }
    }

    const texture = new cc.Texture2D()
    texture.initWithData(data, cc.Texture2D.PixelFormat.RGBA8888, 2, 2)
    texture.handleLoadedTexture()
```

**Comment by yeshao2069** [comment]
感谢反馈，已经将需求提交给负责人。
