### ISSUE TITLE
[缺陷] node.color = color 的奇怪行为 , 以及 cc.Color 的设计问题

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6887]
下列代码
```
let color = cc.Color.fromHex(outColor, 0xffffff);
node.color = color
```
运行时会无效, 且给出错误警告.
```
Should not set alpha via 'color', set 'opacity' please.
```

看源码后,发现  Color.fromHex 返回的color 里 rgba的值都是  [0,1] 区间的.
而 node 接受的 color 是  [0, 255] 区间的.

--------
这个问题 衍生出另一个问题: 
 cocos的 Color 类,  在处理   到底是[0,1] 区间,  还是 [ 0,255]区间?  到底是rgb  还是rgba ?
这一类问题时, 一直非常混乱.

我之前还提过另一个问题:  https://github.com/cocos-creator/engine/issues/6676
是由 rgb / rgba 引发的.

--------
 从名字来说,  Color 应该是一个能够解决所有常见颜色问题的类.
而无论在cocos内部, 还是正常开发中, 程序员难免要和 如下内容打交道: 

[0, 1] 区间的颜色值
[ 0, 255 ]区间的颜色值
RGB
RGBA
HSL(HSB)
HSV
0xffffff (6位数值)
0xffffffff (8位数值)
#ffffff (6位css风格的颜色字符串)
#ffffffff (8位css风格的颜色字符串, 不常用)

然而, 目前的 cc.Color 无法很好的解决这些问题. 而且毫无规律.

我觉得是时候来一次不破不立的大重构了.

**Comment by finscn** [comment]
静态方法  Color. fromHex  和 实例方法   color.fromHEX 
名字差不多, 得到的都是 color对象,  但是 又不是一个体系下的. 
太奇怪了.

**Comment by jareguo** [comment]
> 看源码后,发现 Color.fromHex 返回的color 里 rgba的值都是 [0,1] 区间的.
> 而 node 接受的 color 是 [0, 255] 区间的.

这应该是之前重构或者代码合并时产生的 bug，谢谢反馈

> cocos 的 Color 类, 在处理 到底是[0,1] 区间, 还是 [ 0,255]区间? 到底是rgb 还是rgba ?

是 0 - 255，rgba

> 我觉得是时候来一次不破不立的大重构了.

从性能的角度，0 - 255 比较好，从计算的角度 0 - 1 比较好。我们之后可能会提供 cc.Color32 来支持浮点运算。目前其实用 Vec4 也是能顶替一下的。

**Comment by finscn** [comment]
@jareguo 一般 out 都是最后一个参数, 且可选.   fromHex 能不能也这么设计一下?

**Comment by jareguo** [comment]
这里需要和 3D 统一，不鼓励用户可选。不可选的参数就不放在最后一个了。
