### ISSUE TITLE
[需求]希望增强下cc.tween或者提供一个新的插值系统

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6909]
cc.tween 是对 原有的 cc.Action的增强.
好处主要是:  1) 可以改变任意属性,  2) 使用起来代码更直观简洁  3) 与node解耦, 不用依托于node

这3个特性非常好,  但是tween做的并不彻底, 原有 cc.Action上的一些功能并不支持, 比如非常有用的下面4个:

cc.cardinalSplineTo 
cc.cardinalSplineBy
cc.catmullRomTo
cc.catmullRomBy

此为 cc.tween能支持这4个功能

当然, 严格来说 这4个特性并不属于"tween".  而是一种插值计算.
知名的 Tween.js 库 ( https://github.com/tweenjs/tween.js/ ) , 也是用过一个叫`interpolation` 的子模块来实现的类似功能. ( demo:　http://tweenjs.github.io/tween.js/examples/06_array_interpolation.html　）

希望 cocos能提供类似功能, 无论是硬塞到 cc.tween里, 还是单独提供个 cc.interpolation 我都能接受.
总之, 我需要这几个功能, 同时又很喜欢前面提到的那三个优点 [ 1) 可以改变任意属性,  2) 使用起来代码更直观简洁  3) 与node解耦, 不用依托于node ]

望考虑
谢谢.

**Comment by yeshao2069** [comment]
感谢反馈，你的需求已经提交给负责人
