### ISSUE TITLE
[BUG] 引擎中关于颜色处理的代码里, ` >> 24 ` 应该改成 ` >>> 24 ` 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6910]
### Creator version?（版本号）
2.4 

### Affected platform?（受影响的平台）
all

现在的代码里
```
0xffffffff >> 24   等于 -1  ,
0xffffffff >>> 24   等于 255  ,
```
大多数情况下, 后者才是正确的吧?

**Comment by finscn** [comment]
举个具体例子:
```
    static fromHex (out: Color, hex: number): Color {
        let r = ((hex >> 24)) / 255.0;
        let g = ((hex >> 16) & 0xff) / 255.0;
        let b = ((hex >> 8) & 0xff) / 255.0;
        let a = ((hex) & 0xff) / 255.0;

        out.r = r;
        out.g = g;
        out.b = b;
        out.a = a;
        return out;
    }
```

color里的这个代码.    hex >> 24 就会出现 -1 的情况.
所以 要么 >>> 24 , 要么 后面也和其他颜色位一样, 加个 ` & 0xff` 
反正现在这样有问题. (也不是总有问题, 因为有时候 可能后续使用这个值的函数里, 自己会做 `& 0xff` 的操作.

但是单纯从这个函数来看,  ` >> 24 ` 肯定是不科学的.

**Comment by yeshao2069** [comment]
感谢反馈,  经过验证确实有问题.  不过目前 目前的版本(最新版本 2.4.5)建议 使用cc.Color.fromHEX接口, 弃用cc.Color.fromHex接口,可以试试.
