### ISSUE TITLE
Creator 2.3.3 can't read correct data from Spine3.6.37 binary file, but json file ok

### ISSUE THREAD

**Issue by chongchaoyu** [cocos/cocos-engine#6916]
Creator 2.3.3 can't use spine binary data, spine is created by Spine3.6.37

### Affected platform?（受影响的平台）
1. Mac Editor/Web/Simulator are affected.
2. Windows Editor / iOS / Android are NOT tested.

### How to reproduce?（如何重现）Add the followings into any scripts
All the resources referred can be found at 
1. Add spines files into creator, drag the resources to the scene, then run.
OR
2. Add the code into onLoad function in HelloWorld.js.
`        cc.loader.loadRes("spines/1001", sp.SkeletonData, function (err, asset) {
            var skeleton = this.node.addComponent(sp.Skeleton);
            skeleton.skeletonData = asset;
            skeleton.setAnimation(1, "daiji", true);
        }.bind(this));`

### JavaScript output or error produced?（报错信息和调用栈）
No error will report at Web when using code to add spine, just log "Spine: Animation not found: daiji"

**Comment by chongchaoyu** [comment]
update and so sad:(
Spine skeleton animation resources are data formats that exported by Spine (Creator v2.0.7 and below support for Spine v2.5, Creator v2.0.8 to v2.1 support for Spine v3.6, Creator v2.2 support for Spine v3.7, Creator v2.3 and above support for Spine v3.8). [creator doc](https://docs.cocos.com/creator/manual/en/asset-workflow/spine.html)

**Comment by xianyinchen** [comment]
this spine data parse fail, possible compatibility issues, you can try use spine 3.8.

<img width="1686" alt="WeChat98aeb6a44058a25558f76cddc13b4683" src="https://user-images.githubusercontent.com/8321365/126607597-c4a82be2-f7e0-4539-b88a-34a6bd993570.png">

**Comment by xianyinchen** [comment]
If the problem still exists after upgrading the spine export version 3.8, please provide the spine source file and we will confirm it again.
