### ISSUE TITLE
Creator 3D 1.10中材质的TilingOffset无法保存

### ISSUE THREAD

**Issue by wish-wish** [cocos/cocos-engine#6930]
Creator 3D 1.10中Prefab材质的TilingOffset无法保存

**Comment by yeshao2069** [comment]
感谢反馈。
经确认，这边使用 Cocos Creator3D 1.2.0（Cocos Creator 3D系列最新）做了测试，是可以保存成功的。

在层级管理器下，新建一个material，然后在prefab中使用 meshrender，把material挂载在meshrender组件的material属性上，修改material中的tillingOffset属性，保存。
[testDemo120.zip](https://github.com/cocos-creator/engine/files/6616204/testDemo120.zip)

另外，目前引擎最新的版本为3.1.1，建议你升级至最新的版本，重试，如有问题，可以再次提交issue和我们反馈。
