### ISSUE TITLE
translate函数设置z坐标错误

### ISSUE THREAD

**Issue by 1226085293** [cocos/cocos-engine#6931]
### Creator version?（版本号）
1.1.0

### Affected platform?（受影响的平台）

1.1.0及以下

### How to reproduce?（如何重现）
https://github.com/cocos-creator/engine/blob/cdf18b197ba4cb99f1c901733f2b66de026e61ef/cocos/core/math/mat4.ts#L1781

**Comment by SantyWang** [comment]
已修复
