### ISSUE TITLE
替换粒子系统的plist文件时，新文件关联的SpriteFrame不会被设置到粒子系统中。

### ISSUE THREAD

**Issue by caogtaa** [cocos/cocos-engine#6976]
### Creator version?（版本号）
2.4.0

### Affected platform?（受影响的平台）

All

### How to reproduce?（如何重现）
1. 准备两个粒子的plist文件，两个文件关联不同的SpriteFrame。分别称其为file1、file2
2. 修改cc.ParticleSystem.file，来回替换file1和file2
3. 重现问题：cc.ParticleSystem关联的SpriteFrame没有变化

### Demo project?（demo 项目）

[ParticleSystemFileReplaceTest.zip](https://github.com/cocos-creator/engine/files/4904561/ParticleSystemFileReplaceTest.zip)
![image](https://user-images.githubusercontent.com/4058573/87182207-4276cc00-c316-11ea-8c0e-311e6b6dda3b.png)
![image](https://user-images.githubusercontent.com/4058573/87182263-65a17b80-c316-11ea-80a9-8cc8862587e0.png)

**Comment by zhefengzhang** [comment]
已经修复，尝试合并 pr 看看。

**Comment by caogtaa** [comment]
基于v2.4.1-release分支合并PR后，运行报错
![image](https://user-images.githubusercontent.com/4058573/89067760-7d62a180-d3a2-11ea-8121-b53e3130dc5d.png)

**Comment by zhefengzhang** [comment]
之前的代码有 bug，self._plistFile 需要在 _initWithDictionary 执行之前赋值。已经修改。

**Comment by yeshao2069** [comment]
经确认，这个问题在2.4.4版本被修复了。
使用你的Demo在2.4.5版本，测试运行OK。
麻烦升级到 2.4.4+的creator版本，并重试，感谢反馈。
