### ISSUE TITLE
CCAudioSource 无法正确获得 duration

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6978]
### Creator version?（版本号）
2.4

### Affected platform?（受影响的平台）
all

### 描述
默认创建的CCAudioSources实例 audioSource,

audioSource.clip = 一个已经加载完毕的AudioClip;
console.log(audioSource.getDuration()) // 输出总是0;

原因: CCAudioSource的_ensureDataLoaded没有被调用.
```
  _ensureDataLoaded: function _ensureDataLoaded() {
    if (this.audio.src !== this._clip) {
      this.audio.src = this._clip;
    }
  },
```
此时  this.audio.src总是null.

而getDuration方法如下:
```
    proto.getDuration = function () {
        return this._src ? this._src.duration : 0;
    };

```
于是总是返回 0;

**Comment by finscn** [comment]
@PPpro  在原生环境下， 调用_ensureDataLoaded也不行， 必须调用 play， 才能正确获得duration

**Comment by PPpro** [comment]
感谢反馈，修复将进入 v2.4.3
