### ISSUE TITLE
CocosCreator 2.4 在macOS 10.15.5 下， 无法在VSCode里打开项目文件夹。

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#6979]
### Creator version?（版本号）
 2.4

### Affected platform?（受影响的平台）
macOS 10.15.5 

### How to reproduce?（如何重现）
在 CocosCreator  里双击一个项目里的 ts 文件， 会在 vscode里 打开该文件， 但是无法打开项目所在的文件夹。
需要在vscode里手动打开文件夹才行。
vscode也已经升级到最新版本。

**Comment by yeshao2069** [comment]
经过测试，我使用点击一个 JS / TS文件，可以打开整个工程的文件夹。
macOS版本： 11.3.1 
Cocos Creator 版本：2.4.5
Visual Studio Code 版本： 1.56.2

![image](https://user-images.githubusercontent.com/14273437/119952645-d2297580-bfcf-11eb-9b7b-aff2ad6eb0a9.png)
![image](https://user-images.githubusercontent.com/14273437/119952985-1e74b580-bfd0-11eb-9e25-5fe2bce4eb49.png)

如果是引擎版本、macOS版本、Visual Studio Code版本，请升级至最新后重试，感谢反馈。
