### ISSUE TITLE
creator.d.ts 没有暴露 cc.Assembler , cc.Assembler2D  , SimpleSpriteAssembler,  RenderData

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7009]
### Creator version?（版本号）
2.4

### Affected platform?（受影响的平台）
all

### How to reproduce?（如何重现）
自定义渲染组件以及对应的Assembler是一个正常的需求 (虽然可能普通用户用不到) , 文档里也有相关介绍.
既然如此, 那么 creator.d.ts 里理应暴露 这些类.

**Comment by yeshao2069** [comment]
这个需求已经提交内部评估，是否暴露出来。
