### ISSUE TITLE
creator.d.ts 文件中 `cc.dynamicAtlasManager.insertSpriteFrame` 方法返回类型错误

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7011]
### Creator version?（版本号）
2.4

### Affected platform?（受影响的平台）
all

### How to reproduce?（如何重现）

cc.dynamicAtlasManager.insertSpriteFrame 返回值是一个对象, 不是 void.

**Comment by OnlyKoei** [comment]
在最新版（2.4.4）已经进行修改，如果后续还有其他问题，可以继续联系我们，感谢反馈！
