### ISSUE TITLE
creator.d.ts 没有暴露 Material的getHash()方法

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7012]
### Creator version?（版本号）
2.4

### Affected platform?（受影响的平台）
All

### How to reproduce?（如何重现）
该方法是公共方法, 在自定义RenderComponent时 会用到

**Comment by yeshao2069** [comment]
这个需求已经提交内部评估，是否暴露出来。

**Comment by yeshao2069** [comment]
3.x版本 可以通过 Material.getHash()获取材质的哈希值，也可以通过通过  mat.hash 获取材质实例的哈希值。
2.x版本目前暂时还没有这样子的接口暴露。
