### ISSUE TITLE
bug:cocos creator 在IOS微信无法运行

### ISSUE THREAD

**Issue by sukylovetocode** [cocos/cocos-engine#7041]
手机型号：iOS11 / IOS XR 
环境：微信客户端
Creator version?（版本号） v2.1.2
挂载了音频节点后，打包的H5文件无法在IOS某些版本手机的微信客户端打开
挂载的音频文件内容
![image](https://user-images.githubusercontent.com/36320235/88794174-a0d5f280-d1d0-11ea-8a89-2a684bc75686.png)

直接就打不开，没有报错

![image](https://user-images.githubusercontent.com/36320235/88794323-e1357080-d1d0-11ea-8e3b-f9e9913d12f0.png)

**Comment by xduooo** [comment]
哥们，告诉你个事儿，现在 creator 版本号已经 2.4.2+ 了

**Comment by SantyWang** [comment]
能给个demo么？已经构建好的

**Comment by sukylovetocode** [comment]
非常不好意思，我又测了一次 发现是音乐的meta文件不知道啥时候被人修改了，导致cocos无法获取音效导致的bug 因为当时增加了音乐节点就导致打不开，关闭了就好了

**Comment by SantyWang** [comment]
没问题就好
