### ISSUE TITLE
华为手机3D模型渲染动画出错,bs设置没有效果

### ISSUE THREAD

**Issue by xhk1992** [cocos/cocos-engine#7099]
### Creator version?（版本号）
CocosCreator3D 1.1.1

### Affected platform?（受影响的平台）

Android native 

### How to reproduce?（如何重现）
直接构建工程，勾选usebakedanimation 骨骼动画在华为P9上会有渲染问题

在华为荣耀10上动画没有问题，但是在update里设置blednshape 值无效

PC预览情况:
![image](https://user-images.githubusercontent.com/9582710/89620562-6c45f300-d8c2-11ea-8569-3a7b4a7781a4.png)

华为P9:
![image](https://user-images.githubusercontent.com/9582710/89620500-51737e80-d8c2-11ea-8eab-96b99592706e.png)

### JavaScript output or error produced?（报错信息和调用栈）

![image](https://user-images.githubusercontent.com/9582710/89616576-33565000-d8bb-11ea-83e2-ce7de9ed450c.png)

### Demo project?（demo 项目）

[assets.zip](https://github.com/cocos-creator/engine/files/5039898/assets.zip)
工程仅包含动作示例，BS出错示例未包含

**Comment by zhefengzhang** [comment]
应该是和 https://github.com/cocos-creator/engine/issues/8768 一样的问题。
参考临时方案：
https://forum.cocos.org/t/topic/117447/3?u=695105047
