### ISSUE TITLE
RevoluteJoint is not being detached when ConnectedBody is set to null

### ISSUE THREAD

**Issue by migguli** [cocos/cocos-engine#7105]
RevoluteJoint is not being detached as expected when ConnectedBody is set to null and RevoluteJoint.apply() called.

### Creator version?（版本号）
2.4.1

### Affected platform?（受影响的平台）

Windows editor.

### How to reproduce?（如何重现）
Node one (base):
Static RigidBody.

Node two:
Dynamic RigidBody.
RevoluteJoint with defaults.
PhysicsBoxCollider with defaults
Test script component with script: 

const { ccclass, property } = cc._decorator;

@ccclass
export default class NewClass extends cc.Component {
  // LIFE-CYCLE CALLBACKS:

  onLoad() {
    cc.director.getPhysicsManager().enabled = true;
  }

  start() {
    const joint = this.getComponent(cc.RevoluteJoint);
    joint.connectedBody = cc.find('Canvas/base').getComponent(cc.RigidBody);
    joint.apply();
    joint.connectedBody = null;
    joint.apply();
  }

  update(dt) {
    cc.log(this.node.position.toString());
  }
}
`

Optionally sprite renderers two visually observe the issue. 

### JavaScript output or error produced?（报错信息和调用栈）

No errors produced

### Demo project?（demo 项目）

https://github.com/migguli/RevoluteJointIssueDemo

**Comment by xianyinchen** [comment]
Thanks for the feedback, this is an issue and you can bypass the problem using the code below.

``` javascript
start() {
    const joint = this.getComponent(cc.RevoluteJoint);
    joint.connectedBody = cc.find('Canvas/base').getComponent(cc.RigidBody);
    joint.enabled = true;

    joint.enabled = false;
    joint.connectedBody = null;
    joint.enabled = true;
}
```
