### ISSUE TITLE
[Feature Request] ES6 Classes for inheritance.

### ISSUE THREAD

**Issue by ggarek** [cocos/cocos-engine#711]
It would be awesome if it was possible to use es6 classes for components.

``` javascript
class Enemy extends cc.Component {
  static properties = {
    maxHP: { default: 100, visible: true },
    restoreHPPerSec: 1,
  };

  onLoad() {
    // Props could be treat as immutable 
    const { maxHP } = this.props;
    // It is pretty handy to keep the whole state in one place as plain object
    this.state = {
      hp: maxHP,
      restoreHPTs: 0
    };
  }

  update(dt) {
    const { hp } = this.state;
    const { maxHP, restoreHPPerSec } = this.props;

    if (maxHP !== hp) {
      const now = Date.now();
      if (now - this.state.restoreHPTs >= 1000) {
        this.state.hp = Math.min(maxHP, hp + restoreHPPerSec);
        this.state.restoreHPTs = now;
      }
    }
  }
}
```

The code becomes more clean and thus more readable and imo conformance to the standard is a good idea.

I understand that it may be pretty hard to implement, since it leads to breaking changes. (now properties are spread directly to `this`). Not impossible though.

**Comment by jareguo** [comment]
Thanks, ggarek. There are two phases: first, define properties by using decorators, second, define the entire class by es6. IMO the second is hard to implement since their behaviors is different. Maybe we should try to extends the es6 “class” keyword to "ccClass".

**Comment by jareguo** [comment]
We will implement some decorators in 1.5 to help define the components by using ES6 Classes.
