### ISSUE TITLE
在Mac Editor上导入一个在Windows Editor上导入过的fbx以及生成的meta文件会出现uuid collision报错

### ISSUE THREAD

**Issue by delguoqing** [cocos/cocos-engine#7113]
### Creator version?（版本号）
2.4.2

### Affected platform?（受影响的平台）

Mac Editor

### How to reproduce?（如何重现）
将附件中的zip文件解压到随便一个Mac上的空工程的assets目录下即可重现。

### JavaScript output or error produced?（报错信息和调用栈）

[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Acce2.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh1_13.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Acce3.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh1_14.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/obj1.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh1_17.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Body_9.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh1_32.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/obj3.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh2_16.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh2_9.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_1.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Ribbon_xas.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_2.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh1_35.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_3.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh2_18.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_4.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Hot.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_5.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Don_2.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_9.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Teppan_Base.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_10.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Misoshiru_6.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mouse_11.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh1_5.mesh. This resource is about to be ignored.
[db-task][init] uuid collision, the uuid for /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Table_1.mesh is already in used by /Users/unity/Documents/BugDemos/fbxreimportbug/assets/root.fbx/Mesh2_5.mesh. This resource is about to be ignored.

### Demo project?（demo 项目）

[fbxreimportbug.zip](https://github.com/cocos-creator/engine/files/5055088/fbxreimportbug.zip)

**Comment by xianyinchen** [comment]
你好，这个demo在2.4.5版本测试并不会出现上述错误信息，请确认。
