### ISSUE TITLE
Cocos Creator 开源问题

### ISSUE THREAD

**Issue by winthropchang** [cocos/cocos-engine#7123]
### Creator version?（版本号）
https://docs.cocos.com/creator/manual/zh/submit-pr/submit-pr.html
上面写着 `和 Cocos2d-x 一样，Cocos Creator 也是一个开源引擎，连同范例、文档都是开源的。`
不过找不到 git 位置 
请问是真的开源了吗？
不然写 extension 时遇到数值浮点数问题很麻烦
如果开源了还可以自己修改一份

**Comment by hszhsh** [comment]
引擎是开源的，编辑器不开源

**Comment by yeshao2069** [comment]
目前，引擎是开源的，编辑器不开源。
JavaScript 引擎：https://github.com/cocos-creator/engine
Cocos2d-x 引擎：https://github.com/cocos-creator/engine-native
jsb-adapter：https://github.com/cocos-creator-packages/jsb-adapter
Mini-game-adapters：https://github.com/cocos-creator-packages/adapters/
