### ISSUE TITLE
Cocos Creator 2.4.2 制作Asset Bundle 加入 cc.AnimationClip 时候的错误 (Asset Bundle build issue when cc.AnimationClip is included)

### ISSUE THREAD

**Issue by kenlee11021993** [cocos/cocos-engine#7128]
### How to reproduce :-
1. 开个新的文件夹，然后把"Is Bundle" 勾了

2. 加入 .png 和 .plist到 改文件夹

3. 在当下文件制作新的 cc.AnimationClip 

4. 再到“层级管理器” 下加个新的节点再添加组件（cc.Sprite和cc.Animation）

5. 之后把(3) 制作好的cc.AnimationClip托到(4) 的节点cc.Animation 设置成 "Default Clip" 记得保存

6. 然后编辑(3) 的cc.AnimationClip, 并加入 cc.Sprite.SpriteFrame 将(2) plist文件下的全部 sprite frames 拖入

7. 保存并退出编辑模式

8. 之后开始 “构建发布” 构建出来

9. 在构建出来的文档中，bundle文档应该会出现在 native 文件夹里面，然而native文件夹里并没有 .png

10. 如果删除了(3) 的 cc.AnimationClip 在 从新构建 项目

11. 在项目的Native 文件下的就可以找到 .png文档

English :-
1. Create a new folder and tick "Is Bundle"
2. Add in .png and .plist to the asset bundle folder
3. Create a new cc.AnimationClip asset in the asset bundle folder
4. Create a new cc.Node in scene with cc.Sprite and cc.Animation components
5. Drag the cc.AnimationClip into the cc.Animation component as "Default Clip"
6. Edit the cc.AnimationClip, add "cc.Sprite.SpriteFrame" property and drag in all of the sprite frames in .plist
7. Exit editing mode and save
8. Build the game
9. The exported asset bundle doesn't include the .png in native folder, which results in error when trying to load the image in bundle.load as the .png can't be found
10. Deleting the cc.AnimationClip and build it again.
11. The .png is back in the native folder again

**Comment by SantyWang** [comment]
这个是正常现象，因为场景引用到了 animationClip， animationClip 又引用了这个plist文件，场景属于 main bundle 所以最后这些资源都归到了 main bundle 里面。你可以把该场景也放到这个bundle下，这样就正常了。或者你可以把这个 bundle 的优先级调到比 main bundle 高，比如 8, 这样也会正常。可以参考下 [优先级的说明](https://docs.cocos.com/creator/manual/zh/asset-manager/bundle.html#%E4%BC%98%E5%85%88%E7%BA%A7)

**Comment by kenlee11021993** [comment]
> 这个是正常现象，因为场景引用到了 animationClip， animationClip 又引用了这个plist文件，场景属于 main bundle 所以最后这些资源都归到了 main bundle 里面。你可以把该场景也放到这个bundle下，这样就正常了。或者你可以把这个 bundle 的优先级调到比 main bundle 高，比如 8, 这样也会正常。可以参考下 [优先级的说明](https://docs.cocos.com/creator/manual/zh/asset-manager/bundle.html#%E4%BC%98%E5%85%88%E7%BA%A7)

謝謝， 就是 這個bundle的优先级的問題
