### ISSUE TITLE
16*16的TiledMap地图渲染有问题,每个Tiled块边缘只显示一半的像素

### ISSUE THREAD

**Issue by 958877748** [cocos/cocos-engine#7193]
### How to reproduce?（如何重现）
使用16*16的TiledMap地图 注意观察每个Tiled边缘的一圈像素

**Comment by 958877748** [comment]
[demo.zip](https://github.com/cocos-creator/engine/files/5103039/demo.zip)

**Comment by finscn** [comment]
FIX_ARTIFACTS_BY_STRECHING_TEXEL_TMX  这个参数的锅. 设置成false就可以了

**Comment by 958877748** [comment]
确实如此，谢
