### ISSUE TITLE
[需求] bundle增加 loadAny({uuid: config.image }） 或者loadByUUID 的 api

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7204]
目前有 cc.assetManager.loadAny({uuid: config.image }） 这个api.
但是该api过于强大 和 "偷懒", 如果频繁使用, 会让代码可读性 和 可维护性下降.
因为不能直观的了解资源所属的 bundle.

**Comment by SantyWang** [comment]
赞同你的想法，不过我们有几点考量：
1. UUID 其实不是我们想让开发者关注的属性（至少不是普通开发者），所以 loadByUuid 这类的方法其实并不常用
2. 目前整个 AssetManager 里面的接口已经很多了，再增加一个与 loadAny 相似的 loadByUuid，会增加普通开发者的负担。

我建议暂时自己封装一个类似的 api。等 3.0 之后，我们再重新整理这块的 API
