### ISSUE TITLE
CLEAN_IMAGE_CACHE为true时，加载硬件压缩格式图片不释放文件内存

### ISSUE THREAD

**Issue by dj4156003** [cocos/cocos-engine#7209]
### Creator version?（版本号）
应该是截止目前最新版本都有这个问题

### Affected platform?（受影响的平台）

Native Android和iOS
### How to reproduce?（如何重现）

如果在原生平台上某张图片使用硬件压缩格式，那么当CLEAN_IMAGE_CACHE设置为true时，在运行时加载后图片文件内存部分不会被清除，会造成堆内存过高，**问题的关键代码位于CCTexture2D.js的_nativeAsset setter函数里，如注释所示**
```
        _nativeAsset: {
            get () {
                // maybe returned to pool in webgl
                return this._image;
            },
            set (data) {
                if (data._compressed && data._data) {
                    //压缩的会走这，在Native上data也是一个Image对象，但是如果CLEAN_IMAGE_CACHE为true，
                    //调用完initWithData后并没有像initWithElement里那样针对Image清除src
                    this.initWithData(data._data, this._format, data.width, data.height);
                }
                else {
                    this.initWithElement(data);
                }
            },
            override: true
        },
```

**Comment by xianyinchen** [comment]
这个是目前设计的问题，你可以通过修改下面代码进行优化
<img width="1452" alt="WeChatf87029fda88bf510bdc403472f1d7281" src="https://user-images.githubusercontent.com/8321365/126605454-4deb4e57-316a-417f-a35a-e44c9613a88c.png">
