### ISSUE TITLE
FIX_ARTIFACTS_BY_STRECHING_TEXEL_TMX 这个配置应该去掉. 没啥用, 并不能解决问题,还会产生新问题.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7247]
FIX_ARTIFACTS_BY_STRECHING_TEXEL_TMX 想要解决的问题 本质上是需要通过 预乘 来解决的.

FIX_ARTIFACTS_BY_STRECHING_TEXEL_TMX 并不能解决根本问题, 还会让一些没问题的产生问题.

我新写的TIled组件已经支持预乘了.

**Comment by yeshao2069** [comment]
感谢反馈。

**Comment by yeshao2069** [comment]
FIX_ARTIFACTS_BY_STRECHING_TEXEL_TMX 并不能解决根本问题, 还会让一些没问题的产生问题.

--- 这个产生新的问题， 有具体是哪些问题？

**Comment by yeshao2069** [comment]
该问题已经提交引擎组。该工单暂时先关闭。
