### ISSUE TITLE
node节点的color不能影响 graphics画的图形的颜色

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7253]
### Creator version?（版本号）
2.4.2

### Affected platform?（受影响的平台）
all
### How to reproduce?（如何重现）
Graphics组件所在node的color设置成红色.
Graphics自身的颜色都是白色.  stroke()和fill()画出来的区域仍然是白色. (期待是红色)

**Comment by chenpangzi** [comment]
graphics组件有自己的属性设定颜色 
<html>
<body>


strokeColor | 设置或返回笔触的颜色
-- | --
fillColor | 设置或返回填充绘画的颜色


</body>
</html>

**Comment by yeshao2069** [comment]
和楼上说的一样，graphics组件有自己控制颜色的方法。
如果节点影响graphics组件的话，那么笔触颜色和填充颜色就不好设置(因为会被节点影响)。你这个需求，其实就是改graphics组件就行了。
