### ISSUE TITLE
在engin层增加一个component 编译器面板会有报错

### ISSUE THREAD

**Issue by BoyLei** [cocos/cocos-engine#7324]
### How to reproduce?（如何重现）
在engine层 仿照 button写了一个组件，分别在 cocos2d/core/components/index.js 中增加了 require（''./xxx） 
和在 engine/modules.json 中配置之后，编译egine后 点任意一个节点依旧会报错

### JavaScript output or error produced?（报错信息和调用栈）
![image](https://user-images.githubusercontent.com/23691195/92369042-15367680-f12b-11ea-8649-57e1f8572084.png)

详细过程请调整：https://forum.cocos.org/t/engine-properties/96873

**Comment by yeshao2069** [comment]
使用 3.0.0版本测试，添加component是可以的。
在 engine/cocos/ui 目录下，自定义一个 scroll-view-withLabel 组件

import { ccclass, executionOrder, menu, requireComponent } from 'cc.decorator';
import { UITransform } from 'cocos/2d';
import { Label } from '../2d/components';
import { ScrollView } from './scroll-view';

@ccclass('cc.ScrollViewWithLabel')
@executionOrder(110)
@menu('UI/ScrollViewWithLabel')
@requireComponent(UITransform)
export class ScrollViewWithLabel extends ScrollView {

    get ShowLabel () {
        return this._label;
    }

    set ShowLabel (value: Label | null) {
        if (this._label === value) {
            return;
        }

        this._label = value;
    }

    protected _label: Label | null = null;
}

在engine/cocos/ui/index.ts 添加该组件
// ....
export { ScrollViewWithLabel } from './scroll-view-withLabel';
// ....

然后自定义引擎，在节点上添加 ScrollViewWithLabel 正常
![image](https://user-images.githubusercontent.com/14273437/119706277-58d53a00-be8c-11eb-8345-9a53dfaa1e24.png)
