### ISSUE TITLE
Joints Texture precision problem on iOS webgl

### ISSUE THREAD

**Issue by vominhtam1210** [cocos/cocos-engine#7346]
### Creator version?（版本号）
2.4.2

### Affected platform?（受影响的平台）

Web on iOS devices

### How to reproduce?（如何重现）
Create 3D Stage with a 3d model playing its animation. Put the camera and the model in position with large value, eg. (480, 320).
Play the game in web browser on iOS devices.

### Problem detail
Webgl on iOS devices has only 128 for Max Vertex Uniform Vectors.
As a workaround, Cocos Creator engine will use float texture to contain the joint matrices. And it has the problem with float precision.

### Solution
Change the shader from "uniform sampler2D jointsTexture" to "uniform **highp** sampler2D jointsTexture".

[Reference topic](https://stackoverflow.com/questions/40459944/webgl-does-oes-texture-float-require-storage-as-32-bit-floats-some-devices-see)

**Comment by zhefengzhang** [comment]
Thanks for the feedback, we will improve it into the engine.
