### ISSUE TITLE
Multiple Fonts in a single label due to fallback fonts

### ISSUE THREAD

**Issue by Ronsku** [cocos/cocos-engine#7402]
### Creator version?（版本号）
All versions, but example with latest 2.4.2

### Affected platform?（受影响的平台）
All Platforms

### How to reproduce?（如何重现）
- Create a label
- Attach a font
- Type something that is included in the font and something that is not.
- Check the result of ONE label with TWO different fonts.
**- I think if one character is not supported by the font. Then the whole label should use a fallback font to not look crazy. Another option would be to let you decide how the fallback should work. E.g. "Fallback per character", "fallback per word", "fallback per label" or similar. I think though most of us would always use "Fallback per label" anyway.**

### Demo project?（demo 项目）
Demo project included into this ticket.
[Label-font-fallback-issue.zip](https://github.com/cocos-creator/engine/files/5237945/Label-font-fallback-issue.zip)

Image from the result:
Since the chinese characters in Robot Black isn't supported you will see the numbers in Roboto black and the Chinese characters in some browser/device selected fallback font.
![image](https://user-images.githubusercontent.com/7983358/93452592-42c8b000-f8e1-11ea-8b48-1d527b221599.png)
![image](https://user-images.githubusercontent.com/7983358/93452063-a43c4f00-f8e0-11ea-91ad-afefc2e183a6.png)

**Comment by xianyinchen** [comment]
It is not possible, because the character draw is use the system/browser function, missing character alway instead by default font set.

**Comment by Ronsku** [comment]
@xianyinchen wouldn't it be possible to first investigate the whole string and then decide if it contains any characters that isn't supported in the selected font and in that case use a fallback font for the whole label?
