### ISSUE TITLE
GraphicsComponent内存泄漏严重. Memory Leaks

### ISSUE THREAD

**Issue by dedecn** [cocos/cocos-engine#7418]
### Creator version?（版本号）
cocos creator 3d v1.1.0 ~ v1.1.2

### Affected platform?（受影响的平台）
全平台

### How to reproduce?（如何重现）
在一个UI Node上面添加一个GraphicsComponent， 再添加一个由下面代码写的Draw Component，在浏览器运行后，看到内存飞涨

`
import {_decorator, Component, Node, Vec3, Vec2, GraphicsComponent, Color} from "cc";

const {ccclass, property} = _decorator;

@ccclass("Draw")
export class Draw extends Component {
    i = 0;
    start () {
        this.drawLine()
    }
    drawLine() {
        let g = this.getComponent(GraphicsComponent);
        g.clear()
        g.moveTo(100 + this.i, 100)
        for(let j=0;j<1000;j++) {
            g.lineTo(200 + this.i, 200+j)
        }
        g.stroke();
        this.i++;
    }
    update (deltaTime: number) {
        // Your update function goes here.
        this.drawLine()
    }
}

`

**Comment by yeshao2069** [comment]
使用 Cocos Creator 3D 1.2.0 测试，确实内存涨幅比较明显。
![image](https://user-images.githubusercontent.com/14273437/119943616-d8b2ef80-bfc5-11eb-847a-6d4c0fdd1fe1.png)
![image](https://user-images.githubusercontent.com/14273437/119943626-de103a00-bfc5-11eb-8630-cc5043ba77f1.png)
![image](https://user-images.githubusercontent.com/14273437/119943642-e49eb180-bfc5-11eb-909c-a7a1d35aba81.png)
测试工程
[testGraphics-3d1.2.0.zip](https://github.com/cocos-creator/engine/files/6558928/testGraphics-3d1.2.0.zip)

使用Cocos Creator 3.x测试，内存稳定。
![image](https://user-images.githubusercontent.com/14273437/119942652-ace33a00-bfc4-11eb-86b1-c33dbf452df5.png)
测试工程
[Graphics-3.1.0.zip](https://github.com/cocos-creator/engine/files/6558902/Graphics-3.1.0.zip)

建议升级到3.x版本，感谢支持。
