### ISSUE TITLE
monorepo的项目带@的npm依赖加载错误

### ISSUE THREAD

**Issue by atomcated** [cocos/cocos-engine#7421]
### Creator version?（版本号）
2.4.2

### Affected platform?（受影响的平台）

全平台
### How to reproduce?（如何重现）
cocos creator2.4.2 monorepo的项目，子项目中引用带有@的依赖报错，不带@的依赖正常加载
cocos creator2.2.2都是正常的
例如  import { makeMap } from "@vue/shared";

### JavaScript output or error produced?（报错信息和调用栈）

load script [@vue/shared] failed : Error: Cannot find module '@vue/shared'

**Comment by xianyinchen** [comment]
你好，经过测试2.4.5版本可以正常运行，网页预览和发布网页版本均正常运行，请自行验证下。
