### ISSUE TITLE
How to run cocos-creator engine locally

### ISSUE THREAD

**Issue by sanyaade-teachings** [cocos/cocos-engine#747]
Hi there,

I followed the direction on this github engine repository

I was able to build the engine but I do not how to run the server -->  (Start a http server in cloned project folder). Please tell me which command to use? I am on Windows 7, 32BIT

I have tried all possible node  XXXX.js  I could think off
Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by jareguo** [comment]
Hi, you can install express by running `npm install express`, then `node test/qunit/server.js` or `node test/visual-tests/server.js`

**Comment by sanyaade-buildtools** [comment]
Many thanks for your response.
It works! 
Please can you update the readme.md to include those step for the benefit of others.

**Comment by jareguo** [comment]
Well, PR submitted
