### ISSUE TITLE
cc.EventTarget 的 once方法, 参数要求过于严格了, 在TS里使用非常不方便

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7474]
once(type: string, callback: (arg1?: any, arg2?: any, arg3?: any, arg4?: any, arg5?: any) => void, target?: any): void;

而 on() off()  中的 callback 用的就是  `callback?: Function` 

希望 once也能用更通用的 Function

**Comment by yeshao2069** [comment]
感谢反馈，这个需求已经同步给引擎组。
另外，我看了一下，callback里面的参数是可选的，这个应该使用和on off 一样的把？
