### ISSUE TITLE
cc.game.groupList 属性没有暴露. 导致我自己要取groupIndex时 TS报错

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7477]
create.d.ts 里,  cc.game.groupList 属性没有暴露. 导致我自己要取groupIndex时 TS报错

**Comment by finscn** [comment]
补充一下, 希望能提供一个 根据名字获得 groupIndex 的api.  现在只有 获得node groupIndex的api

![image](https://user-images.githubusercontent.com/288367/94760007-fb0f5180-03d3-11eb-97b7-b23d56376ea9.png)

希望能提供一个全局的 直接根据name获得 groupIndex  以及 根据index获得 groupName 的api

**Comment by yeshao2069** [comment]
感谢反馈，你的需求已经提交给引擎组，谢谢。
