### ISSUE TITLE
Lock/Unlock screen then audio clip finish unexpectedly in WebView on Vivo/OPPO! 在Vivo和OPPO设备上锁屏并解锁会导致H5游戏的音频意外结束！

### ISSUE THREAD

**Issue by GeneralWar** [cocos/cocos-engine#7499]
### Creator version?（版本号）
2.4.2

### Affected platform?（受影响的平台）

WebMobile （Vivo/OPPO）

### How to reproduce?（如何重现）
通过WebView加载游戏，循环播放背景音乐，不断锁屏解锁，极大概率（几乎百分百）导致音频`回调函数被触发`，但是音频`并没有结束！！！`
断点调试发现，这个回调被触发了，但是音频仍然在继续播放！因为此时Cocos已经将这个音频从管理逻辑中移除了，所以即使调用cc.audioEngine.stopAll()也无法中止播放！
![image](https://user-images.githubusercontent.com/37786563/95652921-26f2ab80-0b27-11eb-854d-e641b42e006b.png)

### JavaScript output or error produced?（报错信息和调用栈）

无任何报错！

**Comment by GeneralWar** [comment]
设备信息
![image](https://user-images.githubusercontent.com/37786563/95653081-5eae2300-0b28-11eb-98ee-a8ac8049cfea.png)

**Comment by OnlyKoei** [comment]
#8363 
试试这个

**Comment by OnlyKoei** [comment]
由于你这边长期没回复，暂时关闭 issue，如果后续有问题，可以继续反馈。
