### ISSUE TITLE
希望 cc.size() 可以支持无参数创建.  类似 cc.rect()  , cc.v2(), cc.v3() 

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7517]
### Creator version?（版本号）
2.4.3 

### Affected platform?（受影响的平台）
全平台 , ts开发环境

### How to reproduce?（如何重现）

目前 cc.size 必须要用至少一个参数才能创建.
希望提供类似 cc.rect 那种, 不写参数 默认就用0

**Comment by finscn** [comment]
我看代码好像是支持 不传参的. 但是 d.ts里没有把 参数设置成可选

**Comment by yeshao2069** [comment]
感谢反馈，该需求已经反馈给相关负责人。
