### ISSUE TITLE
2.4.3 版本 Scrollview 组件切换node.active 后, 滚动offset 重置.

### ISSUE THREAD

**Issue by andrewlu1** [cocos/cocos-engine#7569]
### Creator version?（版本号）
2.4.3
### Affected platform?（受影响的平台）

所有平台
### How to reproduce?（如何重现）
 1. 界面放置ScrollView
 2. Scrollview滚动到某一位置
 3. 代码设置ScrollView 节点 active=false
 4. 代码设置ScrollView 节点 active=true.
 5. 出现问题: Scrollview 自动回滚到顶部, 期望停留在上次滚动位置.

**Comment by OnlyKoei** [comment]
未能复现，方便提供个demo??

**Comment by OnlyKoei** [comment]
用户长时间未回复，暂时关闭。
