### ISSUE TITLE
Bug in helmet example

### ISSUE THREAD

**Issue by Woggl** [cocos/cocos-engine#7574]
### Creator version?（版本号）
3.0.0-tech-preview

### Affected platform?（受影响的平台）

All?

### How to reproduce?（如何重现）
The helmet example in cocos-creator/example-3d throws an error. In the exposure.ts script, you need to replace renderer.Ambient -> renderer.scene.Ambient
renderer.Camera -> renderer.scene.Camera
scene.renderScene.ambient -> director.root.pipeline.ambient

**Comment by xianyinchen** [comment]
Thanks for the feedback, the problem has been submitted to the engine group.
