### ISSUE TITLE
iPad OS14下web有严重性能问题

### ISSUE THREAD

**Issue by yue19870813** [cocos/cocos-engine#7599]
![image](https://user-images.githubusercontent.com/1831052/97169327-d9339f80-17c4-11eb-8de6-c23f8d823878.png)

### Creator version? 
all

### Affected platform?（受影响的平台）
iPad OS14下web

### How to reproduce?（如何重现）
必现

**Comment by yeshao2069** [comment]
相关  https://forum.cocos.org/t/ipad-ios14/99474/4

**Comment by zhefengzhang** [comment]
修复 pr：https://github.com/cocos-creator/engine/pull/7746/files。    已合并到 2.4.4 版本。
