### ISSUE TITLE
Creator2.4.3存储本地数据是否有bug?

### ISSUE THREAD

**Issue by sonic-github** [cocos/cocos-engine#7618]
### Creator version?（版本号）
2.4.3

### Affected platform?（受影响的平台）
 Windows Editor

### How to reproduce?（如何重现）
启动编辑器,模拟器执行任意代码

### JavaScript output or error produced?（报错信息和调用栈）

编辑器打开时就报错,执行任何程序都会出错,不需要特定程序:
Simulator: D/jswrapper (134): JS: Read json failed: path: D:\CocosDashboard_1.0.10\resources\.editors\Creator\2.4.3\resources\cocos2d-x\simulator\win32/gamecaches/cacheList.json message: Unexpected end of JSON input
cacheList.json 文件内容如下:
{"files":{},"version":"1.1"}

**Comment by yeah2569** [comment]
我也遇到了，浏览器没问题，win32模拟器有问题

**Comment by OnlyKoei** [comment]
能提供一下demo？或者具体的重现步骤。测试无法复现

**Comment by tkjune** [comment]
2.4.4，Mac 版，同样遇到。
Read json failed: path: /Applications/CocosCreator/Creator/2.4.4/CocosCreator.app/Contents/Resources/cocos2d-x/simulator/mac/Simulator.app/Contents/Resources/gamecaches/cacheList.json message: Unexpected end of JSON input
文件内容
{
  "files": {
  },
  "version": "1.1"
}
删除此文件后会自动重新创建，提示同样错误。

**Comment by yeshao2069** [comment]
感谢反馈，这边做了一个简单的测试，并不会出现上诉问题。此单先关闭, 若还有疑问，可以重启工单并告知具体的复现方式以及提供可以测试的demo,谢谢。

测试版本: CocosCreator 2.4.3
测试电脑系统: win10
测试代码:
```
    @property(cc.Label)
    label: cc.Label = null;

    start () {
        cc.sys.localStorage.setItem("GOLD", 100);

        let a = cc.sys.localStorage.getItem("GOLD");

        this.label.string = a;
    }
```

测试环境：   win10的  creator编辑器上的模拟器   运行OK
![38FD0CB603A622D5454216A583A37EBA](https://user-images.githubusercontent.com/14273437/123076164-72e24800-d44b-11eb-87bb-ec6fb88a6b40.png)

测试环境： 发布成window包，运行OK
![99A6E70339885BD3A4BC3A9CD3BA2124](https://user-images.githubusercontent.com/14273437/123076144-6e1d9400-d44b-11eb-8eb7-8db5dfbc40a2.png)
测试包：
[test243.zip](https://github.com/cocos-creator/engine/files/6700815/test243.zip)
