### ISSUE TITLE
cc.assetManager.loadRemote 中设置 options.maxRetryCount = 0 无效

### ISSUE THREAD

**Issue by insraq** [cocos/cocos-engine#7688]
https://github.com/cocos-creator/engine/blob/7ed46c17ef4abf3b7516c0339c07bb13fda9ac27/cocos2d/core/asset-manager/downloader.js#L474

是这一行的问题，如果传入参数 `options.maxRetryCount = 0`，按照文档，应该是“下载失败时会立即返回错误”。然而这一行会导致采用全局的 maxConcurrency。应该这样写会是正确的：

```
var maxConcurrency = typeof options.maxConcurrency === "number" ? options.maxConcurrency : this.maxConcurrency;
```

**Comment by SantyWang** [comment]
感谢，我们会修改下
