### ISSUE TITLE
cocos creator 2.4.3 字体使用自定义TTF， 开启CHAR模式app版本无法合并渲染， 2.3.4可以合并。

### ISSUE THREAD

**Issue by lsx1994** [cocos/cocos-engine#7694]
如题， 2.4.3 只有H5能合并渲染， app和windows模拟器都不能合并。
2.3.4以及2.1.4 都可以正常合并DrawCall。

**Comment by OnlyKoei** [comment]
你好，这是由于原生实际上是使用了 C++ 的实现. 新的实现优化的大文本的渲染速度,暂未支持合批.
如果你的文本内容较小, 可以采用 非charmode 模式.

**Comment by OnlyKoei** [comment]
实在需要，可以参考：https://forum.cocos.org/t/topic/99737/6
