### ISSUE TITLE
2.4.3 audioengine  bug

### ISSUE THREAD

**Issue by parvparv** [cocos/cocos-engine#7701]
### Creator version?（版本号）
 2.4.3   以及之前的版本一直都有
 
### How to reproduce?（如何重现）
 
音乐播放时   
id=  cc.audioEngine.play(clip, false, 0.5)
然后  在同一贞   执行
	cc.audioEngine.pause(id);
	 cc.audioEngine.resume(id);
就会导致  
音乐还在播放  
引擎直接调用 
setFinishCallback
同时
 cc.audioEngine.getState(id);
cc.audioEngine.getCurrentTime(id); 
所获取的 数值  也是 音乐播放完  才应该有的数值

 

论坛里说可能是  暂停 恢复时  对end事件进行解绑和绑定 造成的
https://forum.cocos.org/t/bug-setfinishcallback/93135

不论什么原因 ，。。。  
恳请请修复bug

**Comment by parvparv** [comment]
dingqi

**Comment by OnlyKoei** [comment]
文件路径：\resources\engine\cocos2d\audio\CCAudio.js
照下图这样修改；
![image](https://user-images.githubusercontent.com/40415168/111142275-71d58b00-85bf-11eb-95a9-23a4a95cd88a.png)

**Comment by sushanhong** [comment]
2.4.5-rc3版本验证，vivo平台播放音乐时，锁屏解锁后，音频还是正常播放
