### ISSUE TITLE
命令行和构建面板构建出来的cocos2d-js-min.js文件的md5值不一致

### ISSUE THREAD

**Issue by JeffGoing** [cocos/cocos-engine#7722]
### Creator version?（版本号）
2.4.3

### Affected platform?（受影响的平台）

web-mobile
### How to reproduce?（如何重现）
1、勾上md5 cache
2、对比命令行以及构建面板构建出来cocos2d-js-min.js文件的md5值

### Demo project?（demo 项目）

示例的helloworld工程

**Comment by yeshao2069** [comment]
验证了一下，在2.4.5版本上也有这个问题。打包的时候，只有cocos2d-js-min.js这个的md5不一样。

**Comment by yeshao2069** [comment]
感谢反馈。
经过验证，这个问题在2.4.6版本上修复了，建议你升级到2.4.6版本试试。

**Comment by JeffGoing** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月26日(周一) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cocos-creator/engine] 命令行和构建面板构建出来的cocos2d-js-min.js文件的md5值不一致 (#7722)




 
感谢反馈。
 经过验证，这个问题在2.4.6版本上修复了，建议你升级到2.4.6版本试试。

**Comment by loohoo** [comment]
> 
> 
> 感谢反馈。 经过验证，这个问题在2.4.6版本上修复了，建议你升级到2.4.6版本试试。

看看我[这个](https://github.com/cocos-creator/engine/issues/9459).
请问你是怎么验证的? 如果按照我的方法重新不出来, 我录视频给你看.
