### ISSUE TITLE
websocket 无法连接

### ISSUE THREAD

**Issue by jiangjiali** [cocos/cocos-engine#7745]
### Creator version?
2.4.3

### Affected platform?
Android / Windows Editor

### How to reproduce?（如何重现）
new Websocket(url)
必现

**Comment by xianyinchen** [comment]
你好，你提供的信息有限，我们这边猜测可能是证书验证问题，可以自己手动传入。

证书获取参考帖子
 https://forum.cocos.org/t/websocket-ssl/60024/6

证书传入示例代码
``` typescript
//@ts-ignore
this.socket = new WebSocket(WS_HOST, null, cc.url.raw('resources/cacert.pem'))
```

**Comment by jiangjiali** [comment]
好呢。收到。
