### ISSUE TITLE
2.4.3从另一个项目导出3d资源，然后另一个工程导入资源会触发一堆警告【CC_USE_SHADOW_MAP】

### ISSUE THREAD

**Issue by shangdibaozi** [cocos/cocos-engine#7790]
![image](https://user-images.githubusercontent.com/6499838/99181544-22469600-276a-11eb-9c43-fcc1678514a3.png)

**Comment by OnlyKoei** [comment]
你好，简单测试，并未复现该情况，测试步骤：
项目A：
创建一个3d 球体预制，导出预制；

项目B：
导入该预制，正常，没有警告；

测试版本：2.4.3，2.4.6
方便的话提供个简单的demo, 以便排查；

**Comment by shangdibaozi** [comment]
我已经从上家公式离职了。无法提供相关资源了。
