### ISSUE TITLE
编辑器console栏出现异常警告

### ISSUE THREAD

**Issue by godnotking** [cocos/cocos-engine#7825]
### Creator version?（版本号）
2.3.4+

### Affected platform?（受影响的平台）

Windows Editor
### How to reproduce?（如何重现）
定义一个`childCls`继承自一个`parentCls`,
`childCls`定义了一个`unRewrite`的方法，`parentCls`没有这个方法，但是`unRewrite`的代码中有一段**注释** `this._super()`,
这种情况下，编辑器会console栏目会出现一个警告：
`this._super declared in 'unRewrite' but no super method defined`

去掉注释就没有这个警告了，猜测`CCClass.js`文件中`boundSuperCalls`方法中`SuperCallRegStrict.test(func)`的func没有去掉注释后再进行正则校验，造成了注释也会被当作代码进行验证，导致这个警告出现。

**Comment by xianyinchen** [comment]
感谢反馈，编辑器确实是这样处理的，这个问题触发的是警告，所以建议使用的时候注意下，采取删除 this._super() 而不用注释的方式。
