### ISSUE TITLE
【Native】纹理勾选Alpha预乘后混合错误

### ISSUE THREAD

**Issue by caogtaa** [cocos/cocos-engine#7830]
### Creator version?（版本号）
2.4.2，2.4.3均有问题

### Affected platform?（受影响的平台）

Android & Simulator

### How to reproduce?（如何重现）
参考Demo
1. 纹理勾选Alpha预乘（Premultiply Alpha），赋给**节点A** 的Sprite组件。Sprite.srcBlendFactor = ONE。（这么做的原因是为了消除图片黑边）
2. 新建一个**节点B**，将**节点A** 作为其子节点
3. 连续修改**节点B** 的opacity属性

预期：图片根据给定的opacity值变换透明度
实际：图片变黑
![image](https://user-images.githubusercontent.com/4058573/99676173-20a30800-2ab3-11eb-8a4a-afa79413dcff.png)

重新设定节点A的 color属性可以使其恢复，

### Demo project?（demo 项目）

[PremultipliedAlphaBlendError.zip](https://github.com/cocos-creator/engine/files/5567187/PremultipliedAlphaBlendError.zip)

**Comment by caogtaa** [comment]
[问题定位]
Assembler.cpp  updateOpacity()方法
在预乘模式下会直接修改renderData里的rgb值，乘以透明度。
如果父节点的透明度修改了，子节点updateOpacity()会被再次调用，但是renderData里的值没有被重置，而是基于上一次预乘后的结果再次预乘，导致rgb值越来越小，所以渲染出来就成黑色了。代码位置在下图:

![image](https://user-images.githubusercontent.com/4058573/100330082-73c41000-3009-11eb-9454-763e8cdccef8.png)

[解决办法]
每次预乘都应该基于节点的原始颜色rgb值。
所以，每次节点修改颜色时可以在Assembler里缓存节点颜色，在updateOpacity()中使用。
个人修改代码PR如下，由于感觉影响面较大，所以就不往官方库里PR了，希望下个版本中能出官方的fix。

[jsb-adapter]
https://github.com/caogtaa/jsb-adapter/pull/1

[cocos2d-x]
https://github.com/caogtaa/cocos2d-x-lite/pull/1

**Comment by drelaptop** [comment]
问题在 2.4.4 依旧存在。采用“纹理勾选Alpha预乘+ Sprite.srcBlendFactor = ONE”方法消除黑边的，在 Android 就有这个问题。是否考虑在下个版本中合并到官方库中呢？ @jareguo

**Comment by caogtaa** [comment]
预乘模式用起来太麻烦，还容易遗漏。
现在把所有图都离线做了扩边，用1/100的透明度 & 边缘邻近色做描边，可同时解决原生和小游戏黑边问题。

**Comment by OnlyKoei** [comment]
已经建立内部issue，对其进行跟踪修复，这边 issue 先关闭了。

**Comment by Greg1129** [comment]
使用这个PR可以解决
https://github.com/cocos-creator/engine-native/pull/4121
