### ISSUE TITLE
音频模块没有监听 'canplaythrough' 事件, 导致判断一个音频到底能否正确播放 非常有难度.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#7878]
在 web环境, audio 有一个 canplaythrough 事件,  webaudio也有类似的回调 (context.decodeAudioData 可以间接实现该功能).

微信小游戏也有一个  InnerAudioContext.onCanplay 事件.
(Native平台我就不知道了)

但是 cocos内部无视了这些事件回调. 
希望cocos内部能够早日支持类似回调.

**Comment by yeshao2069** [comment]
感谢反馈，已经将需求提交给相关负责人。

**Comment by PPpro** [comment]
canplaythrough 这个事件的支持意义不大了，仅仅是 web 平台 DOM Audio 的一个特性，支持了反而降低 DOM Audio 流式播放的体验，而且 DOM Audio 在 3.x 已经是接近废弃状态，load 事件倒是在各个浏览器上验证过，canplaythrough 事件不能确定有没有兼容性问题，暂时不考虑做支持了

感谢反馈
