### ISSUE TITLE
【Native】RichText + TTF字体CHAR模式在Native渲染有黑边

### ISSUE THREAD

**Issue by caogtaa** [cocos/cocos-engine#7880]
### Creator version?（版本号）
2.4.3

### Affected platform?（受影响的平台）

Android

### How to reproduce?（如何重现）
RichText组件，使用TTF字体，在Android环境运行（有Demo工程）
![image](https://user-images.githubusercontent.com/4058573/100536483-d90f3f80-325b-11eb-8e09-00123ebb53a2.png)

### Demo project?（demo 项目）
[TestNativeTTF.zip](https://github.com/cocos-creator/engine/files/5611842/TestNativeTTF.zip)

### 关于NONE模式和BITMAP模式
NONE模式DC太高
BITMAP模式在多次修改RichText内容时出现渲染错误的情况（残留了上一次渲染的图片，这是另外一个bug）
**目前已经拿RichText没辙了，只能先将就用NONE模式。请求引擎组大大的支持，修下这个问题！**

**Comment by xianyinchen** [comment]
你可以原生层canvas绘制的默认的预乘关闭来解决这个问题
<img width="1108" alt="WeChat349c86fc8eec849554a153ec2761fbdf" src="https://user-images.githubusercontent.com/8321365/126437014-54bf386f-fab4-439b-bb5f-74be707db48f.png">
