### ISSUE TITLE
"This archive is corrupted" on Cocos Dashboard Installer

### ISSUE THREAD

**Issue by yepMad** [cocos/cocos-engine#7885]
I downloaded version 1.0.11 of the Cocos Dashboard directly from the Cocos website, however, as soon as I click to open the installer it gives a Windows error:

![Screenshot](https://user-images.githubusercontent.com/22564368/100580091-17404980-32c4-11eb-9ffa-e5c024e46602.png)

### Creator version?（版本号）
1.0.11

### Affected platform?（受影响的平台）
Windows

### How to reproduce?（如何重现）
Download any version and try install it.

**Comment by xwc2021** [comment]
me too

**Comment by tulalan** [comment]
me too, help me please

**Comment by yepMad** [comment]
The Cocos team is answering me on Twitter. I'll update here if you get answers, anyway, here it is: https://twitter.com/madplz/status/1333265872081874944

**Comment by Ryuzeke** [comment]
i have the same problem

**Comment by VisualSJ** [comment]
Can't you try to download it again?
It looks like a file is corrupted.

What's your IP address? We can check whether the server nearest to you is working

**Comment by VisualSJ** [comment]
What is the size of .exe file?

**Comment by CocosLuke** [comment]
Please try downloading again. We may have fixed the issue.

**Comment by xwc2021** [comment]
It is work now . Thank you
