### ISSUE TITLE
Get loaded scene name

### ISSUE THREAD

**Issue by ozergul** [cocos/cocos-engine#790]
Hi, is this possible in cocos creator. I tried all ways to get loaded scene name but I could not achieve this problem.

`cc.director.getScene()` returns `cc.Scene`but its "**name**" property is empty.

**Comment by ozergul** [comment]
I achieved the problem with a few line code

``` javascript
    getSceneName: function() {
        //console.log(cc.game._sceneInfos)
        //console.log(cc.director._scene._id)
        var sceneName
        var _sceneInfos = cc.game._sceneInfos
        for (var i = 0; i < _sceneInfos.length; i++) {
            if(_sceneInfos[i].uuid == cc.director._scene._id) {
                sceneName = _sceneInfos[i].url
                sceneName = sceneName.substring(sceneName.lastIndexOf('/')+1).match(/[^\.]+/)[0]
            }

        }

        return sceneName
    }
```

**Comment by jareguo** [comment]
That is because none of the assets will have names, including scene asset.
But we could retrieve the scene name from passing-in argument in cc.Director.loadScene, @knoxHuang Will you try it?

**Comment by ozergul** [comment]
@jareguo I think, it will be good to get directly scene name as _scene file name_

**Comment by jareguo** [comment]
done, thx @ozergul  & @knoxHuang

**Comment by VYuLinLin** [comment]
请问是在哪个版本解决的，目前1.9.3版本获取场景名称，还是有为空的情况

**Comment by jareguo** [comment]
1.1…… 请问是如何重现的？我们目前测不出来

**Comment by VYuLinLin** [comment]
在 __preload 生命周期里面 通过cc.director.getScene() 获取的场景有时 name 会为空，不是必现，暂时也未定位到具体原因。
