### ISSUE TITLE
Missing Facebook Instant Games Option In the Build panel , Cocos Creator 3.0.0preview.1

### ISSUE THREAD

**Issue by MrZak-dev** [cocos/cocos-engine#7902]
### Creator version?
Cocos Creator 3.0.0 Preview.1

### Affected platform?（受影响的平台）
Facebook Instant Games

### How to reproduce?（如何重现）
I couldn't find Facebook Instant Games as an option in the Build Panel 

### Demo project?（demo 项目）

Open Any new project with Cocos Creator 3.0.0preview , Project > Build

**Comment by jareguo** [comment]
Sorry, FBIG will be removed in 3.0. You can just publish to web directly, and change the html file to adapt it.

**Comment by MrZak-dev** [comment]
That will require the user to integrate the `FBInstant.setLoadingProgress(progress);` alongside other initializing functions in the  main script , and not only Integrating the FBIG SDK .

**Comment by faizanophobia** [comment]
> setLoadingProgress

I tried implementing the same but it's unable to locate the .fire files under settings. Did u face anything similar while publishing on FBIG? Unable to figure out here!!

**Comment by MrZak-dev** [comment]
https://github.com/cocos-creator/engine/issues/8262
