### ISSUE TITLE
IOS 来电结束后不会触发cc.game.EVENT_SHOW

### ISSUE THREAD

**Issue by HtyAe** [cocos/cocos-engine#7922]
### Affected platform?（受影响的平台）
 IOS 微信小程序

**Comment by yeshao2069** [comment]
相关问题issue   https://github.com/cocos-creator/engine/issues/1377

**Comment by xianyinchen** [comment]
2.4.4 在 iOS14.4 上测试问题没有复现

**Comment by qq762278029** [comment]
2.4.4 在 iOS14.4 上
问题复现，一直没找到解决方案

**Comment by qq762278029** [comment]
[官方论坛相关帖子](https://forum.cocos.org/t/topic/106503)

**Comment by yeshao2069** [comment]
https://github.com/cocos-creator/engine-native/pull/3565  这个修复PR试试

**Comment by yeshao2069** [comment]
你好，你可以参考这个修复 pr 手动修复一下你的引擎，pr 已经合并到 2.4.6 版本，即将合并到 3.3 版本。
cocos-creator/engine-native#3565
定制引擎的流程参考：
https://docs.cocos.com/creator/3.1/manual/zh/advanced-topics/engine-customization.html?h=%E5%AE%9A%E5%88%B6


也可以升级引擎到2.4.6版本。感谢反馈。
