### ISSUE TITLE
MaterialVariant property overriding issue when Mat4 contains Float64Array underhood.

### ISSUE THREAD

**Issue by ymiroshnyk** [cocos/cocos-engine#7933]
### Creator version?（版本号）
2.4.3

### Affected platform?（受影响的平台）

Windows Editor, Web

File: effect-base.ts
Function: _createPassProp()
There is a check for Float32Array as a property type.

Expected behavior:
It should also handle Float64Array property type, as Mat4.m can be Float64Array.

Actual result:
MaterialVariant doesn't work well with matrices properties when Mat4.m type is Float64Array (which is chosed by the engine).

**Comment by xianyinchen** [comment]
if you publish to web-mobile platform, it work OK. but Native will fail, because native code use float type.

**Comment by xianyinchen** [comment]
this issue has fixed, refer this PR.
https://github.com/cocos-creator/engine/pull/8073
