### ISSUE TITLE
开放数据域和cc.Widget

### ISSUE THREAD

**Issue by IceJacool** [cocos/cocos-engine#7986]
URL：https://github.com/cocos-creator/engine/blob/master/cocos2d/core/components/SubContextView.js

1：creator2.4.3
2:：使用cc.Widget时，由于node的最终width和在onLoad内获取带的width大小不一致，导致在onLoad里设置sharedCanvas.width不对

**Comment by zhefengzhang** [comment]
请提供一下复现 demo，或详细描述一下复现步骤。
上面的链接已经失效了。

**Comment by IceJacool** [comment]
URL：https://github.com/cocos-creator/engine/blob/v2.4.5/cocos2d/core/components/SubContextView.js

1：creator2.4.5
2：源码onLoad 里调用reset,reset里sharedCanvas.width = this.node.width;sharedCanvas.height = this.node.height;但因为this.node使用了cc.Widget,cc.Widget是在node的onLoad执行完后才调整当前节点的坐标和宽高，所以导致开放数据域的sharedCanvas.width或者sharedCanvas.height大小不匹配

**Comment by zhefengzhang** [comment]
你是否能重现这个问题？
我看到这边代码里也有重新设置子域画布大小的回调：

![图片](https://user-images.githubusercontent.com/35944775/112974827-797f5d00-9185-11eb-9543-9accd5260b9c.png)

https://github.com/cocos-creator/engine/blob/e361a2e93351aacda485d2038abd4eba2998a298/cocos2d/core/components/SubContextView.js#L195

是否也会导致你说的问题？

**Comment by IceJacool** [comment]
> 你是否能重现这个问题？
> 我看到这边代码里也有重新设置子域画布大小的回调：
> 
> ![图片](https://user-images.githubusercontent.com/35944775/112974827-797f5d00-9185-11eb-9543-9accd5260b9c.png)
> 
> https://github.com/cocos-creator/engine/blob/e361a2e93351aacda485d2038abd4eba2998a298/cocos2d/core/components/SubContextView.js#L195
> 
> 是否也会导致你说的问题？
还是会出现，是不是因为子域没有监听updateSubContextViewport内的viewport消息

**Comment by IceJacool** [comment]
还是会出现，是不是因为子域没有监听updateSubContextViewport内的viewport消息

**Comment by zhefengzhang** [comment]
我这边弄个 demo 测试下,要是没有复现的话,在让你帮我修改下.

**Comment by zhefengzhang** [comment]
这是我的测试demo：https://gitee.com/mirrors_cocos-creator/OpenDataContext_TestCase ，请你下载这个 demo 之后尝试复现你的问题。如果复现了之后，你可以上传上来或发到我的邮箱：337031709@qq.com。
