### ISSUE TITLE
Motion Streak with Follow action doesn’t work

### ISSUE THREAD

**Issue by ngocnv371** [cocos/cocos-engine#801]
I cloned the pool-physics-demo and change a bit to add a MotionStreak to the cue and have the scene follow it. But the MotionStreak won't render anything at runtime. If I use the mouse to move it around in the editor it will show properly (with Preview). And if I add the MotionStreak to other ball, it will show as normal. No, I take that back. It will show the streak, not when the ball move, but when the scene move (when the ball remains static).

What should I do to get it works?

![image](https://cloud.githubusercontent.com/assets/1485213/16078925/a0ba6526-332b-11e6-8e05-a636da129a5e.png)

In the picture, when I click, the cue jump up (no streak). The other ball stay static (but has streak).

**Comment by knoxHuang** [comment]
Do you use in webgl mode ?

**Comment by knoxHuang** [comment]
Do you use in WebGL mode?

**Comment by ngocnv371** [comment]
Yes, it is in WebGL mode, my browser did not show the streak at all on Canvas mode.

**Comment by knoxHuang** [comment]
Can you give me a simple project?  I'll test to see

**Comment by ngocnv371** [comment]
I don't know to attach a zipped source, so I put it here:
https://github.com/ngocnv371/bluewalker/commit/47406ba71b23409cf8c2a8b28934e505fc77f281

**Comment by knoxHuang** [comment]
ok, thank you

**Comment by ngocnv371** [comment]
I also notice that Follow doesn't work with collider. This piece of code is ripped from the samples, I only add the Follow action.
You could see it here, I guess it's related somehow.
https://github.com/ngocnv371/bluewalker/commit/64427453607f06292daee167f2f2250d7cc1634a

**Comment by knoxHuang** [comment]
hi, Motion Streak won't render. Because use scene follow, leading to a sphere has been the center of the scene, so trailing effect cannot be displayed.

**Comment by knoxHuang** [comment]
hi, I tested it, the current MotionSteak is rendered correctly in your project. 

I think it was caused by

``` js
  var follow = cc.follow(this.node);
  cc.director.getRunningScene().runAction(follow);
```

You may need to use another way to make the camera follow the target.

Note: The `cc.director.getRunningScene()` has been deprecated,  please use `cc.director.getScene();` get scene, and the scene has been unable to run action.
