### ISSUE TITLE
Label Char 的缓存模式下 enableBold 无效

### ISSUE THREAD

**Issue by zanhaomima** [cocos/cocos-engine#8060]
label 的CacheMode 选择Char，enable Bold 无效，字体无法加粗，希望可以加粗，非常影响整体项目美观，谢谢

### Creator version?（版本号）
2.4.3

### How to reproduce?（如何重现）
label 的CacheMode 选择Char，enable Bold 无效，字体无法加粗

**Comment by zhefengzhang** [comment]
该模式并不支持加粗效果.
