### ISSUE TITLE
Particle System 3D is causing crash on desktop simulator and lag or sometimes freeze on mobile device

### ISSUE THREAD

**Issue by chung-nguyen** [cocos/cocos-engine#8099]
### Creator version?（版本号）
2.4.3

### Affected platform?（受影响的平台）
Happened but not limited to Android, Windows Simulator

### How to reproduce?（如何重现）
Create complex 3D particle systems with Capacity about 1000. More particles will crash sooner.

My game is a top down shooting game. I am actually porting Particle effects from Unity 3D assets. Whenever there are particle components with Capacity 1000 being created, the game crashes on Windows Simulator or mobile device.

It is weird that crashes on Windows Simulator happens more frequently and no Javascript log given, so I think it is definitely native engine problem.

On Android devices, the game lags whenever such Particle Systems are created, and will lead to a freeze or crash.

No such crashes were seen on Browser!

### JavaScript output or error produced?（报错信息和调用栈）
There is no Javascript output when crash, but try forcing Simulator.exe to output crash message will give `nvoglv32.dll Access violation reading location 0x00000000` (running on Geforce 1660 Super)

### Demo project?（demo 项目）
I can provide a demo project if required.

**Comment by zhefengzhang** [comment]
Please give me a demo.

**Comment by zhefengzhang** [comment]
User did not reply for a long time, temporarily closed
