### ISSUE TITLE
destroy时MaterialInstance为空

### ISSUE THREAD

**Issue by lyyyyf111** [cocos/cocos-engine#8110]
### Creator version?（版本号）
V3.0.0-Preview.1

### How to reproduce?（如何重现）
sprite!.customMaterial = material1;
const mat = sprite!.material;
mat!.setProperty('width', 100);
sprite!.customMaterial = material2;
sprite!.node.destroy();         //报错

### JavaScript output or error produced?（报错信息和调用栈）

debug.ts:98 You are trying to destroy a object twice or more.
error @ debug.ts:98
errorID @ debug.ts:292
_destroyImmediate @ object.ts:319
_onPreDestroyBase @ base-node.ts:1364
_onPreDestroy @ base-node.ts:1253
_destroyImmediate @ object.ts:326
_deferredDestroy @ object.ts:169
mainLoop @ director.ts:909
callback @ game.ts:733
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
index.js:1 ErrorEvent {isTrusted: true, message: "Uncaught TypeError: Cannot read property 'destroy' of null", filename: "http://localhost:7456/scripting/engine/bundled/index.js", lineno: 120254, colno: 42, …}
d @ index.js:1
ui-renderable.ts:403 Uncaught TypeError: Cannot read property 'destroy' of null
    at Sprite.onDestroy (ui-renderable.ts:403)
    at Sprite.onDestroy (sprite.ts:529)
    at NodeActivator.destroyComp (node-activator.ts:274)
    at Sprite._onPreDestroy (component.ts:386)
    at Sprite._destroyImmediate (object.ts:326)
    at Node._onPreDestroyBase (base-node.ts:1364)
    at Node._onPreDestroy (base-node.ts:1253)
    at Node._destroyImmediate (object.ts:326)
    at Function._deferredDestroy (object.ts:169)
    at Director.mainLoop (director.ts:909)
onDestroy @ ui-renderable.ts:403
onDestroy @ sprite.ts:529
destroyComp @ node-activator.ts:274
_onPreDestroy @ component.ts:386
_destroyImmediate @ object.ts:326
_onPreDestroyBase @ base-node.ts:1364
_onPreDestroy @ base-node.ts:1253
_destroyImmediate @ object.ts:326
_deferredDestroy @ object.ts:169
mainLoop @ director.ts:909
callback @ game.ts:733
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726
requestAnimationFrame (async)
callback @ game.ts:726

### Demo project?（demo 项目）

![图片](https://user-images.githubusercontent.com/35019983/104086101-c0993880-528f-11eb-99c2-433e8a42c3ff.png)
![图片](https://user-images.githubusercontent.com/35019983/104086117-e1fa2480-528f-11eb-989d-e124f461ad72.png)

**Comment by zhefengzhang** [comment]
问题已经复现,我这边看下原因.

**Comment by zhefengzhang** [comment]
![image](https://user-images.githubusercontent.com/35944775/113266181-8a57dc00-9307-11eb-8c76-d05979aab96d.png)
修改此处为红框中的代码即可。

**Comment by pandamicro** [comment]
之前的修改方式有问题，materials 和 materialInstances 数组是一一对应的，不能做 splice，底层置空是正常的操作，问题在于 renderable-2d 的 onDestroy 没有判断 materialInstance 是否存在就调用了 destroy，修复即可

**Comment by zhefengzhang** [comment]
pr 已修改。
