### ISSUE TITLE
tween一个object对象，属性值不会改变

### ISSUE THREAD

**Issue by bobby169** [cocos/cocos-engine#8165]
### Creator version?（版本号）
3.0

### Affected platform?（受影响的平台）
Mac Editor / Windows Editor / Web / iOS / Android / Simulator 

### How to reproduce?（如何重现）
```js
        let obj = { a: 0 }
        tween(obj)
            .to(1, { a: 100 }, {
                onUpdate(target: object, ratio: number) {
                    console.info(obj.a) // 还是100
                }
            })
            .call(() => {
                console.info(obj) // 还是100
            })
            .start()
```

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/110312483-172cb400-8040-11eb-9bc8-29faa86e3c9c.png)
这是测试情况。是正常的

**Comment by bobby169** [comment]
fixed
