### ISSUE TITLE
3.0建议Tween.hide(time).show(time)

### ISSUE THREAD

**Issue by bobby169** [cocos/cocos-engine#8176]
### Creator version?（版本号）
3.0

### 3.0的tween很难对节点实现fadeIn或fadeOut效果，并自己设置time时间，建议添加time参数

tween(this.bg).hide(500).start()

tween(this.bg).show(500).start()

**Comment by iKest** [comment]
the node does not have a default opacity component, it must be added manually

**Comment by yeshao2069** [comment]
感谢反馈，短时间内，可能暂时不会对tween扩展tween.show和tween.hide。
我这边封装了一个 CCUtils类，你可以试一下。tween来实现。
目前暂时封装了 cc.fadeIn、cc.fadeOut、cc.show、cc.hide。 
https://gitee.com/yeshao2069/cocos-creator-how-to-use/blob/v3.0.0/Tween/CCUtilsDemo/assets/ccUtils.ts

**Comment by jadestrong** [comment]
> 感谢反馈，短时间内，可能暂时不会对tween扩展tween.show和tween.hide。
> 我这边封装了一个 CCUtils类，你可以试一下。tween来实现。
> 目前暂时封装了 cc.fadeIn、cc.fadeOut、cc.show、cc.hide。
> https://gitee.com/yeshao2069/cocos-creator-how-to-use/blob/v3.0.0/Tween/CCUtilsDemo/assets/ccUtils.ts

这个工具类可以和 tween 结合起来一起用吗，比如：
```js
            this.node.runAction(
                cc.sequence(
                    cc.delayTime(10),
                    cc.fadeOut(0.1),
                    cc.callFunc(function() {
                        this.node.active = !1;
                    }, this)
                )
            );
```
能转换成3的用法吗：

```js
            tween(this.node)
            .delay(10)
            // .to(0.1 , { opacity: 255 })
            .call(() => {
                this.node.active = false;
            });
```

**Comment by yeshao2069** [comment]
这种写法目前不支持。因为ccutils内部就是tween实现，如果你要写成上面那种的话，你可能还需要在 call中来实现。

如

tween(node).delay(10).call(
()=>{
  CCUtils.fadeOut(node, 0.1)
});  这样子
