### ISSUE TITLE
[bug] 2.4.3 两层Mask + camera 导致子节点不显示

### ISSUE THREAD

**Issue by endless3000** [cocos/cocos-engine#8208]
### Creator version?（版本号）
2.4.3

### Affected platform?（受影响的平台）

iOS Android
### How to reproduce?（如何重现）
节点A有子节点B, B有子节点C, 其中A和B上有Mask；如果C的摄像机和AB不同，则 C无法显示（此为BUG)，关掉A或B上的Mask则A可以显示；

### JavaScript output or error produced?（报错信息和调用栈）

不会出现报错
### Demo project?（demo 项目）

没有DEMO 可随便测试上面的情况

**Comment by yeshao2069** [comment]
你好，这边使用2.4.5复现你的问题，发现没有你说的这个问题。（推荐你提供你测试的demo, 便于我们复现问题）
复现方式：
使用2.4.5版本，新建a,b,c节点，a节点白色，b节点 粉色，c节点绿色。
因为sprite和mask不能挂在同一个节点上，所以在a下挂一个mask组件，b下挂一个mask组件。
设置分组a,b,c , 节点a和节点a下的mask  分组为a， 节点b和节点b下的mask  分组为b,  节点c的分组 c
![F174C45861B7F37CA458F3EFF0DE01F7](https://user-images.githubusercontent.com/14273437/123390291-53732880-d5cd-11eb-9001-e0c2f03ac034.jpg)
![C6CF160FCC5E70DD9EEC010FE2BB9D44](https://user-images.githubusercontent.com/14273437/123390299-553cec00-d5cd-11eb-88e0-98e2bb80d527.jpg)
效果图：
![CFA0E0CAC297B929513BE7A0E96F74A4](https://user-images.githubusercontent.com/14273437/123391452-a0a3ca00-d5ce-11eb-972d-911f890e1b58.jpg)
测试APK：
[NewProject_1-debug.apk.zip](https://github.com/cocos-creator/engine/files/6714546/NewProject_1-debug.apk.zip)
测试工程：
[NewProject_1.zip](https://github.com/cocos-creator/engine/files/6714548/NewProject_1.zip)
