### ISSUE TITLE
V3.0.0-Preview.1浏览器预览报错，无法正常预览

### ISSUE THREAD

**Issue by ALNY-AC** [cocos/cocos-engine#8225]
### Creator version?（版本号）
V3.0.0-Preview.1

### Affected platform?（受影响的平台）

Mac Editor / web

### How to reproduce?（如何重现）
按照流程正常新建项目，然后点击浏览器预览。

### JavaScript output or error produced?（报错信息和调用栈）

GET http://localhost:7456/scripting/engine/bundled/index.js net::ERR_ABORTED 500 (Internal Server Error)

ENOENT: no such file or directory, stat '/Applications/CocosCreator/Creator/3.0.0-Preview.1/CocosCreator.app/Contents/Resources/resources/3d/engine/bin/.cache/dev/preview/bundled/index.js.js'
 

![image](https://user-images.githubusercontent.com/20777182/106084125-ac42b000-6158-11eb-86a4-4b959d3fc37c.png)
![image](https://user-images.githubusercontent.com/20777182/106084139-b5cc1800-6158-11eb-96e8-da8f2e9afffc.png)

### Demo project?（demo 项目）

就刚新建的项目，啥都没有的情况。

**Comment by OnlyKoei** [comment]
你好，使用3.0.0正式版还会出现这种情况嘛

**Comment by OnlyKoei** [comment]
用户长时间未回复，暂时关闭。
