### ISSUE TITLE
CircleCollider2D Radius setter not work

### ISSUE THREAD

**Issue by shar0** [cocos/cocos-engine#8251]
### Creator version?（版本号）
V3.0.0-Preview.1

### Affected platform?（受影响的平台）
All / 所有

### How to reproduce?（如何重现）
``` 
collider!.radius = spriteFrame.originalSize.width / 2; 
```

### JavaScript output or error produced?（报错信息和调用栈）
No error / 无报错

### Demo project?（demo 项目）
``` typescript
start () {
    const url = "textures/sprite_" + this.index + "/spriteFrame";
    const sprite = this.getComponent(Sprite);
    const collider = this.getComponent(CircleCollider2D);
    resources.load(url, SpriteFrame, (err: any, spriteFrame) => {
        if (
            spriteFrame != null
        ) {
            sprite!.spriteFrame = spriteFrame;
            collider!.radius = spriteFrame.originalSize.width / 2; // this is not work. 这里不起作用
        }   
    });
}

```

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/112793683-4f03a600-9098-11eb-89c4-2737ce39aaf4.png)
![image](https://user-images.githubusercontent.com/40415168/112793728-604cb280-9098-11eb-97b8-86910f80a075.png)
这是3.0.0正式版测试情况，挺正常的。请用正式版再试一次，顺便检查 spriteFrame 是否正确加载，如果还有问题可继续联系我们。
也可用我截图中的代码测试。
