### ISSUE TITLE
无限报错：Sampler binding 'cc_shadowMap' at set 0 binding 2 index 0 is not bounded 

### ISSUE THREAD

**Issue by ayahua** [cocos/cocos-engine#8258]
### How to reproduce?（如何重现）
按照文档的《快速上手：制作第一个游戏》
开启阴影：在 层级管理器 中点击最顶部的 Scene 节点，然后在 属性检查器 勾选 shadows 中的 Enabled，并修改 Distance 和 Normal 属性
之后就开始在控制台无限报这个错，直到浏览器内存溢出。
### JavaScript output or error produced?（报错信息和调用栈）
index.js:sourcemap:63857 Sampler binding 'cc_shadowMap' at set 0 binding 2 index 0 is not bounded

### Demo project?（demo 项目）
按照文档的《快速上手：制作第一个游戏》

**Comment by OnlyKoei** [comment]
![image](https://user-images.githubusercontent.com/40415168/111101509-05d63100-8585-11eb-9805-09d2e564369b.png)
你好，并没有复现这个问题，是否有其他的操作

**Comment by yeshao2069** [comment]
经过测试，没有报错

Cocos Creator 版本： 3.0.0
系统版本： macOS 11.3.1
复现：  新建3.0.0项目，保存scene，然后点击最顶部的 Scene 节点，然后在 属性检查器 勾选 shadows 中的 Enabled，并修改 Distance 和 Normal 属性
结果： 没有复现  Sampler binding 'cc_shadowMap' at set 0 binding 2 index 0 is not bounded 报错。

![{473FB0AD-81E2-774C-008E-637343EEA58A}](https://user-images.githubusercontent.com/14273437/119980118-6aceee00-bfee-11eb-9503-1cf07c47d820.jpg)

测试demo
[testDemo.zip](https://github.com/cocos-creator/engine/files/6560639/testDemo.zip)


麻烦确认一下，是否是 win7的操作系统。如果是win7的系统的话，建议更换 win10的系统。
如果还有后续问题，欢迎重启issue给我们反馈，感谢反馈。
