### ISSUE TITLE
Sorry, FBIG will be removed in 3.0. You can just publish to web directly, and change the html file to adapt it.

### ISSUE THREAD

**Issue by faizanophobia** [cocos/cocos-engine#8262]
Sorry, FBIG will be removed in 3.0. You can just publish to web directly, and change the html file to adapt it.

_Originally posted by @jareguo in https://github.com/cocos-creator/engine/issues/7902#issuecomment-738528386_

But I tried adding it using the custom template mentioned in the docs, it doesn't seem to work like 2.4.3. Could you share some snippets of html changes

**Comment by MrZak-dev** [comment]
After building your project to web mobile 
1- Add this to your `<body></body>` inside your `index.html`.
```html
  <script src="https://connect.facebook.net/en_US/fbinstant.6.3.js"></script>
```
2 - Add this to your `application.js` file 

```javascript
function onGameStarted(cc, settings){
   ....
   ....
   ....
   FBInstant.initializeAsync();
   FBInstant.setLoadingProgress(100);
   FBInstant.startGameAsync();
}
```

you can customize `FBInstant.setLoadingProgress(100);` across `application.js` functions so you can get a dynamic loading from `1` to `100`

**Comment by MrZak-dev** [comment]
https://github.com/cocos-creator/engine/issues/7902

**Comment by faizanophobia** [comment]
Thank you for the reply, I found the same solution
Updating index.html & application.js with fbig function.
