### ISSUE TITLE
电脑微信平台判断错误

### ISSUE THREAD

**Issue by IceJacool** [cocos/cocos-engine#8269]
CocosCreator2.4.4

Windows wechat

windows的微信获取到的cc.sys.browserType=qqbrowser，应该为 cc.sys.browserType=wechat

错误代码：
https://github.com/cocos-creator/engine/blob/v2.4.5/cocos2d/core/platform/CCSys.js

var typeReg1 = /mqqbrowser|micromessenger|qqbrowser|sogou|qzone|liebao|maxthon|ucbs|360 
              aphone|360browser|baiduboxapp|baidubrowser|maxthon|mxbrowser|miuibrowser/i;
var typeReg2 = /qq|ucbrowser|ubrowser|edge|HuaweiBrowser/i;
var typeReg3 = /chrome|safari|firefox|trident|opera|opr\/|oupeng/i;
var browserTypes = typeReg1.exec(ua) || typeReg2.exec(ua) || typeReg3.exec(ua);

当ua中包含qqbrowser和micromessenger  时，qqbrowser的字符串会在micromessenger  之前被查询到

**Comment by OnlyKoei** [comment]
#8376
