### ISSUE TITLE
Label 包含某个表情导致整个Label 内容不显示

### ISSUE THREAD

**Issue by longwQaQ** [cocos/cocos-engine#8273]
### Creator version?（版本号）
Cocos Creator v2.4.3

### Affected platform?（受影响的平台）

Android
### How to reproduce?（如何重现）
Label 包含⛽️表情的时候，在转成微信小游戏后在开发工具中正常显示，但是在安卓真机上整个Label内容都不显示了。

⛽️  === :fuelpump:

**Comment by yeshao2069** [comment]
经过测试，在安卓真机上 ⛽️ === ⛽ 是可以正常显示的。
Cocos Creator 版本:  2.4.5
Android 版本 : 10   
手机型号： HUAWEI P40 Pro
![C43C3A386792C407E7BCA8F0E09D6CBB](https://user-images.githubusercontent.com/14273437/119960239-592e1c00-bfd7-11eb-9b3d-63c1e8bb1c23.jpg)

测试工程:
[testLabel2.4.5.zip](https://github.com/cocos-creator/engine/files/6559722/testLabel2.4.5.zip)

测试包:
[NewProject-debug.apk.zip](https://github.com/cocos-creator/engine/files/6559713/NewProject-debug.apk.zip)

**Comment by yeshao2069** [comment]
测试，使用Cocos Creator 2.4.3版本，在安卓上也是可以显示   ⛽️ === ⛽

![CA2A3E639E88FA7238C67470A3408CA6](https://user-images.githubusercontent.com/14273437/119962500-ae6b2d00-bfd9-11eb-9b4b-f9b26f6f7ede.jpg)

**Comment by longwQaQ** [comment]
我的意思是说转成微信小程序后，在微信开发工具中正常显示，但是在安卓真机的微信上整个Label内容不显示

**Comment by longwQaQ** [comment]
@yeshao2069 ，能验证一下看看吗？

**Comment by yeshao2069** [comment]
可以提供一下  你使用过的微信开发者工具的版本吗?

**Comment by yeshao2069** [comment]
你的这个问题,在微信小游戏  安卓真机预览可以复现.

**Comment by yeshao2069** [comment]
感谢反馈，你的这个问题已经反馈给开发排查。

**Comment by longwQaQ** [comment]
@yeshao2069 好的，大概什么时候会有结果呢？

**Comment by yeshao2069** [comment]
你好，这边初步排查，可能是微信 小游戏平台实现的问题，不支持表情包或者有一些特殊字符不能渲染。

这个问题建议你到  微信小游戏开发平台 提问工单并得到他们的帮助。
