### ISSUE TITLE
2.4.4原生iOS帧动画性能问题

### ISSUE THREAD

**Issue by tptwangw** [cocos/cocos-engine#8274]
Creator版本: 2.4.4
平台: 原生iOS
重现方式: 在2.4.4版本上创建一个空项目，上面放200个序列帧动画，打包iOS，在iPhone6 Plus上运行，帧数就只有14左右，而在2.2.2版本上，能够一直维持60帧

Demo:
[Test244.zip](https://github.com/cocos-creator/engine/files/5951695/Test244.zip)

**Comment by yeshao2069** [comment]
感谢你的反馈。相关论坛反馈 https://forum.cocos.org/t/topic/106064
使用你的测试demo，确实可以复现这个问题。
我们已经修复这个问题，预计将在下一个版本修复。
如果你着急使用的话，可以合并以下PR
https://github.com/cocos-creator/engine/pull/8528
https://github.com/cocos-creator/engine/pull/8501
https://github.com/cocos-creator/engine/pull/8509
