### ISSUE TITLE
FBIG GET URL XMLHttpRequest(); download failed on CC 3.0

### ISSUE THREAD

**Issue by faizanophobia** [cocos/cocos-engine#8275]
I have successfully implemented facebook instant games in CC 3.0, able to send & receive the data but url for downloading the profile pictures is throwing error 404.
After getXMLHttpRequest() was deprecated in 3.0 I am using 
let xhr = new XMLHttpRequest();
which is able to fetch string value
![A62A4B00-9AB5-4670-AC40-C8F17D699542](https://user-images.githubusercontent.com/42056893/107847692-a1a04000-6e13-11eb-8c97-3c81544b0d64.jpg)
but unable to download user's profile picture.

**Comment by faizanophobia** [comment]
> I have successfully implemented facebook instant games in CC 3.0, able to send & receive the data but url for downloading the profile pictures is throwing error 404.
> After getXMLHttpRequest() was deprecated in 3.0 I am using
> let xhr = new XMLHttpRequest();
> which is able to fetch string value
> ![A62A4B00-9AB5-4670-AC40-C8F17D699542](https://user-images.githubusercontent.com/42056893/107847692-a1a04000-6e13-11eb-8c97-3c81544b0d64.jpg)
> but unable to download user's profile picture.

Anybody facing this similar issue?

**Comment by xianyinchen** [comment]
404  mean the server can't find the requested resource, please check you remote resource.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

**Comment by xianyinchen** [comment]
If the problem still exists, please provide a test project and we will confirm it again.
