### ISSUE TITLE
spine开启预乘后设置opacity=0时实际显示为半透明

### ISSUE THREAD

**Issue by liuzhenhuanet** [cocos/cocos-engine#8308]
### Creator version?（版本号）
3.0

### Affected platform?（受影响的平台）

Mac Editor、Mac Chrome Web，其他平台没有测试
### How to reproduce?（如何重现）
复现：节点挂载sp.Skeleton（添加一个spine数据）和cc.UIOpacity组件，将sp.Skeleton组件上的PremultipliedAlpha勾选，cc.UIOpacity的Opacity属性设置为0
预期结果：看不到spine
实际结果：看到半透明的spine

论坛反馈贴：https://forum.cocos.org/t/topic/106910
### Demo project?（demo 项目）

测试的spine动画文件（用其他文件也测试过，表现为同样的问题，该文件在其他creator版本上表现正常）
[test3.8.99.zip](https://github.com/cocos-creator/engine/files/6060116/test3.8.99.zip)

**Comment by yeshao2069** [comment]
经确认，
https://docs.cocos.com/creator/3.0/manual/zh/release-notes/upgrade-guide-v3.0.html#%E9%92%88%E5%AF%B9-cocos-creator-2x-%E7%94%A8%E6%88%B7
![image](https://user-images.githubusercontent.com/14273437/120282243-7bcc7780-c2ec-11eb-8234-d787db142b0d.png)
> opacity：如果节点上有渲染组件，直接设置渲染组件的 color。如果没有渲染组件，则可以通过添加 UIOpacity 组件，并设置相关属性

可以直接设置spine组件的color的alpha属性值，达到你的效果。

另外，目前3.1.0版本，修改spine组件的color属性，在编辑器上无法实时生效问题，是一个已知问题。(由于UI重构导致的，3.0.0，3.0.1版本是正常的)。可以通过在编辑器选择 开发者->重新加载  刷新编辑器界面 查看效果。
<img width="500" alt="wecom-temp-45196e52de2b7bc0b8291bad7a1281dd" src="https://user-images.githubusercontent.com/14273437/120283100-686ddc00-c2ed-11eb-8cc6-ed1e92e888ff.png">

**Comment by yeshao2069** [comment]
https://github.com/cocos-creator/3d-tasks/issues/7668
