### ISSUE TITLE
Sprite设置SrcBlendFactor: ONE, opacity=0时没有隐藏

### ISSUE THREAD

**Issue by liuzhenhuanet** [cocos/cocos-engine#8309]
### Creator version?（版本号）
3.0

### Affected platform?（受影响的平台）

Mac Editor，Mac Chrome Web，其他平台没有测试
### How to reproduce?（如何重现）
详情看帖子：https://forum.cocos.org/t/topic/106965

Sprite组件参数设置如下：
SrcBlendFactor: ONE
DstBlendFactor: ONE_MINUS_SRC_ALPHA

UIOpacity组件参数设置如下：
Opacity: 0

期待结果：Sprite隐藏
实际结果：Sprite显示为近乎白色

以上参数在2.x版本是正常的，3.0版本设置为SrcBlendFactor: SRC_ALPHA后表现正常

**Comment by yeshao2069** [comment]
经确认，
https://docs.cocos.com/creator/3.0/manual/zh/release-notes/upgrade-guide-v3.0.html#%E9%92%88%E5%AF%B9-cocos-creator-2x-%E7%94%A8%E6%88%B7
![image](https://user-images.githubusercontent.com/14273437/120282243-7bcc7780-c2ec-11eb-8234-d787db142b0d.png)
> opacity：如果节点上有渲染组件，直接设置渲染组件的 color。如果没有渲染组件，则可以通过添加 UIOpacity 组件，并设置相关属性

可以直接设置spine组件的color的alpha属性值，达到你的效果。
