### ISSUE TITLE
3.0 SubContextView子节点content的layer问题

### ISSUE THREAD

**Issue by stapler-j** [cocos/cocos-engine#8353]
### Creator version?（版本号）
3.0.0

### Affected platform?（受影响的平台）
wechatgame

现在SubContextView的content节点layer是默认值，是否应该设为当前node的layer

**Comment by xianyinchen** [comment]
这个节点主要是用于计算节点区域位置，layer值不影响。

**Comment by stapler-j** [comment]
> 这个节点主要是用于计算节点区域位置，layer值不影响。

我看 #8677 已经修复过了 ，现在应该没啥问题了
