### ISSUE TITLE
hdr文件无法识别？

### ISSUE THREAD

**Issue by youZhuang** [cocos/cocos-engine#8386]
### Creator version?（版本号）
v3

### Affected platform?（受影响的平台）

Mac Editor
### How to reproduce?（如何重现）
拖一张hdr纹理放入assets，inspector里是白板。

**Comment by xianyinchen** [comment]
你好，编辑器目前不支持hdr格式文件解析。

**Comment by yeshao2069** [comment]
HDR文件识别的需求，已经提交。
