### ISSUE TITLE
Classes require the @deprecated deprecated object keyword

### ISSUE THREAD

**Issue by troublemaker52025** [cocos/cocos-engine#8420]
### Creator version?（版本号）
EN: v3.1
中:：v3.1

### Affected platform?（受影响的平台）

EN: JS-Engine
中：JS-Engine

### Requirements?（需求）
EN: We need to add a deprecated keyword field to the external classes, because some of our objects are available externally, and if the class is deprecated, the deprecated keyword should be added first, and then replaced with another object or function until it is completely removed.
中：需要给对外的类添加一个废弃关键字段，因为我们的某些对象是可以对外获取的，如果该类废弃，则应该优先添加废弃关键字，再使用其他对象或者函数替代，直至彻底删除。

**Comment by SantyWang** [comment]
类似这样
![image](https://user-images.githubusercontent.com/15109777/113377864-18839f00-93a8-11eb-9d51-fab3e35620ca.png)

**Comment by troublemaker52025** [comment]
# 描述

## 目前遇到的问题

1. privateNode 现在需要废弃，但是还要保留这个类，直到彻底删除。
2. 不能在 deprecated.ts 里去声明这个类被 node 替代，因为 node 不满足需求。

## 需求

1. 希望能给 class 加上一个 **@deprecated** 关键字，让用户仍在使用  privateNode 对象报出警告
2. 被标记过 **@deprecated** 的类会逐渐的被取代，甚至删除
3. 平稳的过渡，直至删除暴露给外部使用的类

**Comment by troublemaker52025** [comment]
该 pr 有这样的需求：https://github.com/cocos-creator/engine/pull/8382

**Comment by yeshao2069** [comment]
该需求转内部跟进，此单关闭。
