### ISSUE TITLE
3401 是什么错误？在EngineErrorMap 中未找到。

### ISSUE THREAD

**Issue by meihualuo** [cocos/cocos-engine#8427]

**Comment by yeshao2069** [comment]
可否提供一下，提示3401报错的报错截图看看嘛？

**Comment by yeshao2069** [comment]
你使用的是 Cocos Creator 2.4.x版本的吗？

如果是2.4.x版本的话，3401的报错为  
Set texture with a url of image is not supported anymore. Please use cc.assetManager.loadRemote to load a texture first.（不再支持使用图片的网址设置纹理。 请首先使用cc.assetManager.loadRemote加载纹理。）

**Comment by meihualuo** [comment]
> 你使用的是 Cocos Creator 2.4.x版本的吗？
> 
> 如果是2.4.x版本的话，3401的报错为
> Set texture with a url of image is not supported anymore. Please use cc.assetManager.loadRemote to load a texture first.（不再支持使用图片的网址设置纹理。 请首先使用cc.assetManager.loadRemote加载纹理。）

感谢回复，当时是加载微信头像使用了cc.assetManager.loadAny接口加载，报的3401，后来改用了cc.assetManager.loadRemote接口就好了。因为当时只有抛出3401，并给了这个EngineErrorMap的地址，没有找到对应错误的解释，所以提问。
