### ISSUE TITLE
2.4.x 中的BMFont的cc.js.isEmptyObject导致性能下降

### ISSUE THREAD

**Issue by insraq** [cocos/cocos-engine#8429]
### Creator version?（版本号）
2.4.x

### Affected platform?（受影响的平台）
Web

### How to reproduce?（如何重现）
![image](https://user-images.githubusercontent.com/608221/113890765-1f0d7e80-97cd-11eb-9d4a-adb4c387845f.png)

看上图 Profiler。最近一个项目需要更新大量BMFont文字，导致帧率降低很厉害，开了 Profiler 之后发现最大的问题在这行的isEmptyObject

https://github.com/cocos-creator/engine/blob/c106ab24a54916786ef85bfd3f8973f250353d15/cocos2d/core/renderer/utils/label/bmfont.js#L173

简单的优化就可以提升很多，比如缓存`cc.js.isEmptyObject(kerningDict)`的结果，或者可以直接去掉 (大部分情况应该没问题)

**Comment by finscn** [comment]
看了下 isEmptyObject 的代码, 感觉耗费性能的可能性不大.

```
    isEmptyObject: function (obj) {
        for (var key in obj) {
            return false;
        }
        return true;
    },
```
想象不出这个方法怎么会耗费性能.

**Comment by prataE** [comment]
https://blog.csdn.net/mythma/article/details/83037548
上网查了一下 会不会是因为这个问题呢

**Comment by OnlyKoei** [comment]
> ### Creator version?（版本号）
> 2.4.x
> 
> ### Affected platform?（受影响的平台）
> Web
> 
> ### How to reproduce?（如何重现）
> ![image](https://user-images.githubusercontent.com/608221/113890765-1f0d7e80-97cd-11eb-9d4a-adb4c387845f.png)
> 
> 看上图 Profiler。最近一个项目需要更新大量BMFont文字，导致帧率降低很厉害，开了 Profiler 之后发现最大的问题在这行的isEmptyObject
> 
> https://github.com/cocos-creator/engine/blob/c106ab24a54916786ef85bfd3f8973f250353d15/cocos2d/core/renderer/utils/label/bmfont.js#L173
> 
> 简单的优化就可以提升很多，比如缓存`cc.js.isEmptyObject(kerningDict)`的结果，或者可以直接去掉 (大部分情况应该没问题)

方便提供个demo?, 简单测试没有出现你说的这种情况，而且看 isEmptyObject 的耗时非常低，
测试版本 2.4.4，不确定是不是需要什么特别设置。
![image](https://user-images.githubusercontent.com/40415168/125908791-e4b742ee-618a-460b-97ac-42dd5e3d5a0c.png)
我这边的测试demo:
[BUG.zip](https://github.com/cocos-creator/engine/files/6828671/BUG.zip)

**Comment by OnlyKoei** [comment]
由于你这边长期没有回复，该 issue 暂时关闭，如果后续有问题，可继续进行反馈，给你带来的不便，感到非常抱歉！
