### ISSUE TITLE
cocos2.4.5-rc2编辑器新建组件无法拖动到另一个组件上

### ISSUE THREAD

**Issue by deadwin** [cocos/cocos-engine#8432]
![image](https://user-images.githubusercontent.com/17499435/114006408-fea7f780-9892-11eb-9c4b-8a533b220880.png)
随便新建一个工程，新建2个脚本组件，其中一个引用另一个组件，这时候拖不上去。

**Comment by deadwin** [comment]
![image](https://user-images.githubusercontent.com/17499435/114006716-42026600-9893-11eb-857c-6a1b020ef095.png)

**Comment by unusable** [comment]
cocos2.4.5-rc2编辑器中无法引用用户定义组件的变量了。

**Comment by yeshao2069** [comment]
感谢反馈，这个问题已经修复，会在2.4.6版本修复。

**Comment by yeshao2069** [comment]
你好，是不是有什么特殊的使用需求？

如果是 A脚本中需要挂 B脚本(B脚本继承A)，那么有2种方式

1. 你可以在节点node上挂脚本B，然后把节点node挂在A脚本上。
![image](https://user-images.githubusercontent.com/14273437/119761207-002e8d00-bede-11eb-9ec8-9a09565b6b1f.png)
![image](https://user-images.githubusercontent.com/14273437/119761223-06bd0480-bede-11eb-96de-d92900f4ef08.png)
![image](https://user-images.githubusercontent.com/14273437/119761271-176d7a80-bede-11eb-8df3-588de93b1ff1.png)

2.  直接import B，在A脚本中使用B脚本
