### ISSUE TITLE
wechatgame spine 骨骼动画内存泄露

### ISSUE THREAD

**Issue by Jeleren** [cocos/cocos-engine#8451]
### Creator version?（版本号）
2.4.3

### Affected platform?（受影响的平台）

wechatgame
### How to reproduce?（如何重现）
反复加载释放骨骼动画，内存会不断上涨

### 问题定位
已经定位到骨骼动画json文件没有被释放掉，加载一次骨骼动画，json文件就会泄露一次

### 问题修复
/Applications/CocosCreator/Creator/2.4.3/CocosCreator.app/Contents/Resources/builtin/adapters/platforms/wechat/wrapper/fs-utils.js 
![image](https://user-images.githubusercontent.com/34257705/114676852-51bef600-9d3c-11eb-938d-aa9d60026fca.png)
添加这行代码之后json文件被释放掉了，希望官方测试一下，并及早修复

**Comment by yeshao2069** [comment]
相关论坛反馈  https://forum.cocos.org/t/spine/82247/11

**Comment by yeshao2069** [comment]
相关论坛反馈  https://forum.cocos.org/t/spine/82247/11

**Comment by zhefengzhang** [comment]
我这边测试没有泄漏的情况呢。
![图片](https://user-images.githubusercontent.com/35944775/125759117-f4a57081-7e08-4f2a-bdd3-f63007cfa9d5.png)
请你也测试一下我的代码
[wechatgame.zip](https://github.com/cocos-creator/engine/files/6821678/wechatgame.zip)

**Comment by Jeleren** [comment]
> 我这边测试没有泄漏的情况呢。
> ![图片](https://user-images.githubusercontent.com/35944775/125759117-f4a57081-7e08-4f2a-bdd3-f63007cfa9d5.png)
> 请你也测试一下我的代码
> [wechatgame.zip](https://github.com/cocos-creator/engine/files/6821678/wechatgame.zip)

请问能发下源码吗 我这要加jsb才能在我们的宿主上运行

**Comment by zhefengzhang** [comment]
[spine-leak-test.zip](https://github.com/cocos-creator/engine/files/6923788/spine-leak-test.zip)
