### ISSUE TITLE
Building via commande line without user interaction

### ISSUE THREAD

**Issue by laurieattwobulls** [cocos/cocos-engine#8459]
When attempting to build a project from the command line,  a window called dashboard (not the same as the cocos creator dashboard) opens and prompt to open the project, even when passing the --path argument.
When selecting the project, the build process continue and successfully build the project.

My issue is that I want to build on a CI and I cannot have user interactions during the build process.

### Creator version?（版本号）
3.0.0
dashboard 1.0.12

### Affected platform?（受影响的平台）

Web-mobile
### How to reproduce?（如何重现）
1. Create an helloworld project from the cocos creator Dashboard
2. open a terminal and write the command to build the project
```
/Applications/CocosCreator/Creator/3.0.0/CocosCreator.app/Contents/MacOS/CocosCreator --path ./NewProject_1 --build "platform=web-mobile"
```
3. observe that a window called dashboard (not the same as the cocos creator dashboard) opens to prompt you to open the project.
### JavaScript output or error produced?（报错信息和调用栈）

Load profile failed: local://editor/package.json
Load profile failed: project://editor/package.json
Load profile failed: local://editor/packages.json
Load profile failed: local://packages/utils.json
Load profile failed: defaultProject://packages/utils.json
Load profile failed: project://packages/utils.json
Load profile failed: temp://packages/utils.json

### Demo project?（demo 项目）

You can try see with the hello world project from the cocos creator dashboard.

Thank you :)

**Comment by xianyinchen** [comment]
The editor is dependent on the user interface and currently does not support your use in this way, such as CI .

**Comment by laurieattwobulls** [comment]
Thank you for your answer :)
That is something new with the cocos 3.+ versions, is that correct?
Because I have a project on cocos creator 2.4.5, and I have a jenkins running on a physical mac machine on which I build the project via command line.

**Comment by xianyinchen** [comment]
No change on cocos 3.+.
You can build via command line, but the system user interface still need.

**Comment by laurieattwobulls** [comment]
I understand that you are saying that the machine needs an interface, and I am running my CI on a physical machine that has an interface.

What I am trying to explain is that, while I don't have any issue running cocos creator 2.4.5 from the command line, running the same command line with cocos creator 3.+ opens a dashboard that prompt me to select the path of the project.
<img width="1452" alt="Screen Shot 2021-07-06 at 2 09 46 pm" src="https://user-images.githubusercontent.com/43458980/124541124-2132b800-de64-11eb-87e2-13253ebc9c50.png">

**Comment by xianyinchen** [comment]
Ok, I see it.
3.x can only open from the dashboard, but allow you to do a command line build.
you problem is caused by your command line parameters are not correct. 

refer this document: https://docs.cocos.com/creator/3.1/manual/en/editor/publish/publish-in-command-line.html

**Comment by laurieattwobulls** [comment]
Oh yep! I see, --path has changed for --project. Didn't catch that ^^

Thanks!
