### ISSUE TITLE
why there are differences between the two this code ? Use "setContentSize" before and after "addchild" ! 

### ISSUE THREAD

**Issue by tocaonguyen** [cocos/cocos-engine#846]
code 1 and preview 
<img width="1176" alt="screen shot 2016-06-29 at 11 51 49" src="https://cloud.githubusercontent.com/assets/10234430/16440996/cf7b927a-3df0-11e6-9320-1d1c98e9f43b.png">
<img width="565" alt="screen shot 2016-06-29 at 11 52 00" src="https://cloud.githubusercontent.com/assets/10234430/16440997/cf7c1bf0-3df0-11e6-89d4-466a38e0fd6c.png">

code 2 and preview 

<img width="1070" alt="screen shot 2016-06-29 at 11 51 40" src="https://cloud.githubusercontent.com/assets/10234430/16441006/de16034c-3df0-11e6-8d1e-084378c187a3.png">
<img width="591" alt="screen shot 2016-06-29 at 11 52 17" src="https://cloud.githubusercontent.com/assets/10234430/16441005/de13bd62-3df0-11e6-9835-47485b879706.png">

**Comment by jareguo** [comment]
because the default size mode in Sprite component is TRIMMED, it will reset the node's size when adding to the scene.

**Comment by tocaonguyen** [comment]
yeah , if i use sprite.sizeMode = cc.Sprite.SizeMode.CUSTOM when set frame texture then code 1 run  ok ^^ ,   thank for reply ...! <3 @jareguo

**Comment by jareguo** [comment]
np :D
