### ISSUE TITLE
请问3.0的creator.d.ts如何获取

### ISSUE THREAD

**Issue by dengtongtongtong** [cocos/cocos-engine#8474]
### Creator version?（版本号）
3.0

### Affected platform?（受影响的平台）

mac

### 问题描述

mac下开发者->vs code flow下没有更新 VS Code 智能提示数据 选项，请问如何获取creator.d.ts

**Comment by yeshao2069** [comment]
你好，感谢你的反馈。
1.    Creator 3.0已经取消creator.d.ts文件。
2.   目前Creator 3.0 你可以在 temp/declarations中找到 cc.d.ts定义等。   这个是在tsconfig.json中定义。
![image](https://user-images.githubusercontent.com/14273437/115667242-32494e00-a378-11eb-826a-4c82eb866a33.png)
