### ISSUE TITLE
希望 cocos 2.4 能更新下 对 spine新版runtime的支持

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#8489]
spine新的 runtime修正了一些 非常明显的bug.

https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-ts/build/spine-core.js

希望cc能支持 , 3.0支持的同时 , 也能顾及下2.4 用户.  谢谢了

**Comment by zhefengzhang** [comment]
好的，我这边把这个需求转交给相关模块负责人。

**Comment by zhefengzhang** [comment]
已发内部 issues 跟踪，此 issues 暂时关闭。
