### ISSUE TITLE
UI Image preserve aspect ratio

### ISSUE THREAD

**Issue by ozergul** [cocos/cocos-engine#8627]
Hello
Are there any option to preserve aspect ratio of UI image like Unity? When I scale the image, I have to set width and height to preserve aspect ratio. But I think it must be option in Image Component.
Regards.

**Comment by ozergul** [comment]
Anybody knows the solution?

**Comment by xianyinchen** [comment]
The engine does not provide this functionality. Please code your own implementation.

**Comment by ozergul** [comment]
This is very interesting, I think cocos creator must have this functionality. 
Thanks anyway.
