### ISSUE TITLE
再次强烈建议将 gfx,  node.getWorldPosition/setWorldPosition 加入到 creator.d.ts 文件里

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#8649]
### Creator version?（版本号）
2.4.5

gfx这个枚举对象, node的这两个方法在源码里是公共方法, 文档里也能查到,但是creator.d.ts里一直没有.

虽然现在cocos出到3.0了, 但是因为变化巨大, 估计2.4 会和当初 python2 一样, 会和3共存很长一段时间.
希望能重视下 2.4系列的使用体验. 尤其是ts用户的.

**Comment by yeshao2069** [comment]
感谢反馈，需求已经收集，已经反馈给相关负责人评估。

**Comment by yeshao2069** [comment]
经确认3.x版本， node.getWorldPosition/setWorldPosition 接口时开放给用户使用，2.4.5版本还没有。

**Comment by zhefengzhang** [comment]
谢谢反馈，.d.ts 的问题，可以先修，接口的开放问题我们也出再处理。
