### ISSUE TITLE
3.1下的扩展编辑器中的场景脚本只打印warn和error的日志

### ISSUE THREAD

**Issue by qinfen** [cocos/cocos-engine#8683]
在creator 3.1中编写扩展脚本我发现在场景脚本中的日志打印只能响应warn和error，log和debug均不行。

示例代码:
[scene-test.zip](https://github.com/cocos-creator/engine/files/6497761/scene-test.zip)

期望:
![7193DFEF-951B-41A1-9144-5EDFC39623D1](https://user-images.githubusercontent.com/1481155/118577777-9a475480-b7bd-11eb-89ad-941b76507c01.png)
实际效果:
![FD393B2D-29C8-4309-8869-5990A576823D](https://user-images.githubusercontent.com/1481155/118577832-b21ed880-b7bd-11eb-8afe-d3028333e888.png)

**Comment by yeshao2069** [comment]
checking

**Comment by zhefengzhang** [comment]
感谢反馈，已确认为当前版本 bug ，我们会进行修复的。
