### ISSUE TITLE
3.1的2d粒子特效呈现的效果有问题。

### ISSUE THREAD

**Issue by qinfen** [cocos/cocos-engine#8685]
说明:
 同一个2d粒子特效在3.1和3.0上呈现的效果不一样，很明显是3.1上的有问题。
对比:
![ftsdn-pmlq0](https://user-images.githubusercontent.com/1481155/118579603-fbbcf280-b7c0-11eb-8d2a-911c099b2fa3.gif)
左边是3.1 右边是3.0
粒子源文件:
[jidaguang.plist.zip](https://github.com/cocos-creator/engine/files/6497829/jidaguang.plist.zip)

**Comment by MrZak-dev** [comment]
I had the same issue , change the duration to 1 or a value that fits your needs .

![image](https://user-images.githubusercontent.com/27586088/119170114-7c068080-ba6b-11eb-8b03-86ee716d8e09.png)

**Comment by yeshao2069** [comment]
经过验证，确认表现不一致，已经内部反馈排查了。
