### ISSUE TITLE
V3.1 如何使用CollisionManager

### ISSUE THREAD

**Issue by kevinw-openai** [cocos/cocos-engine#8733]
### Creator version?（版本号）
V3.1

请问V3.1 如何使用 CollisionManager？

V2.4的[document](https://docs.cocos.com/creator/manual/en/physics/collision/collision-manager.html)给了如下例子：
`var manager = cc.director.getCollisionManager();`

但是V3.1没有对等的document，`director` 下面也没有collisionManager

**Comment by zhefengzhang** [comment]
3.1.0 版本已经没有 CollisionManager 的用法了。现在 2D 物理 & 碰撞系统统一使用 PhysicsSystem2D.instance 对象，3D 物理 & 碰撞系统统一用 PhysicsSystem.instance。

**Comment by yeshao2069** [comment]
PhysicsSystem2D（2D物理）  https://docs.cocos.com/creator/3.1/api/zh/classes/physics2d.physicssystem2d.html
PhysicsSystem （3D物理）  https://docs.cocos.com/creator/3.1/api/zh/classes/physics.physicssystem.html

请知悉，谢谢。此单先关闭。
