### ISSUE TITLE
CocosCreator3.1版本 getTiledTileAt(0，0，true) 方法异常

### ISSUE THREAD

**Issue by andaren** [cocos/cocos-engine#8734]
### Creator version?（版本号）
3.1.0

### Affected platform?（受影响的平台）

Mac
### How to reproduce?（如何重现）
正常创建地图的步骤，2.4.5版本下好的。
1. 初始空项目，Canvans 下建立 game 节点
2. game节点下建立 TiledMap 组件节点
3. game脚本内能获取到 TiledMap 组件和里面的层节点，但是调用获取图片方法就报如下异常，无从排查。。。
![image](https://user-images.githubusercontent.com/16839874/120091731-77635b80-c140-11eb-935a-7bbb51c8b00f.png)

game脚本代码
```typescript
@ccclass('Game')
export class Game extends Component {
    // [1]
    // dummy = '';

    // [2]
    // @property
    // serializableDummy = 0;
    @property(TiledMap)
    tiledMap: TiledMap | null = null;

    start () {
        // [3]
        console.log(this.tiledMap);
        let l1 = this.tiledMap?.getLayer('bg');
        let tiledTile = l1?.getTiledTileAt(0, 0, true);
        console.log(tiledTile);// 能打印 tiledTile 信息
        // EventError
    }

    // update (deltaTime: number) {
    //     // [4]
    // }
}
```

**Comment by andaren** [comment]
![image](https://user-images.githubusercontent.com/16839874/120091890-94e4f500-c141-11eb-9122-27190609849c.png)
补充异常堆栈

**Comment by andaren** [comment]
creator3.0.0版本也是有相同问题

**Comment by novain1102** [comment]
麻烦附个demo上来  我排查一下

**Comment by SantyWang** [comment]
已修复

**Comment by purple97** [comment]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/6193351/195592406-305a9096-4ed5-4d89-ad74-73cadc4a3c76.png">
![image](https://user-images.githubusercontent.com/6193351/195592721-102c7991-d575-4929-92db-57c9359c241c.png)

还是遇到同样的问题
