### ISSUE TITLE
3D模型显示异常

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#8736]
### Creator version 
3.1

### Affected platform
Web
iOS
Android
Simulator

### How to reproduce

Editor:

![image](https://user-images.githubusercontent.com/8321365/120131148-58c19b00-c1fa-11eb-880a-1a7aa237fa33.png)

Web preview:
![image](https://user-images.githubusercontent.com/8321365/120131157-5eb77c00-c1fa-11eb-8e78-a020cb326495.png)

### Demo project

[test.zip](https://github.com/cocos-creator/engine/files/6567405/test.zip)

**Comment by zhefengzhang** [comment]
3.3 版本已修复，帮看一下有没有修复 pr 提供给客户。
