### ISSUE TITLE
[2.3.3 ~ 2.4.5] TiledMap 组件无法正确显示 Tiled 编辑器中设置了透明度的图层

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#8750]
小秘书工单 ID：5992

论坛中已经有相关的大量反馈：
https://forum.cocos.org/t/dragonbones/91169
https://forum.cocos.org/t/topic/108291
https://forum.cocos.org/t/tiledmap/36308
https://forum.cocos.org/t/creator-tiledmap-objectgroup/45910

测试资源：
[map.zip](https://github.com/cocos-creator/engine/files/6597201/map.zip)

**Comment by zhefengzhang** [comment]
@zhakesi

**Comment by minggo** [comment]
2.x 问题不再处理。
