### ISSUE TITLE
[2.4.5 & 3.1.0] 原生平台无法动态远程加载二进制 spine 骨骼资源

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#8759]
小秘书工单 ID：6029

目前的引擎内部 issues：
https://github.com/cocos-creator/3d-tasks/issues/7145
https://github.com/cocos-creator/2d-tasks/issues/3361
https://github.com/cocos-creator/3d-tasks/issues/7161

目前暂定在 3.3 版本修复

**Comment by pppluto** [comment]
有临时解决方法没

**Comment by zhefengzhang** [comment]
目前没有，在等引擎修复中。

**Comment by novain1102** [comment]
> 有临时解决方法没

![WeChatWorkScreenshot_1f4734d1-00c1-4329-9208-43774cf6ba4e](https://user-images.githubusercontent.com/18634782/125552683-78f6762b-429a-43cf-892e-2c1d7a7dc75b.png)
试试这个写法

**Comment by zhefengzhang** [comment]
验证上面的写法能正常加载了。
