### ISSUE TITLE
3.1.0 设置swallowTouches无效，不能进行事件传递

### ISSUE THREAD

**Issue by CaedmonKe** [cocos/cocos-engine#8783]
### Demo project?
node.eventProcessor.touchListener.swallowTouches = false;

    中：用于呈现错误的可理解的 Creator 工程或资源，不依赖第三方工具或插件或者服务端。这个 demo 应该越小越好。
    不含可重现范例的 issue 将有可能被关闭。
-->

**Comment by lizhiyu-me** [comment]
请问最后是怎么解决的啊

**Comment by CaedmonKe** [comment]
> 请问最后是怎么解决的啊

可能不是同一个问题哦，我这边记得是设置了cc.macro.ENABLE_MULTI_TOUCH导致的。
