### ISSUE TITLE
编辑器显示模糊问题

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#8793]
用户工单：6076
![817b786ede8504d67c333dcbd46b558e86610](https://user-images.githubusercontent.com/40415168/121314420-ea878180-c939-11eb-8442-fbe696b1f448.png)

部分电脑系统升级，驱动升级，显示器分辨率过高会出现这类显示模糊问题

**Comment by OnlyKoei** [comment]
#https://github.com/cocos-creator/3d-tasks/issues/4678

**Comment by yeshao2069** [comment]
Mac 上是支持动态开关 retina 的，并且支持 ratio 变化。现在 windows 和浏览器也都需要类似功能，否则一旦在不同屏幕间移动，就会出现缩放比例不正确，显示变糊的问题。

**Comment by zhefengzhang** [comment]
@OnlyKoei 这部分优化在 3.4.0 完成了，这个问题有没有办法验证是否解决？

**Comment by OnlyKoei** [comment]
> @OnlyKoei 这部分优化在 3.4.0 完成了，这个问题有没有办法验证是否解决？

用 3.4.0 之前的版本测试过，无法复现。

**Comment by zhefengzhang** [comment]
嗯，那就暂时关闭这个 issues 吧，3.4.0 已经完成优化。

**Comment by yeshao2069** [comment]
该issue 暂时关闭。
