### ISSUE TITLE
[3.1.1] 替换插屏功能，设置竖屏，显示只有半屏(iOS)

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#8797]
工单：6133

用户反馈，3.1.1 版本 使用替换插屏功能，发布iOS版本，显示异常，在CocosCreator3D1.2.0 显示正常。

操作：
发布iOS平台，选择替换插屏，换一张图片。

3.1.1版本
![70195F94C411E3C385F573BA1B575CDE](https://user-images.githubusercontent.com/14273437/121324801-a600e380-c943-11eb-90b1-b567649b5237.png)

3D 1.2.0版本
![DB2288F607D519FB21ADFD1914615C53](https://user-images.githubusercontent.com/14273437/121324846-b1540f00-c943-11eb-8e36-2bc1c1f11a06.png)

测试Demo
creator 3d 1.2.0
[testCP120.zip](https://github.com/cocos-creator/engine/files/6622445/testCP120.zip)

creator 3.1.1
[testCP.zip](https://github.com/cocos-creator/engine/files/6622449/testCP.zip)

验证，发布微信小游戏，在微信开发者工具中模拟器查看没问题。

**Comment by zhefengzhang** [comment]
3.3 版本已修复，帮看一下有没有修复 pr 提供给客户。

**Comment by yeshao2069** [comment]
这个问题将在3.3版本被修复。
测试 合并 修复PR cocos-creator/engine-native#3590
不过3.1.1版本到3.3版本，还有一些改动，会导致合并PR并不能直接使用，请知悉。
