### ISSUE TITLE
[3.1.1-3.2.0] 子包无法加载SpriteFrame报错

### ISSUE THREAD

**Issue by cn-dream** [cocos/cocos-engine#8805]
### Affected platform?（受影响的平台）

Web
### How to reproduce?（如何重现）

 

 
        assetManager.loadBundle('pkg1', (err, bundle) => {
            bundle.load('hello', SpriteFrame, null, (err, asset) => {
                console.log('SpriteFrame = ',asset)
                if(err){
                    console.log(err)
                }
            })
        })
 
 

### JavaScript output or error produced?（报错信息和调用栈）
Error: Bundle pkg1 doesn't contain hello
    at _loop (url-transformer.ts:110)
    at parse (url-transformer.ts:44)
    at Pipeline.sync (pipeline.ts:219)
    at preprocess (preprocess.ts:73)
    at Pipeline._flow (pipeline.ts:262)
    at Pipeline.async (pipeline.ts:257)
    at AssetManager.loadAny (asset-manager.ts:457)
    at Bundle.load (bundle.ts:240)
    at main.ts:15
    at Array.<anonymous> (asset-manager.ts:638)

### Demo project?（demo 项目）
https://github.com/cn-dream/cocos-bug-demo-1.git

**Comment by yeshao2069** [comment]
感谢反馈。
你好，这边使用你的测试Demo测试，发现你这边有2个配置需要修改一下。
1. 放在资源管理器中的pkg1分包里面的hello(图片)，默认的图片格式是texture，但是你动态加载的时候，加载的spriteFrame格式，所以不存在，需要手动修改一下图片的格式。
![image](https://user-images.githubusercontent.com/14273437/121619873-e1162a80-ca9b-11eb-8fad-6bf2dd9ee8ca.png)


2. 在分包中加载图片格式的时候，需要制定加载的spriteFrame路径。这个其实你从断点中可以看到，bundle里面的map其实对于图片是区分的。
![image](https://user-images.githubusercontent.com/14273437/121620326-b8dafb80-ca9c-11eb-86c1-2bf67768453b.png)
所以你可以修改
bundle.load('hello/spriteFrame', SpriteFrame, null, (err, asset) => {
    console.log('SpriteFrame = ',asset)
    if(err){
        console.log(err)
    }

})

**Comment by cn-dream** [comment]
刚才试了一下，可以了，
之前用 bundle.getDirWithPath('/')，看到资源都在，就是不知道怎么拿出来，之前2.4的文档，是不需要这么设置的
厉害，谢谢指教，刚才又看了下，3.0的文档，用法都有，本以为和2.4用法一样，还是文档没研究透，麻烦你们了
![image](https://user-images.githubusercontent.com/28748846/121622977-7536c080-caa1-11eb-8d4e-c5d992df0ccc.png)
