### ISSUE TITLE
[2.4.4] 项目 assets 体积较大时，命令行编译时 Mac 版编辑器会出现崩溃的情况

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#8812]
小秘书工单 ID: 6160

Engine Version: 2.4.4

崩溃日志：
[aa56cc4602da451eff0256cd629135d841100.txt](https://github.com/cocos-creator/engine/files/6637581/aa56cc4602da451eff0256cd629135d841100.txt)

项目情况，assets 的内存占用很大，达到 2G+

**Comment by zhefengzhang** [comment]
准备在 2.4.6 版本进行一轮优化。
关联内部 issues：https://github.com/cocos-creator/2d-tasks/issues/3330

**Comment by zhefengzhang** [comment]
2.4.6 版本计划在 2021 年 7 月 19 日发布。

**Comment by yeshao2069** [comment]
2.4.6版本已经发布，可以测试一下。
