### ISSUE TITLE
希望能更新下 2.4系列的 Spine的SDK

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#8815]
我们实际项目测试下来, 目前cocos里  Spine的性能不如龙骨.
但是 我们直接用纯html5 测试 , spine 是优于 龙骨的.

(测试用例是我们设计师 制作的一模一样的动画,  用龙骨做了一份 用spine做了一份.
动画用到了mesh )

看了下cocos 2.4里使用的spine库, 好像版本不够新.

希望能更新下. 谢谢.

**Comment by zhefengzhang** [comment]
你好，我看到你之前有提过相同的 issues。
https://github.com/cocos-creator/engine/issues/8489

目前引擎后续会升级 3.x 的 spine 库，但是不会再对 2.x 版本进行升级了。后续开发者可以根据 3.x 的提交记录自行升级。
