### ISSUE TITLE
[3.1.1]  小图片 TILED 平铺背景不显示，角度刁钻

### ISSUE THREAD

**Issue by cn-dream** [cocos/cocos-engine#8816]
### Affected platform?（受影响的平台）

chrome，场景编辑器
### How to reproduce?（如何重现）
希望，creator 越来越完善，在论坛提过这个问题
[https://forum.cocos.org/t/topic/115108](https://forum.cocos.org/t/topic/115108)

### JavaScript output or error produced?（报错信息和调用栈）
无

### Demo project?（demo 项目）
有，详见论坛连接

**Comment by yeshao2069** [comment]
感谢反馈，目前这个问题已经新建内部issue给开发排查了。
