### ISSUE TITLE
[2.4.5]WebMobile引擎初始化导致 iOS14.5以上版本正在播放的音频、视频被暂停

### ISSUE THREAD

**Issue by LittleZzUni** [cocos/cocos-engine#8819]
### Creator version?（版本号）
2.4.5

### Affected platform?（受影响的平台）

iOS14.5以上版本
### How to reproduce?（如何重现）
用浏览器打开H5游戏，引擎初始化会打断正在播放的音频、视频。

### JavaScript output or error produced?（报错信息和调用栈）

 __audioSupport.context = new (window.AudioContext || window.webkitAudioContext || window.mozAudioContext)();

会导致iOS14.5以上版本正在播放的音频、视频被暂停

**Comment by zhefengzhang** [comment]
你好，我这边测试没有问题，请你看下我的测试 demo 是否和你差不多？
[testAudio.zip](https://github.com/cocos-creator/engine/files/6805666/testAudio.zip)

**Comment by dserWei** [comment]
仍然存在这个问题，只要调用new window.AudioContext就会暂停
