### ISSUE TITLE
安装@walletconnect/client的时候不能被正确解析

### ISSUE THREAD

**Issue by GHChrisSu** [cocos/cocos-engine#8827]
### Affected platform?（受影响的平台）
Web

### How to reproduce?（如何重现）
![image](https://user-images.githubusercontent.com/13779988/122157588-0e047c00-cea6-11eb-9b0f-9c985b5c141d.png)
![image](https://user-images.githubusercontent.com/13779988/122157610-18bf1100-cea6-11eb-95da-cec5057bb138.png)
安装和导入wallet connect的时候 对象是空的 而且最后打出来esm貌似不正确
![image](https://user-images.githubusercontent.com/13779988/122157667-38eed000-cea6-11eb-9ef9-1a08a841afb9.png)
![image](https://user-images.githubusercontent.com/13779988/122157674-3b512a00-cea6-11eb-9cd1-6a231d990221.png)

### JavaScript output or error produced?（报错信息和调用栈）
导入使用的时候Client就是null

**Comment by zhefengzhang** [comment]
你好，我这边测试是没有问题的哈。
![图片](https://user-images.githubusercontent.com/35944775/125382794-ea5f2380-e3c8-11eb-897f-d343966d341d.png)
这是我的测试 demo，你看一下。
[001.zip](https://github.com/cocos-creator/engine/files/6805552/001.zip)

**Comment by GHChrisSu** [comment]
@zhefengzhang 谢谢帮忙看，您应该是用的1.4.1的正式版， 2.0是walletconnect的测试版， 2.0开始才支持其他的公链  1.x版本仅支持以太坊  所以想要2.0  不知道和cocos的导入方式有关系 我在用vue的前端 webpack打包的时候可以导入
