### ISSUE TITLE
 关于 packToDynamicAtlas 的两个疑问

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#8850]
https://github.com/cocos-creator/engine/blob/a40850c78f9d594fe3f0c30648e2f682b4556381/cocos2d/core/renderer/assembler-2d.js#L136

如果 frame._texture.loaded = false , 整个 方法是否都应该 return? 

另外, 用 下面的代码是否可行? (重点是 oldTex ) 
```
        const oldTex = frame._texture
        if (!frame._original && cc.dynamicAtlasManager && frame._texture.packable) {
            const packedFrame = cc.dynamicAtlasManager.insertSpriteFrame(frame)
            if (packedFrame) {
                frame._setDynamicAtlasFrame(packedFrame)
            }
        }

        const material = comp._materials[0]
        if (!material) return

        if (oldTex !== frame._texture) {
            comp._vertsDirty = true
            comp._updateMaterial()
        }
```
也就是说  用 oldTex  和 frame._texture 做判断, 而不是 从  material 里 取texture.

**Comment by zhefengzhang** [comment]
> 如果 frame._texture.loaded = false , 整个 方法是否都应该 return?
- 是的，在 loaded 为 false 的时候，也不会 updateRenderer
![图片](https://user-images.githubusercontent.com/35944775/125241744-68b2bb80-e31e-11eb-9707-3ff97b257bc4.png)

> 用 oldTex 和 frame._texture 做判断,
- 这个没问题啊，反正都是取合并为大图之前的原始图。
