### ISSUE TITLE
[Spine]挂点上的图片能否插入到 spine 的层级里面

### ISSUE THREAD

**Issue by novain1102** [cocos/cocos-engine#8860]
社区讨论还挺多的, 不过我们引擎好像一直没有支持这个功能
Dragonbones似乎是有相关功能的官方类库, Spine这块不太清楚
https://forum.cocos.org/t/topic/101288
https://forum.cocos.org/t/topic/111680
https://forum.cocos.org/t/spine/89054

**Comment by PatriceJiang** [comment]
可以参考 tilemap 的实现, 嵌入 sprite.   但是这个只能在 UI 系统里实现, 和 3D 化的规划相背.

**Comment by zhefengzhang** [comment]
关联到内部 task issues 了，这个需求还是有必要研究看看的。
