### ISSUE TITLE
cc.Material.BUILTIN_NAME 枚举导出类型错误

### ISSUE THREAD

**Issue by ffpwserver** [cocos/cocos-engine#8870]
### Creator version?（版本号）
v2.4.5

### Affected platform?（受影响的平台）

All

### How to reproduce?（如何重现）
新建项目查看即可
TS项目生成的creator.d.ts中，导出的命名空间Material中的枚举BUILTIN_NAME下面有三个枚举变量
SPRITE，GRAY_SPRITE，UNLIT
三个变量的类型应该是string，但是creator.d.ts文件中将其简单定义为0
在代码中调用
cc.Material.createWithBuiltin
或者
cc.MaterialVariant.createWithBuiltin
这两个方法，如果传入cc.Material.BUILTIN_NAME.SPRITE编辑器便会报错

**Comment by yeshao2069** [comment]
这个问题，确实有问题。

**Comment by zhefengzhang** [comment]
谢谢反馈。
目前 2.x 版本的 enum 参数都会有这个问题，后续版本集中时间优化一遍吧。
3.x 版本已经没有此问题。
