### ISSUE TITLE
Script caching issue

### ISSUE THREAD

**Issue by nickav** [cocos/cocos-engine#889]
Steps to reproduce:
1. Create a new "Hello World" project
2. Run the project in the simulator
3. Edit text property in the file Script/HelloWorld.js and change it to something like "Hello, there!" instead of "Hello, world"
4. Note that after refreshing the new text does not get rendered on the screen. The old "Hello, world!" text still persists.

Only after renaming the properties.text to something else (like test) then using this.test will the auto update grab the changes to the string.

The following is the output of the console:

```
Simulator : LOAD Js FILE: main.js
Simulator : Evaluating script/debugger/actors/script.js failed (evaluatedOK == JS_FALSE)
Simulator : /Applications/CocosCreator.app/Contents/Resources/cocos2d-x/simulator/mac/Simulator.app/Contents/Resources/script/debugger/actors/script.js:3139:ReferenceError: ObjectActor is not defined
Simulator : ScriptingCore::callFunctionName error:__errorHandler wasn't found!
Simulator : Cocos2d-JS v3.9
Simulator : iShow!
```

Mac OSX 10.9.5

**Comment by nickaversano** [comment]
I see that the 'properties' attribute is used as a placeholder and MUST be edited visually (as a property of Canvas). I recommend updating the "Hello World" project to

**Comment by nickav** [comment]
I see now that the properties attribute of the Script just sets up the defaults. This should be made clearer with a comment above like: "defaults, override these from the Canvas"

**Comment by jareguo** [comment]
> This should be made clearer with a comment above like: "defaults, override these from the Canvas"

Hi, where should this comment display?

**Comment by nickav** [comment]
Not sure about the exact wording, but for example in `assets/Script/HelloWorld.js`:

``` javascript
cc.Class({
    extends: cc.Component,

    // defaults, set visually when attaching this script to the Canvas
    properties: {
        label: {
            default: null,
            type: cc.Label
        },
        text: 'Hello, world!'
    },

    // use this for initialization
    onLoad: function () {
        this.label.string = this.text;
    },

    // called every frame
    update: function (dt) {
    },
});
```

**Comment by jareguo** [comment]
I think that's ok, thanks.
@knoxHuang Can you improve the comment in the HelloWorld project?
