### ISSUE TITLE
希望能将 cc.visibleRect 向上取整

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#8918]
因为浮点数误差的原因,  cc.visibleRect 以及其他屏幕相关的组件里的大小 位置等
经常出现小数. 如果游戏里直接拿来用,  经常会出现错误的 边缘缝隙.

希望能做向上取整处理

**Comment by zhefengzhang** [comment]
我觉得这个参数用户自行取整吧，引擎只是返回了平台底层返回的画布宽高信息。
