### ISSUE TITLE
[2.4.4] 使用macOS 打包Android 包，在Creator构建面板 编译失败

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#8929]
经过测试，使用MacOS 打包Android，在构建面板上构建后，使用 Android Studio 可以正常打包apk。但是在Creator构建面板点击编译会报错。

错误信息如
[error.log](https://github.com/cocos-creator/engine/files/6753205/error.log)

**Comment by yeshao2069** [comment]
测试的版本： 2.4.4
测试的jdk版本：1.8.0_291、16.0.1 都会有问题

测试过，在Android Studio build出apk包，再在构建面板上点击编译，也是报错

**Comment by zhefengzhang** [comment]
2.4.5 有这个问题么，请验证一下？2.4.4 是旧版本了，我们没法解决问题。

**Comment by yeshao2069** [comment]
2.4.5 版本也是一样的。
测试方式： 使用构建面板构建Android工程，然后使用Android Studio build，可以build出apk
如果此时，使用构建面板上的编译功能，直接编译，编译失败。
如果使用构建面板重新构建且编译，编译失败。
[native.log](https://github.com/cocos-creator/engine/files/6762942/native.log)

**Comment by zhefengzhang** [comment]
这个问题有内部 issus 了么，关联一下。

**Comment by yeshao2069** [comment]
经过排查，这个原因是是MacOS 电脑缺少 tools.jar包导致的，这个需要拷贝一下即可。可尝试以下方案。
方案：
1.  在命令行终端，输入   /usr/libexec/java_home -V ， 可以查看到自己macOS安装的jdk版本。
> /usr/libexec/java_home -V

![image](https://user-images.githubusercontent.com/14273437/125029556-6ea96200-e0bc-11eb-8dc4-a159e27b2f73.png)
2. 在命令行终端，输入  java -version， 可以查看当前生效的jdk版本。
>java -version

![image](https://user-images.githubusercontent.com/14273437/125029624-8c76c700-e0bc-11eb-8779-e118926093bf.png)
3. 以我的macOS电脑为例，当前生效的jdk版本是1.8.0_291，拷贝 /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/lib 目录下的tools.jar文件到 /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib 目录下。
4. 在构建面板上点击编译，成功。
![image](https://user-images.githubusercontent.com/14273437/125030088-1faffc80-e0bd-11eb-8c7b-c79ac1373488.png)

备注：拷贝的命令可以参考
>sudo cp /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/lib/tools.jar /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib

需要输入电脑密码
![image](https://user-images.githubusercontent.com/14273437/125030274-74ec0e00-e0bd-11eb-82b4-00256d62a56e.png)

可以参考  https://www.cnblogs.com/johnjackson/p/14040958.html 方案3解决。

**Comment by yeshao2069** [comment]
Link 相关issue   https://github.com/cocos-creator/engine/issues/8949
