### ISSUE TITLE
AbortController is not defined

### ISSUE THREAD

**Issue by dorthl** [cocos/cocos-engine#8931]
### Creator version?（版本号）
3.2.0

### Affected platform?（受影响的平台）

Android 

### How to reproduce?（如何重现）
使用 AbortController

**Comment by yeshao2069** [comment]
可以告知你是怎么使用的吗？方便提供demo看看吗？
https://developer.mozilla.org/zh-CN/docs/Web/API/AbortController
我看了AbortController 是一个实验中的功能，此功能某些浏览器尚在开发中，请参考浏览器兼容性表格以得到在不同浏览器中适合使用的前缀。由于该功能对应的标准文档可能被重新修订，所以在未来版本的浏览器中该功能的语法和行为可能随之改变。
![image](https://user-images.githubusercontent.com/14273437/124533233-84aced80-de44-11eb-88d4-f156a9ac3cbc.png)

![image](https://user-images.githubusercontent.com/14273437/124533300-a7d79d00-de44-11eb-9922-48e2b37e6ec6.png)

**Comment by dorthl** [comment]
我在使用 npm 包 @microsoft/signalr ^5.0.7 时候遇到的
包中的调用如下
```
        if (typeof fetch === "undefined") {
            // In order to ignore the dynamic require in webpack builds we need to do this magic
            // @ts-ignore: TS doesn't know about these names
            const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;

            // Cookies aren't automatically handled in Node so we need to add a CookieJar to preserve cookies across requests
            this.jar = new (requireFunc("tough-cookie")).CookieJar();
            this.fetchType = requireFunc("node-fetch");

            // node-fetch doesn't have a nice API for getting and setting cookies
            // fetch-cookie will wrap a fetch implementation with a default CookieJar or a provided one
            this.fetchType = requireFunc("fetch-cookie")(this.fetchType, this.jar);

            // Node needs EventListener methods on AbortController which our custom polyfill doesn't provide
            this.abortControllerType = requireFunc("abort-controller");
        } else {
            this.fetchType = fetch.bind(self);
            this.abortControllerType = AbortController;
        }
```
不知道为什么 signalr 在判断 fetch 存在后就认为 AbortController也存在了...
在把 fetch 指定为 undefined 后问题解决了

**Comment by dorthl** [comment]
解决的过程中我碰到一个问题就是引用 polyfill包非常非常难 基本无解 只能自己定义一个js文件 但是又没有类型注释 而且无法引用npm包 这种情况有什么比较好的解决办法吗  我搜索了很多 3.2.0版本的基本没有相关说明
AbortController 可以不实现 但是官方应该提供 引用 npm polyfill 包的办法

**Comment by dorthl** [comment]
还有 现在遇到的两个问题 在 3.2.0版本中 
1. 在原生平台调用 game.restart() (windos,安卓) 都会直接闪退 安卓中 vulkan 模式下会闪退,gles3下 游戏会失去响应 只能强行杀死进程
2. 在安卓平台下
`systemEvent.on(SystemEvent.EventType.KEY_DOWN, this.onKeyDown);`
监听不了安卓的返回事件调试
java端
```onKeyDown(int keyCode, KeyEvent event)``` 是调用了的 并且 keyCode =4 
但是在js端 onKeyDown根本没有调用

**Comment by dorthl** [comment]
还有 https://docs.cocos.com/creator/3.2/api/zh/ 这个api文档 的搜索功能在多数情况下会直接卡死
还不如 2.4版本的这个 https://docs.cocos.com/creator/api/zh/  但是3.0的api又变更很大...  太难了
