### ISSUE TITLE
[COCOS CREATOR v3.1.1,v3.2] Memory leak on Spine animation

### ISSUE THREAD

**Issue by dev-keishen** [cocos/cocos-engine#8933]
Hello cocos creator team

I am facing a critical problem on cocos creator v3.x

My problem is a huge memory leak was occur when a scene has an spine animation

My scene 1 has no spine animation and nothing memory leak occur
When i switch to scene 2 which has a chacracter animation,my memory increase so much and increase time by time

I would like to send an video to describe this issue
[memory-leak.mov.zip](https://github.com/cocos-creator/engine/files/6759860/memory-leak.mov.zip)

And this is a source code : 
[RabbitJump.zip](https://github.com/cocos-creator/engine/files/6759853/RabbitJump.zip)

Please help me this issue
Thank you very much

**Comment by xianyinchen** [comment]
This is a known issue and we have arranged to deal with it.

**Comment by dev-keishen** [comment]
> This is a known issue and we have arranged to deal with it.

Thank you very much
Pleasure when see your answer

**Comment by obraz29** [comment]
@xianyinchen hello Xian, we're also encountering this issue, any hotfix we can apply ?

**Comment by xianyinchen** [comment]
Yes, this is issue already fixed, refer it please.
https://github.com/cocos-creator/engine-native/pull/3686
