### ISSUE TITLE
2.4.4微信上同时播放两次音频，第一次两个音频均无法播放，第二次开始正常播放

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#8940]
用户工单：6629
问题：2.4.4微信上同时播放两次音频，第一次两个音频均无法播放，第二次开始正常播放；

暂时通过延迟播放第二次音频的办法；
测试demo:
[LabelDemo.zip](https://github.com/cocos-creator/engine/files/6774008/LabelDemo.zip)

**Comment by OnlyKoei** [comment]
#https://github.com/cocos-creator/2d-tasks/issues/3402

**Comment by zhefengzhang** [comment]
因为在手机设备上加载 Audio 资源所需要的时间比在电脑上来得长，所以此问题只有出现在手机设备上。
问题原因是 audioClip 的 loaded 状态不能在设置 _nativeAsset 时就被直接设置，而应该是在原生资源真正被加载完成后的执行回调里设置，否则会导致在手机设备（目前只有 Android 手机会有此问题）上第一次点击播放时无法播放音频。引擎修改方法如下：
<img width="692" alt="图片" src="https://user-images.githubusercontent.com/35944775/232368779-b1864023-cb6b-45c6-9a57-272b3db9ff60.png">
<img width="579" alt="图片" src="https://user-images.githubusercontent.com/35944775/232368837-07b00f2c-22a4-4c60-8ac0-5af48b876553.png">
