### ISSUE TITLE
dragoneBone挂点BUG

### ISSUE THREAD

**Issue by liujin1992112** [cocos/cocos-engine#8975]
在挂点上面绑定的子节点，并在子节点下添加物理引擎的碰撞器组件，会出现挂点下的子节点位置错误，在官网example-cases下的龙骨测试也遇到同样的问题（注意：必须要将物理引擎开启）

**Comment by zhefengzhang** [comment]
这个问题在 3.2.0 版本上没有复现哦~

**Comment by liujin1992112** [comment]
我采用的cocoscreator2.4.4版本，生成龙骨的挂点功能。现在creator.3.x 支持了龙骨自动生成挂点吗？如果有后期我用creator3.x版本测试一下
