### ISSUE TITLE
[3.2.0] GAME_SHOW 回调在微信小游戏平台没有返回值

### ISSUE THREAD

**Issue by zhefengzhang** [cocos/cocos-engine#8982]
小秘书工单：6767

https://developers.weixin.qq.com/minigame/dev/api/base/app/life-cycle/wx.onShow.html

![图片](https://user-images.githubusercontent.com/35944775/125724636-ffbf9a8a-0318-4a2b-982b-d44a0b348f49.png)

微信小游戏的 wx.onShow 接口是能获取参数返回值的。

**Comment by yeshao2069** [comment]
这个问题将在 3.4.0版本修复
修复PR https://github.com/cocos-creator/engine/pull/9661
可同步PR处理，或者升级到3.4.0版本(3.4.0正式版本还没有发布，敬请期待)

**Comment by yeshao2069** [comment]
下周一验证

**Comment by yeshao2069** [comment]
验证 3.4.0  修复了。(3.4.0正式版本还没有发布，敬请期待)
修复PR https://github.com/cocos-creator/engine/pull/9661/files
使用 v3.4.0-darwin-111508 并合并PR https://github.com/cocos-creator/engine/pull/9661/files

修复前
![181636961778_ pic](https://user-images.githubusercontent.com/14273437/141740707-7d62b2b3-1c27-4845-aac5-308d7afc3e7d.jpg)

修复后
![191636961779_ pic](https://user-images.githubusercontent.com/14273437/141740746-547bb54c-2eff-4a50-aaa1-19bdbe73f137.jpg)

**Comment by yeshao2069** [comment]
测试demo
[testGameShow340.zip](https://github.com/cocos-creator/engine/files/7536711/testGameShow340.zip)

该问题已经处理，该issue关闭。
