### ISSUE TITLE
[2.4.5] 嵌套 Prefab 在 Game.fire 会报错，附图 

### ISSUE THREAD

**Issue by az198071123** [cocos/cocos-engine#9009]
### Creator version?（版本号）
Cocos Creator 2.4.5

### Affected platform?（受影响的平台）
目前只在 Mac 測試過

### JavaScript output or error produced?（报错信息和调用栈）
![image](https://user-images.githubusercontent.com/5800906/126253235-a5acbd9a-cdb8-40a0-8161-2e5c01c40141.png)

**Comment by OnlyKoei** [comment]
你好，这个问题在文档中已经有提到了，你这边是开启了自动同步，所以会造成这个现象：
![image](https://user-images.githubusercontent.com/40415168/126256078-39287120-2764-4563-9c28-70791593b9d9.png)
文档链接：https://docs.cocos.com/creator/manual/zh/asset-workflow/prefab.html?q=

**Comment by az198071123** [comment]
你好，感谢回覆

还有一个问题：
这个 Prefab 我放在`另一个 Prefab` 中没事，只有放在 `.fire` 下会报错
请问是嵌套 Prefab 只能在 Prefab 中使用吗？

**Comment by OnlyKoei** [comment]
Prefab 界面，你如果再建个prefab A, 然后在card_back 节点上挂载同个脚本，一样是挂载不上 选择自动同步的 prefab A的；

**Comment by OnlyKoei** [comment]
具体原因主要是： 自动同步的预制中的组件无法引用该预制外的其他对象，就是上面发的截图，具体可看上面发的文档链接里的具体内容，这边这个 issue 就先关了
