### ISSUE TITLE
[3.2.0] The nearest filter for the texture does not work on the Web. 

### ISSUE THREAD

**Issue by mjshin82** [cocos/cocos-engine#9036]
![image](https://user-images.githubusercontent.com/22926212/126485253-e670dbe3-8ebf-443a-877c-4a22ea19007c.png)
The nearest filter for the texture does not work on the Web. 
It only works on the editor.

### Creator version?（版本号）
3.2.0/ 3.1.2

### Affected platform?（受影响的平台）

Web

### How to reproduce?（如何重现）
Every time

### JavaScript output or error produced?（报错信息和调用栈）

No

### Demo project?（demo 项目）

No

**Comment by xianyinchen** [comment]
use nearest filter, please uncheck the packable box of image. or it will use a global dynamic atlas with line filter.

<img width="1090" alt="WeChat5c391b29611a3bec3661229811809db2" src="https://user-images.githubusercontent.com/8321365/128989938-b097d72f-f656-487f-bde4-91e1641b313b.png">
