### ISSUE TITLE
触摸节点 紧接着 pauseSystemEvents 再释放触摸后导致所有触摸失效

### ISSUE THREAD

**Issue by ChasenTsai** [cocos/cocos-engine#9052]
### Creator version?（版本号）
2.4.4

### Affected platform?（受影响的平台）
Web & Android

### How to reproduce?（如何重现）

1. 给一个节点添加`TOUCH_START`事件，事件触发的方法是调用节点的暂停系统事件方法
2. 点击这个节点，即可重现

### JavaScript output or error produced?（报错信息和调用栈）
无报错信息

### Demo project?（demo 项目）
在任意可见的节点身上添加这个事件即可

```
node.on(cc.Node.EventType.TOUCH_START, () => {
    node.pauseSystemEvents(true)
})
```
我注意到 @PPpro 提交的RP：
 #8969 
我尝试了将它合并到我的版本中，但并不能解决这个问题

**Comment by OnlyKoei** [comment]
在那个 pr 的基础上，这边加个判断 
[CCEventManager.zip](https://github.com/cocos-creator/engine/files/6891203/CCEventManager.zip)，
![image](https://user-images.githubusercontent.com/40415168/127283751-aed0510e-39e2-44c0-8791-133075e5f344.png)
