### ISSUE TITLE
3.1.2 模型meta数据字段存在随机排序导致git差异更新

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#9124]
同一个版本，蓝色和绿色的两个字段位置出现调换

<img width="420" alt="wecom-temp-249707e0881a9c8df674f6cc6263b89c" src="https://user-images.githubusercontent.com/8321365/127978403-7d6f0b59-827b-43ce-9a43-405c04c1cafd.png">

**Comment by yeshao2069** [comment]
最新反馈:
这应该是一个 gltf，gltf 里导入的时候使用了 promise.all 乱序排列，而 meta 这个顺序依赖调用接口的顺序。在 3.3.0 已经进行处理。

**Comment by yeshao2069** [comment]
原小秘书工单：  7071
