### ISSUE TITLE
Loading bar in game release build is missing

### ISSUE THREAD

**Issue by wijesijp** [cocos/cocos-engine#9150]
### Affected platform?（受影响的平台）
Release build on all platforms

### How to reproduce?（如何重现）
Previous versions there is a loading bar in the release build of the game. With the new version this feature is missing.
In previous version it had;

```
function setLoadingDisplay () {
    // Loading splash scene
    var splash = document.getElementById('splash');
    var progressBar = splash.querySelector('.progress-bar span');
    onProgress = function (finish, total) {
        if (progressBar) {
            progressBar.style.width = percent.toFixed(2) + '%';
        }
       
    };
    splash.style.display = 'block';
    progressBar.style.width = '0%';

}
```
Using this loading bar could be adjusted.

May I know how to add something similar to the release build of Cocos Creator 3.2.0?
I assume it will be added to "application.js"?

**Comment by xianyinchen** [comment]
Please tell me which version is the previous version. 3.2.0 is no such code, if you add it, you can refer to the previous version.

**Comment by wijesijp** [comment]
@xianyinchen I was using 2.4.3 before switching to 3.2.0
All games i build before have the loading bar with logos.

I would like to do the same.

Can we do something similar in 3.2.0?

**Comment by xianyinchen** [comment]
Yes, you can, modify both the html code and application.js

**Comment by wijesijp** [comment]
can you please provide a code sample on how to change progress bar from application.js?
previous code to change the progress bar is missing in application.js now.

Not sure how to change application.js to detect loading progress...

**Comment by wijesijp** [comment]
@xianyinchen can you please provide some code sample showing how to do this in applicaiton.js ?

**Comment by xianyinchen** [comment]
The progress bar of the download progress is not implemented, this is determined not to provide the feature, this is not a problem, I will submit a suggestion and the engine group can discuss restoring the feature, [link](https://github.com/cocos-creator/3d-tasks/issues/8851). 

I can't provide such reference code at the moment, so propose you to refer to the index.html progress bar implementation and application.js loading resources implementation, through their own learning to modify the code, or send to the cocos forum, seeking help from others.
