### ISSUE TITLE
[2.4.6]IOS and Simulator error websocket receiver data Cocos creator 2.4.6

### ISSUE THREAD

**Issue by bluedoctorhazan** [cocos/cocos-engine#9180]
When I build my project with cocos creator 2.4.6, parse json string error, error for ios and emulator, android and website works well. 
I'm sure it's faulty, because when I build it with 2.4.5 version, it works well all platform.

**Comment by yeshao2069** [comment]
Can you provide a simple demo？

**Comment by yeshao2069** [comment]
https://forum.cocos.org/t/topic/120464

**Comment by bluedoctorhazan** [comment]
> https://forum.cocos.org/t/topic/120464

Yes, the same it

**Comment by bluedoctorhazan** [comment]
> https://forum.cocos.org/t/topic/120464

It only happen with cocos simulator and ios

**Comment by minnguyen0507** [comment]
@phamvansy Hi bro, Have you fixed the bug?

**Comment by bluedoctorhazan** [comment]
> @phamvansy Hi bro, Have you fixed the bug?

i'm in need of a new update to fix the bug

**Comment by xianyinchen** [comment]
You can apply this PR to current native code, and try.
https://github.com/cocos-creator/engine-native/pull/3789
