### ISSUE TITLE
调试断点对不上 

### ISSUE THREAD

**Issue by 958877748** [cocos/cocos-engine#9215]
### Creator version?（版本号）2.4.5

tmx-layer-...js   这个文件   fillbuff 方法

**Comment by yeshao2069** [comment]
你是在Chrome上面直接调试的么？

**Comment by 958877748** [comment]
是的

**Comment by yeshao2069** [comment]
试一下把chrome 开发者模式->设置里面，关闭 javascript 的 sourcesmap，然后在 cc.js 或者 preview里面断点你需要的代码看看

**Comment by 958877748** [comment]
嗯   可以了  谢谢
