### ISSUE TITLE
AnimationClip.createWithSpriteFrames 方法内部生成的动画数据并没有加入到 Clip 里面

### ISSUE THREAD

**Issue by dorthl** [cocos/cocos-engine#9219]
https://github.com/cocos-creator/engine/blob/fbd92ab01ffc4a40c42bb5342872ee0443432284/cocos/core/animation/animation-clip.ts#L104

是否缺少clip.addTrack(track);?

**Comment by OnlyKoei** [comment]
已修复。
#9244
