### ISSUE TITLE
原生上不支持Spine局部换装问题(使用图片局部换装)

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#9221]
用户反馈：

使用多个attachment换装，在原生上， getAttachment接口找不到，从而没办法在原生上实现spine局部换装。

https://blog.csdn.net/xjw532881071/article/details/107766975

经过测试移植发现，现有的JSB自动绑定，存在问题。

**Comment by zhefengzhang** [comment]
skin 的 getAttachment 是有实现 jsb 绑定的
![图片](https://user-images.githubusercontent.com/35944775/130332920-a516b782-9687-42b3-b8e5-120266abab62.png)
目前通过 getAttachment 和 setAttachment 是能够实现 web 和 原生平台的局部换装效果的，只不过相比使用贴图来替换插槽的方案，会显得游戏包体更大。所以目前还无法做到的只是原生平台的 spine 贴图换装方案。

**Comment by zhefengzhang** [comment]
这个就作为后续的预研方案吧，这个不是客户小秘书反馈的问题。我们下周一回来还是着重解决下面这个 issues 问题。
https://github.com/cocos-creator/engine/issues/9225

此 issues 关闭。
