### ISSUE TITLE
[2.4.x]  scrollview下的 content 加 layout组件，Grid模式下, StartAxis=VERTICAL,  有1个隐藏子item 必现堆栈溢出

### ISSUE THREAD

**Issue by OnlyKoei** [cocos/cocos-engine#9249]
测试demo:
[LayoutStackOverflow.zip](https://github.com/cocos-creator/engine/files/7045553/LayoutStackOverflow.zip)

报错截图：
<img width="610" alt="83ea6734990c27baa5165d13cca7c31" src="https://user-images.githubusercontent.com/40415168/130761904-bf892851-a79b-4aaa-b994-4f3b67f9c5cf.png">

**Comment by SantyWang** [comment]
cocos-creator/engine#9914，此 pr 已修复
