### ISSUE TITLE
骨骼动画复用，动画显示异常

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#9253]
用户反馈  小秘书工单： 7454

骨骼动画，复用的时候，骨骼一样的 动画模型boy 和 动画模型 girl

boy 里面复用  girl里面的动画animation，会导致显示异常的问题。

**Comment by yeshao2069** [comment]
网格形状不同，骨骼动画不能复用。

**Comment by yeshao2069** [comment]
用户反馈：

1、骨骼一样，mesh（角色）不一样，骨骼是不可以复用的，需要重新配置权重。
2、骨骼一样，mesh（角色）不一样，但是已经绑定好了，权重也配置好了，动画是可以复用的，目前的流程就是这样。

**Comment by junlas** [comment]
今天和我们设计师讨论，在设计师 Blender 那边的骨骼相对的坐标，男孩和女孩是一样的值，尽管mesh不一样，按照设计师的思路，骨骼动画针对的 Blender 中的权重，所以他们在 Blender 中不同模型可以共用同一个动画。我想知道因为cocos中无法共用.animation动画文件，为什么导入到cocos里以后，节点上显示的骨骼结点的坐标，和 Blender 中的骨骼坐标差异那么大，应该就不是同一个节点坐标的东西？

**Comment by junlas** [comment]
和小秘书沟通的结果是：这个问题是个bug，暂时没有修复方案，需要等待引擎开发人员进行修复。
---- 非常关心这个问题大概在哪个版本中会修复呢？能给个大概计划的时间吗？

**Comment by zhefengzhang** [comment]
模型渲染异常的问题可以提高优先级处理，大概率会在 3.4 版本解决，3.4 预计在 10 月份发布。

**Comment by zhefengzhang** [comment]
一旦有修复方案，我们会第一时间发上来的。

**Comment by yeshao2069** [comment]
你好，经过和我们的工程师沟通以及排查分析。现在有几个反馈同步给你：
1 目前的骨骼动画复用的方式不推荐这么使用，会出现一些问题。
正确的使用方式是：导出一个骨骼动画 A，如果需要复用一个骨骼动画B.animtion，那么你可以在A的基础上，导出一个不带骨骼模型的 animation即可，然后在A上复用B

2 我们工程师，通过 unityce来测试你的这个demo，目前也是会有问题的。
![捕获](https://user-images.githubusercontent.com/14273437/132158199-f6bdcc12-e47e-4b9f-b579-99334b6ed474.PNG)

**Comment by junlas** [comment]
好的，我和我们的设计师再次反馈一下。
