### ISSUE TITLE
UV贴图更改TilingOffset不循环

### ISSUE THREAD

**Issue by yansixing** [cocos/cocos-engine#9254]
### Creator version?（版本号）
Cocos Creator 3.0.0

### Affected platform?（受影响的平台）

web（Mac环境下Chrome测试）
### How to reproduce?（如何重现）

！！！注意，编辑器界面看起来是没问题的，必须是运行场景时复现bug
修改编辑器设置的功能裁剪引发的bug，勾选再取消之后setting.json自动保存，退出cocos重新打开就不行了
![image](https://user-images.githubusercontent.com/10561285/130962510-52b9f705-9ab1-485d-aabf-dab4965ad749.png)
![image](https://user-images.githubusercontent.com/10561285/130962589-ed545ce2-b3a2-47fe-b4c5-daf50fa42971.png)

![image](https://user-images.githubusercontent.com/10561285/130961215-10e4da65-652b-48d8-a841-3449342a3062.png)

### Demo project?（demo 项目）

[UVBugReport.zip](https://github.com/cocos-creator/engine/files/7059615/UVBugReport.zip)

**Comment by yeshao2069** [comment]
感谢反馈，你这个不是bug.

在编辑器上生效，web预览不生效，是你的纹理贴图的大小是 1280 * 1280，不是2次幂，在运行时 repeat 模式自动切换成了 clamp-to-edge模式，导致的tillingoffset等属性失效了。这边也有提示，你需要修改你的纹理贴图即可。

![image](https://user-images.githubusercontent.com/14273437/131453177-18304359-7e7a-41b9-84bf-4b98ee2c5af3.png)

这边简单修改了一下你的贴图  为1024 * 1024 (裁剪了)，验证OK。
[UVBugReport.zip](https://github.com/cocos-creator/engine/files/7081774/UVBugReport.zip)
