### ISSUE TITLE
3.3.0 预置组件嵌套的BUG

### ISSUE THREAD

**Issue by hjoeson** [cocos/cocos-engine#9258]
预置组件A嵌套到B里，在B中修改A中子Node的尺寸，保存后没有生效（反而使得该预置组件的最后一个Node的尺寸发生了变化）

![image](https://user-images.githubusercontent.com/6767087/131208432-ad2e33b2-7f0f-46b3-9654-3cadaf920f7d.png)

如上图：
我修改了dialog_inner的宽度，保存后，dialog_inner的宽度没变，而zhuangshi_2 这个node的宽度变了。。。

**Comment by OnlyKoei** [comment]
论坛上已回复，这边先关了。
https://forum.cocos.org/t/topic/120284/7
