### ISSUE TITLE
文档里函数的返回值是用冒号后面最后一个词自动标记的吗? 

### ISSUE THREAD

**Issue by CocosGames** [cocos/cocos-engine#9259]
https://github.com/cocos-creator/engine/blob/f09a8e444973dc63059622d31dc97dfb28e542ca/cocos/core/director.ts#L596
这样就会出现像
![image](https://user-images.githubusercontent.com/42052366/131217623-3cb9a124-368b-45b7-a321-a90df3890273.png)

该返回Scene的写成返回void的情况.

**Comment by yeshao2069** [comment]
冒号后面的 返回值，是函数的返回值的类型定义。如果你放着为空，则会根据类型自动定义。比如
```ts
public  getA () {
   return 'aaa';
}
```
则返回值默认为 string， 你要定义
```ts
public  getA () : string {
   return 'aaa';
}
```
也是挺好的。

另外
```ts
 public getScene (): Scene | null {  xxx }
```
这边获取的Scene 是 有可能 为空的情况，所以你在使用的时候需要做一下 判空处理。
比如
```ts
director.getScene()!.getChildByName('Canvas)!;
