### ISSUE TITLE
blender导出的模型显示异常

### ISSUE THREAD

**Issue by yeshao2069** [cocos/cocos-engine#9262]
blender导出的模型，显示异常，显得很油腻。

**Comment by yeshao2069** [comment]
因为导入fbx phong材质的时候,  编辑器 会自动使用builtin-default PBR材质, 但phong材质的参数并没有迁移过来, 应该使用roughness = 1.0 - pow(2.0, -10 / shinness)将fbx材质中的高光幂FbxSurfacePhong.Shininess转换到粗糙度再设置给builtin-default

**Comment by junlas** [comment]
同样最想关心：编辑器修复这个bug有大概的计划时间吗？

**Comment by junlas** [comment]
另外，想问下cocos那边是怎么判断给的模型文件是phong还是pbr模型呀？麻烦告之，谢谢

**Comment by yeshao2069** [comment]
同样最想关心：编辑器修复这个bug有大概的计划时间吗？
----  已经在确定问题，尽快同步给你

**Comment by yeshao2069** [comment]
blender导出的 FBX或者 glTF模型，显示异常的问题，目前已经计划在 3.4版本。

**Comment by junlas** [comment]
Animation Layer 也是在3.4版本中支持，对吗？

**Comment by yeshao2069** [comment]
Animation Layer已经在3.4版本的计划中了。

**Comment by yeshao2069** [comment]
关于 blender ( DCC支持)，目前已经规划在3.4.0提供支持，此单先行关闭。谢谢。

**Comment by zhefengzhang** [comment]
@junlas Hi, regarding the issue of rendering exceptions for blender exported models, the editor will provide a better import mechanism in version 3.5.1. Version 3.5.1 is expected to be released in May 2022.
