### ISSUE TITLE
[Error][CC3.3.0] Webview's onJsCallback Crashed the Game

### ISSUE THREAD

**Issue by ZeroHackeR** [cocos/cocos-engine#9275]

**Comment by yeshao2069** [comment]
Thanks for the feedback, I can reproduce this crash problem on your demo.   version 3.3.0
Please try to modify this, and then try to see if it works.
CocosWebView.java line 156
```
CocosHelper.runOnGameThread(new Runnable() {
                  @Override
                  public void run() {
                      CocosWebViewHelper._didFailLoading(mViewTag, failingUrl);
                  }
              });
```
![image](https://user-images.githubusercontent.com/14273437/131979364-ef431515-6653-4cbc-ae8c-a928339aa471.png)

**Comment by ZeroHackeR** [comment]
> CocosWebView.java line 156

Sorry. I could not fix it :frowning:
Might be I was fixing the wrong file?

Is that the right path?
/Applications/CocosCreator/Creator/3.3.0/CocosCreator.app/Contents/Resources/resources/3d/engine-native/cocos/platform/android/java/src/com/cocos/lib

**Comment by yeshao2069** [comment]
Link : https://discuss.cocos2d-x.org/t/error-cc3-3-game-crash-on-webviews-onjscallback/54422

**Comment by yeshao2069** [comment]
Can you provide this CocosWebView.java ?

**Comment by ZeroHackeR** [comment]
> Can you provide this CocosWebView.java ?

I was just trying to add try/catch so that we can trace the error and prevent the app from crashing due to unexpected error.
But, I didn't get anything in the log.
Perhaps, I modified the wrong file?

```
         @Override
         public void onReceivedError(WebView view, int errorCode, String description, final String failingUrl) {
             super.onReceivedError(view, errorCode, description, failingUrl);
            
             try{
              CocosHelper.runOnGameThread(new Runnable() {
                  @Override
                  public void run() {
                      CocosWebViewHelper._didFailLoading(mViewTag, failingUrl);
                  }
              });
             }catch( Exception ex){
                 Log.d(TAG, "onReceivedError ERROR" + description + " " + failingUrl);
             }
         }
```

**Comment by yeshao2069** [comment]
Error tips?

**Comment by ZeroHackeR** [comment]
> Error tips?

I got nothing in the log. I think, I'm modifying the wrong file. 
So, can you tell me which file to modify (I used Cocos Dashboard and Installed Creator 3.3, not complied from source)?

**Comment by yeshao2069** [comment]
Sorry, I should be the wrong number of lines in the screenshot, you can refer to this to modify it.
[CocosWebView.java.zip](https://github.com/cocos-creator/engine/files/7119390/CocosWebView.java.zip)

**Comment by ZeroHackeR** [comment]
> Sorry, I should be the wrong number of lines in the screenshot, you can refer to this to modify it.

Thanks! 

But, we are not busy with project deadline and can not look into it yet. :(

**Comment by yeshao2069** [comment]
You can use a modified java to do a comparison or direct replacement to see if it can be fixed

**Comment by truongpd88** [comment]
no it's wrong place, line 112 it's run on UI thread, it should run on game thread:

CocosHelper.runOnGameThread(new Runnable() {
