### ISSUE TITLE
[1.9.x]   ios14 safari 旋转 横屏后 不全屏

### ISSUE THREAD

**Issue by gowdzy** [cocos/cocos-engine#9284]
### Affected platform?（受影响的平台）
ios 14.x safari 浏览器 

### How to reproduce?（如何重现）
空项目旋转横屏后,底部有灰边，如果修改了 __BrowserGetter.availWidth 和  __BrowserGetter.availHeight 返回 window.innerWidth ,window.innerHeight 的话，就显示了地址栏无法全屏了（横屏下），非ios14.x 不会有该问题
请问能否提供方法，或者思路 谢谢

**Comment by xianyinchen** [comment]
可以加了这个 meta 信息后，屏幕旋转时，就不会下拉地址栏，但是整个网页文档的高度又是减去地址栏后的高度，导致高度适配上的不正确行为，这个是iOS的BUG, 无法解决.
``` html
<meta
    name="viewport"
    content="width=device-width,user-scalable=no,initial-scale=1, minimum-scale=1,maximum-scale=1"
/>
```

**Comment by yeshao2069** [comment]
https://discuss.cocos2d-x.org/t/black-screen-appears-in-bottom-when-rotated-from-portrait-to-landscape/54706
