### ISSUE TITLE
[3.3.0]引擎改为统一在主循环中处理输入事件后，微信小游戏平台上click事件无法调起订阅消息

### ISSUE THREAD

**Issue by daxpot** [cocos/cocos-engine#9285]
### How to reproduce?（如何重现）

1. 创建一个结点做按钮
2. 在结点上添加Button组件，并添加click事件
3. click事件回调函数中调用微信订阅消息接口requestSubscribeMessage

### JavaScript output or error produced?（报错信息和调用栈）

由于在3.3.0中做了（输入事件以前是接收到事件就进行派发，如果事件响应逻辑复杂可能会影响到帧回调，导致帧率不稳，v3.3 已调整为帧间记录事件队列，统一在主循环中处理事件队列。）这个改动，
导致现在click事件调用wx.requestSubscribeMessage接口都会报错，错误信息为 requestSubscribeMessage:fail require user interaction (only in touchend event)

**Comment by xianyinchen** [comment]
问题已提交给引擎组，有处理结果会继续同步。
