### ISSUE TITLE
节点tween动画的同时改变节点的position，节点显示位置不改变，tween动画停止的时候才能改变位置

### ISSUE THREAD

**Issue by amit-gshe** [cocos/cocos-engine#9294]
### Creator version?（版本号）
3.3.0

### Affected platform?（受影响的平台）

Windows Editor / Web

### How to reproduce?（如何重现）
对节点使用tween动画的同时更新节点的位置

### JavaScript output or error produced?（报错信息和调用栈）

没有报错

### Demo project?（demo 项目）

https://github.com/amit-gshe/cocos-tutorial

**Comment by yeshao2069** [comment]
是这个link https://forum.cocos.org/t/topic/120795 吧

**Comment by yeshao2069** [comment]
感谢反馈，这个确实是有这个问题的。
原因是，3.x版本的 tween.by \ tween.to 中缓动的是 node某个属性，修改position的时候，你获取的是当前的node.position.x，那么这个数值就被保存着，所以就会在原地不会移动(看起来就像无效一样)

![image](https://user-images.githubusercontent.com/14273437/132292298-0a673b16-0397-422f-97b7-f59210f99cdf.png)

**Comment by amit-gshe** [comment]
那个地方按照tween().by的定义应该是`{ position: v3(0, -this._jumpHeight, 0) }`，就像这样：
https://github.com/amit-gshe/cocos-tutorial/blob/8477ec8e146f4fdca73b0aeeeeda2383459552c4/assets/scripts/Player.ts#L44-L60
但是还是不行。

请问下3.0版本应该怎样在tween动画的时候修改节点的位置呢？

**Comment by yeshao2069** [comment]
再套一个父节点，缓动父节点Y，设置子节点X

这个是个可行的方案

**Comment by yeshao2069** [comment]
目前的处理方式：
可以在节点A上挂载一个父节点B，父节点做缓动动画，节点A做左右的移动动画。

这个的原因是因为3.x版本去掉了 只修改部分属性的接口导致的问题，比如去掉了 positionX, positionY等属性，只保留了position, 需要同时修改x,y,z坐标，在和tween缓动一起使用的时候，就会产生问题，这个已经反馈给引擎组，建议重新开放node上的一些接口。

该issue关闭，感谢反馈。
