### ISSUE TITLE
[建议]  自动图集的配置信息直接记录到 对应的.pac文件里

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#9316]
### Creator version?（版本号）
2.4.x

### Affected platform?（受影响的平台）
all

### 建议

目前 自动图集的配置信息 记录在了 .pac文件 对应的 .pac.meta 文件里.
如果 一个项目里 有多个 配置信息相同的自动图集, 开发者没办法通过 复制 pac文件的方式来复制图集信息.
而复制meta文件 又会产生类似 uuid冲突的问题. 
(虽然 ide可以自动解决冲突, 但是如果在非ide环境 ,比如命令行脚本, 里就不行了.而且在IDE里不支持复制pac.meta文件)

建议 自动图集的配置信息直接记录到 对应的.pac文件里.

**Comment by yeshao2069** [comment]
感谢你的反馈，你的宝贵意见已经提给引擎组，该issue 暂时先关闭。
