### ISSUE TITLE
UBOBinding没有offset参数？

### ISSUE THREAD

**Issue by jcyuan** [cocos/cocos-engine#9323]
不知道是我没看到还是本来就没有。
多个shader的ubo共用一块float32array时，在绑定
descriptorSet.bindBuffer时，需要提供数据在这块内存中的偏移。
目前貌似没法指定。
![}4DUFY}LAVDQ0)5I%5({A5F](https://user-images.githubusercontent.com/850854/132969778-f29b2878-5b8d-4d0b-ab06-56d01836b298.png)
(图为webgpu原生api，ubo内存可以全部放在同一块内存中)

**Comment by xianyinchen** [comment]
接口有提供index参数，看下是否满足你的需求
descriptorSet.bindBuffer (binding: number, buffer: Buffer, index = 0)

**Comment by jcyuan** [comment]
> 接口有提供index参数，看下是否满足你的需求
> descriptorSet.bindBuffer (binding: number, buffer: Buffer, index = 0)

感谢回复，刚刚具体看了下源码，这个index是指定对于这个binding在descriptorSet中的偏移，而不是ubo的数据偏移。

不过我已经知道答案了哈，需要使用gfx.BufferViewInfo就可以了。

1, 先创建无偏移的整块内存

    const ubo = device.createBuffer(new BufferInfo(....));

2, 然后再通过view来创建所需需的偏移ubo即可（内存是指向的同一块地址）

    const subUbo1 = device.createBuffer(new gfx.BufferViewInfo(ubo, 16, 4);

就可以了！cocos 牛b 👍

**Comment by yeshao2069** [comment]
感谢你的方案。
