### ISSUE TITLE
关于CCComponentEventHandler的一些问题

### ISSUE THREAD

**Issue by JimsC** [cocos/cocos-engine#933]
我在使用cocos-creater的时候，也想用到CCComponentEventHandler一样的效果，就是第一个属性选择了之后，根据第一个属性列出可以选择的第二个属性，选择了第二个属性之后，根据第二个属性列出可以选择的第三个属性，但是看了代码，好像并没有给出如何操作的，我尝试用notify来改动属性的值，也没有成功，请问有什么办法吗?

**Comment by pandamicro** [comment]
目前不支持这样的动态枚举类型
