### ISSUE TITLE
2.4.5 动态图集 无法合并 过滤模式=Point 图片

### ISSUE THREAD

**Issue by 958877748** [cocos/cocos-engine#9336]

**Comment by 958877748** [comment]
可真是为难做像素游戏的了

**Comment by yeshao2069** [comment]
你这个是怎么验证的？

**Comment by yeshao2069** [comment]
用2.4.5版本试了一下，POINT 模式 是可以合批的吧。

你需要设置一个自动图集  AutoAtlas，然后发布后看看。 我简单测试了一下，是有效果的。

[NewProject_30.zip](https://github.com/cocos-creator/engine/files/7189517/NewProject_30.zip)

**Comment by 958877748** [comment]
不是这个  是运行时 动态合图

**Comment by yeshao2069** [comment]
看看，有没有demo 可以看一下？

**Comment by yeshao2069** [comment]
经过测试 在2.4.5、2.4.6版本上，确实 在Point的过滤模式下，动态图集无法合并，我已经将这个反馈给引擎组，感谢你的反馈，该issue 暂时关闭。如果后续有更多的反馈，我会继续追加在这个issue上，感谢支持。
