### ISSUE TITLE
[3.3] 但图片资源丢失后，建议优化提示信息

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#9353]
3.3 版本如果出现图片丢失，只会打印引用该资源的prefab文件路径，建议添加节点路径信息，方便定义问题。
![image](https://user-images.githubusercontent.com/8321365/133884728-a09f5e2e-3d28-4fc9-b549-8c36aa8e281e.png)

**Comment by jareguo** [comment]
列为 22 年重点目标之一。由于不属于重大缺陷，具体实现内部进行跟踪，本工单先关闭。

**Comment by jareguo** [comment]
已在 3.5 优化
