### ISSUE TITLE
【需求】希望 3.x 系列提供 skew 变换组件.

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#9356]
虽然 skew 可以用 node 3d 来替代
但是在2D游戏和 2D动画里, skew 有着不可替代的简单易用且直观, 对2D动画制作人员也更友好.
希望 cocos 3.x 能提供一个 可选组件 (作用于node 或者 渲染组件上) , 来实现 2.x时代的 skew变换.

**Comment by yeshao2069** [comment]
感谢大城小胖的建议，这个需求已经收集并反馈了给引擎组了。

目前建议：
单独添加一个 Skew 组件，参数和 2D 原来的用法一致。组件提供通用的 transformVertex 或 transformVertices 之类的 成员 函数 API，用来对任意顶点进行 skew 变换。2D 渲染组件或 assembler 在顶点计算的最后一步，通过这个 API 实现 skew 变换。目前只要支持 Sprite 就行，之后可以根据用户反馈，在 Label 之类的其它组件上也添加支持。

此issue暂时关闭。
