### ISSUE TITLE
【性能建议】物理同步接口需要判断当前位置及旋转是否与当前值相同

### ISSUE THREAD

**Issue by jcyuan** [cocos/cocos-engine#9385]
场景在子弹多的时候CPU就上来了。调试的时候才发现每帧node的dirtyFlag一直是3 (position | rotation)，但是我并没有设置过rotation，而且静态的刚体也一直在被更新。所以才发这个issue。建议官方更新一下，位置没变或旋转没变时忽略设置。

https://github.com/cocos-creator/engine/blob/33375839a602133d13c370b6e189367f0428b6c6/cocos/physics-2d/box2d/physics-world.ts#L213-L222

其实这个判断应该要放在node基类里面，
所有设置位置及旋转的接口里最好判断一下是否和当前值相同，
相同时直接return不设置dirtyFlag，否则造成太多不必要的matrix计算。

https://github.com/cocos-creator/engine/blob/33375839a602133d13c370b6e189367f0428b6c6/cocos/core/scene-graph/node.ts#L750-L766

目前我在用box2d，但是3d的物理同样有这问题。
我自己在自己的游戏逻辑代码内全部加了判断如果位置及旋转相同时忽略设置，但是引擎的代码就没办法了，目前每帧每个刚体都设置RTS的dirtyFlag即使我没改位置也没改旋转，比如静态刚体。。

这个问题我提交PR应该没有意义，因为修改上面的2d物理同步这里无法彻底解决问题，最好还是应该在node内判断，个人也没有能力修改node这么核心的类，希望官方能采纳建议，谢谢。

**Comment by yeshao2069** [comment]
使用的版本？

**Comment by jcyuan** [comment]
> 使用的版本？

3.3.1

**Comment by yeshao2069** [comment]
感谢你的反馈，该优化建议已经提交给引擎组，谢谢。

**Comment by yeshao2069** [comment]
已经把该需求提交给引擎组，该issue暂时关闭，如果有最新的反馈，我会继续同步在该issue，感谢反馈。

**Comment by SantyWang** [comment]
请问下你的使用场景中，很多情况下旋转是一样的，然后需要重新 setRotation 么
