### ISSUE TITLE
JSCallback未接受到任何参数，与文档描述不同

### ISSUE THREAD

**Issue by patrickyyang** [cocos/cocos-engine#9402]
Cocos Creator version?（版本号）
3.3.0

### Affected platform?（受影响的平台）
iOS&Android

### How to reproduce?（如何重现）
根据官方webview示例，无法从webview接收参数
https://docs.cocos.com/creator/3.3/manual/zh/ui-system/components/editor/webview.html
从函数声明上看，callback未接受任何参数，实际调试也没有接收到参数。
public setOnJSCallback(callback: () => void): void;

**Comment by yeshao2069** [comment]
测试了一下，好像确实有点问题。需要再看一下。

**Comment by yeshao2069** [comment]
你好，经过验证，这个参数实际上是生效的。
1 模仿文档上的写法，写入 function jsCallback (target: any, url: string) 以及 设置 webview.setJavascriptInterfaceScheme(scheme) 和  setOnJSCallback(jsCallback as any) 接口
![image](https://user-images.githubusercontent.com/14273437/136506197-c8e1d65c-2b9a-4c9d-bef6-2e3075a0d842.png)

2 如果你使用的是 vscode的话，你可以安装liveserver插件来模拟本地服务器，或者自己本地开启一个web的服务器，写入以下代码
这个是由于webview需要点击html上的按钮切换的时候，去响应上面的jsCallback回调。(记住因为是 安卓或者ios真机调式去访问web服务器，如果是127.0.0.1的本地ip访问会受限，需要改为局域网IP，如192.168.xxx)
![image](https://user-images.githubusercontent.com/14273437/136506641-4056b4ce-fc6e-4396-954a-f71e421484d7.png)

3 发布安卓或者ios后，可以使用chrome的devtool工具去捕获  ，https://docs.cocos.com/creator/3.3/manual/zh/editor/publish/debug-jsb.html#windows-%E5%B9%B3%E5%8F%B0%E5%8F%8A-mac-%E5%B9%B3%E5%8F%B0%E8%B0%83%E8%AF%95

4 输出结果
![image](https://user-images.githubusercontent.com/14273437/136507171-ebd0973e-2eeb-42ef-988d-bd29f24d795e.png)

备注：发布后遇到相关报错，需要修改一下  CocosWebView.java相关代码
![image](https://user-images.githubusercontent.com/14273437/136507290-46a80836-fca3-4e29-9c5d-d801a9e7984d.png)
public boolean shouldOverrideUrlLoading(WebView view, final String urlString) 接口下，activity.runOnUiThread修改为CocosHelper.runOnGameThread
![image](https://user-images.githubusercontent.com/14273437/136507487-627c792c-c91b-4ec5-9100-1507d284c8e9.png)

**Comment by yeshao2069** [comment]
[webviewTest.zip](https://github.com/cocos-creator/engine/files/7308962/webviewTest.zip)

附上测试的demo, 该issue暂时关闭。
