### ISSUE TITLE
[3.3.1]安卓平台无法监听按键事件

### ISSUE THREAD

**Issue by billyplus** [cocos/cocos-engine#9408]
### Creator version?
3.3.1

### Affected platform?
Android

### How to reproduce?
在代码中监听按键事件，打包安卓包，按返回键没有反应。
```javascript
systemEvent.on(SystemEvent.EventType.KEY_UP, this.onKeyUp, this);
```
跟踪发现在`pal/input/native/keyboard.ts`文件`KeyboardInputSource`这个类里面，
```javascript
this.support = !systemInfo.isMobile;
```
在原生平台中，support=false导致不监听按键事件。

**Comment by yeshao2069** [comment]
有没有Demo 验证看看？

**Comment by yeshao2069** [comment]
试试   https://forum.cocos.org/t/android-9-api-28/82215  上的方案 看看

**Comment by yeshao2069** [comment]
感谢反馈，和相关负责人确认了一下，这个是由于 之前的实现没有考虑到移动端的按键。已经内部反馈了，会安排在之后的版本适配。该issue暂时关闭。

**Comment by yeshao2069** [comment]
最新反馈：目前暂定在3.5版本修复这个问题。

**Comment by PPpro** [comment]
会在 3.4.1 上修复，感谢反馈
