### ISSUE TITLE
[Bug][Skeleton] The enableBatch option is not work correctly on all platforms

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#9446]
### Creator version?（版本号）
3.3.1

### Affected platform?（受影响的平台）

Web: show empty animation
Emulator, Android, IOS: Increase draw calls when spawn the same animations.
### How to reproduce?（如何重现）
The enableBatch option is disabled from Spine Editor windows, but not on api script, we enableBatch using script at onLoad callback.

demo: [SpineSkeleton_enableBatch_notwork.zip](https://github.com/cocos-creator/engine/files/7308377/SpineSkeleton_enableBatch_notwork.zip)

- Download and open demo project.
- Hit run on web browser, there is no animation displayed.
- Hit run on emulator, and pay attention on draw calls value

- Hit 'Hide Anim' button, one animation is hidden and the draw calls is reduced.
- Hit 'Show Anim' button, one animation is showed and the draw calls is increased.

Expectation: 
- The animation still displayed on web browser when hit play.
- When add the same skeleton animation with enableBatch option is enabled, draw calls not be increased.
animation on the scene.

Actual: 
- The animation displayed at empty on web browser.
- The draw calls is increased by adding the same spine animation to the scene.

**Comment by yeshao2069** [comment]
Thanks for the feedback, due to the 3.x and 2.x engine architecture refactoring, spine's enableBatch is currently temporarily not available for batching, we have planned to refactor this, and plan to arrange to provide a new batching solution in version 3.5. Thanks for your support.
