### ISSUE TITLE
不修改任何东西, 每次构建都有文件名的hash值发生变化

### ISSUE THREAD

**Issue by loohoo** [cocos/cocos-engine#9459]
### How to reproduce?（如何重现）
1. 创建 ts hello world 项目
2. 将若干项目文件夹设置成remote bundle (可能不是重现必要条件,但是现象告诉我对结果有影响)
3.构建-构建-构建 对比. 文件名中的hash有变化 但是文件内容前后一致. (android,win or mac等native 构建)

必现!

**Comment by yeshao2069** [comment]
上个问题，他发布的是 同一个平台，在命令行面板和构建面板，打包出来的文件md5不一致的问题。
https://github.com/cocos-creator/engine/issues/7722

你这个构建的比较是：   你使用一个工程然后，分别构建android、windows\mac 后，去比较他们的同名文件，这样子的吗？

**Comment by yeshao2069** [comment]
https://forum.cocos.org/t/topic/122596/10  看看这个  是不是和你的问题是一样的

**Comment by yeshao2069** [comment]
这个问题，是个bug，将会在2.4.7版本解决。感谢你的反馈，可以留意2.4.7版本发布后，帮忙验证，感谢。该issue暂时关闭。

**Comment by loohoo** [comment]
> 
> 
> 上个问题，他发布的是 同一个平台，在命令行面板和构建面板，打包出来的文件md5不一致的问题。 #7722
> 
> 你这个构建的比较是： 你使用一个工程然后，分别构建android、windows\mac 后，去比较他们的同名文件，这样子的吗？

单纯地构建一种目标平台, bundleXX/config.xxx.json  里面的数组顺序每次都不一样 导致md5 计算出来並. 你们的构建脚本改了逻辑.
