### ISSUE TITLE
[CameraViewPort] Low fps on native build (android/ios) if the scene contains big renderer components

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#9468]
### Creator version?（版本号）
3.3.1

### Affected platform?（受影响的平台）

Android, IOS
### How to reproduce?（如何重现）
- Download the demo project and open with Cocos Creator 3.3.1.
- Build to Android or iOS (debug mode), the project contains an already built apk that used on video.
- Run the game on device, press ZOOM IN or ZOOM OUT button
- Looking for the fps changes. 

Expectation: If the scene contains multiple super big renderer components, in my case is Sprite, Skeleton. The fps must not be dropped. In my example, it dropped from 60 fps to 37 fps.

Actual: If the scene contains more than two renderer components (big background, and big skeleton), and they are out of the current camera view port. The fps will be crazy dropped.

Big background and effect may required for multiple resolution game.

### Demo project?（demo 项目）

[CameraViewPortPerformanceIssue.zip](https://github.com/cocos-creator/engine/files/7329848/CameraViewPortPerformanceIssue.zip)

https://user-images.githubusercontent.com/18746281/136956004-8f664e72-73ec-48f5-88c5-dc8d683ff9e0.mp4

![high fps](https://user-images.githubusercontent.com/18746281/136956024-076255f3-0314-4a17-b018-45c687b34b79.png)
![low fps](https://user-images.githubusercontent.com/18746281/136956027-86e18c8e-8c65-452b-b1fd-e48c82a67c10.png)

**Comment by yeshao2069** [comment]
The result of the test demo is the same as you mentioned above, I will confirm it tomorrow

**Comment by yeshao2069** [comment]
Thank you for your feedback, this problem has been submitted to the relevant engineers to investigate

**Comment by thinhlv** [comment]
> submitted

**Comment by thinhlv** [comment]
I've tested this issue again, event if the renderers component still small and fit inside the camera. This issue still accured.
The bigger sprites are the lower fps is. My scene contains only 16 sprites.

Install the apk. 
- press the "Smaller" the fps will be increased
- press the "Bigger" the fps will be decreased
[CameraViewPortPerformanceIssue.zip](https://github.com/cocos-creator/engine/files/7361916/CameraViewPortPerformanceIssue.zip)

**Comment by yeshao2069** [comment]
Thank you for your feedback again, has been synchronized to the relevant colleagues to deal with

**Comment by yeshao2069** [comment]
你好，这个问题确实存在，也已经提交到引擎组处理了，但是很抱歉，目前没有处理进度。该issue会暂时先关闭，后续有处理进度，我会继续补充在这个issue上。再次感谢你的反馈和对creator的支持。

Hello, this issue does exist, and has been submitted to the engine group to deal with, but I'm sorry, there is no processing progress. The issue will be closed for now, and I will continue to add to this issue when there is progress. Thanks again for your feedback and support to creator.

**Comment by pandamicro** [comment]
@thinhlv Which device have you tested on ?
