### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by dhb118** [cocos/cocos-engine#9497]
https://github.com/cocos-creator/engine/blob/33375839a602133d13c370b6e189367f0428b6c6/cocos/core/pipeline/instanced-buffer.ts#L53

this Map will never remove after Pass destory.

**Comment by yeshao2069** [comment]
Which version are you using?

**Comment by dhb118** [comment]
v3.2

**Comment by yeshao2069** [comment]
Thank you for your feedback, I confirmed in the latest version 3.4.0, this part of the code has not been modified, has been internal feedback, thanks

**Comment by yeshao2069** [comment]
This issue has been internal feedback, we will analyze this issue, if confirmed as a bug, we will fix it in time, thank you for your feedback, this issue is closed for now.

**Comment by yeshao2069** [comment]
fixed in 3.4.0

https://github.com/cocos-creator/engine/pull/9605
