### ISSUE TITLE
[3.3.1] Xcode13，构建iOS应用，构建OK 生成OK 运行报错

### ISSUE THREAD

**Issue by linruimin** [cocos/cocos-engine#9501]
![image](https://user-images.githubusercontent.com/18083506/137855209-7abfaf45-446a-4a9e-99d3-a7af0e87d5b9.png)
根据网上的解决方案：
![image](https://user-images.githubusercontent.com/18083506/137855583-c03a0bcc-7efc-41ff-a47e-b8212f49a258.png)
和用 sudo xcode-select -r
试过还是一样的报错

备注：
xcode13去掉instruments了：
https://stackoverflow.com/questions/68872891/xcode-13-beta-xcrun-error-failed-to-locate-instruments

**Comment by jareguo** [comment]
2.4.8、3.4 已修复
