### ISSUE TITLE
Update Spine Runtimes compatibility to ver. 4.0.45

### ISSUE THREAD

**Issue by HeroKato-Developer** [cocos/cocos-engine#9557]
Current spine runtimes are outdated regarding latest Spine version.
i've tried fixing Spine's JSON animation file, but the runtime doesn't process correctly Colors and also Beziers.

- Creator version? 2.4.6
- Latest Spine Export Version

- Affected platform? All

- JavaScript output or error produced? Errors in JSON parsing and runtime behaviour not working properly

**Comment by yeshao2069** [comment]
Thank you for your feedback, I will feedback to our dedicated colleagues to upgrade. This issue is closed for now.
