### ISSUE TITLE
[3.3] 动画导入异常

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#9575]
1. 动画播放异常。
2. 动画从3.1.x版本升级到3.3版本显示异常。

**Comment by yeshao2069** [comment]
问题2：动画从3.1.x版本升级到3.3版本显示异常，处理反馈：

工程中的模型资源在非useBakedAnimation模式下显示异常。
3.1.2 进入动画编辑器时，不取消useBakedAnimation 选项。
3.3 进入动画编辑器时，会取消useBakedAnimation 选项， 因此会看到显示异常。
该工程中的模型在导入时勾选了禁用拆分mesh, 勾选此选项时，动画只可以在useBakedAnimation模式下使用
![捕获](https://user-images.githubusercontent.com/14008865/141400906-e8e7f65f-c773-4a34-b689-87d43d397a34.PNG)

**Comment by yeshao2069** [comment]
问题1:   动画播放异常，这个在3.4.0修复了。

**Comment by yeshao2069** [comment]
问题1 & 问题2  问题已经处理，该issue关闭，感谢支持cocos creator.
