### ISSUE TITLE
[Bug] cc.Animation 不支持"空帧"

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#9577]
### Creator version?（版本号）
2.4.6

### Affected platform?（受影响的平台）
all

### How to reproduce?（如何重现）
使用 cc.Animation 制作帧动画 (动态改变 sprite的 spriteFrame) 时, 如果某一帧需要一个空帧 (spriteFrame为空) , 则运行是报错.
查看生成的 clip anim文件, 会有类似的代码: 
```
                           {
                                "frame": 3.1166666,
                                "value": {}
                            },
```

然后在 动画编辑器里看, 这个地方也是显示一个错误图片的缩略图.

我觉得 "空帧" 这个需求是正常的,  clip anim里 ` "value": {}` 或者 `"value": null` 也都可以.
主要还是 编辑器 和 引擎运行时 对 "value": {} 不太对.

### JavaScript output or error produced?（报错信息和调用栈）
```
TypeError: t.textureLoaded is not a function 
 at d._validateRender
 at Function.198.y.validateRenderers
 at Function.198.y.visitRootNode 
```

**Comment by yeshao2069** [comment]
是啥平台，我使用模拟器和web测试，没有这个报错。
![image](https://user-images.githubusercontent.com/14273437/141454609-f67fb77a-fffc-48c6-97fe-ffaf1bccb08e.png)
![image](https://user-images.githubusercontent.com/14273437/141454642-171c23d3-c502-404c-93e6-a5779a7f575c.png)
[testEmptyClip.zip](https://github.com/cocos-creator/engine/files/7526940/testEmptyClip.zip)

**Comment by yeshao2069** [comment]
暂时关闭。

**Comment by finscn** [comment]
macOS 下的 cc  2.4.6
游戏是  微信小游戏

**Comment by finscn** [comment]
@yeshao2069  我看了你的代码, 你的空帧是 : 
```
          {
            "frame": 0.2,
            "value": null
          },
```

但是我不知道为什么 , 我的空帧是 : 
```
          {
            "frame": 0.2,
            "value":{}
          },
```

问题出这里. 你可以试一试 把 你那个anim文件里的  null 换成 {}

.

**Comment by yeshao2069** [comment]
我试试，我这个 animation是在动画编辑器上直接编辑的。

**Comment by yeshao2069** [comment]
如果手动修改 null 为 {}， 是会报错。

![image](https://user-images.githubusercontent.com/14273437/142820682-1bca16ce-ae95-4201-aa63-de476ccb510d.png)

**Comment by yeshao2069** [comment]
测试  3.3.2 版本， 支持空帧  { "frame": 0.2, "value": null},   不支持  { "frame": 0.2, "value": {} }

**Comment by yeshao2069** [comment]
不支持 { "frame": 0.2, "value": {} }    这个内部反馈了、

**Comment by shrinktofit** [comment]
`{}` 表示一个截然不同的对象，只是属性为空而已，它并不是所谓的“空对象”。SpriteFrame 曲线中只应该有 `SpriteFrame` 和 `null`。

**Comment by yeshao2069** [comment]
@finscn    最新反馈 
{} 表示一个截然不同的对象，只是属性为空而已，它并不是所谓的“空对象”。SpriteFrame 曲线中只应该有 SpriteFrame 和 null。
