### ISSUE TITLE
[v2.4.6] JSB 反射接口提示语法错误

### ISSUE THREAD

**Issue by useobjc** [cocos/cocos-engine#9583]
````js
export function callStaticMethod (className: string, methodName: string, methodSignature: string, ...parameters:any): any;
````

iOS平台调用时，不需要指定`methodSignature `, 导致在VSCode里调用时，一直会有语法错误提示:
````text
creator.d.ts(31571, 82): 未提供 "methodSignature" 的自变量。
````

**Comment by useobjc** [comment]
虽然不耽误实际使用，但是看着很尴尬。

**Comment by yeshao2069** [comment]
感谢你的反馈，这个问题已经反馈给引擎组处理。该issue暂时先关闭。

Thank you for your feedback, this issue has been sent back to the engine group to deal with. The issue is closed for now.

**Comment by yeshao2069** [comment]
这个问题，最新的反馈：
在3.4版本上，会有新的接口来适配安卓和IOS，不过原本的接口，不做改动，会对原本的函数调用有破坏性。
