### ISSUE TITLE
[2.4.x] spine 动画启动合批后，组件所在的3d节点旋转会出现异常

### ISSUE THREAD

**Issue by xianyinchen** [cocos/cocos-engine#9600]
下面是带有spine组件的3d节点，同样的旋转角度下，合批的spine动画表现出现异常

``` javascript
const {ccclass, property} = cc._decorator;

@ccclass
export default class Helloworld extends cc.Component {

    @property(cc.Node)
    node0:cc.Node = null

    @property(cc.Node)
    node1:cc.Node = null

    @property(cc.Node)
    node2:cc.Node = null

    start () {
        this.node0.eulerAngles = cc.v3(30, 0, 0)
        this.node1.eulerAngles = cc.v3(30, 0, 0)
        this.node2.eulerAngles = cc.v3(30, 0, 0)

        this.node1.getComponent(sp.Skeleton).enableBatch = true
        this.node2.getComponent(sp.Skeleton).enableBatch = true
    }
}
```

**Comment by yeshao2069** [comment]
link    https://forum.cocos.org/t/topic/120731

**Comment by yeshao2069** [comment]
同步最新反馈：

batch 模式, 模型矩阵在CPU中完成。 计算方式如下，Z坐标未参与计算。
vbuf[ii] = _x * _m00 + _y * _m04 + _m12;
vbuf[ii + 1] = _x * _m01 + _y * _m05 + _m13;
非batch模式shader 中模型矩阵为4x4的矩阵
#if CC_USE_MODEL
mvp = cc_matViewProj * cc_matWorld;
#else
mvp = cc_matViewProj;
#endif
z坐标参与计算，造成差异。
统一改为Z坐标不参与计算的方式很简单，但这样3D模式Z轴坐标就都丢失了。
若要正确修复该问题，需要将spine buffer中的顶点添加Z属性。

**Comment by jareguo** [comment]
很抱歉人力有限，2.x 中 Spine 不考虑支持 3D 节点了。有需要的项目建议用 3.x
