### ISSUE TITLE
[Bug][3.3.1] This render pass descriptor's clear depth (1.000009) is outside of the range [0..1]

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#9610]
### Creator version?（版本号）
3.3.1

### Affected platform?（受影响的平台）

iOS
### How to reproduce?（如何重现）
When preload a scene, after preloaded, run the next scene. Then back to the previous scene, then repeat again and again and again.

NOTED: My scenes are so complicated which contains sprites, animations, spine animations.

### Demo project?（demo 项目）

![Screen Shot 2021-11-03 at 16 55 50](https://user-images.githubusercontent.com/18746281/140040746-a77498c3-4577-4f81-a71d-740ca969fa70.png)
![Screen Shot 2021-11-03 at 16 56 05](https://user-images.githubusercontent.com/18746281/140040769-d3021b5d-7be3-40e5-92d8-65b1f7bc2f8d.png)
![Screen Shot 2021-11-03 at 16 56 14](https://user-images.githubusercontent.com/18746281/140040771-8df77953-4c25-4c68-99fd-324f6ac608b4.png)
![Screen Shot 2021-11-03 at 16 56 22](https://user-images.githubusercontent.com/18746281/140040775-23b77c1f-3b1a-4678-a3a4-196d20c39820.png)
![Screen Shot 2021-11-03 at 16 56 28](https://user-images.githubusercontent.com/18746281/140040777-90dd8a7c-2c52-4766-a63e-abf352695f6b.png)
![Screen Shot 2021-11-03 at 16 56 35](https://user-images.githubusercontent.com/18746281/140040781-716c0319-e23b-45fb-bdf9-f68aaec42bbc.png)
![Screen Shot 2021-11-03 at 16 56 41](https://user-images.githubusercontent.com/18746281/140040782-6db4f6cd-48b2-45d3-9730-3e64911e2c29.png)
![Screen Shot 2021-11-03 at 16 56 46](https://user-images.githubusercontent.com/18746281/140040783-05f1fe49-2484-4d1c-b9bf-0d2742c7341c.png)
![Screen Shot 2021-11-03 at 16 56 54](https://user-images.githubusercontent.com/18746281/140040785-b53f250c-5780-4a3e-a133-b21583aa84cc.png)
![Screen Shot 2021-11-03 at 16 57 00](https://user-images.githubusercontent.com/18746281/140040787-5af13e12-f64d-48e4-8745-058e0a4e1eed.png)

**Comment by yeshao2069** [comment]
感谢反馈，这个问题应该是个bug，我们也接到了其他开发者的反馈，已经建立内部任务，来跟进排查这个问题，我们会尽快修复这个问题的。

Thanks for the feedback, this issue should be a bug, we have also received feedback from other developers and have set up an internal task to follow up and troubleshoot this issue, we will fix this issue as soon as possible.

**Comment by yeshao2069** [comment]
fixed in 3.4.0
https://github.com/cocos-creator/engine-native/pull/4044
