### ISSUE TITLE
[Bug][3.3.1] iOS background music increase play speed when resume game from background

### ISSUE THREAD

**Issue by thinhlv** [cocos/cocos-engine#9623]
### Creator version?（版本号）
3.3.1

### Affected platform?（受影响的平台）

iOS (my iOS ver is 15.0.2)
### How to reproduce?（如何重现）
+ Create cocos creator 3.3.1 empty project.
+ Create an empty scene.
+ Add an AudioSource to the scene, loop = true, play on awake = true.
+ Set any music clip to AudioSource.
+ Save the scene.
+ Build to iOS then play on iPhone
+ Switch between the game and any app many times (fast as fast possible)

+ Expectation: the music must be resumed with the same playback speed.
+ Actual: the music will be increased playback speed when resume from the background. The more you switch apps the more playback speed will be increased.

**Comment by yeshao2069** [comment]
Thank you for your feedback, this issue does exist and is a known issue at this time, we have given feedback internally. The issue is temporarily closed, and I will continue to add to this issue if there is an update on the outcome.

**Comment by zhefengzhang** [comment]
This issue has been fixed on the latest version of 3.x. https://github.com/cocos/engine-native/pull/3381
