### ISSUE TITLE
[3.x] Batch issues

### ISSUE THREAD

**Issue by yuriilychak** [cocos/cocos-engine#9659]
### Creator version?（版本号）
3.3.2

### Affected platform?（受影响的平台）

Web / iOS / Android

### How to reproduce?（如何重现）
Hi. Currently I'm develop project where will be a lot of spine animations and particles. As I see now Spine skeletons and particles have one draw-call for each even if they use same atlas and material.
- Could you fix batching of particles that use same atlas and material.
- Could you fix batching of spine skeletons that use same atlas and material.
- It will be great if we can combine spine skeleton sprites to one atlas for ability to render a lot of skeletons in one draw-call.

**Comment by yeshao2069** [comment]
Question 1: Particles currently do not support combined batches for the time being.
Question 2: spine does not support batching in version 3.x yet, but we are already planning to batch spine animations.

**Comment by yuriilychak** [comment]
@yeshao2069 Are there any plans for ability to specify single atlas for few skeletons?

**Comment by yeshao2069** [comment]
@yuriilychak    https://forum.cocos.org/t/topic/124637     This is the technical solution we share to the Chinese forum first for now, see if it is what you need?

**Comment by yeshao2069** [comment]
@yuriilychak  For the time being, we suggest that you make all the spine animations that need to be combined in one spine file to solve your problem temporarily.
There is no plan to support multiple spines sharing one set of resources, but we will give priority to solving the problem of spine merging.

**Comment by obraz29** [comment]
Hello @yeshao2069 sorry for opening this thread, it's more than 6 months and this issue is still exist, currently on cocos 3.4.2, 3.5.x, the drawcall still increase even when we use same atlas. I mean even we create 2 animations which are same spine on scene, drawcall still increase. It's affecting on our game much, could you please suggest any solution or patch to fix it ?

**Comment by obraz29** [comment]
@yeshao2069 hello,

**Comment by obraz29** [comment]
Hello @yeshao2069 , currently on cocos v342, cocos v350, spines are not batched at all, even we use same atlas, is it a bug ?
