### ISSUE TITLE
使用命令行打包，什么都没有修改，但再次打包，index.js 的文件名都会发生变化，但内容确什么都没有变

### ISSUE THREAD

**Issue by jiangerji** [cocos/cocos-engine#9666]
### Creator version?（版本号）
2.4.6

### Affected platform?（受影响的平台）

Mac

### How to reproduce?（如何重现）
使用命令行打包编译，源码和资源没有任何修改，但是连续两次打包的话，打包最后的 index.js 的名字是不一样的，按理说应该是一样的
![image](https://user-images.githubusercontent.com/3794175/141753952-8862334b-4c75-4895-9bb8-532199f349bf.png)

编译使用的命令行
```
$CocosCreator \
    --path "$projectPath" \
    --buildPath "$buildPath" \
    --build "platform=${platform};debug=false;autoCompile=false;template=link;sourceMaps=false;compressAutoAtlas=false;encryptJs=false;xxteaKey=${xxteaKey};zipCompressJs=false;md5Cache=true"
```

**Comment by jiangerji** [comment]
左边的 index.37a91.js 和  index.4e566.js 内容都是一样的，但文件名不一样

**Comment by yeshao2069** [comment]
https://forum.cocos.org/t/topic/122596/10   
关于config和index的MD5问题
这个问题，之前有收到反馈，会在2.4.7修复。

**Comment by jiangerji** [comment]
那有手动修复的办法么？还是只能等2.4.7更新 @yeshao2069

**Comment by yeshao2069** [comment]
要等2.4.7更新
