### ISSUE TITLE
TiledMap FLIPPED TILES issue 😮

### ISSUE THREAD

**Issue by ClemAnto** [cocos/cocos-engine#9672]
### Creator version?（版本号）
COCOS CREATOR v3.3.2

### Affected platform?（受影响的平台）
Windows Editor / Web

### How to reproduce?（如何重现）
Import and put on canvas a TiledMap with some FLIPPED TILE.

### JavaScript output or error produced?（报错信息和调用栈）
Imported TiledMap doesn't display correctly FLIPPED TILE
![image](https://user-images.githubusercontent.com/472231/142000692-a31d278b-fe4d-4cd0-b1c1-57ec6525b446.png)

...Instead it should be (Tiled view)....
![image](https://user-images.githubusercontent.com/472231/142000861-7d257a14-fb17-4d72-9e98-46774e977170.png)

### Demo project?（demo 项目）
https://drive.google.com/drive/folders/1HB4EFSinxxMdyZib2-5ht9n_aVhujjp_?usp=sharing

### Thanks for the feedback.（感谢反馈）
Thanks!

**Comment by yeshao2069** [comment]
Thanks for the feedback.
- I looked at your tiledmap resource, which was made using version 1.7.2, but the current supported runtime version of the engine tiledmap is 1.4.0, and the problem occurs. Also the feature FLIPPED TILE is supported in tiledmap 1.5.0, so it shows an exception.

https://github.com/cocos-creator/engine/blob/v3.3.2/cocos/tiledmap/tmx-xml-parser.ts#L188
https://www.mapeditor.org/2021/03/23/tiled-1-5-0-released.html
![image](https://user-images.githubusercontent.com/14273437/142606686-f4fd3dbb-cc1c-471a-af59-8d95efe8f1c2.png)


- Also, the runtime version support of tiledmap needs to be upgraded, I will give feedback to the engine team for this.
