### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by ghost** [cocos/cocos-engine#974]
Hi guys,

Hope you are all well !

I was looking at your amazing work and I was wondering if a dockerfile was available with Alpine as a base image. It would be great for testing or launching latest version faster.

Thanks in advance.

Cheers,
Luc

**Comment by jareguo** [comment]
Sorry not officially support Linux/Docker. Here is a possible resolution: http://discuss.cocos2d-x.org/t/successfully-run-cocos-creator-on-linux-and-released-it-as-docker-image/40755
