### ISSUE TITLE
Create packages for C++/JS bindings

### ISSUE THREAD

**Issue by ghost** [cocos/cocos-engine#975]
Hi guys,

Hope you are all well !

I have a last question about about cocos-creator as I am quite new to your great tool; Is it possible to create a package of assets with a universal configuration file (like a plist) in order to execute a game created with your UI but launchable not only with the JS API but the C++ one also.

More precisely, I was thinking to use Vuforia/Artoolkit with cocos2d-x in order to create augmented reality interactions and to load different mini games per markers/images recognized and tracked.

I was wondering if cocos-creator could be a UI to build those interactions with ease.

Cheers,
Luc Michalski

**Comment by xianyinchen** [comment]
We apologise for the long response and yes, this idea can be implemented, by customising the engine code. If you have an updated question to ask, please create a new issue.
