### ISSUE TITLE
 Failed to resolve symbol Quat, There is no symbol info. node_modules/tfig/build/recast.js:848

### ISSUE THREAD

**Issue by Codes-Breaker** [cocos/cocos-engine#9775]
### Affected platform?（受影响的平台）

Windows

### How to reproduce?（如何重现）
Start Debugging

**Comment by yeshao2069** [comment]
Hi, may I ask on which version you are having this problem. How do I need to go about reproducing this issue?

**Comment by yeshao2069** [comment]
Temporarily unable to reproduce and no response for a long time, the issue is temporarily closed.
