### ISSUE TITLE
[2.4.6] cc.ParticleSystem不受Node透明度影響

### ISSUE THREAD

**Issue by yoki0805** [cocos/cocos-engine#9779]
### Creator version?（版本号）
2.4.6

### Affected platform?（受影响的平台）

Web

### How to reproduce?（如何重现）
空場景中放置一個預設的粒子系統, 調整節點屬性即可重現

--

2.4.3版的粒子系統可以受節點透明度影響
2.4.6則否

此外若調整節點scale屬性
只有當粒子的PositionType為Grouped才能生效

**Comment by yeshao2069** [comment]
你好，测试了一下 2.4.6版本，修改 节点的 color的透明度，表现和 2.4.3版本一致。具体的不受影响是什么表现。

调整节点 的 scale属性，需要当粒子的PositionType為Grouped才能生效。
https://docs.cocos.com/creator/api/zh/enums/ParticleSystem.PositionType.html

**Comment by yoki0805** [comment]
sorry, 我誤會了
我重新測試2.3.3 / 2.4.3 / 2.4.6, 發現這三個版本的節點透明度確實不影響粒子的透明度

想請問實務上常常會有動畫淡出的需求
如果粒子系統不受節點的透明度影響, 該如何實現粒子系統整體淡出的效果?

**Comment by yeshao2069** [comment]
2D粒子目前不支持 淡出/淡入 效果。

**Comment by yoki0805** [comment]
瞭解了, 謝謝解答
