### ISSUE TITLE
if cls.get_cocos2d_mode() is not "distro": 

### ISSUE THREAD

**Issue by qx** [cocos/cocos-engine#9813]
### Creator version?（版本号）

2.4.7
### Affected platform?（受影响的平台）

mac m1,构建android项目

### How to reproduce?（如何重现）
<img width="1643" alt="截屏2021-12-15 10 40 58" src="https://user-images.githubusercontent.com/648406/146113155-775a0a26-f1e9-44b9-a091-f8649276d3ae.png">

**Comment by yeshao2069** [comment]
你好，Mac m1 构建空工程，可以复现吗？

Hi, Mac m1 build empty project, can I reproduce it?

**Comment by yeshao2069** [comment]
暂时无法复现，且长时间没有回复，该issue暂时关闭。

Temporarily unable to reproduce and no response for a long time, the issue is temporarily closed.
