### ISSUE TITLE
oppo小游戏 无法保存截图

### ISSUE THREAD

**Issue by finscn** [cocos/cocos-engine#9833]
### Creator version?（版本号）
2.4.7

### Affected platform?（受影响的平台）

oppo 小游戏

### How to reproduce?（如何重现）

我把一张图片 画到 canvas上. 然后用 toTempFilePath 的api生成文件 存储到相册后, 文件生成了, 文件尺寸也对, 但是 canvas上的内容不对 .
这个过程没有报错. 

我不用图片, 而是 用 clearRect  fillRect fillText 对canvas进行绘制, 导出的内容还是不对.
导出的图片上的内容总是屏幕左上角的一个区域.  如果我的这个canvas是 200x100, 那么导出的图片上的内容就是 屏幕左上角200x100的内容.

即使我什么都不做 ,只是 clearRect , 导出的也不是空白图片, 还是屏幕左上角区域的内容

**Comment by finscn** [comment]
测试代码: 
```ts
    testOppo() {
        const canvas: any = document.createElement('canvas')
        canvas.width = 200
        canvas.height = 100
        const ctx = canvas.getContext('2d')
        ctx.clearRect(0, 0, canvas.width, canvas.height)
        ctx.fillStyle = "#ffffff"
        ctx.fillRect(10, 10, 55, 22)

        if (canvas.toTempFilePath) {
            canvas.toTempFilePath({
                success: res => {
                    const imagePath = res.tempFilePath
                    console.log('保存 图片成功 ：', imagePath)
                },
                fail: res => {
                    console.error('保存 图片失败 ：', res.errCode, res.errMsg)
                },
            })
        }
    }
```

**Comment by yeshao2069** [comment]
web上，正常吗？

**Comment by yeshao2069** [comment]
同步

直接调用 OPPO小游戏平台的 toTempFilePath API 编写测试例，在当前OPPO最新版本调试器 V4.9.1 中, 可复现该问题。
https://activity-cdo.heytapimage.com/cdo-activity/static/201810/26/quickgame/documentation/#/games/use
将与 oppo 反馈该问题。
临时处理方案，可通过接口中的 destWidth 与 destHeight 属性来控制生成图片的大小

**Comment by yeshao2069** [comment]
OPPO 侧修复该问题的版本已全量发布，可进行验证
