### ISSUE TITLE
engine 定制如何正确创建新模块

### ISSUE THREAD

**Issue by qingwabote** [cocos/cocos-engine#9840]
我试图参照文档来创建新模块，但是跑起来并没有在cc空间下找到我添加的内容，我是这么操作的：

在 exports 目录下放置新模块（我的理解是放置用于导出新API的ts文件），然后把模块加在 cc.config.json 的 features 字段里；
npm run build；
开发者->编译引擎；

如果我利用 exports 目录下已存在的官方的文件进行新API的导出是OK的，我想知道我缺少了哪些步骤，谢谢。

参考：https://github.com/cocos-creator/engine/blob/develop/docs/contribution/modules.md#create-public-module

engine v3.3.2

**Comment by qingwabote** [comment]
在 engine-features/render-config.json 添加上新模块的配置解决了这个问题，但是需要手动更改包括 render-config.json 在内的，schema.json 和 types.ts 三个文件，我不确定这些文件是应该手动修改还是使用某种工具自动生成的。

**Comment by yeshao2069** [comment]
使用上的问题，建议到论坛上问一下 https://forum.cocos.org/
