### ISSUE TITLE
CocosCreator3.4 创建材质报错

### ISSUE THREAD

**Issue by eos3tion** [cocos/cocos-engine#9852]
### Creator version? 
CocosCreator3.4

### Affected platform?（受影响的平台）
Windows Editor

### How to reproduce?（如何重现）
[effects.zip](https://github.com/cocos-creator/engine/files/7755203/effects.zip)
创建一个材质，使用 zip包中 `effect3.effect`，然后就会报下面错误
CocosCreator3.3 正常

### JavaScript output or error produced?（报错信息和调用栈）
[Scene] The asset 16400885632650.8175421489308723 is invalid for some reason, detail message: Cannot read property 'minFilter' of undefined, stack: TypeError: Cannot read property 'minFilter' of undefined    at Function.computeHash (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:257045:21)    at WebGL2Device.getSampler (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:230162:35)    at Pass.resetTexture (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:235465:34)    at Pass.resetTextures (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:235513:14)    at Pass.initialize (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:235136:10)    at Proxy._createPasses (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:95067:12)    at Proxy._update (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:95076:27)    at Proxy.onLoaded (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:94875:10)    at Task.onComplete (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:90361:19)    at Task.dispatch (D:\workspace\CocosDashboard\resources\.editors\Creator\3.4.0\resources\resources\3d\engine\bin\.cache\dev\editor\bundled\index.js:92577:16)

**Comment by yeshao2069** [comment]
你好，shader中  texture纹理是没有 green 这个内置的纹理，你改为  white 应该就可以了
![image](https://user-images.githubusercontent.com/14273437/147333955-98cb1e3c-f5d8-49c4-9784-edb29326b741.png)
