### ISSUE TITLE
plist 图集，如果精灵数量很多，在开发测试时加载SpriteAtlas超过3s,体验很差。

### ISSUE THREAD

**Issue by shenxiyou** [cocos/cocos-engine#9861]
### Creator version?（版本号）
3.4

### Affected platform?（受影响的平台）

Mac Editor / Windows Editor
### How to reproduce?（如何重现）
工程里放入一个超过300个精灵的plist 图集
调用
 console.time("load");
 resources.load("xxx", SpriteAtlas, (err, hero) => {
      console.timeEnd("load");// 时间会超过3秒。。
  });
原因是每个精灵都生成了一个json的描述文件，加载时io过高。。
建议同一个plist 的描述文件合并。

**Comment by yeshao2069** [comment]
超过300个精灵的图集，你们的图集 多大？

可否提供资源测试？

**Comment by shenxiyou** [comment]
> 

生成的plist图片只有2048x2048，里面精灵小图很多，每个精灵都是一个json，加载时会同时加载所有精灵的json，就会卡。。目前我不用plist了，自己在texturepacker导出json格式的自己解释，瞬间就加载好了

**Comment by zhefengzhang** [comment]
你好，assetbundle 支持合并 json 的功能，你是否可以试试？此功能仅对构建后的项目有效
![图片](https://user-images.githubusercontent.com/35944775/147800399-8815a533-cd44-4cd6-b0c1-49e52944b68c.png)

![图片](https://user-images.githubusercontent.com/35944775/147800345-880106ff-9b88-4a94-94e6-1c239a318c79.png)

**Comment by zhefengzhang** [comment]
> > 
> 
> 生成的plist图片只有2048x2048，里面精灵小图很多，每个精灵都是一个json，加载时会同时加载所有精灵的json，就会卡。。目前我不用plist了，自己在texturepacker导出json格式的自己解释，瞬间就加载好了

图集资源的加载也会下载图片资源的，如果图片资源较大的话，也会算进加载时间。我这边测试 300+ 散图的 plist 也才 100+ k，序列化和加载的时长应该是很短的。你这边手动做序列化肯定也是快的，因为没有了图片下载的时间。

**Comment by zhefengzhang** [comment]
用户较长时间没有回复，暂时关闭此 issues 。
