### ISSUE TITLE
Can't read the value of "linearVelocity" of a RigidBody2D inside lateUpdate function

### ISSUE THREAD

**Issue by mrtzd** [cocos/cocos-engine#9865]
### Creator version?（版本号）
3.4 and 3.3

### Affected platform?（受影响的平台）

Windows

### How to reproduce?（如何重现）
Whenever I try to read the value of "linearVelocity" from a "RigidBody2D" inside of the "lateUpdate()" function I get an error. 

```
private rigidBody: RigidBody2D;
start() {
        this.rigidBody = this.getComponent(RigidBody2D);
    }
lateUpdate(deltaTime: number) {
    console.log("Velocity: " + this.rigidBody.linearVelocity);
    }
```

**Possible Solution**
To work around this issue I added a new function to RigidBody2D class (which is inside "cocos\physics-2d\framework\components\rigid-body-2d.ts" file). 
```
     getVelocity<Out extends IVec2Like> (out: Out): Out {
        if (this._body) {
            return this._body.getLinearVelocity(out);
        }
        return out;
    }
```
Using the above method I don't encounter any errors but if the issue with the "linearVelocity" property can be fixed it would be a lot better since I don't have to use a custom engine anymore.

### JavaScript output or error produced?（报错信息和调用栈）

```
TypeError: Cannot assign to read only property 'x' of object '[object Object]'
    at b2RigidBody2D.getLinearVelocity (index.js:176485)
    at RigidBody2D.get (index.js:256550)
    at Arrow.lateUpdate (:7456/scripting/x/mods/fs/0/assets/scripts/Arrow.js:188)
    at index.js:148000
    at ReusableInvoker._invoke (index.js:147778)
    at ReusableInvoker.invoke (index.js:147963)
    at ComponentScheduler.lateUpdatePhase (index.js:148207)
    at Director.tick (index.js:6437)
    at callback (index.js:5053)
```

**Comment by yeshao2069** [comment]
I did a simple test on my side and was not able to reproduce this error. Can you provide a demo for testing?
[NewProject_1.zip](https://github.com/cocos-creator/engine/files/7773090/NewProject_1.zip)

**Comment by mrtzd** [comment]
I think I found where the error was coming from. I was resetting the value of linearVelocity in the wrong way. This was my code:
`arrowRigidBody.linearVelocity = Vec2.ZERO;`

Now that I changed it like below this problem is resolved.
`arrowRigidBody.linearVelocity = Vec2.ZERO.clone();`

Thanks for the response. I'll close the issue now.
