### ISSUE TITLE
Loading remote file on Android

### ISSUE THREAD

**Issue by lifzgreat** [cocos/cocos-engine#987]
This works in a browser but not in Android:
`cc.loader.load({id: 'http://mydomain.com/config.php', type: 'json'}, function (err, data) {});`

The browser downloads the file but Android throws this error:
`Get data from file(http://mydomain.com/config.php) failed!`

I've traced the error message to here:
https://github.com/cocos-creator/cocos2d-x-lite/blob/develop/cocos/platform/android/CCFileUtils-android.cpp#L239-L244

**Comment by flovel** [comment]
@jareguo 2.0.10 在cc.loader.load下载远程资源出现404后，android 没有抛出 err

**Comment by lifzgreat** [comment]
My comment was from nearly 3.5 years ago.

**Comment by SantyWang** [comment]
> @jareguo 2.0.10 在cc.loader.load下载远程资源出现404后，android 没有抛出 err

Thanks for your feedback, could you please give us more information. platform?

**Comment by SantyWang** [comment]
> My comment was from nearly 3.5 years ago.

Sorry for so late reply. you still use Cocos Creator?

**Comment by lifzgreat** [comment]
> Sorry for so late reply. you still use Cocos Creator?

No, I don't, sorry!

**Comment by SantyWang** [comment]
Please don't be sorry about anything, it's our problem.  We are soooorry for these unstable behaviors.

**Comment by flovel** [comment]
使用JS引擎是github下载的tag v2.0.11

**Comment by flovel** [comment]
使用JS引擎是github下载的tag v2.0.11 android测试机是华为，后面我用自带的模拟器也出现同样的问题
连续请求多个不同的远程（大概6-7个）资源出现404后，cc.loader.load 的 completeCallback 没有错误抛出，估计导致下载资源线程卡住，后面在请求不到了。网页的错误有返回，在请求就没有问题

**Comment by SantyWang** [comment]
原生的话，远程资源请先用jsb.Downloader下载下来再使用吧，可以看下范例里面的network范例

**Comment by zhefengzhang** [comment]
There is no such problem in 2.4.x and 3.0.0 versions.

**Comment by lifzgreat** [comment]
Thanks zhefengzhang, I'm sure you're right. I can't test it because I don't use Cocos anymore (I opened this over 4.5 yrs ago).
