### ISSUE TITLE
Game crash when destroy and reload spine many times

### ISSUE THREAD

**Issue by obraz29** [cocos/cocos-engine#9871]
### Creator version?（版本号）
Cocos 3.3.1, 3.3.2, 3.4

### Affected platform?（受影响的平台）
Android, iOS
### How to reproduce?（如何重现）
Release spine & reload (10 or 20 times), the game random crash

### JavaScript output or error produced?（报错信息和调用栈）
![2021-12-24 16 31 48](https://user-images.githubusercontent.com/52654061/147340410-3d305872-9155-4771-af68-38b869ec9043.jpg)

### Demo project?（demo 项目）
Project is too big so i cant attach it here, in spine we have using Path feature.

**Comment by yeshao2069** [comment]
Can you provide the code you loaded and released, or test cases?

**Comment by obraz29** [comment]
Hi yeshao2069,
I'm loading assets via bundle like this:
bundle.loadDir('', Prefab, (finish, total, item)=>{
//update loading bar
}, (error, prefabs)=>{
...
//addRef
prefabs.forEach(prefab => {
prefab.addRef();
})
})

when release assets:
- I'm calling decRef() all prefabs, then bundle.releaseUnusedAssets().

I tried to make a delay between loading & releasing process but it doesnt help. sometimes the game crashs without calling release assets

**Comment by obraz29** [comment]
I will try to make a small demo, but not very sure it occurs on small project.
More info: game doesnt crash if the spine doesn't have Path & IK, the spine version is 3.7.94

**Comment by obraz29** [comment]
I'm adding the stack, hope it helps:
![stack](https://user-images.githubusercontent.com/52654061/147353707-84ac908d-60d9-4234-b3e1-93b8022e5928.jpg)

**Comment by yeshao2069** [comment]
Thank, i ' ll have a test.

**Comment by yeshao2069** [comment]
Hi, I used your code snippet and really couldn't reproduce the issue, I tested it with Android version 3.4.0. Can you help me to see if there is any problem with this reproduced project?
[NewProject_4-release.apk.zip](https://github.com/cocos-creator/engine/files/7795443/NewProject_4-release.apk.zip)
[NewProject_4.zip](https://github.com/cocos-creator/engine/files/7795450/NewProject_4.zip)

**Comment by dylan465** [comment]
I had same issue on iOS when decRef prefab. HELP!!!

**Comment by obraz29** [comment]
> Hi, I used your code snippet and really couldn't reproduce the issue, I tested it with Android version 3.4.0. Can you help me to see if there is any problem with this reproduced project? [NewProject_4-release.apk.zip](https://github.com/cocos-creator/engine/files/7795443/NewProject_4-release.apk.zip) [NewProject_4.zip](https://github.com/cocos-creator/engine/files/7795450/NewProject_4.zip)

Hi, i couldn't reproduce using your demo, we decide to update to v3.4.1 and the bug appear on Android platform with same steps
![android](https://user-images.githubusercontent.com/52654061/155709172-563e8dd8-e3d0-4b9c-9827-51a51e8f35ef.jpg)
.

**Comment by obraz29** [comment]
Hello @yeshao2069 @zhakesi  , i'm sending you a small demo. Hope it helps you find the issue. The bug occurs on cocos v3.4.0, v3.4.1 (android platform), due to NDA, i removed image of spines.
Step:
- Run apk and press Test button (auto load & release spine continuously)
- The app is crashed after serveral load & release spines (sometimes it takes longer, in our project the game crashed after 3-5 times
[TestSpine-release.apk.zip](https://github.com/cocos-creator/engine/files/8159805/TestSpine-release.apk.zip)
[TestSpine.zip](https://github.com/cocos-creator/engine/files/8159919/TestSpine.zip)
)

**Comment by obraz29** [comment]
Hi @yeshao2069 could you have a look ? Thank you so much

**Comment by obraz29** [comment]
We merged this pull and the issue is resolved,
https://github.com/cocos/cocos-engine/pull/10314
