### ISSUE TITLE
Render texture read pixels bug.

### ISSUE THREAD

**Issue by PranavSK** [cocos/cocos-engine#9893]
https://github.com/cocos-creator/engine/blob/5d3b5d64c8cefae9f686bbb75020c09e1924aa2a/cocos/core/assets/render-texture.ts#L184

The height variable referenced in the above script needs to set height and not width.

**Comment by ccbbsccbbs** [comment]
i have wasted a long time to find this bug.

**Comment by zhefengzhang** [comment]
Thanks for the feedback, it has been fixed in version 3.4.1.
