### ISSUE TITLE
Web Preview Can't Launch Unless Editor is Running in Administrator Mode

### ISSUE THREAD

**Issue by Xisrith** [cocos/cocos-engine#9908]
### Creator version?（版本号）
3.4.0

### Affected platform?（受影响的平台）
Windows Editor

### How to reproduce?（如何重现）

* Launch Cocos Dashboard regularly
* Open (or create) any project
* Launch the web preview

The game window will not show up in the web preview.

### JavaScript output or error produced?（报错信息和调用栈）
`ui.js: e.Size() is not a constructor`

### Demo project?（demo 项目）
In my experience, it occurred with any project I opened, including the starter templates provided in Cocos Dashboard.

**Comment by yeshao2069** [comment]
Hi, can you help to confirm if the scene is not selected. I tested it on windows and mac, the preview on the web is fine, you can provide information about your device to troubleshoot the problem. Better yet, can you record a video and let's analyze it?

**Comment by zhefengzhang** [comment]
We are sorry, but we are unable to reproduce this issue. This issue usually occurs on a small number of computers.
Since you have not updated your response for a long time, we have temporarily closed this issue and will reopen it when you provide us with more information.
