### ISSUE TITLE
3.4.0 readPixels不能使用height参数

### ISSUE THREAD

**Issue by nyaris-005** [cocos/cocos-engine#9912]
https://github.com/cocos-creator/engine/blob/51ac077cc8b2bd15433ee827089495a621ed5c59/cocos/core/assets/render-texture.ts#L184

将宽度参数赋值给了height，导致height和this.height都没有作用

**Comment by yeshao2069** [comment]
这个bug   已知，会在3.4.1版本修复，感谢反馈。

**Comment by yeshao2069** [comment]
https://github.com/cocos-creator/engine/pull/9900/files   修复的PR
