### ISSUE TITLE
After OrthoHeight is changed, all UI events fire all misaligned.

### ISSUE THREAD

**Issue by cuixin** [cocos/cocos-engine#9966]
版本： cocos engine 3.4

环境： Windows 11

重现步骤：

1. 新建一个工程。
2. 在Hierarchy里面新建一个Button。
3. 关闭Canvas的AlignCanvasWithScreen。
4. 修改Canvas下的Camera的OrthoHeight为原来值的两倍。
5. 修改屏幕Button的位置向整个屏幕的左下或者任意方向偏移，尽量远离中心点。
6. Run。按钮点击将失效，从中心点方式偏移了。

cocos论坛好像早就报这个问题了，官方计划什么时候修复？

**Comment by PPpro** [comment]
这个问题应该 3.5 上处理了，可以验证下哈，相关 PR
https://github.com/cocos/cocos-engine/pull/10496
