### ISSUE TITLE
box2d physics rotation inconsistent with actual node rotation

### ISSUE THREAD

**Issue by LiuPai** [cocos/cocos-engine#9999]
### Creator version?（版本号）
v3.1.2 - v3.4.1

### How to reproduce?（如何重现）
EN: RigidBody2D node with __negitive or greater than 360°__ z-axis rotation
中: 任意 RigidBodx2D 节点设置 __负数或大于360°__ z轴旋转

相关Issue #8930

提交 146385bdfb133dd0f10a5dd409e1aa76125e16b2 中 `this._rotationAxis.z` 可能为-1,导致设置角度错误.
简易补丁
``` typescript
        tempVec3.z = Quat.getAxisAngle(this._rotationAxis, node.worldRotation);
        if (this._rotationAxis.z < -0.5) {
            tempVec3.z = Math.PI*2-tempVec3.z;
        }
        bodyDef.angle = tempVec3.z;
```

**Comment by zxx43** [comment]
tempVec3.z = Quat.getAxisAngle(this._rotationAxis, node.worldRotation);
        if (this._rotationAxis.z < 0.0) {
            tempVec3.z = Math.PI*2-tempVec3.z;
        }
        bodyDef.angle = tempVec3.z;

最好是这么改，只要旋转轴为负，旋转方向就反一下

**Comment by SantyWang** [comment]
将在 3.5 修复
